begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(4,'fr','Elle suit un cours en ligne.','Elle a une réunion en ligne.','cours en ligne à la maison','un cours de cuisine à l''école','business','none'),
(34,'fr','Le badminton : une super activité.','Le tennis : une super activité.','une activité dehors l''après-midi','activité pour jours de pluie','business','none'),
(45,'fr','Elle est en colère contre l''homme !','Elle est en colère contre le chien !','une femme en colère','en colère contre la pluie','dramatic','exclamation'),
(54,'fr','Du liquide retiré au distributeur de billets pour des tournesols !','Du liquide retiré au distributeur de billets pour une pizza !','retirer au distributeur de billets','un distributeur qui avale sa carte','gossip','exclamation'),
(65,'fr','Des légumes sur une plaque de cuisson.','Des cookies sur une plaque de cuisson.','légumes sur plaque de cuisson','cookies sur plaque de cuisson','slang','none'),
(75,'fr','Mec, les chauves-souris battent des ailes.','Mec, les oiseaux battent des ailes.','battre de grandes ailes','battre des ailes au sol','slang','none'),
(78,'fr','La mer a emporté leur château sur la plage.','Un chien a emporté leur château sur la plage.','un château sur la plage','une plage pleine de galets','chill','blaming_someone'),
(89,'fr','Le chat noir saute.','Le chat tigré saute.','chat perché sur l''arbre à chat','chat caché sous l''arbre à chat','chill','none'),
(91,'fr','Maman accuse le garçon. C''est le chat qui a fait le coup.','Maman accuse le garçon. C''est le chien qui a fait le coup.','accuser le chat','accuser la météo','gossip','blaming_someone'),
(97,'fr','L''eau bout.','Le lait bout.','de l''eau qui bout','du lait qui bout','chill','none'),
(139,'fr','Il a trouvé la capitale !','Il a trouvé l''océan !','la capitale en contrebas','une lettre capitale','dramatic','exclamation'),
(145,'fr','Ils sont vraiment doués pour attraper au vol.','Ils sont vraiment doués pour tirer.','attraper une balle orange','attraper froid','flirt','none'),
(153,'fr','Le bouchon de champagne s''envole !','La coupe de champagne s''envole !','servir du champagne','arroser le podium de champagne','dramatic','exclamation'),
(169,'fr','L''argile est devenue un bol.','L''argile est devenue un vase.','une motte d''argile humide','un court en terre battue','chill','none'),
(174,'fr','Ils sont à l''accueil d''une clinique.','Ils sont à l''accueil d''un hôtel.','une visite à la clinique','une visite au gymnase','business','none'),
(184,'fr','Elle ordonne, ils courent.','Elle ordonne, ils dorment.','ordonner aux recrues de courir','commander un navire','business','none'),
(195,'fr','Le thé au miel calme la toux.','La bière fraîche calme la toux.','tousser dans un fauteuil','tousser pendant un concert','chill','guessing'),
(199,'fr','Il fonce dans tout le monde !','Il fonce dans un mur !','se rentrer dedans en autos-tamponneuses','percuter une vraie voiture','dramatic','exaggeration'),
(209,'fr','Chat curieux, zéro intimité.','Chien curieux, zéro intimité.','un chat curieux qui mate','un chien curieux qui mate','slang','exaggeration'),
(230,'fr','Le réalisateur veut ralentir.','Le réalisateur veut accélérer.','réalisateur qui crie « coupez »','un directeur de banque','business','none'),
(237,'fr','L''âne se roule dans la poussière comme au spa.','L''âne se roule dans la boue comme au spa.','un âne dans la poussière','un âne qui porte un sac','slang','exaggeration'),
(240,'fr','Mamie dit que c''est match nul.','Le chien dit que c''est match nul.','match nul au bras de fer','match nul au foot','gossip','guessing'),
(260,'fr','Il fait frire un œuf.','Il fait bouillir un œuf.','œuf au plat sur toast','un œuf dur','chill','none'),
(270,'fr','Sa gomme est devenue une montagne !','Sa gomme est devenue une fleur !','une gomme-montagne miniature','une petite maison de montagne','dramatic','exclamation'),
(273,'fr','Tchin à cette belle soirée !','Tchin à cette belle matinée !','un soir calme en hauteur','une soirée au cinéma','slang','exclamation'),
(279,'fr','Il déploie toute sa force. Enfin, un peu.','Il prend du bon temps. Enfin, un peu.','déployer toute sa force','exercer son pouvoir','ironic','understatement'),
(281,'fr','Son trait de crayon pour les yeux est parfait. Validé !','Son trait de crayon pour les yeux est raté. Validé !','un eye-liner graphique','de l''eye-liner sur les lèvres','slang','exclamation'),
(282,'fr','Son fard à paupières est en or pur.','Son fard à paupières est en argent pur.','du fard à paupières doré irisé','fard bleu sur un pinceau','flirt','exaggeration'),
(288,'fr','Même le chien adore la mode.','Même le chat adore la mode.','la mode des rues parisiennes','une couverture de magazine de mode','gossip','exaggeration'),
(289,'fr','Elle est paralysée par la peur.','Elle est paralysée par le froid.','peur sur un sol vitré','la peur du noir','dramatic','none'),
(290,'fr','Quelle émotion ! But !','Quelle émotion ! Carton rouge !','un sentiment de joie','un sentiment d''ennui','dramatic','exclamation'),
(293,'fr','La réalisation de films sur un toit, ça a l''air fun.','La réalisation de films sur une plage, ça a l''air fun.','un tournage sur un toit','un tournage en studio','chill','none'),
(295,'fr','Une main mélange avec un couteau.','Une main mélange avec une cuillère.','mélanger une pâte dans un seau','mélanger une pâte à gâteau','chill','none'),
(302,'fr','Il est couvert de farine !','Il est couvert de boue !','farine comme de la neige','de la farine sur un gâteau','dramatic','exaggeration'),
(309,'fr','Football sur la plage au coucher du soleil.','Volley sur la plage au coucher du soleil.','football pieds nus sur sable','le football à la télé','chill','none'),
(323,'fr','Le match se passe bien pour son équipe.','Le match se passe mal pour son équipe.','match de basket au crépuscule','une partie de cartes','business','understatement'),
(333,'fr','Cette fille sait tout faire !','Ce garçon sait tout faire !','fille qui saute à la corde','une fille qui sèche les cours','dramatic','exaggeration'),
(336,'fr','Lunettes sur le nez, et encore plus de canards !','Lunettes sur le nez, et encore plus d''oies !','nettoyer des lunettes rondes','casser des lunettes rondes','low_iq','exclamation'),
(347,'fr','Un petit ragot, ils adorent.','Un petit match de foot, ils adorent.','chuchoter des ragots croustillants','des ragots dans un magazine','gossip','understatement'),
(358,'fr','Travail soigné avec ce marteau.','Travail soigné avec cette cuillère.','un marteau sur un clou','un marteau dans une caisse','flirt','none'),
(378,'fr','Le lever du soleil est hyper doré.','Le lever du soleil est hyper gris.','voler vers le lever du soleil','se lever avant l''aube','slang','none'),
(379,'fr','Elle filme son vlog.','Elle filme un mariage.','filmer un vlog du matin','monter un vlog de voyage','chill','none'),
(389,'fr','Le miel est trop lent !','Le miel est trop rapide !','miel sur une cuillère en bois','du miel dans le thé','slang','exclamation'),
(401,'fr','Joli freinage sur ces patins à glace.','Joli freinage sur ce snowboard.','lacer des patins à glace','des patins sur une étagère','flirt','none'),
(410,'fr','Elle étale une épaisse couche de confiture.','Elle étale une fine couche de confiture.','confiture sur du pain grillé','confiture sur une crêpe','chill','none'),
(415,'fr','Ce kangourou a un passager.','Ce koala a un passager.','un kangourou avec son petit','un kangourou boxeur','chill','exaggeration'),
(422,'fr','Ses coups de pied sont hyper hauts.','Ses coups de pied sont hyper bas.','coups de pied au sac','coups de pied au ballon','slang','none'),
(442,'fr','Le travail d''équipe vient à bout d''une lourde caisse.','Le travail d''équipe vient à bout d''un lourd canapé.','travail d''équipe avec une lourde caisse','travail d''équipe au foot','business','cliche'),
(471,'fr','Le chien veut la viande.','Le chat veut la viande.','viande grillée sur une planche','de la viande crue en boucherie','low_iq','guessing'),
(506,'fr','Leur assiette, c''est 100 % nutrition.','Leur assiette, c''est 100 % sucre.','une nutrition équilibrée dans l''assiette','infos nutrition sur une boîte','nerd','exaggeration'),
(563,'fr','Les clés étaient dans sa poche !','Les clés étaient dans sa chaussure !','des clés dans une poche','des clés dans une portière','low_iq','exclamation'),
(565,'fr','À ce jeu de politique, c''est l''orange qui a gagné.','À ce jeu de politique, c''est le vert qui a gagné.','la politique sur la place','la politique à la télé','gossip','none'),
(574,'fr','Quel nuage de poudre !','Quel nuage de fumée !','appliquer de la poudre','pâtisser avec de la farine','dramatic','exclamation'),
(590,'fr','Elle frappe du poing comme une pro !','Elle frappe du pied comme une pro !','frapper les pattes d''ours','frapper du poing le mur','slang','exaggeration'),
(606,'fr','La recette dit : les œufs d''abord.','La recette dit : le poisson d''abord.','une fiche recette dessinée','une recette de soupe','business','none'),
(612,'fr','Elle montre la droite.','Elle montre le ciel.','passer à droite des stands','tourner à droite au feu','chill','none'),
(619,'fr','Elle descend un panier avec une corde.','Elle descend un seau avec une corde.','descendre un panier à la corde','baisser le volume','chill','none'),
(626,'fr','Le coureur boit de l''eau.','Le coureur mange une banane.','un coureur qui boit de l''eau','un coureur sur tapis','chill','none'),
(632,'fr','Ils mettent du sel sur les tomates.','Ils mettent du sel sur les pommes de terre.','du sel sur des tomates','du sel sur une route enneigée','chill','none'),
(636,'fr','Même le canard veut ce sandwich.','Même le chien veut ce sandwich.','un sandwich jambon-fromage','un sandwich dans une gamelle','chill','guessing'),
(637,'fr','Une grenade : des centaines de graines.','Une pastèque : des centaines de graines.','ouvrir une grenade','du jus de grenade','nerd','exaggeration'),
(652,'fr','Beurk ! La mer est salée !','Beurk ! Le lac est salé !','sauter dans la mer','une marée humaine','dramatic','exclamation'),
(660,'fr','Qui a besoin d''un salon ? Une bassine suffit.','Qui a besoin d''un salon ? Un seau suffit.','shampoing dans une bassine','faire la vaisselle dans une bassine','ironic','cheap_quality'),
(663,'fr','Mousse à raser : barbe instantanée !','Mousse à raser : chapeau instantané !','une spirale de mousse à raser','mousse à raser sur gâteau','low_iq','exaggeration'),
(669,'fr','Avec trois pièces, on repart de ce magasin les bras pleins.','Avec dix pièces, on repart de ce magasin les bras pleins.','un petit magasin d''alimentation','un petit magasin de fleurs','gossip','cheap_quality'),
(671,'fr','À force de crier, gorges en feu.','À force de chanter, gorges en feu.','crier à travers la vallée','crier devant la télé','chill','exaggeration'),
(672,'fr','Se doucher à l''eau glacée !','Se doucher à l''eau chaude !','se doucher à la plage','se doucher en salle de bain','dramatic','exaggeration'),
(679,'fr','L''argent brille de nouveau !','L''or brille de nouveau !','polir du vieil argent','une voiture couleur argent','dramatic','exclamation'),
(688,'fr','Elle prend soin de sa peau.','Elle prend soin de son chien.','crème sur la peau','se laver la peau au savon','chill','none'),
(693,'fr','Encore cinq minutes. J''ai tellement sommeil.','Encore cinq minutes. Je suis tellement réveillé.','somnoler en trajet de nuit','somnoler en cours du matin','ironic','bad_excuse'),
(697,'fr','Le coin fumeurs est bondé, tout le monde fume.','Le coin fumeurs est vide, personne ne fume.','fumer devant un bar','un panneau interdit de fumer','chill','none'),
(699,'fr','Il a fait passer du fromage en contrebande devant le garde !','Il a fait passer du vin en contrebande devant le garde !','fromage en contrebande dans le foin','fromage en contrebande en bateau','gossip','exclamation'),
(710,'fr','Un nuage de mousse dans ses mains.','Un nuage de mousse sur sa tête.','un énorme nuage de mousse','mousse dans un lave-linge','chill','exaggeration'),
(747,'fr','C''est juste un petit stress.','C''est juste une petite pluie.','du stress au bureau','stress à la salle de sport','ironic','understatement'),
(750,'fr','La ficelle tient solidement le carton.','La ficelle tient solidement le sac.','un carton noué de ficelle','une corde de guitare','business','none'),
(761,'fr','Elle a une grosse enflure au pied.','Elle a une grosse enflure à la main.','une enflure à la cheville','une enflure au genou','chill','none'),
(768,'fr','L''équipe rame en parfaite synchronisation.','L''équipe court en parfaite synchronisation.','une équipe d''aviron à l''aube','une équipe dans un bureau','business','none'),
(781,'fr','Un, deux, trois… le tonnerre !','Un, deux, trois… un arc-en-ciel !','attendre le tonnerre','le tonnerre dans un stade','dramatic','exclamation'),
(785,'fr','Il consulte les horaires.','Il consulte le journal.','un grand tableau des horaires','un emploi du temps scolaire','business','none'),
(788,'fr','Après, c''est elle qui passe son plat au micro-ondes.','Après, c''est elle qui passe son plat au four.','passer ses nouilles au micro-ondes','passer du lait au micro-ondes','gossip','none'),
(789,'fr','Le grille-pain a propulsé le toast !','Le four a propulsé le toast !','toasts éjectés du grille-pain','un mini-four','slang','exaggeration'),
(834,'fr','L''hôtesse en a marre d''eux.','Le serveur en a marre d''eux.','une hôtesse servant ses invités','une hôtesse de l''air','gossip','guessing'),
(839,'fr','Il allonge sa table !','Il allonge son lit !','allonger une table extensible','prolonger un visa','dramatic','exclamation'),
(842,'fr','Le bébé veut toutes les lettres.','Le bébé veut tous les biscuits.','bébé jouant avec des lettres','bébé jouant avec la nourriture','gossip','guessing'),
(855,'fr','Ils font une promenade au bord de la mer.','Ils font un footing au bord de la mer.','promenade en bord de mer','une promenade en montagne','chill','none'),
(864,'fr','Cette eau est super claire, c''est fou.','Ce lait est super clair, c''est fou.','de l''eau claire en bouteille','de l''eau en gobelet','slang','exaggeration'),
(868,'fr','Juste une petite vague.','Juste un petit requin.','une vague sur des nageurs','un signe de la main','ironic','understatement'),
(871,'fr','Il a marqué depuis son fauteuil roulant !','Il a raté depuis son fauteuil roulant !','un fauteuil roulant de sport','un fauteuil roulant à l''hôpital','dramatic','exclamation'),
(872,'fr','Son sifflement marche enfin !','Son chant marche enfin !','un sifflement au jardin','un sifflement au stade','dramatic','exclamation'),
(873,'fr','Sa femme sait faire sauter les crêpes !','Sa femme sait faire sauter les burgers !','une femme faisant sauter des crêpes','une femme faisant un gâteau','flirt','exclamation'),
(877,'fr','Gagnant plein de boue ? Une légende !','Gagnant tout propre ? Une légende !','le gagnant d''une course boueuse','le gagnant d''une course de natation','slang','none'),
(884,'fr','Elle lui montre le monde.','Elle lui montre la carte.','un monde de lumières urbaines','une carte du monde','chill','exaggeration'),
(885,'fr','Le ver de terre s''enfonce sous terre.','Le ver de terre grimpe à un arbre.','un ver de terre enfoui','un ver sur un hameçon','chill','none'),
(889,'fr','Son yaourt ne coule pas !','Son miel ne coule pas !','un pot de yaourt épais','boire son yaourt au goulot','dramatic','exclamation'),
(916,'fr','Elle utilise un distributeur de billets.','Elle utilise un téléphone.','distributeur de billets sous la pluie','un distributeur en magasin','chill','none'),
(925,'fr','Son sac est à la livraison des bagages.','Son sac est à l''enregistrement.','sac à la livraison des bagages','un sac au contrôle de sécurité','chill','none'),
(927,'fr','Elle secoue un tapis sur le balcon.','Elle secoue une serviette sur le balcon.','un tapis sur le balcon','une plante sur le balcon','chill','none'),
(933,'fr','Elle est dans la salle de bains.','Elle est dans la cuisine.','toilette en salle de bains','nettoyer la salle de bains','chill','none'),
(961,'fr','Le grand frère gagne encore.','La grande sœur gagne encore.','un frère en clé de cou','boxer avec son frère','slang','cliche'),
(962,'fr','Elle a un gros bleu au genou.','Elle a un gros bleu au bras.','un bleu sur un genou','un bleu sur l''œil','chill','none'),
(984,'fr','Le plâtre est encore humide.','Le plâtre est sec.','un plâtre au bras','un plâtre à la jambe','nerd','none'),
(1009,'fr','La boussole est plus maligne que moi.','Le vieux téléphone est plus malin que moi.','une boussole en laiton','une montre en laiton','low_iq','exaggeration'),
(1025,'fr','Ce cycliste a trop de cran.','Ce coureur a trop de cran.','un cycliste en plein virage','un cycliste en ville','slang','none'),
(1072,'fr','Ces deux types sont trop contents.','Ces deux types sont trop énervés.','deux types se serrant la main','un camarade qui fait coucou','slang','none'),
(1073,'fr','La grimpeuse vole !','Le grimpeur vole !','une grimpeuse','une coureuse','dramatic','exaggeration'),
(1074,'fr','Il vérifie si elle a de la fièvre.','Il vérifie son téléphone.','vérifier sa fièvre','prendre son pouls','chill','none'),
(1093,'fr','Il y a une fracture à la jambe.','Il y a une fracture au bras.','une fracture de la jambe','une fracture du poignet','nerd','none'),
(1136,'fr','Il est enfin à la maison !','Il est enfin au travail !','rentrer à la maison','quitter la maison','dramatic','exclamation'),
(1141,'fr','Un client quitte l''hôtel.','Un client entre dans l''hôtel.','quitter un grand hôtel','un hôtel balnéaire','business','none'),
(1161,'fr','Il met de la glace sur son genou.','Il met de la glace sur sa tête.','glace sur un genou plié','un genou à terre','business','none'),
(1179,'fr','Trop de bagages pour un seul homme.','Trop de bagages pour une seule fille.','un chariot plein de bagages','des bagages sur le toit','low_iq','exaggeration'),
(1182,'fr','La femme de chambre fait le lit.','La femme de chambre fait du café.','femme de chambre faisant le lit','femme de chambre à un mariage','chill','none'),
(1185,'fr','Le responsable donne des ordres.','Le responsable donne des cadeaux.','un responsable avec son ordi','un responsable au téléphone','business','none'),
(1215,'fr','Les voisins discutent.','Les voisins se disputent.','des voisins à la clôture','un voisin bruyant','chill','none'),
(1290,'fr','Cet itinéraire a tellement de virages !','Cet itinéraire a tellement de camions !','un itinéraire vers le sommet','un itinéraire côtier','dramatic','exclamation'),
(1316,'fr','Les frères et sœurs rient.','Les frères et sœurs se disputent.','frères et sœurs qui rient ensemble','une bagarre pour un jouet','chill','none'),
(1342,'fr','Son fils est de retour à la maison !','Sa fille est de retour à la maison !','étreindre son fils adulte','dire au revoir à son fils','dramatic','exclamation'),
(1362,'fr','On pose des points de suture sur la coupure.','On pose un pansement sur la coupure.','points de suture à l''avant-bras','points de couture d''une chemise','chill','none'),
(1373,'fr','Ambiance d''été : gros saut dans le lac.','Ambiance d''été : gros saut dans la piscine.','un plongeon d''été au lac','une pool party d''été','slang','none'),
(1381,'fr','La seringue fait gicler du liquide !','La bouteille fait gicler du liquide !','faire gicler une seringue','remplir une seringue','dramatic','exclamation'),
(1406,'fr','Regarde ma brosse à dents !','Regarde ma brosse à cheveux !','une brosse à dents moussante','brosse à dents dans un verre','dramatic','exclamation'),
(1423,'fr','Doigt pointé sur un graphique en barres.','Doigt pointé sur un graphique en camembert.','graphiques en barres et courbes','un graphique sur papier','business','none'),
(1454,'fr','Elle mesure son tour de taille.','Elle mesure son tour de bras.','mesurer son tour de taille','une ceinture à la taille','business','none'),
(1473,'fr','L''ouvrier tient une poutre.','L''ouvrier tient un tuyau.','un ouvrier avec des lunettes','un ouvrier en costume','chill','none'),
(1476,'fr','L''écrivain tape la nuit, évidemment.','L''écrivain tape à midi, évidemment.','un écrivain à la machine','un écrivain sur ordinateur','ironic','cliche'),
(1502,'fr','Coucher de soleil à deux. Trop mignon.','Petit-déj à deux. Trop mignon.','regarder le coucher de soleil ensemble','un coucher de soleil montagnard','gossip','none'),
(1524,'fr','Il fait du stop, et c''est un OVNI qui répond.','Il fait du stop, et c''est un bus qui répond.','faire du stop en montagne','faire du stop sur l''autoroute','gossip','guessing'),
(1569,'fr','C''est un portrait en hachures croisées.','C''est un portrait à l''aquarelle.','un portrait à la plume','un portrait à l''huile','nerd','none'),
(1581,'fr','La vie en camionnette, baby !','La vie sous la tente, baby !','une camionnette avec un surf','une camionnette avec un vélo','slang','exclamation'),
(1593,'fr','J''adore cette coupe de cheveux bleue !','J''adore ce chapeau bleu !','coupe carrée bleu canard','une coupe de cheveux au salon','flirt','exclamation'),
(1613,'fr','Trois fusées décollent !','Deux fusées décollent !','des fusées décollant au crépuscule','une fusée atterrissant au crépuscule','dramatic','exclamation'),
(1617,'fr','L''ange guide un enfant.','L''ange guide un agneau.','un ange qui guide un enfant','un ange à la harpe','chill','none'),
(1618,'fr','Des anges volent autour de lui.','Des oiseaux volent autour de lui.','des anges ailés dans les nuages','des anges sur un sapin','chill','none'),
(1619,'fr','Le grand navire va toutes voiles dehors.','Le grand navire n''a aucune voile.','des voiles gonflées par le vent','des voiles déchirées par le vent','chill','none'),
(1625,'fr','Le surfeur tient une planche de surf.','Le surfeur tient une guitare.','tenir une planche de surf debout','surfer les vagues','chill','none'),
(1672,'fr','Prague brille au crépuscule.','Prague brille à midi.','le château de Prague au crépuscule','le château de Prague enneigé','chill','none'),
(1676,'fr','Assis avec un café ? Trop la vibe.','Assis avec un livre ? Trop la vibe.','assis dans un fauteuil','assis à un bureau','slang','cliche'),
(1706,'fr','Chien stylé, lunettes de soleil stylées.','Chien stylé, chapeau stylé.','un husky en lunettes de soleil','lunettes de soleil sur serviette','slang','none'),
(1707,'fr','Les plantes dévorent la chaumière.','Les plantes dévorent l''église.','une chaumière en pierre envahie','une chaumière sur la côte','ironic','exaggeration'),
(1729,'fr','Elle a deux animaux de compagnie.','Elle a trois animaux de compagnie.','une fille et ses animaux','une fille achetant un animal','chill','none'),
(1752,'fr','Les fenêtres du moulin à vent sont allumées.','Les fenêtres du moulin à vent sont ouvertes.','un moulin près d''un lac','un moulin dans un champ','chill','none'),
(1766,'fr','Des mûres noires et rouges.','Des mûres noires et vertes.','des mûres sur une branche','des mûres dans une tarte','chill','none'),
(1783,'fr','Quatre enfants sur les mêmes genoux, un câlin pour chaque enfant.','Quatre enfants sur les mêmes genoux, un cadeau pour chaque enfant.','un homme serrant chaque enfant','un homme instruisant chaque enfant','chill','none'),
(1847,'fr','Je compte trois sapins de Noël.','Je compte cinq sapins de Noël.','trois petits sapins de Noël','un sapin avec des cadeaux','low_iq','none'),
(1849,'fr','Sa magie brille !','Ses cheveux brillent !','une magie bleue lumineuse','un tour de cartes','dramatic','exclamation'),
(1876,'fr','Casque pas cher : un bocal à poissons.','Casque pas cher : un seau.','un bocal sur la tête','un bocal sur la table','ironic','cheap_quality'),
(1920,'fr','Le cyborg a la tête lumineuse.','Le cyborg a la queue lumineuse.','un cyborg dans une ville néon','un cyborg dans une forêt','nerd','none'),
(1946,'fr','Ce chat est trop cool.','Ce chien est trop cool.','un chat cool à lunettes','une boisson fraîche d''été','slang','exaggeration'),
(1953,'fr','Une couronne de flocons de neige ? Vibe de reine.','Une couronne de fleurs ? Vibe de reine.','une couronne de flocons de neige','des flocons sur une vitre','flirt','exaggeration'),
(1958,'fr','Escalier en pierre et fleurs roses.','Escalier en pierre et fleurs rouges.','escalier en pierre au village','escalier en pierre au château','chill','none'),
(2000,'fr','Le clair de lune brille sur l''eau.','La lumière du soleil brille sur l''eau.','clair de lune sur un marais','clair de lune dans une chambre','chill','none'),
(2001,'fr','Le hibou a un bec en or. Hibou blindé !','Le hibou a un bec rouge. Hibou blindé !','le bec doré d''un hibou','le bec cassé d''un hibou','low_iq','exaggeration'),
(2057,'fr','La cheminée est en pierre.','La cheminée est en métal.','une cheminée en pierre enneigée','ramoner la cheminée','chill','none'),
(2059,'fr','La lumière du soleil ne touche qu''un côté.','Le clair de lune ne touche qu''un côté.','des branches en pleine lumière','la lumière du soleil sur l''eau','nerd','none'),
(2060,'fr','Des skis rouges et jaunes, trop stylé.','Des skis bleus et blancs, trop stylé.','des skis plantés dans la neige','des skis sur une voiture','slang','none'),
(2075,'fr','Des livres sont posés sur le rebord de fenêtre.','Des chats sont posés sur le rebord de fenêtre.','livres sur un rebord de fenêtre','plantes sur un rebord de fenêtre','chill','none'),
(2081,'fr','Des pierres de gué traversent un lac.','Des pierres de gué traversent une route.','des pierres de gué sur l''eau','pierres de gué au jardin','chill','none'),
(2093,'fr','Toute la ville est verte.','Toute la ville est grise.','des tours vertes pleines d''arbres','de la peinture verte','business','none'),
(2099,'fr','Cette cabane dans un arbre est trop cool !','Cette niche est trop cool !','une cabane dans un arbre tropical','une cabane perchée au jardin','slang','exclamation'),
(2100,'fr','Sa robe de bal est plus grande que le jardin !','Son chapeau est plus grand que le jardin !','une immense robe de bal bleue','une robe sur un cintre','dramatic','exaggeration'),
(2114,'fr','Un pont jeté sur le ruisseau.','Un pont jeté sur la route.','un pont sur un ruisseau','une maison en face','chill','none'),
(2134,'fr','L''impératrice n''a pas l''air ravie.','L''impératrice a l''air ravie.','une impératrice sévère','une impératrice à cheval','ironic','understatement'),
(2150,'fr','Queue de cheval faite. Elle va y aller.','Cheveux lâchés. Elle va y aller.','queue de cheval à la fenêtre','la queue d''un vrai cheval','chill','guessing'),
(2151,'fr','Le croissant de lune chill tranquille.','La pleine lune chill tranquille.','croissant de lune voilé','croissant de lune à midi','slang','none'),
(2155,'fr','Ce sourire sûr de soi, ça marche.','Ce sourire nerveux, ça marche.','un demi-sourire sûr de soi','un gros rire assuré','flirt','none'),
(2176,'fr','Il pleut dans l''allée !','Il neige dans l''allée !','une allée de bibliothèque pluvieuse','une allée de supermarché bondée','dramatic','exclamation'),
(2178,'fr','Psst, deux chats jettent un coup d''œil.','Psst, deux chiens jettent un coup d''œil.','coup d''œil derrière les feuilles','coup d''œil par la fenêtre','gossip','none'),
(2190,'fr','Ce méchant a les yeux en feu.','Ce méchant a les yeux bleus.','un méchant parmi les flammes','un méchant dans un château','dramatic','none'),
(2214,'fr','Je vois un château à travers.','Je vois une église à travers.','voir à travers la roche','voir à travers une fenêtre','chill','none'),
(2224,'fr','Ils se tiennent la main.','Ils se serrent la main.','se tenir la main sous l''averse','se tenir la main au soleil','flirt','none'),
(2227,'fr','Elle jette un coup d''œil en arrière. À toi ?','Elle jette un coup d''œil vers le bas. À toi ?','jeter un coup d''œil par-dessus l''épaule','un coup d''œil au téléphone','gossip','guessing'),
(2233,'fr','Elle a deux gants de baseball.','Elle a deux battes de baseball.','deux gants de baseball','du baseball à la télé','chill','none'),
(2260,'fr','Pauvre barque à rames, personne n''en veut.','Pauvre navire, personne n''en veut.','une barque à rames vide','une barque bondée','dramatic','exaggeration'),
(2268,'fr','Elle est sur une corde raide. Sans filet !','Elle est sur une échelle. Sans filet !','en équilibre sur une corde raide','un numéro de cirque','dramatic','exclamation'),
(2273,'fr','Jean déchiré, total look denim.','Jean déchiré, total look noir.','un jean bleu très déchiré','repasser un jean bleu','slang','none'),
(2313,'fr','Mon chez-moi ? Là où se pose le camping-car.','Mon chez-moi ? Là où se pose la tente orange.','un camping-car orange','un camping-car en ville','chill','cliche'),
(2341,'fr','Les fleurs rendent la mort jolie.','Les bougies rendent la mort jolie.','la mort parmi les fleurs','la mort sur la route','ironic','none'),
(2368,'fr','Cette plage, c''est le paradis total.','Ce désert, c''est le paradis total.','un paradis tropical au crépuscule','un paradis pour skieurs','slang','none'),
(2379,'fr','Des feuilles rouges tombent.','Des pommes rouges tombent.','des feuilles tombant sous l''averse','neige tombant sur les voitures','chill','none'),
(2398,'fr','La terrasse offre une vue sur la mer.','La terrasse offre une vue sur la ville.','une terrasse carrelée côté mer','une terrasse à la montagne','business','none'),
(2415,'fr','Le dieu porte des guirlandes de fleurs.','Le dieu porte des guirlandes de papier.','des guirlandes de fleurs rouges','des guirlandes sur un sapin','chill','none'),
(2421,'fr','Ce champignon est grand. Vraiment grand.','Ce champignon est petit. Vraiment petit.','un champignon pâle géant','moisissure sur du vieux pain','low_iq','exaggeration'),
(2430,'fr','La rivière coule entre les rochers.','La rivière coule entre les maisons.','une rivière coulant entre des rochers','une rivière qui coule en ville','chill','none'),
(2451,'fr','Un oiseau près de la tour Eiffel.','Un avion près de la tour Eiffel.','la tour Eiffel côté Seine','la tour Eiffel sous la neige','chill','none'),
(2458,'fr','Une maison de ferme aux fenêtres éclairées.','Une maison de ferme aux fenêtres sombres.','maison de ferme au crépuscule','une maison de ferme côtière','chill','none'),
(2471,'fr','Elle, c''est un vrai rat de bibliothèque.','Elle, c''est une vraie gameuse.','un rat de bibliothèque lisant','un rat de bibliothèque scrollant','gossip','none'),
(2474,'fr','Une écume sauvage sur une mer déchaînée.','Une écume sauvage sur une mer calme.','de l''écume sur des vagues déchaînées','un cappuccino bien mousseux','dramatic','none'),
(2480,'fr','La voiture a beaucoup trop de cadeaux !','La voiture a beaucoup trop de chiens !','des cadeaux sur le toit','des cadeaux sous un sapin','dramatic','exaggeration'),
(2482,'fr','Tant de tourelles sur un seul château !','Tant de drapeaux sur un seul château !','des tourelles de château pointues','une tourelle de char','gossip','exclamation'),
(2490,'fr','Joli chapeau ! Le bonhomme de neige a froid ?','Joli chapeau ! Le chien a froid ?','un bonhomme de neige chapeauté','faire un bonhomme de neige','low_iq','guessing'),
(2499,'fr','Deux ours en peluche se font un câlin.','Deux ours en peluche se battent.','des ours en peluche enneigés','ours en peluche sur un lit','chill','none'),
(2522,'fr','Les trèfles ont quatre feuilles.','Les trèfles ont trois feuilles.','des trèfles à quatre feuilles','un champ de trèfle','nerd','none'),
(2523,'fr','La chute de neige est forte ce soir.','L''averse de pluie est forte ce soir.','une forte chute de neige','une légère chute de neige','chill','none'),
(2530,'fr','La lueur de bougie brille parmi les roses.','La lueur de bougie brille parmi les livres.','lueur de bougie dans une lanterne','lueur de bougie sur un gâteau','chill','none'),
(2537,'fr','La fille lit une histoire du soir.','Le garçon lit une histoire du soir.','une histoire du soir au lit','une histoire du soir télévisée','chill','none'),
(2548,'fr','Tant de tonneaux ! De la bière, peut-être ?','Tant de vélos ! De la bière, peut-être ?','des tonneaux en bois empilés','un tonneau de bière fraîche','low_iq','guessing'),
(2562,'fr','Nuit de pluie, détective solitaire.','Journée de soleil, détective solitaire.','un détective sous la pluie','un détective de la criminelle','dramatic','cliche'),
(2563,'fr','Un marchand vérifie du grain.','Un marchand vérifie des pièces.','un marchand aux chandelles','un marchand au marché','chill','none'),
(2604,'fr','Un arbre sans vie, une lune verte.','Un arbre sans vie, une lune blanche.','arbre sans vie sur des rochers','un arbre en pot sans vie','dramatic','none'),
(2607,'fr','Les chats portent des manteaux habillés.','Les chiens portent des manteaux habillés.','chats portant de longs manteaux','chats portant des colliers','business','none'),
(2622,'fr','Une statue de la Liberté miniature !','Une tour Eiffel miniature !','une mini statue de la Liberté','un déguisement de statue','dramatic','exclamation'),
(2631,'fr','Ses lunettes ont des verres ronds.','Ses lunettes n''ont pas de verres.','des verres ronds teintés','un objectif d''appareil photo','chill','none'),
(2634,'fr','Chaque bouteille a un bouchon.','Chaque bouteille a une paille.','des bouteilles fermées par des bouchons','un panneau en liège','chill','none'),
(2660,'fr','Des lianes pendent au-dessus de l''arche.','Des drapeaux pendent au-dessus de l''arche.','des lianes sur une arche','une vigne chargée de raisins','chill','none'),
(2661,'fr','Les carreaux forment un échiquier.','Les carreaux forment un arc-en-ciel.','des carreaux noirs et blancs','des carreaux bleus et blancs','nerd','none'),
(2666,'fr','Des pots de fleurs bordent les marches.','Des bougies bordent les marches.','pots de fleurs sur les marches','pots de fleurs à la fenêtre','chill','none'),
(2711,'fr','Des feuilles de nénuphar flottent autour d''elle.','Des bateaux flottent autour d''elle.','feuilles de nénuphar sur l''étang','des nénuphars avec des grenouilles','chill','none'),
(2717,'fr','Le Parlement est au bord de la Tamise.','Le Parlement est au bord de la Seine.','le Parlement de Londres','un parlement sur la côte','nerd','none'),
(2732,'fr','Le petit-fils est assis sur ses genoux.','Le petit-fils est assis sur une chaise.','petit-fils sur les genoux de papi','un petit-fils à la plage','chill','none'),
(2741,'fr','Le programmeur code la nuit.','Le programmeur code à midi.','un programmeur qui tape du code','un programmeur à la muscu','nerd','cliche'),
(2745,'fr','De vieilles pierres remplissent la cour.','De vieilles voitures remplissent la cour.','une cour pavée de pierres','un café dans une cour','chill','none'),
(2793,'fr','Deux hommes d''affaires sont au sommet.','Cinq hommes d''affaires sont au sommet.','un homme d''affaires dans l''escalier','homme d''affaires dans un ascenseur','business','none'),
(2808,'fr','La femme d''affaires sourit.','La femme d''affaires pleure.','femme d''affaires devant sa voiture','femme d''affaires dans le train','business','none'),
(2809,'fr','Elle tient une petite tasse à thé.','Elle tient une petite théière.','tasse à thé à deux mains','tasse à thé sur soucoupe','chill','none'),
(2833,'fr','Burn-out : sa tête fume.','Burn-out : son thé fume.','un burn-out au bureau','un burn-out à la muscu','dramatic','exaggeration'),
(2887,'fr','Le feu d''artifice accueille 2025 !','Le feu d''artifice accueille 2024 !','un feu d''artifice au-dessus des toits','feu d''artifice sur la mer','dramatic','exclamation'),
(3052,'fr','Il pense, il bosse pas.','Il dort, il bosse pas.','penser, assis à un pupitre','penser, à la table de cuisine','slang','guessing'),
(3078,'fr','Elle fait frire des œufs comme une pro.','Elle fait frire du poisson comme une pro.','faire frire des œufs','faire bouillir des œufs','slang','cliche'),
(3157,'fr','Il brandit une brique rouge.','Il brandit un casque rouge.','un mur de briques inachevé','une maison de plage en briques','chill','none'),
(3171,'fr','Quel poteau indicateur « utile ».','Quelle carte « utile ».','un vieux poteau indicateur en bois','un vieux poteau de clôture','ironic','understatement'),
(3191,'fr','On serre le chat dans ses bras, il n''a rien demandé.','On serre le chien dans ses bras, il n''a rien demandé.','serrer un chat dans ses bras','serrer un chien dans ses bras','chill','guessing'),
(3194,'fr','Le dentiste a une fraise. Au secours !','Le dentiste a un couteau. Au secours !','un dentiste avec une fraise','une dentiste se brossant les dents','dramatic','exclamation'),
(3266,'fr','Elle fait du vélo le long de la baie.','Elle fait du vélo le long de la rivière.','faire du vélo sur la côte','faire du vélo près des rails','chill','none'),
(3274,'fr','La raquette de tennis de table est rouge.','La raquette de tennis de table est noire.','une table de tennis de table','du tennis de table télévisé','chill','none'),
(3285,'fr','Son costume a des perroquets en plastique !','Son costume a des serpents en plastique !','un costume avec coiffe de fruits','un costume d''Halloween','gossip','exclamation'),
(3293,'fr','Elle a donné un coup de poing, gant bien haut !','Elle a donné un coup de poing, gant bien bas !','coups de poing sur le ring','poinçonner un billet','dramatic','exclamation'),
(3294,'fr','Il va donner un coup de pied dans le ballon !','Il va lancer le ballon !','prêt pour le coup de pied','ouvrir une porte du pied','dramatic','exclamation'),
(3304,'fr','La crosse de hockey, c''est pour le palet, je crois.','La crosse de hockey, c''est pour le ballon, je crois.','une crosse de hockey sur glace','une crosse de hockey cassée','low_iq','guessing'),
(3314,'fr','Elle fait du jogging avec des écouteurs.','Elle fait du jogging avec un chien.','faire du jogging sur une route','faire du jogging sur la plage','chill','none'),
(3458,'fr','Des têtes de pierre sous les étoiles.','Des têtes de pierre sous le soleil.','étoiles au-dessus des têtes de pierre','les étoiles d''un drapeau','chill','none'),
(3463,'fr','Il pagaie dans un canoë.','Il pagaie sur un radeau.','pagayer en canoë au crépuscule','porter un canoë au crépuscule','chill','none'),
(3470,'fr','Une immense dune de sable orange.','Une immense dune de sable blanc.','la crête courbe d''une dune','une dune en bord de mer','chill','none'),
(3479,'fr','Un sac à main rose, un café calme.','Un ordi portable rose, un café calme.','sac à main sur la table','un sac à main en magasin','chill','none'),
(3486,'fr','Elle boit dans une noix de coco.','Elle boit dans une bouteille.','une noix de coco avec paille','ouvrir une noix de coco','chill','none'),
(3493,'fr','Elle laisse des empreintes de pas.','Elle laisse des fleurs.','une ligne d''empreintes de pas','empreintes de pas dans la neige','chill','none'),
(3497,'fr','Elle marche vers le coucher de soleil. Classique.','Elle marche vers la mer. Classique.','marcher vers le coucher de soleil','un coucher de soleil en voiture','ironic','cliche'),
(3589,'fr','Le gorille est juste en train de chiller.','Le gorille est juste en train de manger.','un gorille dans les bambous','un gorille se frappant la poitrine','slang','none'),
(3598,'fr','Ses cheveux bouclés sont au stylo bleu.','Ses cheveux bouclés sont au stylo rouge.','cheveux bouclés au stylo bleu','cheveux bouclés à la peinture rouge','chill','none'),
(3638,'fr','Job spatial : passer la serpillière.','Job spatial : peindre le sol.','serpillière sur un sol brillant','éponger du café renversé','ironic','understatement'),
(3639,'fr','Meilleure place de l''espace : un tabouret rouge.','Meilleure place de l''espace : un tabouret bleu.','assis sur un tabouret rouge','un tabouret de salle de bain','ironic','exaggeration'),
(3640,'fr','La lampe brille dans l''espace.','La lampe éclaire un vaisseau.','un faisceau qui brille dans l''espace','une lumière sur un vaisseau','chill','none'),
(3706,'fr','Les montagnes russes terrifient tout le monde !','La grande roue terrifie tout le monde !','une famille dans les montagnes russes','une famille près des montagnes russes','dramatic','exaggeration'),
(3718,'fr','Sweat à capuche, bomber, lunettes de soleil : la classe.','Sweat à capuche, bomber, casquette : la classe.','sweat à capuche sous un bomber','enfiler un sweat à capuche','slang','none'),
(3779,'fr','Le pauvre jouet est tout seul.','Le pauvre chien est tout seul.','un vieux lapin en peluche','une vieille voiture miniature','dramatic','exaggeration'),
(3797,'fr','Équilibre sur les mains dans l''eau, trop fort !','Équilibre sur les mains dans la neige, trop fort !','équilibre sur les mains dans l''eau','sur les mains à la plage','slang','none'),
(3806,'fr','Il y a deux cerises dans la boisson.','Il y a trois cerises dans la boisson.','deux cerises sur une même queue','un bol de cerises','chill','none'),
(3828,'fr','Le chimpanzé et l''allumette : mauvaise idée.','Le chimpanzé et le couteau : mauvaise idée.','une allumette allumée à la main','un match de foot télévisé','chill','guessing'),
(3832,'fr','Le feu d''artifice explose !','Les ballons explosent !','un feu d''artifice dans la nuit','des feux d''artifice en magasin','dramatic','exclamation'),
(3841,'fr','Les vêtements volent partout !','Les chaussures volent partout !','des vêtements qui flottent en l''air','des vêtements dans le lave-linge','dramatic','exclamation'),
(4004,'fr','L''avion chauffe du pain. Normal.','L''avion chauffe de la soupe. Normal.','chauffer du pain dans un avion','chauffer de la soupe','ironic','understatement'),
(4013,'fr','Un iceberg longe le pont. Vibe Titanic !','Une baleine longe le pont. Vibe Titanic !','des bottes sur le pont','un jeu de cartes','slang','exclamation'),
(4019,'fr','Ce chiot a la bouée la plus stylée.','Ce chaton a la bouée la plus stylée.','une bouée rose','une bague en diamant','slang','exaggeration'),
(4023,'fr','Ils s''amusent comme des fous sur un bateau.','Ils s''amusent comme des fous dans un bus.','du fun sur la rivière','du fun à la plage','chill','none'),
(4029,'fr','La bouteille l''a frappé, il est tombé !','Le ballon l''a frappé, il est tombé !','frappé et projeté du bloc','frapper à une porte','slang','exclamation'),
(4031,'fr','La balle a atterri pile tout en haut !','La balle a atterri pile sur lui !','le niveau supérieur de la pile','l''étagère supérieure','dramatic','exclamation'),
(4032,'fr','Quel carnage vert !','Quel carnage rouge !','du slime vert partout','une chambre en désordre','gossip','exaggeration'),
(4035,'fr','Il fait un pas au-dessus de l''eau.','Il fait un pas au-dessus du feu.','un pas sur des blocs flottants','monter dans un train en marche','chill','none'),
(4039,'fr','Elle a rampé, mais le groupe a gagné.','Elle a couru, mais le groupe a gagné.','ramper sur mains et orteils','ramper sous un lit','gossip','blaming_someone'),
(4042,'fr','Ils sont devant un magasin.','Ils sont dans un magasin.','devant un magasin éclairé','un magasin de noix de coco','chill','none'),
(4053,'fr','Même le maïs est un gâteau !','Même la carotte est un gâteau !','un gâteau en forme de maïs','un champ de maïs au crépuscule','dramatic','exclamation'),
(4058,'fr','Un voyage d''une nuit, dix valises !','Un voyage d''une nuit, deux valises !','faire ses valises pour un voyage','trébucher sur une valise','dramatic','banter'),
(4066,'fr','Un perroquet roule sur la terre rouge. Légende.','Un perroquet roule sur le sable mouillé. Légende.','une piste de terre rouge','terre sur une chemise blanche','slang','exaggeration'),
(4069,'fr','Le poussin tient une tige.','Le pigeon tient une tige.','une tige comme canne à pêche','le pigeon qui tient une tige','chill','none'),
(4079,'fr','La rivière file à toute allure. Dingue !','Les voitures filent à toute allure. Dingue !','foncer en descendant la rivière','foncer à l''aéroport','slang','exaggeration'),
(4086,'fr','Le moustique va piquer.','L''araignée va piquer.','piquer un homme endormi','piquer un chien endormi','chill','guessing'),
(4090,'fr','La fusée monte vite !','L''avion monte vite !','la fusée qui monte vite','le soleil qui se lève','dramatic','exclamation'),
(4091,'fr','La glace se fissure sous elle !','La glace se fissure sous lui !','glace qui se fissure sous elle','casser des œufs sur la glace','dramatic','exclamation'),
(4092,'fr','Il dévale les marches jusqu''en bas !','Il monte les marches jusqu''en haut !','en bas des marches rocheuses','en bas des pistes de ski','dramatic','exclamation'),
(4118,'fr','Ce court offre une vue sur la montagne.','Ce court offre une belle vue sur la mer.','un court en montagne','un court en bord de mer','business','none'),
(4127,'fr','La fourrure du lémurien est si douce.','La fourrure du lémurien est si noire.','une fourrure blanche et douce','du pain blanc et doux','chill','none'),
(4129,'fr','Le chiot quitte la maison.','Le chiot rentre à la maison.','quitter la maison en chapeau','rentrer à la maison en chapeau','chill','none'),
(4151,'fr','Cette voiture customisée, c''est de l''art ultra rose.','Cette voiture customisée, c''est de l''art ultra vert.','de l''art rose sur une voiture','de l''art dans un musée','ironic','understatement'),
(4157,'fr','Tout le monde court, mais sa pancarte gagne.','Tout le monde court, mais son chien gagne.','courir devant une pancarte drôle','une course en voiture de sport','gossip','exaggeration'),
(4162,'fr','Une voiture. Toute la place. Tranquille.','Un bus. Toute la place. Tranquille.','une place pavée mouillée','une place avec des étals','slang','none'),
(4165,'fr','À cette vitesse, les arbres deviennent flous.','À cette vitesse, les maisons deviennent floues.','vitesse sur une route de montagne','vitesse sur un circuit','dramatic','none'),
(4166,'fr','Il entre dans cette voiture rouge comme une star.','Il entre dans cette voiture bleue comme une star.','entrer dans une sportive rouge','entrer dans une cabine téléphonique rouge','flirt','exaggeration'),
(4171,'fr','Le loup se glisse plus près.','Le renard se glisse plus près.','un loup se glissant plus près','un loup qui s''enfuit','chill','none'),
(4172,'fr','La poule a pris la fuite comme dans un film d''action.','Le canard a pris la fuite comme dans un film d''action.','la fuite devant le feu','une évasion de prison','dramatic','exaggeration'),
(4176,'fr','Une luciole brille dans un bocal.','Une bougie brille dans un bocal.','une luciole qui brille','une lampe qui brille','chill','none'),
(4182,'fr','Il a peint toute la pelouse !','Il a peint toute la maison !','peindre un tableau géant sur gazon','peindre une clôture de jardin','dramatic','exaggeration'),
(4185,'fr','Une tasse appuie sur la souris.','Une tasse appuie sur les gaufres.','une tasse appuyant sur une souris','une assiette appuyant sur une souris','chill','none'),
(4221,'fr','Le lézard chill sur le canapé.','Le lézard chill sur la table.','des céréales sur le canapé','céréales sur la table de cuisine','slang','none'),
(4247,'fr','Des garçons sautent dans un puits !','Des garçons sautent dans un lac !','des garçons sautant dans un puits','des garçons buvant à un puits','dramatic','exclamation'),
(4248,'fr','La vague de la piscine couverte a gagné cette fois.','La vague de l''océan a gagné cette fois.','une piscine à vagues couverte','cours de natation en piscine couverte','chill','none'),
(4259,'fr','Ce mouton a une tête de lundi matin.','Cette vache a une tête de lundi matin.','une tête de mouton en colère','une tête de mouton heureux','ironic','cliche'),
(4292,'fr','Une brise fait bouger ses cheveux.','Un ventilateur fait bouger ses cheveux.','une brise dans la prairie','une brise en bord de mer','chill','none'),
(4304,'fr','Il a lancé le ballon de football américain, stylé.','Il a shooté dans le ballon de football américain, stylé.','ballon de football américain en l''air','un ballon rond sur la pelouse','slang','none'),
(4312,'fr','Il parle fort, mais personne n''entend.','Il parle doucement, mais personne n''entend.','un appel très fort','une fête très bruyante','ironic','none'),
(4325,'fr','Fait scientifique : le bétail broute.','Fait scientifique : les chevaux broutent.','du bétail broutant dans une plaine','du bétail dans une étable','nerd','none'),
(4329,'fr','Ils sont assis sur les meubles.','Ils sont assis par terre.','assis sur des meubles moelleux','porter les meubles','chill','none'),
(4339,'fr','Sa carte bancaire passe !','Sa carte bancaire est cassée !','une rangée de distributeurs de banque','une banque près de la rivière','slang','exclamation'),
(4343,'fr','Des rires partout !','Des larmes partout !','des rires en salle de jeux','des rires au cinéma','dramatic','exclamation'),
(4349,'fr','Ce gardien surfe vraiment bien.','Ce gardien skie vraiment bien.','un gardien qui surfe','un gardien à cheval','flirt','none'),
(4354,'fr','Son coup de pied fait voler les feuilles.','Son coup de pied fait voler les glands.','coup de pied dans les feuilles','coup de pied dans un ballon','chill','none'),
(4356,'fr','Dos douloureux ? À califourchon quand même !','Nuque douloureuse ? À califourchon quand même !','frotter un dos douloureux','une gorge douloureuse au lit','slang','exclamation'),
(4357,'fr','Son sac à dos en toile pourrait contenir un canapé.','Son sac à dos en cuir pourrait contenir un canapé.','grand sac à dos en toile','une toile pour peindre','chill','exaggeration'),
(4361,'fr','Elle fait du shopping comme une pro.','Il fait du shopping comme un pro.','faire du shopping, les bras chargés','faire les courses','slang','exaggeration'),
(4371,'fr','Le hall d''entrée de la banque est immense.','Le hall d''entrée de la banque est minuscule.','hall d''entrée de banque en marbre','le hall d''un hôtel bondé','business','none'),
(4389,'fr','Ça a commencé sans lui. Oups.','Le bus est parti sans lui. Oups.','rater le début','démarrer une voiture','ironic','understatement'),
(4390,'fr','L''excitation est à son comble !','L''ennui est à son comble !','l''excitation avant un concert','l''excitation avant un examen','slang','exclamation'),
(4391,'fr','Seul avec une pizza entière ? Oui !','Seul avec un gâteau entier ? Oui !','seul chez soi avec une pizza','seul au restaurant','slang','exclamation'),
(4397,'fr','Il fait du vélo à Amsterdam.','Il fait du vélo en forêt.','du vélo le long d''un canal','du vélo le long d''une plage','chill','none'),
(4407,'fr','Grâce aux épinards, il reste en bonne santé.','Grâce au chocolat, il reste en bonne santé.','un jeune homme en bonne santé','un compte en banque sain','chill','none'),
(4411,'fr','Le traitement, c''est un pansement.','Le traitement, c''est une piqûre.','un traitement contre une ampoule','traitement contre le mal de tête','chill','none'),
(4427,'fr','Ils s''inclinent lors d''une cérémonie.','Ils mangent lors d''une cérémonie.','une cérémonie avec révérences','une cérémonie de mariage','business','none'),
(4451,'fr','Deux adolescents jouent aux jeux vidéo, grave intense.','Deux adolescents dansent, grave intense.','des adolescents jouant à un jeu','des adolescents jouant au foot','slang','exaggeration'),
(4465,'fr','Il est allé en haut, meilleur jour de sa vie !','Il est allé en bas, meilleur jour de sa vie !','en haut d''un bus','en haut dans une maison','dramatic','exaggeration'),
(4474,'fr','Le menu est au mur.','Le menu est sur la table.','menu des cafés sur ardoises','un menu sur un téléphone','chill','none'),
(4503,'fr','Elle fait un vœu.','Elle fait un gâteau.','faire un vœu d''anniversaire','souhaiter qu''il pleuve','chill','none'),
(4505,'fr','Il tombe en arrière !','Il tombe en avant !','tomber de sa chaise en arrière','marcher en arrière vers la table','dramatic','exclamation'),
(4516,'fr','Le sol de la grange est plein de foin.','Le sol de la grange est plein de boue.','un nid fait de foin','bottes de foin sur un camion','chill','none'),
(4528,'fr','De vieilles tombes entourent l''église.','De vieilles tombes entourent le château.','des tombes autour d''une église','tombes sur un champ de bataille','dramatic','none'),
(4529,'fr','Un sol plein de couleurs. Magique !','Un sol plein d''eau. Magique !','couleurs sur un sol en pierre','couleurs sur un mur peint','dramatic','none'),
(4533,'fr','Ils font la fête dans la salle d''audience.','Ils pleurent dans la salle d''audience.','une famille heureuse en salle d''audience','fête sur un court de tennis','chill','none'),
(4539,'fr','Le bonhomme du dessin humoristique passe la serpillière.','Le bonhomme du dessin humoristique cuisine.','le dessin humoristique d''un agent d''entretien','le dessin humoristique d''un cuisinier','chill','none'),
(4540,'fr','Un équipement de sécurité adapté.','Un équipement de plongée adapté.','un équipement de lavage de vitres','équipement de gym en salle','business','none'),
(4542,'fr','Ils sont parvenus à un accord.','Ils sont parvenus à l''aéroport.','serrer la main pour un accord','un contrat de location','business','none'),
(4544,'fr','Sable et glace. Petit contraste.','Mer et glace. Petit contraste.','le contraste sable et glace','le contraste jour et nuit','ironic','understatement'),
(4553,'fr','Une brosse pour ses cheveux, puis la même pour le chien.','Une brosse pour ses cheveux, puis la même pour le chat.','brosser de longs cheveux bruns','poils de chien sur un canapé','gossip','cheap_quality'),
(4567,'fr','Elle a l''air un peu malade.','Elle a l''air très heureuse.','malade, en train de tousser','malade au lit','chill','understatement'),
(4569,'fr','Il fait frire du poisson. Vanlife !','Il fait frire des œufs. Vanlife !','du poisson frit dans un van','du poisson frit sur un bateau','slang','cliche'),
(4607,'fr','De grandes cuves en cuivre derrière elle.','De grandes cuves en plastique derrière elle.','des cuves de brassage en cuivre','pièces en cuivre dans un bocal','chill','none'),
(4614,'fr','Il accroche une guirlande en papier.','Il accroche une lanterne en papier.','accrocher des décorations de fête','étendre le linge','chill','none'),
(4617,'fr','Des hommes en armure se battent.','Des hommes en costume se battent.','se battre avec des boucliers','bagarre pour une place de parking','dramatic','none'),
(4623,'fr','Les bulletins de vote tombent en vrac.','Les pièces tombent en vrac.','compter les votes','déposer son bulletin','chill','none'),
(4625,'fr','Elle vote comme une championne !','Il vote comme un champion !','voter avec joie','voter par correspondance','dramatic','exaggeration'),
(4629,'fr','Des dunes interminables, un minuscule marcheur.','Des dunes interminables, un minuscule chameau.','des rangées de dunes interminables','une file de voitures interminable','dramatic','none'),
(4630,'fr','Il a dessiné la coupe de cheveux en premier.','Il a dessiné la barbe en premier.','une coupe de cheveux dégradée','coupe longue sur les côtés','chill','none'),
(4634,'fr','Elle a enfin atteint la ville !','Elle a enfin atteint le lac !','atteindre la ville côtière','attraper son téléphone','dramatic','exclamation'),
(4639,'fr','Le savon liquide est bleu-vert.','Le savon liquide est rouge vif.','du savon liquide qui coule','peinture liquide sur un pinceau','chill','none'),
(4643,'fr','La production avance bien !','La production avance mal !','une production de film maison','une chaîne de production d''usine','dramatic','exclamation'),
(4647,'fr','Il a trop tourné sur lui-même. Direction le sol.','Il a trop couru. Direction le sol.','tourner sur une chaise de bureau','tourner sur soi-même en boîte','slang','understatement'),
(4652,'fr','Elle affronte un homme au bras de fer.','Elle affronte un enfant au bras de fer.','faire un bras de fer','participer à un concours de cuisine','chill','none'),
(4653,'fr','Il a laissé la boue sur le paillasson. Enfin, presque.','Il a laissé la neige sur le paillasson. Enfin, presque.','des bottes couvertes de boue','boue sur la table de cuisine','ironic','understatement'),
(4664,'fr','Elle compte la dose goutte à goutte.','Elle compte la dose cuillère par cuillère.','une dose d''huile jaune','une dose de sirop','nerd','none'),
(4668,'fr','Elle renifle le linge.','Elle repasse le linge.','renifler du linge propre','renifler l''air marin','chill','none'),
(4672,'fr','Des roseaux poussent sur les deux rives.','Des arbres poussent sur les deux rives.','grands roseaux au bord de l''eau','un panier en roseau tressé','nerd','none'),
(4690,'fr','Son lieu de travail, c''est un box.','Son lieu de travail, c''est une cuisine.','un lieu de travail animé','lieu de travail à la ferme','business','none'),
(4695,'fr','C''est lui qui a semé tout ce chaos.','C''est lui qui a rangé tout ce chaos.','le chaos par terre','le chaos dans la cuisine','gossip','blaming_someone'),
(4697,'fr','Il a un départ fulgurant !','Il a un départ lent !','un départ en starting-blocks','le début des cours','dramatic','exaggeration'),
(4705,'fr','Toute la ville adore le groupe !','Toute la ville déteste le groupe !','un groupe jouant dans la rue','un groupe dans un stade','gossip','exaggeration'),
(4710,'fr','Ils balancent les bras.','Ils balancent les jambes.','bras levés au-dessus de la tête','bras croisés sur la poitrine','business','none'),
(4722,'fr','Même les femmes en lunettes de soleil s''évanouissent !','Même les femmes en lunettes de soleil dansent !','des femmes en lunettes de soleil','lunettes de soleil à la plage','dramatic','exaggeration'),
(4726,'fr','Le fermier arrache des carottes.','Le fermier arrache des oignons.','un fermier heureux au crépuscule','un fermier fatigué à l''aube','chill','none'),
(4727,'fr','Ce père n''est jamais fatigué.','Cette mère n''est jamais fatiguée.','un père jouant à la balle','un père devant la télé','gossip','exaggeration'),
(4734,'fr','Elle prend soin de son amie.','Elle prend soin d''un chien.','des soins tendres sur le canapé','des soins de la peau','chill','none'),
(4735,'fr','Elle donne des coups de poing.','Elle bloque des coups de poing.','coups de poing dans un bouclier','un bol de punch aux fruits','chill','none'),
(4742,'fr','Elle est super forte avec les cordes !','Elle est super forte sur le vélo !','des bras et des jambes forts','un café bien fort','flirt','exclamation'),
(4746,'fr','Le jet survole les photographes !','L''oiseau survole les photographes !','photographes au bord de la piste','des photographes à un mariage','dramatic','exclamation'),
(4761,'fr','Du bacon sur un lac gelé !','Du bacon sur une plage de sable !','du bacon frit sur la glace','du bacon dans un sandwich','slang','exclamation'),
(4773,'fr','La musique a lancé un rassemblement.','La musique a lancé une bagarre.','un rassemblement autour d''un musicien','un rassemblement familial à la maison','chill','none'),
(4795,'fr','Elle a cuit des cookies au four. Meilleure journée !','Elle a cuit une tarte au four. Meilleure journée !','des cookies cuits au four','tartes aux pommes cuites au four','dramatic','exclamation'),
(4804,'fr','Ils visitent une ville bleue.','Ils visitent une ville rouge.','visiter une ville bleue','en tournée avec des rockeurs','chill','none'),
(4813,'fr','Le port est animé.','Le port est vide.','un port animé à l''aube','un port dans la tempête','chill','none'),
(4833,'fr','Il longe la côte en skate comme si de rien n''était.','Il longe la côte à vélo comme si de rien n''était.','en skate sur la route côtière','naviguer le long de la côte','flirt','cliche'),
(4835,'fr','Une course-poursuite en pleine ville !','Un défilé en pleine ville !','une rue en ville, la nuit','une rue en ville, à midi','dramatic','exclamation'),
(4844,'fr','Elle a coupé la citrouille par la moitié.','Elle a coupé le gâteau par la moitié.','une citrouille coupée par la moitié','moitié d''une tarte à la citrouille','chill','none'),
(4867,'fr','Elle lève les deux pouces.','Elle baisse les deux pouces.','deux pouces levés','un pouce sur une guitare','chill','none'),
(4879,'fr','Elle soulève une voiture dans cette compétition !','Elle soulève un vélo dans cette compétition !','une compétition de force féminine','une compétition de chant télévisée','dramatic','exclamation'),
(4891,'fr','Tout le campus se penche !','Tout le campus saute !','étudiants sur la pelouse du campus','un campus sous la neige','dramatic','exaggeration'),
(4917,'fr','Rouge a tiré sur bleu. Touché !','Bleu a tiré sur rouge. Touché !','tirer sur un joueur au paintball','tirer au panier','dramatic','exclamation'),
(4944,'fr','Projecteurs, roses et robe de bal dorée !','Projecteurs, roses et robe de bal rouge !','longue robe de bal or pâle','essayer une robe de mariée','dramatic','exclamation'),
(4946,'fr','Sa queue de cheval danse aussi.','Son écharpe danse aussi.','queue de cheval qui se balance','queue de cheval sous une casquette','chill','exaggeration'),
(4948,'fr','Maquillage avec vue sur la ligne d''horizon de la ville. La classe.','Maquillage avec vue sur la plage. La classe.','la ligne d''horizon derrière elle','ligne d''horizon au crépuscule','gossip','none'),
(4949,'fr','Sommets enneigés : paysage de dingue.','Dunes de sable : paysage de dingue.','paysage de montagne vu du sommet','un paysage vu d''un train','chill','none'),
(4951,'fr','Il est à la maison, et le chien est fou de joie !','Il est à la maison, et le chat est fou de joie !','retrouver le chien à la maison','quitter la maison pour le boulot','dramatic','exclamation'),
(4956,'fr','Elle va à la réception.','Elle va à la cuisine.','la réception de l''auberge','une réception de mariage','chill','none'),
(4978,'fr','Le cuisinier joue avec le feu !','Le cuisinier joue avec la glace !','un cuisinier au wok','un cuisinier au grill','slang','cliche'),
(4981,'fr','Tout le monde a eu le vaccin. Youpi !','Personne n''a eu le vaccin. Youpi !','vaccins dans le haut du bras','un vaccin dans la jambe','dramatic','exclamation'),
(4990,'fr','Il utilise un lourd fer à repasser.','Il utilise un lourd marteau.','lourd fer à repasser à vapeur','une poêle en fonte','chill','none'),
(5006,'fr','Sa bouilloire bosse dur.','Son grille-pain bosse dur.','l''eau qui bout dans la bouilloire','une bouilloire sur le feu','chill','exaggeration'),
(5019,'fr','Elle fait griller du bœuf.','Elle fait griller du poisson.','des tranches de bœuf grillé','burger de bœuf et frites','chill','none'),
(5023,'fr','Il acclame un avion !','Il acclame un train !','un avion qui passe en rase-mottes','un avion qui décolle','dramatic','exclamation'),
(5056,'fr','La femme de chambre a fait un cygne en serviette.','La femme de chambre a fait un chien en serviette.','femme de chambre pliant des serviettes','femme de chambre dans un château','chill','none'),
(5057,'fr','Son courrier s''envole partout !','Son argent s''envole partout !','courrier de la boîte aux lettres','du courrier sur un ordinateur','dramatic','exaggeration'),
(5060,'fr','Il n''y a que des hommes dans cette vidéo.','Il n''y a que des filles dans cette vidéo.','des hommes de tous âges','des hommes en équipe de foot','gossip','none'),
(5078,'fr','Il prépare des tacos au porc.','Il prépare des tacos au poisson.','trancher du porc rôti','côtes de porc à la poêle','chill','none'),
(5089,'fr','Cette mère gère tout.','Ce père gère tout.','une mère faisant sauter des crêpes','une mère achetant des crêpes','chill','exaggeration'),
(5090,'fr','Une chambre de bébé douillette pleine de jouets.','Une cuisine douillette pleine de jouets.','chambre de bébé avec berceau','une pépinière de plantes','chill','none'),
(5099,'fr','Tout le monde ajoute une photo !','Tout le monde ajoute un timbre !','des photos sur un planisphère','un album photo','gossip','none'),
(5101,'fr','Sur ce trajet, c''est la nausée qui gagne.','Sur ce vol, c''est la nausée qui gagne.','la nausée sur un ferry','la nausée en voiture','dramatic','exaggeration'),
(5106,'fr','Moulin à vent, tulipes, stroopwafel : c''est fait.','Moulin à vent, tulipes, part de pizza : c''est fait.','un moulin à vent qui tourne','moulin à vent sur une plage','ironic','cliche'),
(5118,'fr','La lumière du soleil l''inonde. Quel matin !','La pluie l''inonde. Quel matin !','lumière du soleil par une fenêtre','lumière du soleil entre les arbres','dramatic','none'),
(5132,'fr','Il verse le mélange.','Il remue le mélange.','mélange à crêpes dans la poêle','un mélange de couleurs','chill','none'),
(5143,'fr','Les soldats font la paix.','Les soldats font la guerre.','faire la paix','paix et calme à la maison','chill','none'),
(5165,'fr','La rivière est pleine de plastique.','La rivière est pleine de poissons.','du plastique dans la rivière','plastique dans un bac de tri','dramatic','none'),
(5166,'fr','Le tram est sur les voies.','Le tram est sur l''herbe.','voies de tram dans les pavés','voies de tram dans un tunnel','chill','none'),
(5168,'fr','La fournée de tartelettes, ça passe.','La fournée de pain, ça passe.','fournée de tartelettes à la crème','une fournée de cookies','chill','understatement'),
(5193,'fr','De la crème sur l''éruption cutanée ? Ça pique !','De la crème sur la brûlure ? Ça pique !','crème sur une éruption rouge','une éruption sur sa joue','gossip','exclamation'),
(5199,'fr','Recette suivie étape par étape.','Carte suivie étape par étape.','suivre une recette manuscrite','suivre un ami en ligne','business','none'),
(5201,'fr','L''eau reflète tout, même le volcan.','L''eau reflète tout, même la lune.','un volcan reflété dans l''eau','un visage dans un miroir','business','none'),
(5213,'fr','Un train rouge est sur la voie ferrée.','Un tram rouge est sur la voie ferrée.','voie ferrée le long d''un quai','une voie ferrée en montagne','chill','none'),
(5216,'fr','Elle fait une promenade tranquille.','Elle fait une baignade tranquille.','promenade devant des étals de fleurs','une promenade sur la plage','chill','none'),
(5221,'fr','Le sentier serpente jusqu''en haut des collines.','La rivière serpente jusqu''en haut des collines.','un sentier qui serpente en montagne','une rivière serpentant vers la vallée','chill','none'),
(5222,'fr','Elle monte des marches en pierre.','Elle monte des marches en bois.','marches en pierre vers un sommet','marches en pierre vers une plage','chill','none'),
(5225,'fr','Elle finit loin devant !','Elle finit loin derrière !','finir une course','finir ses devoirs','slang','none'),
(5237,'fr','Du thé sous un ciel plein d''étoiles.','Du thé sous un ciel plein d''oiseaux.','étoiles sur un camp du désert','des étoiles au-dessus d''une ville','chill','none'),
(5238,'fr','Selfie sur une dune rouge ? Iconique.','Selfie sur une dune blanche ? Iconique.','un selfie sur une dune rouge','virée en buggy dans les dunes','slang','none'),
(5240,'fr','Les ailes du faucon sont déployées.','Les ailes du faucon sont repliées.','déployer les deux ailes','ailes de poulet dans une assiette','chill','none'),
(5241,'fr','Elle se glisse dans une chambre hyperbare.','Il se glisse dans une chambre hyperbare.','une chambre hyperbare lumineuse','un concert de musique de chambre','chill','none'),
(5244,'fr','Les camarades de classe ont conclu un accord.','Les profs ont conclu un accord.','deux camarades de classe se retrouvant','la fête d''un camarade de classe','chill','guessing'),
(5247,'fr','Nonna est furieuse à cause des empreintes de pas.','Nonna est furieuse à cause du vase cassé.','des empreintes de pas boueuses','empreintes de pas dans un jardin','gossip','blaming_someone'),
(5258,'fr','Bar sur le toit, soirée shaker !','Bar en sous-sol, soirée shaker !','bar sur un toit au crépuscule','une barre de chocolat','slang','exclamation'),
(5303,'fr','Des flocons de neige sur sa moufle.','Des flocons de neige sur sa chaussure.','flocon de neige sur une moufle','flocon de neige sur une fenêtre','chill','none'),
(5310,'fr','Un fils aide à réparer la voiture.','Un fils aide à laver la voiture.','un fils tenant une clé plate','un fils qui lave la voiture','chill','none'),
(5313,'fr','Des enseignes néon couvrent chaque mur.','Des enseignes en papier couvrent chaque mur.','des enseignes néon lumineuses','des néons en boîte de nuit','chill','none'),
(5317,'fr','Ses volants volent partout !','Ses chaussures volent partout !','des couches de volants rouges','volants sur un col de chemise','dramatic','exclamation'),
(5325,'fr','Les époux ont signé un document.','Les époux ont brûlé un document.','des époux qui signent des papiers','époux qui se disputent chez eux','business','none'),
(5326,'fr','L''entraîneur lui bande la cheville.','L''entraîneur lui bande le poignet.','un entraîneur qui aide une gymnaste','entraîneur qui crie sur les joueurs','chill','none'),
(5331,'fr','Sa forme physique ? Elle écrase des pastèques !','Sa forme physique ? Elle écrase des noix de coco !','forme physique au bar de plage','une appli de remise en forme','slang','exaggeration'),
(5342,'fr','Du glaçage sur sa langue. Miam !','Du ketchup sur sa langue. Miam !','du glaçage sur la langue','se brûler la langue au thé','slang','exclamation'),
(5355,'fr','Même le chat imite l''entraîneur !','Même le chien imite l''entraîneur !','un entraîneur dans le parc','dresseur de chiens avec des friandises','gossip','exclamation'),
(5356,'fr','Yoga sur un toit au coucher du soleil : le rêve.','Yoga sur la plage au coucher du soleil : le rêve.','du yoga sur un toit','cours de yoga en salle','slang','exaggeration'),
(5358,'fr','Elle jette un coup d''œil entre les livres.','Elle jette un coup d''œil entre les stores.','coup d''œil par une fente','coup d''œil dans un livre','gossip','none'),
(5367,'fr','Elle s''en fourre plein la bouche !','Elle s''en fourre plein le sac !','fourrer un cheeseburger dans sa bouche','farcir une dinde','gossip','exclamation'),
(5398,'fr','Les gens forment une chaîne humaine.','Les gens forment une tour humaine.','chaîne humaine autour de la Terre','une chaîne en or','chill','none'),
(5409,'fr','Elle montre ses dents.','Elle montre sa langue.','dents de devant en gros plan','une dent de devant manquante','chill','none'),
(5424,'fr','Ils ont signé le traité.','Ils ont déchiré le traité.','poignée de main scellant un traité','déchirer un traité','business','none'),
(5429,'fr','Elle leur fait confiance, les yeux fermés.','Elle leur fait confiance, les yeux ouverts.','faire confiance à l''équipe','faire confiance à un internaute','chill','none'),
(5441,'fr','L''oncle a laissé sa nièce gagner.','L''oncle a laissé son neveu gagner.','bras de fer avec un oncle','boxe avec un oncle','gossip','guessing'),
(5449,'fr','Elle est enfin dans l''embrasure de la porte.','Elle est enfin dans le jardin.','une embrasure de porte en pierre','embrasure de porte avec un rideau','chill','none'),
(5458,'fr','La vitamine pétille comme une folle !','Le lait pétille comme un fou !','un comprimé de vitamine effervescent','un bonbon vitaminé qui fond','slang','exclamation'),
(5470,'fr','Marche rapide au centre-ville, en costume.','Marche rapide au centre-ville, en jean.','aller au travail au centre-ville','un rooftop du centre-ville','business','none'),
(5486,'fr','Il arrose le pot de fleurs.','Il peint le pot de fleurs.','pot de fleurs sur le rebord','un pot de fleurs cassé','chill','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
