begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(1,'fr','Sa « petite » pause dure beaucoup trop longtemps.','Sa « petite » course dure beaucoup trop longtemps.','une petite pause téléphone','une petite pause café','ironic','understatement'),
(2,'fr','Elle a tellement de certificats !','Elle a tellement de médailles !','montrer ses certificats','imprimer ses certificats','dramatic','exclamation'),
(3,'fr','Sa classe est déchaînée !','Sa classe dort !','une classe incontrôlable','un voyage de classe à l''étranger','dramatic','exclamation'),
(6,'fr','Un seul coussin, ça ne suffit pas.','Une seule chaise, ça ne suffit pas.','une pile de coussins','une pile de couvertures','ironic','exaggeration'),
(7,'fr','Jour de remise des diplômes pour lui.','Jour de remise des diplômes pour elle.','une cérémonie de remise des diplômes','un cadeau de remise des diplômes','chill','none'),
(8,'fr','Elle accuse la carte-clé. Mauvaise porte.','Elle accuse la valise. Mauvaise porte.','passer la carte-clé','perdre la carte-clé','ironic','blaming_someone'),
(9,'fr','C''est un laboratoire très animé.','C''est une cuisine très animée.','travailler dans un laboratoire','nettoyer un laboratoire','nerd','none'),
(10,'fr','Une feuille, c''est un parapluie gratuit !','Une feuille, c''est une couverture gratuite !','une feuille verte géante','une grenouille verte géante','low_iq','cheap_quality'),
(11,'fr','Cette bibliothèque est immense !','Cette bibliothèque est minuscule !','une immense bibliothèque ancienne','une petite bibliothèque d''école','dramatic','exaggeration'),
(13,'fr','Sa serviette est une œuvre d''art !','Son gâteau est une œuvre d''art !','plier une serviette','une serviette par terre','dramatic','exaggeration'),
(14,'fr','On pose une fleur sur la page.','On pose une photo sur la page.','une page avec des fleurs','une page de journal','chill','none'),
(15,'fr','Un cachet et il va bien.','Un café et il va bien.','avaler un cachet blanc','un cachet pour dormir','chill','exaggeration'),
(16,'fr','Elle fait une présentation.','Elle donne un concert.','faire une présentation','regarder une présentation','chill','none'),
(17,'fr','Le projet : un abri en bois.','Le projet : un bateau en bois.','un grand projet d''abri','un projet scolaire sur papier','business','none'),
(18,'fr','Elle lave les racines.','Elle coupe les racines.','rincer les racines','les racines d''un grand arbre','chill','none'),
(19,'fr','Il a enfin trouvé une règle !','Il a enfin trouvé un crayon !','tracer avec une règle','tracer avec un compas','dramatic','exclamation'),
(20,'fr','Emploi du temps chargé, mais le sommeil gagne !','Emploi du temps chargé, mais le boulot gagne !','un emploi du temps chargé','un horaire de bus','dramatic','exclamation'),
(21,'fr','Bienvenue dans mon école, frérot.','Bienvenue dans mon bureau, frérot.','la visite de mon école','la visite de mon bureau','slang','none'),
(22,'fr','Le scientifique adore les graphiques.','L''étudiant adore les graphiques.','un scientifique avec un porte-bloc','un scientifique avec un microscope','gossip','guessing'),
(23,'fr','Elle prononce un discours officiel.','Elle donne un petit concert.','un discours émouvant','une bulle de dialogue','business','none'),
(24,'fr','Sa cuillère a vidé tout le bol !','Sa fourchette a vidé tout le bol !','une cuillère pleine de soupe','une cuillère pleine de sucre','low_iq','exaggeration'),
(25,'fr','Son agrafeuse ne lâche jamais rien !','Son imprimante ne lâche jamais rien !','une agrafeuse rouge','une agrafeuse cassée','dramatic','exaggeration'),
(26,'fr','Sa paille carbure grave !','Sa cuillère carbure grave !','une paille pliable à rayures','un chapeau de paille','slang','exclamation'),
(27,'fr','Cette étudiante met des glaçons dans son café.','Cette étudiante réchauffe son café.','une étudiante avec un café glacé','une étudiante avec une soupe chaude','chill','none'),
(28,'fr','L''école propose plein de matières.','L''école propose deux matières.','plein de matières scolaires','l''objet d''un e-mail','business','none'),
(29,'fr','Son télescope montre un météore !','Son télescope montre une fusée !','un télescope sur trépied','un télescope sur un bateau','dramatic','exclamation'),
(30,'fr','Ce manuel ne finit jamais.','Ce film ne finit jamais.','un manuel très épais','un manuel très fin','dramatic','exaggeration'),
(31,'fr','Cinquième semaine : l''université est vide.','Cinquième semaine : l''université est pleine.','un hall d''université vide','une bibliothèque universitaire vide','gossip','none'),
(32,'fr','Ils jouent à un jeu de mots.','Ils jouent à un jeu de cartes.','un jeu de mots rapide','un jeu de cartes rapide','chill','none'),
(33,'fr','Le café aggrave la douleur !','La glace aggrave la douleur !','une douleur à la mâchoire','une douleur dans le dos','dramatic','exclamation'),
(35,'fr','L''acteur mérite un Oscar !','Le chanteur mérite un Oscar !','un acteur sur le tournage','un acteur sur une affiche','dramatic','exclamation'),
(36,'fr','Elle adore tellement ce chat !','Elle adore tellement ce chien !','adorer son chat roux','adorer son chien roux','dramatic','exclamation'),
(37,'fr','L''équipe avance vers son objectif.','L''équipe avance vers la cabane.','avancer vers le sommet','avancer vers la finale','chill','none'),
(38,'fr','Gros trafic à l''aéroport aujourd''hui.','Aucun trafic à l''aéroport aujourd''hui.','une piste d''aéroport animée','une boutique d''aéroport','business','none'),
(39,'fr','Une ambulance se range sur le côté.','Un taxi se range sur le côté.','une ambulance dans la rue','une ambulance sur l''autoroute','chill','none'),
(40,'fr','Elle déteste la réponse.','Elle adore la réponse.','une réponse sur une carte','une réponse d''un ami','dramatic','none'),
(41,'fr','Juste une petite dispute.','Juste un petit bisou.','une dispute à cause d''une image','une dispute à cause de l''argent','ironic','understatement'),
(42,'fr','Cet examen est trop dur pour lui.','Cet examen est trop facile pour lui.','abandonner l''examen','réussir l''examen','dramatic','none'),
(44,'fr','Tant de colère pour un sac de fleurs !','Tant de colère pour un sac de pommes !','la colère au marché aux fleurs','la colère dans un embouteillage','dramatic','exclamation'),
(46,'fr','Cette pomme a l''air trop croquante !','Cette poire a l''air trop croquante !','croquer une pomme rouge','cuire une tarte aux pommes','slang','none'),
(47,'fr','L''arène est blindée. De ouf !','L''arène est vide. De ouf !','une arène couverte bondée','une arène couverte vide','slang','exclamation'),
(48,'fr','Il est arrivé et il est trop content !','Il est arrivé et il est trop triste !','arriver à un hôtel de plage','arriver au bureau','dramatic','exclamation'),
(49,'fr','Sa flèche a touché le mille.','Sa flèche a touché l''arbre.','une flèche dans le mille','une flèche sur le panneau','chill','none'),
(50,'fr','Les pots ressemblent à des gâteaux !','Les pots ressemblent à de la soupe !','remplir des petits pots en verre','ouvrir des petits pots en verre','low_iq','exclamation'),
(51,'fr','Presser du slime, c''est trop satisfaisant.','Presser de la pâte à modeler, c''est trop satisfaisant.','presser du slime coloré','presser un citron','slang','none'),
(52,'fr','L''assistant fait tout.','Le mannequin fait tout.','un assistant serviable','un vendeur en boutique','ironic','exaggeration'),
(53,'fr','C''est de l''athlétisme au top niveau.','C''est de la natation au top niveau.','l''athlétisme au stade','l''athlétisme à la télé','business','cliche'),
(55,'fr','Elle a remporté la vente aux enchères.','Elle a perdu la vente aux enchères.','enchérir à une vente aux enchères','une vente aux enchères en ligne','gossip','none'),
(56,'fr','Des feuilles d''automne partout !','De la neige d''automne partout !','sauter dans les feuilles d''automne','des feuilles d''automne sur un arbre','slang','exclamation'),
(57,'fr','Ils adorent le rang du fond !','Ils adorent le premier rang !','assis au fond','le fond de la scène','dramatic','exclamation'),
(58,'fr','Son sac à dos est énorme, sans blague.','Sa valise est énorme, sans blague.','remplir un sac à dos orange','un sac à dos à l''école','slang','exaggeration'),
(61,'fr','Pourquoi ils marchent en arrière ?','Pourquoi ils courent en arrière ?','marcher en arrière dans un parc','tomber en arrière dans un parc','low_iq','guessing'),
(62,'fr','La pomme s''est échappée du sac !','Le pain s''est échappé du sac !','préparer un sac de pique-nique','un sac de courses en plastique','low_iq','exaggeration'),
(66,'fr','Cuisson au four en cours : du pain.','Cuisson au four en cours : un gâteau.','la cuisson d''une miche dorée','la cuisson de cookies','chill','none'),
(67,'fr','Il a appris un nouveau tour avec une banane.','Il a appris un nouveau tour avec une pomme.','éplucher une banane','une banane dans un smoothie','chill','none'),
(68,'fr','Un bandage pour son poignet.','Un bandage pour son genou.','un bandage élastique au poignet','un bandage sur la tête','chill','none'),
(69,'fr','La barre d''haltères a perdu. Elle a gagné !','La barre d''haltères a gagné. Elle a perdu !','soulever une lourde barre d''haltères','tordre une lourde barre d''haltères','dramatic','exclamation'),
(70,'fr','Ce barbier est une légende !','Ce boulanger est une légende !','un barbier qui taille une barbe','un barbier qui balaie le sol','slang','exaggeration'),
(71,'fr','L''écorce de bouleau, c''est comme du papier.','L''écorce de pin, c''est comme du papier.','peler de l''écorce de bouleau','le gros aboiement d''un chien','nerd','none'),
(72,'fr','Reine du basketball, quel dunk !','Reine du basketball, quel raté !','un dunk au basketball','le basketball à la télé','slang','exaggeration'),
(74,'fr','Une chauve-souris vole au-dessus du lac.','Une chauve-souris vole au-dessus de la ville.','une chauve-souris au coucher du soleil','une batte qui frappe une balle','chill','none'),
(76,'fr','C''est la faute des vieilles piles.','C''est la faute de la vieille ampoule.','mettre des piles neuves','une batterie de voiture','ironic','blaming_someone'),
(79,'fr','L''ours chasse un poisson !','L''ours chasse un canard !','un ours dans une rivière','un ours dans un zoo','dramatic','exclamation'),
(80,'fr','Dix ans pour faire pousser cette barbe !','Dix jours pour faire pousser cette barbe !','une longue barbe noire','une courte barbe grise','gossip','exaggeration'),
(81,'fr','La beauté pure à Santorin.','La beauté pure à Venise.','la beauté du coucher de soleil','un salon de beauté en ville','chill','none'),
(82,'fr','L''abeille retourne au boulot.','La fourmi retourne au boulot.','une abeille sur une fleur','une abeille dans un bocal','business','guessing'),
(83,'fr','La mousse de cette bière est de première qualité.','La mousse de ce lait est de première qualité.','verser une bière dorée','une bière au match de foot','business','none'),
(84,'fr','La ceinture a sauvé son pantalon !','La corde a sauvé son pantalon !','mettre une ceinture en cuir','enlever une ceinture en cuir','dramatic','exclamation'),
(85,'fr','Le gamin l''a trahi !','Le chien l''a trahi !','un fermier trahi','un gamin trahi','dramatic','exclamation'),
(86,'fr','Cette addition est beaucoup trop longue !','Cette addition est beaucoup trop courte !','une très longue addition','une addition dans un portefeuille','slang','exaggeration'),
(87,'fr','L''oiseau donne un concert !','Le chat donne un concert !','un oiseau qui chante fort','un oiseau en cage','dramatic','exaggeration'),
(88,'fr','Le chien veut un selfie.','Le chat veut un selfie.','un chien près de la caméra','un chien près de la porte','chill','guessing'),
(90,'fr','Attends, les chiots savent danser ?!','Attends, les chiots savent voler ?!','un chiot dans le bain','un chiot dans la neige','low_iq','exclamation'),
(92,'fr','Une couverture, deux personnes.','Une couverture, trois personnes.','partager une grande couverture','partager une grande pizza','flirt','understatement'),
(93,'fr','C''est le mixeur qui a fait ça !','C''est le grille-pain qui a fait ça !','un smoothie dans un mixeur','un mixeur plein de soupe','low_iq','blaming_someone'),
(94,'fr','Il a cligné des yeux en premier. Elle a gagné !','Elle a cligné des yeux en premier. Il a gagné !','cligner des yeux en premier','cligner des yeux au soleil','dramatic','exclamation'),
(95,'fr','Elle met du fard à joues rose.','Elle met du fard à joues bleu.','appliquer du fard à joues rose','rougir de honte','chill','none'),
(96,'fr','Elle embarque dans l''avion.','Elle embarque dans le train.','embarquer dans l''avion','embarquer dans le bus','chill','none'),
(98,'fr','Elle lit dans un hamac.','Elle dort dans un hamac.','lire dans un hamac','dormir dans un hamac','chill','none'),
(99,'fr','Elle a fini tout le livre !','Elle a fini tout le gâteau !','lire un livre vert','un livre dans un train','dramatic','exclamation'),
(100,'fr','Ces bottes adorent la boue.','Ces sandales adorent la boue.','des bottes dans la boue','des bottes en magasin','slang','exaggeration'),
(101,'fr','Pff. Elle s''ennuie à mourir.','Pff. Il s''ennuie à mourir.','s''ennuyer à force d''attendre','s''ennuyer à une fête','dramatic','none'),
(102,'fr','Niveau d''ennui : une chaussette mouillée sur la tête.','Niveau d''ennui : un chapeau mouillé sur la tête.','l''ennui à la laverie','l''ennui en classe','low_iq','exaggeration'),
(103,'fr','Soirée à la laverie. Pff !','Soirée à la bibliothèque. Pff !','attendre à la laverie','travailler à la laverie','dramatic','exclamation'),
(104,'fr','Une pierre du fond de la mer !','Un coquillage du fond de la mer !','une pierre du fond','le fond d''un verre','dramatic','exclamation'),
(105,'fr','Son arc ne rate jamais.','Son arc rate toujours.','bander un arc en bois','un arc et une épée','chill','exaggeration'),
(106,'fr','Il vise la botte de foin.','Il vise un arbre.','viser avec un arc en bambou','viser avec un pistolet à eau','chill','none'),
(107,'fr','Le bol, c''est sa tasse maintenant.','La casserole, c''est sa tasse maintenant.','boire dans un bol','laver un bol bleu','low_iq','guessing'),
(110,'fr','Le chat « aide » avec les cartons.','Le chien « aide » avec les cartons.','un grand carton rempli','une boîte de chocolats','ironic','understatement'),
(111,'fr','La boxe la rend trop heureuse.','Le tennis la rend trop heureuse.','la boxe avec des gants rouges','ranger de vieux habits en cartons','slang','none'),
(112,'fr','La petite fille est courageuse, ses parents beaucoup moins.','Le petit garçon est courageux, ses parents beaucoup moins.','une petite fille courageuse','un chevalier courageux en armure','chill','understatement'),
(114,'fr','Le pain est encore tout chaud.','Le pain est encore tout congelé.','du pain chaud sorti du four','du pain du supermarché','slang','none'),
(115,'fr','Le coq est venu au petit-déjeuner aussi.','Le chien est venu au petit-déjeuner aussi.','le petit-déjeuner au jardin','le petit-déjeuner au lit','chill','guessing'),
(116,'fr','Casser des trucs, c''est de l''art maintenant !','Peindre des trucs, c''est de l''art maintenant !','casser des carreaux bleus','casser une fenêtre','low_iq','exclamation'),
(117,'fr','Ils ont fait une mosaïque d''assiettes.','Ils ont fait une mosaïque de tasses.','une mosaïque de fleur en assiettes','une mosaïque en carreaux de verre','chill','none'),
(118,'fr','C''est assemblé, on se tape dans la main !','C''est assemblé, câlin collectif !','assembler un bac surélevé','un grand immeuble de bureaux','dramatic','exclamation'),
(119,'fr','Ampoule changée. Mission accomplie.','Fusible changé. Mission accomplie.','visser une ampoule neuve','un bulbe dans le jardin','business','none'),
(120,'fr','Ce burger se mange à deux mains !','Cette pizza se mange à deux mains !','un burger au fromage bien haut','un burger dans une boîte','slang','exclamation'),
(121,'fr','Il a brûlé la crêpe. Oups !','Il a brûlé le pain grillé. Oups !','une crêpe brûlée toute noire','un steak brûlé tout noir','dramatic','exclamation'),
(122,'fr','Ils attendent une éternité à l''arrêt de bus.','Ils attendent une éternité à la gare.','attendre à un arrêt de bus','attendre à une station de taxis','dramatic','exaggeration'),
(123,'fr','Un oiseau est sorti du buisson !','Un chat a bondi hors du buisson !','cueillir dans les buissons','se cacher derrière les buissons','dramatic','exclamation'),
(124,'fr','Elle étale une brique de beurre.','Elle étale une brique de fromage.','étaler du beurre sur du pain','étaler une nappe de pique-nique','ironic','exaggeration'),
(125,'fr','Le beurre a cassé le pain !','La confiture a cassé le pain !','du beurre trop dur à étaler','du beurre dans une poêle chaude','dramatic','blaming_someone'),
(126,'fr','Il a besoin d''aide pour les boutons.','Il a besoin d''aide pour les lacets.','une rangée de boutons de travers','appuyer sur un bouton d''ascenseur','chill','none'),
(127,'fr','Ce cactus pique beaucoup trop !','Ce palmier pique beaucoup trop !','des épines de cactus pointues','un cactus en pot','slang','exclamation'),
(128,'fr','Son gâteau d''anniversaire a des baies.','Son gâteau d''anniversaire a des bananes.','un gâteau d''anniversaire à la crème','un gâteau de mariage au chocolat','chill','none'),
(129,'fr','Cinq plus trois ? Il lui faut une calculatrice.','Neuf plus neuf ? Il lui faut une calculatrice.','une grosse calculatrice de bureau','une calculatrice sur un téléphone','ironic','understatement'),
(130,'fr','Un cœur sur son calendrier ? L''amour !','Une étoile sur son calendrier ? L''amour !','un cœur sur le calendrier','un calendrier sur le bureau','slang','guessing'),
(131,'fr','C''est le meilleur appel de tous les temps.','C''est le pire appel de tous les temps.','un appel joyeux','un appel à l''aide','dramatic','exaggeration'),
(132,'fr','Les calories du gâteau gagnent !','Les calories de la salade gagnent !','brûler des calories','compter les calories sur l''étiquette','slang','exaggeration'),
(133,'fr','Le chameau fait une pause.','Le chameau prend un bain.','un chameau dans le désert','un chameau dans la neige','business','none'),
(134,'fr','Camping dans une forêt de pins, trop bien.','Camping sur une plage de sable, trop bien.','faire du camping en forêt','faire du camping dans le jardin','slang','none'),
(135,'fr','Ses plans sont annulés. Trop bien !','Son vol est annulé. Trop bien !','annuler ses plans ce soir','annuler un abonnement à la salle','ironic','exclamation'),
(136,'fr','Une bougie pour deux ? Trop mignon.','Une lampe pour deux ? Trop mignon.','une bougie sur la table','une bougie sur un gâteau','flirt','none'),
(137,'fr','Le canyon crie en retour !','La forêt crie en retour !','un canyon étroit','un canyon vu d''en haut','dramatic','exaggeration'),
(138,'fr','Une casquette, enfin de l''ombre.','Un arbre, enfin de l''ombre.','une casquette corail pour l''ombre','une capsule sur une bouteille','chill','none'),
(140,'fr','Leur nouveau tapis est trop doux !','Leur nouveau canapé est trop doux !','un tapis vert tout doux','une couverture verte toute douce','dramatic','exclamation'),
(141,'fr','Cette carotte peut nourrir un cheval.','Cette pomme de terre peut nourrir un cheval.','une carotte géante','une pomme de terre géante','low_iq','exaggeration'),
(142,'fr','Il est immense ! Un vrai château.','Il est minuscule ! Un vrai château.','un château au bord d''un lac','un château sur une colline','dramatic','exclamation'),
(144,'fr','Il a attrapé la balle rouge.','Il a attrapé la balle bleue.','attraper une balle rouge','attraper un rhume','chill','none'),
(146,'fr','Cette chenille a un plan sur cinq ans.','Cet escargot a un plan sur cinq ans.','une chenille sur une feuille','une chenille dans un bocal','business','exaggeration'),
(147,'fr','Ils entrent dans une grotte sombre !','Ils entrent dans une maison sombre !','entrer dans une grotte sombre','dormir dans une grotte','dramatic','exclamation'),
(148,'fr','Ils fêtent ça !','Ils révisent !','fêter un anniversaire','fêter un mariage','dramatic','exclamation'),
(149,'fr','Sa lettre a été censurée. La honte !','Sa lettre a été brûlée. La honte !','une lettre censurée','un film censuré','gossip','exclamation'),
(150,'fr','Il mange ses céréales sans lait !','Il mange ses céréales sans bol !','des céréales sèches dans un bol','des céréales dans leur boîte','low_iq','exclamation'),
(151,'fr','Une chaîne ferme le portail.','Une corde ferme le portail.','une chaîne autour d''un portail','une chaîne autour d''un vélo','business','none'),
(152,'fr','Meilleure chaise du monde ! Tour complet !','Meilleur canapé du monde ! Tour complet !','une nouvelle chaise pivotante','une nouvelle chaise à bascule','slang','exaggeration'),
(154,'fr','Le chargeur était dans le tiroir !','Le chargeur était dans le frigo !','brancher un chargeur','un chargeur de voiture','dramatic','exclamation'),
(155,'fr','Le fromage s''étire à l''infini !','Le pain s''étire à l''infini !','du fromage fondu qui file','du fromage sur une pizza','dramatic','exaggeration'),
(156,'fr','Sa médaille est sur sa poitrine.','Sa médaille est sur sa tête.','les mains sur la poitrine','les mains sur la tête','chill','none'),
(157,'fr','Son chewing-gum est trop rose.','Son chewing-gum est trop vert.','faire des bulles de chewing-gum','un chewing-gum sous une table','slang','none'),
(158,'fr','Mâcher, c''est un vrai boulot !','Marcher, c''est un vrai boulot !','mâcher un caramel collant','mâcher un crayon','dramatic','exclamation'),
(159,'fr','La poule a pondu un œuf !','La poule a mangé un œuf !','une poule dans un poulailler','un poulet dans l''assiette','dramatic','exclamation'),
(160,'fr','Fait : la poule est dans son nid.','Fait : la cane est dans son nid.','une poule dans son nid','une poule qui construit un nid','nerd','none'),
(161,'fr','Le chien veut ce pilon de poulet.','Le chat veut ce pilon de poulet.','croquer un pilon de poulet','une baguette de batterie','ironic','guessing'),
(162,'fr','Il fait fondre du chocolat.','Il fait fondre du beurre.','faire fondre du chocolat','un gâteau d''anniversaire au chocolat','chill','none'),
(163,'fr','Il sait utiliser des baguettes maintenant !','Il sait utiliser une fourchette maintenant !','tenir des baguettes','casser des baguettes','dramatic','exclamation'),
(164,'fr','Un dumpling entier, en une bouchée !','Une pizza entière, en une bouchée !','un dumpling à soupe entier','faire des dumplings maison','gossip','exclamation'),
(165,'fr','Ils sont au cinéma.','Ils sont au zoo.','une salle de cinéma sombre','un ticket de cinéma','chill','none'),
(166,'fr','Ils forment un cercle parfait.','Ils forment une ligne parfaite.','un cercle humain','un cercle de chaises','chill','none'),
(167,'fr','Un bon citoyen vote et nettoie.','Un bon citoyen vote et danse.','un citoyen fier qui vote','un citoyen qui paie ses impôts','chill','cliche'),
(168,'fr','Ils ont obtenu leur citoyenneté !','Ils ont obtenu leurs médailles !','recevoir ses papiers de citoyenneté','perdre sa citoyenneté','dramatic','exclamation'),
(170,'fr','La femme de ménage a réglé ce bazar !','Le cuisinier a réglé ce bazar !','une femme de ménage d''hôtel','un laveur de vitres','slang','exclamation'),
(171,'fr','La réponse du garçon est correcte, pas celle de la fille.','La réponse de la fille est correcte, pas celle du garçon.','une réponse correcte','une orthographe correcte','gossip','none'),
(172,'fr','Ses crampons accrochent l''herbe mouillée.','Ses crampons accrochent le sable mouillé.','lacer ses crampons','lacer ses patins','chill','none'),
(173,'fr','Ils sont allongés sur une falaise.','Ils sont allongés sur une plage.','le bord d''une falaise','escalader une falaise','chill','none'),
(175,'fr','Ils accrochent une horloge.','Ils accrochent un tableau.','une horloge de cuisine ronde','une table de cuisine ronde','chill','none'),
(176,'fr','Charbon dedans, on allume !','Bois dedans, on allume !','mettre du charbon dans le poêle','une mine de charbon profonde','slang','exclamation'),
(177,'fr','Manteau enfilé. L''hiver peut toujours essayer.','Gants enfilés. L''hiver peut toujours essayer.','boutonner un long manteau','accrocher un long manteau','dramatic','cliche'),
(178,'fr','Le cocktail a un petit parapluie.','Le cocktail a un petit drapeau.','un cocktail orange en dégradé','une robe de cocktail','chill','none'),
(179,'fr','Le café, c''est de la magie !','L''eau, c''est de la magie !','du café à la cafetière italienne','du café de la machine','slang','exaggeration'),
(180,'fr','Trop froid ! Sa main dit non.','Trop chaud ! Sa main dit non.','un lac froid et gelé','une boisson froide','dramatic','exaggeration'),
(181,'fr','Le col relevé ? Jamais de la vie !','Les manches relevées ? Jamais de la vie !','un col relevé','le collier d''un chien','slang','exclamation'),
(182,'fr','Il a un peigne orange.','Il a un peigne bleu.','un peigne orange en plastique','un peigne pour chien','chill','none'),
(183,'fr','Son amie la console.','Son amie l''ignore.','consoler une amie en pleurs','consoler un bébé en pleurs','chill','none'),
(185,'fr','Il fait la navette en tram. Bof.','Il fait la navette en bateau. Bof.','faire la navette en tram','faire la navette à vélo','ironic','cliche'),
(186,'fr','Même le chien est au concert !','Même le chat est au concert !','un concert en plein air','une salle de concert','dramatic','exclamation'),
(187,'fr','La notice l''a complètement perdue.','La carte l''a complètement perdue.','perdue face à la notice','perdue dans les dates','ironic','blaming_someone'),
(188,'fr','La constitution dit non.','La constitution dit oui.','lire la constitution','écrire une nouvelle constitution','chill','none'),
(189,'fr','Trois voitures forment un convoi.','Cinq voitures forment un convoi.','un convoi de voitures de sport','un convoi de camions','chill','none'),
(190,'fr','Elle trempe son cookie.','Elle trempe son pain.','tremper un cookie','cuire un gâteau cookie','chill','none'),
(191,'fr','Il utilise un tire-bouchon.','Il utilise un couteau.','visser un tire-bouchon','un tire-bouchon dans un tiroir','chill','none'),
(192,'fr','Ils se cachent au coin de la rue !','Ils se cachent sous la table !','au coin de la rue','une épicerie du coin','dramatic','exclamation'),
(193,'fr','Quel fonctionnaire corrompu !','Quel fonctionnaire honnête !','un fonctionnaire corrompu','un fichier informatique corrompu','gossip','exclamation'),
(194,'fr','Le coton est tellement doux.','La laine est tellement douce.','cueillir du coton tout doux','acheter des draps en coton','chill','none'),
(196,'fr','Le courage l''a fait traverser !','Une tyrolienne l''a fait traverser !','traverser avec courage','le courage de sauter','dramatic','exclamation'),
(197,'fr','On trait la vache.','On trait la chèvre.','une vache avec une cloche','une vache avec un chapeau','chill','none'),
(198,'fr','Une crampe a stoppé sa course.','Une crampe a stoppé sa nage.','une crampe au mollet','une crampe à la main','chill','none'),
(200,'fr','Il tient de la crème au-dessus de sa tête !','Il tient de la soupe au-dessus de sa tête !','de la crème fouettée bien ferme','une crème pour le visage','low_iq','exaggeration'),
(201,'fr','Belles dents, crocodile !','Belles dents, lion !','un crocodile gueule ouverte','un crocodile les yeux fermés','slang','exclamation'),
(202,'fr','Téléphone rangé. Maintenant il peut traverser.','Téléphone rangé. Maintenant il peut nager.','traverser la rue prudemment','croiser les doigts','low_iq','cliche'),
(203,'fr','Leur croisière a aussi des dauphins !','Leur croisière a aussi des requins !','une croisière vers des îles tropicales','une croisière en Antarctique','gossip','exclamation'),
(204,'fr','Il fait la course avec ses béquilles !','Il fait la course à vélo !','marcher avec deux béquilles','s''appuyer sur une béquille','dramatic','exaggeration'),
(205,'fr','Film triste. Tous les deux en pleurs.','Film triste. Tous les deux endormis.','en pleurs devant un film triste','en pleurs à un mariage','dramatic','none'),
(206,'fr','Son spa au concombre ne coûte rien.','Son spa au citron ne coûte rien.','du concombre sur les yeux','du concombre dans un sandwich','chill','cheap_quality'),
(207,'fr','Sa tasse est petite et verte.','Sa tasse est petite et bleue.','une petite tasse verte','une tasse de café','chill','none'),
(210,'fr','C''est une cliente satisfaite.','C''est une cliente mécontente.','une cliente au comptoir','une cliente à la porte','business','none'),
(211,'fr','« Juste un fruit ! » La douane a dit non.','« Juste une chaussure ! » La douane a dit non.','un fruit à la douane','un fruit au marché','gossip','bad_excuse'),
(212,'fr','Ce danseur a de super moves.','Ce chanteur a de super moves.','un danseur de hip-hop','un danseur classique sur scène','flirt','none'),
(213,'fr','Sa danse est super fluide.','Son chant est super fluide.','danser la salsa dans la cuisine','danser sous la pluie','flirt','none'),
(214,'fr','Cette glace est dangereuse !','Cette glace est sûre !','une glace fine et dangereuse','du verglas dangereux sur la route','dramatic','exclamation'),
(215,'fr','La pièce a plongé dans l''obscurité.','Le jardin a plongé dans l''obscurité.','une cuisine dans l''obscurité','l''obscurité dans un cinéma','dramatic','none'),
(217,'fr','Sa fléchette est près du mille !','Sa fléchette est près de la porte !','lancer une fléchette turquoise','lancer une balle turquoise','flirt','none'),
(218,'fr','Elle a déclaré le pont ouvert.','Elle a déclaré l''école ouverte.','déclarer le pont ouvert','déclarer des marchandises à la douane','chill','none'),
(219,'fr','Le cerf nous crie dessus !','Le cerf nous fonce dessus !','un cerf dans le brouillard','un cerf dans la neige','dramatic','exclamation'),
(220,'fr','Il a décongelé le poisson.','Il a décongelé le poulet.','un filet de poisson décongelé','dégivrer le pare-brise','chill','none'),
(221,'fr','Elle brandit son diplôme universitaire.','Elle brandit son bébé.','brandir son diplôme universitaire','préparer son diplôme universitaire','chill','none'),
(222,'fr','Ce retard dure une éternité.','Ce train met une éternité.','un retard à la gare','un retard à l''aéroport','dramatic','exaggeration'),
(223,'fr','La livraison est enfin là !','Le plombier est enfin là !','une livraison de repas','une livraison de colis','dramatic','exclamation'),
(224,'fr','Concevoir une chaise, c''est fun.','Concevoir une table, c''est fun.','concevoir une maquette de chaise','concevoir une robe','chill','none'),
(225,'fr','Son bureau est prêt. Le chat est d''accord.','Son bureau est prêt. Le chien est d''accord.','un bureau propre pour travailler','un bureau propre pour dîner','ironic','guessing'),
(226,'fr','Étui vide, désespoir total.','Étui plein, désespoir total.','le désespoir dans un tunnel vide','le désespoir après un examen','dramatic','none'),
(227,'fr','Ce diamant est en feu !','Ce rubis est en feu !','une bague en diamant étincelante','un collier de diamants','dramatic','exclamation'),
(228,'fr','Un dîner au bord de la mer, pas mal.','Un dîner au bord de la piscine, pas mal.','un dîner en terrasse','un dîner dans la cuisine','chill','understatement'),
(229,'fr','Il a enfin eu son diplôme !','Il a enfin eu sa médaille !','recevoir un diplôme','encadrer un diplôme','dramatic','exclamation'),
(231,'fr','Il l''a beaucoup déçue.','Il a déçu son patron.','décevoir sa moitié','des résultats d''examen décevants','dramatic','none'),
(232,'fr','Il est un peu déçu.','Elle est un peu déçue.','un client déçu','déçu par la pluie','ironic','understatement'),
(233,'fr','Il s''est luxé l''épaule.','Il s''est luxé le genou.','une épaule luxée','un doigt luxé','chill','none'),
(234,'fr','Le sucre s''est dissous. Magie !','Le sel s''est dissous. Magie !','un sucre qui se dissout','un cachet qui se dissout','ironic','exaggeration'),
(235,'fr','Mec, il a rapporté la balle.','Mec, il a rapporté un bâton.','rapporter une balle rouge','rapporter une pomme rouge','slang','none'),
(236,'fr','Le dauphin fait la course avec un bateau.','Le dauphin fait la course avec un requin.','un dauphin à côté d''un bateau','un dauphin dans un bassin','chill','none'),
(238,'fr','Il a volé une boisson !','Il a volé une chaussure !','voler la boisson d''un client','voler le colis d''un client','dramatic','exclamation'),
(239,'fr','Il doute que la bague soit en or.','Il est sûr que la bague est en or.','douter d''une bague en or','douter de sa copine','gossip','guessing'),
(241,'fr','Le dessin ressemble trait pour trait au vrai port !','Le dessin ressemble trait pour trait à la vraie montagne !','un dessin de maisons au crayon','un dessin sur un mur','dramatic','exclamation'),
(242,'fr','Refais un tour ! Superbe robe !','Refais un tour ! Superbe chapeau !','une robe d''été rouge','une robe de mariée rouge','flirt','exclamation'),
(243,'fr','S''habiller en hiver, c''est un vrai boulot !','S''habiller en été, c''est un vrai boulot !','s''habiller vite pour l''hiver','assaisonner une salade','dramatic','exaggeration'),
(244,'fr','Une boisson, ça n''a pas suffi.','Un sandwich, ça n''a pas suffi.','une boisson fraîche à l''orange','une boisson chaude','low_iq','guessing'),
(245,'fr','Elle boit comme un chameau !','Elle mange comme un chameau !','boire dans une gourde en acier','boire à une fête','low_iq','exaggeration'),
(246,'fr','Sa façon de conduire est trop fluide.','Sa façon de pédaler est trop fluide.','conduire le long de la côte','conduire en ville','flirt','none'),
(247,'fr','Il laisse tomber la pomme pour la science.','Il lance la pomme pour la science.','laisser tomber une pomme','laisser tomber un verre','low_iq','guessing'),
(248,'fr','Elle dose avec un compte-gouttes.','Elle dose avec une seringue.','presser un compte-gouttes en verre','faire tomber un compte-gouttes','nerd','none'),
(250,'fr','Le canard fait le poirier !','Le cygne fait le poirier !','un canard sur un étang','un canard sous la pluie','low_iq','exclamation'),
(251,'fr','Lui soulève l''haltère, elle sirote son café.','Lui soulève l''haltère, elle mange du gâteau.','soulever un lourd haltère','un haltère sur le canapé','gossip','banter'),
(252,'fr','Il a soufflé un énorme nuage de poussière !','Il a soufflé un énorme nuage de fumée !','un nuage de poussière','un nuage de fumée','dramatic','exclamation'),
(253,'fr','Ici, l''époussetage, c''est un sport d''équipe.','Ici, la cuisine, c''est un sport d''équipe.','l''époussetage d''un abat-jour','saupoudrer un gâteau de sucre','ironic','exaggeration'),
(254,'fr','Ils font tourner la Terre !','Ils peignent la Terre !','la Terre sur un bureau','une carte de la Terre','low_iq','exaggeration'),
(255,'fr','Le soleil se lève à l''est.','Le soleil se lève à l''ouest.','face à l''est à l''aube','aller vers l''est en train','chill','cliche'),
(256,'fr','À force de manger, ils sont repus.','À force de manger, ils ont faim.','manger une soupe de nouilles','manger un sandwich','chill','none'),
(258,'fr','Attention, c''est le bord !','Attention, c''est le trou !','le bord du ponton','le fil d''un couteau','dramatic','exclamation'),
(259,'fr','Le ciel est inquiétant. Des aliens ?','La mer est inquiétante. Des aliens ?','une lueur rouge inquiétante','une forêt silencieuse inquiétante','dramatic','guessing'),
(261,'fr','L''électricien est le héros !','Le plombier est le héros !','un électricien au travail','un électricien sur un toit','dramatic','exaggeration'),
(262,'fr','Douche gratuite pour l''éléphant.','Douche gratuite pour la girafe.','un éléphant au point d''eau','un éléphant au cirque','slang','cheap_quality'),
(263,'fr','Elle émerge du lac !','Elle émerge de la neige !','émerger de l''eau','émerger d''une grotte','dramatic','exclamation'),
(264,'fr','Tant d''émotion aux arrivées !','Tant d''émotion aux départs !','plein d''émotion','cacher son émotion','dramatic','exclamation'),
(265,'fr','L''employé a été payé !','L''employé a été viré !','un employé heureux','un nouvel employé','slang','exclamation'),
(266,'fr','Elle a beaucoup trop d''énergie !','Il a beaucoup trop d''énergie !','plein d''énergie','l''énergie du soleil','slang','exaggeration'),
(267,'fr','L''ingénieur a fabriqué un bras robotique.','L''ingénieur a fabriqué un chien robot.','un ingénieur dans un labo','un ingénieur sur un pont','chill','none'),
(268,'fr','Ils ont fermé l''enveloppe et l''ont embrassée.','Ils ont fermé l''enveloppe et l''ont brûlée.','une enveloppe en papier fermée','une enveloppe en papier ouverte','gossip','none'),
(272,'fr','Toute l''eau s''est évaporée.','Tout le lait s''est évaporé.','l''eau qui s''évapore d''une casserole','l''eau qui gèle dans une casserole','chill','none'),
(274,'fr','Tout le monde est debout !','Tout le monde est assis !','tout le monde en liesse','tout le monde qui part tôt','dramatic','exclamation'),
(276,'fr','Au programme de l''excursion : une cascade.','Au programme de l''excursion : un château.','une excursion vers une cascade','une excursion au musée','chill','none'),
(277,'fr','L''exercice la rend heureuse.','L''exercice la met en colère.','de l''exercice quotidien au jardin','de l''exercice quotidien en salle','chill','none'),
(278,'fr','Flexions des jambes au lever du soleil dans le parc !','Flexions des jambes au lever du soleil sur la plage !','des flexions des jambes au parc','des flexions avec de lourds poids','slang','exclamation'),
(280,'fr','Le chaton veut la caméra.','Le chiot veut la caméra.','un chaton sur un lit','un chaton dans un panier','chill','guessing'),
(283,'fr','Deux mètres de tissu, s''il vous plaît.','Cinq mètres de tissu, s''il vous plaît.','couper du tissu à motifs','du tissu pour un canapé','business','none'),
(284,'fr','Leurs masques visage craquent.','Leurs masques visage fondent.','des masques visage verts qui craquent','un masque contre la grippe','chill','none'),
(285,'fr','Photo de famille. Dites « ouistiti » !','Baignade en famille. Dites « ouistiti » !','une photo de famille dehors','un album photo de famille','dramatic','exclamation'),
(287,'fr','Le village est encore si loin !','Le lac est encore si loin !','un village au loin','loin de la ville','dramatic','exclamation'),
(291,'fr','Ils sont dans un champ de blé.','Ils sont dans un champ de riz.','un champ de blé doré','un terrain de foot','chill','none'),
(292,'fr','L''oreiller a perdu la bagarre.','La lampe a perdu la bagarre.','une bagarre d''oreillers au lit','une bataille de boules de neige','low_iq','cheap_quality'),
(294,'fr','Le feu s''embrase.','Le feu s''éteint.','un feu au bord du lac','un feu dans une cuisine','chill','none'),
(296,'fr','Il fait griller un poisson entier.','Il fait griller un canard entier.','un poisson entier grillé','un poisson dans un aquarium','chill','none'),
(297,'fr','La pêche, juste pour dire au revoir.','La pêche, juste pour le dîner.','la pêche sur un lac calme','la pêche depuis un grand bateau','ironic','understatement'),
(298,'fr','Troisième essai en cabine d''essayage : c''est le bon.','Premier essai en cabine d''essayage : c''est le bon.','des tenues en cabine d''essayage','la queue à la cabine d''essayage','gossip','cliche'),
(299,'fr','Le chien la réveille.','Le chat la réveille.','se réveiller avec un chien','se réveiller avec un réveil','chill','none'),
(300,'fr','Elle hisse le drapeau.','Elle descend le drapeau.','hisser un drapeau','agiter un drapeau','chill','none'),
(301,'fr','Il flotte sur le lac.','Il flotte dans la piscine.','flotter sur un lac calme','flotter dans les airs','chill','none'),
(303,'fr','Elle t''offre une fleur.','Elle t''offre un cookie.','une jolie fleur rose','une jolie robe rose','flirt','none'),
(305,'fr','La mouche est de retour !','L''abeille est de retour !','une mouche sur la confiture','une mouche dans la soupe','dramatic','exclamation'),
(306,'fr','Voler au-dessus des nuages, c''est magnifique.','Voler au-dessus de la mer, c''est magnifique.','voler au-dessus des nuages','faire voler un cerf-volant','chill','none'),
(307,'fr','Bouh ! Il s''est caché dans le brouillard.','Bouh ! Il s''est caché dans la grange.','se cacher dans un épais brouillard','de la buée sur le miroir','slang','exclamation'),
(308,'fr','Il y a tellement de nourriture !','Il y a si peu de nourriture !','une table pleine de nourriture','de la nourriture dans un frigo','dramatic','exclamation'),
(310,'fr','Cette forêt est immense !','Ce désert est immense !','une forêt de grands arbres','un feu de forêt','dramatic','exclamation'),
(311,'fr','Elle manie la fourchette comme une pro.','Elle manie le couteau comme une pro.','des spaghettis sur une fourchette','une bifurcation sur la route','flirt','none'),
(312,'fr','C''était une faute évidente !','C''était un but évident !','une faute par derrière','une faute d''orthographe','dramatic','exclamation'),
(313,'fr','Son fond de teint est tellement lisse.','Son fond de teint est tellement irrégulier.','estomper le fond de teint','les fondations d''une maison','flirt','none'),
(314,'fr','Le renard plonge dans l''herbe comme un nageur !','Le renard plonge dans l''eau comme un nageur !','un renard dans l''herbe givrée','un renard dans un poulailler','dramatic','exaggeration'),
(315,'fr','Son coup franc, c''était du pur Messi !','Son penalty, c''était du pur Messi !','un coup franc enroulé','un coup franc raté','slang','exaggeration'),
(316,'fr','Le congélateur crache de la brume !','Le four crache de la brume !','un tiroir de congélateur','un sac pour congélateur','dramatic','exaggeration'),
(317,'fr','Les frites sont brûlantes !','Les frites sont glacées !','des frites en cornet','des frites dans une assiette','slang','exclamation'),
(318,'fr','L''amitié, c''est partager une glace en deux.','L''amitié, c''est partager une tablette de chocolat en deux.','l''amitié et une glace','l''amitié et une pizza','chill','cliche'),
(319,'fr','La grenouille chante une chanson !','Le poisson chante une chanson !','une grenouille verte qui coasse','une grenouille dans un seau','low_iq','exclamation'),
(320,'fr','Waouh, du givre partout !','Waouh, du sable partout !','de l''herbe blanche de givre','du givre sur un pare-brise','low_iq','exclamation'),
(321,'fr','Elle veut tous les fruits !','Elle veut tout le pain !','acheter des fruits frais','une salade de fruits','slang','exaggeration'),
(322,'fr','Jeux d''argent : elle mise sur le rouge !','Jeux d''argent : elle mise sur le noir !','jeux d''argent à la roulette','jeux d''argent aux courses de chevaux','dramatic','none'),
(324,'fr','Soirée gaming : elle gagne.','Soirée gaming : il gagne.','une soirée gaming à la maison','un magasin de gaming','gossip','banter'),
(326,'fr','Son jardin a tout !','Son jardin a une piscine !','un jardin au coucher du soleil','un jardin la nuit','dramatic','exaggeration'),
(327,'fr','Ici, le jardinage, c''est du travail d''équipe.','Ici, la cuisine, c''est du travail d''équipe.','du jardinage en bac surélevé','du jardinage sur un balcon','business','none'),
(328,'fr','L''ail sent fort !','L''oignon sent fort !','éplucher une gousse d''ail','éplucher un saucisson à l''ail','dramatic','exclamation')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
