begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(329,'fr','La flamme du gaz est bleue.','La flamme du gaz est verte.','une flamme de gaz bleue','du gaz dans une voiture','business','none'),
(330,'fr','Juste à temps pour la porte !','Trop tard pour la porte !','courir vers la porte d''embarquement','une porte de jardin','dramatic','exclamation'),
(331,'fr','Un gentleman sauve les oranges !','Un gentleman sauve les pommes !','un gentleman avec un parapluie','un gentleman avec un chien','dramatic','exclamation'),
(332,'fr','La girafe est en train de déjeuner.','Le lion est en train de déjeuner.','une girafe qui mange des feuilles','une girafe qui mange de l''herbe','business','none'),
(334,'fr','Son verre est glacé.','Son verre est brûlant.','un verre de limonade','un verre de vin','chill','none'),
(338,'fr','Elle fait un câlin à son globe !','Elle fait un câlin à sa lampe !','faire tourner un globe','dessiner un globe','dramatic','exclamation'),
(339,'fr','Elle va au bout de la rue.','Elle va en haut de l''escalier.','aller au bout de la rue','retourner à la maison','chill','none'),
(340,'fr','Ils ont apporté leur propre but !','Ils ont apporté leur propre banc !','un but sur la place','un but pour l''année prochaine','dramatic','exclamation'),
(341,'fr','La chèvre mange le linge !','La chèvre mange les fleurs !','une chèvre sur un toit','une chèvre dans une voiture','dramatic','exclamation'),
(343,'fr','Elle a attrapé l''anneau !','Elle a attrapé la pièce !','attraper un anneau sous l''eau','attraper l''échelle de la piscine','dramatic','exclamation'),
(344,'fr','Elle aime l''or un peu trop.','Elle aime les chats un peu trop.','un lingot d''or bien lourd','une médaille d''or','gossip','understatement'),
(346,'fr','Balle de golf dans le trou. Oui !','Balle de golf dans l''eau. Oui !','un putt de golf au crépuscule','une balle de golf dans l''eau','dramatic','exclamation'),
(348,'fr','Le gouvernement a voté oui.','Le gouvernement a voté non.','un vote du gouvernement','un gouvernement d''élèves','business','none'),
(349,'fr','Pêche, échecs et câlin : meilleur grand-père du monde.','Pêche, échecs et câlin : meilleure grand-mère du monde.','un grand-père et son petit-fils','un grand-père et son chien','slang','cliche'),
(350,'fr','Son petit-fils est rentré !','Son mari est rentré !','serrer son petit-fils dans ses bras','serrer son mari dans ses bras','dramatic','exclamation'),
(351,'fr','Ils chillent dans l''herbe.','Ils chillent sur le sable.','allongés dans l''herbe douce','tondre l''herbe douce','slang','none'),
(352,'fr','Le fromage a des marques de gril.','Le pain a des marques de gril.','du fromage sur un gril chaud','du poisson sur un gril chaud','chill','none'),
(353,'fr','L''invité est arrivé avec un cadeau.','L''invité est arrivé avec un chien.','accueillir un invité','une chambre d''invité','chill','none'),
(354,'fr','Le guide touristique avait raison !','La carte avait raison !','un gros guide touristique','un gros annuaire','gossip','exclamation'),
(355,'fr','Il n''arrive pas à manger. La culpabilité !','Il n''arrive pas à dormir. La culpabilité !','culpabilité pour une cruche cassée','culpabilité pour un téléphone cassé','dramatic','exclamation'),
(356,'fr','Elle va habiter dans cette salle de sport maintenant.','Elle va habiter dans ce bar maintenant.','une salle de sport toute neuve','le cours de sport au lycée','low_iq','guessing'),
(357,'fr','Sa brosse à cheveux, c''est un micro !','Son peigne, c''est un micro !','une brosse à cheveux en bois','une brosse pour un cheval','slang','exclamation'),
(359,'fr','Joues pleines, hamster heureux.','Joues vides, hamster heureux.','un hamster dans sa roue','un hamster dans une boule','slang','none'),
(360,'fr','Gel hydroalcoolique, puis samoussas.','Crème pour les mains, puis samoussas.','une dose de gel hydroalcoolique','du gel hydroalcoolique à l''entrée','business','none'),
(361,'fr','Pas de fleurs ? Il suffit d''emballer des sucettes.','Pas de fleurs ? Il suffit d''emballer des biscuits.','emballer des sucettes dans du papier','emballer des biscuits dans du papier','ironic','cheap_quality'),
(362,'fr','Elle est tellement heureuse, c''est dingue.','Elle est tellement triste, c''est dingue.','une balade heureuse à la plage','un heureux anniversaire','slang','exaggeration'),
(363,'fr','Il fait de la recherche toute la nuit.','Il fait de la recherche toute la matinée.','faire des recherches la nuit','faire des recherches dehors','chill','exaggeration'),
(364,'fr','Il dit qu''il n''est pas artiste.','Il dit qu''il est un artiste célèbre.','pas du tout artiste','le grand atelier d''un artiste','chill','none'),
(365,'fr','Son casque est trop fort !','Ses enceintes sont trop fortes !','partager le casque','réparer le casque','slang','guessing'),
(366,'fr','Son bras a guéri. Oui !','Sa jambe a guéri. Oui !','un bras guéri','une jambe guérie','dramatic','exclamation'),
(367,'fr','Trop de chaleur pour une glace à l''eau !','Trop de pluie pour une glace à l''eau !','la chaleur dans un village','la chaleur d''un feu','dramatic','exaggeration'),
(368,'fr','Livraison par hélicoptère ? Trop stylé !','Livraison par drone ? Trop stylé !','une livraison en hélicoptère rouge','un hélicoptère sur un bateau','slang','exclamation'),
(369,'fr','Il roule à moto.','Il monte à cheval.','rouler sur une moto sportive','rouler en voiture','chill','none'),
(370,'fr','Le casque rouge a fait son job.','Le casque bleu a fait son job.','un casque de skate rouge','un casque sur une moto','chill','understatement'),
(371,'fr','Des herbes aromatiques fraîches pour les pâtes, miam.','Des herbes aromatiques fraîches pour la pizza, miam.','herbes aromatiques sur la fenêtre','une tisane dans une tasse','slang','none'),
(372,'fr','Il fait des figures sur un toit.','Il fait des figures sur une plage.','faire des figures avec un ballon','faire des tours de cartes','chill','none'),
(373,'fr','Un stade plein de supporters en rouge.','Un stade plein de supporters en bleu.','un stade de foot bondé','un stade vide la nuit','chill','none'),
(374,'fr','Il fait du jogging à l''aube.','Il fait du vélo à l''aube.','jogging sur une route déserte','jogging avec un chien','chill','none'),
(375,'fr','Il a trop la classe dans une voiture de course.','Il a trop la classe dans un taxi.','une voiture de course à l''aube','une voiture de course la nuit','flirt','none'),
(376,'fr','De la nature sauvage, et pas un chat.','Du désert, et pas un chat.','une rivière en pleine nature sauvage','une route en pleine nature sauvage','chill','none'),
(377,'fr','Elle se produit dans un studio.','Elle se produit dans une église.','se produire comme dans un clip','se produire dans un grand stade','chill','none'),
(380,'fr','Son voyage s''est terminé sur un toit.','Son voyage s''est terminé sur un bateau.','un long voyage en ville','un voyage en avion','chill','none'),
(381,'fr','Un grain de raisin lui fait trop peur pour le manger.','Une pomme lui fait trop peur pour la manger.','faire peur à un ami','faire peur aux oiseaux','low_iq','guessing'),
(382,'fr','Waouh, ils bossent tellement haut !','Waouh, ils bossent tellement bas !','haut au-dessus de la rue','tout en haut d''une montagne','dramatic','exclamation'),
(383,'fr','Randonnée jusqu''au sommet !','Ski jusqu''au sommet !','randonnée en montagne','randonnée dans le désert','dramatic','exclamation'),
(385,'fr','Elle l''a frappée haut dans le ciel !','Elle l''a frappée bas dans l''herbe !','frapper la balle haut','frapper une balle dans l''eau','dramatic','exaggeration'),
(386,'fr','Son passe-temps : construire des maquettes.','Son passe-temps : construire des maisons.','passe-temps : maquettes de bateaux','passe-temps : vrais bateaux','chill','none'),
(387,'fr','Caméra de surveillance : c''est le chien !','Caméra de surveillance : c''est le chat !','caméra de surveillance de nuit','caméra de surveillance de magasin','gossip','blaming_someone'),
(388,'fr','Ses devoirs ne finissent jamais.','Ses vacances ne finissent jamais.','des devoirs tard le soir','des devoirs dans le bus','dramatic','exaggeration'),
(390,'fr','Son sweat à capuche est trop douillet.','Sa veste est trop douillette.','enfiler un sweat à capuche','laver un sweat à capuche','slang','exaggeration'),
(391,'fr','Le bateau est revenu. L''espoir gagne !','L''avion est revenu. L''espoir gagne !','l''espoir pour le bateau','l''espoir du beau temps','dramatic','exclamation'),
(392,'fr','Elle monte à cheval.','Elle monte à dos de chameau.','un cheval et sa cavalière','un cheval et sa charrette','chill','none'),
(393,'fr','Un lit en auberge de jeunesse coûte dix euros.','Un lit en auberge de jeunesse coûte six euros.','une couchette en auberge de jeunesse','une chambre d''hôtel','business','none'),
(394,'fr','Trop chaud ! Il fait un câlin au ventilo.','Trop chaud ! Il fait un câlin au chien.','une journée chaude et ensoleillée','une tasse de thé chaud','dramatic','exclamation'),
(395,'fr','La meilleure maison du monde !','La meilleure voiture du monde !','emménager dans une maison jaune','emménager dans une maison blanche','slang','exaggeration'),
(396,'fr','C''est le câlin de l''année !','C''est la bagarre de l''année !','un énorme câlin qui tourne','un petit câlin d''au revoir','dramatic','exaggeration'),
(397,'fr','Ils sont à la chasse dans la forêt.','Ils sont à la chasse dans le désert.','la chasse en forêt d''automne','la chasse dans la neige','chill','none'),
(398,'fr','L''hygiène d''abord, puis un pouce levé.','L''hygiène d''abord, puis un check.','l''hygiène à la salle de bain','l''hygiène à la cuisine','chill','none'),
(399,'fr','Il est en train de perdre contre sa glace.','Il est en train de perdre contre son hot-dog.','une glace qui fond','une glace en pot','low_iq','exaggeration'),
(400,'fr','Le numéro 9 joue au hockey sur glace.','Le numéro 7 joue au hockey sur glace.','hockey sur glace sur une patinoire','hockey sur glace sur un étang','chill','none'),
(402,'fr','Elle glisse sur la glace.','Elle glisse sur l''herbe.','des bulles dans la glace','de la glace dans une boisson','chill','none'),
(404,'fr','Chaos dans la salle de classe, mais lui reste calme.','Chaos dans la cuisine, mais lui reste calme.','une salle de classe bruyante','une salle de classe silencieuse','gossip','understatement'),
(405,'fr','Neige dehors, les potes à l''intérieur.','Neige dehors, les chiens à l''intérieur.','au chaud à l''intérieur du chalet','à l''intérieur d''une tente','chill','none'),
(406,'fr','Il martèle du fer chaud.','Il martèle du verre chaud.','marteler du fer chaud','repasser une chemise au fer','chill','none'),
(407,'fr','C''est pas vrai ! Une île entière pour deux !','C''est pas vrai ! Une île entière pour dix !','une petite île tropicale','un îlot dans une cuisine','dramatic','exaggeration'),
(408,'fr','La veste est mise. Beaucoup mieux.','L''écharpe est mise. Beaucoup mieux.','fermer une veste marron','une veste sur une chaise','chill','none'),
(411,'fr','Waouh, elle est trop jalouse.','Waouh, il est trop jaloux.','jalouse d''une autre danseuse','jalouse de sa prof','gossip','exaggeration'),
(412,'fr','Elle a eu le maillot numéro 7 !','Elle a eu le maillot numéro 9 !','un nouveau maillot numéro 7','un nouveau maillot numéro 10','dramatic','exclamation'),
(413,'fr','Le jus est rouge rubis.','Le jus est orange vif.','du jus de grenade frais','du jus d''orange en brique','chill','none'),
(414,'fr','Il a sauté par-dessus la barre !','Il a sauté par-dessus la clôture !','sauter par-dessus la barre','sauter dans la piscine','dramatic','exclamation'),
(416,'fr','Le ketchup a enfin lâché !','La moutarde a enfin lâché !','du ketchup sur des frites','du ketchup sur un burger','dramatic','exaggeration'),
(418,'fr','Elle a fabriqué son propre porte-clés.','Elle a fabriqué son propre collier.','un porte-clés à pompon','un porte-clés avec une photo','chill','none'),
(419,'fr','Ils shootent dans un ballon.','Ils lancent un ballon.','shooter dans un ballon','ouvrir une porte du pied','chill','none'),
(423,'fr','Elle l''embrasse de loin, il attrape le bisou !','Il l''embrasse de loin, elle attrape le bisou !','envoyer un bisou','un bisou de bonne nuit','flirt','exclamation'),
(424,'fr','Son couteau coupe du pain.','Son couteau coupe du fromage.','un grand couteau à pain','un petit couteau de poche','business','none'),
(426,'fr','Elle grimpe ; lui, il tient juste l''échelle.','Elle grimpe ; lui, il tient juste le panier.','tenir l''échelle bien droite','peindre l''échelle','gossip','banter'),
(427,'fr','La coccinelle s''envole.','La coccinelle mange une feuille.','une coccinelle dans l''herbe','une coccinelle sur une main','chill','none'),
(428,'fr','Un canoë sur un lac calme.','Un canoë sur une mer calme.','un lac de montagne calme','un lac gelé','chill','none'),
(429,'fr','Elle a atterri parfaitement !','Elle a atterri dans l''eau !','atterrir sur un champ d''herbe','faire atterrir un avion','dramatic','exclamation'),
(430,'fr','Il lui apprend sa langue.','Elle lui apprend sa langue.','apprendre une nouvelle langue','une leçon de langue sur appli','chill','none'),
(431,'fr','Paresseux ? Non, c''est un « génie ».','Paresseuse ? Non, c''est un « génie ».','un homme paresseux à la maison','un chat paresseux à la maison','ironic','bad_excuse'),
(432,'fr','Elle guide le groupe avec une lanterne.','Elle guide le groupe avec une lampe torche.','guider avec une lanterne','guider avec une carte','chill','none'),
(435,'fr','Le cuir grince !','Le plancher grince !','étirer du cuir','un canapé en cuir','dramatic','exclamation'),
(436,'fr','Tout le monde fait un pas à gauche.','Tout le monde fait un pas à droite.','faire un pas à gauche','sauter à gauche','chill','none'),
(437,'fr','Elle étire sa jambe.','Elle étire son bras.','une jambe contre le mur','une jambe dans le plâtre','chill','none'),
(438,'fr','Le citron est beaucoup trop acide !','Le citron est beaucoup trop sucré !','croquer un quartier de citron','un gâteau au citron','slang','exclamation'),
(439,'fr','La limonade est super fraîche.','La limonade est super chaude.','un bocal de limonade','une canette de limonade','slang','none'),
(440,'fr','Il soulève une barre chargée !','Il soulève un canapé !','soulever une lourde barre','soulever un petit enfant','dramatic','exclamation'),
(443,'fr','Enfin de la lumière au grenier !','Enfin de la lumière dans la cuisine !','la lumière par la fenêtre','la lumière d''une bougie','dramatic','exclamation'),
(444,'fr','Un éclair ! T''as vu ça ?','Un arc-en-ciel ! T''as vu ça ?','regarder des éclairs la nuit','des éclairs en plein jour','slang','exclamation'),
(445,'fr','Sa ligne blanche est parfaite !','Sa ligne jaune est parfaite !','peindre une ligne blanche','une ligne d''arrivée','dramatic','exclamation'),
(446,'fr','Le lion rugit vers nous !','Le lion court vers nous !','un lion dans les herbes','un lion en cage','dramatic','exclamation'),
(447,'fr','Le baume à lèvres sauve la mise !','La crème pour les mains sauve la mise !','mettre du baume à lèvres','acheter un baume à lèvres','dramatic','cliche'),
(448,'fr','Un gloss brillant comme du verre.','Un gloss mat comme du papier.','un gloss rose brillant','un gloss rouge foncé','flirt','exaggeration'),
(449,'fr','Chut, ils sont à l''écoute !','Chut, ils dorment !','à l''écoute dans la forêt','écouter de la musique','dramatic','exclamation'),
(450,'fr','Le lézard prend un bain de soleil.','Le lézard nage.','un lézard sur un mur','un lézard dans une boîte','chill','none'),
(451,'fr','Elle verrouille la porte.','Elle ouvre la porte.','verrouiller la porte d''un bateau','verrouiller la porte d''une voiture','chill','none'),
(452,'fr','Ils ont même mis le logo sur le chien !','Ils ont même mis le logo sur le chat !','un logo sur un collier','un logo sur un T-shirt','gossip','exclamation'),
(453,'fr','Il est seul à la cantine.','Il est seul à la bibliothèque.','déjeuner tout seul','rentrer tout seul à pied','dramatic','none'),
(454,'fr','Soupe et plaid : le pur amour.','Thé et plaid : le pur amour.','l''amour un soir de pluie','l''amour au premier regard','flirt','exaggeration'),
(455,'fr','Elle a des poumons super puissants.','Il a des poumons super puissants.','des poumons pleins d''air','des poumons pleins de fumée','chill','exaggeration'),
(456,'fr','Le magazine est à elle maintenant.','Le journal est à elle maintenant.','feuilleter un magazine','un magazine dans le train','gossip','guessing'),
(457,'fr','Un artiste s''occupe de son maquillage.','Un artiste s''occupe de sa coiffure.','maquillage devant un miroir','démaquillage devant un miroir','chill','none'),
(458,'fr','Un homme costaud porte une caisse.','Un homme costaud porte un chien.','des hommes qui jouent aux échecs','des hommes qui jouent aux cartes','chill','none'),
(459,'fr','Le responsable donne des ordres.','Le responsable donne des fleurs.','un responsable avec un porte-bloc','un responsable d''équipe de foot','business','none'),
(461,'fr','Il imite le mannequin. Jumeaux !','Il peint le mannequin. Jumeaux !','habiller un mannequin','un mannequin en vitrine','low_iq','exclamation'),
(462,'fr','La carte a trouvé la fontaine !','La carte a trouvé l''église !','une grande carte en papier','une carte sur un téléphone','low_iq','exaggeration'),
(464,'fr','Elle dessine au marqueur.','Elle dessine à la craie.','un gros marqueur rose','un marqueur sur un tableau blanc','chill','none'),
(465,'fr','Elle fait ses courses au marché.','Elle fait ses courses au centre commercial.','un marché de rue animé','une fête de rue animée','chill','none'),
(466,'fr','La tête du mascara : bouche grande ouverte.','La tête du mascara : yeux bien fermés.','appliquer du mascara noir','du mascara qui coule','gossip','cliche'),
(467,'fr','Le maître façonne un vase.','Le maître peint un vase.','un maître potier','un maître au piano','chill','none'),
(468,'fr','Ils sont sur leurs tapis de yoga.','Ils sont sur leurs serviettes.','un tapis de yoga violet','un tapis devant la porte','chill','none'),
(469,'fr','Ces allumettes marchent du premier coup !','Ce briquet marche du premier coup !','une boîte d''allumettes','des allumettes mouillées','dramatic','exclamation'),
(470,'fr','Ils sont tombés dans la prairie.','Ils sont tombés dans la rivière.','une prairie pleine de coquelicots','une prairie pleine de vaches','chill','none'),
(472,'fr','Le mécanicien répare une voiture.','Le mécanicien répare un vélo.','un mécanicien au garage','un mécanicien sur la route','chill','none'),
(473,'fr','Elle mord sa médaille d''or. De l''or, du vrai ?','Elle mord sa bague en or. De l''or, du vrai ?','mordre une médaille d''or','une médaille dans une boîte','dramatic','guessing'),
(474,'fr','Méditation de groupe au coucher du soleil.','Méditation de groupe sur une plage.','méditation sur une terrasse en bois','méditation dans un temple','chill','none'),
(475,'fr','Chaque souvenir la fait sourire.','Chaque souvenir la fait pleurer.','une boîte de vieux souvenirs','une carte mémoire photo','chill','none'),
(476,'fr','Il utilise un microscope.','Il utilise un télescope.','une feuille au microscope','un insecte au microscope','nerd','none'),
(477,'fr','Le micro-ondes, c''est la meilleure série.','Le four, c''est la meilleure série.','regarder le micro-ondes','nettoyer le micro-ondes','ironic','exaggeration'),
(478,'fr','Tout le monde a une moustache de lait !','Personne n''a de moustache de lait !','une moustache de lait','du lait dans le frigo','dramatic','exaggeration'),
(479,'fr','Son esprit a deux coups d''avance.','Son esprit a deux coups de retard.','calculer les coups dans son esprit','changer d''avis','nerd','exaggeration'),
(480,'fr','L''eau minérale la chatouille.','Le jus d''orange la chatouille.','de l''eau minérale pétillante','de l''eau minérale plate','chill','none'),
(481,'fr','Le miroir l''aime en retour.','La fenêtre l''aime en retour.','frimer devant le miroir','nettoyer le miroir','low_iq','guessing'),
(483,'fr','Le singe a volé une banane !','Le singe a volé un chapeau !','un singe qui mange une banane','un singe qui vend une banane','dramatic','exclamation'),
(484,'fr','Elle passe la serpillière.','Elle passe le balai.','une serpillière dans un seau','une serpillière dans un évier','chill','none'),
(485,'fr','La mousse est douce. Super oreiller.','Le foin est doux. Super oreiller.','de la mousse verte toute douce','de la mousse sur un toit','low_iq','none'),
(486,'fr','Au sommet de la montagne, ouais !','Au pied de la montagne, ouais !','au sommet d''une montagne','un lac de montagne','dramatic','exclamation'),
(487,'fr','La souris a trouvé le fromage.','La souris a trouvé le pain.','une souris dans une grange','une souris et un clavier','chill','none'),
(488,'fr','Ses muscles sont énormes !','Ses chaussures sont énormes !','gonfler de gros muscles','un muscle de la jambe','dramatic','exclamation'),
(489,'fr','Le champignon a des points blancs.','Le champignon a des points noirs.','un champignon rouge à pois','une soupe aux champignons rouges','chill','none'),
(490,'fr','Ce musicien va devenir célèbre.','Ce danseur va devenir célèbre.','un musicien de rue','un musicien dans un groupe','gossip','guessing'),
(491,'fr','La moutarde pique.','Le miel pique.','une cuillerée de moutarde','un pot de graines de moutarde','chill','none'),
(492,'fr','Son vernis à ongles est encore humide !','Ses cheveux sont encore humides !','se mettre du vernis à ongles','enlever un vieux vernis à ongles','dramatic','exclamation'),
(495,'fr','Ils se détendent dans la nature.','Ils courent dans la nature.','allongés dans la nature','un film sur la nature','chill','none'),
(496,'fr','Joli collier, super choix.','Joli bracelet, super choix.','un collier de perles colorées','un collier en chaîne dorée','flirt','none'),
(498,'fr','Trop nerveux avant le spectacle !','Trop nerveux avant l''examen !','un guitariste nerveux','un élève nerveux avant l''exam','dramatic','exclamation'),
(499,'fr','Coucou-caché derrière un journal !','Coucou-caché derrière un menu !','caché derrière un journal','lire le journal en ligne','slang','exclamation'),
(500,'fr','Il le dribble comme s''il n''existait pas.','Il dribble trois mecs comme s''ils n''existaient pas.','dribbler un défenseur','dribbler le gardien','slang','exaggeration'),
(501,'fr','Ils marchent la nuit.','Ils marchent à midi.','rentrer à pied la nuit','travailler la nuit','chill','none'),
(502,'fr','Ils mettent le cap au nord.','Ils mettent le cap au sud.','cap au nord avec une boussole','le nord d''une ville','business','none'),
(503,'fr','Un nouveau carnet ! Moment historique.','Un nouvel ordi portable ! Moment historique.','un carnet tout neuf','un carnet plein de notes','ironic','exclamation'),
(505,'fr','Il se bat contre une toute petite noix.','Il se bat contre un tout petit œuf.','casser une noix','une noix de coco','low_iq','exaggeration'),
(507,'fr','Elle observe une libellule.','Elle observe un papillon.','observer une libellule','attraper une libellule','nerd','none'),
(508,'fr','Des dauphins dans l''océan ! Pas possible !','Des requins dans l''océan ! Pas possible !','des dauphins dans l''océan','nager dans l''océan','dramatic','exclamation'),
(509,'fr','L''huile coule lentement.','Le lait coule lentement.','du pain dans l''huile d''olive','de l''huile dans une poêle','chill','none'),
(511,'fr','Il coupe des oignons avec des lunettes de piscine. Génie !','Il coupe des oignons avec des lunettes de soleil. Génie !','émincer un oignon blanc','faire revenir un oignon blanc','low_iq','exclamation'),
(512,'fr','La tenue est enfin au point.','La coupe est enfin au point.','composer une tenue','une tenue pour un mariage','chill','none'),
(513,'fr','Ils mangent dehors. Qui a besoin d''une salle à manger ?','Ils mangent à l''intérieur. Qui a besoin d''une salle à manger ?','manger dehors sur l''herbe','manger dehors dans un café','ironic','guessing'),
(514,'fr','Le four, c''est leur nouvelle télé.','Le frigo, c''est leur nouvelle télé.','du pain qui lève au four','une pizza au four','slang','exaggeration'),
(515,'fr','Elle a surmonté le mur !','Elle a surmonté la rivière !','surmonter un mur d''escalade','surmonter sa peur des chiens','dramatic','exclamation'),
(516,'fr','L''évier a débordé. Oups.','La baignoire a débordé. Oups.','un évier qui déborde','une poubelle qui déborde','ironic','understatement'),
(517,'fr','Bye bye le camping-car ! Il double !','Bye bye le camping-car ! Il se gare !','doubler un camping-car lent','doubler un train rapide','slang','exclamation'),
(518,'fr','Le hibou te regarde.','Le corbeau te regarde.','un hibou sur une branche','un hibou en cage','dramatic','exaggeration'),
(519,'fr','Le sac est préparé pour l''école.','Le sac est préparé pour un voyage.','préparer son cartable','préparer une valise','chill','none'),
(520,'fr','Elle pagaie ; lui, il dort.','Elle pagaie ; lui, il pêche.','pagayer en canoë','pagayer sur une planche de surf','gossip','banter'),
(521,'fr','Il a une douleur terrible à l''orteil !','Il a une douleur terrible à la main !','une douleur à l''orteil','une douleur au dos','dramatic','exclamation'),
(522,'fr','Sa peinture est plus belle que la vraie vue, dit-elle.','Sa peinture est moins belle que la vraie vue, dit-elle.','une peinture de la mer','peindre un mur en blanc','gossip','exaggeration'),
(523,'fr','Joli mouvement avec cette poêle !','Joli mouvement avec cette pâte à pizza !','des légumes dans une poêle','des crêpes dans une poêle','flirt','exclamation'),
(524,'fr','Panique : le train est parti sans elle !','Panique : le bus est parti sans elle !','panique sur le quai','panique dans l''avion','dramatic','exclamation'),
(525,'fr','Un petit trombone bat le gros ventilo.','Une petite agrafeuse bat le gros ventilo.','un trombone sur les feuilles','un trombone qui tient une photo','dramatic','exaggeration'),
(526,'fr','Le pistolet laser l''a paralysé !','Le pistolet à eau l''a paralysé !','paralysé par un pistolet laser','paralysé par la peur','dramatic','exclamation'),
(527,'fr','Elle a reçu un colis !','Elle a reçu une lettre !','ouvrir un colis','envoyer un colis','dramatic','exclamation'),
(528,'fr','Elle se gare comme une pro !','Il se gare comme un pro !','se garer entre deux voitures','se garer dans un garage','slang','exaggeration'),
(530,'fr','Le perroquet dit bonjour.','Le perroquet dit au revoir.','un perroquet sur une rambarde','un perroquet en cage','chill','none'),
(531,'fr','Cette fête au jardin, c''est le feu.','Cette fête à la piscine, c''est le feu.','une fête au jardin au crépuscule','une fête à la piscine','slang','none'),
(532,'fr','Il passe, elle marque, trop facile.','Elle passe, il marque, trop facile.','lui passer le ballon','doubler une voiture lente','slang','none'),
(533,'fr','Elle a embrassé son passeport !','Elle a embrassé sa valise !','un passeport tamponné','un photomaton pour passeport','dramatic','exclamation'),
(535,'fr','La tour de pâtes a l''air très pro.','La tour de gâteaux a l''air très pro.','une tour de pâtes','des pâtes en salade','business','none'),
(536,'fr','Elle trouve le calme dans un hamac.','Elle trouve le calme dans une baignoire.','le calme au lever du soleil','le calme à minuit','chill','none'),
(537,'fr','Elle épluche une pomme rouge.','Elle épluche une pomme verte.','éplucher en une seule spirale','éplucher une banane','chill','none'),
(538,'fr','Son stylo a plein de couleurs.','Son stylo a une seule couleur.','un stylo multicolore','un stylo lumineux','chill','none'),
(540,'fr','Elle a marqué le penalty !','Elle a raté le penalty !','marquer un penalty','arrêter un penalty','dramatic','exclamation'),
(541,'fr','Son dessin au crayon est trop beau.','Son dessin au stylo est trop beau.','dessiner avec un crayon jaune','tailler un crayon jaune','flirt','none'),
(542,'fr','Glissade sur le ventre ! Allez, le pingouin !','Glissade sur le ventre ! Allez, le phoque !','un pingouin sur la glace','un pingouin au zoo','slang','exclamation'),
(543,'fr','Le poivre l''a fait éternuer !','L''oignon l''a fait éternuer !','moudre du poivre noir','moudre des grains de café','dramatic','blaming_someone'),
(545,'fr','Quel spectacle de jonglage !','Quel spectacle de danse !','un spectacle de jonglage de rue','un spectacle de fin d''année','dramatic','exclamation'),
(546,'fr','C''est beaucoup trop de parfum, là !','C''est beaucoup trop d''eau, là !','vaporiser du parfum sur une amie','vaporiser du parfum sur une robe','slang','exaggeration'),
(547,'fr','Son téléphone sonne !','Sa sonnette sonne !','répondre au téléphone','un téléphone dans une poche','dramatic','exclamation'),
(548,'fr','Celle-là ! La photographie, c''est génial.','Celle-là ! La peinture, c''est génial.','photographie de rue au crépuscule','photographie de mariage en intérieur','dramatic','exclamation'),
(549,'fr','Un anneau doré pour son piercing.','Une puce dorée pour son piercing.','un piercing anneau doré','un piercing au nez','chill','none'),
(550,'fr','Le cochon se roule dans la boue.','Le cochon se roule dans la neige.','un cochon à la ferme','un cochon dans une baignoire','chill','none'),
(551,'fr','Le pigeon inspecte le café.','Le pigeon inspecte la banque.','un pigeon sur une place','un pigeon dans un parc','business','exaggeration'),
(553,'fr','Il est trop fier de son terrain.','Il est trop fier de sa voiture.','tondre le terrain','peindre le terrain','gossip','none'),
(554,'fr','L''endroit parfait sur la plage.','L''endroit parfait dans le parc.','l''endroit parfait pour s''asseoir','une place dans la file','chill','none'),
(555,'fr','La plante a une nouvelle feuille !','La plante a une nouvelle fleur !','une plante à grandes feuilles','une plante à fleurs rouges','dramatic','exclamation'),
(556,'fr','Il lui a sauvé la vie avec un pansement.','Il lui a sauvé la vie avec un glaçon.','un pansement au bout du doigt','un pansement sur un genou','ironic','exaggeration'),
(557,'fr','Le chef dresse l''assiette.','Le chef lave l''assiette.','des spaghettis dans une assiette blanche','une pile d''assiettes vides','business','none'),
(558,'fr','Il a perdu son chapeau en jouant au volley.','Il a perdu sa chaussure en jouant au volley.','jouer au volley dans un parc','jouer aux cartes dans un parc','chill','none'),
(559,'fr','Ce joueur est trop content !','Ce joueur est trop énervé !','un joueur en jaune','un joueur sur le banc','dramatic','exclamation'),
(560,'fr','Selfie d''abord, fontaine ensuite.','Selfie d''abord, pizza ensuite.','la célèbre fontaine de Trevi','une fontaine dans un centre commercial','chill','cliche'),
(561,'fr','Un croissant de pur plaisir.','Un bagel de pur plaisir.','le plaisir d''un croissant','un plaisir de te rencontrer','dramatic','none'),
(562,'fr','La prise, c''était ça le problème.','L''ampoule, c''était ça le problème.','une prise mal branchée','une prise de judo','chill','understatement'),
(564,'fr','Leur podium est en mousse.','Leur podium est en or.','un podium en blocs de mousse','un podium à une conférence','ironic','cheap_quality'),
(566,'fr','Il pollue la rivière. La honte !','Il nettoie la rivière. La honte !','polluer une rivière propre','polluer la mer','dramatic','blaming_someone'),
(567,'fr','Des poissons rouges vivent dans cet étang.','Des grenouilles vivent dans cet étang.','des poissons rouges dans l''étang','des canards sur l''étang','chill','none'),
(568,'fr','Elle voulait une journée tranquille à la piscine.','Elle voulait une journée tranquille au lac.','plonger dans la piscine','une piscine gonflable','chill','guessing'),
(569,'fr','Le receveur des postes est très autoritaire.','Le receveur des postes est très timide.','un receveur des postes autoritaire','un receveur des postes en vacances','gossip','none'),
(571,'fr','L''eau de la casserole danse !','L''eau de la casserole gèle !','des patates dans une casserole','des fleurs dans un grand pot','low_iq','exaggeration'),
(572,'fr','Ils ont trouvé plein de pommes de terre !','Ils ont trouvé plein de carottes !','déterrer des pommes de terre','éplucher des pommes de terre','dramatic','exclamation'),
(573,'fr','Sa façon de verser montre un vrai savoir-faire.','Sa façon de chanter montre un vrai savoir-faire.','verser de très haut','une pluie battante dehors','business','none'),
(575,'fr','Elle a été sauvée par sa batterie externe !','Il a été sauvé par sa batterie externe !','recharger sur une batterie externe','une batterie externe à la maison','dramatic','cliche'),
(576,'fr','Elle prie pour avoir une bonne note.','Elle prie pour avoir un nouveau téléphone.','prier pour une bonne note','prier à l''église','dramatic','none'),
(577,'fr','Elle avait prédit la pluie. Lui, non.','Elle avait prédit la neige. Lui, non.','prédire la pluie','prédire les numéros du loto','gossip','banter'),
(578,'fr','Elle rayonne de fierté.','Elle pleure de fierté.','la fierté de sa moto','la fierté de sa nouvelle voiture','chill','none'),
(579,'fr','La programmation d''un robot, c''est dur.','La programmation d''un drone, c''est dur.','la programmation d''un petit robot','la programmation d''un jeu vidéo','chill','understatement'),
(580,'fr','Elle la protège de la pluie.','Elle la protège du soleil.','protéger quelqu''un de la pluie','protéger quelqu''un d''un chien','chill','none'),
(581,'fr','Manifester avec des tournesols !','Manifester avec des parapluies !','manifester pour la nature','manifester sous la pluie','dramatic','exclamation'),
(582,'fr','Elle est fière de sa chaise.','Elle est fière de sa table.','fière de son travail','fière de sa voiture','chill','none'),
(584,'fr','Elle lui a prouvé qu''il avait tort. Facile.','Il lui a prouvé qu''elle avait tort. Facile.','lui prouver qu''il a tort','lui prouver qu''elle a tort','ironic','understatement'),
(585,'fr','Elle joue de la musique en public.','Elle joue aux échecs en public.','jouer de la musique en public','une piscine publique','chill','none'),
(587,'fr','Les jaunes ont marqué avec le palet !','Les violets ont marqué avec le palet !','un palet dans le filet','un palet dans les tribunes','dramatic','exclamation'),
(588,'fr','Splash ! Gros saut dans la flaque.','Splash ! Gros saut dans la piscine.','sauter dans une flaque','contourner une flaque','slang','exclamation'),
(589,'fr','Grosse traction, belle fin.','Grosse poussée, belle fin.','tirer sur une grosse corde','ouvrir une porte en tirant','chill','cliche'),
(591,'fr','Il est amoureux de son sac de frappe.','Il est amoureux de son escabeau du garage.','accrocher un sac de frappe','frapper la porte du garage','gossip','guessing'),
(592,'fr','Une petite poussée sur la camionnette ? Facile !','Une petite poussée sur le bus ? Facile !','pousser une camionnette blanche','pousser une voiture blanche','ironic','understatement'),
(593,'fr','Des pyjamas assortis ? Trop mignon !','Des vestes assorties ? Trop mignon !','pyjamas à carreaux assortis','pyjamas rayés assortis','flirt','exclamation'),
(594,'fr','Grâce au saut, elle s''est qualifiée.','Grâce à la nage, elle s''est qualifiée.','se qualifier pour le tour suivant','décrocher son diplôme de médecin','chill','none'),
(595,'fr','Le lapin est assis.','Le lapin est couché.','un lapin dans les dunes','un lapin dans un chapeau','chill','none'),
(596,'fr','Allez, allez, allez ! Quelle course !','Allez, allez, allez ! Quelle nage !','une course sur piste','une course dans une piscine','dramatic','exclamation'),
(597,'fr','Trop stylé, le trick avec la raquette.','Trop stylé, le trick avec la bouteille.','une raquette de tennis noire','une raquette de badminton','slang','none'),
(598,'fr','Elle danse sous la pluie.','Elle danse sous la neige.','danser sous une pluie battante','s''abriter de la pluie','chill','none'),
(599,'fr','Ces gestes sont hyper rapides.','Ces gestes sont hyper lents.','des passements de jambes rapides','des passes rapides','slang','none'),
(600,'fr','Le rat vole de la pizza !','Le rat vole du pain !','un rat avec une pizza','un rat en cage','dramatic','exclamation'),
(601,'fr','Il se rase avec un rasoir.','Il se rase avec un couteau.','un rasoir électrique','une lame de rasoir','chill','none'),
(602,'fr','Lecture dans un train, la nuit.','Lecture sur un bateau, la nuit.','lecture dans un train de nuit','lecture à la bibliothèque','chill','none'),
(604,'fr','Ce ticket de caisse ne finit jamais !','Ce menu ne finit jamais !','un ticket de caisse très long','un ticket de caisse très court','slang','exaggeration'),
(607,'fr','Le réfrigérateur est plein maintenant.','Le four est plein maintenant.','remplir le réfrigérateur','nettoyer le réfrigérateur','chill','none'),
(608,'fr','Voiture garée ! Quel soulagement !','Voiture accidentée ! Quel soulagement !','soulagement après le créneau','soulagement après un accident','dramatic','exclamation'),
(609,'fr','Ils se reposent sur la colline.','Ils courent sur la colline.','se reposer au sommet d''une colline','se reposer dans un hamac','chill','none'),
(610,'fr','La citrouille a gagné un ruban bleu. Elle est choquée !','La carotte a gagné un ruban bleu. Elle est choquée !','le ruban bleu d''une citrouille','un ruban dans ses cheveux','gossip','none'),
(613,'fr','Il sautille sur le ring.','Il sautille dans la piscine.','monter sur le ring','une bague au doigt','chill','none'),
(615,'fr','Course de feuilles sur la rivière. Allez, allez !','Course de bateaux sur la rivière. Allez, allez !','des feuilles sur une rivière claire','un bateau sur une rivière','slang','none'),
(616,'fr','Rocher : 1. Humains : 0.','Arbre : 1. Humains : 0.','pousser un rocher géant','lancer un petit rocher','slang','cliche'),
(617,'fr','Elle est venue en rollers juste pour lui piquer son verre !','Elle est venue à vélo juste pour lui piquer son verre !','des rollers violets au parc','des rollers sur une patinoire','dramatic','exaggeration'),
(618,'fr','La corde a sauvé la charrette !','La chaîne a sauvé la charrette !','une corde autour d''une roue','une corde à sauter','dramatic','exaggeration'),
(620,'fr','Cette rose sent le paradis.','Cette tulipe sent le paradis.','sentir une rose de couleur rose','acheter une rose de couleur rose','dramatic','cliche'),
(621,'fr','La rangée est parfaitement droite.','La rangée est parfaitement ronde.','planter en rangée droite','assis au premier rang','business','none'),
(622,'fr','Un élastique tient les herbes.','Un élastique tient les poireaux.','un élastique orange','un élastique à cheveux','business','none'),
(623,'fr','Trop impoli, ce mec !','Trop gentil, ce mec !','un client de café impoli','une serveuse impolie','slang','exclamation'),
(624,'fr','Elle court après son chapeau !','Elle court après son chien !','courir après un chapeau','courir après un bus','dramatic','exclamation'),
(627,'fr','Podium dans le salon. Vas-y, défile !','Podium dans la cuisine. Vas-y, défile !','un podium dans le salon','une piste d''aéroport','slang','exclamation'),
(628,'fr','Son visage est plein de tristesse.','Son visage est plein de joie.','tristesse dans une boutique vide','tristesse à un enterrement','dramatic','none'),
(629,'fr','En sécurité dedans, tempête dehors.','En sécurité dedans, soleil dehors.','en sécurité dans un refuge','un coffre-fort au mur','chill','cliche'),
(630,'fr','Le marin est à la barre !','Le marin est à table !','un marin sur le pont','un marin dans un bar','slang','exclamation'),
(631,'fr','Il fait des salades avec une efficacité redoutable.','Il fait des gâteaux avec une efficacité redoutable.','mélanger une salade fraîche','une salade en barquette','business','none'),
(634,'fr','Une vague a mangé son dessin dans le sable.','Un chien a mangé son dessin dans le sable.','dessiner dans le sable','faire un château de sable','slang','exaggeration'),
(635,'fr','Sandales aux pieds, orteils à l''air !','Bottes aux pieds, orteils à l''air !','attacher des sandales beiges','acheter des sandales beiges','slang','none'),
(638,'fr','Il a mis beaucoup trop de sauce !','Il a mis beaucoup trop de sel !','une assiette pleine de sauce','de la sauce en bouteille','slang','exaggeration'),
(639,'fr','Il fait frire des saucisses.','Il fait frire des œufs.','des saucisses à la poêle','des saucisses sur une pizza','chill','none'),
(640,'fr','La balance doit être cassée !','L''horloge doit être cassée !','une grosse balance à cadran','une balance de cuisine','low_iq','bad_excuse'),
(641,'fr','Le chat est sur la balance !','Le chien est sur la balance !','un chat sur la balance','une balance de cuisine vide','gossip','exclamation'),
(642,'fr','Ils comparent leurs cicatrices.','Ils comparent leurs tatouages.','comparer leurs cicatrices','cacher leurs cicatrices','chill','none'),
(644,'fr','Qui est là ? Elle est effrayée !','Qui est là ? Il est effrayé !','effrayée dans un parking','effrayée dans des montagnes russes','dramatic','exclamation'),
(645,'fr','Il organise son emploi du temps.','Il organise son bureau.','planifier son emploi du temps','les horaires de bus','business','none'),
(646,'fr','La science fait de la mousse orange !','La science fait de la mousse bleue !','une expérience de science','un musée des sciences','dramatic','exclamation'),
(647,'fr','Juste une petite coupe aux ciseaux.','Juste une petite coupe au rasoir.','couper sa frange aux ciseaux','découper du papier aux ciseaux','ironic','understatement'),
(649,'fr','Mamie le gronde encore.','Mamie lui fait encore un câlin.','gronder un petit-fils','gronder un chien','gossip','none'),
(650,'fr','Il a trouvé la dernière vis !','Il a trouvé le dernier clou !','la dernière vis manquante','la dernière chaussette manquante','dramatic','exclamation'),
(651,'fr','Elle tient le tournevis ; lui, il stresse.','Elle tient le marteau ; lui, il stresse.','serrer avec un tournevis','lui, un tournevis à la main','gossip','banter'),
(653,'fr','Chercher partout... et les clés étaient sur la porte !','Chercher partout... et les clés étaient dans la voiture !','chercher des clés perdues','chercher un chien perdu','dramatic','exclamation'),
(654,'fr','Elle chuchote un secret.','Elle crie un secret.','chuchoter un secret','écrire un secret','chill','none'),
(655,'fr','Des chapeaux de fête ? Elle reste sérieuse.','Des chapeaux de fête ? Il reste sérieux.','un air sérieux au boulot','une discussion sérieuse au dîner','ironic','understatement'),
(656,'fr','Toute la foule n''arrive pas à la distraire !','Toute la foule n''arrive pas à le distraire !','essayer de la distraire','essayer de distraire un chien','dramatic','exclamation'),
(657,'fr','Elle sert des nouilles comme une pro.','Elle sert des pizzas comme une pro.','servir un bol de nouilles','servir une balle de tennis','slang','none'),
(659,'fr','Ça fait beaucoup de shampooing !','Ça fait beaucoup de crème !','une tour de mousse de shampooing','un shampooing pour chiens','dramatic','exclamation'),
(661,'fr','Le requin te sourit.','Le dauphin te sourit.','un requin près de la caméra','un requin près d''un bateau','dramatic','guessing'),
(662,'fr','Le taille-crayon marche parfaitement.','Le taille-crayon marche très mal.','un petit taille-crayon','un petit aiguise-couteau','business','none'),
(664,'fr','Se raser à la main, à l''ancienne.','S''épiler à la main, à l''ancienne.','se raser au coupe-chou','se raser au rasoir électrique','slang','cliche'),
(665,'fr','Le mouton est fâché contre moi ?','La chèvre est fâchée contre moi ?','un mouton sur une colline','un mouton dans une grange','low_iq','exaggeration'),
(666,'fr','Il met une chemise bleue.','Il met une chemise rouge.','boutonner une chemise bleu clair','repasser une chemise bleu clair','chill','none'),
(667,'fr','Le scooter renversé, c''est le choc.','Le vélo renversé, c''est le choc.','le choc d''un scooter renversé','un choc électrique','dramatic','none'),
(668,'fr','Chaussures lacées. Prêt à partir.','Bottes lacées. Prêt à partir.','lacer des chaussures marron','cirer des chaussures marron','business','none'),
(670,'fr','Elle fait les courses avec efficacité.','Elle nage avec efficacité.','faire les courses au supermarché','acheter des vêtements','business','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
