begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(673,'fr','Son pull a rétréci. Beaucoup !','Son écharpe a rétréci. Beaucoup !','un pull rouge rétréci','se recroqueviller de peur','dramatic','exclamation'),
(674,'fr','Elle est malade, à la maison.','Elle est malade, au boulot.','malade sur le canapé','malade dans un lit d''hôpital','chill','none'),
(675,'fr','Un côté du bateau est fini.','Un côté de la maison est fini.','peindre le côté du bateau','la rive d''un lac','business','none'),
(676,'fr','Ils font du tourisme à Venise.','Ils font du tourisme à Paris.','du tourisme en gondole','du tourisme en bus','chill','none'),
(678,'fr','La soie refuse de rester en place.','Le chat refuse de rester en place.','de la soie verte brillante','une cravate en soie','ironic','none'),
(680,'fr','Le chanteur s''éclate.','Le chanteur déjeune.','un chanteur en studio','un chanteur sur scène','chill','none'),
(681,'fr','Chanter à fond dans la voiture !','Chanter à fond sous la douche !','chanter en voiture','chanter sur scène','dramatic','exclamation'),
(683,'fr','L''évier est une montagne de mousse !','La baignoire est une montagne de mousse !','un évier plein de mousse','un évier plein de jouets','low_iq','exaggeration'),
(684,'fr','Sa sœur est enfin rentrée !','Son frère est enfin rentré !','serrer sa sœur dans ses bras','se disputer avec sa sœur','dramatic','exclamation'),
(685,'fr','Enfin, la bonne taille.','Enfin, les bonnes chaussures.','la bonne taille de chapeau','la bonne taille de chaussures','chill','none'),
(687,'fr','Skateboard au coucher du soleil ? Trop stylé.','Vélo au coucher du soleil ? Trop stylé.','faire du skateboard','un skateboard en magasin','slang','none'),
(689,'fr','Jolie jupe, joli tour !','Joli chapeau, joli tour !','une jupe plissée jaune','une longue jupe noire','flirt','exclamation'),
(690,'fr','Le ciel est tellement grand.','La mer est tellement grande.','regarder le ciel','un ciel plein d''étoiles','chill','none'),
(691,'fr','Il garde sa voiture. Mal.','Il lave sa voiture. Mal.','garder une voiture garée','garder une banque','ironic','none'),
(692,'fr','Dormir ? C''est un pro.','Lire ? C''est un pro.','dormir sous une couverture','dormir sous une tente','slang','cliche'),
(694,'fr','Il coupe une tomate en tranches.','Il coupe un concombre en tranches.','couper une tomate en fines tranches','couper un gâteau en tranches','chill','none'),
(695,'fr','Bientôt, tout le monde sourit.','Bientôt, tout le monde pleure.','sourire sur un ferry','sourire à la caméra','chill','none'),
(696,'fr','Il est perdu dans la fumée !','Il est perdu dans la neige !','un nuage de fumée grise','de la fumée de cheminée','dramatic','exaggeration'),
(698,'fr','Ce smoothie est trop violet.','Ce smoothie est trop vert.','un smoothie épais aux baies','un smoothie vert','slang','none'),
(700,'fr','L''escargot n''est pas pressé.','La grenouille n''est pas pressée.','un escargot sur une feuille','un escargot dans une assiette','chill','understatement'),
(701,'fr','Le serpent est sur un rocher noir.','Le serpent est sur un rocher blanc.','un serpent dans le sable','un serpent dans l''herbe','chill','none'),
(702,'fr','Baskets aux pieds, les escaliers ensuite.','Sandales aux pieds, les escaliers ensuite.','lacer des baskets bleu canard','nettoyer des baskets bleu canard','slang','none'),
(704,'fr','Il a éternué si fort que son chapeau est tombé !','Il a éternué si fort que sa chaussure est tombée !','éternuer à cause des pissenlits','éternuer à cause d''un chat','dramatic','exaggeration'),
(705,'fr','Elle n''arrête pas d''éternuer.','Elle n''arrête pas de chanter.','éternuer dans son coude','éternuer dans un mouchoir','dramatic','none'),
(706,'fr','De la neige sur la langue ? Miam !','De la pluie sur la langue ? Miam !','attraper la neige avec la langue','enlever la neige d''une voiture','slang','exclamation'),
(707,'fr','Snowboard orange stylé, mec.','Snowboard bleu stylé, mec.','attacher son snowboard','un snowboard en magasin','slang','none'),
(708,'fr','Mains pleines de boue ? Place au savon !','Pieds pleins de boue ? Place au savon !','un pain de savon','un flacon de savon','slang','exclamation'),
(711,'fr','Téléphone à 1 %. Prise trouvée !','Téléphone à 50 %. Prise trouvée !','une prise murale cachée','une douille d''ampoule','dramatic','exclamation'),
(712,'fr','Il a peur de son soda.','Il a peur de son sandwich.','une canette de soda à l''orange','un verre de soda au cola','low_iq','guessing'),
(713,'fr','Oh, salut ! Un ver dans la terre !','Oh, salut ! Une pièce dans la terre !','planter dans de la terre noire','de la terre sur le tapis','dramatic','exclamation'),
(714,'fr','Le soldat est de nouveau à la maison !','Le soldat est de nouveau en mer !','un soldat qui rentre chez lui','un soldat qui quitte la maison','dramatic','exclamation'),
(715,'fr','Quelqu''un lui a laissé un café.','Quelqu''un lui a laissé une pizza.','un mot de quelqu''un','la carte d''anniversaire de quelqu''un','chill','none'),
(716,'fr','Il mange avec une cuillère à soupe.','Il mange avec des baguettes.','manger avec une cuillère à soupe','remuer avec une cuillère à soupe','chill','none'),
(717,'fr','La soupe est brûlante !','La soupe est glacée !','une soupe de tomates chaude','une soupe de tomates froide','dramatic','exclamation'),
(718,'fr','Les oies volent vers le sud.','Les oies marchent vers le sud.','suivre les oiseaux vers le sud','rouler vers le sud','chill','none'),
(719,'fr','Waouh, l''espace est tellement vide !','Waouh, la mer est tellement vide !','des étoiles dans l''espace','un espace de stationnement','dramatic','exclamation'),
(720,'fr','Cette épice est vraiment forte.','Cette épice est vraiment verte.','une épice rouge en cône','un pot d''épices séchées','chill','none'),
(721,'fr','C''est elle qui a tout renversé !','C''est le garçon qui a tout renversé !','renverser un verre d''eau','renverser une tasse de café','dramatic','blaming_someone'),
(723,'fr','Le médecin lui montre la colonne vertébrale, os par os.','Le médecin lui montre le crâne, os par os.','les os de la colonne vertébrale','le dos d''un livre','nerd','none'),
(724,'fr','Chaque gerbe d''eau est plus grande !','Chaque gerbe d''eau est plus petite !','une énorme gerbe d''eau','une giclée de lait','dramatic','exclamation'),
(726,'fr','C''est le printemps, on tombe la veste.','C''est l''hiver, on tombe la veste.','le printemps sous les cerisiers','une pluie de printemps en ville','chill','none'),
(727,'fr','Elle a sprinté jusqu''à l''arrivée !','Elle a marché jusqu''à l''arrivée !','sprinter vers la ligne d''arrivée','sprinter pour attraper le bus','dramatic','exclamation'),
(729,'fr','L''écureuil prépare son plan pour l''hiver.','Le lapin prépare son plan pour l''hiver.','un écureuil avec un gland','un écureuil avec une pizza','business','guessing'),
(730,'fr','Le personnel pose ensemble.','Le personnel mange ensemble.','le personnel d''un restaurant au travail','le personnel d''un train','chill','none'),
(731,'fr','Il met un timbre dessus.','Il met une pièce dessus.','un timbre sur une enveloppe','un tampon dans un passeport','chill','none'),
(733,'fr','Deux États ont signé un traité.','Trois États ont signé un traité.','deux États signant un traité','un état de chaos','business','none'),
(734,'fr','Le chien veut ce steak, c''est clair.','Le chat veut ce steak, c''est clair.','un steak rosé à l''intérieur','un steak au congélateur','gossip','guessing'),
(735,'fr','La vapeur a embué ses lunettes !','La pluie a embué ses lunettes !','un nuage de vapeur','un nuage de fumée','dramatic','exclamation'),
(736,'fr','Salut, nouveau demi-frère !','Salut, nouvelle demi-sœur !','rencontrer un nouveau demi-frère','se battre avec un demi-frère','dramatic','exclamation'),
(737,'fr','Le beau-père de l''année a réparé le vélo.','Le beau-père de l''année a réparé la voiture.','un beau-père qui répare un vélo','un beau-père à un mariage','gossip','exaggeration'),
(738,'fr','Il a dessiné un cœur sur un post-it.','Il a dessiné une étoile sur un post-it.','un post-it avec un cœur','des post-it sur un écran','flirt','none'),
(739,'fr','Il s''est arrêté pour une pizza. Les règles, c''est les règles.','Il s''est arrêté pour des sushis. Les règles, c''est les règles.','s''arrêter pour une pizza','s''arrêter pour faire le plein','ironic','cliche'),
(740,'fr','Le chronomètre doit être cassé !','Le téléphone doit être cassé !','déclencher un chronomètre','déclencher l''appareil photo du téléphone','ironic','bad_excuse'),
(741,'fr','Grosse tempête dehors, thé dedans.','Grand soleil dehors, thé dedans.','regarder la tempête avec un thé','marcher dans la tempête','chill','none'),
(742,'fr','Les quatre feux de la cuisinière sont allumés.','Un seul feu de la cuisinière est allumé.','quatre feux sur une cuisinière','un petit réchaud de camping','business','none'),
(743,'fr','La route est complètement droite.','La route est complètement sinueuse.','une rangée de briques bien droite','une réponse directe','slang','none'),
(744,'fr','Elle a rencontré un inconnu avec un parapluie.','Elle a rencontré un inconnu avec un gros chien.','un inconnu avec un parapluie','un inconnu avec un vélo','gossip','none'),
(746,'fr','Ils sautent par-dessus le ruisseau !','Ils sautent par-dessus la clôture !','sauter par-dessus un ruisseau','nager dans un ruisseau','dramatic','exclamation'),
(749,'fr','Ils s''étirent ensemble.','Ils dansent ensemble.','s''étirer avant de courir','étirer un élastique','chill','none'),
(751,'fr','Être assortie ? Pas son style.','Des bottes violettes ? Pas son style.','son propre style audacieux','un style de musique','gossip','guessing'),
(752,'fr','Le sucre a sauvé son café !','Le lait a sauvé son café !','du sucre dans un café noir','du sucre sur un gâteau','dramatic','exaggeration'),
(753,'fr','Ce costume bleu lui va trop bien.','Ce costume gris lui va trop bien.','essayer un costume bleu','laver un costume bleu','flirt','none'),
(754,'fr','Son amie la soutient.','Son amie l''ignore.','soutenir son amie','soutenir une équipe de foot','chill','none'),
(755,'fr','Ici, chaque surface est lisse.','Ici, chaque surface est rugueuse.','une surface lisse et brillante','une surface pleine de rayures','chill','none'),
(756,'fr','Belle glisse sur cette planche de surf.','Belle glisse sur ce jet-ski.','farter une planche de surf blanche','une planche de surf en magasin','flirt','none'),
(757,'fr','Un chiot dans une boîte ! Quelle surprise !','Un chaton dans une boîte ! Quelle surprise !','une surprise dans une boîte','une fête surprise à la maison','dramatic','exclamation'),
(758,'fr','Le cygne fait sa toilette.','Le cygne mange un poisson.','un cygne sur un lac','un cygne sur l''herbe','chill','none'),
(759,'fr','Pluie dehors, pull dedans.','Soleil dehors, pull dedans.','enfiler un pull douillet','tricoter un pull douillet','chill','none'),
(760,'fr','Oh non ! Sa cheville enfle !','Oh non ! Son poignet enfle !','une cheville qui enfle','un poignet qui enfle','dramatic','none'),
(762,'fr','Non, non, peut-être… ce T-shirt !','Non, non, peut-être… cette veste !','enfiler un T-shirt bleu canard','plier un T-shirt bleu canard','slang','none'),
(763,'fr','La nappe s''envole.','Le rideau s''envole.','lancer une nappe en l''air','une nappe tachée de vin','chill','none'),
(764,'fr','Il dessine sur une tablette.','Il dessine sur une serviette en papier.','dessiner sur une tablette','un comprimé de médicament','chill','none'),
(766,'fr','Ce tatouage, c''est pour toujours !','Cet autocollant, c''est pour toujours !','un tatouage d''oiseau tout frais','un tatouage sur la jambe','dramatic','exclamation'),
(767,'fr','Les feuilles de thé dansent !','Les sachets de thé dansent !','servir du thé à la menthe','du thé au lait','dramatic','exclamation'),
(769,'fr','Les petites cuillères sont minuscules.','Les petites cuillères sont énormes.','remuer avec une petite cuillère','une cuillère à café de sucre','chill','none'),
(770,'fr','Elle a plongé pour une balle de tennis !','Elle a plongé pour une balle de golf !','plonger pendant un match de tennis','du tennis sur gazon','dramatic','exclamation'),
(771,'fr','Le terminal est immense.','Le terminal est minuscule.','un immense terminal vitré','un petit terminal de bus','chill','none'),
(772,'fr','La thérapie aide le client.','Le yoga aide le client.','une séance de thérapie','une séance de yoga','business','none'),
(773,'fr','Son thermomètre a pété un câble !','Sa montre a pété un câble !','un thermomètre dans la bouche','un thermomètre au mur','slang','exaggeration'),
(775,'fr','Autant de réflexion pour un seul coup !','Autant de réflexion pour un seul but !','grosse réflexion aux échecs','grosse réflexion aux cartes','slang','exclamation'),
(776,'fr','Une goutte pour une grosse soif.','Un biscuit pour une grosse soif.','une soif terrible','une soif d''aventure','ironic','understatement'),
(777,'fr','Il est trop assoiffé !','Il est trop affamé !','assoiffé au marché','assoiffé après un footing','slang','none'),
(778,'fr','Un fil long de plusieurs kilomètres !','Une corde longue de plusieurs kilomètres !','un long fil rouge','un fil de discussion','dramatic','exaggeration'),
(779,'fr','Cette loutre veut faire la sieste.','Ce chat veut faire la sieste.','une loutre endormie','une loutre dans une rivière','chill','guessing'),
(780,'fr','Les chats se tiennent debout comme des soldats !','Les chiens se tiennent debout comme des soldats !','des chats debout sur un lit','des chats debout sur une table','dramatic','exaggeration'),
(782,'fr','Deuxième essai, cravate parfaite.','Deuxième essai, gâteau parfait.','nouer une cravate bordeaux','acheter une cravate bordeaux','business','none'),
(783,'fr','Tigre mouillé, humeur pourrie !','Lion mouillé, humeur pourrie !','un tigre dans une rivière','un tigre dans un arbre','slang','guessing'),
(784,'fr','Elle incline le parapluie.','Elle ferme le parapluie.','incliner le parapluie','incliner la tête','chill','none'),
(786,'fr','Il est un peu fatigué.','Il n''est pas fatigué du tout.','fatigué après le travail','fatigué d''attendre','ironic','understatement'),
(787,'fr','Elle ne juge pas son amie.','Elle ne juge pas son chien.','ne pas juger une amie','juger un concours de cuisine','chill','none'),
(790,'fr','Joli travail avec cette tomate.','Joli travail avec cet oignon.','trancher une tomate bien mûre','planter une tomate','flirt','none'),
(791,'fr','Il a d''abord pris le mauvais outil.','Il a d''abord pris le bon outil.','choisir le bon outil','un outil de jardin','chill','none'),
(792,'fr','Beaucoup trop de dentifrice !','Beaucoup trop de shampoing !','une tour de dentifrice','un tube de dentifrice','dramatic','exaggeration'),
(793,'fr','Elle a posé la dernière pierre au sommet.','Elle a posé le dernier coquillage au sommet.','une pierre au sommet','le toit d''une voiture','chill','none'),
(794,'fr','Le garçon a gagné le tournoi !','Le marin a gagné le tournoi !','un tournoi de bras de fer','un tournoi d''échecs','dramatic','exclamation'),
(795,'fr','Le chien a droit à la serviette aussi !','Le chat a droit à la serviette aussi !','se sécher avec une serviette','s''allonger sur une serviette de plage','dramatic','exclamation'),
(797,'fr','Ils font la course sur la piste !','Ils font la course dans la piscine !','une piste d''athlétisme rouge','une voie ferrée','dramatic','exclamation'),
(798,'fr','Gang en survêtement dans la ruelle !','Gang en survêtement sur la plage !','des survêtements turquoise assortis','des survêtements sur une piste d''athlé','slang','exclamation'),
(800,'fr','Entraînement fini, jambes en compote.','Match fini, jambes en compote.','entraînement sous les projecteurs','dresser un chiot','slang','exaggeration'),
(801,'fr','Elle vole sur un trampoline !','Elle vole sur un lit !','sauter sur un trampoline','se cacher sous un trampoline','dramatic','exaggeration'),
(802,'fr','Il fait son LeBron sur une poubelle.','Il fait son LeBron sur une baignoire.','une poubelle en guise de panier','un couvercle de poubelle','slang','guessing'),
(804,'fr','Elle kiffe grave voyager.','Elle déteste grave voyager.','voyager en avion','voyager en bus','slang','none'),
(805,'fr','Voyage en train, juste à temps !','Voyage en bus, juste à temps !','un voyage à travers les Alpes','un voyage en bateau','dramatic','exclamation'),
(806,'fr','Elle porte les plateaux comme une pro.','Elle porte les cartons comme une pro.','un plateau tenu bien haut','un plateau par terre','slang','cliche'),
(807,'fr','Le tapis de course a failli gagner, frère.','Le vélo a failli gagner, frère.','courir sur un tapis de course','marcher sur un tapis de course','slang','guessing'),
(808,'fr','L''arbre est gigantesque !','Le rocher est gigantesque !','un vieil arbre gigantesque','une cabane dans un arbre','dramatic','exclamation'),
(809,'fr','Même le corgi suit la tendance !','Même le chat suit la tendance !','suivre la tendance du chapeau jaune','lancer une nouvelle tendance','gossip','exaggeration'),
(811,'fr','Trophée en l''air, confettis qui tombent !','Médaille en l''air, confettis qui tombent !','soulever un trophée doré','nettoyer un trophée doré','slang','exclamation'),
(812,'fr','Confiance totale : elle lâche le rocher !','Confiance totale : elle lâche la corde !','confiance en son partenaire','confiance en sa chance','dramatic','exclamation'),
(813,'fr','Le dindon pose comme une star.','L''oie pose comme une star.','un dindon sur la paille','une dinde dans une assiette','chill','exaggeration'),
(814,'fr','Elle éteint le ventilateur.','Elle éteint la télé.','éteindre la lumière','quitter la route','chill','none'),
(815,'fr','La tortue est dans la mer maintenant.','La tortue est dans une piscine maintenant.','une tortue sur la plage','une tortue dans un aquarium','chill','none'),
(816,'fr','Il a trop la classe en smoking.','Il a trop la classe en survêtement.','enfiler un smoking','louer un smoking','flirt','none'),
(817,'fr','Deux chats sont côte à côte.','Deux chiens sont côte à côte.','deux chats côte à côte','deux chats face à face','chill','none'),
(818,'fr','Sa frappe au clavier est ultra rapide !','Sa lecture est ultra rapide !','une frappe au clavier rapide','taper un SMS','slang','exclamation'),
(819,'fr','Joli parapluie. Il reste de la place pour moi ?','Jolie voiture. Il reste de la place pour moi ?','partager un parapluie','un parapluie sur la plage','flirt','banter'),
(821,'fr','Enfin chez soi : c''est l''heure des sous-vêtements !','Enfin chez soi : c''est l''heure du pyjama !','se mettre en sous-vêtements','acheter des sous-vêtements neufs','slang','exclamation'),
(823,'fr','L''écran affiche les chiffres.','L''écran affiche la météo.','montrer l''écran du doigt','nettoyer l''écran','business','none'),
(825,'fr','Le chien adore la vue aussi.','Le chat adore la vue aussi.','une vue sur des sommets rocheux','une vue sur la mer','low_iq','guessing'),
(826,'fr','Ils filment dans un bureau.','Ils filment dans une forêt.','filmer avec un travelling','filmer un mariage','chill','none'),
(827,'fr','Il y a plein d''animaux ici.','Il y a deux animaux ici.','des animaux dans un livre d''histoires','des animaux dans un vrai zoo','chill','none'),
(828,'fr','Un scoop ? Elle a l''air surprise.','Un scoop ? Il a l''air surpris.','surprise dans un café','surprise à la porte','gossip','guessing'),
(830,'fr','Elle explique les changements.','Elle explique le menu.','expliquer le design de l''appli','expliquer un problème de maths','business','none'),
(831,'fr','Elle fait un discours.','Elle fait un concert.','un discours au pupitre','un discours à un mariage','business','none'),
(832,'fr','Il déballe l''écharpe la plus longue du monde.','Il déballe la chaussette la plus longue du monde.','déballer une valise','déballer les courses','low_iq','exaggeration'),
(833,'fr','Déballage : le coquillage a survécu !','Déballage : la tasse a survécu !','le déballage après un voyage','le déballage d''un nouveau téléphone','dramatic','exclamation'),
(835,'fr','Le faux plombier s''est fait tremper !','Le faux plombier s''est enrichi !','un plombier à l''évier','un plombier sur le toit','dramatic','exclamation'),
(836,'fr','Il est très préparé. Trop préparé.','Elle est très préparée. Trop préparée.','un élève préparé','un plat préparé','ironic','exaggeration'),
(837,'fr','Ce taxi passe dans n''importe quelle ruelle.','Ce bus passe dans n''importe quelle ruelle.','un taxi dans une ruelle','un taxi à l''aéroport','ironic','exaggeration'),
(838,'fr','Le pilote se prend pour une star.','Le cuisinier se prend pour une star.','un pilote en blouson','un pilote dans un avion','gossip','guessing'),
(840,'fr','Il a randonné jusqu''en haut juste pour un selfie.','Il a nagé jusqu''au large juste pour un selfie.','randonner jusqu''à un lac','randonner jusqu''à une plage','ironic','guessing'),
(841,'fr','Elle a fait fondre la glace. Et maintenant ?','Elle a fait geler l''eau. Et maintenant ?','faire fondre des glaçons','faire fondre du chocolat','ironic','guessing'),
(843,'fr','Hisse ! Le panier monte tout en haut !','Hisse ! Le seau monte tout en haut !','hisser un panier en haut','hisser un bateau en haut','dramatic','exclamation'),
(844,'fr','Quelle immense vallée verte !','Quel immense désert vert !','une vallée verte en contrebas','une vallée sous la neige','dramatic','exclamation'),
(845,'fr','Encore un truc qui disparaît ! Merci, la mer.','Encore un truc qui disparaît ! Merci, le chien.','un dessin qui disparaît','un bateau qui disparaît','ironic','blaming_someone'),
(847,'fr','Leur victoire est nette.','Leur défaite est nette.','une victoire en course d''aviron','une victoire aux échecs','chill','none'),
(848,'fr','Du vinaigre ? Sa tête dit non !','Du miel ? Sa tête dit non !','un filet de vinaigre','nettoyer au vinaigre','slang','exclamation'),
(849,'fr','Il a eu son visa !','Il a perdu son visa !','un visa dans un passeport','un visa pour des vacances','dramatic','exclamation'),
(850,'fr','Le volcan fume. Pas de panique.','La cheminée fume. Pas de panique.','un volcan qui fume','un volcan sous la mer','ironic','understatement'),
(851,'fr','Elle attend. Et elle attend.','Elle danse. Et elle danse.','attendre le bus','attendre un taxi','low_iq','exaggeration'),
(852,'fr','Le serveur est hyper rapide !','Le serveur est hyper lent !','un serveur avec des assiettes','un serveur avec la carte','slang','exclamation'),
(853,'fr','Elle marche dans le parc.','Elle court dans le parc.','marcher au bord du lac','promener le chien','chill','none'),
(857,'fr','Il a trouvé son portefeuille et a eu une fleur.','Il a trouvé son portefeuille et a eu un gâteau.','rendre un portefeuille perdu','voler un portefeuille perdu','gossip','none'),
(859,'fr','L''armoire l''a attaquée !','Le frigo l''a attaquée !','une armoire pleine de manteaux','une armoire pleine de chaussures','dramatic','blaming_someone'),
(860,'fr','La voiture avait besoin d''un « petit » lavage.','Le vélo avait besoin d''un « petit » lavage.','le lavage d''une voiture boueuse','le lavage d''un chien boueux','ironic','understatement'),
(861,'fr','Sa montre dit : en retard !','Son téléphone dit : en retard !','regarder sa montre','acheter une montre','dramatic','exclamation'),
(862,'fr','Pas de visionnage télé sans pop-corn.','Pas de visionnage télé sans pizza.','une soirée de visionnage télé','une soirée d''observation des oiseaux','chill','cliche'),
(863,'fr','Sa gourde est en métal.','Sa gourde est en plastique.','remplir une gourde','une gourde dans le lit','chill','none'),
(866,'fr','Un arc-en-ciel à la cascade !','Un arc-en-ciel au lac !','une haute cascade en Islande','une cascade dans un jardin','dramatic','exclamation'),
(867,'fr','Le basilic aime l''arrosage.','La rose aime l''arrosage.','l''arrosage des tomates','l''arrosage de la pelouse','chill','guessing'),
(869,'fr','Elle porte un poids.','Elle porte un carton.','un gros poids rond','perdre du poids rapidement','chill','none'),
(870,'fr','Le soleil se couche à l''ouest.','Le soleil se couche à l''est.','regarder le soleil partir à l''ouest','rouler vers l''ouest la nuit','chill','none'),
(874,'fr','La perruque rose lui va super bien.','Le chapeau rose lui va super bien.','mettre une perruque rose','brosser une perruque rose','flirt','none'),
(875,'fr','Le vent lui a volé son écharpe !','Le vent lui a volé son chapeau !','une écharpe dans le vent','le vent qui souffle la neige','dramatic','blaming_someone'),
(876,'fr','Du vin rouge au coucher du soleil ? La classe.','De la bière fraîche au coucher du soleil ? La classe.','un verre de vin rouge','une bouteille de vin blanc','flirt','cliche'),
(878,'fr','L''hiver, c''est luge à fond !','L''hiver, c''est ski à fond !','une journée d''hiver en luge','une journée d''hiver à l''intérieur','slang','exclamation'),
(879,'fr','Le loup hurle !','Le loup dort !','un loup dans la neige','un loup sur une plage','dramatic','exclamation'),
(880,'fr','L''agneau porte sa propre laine !','L''agneau porte un bonnet en laine !','une pelote de laine','une couverture en laine','dramatic','exaggeration'),
(882,'fr','Le chien est son coach d''entraînement.','Le chat est son coach d''entraînement.','un entraînement complet','un entraînement sur la plage','low_iq','exaggeration'),
(886,'fr','Mamie a mérité ses rides.','La fille a mérité ses rides.','de profondes rides sur son visage','des plis sur une chemise','chill','none'),
(887,'fr','Elle écrit dans son journal intime.','Elle écrit sur son ordi portable.','écrire dans un journal intime','écrire sur un mur','chill','none'),
(888,'fr','Bâiller est contagieux, même pour les chiens.','Rire est contagieux, même pour les chiens.','bâiller dans la cuisine','bâiller dans la voiture','nerd','cliche'),
(891,'fr','Oups, cette voiture est chère !','Oups, ce vélo est cher !','une déco de voiture chère','un lavage auto cher','slang','exclamation'),
(893,'fr','Fermeture éclair remontée, direction la neige.','Fermeture éclair remontée, direction le soleil.','remonter la fermeture éclair d''une veste','remonter la fermeture éclair d''une valise','chill','none'),
(894,'fr','La fermeture éclair est coincée !','Le ski est coincé !','une fermeture éclair de veste coincée','une fermeture éclair de tente','dramatic','exclamation'),
(895,'fr','Gros bouchon. Peut-être un accident ?','Grosse fête. Peut-être un accident ?','un accident sur l''autoroute','un accident dans la cuisine','dramatic','guessing'),
(898,'fr','L''actrice tourne sur elle-même.','L''actrice dort.','une actrice sur le tournage','une actrice sur une affiche','chill','none'),
(899,'fr','C''est un après-midi ensoleillé.','C''est un après-midi enneigé.','un après-midi au parc','un après-midi à la plage','chill','none'),
(900,'fr','L''agent est au téléphone.','L''agent est dans le bus.','un agent au téléphone','une agence de voyages','business','none'),
(901,'fr','Il respire l''air frais, les bras grands ouverts.','Il respire l''air de la ville, les bras grands ouverts.','l''air frais de la montagne','l''air frais en ville','chill','none'),
(902,'fr','Elle fait coucou à l''avion !','Elle fait coucou au train !','un avion qui passe bas','un avion en papier','dramatic','exclamation'),
(904,'fr','Elle a une allergie au pollen.','Elle a une allergie à la poussière.','une allergie au pollen','une allergie aux chats','chill','none'),
(905,'fr','Un chat traverse la ruelle.','Un chien traverse la ruelle.','une ruelle pavée étroite','une ruelle pleine de boutiques','chill','none'),
(907,'fr','Il y a quelqu''un ? Que des pigeons.','Il y a quelqu''un ? Que des chats.','quelqu''un dans la gare','quelqu''un à la fête','chill','understatement'),
(909,'fr','Il demande s''il y a quelqu''un.','Elle demande s''il y a quelqu''un.','demander s''il y a quelqu''un','demander si quelqu''un a faim','chill','none'),
(911,'fr','Un appartement lumineux et ensoleillé.','Un appartement sombre et lugubre.','un appartement moderne et lumineux','un bureau moderne et lumineux','chill','none'),
(912,'fr','L''architecte a un plan.','L''architecte a un marteau.','un architecte avec des plans','un architecte à la plage','business','none'),
(913,'fr','Son bras est levé bien haut.','Son bras est baissé bien bas.','un bras tendu vers le haut','un bras en écharpe','chill','none'),
(914,'fr','Il adore ce fauteuil !','Il adore ce canapé !','se laisser tomber dans un fauteuil','se laisser tomber dans une piscine','dramatic','exclamation'),
(917,'fr','Le grenier est plein de bazar.','Le grenier est plein d''eau.','un vieux grenier poussiéreux','un grenier neuf et lumineux','slang','none'),
(918,'fr','Le public applaudit.','Le public s''en va.','un public qui applaudit','un public de télé','business','none'),
(919,'fr','Sa tante, c''est une marrante.','Son oncle, c''est un marrant.','danser avec sa tante','faire du shopping avec sa tante','slang','none'),
(920,'fr','De la balançoire en Autriche ? Objectif de vie.','Du ski en Autriche ? Objectif de vie.','se balancer en Autriche','skier en Autriche','slang','cliche'),
(921,'fr','Il sert un gâteau autrichien.','Il sert une bière autrichienne.','un café autrichien','une brasserie autrichienne','business','none'),
(926,'fr','Le pain du boulanger est prêt !','La pizza du boulanger est prête !','un boulanger devant le four','un boulanger à la caisse','dramatic','exclamation'),
(929,'fr','Il enroule un bandage.','Il emballe un cadeau.','enrouler un bandage blanc','enrouler une écharpe blanche','chill','none'),
(934,'fr','Plouf ! Elle est dans la baignoire.','Plouf ! Elle est dans la piscine.','barboter dans une baignoire','barboter dans une flaque','slang','exclamation'),
(938,'fr','Elle fait le lit.','Elle fait un gâteau.','faire le lit','aller au lit','chill','none'),
(939,'fr','Oreiller en l''air ! Soirée dans la chambre !','Oreiller en l''air ! Soirée dans la cuisine !','une chambre lumineuse en bazar','une cuisine lumineuse en bazar','slang','exclamation'),
(941,'fr','Des pigeons ont attaqué son banc !','Des canards ont attaqué son banc !','une femme sur un banc','un banc à la gare','dramatic','exaggeration'),
(942,'fr','Il fait du vélo.','Il fait de la trottinette.','un vélo en automne','un vélo dans la neige','chill','none'),
(943,'fr','Il colle une affiche sur un panneau publicitaire.','Il peint un panneau publicitaire.','un panneau publicitaire géant vierge','un panneau publicitaire sur un bus','chill','none'),
(944,'fr','Il a oublié d''utiliser ses jumelles.','Il a oublié d''utiliser son télescope.','des jumelles noires sur la poitrine','des jumelles noires sur une table','ironic','guessing'),
(947,'fr','Son nez saigne.','Son genou saigne.','un nez qui saigne','un genou qui saigne','chill','none'),
(948,'fr','Des baies dans le mixeur ? Miam !','Des cerises dans le mixeur ? Miam !','remplir un mixeur','nettoyer un mixeur','slang','none'),
(949,'fr','Aïe, une ampoule au talon !','Aïe, une ampoule à l''orteil !','une ampoule au talon','une ampoule à la main','dramatic','exclamation'),
(950,'fr','Il donne son sang.','Il donne une conférence.','une poche de sang donné','du sang sur une chemise blanche','chill','none'),
(952,'fr','Il rame dans un bateau en bois.','Il rame dans un bateau pneumatique.','ramer dans un bateau en bois','un bateau dans un port','chill','none'),
(953,'fr','La frontière est ouverte pour la voiture.','La frontière est ouverte pour le bus.','un poste-frontière','une bordure de fleurs','business','none'),
(954,'fr','Le chef fait une présentation.','Le chef fait un cadeau.','un chef en réunion','un chef à une fête','business','none'),
(956,'fr','Elle étudie une maquette de cerveau.','Elle étudie une maquette de cœur.','une maquette de cerveau','une image de cerveau','chill','none'),
(957,'fr','Un rouge-gorge est posé sur la branche.','Une chouette est posée sur la branche.','une balançoire sur une branche','une balançoire au parc','chill','none'),
(958,'fr','La mariée est prête !','Le marié est prêt !','une mariée avec des roses blanches','une mariée avec des roses rouges','dramatic','exclamation'),
(959,'fr','Elle marche sous un pont.','Elle marche sur un pont.','un immense pont suspendu','un petit pont en bois','chill','none'),
(960,'fr','Elle balaie avec un balai.','Elle balaie avec un râteau.','un balai en paille','un balai de sorcière','chill','none'),
(963,'fr','Le maçon construit un mur.','Le maçon construit un toit.','un maçon avec une truelle','un maçon avec un marteau','chill','none'),
(965,'fr','La truelle du maçon est pleine.','Le seau du maçon est plein.','une truelle pleine de mortier','une truelle pleine de terre','chill','none'),
(967,'fr','Ce chauffeur de bus est trop content.','Ce chauffeur de taxi est trop content.','un chauffeur de bus souriant','un chauffeur de bus en grève','ironic','exaggeration'),
(970,'fr','Le boucher coupe du bœuf.','Le boucher coupe du pain.','un boucher qui découpe du bœuf','un boucher qui vend du poisson','chill','none'),
(973,'fr','Un oiseau s''est posé sur le cactus.','Une abeille s''est posée sur le cactus.','un oiseau sur un cactus','un cactus en pot','chill','none'),
(974,'fr','C''est un petit café animé.','C''est un petit café vide.','un café cosy et ensoleillé','un café fermé','chill','none'),
(977,'fr','Elle vise avec son appareil photo.','Elle vise avec son téléphone.','un appareil photo vintage','une caméra de surveillance','chill','none'),
(980,'fr','Le capitaine est à la barre.','Le capitaine est au bar.','un capitaine à la barre','un capitaine d''équipe de foot','chill','none'),
(981,'fr','Voiture verte, vue sur la mer, la grande classe.','Voiture verte, vue sur la ville, la grande classe.','une voiture verte de collection','une voiture familiale verte','flirt','exaggeration'),
(983,'fr','Le caissier scanne un bocal.','Le caissier scanne une canette.','un caissier à la caisse','un caissier à la banque','chill','none'),
(986,'fr','Une chenille déjeune.','Un escargot déjeune.','une chenille qui mange une feuille','une chenille sur une fleur','chill','understatement'),
(989,'fr','Elle enregistre son sac.','Elle enregistre son chien.','s''enregistrer à l''aéroport','s''enregistrer à l''hôtel','business','none'),
(990,'fr','Le chef utilise une pince.','Le chef utilise une cuillère.','un chef qui dresse une assiette','un chef qui goûte la soupe','chill','none'),
(995,'fr','Son camarade de classe connaît un secret.','Son prof connaît un secret.','chuchoter à un camarade de classe','un camarade de classe au tableau','chill','guessing'),
(996,'fr','Des mains façonnent de l''argile humide.','Des mains façonnent du sable humide.','façonner un pot en argile','peindre un pot en argile','chill','none'),
(998,'fr','Les papiers volent, l''employé de bureau tamponne toujours.','Les papiers volent, l''employé de bureau dort toujours.','un employé de bureau qui tamponne','un réceptionniste d''hôtel','dramatic','exaggeration'),
(1000,'fr','Le climat se réchauffe.','Le climat se refroidit.','un climat de montagne qui change','un climat d''île tropicale','nerd','none'),
(1001,'fr','La clinique est prête à vous accueillir.','L''école est prête à vous accueillir.','la salle d''attente d''une clinique','une clinique pour chiens','business','none'),
(1003,'fr','Juste un nuage aujourd''hui.','Juste deux nuages aujourd''hui.','un gros nuage blanc','un nuage de pluie gris','chill','understatement'),
(1004,'fr','L''entraîneur ne chuchote pas.','L''entraîneur ne crie pas.','un entraîneur avec un sifflet','un car plein de touristes','chill','understatement'),
(1006,'fr','La cafetière est trop lente.','Le grille-pain est trop lent.','une cafetière qui goutte','une cafetière neuve','chill','blaming_someone'),
(1007,'fr','Deux collègues discutent.','Deux collègues mangent.','des collègues devant un tableau blanc','des collègues à une fête','chill','none'),
(1008,'fr','La communauté fait des plantations.','La communauté fait de la peinture.','le jardin de la communauté','une communauté de gamers','business','none'),
(1010,'fr','Elle s''est fait un contact utile.','Elle a passé un coup de fil utile.','un nouveau contact professionnel','un contact dans son téléphone','business','none'),
(1011,'fr','Ce cuisinier a besoin de deux cuillères !','Ce cuisinier a besoin de deux casseroles !','un cuisinier qui goûte le plat','un cuisinier qui lit une recette','dramatic','exclamation'),
(1012,'fr','Elle tousse si fort !','Elle rit si fort !','tousser dans son coude','tousser dans un mouchoir','dramatic','exclamation'),
(1013,'fr','Deux cousins rient aux éclats.','Deux cousins pleurent à chaudes larmes.','deux cousins sur l''herbe','deux cousins à table','chill','none'),
(1015,'fr','Il se tient le mollet.','Il se tient la tête.','se tenir le mollet','nourrir un veau','chill','none'),
(1017,'fr','Une femme est sur le passage piéton.','Un chien est sur le passage piéton.','traverser au passage piéton','un passage piéton sous la pluie','chill','none'),
(1022,'fr','Ce coussin a perdu le combat.','Ce canapé a perdu le combat.','regonfler un coussin','s''asseoir sur un coussin','ironic','exaggeration'),
(1026,'fr','Une bière tchèque ? Oui, s''il te plaît !','Un vin tchèque ? Oui, s''il te plaît !','une brasserie tchèque','une cave à vin tchèque','slang','exclamation'),
(1028,'fr','Elle est en Tchéquie.','Il est en Tchéquie.','coucher de soleil en Tchéquie','neige en Tchéquie','chill','none'),
(1030,'fr','Des fleurs de la part de sa fille !','Des fleurs de la part de son fils !','des fleurs offertes par une fille','des fleurs offertes à une fille','dramatic','exclamation'),
(1033,'fr','Le désert n''a pas de fin !','La forêt n''a pas de fin !','des chameaux dans le désert','de la neige dans le désert','dramatic','exaggeration'),
(1035,'fr','Il ne voit pas sa destination.','Il ne voit pas la circulation.','loin de la destination','arriver à destination','ironic','guessing'),
(1037,'fr','Plus de détergent, plus de mousse.','Plus de détergent, zéro mousse.','verser du détergent vaisselle','du détergent pour le linge','slang','cliche'),
(1040,'fr','Bientôt, ils seront divorcés.','Bientôt, ils seront mariés.','bientôt divorcés','bientôt mariés','gossip','guessing'),
(1041,'fr','Le vertige la frappe de plein fouet.','Le vertige le frappe de plein fouet.','une vague de vertige','des vertiges sur un bateau','dramatic','none'),
(1043,'fr','L''arc du dauphin mérite dix points !','L''arc du phoque mérite dix points !','l''arc d''un dauphin qui saute','l''arc d''un arc-en-ciel','slang','exaggeration'),
(1048,'fr','Cet haltère est super lourd.','Cet haltère est super léger.','soulever un haltère lourd','un haltère par terre','slang','exaggeration'),
(1050,'fr','Des tulipes sur un vélo ? Trop néerlandais !','Du fromage sur un vélo ? Trop néerlandais !','de hautes maisons néerlandaises','un marché au fromage néerlandais','slang','cliche'),
(1057,'fr','L''employeur serre des mains.','L''employeur se lave les mains.','un employeur accueillant','un employeur en colère','business','none'),
(1064,'fr','Tout le monde applaudit !','Tout le monde dort !','tout le monde lève les bras','tout le monde s''assoit','dramatic','exclamation'),
(1067,'fr','C''est un vrai expert en montres.','C''est un vrai expert en vin.','un expert en montres','un expert à la télé','chill','none'),
(1069,'fr','Cet œil est vert-marron.','Cet œil est bleu vif.','un œil ouvert','un œil fermé','chill','none'),
(1070,'fr','Elle a un visage rieur.','Elle a un visage en larmes.','un visage rieur','un visage endormi','chill','none'),
(1071,'fr','Le fermier travaille tard.','Le fermier fait la grasse matinée.','un fermier avec une fourche','un fermier avec une vache','chill','guessing'),
(1076,'fr','Un doigt touche une goutte.','Un doigt touche une abeille.','un doigt qui touche une goutte','un doigt près d''une abeille','chill','none'),
(1078,'fr','Le pompier est de service.','Le pompier est en vacances.','un pompier avec une lance','un pompier avec un chat','business','none'),
(1079,'fr','Il donne les premiers secours.','Il donne des indications.','une trousse de premiers secours ouverte','un cours de premiers secours','chill','none'),
(1082,'fr','Le pêcheur a attrapé plein de poissons !','Le pêcheur n''a rien attrapé !','un pêcheur avec un filet','un pêcheur avec une canne','slang','exclamation'),
(1084,'fr','Le vol vient de décoller.','Le vol vient d''atterrir.','un vol juste après le décollage','une volée de marches','business','none'),
(1085,'fr','Elle passe la serpillière sur un sol en bois.','Elle passe la serpillière sur un sol en pierre.','un grand sol en bois','le premier étage','business','none'),
(1088,'fr','Un pied nu dans l''herbe.','Un pied nu dans la neige.','un pied nu dans l''herbe','un pied dans une chaussette','chill','none'),
(1096,'fr','Elle est dans une galerie blanche.','Elle est dans une cuisine blanche.','se promener dans une galerie','se promener dans un magasin','chill','none'),
(1097,'fr','Elle ferme le garage.','Elle ferme la fenêtre.','fermer la porte du garage','ouvrir la porte du garage','chill','none'),
(1100,'fr','Le jardinier coupe des roses.','Le jardinier coupe l''herbe.','un jardinier avec des roses','un jardinier avec une tondeuse','chill','none'),
(1104,'fr','Quel gentleman !','Quelle grande dame !','un gentleman qui soulève son chapeau','un gentleman qui ferme la porte','flirt','exclamation'),
(1107,'fr','Il serre sa copine dans ses bras.','Il porte sa copine.','serrer sa copine dans ses bras','une copine au téléphone','flirt','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
