begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(1110,'fr','Des bisous de la petite-fille !','Des bisous du petit-fils !','le bisou d''une petite-fille','le dessin d''une petite-fille','slang','exclamation'),
(1112,'fr','Grand-mère fait du pain.','Grand-mère fait de la soupe.','faire du pain avec grand-mère','tricoter avec grand-mère','chill','none'),
(1115,'fr','Danser en Grèce ? Joli style.','Plonger en Grèce ? Joli style.','danser en Grèce','nager en Grèce','flirt','none'),
(1116,'fr','Le marié la porte dans ses bras.','Le marié porte un gâteau dans ses bras.','un marié portant sa mariée','un marié brossant un cheval','flirt','none'),
(1119,'fr','Le guide mène la visite.','Le guide mène la course.','un guide avec un parapluie','un guide de montagne qui grimpe','business','none'),
(1120,'fr','Ce mec lance ses clés, trop stylé.','Ce mec lance son téléphone, trop stylé.','un mec avec une pizza','un mec avec une guitare','slang','none'),
(1123,'fr','Son couloir, c''est une piste de danse !','Sa cuisine, c''est une piste de danse !','danser dans un couloir','courir dans un couloir','slang','exclamation'),
(1125,'fr','Les bateaux se reposent au port.','Les bateaux se reposent sur la plage.','des bateaux au port','des bateaux sur le canal','chill','none'),
(1126,'fr','Le travail lui a donné mal à la tête.','La musique lui a donné mal à la tête.','un mal de tête la nuit','un mal de tête au soleil','chill','blaming_someone'),
(1127,'fr','Que de la santé et du bonheur !','Que de la pluie et de l''obscurité !','plein de santé et de joie','un bilan de santé','dramatic','cliche'),
(1129,'fr','Le médecin tient un cœur !','Le médecin tient un cerveau !','une maquette de cœur','une maquette de cerveau','dramatic','exclamation'),
(1131,'fr','Les deux talons sont décollés du sol.','Les deux talons sont posés au sol.','lever les deux talons','porter des talons hauts','chill','none'),
(1133,'fr','L''aide tient son sac.','L''aide tient son chien.','une aide avec son sac','une aide dans la cuisine','chill','none'),
(1134,'fr','Devine qui déjeune sur la colline ? Les moutons.','Devine qui déjeune sur la colline ? Les vaches.','un arbre sur la colline','une maison sur la colline','gossip','guessing'),
(1135,'fr','Elle a la main sur la hanche.','Elle a la main sur la tête.','une main sur la hanche','une main sur l''épaule d''un homme','chill','none'),
(1138,'fr','Journée calme à l''hôpital.','Journée calme à l''aéroport.','un couloir d''hôpital lumineux','un service d''hôpital plein','gossip','guessing'),
(1139,'fr','L''hôte porte un toast.','L''hôte fait un gâteau.','un hôte qui lève son verre','un animateur de télé','business','none'),
(1143,'fr','Il n''y a qu''un seul humain ici.','Il n''y a qu''un seul chameau ici.','un humain dans le désert','une foule d''humains','ironic','understatement'),
(1144,'fr','Le chasseur est à genoux.','Le chasseur court.','un chasseur avec des jumelles','un chasseur avec un fusil','chill','none'),
(1147,'fr','Il a une infection au coude.','Il a une infection au genou.','une infection au coude','une infection à l''œil','chill','none'),
(1148,'fr','L''injection est prête. Fuis !','Le pansement est prêt. Fuis !','un plateau pour une injection','un plateau prêt pour le dîner','low_iq','exclamation'),
(1149,'fr','Insomnie : lui contre le plafond.','Insomnie : lui contre le frigo.','l''insomnie en pleine nuit','l''insomnie avant un examen','ironic','exaggeration'),
(1151,'fr','Son fer à repasser crache de la vapeur.','Sa bouilloire crache de la vapeur.','un fer à repasser fumant','un portail en fer','business','none'),
(1152,'fr','On déplie une planche à repasser.','On déplie une chaise de plage.','installer une planche à repasser','s''asseoir sur une planche à repasser','chill','none'),
(1154,'fr','Le journaliste veut des réponses.','Le médecin veut des réponses.','un journaliste avec un dictaphone','un journaliste à son bureau','gossip','guessing'),
(1156,'fr','Le perroquet est le boss de cette jungle.','Le singe est le boss de cette jungle.','un perroquet dans la jungle','un perroquet en cage','slang','exaggeration'),
(1158,'fr','L''eau de la bouilloire est chaude. Sans blague ?','L''eau du robinet est chaude. Sans blague ?','verser l''eau de la bouilloire','une bouilloire sur la gazinière','low_iq','understatement'),
(1159,'fr','Voici la clé de votre chambre.','Voici la clé de votre voiture.','une clé de chambre d''hôtel','une clé de voiture','business','none'),
(1160,'fr','La cuisine est bien équipée.','La cuisine est presque vide.','une cuisine lumineuse','une cuisine sombre','business','none'),
(1163,'fr','La dame porte des gants blancs.','La dame porte des gants noirs.','une dame dans l''escalier','une dame au bar','chill','none'),
(1166,'fr','Elle déplace une grande lampe.','Elle déplace une grande plante.','une lampe de table','une lampe de jardin','chill','none'),
(1167,'fr','L''avocat a plein de livres.','L''avocat a plein de chats.','un avocat avec un dossier','un avocat au tribunal','chill','none'),
(1170,'fr','La bibliothécaire est sur une échelle.','La bibliothécaire est sur une table.','une bibliothécaire sur une échelle','une bibliothécaire devant un ordinateur','chill','none'),
(1173,'fr','Un éclair frappe la mer !','Un éclair frappe un arbre !','un éclair au-dessus de la mer','un éclair au-dessus d''une ville','dramatic','exclamation'),
(1175,'fr','Le pop-corn vole partout dans le salon.','Le pop-corn vole partout dans la cuisine.','des amis dans un salon','des amis dans une salle d''attente','slang','exaggeration'),
(1178,'fr','Le perdant est sous une serviette.','Le perdant est sous une table.','le perdant du match','le perdant de la course','dramatic','none'),
(1180,'fr','L''étiquette à bagage est vierge.','L''étiquette à bagage est rouge.','attacher une étiquette à bagage','couper une étiquette à bagage','chill','none'),
(1183,'fr','Un athlète masculin rame.','Une athlète féminine rame.','un rameur masculin','un nageur masculin','chill','none'),
(1188,'fr','Tout juste mariés et ils dansent déjà.','Tout juste mariés et ils se disputent déjà.','un couple marié qui danse','un couple marié qui se dispute','chill','none'),
(1189,'fr','Ils portent un matelas.','Ils portent un piano.','un matelas dans l''escalier','un matelas par terre','chill','none'),
(1193,'fr','Ouvre grand pour le médicament.','Ouvre grand pour la glace.','un médicament liquide sur une cuillère','des médicaments dans un pilulier','chill','cliche'),
(1195,'fr','Une tortilla mexicaine volante !','Un taco mexicain volant !','un stand de rue mexicain','un restaurant mexicain','dramatic','exclamation'),
(1198,'fr','Le mannequin assure sur le podium.','Le mannequin assure sur la plage.','un mannequin sur un podium','un mannequin de vitrine','slang','exaggeration'),
(1200,'fr','Elle adore ce matin ensoleillé.','Elle adore ce matin pluvieux.','un matin ensoleillé','un matin pluvieux','chill','guessing'),
(1202,'fr','Mère et bébé : nez contre nez.','Mère et chien : nez contre nez.','une mère qui soulève son bébé','une mère qui nourrit son bébé','chill','none'),
(1203,'fr','Sa moto fait des étincelles !','Son scooter fait des étincelles !','une moto dans un virage','une moto au garage','dramatic','exclamation'),
(1206,'fr','De la boue vole partout !','De la neige vole partout !','une chaussure dans la boue épaisse','une chaussure dans la neige fraîche','dramatic','exclamation'),
(1208,'fr','Un dinosaure au musée !','Une baleine au musée !','un dinosaure dans un musée','un musée d''art moderne','dramatic','exclamation'),
(1211,'fr','Toute une nation chante d''une seule voix.','Toute une nation danse comme un seul homme.','une nation qui chante ensemble','une nation d''amateurs de café','dramatic','cliche'),
(1213,'fr','Grosses vagues, grosse nausée.','Petites vagues, grosse nausée.','la nausée sur une mer agitée','la nausée après un gros repas','dramatic','none'),
(1214,'fr','Elle s''étire le cou.','Elle s''étire la jambe.','un long cou étiré','une écharpe autour du cou','chill','none'),
(1216,'fr','Vélo, tulipes, moulins. Oui, les Pays-Bas.','Voiture, tulipes, moulins. Oui, les Pays-Bas.','des tulipes aux Pays-Bas','un marché aux Pays-Bas','chill','cliche'),
(1218,'fr','Il n''y a personne sur l''aire de jeux. Flippant !','Il y a des enfants sur l''aire de jeux. Flippant !','personne sur les balançoires','personne sur la plage','dramatic','exclamation'),
(1219,'fr','Personne n''est venu. Super soirée.','Tout le monde est venu. Super soirée.','personne à table','une table pleine de monde','ironic','understatement'),
(1221,'fr','L''officier fait le salut militaire.','L''officier danse.','un officier qui salue','un officier qui conduit','chill','none'),
(1225,'fr','Le peintre adore vraiment le bleu canard.','Le peintre adore vraiment le rose.','un peintre sur une échelle','un peintre devant un chevalet','chill','guessing'),
(1227,'fr','Mode parent : jogging.','Mode parent : sieste.','un parent à côté d''un vélo','un parent qui répare un vélo','slang','cliche'),
(1230,'fr','Le passager dort profondément.','Le passager est bien réveillé.','un passager de train endormi','un passager dans un taxi','chill','none'),
(1232,'fr','Le patient inspire.','Le patient déjeune.','un patient qui respire profondément','un patient au lit','chill','none'),
(1233,'fr','Le piéton a un café.','Le piéton a un chien.','un piéton avec un café','un pont pour piétons','chill','none'),
(1237,'fr','Un passage piéton « bondé » : une seule personne.','Un passage piéton « bondé » : un seul chien.','une personne sur le passage piéton','une personne dans le bus','ironic','understatement'),
(1238,'fr','La pharmacie a plein de bocaux.','La pharmacie a plein de jouets.','une vieille pharmacie chaleureuse','une pharmacie avec une croix verte','chill','none'),
(1241,'fr','Le photographe est allongé dans la rue mouillée !','Le photographe est debout dans la rue mouillée !','un photographe par terre','un photographe en studio','dramatic','exclamation'),
(1242,'fr','Elle accroche un tableau.','Elle accroche un miroir.','un tableau au mur','une image sur son téléphone','chill','none'),
(1248,'fr','La planète a des anneaux !','La planète n''a pas d''anneaux !','une planète à anneaux','une planète sur une carte','dramatic','exclamation'),
(1254,'fr','Le plombier répare un tuyau.','Le plombier répare une porte.','un plombier sous un évier','un plombier sur un toit','chill','none'),
(1255,'fr','C''est l''hiver en Pologne.','C''est l''été en Pologne.','une place enneigée en Pologne','une plage de sable en Pologne','chill','none'),
(1256,'fr','Le policier sourit.','Le policier pleure.','un policier qui montre du doigt','un policier qui court','chill','none'),
(1258,'fr','Elle a fait des pierogi polonais.','Elle a fait des saucisses polonaises.','des pierogi polonais alignés','des saucisses polonaises sur le grill','chill','none'),
(1260,'fr','Elle court au Portugal.','Elle fait du vélo au Portugal.','courir au Portugal','prendre le tram au Portugal','chill','none'),
(1262,'fr','De la cannelle sur les flans portugais !','Du chocolat sur les flans portugais !','des pastéis de nata portugais','des sardines portugaises','dramatic','exclamation'),
(1263,'fr','Le facteur distribue des lettres.','Le facteur distribue des pizzas.','un facteur à une porte','un facteur dans sa camionnette','business','none'),
(1266,'fr','Le président parle et les flashs crépitent !','Le président chante et les flashs crépitent !','un président qui fait un discours','un président qui serre des mains','dramatic','exclamation'),
(1267,'fr','Elle a l''air très professionnelle.','Elle a l''air très endormie.','un look professionnel','une athlète professionnelle','flirt','none'),
(1268,'fr','Le professeur donne un cours.','Le professeur dort.','un professeur en plein cours','le bureau d''un professeur','chill','none'),
(1270,'fr','Elle saute à pieds joints dans une flaque.','Elle saute à pieds joints dans la neige.','sauter dans une flaque','une flaque de lait renversé','chill','none'),
(1274,'fr','Un immense arc-en-ciel sur les collines.','Un immense arc-en-ciel sur la mer.','un arc-en-ciel sur des collines vertes','un arc-en-ciel sur une ville','chill','none'),
(1275,'fr','Il gratte son éruption cutanée.','Il se gratte la tête.','gratter une éruption cutanée rouge','une éruption cutanée sur le visage','chill','none'),
(1278,'fr','La réception a une sonnette en laiton.','La réception a une lampe en laiton.','une clé à la réception','une réception de mariage','business','none'),
(1286,'fr','Un ouvrier déblaie le toit.','Un ouvrier peint le toit.','un toit de maison en tuiles','un toit de gare en verre','business','none'),
(1287,'fr','Une pièce vide ? Place à la danse !','Un magasin vide ? Place à la danse !','une pièce vide et ensoleillée','une plage vide et ensoleillée','slang','exclamation'),
(1299,'fr','Il adore son scanner, apparemment.','Il déteste son scanner, apparemment.','un patient qui passe un scanner','un scanner à l''aéroport','ironic','guessing'),
(1303,'fr','Quelle balade stylée en scooter !','Quelle balade stylée à vélo !','un scooter en Italie','un scooter sur la plage','flirt','exaggeration'),
(1304,'fr','La secrétaire est débordée !','La secrétaire s''ennuie ferme !','une secrétaire débordée','une secrétaire en vacances','dramatic','exclamation'),
(1305,'fr','Une graine de haricot tombe.','Un petit caillou tombe.','planter une graine de haricot','un oiseau qui mange des graines','chill','none'),
(1306,'fr','Le vendeur est très content.','Le vendeur est très en colère.','un vendeur de légumes','un vendeur de livres','chill','none'),
(1307,'fr','Le domestique a un plateau en argent.','Le domestique a une clochette en argent.','un domestique avec un plateau','un domestique dans une cuisine','chill','none'),
(1308,'fr','Même son ombre danse !','Même son amie danse !','une ombre géante sur le mur','une ombre sous un arbre','dramatic','exclamation'),
(1311,'fr','Elle fait signe à un immense navire !','Elle fait signe à un tout petit navire !','saluer un grand navire','saluer depuis un grand navire','dramatic','exclamation'),
(1312,'fr','La vendeuse a un manteau.','La vendeuse a un chapeau.','une vendeuse au travail','une vendeuse en pause','business','none'),
(1314,'fr','Son épaule a besoin d''un examen.','Son genou a besoin d''un examen.','examiner une épaule','un sac sur l''épaule','business','none'),
(1315,'fr','Douche à effet pluie ? Plutôt une cascade !','Douche de jardin ? Plutôt une cascade !','une grande douche à effet pluie','un rideau de douche','dramatic','exaggeration'),
(1317,'fr','Il est sur un trottoir en pierre.','Il est sur un trottoir en bois.','un large trottoir en pierre','un trottoir plein de monde','business','none'),
(1319,'fr','Elle est célibataire et heureuse.','Elle est célibataire et triste.','heureuse d''être célibataire','une seule tasse de thé','chill','none'),
(1321,'fr','Voici votre plat, monsieur.','Voici votre addition, monsieur.','votre plat, monsieur','votre addition, monsieur','business','none'),
(1323,'fr','Quel gratte-ciel immense !','Quel phare immense !','lever les yeux vers un gratte-ciel','regarder en bas depuis un gratte-ciel','dramatic','exclamation'),
(1325,'fr','Elle dort. L''oreiller est son ami.','Elle dort. Le chat est son ami.','dormir sur un lit','dormir dans un train','low_iq','guessing'),
(1326,'fr','Chaussons tout doux, matin paresseux.','Chaussettes toutes douces, matin paresseux.','enfiler des chaussons tout doux','des chaussons tout doux en magasin','chill','none'),
(1327,'fr','Il porte un costume folklorique slovaque.','Elle porte un costume folklorique slovaque.','une tenue folklorique slovaque','un maillot de foot slovaque','chill','none'),
(1328,'fr','Elle danse en Slovaquie !','Elle nage en Slovaquie !','une prairie en Slovaquie','une plage en Slovaquie','dramatic','exclamation'),
(1337,'fr','Ils jouent sur le canapé.','Ils jouent par terre.','des amis sur un canapé gris','des amis dans un bus gris','chill','none'),
(1340,'fr','Quelqu''un part en douce.','Quelqu''un danse en douce.','quelqu''un qui s''éloigne','quelqu''un qui promène un chien','gossip','guessing'),
(1344,'fr','L''araignée est au travail.','La fourmi est au travail.','une araignée dans sa toile','une araignée dans la baignoire','business','none'),
(1346,'fr','Le boxeur crache de l''eau.','Le boxeur boit de l''eau.','cracher de l''eau dans un seau','cracher son chewing-gum','chill','none'),
(1347,'fr','Une main presse une éponge.','Une main presse un citron.','une éponge savonneuse pressée','une éponge de mer','chill','none'),
(1350,'fr','Elle traverse la place. Salut, les pigeons !','Elle traverse la rivière. Salut, les pigeons !','courir sur une place','s''asseoir sur une place calme','slang','none'),
(1353,'fr','Une étoile brillante. Fais un vœu !','Une lune brillante. Fais un vœu !','montrer une étoile brillante','une étoile sur un sapin','slang','exclamation'),
(1354,'fr','Encore en retard à la gare !','Encore en retard à l''aéroport !','traverser une gare en courant','dormir à la gare','dramatic','guessing'),
(1355,'fr','Les mains sur le volant.','Les mains sur le téléphone.','les mains sur le volant','le volant d''un bateau','chill','none'),
(1358,'fr','Sa belle-mère lui tresse les cheveux.','Sa belle-mère lui coupe les cheveux.','une belle-mère qui tresse des cheveux','une belle-mère à l''école','chill','none'),
(1359,'fr','Les demi-sœurs n''arrêtent pas de rire.','Les demi-sœurs n''arrêtent pas de pleurer.','des demi-sœurs qui rient ensemble','des demi-sœurs qui partagent un lit','gossip','exaggeration'),
(1360,'fr','Elle utilise un stéthoscope. Chut !','Elle utilise un thermomètre. Chut !','écouter au stéthoscope','un stéthoscope sur une table','dramatic','exclamation'),
(1363,'fr','Cette pierre va nager, non ?','Cette feuille va nager, non ?','une pierre au-dessus d''un lac','une pierre dans un mur','low_iq','guessing'),
(1365,'fr','Un inconnu l''interpelle.','Un policier l''interpelle.','un inconnu à capuche','un inconnu avec un chien','dramatic','none'),
(1366,'fr','Une feuille fait du surf sur le ruisseau.','Une grenouille fait du surf sur le ruisseau.','un ruisseau limpide en forêt','un ruisseau plein de poissons','low_iq','exaggeration'),
(1367,'fr','Elle traverse une rue animée.','Elle traverse un pont animé.','une rue animée de grande ville','une rue de village calme','business','none'),
(1369,'fr','Il pleut ? Il danse avec un lampadaire !','Il pleut ? Il danse avec un feu rouge !','une rangée de lampadaires allumés','une rangée de bougies allumées','dramatic','exclamation'),
(1371,'fr','Le métro va super vite.','Le métro va super lentement.','une rame de métro qui file','un plan de métro','slang','exaggeration'),
(1372,'fr','Sa valise est grise et pratique.','Sa valise est rouge et pratique.','tirer une valise grise','remplir une valise grise','business','none'),
(1375,'fr','La sueur gicle de son gant !','La sueur gicle de sa chaussure !','de la sueur sur son bras','de la sueur sur un t-shirt','dramatic','exclamation'),
(1378,'fr','Elle mange une fondue suisse.','Elle mange du chocolat suisse.','une fondue suisse au fromage','une fondue suisse au chocolat','chill','none'),
(1379,'fr','Quelqu''un a trouvé l''interrupteur. Bravo.','Quelqu''un a trouvé le téléphone. Bravo.','un interrupteur au mur','un aiguillage ferroviaire','low_iq','exaggeration'),
(1380,'fr','Suisse : même les vaches ont droit à la musique.','Suisse : même les chèvres ont droit à la musique.','un cor des Alpes en Suisse','une boutique de cloches en Suisse','chill','exaggeration'),
(1383,'fr','Le tailleur répare une veste.','Le tailleur répare une chaussure.','un tailleur avec un mètre ruban','un tailleur qui vend des chaussures','chill','none'),
(1385,'fr','De l''eau qui sort du robinet ! Waouh !','De l''eau qui sort du tuyau d''arrosage ! Waouh !','tourner le robinet','une tape sur l''épaule','low_iq','exclamation'),
(1386,'fr','Le chauffeur de taxi fait coucou !','Le chauffeur de taxi dort !','un chauffeur de taxi qui salue','un chauffeur de taxi de nuit','slang','exclamation'),
(1389,'fr','Elle verse des larmes.','Il verse des larmes.','une larme sur sa joue','une larme sur sa robe','dramatic','none'),
(1390,'fr','Il veut toucher la lune.','Il veut toucher le soleil.','tendre la main vers la lune','une lune au-dessus de la mer','dramatic','guessing'),
(1394,'fr','Un grand soleil orange sur la mer.','Un grand soleil orange sur la neige.','le soleil sur la mer','le soleil sur les montagnes','chill','none'),
(1396,'fr','Tout le théâtre est à elle !','Tout le théâtre est à lui !','un vieux théâtre vide','un théâtre plein de monde','dramatic','exaggeration'),
(1398,'fr','Son thermomètre est énorme !','Sa brosse à dents est énorme !','un grand thermomètre en verre','un thermomètre au mur','dramatic','exclamation'),
(1400,'fr','On lui examine la gorge.','On lui examine l''oreille.','une lumière dans la gorge','se racler la gorge','business','none'),
(1403,'fr','Ces orteils adorent la plage !','Ces orteils adorent la neige !','des orteils dans le sable mouillé','des orteils dans l''herbe douce','dramatic','exaggeration'),
(1404,'fr','Sa langue attrape de la neige pour le déjeuner.','Sa main attrape de la neige pour le déjeuner.','tirer la langue','se mordre la langue','low_iq','guessing'),
(1405,'fr','Chaque dent est contrôlée, une par une.','Chaque ongle est contrôlé, un par un.','examiner une dent','la petite souris','business','none'),
(1410,'fr','Elle attend à un feu de circulation.','Elle attend à un arrêt de bus.','attendre à un feu de circulation','attendre à la gare','chill','none'),
(1411,'fr','Vieux tramway, grand sourire, super style.','Vieux bus, grand sourire, super style.','un vieux tramway vert','un vieux bus vert','flirt','none'),
(1413,'fr','Tapis de course : courir pour aller nulle part.','Tapis de course : marcher pour aller nulle part.','courir sur un tapis de course','réparer un tapis de course cassé','ironic','cliche'),
(1414,'fr','Waouh, le chêne est énorme !','Waouh, le palmier est énorme !','un chêne énorme','un énorme panier de pique-nique','low_iq','exclamation'),
(1415,'fr','Il monte dans son camion.','Il monte dans sa voiture.','un gros camion argenté','un gros bus argenté','chill','none'),
(1416,'fr','Il sort d''un tunnel.','Il sort d''un garage.','la sortie d''un tunnel routier','l''entrée d''un tunnel ferroviaire','chill','none'),
(1419,'fr','Jumelles, même robe. C''était prévu ?','Jumelles, même chapeau. C''était prévu ?','des jumelles en robes assorties','des jumeaux dans un landau','gossip','guessing'),
(1420,'fr','Le meilleur oncle du monde !','La meilleure tante du monde !','sur les épaules de son oncle','sur le vélo de son oncle','slang','exaggeration'),
(1422,'fr','Une main montre l''écran du doigt.','Une main montre la fenêtre du doigt.','montrer un écran du doigt','montrer la porte du doigt','chill','none'),
(1424,'fr','Le collègue debout est en bleu.','Le collègue debout est en rouge.','collègue en chemise bleue','collègue en chemise rouge','chill','none'),
(1425,'fr','Devine qui est en laisse.','Devine qui est sur le canapé.','un chien en laisse','un chien sans laisse','gossip','none'),
(1427,'fr','Il garde l''équilibre sur une corde !','Il garde l''équilibre sur un tronc !','garder l''équilibre sur une fine corde','garder l''équilibre sur une fine branche','dramatic','exclamation'),
(1429,'fr','Il chante pour ses amis.','Il danse pour ses amis.','chanter dans un micro','chanter sous la douche','chill','none'),
(1432,'fr','Il chante en costume. La pantoufle de verre est prête.','Il danse en costume. La pantoufle de verre est prête.','chanter en costume','acheter un costume','gossip','guessing'),
(1433,'fr','On danse à la maison, rien d''anormal.','On dîne à la maison, rien d''anormal.','danser en costume','danser sur scène','chill','understatement'),
(1434,'fr','Personne ne voit le voleur sur le lustre.','Personne ne voit le voleur sur le toit.','un voleur avec un sac','un voleur avec une arme','ironic','guessing'),
(1435,'fr','Il ne veut pas partager le micro.','Il ne veut pas partager la guitare.','un micro sur pied','le micro d''un téléphone','ironic','guessing'),
(1436,'fr','Les gens sont d''âges divers.','Les gens sont tous ados.','cinq portraits divers','cinq paysages divers','chill','none'),
(1438,'fr','Il enregistre un podcast.','Elle enregistre un podcast.','enregistrer un podcast','écouter un podcast','chill','none'),
(1441,'fr','Sa victoire valait bien tous ces efforts.','Sa victoire valait bien tout cet argent.','ça vaut l''effort','un effort pour rester éveillée','chill','none'),
(1442,'fr','Ce bureau est plein de plantes.','Ce bureau est plein de chiens.','un bureau ouvert et lumineux','un bureau sombre et vide','business','none'),
(1446,'fr','La conférence est bondée !','La conférence est vide !','une salle de conférence bondée','une conférence en visio','dramatic','exclamation'),
(1447,'fr','Le vaccin fait un peu mal.','Le vaccin chatouille un peu.','un vaccin dans le bras','un vaccin dans la jambe','chill','understatement'),
(1450,'fr','Des fleurs d''un visiteur. Trop mignon.','Des bonbons d''un visiteur. Trop mignon.','un visiteur avec des fleurs','un visiteur au musée','flirt','none'),
(1451,'fr','Cette vitamine la fait rire.','Cette vitamine la fait pleurer.','une vitamine orange à mâcher','une vitamine verte à mâcher','gossip','guessing'),
(1452,'fr','Le volcan est un peu énervé.','Le volcan est un peu endormi.','un volcan en éruption la nuit','un volcan couvert de neige','ironic','understatement'),
(1453,'fr','Le navire fait un long voyage en mer.','Le navire fait un voyage sur un fleuve.','un long voyage en mer','un voyage le long du fleuve','chill','none'),
(1457,'fr','La serveuse sert un milkshake.','La serveuse sert une pizza.','une serveuse qui sert le petit-déj','une serveuse qui prend son petit-déj','business','none'),
(1458,'fr','Le marcheur a un chien au pelage doré.','Le marcheur a un chien noir.','un marcheur avec des bâtons','un marcheur avec une poussette','chill','none'),
(1459,'fr','Il peint le mur en blanc.','Il peint le mur en bleu.','un grand mur nu','un mur autour d''un jardin','chill','none'),
(1466,'fr','Pluie ou soleil ? Le temps n''arrive pas à se décider.','Neige ou soleil ? Le temps n''arrive pas à se décider.','un temps changeant sur une colline','un temps ensoleillé à la plage','ironic','guessing'),
(1467,'fr','Un mécanicien fait rouler une roue.','Un mécanicien lave une roue.','faire rouler une roue de voiture','une roue de vélo','business','none'),
(1468,'fr','À fond dans un fauteuil roulant de course !','À fond dans un kart de course !','un fauteuil roulant de course','une rampe pour fauteuil roulant','dramatic','exclamation'),
(1477,'fr','La radiographie montre les os d''une main.','La radiographie montre les os d''un pied.','une radiographie de main','une radiographie de pied','nerd','none'),
(1479,'fr','C''est l''heure du déjeuner au zoo.','C''est l''heure du déjeuner à la ferme.','une girafe au zoo','un lion au zoo','business','none'),
(1481,'fr','Le château a deux arches.','Le château a quatre arches.','une arche sous les marches','une arche au-dessus de la rivière','chill','none'),
(1482,'fr','Superbes boucles d''oreilles en or !','Superbes boucles d''oreilles en argent !','de grandes boucles d''oreilles en or','des boucles d''oreilles dans un écrin','flirt','exclamation'),
(1483,'fr','Les fraises sont rouges.','Les fraises sont vertes.','un plant de fraises','un milkshake à la fraise','chill','none'),
(1484,'fr','Cette musique n''a pas de bouton play.','Ce poème n''a pas de bouton play.','une vieille partition de musique','une vieille boîte à musique','ironic','exaggeration'),
(1485,'fr','Ils veulent vendre la maison.','Ils veulent vendre la voiture.','vendre une maison blanche','vendre une voiture rouge','chill','none'),
(1487,'fr','Le dieu a un trône doré.','Le dieu a un trône argenté.','un dieu sur un trône','un roi à cheval','chill','none'),
(1488,'fr','Des chevaux tirent un carrosse.','Des bœufs tirent un carrosse.','un carrosse royal doré','un wagon de train doré','chill','none'),
(1489,'fr','Le meilleur ami de la fée ? Une grenouille.','Le meilleur ami de la fée ? Un chat.','une fée sur la mousse','une fée dans le ciel','gossip','guessing'),
(1491,'fr','Tant de papillons !','Tant d''oiseaux !','des papillons au-dessus des fleurs','des papillons sur une chemise','dramatic','exaggeration'),
(1495,'fr','Fait : une licorne a une seule corne.','Fait : une licorne a deux cornes.','une licorne cabrée','une licorne endormie','nerd','cliche'),
(1497,'fr','Le violon repose sur une vieille partition.','La guitare repose sur une vieille partition.','un violon avec des roses','un cours de violon','chill','none'),
(1498,'fr','Deux mecs en montgolfière. Ciao !','Deux mecs à cheval. Ciao !','une montgolfière avec deux hommes','une montgolfière avec deux chiens','slang','none'),
(1499,'fr','Les tiges sont longues et bouclées.','Les tiges sont courtes et épaisses.','de longues tiges en spirale','des tiges dans un vase','nerd','none'),
(1501,'fr','Elle verse un liquide vert.','Elle verse un liquide rouge.','verser depuis un grand bol','verser du thé dans une tasse','chill','none'),
(1504,'fr','Le philosophe a une barbe.','Le philosophe a un chapeau.','un philosophe barbu','un philosophe qui rit','chill','none'),
(1505,'fr','Virée au supermarché, style années 50.','Virée à la boulangerie, style années 50.','une caisse de supermarché','un parking de supermarché','slang','cliche'),
(1508,'fr','L''église a un haut clocher.','L''église a un tout petit clocher.','une vieille église en pierre','un vieux pont en pierre','business','none'),
(1510,'fr','Pourquoi le personnage crie ?','Pourquoi le personnage chante ?','crier sur un pont','crier dans des montagnes russes','low_iq','guessing'),
(1513,'fr','Les mains jointes pour prier.','Les mains jointes pour applaudir.','les mains jointes pour prier','prier les mains ouvertes','chill','none'),
(1514,'fr','La religion dans un vieux tableau.','La religion dans une BD moderne.','un tableau sur la religion','un livre sur la religion','nerd','none'),
(1519,'fr','Ses fleurs sont trop jolies.','Ses plumes sont trop jolies.','de jolies fleurs dans ses cheveux','de jolis rubans dans ses cheveux','flirt','none'),
(1520,'fr','Cheveux bouclés et perles ? La classe.','Cheveux courts et perles ? La classe.','de longs cheveux blonds bouclés','un chien au poil bouclé','flirt','none'),
(1522,'fr','Elle a un panier de cerises.','Elle a un panier de pommes.','un panier de cerises','un chien dans un panier','chill','none'),
(1523,'fr','Des cheveux blonds pleins de fleurs.','Des cheveux noirs pleins de fleurs.','de longs cheveux blonds ondulés','des cheveux blonds courts','chill','none'),
(1525,'fr','Le train fonce sur nous !','Le camion fonce sur nous !','un train à vapeur noir','s''entraîner pour une course','dramatic','exclamation'),
(1526,'fr','Le guerrier a un casque.','Le guerrier a un bouclier.','un guerrier samouraï','un guerrier à cheval','chill','none'),
(1527,'fr','La cathédrale a un immense dôme.','La cathédrale a un toit plat.','un dôme de cathédrale baroque','une chorale de cathédrale qui chante','chill','none'),
(1528,'fr','Des ballons au-dessus du Japon !','Des oiseaux au-dessus du Japon !','des symboles du Japon','une carte du Japon','dramatic','exclamation'),
(1529,'fr','Deux tours, un volcan.','Deux tours, deux volcans.','deux tours de château rondes','deux hauts châteaux d''eau','chill','none'),
(1530,'fr','La ville est sur une colline. Belle vue, paraît-il.','La ville est au bord de la mer. Belle vue, paraît-il.','une vieille ville perchée','une ville balnéaire récente','gossip','none'),
(1531,'fr','Une arche encadre l''église.','Un arbre encadre l''église.','une grande arche pointue','une grande tour pointue','chill','none'),
(1534,'fr','Waouh, une corne sur chaque cheval !','Waouh, deux cornes sur chaque cheval !','la longue corne d''une licorne','le klaxon bruyant d''une voiture','low_iq','exclamation'),
(1535,'fr','Il est à l''envers. Trop facile.','Il est allongé. Trop facile.','en équilibre à l''envers','suspendu à l''envers','slang','understatement'),
(1537,'fr','Le pharaon d''Égypte a un arc.','Le pharaon d''Égypte a une épée.','un pharaon d''Égypte','une pyramide en Égypte','chill','none'),
(1538,'fr','Elle est entre deux colonnes.','Elle est entre deux arbres.','deux colonnes décorées','une colonne dans un journal','chill','none'),
(1541,'fr','Mini chapelle, ambiance neige.','Mini chapelle, ambiance soleil.','une chapelle blanche sous la neige','une chapelle pleine d''invités','slang','none'),
(1543,'fr','Elle tient un gros chou.','Elle tient une grosse citrouille.','un potager plein de choux','un chou dans une marmite','chill','none'),
(1544,'fr','Elle étend le linge.','Elle accroche les drapeaux.','étendre du linge blanc','plier du linge blanc','chill','none'),
(1545,'fr','Le col de la reine est énorme !','Le chien de la reine est énorme !','une reine avec un sceptre','une reine avec une épée','gossip','none'),
(1547,'fr','Le saint homme réfléchit intensément.','Le saint homme rit aux éclats.','un saint homme qui réfléchit','un saint homme qui prie','chill','none'),
(1548,'fr','Il y a des gens à chaque fenêtre.','Il y a des chats à chaque fenêtre.','une famille à chaque fenêtre','un chat à chaque fenêtre','chill','none'),
(1549,'fr','Quelqu''un a renversé toute la peinture !','Quelqu''un a renversé tout le lait !','des coulures de peinture','un pot de peinture','dramatic','blaming_someone'),
(1551,'fr','Le ciel nous a envoyé une guitare !','Le ciel nous a envoyé un violon !','brandir une guitare','accorder une guitare','dramatic','exclamation'),
(1554,'fr','Le moine a un parapluie rouge.','Le moine a un parapluie noir.','un moine en rose','un moine en noir','chill','none'),
(1555,'fr','Le personnage tient une grande épée.','Le personnage tient une grande lance.','tenir une épée à la verticale','une épée au mur','chill','none'),
(1559,'fr','Des tournesols remplissent un vase jaune.','Des roses remplissent un vase jaune.','des tournesols dans un vase','des tournesols dans un champ','chill','none'),
(1560,'fr','Elle est debout près d''une balançoire.','Elle est debout près d''un portail.','une balançoire en corde','une danse swing','chill','none'),
(1562,'fr','Le cowboy chevauche vers le coucher du soleil.','Le cowboy chevauche vers la mer.','un cowboy à cheval','un cowboy sur un taureau','dramatic','cliche'),
(1565,'fr','Elle est faite d''engrenages rouillés.','Elle est faite de chaînes rouillées.','des engrenages en métal rouillé','des chaînes en métal rouillé','chill','none'),
(1567,'fr','L''avion prend de l''altitude !','L''avion descend !','un avion qui monte','un avion qui descend','dramatic','exclamation'),
(1568,'fr','Le bateau navigue sous la lune.','Le bateau navigue sous le soleil.','naviguer la nuit','naviguer au soleil','chill','none'),
(1574,'fr','Une lanterne pend à une branche.','Une lanterne pend à un toit.','une lanterne au bout d''une chaîne','une lanterne à la main','chill','none'),
(1575,'fr','Le couple s''enlace.','Le couple se dispute.','un couple sous la lune','un couple sur une plage','chill','none'),
(1576,'fr','Dans son rêve, elle se balance à la lune.','Dans son rêve, elle se balance à un arbre.','un rêve de lune','un rêve de mer','chill','guessing'),
(1579,'fr','Les smartphones ont construit une maison.','Les livres ont construit une maison.','une maison de smartphones','un smartphone dans une poche','chill','exaggeration'),
(1583,'fr','L''astronaute s''envole !','Le pilote s''envole !','un astronaute dans l''espace','un astronaute sur la lune','dramatic','exclamation'),
(1584,'fr','Sa jupe danse aussi.','Son chien danse aussi.','danser en jupe rouge','danser sous la pluie','chill','exaggeration'),
(1585,'fr','Il y a cinq roses blanches.','Il y a cinq roses rouges.','cinq roses blanches en fleur','des roses blanches dans un vase','chill','none'),
(1586,'fr','De la pollution où qu''on regarde.','Des fleurs où qu''on regarde.','la pollution d''une usine','la pollution d''un navire','dramatic','exaggeration'),
(1589,'fr','Cette personne a l''air triste.','Cette personne a l''air heureuse.','un personnage triste aux cheveux orange','un personnage triste aux cheveux bleus','chill','none'),
(1590,'fr','La capuche est pleine d''étoiles.','La capuche est pleine de fleurs.','une capuche étoilée','une capuche sur les yeux','chill','none'),
(1591,'fr','Ce phare a des rayures.','Ce phare a des pois.','un phare rayé','une cabane de plage rayée','chill','none'),
(1592,'fr','Le robot a les lèvres bleues. Il a froid ?','Le robot a les lèvres rouges. Il a froid ?','une tête de robot en métal','un robot aspirateur','low_iq','guessing'),
(1595,'fr','Deux pyramides. Très pointues.','Deux tours. Très pointues.','deux pyramides marron','une pyramide d''oranges','low_iq','none'),
(1596,'fr','La lune brille sur la Russie.','Le soleil brille sur la Russie.','une église en Russie','un palais en Russie','chill','none'),
(1597,'fr','Oups, il a la tête sous l''eau !','Oups, il a la tête dans le sable !','un chien sous l''eau','un chien hors de l''eau','dramatic','exclamation'),
(1598,'fr','Jésus lève une main.','Jésus lève les deux mains.','Jésus qui bénit','Jésus qui porte la croix','chill','none'),
(1600,'fr','Un petit bateau est sur le canal.','Un grand navire est sur le canal.','un bateau sur le canal','un bateau sur le lac','chill','none'),
(1603,'fr','On extrait du pétrole en pleine mer.','On extrait du pétrole sur une colline.','une plateforme pétrolière en mer','de l''huile dans une poêle','business','none'),
(1609,'fr','Elle fait du ballet sur un rocher !','Elle fait du ballet sur un bateau !','du ballet sur un rocher','du ballet en studio','dramatic','exclamation'),
(1610,'fr','La lune éclaire le balcon.','Une lampe éclaire le balcon.','un balcon au clair de lune','un balcon ensoleillé','dramatic','none'),
(1611,'fr','Une colombe vole dans la lumière.','Un corbeau vole dans la lumière.','une colombe aux ailes déployées','une colombe en cage','chill','none'),
(1612,'fr','Des enfants de Corée font coucou.','Des enfants de Corée dansent.','des enfants de Corée qui saluent','des enfants de Corée qui chantent','chill','none'),
(1614,'fr','Des taureaux courent en Espagne !','Des chevaux courent en Espagne !','des taureaux qui courent en Espagne','une course de chevaux en Espagne','dramatic','exclamation'),
(1620,'fr','Le paradis a l''air bien chargé aujourd''hui.','Le paradis a l''air bien vide aujourd''hui.','des chérubins qui volent au paradis','un paradis plein de saints','ironic','exaggeration'),
(1623,'fr','Tant de gratte-ciel !','Tant de ponts !','des gratte-ciel au crépuscule','un gratte-ciel en construction','dramatic','exclamation'),
(1629,'fr','Un seul ananas. Si seul.','Une seule banane. Si seule.','un ananas debout, tout seul','un ananas coupé en tranches','dramatic','exaggeration'),
(1630,'fr','La pieuvre a huit bras. J''ai compté.','La pieuvre a six bras. J''ai compté.','une pieuvre à huit bras','une pieuvre dans un bocal','low_iq','none'),
(1631,'fr','La sorcière a un balai. Malin.','La sorcière a un chat. Malin.','une sorcière avec son balai','une sorcière sur son balai','low_iq','none'),
(1633,'fr','Cette statue te regarde.','Ce chien te regarde.','une statue de gargouille','une statue de cheval','gossip','guessing'),
(1635,'fr','Queue de sirène ? Carrément verte.','Queue de sirène ? Carrément bleue.','une sirène de dessin animé souriante','une sirène sur un rocher','slang','none'),
(1638,'fr','Des rideaux encadrent une mer au clair de lune.','Des rideaux encadrent une mer ensoleillée.','de lourds rideaux violets','de lourds tapis violets','dramatic','none'),
(1639,'fr','Fait : le bébé est dans une étable.','Fait : le bébé est dans un château.','un bébé dans une étable','un cheval dans une étable','nerd','none'),
(1641,'fr','Un clown effrayant et un corbeau.','Un clown effrayant et un chat.','des yeux effrayants dans le ciel','un film effrayant à la télé','chill','none'),
(1642,'fr','Le ciel du village est rouge.','Le ciel du village est bleu.','un village au coucher du soleil','un village sous la neige','business','none'),
(1643,'fr','Il porte un chapeau de cowboy.','Il porte une casquette de baseball.','un grand chapeau de cowboy','un grand chapeau de paille','chill','none'),
(1644,'fr','Le chevalier porte une armure complète.','Le chevalier ne porte pas d''armure.','un chevalier en armure de métal','un chevalier sans armure','chill','none'),
(1647,'fr','Il y a une femme sur la carte postale.','Il y a un homme sur la carte postale.','une vieille carte postale déchirée','une carte postale de plage','chill','none'),
(1649,'fr','Tout est coloré ici !','Tout est gris ici !','un chemin arc-en-ciel coloré','un parapluie coloré','dramatic','exclamation'),
(1650,'fr','Joli château, falaise flippante.','Joli château, pont flippant.','un château sur une falaise','une falaise au-dessus de la mer','gossip','understatement'),
(1651,'fr','Sa cape bleue est pleine d''étoiles.','Sa cape rouge est pleine d''étoiles.','une cape bleue étoilée','une cape en plumes','chill','none'),
(1652,'fr','Elle va toucher le papillon !','Elle va toucher l''oiseau !','toucher un papillon lumineux','attraper un papillon lumineux','dramatic','guessing'),
(1653,'fr','Le chat veut le poisson rouge...','Le chat veut l''oiseau...','un poisson rouge dans un bocal','un poisson rouge dans un bassin','dramatic','guessing'),
(1655,'fr','Waouh, sa couronne est trop haute !','Waouh, sa couronne est trop petite !','une haute couronne dorée','une petite couronne argentée','low_iq','exclamation'),
(1656,'fr','Ses lèvres sont rouges.','Ses lèvres sont bleues.','des lèvres rouges brillantes','des lèvres sur un verre','chill','none'),
(1658,'fr','Pierre sombre, roses rouges, stylé.','Pierre sombre, roses blanches, stylé.','une arche gothique sombre','un chemin sombre en forêt','slang','none'),
(1660,'fr','Un coffre plein de trésors !','Un coffre plein de bouteilles !','un coffre au trésor ouvert','une carte au trésor en papier','dramatic','exclamation'),
(1661,'fr','L''heure est un peu floue.','La carte est un peu floue.','lire l''heure','une machine à remonter le temps','chill','understatement'),
(1664,'fr','Le prêtre écoute.','Le prêtre chante.','un prêtre au confessionnal','un prêtre à un mariage','chill','none'),
(1665,'fr','Elle est dans un temple antique.','Elle est dans un château antique.','un temple égyptien antique','un temple grec antique','chill','none'),
(1666,'fr','Un cobra trône sur le pharaon.','Un faucon trône sur le pharaon.','un pharaon de profil','un pharaon sur un trône','nerd','none'),
(1667,'fr','Paris la nuit. Pure magie !','Paris à midi. Pure magie !','Paris la nuit','Paris sous la pluie','dramatic','exclamation'),
(1669,'fr','Deux ailes, mais la statue ne peut pas voler.','Quatre ailes, mais la statue ne peut pas voler.','deux ailes à plumes','deux ailes d''avion','low_iq','understatement'),
(1670,'fr','Un bus rouge à Londres. Classique.','Une voiture rouge à Londres. Classique.','un bus rouge à Londres','un bus rouge à Paris','chill','cliche'),
(1674,'fr','Ciel violet, collines violettes.','Ciel violet, collines vertes.','un ciel violet étoilé','un champ de fleurs violettes','chill','none'),
(1675,'fr','Il se tient seul près d''un arbre.','Il se tient seul près d''une maison.','seul dans un champ vide','seul dans une pièce vide','dramatic','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
