begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(2652,'fr','Tout est gris sauf son manteau !','Tout est rouge sauf son manteau !','des manteaux gris sous la pluie','des manteaux gris sous la neige','dramatic','exclamation'),
(2654,'fr','Sangles attachées, cap sur la Lune.','Sangles attachées, cap sur la mer.','de larges sangles blanches','un bracelet de montre en cuir','chill','guessing'),
(2656,'fr','Deux bus rouges. Très Londres.','Deux trams rouges. Très Londres.','un bus rouge à impériale','un tram rouge à impériale','slang','cliche'),
(2657,'fr','L''oiseau fait partie d''un collage.','Le chat fait partie d''un collage.','un oiseau dans un collage','un collage de vieilles photos','chill','none'),
(2658,'fr','Il lève le poing !','Il lève son épée !','un poing levé','un poing plein de pièces','dramatic','exclamation'),
(2663,'fr','Son ombre est si longue !','Son ombre est si courte !','la longue ombre d''un cow-boy','une ombre sur le mur','dramatic','exclamation'),
(2664,'fr','Quelqu''un se noie pour un abonné de plus.','Quelqu''un nage pour un abonné de plus.','se noyer dans l''océan','se noyer sous les devoirs','ironic','exaggeration'),
(2669,'fr','Un million de théières, je te jure.','Un million de lampes, je te jure.','des étagères de théières en porcelaine','une théière sur le feu','gossip','exaggeration'),
(2670,'fr','La table a un seul tiroir.','La table a trois tiroirs.','un tiroir avec un bouton','un tiroir plein de chaussettes','chill','none'),
(2673,'fr','Lui est dans la cage, l''oiseau est libre.','L''oiseau est dans la cage, lui est libre.','assis dans une cage','nettoyer une cage','ironic','none'),
(2675,'fr','Le chat a une patte sur le livre, comme un prof.','Le chat a une patte sur la tasse, comme un prof.','une patte sur le livre','une patte sur le crayon','nerd','exaggeration'),
(2678,'fr','Le papier est en train de dévorer l''ordi.','Le papier est en train de dévorer le lit.','des piles de papier','un avion en papier','dramatic','exaggeration'),
(2679,'fr','Il est hyper pressé !','Il n''est pas du tout pressé !','pressé, en pleine course','pressé de manger','dramatic','exclamation'),
(2682,'fr','Le tigre attaque !','Le lion attaque !','un tigre qui attaque','un tigre attaqué','dramatic','exclamation'),
(2683,'fr','Sa peinture faciale est un mandala.','Sa peinture faciale est une araignée.','un mandala en peinture faciale','la peinture faciale d''un clown','nerd','none'),
(2684,'fr','Ces masques sont pour le carnaval.','Ces masques sont pour le bloc opératoire.','des masques de carnaval','un défilé de carnaval','chill','guessing'),
(2685,'fr','Les masques du bal masqué sont dorés.','Les masques du bal masqué sont rouges.','des masques dorés de bal masqué','une invitation au bal masqué','business','none'),
(2686,'fr','La brune a l''air si calme.','La blonde a l''air si calme.','une brune en bleu','une brune en rouge','flirt','none'),
(2687,'fr','Villa avec piscine. Très exclusif.','Villa avec court de tennis. Très exclusif.','une piscine turquoise','une piscine couverte','business','none'),
(2688,'fr','Ses dreadlocks sont très longues.','Ses dreadlocks sont très courtes.','de longues dreadlocks sur le torse','des dreadlocks courtes sous un bonnet','chill','none'),
(2690,'fr','Sa couronne est pleine de diamants.','Sa couronne est pleine de plumes.','une couronne de diamants','une bague en diamant','gossip','exaggeration'),
(2691,'fr','Elle porte un trench-coat.','Elle porte une veste de ski.','un trench-coat beige','un trench-coat mouillé','chill','none'),
(2693,'fr','Un arbre pousse hors d''un livre !','Un arbre pousse hors d''une tasse !','qui pousse hors d''un livre','qui pousse hors d''un pot','dramatic','exclamation'),
(2694,'fr','Elle pense très fort.','Elle rit très fort.','penser dans le noir','penser au dîner','chill','none'),
(2698,'fr','Volets ouverts, café chaud, parfait.','Volets ouverts, bière fraîche, parfait.','des volets verts grands ouverts','des volets fermés pour la nuit','chill','cliche'),
(2702,'fr','Formule nature : cascade incluse.','Formule nature : château inclus.','la nature avec une cascade','la nature avec une route passante','business','none'),
(2703,'fr','Un obélisque géant dans la neige.','Un obélisque géant dans le désert.','un obélisque noir dans la neige','un obélisque sur une place','dramatic','none'),
(2704,'fr','Il ne reste que des décombres et du brouillard.','Il ne reste que de la neige et du brouillard.','des décombres dans le brouillard','déblayer des décombres à la pelleteuse','dramatic','none'),
(2708,'fr','Le dieu singe a l''air fort.','Le dieu singe a l''air minuscule.','des bras et un torse forts','un café bien fort','chill','none'),
(2709,'fr','Il porte une guirlande d''œillets d''Inde.','Il porte une guirlande de roses.','une guirlande d''œillets d''Inde','des œillets d''Inde en pot','chill','none'),
(2712,'fr','C''est moitié visage, moitié anatomie.','C''est moitié visage, moitié fleurs.','un dessin d''anatomie','un examen d''anatomie','nerd','none'),
(2714,'fr','Des citrons, la mer et un chapeau de paille.','Des oranges, la mer et un chapeau de paille.','un grand chapeau de paille','le chapeau de paille d''un épouvantail','chill','none'),
(2716,'fr','Big Ben derrière les arbres, stylé.','Big Ben derrière les bateaux, stylé.','une vue sur Big Ben','Big Ben à minuit','slang','none'),
(2718,'fr','Le piano est à moitié un plan technique.','La harpe est à moitié un plan technique.','le plan technique d''un piano','le plan technique d''une maison','nerd','none'),
(2722,'fr','La spirale est sous le cow-boy.','La spirale est au-dessus du cow-boy.','une spirale d''étoiles','un escalier en spirale','chill','none'),
(2723,'fr','Il est complètement furieux !','Elle est complètement furieuse !','un guerrier furieux','un dragon furieux','dramatic','exclamation'),
(2724,'fr','Il règne sur cette jungle brumeuse.','Il règne sur ce désert brumeux.','une jungle verte et brumeuse','une jungle pleine de tigres','dramatic','none'),
(2725,'fr','Il est accroupi sur un rocher.','Il est accroupi sur un arbre.','accroupi en haut d''un rocher','accroupi au fond d''une grotte','chill','none'),
(2726,'fr','Il porte deux colliers de perles.','Il porte deux colliers de clochettes.','des colliers de perles orange','compter des perles sur un fil','chill','none'),
(2728,'fr','Un lapin câline un renard.','Un lapin câline un chat.','câliner un bébé renard','câliner un bébé lapin','chill','none'),
(2729,'fr','Sa boule de cristal brille.','Sa boule de cristal est cassée.','toucher une boule de cristal','une boule de cristal cassée','chill','none'),
(2731,'fr','Fait : la pupille est noire.','Fait : la pupille est blanche.','une pupille noire','un élève à l''école','nerd','none'),
(2733,'fr','L''armée charge !','L''armée bat en retraite !','une armée à cheval','une armée à pied','dramatic','exclamation'),
(2734,'fr','Le chat a un tout petit nez rose.','Le chat a un tout petit nez noir.','un petit nez rose','un petit nez noir','chill','none'),
(2735,'fr','Cette explosion est trop marrante !','Cette inondation est trop marrante !','une explosion dans un labo','une explosion de couleurs','dramatic','exclamation'),
(2736,'fr','L''astronome est un vieil homme.','L''astronome est un jeune homme.','un vieil astronome','un astronome au télescope','chill','none'),
(2737,'fr','C''est un trou noir dans l''espace.','C''est une lune noire dans l''espace.','un trou noir dans l''espace','un trou noir financier','nerd','none'),
(2738,'fr','Cet oiseau exotique porte un casque pour t''ignorer.','Cet oiseau exotique porte des lunettes de soleil pour t''ignorer.','un oiseau exotique avec un casque','des oiseaux exotiques en cage','ironic','guessing'),
(2740,'fr','Sa moustache est blanche comme la neige.','Sa moustache est noire comme le charbon.','une épaisse moustache blanche','une fine moustache noire','dramatic','cliche'),
(2742,'fr','Il se concentre sur le code.','Il se concentre sur un livre.','se concentrer sur un écran','se concentrer sur un jeu','nerd','none'),
(2743,'fr','Des parois rocheuses abruptes ? Non merci.','Des parois de sable abruptes ? Non merci.','des parois rocheuses abruptes','une rue abrupte en ville','slang','guessing'),
(2744,'fr','Fait : les paons ont une huppe.','Fait : les paons n''ont pas de huppe.','une huppe de plumes fines','un emblème sur un bouclier','nerd','cliche'),
(2747,'fr','Le bambin potelé tient une massue.','Le bambin potelé tient un arc.','un dieu bambin potelé','un chiot potelé','chill','none'),
(2749,'fr','Elle est assise au bar, avec classe.','Elle est assise dans une voiture, avec classe.','assise à un bar','une barre de chocolat','flirt','none'),
(2750,'fr','La plante d''intérieur est posée sur des livres.','La plante d''intérieur est posée sur une télé.','une plante d''intérieur sur une étagère','une plante d''intérieur par terre','chill','none'),
(2751,'fr','Cette plante est hyper piquante.','Cette plante est hyper douce.','une plante en pot piquante','une boule de cactus piquante','slang','none'),
(2752,'fr','La souris joue pour l''Allemagne !','Le chat joue pour l''Allemagne !','un fan de l''Allemagne','une carte de l''Allemagne','low_iq','guessing'),
(2753,'fr','Cette tirelire est blindée !','Cette tirelire est fauchée !','une grosse tirelire rose','une tirelire cassée','slang','exaggeration'),
(2754,'fr','Tant de vapeur au coucher du soleil !','Tant de neige au coucher du soleil !','de la vapeur blanche d''une locomotive','de la fumée blanche d''une cheminée','dramatic','exclamation'),
(2757,'fr','Un piano plein d''inspiration.','Une cuisine pleine d''inspiration.','un éclair d''inspiration','l''inspiration tirée d''un livre','chill','none'),
(2758,'fr','Un buste en pierre dans le désert.','Un buste en pierre dans la jungle.','un immense buste en pierre','un buste dans un musée','nerd','none'),
(2759,'fr','Il se tient debout comme un vrai héros.','Il est assis comme un vrai héros.','un héros sur un rocher','un héros à cheval','dramatic','cliche'),
(2762,'fr','Une silhouette marche dans le blé.','Une silhouette marche dans la neige.','un champ de blé mûr','une miche de pain de blé','chill','none'),
(2765,'fr','Le bébé sourit.','Le bébé pleure.','sourire avec une flûte','sourire à sa mère','chill','none'),
(2766,'fr','Un cobra juste à côté de son épaule !','Un tigre juste à côté de son épaule !','un cobra dressé','un cobra dans un panier','dramatic','exclamation'),
(2770,'fr','Le numéro 3 transpire à grosses gouttes !','Le numéro 7 transpire à grosses gouttes !','transpirer après une course','transpirer au sauna','dramatic','exclamation'),
(2771,'fr','La souris mange une glace !','La souris mange du fromage !','manger un cornet de glace','manger un sandwich au fromage','dramatic','exclamation'),
(2774,'fr','L''architecture est gothique.','L''architecture est moderne.','une architecture gothique de cathédrale','une architecture moderne en verre','nerd','none'),
(2776,'fr','Elle brandit la torche bien haut.','Elle brandit le drapeau bien haut.','une torche allumée brandie','une torche dans une grotte','chill','none'),
(2777,'fr','Son turban porte une grosse broche.','Son turban porte une grosse fleur.','une grande broche en argent','une broche sur un manteau','chill','none'),
(2779,'fr','Son iris est bleu-vert.','Son iris est marron foncé.','un iris bleu-vert','une fleur d''iris violette','chill','none'),
(2781,'fr','Elle porte tellement de trucs !','Il porte tellement de trucs !','porter un sac lourd','porter un carton lourd','dramatic','exclamation'),
(2782,'fr','Cette gravure n''est faite que de lignes.','Cette gravure n''est faite que de points.','une fine gravure au trait','une gravure sur une bague','nerd','none'),
(2788,'fr','Elle souffle des pétales.','Elle souffle des bougies.','souffler des pétales et des papillons','souffler des bougies','chill','none'),
(2791,'fr','Sa tête est transparente. Trop stylé !','Sa tête est dorée. Trop stylé !','un crâne en dôme transparent','un imperméable transparent','slang','exclamation'),
(2794,'fr','Le vétérinaire tient un chat.','Le vétérinaire tient un chien.','un vétérinaire qui câline un chat','un vétérinaire dans une ferme','chill','none'),
(2795,'fr','Il escalade la tête en bas !','Il dort la tête en bas !','escalader sous une falaise','grimper à une échelle','dramatic','exclamation'),
(2800,'fr','Je peux éclater cette grosse bulle ?','Je peux éclater ce gros ballon ?','une bulle dans le ciel','une bulle dans un verre','low_iq','guessing'),
(2801,'fr','Ses phares sont orange vif.','Ses phares sont bleu vif.','des phares orange dans la neige','des phares sur une voiture enneigée','chill','none'),
(2803,'fr','Son visage est psychédélique !','Son visage est gris et terne !','un portrait psychédélique','une voiture psychédélique','dramatic','exclamation'),
(2805,'fr','Il va dessiner un chef-d''œuvre.','Elle va dessiner un chef-d''œuvre.','dessiner une image','tirer les rideaux','ironic','guessing'),
(2806,'fr','Un bambin en turban doré.','Un bambin en casque doré.','un bambin avec une plume','un bambin en poussette','chill','none'),
(2810,'fr','Deux cafés pour un seul espace de travail !','Deux ordis pour un seul espace de travail !','un espace de travail cosy','un espace de travail partagé','ironic','exclamation'),
(2811,'fr','Il touche une voiture en hologramme.','Il touche une voiture jouet.','l''hologramme d''une voiture','un hologramme sur une carte','nerd','none'),
(2812,'fr','Un drone est sur le grand écran.','Un avion est sur le grand écran.','un drone sur un écran','un drone au-dessus d''un champ','chill','none'),
(2814,'fr','Il est allongé dans les nuages.','Il est allongé dans la mer.','allongé sur un siège sculpté','allongé sur un canapé','chill','none'),
(2815,'fr','Il est prêt pour la bataille.','Il est prêt pour le dodo.','prêt pour la bataille','une bataille navale','chill','none'),
(2817,'fr','L''arrosoir a des fleurs.','La théière a des fleurs.','un arrosoir avec des fleurs','un arrosoir plein d''eau','chill','none'),
(2818,'fr','Il pleut de l''argent !','Il pleut des pièces !','une table pleine d''argent','une table pleine de nourriture','dramatic','exaggeration'),
(2819,'fr','Ses bagues sont d''un or rayonnant.','Ses bagues sont d''un vert rayonnant.','des bagues dorées rayonnantes','des yeux rouges lumineux','chill','none'),
(2820,'fr','Ils partagent un livre.','Ils partagent une pizza.','partager un livre','partager un bureau','chill','none'),
(2823,'fr','Zéro vent : l''eau est calme.','Zéro vent : l''eau est agitée.','un bateau sur une eau calme','une nuit calme en ville','nerd','none'),
(2824,'fr','La boîte de nuit est pleine maintenant.','La boîte de nuit est vide maintenant.','une boîte de nuit aux néons','le videur d''une boîte de nuit','gossip','none'),
(2825,'fr','Il est entouré de livres !','Il est entouré de jouets !','entouré de murs de livres','entouré de murs de jouets','dramatic','exclamation'),
(2826,'fr','Le ruban jaune lui va trop bien.','Le ruban rouge lui va trop bien.','un ruban jaune dans les cheveux','un ruban jaune de cadeau','flirt','none'),
(2827,'fr','Il s''est assoupi. L''art, c''est épuisant.','Il s''est assoupi. Les maths, c''est épuisant.','s''assoupir à son bureau','s''assoupir sur le canapé','gossip','bad_excuse'),
(2829,'fr','Elle parcourt les rayons d''une bibliothèque.','Elle parcourt les rayons d''un magasin.','parcourir les rayons d''une bibliothèque','parcourir Internet','chill','none'),
(2831,'fr','Même le soleil est joyeux !','Même la pluie est joyeuse !','un soleil joyeux qui sourit','un jour de pluie joyeux','low_iq','exclamation'),
(2837,'fr','Elle est dans une librairie.','Elle est dans un magasin de jouets.','une librairie bondée','le comptoir café d''une librairie','chill','none'),
(2838,'fr','Des paillettes arc-en-ciel sur ses joues.','Des paillettes noires sur ses joues.','des paillettes arc-en-ciel sur les joues','des paillettes sur une carte','chill','none'),
(2840,'fr','Une ville entière sur un seul parchemin !','Une forêt entière sur un seul parchemin !','une ville sur un parchemin','un parchemin dans une bouteille','gossip','exclamation'),
(2847,'fr','Des poumons comme des arbres. Très poétique.','Des poumons comme des étoiles. Très poétique.','des poumons comme des branches','des poumons sur une radio','ironic','none'),
(2850,'fr','Sa batterie est énorme !','Sa guitare est énorme !','une grosse batterie','un bidon d''huile','slang','exclamation'),
(2856,'fr','Tant de climatiseurs !','Tant de jardinières !','des blocs de climatiseurs','un climatiseur de voiture','dramatic','exclamation'),
(2859,'fr','Elle médite dans une grotte.','Elle médite sur une plage.','méditer dans une grotte','méditer sur une montagne','chill','none'),
(2861,'fr','Devine qui lit un livre ?','Devine qui lit une carte ?','lire sur le canapé','lire au lit','gossip','none'),
(2867,'fr','Cette sphère est pleine d''étincelles !','Cette sphère est pleine d''eau !','une sphère de verre géante','une sphère en pierre','dramatic','exclamation'),
(2877,'fr','Il escalade la corde.','Il escalade une échelle.','escalader une corde','escalader un arbre','chill','none'),
(2890,'fr','Pas de rennes aujourd''hui, alors le père Noël skie.','Pas de rennes aujourd''hui, alors le père Noël marche.','skier sur une piste','skier sur un lac gelé','ironic','guessing'),
(2892,'fr','Il tient un cierge magique.','Il tient une bougie.','tenir un cierge magique allumé','un cierge magique sur un gâteau','chill','none'),
(2894,'fr','L''homme porte un agneau.','L''homme porte un chien.','porter un agneau blanc','un agneau avec sa mère','chill','none'),
(2897,'fr','Il est où, le père Noël ? Il a laissé son traîneau.','Il est où, le père Noël ? Il a laissé sa voiture.','un traîneau plein de cadeaux','un traîneau tiré par des rennes','gossip','guessing'),
(2898,'fr','Un sphinx garde le désert.','Un chameau garde le désert.','des pyramides dans le désert','un road trip dans le désert','dramatic','none'),
(2900,'fr','Un loup énorme lui fait face.','Un ours énorme lui fait face.','un loup énorme et lumineux','des loups qui hurlent la nuit','chill','none'),
(2906,'fr','Elle porte un gros carton.','Elle porte une grosse plante.','porter un gros carton','porter un bébé','chill','none'),
(2908,'fr','Un livre géant flotte dans l''air.','Un ballon géant flotte dans l''air.','un livre géant qui flotte','un géant de conte de fées','chill','none'),
(2909,'fr','Le scientifique adore le violet.','Le scientifique adore le vert.','le labo d''un scientifique fou','un scientifique à la télé','gossip','guessing'),
(2910,'fr','Trop de livres ! L''étagère à livres est pleine !','Trop de jouets ! L''étagère à livres est pleine !','une étagère à livres colorée','une étagère à livres vide','low_iq','exclamation'),
(2914,'fr','Quelqu''un s''étire très haut.','Quelqu''un saute très haut.','s''étirer les bras en l''air','s''étirer avant de courir','chill','none'),
(2915,'fr','L''équipe plante des fleurs.','L''équipe cueille des fleurs.','planter des fleurs orange','cueillir des fleurs orange','business','none'),
(2925,'fr','Ce bec est long. Trop long.','Ce bec est court. Trop court.','un long bec pointu','un bec court et crochu','low_iq','exaggeration'),
(2928,'fr','Un vaisseau spatial vole au-dessus d''elle.','Un gros dragon vole au-dessus d''elle.','un immense vaisseau spatial pâle','un vaisseau spatial qui atterrit','chill','none'),
(2937,'fr','L''astronaute flotte.','L''astronaute court.','un astronaute dans l''espace lointain','un astronaute sur la Lune','chill','none'),
(2942,'fr','Il y a une planète orange.','Il y a une planète verte.','une planète orange lumineuse','une planète avec des anneaux','nerd','none'),
(2949,'fr','Un astronaute voit une éclipse.','Un astronaute voit un arc-en-ciel.','regarder une éclipse solaire','une éclipse de lune','nerd','none'),
(2950,'fr','Des papillons sortent de la radio !','Des abeilles sortent de la radio !','une vieille radio','une station de radio','dramatic','exclamation'),
(2951,'fr','Deux mains se touchent presque !','Deux pieds se touchent presque !','deux mains qui se touchent presque','deux mains qui se serrent','dramatic','exclamation'),
(2952,'fr','Cape jaune, donc super-héros. Facile.','Cape rouge, donc super-héros. Facile.','un super-héros en armure noire','un super-héros masqué','low_iq','none'),
(2964,'fr','Elle respire, les yeux fermés.','Elle dort, les yeux fermés.','respirer dans le noir','respirer contre une vitre','chill','none'),
(2967,'fr','Ce vétérinaire a un patient trop content !','Ce vétérinaire a un chaton trop content !','un vétérinaire avec un bouledogue','un vétérinaire avec un chaton','slang','exclamation'),
(2971,'fr','Tant de post-it. Tellement « organisé ».','Tant de photos. Tellement « organisé ».','des post-it sur une fenêtre','des post-it sur un frigo','ironic','exaggeration'),
(2973,'fr','Quelqu''un vient d''avoir une idée !','Quelqu''un vient de prendre un café !','une nouvelle idée brillante','une idée pour le dîner','slang','exclamation'),
(2980,'fr','Il utilise un énorme télescope.','Il utilise un énorme appareil photo.','un énorme télescope en laiton','un petit télescope en plastique','nerd','none'),
(2981,'fr','Cette tornade est faite de code.','Cette tornade est faite de poussière.','une tornade faite de code','une tornade au-dessus d''une ferme','nerd','none'),
(2987,'fr','Le robot doré est « modeste ».','Le robot argenté est « modeste ».','un robot en armure dorée','une alliance dorée','ironic','understatement'),
(3003,'fr','La foule a les mains en l''air.','La foule a les mains baissées.','une foule les mains en l''air','une foule dans un stade','chill','none'),
(3019,'fr','La fille nous sourit.','Le garçon nous sourit.','sourire à l''objectif','sourire à un chien','chill','none'),
(3022,'fr','Les échecs, c''est un peu difficile.','Le poker, c''est un peu difficile.','une partie d''échecs','un club d''échecs','ironic','understatement'),
(3024,'fr','Ils se tiennent la main.','Ils tapent dans leurs mains.','se tenir la main de dos','se tenir la main à table','flirt','none'),
(3027,'fr','Il guérit le vieil homme.','Il guérit le jeune homme.','guérir les yeux d''un vieil homme','guérir la jambe d''un jeune homme','chill','none'),
(3034,'fr','Elle étudie seule.','Elle dort seule.','étudier en classe','étudier à la bibliothèque','chill','none'),
(3035,'fr','Les élèves font un contrôle.','Les élèves jouent à un jeu.','faire un contrôle','un contrôle routier','chill','none'),
(3040,'fr','Cette pile de boulot, c''est dingue !','Cette pile de bouffe, c''est dingue !','une pile de papiers','une pile de vêtements','slang','exclamation'),
(3041,'fr','Il a l''air inquiet à son bureau.','Il a l''air inquiet dans son lit.','un garçon inquiet au travail','inquiet à cause de la météo','chill','none'),
(3049,'fr','Il a une grande question.','Il a un gros sandwich.','une question dans une bulle','une question à un contrôle','chill','none'),
(3057,'fr','Il marche dans le parc.','Il court dans le parc.','marcher le long d''un chemin','marcher le long d''une plage','chill','none'),
(3059,'fr','L''aurore boréale, c''est une vibe.','Le feu d''artifice, c''est une vibe.','une aurore boréale sur les montagnes','une aurore boréale sur une ville','slang','none'),
(3061,'fr','Elle flotte au-dessus d''un disque vinyle.','Elle flotte au-dessus d''un piano.','un disque vinyle qui tourne','battre un record du monde','chill','none'),
(3062,'fr','Le DJ mixe des vinyles.','Le DJ dédicace des vinyles.','un DJ aux platines','un DJ à la radio','slang','none'),
(3063,'fr','Elle écoute de la musique.','Elle écoute sur un canapé.','écouter avec un casque','écouter un prof','chill','none'),
(3064,'fr','Elle ouvre les rideaux !','Elle ferme les rideaux !','ouvrir les rideaux','ouvrir la porte d''entrée','dramatic','exclamation'),
(3070,'fr','Un arbre est au-dessus des mains.','Un chat est au-dessus des mains.','deux mains ouvertes en coupe','deux mains dans les poches','chill','none'),
(3072,'fr','Attends. Les chats savent ratisser les feuilles ?','Attends. Les chiens savent ratisser les feuilles ?','ratisser les feuilles mortes','ratisser le sable','low_iq','none'),
(3079,'fr','Il boit dans un mug.','Il boit dans une bouteille.','boire dans un mug','boire à la bouteille','chill','none'),
(3082,'fr','La ballerine est sur une seule pointe !','La ballerine est sur ses deux pieds !','une ballerine sur une pointe','une ballerine sur scène','dramatic','exclamation'),
(3087,'fr','Elle verse des croquettes.','Elle verse du jus d''orange.','verser des croquettes','verser du thé chaud','business','none'),
(3089,'fr','Elle a fait cuire des cookies au four. Pour moi ?','Elle a fait cuire un gâteau au four. Pour moi ?','des cookies cuits au four','des petits pains cuits au four','flirt','guessing'),
(3090,'fr','Elle porte ses courses.','Elle porte son linge.','un sac de courses','des courses sur un vélo','chill','none'),
(3098,'fr','Deux burgers sur le barbecue.','Deux steaks sur le barbecue.','un barbecue dans le jardin','un barbecue sur la plage','chill','none'),
(3101,'fr','Elle saute trop haut !','Elle nage trop vite !','sauter à la corde','sauter dans un lac','slang','exclamation'),
(3118,'fr','Il brandit sa hache !','Il brandit sa batte !','une hache plantée dans un arbre','une hache au mur','dramatic','exclamation'),
(3119,'fr','La fée a des ailes dorées.','La fée a des ailes noires.','une fée aux ailes dorées','une fée avec une baguette','chill','none'),
(3122,'fr','Seulement huit parts de pizza.','Seulement six parts de pizza.','une pizza en huit parts','une pizza dans un carton','ironic','understatement'),
(3124,'fr','Le hot-dog a de la moutarde.','Le hot-dog a du ketchup.','un hot-dog à la moutarde','un hot-dog au ketchup','chill','none'),
(3125,'fr','Un chocolat chaud avec de la chantilly !','Un café chaud avec de la chantilly !','un mug de chocolat chaud','un gâteau au chocolat chaud','dramatic','exclamation'),
(3126,'fr','Le boxeur a l''air hyper sérieux.','Le boxeur a l''air hyper endormi.','un boxeur aux gants rouges','promener un boxer','slang','none'),
(3127,'fr','Il va la lancer super vite !','Il va la shooter super vite !','lancer une balle de baseball','jeter le gant','dramatic','guessing'),
(3132,'fr','Il randonne avec un bâton.','Il randonne avec un chien.','randonner en montagne','faire grimper les prix','chill','none'),
(3135,'fr','Elle gagne la course !','Elle perd la course !','gagner une course à pied','gagner une course de natation','dramatic','exclamation'),
(3136,'fr','Elle nage dans un lac.','Elle nage dans une piscine.','nager dans un lac','nager dans la mer','chill','none'),
(3141,'fr','Le groupe est en réunion.','Le groupe fait la fête.','un groupe en cercle','un groupe en file','business','none'),
(3143,'fr','Il teint du tissu en bleu.','Il teint du tissu en rouge.','teindre du tissu en bleu','se teindre les cheveux en bleu','chill','none'),
(3144,'fr','Il tisse une étoffe.','Il tisse un panier.','tisser sur un métier','se faufiler dans la circulation','chill','none'),
(3145,'fr','Il travaille sur un grand métier à tisser.','Il travaille à un grand bureau.','un métier à tisser en bois','coudre à la machine à coudre','chill','none'),
(3147,'fr','Du tissu bleu sèche sur un fil au-dessus de la ruelle.','Du papier bleu sèche sur un fil au-dessus de la ruelle.','du tissu bleu sur un fil','un tissu pour la table','chill','none'),
(3148,'fr','Les femmes récoltent.','Les femmes dansent.','récolter des tiges dorées','récolter des pommes','chill','none'),
(3158,'fr','L''ouvrier soude de l''acier.','L''ouvrier peint de l''acier.','souder une plaque d''acier','souder un vélo cassé','nerd','none'),
(3163,'fr','Elle se lave les mains.','Elle se lave le visage.','se laver les mains','laver la vaisselle','chill','none'),
(3164,'fr','C''est l''heure de te brosser les dents !','C''est l''heure de te brosser les cheveux !','se brosser les dents','se brosser les cheveux','dramatic','exclamation'),
(3176,'fr','Elle est assise sous un arbre.','Elle est assise dans un arbre.','assise sous un arbre','assise sur une branche','chill','none'),
(3180,'fr','Elle patine sur une jambe !','Elle skie sur une jambe !','patiner sur un lac','patiner dans un parc','dramatic','exclamation'),
(3188,'fr','Quelqu''un prie sur un tapis.','Quelqu''un dort sur un tapis.','prier sur un tapis','prier dans une église','chill','none'),
(3192,'fr','Seuls ses yeux sont visibles.','Seule sa bouche est visible.','seuls les yeux visibles','les yeux fermés, endormie','business','none'),
(3195,'fr','Il travaille encore. Le pauvre.','Il mange encore. Le pauvre.','travailler tard le soir','s''entraîner tard le soir','slang','guessing'),
(3197,'fr','Elle rêvasse de thé, de livres et de musique.','Elle rêvasse de voitures, de livres et de musique.','rêvasser à table','rêvasser au lit','gossip','guessing'),
(3198,'fr','Leur télé, c''est un aquarium.','Leur télé, c''est une cheminée.','des poissons dans un aquarium','des poissons dans une assiette','ironic','understatement'),
(3199,'fr','Cette double spirale, c''est de l''ADN.','Cette double spirale, c''est une corde.','une spirale d''ADN lumineuse','un kit de test ADN','nerd','none'),
(3200,'fr','La lettre est au milieu.','Le téléphone est au milieu.','une lettre manuscrite','une lettre imprimée','chill','none'),
(3207,'fr','Qui a besoin d''une lampe ? La plante luit.','Qui a besoin d''une lampe ? Le livre luit.','une petite plante qui luit','un feu qui luit','ironic','cheap_quality'),
(3216,'fr','Ils courent côte à côte.','Ils dansent côte à côte.','courir côte à côte','courir après un bus','chill','none'),
(3222,'fr','Un chat dort comme un roi.','Un chien dort comme un roi.','dormir dans un fauteuil','dormir dans un panier','slang','cliche'),
(3235,'fr','Regarde, le koala a des roses.','Regarde, le koala a des carottes.','un koala qui tient des roses','un koala qui mange des feuilles','gossip','none'),
(3240,'fr','Il nous crie dessus !','Il nous chante une chanson !','crier dans un mégaphone','crier sur un chien','dramatic','exclamation'),
(3242,'fr','Du pop-corn au lit avec la télécommande ? Ces chats ont tout compris.','De la pizza au lit avec la télécommande ? Ces chats ont tout compris.','du pop-corn au lit','du pop-corn au cinéma','slang','cliche'),
(3243,'fr','Le réseau brille en bleu.','Le réseau brille en rouge.','un réseau bleu lumineux','un réseau de télévision','chill','none'),
(3256,'fr','Le groupe met le feu au club !','Le groupe met le feu à la plage !','un groupe sur scène','un groupe dans un stade','slang','none'),
(3269,'fr','Elle se détend sur le toit.','Elle se détend sur la plage.','se détendre dans un transat','se détendre dans la baignoire','chill','none'),
(3272,'fr','Talons, mallette : la boss absolue !','Talons, sac à dos : la boss absolue !','porter une mallette en cuir','une mallette pleine d''argent','flirt','exclamation'),
(3277,'fr','L''enfant tient une étoile !','L''enfant tient une lampe !','tenir une étoile lumineuse','tenir une lampe lumineuse','dramatic','exclamation'),
(3278,'fr','Le couple s''enlace.','Le couple danse.','un couple enlacé','un couple d''amis','flirt','none'),
(3281,'fr','Le cerf-volant fait tout le boulot.','Le bateau fait tout le boulot.','tiré par un cerf-volant','un cerf-volant au parc','ironic','exaggeration'),
(3283,'fr','La mouette fait la touriste maintenant.','Le pigeon fait le touriste maintenant.','une mouette sur une jetée','une mouette sur un bateau','chill','exaggeration'),
(3288,'fr','Ils marchent sur des échasses.','Ils marchent sur une scène.','marcher sur de hautes échasses','des maisons sur pilotis','chill','none'),
(3301,'fr','Il barre le navire.','Il conduit la voiture.','barrer un grand navire','conduire une petite voiture','chill','none'),
(3303,'fr','Son avion en papier vole !','Son cerf-volant vole !','lancer un avion en papier','plier un avion en papier','dramatic','exclamation'),
(3306,'fr','Le coq est le maître du monde.','L''aigle est le maître du monde.','un coq sur un globe','un coq sur une clôture','dramatic','exaggeration'),
(3311,'fr','Elle entre dans un tunnel.','Elle entre dans un lac.','un tunnel dans la roche','un tunnel sous une rivière','chill','none'),
(3313,'fr','Quel stade « plein à craquer ».','Quelle plage « pleine à craquer ».','un stade vide','un stade plein','ironic','none'),
(3317,'fr','L''alpaga veut être sur la photo.','Le cheval veut être sur la photo.','un alpaga brun curieux','un alpaga brun endormi','gossip','guessing'),
(3323,'fr','Le bébé hippopotame est très occupé.','Le lionceau est très occupé.','un bébé hippopotame au repos','un bébé hippopotame qui nage','chill','understatement'),
(3325,'fr','De la magie jaillit d''un vieux livre !','De la magie jaillit d''une vieille tasse !','la magie d''un vieux livre','un spectacle de magie sur scène','dramatic','exclamation'),
(3341,'fr','Un gars a une trompette dorée.','Un gars a un violon doré.','une trompette dorée','jouer de la trompette','chill','none'),
(3346,'fr','Deux personnes sont dans une bibliothèque.','Deux personnes sont dans une cuisine.','deux personnes dans une bibliothèque','une carte de bibliothèque','chill','none'),
(3357,'fr','Une grande chaise près du filet.','Une grande échelle près du filet.','un filet au milieu du court','un filet de pêche','chill','none'),
(3362,'fr','Mec, le raton laveur nous fixe.','Mec, le chat nous fixe.','un raton laveur sur un rebord','un raton laveur dans une poubelle','slang','none'),
(3368,'fr','Le paresseux n''est pas pressé.','Le koala n''est pas pressé.','un paresseux souriant','un paresseux endormi','chill','understatement'),
(3369,'fr','Il sent une fleur bleue.','Il sent une fleur rouge.','sentir une fleur','sentir la soupe','chill','none'),
(3379,'fr','Il court vers le ballon.','Il fuit le ballon.','courir vers le ballon','un ballon dans le ciel','chill','none'),
(3382,'fr','Wesh, ce perroquet est un pirate.','Wesh, ce perroquet est un chef cuisinier.','un perroquet avec un cache-œil','un perroquet en cage','slang','exaggeration'),
(3383,'fr','Un poussin surfe sur une vague !','Un canard surfe sur une vague !','un poussin qui surfe','un poussin dans un œuf','dramatic','exclamation'),
(3390,'fr','Ils s''embrassent au milieu des roses.','Ils s''embrassent sur une plage.','s''embrasser dans une roseraie','s''embrasser sur un pont','flirt','none'),
(3392,'fr','Le hibou est de l''équipe de nuit.','Le hibou est de l''équipe de jour.','un hibou dans la neige','un hibou blanc en vol','business','cliche'),
(3395,'fr','Le brouillard cache les montagnes.','Le brouillard cache la ville.','un épais brouillard sur les sommets','de la buée sur le miroir','chill','none'),
(3401,'fr','Le feu de circulation a des fleurs !','Le feu de circulation a des bougies !','un feu de circulation fleuri','un feu de circulation en panne','low_iq','exclamation'),
(3406,'fr','Quelqu''un plonge avec un monstre marin !','Quelqu''un plonge avec un requin !','plonger au-dessus d''un récif','plonger d''une falaise','dramatic','exaggeration'),
(3412,'fr','Elle soulève de la fonte en robe rouge !','Elle soulève de la fonte en manteau rouge !','soulever une barre de muscu','soulever une valise','dramatic','exclamation'),
(3418,'fr','Elle va frapper la batterie.','Elle va frapper le gong.','jouer de la batterie','porter la batterie','chill','guessing'),
(3419,'fr','Il souffle dans une trompette.','Il souffle dans un sifflet.','souffler dans une trompette dorée','nettoyer une trompette dorée','chill','none'),
(3420,'fr','La contrebasse est plus grande qu''elle.','La contrebasse est plus petite qu''elle.','jouer de la contrebasse à l''archet','porter une contrebasse','nerd','none'),
(3422,'fr','Elle dirige l''orchestre.','Elle dirige le chœur.','diriger un orchestre','jouer dans un orchestre','business','none'),
(3423,'fr','Elle pince les cordes de la harpe.','Elle pince les cordes de la guitare.','pincer une grande harpe','porter une grande harpe','chill','none'),
(3424,'fr','Le chef d''orchestre tient une baguette.','Le chef d''orchestre tient une flûte.','un chef d''orchestre en queue-de-pie','un contrôleur dans un train','business','none'),
(3428,'fr','Elle joue du violon à merveille.','Elle joue du violoncelle à merveille.','jouer du violon','accorder le violon','flirt','none'),
(3431,'fr','Elle joue de la clarinette.','Elle joue de la trompette.','souffler dans une clarinette','nettoyer une clarinette','chill','none'),
(3435,'fr','Deux entrées de grotte dans la falaise.','Deux entrées de grotte dans le sable.','une grotte marine dans les falaises','une grotte pleine de chauves-souris','chill','none'),
(3441,'fr','Elle s''appuie sur des pastèques.','Elle s''appuie sur des citrouilles.','une caisse de pastèques','un stand de jus de pastèque','chill','none'),
(3447,'fr','Une statue sous la Voie lactée.','Une statue sous un arc-en-ciel.','une statue en pierre la nuit','une statue dans un parc','chill','none'),
(3469,'fr','Le guépard fait une pause.','Le guépard prend un bain.','un guépard au coucher du soleil','un guépard qui court vite','business','understatement'),
(3472,'fr','Jolie robe ! Elle tourne sur elle-même avec.','Joli chapeau ! Elle tourne sur elle-même avec.','tourner sur soi-même en robe rouge','tourner sur soi-même en robe bleue','flirt','none'),
(3473,'fr','Le flamant rose est dans l''eau.','Le flamant rose est dans un arbre.','un flamant rose dans l''eau','un flamant rose en vol','chill','none'),
(3482,'fr','Elle chill sur les marches.','Elle dort sur les marches.','des marches en pierre au soleil','les pas d''une danse','slang','none'),
(3485,'fr','Elle touche l''éléphant.','Elle touche le tigre.','toucher un éléphant','toucher un tronc d''arbre','chill','none'),
(3489,'fr','Du vin dans un bateau ? Elle rit.','Du vin dans une voiture ? Elle rit.','rire dans un bateau','rire d''un bateau','gossip','guessing'),
(3494,'fr','Elle s''étire vers le soleil.','Il s''étire vers le soleil.','s''étirer les deux bras en l''air','étirer un élastique','chill','none'),
(3513,'fr','Le voile de la mariée est très long.','Le voile de la mariée est très sombre.','le long voile d''une mariée','une mariée avec un bouquet','gossip','none'),
(3516,'fr','Le vase contient une seule fleur.','Le vase contient dix fleurs.','un vase sur une étagère','un vase sur une table','chill','none'),
(3519,'fr','Cette boucle d''oreille blanche est trop jolie.','Ce collier blanc est trop joli.','une boucle d''oreille goutte blanche','une boucle d''oreille par terre','flirt','none'),
(3522,'fr','Fait : cette méduse brille.','Fait : cette étoile de mer brille.','une méduse lumineuse','une méduse sur la plage','nerd','cliche'),
(3541,'fr','Une haute cascade, un petit lac.','Une haute cascade, un petit bateau.','une cascade qui tombe d''une falaise','une cascade dans un jardin','chill','none'),
(3548,'fr','Elle fume en smoking.','Elle fume en robe.','fumer une cigarette','fumer la pipe','chill','none'),
(3552,'fr','Le Japon au printemps, le Fuji derrière.','Le Japon en hiver, le Fuji derrière.','une ruelle printanière au Japon','un guide de voyage du Japon','chill','none'),
(3556,'fr','Les lamas se sont mis sur leur trente-et-un pour la photo.','Les chèvres se sont mises sur leur trente-et-un pour la photo.','des lamas avec des couvertures','des lamas dans la neige','gossip','guessing'),
(3559,'fr','Petite île, zéro voisin.','Petite île, zéro cactus.','une petite île rocheuse','une île avec un hôtel','ironic','understatement'),
(3561,'fr','L''âne fait les livraisons.','Le cheval fait les livraisons.','mener un âne chargé','monter un âne chargé','business','none'),
(3562,'fr','L''Égypte antique au bord du Nil.','L''Égypte antique sous la neige.','l''Égypte antique sur le Nil','une photo de vacances en Égypte','chill','none'),
(3564,'fr','Les rennes sont dans la neige.','Les rennes sont sur la plage.','des rennes dans la neige','des rennes qui tirent un traîneau','chill','none'),
(3567,'fr','Un soleil rouge flotte au-dessus du Pérou.','Un soleil jaune flotte au-dessus du Pérou.','les ruines du Pérou','le drapeau du Pérou','chill','none'),
(3572,'fr','Les femmes cueillent du thé.','Les femmes cueillent des pommes.','cueillir des feuilles de thé','cueillir des fleurs','chill','none'),
(3585,'fr','Un zèbre est en pause déjeuner.','Un zèbre prend un bain.','des zèbres sur une colline','des zèbres dans une rivière','business','none'),
(3586,'fr','La tortue terrestre est pressée.','Le crabe est pressé.','une tortue terrestre géante','une tortue qui nage dans l''eau','ironic','exaggeration'),
(3590,'fr','Une autruche marche sur le sable.','Un chameau marche sur le sable.','une autruche dans le désert','une autruche qui cache sa tête','chill','none'),
(3592,'fr','Les deux font du sport à fond.','Les deux dansent à fond.','faire du sport ensemble','promener un chien','business','none'),
(3619,'fr','Un aigle survole la rivière.','Un aigle survole la ville.','un aigle au-dessus de la rivière','un aigle au-dessus des montagnes','chill','none'),
(3629,'fr','Ils se serrent la main comme dans Star Wars !','Ils se battent comme dans Star Wars !','serrer la main d''un alien','serrer la main d''un robot','dramatic','exclamation'),
(3633,'fr','Flotter dans l''espace ? Non, dans une piscine.','Flotter dans l''espace ? Non, dans un lac.','flotter sur le dos','flotter dans l''espace','ironic','none'),
(3641,'fr','Même sur cette planète, un distributeur automatique !','Même sur cette planète, un coffee shop !','un distributeur automatique allumé','un distributeur automatique en panne','ironic','exclamation'),
(3642,'fr','Il tire une planète !','Il tire une fusée !','tirer sur une ficelle','arracher une dent','dramatic','exaggeration'),
(3644,'fr','Il arrose une toute petite plante.','Il arrose un grand arbre.','arroser une toute petite pousse','arroser un grand jardin','chill','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
