begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(4904,'fr','Ces chaises ont l''air un peu risquées.','Ces tables ont l''air un peu risquées.','une pile de chaises risquée','un pari risqué aux courses','ironic','understatement'),
(4905,'fr','Le pont enjambe le canyon.','Le pont enjambe la rue.','des arches qui enjambent un canyon','une capacité d''attention courte','business','none'),
(4906,'fr','La tente est la seule survivante.','L''arche est la seule survivante.','une tente de réception blanche','une tente dans les bois','dramatic','exaggeration'),
(4907,'fr','Grosse enceinte, eau qui danse.','Grosse enceinte, lait qui danse.','une grosse enceinte de club','un intervenant à une conférence','slang','exaggeration'),
(4908,'fr','Quelqu''un plie une branche.','Quelqu''un coupe une branche.','plier une branche de pommier','une agence bancaire','chill','none'),
(4909,'fr','Les gens la filment comme si elle était célèbre.','Les gens la peignent comme si elle était célèbre.','célèbre pendant une minute','célèbre pour ses chansons','chill','exaggeration'),
(4910,'fr','Il hurle dans son écharpe de supporter !','Il dort dans son écharpe de supporter !','une écharpe de supporter rayée','une écharpe chaude d''hiver','dramatic','exclamation'),
(4911,'fr','C''est elle, la nouvelle propriétaire !','C''est lui, le nouveau propriétaire !','la nouvelle propriétaire du café','la nouvelle cuisinière du café','gossip','exclamation'),
(4912,'fr','Le moniteur donne un coup de pied.','Le moniteur danse.','un moniteur de karaté','un moniteur d''auto-école','chill','none'),
(4913,'fr','Elle attache un bracelet.','Elle attache un collier.','un bracelet tressé en perles','acheter un bracelet en or','chill','none'),
(4914,'fr','Tout le monde adore le mec à la guitare.','Tout le monde adore le mec à la batterie.','jouer de la guitare acoustique','réparer une guitare acoustique','gossip','guessing'),
(4915,'fr','Ils marchent épaule contre épaule.','Ils sont assis épaule contre épaule.','les bras sur les épaules','un sac sur l''épaule','chill','none'),
(4916,'fr','On l''a fait ! Deux vélos, un coucher de soleil.','On l''a fait ! Deux trottinettes, un coucher de soleil.','des vélos sur une jetée','des vélos dans un train','dramatic','exclamation'),
(4918,'fr','Il monte l''escalier.','Il descend l''escalier en glissant.','monter l''escalier avec des sacs','descendre l''escalier seul','chill','none'),
(4921,'fr','Le sentier est plein de racines.','Le sentier est plein de neige.','un sentier forestier accidenté','une suite d''empreintes de pas','chill','none'),
(4922,'fr','L''hôte accueille ses invités.','L''hôte ignore ses invités.','un hôte qui lève son verre','un animateur de talk-show','business','none'),
(4923,'fr','Elle place deux clients.','Elle place quatre clients.','placer un jeune couple','s''installer au bar','chill','none'),
(4924,'fr','Elle voit un visage familier.','Elle voit un chien familier.','un visage familier','une chanson familière','chill','none'),
(4925,'fr','Elle prend soin d''un patient.','Elle prend soin d''un bébé.','prendre soin d''un patient à l''hôpital','prendre soin d''un jardin','business','none'),
(4926,'fr','Le dentiste a un miroir.','Le dentiste a un téléphone.','un dentiste avec un miroir','un dentiste qui arrache une dent','chill','none'),
(4927,'fr','L''avocat serre la main de quelqu''un.','L''avocat tient la main de quelqu''un.','un avocat avec une mallette','un avocat avec un ordi portable','chill','none'),
(4928,'fr','Il a réparé la fuite tout seul !','Il a réparé la voiture tout seul !','réparer un évier qui fuit','réparer une voiture en panne','dramatic','exclamation'),
(4929,'fr','Devine qui a eu une super note !','Devine qui a eu une sale note !','une excellente note','une mauvaise note','gossip','exclamation'),
(4930,'fr','Sa récompense : une étoile en or !','Sa récompense : une étoile en argent !','une étoile en or en récompense','une récompense pour des clés perdues','dramatic','exclamation'),
(4931,'fr','Elle explique un schéma.','Elle explique un poème.','un schéma à la craie','un schéma de manuel scolaire','nerd','none'),
(4932,'fr','Jolie casquette ! Elle pilote un taxi.','Jolie casquette ! Elle pilote un bateau.','piloter un taxi jaune','piloter un bateau jaune','flirt','none'),
(4933,'fr','Une main reste sur le volant.','Une main reste sur le téléphone.','un volant de bus','une roue de secours de bus','business','none'),
(4934,'fr','Elle met un casque.','Elle met une casquette.','un casque de pilote vert','un casque VR pour jouer','chill','none'),
(4935,'fr','Elle touche la boussole.','Elle touche la radio.','une boussole de bateau en laiton','un compas pour tracer des cercles','nerd','none'),
(4936,'fr','Elle cuisine dans une cuisine.','Elle cuisine dans un jardin.','une cuisine professionnelle','une cuisine de maison','chill','none'),
(4937,'fr','Il sonne la cloche.','Il sonne à la porte.','sonner la cloche du comptoir','appeler un ami','business','none'),
(4938,'fr','C''est une serveuse débordée.','C''est une infirmière débordée.','une serveuse en terrasse','une serveuse en cuisine','chill','none'),
(4939,'fr','Croûte dorée. Beau travail, boulanger.','Croûte brûlée. Super travail, boulanger.','des croissants bien dorés','une alliance dorée','flirt','none'),
(4940,'fr','Le boucher emballe de la viande.','Le boucher emballe des cadeaux.','un boucher qui emballe un steak','un boucher qui découpe du poulet','chill','none'),
(4941,'fr','Le pompier a sauvé un chat !','Le pompier a sauvé un chien !','un pompier qui sauve un chat','un pompier qui combat un feu','dramatic','exclamation'),
(4942,'fr','Un seul sac comme bagages ? Une légende !','Cinq sacs comme bagages ? Une légende !','des bagages sur l''épaule','des bagages sur un chariot','slang','exclamation'),
(4943,'fr','Il adore tous ces éloges.','Il déteste tous ces éloges.','les éloges de l''équipe de tournage','les éloges de son prof','gossip','guessing'),
(4945,'fr','Elle chante dans le micro.','Elle chante dans un téléphone.','chanter dans un micro','chanter dans une chorale','chill','none'),
(4947,'fr','Portrait terminé. Les bras en l''air !','Paysage terminé. Les bras en l''air !','un portrait terminé','un portrait de chat','dramatic','none'),
(4950,'fr','Mains sur les hanches. Très sérieux.','Mains sur la tête. Très sérieux.','les mains sur les hanches','rouler des hanches','ironic','understatement'),
(4952,'fr','Son lit lui a tellement manqué.','Sa voiture lui a tellement manqué.','se laisser tomber sur le lit','faire le lit','dramatic','guessing'),
(4953,'fr','Elle espère une photosynthèse.','Elle espère un orage.','espérer une pousse','espérer un arc-en-ciel','nerd','exaggeration'),
(4954,'fr','La visite la rend si heureuse !','La visite la rend si triste !','une visite à l''hôpital','une visite au zoo','dramatic','exclamation'),
(4955,'fr','Ici, seuls les casiers ont l''air rangés.','Ici, seuls les lits superposés ont l''air rangés.','une rangée de casiers gris','un casier à la piscine','ironic','exaggeration'),
(4957,'fr','Les prix des hôtels vont de pas cher à 2 000 EUR.','Les prix des hôtels vont de pas cher à 20 EUR.','trois types d''hôtel','un hôtel en bord de mer','business','cheap_quality'),
(4958,'fr','D''une cabane à une villa en verre !','D''une cabane à une villa en bois !','une immense villa en verre','une villa de vacances à louer','dramatic','exclamation'),
(4959,'fr','Une chaumière avec un tournesol.','Une chaumière avec un pommier.','une petite chaumière en bois','une chaumière au bord d''un lac','chill','none'),
(4960,'fr','Ils se câlinent aux arrivées !','Ils se battent aux arrivées !','un câlin de groupe aux arrivées','câliner un nounours','dramatic','exclamation'),
(4961,'fr','L''animal de compagnie chasse un jouet.','L''animal de compagnie chasse une balle.','un animal de compagnie en chasse','un animal de compagnie endormi','chill','none'),
(4962,'fr','Il sort les jumelles. Alerte cerf !','Il sort un télescope. Alerte cerf !','regarder dans des jumelles','des jumelles à l''opéra','dramatic','exclamation'),
(4963,'fr','Elle s''est fait mal au doigt, puis à l''orteil !','Elle s''est fait mal au doigt, puis à l''oreille !','un doigt blessé','pointer quelqu''un du doigt','dramatic','exclamation'),
(4964,'fr','La soupe à goûter, puis des fleurs. Bien joué.','La soupe à goûter, puis du chocolat. Bien joué.','goûter la soupe à la cuillère','goûter du vin à une fête','flirt','cliche'),
(4966,'fr','La glace s''est fendue en deux.','La glace s''est fendue en trois.','fendre un bloc de glace','fendre une bûche','nerd','none'),
(4967,'fr','Un scanner vérifie son identité.','Un scanner vérifie ses bagages.','vérifier son identité','cacher son identité','nerd','none'),
(4968,'fr','Elle a reçu sa nouvelle carte d''identité !','Elle a reçu son nouveau téléphone !','une nouvelle carte d''identité','une nouvelle carte d''anniversaire','slang','exclamation'),
(4969,'fr','Au café, c''est son livre à elle qui gagne.','Au café, c''est son téléphone à lui qui gagne.','lire à une table de café','travailler dans la cuisine d''un café','gossip','banter'),
(4970,'fr','Des feux d''artifice pour l''indépendance !','Des bougies pour l''indépendance !','fêter l''indépendance','se battre pour l''indépendance','dramatic','none'),
(4971,'fr','Le feu d''artifice illumine le dôme.','Le feu d''artifice illumine le pont.','un feu d''artifice au-dessus d''un dôme','un feu d''artifice au-dessus d''un lac','chill','none'),
(4972,'fr','Quelle soirée patriotique !','Quelle matinée patriotique !','une foule patriotique','un défilé militaire patriotique','dramatic','exclamation'),
(4973,'fr','Il pose devant un monument.','Il pose devant une cascade.','poser devant un monument blanc','un monument sur une montagne','chill','none'),
(4974,'fr','Le vendeur verse comme un pro.','Le vendeur jongle comme un pro.','un vendeur de thé qui verse','un vendeur de fleurs','flirt','cliche'),
(4975,'fr','Elle a un style tellement différent !','Il a un style tellement différent !','différente de la foule','différente de sa sœur','flirt','exclamation'),
(4976,'fr','Il patauge dans l''eau.','Il patauge dans la neige.','patauger dans les rizières','patauger dans la neige profonde','chill','none'),
(4977,'fr','Une main montre le chemin.','Un chien montre le chemin.','une main tendue et ouverte','une main pleine de riz','chill','none'),
(4979,'fr','Tout le bureau est malade !','Tout le bureau est endormi !','tousser au bureau','chanter au bureau','dramatic','exaggeration'),
(4980,'fr','Ils respirent profondément.','Ils crient très fort.','respirer de l''air frais','respirer sous l''eau','chill','none'),
(4982,'fr','Il se tient la cheville.','Il se tient la tête.','une cheville blessée','un bracelet à la cheville','chill','none'),
(4983,'fr','L''officier contrôle tout, même sous la camionnette.','L''officier contrôle tout, même sous le bus.','un officier qui contrôle une camionnette','un officier sur un navire','dramatic','exaggeration'),
(4984,'fr','Mallette à la main, il fait du skate !','Café à la main, il fait du skate !','faire du skate avec une mallette','une mallette pleine de papiers','gossip','exclamation'),
(4985,'fr','Les écrans sont bien fixés.','Les miroirs sont bien fixés.','fixer des écrans au mur','fixer une date de réunion','business','none'),
(4986,'fr','Le mur est un poil lumineux.','Le mur est un poil sombre.','des écrans bleus lumineux','une journée lumineuse et ensoleillée','ironic','understatement'),
(4987,'fr','Elle a présenté. Le café a gagné.','Elle a présenté. La pizza a gagné.','présenter son travail','présenter une émission télé','ironic','exaggeration'),
(4988,'fr','L''attaque commence !','Le pique-nique commence !','une attaque médiévale','une crise cardiaque','dramatic','exclamation'),
(4989,'fr','Ils dévalent la colline à l''assaut !','Ils dévalent la route à l''assaut !','charger du haut d''une colline','rouler en bas d''une colline','dramatic','exclamation'),
(4991,'fr','Quel tas de vêtements en désordre !','Quel tas de livres en désordre !','un tas de vêtements en désordre','une table de cuisine en désordre','dramatic','exclamation'),
(4992,'fr','Tout ce repassage ! Elle est occupée.','Toute cette cuisine ! Elle est occupée.','occupée par le repassage','occupée par la vaisselle','dramatic','exclamation'),
(4993,'fr','Elle est toute seule sur le lac.','Elle est toute seule sur la plage.','seule sur une île minuscule','seule dans une grande ville','chill','none'),
(4994,'fr','Elle utilise une cuillère en bois.','Elle utilise une cuillère en métal.','une longue cuillère en bois','une planche à découper en bois','chill','none'),
(4995,'fr','Une fontaine avec une sculpture.','Une fontaine avec une horloge.','une sculpture de fontaine en pierre','une sculpture de glace de mariage','chill','none'),
(4996,'fr','Les pigeons adorent son cornet de glace.','Les mouettes adorent son cornet de glace.','un cornet de glace','un cône de signalisation orange','gossip','guessing'),
(4997,'fr','Il a un rire bruyant.','Il a un rire discret.','un rire au Colisée','un rire à Paris','chill','none'),
(4998,'fr','Le tunnel est fait de portiques.','Le tunnel est fait d''arbres.','un tunnel de portiques de sanctuaire','un tunnel sous la mer','chill','none'),
(4999,'fr','Il combat un épéiste.','Il combat un archer.','combattre un épéiste','combattre un gros rhume','chill','none'),
(5000,'fr','Ses tranches fines sont parfaites.','Ses tranches épaisses sont parfaites.','de fines tranches de poisson','de fines tranches de pain','flirt','none'),
(5001,'fr','Ce paysage valait le coup.','Cette plage valait le coup.','un paysage de montagne','un tableau de paysage','slang','cliche'),
(5002,'fr','Ils sautent à l''eau au crépuscule.','Ils sautent à l''eau à midi.','un lac en forêt au crépuscule','le crépuscule dans une grande ville','chill','none'),
(5003,'fr','Un explorateur taille un chemin.','Un explorateur taille un arbre.','un explorateur avec une machette','un explorateur avec une carte','chill','none'),
(5004,'fr','Le kangourou bondit en avant.','Le kangourou bondit en arrière.','bondir sur le sable','bondir hors du lit','chill','none'),
(5005,'fr','Dans cette baie, rien ne lui échappe.','Dans ce parc, rien ne lui échappe.','des bateaux dans une baie calme','une baie pleine de glace','gossip','guessing'),
(5007,'fr','Oui ! Sa clé est dans la serrure !','Oui ! Sa clé est dans la voiture !','une clé dans la serrure','un cadenas sur un vélo','dramatic','exclamation'),
(5008,'fr','Elle a déverrouillé la porte en bois.','Elle a déverrouillé la porte du garage.','déverrouiller la porte en bois','déverrouiller un téléphone','chill','none'),
(5009,'fr','L''enfant glisse vers le bas.','L''enfant grimpe vers le haut.','un enfant sur un toboggan','un enfant sur une balançoire','chill','none'),
(5010,'fr','Vive le roi !','Vive la reine !','un roi sur un balcon','un roi à cheval','dramatic','cliche'),
(5011,'fr','Le vieux couple s''embrasse, trop mignon !','Le vieux couple danse, trop mignon !','un vieux couple qui s''embrasse','un vieux couple qui danse','gossip','exclamation'),
(5012,'fr','Paris déborde de romance !','Paris déborde de neige !','la romance à Paris','un roman d''amour','dramatic','exaggeration'),
(5013,'fr','La cuisine bon marché est vieille.','La cuisine bon marché est immense.','une vieille cuisine bon marché','une voiture rapide bon marché','chill','none'),
(5014,'fr','Le cuisinier riche a la plus belle vue.','Le cuisinier riche a le plus beau chien.','la cuisine d''un homme riche','la voiture d''un homme riche','gossip','none'),
(5015,'fr','Du pain fait maison, pétri à la main.','Des pâtes faites maison, pétries à la main.','une miche de pain fait maison','de la confiture maison en pots','chill','none'),
(5016,'fr','Il plie les genoux.','Il plie les bras.','genoux nus en squat','un genou à terre','business','none'),
(5017,'fr','Un arc-en-ciel de légumes coupés !','Un arc-en-ciel de fruits coupés !','des légumes coupés en rangées','des fleurs coupées dans un vase','dramatic','exclamation'),
(5018,'fr','Ce plat a l''air trop savoureux !','Cette soupe a l''air trop savoureuse !','un bol de riz savoureux','une part de gâteau savoureuse','gossip','exclamation'),
(5020,'fr','Deux personnes pour remplacer une ampoule !','Cinq personnes pour remplacer une ampoule !','remplacer une ampoule grillée','remplacer un pneu crevé','low_iq','cliche'),
(5021,'fr','Quelle dame élégante, à servir le thé.','Quelle dame élégante, à servir le vin.','une dame en bonnet','une dame à cheval','flirt','none'),
(5022,'fr','Le lustre brille de mille feux !','Le miroir brille de mille feux !','un lustre qui brille','des chaussures qui brillent','dramatic','exclamation'),
(5024,'fr','Elle a tous les dictionnaires !','Elle a tous les livres de cuisine !','une pile de dictionnaires','une appli de dictionnaire','dramatic','exaggeration'),
(5025,'fr','MDR, cette blague est trop drôle !','MDR, ce cours est trop drôle !','une blague sur un téléphone','une blague du prof','gossip','exclamation'),
(5026,'fr','Son téléphone est hilarant aujourd''hui.','Son livre est hilarant aujourd''hui.','hilarant en plein cours','hilarant à un mariage','gossip','none'),
(5027,'fr','La juge utilise son marteau.','La juge utilise son téléphone.','une juge avec un marteau','une juge en perruque','business','none'),
(5028,'fr','Affaire difficile ? Juste quelques livres.','Affaire difficile ? Juste quelques stylos.','une affaire judiciaire difficile','un examen difficile','ironic','understatement'),
(5029,'fr','Le geste de ce gars dit : j''ai gagné !','Le geste de cette fille dit : j''ai gagné !','un geste de victoire du poing','un geste grossier de la main','dramatic','guessing'),
(5030,'fr','Son costume a toutes les couleurs !','Son chapeau a toutes les couleurs !','un costume arc-en-ciel à plumes','un costume pour Halloween','gossip','exaggeration'),
(5031,'fr','Le chef pointe droit devant.','Le chef est assis.','un chef sur une montagne','un chef sur une plage','chill','none'),
(5032,'fr','Elle mène l''équipe droit devant.','Elle ramène l''équipe en arrière.','marcher devant le groupe','préparer le voyage à l''avance','business','none'),
(5033,'fr','Les voisins entendent bien ces tambours.','Les voisins entendent bien ces cors.','battre les tambours','un solo de tambour','ironic','guessing'),
(5034,'fr','Chez elle, tout se renverse !','Chez elle, tout brûle !','du lait renversé sur la table','renverser du café sur un ordi','ironic','exaggeration'),
(5035,'fr','Ce jongleur a du talent !','Ce chanteur a du talent !','un talent pour jongler','un concours de talents','slang','exclamation'),
(5036,'fr','Elle enseigne, il apprend. Lentement.','Il enseigne, elle apprend. Lentement.','apprendre à jongler','apprendre à danser','chill','banter'),
(5037,'fr','Elle est sur un trottoir parisien.','Elle est sur un pont parisien.','un large trottoir pavé','une table de café en terrasse','chill','none'),
(5038,'fr','Un rythme régulier en montant la Grande Muraille.','Un rythme régulier en descendant la Grande Muraille.','un rythme de course régulier','un rythme de marche lent','chill','none'),
(5039,'fr','Il ouvre les cages.','Il ferme les cages.','ouvrir les cages à oiseaux','nettoyer les cages à oiseaux','chill','none'),
(5040,'fr','Un fauteuil ? Sur un vélo ? Mais bien sûr.','Un canapé ? Sur un vélo ? Mais bien sûr.','un fauteuil en velours jaune','un fauteuil dans une voiture','ironic','understatement'),
(5041,'fr','Un éclair blanc illumine le toit.','Un éclair vert illumine le toit.','un éclair blanc aveuglant','un flash d''appareil photo en intérieur','dramatic','none'),
(5042,'fr','La séance jambes a été douloureuse !','La séance bras a été douloureuse !','des jambes raides et douloureuses','un coup de soleil douloureux','dramatic','exclamation'),
(5043,'fr','Le lion n''est pas silencieux.','Le lion n''est pas seul.','un lion pas du tout silencieux','un lion silencieux','ironic','understatement'),
(5044,'fr','Il entend à travers la porte.','Il entend à travers le mur.','entendre à travers une porte','entendre la sonnette','chill','none'),
(5045,'fr','Les enceintes font un gros son !','La batterie fait un gros son !','le son d''un boombox','le son d''un autoradio','low_iq','exclamation'),
(5046,'fr','La télévision l''a fait sursauter !','La télévision l''a fait pleurer !','regarder la télévision','réparer la télévision','slang','blaming_someone'),
(5047,'fr','Ce soir, personne ne quitte le salon.','Ce soir, personne ne quitte la cuisine.','un salon douillet','nettoyer le salon','gossip','guessing'),
(5048,'fr','Gros cadenas, portes toujours fermées.','Gros cadenas, portes grandes ouvertes.','des portes bien fermées','les yeux bien fermés','ironic','understatement'),
(5049,'fr','Il ferme la porte d''entrée.','Il ferme la porte du garage.','fermer une porte d''entrée','fermer un magasin','chill','none'),
(5050,'fr','Il a perdu, et les invités sont partis.','Il a gagné, et les invités sont partis.','perdre une élection','perdre ses clés de voiture','gossip','none'),
(5051,'fr','Elle l''a perdu. Le passeport, peut-être ?','Elle l''a trouvé. Le passeport, peut-être ?','perdre un truc important','perdre un match de foot','gossip','guessing'),
(5052,'fr','Les sacs ne sont pas légers.','Les chaises ne sont pas légères.','des valises pas légères','un bagage à main léger','chill','understatement'),
(5053,'fr','L''étiquette affiche sa photo.','L''étiquette affiche son chien.','une étiquette avec sa photo','une étiquette sur un bocal','business','none'),
(5054,'fr','Le frérot soulève la moitié de la maison.','Le frérot soulève la moitié de la tente.','soulever des valises dans un van','soulever des poids à la salle','slang','exaggeration'),
(5055,'fr','Deux organes roses : les poumons.','Deux organes roses : les reins.','une paire d''organes respiratoires','un orgue d''église qui joue','nerd','none'),
(5058,'fr','Le garçon adore le facteur maintenant.','Le garçon adore le prof maintenant.','un facteur avec des lettres','un facteur avec un chien','gossip','guessing'),
(5059,'fr','Il a reçu une tonne de lettres !','Il a reçu une tonne de fleurs !','une pile de lettres','une lettre de l''école','slang','exclamation'),
(5061,'fr','Oh waouh, quel aquarium !','Oh waouh, quel volcan !','un immense aquarium','une immense piscine','dramatic','exclamation'),
(5062,'fr','Le chef dessine un graphique.','Le chef dessine un chat.','un chef qui donne des consignes','un chef qui fait une pause','business','none'),
(5063,'fr','La colonne avance en ordre.','La foule avance en ordre.','une colonne de rangs en marche','une colonne dans un journal','business','none'),
(5064,'fr','Cent trompettes. Mes pauvres oreilles !','Cent violons. Mes pauvres oreilles !','défiler avec des trompettes','une trompette de club de jazz','dramatic','exaggeration'),
(5065,'fr','Une longue allée d''épices.','Une longue allée de chaussures.','une allée d''étals d''épices','l''allée d''un avion','chill','none'),
(5066,'fr','Juste une olive, comme échantillon.','Juste une datte, comme échantillon.','une olive en échantillon','un échantillon d''épices','ironic','understatement'),
(5067,'fr','Le mariage commence par un baiser !','Le mariage commence par une dispute !','un mariage sous les confettis','un mariage à l''église','dramatic','exclamation'),
(5068,'fr','La mariée donne une bague.','La mariée fait un discours.','une mariée sur la plage','une mariée à l''église','chill','none'),
(5069,'fr','Oh waouh ! Il apprécie le massage.','Oh waouh ! Il apprécie le café.','apprécier un massage de la nuque','apprécier un massage des pieds','dramatic','exclamation'),
(5070,'fr','Elle teste tous les matelas.','Elle teste tous les oreillers.','allongée sur un matelas','porter un matelas','chill','none'),
(5071,'fr','Il révise le véhicule.','Il révise le vélo.','réviser une voiture argentée','réviser une machine à laver','business','none'),
(5072,'fr','Le liquide brun est très visqueux.','Le liquide vert est très visqueux.','verser un liquide brun','verser un liquide transparent','nerd','none'),
(5073,'fr','Ce médicament a un goût horrible !','Ce médicament a un goût délicieux !','une cuillère de médicament brun','un médicament pour chien','dramatic','exclamation'),
(5074,'fr','Tout le monde se présente à elle.','Tout le monde se présente à lui.','présenter une nouvelle collègue','présenter un nouveau produit','business','none'),
(5075,'fr','Mains collantes, cornet vide. « Génial. »','Mains collantes, cornet plein. « Génial. »','des mains collantes de glace','du scotch collant sur un carton','ironic','understatement'),
(5076,'fr','Elle est nouveau membre du club.','Elle est nouveau membre du groupe.','un nouveau membre du club','un membre d''un groupe de musique','business','none'),
(5077,'fr','Il s''est rappelé chaque carte, facile.','Elle s''est rappelé chaque carte, facile.','se rappeler les réponses des cartes','le rappel d''une voiture défectueuse','slang','understatement'),
(5079,'fr','Taco d''abord, pyramide ensuite.','Taco d''abord, plage ensuite.','une pyramide dans la jungle','une pyramide dans le désert','ironic','cliche'),
(5080,'fr','La robe jaune lui va à merveille.','Le manteau jaune lui va à merveille.','une robe d''été jaune vif','un imperméable jaune vif','flirt','none'),
(5081,'fr','Le violet, c''est sa couleur.','Le vert, c''est sa couleur.','une robe violette ajustée','un foulard en soie violet','flirt','none'),
(5082,'fr','Deux chignons ? Super coiffure.','Deux tresses ? Super coiffure.','une coiffure à deux chignons','une coiffure avec une frange','flirt','none'),
(5083,'fr','Ils ajoutent des baies.','Ils ajoutent des noix.','des baies rouges dans la pâte','cueillir des baies en forêt','chill','none'),
(5084,'fr','La robe de bal verte est sublime !','La robe de bal rouge est sublime !','une longue robe verte','une pochette de soirée verte','dramatic','exclamation'),
(5085,'fr','Elle prend la même pose que la statue !','Elle prend la même pose que le garde !','un selfie avec une statue','un selfie avec un cheval','gossip','exclamation'),
(5086,'fr','Le sol est tellement brillant !','Le sol est tellement poussiéreux !','un sol en pierre brillant','un nouveau téléphone brillant','dramatic','exclamation'),
(5087,'fr','Les pattes ont rendu le sol sale.','Les pattes ont rendu le mur sale.','un sol carrelé sale','de la vaisselle sale dans l''évier','gossip','blaming_someone'),
(5088,'fr','Le garçon est réveillé et bâille.','Le garçon est réveillé et mange.','réveillé au lever du soleil','réveillé à minuit','chill','none'),
(5091,'fr','La petite moto est verte.','La petite moto est rouge.','une moto verte en ville','une moto verte à vendre','chill','none'),
(5092,'fr','Notre aide déplace les cartons comme un pro.','Notre aide déplace les plantes comme un pro.','un aide avec un carton','un aide avec une lampe','slang','exaggeration'),
(5093,'fr','La pelouse était un peu envahie par la végétation.','La piscine était un peu envahie par la végétation.','tondre une pelouse envahie','une haie envahie par la végétation','ironic','understatement'),
(5094,'fr','Il contracte son bras maigre.','Il contracte sa jambe maigre.','contracter un bras maigre','porter un jean slim','chill','none'),
(5095,'fr','Il lève les yeux, plein d''émerveillement !','Il baisse les yeux, plein d''émerveillement !','émerveillement face à un squelette géant','émerveillement face à une pièce minuscule','dramatic','exclamation'),
(5096,'fr','Les champignons poussent dans le sol.','Les champignons poussent dans l''eau.','un champignon sur le sol','un champignon sur une pizza','chill','none'),
(5097,'fr','Sa musique a figé toute la rue.','Sa musique a vidé toute la rue.','de la musique de rue','un magasin de musique','chill','exaggeration'),
(5098,'fr','Il adore son équipe nationale.','Elle adore son équipe nationale.','les couleurs nationales sur le visage','une fête nationale','chill','guessing'),
(5100,'fr','Ils fixent des photos sur une carte.','Ils fixent des photos sur une porte.','fixer des photos sur une carte','fixer des cartes au mur','chill','none'),
(5102,'fr','Cette ruelle est hyper étroite !','Cette ruelle est hyper large !','une ruelle étroite de la médina','une ruelle pleine de chats','slang','exaggeration'),
(5103,'fr','Le cou d''une girafe est au-dessus d''elle !','Le cou d''un cheval est au-dessus d''elle !','le long cou d''une girafe','un serpent autour de son cou','dramatic','exclamation'),
(5104,'fr','Leur conversation est amicale.','Leur conversation est houleuse.','une conversation par-dessus la clôture','une conversation à une conférence','chill','none'),
(5105,'fr','Un fossé plein de canards.','Un fossé plein de bateaux.','un fossé d''eau tout droit','un fossé le long de l''autoroute','chill','exaggeration'),
(5107,'fr','Tous les deux bercent le bébé.','Tous les deux lavent le bébé.','bercer un nouveau-né','bercer une tasse de thé','chill','none'),
(5108,'fr','Le village est sur l''eau.','Le village est sur la colline.','un village sur pilotis','un village sous la neige','business','none'),
(5109,'fr','Une douzaine de cupcakes sucrés, et elle mange seule.','Une douzaine de cookies sucrés, et elle mange seule.','un plateau de cupcakes sucrés','un thé bien sucré','ironic','guessing'),
(5110,'fr','Le parc est très calme.','La plage est très calme.','un parc calme et brumeux','une plage calme et brumeuse','chill','none'),
(5111,'fr','Elle soigne un enfant malade.','Elle soigne un chiot malade.','soigner un enfant malade','siroter un verre d''eau','chill','none'),
(5112,'fr','Des grains volent dans les airs.','Des grains volent vers une tasse.','des grains de riz qui tombent','un grain de sable','chill','none'),
(5113,'fr','Bon conseil : mange plus de poisson.','Bon conseil : mange plus de gâteau.','des conseils pour manger sain','des conseils sur l''argent','business','none'),
(5114,'fr','Les flamants roses s''envolent.','Les cygnes s''envolent.','une volée de flamants roses','un flamant rose dans un zoo','chill','none'),
(5115,'fr','Elle examine un insecte.','Elle examine une fleur.','examiner un petit insecte','réviser pour un examen','chill','none'),
(5116,'fr','Il ouvre toutes les fenêtres !','Il ferme toutes les fenêtres !','ouvrir les fenêtres','ouvrir un cadeau','dramatic','exclamation'),
(5117,'fr','Il kiffe trop cette librairie !','Il déteste trop cette librairie !','une vieille librairie bondée','une librairie qui ferme','slang','exclamation'),
(5119,'fr','L''entrée a des portes en bois.','L''entrée a des portes en verre.','l''entrée du parc','l''entrée du musée','chill','none'),
(5120,'fr','C''est fini ! Les chirurgiens sont contents.','C''est fini ! Les boulangers sont contents.','des chirurgiens autour d''un patient','des chirurgiens en salle d''attente','dramatic','exclamation'),
(5121,'fr','Elle retire les muffins.','Elle retire les cookies.','retirer une plaque de muffins','retirer la porte du four','chill','none'),
(5122,'fr','Ils ont tous accompli leurs objectifs.','Ils ont tous raté leurs objectifs.','accomplir un objectif difficile','avoir de bonnes notes','chill','none'),
(5123,'fr','Café, évier et baignoire inondent tout !','Café, évier et four inondent tout !','une baignoire qui inonde tout','une route inondée après la pluie','dramatic','exaggeration'),
(5124,'fr','Marathon dans la vieille ville.','Marathon dans la forêt.','courir un marathon en ville','un marathon de films','chill','none'),
(5125,'fr','Ils montent une révolution !','Ils montent un mariage !','monter une vieille pièce','organiser une manif','dramatic','exclamation'),
(5126,'fr','Il est fier de son entreprise.','Il est fier de sa voiture.','une petite entreprise du coin','une grosse entreprise en ligne','chill','none'),
(5127,'fr','La valise ne veut pas fermer !','La valise ne veut pas s''ouvrir !','fermer une valise pleine','fermer une fenêtre','dramatic','exclamation'),
(5129,'fr','Les meubles sont sous des bâches.','Les meubles sont sous des serviettes.','des bâches grises sur les meubles','une couverture sur un livre','business','none'),
(5130,'fr','Son cerf-volant vole trop haut !','Son drone vole trop haut !','faire voler un cerf-volant','un cerf-volant dans un arbre','slang','exaggeration'),
(5131,'fr','Il se concentre sur le ballon.','Il se concentre sur les garçons.','se concentrer sur le ballon','se concentrer sur la foule','chill','none'),
(5133,'fr','Elle crie dans le parc.','Elle crie dans la piscine.','crier pendant un jeu de statues','crier devant un film d''horreur','chill','none'),
(5134,'fr','Les parents sont un peu occupés.','Les chiens sont un peu occupés.','des parents qui nourrissent un bébé','des parents qui nourrissent les canards','ironic','understatement'),
(5135,'fr','Place serrée, créneau parfait.','Grande place, créneau parfait.','une place de parking serrée','le lancement d''une fusée spatiale','flirt','none'),
(5136,'fr','Le débat devient bruyant !','Le débat devient calme !','un débat bruyant','un débat à la télé','dramatic','exclamation'),
(5137,'fr','Le parlement est plein aujourd''hui.','Le parlement est vide aujourd''hui.','un parlement plein','un parlement vide','business','none'),
(5138,'fr','Elle est dans le train maintenant.','Elle est dans le bus maintenant.','une place dans le train','une place dans l''avion','chill','none'),
(5139,'fr','Au début, les pages étaient vierges.','Au début, les pages étaient pleines.','une page de passeport vierge','un regard vide','chill','none'),
(5140,'fr','Le tampon lui permet d''entrer.','Le tampon lui permet de conduire.','la permission d''entrer','la permission de fumer','business','none'),
(5141,'fr','Le médecin a un stéthoscope.','Le médecin a un appareil photo.','un médecin avec un stéthoscope','un médecin dans une ambulance','chill','none'),
(5142,'fr','Le quartier est décoré.','Le quartier est désert.','un quartier décoré','un vide-grenier de quartier','chill','none'),
(5144,'fr','Les filles lâchent des colombes !','Les garçons lâchent des colombes !','lâcher des colombes blanches','nourrir des colombes blanches','dramatic','exclamation'),
(5145,'fr','Le tramway est juste derrière lui.','Le bus est juste derrière lui.','un tramway sur la place','un tramway sur un pont','chill','none'),
(5146,'fr','L''épluchure fait une seule longue bande !','L''épluchure fait deux petites bandes !','une longue bande d''épluchure','une bande de scotch','dramatic','exclamation'),
(5147,'fr','Tant de gens qui traversent !','Tant de voitures qui traversent !','des gens qui remplissent le passage','des gens qui attendent le bus','dramatic','exclamation'),
(5148,'fr','Ville vide, petit matin : bonjour !','Ville vide, pleine nuit : bonne nuit !','une rue vide le matin','une rue animée le matin','dramatic','exclamation'),
(5149,'fr','Quelle grande pharmacie à l''ancienne !','Quelle grande boulangerie à l''ancienne !','une grande pharmacie ancienne','une pharmacie d''hôpital','dramatic','exclamation'),
(5150,'fr','Il présente une ordonnance.','Il présente un billet de train.','tendre une ordonnance','rédiger une ordonnance','business','none'),
(5151,'fr','Le cadre est argenté.','Le cadre est doré.','un cadre photo argenté','un cadre de fenêtre argenté','chill','none'),
(5152,'fr','Sa chambre, c''est que des coussins !','Sa chambre, c''est que des livres !','des coussins dans la chambre','des coussins dans le salon','dramatic','exaggeration'),
(5153,'fr','L''équipe plante la plate-bande.','L''équipe peint la plate-bande.','une plate-bande surélevée','un lit défait','business','none'),
(5154,'fr','Ses plantes d''intérieur, c''est une jungle.','Ses livres, c''est une jungle.','une pièce pleine de plantes d''intérieur','une plante d''intérieur à vendre','chill','exaggeration'),
(5155,'fr','Déjeuner pour toute la famille !','Déjeuner pour deux personnes seulement !','un grand déjeuner en famille','un déjeuner rapide au travail','dramatic','exclamation'),
(5156,'fr','Il a marqué, alors il s''agenouille.','Il a raté, alors il s''agenouille.','s''agenouiller sur la pelouse','s''agenouiller pour prier','dramatic','none'),
(5157,'fr','Tout le voisinage joue au foot !','Tout le voisinage joue au volley !','un match de foot du voisinage','une course de vélo du voisinage','dramatic','exaggeration'),
(5158,'fr','Il connecte les câbles.','Il coupe les câbles.','connecter une config gaming','rester connecté avec ses potes','nerd','none'),
(5159,'fr','Le tuyau l''a mouillé exprès.','Le chien l''a mouillé exprès.','mouiller le visage du plombier','arroser les plantes de la cuisine','ironic','blaming_someone'),
(5160,'fr','Il file sous la pluie.','Il file sous la neige.','filer devant les pigeons','filer devant la police','chill','none'),
(5161,'fr','Il se tient devant une cathédrale.','Il se tient devant un château.','la tour d''une cathédrale en brique','dans une cathédrale sombre','chill','none'),
(5162,'fr','De belles vues et des raviolis.','De belles vues et des crêpes.','un beau lac de montagne','une belle plage','chill','none'),
(5164,'fr','Cette campagne a tout : affiches, débats, confettis.','Cette campagne a tout : affiches, débats, feux d''artifice.','une campagne électorale','une campagne anti-tabac','gossip','exaggeration'),
(5169,'fr','Il poste une carte postale.','Il poste un colis.','poster une carte postale','poster un colis','chill','none'),
(5170,'fr','Il remet un colis.','Il remet une pizza.','un colis d''anniversaire emballé','un séjour tout compris','chill','none'),
(5171,'fr','Il ajoute du bouillon dans la marmite.','Il ajoute du lait dans la marmite.','ajouter des légumes dans la marmite','ajouter du sel dans la soupe','chill','none'),
(5172,'fr','Pauvre pâte ! Il la cogne.','Pauvre porte ! Il la cogne.','cogner une pâte à pain','cogner à la porte d''entrée','dramatic','exclamation'),
(5173,'fr','Heureusement qu''elle a un imperméable.','Heureusement qu''elle a un chapeau de soleil.','un imperméable rouge à capuche','un imperméable sur un portemanteau','chill','understatement'),
(5174,'fr','C''est un dîner joyeux.','C''est un petit-déjeuner joyeux.','un joyeux dîner en famille','une joyeuse fête de bureau','chill','none'),
(5175,'fr','Jolie moustache, mains sûres.','Jolie barbe, mains sûres.','un serveur à moustache','un serveur qui rase sa moustache','flirt','none'),
(5176,'fr','Du café chaud dans un grand mug.','Du thé chaud dans un grand mug.','un grand mug blanc','un mug sans anse','chill','none'),
(5177,'fr','Elle sert avec une théière.','Elle sert avec une bouteille.','verser d''une théière blanche','une théière sur la cuisinière','chill','none'),
(5178,'fr','Elle fait des gâteaux avec un foulard.','Elle fait des gâteaux avec un chapeau.','un foulard bleu marine','un foulard dans le vent','chill','none'),
(5179,'fr','Elle tend le bras pour atteindre le four.','Elle tend le bras pour atteindre le frigo.','atteindre un four chaud','atteindre l''étagère du haut','chill','none'),
(5180,'fr','L''orateur est au pupitre.','L''orateur est au piano.','un orateur au pupitre','un orateur dans le public','business','none'),
(5181,'fr','Sa signature est à l''encre bleue.','Sa signature est à l''encre rouge.','une signature bleue toute fraîche','une signature sur un chèque','business','none'),
(5182,'fr','Regarde, la fresque, c''est sa réussite à elle.','Regarde, la fresque, c''est sa réussite à lui.','une fresque, une vraie réussite','un succès de jeu vidéo','gossip','none'),
(5183,'fr','Tellement passionné que la craie vole !','Tellement passionné que les livres volent !','un vieux prof passionné','un jeune chanteur passionné','dramatic','exaggeration'),
(5184,'fr','Il a fait sa demande. Trop romantique !','Il a chanté. Trop romantique !','une demande romantique','une comédie romantique','flirt','exclamation'),
(5185,'fr','La gentillesse garde le monsieur au sec.','La gentillesse garde le chien au sec.','la gentillesse sous la pluie','la gentillesse au soleil','chill','none'),
(5186,'fr','Le public est sur la place.','Le public est dans l''église.','le public sur la place','le public au théâtre','chill','none'),
(5187,'fr','Trop costaud ! Il tire un chariot !','Trop costaud ! Il tire une voiture !','tirer un chariot de ferme','tirer une charrette à cheval','low_iq','exclamation'),
(5188,'fr','Une botte ? Grosse déception.','Un poisson ? Grosse déception.','la déception sur un ponton','la déception au zoo','ironic','understatement'),
(5189,'fr','Point sur le temps : il pleut toujours.','Point sur le temps : il neige toujours.','vérifier le temps à la main','la météo à la télé','chill','none'),
(5190,'fr','Venteux ? Elle adore !','Ensoleillé ? Elle adore !','un front de mer venteux','un sommet venteux','slang','exclamation'),
(5191,'fr','Un drapeau sur une plaine enneigée.','Un drapeau sur une plage de sable.','une plaine blanche enneigée','une rue enneigée en ville','chill','none'),
(5192,'fr','Rien que de la neige jusqu''à l''horizon.','Rien que du sable jusqu''à l''horizon.','de la neige jusqu''à l''horizon','la mer à l''horizon','dramatic','none'),
(5194,'fr','Devine qui adore ce roman ?','Devine qui adore ce film ?','lire un gros roman','écrire un roman','gossip','none'),
(5195,'fr','Ses livres prennent tout le banc.','Ses chaussures prennent tout le banc.','des livres sur un banc public','un chien sur un banc','gossip','exaggeration'),
(5196,'fr','Son chignon et son livre la suivent partout.','Son chignon et son chien la suivent partout.','un chignon blond sur le dessus','un petit pain sucré','chill','exaggeration'),
(5197,'fr','Le bureau se rebelle !','Le bureau fait la sieste !','se rebeller contre le boulot','se rebeller contre ses parents','dramatic','exclamation'),
(5198,'fr','Elle lui tend une feuille.','Elle lui tend une tasse.','une petite feuille écrite','un drap sur un lit','chill','none'),
(5200,'fr','Quel groupe animé !','Quel chien animé !','un salon animé','une boîte de nuit animée','dramatic','exclamation'),
(5202,'fr','Elle a mis tout le magasin dans le frigo !','Elle a mis tout le magasin dans le four !','mettre les courses au frigo','mettre la nourriture sur la table','dramatic','exaggeration'),
(5204,'fr','La pièce s''est vraiment améliorée.','Le jardin s''est vraiment amélioré.','améliorer une vieille pièce','améliorer leur anglais','business','none'),
(5205,'fr','Elle prête serment.','Il prête serment.','prêter serment','rompre un serment','chill','none'),
(5206,'fr','Elle a trouvé la preuve !','Elle a perdu la preuve !','épingler des preuves','cacher la preuve','dramatic','guessing'),
(5207,'fr','Grandes montagnes, beaucoup de sueur.','Grands lacs, beaucoup de sueur.','ruisselant de sueur','la sueur après un sauna','dramatic','none'),
(5208,'fr','Chaque cuisine l''épate !','Chaque boisson l''épate !','trois cuisines différentes','une seule cuisine','gossip','exaggeration'),
(5209,'fr','Personne ne bosse ; ils se prélassent tous.','Personne ne bosse ; ils dansent tous.','se prélasser dans un hamac','se prélasser sur un bateau','ironic','exaggeration')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
