begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(5210,'fr','Une oie « terrifiante » les a fait reculer.','Un chien « terrifiant » les a fait reculer.','reculer devant une oie','reculer devant la pluie','ironic','exaggeration'),
(5211,'fr','Quel heureux retour à la maison !','Quel triste retour à la maison !','un heureux retour à la maison','un retour à l''école','dramatic','exclamation'),
(5212,'fr','Gros câlins à la gare !','Gros câlins à l''aéroport !','des câlins à la gare','une station de radio','dramatic','exclamation'),
(5214,'fr','Vélo, trottinette, puis désert !','Vélo, trottinette, puis jungle !','un chameau dans le désert','un chameau dans un zoo','dramatic','exclamation'),
(5215,'fr','Elle fait du cyclisme au bord d''un fjord.','Elle fait du cyclisme en ville.','du cyclisme au bord du fjord','du cyclisme en ville','chill','none'),
(5217,'fr','Il porte un gilet jaune.','Il porte un gilet orange.','un gilet de sécurité jaune','un gilet sous une chemise','chill','none'),
(5218,'fr','Elle inspecte chaque pièce.','Elle nettoie chaque pièce.','une pièce aux fenêtres en arc','une pièce avec une cheminée','chill','none'),
(5219,'fr','Les colocataires ont fait des pâtes. Miam.','Les colocataires ont fait des pizzas. Miam.','deux colocataires en appart','deux colocataires qui déménagent','low_iq','none'),
(5220,'fr','Quelqu''un coupe la rose.','Quelqu''un arrose la rose.','couper la tige d''une rose','couper les griffes d''un chien','chill','none'),
(5223,'fr','Son itinéraire est tracé en rouge.','Son itinéraire est tracé en bleu.','un itinéraire sur une carte','un itinéraire de bus en ville','chill','none'),
(5224,'fr','Il a une fanfare royale.','Il a un cheval royal.','un trône royal','un mariage royal','chill','none'),
(5226,'fr','Il a réussi à monter dans le wagon !','Il a réussi à monter dans le taxi !','sauter dans un wagon','une calèche tirée par des chevaux','dramatic','exclamation'),
(5227,'fr','Elle a plusieurs nouveaux fans.','Elle a plusieurs nouveaux chats.','plusieurs chiens qui courent','plusieurs voitures qui roulent','gossip','exaggeration'),
(5228,'fr','Il neige fort !','Il pleut fort !','il neige sur une place','il neige sur une plage','dramatic','exclamation'),
(5229,'fr','Elle a lancé une poignée de neige.','Elle a lancé une poignée de sable.','une poignée de neige poudreuse','une poignée de pièces','chill','none'),
(5230,'fr','La poupée cache une poupée !','La poupée cache une pièce !','une poupée en bois peinte','une maison de poupée','dramatic','exclamation'),
(5231,'fr','Son hospitalité inclut du thé.','Son hospitalité inclut de la bière.','l''hospitalité avec thé et gâteaux','un métier de l''hôtellerie','business','none'),
(5232,'fr','Elle navigue sur un yacht.','Elle nettoie un yacht.','un yacht à voile classique','un yacht dans un port','chill','none'),
(5233,'fr','Le défilé militaire est immense.','Le défilé militaire est minuscule.','un défilé militaire','un hôpital militaire','chill','none'),
(5234,'fr','Chaque rang est parfaitement aligné.','Chaque rang est un vrai bazar.','des rangs de femmes qui saluent','des rangs d''hommes qui courent','business','none'),
(5235,'fr','Elle tamponne la cargaison.','Elle peint la cargaison.','une cargaison au port à conteneurs','une cargaison à l''aéroport','chill','none'),
(5236,'fr','On aperçoit la ville à distance.','On aperçoit le chameau à distance.','des tours vues à distance','un appel longue distance','chill','none'),
(5239,'fr','Quelle libération parfaite !','Quel atterrissage parfait !','la libération d''un faucon','la sortie d''un album','dramatic','exclamation'),
(5242,'fr','Son peignoir en satin a l''air élégant.','Son peignoir en laine a l''air élégant.','un peignoir en satin élégant','une soirée élégante','flirt','none'),
(5243,'fr','Elle a planifié tout le mois.','Elle a planifié toute la semaine.','planifier tout le mois','planifier une réunion','business','none'),
(5245,'fr','Le produit chimique brille en violet !','Le produit chimique brille en orange !','un produit chimique violet lumineux','un produit chimique dans une cuve','dramatic','exclamation'),
(5246,'fr','Elle tient une fiole rose.','Elle tient un téléphone rose.','une fiole de liquide bleu','une fiole de thé chaud','nerd','none'),
(5248,'fr','Elle paie la location du scooter.','Elle paie la location du vélo.','la location d''un scooter','le loyer d''un appart','chill','none'),
(5249,'fr','Il lave une poêle qui a connu des jours meilleurs.','Il lave une tasse qui a connu des jours meilleurs.','laver une marmite noircie','se laver le visage','ironic','cliche'),
(5250,'fr','Elle est en appel pro.','Elle est en appel vidéo.','un appel sur le téléphone fixe','un appel vidéo sur ordinateur','business','none'),
(5251,'fr','Elle tape et téléphone en même temps !','Elle tape et mange en même temps !','taper tout en téléphonant','taper un SMS','dramatic','exclamation'),
(5252,'fr','Les fruits tropicaux sont en promo.','Les fruits surgelés sont en promo.','une pile de fruits tropicaux','un aquarium tropical','business','none'),
(5253,'fr','Ces personnes âgées dansent mieux que moi, sérieux.','Ces personnes âgées nagent mieux que moi, sérieux.','des danseurs âgés dans le parc','des nageurs âgés à la piscine','slang','exaggeration'),
(5254,'fr','Regarde ces partenaires danser !','Regarde ces partenaires nager !','danser avec un partenaire','jouer aux cartes avec un partenaire','flirt','exclamation'),
(5255,'fr','Il a l''air très coupable, et très choqué.','Elle a l''air très coupable, et très choquée.','un jeune homme coupable','un juge coupable','gossip','guessing'),
(5256,'fr','Un juge s''adresse à eux.','Un infirmier s''adresse à eux.','s''adresser à une salle comble','adresser une lettre','chill','none'),
(5257,'fr','Le majordome apporte le thé.','Le majordome apporte le vin.','un majordome qui apporte le thé','un majordome qui ouvre la porte','chill','none'),
(5259,'fr','Le gros chien secoue sa fourrure mouillée. Douche pour tout le monde.','Le gros chat secoue sa fourrure mouillée. Douche pour tout le monde.','secouer sa fourrure mouillée','brosser sa fourrure mouillée','ironic','exaggeration'),
(5260,'fr','Pris avec le gâteau. Quelle honte !','Pris avec la pizza. Quelle honte !','la honte pour un gâteau','la honte pour une assiette cassée','dramatic','exclamation'),
(5261,'fr','Même le joggeur a eu sa part !','Même le cycliste a eu sa part !','une part de pizza','une part de l''entreprise','gossip','exclamation'),
(5262,'fr','Quelle étagère « stable » !','Quelle table « stable » !','une étagère pas très stable','une chaise en bois stable','ironic','exclamation'),
(5263,'fr','Une photo est posée sur l''étagère.','Un miroir est posé sur l''étagère.','une photo de famille encadrée','prendre une photo de famille','chill','none'),
(5264,'fr','Elle déplace le canapé.','Elle déplace le frigo.','déplacer les meubles','passer les vitesses','chill','none'),
(5265,'fr','Le navire transporte des conteneurs.','Le navire transporte des voitures.','un navire avec des conteneurs','un camion avec des conteneurs','chill','none'),
(5266,'fr','Elle a fait tomber le téléphone !','Elle a fait tomber la tasse !','un téléphone tombé par terre','une cabine téléphonique','dramatic','exclamation'),
(5267,'fr','Son pistolet repose sur un support.','Son pistolet repose sur une chaise.','un pistolet sur un support','un pistolet dans un étui','business','none'),
(5268,'fr','Elle vise avec son fusil.','Elle nettoie son fusil.','tirer au fusil couchée','porter un fusil à ski','chill','none'),
(5269,'fr','Elle a acheté un manteau.','Elle a acheté une robe.','acheter un manteau olive','acheter une voiture neuve','business','none'),
(5270,'fr','Elle achète toutes les céréales du supermarché !','Elle achète toute la soupe du supermarché !','un chariot de supermarché','un parking de supermarché','gossip','exaggeration'),
(5271,'fr','Leur cri remplit le canyon !','Leur chanson remplit le canyon !','un cri au-dessus du canyon','un cri à l''aide','dramatic','exclamation'),
(5272,'fr','Les randonneurs s''enflamment.','Les randonneurs rentrent chez eux.','des randonneurs en fête au canyon','des randonneurs sous une tente','slang','none'),
(5273,'fr','Le mannequin assure en pantalon vert.','Le mannequin assure en pantalon orange.','un mannequin sur le podium','une maquette d''avion','slang','none'),
(5274,'fr','Douche ouverte. Maintenant il est trempé.','Douche fermée. Maintenant il est trempé.','trempé sous la douche','trempé sous la pluie','low_iq','none'),
(5275,'fr','Deux enfants égoïstes, une télécommande.','Deux enfants égoïstes, un téléphone.','des enfants égoïstes qui se disputent','un conducteur égoïste qui se gare','gossip','none'),
(5276,'fr','Un cookie, deux frères et sœurs : c''est la guerre.','Un gâteau, deux frères et sœurs : c''est la guerre.','une cabane entre frères et sœurs','des devoirs entre frères et sœurs','dramatic','exaggeration'),
(5277,'fr','Ils sont d''accord : moitié-moitié.','Ils sont d''accord : tout pour lui.','être d''accord pour partager un cookie','être d''accord pour partager une chambre','chill','none'),
(5278,'fr','Coin atteint. On continue.','Rivière atteinte. On continue.','le coin de deux rues','un coin de la pièce','business','none'),
(5279,'fr','Il signe un parchemin géant avec un stylo géant !','Il signe un parchemin géant avec un stylo minuscule !','signer un parchemin géant','lire un vieux parchemin','dramatic','exclamation'),
(5280,'fr','Elle lit le poteau indicateur.','Elle peint le poteau indicateur.','lire un poteau indicateur en bois','peindre un poteau indicateur en bois','chill','none'),
(5281,'fr','La star chante sur scène.','La star danse sur scène.','une star sur scène','une étoile dans le ciel','chill','none'),
(5282,'fr','Tout le monde chante une chanson.','Tout le monde écrit une chanson.','chanter une chanson','une chanson à la radio','gossip','none'),
(5283,'fr','C''est juste une petite tour d''assiettes.','C''est juste une petite tour de tasses.','une tour d''assiettes','une tour de verres','chill','understatement'),
(5284,'fr','J''adore ton armure métallique, chevalier.','J''adore ta couronne métallique, chevalier.','une armure entièrement métallique','un groupe de heavy metal','flirt','none'),
(5285,'fr','Le bonheur absolu au jardin.','Le bonheur absolu en cuisine.','le bonheur dans un jardin ensoleillé','le bonheur sur une plage ensoleillée','chill','none'),
(5286,'fr','Ils veulent tous les deux le sweat-shirt !','Ils veulent tous les deux le nounours !','tirer sur un sweat-shirt lilas','laver un sweat-shirt lilas','dramatic','exclamation'),
(5287,'fr','Quinze filles, zéro silence !','Quinze garçons, zéro silence !','une salle sans aucun silence','une minute de silence','dramatic','exaggeration'),
(5288,'fr','Il dévale la pente à skis !','Il dévale la pente en luge !','un virage carvé à skis','des skis contre un mur','dramatic','exaggeration'),
(5289,'fr','La peau manque d''humidité.','La peau manque de pores.','une peau sans humidité','de l''humidité sur une vitre','nerd','none'),
(5290,'fr','Quel gratte-ciel immense !','Quel phare immense !','un gratte-ciel à flèche','un gratte-ciel en construction','dramatic','exclamation'),
(5291,'fr','Tous les hommes d''affaires dorment.','Tous les hommes d''affaires lisent.','hommes d''affaires endormis en avion','hommes d''affaires endormis en train','chill','none'),
(5292,'fr','Personne ici n''est très productif.','Tout le monde ici est très productif.','une journée pas très productive','une réunion d''équipe productive','ironic','understatement'),
(5293,'fr','La balle est maintenant dans son gant.','La balle est maintenant dans sa casquette.','un gant de baseball en cuir','un gant pour l''hiver','chill','none'),
(5294,'fr','Ses pieds adorent les chaussons.','Ses pieds adorent les chaussettes.','des chaussons moutons tout doux','des chaussons sous le lit','chill','exaggeration'),
(5295,'fr','Il souffle dans un cor énorme.','Il souffle dans un cor minuscule.','souffler dans un long cor','une corne de mouton','chill','none'),
(5296,'fr','Il prépare des plats traditionnels !','Il achète des plats traditionnels !','cuisiner un plat traditionnel','une danse traditionnelle','dramatic','exclamation'),
(5297,'fr','Le vieux château est en ruine.','Le vieux pont est en ruine.','un château en ruine','un château sous la neige','chill','none'),
(5298,'fr','Son blazer est beige.','Son blazer est noir.','un blazer beige cintré','essayer un blazer','chill','none'),
(5299,'fr','Ses saucisses sont illégales ici !','Ses livres sont illégaux ici !','de la nourriture illégale en valise','stationnement illégal à l''aéroport','gossip','exclamation'),
(5300,'fr','La vipère est une vraie menace.','Le lézard est une vraie menace.','une menace sur les rochers','une menace dans une lettre','dramatic','none'),
(5301,'fr','Son allergie déteste ce pré.','Son allergie déteste cette plage.','une allergie au pollen','une allergie aux chiens','low_iq','exaggeration'),
(5302,'fr','Les fleurs l''ont fait éternuer !','Les fleurs l''ont fait pleurer !','éternuer sous les fleurs','peindre des fleurs de cerisier','dramatic','blaming_someone'),
(5304,'fr','Beurk ! De la saleté plein les mains !','Beurk ! De la peinture plein les mains !','de la saleté sur ses mains','de la saleté sur ses chaussures','dramatic','exclamation'),
(5305,'fr','Leur société travaille dur.','Leur société est en vacances.','toute une société au travail','une société en pleine fête','business','none'),
(5306,'fr','Si confortables sur un seul canapé !','Si confortables sur un seul lit !','confortables sur un canapé plein','confortables dans un grand lit','dramatic','exclamation'),
(5307,'fr','La pièce est très spacieuse.','La pièce est très petite.','un salon spacieux','un coffre de voiture spacieux','business','none'),
(5308,'fr','Un homme lui apporte des tournesols.','Un homme lui apporte des roses.','un bouquet de tournesols','un champ de tournesols','chill','none'),
(5309,'fr','Quelqu''un lui a laissé une note adorable.','Quelqu''un lui a laissé une note triste.','une note avec un smiley','une note sur le frigo','gossip','none'),
(5311,'fr','Maintenant, tout le groupe est calme.','Maintenant, tout le groupe est en colère.','calmes sous les couvertures','calme sous la pression','chill','none'),
(5314,'fr','Son panier contient tout Paris !','Son sac contient tout Paris !','un panier de souvenirs','un panier de fruits','slang','exaggeration'),
(5315,'fr','Elle a plein de cartes postales. Pour qui ?','Elle a plein de timbres. Pour qui ?','des cartes postales de Paris','écrire une carte postale','gossip','guessing'),
(5316,'fr','J''adore ses cheveux bouclés qui rebondissent.','J''adore ses cheveux raides qui rebondissent.','des cheveux bruns très bouclés','de longs cheveux blonds bouclés','flirt','none'),
(5318,'fr','Elle parle devant le public.','Elle chante devant le public.','parler dans un micro','parler au téléphone','business','none'),
(5319,'fr','L''araignée est sous sa toile.','L''araignée est au-dessus de sa toile.','une toile entre des branches','une toile dans un coin','chill','none'),
(5320,'fr','Elle montre une colonne vertébrale.','Elle montre un cœur.','montrer une colonne vertébrale','manifester dans la rue','business','none'),
(5321,'fr','Il patine comme un pro.','Il skie comme un pro.','patiner sur une jambe','patiner sur une route','slang','cliche'),
(5322,'fr','Soupe dégueu ! Il l''a crachée.','Thé dégueu ! Il l''a craché.','cracher une soupe verte','cracher un noyau de cerise','low_iq','none'),
(5323,'fr','Cette pierre a fait un gros plouf.','Ce bateau a fait un gros plouf.','lancer une grosse pierre','faire ricocher une pierre plate','slang','exaggeration'),
(5324,'fr','L''éponge a vaincu la sauce !','L''éponge a vaincu le fromage !','une éponge pleine de mousse','un gâteau éponge','dramatic','exclamation'),
(5327,'fr','La cliente porte une cape noire.','La cliente porte une cape blanche.','une cape de coiffeur noire','une cape de super-héros','chill','none'),
(5328,'fr','Elle renifle un chemisier pêche.','Elle renifle un chemisier blanc.','un chemisier pêche à volants','repasser un chemisier pêche','chill','none'),
(5329,'fr','La graine a une minuscule racine !','La graine a une minuscule fleur !','une graine avec une racine','une graine dans un bec','dramatic','exclamation'),
(5330,'fr','L''espion « secret » a un trou dans son journal.','L''espion « secret » a un trou dans son chapeau.','un espion derrière un journal','un espion derrière une porte','ironic','none'),
(5332,'fr','Le personnel fait preuve d''une grande unité.','Les clients font preuve d''une grande unité.','l''unité de l''équipe','l''unité du pays','business','none'),
(5333,'fr','Chaque escalier est plus chic !','Chaque escalier est plus sale !','un grand escalier en marbre','un escalier dans un phare','dramatic','exclamation'),
(5334,'fr','Les fans respectent ce moment.','Les fans ignorent ce moment.','respecter le moment','respecter la limitation de vitesse','chill','none'),
(5335,'fr','C''est une fan enthousiaste.','C''est une joueuse enthousiaste.','une fan de foot enthousiaste','une fan de tennis enthousiaste','chill','none'),
(5336,'fr','Sa casquette montre sa loyauté.','Son écharpe montre sa loyauté.','la loyauté envers le club','la loyauté envers le roi','dramatic','none'),
(5337,'fr','Croissant en bouche, il voyage par le rail.','Pizza en bouche, il voyage par le rail.','voyager par le rail','voyager par avion','gossip','none'),
(5338,'fr','Tu peux rester pour 10 euros ou pour 10 000 euros.','Tu peux rester pour 10 euros ou pour 1 000 euros.','rester dans une auberge de jeunesse','rester à la maison','business','cheap_quality'),
(5339,'fr','Elle conduit un bus.','Elle conduit un tram.','conduire un bus urbain','piloter un drone','chill','none'),
(5340,'fr','Un carton part au garage.','Un carton part dans la voiture.','un garage ouvert','un garage plein de voitures','business','none'),
(5341,'fr','Le garçon cloue une planche.','Le garçon peint une planche.','clouer une planche','clouer une affiche','chill','none'),
(5343,'fr','Les filles ont des lits jumeaux.','Les filles ont des lits superposés.','deux lits jumeaux assortis','une chambre twin à l''hôtel','chill','none'),
(5344,'fr','Ils ont fait une grande courtepointe !','Ils ont fait un grand drapeau !','une courtepointe en patchwork finie','une courtepointe sur un lit','dramatic','exclamation'),
(5345,'fr','Elle s''appuie contre la rambarde.','Elle s''appuie contre un arbre.','s''appuyer sur la rambarde d''un pont','s''appuyer sur une clôture de jardin','chill','none'),
(5346,'fr','Il se tapote l''estomac.','Il se tapote la tête.','un estomac plein','un estomac plein de soupe','chill','none'),
(5347,'fr','La circulation est à l''arrêt.','Les trains sont à l''arrêt.','un arrêt pour la circulation','un arrêt pour un café','chill','none'),
(5348,'fr','Elle remercie l''homme au parapluie.','Elle remercie l''homme au chien.','remercier un gentil inconnu','remercier le chauffeur du bus','chill','none'),
(5349,'fr','Elle décerne encore une médaille !','Elle décerne encore un trophée !','décerner une médaille','décerner un prix de la chanson','dramatic','exaggeration'),
(5350,'fr','En plein vol au-dessus du ruisseau. Courageux !','En plein vol au-dessus du lac. Courageux !','sauter par-dessus un ruisseau','nager dans un ruisseau','dramatic','exclamation'),
(5351,'fr','Lampadaires orange, trop cosy.','Lampadaires bleus, trop cosy.','une rangée de lampadaires','un lampadaire cassé','slang','none'),
(5352,'fr','Sa frustration est à 1000 %.','Sa frustration est à 0 %.','la frustration devant un ordi','la frustration face à un prof','nerd','exaggeration'),
(5353,'fr','La paperasse est en train de gagner.','La paperasse est en train de fondre.','des tours de paperasse','de la paperasse sur un ordi','dramatic','exaggeration'),
(5354,'fr','La classe la suit bien.','La classe le suit bien.','une classe dans le parc','une classe à l''école','business','none'),
(5357,'fr','Le chien a une poussette plus chic que la plupart des bébés.','Le chat a une poussette plus chic que la plupart des bébés.','une poussette chromée chic','une soirée déguisée','dramatic','exaggeration'),
(5359,'fr','L''hippopotame se cache d''elle.','Le canard se cache d''elle.','un hippopotame dans la rivière','un hippopotame sur le ponton','chill','guessing'),
(5360,'fr','Le métro est « un peu » bondé.','Le métro est « un peu » vide.','une station de métro bondée','une station de métro vide','ironic','understatement'),
(5361,'fr','Six sacs, c''est « facile » à pousser.','Six cartons, c''est « facile » à pousser.','pas un voyage facile','pas un examen facile','ironic','understatement'),
(5362,'fr','Les lunettes les plus loufoques de l''île !','Le chapeau le plus loufoque de l''île !','des lunettes cœur loufoques','des ballons cœur loufoques','dramatic','exaggeration'),
(5363,'fr','Ils aident le coureur.','Ils aident le cycliste.','aider un coureur épuisé','aider un touriste perdu','chill','none'),
(5364,'fr','Deux héros l''assistent !','Deux infirmiers l''assistent !','assister une coureuse épuisée','assister une conductrice épuisée','dramatic','exaggeration'),
(5365,'fr','Il baisse son arme.','Il nettoie son arme.','baisser une arme de paintball','charger une arme de paintball','chill','none'),
(5366,'fr','Il se rend !','Il attaque !','se rendre les mains en l''air','remettre son passeport','dramatic','exclamation'),
(5368,'fr','La chaleur les fait souffrir.','Le froid les fait souffrir.','souffrir de la chaleur','souffrir d''un rhume','dramatic','none'),
(5369,'fr','Un boxeur dur à cuire, trempé de sueur.','Un boxeur dur à cuire, trempé de pluie.','un jeune boxeur dur à cuire','un morceau de viande dur','chill','none'),
(5370,'fr','Il pagaie dans un canoë jaune.','Il pagaie dans un canoë rouge.','pagayer dans un canoë jaune','ramener un canoë à la maison','chill','none'),
(5371,'fr','Ils ont trop la classe avec leurs guirlandes de fleurs.','Ils ont trop la classe avec leurs couronnes en papier.','porter des guirlandes de fleurs','accrocher une guirlande à l''intérieur','slang','none'),
(5372,'fr','Son balai pousse des feuilles.','Son balai pousse de la neige.','un balai et des feuilles mortes','un balai dans la cuisine','chill','none'),
(5373,'fr','Tout s''agrandit !','Tout rétrécit !','un château gonflable qui s''agrandit','une boîte qui s''agrandit à l''étranger','dramatic','exclamation'),
(5374,'fr','L''eau est juste un peu trop peu profonde.','L''eau est juste un peu trop profonde.','nager en eau peu profonde','un bol à soupe peu profond','ironic','understatement'),
(5375,'fr','Elle balance son club comme une pro.','Elle nage comme une pro.','balancer un club de golf','balancer une batte de baseball','flirt','cliche'),
(5376,'fr','Il a appuyé sur l''interrupteur. Lumière !','Il a donné un coup de pied dans l''interrupteur. Lumière !','appuyer sur un interrupteur','un aiguillage de chemin de fer','dramatic','exclamation'),
(5377,'fr','Elle a rassemblé les assiettes.','Elle a rassemblé les pommes.','des assiettes sales rassemblées','rassembler des pommes rouges','business','none'),
(5378,'fr','Elle met la table.','Elle met le réveil.','mettre la table','mettre un réveil','business','none'),
(5379,'fr','Le tailleur a modifié la veste.','Le tailleur a modifié la chemise.','modifier une veste bleu marine','modifier les plans de voyage','chill','none'),
(5380,'fr','Il a même pris la boîte !','Elle a même pris la boîte !','prendre des trucs dans une boîte','emporter une boîte à l''école','gossip','exclamation'),
(5381,'fr','Un café et une grande conversation.','Une bière et une grande conversation.','une conversation autour d''un café','une conversation par e-mail','chill','none'),
(5382,'fr','Tout le monde à table en discute en même temps !','Tout le monde dans le bus en discute en même temps !','discuter à une table de café','en discuter au téléphone','dramatic','exaggeration'),
(5383,'fr','Trop de taxis sur l''avenue !','Trop de bus sur l''avenue !','une grande avenue pleine de taxis','une avenue bordée de vieux arbres','slang','exclamation'),
(5384,'fr','Les champions s''enflamment.','Les champions rentrent chez eux.','des champions en maillots rayés','un champion sur un podium','slang','none'),
(5385,'fr','L''échange se termine par une victoire.','L''échange se termine par une défaite.','une victoire au beach-volley','une victoire aux cartes','chill','none'),
(5386,'fr','Elle déchire le contrat.','Elle déchire les rideaux.','déchirer un contrat en deux','arracher les pages d''un livre','business','none'),
(5387,'fr','Ils partagent leur chagrin.','Ils partagent leur pizza.','du chagrin sur un canapé','du chagrin à un enterrement','dramatic','none'),
(5388,'fr','Elle a gagné le paquet de chips !','Elle a gagné le paquet de bonbons !','attraper un paquet de chips','un paquet de graines','slang','banter'),
(5389,'fr','Il l''esquive comme Messi.','Elle l''esquive comme Messi.','esquiver ses mains','esquiver un ballon de foot','slang','exaggeration'),
(5390,'fr','Un jeune fait du skate, trop stylé.','Un jeune fait du vélo, trop stylé.','un jeune sur un skate','un jeune à vélo','slang','none'),
(5391,'fr','Joli coucher de soleil, ils fixent un téléphone.','Joli coucher de soleil, ils fixent un livre.','fixer un téléphone','fixer le coucher de soleil','ironic','none'),
(5392,'fr','Ils hurlent de terreur !','Ils hurlent dans une voiture !','hurler de terreur','hurler de joie','dramatic','exclamation'),
(5393,'fr','Le T-rex lui a volé son calme.','Le chien lui a volé son calme.','perdre son calme','garder son calme','gossip','blaming_someone'),
(5394,'fr','Quelqu''un l''a revendiqué en premier !','Personne ne l''a revendiqué en premier !','revendiquer une terre gelée','réclamer un sac perdu','gossip','exclamation'),
(5395,'fr','Un employé du ranch longe la clôture à cheval.','Un employé du ranch longe la rivière à cheval.','un employé de ranch à cheval','un ranch plein de bétail','chill','none'),
(5396,'fr','Des drapeaux orange marquent la ligne.','Des drapeaux bleus marquent la ligne.','marquer une ligne avec des drapeaux','corriger une copie d''examen','business','none'),
(5397,'fr','Une vague puissante, quatre mouettes calmes.','Une vague puissante, quatre canards calmes.','une vague puissante qui déferle','un roi puissant','ironic','understatement'),
(5399,'fr','Deux acteurs jouent dans une pièce de théâtre.','Deux chiens jouent dans une pièce de théâtre.','une pièce de théâtre sur scène','une pièce de théâtre à l''école','chill','none'),
(5400,'fr','Elle est à l''opéra, et avec style.','Elle est au cinéma, et avec style.','une soirée à l''opéra','un chanteur d''opéra','flirt','none'),
(5401,'fr','Tout le monde se le demande.','Tout le monde dort.','se demander comment régler un souci','se demander quel temps il fera','chill','none'),
(5402,'fr','Elle examine sa gorge.','Elle examine ses oreilles.','un examen de la gorge','une écharpe autour de la gorge','chill','none'),
(5403,'fr','Elle regarde l''heure.','Elle regarde la carte.','regarder l''heure','perdre son temps','chill','none'),
(5404,'fr','Il est tellement avide de toasts !','Il est tellement avide de gâteau !','un mangeur de toasts avide','un mangeur de gâteau avide','dramatic','exclamation'),
(5405,'fr','Le bambin marche !','Le bambin rampe !','les premiers pas d''un bambin','les premiers mots d''un bambin','dramatic','exclamation'),
(5406,'fr','Ses orteils sont à côté d''un coquillage.','Ses orteils sont à côté d''un crabe.','des orteils écartés dans le sable','des orteils dans une tong','chill','none'),
(5407,'fr','Tout le monde veut aller aux toilettes, là.','Tout le monde veut aller à la sortie, là.','la queue pour les toilettes','nettoyer les toilettes','gossip','exaggeration'),
(5408,'fr','La trousse a réglé le problème de chaise.','La trousse a réglé le problème de table.','une trousse à outils rouge','une trousse de premiers secours','business','none'),
(5410,'fr','Il a une brosse à dents verte.','Il a une brosse à dents bleue.','une brosse à dents verte','une brosse à dents électrique','chill','none'),
(5411,'fr','Lui a droit à une traînée, elle à des volutes.','Lui a droit à des volutes, elle à une traînée.','une volute de dentifrice','une volute de chantilly','gossip','banter'),
(5412,'fr','Piliers grecs, marbre cannelé.','Piliers grecs, marbre rose.','d''immenses piliers en marbre cannelé','un pilier de parking','nerd','none'),
(5413,'fr','Des voitures partout. Cas désespéré !','Des vélos partout. Cas désespéré !','un embouteillage désespéré','une équipe de foot désespérée','low_iq','exclamation'),
(5414,'fr','Il tient la rambarde en métal.','Il tient le portail en métal.','la rambarde d''une passerelle','un train sur les rails','chill','none'),
(5415,'fr','Il attend au feu rouge.','Il attend à l''arrêt de bus.','un feu rouge','un panneau stop rouge','chill','none'),
(5416,'fr','Elle adore cette locomotive.','Elle adore cet hélicoptère.','une locomotive électrique orange','une locomotive à vapeur orange','gossip','guessing'),
(5417,'fr','Le tram finit au dépôt.','Le tram finit dans un musée.','des trams au dépôt','des bus au dépôt','chill','none'),
(5418,'fr','L''intérieur est tout en bois.','L''intérieur est tout en plastique.','un intérieur de tram en bois','un intérieur de voiture moderne','chill','none'),
(5419,'fr','Il réussit chaque transfert.','Il rate chaque transfert.','un transfert vers un ferry','un virement bancaire','chill','none'),
(5420,'fr','Il monte à bord d''un navire blanc.','Il monte à bord d''un navire rouge.','un petit navire de passagers','un énorme navire-cargo','chill','none'),
(5421,'fr','Il y a des ordures partout !','Il y a des fleurs partout !','une poubelle pleine d''ordures','une poubelle pleine de fleurs','dramatic','exaggeration'),
(5422,'fr','Recyclage à la LeBron.','Recyclage à la Messi.','jeter dans les bacs de recyclage','le recyclage de vieux vêtements','slang','exaggeration'),
(5423,'fr','Son sac à dos voyage à l''échelle mondiale.','Son sac à dos reste dans une seule ville.','des voyages à l''échelle mondiale','un réseau téléphonique mondial','chill','none'),
(5425,'fr','Le marché est conclu.','Le marché est annulé.','conclure un gros marché','un deal au marché','business','none'),
(5426,'fr','Les deux délégations ont un accord.','Aucune délégation n''a d''accord.','deux délégations qui se rencontrent','une délégation à l''aéroport','business','none'),
(5427,'fr','L''enveloppe a un sceau rouge.','L''enveloppe a un sceau bleu.','un sceau de cire rouge','un phoque sur la plage','chill','none'),
(5428,'fr','Le camion apporte du fret.','Le train apporte du fret.','du fret sur un gros camion','du fret sur un bateau','chill','none'),
(5430,'fr','Elle est rapide sur son vélo de route.','Elle est rapide sur son skate.','une balade rapide dans des tunnels','une balade rapide en ville','chill','none'),
(5431,'fr','Elle vole en montgolfière.','Elle vole en avion.','une montgolfière au-dessus des rochers','un ballon de fête','chill','none'),
(5432,'fr','Il dupe le pauvre gars !','Il dupe le pauvre chien !','duper un client','duper un prof','dramatic','exclamation'),
(5433,'fr','Il allume les lumières.','Il éteint les lumières.','allumer une guirlande lumineuse','allumer la télé','chill','none'),
(5434,'fr','Elle gaspille l''électricité !','Elle gaspille du papier !','consommer beaucoup d''électricité','l''électricité des panneaux solaires','dramatic','exaggeration'),
(5435,'fr','OMG, leurs tenues sont exactement semblables.','OMG, leurs tenues sont différentes.','des tenues exactement semblables','semblables en uniforme scolaire','gossip','none'),
(5436,'fr','L''équipe tord la pâte.','L''équipe coupe la pâte.','tordre un boudin de pâte','tordre un fil de laine','business','none'),
(5437,'fr','Soirée dans la cour !','Soirée dans la cuisine !','une soirée dans la cour illuminée','une cour d''école à la récré','slang','exclamation'),
(5438,'fr','Un bol de garniture rouge.','Un bol de garniture verte.','une garniture aux fruits rouges','un plombage chez le dentiste','chill','none'),
(5439,'fr','Quatre hommes, un parapluie gris !','Quatre hommes, un parapluie rouge !','une ville grise et pluvieuse','un manteau d''hiver gris','dramatic','exclamation'),
(5440,'fr','Journée cerf-volant avec son neveu.','Journée cerf-volant avec son chien.','cerfs-volants avec son neveu','à la pêche avec son neveu','chill','none'),
(5442,'fr','Il se bat contre chaque manche !','Il se bat contre chaque fermeture éclair !','sortir les bras des manches','retrousser ses manches','dramatic','exaggeration'),
(5443,'fr','La solidarité remplit la rue.','La solidarité remplit le stade.','une chaîne de solidarité','une chaîne de magasins','dramatic','none'),
(5444,'fr','Ils coopèrent sur une carte.','Ils coopèrent sur une voiture.','coopérer sur un puzzle','coopérer avec la police','chill','none'),
(5445,'fr','Son parapluie est inutile maintenant.','Sa mallette est inutile maintenant.','un parapluie inutile','un parapluie inutile au soleil','dramatic','none'),
(5446,'fr','Les collines sont brumeuses.','Les collines sont ensoleillées.','des collines brumeuses sur un lac','des yeux embués à un mariage','chill','none'),
(5447,'fr','Cette route est très isolée.','Cette route est très fréquentée.','une route isolée dans le désert','une télécommande','chill','none'),
(5448,'fr','Des panneaux publicitaires sur chaque mur !','Des tableaux sur chaque mur !','d''énormes panneaux publicitaires','un panneau publicitaire dans un champ','dramatic','exaggeration'),
(5450,'fr','Pour économiser, elle débranche les appareils.','Pour économiser, elle branche les appareils.','débrancher chaque appareil','recharger chaque appareil','business','none'),
(5451,'fr','Une injection, et le voilà Hulk !','Une pilule, et le voilà Hulk !','une injection dans le bras','une injection dans la jambe','slang','exaggeration'),
(5452,'fr','Un lac paisible dans la brume.','Une plage paisible dans la brume.','un lac de montagne paisible','un village de montagne paisible','chill','none'),
(5453,'fr','Elle remplit un vase bleu.','Elle remplit un vase rouge.','mettre des fleurs dans un vase','casser un vase à fleurs','chill','none'),
(5454,'fr','De l''encre gicle partout sur le passeport.','De l''eau gicle partout sur le passeport.','des gouttes d''encre noire','de l''encre bleue sur les doigts','slang','exaggeration'),
(5455,'fr','Il a eu l''approbation !','Il n''a eu aucune approbation !','l''approbation d''un passeport','l''approbation de ses parents','dramatic','exclamation'),
(5456,'fr','Il a eu la permission.','Il n''a pas eu la permission.','la permission de voyager','la permission de se garer','chill','none'),
(5457,'fr','Les visiteurs ont apporté un gâteau.','Les visiteurs ont apporté un chien.','des visiteurs avec un gâteau','des visiteurs dans un musée','chill','none'),
(5459,'fr','De la lave sur chaque pente.','De la neige sur chaque pente.','des coulées de lave incandescente','une lampe à lave','dramatic','none'),
(5460,'fr','Les tasses tournantes donnent un malaise !','La grande roue donne un malaise !','un malaise après un manège','un malaise sur un bateau','dramatic','exclamation'),
(5461,'fr','Tout le monde glisse un bulletin de vote.','Tout le monde glisse une lettre.','glisser un bulletin de vote plié','lire un long bulletin de vote','chill','none'),
(5462,'fr','La démocratie dans une seule boîte en plastique.','La démocratie dans une seule boîte en bois.','la démocratie en action','la démocratie à la télé','ironic','understatement'),
(5463,'fr','Il écrit son journal intime en mer. Trop la vibe.','Il écrit son journal intime au lit. Trop la vibe.','tenir un journal intime de voyage','lire une revue scientifique','slang','none'),
(5464,'fr','Elle est mince.','Il est mince.','une femme mince en jean','une femme mince en short','chill','none'),
(5465,'fr','Taille mesurée. Ceinture ajustée.','Bras mesuré. Ceinture ajustée.','mesurer son tour de taille','un tablier noué à la taille','business','none'),
(5466,'fr','Le serveur a une tenue très formelle.','Le serveur a une tenue très décontractée.','un uniforme de serveur formel','une lettre de réclamation formelle','chill','none'),
(5467,'fr','Le garçon se réveille en sursaut !','Le chien se réveille en sursaut !','se réveiller dans un lit superposé','se réveiller sous une tente','dramatic','exclamation'),
(5468,'fr','Les panneaux brillent.','Les arbres brillent.','d''immenses panneaux lumineux','un panneau stop','chill','none'),
(5469,'fr','Ce marcheur a fait 10 000 pas !','Ce marcheur a fait 100 pas !','un marcheur et ses bâtons nordiques','un marcheur en montagne','gossip','exclamation'),
(5471,'fr','La bulle dit que c''est de niveau.','La bulle dit que c''est de travers.','un cadre bien de niveau','une route plane','nerd','none'),
(5472,'fr','Les billets tombent.','Les clés tombent.','des billets qui tombent d''un portefeuille','des billets dans un distributeur','chill','none'),
(5473,'fr','Un homme « riche » au portefeuille vide.','Un homme « riche » au portefeuille plein.','un homme pas si riche','la grande maison d''un homme riche','ironic','understatement'),
(5474,'fr','Il trie ses pièces.','Il trie ses cartes.','des pièces sorties d''un porte-monnaie','des pièces dans une fontaine','chill','none'),
(5475,'fr','Un char arrive derrière eux !','Un cheval arrive derrière eux !','un char dans la fumée','un réservoir plein d''eau','dramatic','exclamation'),
(5476,'fr','Elle marche sur des décombres.','Elle marche sur des fleurs.','marcher dans les décombres','balayer les décombres','chill','none'),
(5477,'fr','Meilleure bataille de fort en neige de tous les temps.','Meilleure bataille de fort en sable de tous les temps.','un fort en neige','un fort en pierre','slang','exaggeration'),
(5478,'fr','Ses trucs l''attaquent !','Ses livres l''attaquent !','des trucs qui tombent','des trucs sous le lit','dramatic','exaggeration'),
(5479,'fr','Une robe longue et une « minuscule » garde-robe.','Une robe longue et une « minuscule » cuisine.','une robe longue en satin','un peignoir de spa d''hôtel','ironic','understatement'),
(5480,'fr','Sa tâche : une tour d''assiettes.','Sa tâche : une tour de chaussures.','une tâche difficile en cuisine','une tâche sur l''ordinateur','low_iq','none'),
(5481,'fr','Cheveux roses, chemise blanche. Ouf.','Cheveux roses, chemise rose. Ouf.','de longs cheveux rose vif','une machine à laver rose','gossip','guessing'),
(5482,'fr','Le chien prend un bain. Journée spa !','Le chat prend un bain. Journée spa !','un chien dans un bain','un chien dans une piscine','slang','cliche'),
(5483,'fr','Elle scrute la plage. Pour qui ?','Elle scrute la forêt. Pour qui ?','scruter le rivage','scanner un code-barres','gossip','guessing'),
(5484,'fr','Ils contemplent le feu d''artifice.','Ils contemplent la mer.','contempler le ciel','contempler l''écran','chill','none'),
(5485,'fr','Elle utilise un arrosoir.','Elle utilise un tuyau d''arrosage.','un arrosoir vert','un arrosoir vide','chill','none'),
(5487,'fr','Le surf dans le tube de la vague, trop cool !','La plongée dans le tube de la vague, trop cool !','du surf sur une vague géante','surfer sur Internet','slang','exclamation'),
(5488,'fr','Cet adieu dure une éternité.','Cet accueil dure une éternité.','un adieu au port','un adieu à l''aéroport','dramatic','exaggeration'),
(5489,'fr','Elle porte chaque manteau à merveille.','Elle porte chaque costume à merveille.','porter un chapeau à plumes','porter un chapeau de paille','flirt','none'),
(5490,'fr','Il a arraché une mauvaise herbe géante !','Il a arraché une carotte géante !','arracher une mauvaise herbe','une mauvaise herbe dans le trottoir','dramatic','exaggeration'),
(5491,'fr','Il est vraiment le bienvenu ici !','Il est vraiment seul ici !','un invité bienvenu','une pause bienvenue au boulot','dramatic','exclamation'),
(5492,'fr','La roue a de fins rayons.','La roue n''a pas de rayons.','de fins rayons en métal','de fins rayons en bois','chill','none'),
(5493,'fr','Il adore chaque moyeu qu''il voit.','Il adore chaque voiture qu''il voit.','le moyeu d''une roue','la plaque tournante d''une ville','gossip','guessing'),
(5494,'fr','Un homme handicapé roule vite.','Un homme handicapé roule lentement.','un homme handicapé en fauteuil','un homme handicapé avec des béquilles','chill','none'),
(5495,'fr','Une rumeur à la bibliothèque !','Une rumeur dans la cuisine !','faire passer une rumeur','lancer une rumeur en ligne','dramatic','exclamation'),
(5496,'fr','Elle ajuste sa cravate.','Elle ajuste son chapeau.','ajuster un nœud de cravate','ajuster une montre','flirt','none'),
(5497,'fr','Le candidat a gagné !','Le candidat a perdu !','un candidat vainqueur','un candidat perdant','dramatic','exclamation'),
(5498,'fr','À chaque fenêtre, une nouvelle vue !','À chaque porte, une nouvelle vue !','se pencher par une fenêtre','nettoyer une fenêtre','slang','exaggeration'),
(5499,'fr','Une femme en rouge tourne sur elle-même.','Une femme en rouge fait son jogging.','une femme qui arrose ses fleurs','une femme qui achète des fleurs','chill','none'),
(5500,'fr','Du bois d''œuvre frais repose en tas.','Du bois d''œuvre frais repose dans un camion.','un tas de bois d''œuvre frais','un camion de bois d''œuvre frais','chill','none'),
(5501,'fr','Il travaille dans l''industrie lourde.','Il travaille chez un fleuriste.','une usine d''industrie lourde','l''industrie du tourisme','business','none'),
(5502,'fr','Les cartons partent au stockage.','Les cartons partent à la poubelle.','des cartons pour le stockage','le stockage d''un téléphone','business','none'),
(5503,'fr','Elle est en position de planche.','Elle est en position du lotus.','une position de planche haute','un poste dans l''entreprise','chill','none'),
(5504,'fr','Elle envoie une lettre.','Elle envoie un colis.','envoyer une lettre manuscrite','envoyer un SMS','chill','none'),
(5505,'fr','Elle étudie un film radiographique.','Elle étudie une carte papier.','un film radiographique','un film au cinéma','nerd','none'),
(5506,'fr','Littéralement tout le monde est venu à cette soirée dansante.','Littéralement personne n''est venu à cette soirée dansante.','une soirée dansante dans la rue','un cours de danse à l''école','slang','exaggeration'),
(5507,'fr','Il s''amuse au zoo.','Il s''amuse à la plage.','une journée au zoo','une journée à la ferme','chill','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
