begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(74,'en','A bat is flying over the lake.','A bat is flying over the city.','a bat flying at sunset','a bat hitting a ball','chill','none'),
(79,'en','The bear is chasing a fish!','The bear is chasing a duck!','a bear in a river','a bear in a zoo','dramatic','exclamation'),
(82,'en','The bee is going back to work.','The ant is going back to work.','a bee on a flower','a bee in a jar','business','guessing'),
(87,'en','The bird is giving a concert!','The cat is giving a concert!','a bird singing loudly','a bird in a cage','dramatic','exaggeration'),
(88,'en','The dog wants a selfie.','The cat wants a selfie.','a dog near the camera','a dog near the door','chill','guessing'),
(89,'en','The black cat is jumping off.','The tabby cat is jumping off.','a cat on a tower','a cat under a tower','chill','none'),
(90,'en','Wait, puppies can dance?!','Wait, puppies can fly?!','a puppy in the bath','a puppy in the snow','low_iq','exclamation'),
(133,'en','The camel is taking a break.','The camel is taking a bath.','a camel in the desert','a camel in the snow','business','none'),
(146,'en','This caterpillar has a five-year plan.','This snail has a five-year plan.','a caterpillar on a leaf','a caterpillar in a jar','business','exaggeration'),
(159,'en','The chicken laid an egg!','The chicken ate an egg!','a chicken in a coop','a chicken on a plate','dramatic','exclamation'),
(197,'en','The cow is being milked.','The goat is being milked.','a cow with a bell','a cow with a hat','chill','none'),
(201,'en','Nice teeth, crocodile!','Nice teeth, lion!','a crocodile with open jaws','a crocodile with closed eyes','slang','exclamation'),
(209,'en','Curious cat, no privacy.','Curious dog, no privacy.','a curious cat peeking in','a curious dog peeking in','slang','exaggeration'),
(219,'en','The deer is shouting at us!','The deer is running at us!','a deer in the fog','a deer in the snow','dramatic','exclamation'),
(236,'en','The dolphin is racing a boat.','The dolphin is racing a shark.','a dolphin beside a boat','a dolphin in a pool','chill','none'),
(237,'en','The donkey is rolling in the dust like it''s a spa.','The donkey is rolling in the mud like it''s a spa.','a donkey rolling in dust','a donkey carrying a bag','slang','exaggeration'),
(250,'en','The duck is doing a headstand!','The swan is doing a headstand!','a duck on a pond','a duck in the rain','low_iq','exclamation'),
(262,'en','Free shower for the elephant.','Free shower for the giraffe.','an elephant at a waterhole','an elephant in a circus','slang','cheap_quality'),
(280,'en','The kitten wants the camera.','The puppy wants the camera.','a kitten on a bed','a kitten in a basket','chill','guessing'),
(305,'en','The fly is back again!','The bee is back again!','a fly on the jam','a fly in the soup','dramatic','exclamation'),
(314,'en','The fox is diving into the grass like a swimmer!','The fox is diving into the water like a swimmer!','a fox in frosty grass','a fox in a henhouse','dramatic','exaggeration'),
(319,'en','The frog is singing a song!','The fish is singing a song!','a croaking green frog','a frog in a bucket','low_iq','exclamation'),
(332,'en','The giraffe is having lunch.','The lion is having lunch.','a giraffe eating leaves','a giraffe eating grass','business','none'),
(341,'en','The goat is eating laundry!','The goat is eating flowers!','a goat on a roof','a goat in a car','dramatic','exclamation'),
(359,'en','Full cheeks, happy hamster.','Empty cheeks, happy hamster.','a hamster in a wheel','a hamster in a ball','slang','none'),
(392,'en','She is riding the horse.','She is riding the camel.','a horse and its rider','a horse and its cart','chill','none'),
(415,'en','This kangaroo has a passenger.','This koala has a passenger.','a kangaroo with a joey','a kangaroo with boxing gloves','chill','exaggeration'),
(427,'en','The ladybug is flying away.','The ladybug is eating a leaf.','a ladybug on the grass','a ladybug on a hand','chill','none'),
(446,'en','The lion is roaring at us!','The lion is running at us!','a lion in the grass','a lion in a cage','dramatic','exclamation'),
(450,'en','The lizard is sunbathing.','The lizard is swimming.','a lizard on a wall','a lizard in a box','chill','none'),
(483,'en','The monkey stole a banana!','The monkey stole a hat!','a monkey eating a banana','a monkey selling a banana','dramatic','exclamation'),
(487,'en','The mouse found the cheese.','The mouse found the bread.','a mouse in a barn','a mouse and a keyboard','chill','none'),
(518,'en','The owl is watching you.','The crow is watching you.','an owl on a branch','an owl in a cage','dramatic','exaggeration'),
(530,'en','The parrot is saying hello.','The parrot is saying goodbye.','a parrot on a railing','a parrot in a cage','chill','none'),
(542,'en','Belly slide! Go, penguin!','Belly slide! Go, seal!','a penguin on the ice','a penguin in a zoo','slang','exclamation'),
(550,'en','The pig is rolling in the mud.','The pig is rolling in snow.','a pig in a farmyard','a pig in a bathtub','chill','none'),
(551,'en','The pigeon is inspecting the cafe.','The pigeon is inspecting the bank.','a pigeon on a square','a pigeon in a park','business','exaggeration'),
(595,'en','The rabbit is sitting up.','The rabbit is lying down.','a rabbit in the dunes','a rabbit in a hat','chill','none'),
(600,'en','The rat is stealing pizza!','The rat is stealing bread!','a rat with pizza','a rat in a cage','dramatic','exclamation'),
(661,'en','The shark is smiling at you.','The dolphin is smiling at you.','a shark near the camera','a shark near a boat','dramatic','guessing'),
(665,'en','Is the sheep angry at me?','Is the goat angry at me?','a sheep on a hillside','a sheep in a barn','low_iq','exaggeration'),
(700,'en','The snail is in no hurry.','The frog is in no hurry.','a snail on a leaf','a snail on a plate','chill','understatement'),
(701,'en','The snake is on a black rock.','The snake is on a white rock.','a snake in the sand','a snake in the grass','chill','none'),
(729,'en','The squirrel is planning for winter.','The rabbit is planning for winter.','a squirrel with an acorn','a squirrel with a pizza','business','guessing'),
(758,'en','The swan is cleaning itself.','The swan is eating a fish.','a swan on a lake','a swan on the grass','chill','none'),
(780,'en','The cats are standing like soldiers!','The dogs are standing like soldiers!','cats standing on a bed','cats standing on a table','dramatic','exaggeration'),
(783,'en','Wet tiger, bad mood!','Wet lion, bad mood!','a tiger in a river','a tiger in a tree','slang','guessing'),
(813,'en','The turkey is posing like a star.','The goose is posing like a star.','a turkey on the hay','a turkey on a plate','chill','exaggeration'),
(815,'en','The turtle is in the sea now.','The turtle is in a pool now.','a turtle on the beach','a turtle in a tank','chill','none'),
(827,'en','There are many animals here.','There are two animals here.','animals in a storybook','animals in a real zoo','chill','none'),
(879,'en','The wolf is howling!','The wolf is sleeping!','a wolf in the snow','a wolf on a beach','dramatic','exclamation'),
(880,'en','The lamb is wearing its own wool!','The lamb is wearing a wool hat!','a ball of wool','a wool blanket','dramatic','exaggeration'),
(1344,'en','The spider is at work.','The ant is at work.','a spider in its web','a spider in the bath','business','none'),
(1479,'en','Lunch service at the zoo.','Lunch service at the farm.','a giraffe at the zoo','a lion at the zoo','business','none'),
(1491,'en','So many butterflies!','So many birds!','butterflies above the flowers','butterflies on a shirt','dramatic','exaggeration'),
(1534,'en','Wow, one horn on each horse!','Wow, two horns on each horse!','a unicorn''s long horn','a car''s loud horn','low_iq','exclamation'),
(1653,'en','The cat wants the goldfish...','The cat wants the bird...','a goldfish in a bowl','a goldfish in a pond','dramatic','guessing'),
(1729,'en','She has two pets.','She has three pets.','a girl with her pets','a girl buying a pet','chill','none'),
(1762,'en','A man is falling into a whale!','A man is falling into a boat!','the mouth of a whale','a whale in an aquarium','dramatic','exclamation'),
(1855,'en','The peacock has a huge tail!','The peacock has a short tail!','a peacock showing its tail','a peacock hiding its tail','dramatic','exaggeration'),
(1872,'en','The black cat loves books.','The white cat loves books.','a black cat on books','a black cat outside','chill','guessing'),
(1883,'en','The hens are eating outside.','The hens are eating inside.','hens in a farmyard','hens in a kitchen','chill','none'),
(1894,'en','Sleep well, little hedgehogs.','Sleep well, little rabbits.','a hedgehog family in bed','a hedgehog in a garden','chill','none'),
(1941,'en','This pirate mouse looks like Jack Sparrow.','This pirate cat looks like Jack Sparrow.','a pirate mouse','a pirate ship','slang','exaggeration'),
(1967,'en','The baby fox is so cute!','The baby bear is so cute!','a cute baby fox','a cute baby bird','dramatic','exclamation'),
(1994,'en','A cat is on top of the books.','A cat is on top of the hedge.','on top of the books','on top of the car','chill','none'),
(2001,'en','The owl has a gold beak. Rich owl!','The owl has a red beak. Rich owl!','an owl''s golden beak','an owl''s broken beak','low_iq','exaggeration'),
(2002,'en','The cat has long whiskers.','The cat has short whiskers.','a cat with long whiskers','a man with long whiskers','chill','none'),
(2005,'en','The crow is waiting for news.','The owl is waiting for news.','a crow on a branch','a crow on a scarecrow','dramatic','guessing'),
(2048,'en','This wolf is wild!','This dog is wild!','a wild wolf','a wild party','dramatic','exclamation'),
(2058,'en','A bear is reaching for a star.','A bear is reaching for a bird.','reaching for a star','reaching for the honey','chill','none'),
(2069,'en','The reindeer had a bad flight.','The reindeer had a fun flight.','reindeer stuck on a turbine','reindeer pulling a sleigh','chill','understatement'),
(2092,'en','What a fluffy owl!','What a fluffy cat!','a fluffy blue owl','a fluffy blue blanket','dramatic','exclamation'),
(2204,'en','He is holding a lamb.','He is holding a dog.','a lamb in his arms','a lamb in a field','chill','none'),
(2212,'en','Nice stripes, tiger!','Nice spots, tiger!','a tiger with black stripes','a zebra with black stripes','slang','exclamation'),
(2364,'en','A white bull is behind him.','A white horse is behind him.','a bull with curved horns','a bull in a ring','chill','none'),
(2381,'en','Those claws are really sharp!','Those teeth are really sharp!','claws on a branch','claws on a cat','dramatic','exclamation'),
(2499,'en','Two teddy bears are cuddling.','Two teddy bears are fighting.','teddy bears in the snow','teddy bears on a bed','chill','none'),
(2525,'en','Mum is lifting her baby bear.','Mum is lifting her baby fox.','to lift the cub up','to lift a heavy box','chill','none'),
(2648,'en','This ant is bigger than me!','This bee is bigger than me!','a huge black ant','a huge ant hill','low_iq','exaggeration'),
(2682,'en','The tiger is attacking!','The lion is attacking!','a tiger attacking','a tiger under attack','dramatic','exclamation'),
(3191,'en','The cat did not ask for this hug.','The dog did not ask for this hug.','to hug a big cat','to hug a big dog','chill','guessing'),
(3283,'en','The seagull is a tourist now.','The pigeon is a tourist now.','a seagull on a pier','a seagull on a boat','chill','exaggeration'),
(3323,'en','The baby hippo is very busy.','The baby lion is very busy.','a baby hippo resting','a baby hippo swimming','chill','understatement'),
(3369,'en','It is smelling a blue flower.','It is smelling a red flower.','to smell a flower','to smell the soup','chill','none'),
(3485,'en','She is touching the elephant.','She is touching the tiger.','to touch an elephant','to touch a tree trunk','chill','none'),
(3585,'en','One zebra is having lunch.','One zebra is having a bath.','zebras on a hill','zebras in a river','business','none'),
(3619,'en','An eagle is above the river.','An eagle is above the city.','an eagle over the river','an eagle over the mountains','chill','none'),
(3663,'en','The llama is checking you out.','The goat is checking you out.','a llama on a ridge','a llama in a barn','slang','guessing'),
(3777,'en','Its wings are on fire!','Its wings are in the water!','wings spread wide','wings folded tight','dramatic','exclamation'),
(4009,'en','The ducks are walking in a line like a school trip.','The hens are walking in a line like a school trip.','ducks in a long line','ducks in a small pond','chill','exaggeration'),
(4020,'en','The dog is watching a frog.','The dog is watching a fish.','to watch the frog','to watch the TV','chill','none'),
(4024,'en','The whole farm is following him!','The whole farm is following her!','animals following a man','animals following a dog','dramatic','exaggeration'),
(4055,'en','Dinosaurs? The husky says no!','Dinosaurs? The cat says no!','a dog and two dinosaurs','a dog and two cats','slang','exclamation'),
(4065,'en','The driver is a dog. Please fasten your seatbelts.','The driver is a cat. Please fasten your seatbelts.','a dog as the driver','a dog as the passenger','business','cliche'),
(4077,'en','One pigeon is still asleep.','Both pigeons are still asleep.','asleep in a nest','asleep on a bench','chill','none'),
(4089,'en','The octopuses are dancing!','The crabs are dancing!','octopuses dancing at a club','octopuses hiding in the sand','dramatic','exclamation'),
(4094,'en','The feed bags are colourful.','The feed bags are all white.','sacks of animal feed','sacks of potatoes','chill','none'),
(4096,'en','The turtle is free and does not even say thanks.','The shark is free and does not even say thanks.','a turtle set free','a turtle for free','chill','guessing'),
(4107,'en','They covered an elephant and got a tiger!','They covered an elephant and got a lion!','to cover the elephant','to cover the tiger','dramatic','exclamation'),
(4111,'en','The ram is his annoying coworker.','The dog is his annoying coworker.','an annoying ram','an annoying fly','business','exaggeration'),
(4127,'en','The lemur''s fur is so soft.','The lemur''s fur is so black.','soft white fur','soft white bread','chill','none'),
(4138,'en','He is petting the old dog.','He is petting the old cat.','to pet an old dog','to walk an old dog','chill','none'),
(4144,'en','The ferrets love the tube.','The cats love the tube.','ferrets in a tube','a tube of toothpaste','chill','guessing'),
(4168,'en','The slow tortoise never stops.','The slow hare never stops.','a slow tortoise','a slow snail','chill','none'),
(4170,'en','The hen saved her chick!','The hen saved her egg!','to save a chick','to save some money','dramatic','exclamation'),
(4172,'en','The hen made an escape worthy of an action movie.','The duck made an escape worthy of an action movie.','an escape from the fire','an escape from prison','dramatic','exaggeration'),
(4177,'en','The chicks have open mouths.','The chicks have closed mouths.','chicks with open mouths','chicks with open wings','chill','none'),
(4184,'en','The puppy brings the ball back. Who needs humans?','The puppy brings the shoe back. Who needs humans?','to bring the ball back','to bring the ball home','slang','exaggeration'),
(4186,'en','The dog is returning the ball.','The dog is returning the shoe.','to return to the machine','to return to the car','chill','none'),
(4187,'en','The parrots are playing dead!','The parrots are playing ball!','parrots playing dead','parrots playing cards','dramatic','exclamation'),
(4189,'en','Empty bowl, one pill left.','Empty bowl, two pills left.','an empty dog bowl','an empty fridge','chill','none'),
(4190,'en','The cat is meeting a lion. No big deal.','The dog is meeting a lion. No big deal.','to meet a lion','to meet a tiger','slang','understatement'),
(4205,'en','It is carrying a daisy.','It is carrying a rose.','to carry a flower','to carry a seed','chill','none'),
(4225,'en','Lunch is a sponge in a dish!','Lunch is a carrot in a dish!','a small white dish','a dish of cheese','low_iq','exclamation'),
(4230,'en','A dog is in the driver''s seat.','A cat is in the driver''s seat.','the driver''s seat','the back seat','chill','none'),
(4232,'en','The dolphin did a Ronaldo kick in the show!','The seal did a Ronaldo kick in the show!','a dolphin show','a dolphin on TV','dramatic','exaggeration'),
(4246,'en','The peacock is all blue.','The peacock is all green.','a peacock in blue','a parrot in blue','chill','none'),
(4249,'en','I am on a dragon''s back!','I am on a horse''s back!','the back of a dragon','the back of a horse','dramatic','exclamation'),
(4257,'en','The turtle is in a tight hug.','The fish is in a tight hug.','a tight panda hug','a tight hug under water','chill','none'),
(4261,'en','It is a sunny day at the pool.','It is a rainy day at the pool.','a sunny garden pool','a sunny beach','chill','none'),
(4266,'en','What an energetic dog!','What an energetic cat!','an energetic dog running','an energetic dog swimming','dramatic','exclamation'),
(4281,'en','The colour change is amazing.','The size change is amazing.','a change of colour','a change of clothes','chill','none'),
(4350,'en','Each cow has a big bell.','Each cow has a big horn.','a bell on a cow','a bell on a church','chill','none'),
(4376,'en','The smallest dog is making the biggest noise!','The smallest cat is making the biggest noise!','a lot of noise','a lot of music','dramatic','exaggeration'),
(4501,'en','This insect had a snack.','This bird had a snack.','an insect on a leaf','an insect on a flower','chill','understatement'),
(4747,'en','The seagulls want his bread!','The seagulls want his hat!','seagulls around a ferry','seagulls on a beach','dramatic','guessing'),
(4961,'en','The pet is hunting a toy.','The pet is hunting a ball.','a pet cat hunting','a pet cat sleeping','chill','none'),
(5319,'en','The spider is below its web.','The spider is above its web.','a web between branches','a web in a corner','chill','none'),
(5359,'en','The hippo is hiding from her.','The duck is hiding from her.','a hippo in the river','a hippo on the jetty','chill','guessing'),
(5507,'en','He is having fun at the zoo.','He is having fun at the beach.','a day at the zoo','a day at the farm','chill','none'),
(318,'en','Friendship is half an ice cream.','Friendship is half a chocolate bar.','friendship and ice cream','friendship and pizza','chill','cliche'),
(654,'en','She is whispering a secret.','She is shouting a secret.','to whisper a secret','to write a secret','chill','none'),
(872,'en','Her whistling works at last!','Her singing works at last!','whistling at a garden table','whistling at a football game','dramatic','exclamation'),
(2820,'en','They are sharing a book.','They are sharing a pizza.','to share a book','to share a desk','chill','none'),
(3019,'en','The girl is smiling at us.','The boy is smiling at us.','to smile at the camera','to smile at a dog','chill','none'),
(4023,'en','They are having fun on a boat.','They are having fun on a bus.','fun on the river','fun on the beach','chill','none'),
(4050,'en','The friends have a dog.','The friends have a cat.','friends by a fire','friends in a bar','chill','none'),
(4057,'en','The cola is all over her!','The water is all over her!','a bottle of cola','a glass of cola','dramatic','exclamation'),
(4594,'en','They are crying together!','They are dancing together!','crying together','singing together','dramatic','exaggeration'),
(4760,'en','They are sharing an ice cream.','They are sharing a pizza.','to share an ice cream','to share a tram ticket','chill','none'),
(156,'en','His medal is on his chest.','His medal is on his head.','hands on his chest','hands on his head','chill','none'),
(437,'en','She is stretching her leg.','She is stretching her arm.','a leg on the wall','a leg in a cast','chill','none'),
(913,'en','Her arm is up high.','Her arm is down low.','an arm stretched up','an arm in a sling','chill','none'),
(956,'en','She is studying a brain model.','She is studying a heart model.','a model of a brain','a picture of a brain','chill','none'),
(1069,'en','This eye is green-brown.','This eye is bright blue.','an open eye','a closed eye','chill','none'),
(1070,'en','She has a laughing face.','She has a crying face.','a laughing face','a sleeping face','chill','none'),
(4169,'en','He is giving the bear a look!','He is giving the bear a fish!','a look at the bear','a look at the map','dramatic','exclamation')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
