begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(1076,'en','A finger is touching a drop.','A finger is touching a bee.','a finger touching a drop','a finger near a bee','chill','none'),
(1088,'en','A bare foot is in the grass.','A bare foot is in the snow.','a bare foot in grass','a foot in a sock','chill','none'),
(1129,'en','The doctor is holding a heart!','The doctor is holding a brain!','a model of a heart','a model of a brain','dramatic','exclamation'),
(1161,'en','He is putting ice on his knee.','He is putting ice on his head.','ice on a bent knee','down on one knee','business','none'),
(1214,'en','She is stretching her neck.','She is stretching her leg.','a long stretched neck','a scarf around the neck','chill','none'),
(1314,'en','Her shoulder needs a check.','Her knee needs a check.','examining a shoulder','a bag on her shoulder','business','none'),
(1400,'en','Her throat is getting a check.','Her ear is getting a check.','a light in the throat','clearing her throat','business','none'),
(1403,'en','These toes love the beach!','These toes love the snow!','toes in wet sand','toes in soft grass','dramatic','exaggeration'),
(1404,'en','Her tongue is catching snow for lunch.','Her hand is catching snow for lunch.','sticking out her tongue','biting her tongue','low_iq','guessing'),
(1454,'en','She is measuring her waist.','She is measuring her arm.','a tape around the waist','a belt around the waist','business','none'),
(1656,'en','Her lips are red.','Her lips are blue.','shiny red lips','lips on a glass','chill','none'),
(1926,'en','The skull has all its teeth!','The skull has no teeth!','a skull''s grinning teeth','a dog''s sharp teeth','dramatic','exclamation'),
(1961,'en','These bones love a good book.','These bones love a good film.','bones over an open book','a dog with a bone','gossip','guessing'),
(2097,'en','Those ears are bigger than its head!','Those eyes are bigger than its head!','enormous round ears','ears under a hat','dramatic','exclamation'),
(2257,'en','Her eyebrows are very dark.','Her eyebrows are very light.','thick dark eyebrows','thin blond eyebrows','chill','none'),
(3070,'en','A tree is above the hands.','A cat is above the hands.','two open cupped hands','two hands in pockets','chill','none'),
(3192,'en','Only her eyes are visible.','Only her mouth is visible.','only the eyes showing','eyes closed in sleep','business','none'),
(3671,'en','Its arms are spread wide.','Its arms are crossed.','to spread your arms wide','to cross your arms','chill','none'),
(4596,'en','She is blowing her nose.','She is blowing a bubble.','blowing her nose','holding her nose','chill','none'),
(4710,'en','They are swinging their arms.','They are swinging their legs.','arms up over the head','arms crossed over the chest','business','none'),
(4718,'en','Her brown eye fills the frame.','Her blue eye fills the frame.','a torch in an eye','an eye behind glasses','chill','none'),
(4719,'en','The chin is round.','The chin is pointed.','a rounded chin','a hand on the chin','business','none'),
(4816,'en','Her heart is racing!','Her heart is resting!','a hand over the heart','a heart on her shirt','dramatic','exclamation'),
(4977,'en','A hand is leading the way.','A dog is leading the way.','an outstretched open hand','a hand full of rice','chill','none'),
(4982,'en','He is holding his ankle.','He is holding his head.','a hurt ankle','a bracelet on the ankle','chill','none'),
(5016,'en','He is bending his knees.','He is bending his arms.','bare knees in a squat','down on one knee','business','none'),
(5103,'en','A giraffe''s neck is over her!','A horse''s neck is over her!','a giraffe''s long neck','a snake around her neck','dramatic','exclamation'),
(5346,'en','He is patting his stomach.','He is patting his head.','a full stomach','a stomach full of soup','chill','none'),
(5406,'en','Her toes are next to a shell.','Her toes are next to a crab.','toes spread in the sand','toes in a flip-flop','chill','none'),
(5409,'en','She is showing her teeth.','She is showing her tongue.','front teeth up close','a missing front tooth','chill','none'),
(252,'en','He blew a huge cloud of dust!','He blew a huge cloud of smoke!','a cloud of dust','a cloud of smoke','dramatic','exclamation'),
(253,'en','Dusting is a team sport here.','Cooking is a team sport here.','dusting a lampshade','dusting a cake with sugar','ironic','exaggeration'),
(484,'en','She is mopping the floor.','She is sweeping the floor.','a mop in a bucket','a mop of curly hair','chill','none'),
(683,'en','The sink is a foam mountain!','The bath is a foam mountain!','a sink full of foam','a sink full of toys','low_iq','exaggeration'),
(802,'en','He is playing LeBron over a trash can.','He is playing LeBron over a bathtub.','a trash can hoop','a trash can lid','slang','guessing'),
(860,'en','The car needed a "little" washing.','The bike needed a "little" washing.','washing a muddy car','washing a muddy dog','ironic','understatement'),
(960,'en','She is sweeping with a broom.','She is sweeping with a rake.','a straw broom','a witch''s broom','chill','none'),
(1085,'en','She is mopping a wooden floor.','She is mopping a stone floor.','a wide wooden floor','the first floor','business','none'),
(1151,'en','His iron is steaming.','His kettle is steaming.','a steaming iron','an iron gate','business','none'),
(1152,'en','An ironing board is going up.','A beach chair is going up.','setting up an ironing board','sitting on an ironing board','chill','none'),
(1347,'en','A hand is squeezing a sponge.','A hand is squeezing a lemon.','a squeezed soapy sponge','a sponge cake','chill','none'),
(1544,'en','She is hanging up the laundry.','She is hanging up the flags.','hanging white laundry','folding white laundry','chill','none'),
(3087,'en','She is pouring pet food.','She is pouring orange juice.','to pour pet food','to pour hot tea','business','none'),
(3767,'en','These fans even clean up!','These players even clean up!','to clean up the seats','to clean up your room','gossip','exclamation'),
(4155,'en','The plates are "clean" now.','The cups are "clean" now.','a clean white plate','a clean white towel','ironic','understatement'),
(4196,'en','A candle is in the bucket.','A flower is in the bucket.','a candle in a bucket','a bucket of water','chill','none'),
(4220,'en','He is cleaning a white car.','He is cleaning a black car.','to clean the paint','to clean the house','business','none'),
(4253,'en','They are washing the mud man.','They are washing the mud dog.','washing off thick mud','washing up the dishes','low_iq','exaggeration'),
(4367,'en','Sheets are drying in the wind.','Sheets are drying on a boat.','sheets drying in the wind','dishes drying on a rack','chill','none'),
(4448,'en','She is gripping the handle.','She is gripping the ladder.','a long blue handle','a door handle','chill','none'),
(4539,'en','The cartoon man is mopping.','The cartoon man is cooking.','a cartoon of a cleaner','a cartoon of a cook','chill','none'),
(5087,'en','Paws made the floor dirty.','Paws made the wall dirty.','a dirty tiled floor','dirty dishes in a sink','gossip','blaming_someone'),
(5249,'en','He is washing a pan that has seen better days.','He is washing a cup that has seen better days.','washing a sooty pot','washing his face','ironic','cliche'),
(5324,'en','The sponge beat the sauce!','The sponge beat the cheese!','a soapy sponge','a sponge cake','dramatic','exclamation'),
(5372,'en','His broom is pushing leaves.','His broom is pushing snow.','a broom and dry leaves','a broom in the kitchen','chill','none'),
(5377,'en','She collected the plates.','She collected the apples.','collected dirty plates','collecting red apples','business','none'),
(5378,'en','She is setting the table.','She is setting the alarm.','to set the table','to set an alarm','business','none'),
(5421,'en','The garbage is everywhere!','The flowers are everywhere!','a bin full of garbage','a bin full of flowers','dramatic','exaggeration'),
(5480,'en','His task is a tower of plates.','His task is a tower of shoes.','a hard kitchen task','a task at the computer','low_iq','none'),
(382,'en','Wow, they work so high!','Wow, they work so low!','high above the street','high on a mountain','dramatic','exclamation'),
(465,'en','She is shopping at a market.','She is shopping at a mall.','a busy street market','a busy street party','chill','none'),
(669,'en','Three coins buy a lot in this shop.','Ten coins buy a lot in this shop.','a little grocery shop','a little flower shop','gossip','cheap_quality'),
(739,'en','He stopped for pizza. Rules are rules.','He stopped for sushi. Rules are rules.','to stop for pizza','to stop for petrol','ironic','cliche'),
(941,'en','Pigeons attacked her bench!','Ducks attacked her bench!','a woman on a bench','a bench at the station','dramatic','exaggeration'),
(959,'en','She is walking under a bridge.','She is walking over a bridge.','a huge suspension bridge','a small wooden bridge','chill','none'),
(1218,'en','No one is on the playground. Creepy!','Kids are on the playground. Creepy!','no one on the swings','no one on the beach','dramatic','exclamation'),
(1317,'en','He is on a stone sidewalk.','He is on a wooden sidewalk.','a wide stone sidewalk','a sidewalk full of people','business','none'),
(1323,'en','What a tall skyscraper!','What a tall lighthouse!','gazing up at a skyscraper','gazing down from a skyscraper','dramatic','exclamation'),
(1350,'en','She is crossing the square. Bye, pigeons!','She is crossing the river. Bye, pigeons!','running across a square','sitting in a quiet square','slang','none'),
(1367,'en','She is crossing a busy street.','She is crossing a busy bridge.','a busy big-city street','a quiet village street','business','none'),
(1369,'en','Rain? He is dancing with a streetlight!','Rain? He is dancing with a traffic light!','a row of lit streetlights','a row of lit candles','dramatic','exclamation'),
(1410,'en','She is at a traffic light.','She is at a bus stop.','waiting at a traffic light','waiting at a train station','chill','none'),
(1508,'en','The church has a tall tower.','The church has a tiny tower.','an old stone church','an old stone bridge','business','none'),
(1642,'en','The village sky is red.','The village sky is blue.','a village at sunset','a village under deep snow','business','none'),
(1652,'en','She will touch the butterfly!','She will touch the bird!','to touch a glowing butterfly','to catch a glowing butterfly','dramatic','guessing'),
(1677,'en','They are not looking at the city.','They are not looking at their phones.','a city at dusk','a city at noon','ironic','cliche'),
(1919,'en','The lane is very narrow.','The lane is very wide.','a narrow cobblestone lane','a narrow escape','chill','none'),
(1987,'en','This city is from the future.','This city is from the past.','a city of the future','a city of the past','business','none'),
(2040,'en','Decorations are on every roof.','Snowmen are on every roof.','decorations on the roofs','decorations in a box','chill','none'),
(2093,'en','The whole city is green.','The whole city is grey.','green towers full of trees','green paint on the towers','business','none'),
(2201,'en','Her orange armour is so cool!','Her pink armour is so cool!','orange hair and armour','an orange in her hand','flirt','exclamation'),
(2208,'en','Her hair is bright pink.','Her hair is bright green.','bright pink hair','a bright pink dress','business','none'),
(2228,'en','She is sitting above the city.','She is sitting above the sea.','high above the city','above the clouds','chill','none'),
(2379,'en','Red leaves are falling.','Red apples are falling.','leaves falling in the rain','snow falling on cars','chill','none'),
(2439,'en','The street is wet at night.','The street is dry at night.','a wet night street','a wet sandy beach','business','none'),
(3482,'en','She is chilling on the steps.','She is sleeping on the steps.','sunny stone steps','steps in a dance','slang','none'),
(3842,'en','He is throwing away a cup.','He is throwing away a bag.','to throw away a cup','to throw a ball away','business','none'),
(4030,'en','He took a swim in the park.','He took a nap in the park.','a pond in a park','a skate park','ironic','understatement'),
(4042,'en','They are outside a store.','They are inside a store.','outside a lit store','a store full of coconuts','chill','none'),
(4126,'en','Thousands of buildings are lit.','Thousands of buildings are dark.','lit buildings by a harbour','old buildings by a lake','dramatic','none'),
(4398,'en','Advertisements are everywhere!','Trees are everywhere!','huge lit advertisements','advertisements in a paper','dramatic','exaggeration'),
(4456,'en','The tower is very modern.','The tower is very old.','a modern glass tower','a modern glass phone','business','none'),
(4588,'en','The traffic is stopped.','The traffic is moving.','stopped traffic at night','heavy traffic in the day','business','none'),
(4670,'en','She is on the roof.','She is in the garden.','washing on a flat roof','a cat on a roof','chill','none'),
(4692,'en','He is shelving the products.','He is shelving the books.','products on a shelf','products in a truck','business','none'),
(4798,'en','She is walking to a temple.','She is walking to a church.','an old hilltop temple','an old hilltop castle','chill','none'),
(4802,'en','This guard is the museum boss.','This cook is the museum boss.','a museum guard','a guard at a bank','ironic','guessing'),
(4805,'en','He is pointing at a church.','He is pointing at a boat.','a domed church','a wooden church','chill','none'),
(4835,'en','A chase is on in the city!','A parade is on in the city!','a city street at night','a city street at noon','dramatic','exclamation'),
(4885,'en','They are going up the street.','They are going up the stairs.','a sunny cobbled street','a busy shopping street','business','none'),
(5037,'en','She is on a Paris sidewalk.','She is on a Paris bridge.','a wide paved sidewalk','a sidewalk cafe table','chill','none'),
(5085,'en','She is posing like the statue!','She is posing like the guard!','a selfie with a statue','a selfie with a horse','gossip','exclamation'),
(5108,'en','The village is on the water.','The village is on the hill.','a village on stilts','a village in the snow','business','none'),
(5195,'en','His books take up the whole bench.','His shoes take up the whole bench.','books on a park bench','a dog on a bench','gossip','exaggeration'),
(5340,'en','A box is going to the garage.','A box is going to the car.','an open garage','a garage full of cars','business','none'),
(5468,'en','The signs are glowing.','The trees are glowing.','huge glowing signs','a stop sign','chill','none'),
(24,'en','Her spoon emptied the whole bowl!','Her fork emptied the whole bowl!','a spoon full of soup','a spoon full of sugar','low_iq','exaggeration'),
(66,'en','They are baking bread.','They are baking a cake.','baking a golden loaf','baking cookies','chill','none'),
(97,'en','The water is boiling.','The milk is boiling.','water at a rolling boil','milk at a rolling boil','chill','none'),
(121,'en','He burned the pancake. Oops!','He burned the toast. Oops!','a burned black pancake','a burned black steak','dramatic','exclamation'),
(200,'en','He is holding cream over his head!','He is holding soup over his head!','stiff whipped cream','a cream for the face','low_iq','exaggeration'),
(260,'en','He is frying an egg.','He is boiling an egg.','a fried egg on toast','a boiled egg','chill','none'),
(328,'en','The garlic smells strong!','The onion smells strong!','peeling a garlic clove','peeling a garlic sausage','dramatic','exclamation'),
(329,'en','The gas flame is blue.','The gas flame is green.','a blue gas flame','gas in a car','business','none'),
(352,'en','The cheese has grill stripes.','The bread has grill stripes.','cheese on a hot grill','fish on a hot grill','chill','none'),
(424,'en','His knife is cutting bread.','His knife is cutting cheese.','a large bread knife','a small pocket knife','business','none'),
(491,'en','The mustard is sharp.','The honey is sharp.','a spoonful of mustard','a jar of mustard seeds','chill','none'),
(511,'en','He is cutting onions in swim goggles. Genius!','He is cutting onions in sunglasses. Genius!','chopping a white onion','frying a white onion','low_iq','exclamation'),
(514,'en','The oven is their new TV.','The fridge is their new TV.','bread rising in the oven','pizza in the oven','slang','exaggeration'),
(537,'en','She is peeling a red apple.','She is peeling a green apple.','to peel in one spiral','to peel a banana','chill','none'),
(543,'en','The pepper made him sneeze!','The onion made him sneeze!','grinding black pepper','grinding coffee beans','dramatic','blaming_someone'),
(557,'en','The chef is serving the plate.','The chef is washing the plate.','spaghetti on a white plate','a stack of empty plates','business','none'),
(571,'en','The pot water is dancing!','The pot water is freezing!','potatoes in a big pot','flowers in a big pot','low_iq','exaggeration'),
(606,'en','The recipe says: eggs first.','The recipe says: fish first.','a hand-drawn recipe card','a recipe for soup','business','none'),
(632,'en','They are salting the tomatoes.','They are salting the potatoes.','salt on tomato slices','salt on a snowy road','chill','none'),
(694,'en','He is slicing a tomato.','He is slicing a cucumber.','to slice a tomato thin','to slice a cake','chill','none'),
(734,'en','The dog wants that steak.','The cat wants that steak.','a steak with pink inside','a steak in the freezer','gossip','guessing'),
(735,'en','Steam fogged up his glasses!','Rain fogged up his glasses!','a cloud of steam','a cloud of smoke','dramatic','exclamation'),
(742,'en','All four stove burners are on.','Only one stove burner is on.','four burners on a stove','a small camping stove','business','none'),
(769,'en','The teaspoons are tiny.','The teaspoons are huge.','stirring with a teaspoon','a teaspoon of sugar','chill','none'),
(2734,'en','The cat has a tiny pink nose.','The cat has a tiny black nose.','a small pink nose','a small black nose','chill','none'),
(2951,'en','Two hands are almost touching!','Two feet are almost touching!','two hands almost touching','two hands shaking','dramatic','exclamation'),
(4202,'en','Very busy dogs, bellies up.','Very busy cats, bellies up.','bellies up in the sun','a belly full of food','ironic','understatement'),
(4915,'en','They are walking shoulder to shoulder.','They are sitting shoulder to shoulder.','arms over shoulders','a bag on the shoulder','chill','none'),
(110,'en','The cat is "helping" with the boxes.','The dog is "helping" with the boxes.','a big packed box','a box of chocolates','ironic','understatement'),
(4990,'en','He is using a heavy iron.','He is using a heavy hammer.','a heavy steam iron','an iron pan','chill','none'),
(585,'en','She is playing music in public.','She is playing chess in public.','playing music in public','a public swimming pool','chill','none'),
(1548,'en','People are in every window.','Cats are in every window.','a family in every window','a cat in every window','chill','none'),
(2023,'en','Gifts were left in the snow!','Skis were left in the snow!','gift boxes in the snow','gift boxes under a bed','dramatic','exclamation'),
(2449,'en','Just a "few" glowing shop windows.','Just a "few" dark shop windows.','glowing shop windows','a broken shop window','ironic','understatement'),
(2652,'en','Everything is grey except her coat!','Everything is red except her coat!','grey coats in the rain','grey coats in the snow','dramatic','exclamation'),
(4323,'en','Nice dance moves in the lane!','Nice bike tricks in the lane!','a narrow painted lane','a fast lane','flirt','exclamation'),
(4465,'en','He went upstairs, best day ever!','He went downstairs, best day ever!','upstairs on a bus','upstairs in a house','dramatic','exaggeration'),
(4676,'en','Carrying cheese is a tradition here.','Carrying fish is a tradition here.','an old cheese tradition','an old dance tradition','chill','none'),
(4874,'en','She stopped at a traffic light.','She stopped at a busy gas station.','stopped at a traffic light','a red traffic light','chill','none'),
(5045,'en','The speakers make a big sound!','The drums make a big sound!','sound from a boombox','sound from a car radio','low_iq','exclamation'),
(523,'en','Nice moves with that frying pan!','Nice moves with that pizza dough!','vegetables in a frying pan','pancakes in a frying pan','flirt','exclamation')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
