begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(948,'en','Berries in the blender? Yum!','Cherries in the blender? Yum!','filling a blender','cleaning a blender','slang','none'),
(1011,'en','This cook needs two spoons!','This cook needs two pots!','a cook tasting the food','a cook reading a recipe','dramatic','exclamation'),
(1160,'en','The kitchen is well equipped.','The kitchen is almost empty.','a bright kitchen','a dark kitchen','business','none'),
(3078,'en','She is frying eggs like a pro.','She is frying fish like a pro.','frying eggs in a pan','boiling eggs in a pot','slang','cliche'),
(3089,'en','She baked cookies. For me?','She baked a cake. For me?','baked chocolate cookies','baked bread rolls','flirt','guessing'),
(3709,'en','The chef is tasting the soup.','The chef is tasting the salad.','tasting the soup','tasting the wine','chill','none'),
(4021,'en','Cutting the cake? Me first!','Cutting the bread? Me first!','cutting the cake into squares','cutting the cake in half','slang','guessing'),
(4037,'en','Someone cooked an omelette.','Someone cooked a pancake.','cooking an omelette','cooking pasta','chill','none'),
(4228,'en','A helicopter to the shore, just for eggs!','A boat to the shore, just for eggs!','on the grassy shore','on the sandy shore','dramatic','exaggeration'),
(4238,'en','No oven? They roasted ribs on a stone.','No oven? They roasted fish on a stone.','roasted lamb ribs','roasted chicken','slang','none'),
(4283,'en','Her cooking gets applause!','Her singing gets applause!','a cooking class','a cooking contest','dramatic','exclamation'),
(4326,'en','The wood is burning.','The coal is burning.','burning wood','cutting wood','chill','none'),
(4365,'en','So much fresh bread!','So much fresh fish!','fresh bread from the oven','fresh fish from the sea','dramatic','exclamation'),
(4514,'en','The chef has crazy skills.','The waiter has crazy skills.','a chef''s cooking skill','a juggling skill','slang','exaggeration'),
(4569,'en','He is frying fish. Van life!','He is frying eggs. Van life!','frying fish in a van','frying fish on a boat','slang','cliche'),
(4570,'en','The chef is plating pork.','The chef is plating fish.','a chef plating a dish','a chef eating a dish','business','none'),
(4619,'en','Raw chicken, raw fish, no dinner yet.','Raw chicken, raw beef, no dinner yet.','a raw frozen chicken','a raw egg','chill','understatement'),
(4795,'en','She baked cookies. Best day!','She baked a pie. Best day!','baked chocolate cookies','baked apple pies','dramatic','exclamation'),
(4994,'en','She is using a wooden spoon.','She is using a metal spoon.','a long wooden spoon','a wooden chopping board','chill','none'),
(5017,'en','A rainbow of cut vegetables!','A rainbow of cut fruit!','cut vegetables in rows','cut flowers in a vase','dramatic','exclamation'),
(5168,'en','The batch of tarts is okay.','The batch of bread is okay.','a batch of custard tarts','a batch of cookies','chill','understatement'),
(5171,'en','He is adding stock to the pot.','He is adding milk to the pot.','adding vegetables to the pot','adding salt to the soup','chill','none'),
(139,'en','He found the capital!','He found the ocean!','the capital below the hill','a capital letter','dramatic','exclamation'),
(300,'en','She is raising the flag.','She is lowering the flag.','raising a flag','waving a flag','chill','none'),
(920,'en','Swinging in Austria? Goals.','Skiing in Austria? Goals.','swinging in Austria','skiing in Austria','slang','cliche'),
(921,'en','He is serving Austrian cake.','He is serving Austrian beer.','an Austrian coffee house','an Austrian beer hall','business','none'),
(1026,'en','Czech beer? Yes, please!','Czech wine? Yes, please!','a Czech beer hall','a Czech wine cellar','slang','exclamation'),
(1050,'en','Tulips on a bike? So Dutch!','Cheese on a bike? So Dutch!','tall Dutch houses','a Dutch cheese market','slang','cliche'),
(1115,'en','Dancing in Greece? Nice style.','Diving in Greece? Nice style.','dancing in Greece','swimming in Greece','flirt','none'),
(1195,'en','A flying Mexican tortilla!','A flying Mexican taco!','a Mexican street stall','a Mexican restaurant','dramatic','exclamation'),
(1216,'en','Bike, tulips, windmills. Yes, the Netherlands.','Car, tulips, windmills. Yes, the Netherlands.','tulips in the Netherlands','a market in the Netherlands','chill','cliche'),
(1255,'en','It is winter in Poland.','It is summer in Poland.','a snowy square in Poland','a sandy beach in Poland','chill','none'),
(1258,'en','She made Polish dumplings.','She made Polish sausages.','Polish dumplings in rows','Polish sausages on a grill','chill','none'),
(1260,'en','She is running in Portugal.','She is cycling in Portugal.','running in Portugal','riding a tram in Portugal','chill','none'),
(1262,'en','Cinnamon on Portuguese tarts!','Chocolate on Portuguese tarts!','Portuguese custard tarts','Portuguese sardines','dramatic','exclamation'),
(1327,'en','He wears Slovak folk clothes.','She wears Slovak folk clothes.','Slovak folk dress','a Slovak football shirt','chill','none'),
(1328,'en','She is dancing in Slovakia!','She is swimming in Slovakia!','a meadow in Slovakia','a beach in Slovakia','dramatic','exclamation'),
(1380,'en','Switzerland: even the cows get music.','Switzerland: even the goats get music.','an alphorn in Switzerland','a cowbell shop in Switzerland','chill','exaggeration'),
(1528,'en','Balloons over Japan!','Birds over Japan!','symbols of Japan','a map of Japan','dramatic','exclamation'),
(1537,'en','Egypt''s pharaoh has a bow.','Egypt''s pharaoh has a sword.','a pharaoh of Egypt','a pyramid in Egypt','chill','none'),
(1596,'en','The moon shines over Russia.','The sun shines over Russia.','a church in Russia','a palace in Russia','chill','none'),
(1612,'en','Kids from Korea are waving.','Kids from Korea are dancing.','kids from Korea waving','kids from Korea singing','chill','none'),
(1614,'en','Bulls are running in Spain!','Horses are running in Spain!','bulls running in Spain','horses racing in Spain','dramatic','exclamation'),
(1743,'en','Ice cream in Italy? Of course.','Pizza in Italy? Of course.','a leaning tower in Italy','a pizza oven in Italy','chill','cliche'),
(1935,'en','It is sunset in New York.','It is night in New York.','New York at sunset','New York at night','chill','none'),
(2146,'en','France has a purple tower.','France has a green tower.','a tower in France','a bridge in France','low_iq','guessing'),
(2153,'en','China has a flying dragon!','China has a sleeping dragon!','a dragon from China','a tiger from China','dramatic','exclamation'),
(2157,'en','A baby from India wears gold.','A baby from India wears red.','a painting from India','a carpet from India','chill','none'),
(2247,'en','Scotland has a lonely church.','Scotland has a lonely castle.','a church in Scotland','a castle in Scotland','chill','none'),
(2752,'en','The mouse plays for Germany!','The cat plays for Germany!','a fan of Germany','a map of Germany','low_iq','guessing'),
(4568,'en','She is jumping on every continent. Cheap travel!','He is jumping on every continent. Cheap travel!','jumping on a continent','drawing a continent','slang','cheap_quality'),
(4579,'en','She travels abroad a lot!','She stays at home a lot!','travelling abroad','studying abroad','dramatic','exclamation'),
(4756,'en','A baguette on a bike? That is France!','A pizza on a bike? That is France!','cycling in France','skiing in France','slang','cliche'),
(4779,'en','He is having fun in Germany!','She is having fun in Germany!','a trip around Germany','a job in Germany','dramatic','exclamation'),
(4970,'en','Fireworks for independence!','Candles for independence!','celebrating independence','fighting for independence','dramatic','none'),
(5098,'en','He loves his national team.','She loves her national team.','national colours on a face','a national holiday','chill','guessing'),
(130,'en','A heart on her calendar? Love!','A star on her calendar? Love!','a heart on the calendar','a calendar on the desk','slang','guessing'),
(243,'en','Winter dressing is hard work!','Summer dressing is hard work!','fast dressing for winter','dressing a salad','dramatic','exaggeration'),
(273,'en','Cheers to a nice evening!','Cheers to a nice morning!','a quiet evening above town','an evening at the cinema','slang','exclamation'),
(299,'en','The dog is waking her up.','The cat is waking her up.','waking up with a dog','waking up with an alarm','chill','none'),
(499,'en','Peek-a-boo with a newspaper!','Peek-a-boo with a menu!','hiding behind a newspaper','reading a newspaper online','slang','exclamation'),
(519,'en','The bag is packed for school.','The bag is packed for a trip.','packing a school bag','packing a suitcase','chill','none'),
(593,'en','Matching pyjamas? So cute!','Matching jackets? So cute!','matching checked pyjamas','matching striped pyjamas','flirt','exclamation'),
(653,'en','So much searching! The keys were in the door.','So much searching! The keys were in the car.','searching for lost keys','searching for a lost dog','dramatic','exclamation'),
(672,'en','Showering in ice water!','Showering in hot water!','showering at the beach','showering in a bathroom','dramatic','exaggeration'),
(692,'en','Sleeping? He is a pro.','Reading? He is a pro.','sleeping under a blanket','sleeping in a tent','slang','cliche'),
(708,'en','Muddy hands? Soap time!','Muddy feet? Soap time!','a bar of soap','a bottle of soap','slang','exclamation'),
(792,'en','Way too much toothpaste!','Way too much shampoo!','a tower of toothpaste','a tube of toothpaste','dramatic','exaggeration'),
(795,'en','The dog gets the towel too!','The cat gets the towel too!','drying off with a towel','lying on a beach towel','dramatic','exclamation'),
(861,'en','His watch says: late!','His phone says: late!','checking a watch','buying a watch','dramatic','exclamation'),
(933,'en','She is in the bathroom.','She is in the kitchen.','washing in the bathroom','cleaning the bathroom','chill','none'),
(1200,'en','She loves this sunny morning.','She loves this rainy morning.','a sunny morning','a rainy morning','chill','guessing'),
(1315,'en','Rain shower? More like a waterfall!','Garden shower? More like a waterfall!','a big rain shower','a shower curtain','dramatic','exaggeration'),
(1406,'en','Look at my toothbrush!','Look at my hairbrush!','a toothbrush with foam','a toothbrush in a cup','dramatic','exclamation'),
(1676,'en','Sitting with a coffee? Vibes.','Sitting with a book? Vibes.','sitting in an armchair','sitting at a desk','slang','cliche'),
(2510,'en','Bedtime for a boy and a cat!','Bedtime for a boy and a dog!','bedtime under a blanket','bedtime story with a book','dramatic','exclamation'),
(3164,'en','Time to brush your teeth!','Time to brush your hair!','to brush your teeth','to brush your hair','dramatic','exclamation'),
(3176,'en','She is sitting under a tree.','She is sitting in a tree.','sitting under a tree','sitting on a branch','chill','none'),
(4016,'en','The cat says no to the bath.','The dog says no to the bath.','a cat on the bath','a cat in the bath','low_iq','guessing'),
(4045,'en','He found his phone!','He found his wallet!','finding a lost phone','finding a lost dog','dramatic','exclamation'),
(4117,'en','Just a small search.','Just a small nap.','a search for a phone','a search for a dog','chill','understatement'),
(4197,'en','It is late! Run!','It is early! Run!','waking up late','staying up late','dramatic','exclamation'),
(4224,'en','A lizard is using the toilet.','A lizard is using the kitchen.','a lizard at the toilet','a lizard cleaning a toilet','chill','none'),
(4284,'en','He is leaving in a rush!','He is leaving in a car!','a morning rush','a rush hour','dramatic','exclamation'),
(4285,'en','Adult life means bills.','Adult life means games.','an adult going to work','an adult going to bed','slang','cliche'),
(4378,'en','Two showers in one bathroom? Wow!','Two toilets in one bathroom? Wow!','a shower on the wall','a shower in the garden','dramatic','exclamation'),
(4380,'en','She is filling the bath.','She is filling the sink.','filling a bath with foam','filling a glass with water','chill','none'),
(4391,'en','Alone with a whole pizza? Yes!','Alone with a whole cake? Yes!','home alone with pizza','alone in a restaurant','slang','exclamation'),
(4477,'en','He is turning to a new month.','He is turning to a new book.','turning to a new month','a month at the beach','chill','none'),
(4478,'en','She marked a date. Big day!','She marked a name. Big day!','a date marked in red','a date at a restaurant','dramatic','guessing'),
(4548,'en','Oh no, he woke up late!','Oh no, he woke up early!','waking up late','working late','dramatic','exclamation'),
(4550,'en','Finally, coffee. She is alive.','Finally, tea. She is alive.','finally drinking coffee','finally going to bed','slang','exaggeration'),
(4877,'en','Now everybody is sitting!','Now everybody is standing!','sitting in a full hall','sitting in an empty bus','dramatic','exclamation'),
(4992,'en','So much ironing! She is busy.','So much cooking! She is busy.','busy with the ironing','busy with the dishes','dramatic','exclamation'),
(5088,'en','The boy is awake and yawning.','The boy is awake and eating.','awake at sunrise','awake at midnight','chill','none'),
(5148,'en','Good morning, empty city!','Good night, empty city!','an empty morning street','a busy morning street','dramatic','exclamation'),
(5202,'en','She put the whole shop in the fridge!','She put the whole shop in the oven!','putting food in the fridge','putting food on the table','dramatic','exaggeration'),
(5410,'en','He has a green toothbrush.','He has a blue toothbrush.','a green toothbrush','an electric toothbrush','chill','none'),
(5482,'en','The dog is having a bath. Spa day!','The cat is having a bath. Spa day!','a dog in a bath','a dog in a pool','slang','cliche'),
(5496,'en','She is adjusting his tie.','She is adjusting his hat.','adjusting a tie knot','adjusting a watch','flirt','none'),
(151,'en','A chain secures the gate.','A rope secures the gate.','a chain around a gate','a chain around a bike','business','none'),
(451,'en','She is locking the door.','She is opening the door.','locking a boat door','locking a car door','chill','none'),
(1097,'en','She is closing the garage.','She is closing the window.','closing the garage door','opening the garage door','chill','none'),
(1159,'en','Here is your room key.','Here is your car key.','a hotel room key','a car key','business','none'),
(1988,'en','The fence has sharp spikes.','The fence has no gate.','a spiked iron fence','a wooden garden fence','chill','none'),
(2011,'en','The door is wide open.','The door is closed.','an open glass door','an open laptop','chill','none'),
(4769,'en','She is standing by a fence.','She is sitting on a fence.','a fence along the rim','a fence around a garden','chill','none'),
(4841,'en','She found the key! Finally!','She found the phone! Finally!','finding a small key','losing a small key','dramatic','exclamation'),
(4883,'en','The doors reveal green hills.','The doors reveal a blue sea.','revealing a green valley','revealing a secret','chill','none'),
(5007,'en','Yes! Her key is in the lock!','Yes! Her key is in the car!','a key in the lock','a lock on a bike','dramatic','exclamation'),
(5049,'en','He is closing the front door.','He is closing the garage door.','closing a front door','closing a shop','chill','none'),
(5116,'en','He is opening all the windows!','He is closing all the windows!','to open the windows','to open a present','dramatic','exclamation'),
(5127,'en','The suitcase won''t shut!','The suitcase won''t open!','to shut a full suitcase','to shut a window','dramatic','exclamation'),
(5498,'en','Every window, a new view!','Every door, a new view!','leaning out of a window','cleaning a window','slang','exaggeration'),
(147,'en','They are walking into a dark cave!','They are walking into a dark house!','walking into a dark cave','sleeping in a cave','dramatic','exclamation'),
(173,'en','They are lying on a cliff.','They are lying on a beach.','the edge of a cliff','climbing a cliff','chill','none'),
(254,'en','They are spinning the Earth!','They are painting the Earth!','the Earth on a desk','a map of the Earth','low_iq','exaggeration'),
(291,'en','They are in a wheat field.','They are in a rice field.','a golden wheat field','a football field','chill','none'),
(310,'en','This forest is huge!','This desert is huge!','a forest of tall trees','a forest fire','dramatic','exclamation'),
(495,'en','They are relaxing in nature.','They are running in nature.','lying in nature','a nature film','chill','none'),
(508,'en','Dolphins in the ocean! No way!','Sharks in the ocean! No way!','dolphins in the ocean','swimming in the ocean','dramatic','exclamation'),
(616,'en','Rock: one. Humans: zero.','Tree: one. Humans: zero.','pushing a giant rock','throwing a small rock','slang','cliche'),
(634,'en','A wave ate her sand art.','A dog ate her sand art.','drawing in the sand','building a sand castle','slang','exaggeration'),
(718,'en','The geese are flying south.','The geese are walking south.','following the birds south','driving south','chill','none'),
(793,'en','She put the last stone on top.','She put the last shell on top.','a stone on the top','the top of a car','chill','none'),
(808,'en','The tree is huge!','The rock is huge!','a huge old tree','a tree house','dramatic','exclamation'),
(4527,'en','He is chopping vegetables!','He is chopping meat!','chopping vegetables','washing vegetables','dramatic','exclamation'),
(4936,'en','She is cooking in a kitchen.','She is cooking in a garden.','a professional kitchen','a home kitchen','chill','none'),
(1028,'en','She is in the Czech Republic.','He is in the Czech Republic.','sunset in the Czech Republic','snow in the Czech Republic','chill','none'),
(4731,'en','Each nation''s flag is rising.','Each nation''s flag is falling.','the flag of every nation','the army of a nation','business','none'),
(5296,'en','He is making traditional food!','He is buying traditional food!','cooking traditional food','a traditional dance','dramatic','exclamation'),
(501,'en','They are walking at night.','They are walking at noon.','walking home at night','working at night','chill','none'),
(645,'en','He is organising his schedule.','He is organising his desk.','planning a schedule','a bus schedule','business','none'),
(855,'en','They are walking by the sea.','They are running by the sea.','walking by the sea','walking in the mountains','chill','none'),
(1325,'en','She is sleeping. The pillow is her friend.','She is sleeping. The cat is her friend.','sleeping on a bed','sleeping on a train','low_iq','guessing'),
(1385,'en','Water from a tap! Wow!','Water from a hose! Wow!','turning the tap','a tap on the shoulder','low_iq','exclamation'),
(3163,'en','She is washing her hands.','She is washing her face.','washing her hands','washing the dishes','chill','none'),
(3222,'en','A cat is sleeping like a king.','A dog is sleeping like a king.','sleeping in an armchair','sleeping in a basket','slang','cliche'),
(4728,'en','She is sleeping on the sofa. Long day!','She is sleeping on the floor. Long day!','sleeping on the sofa','sleeping at work','slang','guessing'),
(4937,'en','He is ringing the bell.','He is ringing the doorbell.','ringing the service bell','ringing a friend','business','none'),
(5467,'en','The boy is awaking in shock!','The dog is awaking in shock!','awaking in a bunk bed','awaking in a tent','dramatic','exclamation'),
(909,'en','He is asking if anyone is home.','She is asking if anyone is home.','asking if anyone is home','asking if anyone is hungry','chill','none'),
(2068,'en','The red door is open.','The blue door is open.','an open red door','a red garage door','chill','none'),
(4076,'en','They are jumping out of the door!','They are jumping out of the window!','an open helicopter door','an open car door','dramatic','exclamation'),
(4242,'en','A gate? The cat is passing anyway.','A gate? The dog is passing anyway.','passing through a gate','passing a ball','slang','understatement'),
(615,'en','Leaf race on the river. Go go!','Boat race on the river. Go go!','leaves on a clear river','a boat on a river','slang','none'),
(746,'en','They are jumping the stream!','They are jumping the fence!','jumping over a stream','swimming in a stream','dramatic','exclamation')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
