begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(844,'en','What a huge green valley!','What a huge green desert!','a green valley below','a valley under snow','dramatic','exclamation'),
(850,'en','The volcano is smoking. Nobody panic.','The chimney is smoking. Nobody panic.','a smoking volcano','a volcano under the sea','ironic','understatement'),
(864,'en','This water is crazy clear.','This milk is crazy clear.','clear water in a bottle','water in a plastic cup','slang','exaggeration'),
(868,'en','Just a small wave.','Just a small shark.','a wave crashing on swimmers','a wave of the hand','ironic','understatement'),
(901,'en','He is breathing the fresh air, arms wide open.','He is breathing the city air, arms wide open.','fresh mountain air','fresh air in the city','chill','none'),
(1033,'en','The desert has no end!','The forest has no end!','camels in the desert','snow in the desert','dramatic','exaggeration'),
(1134,'en','Guess who is having lunch on the hill? The sheep.','Guess who is having lunch on the hill? The cows.','a tree on the hill','a house on the hill','gossip','guessing'),
(1156,'en','The parrot runs this jungle.','The monkey runs this jungle.','a parrot in the jungle','a parrot in a cage','slang','exaggeration'),
(1206,'en','Mud is flying everywhere!','Snow is flying everywhere!','a shoe in deep mud','a shoe in fresh snow','dramatic','exclamation'),
(1363,'en','This stone will swim, right?','This leaf will swim, right?','a stone over a lake','a stone in a wall','low_iq','guessing'),
(2045,'en','These stones are super tall.','These trees are super tall.','tall standing stones','tall trees in a field','slang','exaggeration'),
(2121,'en','Heavy rocks, perfect balance.','Heavy bricks, perfect balance.','a tower of heavy rocks','a heavy bag of rocks','business','none'),
(2164,'en','A path goes into the woods. Who wants to go first?','A river goes into the woods. Who wants to go first?','a path through the woods','a cabin in the woods','dramatic','guessing'),
(2214,'en','I can see a castle through it.','I can see a church through it.','looking through a rock hole','looking through a window','chill','none'),
(2297,'en','Waves are hitting the shore.','Waves are hitting the boat.','palm trees on the shore','a boat on the shore','chill','none'),
(2306,'en','The countryside never ends.','The city never ends.','kids in the countryside','kids leaving the countryside','chill','exaggeration'),
(2663,'en','His shadow is so long!','His shadow is so short!','a cowboy''s long shadow','a shadow on the wall','dramatic','exclamation'),
(2800,'en','Can I pop that big bubble?','Can I pop that big balloon?','a bubble in the sky','a bubble in a glass','low_iq','guessing'),
(4005,'en','Frozen wall? No problem.','Rock wall? No problem.','climbing a frozen wall','a frozen lake for skating','ironic','understatement'),
(4010,'en','She is climbing like a pro!','She is swimming like a pro!','to climb a white cliff','to climb a ladder','flirt','cliche'),
(4015,'en','Sheep are jumping to the bank!','Goats are jumping to the bank!','sheep on the river bank','sheep outside a bank','dramatic','exclamation'),
(4088,'en','This waterfall is really wide. Do not step closer.','This bridge is really wide. Do not step closer.','a wide waterfall edge','a wide river bridge','dramatic','guessing'),
(4198,'en','The hole goes deep underwater. See you at the bottom!','The rope goes deep underwater. See you at the bottom!','dropping deep down a shaft','digging deep in the sand','slang','exclamation'),
(4233,'en','Stone bridge: strong enough for trains.','Wood bridge: strong enough for trains.','a stone railway bridge','a stone railway tunnel','business','none'),
(4247,'en','Boys are jumping into a well!','Boys are jumping into a lake!','boys jumping into a well','boys drinking from a well','dramatic','exclamation'),
(4354,'en','Her kick sent leaves flying.','Her kick sent acorns flying.','a kick in the leaves','a kick at a football','chill','none'),
(4485,'en','Powerful falls, free shower!','Powerful rain, free shower!','a powerful waterfall','a powerful canoe engine','slang','exaggeration'),
(4491,'en','The river is far below.','The sun is far below.','a river far below','clouds far below','chill','none'),
(4826,'en','The dam is overflowing!','The pool is overflowing!','an overflowing dam','a dry dam in summer','dramatic','exclamation'),
(4833,'en','He is skating along the coast like it is nothing.','He is cycling along the coast like it is nothing.','skating down the coast road','sailing along the coast','flirt','cliche'),
(4989,'en','They are storming down the hill!','They are storming down the road!','charging down a hill','rolling down a hill','dramatic','exclamation'),
(5001,'en','Worth it for this landscape.','Worth it for this beach.','a mountain landscape','a landscape painting','slang','cliche'),
(5005,'en','She sees everything in this bay.','She sees everything in this park.','boats in a quiet bay','a bay full of ice','gossip','guessing'),
(5096,'en','Mushrooms grow in the ground.','Mushrooms grow in the water.','a mushroom on the ground','a mushroom on a pizza','chill','none'),
(5201,'en','The water reflects everything, including the volcano.','The water reflects everything, including the moon.','a volcano reflected in water','a face in a mirror','business','none'),
(5214,'en','Bike, scooter, then desert!','Bike, scooter, then jungle!','a camel in the desert','a camel in a zoo','dramatic','exclamation'),
(5323,'en','That stone made a big splash.','That boat made a big splash.','throwing a big stone','skimming a flat stone','slang','exaggeration'),
(41,'en','Just a small argument.','Just a small kiss.','an argument about a picture','an argument about money','ironic','understatement'),
(285,'en','Family photo time. Say cheese!','Family swim time. Say cheese!','a family photo outside','a family photo album','dramatic','exclamation'),
(349,'en','Fishing, chess and a hug: best grandfather ever.','Fishing, chess and a hug: best grandmother ever.','a grandfather and grandson','a grandfather and his dog','slang','cliche'),
(350,'en','Her grandson is home!','Her husband is home!','hugging her grandson','hugging her husband','dramatic','exclamation'),
(454,'en','Soup and a blanket: pure love.','Tea and a blanket: pure love.','love on a rainy night','love at first sight','flirt','exaggeration'),
(513,'en','They are eating outside. Who needs a dining room?','They are eating inside. Who needs a dining room?','eating outside on the grass','eating outside at a cafe','ironic','guessing'),
(684,'en','Her sister is finally home!','Her brother is finally home!','hugging her sister','fighting with her sister','dramatic','exclamation'),
(842,'en','The baby wants every letter.','The baby wants every biscuit.','a baby playing with letters','a baby playing with food','gossip','guessing'),
(873,'en','His wife can flip pancakes!','His wife can flip burgers!','a wife flipping pancakes','a wife baking a cake','flirt','exclamation'),
(919,'en','Her aunt is a fun one.','Her uncle is a fun one.','dancing with her aunt','shopping with her aunt','slang','none'),
(958,'en','The bride is ready!','The groom is ready!','a bride with white roses','a bride with red roses','dramatic','exclamation'),
(961,'en','Big brother wins again.','Big sister wins again.','a brother in a headlock','boxing with a brother','slang','cliche'),
(1013,'en','Two cousins are laughing hard.','Two cousins are crying hard.','two cousins on the grass','two cousins at a table','chill','none'),
(1030,'en','Flowers from his daughter!','Flowers from his son!','flowers from a daughter','flowers for a daughter','dramatic','exclamation'),
(1040,'en','Soon they will be divorced.','Soon they will be married.','getting divorced','getting married','gossip','guessing'),
(1110,'en','Kisses from a granddaughter!','Kisses from a grandson!','a granddaughter''s kiss','a granddaughter''s drawing','slang','exclamation'),
(1112,'en','Grandmother is making bread.','Grandmother is making soup.','baking with grandmother','knitting with grandmother','chill','none'),
(1136,'en','He is finally home!','He is finally at work!','coming home with a bag','leaving home with a bag','dramatic','exclamation'),
(1188,'en','They just got married and are already dancing.','They just got married and are already fighting.','a married couple dancing','a married couple arguing','chill','none'),
(1202,'en','Mother and baby: nose to nose.','Mother and dog: nose to nose.','a mother lifting her baby','a mother feeding her baby','chill','none'),
(1227,'en','Parent mode: jogging.','Parent mode: sleeping.','a parent beside a bike','a parent fixing a bike','slang','cliche'),
(1342,'en','His son is back home!','His daughter is back home!','hugging his adult son','waving goodbye to his son','dramatic','exclamation'),
(1419,'en','Twins, same dress. Planned?','Twins, same hat. Planned?','twins in matching dresses','twins in a pram','gossip','guessing'),
(1420,'en','Best uncle ever!','Best aunt ever!','on his uncle''s shoulders','on his uncle''s bike','slang','exaggeration'),
(1704,'en','It says ''happy Christmas''.','It says ''happy birthday''.','an old Christmas card','an old Christmas tree','chill','none'),
(1783,'en','Four children, one lap, a hug for each child.','Four children, one lap, a gift for each child.','a man hugging each child','a man teaching each child','chill','none'),
(2188,'en','The boy is crying, Mom isn''t.','The boy is singing, Mom isn''t.','crying on a bike','crying in bed','ironic','none'),
(2549,'en','Father and son are cheering!','Father and son are crying!','a father carrying his son','a father carrying shopping','dramatic','exclamation'),
(3645,'en','Far from home, a family photo on his desk.','Far from home, a family dog on his desk.','a family photo in space','a family photo album','dramatic','none'),
(4108,'en','His car says he''s her husband.','His car says he''s her brother.','a husband in a car','a husband washing a car','gossip','none'),
(4182,'en','He painted the whole lawn!','He painted the whole house!','painting a giant lawn picture','painting a garden fence','dramatic','exaggeration'),
(4183,'en','The gift has a man inside!','The gift has a dog inside!','a man inside a gift','a watch inside a gift','dramatic','exclamation'),
(4305,'en','The boy got a huge burger.','The boy got a huge pizza.','a boy getting a burger','a boy cooking a burger','chill','exaggeration'),
(4443,'en','The wedding is starting and everyone is turning around.','The wedding is ending and everyone is turning around.','walking down a wedding aisle','dancing at a wedding party','chill','none'),
(4610,'en','Dad is ready to catch her!','Mom is ready to catch her!','jumping into dad''s arms','running away from dad','dramatic','exclamation'),
(4611,'en','Her daughter drew the family.','Her daughter drew a horse.','a daughter baking with mom','a daughter shopping with mom','chill','none'),
(4727,'en','This father never gets tired.','This mother never gets tired.','a father playing catch','a father watching TV','gossip','exaggeration'),
(4774,'en','Every generation is laughing under the apple tree.','Every generation is laughing under the palm tree.','generations in a garden','generations at a dinner table','chill','none'),
(4781,'en','She is marrying him!','She is leaving him!','to marry in a garden','to marry on a beach','dramatic','exclamation'),
(4794,'en','Grandmother''s cookies win.','Grandmother''s pizza wins.','cookies from grandmother','cookies from a shop','slang','cliche'),
(5089,'en','This mother does it all.','This father does it all.','a mother flipping pancakes','a mother buying pancakes','chill','exaggeration'),
(5134,'en','The parents are a bit busy.','The dogs are a bit busy.','parents feeding a baby','parents feeding the ducks','ironic','understatement'),
(5310,'en','A son is helping fix the car.','A son is helping wash the car.','a son holding a spanner','a son washing the car','chill','none'),
(5441,'en','The uncle let her win.','The uncle let him win.','arm-wrestling with an uncle','boxing with an uncle','gossip','guessing'),
(84,'en','The belt saved his trousers!','The rope saved his trousers!','putting on a leather belt','taking off a leather belt','dramatic','exclamation'),
(100,'en','These boots love mud.','These sandals love mud.','boots in the mud','boots in a shop','slang','exaggeration'),
(126,'en','He needs help with the buttons.','He needs help with the shoelaces.','a crooked row of buttons','pressing a lift button','chill','none'),
(138,'en','A cap, finally some shade.','A tree, finally some shade.','a coral cap for shade','a cap on a bottle','chill','none'),
(177,'en','Coat on. Winter, do your worst.','Gloves on. Winter, do your worst.','buttoning a long coat','hanging up a long coat','dramatic','cliche'),
(181,'en','Collar up? No way!','Sleeves up? No way!','a collar popped up','a dog''s collar','slang','exclamation'),
(194,'en','The cotton is so soft.','The wool is so soft.','picking soft cotton','buying cotton sheets','chill','none'),
(242,'en','Spin again! Great dress!','Spin again! Great hat!','a red summer dress','a red wedding dress','flirt','exclamation'),
(288,'en','Even the dog loves fashion.','Even the cat loves fashion.','fashion on a Paris street','a fashion magazine cover','gossip','exaggeration'),
(336,'en','Glasses on, more ducks!','Glasses on, more geese!','cleaning round glasses','breaking round glasses','low_iq','exclamation'),
(390,'en','His hoodie is super cozy.','His jacket is super cozy.','pulling up a hoodie','washing a hoodie','slang','exaggeration'),
(408,'en','The jacket is on. Much better.','The scarf is on. Much better.','zipping up a brown jacket','a jacket on a chair','chill','none'),
(435,'en','The leather is creaking!','The floor is creaking!','stretching leather','a leather sofa','dramatic','exclamation'),
(496,'en','Nice necklace, great choice.','Nice bracelet, great choice.','a colourful beaded necklace','a gold chain necklace','flirt','none'),
(512,'en','The outfit finally works.','The haircut finally works.','putting together an outfit','an outfit for a wedding','chill','none'),
(563,'en','The keys were in his pocket!','The keys were in his shoe!','keys in a jacket pocket','keys in a car door','low_iq','exclamation'),
(635,'en','Sandals on, toes out!','Boots on, toes out!','buckling tan sandals','buying tan sandals','slang','none'),
(666,'en','He is putting on a blue shirt.','He is putting on a red shirt.','buttoning a light-blue shirt','ironing a light-blue shirt','chill','none'),
(668,'en','Shoes laced. Ready to go.','Boots laced. Ready to go.','lacing up brown shoes','polishing brown shoes','business','none'),
(679,'en','The silver is shining again!','The gold is shining again!','polishing old silver','silver paint on a car','dramatic','exclamation'),
(685,'en','Finally, the right size.','Finally, the right shoes.','the right hat size','the right shoe size','chill','none'),
(689,'en','Great skirt, great spin!','Great hat, great spin!','a yellow pleated skirt','a long black skirt','flirt','exclamation'),
(702,'en','Sneakers on, stairs next.','Sandals on, stairs next.','lacing teal sneakers','cleaning teal sneakers','slang','none'),
(753,'en','That blue suit fits him well.','That grey suit fits him well.','trying on a blue suit','washing a blue suit','flirt','none'),
(759,'en','Rain outside, sweater inside.','Sun outside, sweater inside.','pulling on a cozy sweater','knitting a cozy sweater','chill','none'),
(762,'en','No, no, maybe... that T-shirt!','No, no, maybe... that jacket!','pulling on a teal T-shirt','folding a teal T-shirt','slang','none'),
(766,'en','This tattoo is forever!','This sticker is forever!','a fresh bird tattoo','a tattoo on a leg','dramatic','exclamation'),
(782,'en','Second try, perfect tie.','Second try, perfect cake.','knotting a dark red tie','buying a dark red tie','business','none'),
(821,'en','Home again: underwear time!','Home again: pyjama time!','stripping down to underwear','buying new underwear','slang','exclamation'),
(893,'en','Zipped up and ready for snow.','Zipped up and ready for sun.','to zip up a jacket','to zip up a suitcase','chill','none'),
(894,'en','The zipper is stuck!','The ski is stuck!','a stuck jacket zipper','a zipper on a tent','dramatic','exclamation'),
(1198,'en','The model owns the runway.','The model owns the beach.','a model on a runway','a model of a plane','slang','exaggeration'),
(1326,'en','Fluffy slippers, lazy morning.','Fluffy socks, lazy morning.','putting on fluffy slippers','fluffy slippers in a shop','chill','none'),
(1432,'en','He is singing in a costume. The glass slipper is ready.','He is dancing in a costume. The glass slipper is ready.','singing in a costume','shopping for a costume','gossip','guessing'),
(1482,'en','Great gold earrings!','Great silver earrings!','big gold hoop earrings','earrings in a gift box','flirt','exclamation'),
(1643,'en','He wears a cowboy hat.','He wears a baseball cap.','a wide cowboy hat','a wide straw hat','chill','none'),
(1706,'en','Cool dog, cool sunglasses.','Cool dog, cool hat.','a husky in sunglasses','sunglasses on a beach towel','slang','none'),
(1713,'en','Hundreds of feathers on top.','Hundreds of flowers on top.','a headdress of long feathers','a pillow full of feathers','chill','exaggeration'),
(1728,'en','Red fan up, leg up!','Red hat up, leg up!','waving a red fan','a fan on the ceiling','dramatic','exclamation'),
(1811,'en','The raincoat is doing its job.','The umbrella is doing its job.','a long yellow raincoat','a raincoat on a hook','business','none'),
(1858,'en','The child has a long scarf and a big balloon.','The child has a long sword and a big balloon.','a long striped scarf','a scarf in a drawer','chill','none'),
(1936,'en','Her flower crown is huge!','Her feather crown is huge!','wearing a flower crown','making a flower crown','dramatic','exclamation'),
(1946,'en','This cat is too cool.','This dog is too cool.','a cool cat in sunglasses','a cool summer drink','slang','exaggeration'),
(2144,'en','She has a white t-shirt on.','She has a black t-shirt on.','a white t-shirt and jacket','a t-shirt on a hanger','chill','none'),
(2269,'en','Her blouse is loose and white.','Her dress is loose and white.','a loose white blouse','a tight black blouse','chill','none'),
(2273,'en','Ripped jeans, full denim look.','Ripped jeans, full black look.','heavily ripped blue jeans','ironing blue jeans','slang','none'),
(2285,'en','Her sweatshirt is huge.','Her backpack is huge.','a big blue sweatshirt','a sweatshirt on a chair','chill','exaggeration'),
(2295,'en','Those sleeves are enormous!','Those boots are enormous!','wide white sleeves','short black sleeves','dramatic','exclamation'),
(2317,'en','Her red hood is up.','Her red hood is down.','a red hood pulled up','the hood of a car','chill','none'),
(2349,'en','Even the cat dressed up!','Even the dog dressed up!','dressed up as witches','dressed up as pirates','gossip','exclamation'),
(2393,'en','Office look with high heels.','Office look with trainers.','black strappy high heels','high heels in a box','business','none'),
(2395,'en','His vest has gold buttons.','His vest has silver buttons.','a black leather vest','a vest under a jacket','chill','none'),
(2446,'en','Big bows, long shoelaces!','Big bows, short shoelaces!','long yellow shoelaces','broken yellow shoelaces','low_iq','exclamation'),
(2455,'en','She wears green shorts.','She wears green trousers.','green denim shorts','green swimming shorts','chill','none'),
(2607,'en','The cats wear formal coats.','The dogs wear formal coats.','cats wearing long coats','cats wearing collars','business','none'),
(2690,'en','Her crown is full of diamonds.','Her crown is full of feathers.','a crown of diamonds','a diamond ring','gossip','exaggeration'),
(3147,'en','Blue cloth is drying on a line above the alley.','Blue paper is drying on a line above the alley.','blue cloth on a line','a cloth for the table','chill','none'),
(3479,'en','A pink handbag, a quiet cafe.','A pink laptop, a quiet cafe.','a handbag on the table','a handbag in a shop','chill','none'),
(3519,'en','That white earring is lovely.','That white necklace is lovely.','a white teardrop earring','an earring on the floor','flirt','none'),
(3841,'en','The clothes are flying around!','The shoes are flying around!','clothes floating in the air','clothes in a washing machine','dramatic','exclamation'),
(4003,'en','Two pairs of monster slippers.','Two pairs of monster boots.','a pair of yellow slippers','a pair of yellow gloves','chill','none'),
(4085,'en','She changed him completely.','He changed her completely.','to change into a suit','to change a car tyre','gossip','exaggeration'),
(4113,'en','Jewellery drama on the street!','Jewellery drama in the shop!','pink jewellery on a pigeon','pink jewellery in a window','gossip','exclamation'),
(4137,'en','So much yellow in one room!','So much green in one room!','a dress in bright yellow','a room painted yellow','slang','exaggeration'),
(4544,'en','Sand and ice. Small contrast.','Sea and ice. Small contrast.','sand and ice in contrast','day and night in contrast','ironic','understatement'),
(5254,'en','Look at those partners dance!','Look at those partners swim!','dancing with a partner','playing cards with a partner','flirt','exclamation'),
(2226,'en','He has golden bracelets.','He has golden gloves.','golden bracelets on wrists','a bracelet in a shop','chill','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
