begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(4212,'en','Their brown looks match well.','Their red looks match well.','matching brown outfits','a brown leather sofa','business','none'),
(4213,'en','They look like queens in red!','They look like queens in blue!','dressed in deep red','red wine in a glass','dramatic','exaggeration'),
(4214,'en','Both start in light blue.','Both start in dark green.','a couple in light blue','light blue curtains','chill','none'),
(4216,'en','Her white dress is gorgeous.','Her yellow dress is gorgeous.','a white cotton dress','a white wedding dress','flirt','none'),
(4272,'en','She is adding more gold!','She is adding more silver!','gold hoop earrings','a gold medal','dramatic','exclamation'),
(4442,'en','Her shoes are white.','Her shoes are red.','plain white shoes','white running shoes','chill','none'),
(4704,'en','He wears a fur hat in a sauna!','He wears a cap in a sauna!','wearing a fur hat','wearing a straw hat','slang','exclamation'),
(4722,'en','Even the women in sunglasses are fainting!','Even the women in sunglasses are dancing!','women in dark sunglasses','sunglasses on a sunny beach','dramatic','exaggeration'),
(4750,'en','She built a castle of clothes.','She built a castle of books.','folding clean clothes','washing dirty clothes','low_iq','none'),
(4845,'en','Hands are sewing the cloth.','Hands are cutting the cloth.','stitching the cloth','wiping with a cloth','chill','none'),
(4864,'en','The band is in uniform!','The band is in pyjamas!','a band in uniform','a school uniform','dramatic','exclamation'),
(4892,'en','Those swim shorts are so fast!','Those swim fins are so fast!','colourful swim shorts','shorts for football','slang','exaggeration'),
(4910,'en','He is screaming in his team scarf!','He is sleeping in his team scarf!','a striped team scarf','a warm winter scarf','dramatic','exclamation'),
(5173,'en','Good thing she has a raincoat.','Good thing she has a sun hat.','a red hooded raincoat','a raincoat on a hook','chill','understatement'),
(5217,'en','He has a yellow vest on.','He has an orange vest on.','a yellow safety vest','a vest under a shirt','chill','none'),
(5286,'en','They both want the sweatshirt!','They both want the teddy bear!','pulling a lilac sweatshirt','washing a lilac sweatshirt','dramatic','exclamation'),
(5294,'en','Her feet love the slippers.','Her feet love the socks.','fluffy sheep slippers','slippers under the bed','chill','exaggeration'),
(5328,'en','She is sniffing a peach blouse.','She is sniffing a white blouse.','a peach ruffled blouse','ironing a peach blouse','chill','none'),
(5357,'en','The dog has a fancier stroller than most babies.','The cat has a fancier stroller than most babies.','a fancy chrome stroller','a fancy dress party','dramatic','exaggeration'),
(5489,'en','She wears every coat so well.','She wears every suit so well.','wearing a feather hat','wearing a straw hat','flirt','none'),
(15,'en','One pill and he is fine.','One coffee and he is fine.','swallowing a white pill','a pill for sleeping','chill','exaggeration'),
(195,'en','Honey tea stops the coughing.','Cold beer stops the coughing.','coughing in an armchair','coughing at a concert','chill','guessing'),
(521,'en','His toe is in serious pain!','His hand is in serious pain!','pain in the toe','pain in the back','dramatic','exclamation'),
(674,'en','She is sick and at home.','She is sick and at work.','sick on the sofa','sick in a hospital bed','chill','none'),
(704,'en','He sneezed his hat off!','He sneezed his shoe off!','sneezing at dandelions','sneezing at a cat','dramatic','exaggeration'),
(705,'en','The sneezing never stops.','The singing never stops.','sneezing into her elbow','sneezing into a tissue','dramatic','none'),
(904,'en','She has a pollen allergy.','She has a dust allergy.','an allergy to pollen','an allergy to cats','chill','none'),
(1012,'en','She is coughing so hard!','She is laughing so hard!','coughing into the elbow','coughing into a tissue','dramatic','exclamation'),
(1074,'en','He is checking her fever.','He is checking her phone.','checking her fever','checking her pulse','chill','none'),
(1126,'en','Work gave him a headache.','Music gave him a headache.','a headache at night','a headache in the sun','chill','blaming_someone'),
(1193,'en','Open wide for the medicine.','Open wide for the ice cream.','liquid medicine on a spoon','medicine in a pill box','chill','cliche'),
(1398,'en','Her thermometer is huge!','Her toothbrush is huge!','a big glass thermometer','a thermometer on the wall','dramatic','exclamation'),
(4405,'en','His friend is a big help.','His dog is a big help.','help from a friend','help with homework','chill','none'),
(4452,'en','That shin must really hurt!','That arm must really hurt!','a shin that hurts','an arm that hurts','dramatic','guessing'),
(4567,'en','She looks a bit ill.','She looks very happy.','ill and coughing','ill in bed','chill','understatement'),
(4575,'en','Her cold came to the library.','Her cold came to the cinema.','a cold in the library','a cold in the snow','chill','none'),
(4733,'en','His temperature is sky high!','His temperature is very low!','taking his temperature','the temperature outside','dramatic','exaggeration'),
(5128,'en','The sofa caused real hurt!','The table caused real hurt!','hurt from the sofa corner','hurt from a football game','dramatic','blaming_someone'),
(5301,'en','Her allergy hates this meadow.','Her allergy hates this beach.','an allergy to pollen','an allergy to dogs','low_iq','exaggeration'),
(111,'en','Boxing makes her so happy.','Tennis makes her so happy.','boxing with red gloves','boxing up old clothes','slang','none'),
(266,'en','She has way too much energy!','He has way too much energy!','full of energy','energy from the sun','slang','exaggeration'),
(356,'en','She will live in this gym now.','She will live in this pub now.','a bright new gym','gym class at school','low_iq','guessing'),
(414,'en','He jumped over the bar!','He jumped over the fence!','to jump over the bar','to jump into the pool','dramatic','exclamation'),
(422,'en','Her kicking is super high.','Her kicking is super low.','kicking a punching bag','kicking a football','slang','none'),
(468,'en','They are on their yoga mats.','They are on their towels.','a purple yoga mat','a mat at the door','chill','none'),
(481,'en','The mirror loves him back.','The window loves him back.','flexing at the mirror','cleaning the mirror','low_iq','guessing'),
(488,'en','His muscles are enormous!','His shoes are enormous!','flexing big muscles','a muscle in the leg','dramatic','exclamation'),
(613,'en','He is bouncing in the ring.','He is bouncing in the pool.','climbing into the ring','a ring on a finger','chill','none'),
(640,'en','The scale must be broken!','The clock must be broken!','a big dial scale','a kitchen scale','low_iq','bad_excuse'),
(724,'en','Each splash gets bigger!','Each splash gets smaller!','a huge splash','a splash of milk','dramatic','exclamation'),
(749,'en','They are stretching together.','They are dancing together.','to stretch before running','to stretch a rubber band','chill','none'),
(807,'en','The treadmill almost won, bro.','The bike almost won, bro.','running on a treadmill','walking on a treadmill','slang','guessing'),
(869,'en','She is carrying a weight.','She is carrying a box.','a heavy round weight','losing weight fast','chill','none'),
(882,'en','The dog is her workout coach.','The cat is her workout coach.','a full workout','a workout on the beach','low_iq','exaggeration'),
(1025,'en','That cyclist is super brave.','That runner is super brave.','a cyclist cornering fast','a cyclist in the city','slang','none'),
(1073,'en','The female climber is flying!','The male climber is flying!','a female climber','a female runner','dramatic','exaggeration'),
(1375,'en','Sweat is flying off her glove!','Sweat is flying off her shoe!','sweat on her arm','sweat on a shirt','dramatic','exclamation'),
(1699,'en','Someone is swimming to the music.','Someone is flying to the music.','swimming across calm water','swimming in a pool','chill','none'),
(2378,'en','She is totally relaxing now.','She is totally running now.','relaxing under the moon','relaxing on the beach','slang','none'),
(2602,'en','They are skiing down so fast.','They are skiing up so fast.','skiing down a steep slope','skiing on a flat road','slang','none'),
(2708,'en','The monkey god looks strong.','The monkey god looks tiny.','strong arms and chest','a strong cup of coffee','chill','none'),
(2795,'en','He is climbing upside down!','He is sleeping upside down!','climbing under a cliff','climbing up a ladder','dramatic','exclamation'),
(2877,'en','He is climbing the rope.','He is climbing a ladder.','to climb a rope','to climb a tree','chill','none'),
(2914,'en','Someone is stretching up high.','Someone is jumping up high.','to stretch the arms up','to stretch before a run','chill','none'),
(3101,'en','She is jumping so high!','She is swimming so fast!','to jump over a rope','to jump into a lake','slang','exclamation'),
(3126,'en','The boxer looks super serious.','The boxer looks super sleepy.','a boxer in red gloves','walking a boxer dog','slang','none'),
(3136,'en','She is swimming in a lake.','She is swimming in a pool.','to swim in a lake','to swim in the sea','chill','none'),
(3216,'en','They are running side by side.','They are dancing side by side.','to run side by side','to run for a bus','chill','none'),
(3412,'en','She is lifting in a red dress!','She is lifting in a red coat!','to lift a barbell','to lift a suitcase','dramatic','exclamation'),
(3592,'en','Both are exercising hard.','Both are dancing hard.','to exercise together','to exercise a dog','business','none'),
(4136,'en','Exercising with four dogs is not easy.','Exercising with four cats is not easy.','to exercise with dogs','to exercise in a park','chill','understatement'),
(4271,'en','The athlete is so fast!','The athlete is so slow!','an athlete at full speed','an athlete at the finish','slang','exclamation'),
(4479,'en','This ride is hard work!','This ride is easy work!','a hard spin class','a hard bike seat','dramatic','none'),
(4545,'en','She has huge finger strength.','He has huge finger strength.','strength in her fingers','strength in her legs','chill','exaggeration'),
(4673,'en','He is way too weak for it!','He is way too strong for it!','a weak skinny arm','a weak cup of tea','slang','exclamation'),
(4697,'en','He has a lightning start!','He has a slow start!','a start from the blocks','the start of school','dramatic','exaggeration'),
(4711,'en','His face is pure effort.','His face is pure boredom.','rowing with full effort','running with full effort','dramatic','none'),
(4742,'en','She is strong on the ropes!','She is strong on the bike!','strong arms and legs','a strong cup of coffee','flirt','exclamation'),
(5326,'en','The coach is taping her ankle.','The coach is taping her wrist.','a coach helping a gymnast','a coach shouting at players','chill','none'),
(5354,'en','The class follows her well.','The class follows him well.','a class in the park','a class in a school','business','none'),
(13,'en','Her napkin is a work of art!','Her cake is a work of art!','folding a napkin','a napkin on the floor','dramatic','exaggeration'),
(26,'en','His straw works super fast!','His spoon works super fast!','a striped bendy straw','a straw sun hat','slang','exclamation'),
(46,'en','That apple looks so crispy!','That pear looks so crispy!','biting a red apple','baking an apple pie','slang','none'),
(62,'en','The apple escaped the bag!','The bread escaped the bag!','packing a picnic bag','a plastic shopping bag','low_iq','exaggeration'),
(67,'en','He learned a new banana trick.','He learned a new apple trick.','peeling a banana','a banana in a smoothie','chill','none'),
(83,'en','The beer foam is top quality.','The milk foam is top quality.','pouring a golden beer','beer at a football match','business','none'),
(107,'en','The bowl is his cup now.','The pot is his cup now.','drinking from a bowl','washing a blue bowl','low_iq','guessing'),
(114,'en','The bread is still so warm.','The bread is still so frozen.','warm bread from the oven','bread from the supermarket','slang','none'),
(115,'en','The rooster came for breakfast too.','The dog came for breakfast too.','breakfast in the garden','breakfast in bed','chill','guessing'),
(120,'en','That burger needs both hands!','That pizza needs both hands!','a tall cheese burger','a burger in a box','slang','exclamation'),
(125,'en','The butter broke the bread!','The jam broke the bread!','butter too hard to spread','butter in a hot pan','dramatic','blaming_someone'),
(128,'en','Her birthday cake has berries.','Her birthday cake has bananas.','a cream birthday cake','a chocolate wedding cake','chill','none'),
(150,'en','He eats cereal without milk!','He eats cereal without a bowl!','dry cereal in a bowl','cereal in a box','low_iq','exclamation'),
(155,'en','The cheese stretches forever!','The bread stretches forever!','stretchy melted cheese','cheese on a pizza','dramatic','exaggeration'),
(157,'en','Her chewing gum is so pink.','Her chewing gum is so green.','blowing chewing gum bubbles','chewing gum under a desk','slang','none'),
(158,'en','The chewing is hard work!','The walking is hard work!','chewing sticky toffee','chewing a pencil','dramatic','exclamation'),
(162,'en','He is melting chocolate.','He is melting butter.','melting chocolate in a pot','a chocolate birthday cake','chill','none'),
(163,'en','He can use chopsticks now!','He can use a fork now!','holding chopsticks','breaking chopsticks','dramatic','exclamation'),
(179,'en','Coffee works like magic!','Water works like magic!','coffee from a moka pot','coffee from a machine','slang','exaggeration'),
(190,'en','She is dunking her cookie.','She is dunking her bread.','dunking a cookie','baking a cookie cake','chill','none'),
(206,'en','Her cucumber spa is cheap.','Her lemon spa is cheap.','cucumber slices on the eyes','cucumber in a sandwich','chill','cheap_quality'),
(207,'en','Her cup is small and green.','Her cup is small and blue.','a small green cup','a cup of coffee','chill','none'),
(223,'en','The delivery is finally here!','The plumber is finally here!','a food delivery','a parcel delivery','dramatic','exclamation'),
(228,'en','Dinner by the sea is not bad.','Dinner by the pool is not bad.','dinner on the terrace','dinner in the kitchen','chill','understatement'),
(244,'en','One drink was not enough.','One sandwich was not enough.','a fresh orange drink','a hot drink','low_iq','guessing'),
(256,'en','All that eating made them full.','All that eating made them hungry.','eating noodle soup','eating a sandwich','chill','none'),
(296,'en','He is grilling a whole fish.','He is grilling a whole duck.','a grilled whole fish','a fish in a tank','chill','none'),
(308,'en','There is so much food!','There is so little food!','a big spread of food','food in a fridge','dramatic','exclamation'),
(311,'en','Her fork skills are impressive.','Her knife skills are impressive.','spaghetti on a fork','a fork in the road','flirt','none'),
(317,'en','The french fries are so hot!','The french fries are so cold!','french fries in a cone','french fries on a plate','slang','exclamation'),
(321,'en','She wants all the fruit!','She wants all the bread!','buying fresh fruit','a fruit salad','slang','exaggeration'),
(334,'en','Her glass is ice cold.','Her glass is hot.','a glass of lemonade','a glass of wine','chill','none'),
(389,'en','The honey is so slow!','The honey is so fast!','honey on a wooden dipper','honey in tea','slang','exclamation'),
(399,'en','He is losing to his ice cream.','He is losing to his hot dog.','melting ice cream','ice cream in a cup','low_iq','exaggeration'),
(410,'en','She is spreading jam thickly.','She is spreading jam thinly.','jam on toast','a traffic jam','chill','none'),
(413,'en','The juice is ruby red.','The juice is bright orange.','fresh pomegranate juice','orange juice in a box','chill','none'),
(416,'en','The ketchup finally gave up!','The mustard finally gave up!','ketchup on fries','ketchup on a burger','dramatic','exaggeration'),
(438,'en','The lemon is way too sour!','The lemon is way too sweet!','biting a lemon wedge','a lemon cake','slang','exclamation'),
(439,'en','The lemonade is super cold.','The lemonade is super hot.','a jar of lemonade','a can of lemonade','slang','none'),
(471,'en','The dog wants the meat.','The cat wants the meat.','grilled meat on a board','raw meat in a shop','low_iq','guessing'),
(478,'en','Everyone has a milk moustache!','Nobody has a milk moustache!','a milk moustache','milk in the fridge','dramatic','exaggeration'),
(480,'en','The mineral water tickles her.','The orange juice tickles her.','fizzy mineral water','still mineral water','chill','none'),
(505,'en','He is fighting a tiny nut.','He is fighting a tiny egg.','cracking a nut','a nut on a bolt','low_iq','exaggeration'),
(509,'en','The oil is pouring slowly.','The milk is pouring slowly.','bread in olive oil','oil in a frying pan','chill','none'),
(535,'en','The pasta tower looks professional.','The cake tower looks professional.','a tower of pasta','pasta in a salad','business','none'),
(573,'en','His pouring shows real skill.','His singing shows real skill.','pouring from up high','pouring rain outside','business','none'),
(631,'en','He makes salads very efficiently.','He makes cakes very efficiently.','tossing a fresh salad','a salad in a box','business','none'),
(636,'en','Even the duck wants that sandwich.','Even the dog wants that sandwich.','a ham and cheese sandwich','a sandwich in a lunchbox','chill','guessing'),
(638,'en','He used way too much sauce!','He used way too much salt!','a plate full of sauce','sauce in a bottle','slang','exaggeration'),
(639,'en','He is frying sausages.','He is frying eggs.','frying sausages in a pan','sausages on a pizza','chill','none'),
(657,'en','She serves noodles like a pro.','She serves pizza like a pro.','to serve a noodle bowl','to serve a tennis ball','slang','none'),
(670,'en','Her shopping is efficient.','Her swimming is efficient.','shopping at the supermarket','shopping for clothes','business','none'),
(698,'en','The smoothie is so purple.','The smoothie is so green.','a thick berry smoothie','a green smoothie','slang','none'),
(712,'en','He is scared of his soda.','He is scared of his sandwich.','a can of orange soda','a glass of cola soda','low_iq','guessing'),
(716,'en','He eats with a soup spoon.','He eats with chopsticks.','eating with a soup spoon','stirring with a soup spoon','chill','none'),
(717,'en','The soup is burning hot!','The soup is ice cold!','hot tomato soup','cold tomato soup','dramatic','exclamation'),
(721,'en','She caused the spilling!','The boy caused the spilling!','spilling a glass of water','spilling a cup of coffee','dramatic','blaming_someone'),
(750,'en','The string holds the box securely.','The string holds the bag securely.','a box tied with string','a guitar string','business','none'),
(752,'en','Sugar saved her coffee!','Milk saved her coffee!','sugar in black coffee','sugar on a cake','dramatic','exaggeration'),
(767,'en','The tea leaves are dancing!','The tea bags are dancing!','pouring mint tea','tea with milk','dramatic','exclamation'),
(777,'en','He is super thirsty!','He is super hungry!','thirsty at the market','thirsty after a run','slang','none'),
(4215,'en','She is in orange and white.','She is in green and white.','orange with white','peeling an orange','chill','none'),
(4655,'en','He is dressing in a suit.','He is dressing in a hoodie.','dressing in a suit','dressing a salad','chill','none'),
(440,'en','He is lifting a barbell!','He is lifting a sofa!','lifting a heavy barbell','lifting a small child','dramatic','exclamation'),
(626,'en','The runner is drinking water.','The runner is eating a banana.','a runner drinking water','a runner on a treadmill','chill','none'),
(797,'en','They are racing on the track!','They are racing in the pool!','a red running track','a train track','dramatic','exclamation'),
(5215,'en','She is cycling by a fjord.','She is cycling in a city.','cycling by the fjord','cycling in the city','chill','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
