begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(45,'en','She is angry at the man!','She is angry at the dog!','an angry woman','angry about the rain','dramatic','exclamation'),
(101,'en','Ugh. She is so bored.','Ugh. He is so bored.','bored of waiting','bored at a party','dramatic','none'),
(187,'en','The instructions confused her.','The map confused her.','confused by the instructions','confused about the date','ironic','blaming_someone'),
(205,'en','Sad film. Both are crying.','Sad film. Both are sleeping.','crying at a sad film','crying at a wedding','dramatic','none'),
(290,'en','What a feeling! Goal!','What a feeling! A red card!','a feeling of joy','a feeling of boredom','dramatic','exclamation'),
(362,'en','She is so happy it''s unreal.','She is so sad it''s unreal.','a happy seaside walk','a happy birthday party','slang','exaggeration'),
(391,'en','The boat is back. Hope wins!','The plane is back. Hope wins!','hope for the boat','hope for good weather','dramatic','exclamation'),
(431,'en','Lazy? No, he is a "genius".','Lazy? No, she is a "genius".','a lazy man at home','a lazy cat at home','ironic','bad_excuse'),
(453,'en','He is lonely in the cafeteria.','He is lonely in the library.','a lonely lunch','a lonely walk home','dramatic','none'),
(628,'en','Her face is full of sadness.','Her face is full of joy.','sadness in an empty shop','sadness at a funeral','dramatic','none'),
(655,'en','Party hats? She stays serious.','Party hats? He stays serious.','a serious face at work','a serious talk at dinner','ironic','understatement'),
(693,'en','Just five more minutes. So sleepy.','Just five more minutes. So awake.','a sleepy night ride','a sleepy morning class','ironic','bad_excuse'),
(695,'en','Soon everyone is smiling.','Soon everyone is crying.','smiling on a ferry','smiling at the camera','chill','none'),
(757,'en','A puppy in a box! What a surprise!','A kitten in a box! What a surprise!','a surprise in a box','a surprise party at home','dramatic','exclamation'),
(828,'en','Hot news? She looks surprised.','Hot news? He looks surprised.','surprised in a cafe','surprised at the door','gossip','guessing'),
(1389,'en','Her tears are falling.','His tears are falling.','a tear on her cheek','a tear in her dress','dramatic','none'),
(1589,'en','This person looks sad.','This person looks happy.','a sad orange-haired figure','a sad blue-haired figure','chill','none'),
(1675,'en','He stands alone by a tree.','He stands alone by a house.','alone in an empty field','alone in an empty room','dramatic','none'),
(2529,'en','He has a gentle face.','He has a gentle dog.','a gentle calm face','a gentle calm sea','chill','none'),
(2765,'en','The baby is smiling.','The baby is crying.','to smile with a flute','to smile at his mother','chill','none'),
(3489,'en','Wine in a boat? She is laughing.','Wine in a car? She is laughing.','to laugh in a boat','to laugh at a boat','gossip','guessing'),
(4036,'en','Big smile for the camera!','Big smile for the dog!','a smile for the photo','a smile for the dentist','dramatic','exclamation'),
(4259,'en','This sheep has a Monday face.','This cow has a Monday face.','an angry sheep face','a happy sheep face','ironic','cliche'),
(4263,'en','Wow! The birds admire her.','Wow! The birds ignore her.','to admire a pink bird','to admire a pink cake','gossip','exclamation'),
(4275,'en','She is complaining about the car.','She is complaining about the bike.','to complain about a crash','to complain about the food','dramatic','none'),
(4316,'en','He is sorry. Tulips will help.','He is sorry. Roses will help.','sorry about the coffee','sorry about the cake','ironic','guessing'),
(4345,'en','Gifts, cake, pure joy!','Gifts, pizza, pure joy!','joy at a birthday party','joy at a wedding party','dramatic','exclamation'),
(4628,'en','Picnic cancelled. He is sad.','Picnic cancelled. She is sad.','sad about the rain','sad about the snow','chill','none'),
(4720,'en','Funny faces and zero shame!','Funny hats and zero shame!','funny faces for the phone','funny faces for the teacher','slang','exaggeration'),
(4724,'en','She can''t stop laughing.','She can''t stop crying.','laughing in a foam pit','laughing in a ball pit','chill','none'),
(4744,'en','She is relaxing on the water.','She is relaxing on the sand.','to relax on salty water','relaxing in a hot bath','chill','none'),
(4757,'en','Summer freedom at last!','Winter freedom at last!','freedom on an open road','freedom in a big city','dramatic','exclamation'),
(4788,'en','Salon gossip. Everyone is shocked.','Salon gossip. Everyone is bored.','shocked by salon gossip','shocked by the price','gossip','exaggeration'),
(4819,'en','The old woman is grateful.','The old man is grateful.','grateful for the umbrella','grateful for the taxi','chill','none'),
(5069,'en','Oh wow! He is enjoying the massage.','Oh wow! He is enjoying the coffee.','to enjoy a neck massage','to enjoy a foot massage','dramatic','exclamation'),
(5110,'en','The park is very quiet.','The beach is very quiet.','a quiet misty park','a quiet misty beach','chill','none'),
(5200,'en','What a lively group!','What a lively dog!','a lively living room','a lively dance club','dramatic','exclamation'),
(5285,'en','Pure happiness in the garden.','Pure happiness in the kitchen.','happiness in a sunny garden','happiness on a sunny beach','chill','none'),
(5362,'en','The silliest glasses on the island!','The silliest hat on the island!','silly heart sunglasses','silly heart balloons','dramatic','exaggeration'),
(5452,'en','A peaceful lake in the mist.','A peaceful beach in the mist.','a peaceful mountain lake','a peaceful mountain village','chill','none'),
(61,'en','Why are they walking backward?','Why are they running backward?','walking backward in a park','falling backward in a park','low_iq','guessing'),
(122,'en','They are waiting forever at the bus stop.','They are waiting forever at the train station.','waiting at a bus stop','waiting at a taxi rank','dramatic','exaggeration'),
(202,'en','Phone down. Now he can cross.','Phone down. Now he can swim.','to cross the street safely','to cross your fingers','low_iq','cliche'),
(246,'en','That driving is so smooth.','That cycling is so smooth.','driving along the coast','driving through the city','flirt','none'),
(301,'en','He is floating on the lake.','He is floating in the pool.','floating on a calm lake','to float in the air','chill','none'),
(339,'en','She is going down the street.','She is going up the stairs.','to go down the street','to go back home','chill','none'),
(368,'en','Delivery by helicopter? Cool!','Delivery by drone? Cool!','a red helicopter delivery','a helicopter on a ship','slang','exclamation'),
(369,'en','He is riding a motorbike.','He is riding a horse.','to ride a sport motorbike','to ride in a car','chill','none'),
(436,'en','Everyone is stepping left.','Everyone is stepping right.','to step to the left','to jump to the left','chill','none'),
(528,'en','She is parking like a pro!','He is parking like a pro!','to park between two cars','to park in a garage','slang','exaggeration'),
(592,'en','Pushing a van? Easy!','Pushing a bus? Easy!','pushing a white van','pushing a white car','ironic','understatement'),
(612,'en','She is pointing to the right.','She is pointing to the sky.','going right past the stalls','turning right at the lights','chill','none'),
(624,'en','She is running after her hat!','She is running after her dog!','to run after a hat','to run after a bus','dramatic','exclamation'),
(837,'en','This taxi fits in any alley.','This bus fits in any alley.','a taxi in an alley','a taxi at the airport','ironic','exaggeration'),
(843,'en','Higher! The basket is going up!','Higher! The bucket is going up!','to pull a basket up','to pull a boat up','dramatic','exclamation'),
(851,'en','She is waiting. And waiting.','She is dancing. And dancing.','to wait for the bus','to wait for a taxi','low_iq','exaggeration'),
(853,'en','She is walking in the park.','She is running in the park.','to walk by the lake','to walk the dog','chill','none'),
(895,'en','Big jam. Maybe an accident?','Big party. Maybe an accident?','an accident on the highway','an accident in the kitchen','dramatic','guessing'),
(942,'en','He is riding a bicycle.','He is riding a scooter.','a bicycle in autumn','a bicycle in the snow','chill','none'),
(981,'en','Green car, sea view, pure style.','Green car, city view, pure style.','a green classic car','a green family car','flirt','exaggeration'),
(1203,'en','His motorbike is sparking!','His scooter is sparking!','a motorbike in a curve','a motorbike in a garage','dramatic','exclamation'),
(1303,'en','What a stylish scooter ride!','What a stylish bicycle ride!','a scooter in Italy','a scooter on the beach','flirt','exaggeration'),
(1355,'en','Hands on the steering wheel.','Hands on the phone.','hands on the steering wheel','a boat''s steering wheel','chill','none'),
(1371,'en','The subway train is super fast.','The subway train is super slow.','a subway train rushing past','a subway map','slang','exaggeration'),
(1411,'en','Old tram, big smile, great style.','Old bus, big smile, great style.','an old green tram','an old green bus','flirt','none'),
(1415,'en','He is climbing into his truck.','He is climbing into his car.','a big silver truck','a big silver bus','chill','none'),
(1751,'en','Each sign shows a landscape.','Each sign shows a city.','arrow signs with landscapes','arrow signs with prices','chill','none'),
(1780,'en','A dog is chasing his bike!','A cat is chasing his bike!','a bike ride downhill','a bike ride uphill','dramatic','exclamation'),
(2084,'en','A train on a wet railway.','A train on a dry railway.','a railway at night','a railway in the desert','chill','none'),
(2172,'en','A sports car in a paint storm.','A sports car in a snow storm.','a dark-blue sports car','a dark-blue family car','dramatic','exaggeration'),
(2237,'en','Look at this shiny yellow car!','Look at this shiny red car!','a shiny yellow car','a shiny yellow bus','slang','exclamation'),
(2312,'en','A race car by the palm trees.','A race car by the pine trees.','a red race car','a red race horse','chill','none'),
(2351,'en','Someone is driving a green car.','Someone is driving a yellow car.','to drive through autumn','to drive through the snow','chill','none'),
(2356,'en','The road leads toward a planet.','The road leads toward a castle.','toward a huge planet','toward a huge city','dramatic','none'),
(2360,'en','That red car looks crazy fast.','That red van looks crazy fast.','a fast red car','a fast red boat','slang','exaggeration'),
(2367,'en','This car is a little dirty.','This bus is a little dirty.','an old dirty sports car','a dirty old bus','ironic','understatement'),
(2375,'en','Half grey, half yellow. It cannot decide.','Half grey, half green. It cannot decide.','half a yellow car','half a yellow bus','low_iq','guessing'),
(2656,'en','Two red buses. Very London.','Two red trams. Very London.','a red double-decker bus','a red double-decker tram','slang','cliche'),
(3057,'en','He is walking in the park.','He is running in the park.','to walk along a path','to walk along a beach','chill','none'),
(3266,'en','She is riding along the bay.','She is riding along the river.','to ride along the sea','to ride along the tracks','chill','none'),
(4018,'en','Two dogs are on a scooter!','Two cats are on a scooter!','dogs on a green scooter','dogs on a green bicycle','dramatic','exclamation'),
(4022,'en','Just a little walk on a flying plane.','Just a little walk on a moving train.','to fly over a city','to fly over the sea','ironic','understatement'),
(4028,'en','The bulldog is turning like a pro!','The bulldog is jumping like a pro!','to turn on a skateboard','to turn on the TV','slang','exaggeration'),
(4035,'en','He is stepping over the water.','He is stepping over the fire.','stepping onto floating blocks','stepping onto a moving train','chill','none'),
(4092,'en','He is riding down the steps!','He is riding up the steps!','down the cliff steps','down the ski slope','dramatic','exclamation'),
(4097,'en','He is riding super fast.','He is riding super slowly.','to ride fast downhill','to fast before dinner','slang','exaggeration'),
(4099,'en','The dog is back on top!','The cat is back on top!','back on the mattresses','back on the sofa','dramatic','exclamation'),
(4147,'en','He is hurrying. Why that sign?','He is sleeping. Why that sign?','to hurry to the car','to hurry to the bus','gossip','guessing'),
(4153,'en','A blue car on the highway.','A red car on the highway.','a highway to the mountains','a highway to the sea','chill','none'),
(4159,'en','So high above the valley!','So high above the city!','high above the valley','high above the clouds','dramatic','exclamation'),
(4160,'en','Poof! The red car disappeared.','Poof! The red van disappeared.','to disappear in the sand','to disappear in the snow','slang','exaggeration'),
(4164,'en','The brake is big and red.','The brake is big and blue.','a big red brake','a big red button','chill','none'),
(4165,'en','The trees blur at this speed.','The houses blur at this speed.','speed on a mountain road','speed on a race track','dramatic','none'),
(4166,'en','He is entering that red car like a star.','He is entering that blue car like a star.','entering a red sports car','entering a red phone box','flirt','exaggeration'),
(4194,'en','What a ride in a tiny jeep!','What a ride in a tiny boat!','a toy jeep ride','a toy boat ride','dramatic','exclamation'),
(4231,'en','Two dogs behind the window? Suspicious.','Two cats behind the window? Suspicious.','a foggy truck window','a foggy bathroom window','gossip','guessing'),
(4352,'en','She is making a sharp turn.','She is making a sharp jump.','a sharp turn on skis','a wrong turn on skis','chill','none'),
(4397,'en','He is biking in Amsterdam.','He is biking in the forest.','to bike along a canal','to bike along a beach','chill','none'),
(4463,'en','The driver is welcoming them.','The pilot is welcoming them.','welcoming people on a bus','welcoming people on a plane','chill','none'),
(4587,'en','No way! The cyclist is surprised.','No way! The cyclist is sleeping.','a cyclist at a junction','a cyclist at a race','dramatic','exclamation'),
(4603,'en','The road winds through hills.','The road winds through a city.','a winding mountain road','a winding mountain river','chill','none'),
(4658,'en','She is driving by the sea.','She is driving by a lake.','to drive along the coast','to drive along a river','chill','none'),
(4659,'en','All these people are in cars.','All these people are on bikes.','people in their cars','people in their beds','chill','none'),
(4675,'en','He is not careful at all!','She is not careful at all!','not careful on a bridge','careful with the tulips','dramatic','understatement'),
(4689,'en','A whale next to the boat!','A shark next to the boat!','a whale by the boat','a dolphin by the boat','dramatic','exclamation'),
(4723,'en','People are falling into foam.','People are falling into water.','falling into a foam pit','falling into a pool','chill','none'),
(4830,'en','Two divers are swimming up.','Three divers are swimming up.','swimming up to the surface','to swim across the river','chill','none'),
(4839,'en','He can move a car alone!','He can move a bus alone!','moving heavy things','moving to a new city','dramatic','exaggeration'),
(4875,'en','The team is loading the truck.','The team is loading the boat.','a truck full of boxes','a truck full of sand','business','none'),
(4881,'en','People are pushing a bus!','People are pushing a train!','pushing a city bus','catching a city bus','dramatic','exclamation'),
(4894,'en','Everyone is still. Very normal.','Everyone is dancing. Very normal.','still students in a hall','still water in a lake','ironic','understatement'),
(4916,'en','We made it! Two bicycles, one sunset.','We made it! Two scooters, one sunset.','bicycles on a pier','bicycles on a train','dramatic','exclamation'),
(4933,'en','One hand stays on the wheel.','One hand stays on the phone.','a bus steering wheel','a bus spare wheel','business','none'),
(4951,'en','He is home, and the dog is happy!','He is home, and the cat is happy!','coming home to the dog','leaving home for work','dramatic','exclamation'),
(5004,'en','The kangaroo is springing forward.','The kangaroo is springing backward.','to spring across the sand','to spring out of bed','chill','none'),
(5032,'en','She is leading the team ahead.','She is leading the team back.','walking ahead of the group','planning ahead for the trip','business','none'),
(5063,'en','The column is moving in order.','The crowd is moving in order.','a column of marching ranks','a column in a newspaper','business','none'),
(5091,'en','The small motorbike is green.','The small motorbike is red.','a green motorbike in town','a green motorbike for sale','chill','none'),
(5138,'en','She is on the train now.','She is on the bus now.','a seat on the train','a seat on the plane','chill','none'),
(5145,'en','The tram is right behind him.','The bus is right behind him.','a tram on the square','a tram on a bridge','chill','none'),
(5265,'en','The ship carries containers.','The ship carries cars.','a ship with containers','a truck with containers','chill','none'),
(5430,'en','She is fast on her road bike.','She is fast on her skateboard.','a fast ride through tunnels','a fast ride through town','chill','none'),
(92,'en','One blanket, two people.','One blanket, three people.','sharing a big blanket','sharing a big pizza','flirt','understatement'),
(136,'en','Candlelight for two? So cute.','Lamplight for two? So cute.','a candle on the table','a candle on a cake','flirt','none'),
(140,'en','Their new carpet is so soft!','Their new sofa is so soft!','a soft green carpet','a soft green blanket','dramatic','exclamation'),
(152,'en','Best chair ever! Full circle!','Best sofa ever! Full circle!','a new swivel chair','a new rocking chair','slang','exaggeration'),
(175,'en','They are hanging a clock.','They are hanging a picture.','a round kitchen clock','a round kitchen table','chill','none'),
(225,'en','Her desk is ready. The cat agrees.','Her desk is ready. The dog agrees.','a clean desk for work','a clean desk for dinner','ironic','guessing'),
(395,'en','Best house in the whole world!','Best car in the whole world!','moving into a yellow house','moving into a white house','slang','exaggeration'),
(443,'en','Finally, light in the attic!','Finally, light in the kitchen!','light through the window','light from a candle','dramatic','exclamation'),
(911,'en','A bright, sunny apartment.','A dark, gloomy apartment.','a bright modern apartment','a bright modern office','chill','none'),
(914,'en','He loves this armchair!','He loves this sofa!','flopping into an armchair','flopping into a pool','dramatic','exclamation'),
(927,'en','She is shaking a rug on the balcony.','She is shaking a towel on the balcony.','a rug over the balcony','a plant on the balcony','chill','none'),
(934,'en','Splash! She is in the bathtub.','Splash! She is in the pool.','splashing in a bathtub','splashing in a puddle','slang','exclamation'),
(938,'en','She is making the bed.','She is making a cake.','to make the bed','to go to bed','chill','none'),
(939,'en','Pillow up! Bedroom party!','Pillow up! Kitchen party!','a bright messy bedroom','a bright messy kitchen','slang','exclamation'),
(1022,'en','This cushion lost the fight.','This sofa lost the fight.','to fluff a cushion','to sit on a cushion','ironic','exaggeration'),
(1123,'en','Her hallway is a dance floor!','Her kitchen is a dance floor!','dancing down a hallway','running down a hallway','slang','exclamation'),
(1166,'en','She is moving a big lamp.','She is moving a big plant.','a lamp for the table','a lamp for the garden','chill','none'),
(1175,'en','Popcorn is flying all over the living room.','Popcorn is flying all over the kitchen.','friends in a living room','friends in a waiting room','slang','exaggeration'),
(1242,'en','She is hanging a picture.','She is hanging a mirror.','a picture on the wall','a picture on her phone','chill','none'),
(1287,'en','An empty room? Time to dance!','An empty shop? Time to dance!','an empty sunny room','an empty sunny beach','slang','exclamation'),
(1337,'en','They are playing on the sofa.','They are playing on the floor.','friends on a grey sofa','friends on a grey bus','chill','none'),
(1638,'en','Curtains frame a moonlit sea.','Curtains frame a sunny sea.','heavy purple curtains','heavy purple carpets','dramatic','none'),
(1990,'en','A super comfortable armchair.','A super comfortable sofa.','a comfortable golden armchair','a comfortable golden bed','slang','none'),
(5404,'en','He is so greedy with toast!','He is so greedy with cake!','a greedy toast eater','a greedy cake eater','dramatic','exclamation'),
(5347,'en','Traffic is coming to a stop.','Trains are coming to a stop.','a stop for the traffic','a stop for a coffee','chill','none'),
(1812,'en','The cat is looking out too.','The dog is looking out too.','looking out of the window','to look after a cat','chill','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
