begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(2053,'en','Bottles fill every shelf.','Books fill every shelf.','shelves of old bottles','shelves of old books','chill','none'),
(2056,'en','The shelves are full of books.','The shelves are full of jars.','shelves full of old books','shelves full of old toys','chill','none'),
(2073,'en','Look, the sun is shining in!','Look, the moon is shining in!','sunlight shining in','moonlight shining in','dramatic','exclamation'),
(2079,'en','Everything here is wooden.','Everything here is plastic.','tall wooden bookcases','tall wooden ladders','low_iq','exaggeration'),
(2809,'en','She is holding a small teacup.','She is holding a small teapot.','a teacup in both hands','a teacup on a saucer','chill','none'),
(3064,'en','She is opening the curtains!','She is closing the curtains!','opening the curtains','opening the front door','dramatic','exclamation'),
(3779,'en','The poor toy is all alone.','The poor dog is all alone.','an old toy rabbit','an old toy car','dramatic','exaggeration'),
(4083,'en','A "small" pug took the middle.','A "small" cat took the middle.','the middle of the bed','the middle of the sofa','ironic','understatement'),
(4129,'en','The puppy is leaving home.','The puppy is coming home.','leaving home in a hat','coming home in a hat','chill','none'),
(4221,'en','The lizard is chilling on the couch.','The lizard is chilling on the table.','cereal on the couch','cereal on the kitchen table','slang','none'),
(4386,'en','Posters cover his whole room.','Maps cover his whole room.','walls covered in posters','posters on the fridge','chill','exaggeration'),
(4387,'en','We compare three bedrooms.','We compare three kitchens.','comparing three bedrooms','comparing three kitchens','business','none'),
(4674,'en','He is dusting the shelves.','He is painting the shelves.','dusting the shelves','building the shelves','chill','none'),
(4738,'en','Her clothes are everywhere!','Her books are everywhere!','clothes everywhere','passports everywhere','dramatic','exclamation'),
(4764,'en','She is going wild on the sofa.','She is going wild on the bed.','jumping on the sofa','sleeping on the sofa','slang','exaggeration'),
(4828,'en','Half the wall is green now.','Half the wall is blue now.','a half-green wall','a green garden wall','business','none'),
(4837,'en','The table is full of food.','The table is full of books.','a table full of food','a table full of games','chill','none'),
(4847,'en','What a clean floor!','What a dirty floor!','mopping the floor','painting the floor','dramatic','exclamation'),
(4952,'en','He missed his bed so much.','He missed his car so much.','dropping onto the bed','making the bed','dramatic','guessing'),
(4965,'en','The bathroom routine is done.','The kitchen routine is done.','brushing teeth in the bathroom','singing in the bathroom','business','none'),
(5047,'en','Nobody is leaving the living room tonight.','Nobody is leaving the kitchen tonight.','a cosy living room','cleaning the living room','gossip','guessing'),
(5151,'en','The frame is silver.','The frame is gold.','a silver picture frame','a silver window frame','chill','none'),
(5152,'en','Her bedroom is all pillows!','Her bedroom is all books!','pillows in the bedroom','pillows in the living room','dramatic','exaggeration'),
(5218,'en','She is checking every room.','She is cleaning every room.','a room with arched windows','a room with a fireplace','chill','none'),
(5263,'en','A photograph is on the shelf.','A mirror is on the shelf.','a framed family photograph','taking a family photograph','chill','none'),
(331,'en','A gentleman is saving the oranges!','A gentleman is saving the apples!','a gentleman with an umbrella','a gentleman with a dog','dramatic','exclamation'),
(333,'en','This girl can do everything!','This boy can do everything!','a girl skipping rope','a girl skipping school','dramatic','exaggeration'),
(458,'en','A big man is carrying a crate.','A big man is carrying a dog.','men playing chess','men playing cards','chill','none'),
(744,'en','She met a stranger with an umbrella.','She met a stranger with a big dog.','a stranger with an umbrella','a stranger with a bike','gossip','none'),
(1120,'en','This guy is tossing his keys, so cool.','This guy is tossing his phone, so cool.','a guy with a pizza','a guy with a guitar','slang','none'),
(1133,'en','The helper has her bag.','The helper has her dog.','a helper with her bag','a helper in the kitchen','chill','none'),
(1163,'en','The lady has white gloves on.','The lady has black gloves on.','a lady on the stairs','a lady at the bar','chill','none'),
(1183,'en','A male athlete is rowing.','A female athlete is rowing.','a male rower','a male swimmer','chill','none'),
(1235,'en','People are cheering!','People are crying!','people cheering at night','people cheering in a stadium','dramatic','exclamation'),
(1237,'en','Such a "busy" crossing: one person.','Such a "busy" crossing: one dog.','one person on the crosswalk','one person on the bus','ironic','understatement'),
(1321,'en','Here is your dish, sir.','Here is your bill, sir.','your dish, sir','your bill, sir','business','none'),
(1340,'en','Somebody is leaving in secret.','Somebody is dancing in secret.','somebody walking away','somebody walking a dog','gossip','guessing'),
(1519,'en','Her flowers are so pretty.','Her feathers are so pretty.','pretty flowers in her hair','pretty ribbons in her hair','flirt','none'),
(1562,'en','The cowboy is riding into the sunset.','The cowboy is riding into the sea.','a cowboy on a horse','a cowboy on a bull','dramatic','cliche'),
(1669,'en','Two wings, but the statue can''t fly.','Four wings, but the statue can''t fly.','two feathered wings','two plane wings','low_iq','understatement'),
(1734,'en','This superhero is Spider-Man.','This superhero is Batman.','a superhero in a mask','a superhero with a cape','chill','none'),
(1892,'en','The old man has a thin stick.','The old man has an umbrella.','the old man''s stick','the old man''s umbrella','chill','none'),
(2088,'en','The handsome man has a beard.','The handsome man has glasses.','a handsome bearded man','a handsome man with glasses','flirt','none'),
(2232,'en','The Buddha looks peaceful.','The Buddha looks angry.','a peaceful golden Buddha','a peaceful golden temple','chill','none'),
(2326,'en','The prince has cool blue hair.','The prince has cool pink hair.','a prince with a crown','a prince on a horse','slang','none'),
(2345,'en','What a long wizard beard!','What a short wizard beard!','an old wizard in grey','an old wizard in red','dramatic','exclamation'),
(2365,'en','His metal suit is so shiny.','His metal suit is so dirty.','a red metal suit','a red metal car','slang','none'),
(2497,'en','Santa Claus is taking a break.','Santa Claus is taking a bath.','Santa Claus with presents','Santa Claus with reindeer','gossip','guessing'),
(3003,'en','The crowd has its hands up.','The crowd has its hands down.','a crowd with hands up','a crowd in a stadium','chill','none'),
(3724,'en','The woman''s dress is bright.','The woman''s dress is black.','a woman in bright colours','a woman in dark colours','chill','none'),
(4110,'en','The clown did not expect a tiger!','The clown did not expect a lion!','the clown''s orange wig','the clown''s purple wig','dramatic','guessing'),
(4276,'en','An elderly lady is going home.','An elderly man is going home.','an elderly woman walking','an elderly woman dancing','chill','none'),
(4311,'en','Even grandma plays with the young man.','Even grandpa plays with the young man.','a young basketball player','a young tennis player','gossip','none'),
(4430,'en','The kid is so happy!','The kid is so sad!','a kid running fast','a kid sitting still','dramatic','exclamation'),
(4451,'en','Two teenagers are gaming, so intense.','Two teenagers are dancing, so intense.','teenagers playing a game','teenagers playing football','slang','exaggeration'),
(4487,'en','What a kind guy!','What a lazy guy!','a kind young man','a kind of pancake','flirt','exclamation'),
(4709,'en','The whole group is cheering!','The whole group is crying!','a group in matching hats','a group in matching shirts','dramatic','none'),
(4776,'en','So polite: he is lifting his hat.','So polite: he is lifting his cane.','a polite greeting','a polite letter','flirt','none'),
(4777,'en','He is helpful to everyone.','He is rude to everyone.','a helpful old gentleman','a helpful young waiter','chill','none'),
(4884,'en','Everybody is pointing up!','Everybody is pointing down!','pointing at the sky','pointing at a map','dramatic','exclamation'),
(5009,'en','The child is sliding down.','The child is climbing up.','a child on a slide','a child on a swing','chill','none'),
(5011,'en','The old couple is kissing, how cute!','The old couple is dancing, how cute!','an old couple kissing','an old couple dancing','gossip','exclamation'),
(5021,'en','Such an elegant lady pouring tea.','Such an elegant lady pouring wine.','a lady in a bonnet','a lady on a horse','flirt','none'),
(5031,'en','The leader is pointing ahead.','The leader is sitting down.','a leader on a mountain','a leader on a beach','chill','none'),
(5092,'en','Our helper moves boxes like a pro.','Our helper moves plants like a pro.','a helper with a box','a helper with a lamp','slang','exaggeration'),
(5147,'en','So many people are crossing!','So many cars are crossing!','people filling the crossing','people waiting for a bus','dramatic','exclamation'),
(5180,'en','The speaker is at the lectern.','The speaker is at the piano.','a speaker at a lectern','a speaker in the audience','business','none'),
(5186,'en','The public is in the square.','The public is in the church.','the public in the square','the public in the theatre','chill','none'),
(5253,'en','These seniors dance better than me.','These seniors swim better than me.','senior dancers in the park','senior swimmers in the pool','slang','exaggeration'),
(5281,'en','The star is singing on stage.','The star is dancing on stage.','a star on stage','a star in the sky','chill','none'),
(5305,'en','Their society is hard at work.','Their society is on holiday.','a whole society at work','a society at a party','business','none'),
(5390,'en','A youth is skating, so cool.','A youth is cycling, so cool.','a youth on a skateboard','a youth on a bicycle','slang','none'),
(5398,'en','People form a human chain.','People form a human tower.','a human chain around Earth','a gold chain necklace','chill','none'),
(5499,'en','A woman in red is spinning.','A woman in red is jogging.','a woman watering her flowers','a woman buying flowers','chill','none'),
(10,'en','A leaf is a free umbrella!','A leaf is a free blanket!','a giant green leaf','a giant green frog','low_iq','cheap_quality'),
(123,'en','A bird flew out of the bush!','A cat jumped out of the bush!','picking from the bushes','hiding behind the bushes','dramatic','exclamation'),
(141,'en','This carrot can feed a horse.','This potato can feed a horse.','a giant carrot','a giant potato','low_iq','exaggeration'),
(303,'en','She is giving you a flower.','She is giving you a cookie.','a pretty pink flower','a pretty pink dress','flirt','none'),
(326,'en','Her garden has everything!','Her garden has a pool!','a garden at sunset','a garden at night','dramatic','exaggeration'),
(327,'en','Gardening is teamwork here.','Cooking is teamwork here.','gardening in a raised bed','gardening on a balcony','business','none'),
(351,'en','They''re chilling on the grass.','They''re chilling on the sand.','lying on the soft grass','cutting the soft grass','slang','none'),
(426,'en','She is climbing; he is just holding the ladder.','She is climbing; he is just holding the basket.','holding the ladder steady','painting the ladder','gossip','banter'),
(489,'en','The mushroom has white spots.','The mushroom has black spots.','a red mushroom with spots','a red mushroom soup','chill','none'),
(555,'en','The plant has a new leaf!','The plant has a new flower!','a plant with big leaves','a plant with red flowers','dramatic','exclamation'),
(567,'en','Goldfish live in this pond.','Frogs live in this pond.','goldfish in the pond','ducks on the pond','chill','none'),
(572,'en','They found a lot of potatoes!','They found a lot of carrots!','digging up potatoes','peeling potatoes','dramatic','exclamation'),
(620,'en','This rose smells like heaven.','This tulip smells like heaven.','smelling a pink rose','buying a pink rose','dramatic','cliche'),
(621,'en','The row is perfectly straight.','The row is perfectly round.','planting in a straight row','sitting in the front row','business','none'),
(696,'en','He is lost in the smoke!','He is lost in the snow!','a cloud of grey smoke','smoke from a chimney','dramatic','exaggeration'),
(867,'en','The basil likes the watering.','The rose likes the watering.','watering the tomatoes','watering the lawn','chill','guessing'),
(885,'en','The worm is going underground.','The worm is going up a tree.','a worm in the soil','a worm on a hook','chill','none'),
(957,'en','A robin sits on the branch.','An owl sits on the branch.','a swing on a branch','a swing in the park','chill','none'),
(973,'en','A bird landed on the cactus.','A bee landed on the cactus.','a bird on a cactus','a cactus in a pot','chill','none'),
(1543,'en','She is holding a big cabbage.','She is holding a big pumpkin.','a garden full of cabbages','a cabbage in a pot','chill','none'),
(1559,'en','Sunflowers fill a yellow vase.','Roses fill a yellow vase.','sunflowers in a vase','sunflowers in a field','chill','none'),
(1847,'en','I count three Christmas trees.','I count five Christmas trees.','three little Christmas trees','a Christmas tree with gifts','low_iq','none'),
(1862,'en','The vase has pink roses.','The vase has white roses.','a grey classical vase','a broken classical vase','chill','none'),
(1966,'en','The path is made of stones.','The path is made of wood.','a cobblestone path','a forest path','chill','none'),
(1985,'en','The tree is bright red!','The tree is bright green!','bright red leaves','bright red apples','dramatic','exclamation'),
(2012,'en','Flowers cover the entrance.','Snow covers the entrance.','a garden entrance with flowers','a hotel entrance with flowers','chill','none'),
(2091,'en','The pine tree stands alone.','The palm tree stands alone.','a frosty pine tree','a pine tree with lights','dramatic','none'),
(2113,'en','The flowers are bright yellow.','The flowers are bright purple.','a dove on yellow flowers','yellow flowers in a vase','chill','none'),
(2327,'en','This car and the palm trees look so cool.','This bike and the palm trees look so cool.','palm trees at sunset','palm trees on an island','slang','none'),
(2358,'en','The farm has red roofs.','The farm has blue roofs.','a farm on a hillside','a farm with cows','chill','none'),
(2483,'en','Dried flowers lie in the book.','Fresh flowers lie in the book.','dried flowers in a book','dried fruit in a bowl','chill','none'),
(2651,'en','The red roof has white spots.','The red roof has black spots.','a cap with white spots','a dog with white spots','chill','none'),
(2666,'en','Flowerpots line the steps.','Candles line the steps.','flowerpots on stone steps','flowerpots on a windowsill','chill','none'),
(2693,'en','A tree is growing from a book!','A tree is growing from a cup!','growing out of a book','growing out of a pot','dramatic','exclamation'),
(2915,'en','The team is planting flowers.','The team is picking flowers.','planting orange flowers','picking orange flowers','business','none'),
(4128,'en','The puppy loves this yard.','The kitten loves this yard.','a puppy in the yard','a puppy in the street','chill','guessing'),
(4269,'en','The dry soil is drinking fast.','The dry sand is drinking fast.','watering dry soil','sweeping dry leaves','dramatic','exaggeration'),
(4413,'en','She loves the smell.','She hates the smell.','the smell of blossoms','the smell of coffee','chill','none'),
(4613,'en','He is turning the dark earth.','He is turning the white sand.','turning the dark earth','digging in the sand','chill','none'),
(4766,'en','She loves to garden.','She loves to swim.','to garden among flowers','to garden in the rain','chill','none'),
(4814,'en','The team is picking tomatoes.','The team is picking apples.','picking a red tomato','picking a red apple','business','none'),
(4848,'en','Look what she grew: a pumpkin!','Look what she grew: a melon!','growing a big pumpkin','growing a long beard','dramatic','exclamation'),
(5153,'en','The team is planting the bed.','The team is painting the bed.','a raised garden bed','an unmade bed','business','none'),
(5308,'en','A man brings her sunflowers.','A man brings her roses.','a bunch of sunflowers','a field of sunflowers','chill','none'),
(5329,'en','The seed has a tiny root!','The seed has a tiny flower!','a seed with a root','a seed in a beak','dramatic','exclamation'),
(5486,'en','He is watering the flowerpot.','He is painting the flowerpot.','a flowerpot on the windowsill','a broken flowerpot','chill','none'),
(1,'en','His "short" break is too long.','His "short" run is too long.','a short phone break','a short coffee break','ironic','understatement'),
(3,'en','Her class is crazy!','Her class is sleeping!','a class out of control','a class trip abroad','dramatic','exclamation'),
(4,'en','She has an online course.','She has an online meeting.','an online course at home','a cooking course at school','business','none'),
(11,'en','This library is huge!','This library is tiny!','a huge old library','a small school library','dramatic','exaggeration'),
(19,'en','He found a ruler at last!','He found a pencil at last!','drawing with a ruler','drawing with a compass','dramatic','exclamation'),
(21,'en','Welcome to my school, bro.','Welcome to my office, bro.','a tour of my school','a tour of my office','slang','none'),
(22,'en','The scientist loves charts.','The student loves charts.','a scientist with a clipboard','a scientist with a microscope','gossip','guessing'),
(27,'en','This student ices her coffee.','This student heats her coffee.','a student with cold coffee','a student with hot soup','chill','none'),
(28,'en','School offers many subjects.','School offers two subjects.','many school subjects','the subject of an email','business','none'),
(29,'en','Her telescope shows a meteor!','Her telescope shows a rocket!','a telescope on a tripod','a telescope on a ship','dramatic','exclamation'),
(30,'en','This textbook never ends.','This movie never ends.','a very thick textbook','a very thin textbook','dramatic','exaggeration'),
(31,'en','Week five: the university is empty.','Week five: the university is full.','an empty university hall','an empty university library','gossip','none'),
(42,'en','This exam is too hard for him.','This exam is too easy for him.','giving up on the exam','passing the exam','dramatic','none'),
(129,'en','Five plus three? He needs a calculator.','Nine plus nine? He needs a calculator.','a big desk calculator','a calculator on a phone','ironic','understatement'),
(171,'en','The boy is correct, the girl is not.','The girl is correct, the boy is not.','a correct answer','a correct spelling','gossip','none'),
(270,'en','Her eraser became a mountain!','Her eraser became a flower!','a tiny mountain eraser','a tiny mountain house','dramatic','exclamation'),
(388,'en','Her homework never ends.','Her holiday never ends.','homework late at night','homework on the bus','dramatic','exaggeration'),
(404,'en','Chaos in the classroom, but he is calm.','Chaos in the kitchen, but he is calm.','a noisy classroom','a quiet classroom','gossip','understatement'),
(538,'en','His pen has many colours.','His pen has one colour.','a pen with many colours','a pen with a light','chill','none'),
(541,'en','Her pencil drawing is so good.','Her pen drawing is so good.','drawing with a yellow pencil','sharpening a yellow pencil','flirt','none'),
(576,'en','She prays for a good grade.','She prays for a new phone.','praying for a good grade','praying in a church','dramatic','none'),
(646,'en','Science makes orange foam!','Science makes blue foam!','a science experiment','a science museum','dramatic','exclamation'),
(662,'en','The sharpener works perfectly.','The sharpener works badly.','a small pencil sharpener','a small knife sharpener','business','none'),
(4329,'en','They are sitting on furniture.','They are sitting on the floor.','sitting on soft furniture','carrying the furniture','chill','none'),
(5306,'en','So comfortable on one sofa!','So comfortable on one bed!','comfortable on a full sofa','comfortable in a big bed','dramatic','exclamation'),
(1585,'en','There are five white roses.','There are five red roses.','five white rose blossoms','white roses in a vase','chill','none'),
(3644,'en','He is watering a tiny plant.','He is watering a tall tree.','watering a tiny seedling','watering a big garden','chill','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
