begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(5287,'en','Fifteen girls, zero silence!','Fifteen boys, zero silence!','a room without silence','a minute of silence','dramatic','exaggeration'),
(5318,'en','She is speaking to the public.','She is singing to the public.','speaking into a microphone','speaking on the phone','business','none'),
(5348,'en','She is thanking the man with the umbrella.','She is thanking the man with the dog.','to thank a kind stranger','to thank the bus driver','chill','none'),
(5381,'en','Coffee and a big conversation.','Beer and a big conversation.','a conversation over coffee','a conversation by email','chill','none'),
(5382,'en','Everyone at the table is discussing it at once!','Everyone on the bus is discussing it at once!','discussing at a cafe table','discussing it by phone','dramatic','exaggeration'),
(5457,'en','The visitors brought a cake.','The visitors brought a dog.','visitors with a cake','visitors at a museum','chill','none'),
(5495,'en','A rumor in the library!','A rumor in the kitchen!','passing on a rumor','starting a rumor online','dramatic','exclamation'),
(5506,'en','Literally everyone came to this dance.','Literally nobody came to this dance.','a street dance at sunset','a dance class at school','slang','exaggeration'),
(342,'en','Goggles on, super tight!','Helmet on, super tight!','blue swim goggles','ski goggles in the snow','slang','exclamation'),
(370,'en','The red helmet did its job.','The blue helmet did its job.','a red skate helmet','a helmet on a motorbike','chill','understatement'),
(401,'en','Nice stop on those ice skates.','Nice stop on that snowboard.','lacing up ice skates','ice skates on a shelf','flirt','none'),
(597,'en','Cool trick with the racket.','Cool trick with the bottle.','a black tennis racket','a racket for badminton','slang','none'),
(617,'en','She came on rollerblades just to take his drink!','She came on a bike just to take his drink!','purple rollerblades in a park','rollerblades on an ice rink','dramatic','exaggeration'),
(707,'en','Cool orange snowboard, dude.','Cool blue snowboard, dude.','strapping on a snowboard','a snowboard in a shop','slang','none'),
(756,'en','Nice ride on that surfboard.','Nice ride on that jet ski.','waxing a white surfboard','a surfboard in a shop','flirt','none'),
(1048,'en','That dumbbell is super heavy.','That dumbbell is super light.','curling a heavy dumbbell','a dumbbell on the floor','slang','exaggeration'),
(1917,'en','A helmet designed for speed.','A helmet designed for cycling.','a helmet built for speed','speed on a bicycle','business','none'),
(2060,'en','Red and yellow skis, so cool.','Blue and white skis, so cool.','skis standing in the snow','skis on a car roof','slang','none'),
(3357,'en','A tall chair by the net.','A tall ladder by the net.','a net across the court','a net for fishing','chill','none'),
(4033,'en','First try with a golf club!','First try with a hockey stick!','swinging a golf club','a golf club for members','dramatic','exclamation'),
(4288,'en','She is focusing on the target.','She is focusing on the camera.','three round targets','a target on a wall','business','none'),
(4304,'en','He threw the football, nice.','He kicked the football, nice.','an oval football mid-air','a round football on grass','slang','none'),
(5267,'en','Her gun is resting on a stand.','Her gun is resting on a chair.','a gun on a stand','a gun in a holster','business','none'),
(5288,'en','He is flying down on his skis!','He is flying down on his sled!','carving on skis','skis leaning on a wall','dramatic','exaggeration'),
(5293,'en','The ball is in his glove now.','The ball is in his cap now.','a leather baseball glove','a glove for the winter','chill','none'),
(112,'en','The little girl is brave, her parents not so much.','The little boy is brave, his parents not so much.','a brave little girl','a brave knight in armour','chill','understatement'),
(381,'en','He is too scared to eat a grape.','He is too scared to eat an apple.','to scare a friend','to scare birds away','low_iq','guessing'),
(498,'en','So nervous before the show!','So nervous before the exam!','a nervous guitar player','a nervous student before exams','dramatic','exclamation'),
(629,'en','Safe inside, storm outside.','Safe inside, sun outside.','safe in a mountain hut','a safe on the wall','chill','cliche'),
(644,'en','Who''s there? She is scared!','Who''s there? He is scared!','scared in a parking garage','scared on a roller coaster','dramatic','exclamation'),
(1641,'en','A scary clown and a crow.','A scary clown and a cat.','scary eyes in the sky','a scary movie night','chill','none'),
(1658,'en','Dark stone, red roses, cool.','Dark stone, white roses, cool.','a dark gothic archway','a dark forest path','slang','none'),
(1781,'en','Halloween every day in this house.','Halloween every day in this castle.','a Halloween haunted house','a Halloween party at school','chill','exaggeration'),
(1788,'en','A sea monster with passengers!','A sea turtle with passengers!','a sea monster rising','a monster under the bed','dramatic','exclamation'),
(1921,'en','A shocked face by the water.','A shocked face in the forest.','a shocked, screaming face','shocked by the phone bill','chill','none'),
(2038,'en','She is afraid, and the birds know it.','She is afraid, and the wolves know it.','afraid in a dark forest','afraid of a big dog','dramatic','guessing'),
(2314,'en','The ghost''s costume: one old sheet.','The ghost''s costume: one old towel.','a white sheet ghost','a ghost in a castle','low_iq','cheap_quality'),
(2425,'en','A black cat in a spooky frame!','A white cat in a spooky frame!','a frame with black roses','a frame for a bicycle','dramatic','exclamation'),
(2964,'en','She is breathing, eyes closed.','She is sleeping, eyes closed.','breathing in the dark','breathing on a window','chill','none'),
(3809,'en','A life ring will help!','A life jacket will help!','reaching up for help','help with homework','dramatic','exclamation'),
(4075,'en','Sharks all around: danger? What danger?','Dolphins all around: danger? What danger?','danger all around her','danger on the road','dramatic','understatement'),
(4729,'en','The mask made them afraid!','The clown made them afraid!','afraid in a haunted house','afraid of a spider','dramatic','exclamation'),
(72,'en','Basketball queen, what a dunk!','Basketball queen, what a miss!','a basketball dunk','basketball on television','slang','exaggeration'),
(274,'en','Everyone is on their feet!','Everyone is in their seats!','everyone cheering at once','everyone leaving early','dramatic','exclamation'),
(309,'en','Beach football at sunset.','Beach volleyball at sunset.','barefoot football on sand','football on television','chill','none'),
(323,'en','The game is going well for her team.','The game is going badly for her team.','a basketball game at sunset','a game of cards','business','understatement'),
(340,'en','They brought their own goal!','They brought their own bench!','a goal on the square','a goal for next year','dramatic','exclamation'),
(373,'en','A stadium full of red fans.','A stadium full of blue fans.','a packed football stadium','an empty stadium at night','chill','none'),
(385,'en','She hit it high into the sky!','She hit it low into the grass!','hitting the ball high','hitting a ball into water','dramatic','exaggeration'),
(400,'en','Number 9 plays ice hockey.','Number 7 plays ice hockey.','ice hockey on a rink','ice hockey on a pond','chill','none'),
(445,'en','Her white line is perfect!','Her yellow line is perfect!','painting a white line','a line of people','dramatic','exclamation'),
(532,'en','He passed, she scored, easy.','She passed, he scored, easy.','passing the ball to her','passing a slow car','slang','none'),
(558,'en','He lost his hat playing volleyball.','He lost his shoe playing volleyball.','playing volleyball in a park','playing cards in a park','chill','none'),
(559,'en','This player is so happy!','This player is so angry!','a player in yellow','a player on the bench','dramatic','exclamation'),
(589,'en','Hard pulling, happy ending.','Hard pushing, happy ending.','pulling on a thick rope','pulling a door open','chill','cliche'),
(768,'en','The team is rowing in unison.','The team is running in unison.','a rowing team at sunrise','a team in an office','business','none'),
(770,'en','She dived for a tennis ball!','She dived for a golf ball!','diving in a tennis match','tennis on a grass court','dramatic','exclamation'),
(800,'en','Training done, legs gone.','Match done, legs gone.','training under floodlights','training a puppy','slang','exaggeration'),
(871,'en','He scored from his wheelchair!','He missed from his wheelchair!','a sports wheelchair on court','a wheelchair in a hospital','dramatic','exclamation'),
(1004,'en','The coach is not whispering.','The coach is not shouting.','a coach with a whistle','a coach full of tourists','chill','understatement'),
(1803,'en','He is going to throw the ball.','He is going to kick the ball.','about to throw the ball','to throw a party','chill','none'),
(2233,'en','She has two baseball gloves.','She has two baseball bats.','baseball gloves in both hands','baseball on television','chill','none'),
(3127,'en','He will throw it very fast!','He will kick it very fast!','to throw a baseball','to throw away the glove','dramatic','guessing'),
(3274,'en','The table tennis bat is red.','The table tennis bat is black.','a table tennis table','table tennis on television','chill','none'),
(3294,'en','He is going to kick the ball!','He is going to throw the ball!','about to kick the ball','to kick a door open','dramatic','exclamation'),
(3379,'en','He is running to the ball.','He is running from the ball.','running to the ball','a ball in the sky','chill','none'),
(4135,'en','She kicked the ball, then jumped off the pitch!','She caught the ball, then jumped off the pitch!','kicking the ball at goal','catching the ball with hands','dramatic','exclamation'),
(4154,'en','Night sport on a clay court.','Night sport on a grass court.','a sport under floodlights','sport on television','chill','none'),
(4264,'en','Street volleyball, no net.','Beach volleyball, no net.','volleyball on a quiet street','volleyball at the beach','chill','understatement'),
(4268,'en','The dog is a bigger fan, no joke.','The cat is a bigger fan, no joke.','a dog football fan','a fan for hot days','slang','exaggeration'),
(4917,'en','Red shot blue. Gotcha!','Blue shot red. Gotcha!','shooting paint at a player','shooting a basketball','dramatic','exclamation'),
(5429,'en','She trusts them, eyes closed.','She trusts them, eyes open.','trusting the team to catch','trusting a stranger online','chill','none'),
(17,'en','The project: one wooden shed.','The project: one wooden boat.','a big shed project','a school project on paper','business','none'),
(118,'en','Building done, time for a high-five!','Building done, time for a group hug!','building a raised planter','a tall office building','dramatic','exclamation'),
(358,'en','Careful work with that hammer.','Careful work with that spoon.','a hammer on a nail','a hammer in a toolbox','flirt','none'),
(469,'en','These matches work first time!','This lighter works first time!','a box of matches','matches on television','dramatic','exclamation'),
(618,'en','The rope saved the cart!','The chain saved the cart!','a rope around a wheel','a rope for skipping','dramatic','exaggeration'),
(622,'en','A rubber band secures herbs.','A rubber band secures leeks.','an orange rubber band','a rubber band for hair','business','none'),
(791,'en','He picked the wrong tool first.','He picked the right tool first.','picking the right tool','a tool for the garden','chill','none'),
(1286,'en','A worker is clearing the roof.','A worker is painting the roof.','a tiled house roof','a glass station roof','business','none'),
(1459,'en','He is painting the wall white.','He is painting the wall blue.','a big bare wall','a wall around a garden','chill','none'),
(1467,'en','A mechanic is rolling a wheel.','A mechanic is washing a wheel.','rolling a car wheel','a wheel on a bicycle','business','none'),
(1840,'en','A giant machine made of gears!','A giant machine made of wood!','a machine of rusty gears','a coffee machine','dramatic','exaggeration'),
(3118,'en','He is swinging his axe!','He is swinging his bat!','an axe in a tree','an axe on the wall','dramatic','exclamation'),
(3157,'en','He is holding up a red brick.','He is holding up a red helmet.','a half-finished brick wall','a brick seaside house','chill','none'),
(3653,'en','He is fixing the moon!','He is fixing the sun!','fixing a broken moon','fixing a flat tyre','dramatic','exaggeration'),
(3828,'en','The chimp and the match: bad idea.','The chimp and the knife: bad idea.','a burning match in hand','a football match on TV','chill','guessing'),
(4112,'en','A neat hole in the block.','A neat hole in the door.','drilling into a block','a block of cheese','chill','none'),
(4120,'en','A board for cracking walnuts.','A board for cracking eggs.','a board with a hole','a board for cutting bread','chill','none'),
(4161,'en','The two fronts almost touch.','The two backs almost touch.','the front of a car','the front of a house','chill','none'),
(4685,'en','He is repairing the fuse box.','He is repairing the car.','repairing the fuse box','repairing a flat tyre','business','none'),
(4686,'en','Repair done, lights on!','Repair done, water on!','a repair in the dark','a car repair shop','dramatic','exclamation'),
(4732,'en','He is building a wooden fence.','He is building a wooden shed.','building a garden fence','building a sandcastle','chill','none'),
(4843,'en','That is one big wooden structure!','That is one big metal structure!','a wooden house structure','the structure of a sentence','dramatic','exclamation'),
(5020,'en','Two people to replace one bulb!','Five people to replace one bulb!','replacing a dead bulb','replacing a flat tyre','low_iq','cliche'),
(5129,'en','The furniture is under covers.','The furniture is under towels.','grey covers on furniture','a cover on a book','business','none'),
(5204,'en','The room has improved a lot.','The garden has improved a lot.','improving an old room','improving their English','business','none'),
(5408,'en','The kit solved the chair problem.','The kit solved the table problem.','a red tool kit','a first aid kit','business','none'),
(38,'en','Heavy traffic at the airport today.','No traffic at the airport today.','a busy airport runway','an airport shop','business','none'),
(48,'en','He arrived and he is so happy!','He arrived and he is so sad!','arriving at a beach hotel','arriving at the office','dramatic','exclamation'),
(58,'en','Her backpack is huge, no joke.','Her suitcase is huge, no joke.','packing an orange backpack','a backpack at school','slang','exaggeration'),
(81,'en','Pure beauty in Santorini.','Pure beauty in Venice.','the beauty of the sunset','a beauty salon in town','chill','none'),
(104,'en','A stone from the sea bottom!','A shell from the sea bottom!','a stone from the bottom','the bottom of a glass','dramatic','exclamation'),
(134,'en','Camping in a pine forest, so cool.','Camping on a sandy beach, so cool.','camping in a forest','camping in the garden','slang','none'),
(142,'en','It is so big! A real castle.','It is so small! A real castle.','a castle on a lake','a castle on a hill','dramatic','exclamation'),
(287,'en','The village is still so far!','The lake is still so far!','a village far away','far from the city','dramatic','exclamation'),
(294,'en','The fire is flaring up.','The fire is going out.','a fire by the lake','a fire in a kitchen','chill','none'),
(306,'en','Flying over the clouds is beautiful.','Flying over the sea is beautiful.','flying above the clouds','flying a kite','chill','none'),
(330,'en','Just in time for the gate!','Too late for the gate!','running to the gate','a gate in a garden','dramatic','exclamation'),
(405,'en','Snow outside, friends inside.','Snow outside, dogs inside.','warm inside the cabin','inside a tent','chill','none'),
(407,'en','No way! A whole island for two!','No way! A whole island for ten!','a small tropical island','an island in a kitchen','dramatic','exaggeration'),
(428,'en','A canoe on a calm lake.','A canoe on a calm sea.','a calm mountain lake','a frozen lake','chill','none'),
(430,'en','He is teaching her his language.','She is teaching him her language.','learning a new language','a language app lesson','chill','none'),
(449,'en','Shh, they are listening!','Shh, they are sleeping!','listening in the forest','listening to music','dramatic','exclamation'),
(462,'en','The map found the fountain!','The map found the church!','a big paper map','a map on a phone','low_iq','exaggeration'),
(486,'en','Top of the mountain, yes!','Bottom of the mountain, yes!','on top of a mountain','a mountain lake','dramatic','exclamation'),
(502,'en','They are heading north.','They are heading south.','heading north with a compass','the north of a city','business','none'),
(533,'en','She kissed her passport!','She kissed her suitcase!','a stamped passport','a passport photo booth','dramatic','exclamation'),
(554,'en','Perfect place on the beach.','Perfect place in the park.','the perfect place to sit','a place in the queue','chill','none'),
(560,'en','Selfie first, fountain second.','Selfie first, pizza second.','the famous Trevi Fountain','a fountain in a mall','chill','cliche'),
(609,'en','They are resting on the hill.','They are running on the hill.','resting on a hilltop','resting in a hammock','chill','none'),
(652,'en','Ew! The sea is salty!','Ew! The lake is salty!','jumping into the sea','a sea of people','dramatic','exclamation'),
(671,'en','Too much shouting, sore throats.','Too much singing, sore throats.','shouting across a valley','shouting at the TV','chill','exaggeration'),
(785,'en','He is checking the timetable.','He is checking the newspaper.','a big train timetable','a school timetable','business','none'),
(804,'en','She totally loves to travel.','She totally hates to travel.','to travel by plane','to travel by bus','slang','none'),
(805,'en','Traveling by train, just in time!','Traveling by bus, just in time!','traveling through the Alps','traveling by ship','dramatic','exclamation'),
(825,'en','The dog loves the view too.','The cat loves the view too.','a view of rocky peaks','a view of the sea','low_iq','guessing'),
(832,'en','He is unpacking the longest scarf ever.','He is unpacking the longest sock ever.','unpacking a suitcase','unpacking the shopping','low_iq','exaggeration'),
(833,'en','Unpacking: the shell survived!','Unpacking: the mug survived!','unpacking after a trip','unpacking a new phone','dramatic','exclamation'),
(863,'en','Her water bottle is metal.','Her water bottle is plastic.','filling a water bottle','a water bottle in bed','chill','none'),
(866,'en','A rainbow at the waterfall!','A rainbow at the lake!','a tall waterfall in Iceland','a waterfall in a garden','dramatic','exclamation'),
(884,'en','She is showing him the world.','She is showing him the map.','a world of city lights','a map of the world','chill','exaggeration'),
(902,'en','She is waving at the airplane!','She is waving at the train!','a low airplane overhead','a paper airplane','dramatic','exclamation'),
(907,'en','Is anybody here? Only pigeons.','Is anybody here? Only cats.','anybody in the station','anybody at the party','chill','understatement'),
(952,'en','He is rowing a wooden boat.','He is rowing a rubber boat.','rowing a wooden boat','a boat in a harbour','chill','none'),
(989,'en','She is checking in her bag.','She is checking in her dog.','checking in at the airport','checking in at a hotel','business','none'),
(1084,'en','The flight is just starting.','The flight is just landing.','a flight after takeoff','a flight of stairs','business','none'),
(1119,'en','The guide is leading the tour.','The guide is leading the race.','a guide with an umbrella','a mountain guide climbing','business','none'),
(1141,'en','A guest is leaving the hotel.','A guest is entering the hotel.','leaving a grand hotel','a hotel by the sea','business','none'),
(1179,'en','Too much luggage for one man.','Too much luggage for one girl.','a trolley full of luggage','luggage on a car roof','low_iq','exaggeration'),
(1208,'en','A dinosaur in the museum!','A whale in the museum!','a dinosaur in a museum','a museum of modern art','dramatic','exclamation'),
(1230,'en','The passenger is fast asleep.','The passenger is wide awake.','a sleeping train passenger','a passenger in a taxi','chill','none'),
(1278,'en','Reception has a brass bell.','Reception has a brass lamp.','a key at reception','a wedding reception','business','none'),
(214,'en','This ice is dangerous!','This ice is safe!','dangerous thin ice','dangerous ice on a road','dramatic','exclamation'),
(3041,'en','He looks worried at his desk.','He looks worried in his bed.','a worried boy at work','worried about the weather','chill','none'),
(295,'en','A hand is mixing with a knife.','A hand is mixing with a spoon.','mixing paste in a bucket','mixing cake batter','chill','none'),
(78,'en','The sea took their castle on the beach.','A dog took their castle on the beach.','a sandcastle on the beach','a beach full of stones','chill','blaming_someone'),
(245,'en','She is drinking like a camel!','She is eating like a camel!','drinking from a steel bottle','drinking at a party','low_iq','exaggeration')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
