begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(1311,'en','She is waving at a huge ship!','She is waving at a tiny ship!','waving at a big ship','waving from a big ship','dramatic','exclamation'),
(1354,'en','Late again at the station!','Late again at the airport!','hurrying through a station','sleeping at the station','dramatic','guessing'),
(1372,'en','Her suitcase is grey and practical.','Her suitcase is red and practical.','pulling a grey suitcase','packing a grey suitcase','business','none'),
(1498,'en','Two guys in a balloon. Ciao!','Two guys on a horse. Ciao!','a balloon with two men','a balloon with two dogs','slang','none'),
(1525,'en','The train is coming at us!','The truck is coming at us!','a black steam train','to train for a race','dramatic','exclamation'),
(1529,'en','Two towers, one volcano.','Two towers, two volcanoes.','two round castle towers','two tall water towers','chill','none'),
(1530,'en','The town is on a hill. Nice view, they say.','The town is by the sea. Nice view, they say.','an old hilltop town','a new seaside town','gossip','none'),
(1567,'en','The plane is climbing up!','The plane is going down!','a plane climbing up','a plane coming down','dramatic','exclamation'),
(1568,'en','It is sailing under the moon.','It is sailing under the sun.','to sail at night','to sail in the sun','chill','none'),
(1581,'en','Van life, baby!','Tent life, baby!','a van with a surfboard','a van with a bike','slang','exclamation'),
(1647,'en','A woman is on the postcard.','A man is on the postcard.','an old torn postcard','a postcard of a beach','chill','none'),
(1667,'en','Paris at night. Pure magic!','Paris at noon. Pure magic!','Paris at night','Paris in the rain','dramatic','exclamation'),
(1670,'en','A red bus in London. Classic.','A red car in London. Classic.','a red bus in London','a red bus in Paris','chill','cliche'),
(1672,'en','Prague glows at dusk.','Prague glows at noon.','Prague castle at dusk','Prague castle in snow','chill','none'),
(1747,'en','Best tent spot ever!','Best beach spot ever!','a tent on a hill','a tent on a beach','slang','exaggeration'),
(1832,'en','She is taking a photo. Cool!','She is making a call. Cool!','taking a photo at night','taking a photo indoors','slang','exclamation'),
(1958,'en','Stone stairs and pink flowers.','Stone stairs and red flowers.','stone stairs in a village','stone stairs in a castle','chill','none'),
(1965,'en','Cosy cabin. A bit of snow.','Cosy cabin. A bit of sand.','a snowy wooden cabin','a cabin on a ship','ironic','understatement'),
(1970,'en','The hut has one plank door. Basic, but solid.','The hut has one glass door. Basic, but solid.','a tiny snowy hut','a tiny beach hut','business','cheap_quality'),
(2099,'en','This tree house is so cool!','This dog house is so cool!','a jungle tree house','a garden tree house','slang','exclamation'),
(2114,'en','A bridge across the stream.','A bridge across the road.','a bridge across a stream','a house across the street','chill','none'),
(2236,'en','Palace under a huge moon. Wow!','Palace under a huge sun. Wow!','a palace in the mountains','a palace in the desert','dramatic','exclamation'),
(2282,'en','Sailing at sunset. So chill.','Surfing at sunset. So chill.','sailing at sunset','sailing in a storm','slang','none'),
(2406,'en','One jeep, too many bags!','One bike, too many bags!','a jeep full of bags','a jeep in the city','dramatic','exaggeration'),
(2451,'en','A bird near the Eiffel Tower.','A plane near the Eiffel Tower.','the riverside Eiffel Tower','the Eiffel Tower in snow','chill','none'),
(2687,'en','Villa with a swimming pool. Very exclusive.','Villa with a tennis court. Very exclusive.','a turquoise swimming pool','an indoor swimming pool','business','none'),
(3447,'en','A statue under the Milky Way.','A statue under a rainbow.','a stone statue at night','a statue in a park','chill','none'),
(3685,'en','So many hot-air balloons!','So many helicopters!','hot-air balloons over rocks','hot-air balloons over the sea','dramatic','exclamation'),
(3740,'en','She has a swimming ring.','She has a surfboard.','running with a swimming ring','sitting in a swimming ring','chill','none'),
(4047,'en','A perfect holiday, but he still holds his phone.','A perfect holiday, but he still holds his book.','a holiday at the beach','a holiday in the snow','ironic','banter'),
(4052,'en','They are recording again. Take ten?','They are dancing again. Take ten?','recording with a phone','recording a song','gossip','guessing'),
(4058,'en','One night trip, ten suitcases!','One night trip, two suitcases!','packing for a short trip','to trip over a suitcase','dramatic','banter'),
(4115,'en','Two tourists are having fun. So cute!','Two tourists are having lunch. So cute!','tourists at night','tourists on a bus','gossip','exclamation'),
(4124,'en','A van, a dog and good friends.','A van, a cat and good friends.','life in a camper van','moving house with a van','chill','none'),
(4140,'en','He is jumping off a ledge. Adventure or bad idea?','He is jumping off a boat. Adventure or bad idea?','an adventure with friends','an adventure film','dramatic','guessing'),
(4293,'en','The jet is taking off!','The jet is landing!','a jet taking off','a jet of water','dramatic','exclamation'),
(4314,'en','Four oranges are in the bowl.','Four apples are in the bowl.','a bowl of oranges','a glass of orange juice','chill','none'),
(4358,'en','That bag looks a bit heavy.','That bike looks a bit heavy.','a heavy rucksack','heavy rain','ironic','understatement'),
(4362,'en','A suitcase is on the belt.','A suitcase is on the bus.','a moving luggage belt','a leather belt','chill','none'),
(4416,'en','Green light, ticket OK!','Green light, passport OK!','scanning a ticket','buying a train ticket','slang','exclamation'),
(4417,'en','Travel by tram, boat, plane.','Travel by bus, boat, plane.','travel by boat','travel by car','chill','none'),
(4445,'en','Wow, this bridge is huge!','Wow, this boat is huge!','a red suspension bridge','a bridge over a road','dramatic','exclamation'),
(4499,'en','Castles: he visits them all.','Farms: he visits them all.','visiting old castles','visiting old friends','slang','exaggeration'),
(4509,'en','The bag weighs 12.95 kg. Accepted.','The bag weighs 21.95 kg. Accepted.','weighing a bag','weighing the fruit','business','none'),
(4510,'en','She is checking her ticket. Wrong gate?','She is checking her phone. Wrong gate?','checking the flight board','checking her bag','dramatic','guessing'),
(4513,'en','All good: suitcase and ticket.','All good: backpack and ticket.','a suitcase at the airport','a suitcase on a train','chill','none'),
(4522,'en','Her tour has a wall, a boat and dumplings!','Her tour has a wall, a boat and pizza!','a tour of China','a tour of Italy','slang','exclamation'),
(4529,'en','Floor full of color. Magic!','Floor full of water. Magic!','colors on a stone floor','colors on a painted wall','dramatic','none'),
(4551,'en','Cheap tent. Great camping!','Cheap car. Great camping!','camping by a lake','camping in the snow','ironic','cheap_quality'),
(4562,'en','She is checking the direction. Serious face.','She is checking the time. Serious face.','finding the right direction','asking for directions','dramatic','none'),
(4590,'en','Vacation mode: big splash!','Vacation mode: long nap!','a vacation on a ship','a vacation on a train','slang','exclamation'),
(4591,'en','The ship offers a pool on the top deck.','The ship offers a cinema on the top deck.','a big passenger ship','a big cargo ship','business','none'),
(4606,'en','He is looking up at a tower.','He is looking up at a plane.','a clock on a tower','a clock on a wall','chill','none'),
(4621,'en','The passengers look like the flight is never coming.','The pilots look like the flight is never coming.','tired passengers waiting','passengers on a plane','dramatic','guessing'),
(4627,'en','Everyone leaves. He waves!','Everyone stays. He waves!','waving as the ship leaves','leaving on a bike','dramatic','exaggeration'),
(4634,'en','She reached the town at last!','She reached the lake at last!','reaching the seaside town','reaching for the phone','dramatic','exclamation'),
(4667,'en','The plane is dropping boxes. Air delivery!','The plane is dropping letters. Air delivery!','a plane dropping crates','a plane landing on grass','slang','none'),
(4681,'en','So many glass lamps!','So many glass bottles!','a blue glass lamp','a blue glass vase','dramatic','exclamation'),
(4716,'en','He is exploring the jungle like Indiana Jones.','He is exploring the desert like Indiana Jones.','exploring a jungle cave','exploring a big city','dramatic','exaggeration'),
(4751,'en','Guide with a yellow umbrella.','Guide with a red umbrella.','a guide with an umbrella','a guide in a museum','chill','none'),
(4771,'en','Gate, gate, gate... palace!','Gate, gate, gate... church!','a gate to a palace','a palace in a city','dramatic','exclamation'),
(4956,'en','She is walking to reception.','She is walking to the kitchen.','the hostel reception desk','a wedding reception','chill','none'),
(4957,'en','Hotel prices range from cheap to 2,000 EUR.','Hotel prices range from cheap to 20 EUR.','three kinds of hotel','a hotel by the sea','business','cheap_quality'),
(5162,'en','Beautiful views and dumplings.','Beautiful views and pancakes.','a beautiful mountain lake','a beautiful beach','chill','none'),
(5212,'en','Big hugs at the station!','Big hugs at the airport!','hugging at the station','a radio station','dramatic','exclamation'),
(5314,'en','Her basket holds all of Paris!','Her bag holds all of Paris!','a basket of souvenirs','a basket of fruit','slang','exaggeration'),
(5315,'en','She has a lot of postcards. For whom?','She has a lot of stamps. For whom?','postcards of Paris','writing a postcard','gossip','guessing'),
(5338,'en','You can stay for 10 euros or for 10,000 euros.','You can stay for 10 euros or for 1,000 euros.','staying in a hostel','staying at home','business','cheap_quality'),
(5431,'en','She is flying in a balloon.','She is flying in a plane.','a balloon over rocks','a party balloon','chill','none'),
(5447,'en','This road is very remote.','This road is very busy.','a remote desert road','a remote control','chill','none'),
(56,'en','Autumn leaves everywhere!','Autumn snow everywhere!','jumping into autumn leaves','autumn leaves on a tree','slang','exclamation'),
(180,'en','So cold! Her hand says no.','So hot! Her hand says no.','a cold frozen lake','a cold drink','dramatic','exaggeration'),
(255,'en','The sun rises in the east.','The sun rises in the west.','facing the east at dawn','going east by train','chill','cliche'),
(307,'en','Boo! He hid in the fog.','Boo! He hid in the barn.','hiding in thick fog','fog on the mirror','slang','exclamation'),
(367,'en','Too much heat for an ice pop!','Too much rain for an ice pop!','the heat in a village','the heat of a fire','dramatic','exaggeration'),
(394,'en','Too hot! He is hugging the fan.','Too hot! He is hugging the dog.','a hot sunny day','a hot cup of tea','dramatic','exclamation'),
(402,'en','She is sliding on the ice.','She is sliding on the grass.','bubbles in the ice','ice in a drink','chill','none'),
(444,'en','Lightning! Did you see that?','Rainbow! Did you see that?','watching lightning at night','lightning in the daytime','slang','exclamation'),
(580,'en','She is protecting her from the rain.','She is protecting her from the sun.','protecting someone from rain','protecting someone from a dog','chill','none'),
(588,'en','Splash! A big puddle jump.','Splash! A big pool jump.','jumping into a puddle','stepping around a puddle','slang','exclamation'),
(598,'en','She is dancing in the rain.','She is dancing in the snow.','dancing in heavy rain','hiding from the rain','chill','none'),
(690,'en','The sky is so big.','The sea is so big.','looking up at the sky','a sky full of stars','chill','none'),
(706,'en','Snow on the tongue? Yummy!','Rain on the tongue? Yummy!','catching snow on the tongue','clearing snow from a car','slang','exclamation'),
(726,'en','Spring is here, jacket off.','Winter is here, jacket off.','spring under cherry trees','spring rain in the city','chill','none'),
(741,'en','Big storm outside, tea inside.','Big sun outside, tea inside.','watching a storm with tea','walking in a storm','chill','none'),
(781,'en','One, two, three... thunder!','One, two, three... rainbow!','waiting for the thunder','thunder in a football stadium','dramatic','exclamation'),
(819,'en','Nice umbrella. Room for me?','Nice car. Room for me?','sharing an umbrella','an umbrella on the beach','flirt','banter'),
(870,'en','The sun sets in the west.','The sun sets in the east.','watching the sun go west','driving west at night','chill','none'),
(875,'en','The wind stole her scarf!','The wind stole her hat!','a scarf in the wind','wind blowing snow','dramatic','blaming_someone'),
(878,'en','Winter fun on sleds!','Winter fun on skis!','a winter day on sleds','a winter day indoors','slang','exclamation'),
(1003,'en','Just one cloud today.','Just two clouds today.','one big white cloud','a grey rain cloud','chill','understatement'),
(1274,'en','A huge rainbow over the hills.','A huge rainbow over the sea.','a rainbow over green hills','a rainbow over a city','chill','none'),
(1353,'en','One bright star. Make a wish!','One bright moon. Make a wish!','pointing at a bright star','a star on a tree','slang','exclamation'),
(1373,'en','Summer vibes: big lake jump.','Summer vibes: big pool jump.','a summer lake jump','a summer pool party','slang','none'),
(1390,'en','He wants to touch the moon.','He wants to touch the sun.','reaching for the moon','a moon over the sea','dramatic','guessing'),
(1394,'en','A big orange sun on the sea.','A big orange sun on the snow.','the sun over the sea','the sun over mountains','chill','none'),
(1466,'en','Rain or sun? The weather can''t decide.','Snow or sun? The weather can''t decide.','changing weather on a hill','sunny weather on a beach','ironic','guessing'),
(1502,'en','Sunset for two. So sweet.','Breakfast for two. So sweet.','watching the sunset together','a sunset in the mountains','gossip','none'),
(1674,'en','Purple sky, purple hills.','Purple sky, green hills.','a purple starry sky','a purple flower field','chill','none'),
(1724,'en','She is holding the moon!','She is holding the sun!','holding the moon','holding a poppy','dramatic','exclamation'),
(1931,'en','A rainy city street.','A sunny city street.','a rainy street','a rainy beach','chill','none'),
(1952,'en','A full moon behind one tree.','A full moon behind two trees.','full moon behind a tree','full moon over the sea','chill','none'),
(1953,'en','Snowflake crown? Queen vibes.','Flower crown? Queen vibes.','a crown of snowflakes','snowflakes on a window','flirt','exaggeration'),
(2042,'en','That moon is huge!','That sun is huge!','a huge full moon','a huge old castle','dramatic','exclamation'),
(2046,'en','A snowy night in the forest. So quiet...','A snowy night in the city. So quiet...','a snowy forest at night','a snowy street at night','dramatic','none'),
(2057,'en','The chimney is made of stone.','The chimney is made of metal.','a stone chimney in snow','cleaning the chimney','chill','none'),
(2096,'en','Even the sky is red!','Even the sky is green!','a red desert sky','a red sports car','dramatic','exclamation'),
(2124,'en','She is walking on a wet road.','She is walking on a wet beach.','walking down a country road','driving down a country road','chill','none'),
(2175,'en','Midnight in the pine forest.','Midnight in the desert.','midnight under the stars','a party at midnight','chill','none'),
(2254,'en','A frozen palace. Hi, Elsa!','A frozen lake. Hi, Elsa!','a frozen snowy palace','frozen peas in a bag','slang','exclamation'),
(2450,'en','A thunderstorm over the water.','A thunderstorm over the city.','a thunderstorm over water','a thunderstorm over a town','chill','none'),
(2490,'en','Nice hat! Is the snowman cold?','Nice hat! Is the dog cold?','a snowman in a hat','building a snowman','low_iq','guessing'),
(3277,'en','The child is holding a star!','The child is holding a lamp!','holding a glowing star','holding a glowing lamp','dramatic','exclamation'),
(3458,'en','Stone heads under the stars.','Stone heads under the sun.','stars over stone heads','stars on a flag','chill','none'),
(3640,'en','The lamp is shining in space.','The lamp is shining at a ship.','shining a beam into space','a light on a ship','chill','none'),
(3658,'en','So windy, the tree gave up.','So rainy, the tree gave up.','a windy day in Patagonia','windy weather at sea','ironic','exaggeration'),
(4074,'en','The sun is behind her.','The moon is behind her.','the sun over a lagoon','the sun over a city','chill','none'),
(4102,'en','The sunshine is calling him!','The rain is calling him!','sunshine outside the window','sunshine in the office','dramatic','exaggeration'),
(4142,'en','It is raining on her. Fun!','It is snowing on her. Fun!','spinning while it rains','hiding while it rains','slang','exclamation'),
(4292,'en','A breeze is moving her hair.','A fan is moving her hair.','a breeze in the meadow','a breeze by the sea','chill','none'),
(4381,'en','A warm day at the beach.','A cold day at the beach.','a warm sunny beach','a warm winter coat','chill','none'),
(4447,'en','Just a little wet today.','Just a little snowy today.','a wet bus stop','a wet dog','ironic','understatement'),
(4717,'en','It is so dark in the tunnel!','It is so dark in the house!','a dark rock tunnel','a dark night sky','dramatic','exclamation'),
(4748,'en','Only clouds below the wing.','Only mountains below the wing.','clouds below a plane','clouds over the sea','chill','none'),
(4849,'en','Summer: water for everyone!','Summer: cake for everyone!','a summer garden sprinkler','a summer beach day','slang','exclamation'),
(4896,'en','Everyone has a long shadow!','Everyone has a long scarf!','long shadows on stones','shadows on a wall','slang','none'),
(4901,'en','Blue sea, blue sky, big dive.','Blue pool, blue sky, big dive.','diving into blue water','diving into a blue pool','slang','none'),
(5118,'en','Sunlight is pouring over him. What a morning!','Rain is pouring over him. What a morning!','sunlight through a window','sunlight through the trees','dramatic','none'),
(5189,'en','Weather check: still raining.','Weather check: still snowing.','checking the weather by hand','the weather on TV','chill','none'),
(5190,'en','Windy? She loves it!','Sunny? She loves it!','a windy seafront','a windy mountain top','slang','exclamation'),
(5191,'en','A flag on a snowy plain.','A flag on a sandy beach.','a snowy white plain','a snowy city street','chill','none'),
(5228,'en','It is snowing hard!','It is raining hard!','snowing on a city square','snowing on a beach','dramatic','exclamation'),
(5237,'en','Tea under a sky full of stars.','Tea under a sky full of birds.','stars over a desert camp','stars over a city','chill','none'),
(5303,'en','Snowflakes on her mitten.','Snowflakes on her shoe.','a snowflake on a mitten','a snowflake on a window','chill','none'),
(5439,'en','Four men, one grey umbrella!','Four men, one red umbrella!','a grey rainy city','a grey winter coat','dramatic','exclamation'),
(473,'en','She is biting her gold medal. Real gold?','She is biting her gold ring. Real gold?','biting a gold medal','a medal in a box','dramatic','guessing'),
(596,'en','Go, go, go! What a race!','Go, go, go! What a swim!','a race on a track','a race in a pool','dramatic','exclamation'),
(610,'en','The pumpkin got a blue ribbon. She''s shocked!','The carrot got a blue ribbon. She''s shocked!','a pumpkin''s blue ribbon','a ribbon in her hair','gossip','none'),
(811,'en','Trophy up, confetti down!','Medal up, confetti down!','lifting a gold trophy','cleaning a gold trophy','slang','exclamation'),
(877,'en','Muddy winner? Legend!','Clean winner? Legend!','winner of a mud race','winner of a swim race','slang','none'),
(3135,'en','She is winning the race!','She is losing the race!','winning a running race','winning a swimming race','dramatic','exclamation'),
(4389,'en','He missed the start. Oops.','He missed the bus. Oops.','missing the start','starting a car','ironic','understatement'),
(4410,'en','Staring contest! Don''t blink!','Eating contest! Don''t blink!','a staring contest','a singing contest','slang','exclamation'),
(4515,'en','He won a medal. You bet!','He won a cup. You bet!','to win a medal','to win a car','slang','none'),
(5122,'en','They all achieved their goals.','They all missed their goals.','achieving a hard goal','achieving good grades','chill','none'),
(5225,'en','She is finishing way ahead!','She is finishing way behind!','finishing a race','finishing her homework','slang','none'),
(5023,'en','He is cheering at an airplane!','He is cheering at a train!','an airplane landing low','an airplane taking off','dramatic','exclamation'),
(1178,'en','The loser is under a towel.','The loser is under a table.','the loser of the match','the loser of the race','dramatic','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
