begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(4091,'en','The ice is cracking under her!','The ice is cracking under him!','ice cracking under her feet','cracking eggs on the ice','dramatic','exclamation'),
(4119,'en','The stone man collapsed. RIP.','The stone dog collapsed. RIP.','a stone figure collapsing','a stone bridge collapsing','slang','none'),
(4185,'en','A mug is pressing the mouse.','A mug is pressing the waffles.','a mug pressing a mouse','a plate pressing a mouse','chill','none'),
(4274,'en','Just a "little" damage.','Just a "little" snow.','damage to a parked car','damage to a bicycle','ironic','understatement'),
(4392,'en','What a fall in the park!','What a fall in the kitchen!','a fall over a bench','a fall from a ladder','dramatic','exclamation'),
(4454,'en','She is tipping the apples out.','She is tipping the eggs out.','tipping a bucket of apples','tipping the waiter','chill','none'),
(4473,'en','The cactus made him yell!','The snake made him yell!','yelling in the desert','yelling in the snow','gossip','blaming_someone'),
(4505,'en','He is falling over backwards!','He is falling over forwards!','falling backwards off a chair','walking backwards to the table','dramatic','exclamation'),
(4638,'en','Bye, house. Now it is rubble.','Bye, barn. Now it is rubble.','a heap of rubble','clearing away the rubble','gossip','none'),
(4666,'en','The pumpkin smashed. Oops!','The egg smashed. Oops!','a pumpkin smashing on concrete','a pumpkin smashing a window','ironic','exclamation'),
(4829,'en','Paint chips are falling off.','Paint drops are falling off.','chips of old paint','chips of old glass','chill','none'),
(4966,'en','The ice split in two.','The ice split in three.','splitting a slab of ice','splitting a log of wood','nerd','none'),
(5054,'en','Bro is lifting half the house.','Bro is lifting half the tent.','lifting cases into a van','lifting weights in a gym','slang','exaggeration'),
(5100,'en','They are sticking photos on a map.','They are sticking photos on a door.','sticking photos on a map','sticking maps on the wall','chill','none'),
(5121,'en','She is removing the muffins.','She is removing the cookies.','removing a tray of muffins','removing the oven door','chill','none'),
(5172,'en','Poor dough! He is banging it.','Poor door! He is banging it.','banging on bread dough','banging on the front door','dramatic','exclamation'),
(5179,'en','She is reaching into the oven.','She is reaching into a fridge.','reaching toward a hot oven','reaching the top shelf','chill','none'),
(5239,'en','What a perfect release!','What a perfect landing!','the release of a falcon','the release of an album','dramatic','exclamation'),
(5297,'en','The old castle lies in ruins.','The old bridge lies in ruins.','a castle in ruins','a castle in the snow','chill','none'),
(5380,'en','He even took the box!','She even took the box!','taking stuff from a box','taking a box to school','gossip','exclamation'),
(5386,'en','She is tearing the contract.','She is tearing the curtains.','tearing a contract in half','tearing pages from a book','business','none'),
(5436,'en','The team is twisting dough.','The team is cutting dough.','twisting a rope of dough','twisting a rope of wool','business','none'),
(5476,'en','She is walking over debris.','She is walking over flowers.','walking through debris','sweeping up the debris','chill','none'),
(70,'en','This barber is a legend!','This baker is a legend!','a barber trimming a beard','a barber sweeping the floor','slang','exaggeration'),
(398,'en','Hygiene first, then thumbs up.','Hygiene first, then high five.','good hygiene in the bathroom','good hygiene in the kitchen','chill','none'),
(660,'en','Who needs a salon? A basin works.','Who needs a salon? A bucket works.','washing hair over a basin','washing dishes in a basin','ironic','cheap_quality'),
(874,'en','The pink wig suits her.','The pink hat suits her.','putting on a pink wig','brushing a pink wig','flirt','none'),
(1806,'en','Two buns? She is so trendy.','Two bows? She is so trendy.','hair in two round buns','two buns on a plate','gossip','none'),
(1948,'en','Her wavy hair is everywhere!','Her short hair is everywhere!','wavy hair full of leaves','wavy hair full of flowers','dramatic','exclamation'),
(1959,'en','Her braid reaches her waist.','Her braid reaches her knees.','a waist-long braid','a short braid','chill','none'),
(1979,'en','She dyed it purple. Bold!','She dyed it green. Bold!','hair dyed bright purple','hair dyed bright green','gossip','exclamation'),
(2150,'en','Ponytail up. She will go out there.','Hair down. She will go out there.','a ponytail at the window','a ponytail on a horse','chill','guessing'),
(2162,'en','Her ginger hair looks perfect.','Her black hair looks perfect.','long ginger hair in waves','ginger hair in a bun','flirt','none'),
(2626,'en','A city lives in his bald head.','A farm lives in his bald head.','a bald head in profile','a bald head with glasses','chill','none'),
(2629,'en','Her hair is in two pigtails.','Her hair is in two buns.','two long braided pigtails','two short curly pigtails','chill','none'),
(2686,'en','The brunette looks so calm.','The blonde looks so calm.','a brunette in blue','a brunette in red','flirt','none'),
(2688,'en','His dreadlocks are very long.','His dreadlocks are very short.','long dreadlocks past the chest','short dreadlocks under a hat','chill','none'),
(2740,'en','His moustache is as white as snow.','His moustache is as black as coal.','a thick white moustache','a thin black moustache','dramatic','cliche'),
(2826,'en','The yellow ribbon suits her.','The red ribbon suits her.','a yellow hair ribbon','a yellow gift ribbon','flirt','none'),
(3598,'en','Her curly hair is in blue pen.','Her curly hair is in red pen.','curly hair in blue pen','curly hair in red paint','chill','none'),
(4130,'en','The cat gave him a flat top!','The dog gave him a flat top!','a gorilla''s flat top','a cat''s flat top','gossip','exclamation'),
(4808,'en','The stylist is making a braid.','The stylist is making a bun.','weaving a long braid','cutting a long braid','chill','none'),
(4946,'en','Her ponytail is dancing too.','Her scarf is dancing too.','a swinging ponytail','a ponytail under a cap','chill','exaggeration'),
(5196,'en','Her bun and her book go everywhere.','Her bun and her dog go everywhere.','a blonde bun on top','a sweet bun','chill','exaggeration'),
(5316,'en','Love her bouncy curly hair.','Love her bouncy straight hair.','tight curly dark hair','long curly blonde hair','flirt','none'),
(174,'en','They are at a clinic desk.','They are at a hotel desk.','a visit to the clinic','a visit to the gym','business','none'),
(204,'en','He is racing on his crutches!','He is racing on his bike!','walking on two crutches','leaning on one crutch','dramatic','exaggeration'),
(233,'en','He dislocated his shoulder.','He dislocated his knee.','a dislocated shoulder','a dislocated finger','chill','none'),
(248,'en','She is dosing with a dropper.','She is dosing with a syringe.','squeezing a glass dropper','dropping a glass dropper','nerd','none'),
(366,'en','Her arm has healed. Yes!','Her leg has healed. Yes!','a healed arm','a healed leg','dramatic','exclamation'),
(760,'en','Oh no! His ankle is swelling!','Oh no! His wrist is swelling!','an ankle swelling up','a wrist swelling up','dramatic','none'),
(761,'en','Her foot has a big swelling.','Her hand has a big swelling.','a swelling on the ankle','a swelling on the knee','chill','none'),
(772,'en','Therapy is helping the client.','Yoga is helping the client.','a therapy session','a yoga session','business','none'),
(929,'en','He is wrapping a bandage.','He is wrapping a present.','wrapping a white bandage','wrapping a white scarf','chill','none'),
(949,'en','Ouch, a blister on the heel!','Ouch, a blister on the toe!','a blister on the heel','a blister on the hand','dramatic','exclamation'),
(962,'en','Her knee has a big bruise.','Her arm has a big bruise.','a bruise on a knee','a bruise on an eye','chill','none'),
(984,'en','The plaster cast is still wet.','The plaster cast is dry.','a fresh arm cast','a fresh leg cast','nerd','none'),
(1093,'en','There is a fracture in the leg.','There is a fracture in the arm.','a leg bone fracture','a wrist bone fracture','nerd','none'),
(1147,'en','His elbow has an infection.','His knee has an infection.','an infection on the elbow','an infection in the eye','chill','none'),
(1148,'en','The injection is ready. Run!','The bandage is ready. Run!','a tray for an injection','a tray ready for dinner','low_iq','exclamation'),
(1299,'en','He loves his scan, apparently.','He hates his scan, apparently.','a patient having a scan','a scan at the airport','ironic','guessing'),
(1360,'en','She is using a stethoscope. Shh!','She is using a thermometer. Shh!','listening with a stethoscope','a stethoscope on a table','dramatic','exclamation'),
(1362,'en','The cut is getting stitches.','The cut is getting a plaster.','stitches in a forearm','stitches in a shirt','chill','none'),
(1381,'en','The syringe is squirting!','The bottle is squirting!','squirting a syringe','filling a syringe','dramatic','exclamation'),
(1447,'en','The vaccine hurts a bit.','The vaccine tickles a bit.','a vaccine in the arm','a vaccine in the leg','chill','understatement'),
(1451,'en','This vitamin makes her laugh.','This vitamin makes her cry.','an orange gummy vitamin','a green gummy vitamin','gossip','guessing'),
(1477,'en','The X-ray shows hand bones.','The X-ray shows foot bones.','an X-ray of a hand','an X-ray of a foot','nerd','none'),
(3027,'en','He is healing the old man.','He is healing the young man.','healing an old man''s eyes','healing a young man''s leg','chill','none'),
(4411,'en','The treatment is a plaster.','The treatment is an injection.','treatment for a blister','treatment for a headache','chill','none'),
(4546,'en','The surgery has a green couch.','The surgery has a red couch.','a boy in the surgery','a boy having surgery','chill','none'),
(4547,'en','They are in the waiting room.','They are in the dining room.','sitting in a waiting room','sitting in a living room','chill','none'),
(4648,'en','She is examining a small boy.','She is examining a small dog.','examining a worried boy','examining a worried cat','business','none'),
(4649,'en','The teddy is braver than him.','The puppy is braver than him.','hugging a brown teddy','hugging a brown puppy','ironic','guessing'),
(4664,'en','She is counting the dose drop by drop.','She is counting the dose spoon by spoon.','a dose of yellow oil','a dose of cough syrup','nerd','none'),
(4740,'en','He will clean the wound now.','He will clean the bike now.','cleaning a bleeding wound','a wound on the face','chill','none'),
(4755,'en','The X-ray shows a hand fracture.','The X-ray shows a leg fracture.','a fracture on an X-ray','a fracture in a leg','nerd','none'),
(4925,'en','She is caring for a patient.','She is caring for a baby.','caring for a hospital patient','caring for a garden','business','none'),
(4981,'en','Everyone got the vaccine. Yay!','Nobody got the vaccine. Yay!','vaccines in upper arms','a vaccine in the leg','dramatic','exclamation'),
(5072,'en','The brown liquid is very viscous.','The green liquid is very viscous.','pouring a brown liquid','pouring a clear liquid','nerd','none'),
(5111,'en','She is nursing a sick child.','She is nursing a sick puppy.','nursing a sick child','nursing a glass of water','chill','none'),
(5120,'en','All done! The surgeons are happy.','All done! The bakers are happy.','surgeons around a patient','surgeons in a waiting room','dramatic','exclamation'),
(5150,'en','He is presenting a prescription.','He is presenting a train ticket.','handing over a prescription','writing a prescription','business','none'),
(5320,'en','She is demonstrating a spine.','She is demonstrating a heart.','demonstrating on a spine model','demonstrating in the street','business','none'),
(5451,'en','One injection, now he is Hulk!','One pill, now he is Hulk!','an injection in the arm','an injection in the leg','slang','exaggeration'),
(5458,'en','The vitamin is fizzing like crazy!','The milk is fizzing like crazy!','a fizzing vitamin tablet','a melting vitamin gummy','slang','exclamation'),
(5494,'en','A disabled man is rolling fast.','A disabled man is rolling slowly.','a disabled wheelchair user','a disabled man on crutches','chill','none'),
(117,'en','They made a plate mosaic.','They made a cup mosaic.','a flower mosaic from plates','a mosaic of glass tiles','chill','none'),
(217,'en','Her dart is near the bullseye!','Her dart is near the door!','throwing a turquoise dart','throwing a turquoise ball','flirt','none'),
(263,'en','She is emerging from the lake!','She is emerging from the snow!','emerging from the water','emerging from a cave','dramatic','exclamation'),
(361,'en','No flowers? Just wrap lollipops.','No flowers? Just wrap biscuits.','wrapping lollipops in paper','wrapping biscuits in paper','ironic','cheap_quality'),
(377,'en','She is performing in a studio.','She is performing in a church.','performing like a music video','performing in a big stadium','chill','none'),
(397,'en','They are hunting in the forest.','They are hunting in the desert.','hunting in an autumn forest','hunting in the snow','chill','none'),
(548,'en','That one! Photography is fun.','That one! Painting is fun.','street photography at sunset','wedding photography indoors','dramatic','exclamation'),
(845,'en','Another vanishing! Thanks, sea.','Another vanishing! Thanks, dog.','the vanishing of a drawing','the vanishing of a ship','ironic','blaming_someone'),
(944,'en','He forgot to use his binoculars.','He forgot to use his telescope.','black binoculars at the chest','black binoculars on a table','ironic','guessing'),
(996,'en','Hands are shaping wet clay.','Hands are shaping wet sand.','shaping a clay pot','painting a clay pot','chill','none'),
(1096,'en','She is in a white gallery.','She is in a white kitchen.','walking through a gallery','walking through a shop','chill','none'),
(1427,'en','He is balancing on a rope!','He is balancing on a log!','balancing on a thin rope','balancing on a thin branch','dramatic','exclamation'),
(1438,'en','He is recording a podcast.','She is recording a podcast.','recording a podcast','listening to a podcast','chill','none'),
(1458,'en','The walker has a golden dog.','The walker has a black dog.','a walker with trekking poles','a walker with a buggy','chill','none'),
(1535,'en','He is upside down. So easy.','He is lying down. So easy.','balancing upside down','hanging upside down','slang','understatement'),
(1609,'en','She is doing ballet on a rock!','She is doing ballet on a boat!','ballet on a rock','ballet in a studio','dramatic','exclamation'),
(1717,'en','This instrument is a violin.','This instrument is a guitar.','a string instrument','a wind instrument','nerd','none'),
(1777,'en','This dude is playing the banjo.','This dude is playing the drums.','playing a banjo','tuning a banjo','slang','none'),
(1799,'en','The cello is the largest one.','The violin is the largest one.','a large dark cello','a small dark cello','nerd','none'),
(1833,'en','He is leaning on his guitar.','He is leaning on his piano.','leaning on a guitar','leaning on a tree','chill','none'),
(1854,'en','The guitar has white strings.','The guitar has black strings.','white strings on a guitar','white strings on a kite','nerd','none'),
(1915,'en','The bass has four strings.','The bass has six strings.','a bass with four strings','a bass with six strings','nerd','none'),
(2033,'en','The guitar is in a whirlpool!','The guitar is in a desert!','a guitar in a whirlpool','a boat in a whirlpool','dramatic','exclamation'),
(2070,'en','The electric guitar is a rocket!','The electric guitar is sinking!','an electric guitar taking off','an electric guitar on stage','slang','exaggeration'),
(2185,'en','The pianist has blonde hair.','The pianist has black hair.','a pianist at the piano','a pianist at a keyboard','chill','none'),
(2195,'en','The watercolor is dripping.','The oil paint is dripping.','a watercolor portrait','a watercolor landscape','chill','none'),
(2310,'en','A melody rises from the piano.','A melody rises from the drum.','a golden melody rising','a golden melody falling','dramatic','none'),
(2350,'en','Somebody carved faces! Wow!','Somebody carved names! Wow!','carved pumpkin faces','carved wooden faces','low_iq','exclamation'),
(2388,'en','This gamer loves pink.','This gamer loves green.','a gamer in pink','a gamer in blue','gossip','none'),
(2432,'en','Her flamenco pose is fire!','Her ballet pose is fire!','flamenco with a fan','flamenco on a stage','slang','exclamation'),
(2470,'en','The saxophone has a curved bell.','The saxophone has a straight bell.','a floating saxophone','a saxophone player','nerd','none'),
(2471,'en','She is such a bookworm.','She is such a gamer.','a bookworm with a book','a bookworm with a phone','gossip','none'),
(2493,'en','The farm is sewn as a quilt.','The farm is sewn as a flag.','a quilt of a farm','a quilt on a bed','nerd','none'),
(2527,'en','The DJ wears a gas mask. Why?','The DJ wears a ski mask. Why?','gas mask and headphones','gas mask and goggles','ironic','guessing'),
(2550,'en','She sits cross-legged, barefoot.','She sits cross-legged in boots.','sitting cross-legged','standing cross-legged','chill','none'),
(2581,'en','He is playing a bamboo flute.','He is playing a bamboo drum.','playing a bamboo flute','carving a bamboo flute','chill','none'),
(2595,'en','Someone left a grand piano outside.','Someone left a grand piano inside.','a grand piano outside','a grand piano inside','ironic','guessing'),
(2603,'en','The sheet music is handwritten.','The sheet music is printed out.','old handwritten sheet music','new printed sheet music','nerd','none'),
(2618,'en','The handwriting is in cursive.','The handwriting is in print.','faded cursive handwriting','neat printed handwriting','nerd','none'),
(2657,'en','The bird is part of a collage.','The cat is part of a collage.','a bird in a collage','a collage of old photos','chill','none'),
(2825,'en','He is surrounded by books!','He is surrounded by toys!','surrounded by walls of books','surrounded by walls of toys','dramatic','exclamation'),
(3061,'en','She floats above a record.','She floats above a piano.','a spinning vinyl record','breaking a world record','chill','none'),
(3082,'en','The ballerina is on one toe!','The ballerina is on two feet!','a ballerina on one toe','a ballerina on a stage','dramatic','exclamation'),
(3256,'en','The band is rocking the club!','The band is rocking the beach!','a band on stage','a band in a stadium','slang','none'),
(3406,'en','Someone is diving with a sea monster!','Someone is diving with a shark!','diving over a reef','diving off a cliff','dramatic','exaggeration'),
(3419,'en','He is blowing a trumpet.','He is blowing a whistle.','blowing a golden trumpet','cleaning a golden trumpet','chill','none'),
(3420,'en','The double bass is taller than her.','The double bass is smaller than her.','bowing a double bass','carrying a double bass','nerd','none'),
(3422,'en','She is leading the orchestra.','She is leading the choir.','leading an orchestra','playing in an orchestra','business','none'),
(3423,'en','She is plucking the harp.','She is plucking the guitar.','plucking a tall harp','carrying a tall harp','chill','none'),
(3424,'en','The conductor holds a baton.','The conductor holds a flute.','a conductor in a tailcoat','a conductor on a train','business','none'),
(3428,'en','She is playing the violin beautifully.','She is playing the cello beautifully.','playing the violin','tuning the violin','flirt','none'),
(3431,'en','She is playing a clarinet.','She is playing a trumpet.','blowing into a clarinet','cleaning a clarinet','chill','none'),
(3463,'en','He is paddling a canoe.','He is paddling a raft.','paddling a canoe at sunset','carrying a canoe at sunset','chill','none'),
(3633,'en','Floating in space? No, in a pool.','Floating in space? No, in a lake.','floating on his back','floating in open space','ironic','none'),
(3706,'en','The rollercoaster is scaring everyone!','The big wheel is scaring everyone!','a family on a rollercoaster','a family by a rollercoaster','dramatic','exaggeration'),
(4031,'en','The ball landed right on top!','The ball landed right on him!','the top of the stack','the top shelf','dramatic','exclamation'),
(4062,'en','Bro is gripping the kite bar.','Bro is gripping the boat rail.','gripping a kite bar','gripping a steering wheel','slang','none'),
(5175,'en','Nice moustache, steady hands.','Nice beard, steady hands.','a waiter with a moustache','a waiter shaving his moustache','flirt','none'),
(106,'en','He is aiming at the hay bale.','He is aiming at a tree.','aiming a bamboo bow','aiming a water gun','chill','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
