begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(1742,'en','The angel is holding a shield.','The angel is holding a sword.','a large round shield','a shield on the ground','chill','none'),
(1866,'en','Sunglasses and a gun: a classic spy.','Sunglasses and a knife: a classic spy.','a spy with a pistol','a spy with a camera','ironic','cliche'),
(1868,'en','Justice needs a lot of heavy books.','Justice needs a lot of candles.','the scales of justice','the sword of justice','chill','exaggeration'),
(1909,'en','Her blade is shining.','Her blade is rusty.','a long steel blade','a short broken blade','chill','none'),
(2134,'en','The empress is not amused.','The empress is very amused.','a stern empress','an empress on a horse','ironic','understatement'),
(2154,'en','The general''s beard is white.','The general''s beard is black.','an old general in armour','a young general in armour','chill','none'),
(2328,'en','Such a "humble" throne!','Such a "humble" bed!','a huge golden throne','an empty golden throne','ironic','exclamation'),
(2505,'en','Rain, a rifle and zero complaints.','Sun, a rifle and zero complaints.','a long scoped rifle','a rifle on the ground','chill','understatement'),
(2717,'en','Parliament is by the Thames.','Parliament is by the Seine.','the Houses of Parliament','a parliament by the sea','nerd','none'),
(2733,'en','The army is charging!','The army is retreating!','an army on horses','an army on foot','dramatic','exclamation'),
(2815,'en','He is ready for battle.','He is ready for bed.','ready for battle','a battle at sea','chill','none'),
(4306,'en','They are leaving prison!','They are entering prison!','leaving the prison','visiting a prison','dramatic','exclamation'),
(4330,'en','The soldiers are marching.','The soldiers are dancing.','soldiers marching in step','soldiers marching at night','chill','none'),
(4332,'en','He is arresting a burglar with rubber chickens.','He is arresting a burglar with gold watches.','arresting a burglar','arresting a police officer','gossip','none'),
(4526,'en','She is thinking very hard about this election.','He is thinking very hard about this election.','voting in an election','winning an election','ironic','exaggeration'),
(4533,'en','They are celebrating in court.','They are crying in court.','a happy family in court','a tennis court party','chill','none'),
(4563,'en','The law book has gold corners.','The law book has iron corners.','a huge book of law','breaking the law','nerd','none'),
(4602,'en','Customs is searching her bag.','Customs is searching her car.','searching a suitcase','searching for a lost dog','business','none'),
(4624,'en','A clear majority!','A clear minority!','a clear majority','a majority of empty chairs','dramatic','exclamation'),
(4625,'en','She is voting like a champion!','He is voting like a champion!','voting with joy','voting by post','dramatic','exaggeration'),
(4736,'en','The army is training on sand.','The army is training in snow.','an army training together','an army at war','chill','none'),
(4754,'en','He is protesting: "Not me!"','She is protesting: "Not me!"','protesting to the referee','protesting in the street','dramatic','bad_excuse'),
(4789,'en','She has full authority.','He has full authority.','a woman with authority','authority over an army','business','none'),
(4790,'en','Conflict at the big table, and papers are flying!','Peace at the big table, and papers are flying!','a conflict at the table','a conflict on the street','gossip','exclamation'),
(5027,'en','The judge is using her gavel.','The judge is using her phone.','a judge with a gavel','a judge in a wig','business','none'),
(5137,'en','The parliament is full today.','The parliament is empty today.','a full parliament','an empty parliament','business','none'),
(5140,'en','The stamp allows her to enter.','The stamp allows her to drive.','allowed to enter','allowed to smoke','business','none'),
(5163,'en','Politicians, arguing as usual.','Politicians, hugging as usual.','angry politicians pointing','politicians shaking hands','ironic','cliche'),
(5164,'en','This campaign has it all: posters, debates, confetti.','This campaign has it all: posters, debates, fireworks.','an election campaign','a campaign against smoking','gossip','exaggeration'),
(5197,'en','The office is rebelling!','The office is sleeping!','rebelling against work','rebelling against parents','dramatic','exclamation'),
(5205,'en','She is taking the oath.','He is taking the oath.','taking an oath','breaking an oath','chill','none'),
(5233,'en','The military parade is huge.','The military parade is tiny.','a military parade','a military hospital','chill','none'),
(5234,'en','Each rank is perfectly level.','Each rank is a total mess.','ranks of saluting women','ranks of running men','business','none'),
(5255,'en','He looks very guilty, and very shocked.','She looks very guilty, and very shocked.','a guilty young man','a guilty judge','gossip','guessing'),
(5394,'en','Someone claimed it first!','Nobody claimed it first!','claiming the frozen land','claiming a lost bag','gossip','exclamation'),
(5424,'en','They signed the treaty.','They tore up the treaty.','shaking hands on a treaty','tearing up a treaty','business','none'),
(5426,'en','Both delegations have a deal.','No delegation has a deal.','two delegations meeting','a delegation at the airport','business','none'),
(5455,'en','He got the approval!','He got no approval!','approval for a passport','approval from his parents','dramatic','exclamation'),
(5461,'en','Everyone is posting a ballot.','Everyone is posting a letter.','posting a folded ballot','reading a long ballot','chill','none'),
(5462,'en','Democracy in one plastic box.','Democracy in one wooden box.','democracy in action','democracy on television','ironic','understatement'),
(5475,'en','A tank is coming behind them!','A horse is coming behind them!','a tank in the smoke','a tank full of water','dramatic','exclamation'),
(5477,'en','Best snow fort battle ever.','Best sand fort battle ever.','a fort made of snow','a fort made of stone','slang','exaggeration'),
(5497,'en','The candidate won!','The candidate lost!','a winning candidate','a losing candidate','dramatic','exclamation'),
(95,'en','She is putting on pink blush.','She is putting on blue blush.','sweeping on pink blush','blushing from shame','chill','none'),
(281,'en','Her eyeliner wing is perfect. Nailed it!','Her eyeliner wing is a mess. Nailed it!','a winged eyeliner line','eyeliner on the lips','slang','exclamation'),
(282,'en','Her eyeshadow is pure gold.','Her eyeshadow is pure silver.','shimmery gold eyeshadow','blue eyeshadow on a brush','flirt','exaggeration'),
(284,'en','Their face masks are cracking.','Their face masks are melting.','cracking green face masks','a face mask against flu','chill','none'),
(313,'en','Her foundation is so smooth.','Her foundation is so patchy.','blending in foundation','the foundation of a house','flirt','none'),
(448,'en','Lip gloss as shiny as glass.','Lip gloss as matte as paper.','shiny pink lip gloss','dark red lip gloss','flirt','exaggeration'),
(466,'en','The mascara face: mouth wide open.','The mascara face: eyes shut tight.','brushing on black mascara','mascara running down cheeks','gossip','cliche'),
(886,'en','Grandma earned her wrinkles.','The girl earned her wrinkles.','deep wrinkles on her face','wrinkles in a shirt','chill','none'),
(1871,'en','Her eye is glowing white.','Her eye is glowing red.','an eye glowing white','a lamp glowing white','chill','none'),
(1912,'en','Her tattoos are blue.','Her tattoos are red.','swirling blue face tattoos','a tattoo on her hand','chill','none'),
(1924,'en','So many vivid colours!','So many dull colours!','vivid swirls of colour','a vivid dream','gossip','exclamation'),
(1983,'en','Her eyelashes are very long.','Her eyelashes are very short.','long dark eyelashes','fake eyelashes in a box','chill','none'),
(2683,'en','Her face paint is a mandala.','Her face paint is a spider.','a mandala in face paint','face paint on a clown','nerd','none'),
(2691,'en','She is wearing a trench coat.','She is wearing a ski jacket.','a beige trench coat','a wet trench coat','chill','none'),
(2838,'en','Rainbow glitter on her cheeks.','Black glitter on her cheeks.','rainbow glitter on cheeks','glitter on a card','chill','none'),
(4319,'en','The stripes are blending in.','The stripes are growing wider.','blending cream into skin','blending fruit in a mixer','chill','none'),
(4406,'en','The artist is smoothing lines.','The artist is drawing lines.','smoothing harsh lines','smoothing a bed sheet','chill','none'),
(5289,'en','The skin lacks moisture.','The skin lacks pores.','skin without moisture','moisture on a window','nerd','none'),
(224,'en','Designing a chair is fun.','Designing a table is fun.','designing a model chair','designing a dress','chill','none'),
(475,'en','Each memory makes her smile.','Each memory makes her cry.','a box of old memories','a camera memory card','chill','none'),
(479,'en','Her mind is two moves ahead.','Her mind is two moves behind.','planning moves in her mind','changing her mind','nerd','exaggeration'),
(656,'en','The whole crowd can''t distract her!','The whole crowd can''t distract him!','trying to distract her','trying to distract a dog','dramatic','exclamation'),
(1513,'en','Hands pressed together to pray.','Hands pressed together to clap.','hands pressed to pray','praying with open hands','chill','none'),
(1514,'en','Religion in an old painting.','Religion in a modern cartoon.','a painting about religion','a book about religion','nerd','none'),
(1547,'en','The holy man is thinking hard.','The holy man is laughing hard.','a holy man thinking','a holy man praying','chill','none'),
(1576,'en','In her dream, she swings from the moon.','In her dream, she swings from a tree.','a dream about the moon','a dream about the sea','chill','guessing'),
(1878,'en','His head is invisible!','His suit is invisible!','an invisible head','an invisible hand','dramatic','exclamation'),
(1880,'en','Best invention ever: a flying ship.','Best invention ever: a flying car.','a flying invention','an invention on wheels','slang','exaggeration'),
(1934,'en','These shelves are surreal.','These shelves are ordinary.','surreal bending bookshelves','a surreal melting clock','nerd','none'),
(2032,'en','A portal to a golden city.','A portal to a dark forest.','a glowing round portal','a portal under the sea','chill','none'),
(2037,'en','A creature with dark wings.','A creature with long horns.','a dark winged creature','a creature in the sea','chill','none'),
(2076,'en','So much literature, so little time.','So many pizzas, so little time.','shelves of old literature','literature on a phone','nerd','cliche'),
(2389,'en','She is praying with faith.','She is praying with open arms.','praying with deep faith','losing her faith','chill','none'),
(2401,'en','A path into a fantasy world.','A path into a busy city.','a fantasy forest path','a fantasy book cover','chill','none'),
(2408,'en','Imagination opens a real path.','Imagination opens a real door.','a book of imagination','no imagination at all','chill','none'),
(2417,'en','Dark and light in harmony.','Red and blue in harmony.','a sphere of harmony','singing in harmony','nerd','none'),
(2482,'en','So many turrets on one castle!','So many flags on one castle!','pointed castle turrets','a tank turret','gossip','exclamation'),
(2501,'en','Shiva is meditating on a rock.','Shiva is meditating in a boat.','Shiva with a trident','Shiva with a sword','nerd','none'),
(2502,'en','A forest shrine full of moss.','A desert shrine full of sand.','a mossy forest shrine','a shrine in a city','chill','none'),
(2504,'en','Krishna has a peacock feather.','Krishna has an eagle feather.','Krishna with a crown','Krishna with a flute','nerd','none'),
(2520,'en','A sacred light from above!','A sacred light from below!','a sacred beam of light','a sacred river','dramatic','exclamation'),
(2526,'en','Poseidon has two spears.','Poseidon has two swords.','Poseidon rising from waves','Poseidon sinking a ship','nerd','none'),
(2544,'en','Hanuman has a golden crown.','Hanuman has a silver crown.','Hanuman with a golden staff','Hanuman with a sword','nerd','none'),
(2545,'en','The monkey is worshipping.','The monkey is sleeping.','worshipping on stone steps','worshipping a football star','chill','none'),
(2606,'en','Her head is pure clockwork.','Her head is pure glass.','a head full of clockwork','a clockwork toy mouse','nerd','exaggeration'),
(2729,'en','Her crystal ball is glowing.','Her crystal ball is broken.','touching a crystal ball','a broken crystal ball','chill','none'),
(2742,'en','He is concentrating on code.','He is concentrating on a book.','concentrating on a screen','concentrating on a game','nerd','none'),
(2757,'en','A piano full of inspiration.','A kitchen full of inspiration.','a flash of inspiration','inspiration from a book','chill','none'),
(2758,'en','A stone bust in the desert.','A stone bust in the jungle.','a huge stone bust','a bust in a museum','nerd','none'),
(2803,'en','His face looks psychedelic!','His face looks grey and dull!','a psychedelic portrait','a psychedelic car','dramatic','exclamation'),
(2819,'en','Her rings are glowing gold.','Her rings are glowing green.','glowing golden rings','glowing red eyes','chill','none'),
(2859,'en','She is meditating in a cave.','She is meditating on a beach.','to meditate in a cave','to meditate on a mountain','chill','none'),
(3119,'en','The fairy has golden wings.','The fairy has black wings.','a fairy with golden wings','a fairy with a wand','chill','none'),
(3188,'en','Someone is praying on a mat.','Someone is sleeping on a mat.','to pray on a mat','to pray in a church','chill','none'),
(3197,'en','She is daydreaming about tea, books and music.','She is daydreaming about cars, books and music.','to daydream at a table','to daydream in bed','gossip','guessing'),
(3325,'en','Magic sparks from an old book!','Magic sparks from an old cup!','magic from an old book','a magic show on stage','dramatic','exclamation'),
(5077,'en','He recalled every card, easy.','She recalled every card, easy.','recalling answers on cards','recalling a broken car','slang','understatement'),
(5396,'en','Orange flags mark the line.','Blue flags mark the line.','marking a line with flags','marking an exam paper','business','none'),
(54,'en','ATM cash for sunflowers!','ATM cash for pizza!','taking cash from an ATM','an ATM keeping her card','gossip','exclamation'),
(55,'en','She won the auction.','She lost the auction.','bidding at an auction','an auction on the internet','gossip','none'),
(86,'en','That bill is way too long!','That bill is way too short!','a very long bill','a bill in a wallet','slang','exaggeration'),
(239,'en','He doubts the ring is gold.','He is sure the ring is gold.','doubting a gold ring','doubting his girlfriend','gossip','guessing'),
(849,'en','He got his visa!','He lost his visa!','a visa in a passport','a visa for a holiday','dramatic','exclamation'),
(1423,'en','Pointing at a bar chart.','Pointing at a pie chart.','bar and line charts','a chart on paper','business','none'),
(1765,'en','So greedy! Hands off the gold!','So greedy! Hands off the cake!','a greedy man with coins','a greedy dog with food','dramatic','exclamation'),
(1886,'en','The consumer''s plate is empty.','The consumer''s plate is full.','a hungry consumer','a consumer in a shop','business','none'),
(2753,'en','This piggy bank is rich!','This piggy bank is broke!','a big pink piggy bank','a broken piggy bank','slang','exaggeration'),
(2840,'en','A whole city on one scroll!','A whole forest on one scroll!','a city on a scroll','a scroll in a bottle','gossip','exclamation'),
(4148,'en','Pure luxury: a red sports car.','Pure luxury: a red motorbike.','a luxury sports car','a luxury hotel room','flirt','exaggeration'),
(4277,'en','The accountant found it!','The accountant lost it!','an accountant with receipts','an accountant on holiday','dramatic','exclamation'),
(4287,'en','They are viewing the flat.','They are viewing the car.','viewing an empty flat','viewing a used car','business','none'),
(4361,'en','She is shopping like a pro.','He is shopping like a pro.','shopping with many bags','shopping for food','slang','exaggeration'),
(4370,'en','The big safe is open.','The big safe is closed.','an open bank safe','a safe place to hide','business','none'),
(4371,'en','The bank lobby is huge.','The bank lobby is tiny.','a marble bank lobby','a busy hotel lobby','business','none'),
(4488,'en','Every document gets a red X. Bad day at the office.','Every document gets a green tick. Bad day at the office.','stamping a document','printing a document','ironic','exaggeration'),
(4573,'en','A secret deal over cash.','A secret deal over coffee.','a secret cash deal','a secret love letter','gossip','guessing'),
(4599,'en','Payment in coins and notes.','Payment in notes only.','a payment in cash','a payment by card','business','none'),
(4600,'en','He is exchanging money.','He is exchanging hats.','exchanging foreign money','exchanging gifts','business','none'),
(4694,'en','He signed the contract!','He tore up the contract!','signing a contract','reading a contract at home','dramatic','exclamation'),
(4787,'en','This pan is very valuable.','This pan is totally empty.','a valuable pan of gold','a valuable old painting','chill','none'),
(4791,'en','She is setting down papers.','She is setting down flowers.','a folder of papers','papers on the floor','business','none'),
(4871,'en','The registration queue is endless.','The registration queue is empty.','a registration desk','a car registration plate','dramatic','exaggeration'),
(4967,'en','A scan checks her identity.','A scan checks her luggage.','checking her identity','hiding her identity','nerd','none'),
(5169,'en','He is mailing a postcard.','He is mailing a package.','mailing a postcard','mailing a parcel','chill','none'),
(5170,'en','He is handing over a package.','He is handing over a pizza.','a wrapped birthday package','a package holiday','chill','none'),
(5181,'en','Her signature is in blue ink.','Her signature is in red ink.','a fresh blue signature','a signature on a cheque','business','none'),
(5198,'en','She is handing him a sheet.','She is handing him a cup.','a small written sheet','a sheet on a bed','chill','none'),
(5269,'en','She purchased a coat.','She purchased a dress.','purchasing an olive coat','purchasing a new car','business','none'),
(5279,'en','He is signing a giant scroll with a giant pen!','He is signing a giant scroll with a tiny pen!','signing a giant scroll','reading an old scroll','dramatic','exclamation'),
(5353,'en','The paperwork is winning.','The paperwork is shrinking.','towers of paperwork','paperwork on a laptop','dramatic','exaggeration'),
(5427,'en','The envelope has a red seal.','The envelope has a blue seal.','a red wax seal','a seal on the beach','chill','none'),
(5454,'en','Ink is splashing all over the passport.','Water is splashing all over the passport.','black ink drops','blue ink on fingers','slang','exaggeration'),
(5472,'en','The bills are falling out.','The keys are falling out.','bills falling from a wallet','bills in a cash machine','chill','none'),
(5473,'en','A "wealthy" man with an empty wallet.','A "wealthy" man with a full wallet.','a not so wealthy man','a wealthy man''s big house','ironic','understatement'),
(5504,'en','She is sending a letter.','She is sending a parcel.','sending a handwritten letter','sending a text message','chill','none'),
(44,'en','So much anger over a bag of flowers!','So much anger over a bag of apples!','anger at the flower market','anger at a traffic jam','dramatic','exclamation'),
(102,'en','Boredom level: a wet sock on his head.','Boredom level: a wet hat on his head.','boredom in a laundromat','boredom in a classroom','low_iq','exaggeration'),
(226,'en','Empty case, total despair.','Full case, total despair.','despair in an empty tunnel','despair after an exam','dramatic','none'),
(4534,'en','The official wears a chain.','The official wears a crown.','an official with a chain','an official stamping passports','chill','none'),
(4870,'en','His face is covered in foam.','His face is covered in mud.','foam on his cheek','foam on a beer','chill','none'),
(2538,'en','Little Red Riding Hood trusts the wolf.','Little Red Riding Hood trusts the bear.','Little Red Riding Hood''s wolf','Little Red Riding Hood''s gran','gossip','guessing'),
(525,'en','One little paperclip is beating the big fan.','One little stapler is beating the big fan.','a paperclip on the papers','a paperclip holding a photo','dramatic','exaggeration')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
