begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(232,'en','He is a little disappointed.','She is a little disappointed.','a disappointed customer','disappointed by the rain','ironic','understatement'),
(264,'en','So much emotion at arrivals!','So much emotion at departures!','full of emotion','hiding her emotion','dramatic','exclamation'),
(269,'en','Pure envy on the bus.','Pure envy on the train.','envy of a cyclist','envy of a bus driver','chill','none'),
(355,'en','He can''t eat. Guilt!','He can''t sleep. Guilt!','guilt over a broken jug','guilt over a broken phone','dramatic','exclamation'),
(411,'en','Wow, she is so jealous.','Wow, he is so jealous.','jealous of another dancer','jealous of her teacher','gossip','exaggeration'),
(536,'en','She finds peace in a hammock.','She finds peace in a bathtub.','peace at sunrise','peace at midnight','chill','none'),
(608,'en','Parked! What a relief!','Crashed! What a relief!','relief after parking','relief after a crash','dramatic','exclamation'),
(1718,'en','The Buddha is 100 % calm.','The Buddha is 100 % angry.','a calm face','a calm sea','nerd','exaggeration'),
(1823,'en','She feels lonely tonight.','She feels lonely this morning.','lonely on a balcony','lonely in a crowd','dramatic','none'),
(2498,'en','They share a tender hug.','They share a tender kiss.','a tender embrace','a tender steak','chill','none'),
(2558,'en','She is flying. Pure freedom!','She is swimming. Pure freedom!','freedom above the sea','freedom under the sea','dramatic','exclamation'),
(2571,'en','The boy is grumpy. Again.','The girl is grumpy. Again.','a grumpy little boy','a grumpy old man','ironic','guessing'),
(2576,'en','He is heartbroken in Paris.','He is heartbroken in Rome.','heartbroken in the rain','heartbroken in the snow','dramatic','none'),
(2723,'en','He is absolutely furious!','She is absolutely furious!','a furious warrior','a furious dragon','dramatic','exclamation'),
(2814,'en','He is reclining in the clouds.','He is reclining in the sea.','reclining on a carved seat','reclining on a sofa','chill','none'),
(2831,'en','Even the sun is cheerful!','Even the rain is cheerful!','a cheerful smiling sun','a cheerful rainy day','low_iq','exclamation'),
(3269,'en','She is relaxing on the roof.','She is relaxing on the beach.','relaxing in a deck chair','to relax in a bathtub','chill','none'),
(4123,'en','Tears over an A+? Really?','Tears over an F? Really?','tears over an A+','tears of laughter','ironic','guessing'),
(4146,'en','Too exhausted to take off his shoes.','Too exhausted to take off his shirt.','exhausted on the wet sand','exhausted in a hot bath','ironic','exaggeration'),
(4265,'en','A hug is calming the parrot.','A song is calming the parrot.','to calm an angry parrot','to calm a crying baby','chill','none'),
(4390,'en','The excitement is real!','The boredom is real!','excitement before a concert','excitement before an exam','slang','exclamation'),
(4506,'en','Comfort? The green chair wins.','Comfort? The white chair wins.','comfort in a big armchair','comfort on a kitchen chair','business','none'),
(4595,'en','He can''t stop crying.','He can''t stop laughing.','crying on the sofa','crying in the shower','dramatic','none'),
(4876,'en','Rain, but she is smiling.','Rain, but she is crying.','smiling at a puppy','smiling at the bus driver','chill','none'),
(4953,'en','She is hoping for photosynthesis.','She is hoping for a thunderstorm.','hoping for a sprout','hoping for a rainbow','nerd','exaggeration'),
(5026,'en','His phone is hilarious today.','His book is hilarious today.','hilarious in a lecture','hilarious at a wedding','gossip','none'),
(5133,'en','She is screaming in the park.','She is screaming in the pool.','screaming in a freeze game','screaming at a horror film','chill','none'),
(5174,'en','It is a cheerful dinner.','It is a cheerful breakfast.','a cheerful family dinner','a cheerful office party','chill','none'),
(5183,'en','So passionate, the chalk is flying!','So passionate, the books are flying!','a passionate old teacher','a passionate young singer','dramatic','exaggeration'),
(5185,'en','Kindness keeps the man dry.','Kindness keeps the dog dry.','kindness in the rain','kindness in the sun','chill','none'),
(5188,'en','A boot? Total disappointment.','A fish? Total disappointment.','disappointment on a jetty','disappointment at a zoo','ironic','understatement'),
(5260,'en','Caught with cake. The shame!','Caught with pizza. The shame!','shame over a cake','shame over a broken plate','dramatic','exclamation'),
(5311,'en','Now the whole group is calm.','Now the whole group is angry.','calm under blankets','calm under pressure','chill','none'),
(5352,'en','Her frustration is at 1000 %.','Her frustration is at 0 %.','frustration at a laptop','frustration at a teacher','nerd','exaggeration'),
(5387,'en','They share their sorrow.','They share their pizza.','sorrow on a sofa','sorrow at a funeral','dramatic','none'),
(5413,'en','Cars everywhere. Hopeless!','Bikes everywhere. Hopeless!','a hopeless traffic jam','a hopeless football team','low_iq','exclamation'),
(37,'en','The team is advancing to the goal.','The team is advancing to the hut.','advancing to the summit','advancing to the final','chill','none'),
(185,'en','He commutes by tram. Yawn.','He commutes by boat. Yawn.','commuting by tram','commuting by bike','ironic','cliche'),
(189,'en','Three cars form a convoy.','Five cars form a convoy.','a convoy of sports cars','a convoy of trucks','chill','none'),
(375,'en','He looks cool in a race car.','He looks cool in a taxi.','a race car at sunrise','a race car at night','flirt','none'),
(517,'en','Bye, camper! He''s overtaking!','Bye, camper! He''s parking!','overtaking a slow camper','overtaking a fast train','slang','exclamation'),
(1035,'en','He can''t see his destination.','He can''t see the traffic.','far from the destination','arriving at the destination','ironic','guessing'),
(1416,'en','He is riding out of a tunnel.','He is riding out of a garage.','out of a road tunnel','into a train tunnel','chill','none'),
(2019,'en','The locomotive runs on steam.','The locomotive runs on diesel.','an old steam locomotive','an old diesel locomotive','nerd','none'),
(2071,'en','Nice vintage car, so festive.','Nice vintage van, so festive.','a vintage red car','a vintage red dress','flirt','none'),
(2380,'en','The car is escaping the fire!','The car is escaping the flood!','escaping a burning forest','escaping a burning house','dramatic','exclamation'),
(2601,'en','The man is kneeling in prayer.','The man is sitting in prayer.','kneeling on stone ground','kneeling on a soft sofa','chill','none'),
(2725,'en','He is crouching on a rock.','He is crouching on a tree.','crouching high on a rock','crouching low in a cave','chill','none'),
(2754,'en','So much steam at sunset!','So much snow at sunset!','white steam from a funnel','white smoke from a chimney','dramatic','exclamation'),
(2801,'en','Its headlights burn orange.','Its headlights burn blue.','orange headlights in the snow','headlights on a snowy car','chill','none'),
(3301,'en','He is steering the ship.','He is steering the car.','steering a big ship','steering a small car','chill','none'),
(3401,'en','The traffic light has flowers!','The traffic light has candles!','a flowery traffic light','a broken traffic light','low_iq','exclamation'),
(3472,'en','Lovely dress! She is spinning in it.','Lovely hat! She is spinning in it.','spinning in a red dress','spinning in a blue dress','flirt','none'),
(3813,'en','He is looking along the path.','He is looking along the river.','a colourful painted path','a muddy forest path','chill','none'),
(4014,'en','The suitcase is rolling along.','The bicycle is rolling along.','rolling through a car park','rolling down a hill','chill','none'),
(4051,'en','A truck carries a motorcycle.','A truck carries a bicycle.','an electric motorcycle','a motorcycle helmet','chill','none'),
(4071,'en','She is leaping off a wreck!','She is leaping off a bridge!','leaping into the sea','leaping into a pool','dramatic','exclamation'),
(4079,'en','The river is rushing past. Wild!','The cars are rushing past. Wild!','rushing down a river','rushing to the airport','slang','exaggeration'),
(4098,'en','Two cows block the way. Rude.','Two sheep block the way. Rude.','cows in the way','the way to the beach','ironic','blaming_someone'),
(4150,'en','The green car is speeding.','The red car is speeding.','speeding down a country road','speeding down a motorway','chill','none'),
(4152,'en','The trailer hides a vehicle.','The trailer hides a horse.','a vehicle inside a trailer','a vehicle on a ferry','gossip','guessing'),
(4199,'en','His feet are dragging in the lake.','His hands are dragging in the lake.','dragging his feet in water','dragging a boat to water','chill','none'),
(4201,'en','Show-offs! The bikes stand upright.','Show-offs! The cars stand upright.','bikes upright on one wheel','sitting upright in a chair','ironic','exclamation'),
(4270,'en','It is slowing for a duck.','It is slowing for a dog.','slowing down for a duck','slowing down at a light','chill','none'),
(4273,'en','There was a collision here.','There was a concert here.','a collision at a crossroads','a collision on a motorway','dramatic','none'),
(4412,'en','Sheep are blocking the road!','Cows are blocking the road!','blocking a mountain road','blocking a phone number','dramatic','exclamation'),
(4419,'en','She is rowing with her puppy.','She is rowing with her kitten.','rowing on a calm pond','rowing on a wild sea','chill','none'),
(4647,'en','He spun too much. Floor time.','He ran too much. Floor time.','spinning on an office chair','spinning on a dance floor','slang','understatement'),
(4662,'en','A plane is supplying the village.','A truck is supplying the village.','supplying a village by air','supplying a village by boat','chill','none'),
(4698,'en','What a huge motor!','What a huge tyre!','a huge V8 motor','a huge boat motor','dramatic','exclamation'),
(4702,'en','The goat escaped. Bye, farmer!','The cow escaped. Bye, farmer!','escaping from a goat pen','escaping from a fox','slang','blaming_someone'),
(4703,'en','He is raising a green flag.','He is raising a red flag.','raising a flag','raising a child','chill','none'),
(4890,'en','Everyone is circling the top.','Everyone is circling the tree.','circling a spinning top','circling a football','chill','none'),
(4902,'en','A submarine, then a whale. Swim faster!','A submarine, then a shark. Swim faster!','a submarine in a lake','a submarine in a harbour','dramatic','guessing'),
(4918,'en','He is climbing the stairs.','He is sliding down the stairs.','up the stairs with bags','down the stairs alone','chill','none'),
(4932,'en','Cool cap! She is steering a taxi.','Cool cap! She is steering a boat.','steering a yellow taxi','steering a yellow boat','flirt','none'),
(4976,'en','He is wading through water.','He is wading through snow.','wading in rice fields','wading in deep snow','chill','none'),
(4998,'en','The tunnel is made of gates.','The tunnel is made of trees.','a tunnel of shrine gates','a tunnel under the sea','chill','none'),
(5156,'en','He scored, so he is kneeling.','He missed, so he is kneeling.','kneeling on the grass','kneeling to pray','dramatic','none'),
(5160,'en','He''s dashing through the rain.','He''s dashing through the snow.','dashing past pigeons','dashing past the police','chill','none'),
(5166,'en','The tram is on the tracks.','The tram is on the grass.','tram tracks in the cobbles','tram tracks in a tunnel','chill','none'),
(5187,'en','Strong boy! He''s pulling a wagon!','Strong boy! He''s pulling a car!','pulling a farm wagon','pulling a horse wagon','low_iq','exclamation'),
(5210,'en','One "scary" goose made them retreat.','One "scary" dog made them retreat.','retreating from a goose','retreating from the rain','ironic','exaggeration'),
(5216,'en','She is taking a slow stroll.','She is taking a slow swim.','a stroll past flower stalls','a stroll along the beach','chill','none'),
(5221,'en','The path winds up the hills.','The river winds up the hills.','a path winding up mountains','a river winding downhill','chill','none'),
(5222,'en','She is climbing stone steps.','She is climbing wooden steps.','stone steps up a mountain','stone steps to a beach','chill','none'),
(5235,'en','She is stamping the cargo.','She is painting the cargo.','cargo at a container port','cargo at an airport','chill','none'),
(5247,'en','Nonna is angry about the footprints.','Nonna is angry about the broken vase.','muddy footprints in a hall','muddy footprints in a garden','gossip','blaming_someone'),
(5264,'en','She is shifting the sofa.','She is shifting the fridge.','shifting furniture around','shifting gears in a car','chill','none'),
(5337,'en','Croissant in mouth, he is travelling by rail.','Pizza in mouth, he is travelling by rail.','travelling by rail','travelling by air','gossip','none'),
(5339,'en','She is controlling a bus.','She is controlling a tram.','controlling a city bus','controlling a drone','chill','none'),
(5345,'en','She is leaning on the railing.','She is leaning on a tree.','leaning on a bridge railing','leaning on a garden fence','chill','none'),
(5360,'en','The metro is "a bit" busy.','The metro is "a bit" empty.','a packed metro station','an empty metro station','ironic','understatement'),
(5389,'en','He is dodging her like Messi.','She is dodging him like Messi.','dodging her hands','dodging a football','slang','exaggeration'),
(5416,'en','She loves that locomotive.','She loves that helicopter.','an orange electric locomotive','an orange steam locomotive','gossip','guessing'),
(5417,'en','The tram ends up in the depot.','The tram ends up in a museum.','trams in a depot','buses in a depot','chill','none'),
(5418,'en','The interior is all wood.','The interior is all plastic.','a wooden tram interior','a modern car interior','chill','none'),
(5419,'en','He makes every transfer.','He misses every transfer.','a transfer to a ferry','a bank transfer','chill','none'),
(5420,'en','He is boarding a white vessel.','He is boarding a red vessel.','a small passenger vessel','a huge cargo vessel','chill','none'),
(5428,'en','The truck is bringing freight.','The train is bringing freight.','freight on a big truck','freight on a ship','chill','none'),
(5492,'en','The wheel has thin spokes.','The wheel has no spokes.','thin metal spokes','thin wooden spokes','chill','none'),
(5493,'en','He loves every hub he sees.','He loves every car he sees.','the hub of a wheel','the hub of a city','gossip','guessing'),
(6,'en','One cushion is not enough.','One chair is not enough.','a pile of cushions','a pile of blankets','ironic','exaggeration'),
(839,'en','He is extending his table!','He is extending his bed!','extending a dining table','extending a visa','dramatic','exclamation'),
(859,'en','The wardrobe attacked her!','The fridge attacked her!','a wardrobe full of coats','a wardrobe full of shoes','dramatic','blaming_someone'),
(917,'en','The attic is full of junk.','The attic is full of water.','a dusty old attic','a bright new attic','slang','none'),
(1189,'en','They are carrying a mattress.','They are carrying a piano.','a mattress up the stairs','a mattress on the floor','chill','none'),
(1861,'en','This antique seat has a swan.','This antique seat has a lion.','an antique carved seat','an antique carved clock','chill','none'),
(1951,'en','An armchair awaits a reader.','A sofa awaits a reader.','a worn leather armchair','a new plastic armchair','chill','guessing'),
(1982,'en','The room is "a bit" cluttered.','The room is "a bit" empty.','cluttered shelves','a cluttered desk','ironic','understatement'),
(2026,'en','What a dreamy study!','What a dreamy kitchen!','a study full of flowers','a study full of students','slang','exclamation'),
(2028,'en','A white jug sits among books.','A white cat sits among books.','a jug on a bookshelf','a jug on a table','chill','none'),
(2064,'en','The snow globe has a church.','The snow globe has a castle.','a glowing snow globe','a broken snow globe','chill','none'),
(2075,'en','Books sit on the windowsill.','Cats sit on the windowsill.','books on a windowsill','plants on a windowsill','chill','none'),
(2078,'en','Two flames light the book.','Three flames light the book.','two candle flames','flames in a fireplace','chill','none'),
(2109,'en','The books stand in tidy rows.','The cups stand in tidy rows.','tidy rows of books','a tidy desk','chill','none'),
(2192,'en','Harry Potter would love these flasks.','Harry Potter would love these brooms.','glowing glass flasks','a thermos flask','nerd','guessing'),
(2250,'en','She is gazing at the city.','She is gazing at the sea.','gazing at a rainy city','gazing at a starry sky','dramatic','none'),
(2311,'en','The stained glass is huge.','The stained glass is tiny.','tall stained glass windows','a stained glass lamp','chill','none'),
(2397,'en','This room is so gloomy!','This room is so sunny!','a gloomy gothic room','a gloomy rainy day','dramatic','exclamation'),
(2434,'en','The still life shows blossoms.','The still life shows oranges.','a still life with blossoms','a still life with fruit','nerd','none'),
(2475,'en','She is reading barefoot.','She is dancing barefoot.','barefoot on a daybed','barefoot on the beach','chill','none'),
(2530,'en','Candlelight glows among roses.','Candlelight glows among books.','candlelight in a lantern','candlelight on a cake','chill','none'),
(2537,'en','The girl is reading a bedtime story.','The boy is reading a bedtime story.','a bedtime story in bed','a bedtime story on TV','chill','none'),
(2546,'en','This hall is "quite" spacious.','This hall is "quite" tiny.','a spacious hall','a spacious car','ironic','understatement'),
(2661,'en','The tiles form a chessboard.','The tiles form a rainbow.','black and white floor tiles','blue and white wall tiles','nerd','none'),
(2670,'en','The table has one drawer.','The table has three drawers.','a drawer with a knob','a drawer full of socks','chill','none'),
(2750,'en','The houseplant sits on books.','The houseplant sits on a TV.','a houseplant on a shelf','a houseplant on the floor','chill','none'),
(2910,'en','So many books! The bookshelf is full!','So many toys! The bookshelf is full!','a colourful bookshelf','an empty bookshelf','low_iq','exclamation'),
(3516,'en','The vase holds one flower.','The vase holds ten flowers.','a vase on a shelf','a vase on a table','chill','none'),
(4017,'en','The red lantern is glowing.','The blue lantern is glowing.','a glowing paper lantern','a glowing street lamp','chill','none'),
(4078,'en','Seven pillows for one person!','Seven blankets for one person!','a row of white pillows','a pile of white towels','gossip','exclamation'),
(4234,'en','He destroyed her closet in seconds.','She destroyed his closet in seconds.','a walk-in closet','a kitchen closet','gossip','banter'),
(4251,'en','His space? One empty shelf.','His space? One full shelf.','space for his clothes','space for a car','ironic','understatement'),
(4328,'en','The rug has a fringe.','The rug has a hole.','a fringed rug','a rug on the wall','chill','none'),
(578,'en','She is beaming with pride.','She is crying with pride.','pride in her motorbike','pride in her new car','chill','none'),
(4310,'en','The emotional player is crying!','The emotional player is laughing!','an emotional team song','an emotional wedding song','dramatic','exclamation'),
(4997,'en','He has a loud laugh.','He has a quiet laugh.','a laugh at the Colosseum','a laugh in Paris','chill','none'),
(5095,'en','He is staring up in awe!','He is staring down in awe!','awe at a giant skeleton','awe at a tiny coin','dramatic','exclamation'),
(5335,'en','She is an enthusiastic fan.','She is an enthusiastic player.','an enthusiastic football fan','an enthusiastic tennis fan','chill','none'),
(2897,'en','Where is Santa? He left his sleigh.','Where is Santa? He left his car.','a sleigh full of presents','a sleigh with reindeer','gossip','guessing'),
(3493,'en','She is leaving footprints.','She is leaving flowers.','a line of footprints','footprints in the snow','chill','none'),
(4218,'en','The corgi is pushing the engine hard.','The cat is pushing the engine hard.','a smoking tractor engine','a smoking car engine','ironic','blaming_someone'),
(4466,'en','All aboard the tour bus!','All aboard the ferry!','aboard a city bus','aboard a cruise ship','dramatic','cliche'),
(2049,'en','The reading corner looks cozy.','The kitchen corner looks cozy.','a cozy reading corner','a cozy wool jumper','chill','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
