begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(1930,'en','The medieval town looks cosy.','The modern city looks cosy.','a medieval stone town','a medieval market day','chill','none'),
(1962,'en','This fortress looks scary!','This cottage looks scary!','a dark hilltop fortress','a fortress in the desert','dramatic','exclamation'),
(1998,'en','Rich people live in this mansion.','Rich people live in this cottage.','a mansion at dusk','a mansion on the beach','gossip','guessing'),
(2015,'en','Fact: the monument is stone.','Fact: the monument is wood.','an old stone monument','a monument in a square','nerd','none'),
(2080,'en','Snow is falling on the pagoda.','Rain is falling on the pagoda.','a red pagoda in snow','a pagoda in the jungle','chill','none'),
(2081,'en','Stepping stones cross a lake.','Stepping stones cross a road.','stepping stones across water','stepping stones in a garden','chill','none'),
(2182,'en','The hiker has a red backpack.','The hiker has a blue backpack.','a hiker on a ledge','a hiker in a tent','chill','none'),
(2189,'en','Someone is falling overboard!','Someone is diving overboard!','falling overboard backwards','falling asleep in the boat','dramatic','exclamation'),
(2238,'en','The mosque has many domes.','The mosque has one dome.','a grand mosque with domes','a mosque in the desert','chill','none'),
(2258,'en','The church has a tall spire.','The church has a round dome.','a tall church spire','a spire on a castle','chill','none'),
(2259,'en','Take me to this lagoon now!','Take me to this glacier now!','a turquoise lagoon with palms','a frozen lagoon in winter','dramatic','exclamation'),
(2260,'en','Poor rowboat, nobody wants it.','Poor ship, nobody wants it.','an empty wooden rowboat','a rowboat full of people','dramatic','exaggeration'),
(2271,'en','She is chilling in a corridor.','She is chilling in a kitchen.','a spaceship corridor','a hospital corridor','slang','none'),
(2313,'en','Home is where the camper van is.','Home is where the orange tent is.','an orange camper van','a camper van in town','chill','cliche'),
(2347,'en','He is exploring an exoplanet.','He is exploring a deep cave.','exploring an alien world','exploring an old castle','nerd','none'),
(2368,'en','This beach is total paradise.','This desert is total paradise.','a tropical paradise at sunset','a paradise for skiers','slang','none'),
(2386,'en','The railing faces the sunset.','The railing faces a mountain.','a metal balcony railing','a railing on a staircase','chill','none'),
(2398,'en','The terrace offers sea views.','The terrace offers city views.','a tiled seaside terrace','a terrace in the mountains','business','none'),
(2454,'en','The winding path has lanterns.','The straight path has lamps.','a winding cobblestone path','a winding mountain river','chill','none'),
(2541,'en','Nobody cleaned this staircase.','Nobody cleaned this kitchen.','a crumbling stone staircase','a crumbling stone bridge','ironic','understatement'),
(2557,'en','Wait, the sailboat is glass?','Wait, the sailboat is wood?','a glass sailboat','a sailboat in a bottle','low_iq','none'),
(2614,'en','Two boys are near a minaret.','Two girls are near a minaret.','walking toward a minaret','climbing up a minaret','chill','none'),
(2621,'en','The mast has lots of rigging.','The mast has lots of flags.','a tall mast with rigging','a mast with pirate flags','nerd','none'),
(2928,'en','A spaceship is flying over her.','A big dragon is flying over her.','a huge pale spaceship','a spaceship landing nearby','chill','none'),
(3132,'en','He is hiking with a stick.','He is hiking with a dog.','to hike up a mountain','to hike up the prices','chill','none'),
(3171,'en','Such a "helpful" signpost.','Such a "helpful" map.','an old wooden signpost','an old wooden fence post','ironic','understatement'),
(3673,'en','Six hot-air balloons are up.','Two hot-air balloons are up.','hot-air balloons at sunrise','hot-air balloons at night','chill','none'),
(4013,'en','An iceberg is passing the deck. Titanic vibes!','A whale is passing the deck. Titanic vibes!','boots on a wooden deck','a deck of playing cards','slang','exclamation'),
(4139,'en','He is climbing a narrow path.','He is climbing a steep ladder.','a narrow dirt path','a path through the desert','chill','none'),
(4141,'en','Five guys are lying in the sun.','Five guys are lying in the mud.','lying in the grass','lying to his friends','slang','none'),
(4239,'en','Best taxi ever: a seagull over the port.','Best taxi ever: a dragon over the port.','flying over a busy port','a port full of yachts','slang','exaggeration'),
(4245,'en','They are sliding for free!','They are skiing for free!','sliding along a water channel','sliding down a snowy hill','dramatic','cheap_quality'),
(4296,'en','Raised wands send a signal.','Raised flags send a signal.','a signal to the pilot','a weak phone signal','nerd','none'),
(4297,'en','The departures board is huge!','The arrivals board is huge!','a huge departures board','a departure by train','dramatic','exclamation'),
(4301,'en','He is squeezing through a gap.','He is crawling through a gap.','squeezing through a narrow gap','a gap in the fence','chill','none'),
(4333,'en','She stepped onto the platform.','She stepped onto the bus.','a busy station platform','a diving platform','chill','none'),
(4347,'en','A boat is ferrying her across.','A bus is ferrying her across.','to ferry people across','to ferry goods upriver','chill','none'),
(4351,'en','She is leaning on the marble.','She is leaning on the piano.','a polished marble railing','a marble garden statue','chill','none'),
(4357,'en','Her canvas rucksack could hold a sofa.','Her leather rucksack could hold a sofa.','a big canvas rucksack','a canvas for painting','chill','exaggeration'),
(4363,'en','His backpack finally appeared!','His suitcase finally appeared!','appearing on the belt','appearing on television','dramatic','exclamation'),
(4424,'en','The border is just a stripe.','The border is just a fence.','crossing the border on foot','a border around a picture','nerd','understatement'),
(4438,'en','She is leading the parade!','She is leading the marathon!','a carnival parade','a military parade','gossip','exaggeration'),
(4461,'en','They are digging. He can''t escape.','They are swimming. He can''t escape.','digging in the sand','digging in the garden','dramatic','guessing'),
(4468,'en','The porter is carrying a lot.','The porter is holding nothing.','a heavily loaded porter','a porter at a hotel','ironic','understatement'),
(4472,'en','He can''t believe the altitude!','He can''t believe the heat!','a cable car at altitude','the altitude of a plane','dramatic','exclamation'),
(4507,'en','The agent is attaching a tag.','The agent is attaching a lock.','a tag on a suitcase','a jacket name tag','business','none'),
(4508,'en','He''s loading bags like a boss.','He''s loading food like a boss.','loading bags onto the belt','loading a truck with boxes','slang','exaggeration'),
(4511,'en','The service here is excellent.','The service here is rude.','friendly service at a desk','room service in a hotel','business','none'),
(4520,'en','The wall stretches forever.','The river stretches forever.','stretching over the mountains','stretching before a run','dramatic','exaggeration'),
(4521,'en','Towers fade in the distance.','Houses fade in the distance.','towers in the distance','a long-distance phone call','chill','none'),
(4620,'en','He is sleeping here overnight.','He is working here overnight.','stuck overnight at an airport','an overnight train journey','chill','none'),
(4622,'en','She is sighing at the ceiling.','She is sighing at the window.','sighing at the gate','sighing with relief','chill','none'),
(4635,'en','She reached her destination.','She reached her hotel.','reaching her destination','a destination by plane','chill','none'),
(4636,'en','She found the real lighthouse!','She found the real castle!','a red-and-white lighthouse','a lighthouse in a storm','dramatic','exclamation'),
(4680,'en','A rider is mounting a camel.','A rider is mounting a horse.','a rider mounting a camel','a rider on a horse','chill','none'),
(4708,'en','A man is guiding the group.','A dog is guiding the group.','guiding a tour group','guiding a ship into port','chill','none'),
(4743,'en','Juice! Best flight ever!','Pizza! Best flight ever!','a flight at sunset','a flight of stairs','slang','exaggeration'),
(4770,'en','Boarding is now in progress.','Landing is now in progress.','boarding through a jet bridge','boarding at a train station','business','none'),
(4804,'en','They are touring a blue town.','They are touring a red town.','touring a blue town','touring with a rock band','chill','none'),
(4878,'en','This guy is diving off the pier.','This guy is diving off the boat.','diving off a wooden pier','fishing off a wooden pier','slang','none'),
(4882,'en','They are pulling an aircraft!','They are pulling a truck!','pulling a huge aircraft','an aircraft taking off','dramatic','exclamation'),
(4906,'en','The tent is the only survivor.','The arch is the only survivor.','a white party tent','a tent in the woods','dramatic','exaggeration'),
(4921,'en','The trail is full of roots.','The trail is full of snow.','a rough forest trail','a trail of footprints','chill','none'),
(4935,'en','She is touching the compass.','She is touching the radio.','a brass ship''s compass','a compass for drawing circles','nerd','none'),
(4942,'en','One bag of luggage? Legend!','Five bags of luggage? Legend!','luggage over his shoulder','luggage on a trolley','slang','exclamation'),
(4955,'en','Only the lockers look tidy here.','Only the bunk beds look tidy here.','a row of grey lockers','a locker at a pool','ironic','exaggeration'),
(4973,'en','He is posing at a monument.','He is posing at a waterfall.','posing at a white monument','a monument on a mountain','chill','none'),
(5051,'en','She lost it. Passport, maybe?','She found it. Passport, maybe?','losing something important','losing a football match','gossip','guessing'),
(5053,'en','The label displays her photo.','The label displays her dog.','a label with her photo','a label on a jar','business','none'),
(5161,'en','He stands before a cathedral.','He stands before a castle.','a brick cathedral tower','inside a dark cathedral','chill','none'),
(5211,'en','What a happy return home!','What a sad return home!','a happy return home','a return to school','dramatic','exclamation'),
(5213,'en','A red train is on the railway.','A red tram is on the railway.','a railway station platform','a railway in the mountains','chill','none'),
(5223,'en','Her route is marked in red.','Her route is marked in blue.','a route on a map','a bus route through town','chill','none'),
(5226,'en','He made it into the carriage!','He made it into the taxi!','jumping into a train carriage','a carriage pulled by horses','dramatic','exclamation'),
(5232,'en','She is sailing a yacht.','She is cleaning a yacht.','a classic sailing yacht','a yacht in a harbour','chill','none'),
(5272,'en','The hikers are going wild.','The hikers are going home.','hikers cheering at a canyon','hikers resting in a tent','slang','none'),
(5280,'en','She is reading the signpost.','She is painting the signpost.','reading a wooden signpost','painting a wooden signpost','chill','none'),
(5333,'en','Each staircase is fancier!','Each staircase is dirtier!','a grand marble staircase','a staircase in a lighthouse','dramatic','exclamation'),
(5423,'en','His rucksack travels worldwide.','His rucksack stays in one city.','travelling worldwide','a worldwide phone network','chill','none'),
(5491,'en','He is so welcome here!','He is so lonely here!','a welcome guest','a welcome break from work','dramatic','exclamation'),
(259,'en','The sky is eerie. Aliens?','The sea is eerie. Aliens?','an eerie red glow','an eerie silent forest','dramatic','guessing'),
(320,'en','Wow, frost is everywhere!','Wow, sand is everywhere!','grass white with frost','frost on a car window','low_iq','exclamation'),
(378,'en','The sunrise is super golden.','The sunrise is super grey.','flying into the sunrise','waking up before sunrise','slang','none'),
(577,'en','She predicted the rain. He didn''t.','She predicted the snow. He didn''t.','predicting the rain','predicting the lottery numbers','gossip','banter'),
(1000,'en','The climate is getting warmer.','The climate is getting colder.','a changing mountain climate','a tropical island climate','nerd','none'),
(1173,'en','Lightning is hitting the sea!','Lightning is hitting a tree!','lightning over the sea','lightning over a city','dramatic','exclamation'),
(1270,'en','She is stomping in a puddle.','She is stomping in the snow.','stomping into a puddle','a puddle of spilled milk','chill','none'),
(1308,'en','Even her shadow is dancing!','Even her friend is dancing!','a giant wall shadow','a shadow under a tree','dramatic','exclamation'),
(1620,'en','Heaven looks very busy today.','Heaven looks very empty today.','cherubs flying in heaven','a heaven full of saints','ironic','exaggeration'),
(1786,'en','Meteors are falling like rain.','Leaves are falling like rain.','meteors raining down','a meteor in a museum','nerd','none'),
(1856,'en','The figure is tiny. The sky is big.','The figure is huge. The sky is big.','a tiny figure on grass','a tiny shelf figure','low_iq','none'),
(1981,'en','Waves are crashing into the lighthouse!','Waves are crashing into the harbour!','waves crashing on rocks','crashing on a friend''s sofa','dramatic','exclamation'),
(2000,'en','Moonlight is shining on water.','Sunlight is shining on water.','moonlight on a marsh','moonlight in a bedroom','chill','none'),
(2021,'en','Constellations fill the sky.','Rainbows fill the sky.','constellations above the house','constellations on a map','nerd','none'),
(2061,'en','The galaxy is showing off.','The moon is showing off.','a glowing purple galaxy','a galaxy on a T-shirt','slang','exaggeration'),
(2151,'en','The crescent moon is chilling.','The full moon is chilling.','a crescent moon in clouds','a crescent moon at noon','slang','none'),
(2225,'en','Poor girl, her hair is soaked.','Poor girl, her hair is dry.','soaked in heavy rain','soaked in hot water','gossip','none'),
(2373,'en','The universe looks crowded.','The universe looks empty.','a universe full of planets','a universe without stars','ironic','exaggeration'),
(2462,'en','The starry sky has a moon.','The starry sky has a rainbow.','a starry night sky','a starry city night','chill','none'),
(2465,'en','She is floating. No big deal.','She is swimming. No big deal.','floating in a blue sky','floating in a pool','ironic','understatement'),
(2484,'en','The church has a tall steeple.','The castle has a tall steeple.','a church steeple in snow','a steeple in a city','chill','none'),
(2523,'en','The snowfall is heavy tonight.','The rainfall is heavy tonight.','heavy snowfall over a village','light snowfall in a city','chill','none'),
(2531,'en','Even the sky sparkles for them.','Even the sea sparkles for them.','a sparkling night sky','sparkling water in a glass','flirt','none'),
(2949,'en','An astronaut sees an eclipse.','An astronaut sees a rainbow.','watching a solar eclipse','an eclipse of the moon','nerd','none'),
(2981,'en','This tornado is made of code.','This tornado is made of dust.','a tornado made of code','a tornado over a farm','nerd','none'),
(3059,'en','Northern lights are a vibe.','The fireworks are a vibe.','northern lights over mountains','northern lights over a city','slang','none'),
(3395,'en','Fog hides the mountains.','Fog hides the city.','thick fog on the peaks','fog on a bathroom mirror','chill','none'),
(3497,'en','She is walking into the sunset. Classic.','She is walking into the sea. Classic.','walking into the sunset','watching a sunset by car','ironic','cliche'),
(4093,'en','Wow, the moon is so round.','Wow, the moon is so red.','a round grey moon','a round of applause','low_iq','none'),
(4200,'en','The sea is gold at sunset.','The sea is red at sunset.','sea and sky in gold','a ring made of gold','chill','none'),
(4286,'en','She is fanning herself.','She is fanning the cat.','fanning herself in the heat','fanning a barbecue fire','chill','none'),
(4414,'en','Going uphill is a real struggle.','Going downhill is a real struggle.','a struggle against the wind','a struggle with homework','dramatic','none'),
(4441,'en','Wow, her breath makes clouds.','Wow, her breath makes bubbles.','a cloud of warm breath','a breath of fresh air','low_iq','none'),
(4484,'en','Dawn lights up the peaks first.','Dawn lights up the trees first.','the first light of dawn','dawn in a busy city','nerd','none'),
(4493,'en','He is struggling at the wheel.','He is sleeping at the wheel.','struggling with the wheel','struggling with a heavy bag','dramatic','none'),
(4661,'en','Fall is here in the park!','Spring is here in the park!','yellow leaves in the fall','fall fashion in a shop','dramatic','none'),
(4721,'en','Nooo, the rainbow is fading!','Nooo, the rainbow is growing!','a rainbow fading away','a photo fading away','dramatic','exclamation'),
(4817,'en','Even the tree melts in this drought.','Even the dog melts in this drought.','a drought with cracked ground','the end of a drought','dramatic','exaggeration'),
(4821,'en','Sunset pizza is here!','Sunset sushi is here!','pizza delivery at sunset','a sunset over the mountains','flirt','exclamation'),
(5002,'en','They are jumping in at dusk.','They are jumping in at noon.','a forest lake at dusk','dusk in a big city','chill','none'),
(5041,'en','A white flash lights the roof.','A green flash lights the roof.','a blinding white flash','a camera flash indoors','dramatic','none'),
(5252,'en','Tropical fruit is on sale.','Frozen fruit is on sale.','a pile of tropical fruit','a tropical fish tank','business','none'),
(5446,'en','The hills are misty.','The hills are sunny.','misty hills over a lake','misty eyes at a wedding','chill','none'),
(240,'en','Grandma calls it a draw.','The dog calls it a draw.','an arm-wrestling draw','a draw in football','gossip','guessing'),
(322,'en','She is gambling on red.','She is gambling on black.','gambling at a roulette wheel','gambling on horse races','dramatic','none'),
(515,'en','She overcame the wall!','She overcame the river!','overcoming a climbing wall','overcoming a fear of dogs','dramatic','exclamation'),
(564,'en','Their podium is made of foam.','Their podium is made of gold.','a foam block podium','a podium at a conference','ironic','cheap_quality'),
(594,'en','The jump qualified her.','The swim qualified her.','qualifying for the next round','qualifying as a doctor','chill','none'),
(794,'en','The boy won the tournament!','The sailor won the tournament!','an arm-wrestling tournament','a chess tournament','dramatic','exclamation'),
(847,'en','Their victory is clear.','Their defeat is clear.','a boat race victory','a chess game victory','chill','none'),
(1441,'en','Her win was worth the effort.','Her win was worth the money.','worth the effort','an effort to stay awake','chill','none'),
(4617,'en','Men in armour are fighting.','Men in suits are fighting.','fighting with shields','fighting over a parking space','dramatic','none'),
(4618,'en','Here comes the charge!','Here comes the rain!','a charge with shields','a charge for extra bags','dramatic','exclamation'),
(4652,'en','She is competing with a man.','She is competing with a child.','competing at arm-wrestling','competing in a cooking show','chill','none'),
(4752,'en','Failure! The oven did it.','Success! The oven did it.','a baking failure','a failure in maths','dramatic','blaming_someone'),
(4879,'en','She is lifting a car in this competition!','She is lifting a bike in this competition!','a strongwoman competition','a singing competition on TV','dramatic','exclamation'),
(5050,'en','He lost, and the guests left.','He won, and the guests left.','losing an election','losing his car keys','gossip','none'),
(5182,'en','Look, the mural is her achievement.','Look, the mural is his achievement.','a big mural achievement','a video game achievement','gossip','none'),
(5349,'en','She is awarding yet another medal!','She is awarding yet another trophy!','awarding a medal','awarding a song prize','dramatic','exaggeration'),
(5366,'en','He is surrendering!','He is attacking!','surrendering with raised hands','surrendering his passport','dramatic','exclamation'),
(5384,'en','The champions are going wild.','The champions are going home.','champions in striped shirts','a champion on a podium','slang','none'),
(5385,'en','The rally ends in a win.','The rally ends in a loss.','a beach volleyball win','a win at cards','chill','none'),
(4813,'en','The harbour is busy.','The harbour is empty.','a busy harbour at sunrise','a harbour in a storm','chill','none'),
(2641,'en','Rays are filling the sky!','Rays are filling the room!','golden rays of light','rays through a window','dramatic','exclamation'),
(4999,'en','He''s combating a swordsman.','He''s combating an archer.','combating a swordsman','combating a bad cold','chill','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
