begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(131,'hu','Ennél jobban még sosem telefonált!','Ennél rosszabbul még sosem telefonált!','vidáman telefonál','segítségért telefonál','dramatic','exaggeration'),
(187,'hu','Teljesen összezavarodott az útmutatótól.','Teljesen összezavarodott a térképtől.','összezavarodott az útmutatótól','összezavarodott a dátum miatt','ironic','blaming_someone'),
(196,'hu','A bátorság vitte át!','Egy drótkötélpálya vitte át!','átkelés bátorsággal','bátorság a leugráshoz','dramatic','exclamation'),
(278,'hu','Guggolás napfelkeltekor a parkban!','Guggolás napfelkeltekor a tengerparton!','mély guggolás a parkban','guggolás nehéz súlyokkal','slang','exclamation'),
(281,'hu','Tökéletes a szemceruzás macskaszeme. Ez az!','Katasztrófa a szemceruzás macskaszeme. Ez az!','szemceruzás macskaszem','szemceruza a szájon','slang','exclamation'),
(394,'hu','Forróság van! A ventilátort öleli.','Forróság van! A kutyát öleli.','forró, napos nap','egy csésze forró tea','dramatic','exclamation'),
(447,'hu','Az ajakápoló a nap hőse!','A kézkrém a nap hőse!','ajakápoló felkenése','ajakápoló vásárlása','dramatic','cliche'),
(526,'hu','A sugárpisztoly lebénította!','A vízipisztoly lebénította!','sugárpisztollyal lebénítva','a félelemtől lebénulva','dramatic','exclamation'),
(575,'hu','A lány külső akkumulátora mentette meg a helyzetet!','A fiú külső akkumulátora mentette meg a helyzetet!','töltés külső akkumulátorról','külső akkumulátor otthon','dramatic','cliche'),
(724,'hu','Minden csobbanás egyre nagyobb!','Minden csobbanás egyre kisebb!','hatalmas csobbanás','egy csöpp tej','dramatic','exclamation'),
(730,'hu','A személyzet együtt pózol.','A személyzet együtt eszik.','éttermi személyzet munka közben','személyzet a vonaton','chill','none'),
(776,'hu','Egy csepp egy nagy szomjúságra.','Egy keksz egy nagy szomjúságra.','szörnyű szomjúság','kalandszomj','ironic','understatement'),
(848,'hu','Ecet? Az arca szerint nem!','Méz? Az arca szerint nem!','egy löttyintésnyi ecet','takarítás ecettel','slang','exclamation'),
(877,'hu','Sáros győztes? Legenda!','Patyolattiszta győztes? Legenda!','sárfutás győztese','úszóverseny győztese','slang','none'),
(943,'hu','Kiragasztja az óriásplakátot.','Kifesti az óriásplakátot.','üres óriásplakát','óriásplakát egy buszon','chill','none'),
(1040,'hu','Hamarosan elvált emberek lesznek.','Hamarosan házasok lesznek.','épp elválnak','épp összeházasodnak','gossip','guessing'),
(1218,'hu','Senki sincs a játszótéren. Hátborzongató!','Gyerekek vannak a játszótéren. Hátborzongató!','senki sincs a hintákon','senki sincs a strandon','dramatic','exclamation'),
(1219,'hu','Senki sem jött el. Szuper buli.','Mindenki eljött. Szuper buli.','senki sincs az asztalnál','zsúfolt vacsoraasztal','ironic','understatement'),
(1433,'hu','Semmi extra, csak táncolnak itthon.','Semmi extra, csak vacsoráznak itthon.','táncolás jelmezekben','táncolás a színpadon','chill','understatement'),
(1484,'hu','Ennek a zenének nincs lejátszógombja.','Ennek a versnek nincs lejátszógombja.','régi kotta','régi zenedoboz','ironic','exaggeration'),
(1765,'hu','De kapzsi! El a kezekkel az aranytól!','De kapzsi! El a kezekkel a tortától!','kapzsi férfi érmékkel','kapzsi kutya kajával','dramatic','exclamation'),
(1783,'hu','Négy gyerek egy ölben, mindegyiknek jár egy ölelés.','Négy gyerek egy ölben, mindegyiknek jár egy ajándék.','férfi minden gyereket megölel','férfi minden gyereket tanít','chill','none'),
(1808,'hu','Tesó, a headsetje óriási.','Tesó, a sapkája óriási.','masszív headset','headset egy pilótán','slang','none'),
(1920,'hu','A kiborgnak világít a feje.','A kiborgnak világít a keze.','neonvárosi kiborg','kiborg az erdőben','nerd','none'),
(1944,'hu','Tény: látszanak a bordái.','Tény: látszik a szíve.','bordakosár','oldalas a grillen','nerd','none'),
(2177,'hu','Még a hold is eljött a DJ miatt!','Még a nap is eljött a DJ miatt!','DJ az utcán','DJ egy klubban','slang','exaggeration'),
(2220,'hu','Gondosan számolja a pénzt.','Gondosan számolja az érméket.','bankjegyköteget számol','visszaszámolja a másodperceket','business','none'),
(2262,'hu','Pontok és vonalak kapcsolják össze őket.','Pontok és vonalak választják el őket.','két embert összekapcsoló vonalak','telefonhoz csatlakoztatott kábel','nerd','none'),
(2280,'hu','Átöleli őt naplementekor.','Átöleli őt egy autóban.','átölelik egymást egy vitorláson','felkarolnak egy új ötletet','flirt','none'),
(2401,'hu','Ösvény egy fantáziavilágba.','Ösvény egy nyüzsgő városba.','erdei ösvény a fantáziavilágban','fantasy könyvborító','chill','none'),
(2493,'hu','A farm foltvarrott takaróra van varrva.','A farm egy zászlóra van varrva.','farmot ábrázoló foltvarrott takaró','foltvarrott takaró az ágyon','nerd','none'),
(2529,'hu','Szelíd arca van.','Szelíd kutyája van.','szelíd, nyugodt arc','szelíd, nyugodt tenger','chill','none'),
(2549,'hu','Apa és fia ujjongnak!','Apa és fia sírnak!','fiát cipelő apa','bevásárlást cipelő apa','dramatic','exclamation'),
(2578,'hu','A sisakplexi olyan, mint egy tükör.','A sisakplexi olyan, mint egy ablak.','tükröződő sisakplexi','siltes sapka','chill','none'),
(2586,'hu','A legjobb barátság ever: egy óriásrobot és egy kislány.','A legjobb barátság ever: egy óriáskutya és egy kislány.','szokatlan barátság','barátságkarkötő','dramatic','exaggeration'),
(2679,'hu','Nagyon sietve rohan el!','Egyáltalán nem siet!','sietve futni','sietve enni','dramatic','exclamation'),
(3070,'hu','Egy fa van a kezek fölött.','Egy macska van a kezek fölött.','két tálat formáló kéz','két kéz zsebben','chill','none'),
(3304,'hu','A hokiütő a koronghoz kell, azt hiszem.','A hokiütő a labdához kell, azt hiszem.','hokiütő a jégen','törött hokiütő','low_iq','guessing'),
(3647,'hu','Épp áttörli a Holdat.','Épp áttörli a Napot.','áttörli a Holdat','áttörli a sisakplexijét','chill','none'),
(4008,'hu','Rázza az almafát!','Felmászik az almafára!','faágat ráz','kezet ráz','dramatic','exclamation'),
(4029,'hu','Az üveg megütötte, és leesett!','A labda megütötte, és leesett!','leesik egy kockáról','kopogás az ajtón','slang','exclamation'),
(4037,'hu','Valaki főzött: omlett lett belőle.','Valaki főzött: palacsinta lett belőle.','omlettet süt','tésztát főz','chill','none'),
(4040,'hu','Étkezés: a lánynak saláta, a fiúnak óriási burger.','Étkezés: a lánynak pizza, a fiúnak óriási burger.','étkezés a strandon','étkezés a konyhában','gossip','banter'),
(4086,'hu','A szúnyog mindjárt megcsíp valakit.','A pók mindjárt megcsíp valakit.','alvó férfit csíp','alvó kutyát csíp','chill','guessing'),
(4094,'hu','A takarmányos zsákok színesek.','A takarmányos zsákok mind fehérek.','takarmány zsákokban','krumpli zsákokban','chill','none'),
(4101,'hu','Egy előadó büszkén megmutatja a pávafarkát.','Egy előadó büszkén megmutatja a zászlóját.','óriási pávafarkat mutat meg','fehér zászlót mutat fel','chill','none'),
(4107,'hu','Letakartak egy elefántot, és tigris lett belőle!','Letakartak egy elefántot, és oroszlán lett belőle!','letakarni az elefántot','letakarni a tigrist','dramatic','exclamation'),
(4129,'hu','A kiskutya elhagyja az otthonát.','A kiskutya hazaér.','kalapban hagyja el az otthonát','kalapban jön haza','chill','none'),
(4167,'hu','Sötét barlang, fényes kijárat.','Sötét barlang, nincs kijárat.','fényes barlangkijárat','autópálya-kijárati tábla','dramatic','none'),
(4187,'hu','A papagájok halottnak tettetik magukat!','A papagájok labdáznak!','halottat játszó papagájok','kártyázó papagájok','dramatic','exclamation'),
(4194,'hu','Micsoda kocsikázás egy apró dzsipben!','Micsoda utazás egy apró csónakban!','kocsikázás egy játékdzsippel','hajókázás egy játékcsónakkal','dramatic','exclamation'),
(4199,'hu','A lábát a tó vizében húzza maga után.','A kezét a tó vizében húzza maga után.','lábát húzza a vízben','csónakot vonszol a vízhez','chill','none'),
(4245,'hu','Ingyen csúsznak!','Ingyen síelnek!','csúszás egy vízcsatornában','lecsúszás egy havas dombon','dramatic','cheap_quality'),
(4284,'hu','Nagy rohanásban távozik!','Autóval távozik!','reggeli rohanás','csúcsforgalom','dramatic','exclamation'),
(4319,'hu','A csíkok beleolvadnak a környezetbe.','A csíkok egyre szélesebbek.','krém bedolgozása a bőrbe','gyümölcs turmixolása','chill','none'),
(4347,'hu','Egy csónak szállítja át.','Egy busz szállítja át.','embereket átszállítani','árut szállítani felfelé a folyón','chill','none'),
(4402,'hu','Alma, burger, dinnye: nagy étvágy!','Alma, pizza, dinnye: nagy étvágy!','óriási piknikétvágy','semmi étvágy','slang','exaggeration'),
(4526,'hu','A lány nagyon töri a fejét ezen a választáson.','A srác nagyon töri a fejét ezen a választáson.','szavazás egy választáson','választást nyerni','ironic','exaggeration'),
(4535,'hu','Papírt dobál a tanórán!','Krétát dobál a tanórán!','matekóra','úszóóra','dramatic','exclamation'),
(4612,'hu','Ő árulja a legjobb barackot.','Ő árulja a legjobb almát.','barackot árul a piacon','almát árul a piacon','gossip','cliche'),
(4633,'hu','A régi autótól teljesen kétségbeesett.','A régi furgontól teljesen kétségbeesett.','kétségbeesett az esőben','kétségbeesetten vágyik egy kávéra','dramatic','cheap_quality'),
(4643,'hu','Jól halad a produkció!','Rosszul halad a produkció!','otthoni filmprodukció','gyári futószalag','dramatic','exclamation'),
(4678,'hu','Mindenki eszik valamit.','Mindenki teát iszik.','tripla burgert eszik','egy tál salátát eszik','chill','none'),
(4871,'hu','Végtelen a regisztrációs sor.','Üres a regisztrációs sor.','regisztrációs pult','autó rendszámtáblája','dramatic','exaggeration'),
(4986,'hu','A fal kicsit világos.','A fal kicsit sötét.','élénkkék képernyők','napsütéses világos nap','ironic','understatement'),
(5019,'hu','Marhahúst grillez.','Halat grillez.','grillezett marhahússzeletek','marhahúsburger sült krumplival','chill','none'),
(5055,'hu','Két rózsaszín szerv: a tüdő.','Két rózsaszín szerv: a vesék.','egy pár légzőszerv','szóló templomi orgona','nerd','none'),
(5057,'hu','Mindenfelé repül a postája!','Mindenfelé repül a készpénze!','posta a postaládából','levelek a számítógépen','dramatic','exaggeration'),
(5093,'hu','Kicsit benőtte a gaz a pázsitot.','Kicsit benőtte a gaz a medencét.','magasra nőtt fű lenyírása','elburjánzott sövény','ironic','understatement'),
(5122,'hu','Mindannyian elérték a céljukat.','Egyikük sem érte el a célját.','nehéz cél elérése','jó jegyek elérése','chill','none'),
(5159,'hu','A cső direkt lefröcskölte.','A kutya direkt lefröcskölte.','a vízszerelő arcának lefröcskölése','a konyhai növények lefröcskölése','ironic','blaming_someone'),
(5179,'hu','Benyúl a sütőbe.','Benyúl a hűtőbe.','a forró sütő felé nyúl','eléri a legfelső polcot','chill','none'),
(5181,'hu','Az aláírása kék tintás.','Az aláírása piros tintás.','friss kék aláírás','aláírás egy csekken','business','none'),
(5182,'hu','Nézd, a falfestmény a lány teljesítménye!','Nézd, a falfestmény a srác teljesítménye!','nagy teljesítmény: egy falfestmény','videojátékos teljesítmény','gossip','none'),
(5187,'hu','Erős fiú! Szekeret húz!','Erős fiú! Autót húz!','szekér húzása','lovaskocsi húzása','low_iq','exclamation'),
(5225,'hu','Messze az élen fejezi be, durva!','Messze leghátul fejezi be, durva!','verseny befejezése','házi befejezése','slang','none'),
(5261,'hu','Még a kocogó is megkapta a részét!','Még a biciklis is megkapta a részét!','rész a pizzából','részesedés a cégből','gossip','exclamation'),
(5268,'hu','Céloz a puskájával.','Tisztítja a puskáját.','fekve lövés puskával','síelés puskával a hátán','chill','none'),
(5317,'hu','Repülnek a fodrai!','Repülnek a cipői!','több réteg piros fodor','fodrok az inggalléron','dramatic','exclamation'),
(5334,'hu','A szurkolók tisztelik ezt a pillanatot.','A szurkolók figyelmen kívül hagyják ezt a pillanatot.','a pillanat tiszteletben tartása','a sebességkorlátozás tiszteletben tartása','chill','none'),
(5347,'hu','A forgalom lassul, aztán teljes megállás.','A vonatok lassulnak, aztán teljes megállás.','megállás a forgalom miatt','megállás egy kávéra','chill','none'),
(5378,'hu','Megteríti az asztalt.','Beállítja az ébresztőt.','megteríteni az asztalt','beállítani az ébresztőt','business','none'),
(5423,'hu','A hátizsákja bejárja az egész világot.','A hátizsákja egy városban marad.','világ körüli utazás','világméretű telefonhálózat','chill','none'),
(5431,'hu','Hőlégballonnal utazik.','Repülőgéppel utazik.','hőlégballon sziklák felett','parti lufi','chill','none'),
(5444,'hu','Együttműködnek egy térkép elkészítésében.','Együttműködnek egy autó megépítésében.','együttműködés egy kirakós kirakásában','együttműködés a rendőrséggel','chill','none'),
(5507,'hu','Jól érzi magát az állatkertben.','Jól érzi magát a strandon.','egy nap az állatkertben','egy nap a farmon','chill','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
