begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(329,'hu','A gáz lángja kék.','A gáz lángja zöld.','kék gázláng','gáz az autóban','business','none'),
(330,'hu','Épp időben ért a kapuhoz!','Túl későn ért a kapuhoz!','rohanás a kapuhoz','egy kerti kapu','dramatic','exclamation'),
(331,'hu','Egy úriember menti meg a narancsokat!','Egy úriember menti meg az almákat!','úriember esernyővel','úriember kutyával','dramatic','exclamation'),
(332,'hu','A zsiráf ebédel.','Az oroszlán ebédel.','leveleket evő zsiráf','füvet evő zsiráf','business','none'),
(333,'hu','Ez a lány mindenre képes!','Ez a fiú mindenre képes!','ugrókötelező lány','iskolát lógó lány','dramatic','exaggeration'),
(334,'hu','A pohara jéghideg.','A pohara forró.','egy pohár limonádé','egy pohár bor','chill','none'),
(336,'hu','Szemüveg fel, több kacsa!','Szemüveg fel, több liba!','kerek szemüveg pucolása','kerek szemüveg eltörése','low_iq','exclamation'),
(338,'hu','Megöleli a földgömbjét!','Megöleli a lámpáját!','asztali földgömb pörgetése','földgömb rajzolása','dramatic','exclamation'),
(339,'hu','Megy lefelé az utcán.','Megy felfelé a lépcsőn.','lefelé menni az utcán','hazamenni','chill','none'),
(340,'hu','Saját kaput hoztak!','Saját padot hoztak!','kapu a téren','egy kerti kapu','dramatic','exclamation'),
(341,'hu','A kecske a szennyest eszi!','A kecske a virágokat eszi!','kecske a tetőn','kecske az autóban','dramatic','exclamation'),
(342,'hu','Védőszemüveg fel, tök szorosan!','Sisak fel, tök szorosan!','kék védőszemüveg úszáshoz','síszemüveg a hóban','slang','exclamation'),
(343,'hu','Megragadta a gyűrűt!','Megragadta az érmét!','gyűrű megragadása a víz alatt','a medencelétra megragadása','dramatic','exclamation'),
(344,'hu','Kicsit túlságosan szereti az aranyat.','Kicsit túlságosan szereti a macskákat.','nehéz aranyrúd','aranyérem','gossip','understatement'),
(346,'hu','Golflabda a lyukban. Igen!','Golflabda a vízben. Igen!','golfütés naplementekor','golflabda a vízben','dramatic','exclamation'),
(347,'hu','Imádnak egy kis pletykát.','Imádnak egy kis focit.','szaftos pletyka suttogása','pletyka egy magazinban','gossip','understatement'),
(348,'hu','A kormány igennel szavazott.','A kormány nemmel szavazott.','kormányszavazás','diákönkormányzat','business','none'),
(349,'hu','Horgászat, sakk és egy ölelés: a világ legjobb nagypapája.','Horgászat, sakk és egy ölelés: a világ legjobb nagymamája.','nagypapa és unokája','nagypapa és a kutyája','slang','cliche'),
(350,'hu','Hazajött az unokája!','Hazajött a férje!','ölelés az unokájával','ölelés a férjével','dramatic','exclamation'),
(351,'hu','A füvön chillelnek.','A homokon chillelnek.','fekvés a puha füvön','a puha fű nyírása','slang','none'),
(352,'hu','A sajton grillcsíkok vannak.','A kenyéren grillcsíkok vannak.','sajt a forró grillen','hal a forró grillen','chill','none'),
(353,'hu','A vendég ajándékkal érkezett.','A vendég kutyával érkezett.','vendég fogadása','vendégszoba','chill','none'),
(354,'hu','Az útikönyvnek igaza lett!','A térképnek igaza lett!','vastag útikönyv','vastag telefonkönyv','gossip','exclamation'),
(355,'hu','Nem tud enni. Bűntudat!','Nem tud aludni. Bűntudat!','bűntudat egy törött kancsó miatt','bűntudat egy törött telefon miatt','dramatic','exclamation'),
(356,'hu','Mostantól ebben az edzőteremben fog lakni.','Mostantól ebben a kocsmában fog lakni.','világos, új edzőterem','tesióra az iskolában','low_iq','guessing'),
(357,'hu','A hajkeféje egy mikrofon!','A fésűje egy mikrofon!','fa hajkefe','hajkefe lóhoz','slang','exclamation'),
(358,'hu','Óvatos munka azzal a kalapáccsal.','Óvatos munka azzal a kanállal.','kalapács egy szögön','kalapács a szerszámosládában','flirt','none'),
(359,'hu','Tele pofazacskó, boldog hörcsög.','Üres pofazacskó, boldog hörcsög.','hörcsög a mókuskerékben','hörcsög egy futógömbben','slang','none'),
(360,'hu','Kézfertőtlenítő, aztán szamosza.','Kézkrém, aztán szamosza.','egy pumpa kézfertőtlenítő','kézfertőtlenítő az ajtónál','business','none'),
(361,'hu','Nincs virág? Csomagolj be nyalókát.','Nincs virág? Csomagolj be kekszet.','nyalókák becsomagolása papírba','kekszek becsomagolása papírba','ironic','cheap_quality'),
(362,'hu','Olyan boldog, hogy az már nem is igaz.','Olyan szomorú, hogy az már nem is igaz.','boldog tengerparti séta','boldog szülinapi buli','slang','exaggeration'),
(363,'hu','Egész éjjel kutatást végez.','Egész délelőtt kutatást végez.','éjszakai kutatás','kutatás a szabadban','chill','exaggeration'),
(364,'hu','Azt mondja, ő nem művész.','Azt mondja, ő híres művész.','nem művész','egy művész nagy műterme','chill','none'),
(365,'hu','Túl hangos a fejhallgatója!','Túl hangosak a hangszórói!','fejhallgató megosztása','fejhallgató megjavítása','slang','guessing'),
(366,'hu','Meggyógyult a karja. Igen!','Meggyógyult a lába. Igen!','meggyógyult kar','meggyógyult láb','dramatic','exclamation'),
(367,'hu','Túl nagy a hőség egy jégkrémhez!','Túl sok az eső egy jégkrémhez!','hőség egy faluban','hőség a tűz mellett','dramatic','exaggeration'),
(368,'hu','Szállítás helikopterrel? Menő!','Szállítás drónnal? Menő!','piros helikopteres szállítás','helikopter egy hajón','slang','exclamation'),
(369,'hu','Épp motorozik.','Épp lovagol.','sportmotorral motorozni','autózni','chill','none'),
(370,'hu','A piros sisak megtette a dolgát.','A kék sisak megtette a dolgát.','piros gördeszkás sisak','sisak egy motoron','chill','understatement'),
(371,'hu','Friss fűszernövények a tésztába, nyami.','Friss fűszernövények a pizzára, nyami.','friss fűszernövények az ablakból','gyógytea egy bögrében','slang','none'),
(372,'hu','Trükköket csinál egy tetőn.','Trükköket csinál egy tengerparton.','trükkök labdával','kártyatrükkök','chill','none'),
(373,'hu','Egy stadion tele piros szurkolókkal.','Egy stadion tele kék szurkolókkal.','zsúfolt focistadion','üres stadion éjjel','chill','none'),
(374,'hu','Hajnalban kocog.','Hajnalban biciklizik.','kocogás egy üres úton','kocogás egy kutyával','chill','none'),
(375,'hu','Jól néz ki egy versenyautóban.','Jól néz ki egy taxiban.','versenyautó napfelkeltekor','versenyautó éjjel','flirt','none'),
(376,'hu','Tiszta vadon, sehol senki.','Tiszta sivatag, sehol senki.','folyó a vadonban','út a vadonon át','chill','none'),
(377,'hu','Egy stúdióban lép fel.','Egy templomban lép fel.','fellépés, mint egy klipben','fellépés egy nagy stadionban','chill','none'),
(378,'hu','Tök aranyszínű a napkelte.','Tök szürke a napkelte.','repülés a napkeltébe','ébredés napkelte előtt','slang','none'),
(379,'hu','Videóblogot forgat.','Esküvőt forgat.','reggeli videóblog forgatása','utazós videóblog vágása','chill','none'),
(380,'hu','Az utazása egy tetőn ért véget.','Az utazása egy hajón ért véget.','hosszú városi utazás','utazás repülővel','chill','none'),
(381,'hu','Annyira megijedt, hogy meg sem meri enni a szőlőt.','Annyira megijedt, hogy meg sem meri enni az almát.','megijeszteni egy barátot','elijeszteni a madarakat','low_iq','guessing'),
(382,'hu','Hű, milyen magasan dolgoznak!','Hű, milyen alacsonyan dolgoznak!','magasan az utca felett','magasan egy hegyen','dramatic','exclamation'),
(383,'hu','Túrázás egészen a csúcsig!','Síelés egészen a csúcsig!','túrázás fel a hegyre','túrázás a sivatagban','dramatic','exclamation'),
(385,'hu','Eltalálta – egyenesen fel az égbe!','Eltalálta – egyenesen le a fűbe!','magasra ütött labda','vízbe ütött labda','dramatic','exaggeration'),
(386,'hu','A hobbija a makettépítés.','A hobbija a házépítés.','hobbi hajómakettekkel','hobbi igazi hajókkal','chill','none'),
(387,'hu','Biztonsági kamera: a kutya volt.','Biztonsági kamera: a macska volt.','éjszakai biztonsági kamerás felvétel','bolti biztonsági kamera','gossip','blaming_someone'),
(388,'hu','A házi feladata sosem ér véget.','A szünidője sosem ér véget.','házi feladat késő éjjel','házi feladat a buszon','dramatic','exaggeration'),
(389,'hu','A méz olyan lassú!','A méz olyan gyors!','méz egy mézcsorgatón','méz a teában','slang','exclamation'),
(390,'hu','Szuper kényelmes a kapucnis pulóvere.','Szuper kényelmes a dzsekije.','kapucnis pulóver felvétele','kapucnis pulóver mosása','slang','exaggeration'),
(391,'hu','Visszajött a hajó. A remény győz!','Visszajött a repülő. A remény győz!','remény a hajóért','remény a jó időért','dramatic','exclamation'),
(392,'hu','A lovon lovagol.','A tevén lovagol.','ló és lovasa','ló és a szekere','chill','none'),
(393,'hu','Egy hosztelágy tíz euró.','Egy hosztelágy hat euró.','emeletes ágy egy hosztelben','szoba egy hotelben','business','none'),
(395,'hu','A világ legjobb háza!','A világ legjobb autója!','beköltözés egy sárga házba','beköltözés egy fehér házba','slang','exaggeration'),
(396,'hu','Ez az év ölelése!','Ez az év verekedése!','hatalmas pörgős ölelés','gyors búcsúölelés','dramatic','exaggeration'),
(397,'hu','Vadászaton vannak az erdőben.','Vadászaton vannak a sivatagban.','vadászat őszi erdőben','vadászat a hóban','chill','none'),
(398,'hu','Előbb a higiénia, aztán hüvelykujj fel.','Előbb a higiénia, aztán pacsi.','jó higiénia a fürdőszobában','jó higiénia a konyhában','chill','none'),
(399,'hu','Veszít a fagylaltja ellen.','Veszít a hot dogja ellen.','olvadó fagylalt','fagylalt kehelyben','low_iq','exaggeration'),
(400,'hu','A 9-es jégkorongozik.','A 7-es jégkorongozik.','jégkorong a pályán','jégkorong egy tavon','chill','none'),
(401,'hu','Szép megállás azon a korcsolyán.','Szép megállás azon a snowboardon.','korcsolya befűzése','korcsolya a polcon','flirt','none'),
(402,'hu','Csúszkál a jégen.','Csúszkál a füvön.','buborékok a jégben','jég egy italban','chill','none'),
(404,'hu','Káosz a tanteremben, de ő nyugodt.','Káosz a konyhában, de ő nyugodt.','zajos tanterem','csendes tanterem','gossip','understatement'),
(405,'hu','Kint hó, bent a barátok.','Kint hó, bent a kutyák.','meleg bent a kunyhóban','bent egy sátorban','chill','none'),
(406,'hu','Forró vasat kalapál.','Forró üveget kalapál.','forró vas kalapálása','forró ing vasalása','chill','none'),
(407,'hu','Ez komoly?! Egy egész sziget kettőnek!','Ez komoly?! Egy egész sziget tíznek!','kis trópusi sziget','konyhasziget','dramatic','exaggeration'),
(408,'hu','Rajta a dzseki. Így már sokkal jobb.','Rajta a sál. Így már sokkal jobb.','barna dzseki becipzározása','dzseki egy széken','chill','none'),
(410,'hu','Vastagon keni a lekvárt.','Vékonyan keni a lekvárt.','lekvár pirítóson','lekváros fánk','chill','none'),
(411,'hu','Hű, ez a lány nagyon féltékeny.','Hű, ez a fiú nagyon féltékeny.','féltékeny egy másik táncosra','féltékeny a tanárára','gossip','exaggeration'),
(412,'hu','Megkapta a 7-es mezt!','Megkapta a 9-es mezt!','új 7-es mez','új 10-es mez','dramatic','exclamation'),
(413,'hu','A gyümölcslé rubinpiros.','A gyümölcslé élénk narancssárga.','friss gránátalmalé','narancslé dobozban','chill','none'),
(414,'hu','Átugrotta a lécet!','Átugrotta a kerítést!','átugrani a lécet','beugrani a medencébe','dramatic','exclamation'),
(415,'hu','Ennek a kengurunak utasa van.','Ennek a koalának utasa van.','kenguru a kicsinyével','kenguru bokszkesztyűben','chill','exaggeration'),
(416,'hu','A ketchup végre feladta!','A mustár végre feladta!','ketchup a sültkrumplin','ketchup egy hamburgeren','dramatic','exaggeration'),
(418,'hu','Saját kezűleg csinálta a kulcstartóját.','Saját kezűleg csinálta a nyakláncát.','kulcstartó pomponnal','kulcstartó fotóval','chill','none'),
(419,'hu','Labdát rúgnak.','Labdát dobálnak.','labda rugdosása','ajtó berúgása','chill','none'),
(422,'hu','Szuper magas a rúgása.','Szuper alacsony a rúgása.','rúgások a bokszzsákba','rúgás egy focilabdába','slang','none'),
(423,'hu','Légcsókot küld a lány, a srác elkapja!','Légcsókot küld a srác, a lány elkapja!','légcsókot dobni','jóéjt-csók','flirt','exclamation'),
(424,'hu','A kése kenyeret vág.','A kése sajtot vág.','nagy kenyérvágó kés','kis zsebkés','business','none'),
(426,'hu','A lány mászik, a srác csak a létrát tartja.','A lány mászik, a srác csak a kosarat tartja.','a létra megtartása','a létra festése','gossip','banter'),
(427,'hu','Elrepül a katicabogár.','A katicabogár egy levelet eszik.','katicabogár a fűben','katicabogár egy kézen','chill','none'),
(428,'hu','Kenu egy nyugodt tavon.','Kenu egy nyugodt tengeren.','nyugodt hegyi tó','befagyott tó','chill','none'),
(429,'hu','Tökéletesen landolt!','A vízben landolt!','landolás egy füves mezőn','repülőgép landoltatása','dramatic','exclamation'),
(430,'hu','A srác a saját nyelvére tanítja a lányt.','A lány a saját nyelvére tanítja a srácot.','új nyelv tanulása','lecke egy nyelvtanuló appban','chill','none'),
(431,'hu','Lusta? Dehogy, ez a srác egy „zseni”.','Lusta? Dehogy, ez a csaj egy „zseni”.','lusta férfi otthon','lusta macska otthon','ironic','bad_excuse'),
(432,'hu','Lámpással vezeti a csapatot.','Zseblámpával vezeti a csapatot.','túrázók vezetése lámpással','túrázók vezetése térképpel','chill','none'),
(435,'hu','Nyikorog a bőr!','Nyikorog a padló!','bőr nyújtása','bőrkanapé','dramatic','exclamation'),
(436,'hu','Mindenki balra lép.','Mindenki jobbra lép.','balra lépni','balra ugrani','chill','none'),
(437,'hu','Nyújtja a lábát.','Nyújtja a karját.','láb a falon','láb gipszben','chill','none'),
(438,'hu','Ez a citrom brutál savanyú!','Ez a citrom brutál édes!','citromgerezdbe harapni','citromtorta','slang','exclamation'),
(439,'hu','A limonádé tök hideg.','A limonádé tök forró.','egy befőttesüveg limonádé','egy doboz limonádé','slang','none'),
(440,'hu','Ez aztán a súlyemelés: fent a súlyzó!','Ez aztán a súlyemelés: fent a kanapé!','nehéz súlyzó emelése','kisgyerek emelése','dramatic','exclamation'),
(442,'hu','A csapatmunka legyőz egy nehéz dobozt.','A csapatmunka legyőz egy nehéz kanapét.','csapatmunka egy nehéz dobozzal','csapatmunka a focipályán','business','cliche'),
(443,'hu','Végre fény a padláson!','Végre fény a konyhában!','fény az ablakon át','gyertyafény','dramatic','exclamation'),
(444,'hu','Villám! Láttad ezt?','Szivárvány! Láttad ezt?','villámok nézése éjjel','villám nappal','slang','exclamation'),
(445,'hu','Tökéletes a fehér vonala!','Tökéletes a sárga vonala!','fehér vonal festése','egy sor ember','dramatic','exclamation'),
(446,'hu','Ránk üvölt az oroszlán!','Felénk rohan az oroszlán!','oroszlán a fűben','oroszlán egy ketrecben','dramatic','exclamation'),
(448,'hu','Olyan fényes a szájfény, mint az üveg.','Olyan matt a szájfény, mint a papír.','csillogó rózsaszín szájfény','sötétpiros szájfény','flirt','exaggeration'),
(449,'hu','Pszt, hallgatóznak!','Pszt, alszanak!','hallgatózás az erdőben','zenehallgatás','dramatic','exclamation'),
(450,'hu','A gyík napozik.','A gyík úszik.','gyík a falon','gyík egy dobozban','chill','none'),
(451,'hu','Bezárja az ajtót.','Kinyitja az ajtót.','hajóajtó bezárása','autóajtó bezárása','chill','none'),
(452,'hu','Még a kutyára is rátették a logót!','Még a macskára is rátették a logót!','logó egy nyakörvön','logó egy pólón','gossip','exclamation'),
(453,'hu','Magányos a menzán.','Magányos a könyvtárban.','magányos ebéd','magányos séta hazafelé','dramatic','none'),
(454,'hu','Leves és egy takaró: maga a szeretet.','Tea és egy takaró: maga a szeretet.','szeretet egy esős estén','szerelem első látásra','flirt','exaggeration'),
(455,'hu','A lánynak szuper erős tüdeje van.','A fiúnak szuper erős tüdeje van.','levegővel teli tüdő','füsttel teli tüdő','chill','exaggeration'),
(456,'hu','A magazin mostantól az övé.','Az újság mostantól az övé.','magazin lapozgatása','magazin a vonaton','gossip','guessing'),
(457,'hu','Egy sminkes csinálja meg a sminkjét.','Egy sminkes csinálja meg a haját.','sminkelés a tükör előtt','smink lemosása a tükör előtt','chill','none'),
(458,'hu','Egy nagydarab férfi egy ládát cipel.','Egy nagydarab férfi egy kutyát cipel.','sakkozó férfiak','kártyázó férfiak','chill','none'),
(459,'hu','A menedzser utasításokat oszt.','A menedzser virágot oszt.','menedzser csiptetős mappával','focicsapat menedzsere','business','none'),
(461,'hu','Utánozza a próbababát. Ikrek!','Festi a próbababát. Ikrek!','próbababa felöltöztetése','próbababa a kirakatban','low_iq','exclamation'),
(462,'hu','A térkép megtalálta a szökőkutat!','A térkép megtalálta a templomot!','nagy papírtérkép','térkép a telefonon','low_iq','exaggeration'),
(464,'hu','Filctollal rajzol.','Krétával rajzol.','vastag rózsaszín filctoll','filctoll egy táblán','chill','none'),
(465,'hu','A piacon vásárol.','A plázában vásárol.','nyüzsgő utcai piac','nyüzsgő utcabál','chill','none'),
(466,'hu','A szempillaspirál-arc: tátott száj.','A szempillaspirál-arc: szorosan csukott szem.','fekete szempillaspirál felvitele','arcon lefolyó szempillaspirál','gossip','cliche'),
(467,'hu','A mester egy vázát formáz.','A mester egy vázát fest.','fazekasmester','mester a zongoránál','chill','none'),
(468,'hu','A jógaszőnyegükön vannak.','A törölközőjükön vannak.','lila jógaszőnyeg','szőnyeg az ajtó előtt','chill','none'),
(469,'hu','Ezek a gyufák elsőre meggyulladnak!','Ez az öngyújtó elsőre meggyullad!','egy doboz gyufa','gyufaszálak egy hamutartóban','dramatic','exclamation'),
(470,'hu','A rétre zuhantak.','A folyóba zuhantak.','pipacsokkal teli rét','tehenekkel teli rét','chill','none'),
(471,'hu','A kutya a húst akarja.','A macska a húst akarja.','grillezett hús egy deszkán','nyers hús a boltban','low_iq','guessing'),
(472,'hu','A szerelő egy autót javít.','A szerelő egy biciklit javít.','szerelő a műhelyben','szerelő az úton','chill','none'),
(473,'hu','Beleharap az aranyérmébe. Tényleg arany?','Beleharap az aranygyűrűjébe. Tényleg arany?','aranyérembe harapni','érem egy dobozban','dramatic','guessing'),
(474,'hu','Csoportos meditáció naplementekor.','Csoportos meditáció a tengerparton.','meditáció egy fa teraszon','meditáció egy templomban','chill','none'),
(475,'hu','Minden emléktől mosolyog.','Minden emléktől sír.','egy doboz régi emlék','fényképezőgép memóriakártyája','chill','none'),
(476,'hu','Mikroszkópot használ.','Teleszkópot használ.','levél a mikroszkóp alatt','bogár a mikroszkóp alatt','nerd','none'),
(477,'hu','A mikró a legjobb tévéműsor.','A sütő a legjobb tévéműsor.','a mikró bámulása','a mikró tisztítása','ironic','exaggeration'),
(478,'hu','Mindenkinek tejbajusza van!','Senkinek sincs tejbajusza!','tejbajusz','tej a hűtőben','dramatic','exaggeration'),
(479,'hu','Az elméje két lépéssel előrébb jár.','Az elméje két lépéssel le van maradva.','lépéstervezés az elméjében','meggondolja magát','nerd','exaggeration'),
(480,'hu','Csiklandozza az ásványvíz.','Csiklandozza a narancslé.','szénsavas ásványvíz','szénsavmentes ásványvíz','chill','none'),
(481,'hu','A tükör viszontszereti.','Az ablak viszontszereti.','izompózolás a tükör előtt','a tükör tisztítása','low_iq','guessing'),
(483,'hu','A majom lopott egy banánt!','A majom lopott egy kalapot!','banánt evő majom','banánt áruló majom','dramatic','exclamation'),
(484,'hu','Felmosóval mossa fel a padlót.','Seprűvel söpri a padlót.','felmosó egy vödörben','felmosó egy szekrényben','chill','none'),
(485,'hu','Puha a moha. Szuper párna.','Puha a széna. Szuper párna.','puha zöld moha','moha a tetőn','low_iq','none'),
(486,'hu','A hegy tetején, igen!','A hegy lábánál, igen!','egy hegy tetején','hegyi tó','dramatic','exclamation'),
(487,'hu','Az egér megtalálta a sajtot.','Az egér megtalálta a kenyeret.','egér a pajtában','egér és billentyűzet','chill','none'),
(488,'hu','Hatalmasak az izmai!','Hatalmas a cipője!','nagy izmok feszítése','izom a lábban','dramatic','exclamation'),
(489,'hu','A gombán fehér pöttyök vannak.','A gombán fekete pöttyök vannak.','piros pöttyös gomba','gombaleves egy tányérban','chill','none'),
(490,'hu','Ez a zenész híres lesz.','Ez a táncos híres lesz.','utcazenész','zenész egy bandában','gossip','guessing'),
(491,'hu','Csípős a mustár.','Csípős a méz.','egy kanál mustár','egy üveg mustármag','chill','none'),
(492,'hu','Még nedves a körömlakkja!','Még nedves a haja!','körömlakk felkenése','régi körömlakk lemosása','dramatic','exclamation'),
(495,'hu','A természetben pihennek.','A természetben futnak.','fekvés a természetben','természetfilm','chill','none'),
(496,'hu','Szép nyaklánc, jó választás.','Szép karkötő, jó választás.','színes gyöngyös nyaklánc','arany nyaklánc','flirt','none'),
(498,'hu','Annyira ideges a fellépés előtt!','Annyira ideges a vizsga előtt!','ideges gitáros','ideges diák vizsga előtt','dramatic','exclamation'),
(499,'hu','Kukucs egy újsággal!','Kukucs egy étlappal!','elbújás egy újság mögött','újságolvasás online','slang','exclamation'),
(500,'hu','Úgy cselezi ki, mintha ott sem lenne.','Úgy cselez ki három embert, mintha ott sem lennének.','védő kicselezése','kapus kicselezése','slang','exaggeration'),
(501,'hu','Éjszaka sétálnak.','Délben sétálnak.','hazasétálás éjszaka','éjszakai munka','chill','none'),
(502,'hu','Észak felé tartanak.','Dél felé tartanak.','észak felé iránytűvel','egy város északi része','business','none'),
(503,'hu','Új füzet! Nagy pillanat.','Új laptop! Nagy pillanat.','vadonatúj füzet','jegyzetekkel teli füzet','ironic','exclamation'),
(505,'hu','Harcol egy apró dióval.','Harcol egy apró tojással.','dió feltörése','dió egy tortán','low_iq','exaggeration'),
(506,'hu','A tányérjuk maga az egészséges táplálkozás.','A tányérjuk maga a cukor.','egészséges táplálkozás egy tányéron','tápérték-táblázat egy dobozon','nerd','exaggeration'),
(507,'hu','Egy szitakötőt figyel meg.','Egy lepkét figyel meg.','szitakötő megfigyelése','szitakötő elkapása','nerd','none'),
(508,'hu','Delfinek az óceánban! Ez komoly?!','Cápák az óceánban! Ez komoly?!','delfinek az óceánban','úszás az óceánban','dramatic','exclamation'),
(509,'hu','Lassan folyik az olaj.','Lassan folyik a tej.','kenyér olívaolajban','olaj egy serpenyőben','chill','none'),
(511,'hu','Úszószemüvegben vágja a hagymát. Zseni!','Napszemüvegben vágja a hagymát. Zseni!','fehér hagyma aprítása','fehér hagyma pirítása','low_iq','exclamation'),
(512,'hu','Végre jó a szett.','Végre jó a frizura.','szett összeállítása','szett egy esküvőre','chill','none'),
(513,'hu','Kint esznek. Kinek kell ebédlő?','Bent esznek. Kinek kell ebédlő?','evés kint a füvön','evés kint egy kávézóban','ironic','guessing'),
(514,'hu','A sütő az új tévéjük.','A hűtő az új tévéjük.','kenyér kel a sütőben','pizza a sütőben','slang','exaggeration'),
(515,'hu','Leküzdötte a falat!','Leküzdötte a folyót!','mászófal leküzdése','kutyafóbia leküzdése','dramatic','exclamation'),
(516,'hu','Túlcsordult a mosdó. Hoppá.','Túlcsordult a kád. Hoppá.','túlcsorduló mosdó','túlcsorduló kuka','ironic','understatement'),
(517,'hu','Viszlát, lakóautó! Előz!','Viszlát, lakóautó! Parkol!','lassú lakóautó előzése','gyors vonat előzése','slang','exclamation'),
(518,'hu','A bagoly téged figyel.','A varjú téged figyel.','bagoly egy ágon','bagoly ketrecben','dramatic','exaggeration'),
(519,'hu','A táska be van pakolva a suliba.','A táska be van pakolva egy utazáshoz.','iskolatáska bepakolása','bőrönd bepakolása','chill','none'),
(520,'hu','A lány evez, a srác alszik.','A lány evez, a srác horgászik.','kenuval evezni','szörfdeszkán evezni','gossip','banter'),
(521,'hu','Iszonyú fájdalom a lábujjában!','Iszonyú fájdalom a kezében!','fájdalom a lábujjban','fájdalom a hátban','dramatic','exclamation'),
(522,'hu','Azt mondja, a festménye szebb, mint a valódi látvány.','Azt mondja, a festménye csúnyább, mint a valódi látvány.','festmény a tengerről','fal fehérre festése','gossip','exaggeration'),
(523,'hu','Szép mozdulatok azzal a serpenyővel!','Szép mozdulatok azzal a pizzatésztával!','zöldségek egy serpenyőben','palacsinta egy serpenyőben','flirt','exclamation'),
(524,'hu','Pánik: a vonat elment nélküle!','Pánik: a busz elment nélküle!','pánik a peronon','pánik a repülőn','dramatic','exclamation'),
(525,'hu','Egy kis gemkapocs legyőzi a nagy ventilátort.','Egy kis tűzőgép legyőzi a nagy ventilátort.','gemkapocs a papírokon','fotót tartó gemkapocs','dramatic','exaggeration'),
(527,'hu','Csomagot kapott!','Levelet kapott!','csomag kibontása','csomag feladása','dramatic','exclamation'),
(528,'hu','A csaj profin parkol!','A srác profin parkol!','parkolni két autó között','parkolni egy garázsban','slang','exaggeration'),
(530,'hu','A papagáj azt mondja: szia.','A papagáj azt mondja: viszlát.','papagáj a korláton','papagáj egy kalitkában','chill','none'),
(531,'hu','Ez a kerti buli ütős.','Ez a medencés buli ütős.','kerti buli naplementekor','medencés buli','slang','none'),
(532,'hu','A srác passzolt, a csaj gólt lőtt, ennyi.','A csaj passzolt, a srác gólt lőtt, ennyi.','passzolni a lánynak','előzni egy lassú autót','slang','none'),
(533,'hu','Megcsókolta az útlevelét!','Megcsókolta a bőröndjét!','lepecsételt útlevél','útlevélfotó-automata','dramatic','exclamation'),
(535,'hu','A tésztatorony profin néz ki.','A tortatorony profin néz ki.','tésztatorony','tésztasaláta','business','none'),
(536,'hu','Egy függőágyban talál nyugalmat.','Egy fürdőkádban talál nyugalmat.','nyugalom napkeltekor','nyugalom éjfélkor','chill','none'),
(537,'hu','Egy piros almát hámoz.','Egy zöld almát hámoz.','egy spirálban hámozni','banánt hámozni','chill','none'),
(538,'hu','Sokszínű a tolla.','Egyszínű a tolla.','sokszínű toll','világító toll','chill','none'),
(540,'hu','Belőtte a tizenegyest!','Kihagyta a tizenegyest!','tizenegyes belövése','tizenegyes kivédése','dramatic','exclamation'),
(541,'hu','Nagyon jó a ceruzarajza.','Nagyon jó a tollrajza.','rajzolás sárga ceruzával','sárga ceruza hegyezése','flirt','none'),
(542,'hu','Hascsúszás! Hajrá, pingvin!','Hascsúszás! Hajrá, fóka!','pingvin a jégen','pingvin az állatkertben','slang','exclamation'),
(543,'hu','A borstól tüsszentett!','A hagymától tüsszentett!','fekete bors őrlése','kávébab őrlése','dramatic','blaming_someone'),
(545,'hu','Micsoda zsonglőr-előadás!','Micsoda táncelőadás!','utcai zsonglőr-előadás','iskolai kiselőadás','dramatic','exclamation'),
(546,'hu','Ez aztán túl sok parfüm!','Ez aztán túl sok víz!','parfüm fújása egy barátra','parfüm fújása egy ruhára','slang','exaggeration'),
(547,'hu','Szól a telefonja!','Szól a csengője!','telefon felvétele','telefon a zsebben','dramatic','exclamation'),
(548,'hu','Az! A fotózás tök jó.','Az! A festés tök jó.','utcai fotózás naplementekor','esküvői fotózás beltérben','dramatic','exclamation'),
(549,'hu','Egy arany karika a piercingjébe.','Egy arany stift a piercingjébe.','arany karikás piercing','piercing az orrában','chill','none'),
(550,'hu','A disznó a sárban hempereg.','A disznó a hóban hempereg.','disznó a tanyaudvaron','disznó egy fürdőkádban','chill','none'),
(551,'hu','A galamb ellenőrzi a kávézót.','A galamb ellenőrzi a bankot.','galamb egy téren','galamb egy parkban','business','exaggeration'),
(553,'hu','Nagyon büszke a pályájára.','Nagyon büszke az autójára.','a pálya nyírása','a pálya festése','gossip','none'),
(554,'hu','Tökéletes hely a tengerparton.','Tökéletes hely a parkban.','tökéletes hely az üldögéléshez','hely a sorban','chill','none'),
(555,'hu','Új levele van a növénynek!','Új virága van a növénynek!','nagy levelű növény','piros virágú növény','dramatic','exclamation'),
(556,'hu','Egy sebtapasszal mentette meg az életét.','Egy kis jéggel mentette meg az életét.','sebtapasz az ujjbegyen','sebtapasz a térden','ironic','exaggeration'),
(557,'hu','A séf tálalja a tányért.','A séf mossa a tányért.','spagetti egy fehér tányéron','üres tányérok halma','business','none'),
(558,'hu','Elhagyta a sapkáját, miközben röplabdát játszott.','Elhagyta a cipőjét, miközben röplabdát játszott.','röplabdát játszani a parkban','kártyázni a parkban','chill','none'),
(559,'hu','Ez a játékos nagyon boldog!','Ez a játékos nagyon dühös!','sárga mezes játékos','játékos a kispadon','dramatic','exclamation'),
(560,'hu','Előbb szelfi, aztán a szökőkút.','Előbb szelfi, aztán a pizza.','a híres Trevi-szökőkút','szökőkút egy plázában','chill','cliche'),
(561,'hu','Egy croissant, maga a tiszta élvezet.','Egy bagel, maga a tiszta élvezet.','a croissant élvezete','élvezet a munkában','dramatic','none'),
(562,'hu','A dugó volt a baj.','Az izzó volt a baj.','laza dugó','a kád dugója','chill','understatement'),
(563,'hu','A kulcsok a zsebében voltak!','A kulcsok a cipőjében voltak!','kulcsok a dzsekizsebben','kulcsok az autóajtóban','low_iq','exclamation'),
(564,'hu','A dobogójuk szivacsból van.','A dobogójuk aranyból van.','szivacskockás dobogó','dobogó egy konferencián','ironic','cheap_quality'),
(565,'hu','Politika játékosan: a narancssárga nyert.','Politika játékosan: a zöld nyert.','politika a főtéren','politika a tévében','gossip','none'),
(566,'hu','Szennyezi a folyót. Szégyen!','Tisztítja a folyót. Szégyen!','tiszta folyót szennyezni','a tengert szennyezni','dramatic','blaming_someone'),
(567,'hu','Aranyhalak élnek ebben a tavacskában.','Békák élnek ebben a tavacskában.','aranyhalak a tavacskában','kacsák a tavacskán','chill','none'),
(568,'hu','Egy nyugis napot akart a medencénél.','Egy nyugis napot akart a tónál.','csobbanás a medencébe','gyerekmedence','chill','guessing'),
(569,'hu','A postamester nagyon parancsolgató.','A postamester nagyon félénk.','parancsolgató postamester','postamester szabadságon','gossip','none'),
(571,'hu','Táncol a víz a fazékban!','Megfagy a víz a fazékban!','krumpli egy nagy fazékban','virág egy nagy cserépben','low_iq','exaggeration'),
(572,'hu','Egy csomó krumplit találtak!','Egy csomó répát találtak!','krumpli kiásása','krumpli hámozása','dramatic','exclamation'),
(573,'hu','Az öntése igazi szakértelemről árulkodik.','Az éneklése igazi szakértelemről árulkodik.','öntés nagy magasságból','zuhogó eső odakint','business','none'),
(574,'hu','Micsoda púderfelhő!','Micsoda füstfelhő!','arcpúder felvitele','sütés fehér porral','dramatic','exclamation'),
(576,'hu','Jó jegyért imádkozik.','Új telefonért imádkozik.','imádkozás jó jegyért','imádkozás a templomban','dramatic','none'),
(577,'hu','A lány megjósolta az esőt. A srác nem.','A lány megjósolta a havat. A srác nem.','az eső megjóslása','a lottószámok megjóslása','gossip','banter'),
(578,'hu','Ragyog a büszkeségtől.','Sír a büszkeségtől.','büszkeség a motorjára','büszkeség az új autójára','chill','none'),
(579,'hu','Egy robot programozása nehéz.','Egy drón programozása nehéz.','kis robot programozása','videójáték programozása','chill','understatement'),
(580,'hu','Megvédi a lányt az esőtől.','Megvédi a lányt a naptól.','valaki megvédése az esőtől','valaki megvédése egy kutyától','chill','none'),
(581,'hu','Napraforgókkal tüntetnek!','Esernyőkkel tüntetnek!','tüntetni a természetért','tüntetni az esőben','dramatic','exclamation'),
(582,'hu','Büszke a székére.','Büszke az asztalára.','büszke a munkájára','büszke az autójára','chill','none'),
(584,'hu','A lány bebizonyította, hogy a srác téved. Pofonegyszerű.','A srác bebizonyította, hogy a lány téved. Pofonegyszerű.','bebizonyítani, hogy a srác téved','bebizonyítani, hogy a lány téved','ironic','understatement'),
(585,'hu','Nyilvános helyen zenél.','Nyilvános helyen sakkozik.','zenélés nyilvános helyen','nyilvános uszoda','chill','none'),
(587,'hu','A sárga lőtt gólt a koronggal!','A lila lőtt gólt a koronggal!','korong a hálóban','korong a lelátón','dramatic','exclamation'),
(588,'hu','Csobb! Nagy tócsaugrás.','Csobb! Nagy medenceugrás.','beugrani egy tócsába','kikerülni egy tócsát','slang','exclamation'),
(589,'hu','Kemény húzás, happy end.','Kemény tolás, happy end.','vastag kötél húzása','ajtónyitás húzással','chill','cliche'),
(590,'hu','Úgy üt, mint egy profi!','Úgy rúg, mint egy profi!','ütés a fókuszpárnákba','ütés a falba','slang','exaggeration'),
(591,'hu','Szerelmes a boxzsákjába.','Szerelmes a garázslétrájába.','boxzsák felakasztása','a garázsajtó ütése','gossip','guessing'),
(592,'hu','Egy furgon tolása? Könnyű!','Egy busz tolása? Könnyű!','fehér furgon tolása','fehér autó tolása','ironic','understatement'),
(593,'hu','Összeillő pizsama? De cuki!','Összeillő dzseki? De cuki!','összeillő kockás pizsama','összeillő csíkos pizsama','flirt','exclamation'),
(594,'hu','Az ugrással jutott tovább.','Az úszással jutott tovább.','továbbjutni a következő körbe','továbbjutni az úszásban','chill','none'),
(595,'hu','A nyúl két lábra ágaskodik.','A nyúl fekszik.','nyúl a dűnéken','nyúl a kalapban','chill','none'),
(596,'hu','Gyerünk, gyerünk! Micsoda verseny!','Gyerünk, gyerünk! Micsoda úszás!','verseny a futópályán','verseny a medencében','dramatic','exclamation'),
(597,'hu','Menő trükk az ütővel.','Menő trükk a palackkal.','fekete teniszütő','tollasütő','slang','none'),
(598,'hu','Táncol az esőben.','Táncol a hóban.','tánc a zuhogó esőben','bujkálás az eső elől','chill','none'),
(599,'hu','Ezek a mozdulatok szupergyorsak.','Ezek a mozdulatok szuperlassúak.','gyors átlépések','gyors passzok','slang','none'),
(600,'hu','A patkány pizzát lop!','A patkány kenyeret lop!','patkány pizzával','patkány ketrecben','dramatic','exclamation'),
(601,'hu','Borotvával borotválkozik.','Késsel borotválkozik.','elektromos borotva','borotvapenge','chill','none'),
(602,'hu','Olvasás éjjel a vonaton.','Olvasás éjjel a hajón.','olvasás egy éjszakai vonaton','olvasás a könyvtárban','chill','none'),
(604,'hu','Ez a blokk sosem ér véget!','Ez az étlap sosem ér véget!','nagyon hosszú blokk','nagyon rövid blokk','slang','exaggeration'),
(606,'hu','A recept szerint: előbb a tojás.','A recept szerint: előbb a hal.','kézzel rajzolt receptkártya','egy leves receptje','business','none'),
(607,'hu','Most már tele van a hűtőszekrény.','Most már tele van a sütő.','a hűtőszekrény feltöltése','a hűtőszekrény takarítása','chill','none'),
(608,'hu','Beparkolva! Micsoda megkönnyebbülés!','Összetörve! Micsoda megkönnyebbülés!','megkönnyebbülés parkolás után','megkönnyebbülés egy baleset után','dramatic','exclamation'),
(609,'hu','A dombon pihennek.','A dombon futnak.','pihenés egy dombtetőn','pihenés egy függőágyban','chill','none'),
(610,'hu','A tök kék szalagot kapott. A lány ledöbbent!','A répa kék szalagot kapott. A lány ledöbbent!','a tök kék szalagja','szalag a hajában','gossip','none'),
(612,'hu','Jobbra mutat.','Az égre mutat.','jobbra menni a standok mellett','jobbra kanyarodni a lámpánál','chill','none'),
(613,'hu','A ringben ugrál.','A medencében ugrál.','bemászás a ringbe','gyűrű az ujjon','chill','none'),
(615,'hu','Levélverseny a folyón. Hajrá!','Hajóverseny a folyón. Hajrá!','levelek egy tiszta folyón','hajó egy folyón','slang','none'),
(616,'hu','Szikla: egy. Emberek: nulla.','Fa: egy. Emberek: nulla.','óriási szikla tolása','kis kő dobása','slang','cliche'),
(617,'hu','Görkorcsolyán jött, csak hogy elvegye a srác italát!','Biciklin jött, csak hogy elvegye a srác italát!','lila görkorcsolya a parkban','görkorcsolya a jégpályán','dramatic','exaggeration'),
(618,'hu','A kötél megmentette a szekeret!','A lánc megmentette a szekeret!','kötél egy kerék körül','ugrókötél','dramatic','exaggeration'),
(619,'hu','Egy kosarat ereszt le.','Egy vödröt ereszt le.','kosár leeresztése kötélen','zászló leeresztése','chill','none'),
(620,'hu','Ez a rózsa mennyei illatú.','Ez a tulipán mennyei illatú.','rózsaszín rózsa szagolgatása','rózsaszín rózsa vásárlása','dramatic','cliche'),
(621,'hu','A sor tökéletesen egyenes.','A sor tökéletesen kerek.','ültetés egyenes sorba','ülés az első sorban','business','none'),
(622,'hu','Egy gumigyűrű tartja össze a fűszernövényeket.','Egy gumigyűrű tartja össze a póréhagymát.','narancssárga gumigyűrű','gumigyűrű hajhoz','business','none'),
(623,'hu','Micsoda udvariatlan fickó!','Micsoda kedves fickó!','udvariatlan vendég a kávézóban','udvariatlan pincérnő','slang','exclamation'),
(624,'hu','A kalapja után fut!','A kutyája után fut!','futni egy kalap után','futni a busz után','dramatic','exclamation'),
(626,'hu','A futó vizet iszik.','A futó banánt eszik.','vizet ivó futó','futó a futópadon','chill','none'),
(627,'hu','Kifutó a nappaliban. Mutasd, mit tudsz!','Kifutó a konyhában. Mutasd, mit tudsz!','kifutó a nappaliban','kifutópálya a reptéren','slang','exclamation'),
(628,'hu','Az arca csupa szomorúság.','Az arca csupa öröm.','szomorúság egy üres boltban','szomorúság egy temetésen','dramatic','none'),
(629,'hu','Bent biztonságban, kint vihar.','Bent biztonságban, kint napsütés.','biztonságban egy hegyi kunyhóban','széf a falban','chill','cliche'),
(630,'hu','A tengerész a kormánynál van!','A tengerész az asztalnál van!','tengerész a fedélzeten','tengerész egy bárban','slang','exclamation'),
(631,'hu','Nagyon hatékonyan készíti a salátákat.','Nagyon hatékonyan készíti a tortákat.','friss saláta összeforgatása','saláta egy dobozban','business','none'),
(632,'hu','Sót szórnak a paradicsomra.','Sót szórnak a krumplira.','só a paradicsomszeleteken','só egy havas úton','chill','none'),
(634,'hu','Egy hullám megette a homokrajzát.','Egy kutya megette a homokrajzát.','rajzolás a homokba','homokvár építése','slang','exaggeration'),
(635,'hu','Szandál fel, lábujjak ki!','Csizma fel, lábujjak ki!','barna szandál becsatolása','barna szandál vásárlása','slang','none'),
(636,'hu','Még a kacsa is azt a szendvicset akarja.','Még a kutya is azt a szendvicset akarja.','sonkás-sajtos szendvics','szendvics egy uzsonnásdobozban','chill','guessing'),
(637,'hu','Gránátalma: több száz mag.','Görögdinnye: több száz mag.','gránátalma kibontása','gránátalmalé egy pohárban','nerd','exaggeration'),
(638,'hu','Túl sok szószt tett rá!','Túl sok sót tett rá!','szósszal teli tányér','szósz egy üvegben','slang','exaggeration'),
(639,'hu','Kolbászt süt.','Tojást süt.','kolbász sütése serpenyőben','kolbász egy pizzán','chill','none'),
(640,'hu','Ez a mérleg biztos elromlott!','Ez az óra biztos elromlott!','nagy, mutatós mérleg','konyhai mérleg','low_iq','bad_excuse'),
(641,'hu','A macska a mérlegen van!','A kutya a mérlegen van!','macska a mérlegen','mérleg a piacon','gossip','exclamation'),
(642,'hu','A hegeiket hasonlítják össze.','A tetoválásaikat hasonlítják össze.','hegek összehasonlítása','hegek eltakarása','chill','none'),
(644,'hu','Ki van ott? A lány nagyon ijedt!','Ki van ott? A fiú nagyon ijedt!','ijedten a parkolóházban','ijedten a hullámvasúton','dramatic','exclamation'),
(645,'hu','Rendezi az időbeosztását.','Rendezi az íróasztalát.','időbeosztás tervezése','buszmenetrend','business','none'),
(646,'hu','A tudomány narancssárga habot csinál!','A tudomány kék habot csinál!','tudományos kísérlet','tudományos múzeum','dramatic','exclamation'),
(647,'hu','Csak egy kis igazítás az ollóval.','Csak egy kis igazítás a borotvával.','frufruvágás ollóval','papírvágás ollóval','ironic','understatement'),
(649,'hu','A nagyi megint szidja.','A nagyi megint öleli.','unokát szidni','kutyát szidni','gossip','none'),
(650,'hu','Megtalálta az utolsó csavart!','Megtalálta az utolsó szöget!','az utolsó hiányzó csavar','az utolsó hiányzó zokni','dramatic','exclamation'),
(651,'hu','A lány a csavarhúzót használja, a srác aggódik.','A lány a kalapácsot használja, a srác aggódik.','meghúzás csavarhúzóval','csavarhúzó a srác kezében','gossip','banter'),
(652,'hu','Fúj! A tenger sós!','Fúj! A tó sós!','fejesugrás a tengerbe','emberek tengere','dramatic','exclamation'),
(653,'hu','Annyit kerestük! A kulcsok az ajtóban voltak.','Annyit kerestük! A kulcsok az autóban voltak.','elveszett kulcsokat keresni','elveszett kutyát keresni','dramatic','exclamation'),
(654,'hu','Egy titkot suttog.','Egy titkot kiabál.','titkot suttogni','titkot leírni','chill','none'),
(655,'hu','Partisapkák? A lány komoly marad.','Partisapkák? A fiú komoly marad.','komoly arc a munkahelyen','komoly beszélgetés vacsoránál','ironic','understatement'),
(656,'hu','Az egész tömeg sem tudja elterelni a lány figyelmét!','Az egész tömeg sem tudja elterelni a fiú figyelmét!','próbálja elterelni a figyelmét','próbálja elterelni a kutya figyelmét','dramatic','exclamation'),
(657,'hu','Profin szolgálja fel a nudlit.','Profin szolgálja fel a pizzát.','nudlis tál felszolgálása','szerválás a teniszben','slang','none'),
(659,'hu','Ez aztán a sok sampon!','Ez aztán a sok krém!','samponhabtorony','kutyasampon','dramatic','exclamation'),
(660,'hu','Kinek kell szalon? Jó a lavór is.','Kinek kell szalon? Jó a vödör is.','hajmosás lavór fölött','mosogatás lavórban','ironic','cheap_quality'),
(661,'hu','A cápa rád mosolyog.','A delfin rád mosolyog.','cápa a kamera mellett','cápa egy hajó mellett','dramatic','guessing'),
(662,'hu','A hegyező tökéletesen működik.','A hegyező rosszul működik.','kis ceruzahegyező','kis késélező','business','none'),
(663,'hu','Borotvahab: azonnali szakáll!','Borotvahab: azonnali kalap!','borotvahab-kupac','borotvahab egy tortán','low_iq','exaggeration'),
(664,'hu','Borotválkozás kézzel, oldschool.','Gyantázás kézzel, oldschool.','borotválkozás tokos borotvával','borotválkozás villanyborotvával','slang','cliche'),
(665,'hu','Mérges rám a birka?','Mérges rám a kecske?','birka a domboldalon','birka egy pajtában','low_iq','exaggeration'),
(666,'hu','Kék inget vesz fel.','Piros inget vesz fel.','világoskék ing begombolása','világoskék ing vasalása','chill','none'),
(667,'hu','Az eldőlt roller igazi sokk.','Az eldőlt bicikli igazi sokk.','sokk egy eldőlt roller miatt','elektromos sokk','dramatic','none'),
(668,'hu','Cipő befűzve. Mehetünk.','Bakancs befűzve. Mehetünk.','barna cipő befűzése','barna cipő pucolása','business','none'),
(669,'hu','Három érméért sokat lehet venni ebben a boltban.','Tíz érméért sokat lehet venni ebben a boltban.','kis élelmiszerbolt','kis virágbolt','gossip','cheap_quality'),
(670,'hu','Hatékonyan vásárol.','Hatékonyan úszik.','vásárolni a szupermarketben','ruhát vásárolni','business','none'),
(671,'hu','Annyit kiabáltak, hogy fáj a torkuk.','Annyit énekeltek, hogy fáj a torkuk.','átkiabálni a völgyön','kiabálni a tévére','chill','exaggeration'),
(672,'hu','Zuhanyozás jeges vízben!','Zuhanyozás forró vízben!','zuhanyozás a tengerparton','zuhanyozás a fürdőszobában','dramatic','exaggeration')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
