begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(1110,'hu','Puszik a lányunokától!','Puszik a fiúunokától!','lányunoka puszija','lányunoka rajza','slang','exclamation'),
(1112,'hu','A nagymama kenyeret süt.','A nagymama levest főz.','sütés a nagymamával','kötés a nagymamával','chill','none'),
(1115,'hu','Tánc Görögországban? Jó a stílusod.','Búvárkodás Görögországban? Jó a stílusod.','tánc Görögországban','úszás Görögországban','flirt','none'),
(1116,'hu','A vőlegény ölben viszi a menyasszonyt.','A vőlegény ölben viszi a tortát.','menyasszonyát vivő vőlegény','lovat csutakoló vőlegény','flirt','none'),
(1119,'hu','Az idegenvezető vezeti a túrát.','Az idegenvezető vezeti a versenyt.','idegenvezető esernyővel','mászó hegyi vezető','business','none'),
(1120,'hu','Ez a srác a kulcsát dobálja. Nagyon menő.','Ez a srác a telefonját dobálja. Nagyon menő.','srác pizzával','srác gitárral','slang','none'),
(1123,'hu','Nála a folyosó a tánctér!','Nála a konyha a tánctér!','tánc a folyosón','futás a folyosón','slang','exclamation'),
(1125,'hu','Hajók pihennek a kikötőben.','Hajók pihennek a strandon.','hajók a kikötőben','hajók a csatornán','chill','none'),
(1126,'hu','A munkától fejfájása lett.','A zenétől fejfájása lett.','fejfájás éjjel','fejfájás a napon','chill','blaming_someone'),
(1127,'hu','Csupa egészség és boldogság!','Csupa eső és sötétség!','csupa egészség és öröm','egészségügyi ellenőrzés','dramatic','cliche'),
(1129,'hu','Az orvos egy szívet tart a kezében!','Az orvos egy agyat tart a kezében!','szívmodell','agymodell','dramatic','exclamation'),
(1131,'hu','Mindkét sarka elemelkedik a padlótól.','Mindkét sarka a padlón van.','sarkak felemelése','magas sarkú cipőben','chill','none'),
(1133,'hu','A segítő viszi a táskáját.','A segítő viszi a kutyáját.','segítő a táskájával','segítő a konyhában','chill','none'),
(1134,'hu','Találd ki, ki ebédel a dombon! A birkák.','Találd ki, ki ebédel a dombon! A tehenek.','fa a dombon','ház a dombon','gossip','guessing'),
(1135,'hu','A keze a csípőjén van.','A keze a fején van.','kéz a csípőn','kéz a vállon','chill','none'),
(1136,'hu','Végre otthon van!','Végre a munkahelyén van!','hazaérkezés táskával','elindulás hazulról táskával','dramatic','exclamation'),
(1138,'hu','Nyugis nap a kórházban.','Nyugis nap a reptéren.','világos kórházi folyosó','zsúfolt kórházi kórterem','gossip','guessing'),
(1139,'hu','A házigazda pohárköszöntőt mond.','A házigazda tortát süt.','poharát emelő házigazda','tévéműsor házigazdája','business','none'),
(1141,'hu','Egy vendég kilép a szállodából.','Egy vendég belép a szállodába.','kilépés egy elegáns szállodából','szálloda a tenger mellett','business','none'),
(1143,'hu','Itt csak egyetlen ember van.','Itt csak egyetlen teve van.','egy ember a sivatagban','embertömeg','ironic','understatement'),
(1144,'hu','A vadász térdel.','A vadász fut.','vadász távcsővel','vadász puskával','chill','none'),
(1147,'hu','Fertőzés van a könyökén.','Fertőzés van a térdén.','fertőzés a könyökön','fertőzés a szemben','chill','none'),
(1148,'hu','Kész az injekció. Fuss!','Kész a kötés. Fuss!','tálca az injekcióhoz','vacsorára kész tálca','low_iq','exclamation'),
(1149,'hu','Álmatlanság: ő a plafon ellen.','Álmatlanság: ő a hűtő ellen.','álmatlanság éjjel','álmatlanság vizsga előtt','ironic','exaggeration'),
(1151,'hu','Gőzölög a vasalója.','Gőzölög a vízforralója.','gőzölgő vasaló','vaskapu','business','none'),
(1152,'hu','Egy vasalódeszka épp kinyílik.','Egy nyugágy épp kinyílik.','vasalódeszka felállítása','ülés a vasalódeszkán','chill','none'),
(1154,'hu','Az újságíró válaszokat akar.','Az orvos válaszokat akar.','újságíró diktafonnal','újságíró az íróasztalnál','gossip','guessing'),
(1156,'hu','Ebben a dzsungelben a papagáj a főnök.','Ebben a dzsungelben a majom a főnök.','papagáj a dzsungelben','papagáj kalitkában','slang','exaggeration'),
(1158,'hu','A vízforraló vize forró. Ki gondolta volna?','A csap vize forró. Ki gondolta volna?','öntés a vízforralóból','vízforraló a tűzhelyen','low_iq','understatement'),
(1159,'hu','Parancsoljon, a szobája kulcsa.','Parancsoljon, az autója kulcsa.','szállodai szobakulcs','autókulcs','business','none'),
(1160,'hu','A konyha jól felszerelt.','A konyha szinte üres.','világos konyha','sötét konyha','business','none'),
(1161,'hu','Jeget tesz a térdére.','Jeget tesz a fejére.','jég a behajlított térden','féltérdre ereszkedve','business','none'),
(1163,'hu','A hölgyön fehér kesztyű van.','A hölgyön fekete kesztyű van.','hölgy a lépcsőn','hölgy a bárpultnál','chill','none'),
(1166,'hu','Egy nagy lámpát cipel.','Egy nagy növényt cipel.','asztali lámpa','kerti lámpa','chill','none'),
(1167,'hu','Az ügyvédnek rengeteg könyve van.','Az ügyvédnek rengeteg macskája van.','ügyvéd mappával','ügyvéd a tárgyalóteremben','chill','none'),
(1170,'hu','A könyvtáros létrán áll.','A könyvtáros asztalon áll.','könyvtáros létrán','könyvtáros a számítógépnél','chill','none'),
(1173,'hu','Villám csap a tengerbe!','Villám csap egy fába!','villám a tenger fölött','villám a város fölött','dramatic','exclamation'),
(1175,'hu','Repked a popcorn az egész nappaliban.','Repked a popcorn az egész konyhában.','barátok a nappaliban','barátok a váróteremben','slang','exaggeration'),
(1178,'hu','A vesztes a törölköző alá bújt.','A vesztes az asztal alá bújt.','a meccs vesztese','a futam vesztese','dramatic','none'),
(1179,'hu','Túl sok poggyász egy férfinak.','Túl sok poggyász egy lánynak.','poggyásszal megrakott kocsi','poggyász az autó tetején','low_iq','exaggeration'),
(1180,'hu','A poggyászcímke üres.','A poggyászcímke piros.','poggyászcímke felkötése','poggyászcímke levágása','chill','none'),
(1182,'hu','A szobalány beágyaz.','A szobalány kávét főz.','ágyat bevető szobalány','szobalány egy esküvőn','chill','none'),
(1183,'hu','Egy férfi sportoló evez.','Egy női sportoló evez.','férfi evezős','férfi úszó','chill','none'),
(1185,'hu','A menedzser utasításokat oszt.','A menedzser ajándékokat oszt.','menedzser laptoppal','menedzser telefonnal','business','none'),
(1188,'hu','Frissen házasok, és már táncolnak.','Frissen házasok, és már veszekednek.','táncoló házaspár','veszekedő házaspár','chill','none'),
(1189,'hu','Egy matracot cipelnek.','Egy zongorát cipelnek.','matrac fel a lépcsőn','matrac a padlón','chill','none'),
(1193,'hu','Tátsd ki a szád, jön a gyógyszer.','Tátsd ki a szád, jön a fagyi.','folyékony gyógyszer kanálon','gyógyszer gyógyszeradagolóban','chill','cliche'),
(1195,'hu','Repülő mexikói tortilla!','Repülő mexikói taco!','mexikói utcai stand','mexikói étterem','dramatic','exclamation'),
(1198,'hu','A modell uralja a kifutót.','A modell uralja a strandot.','modell a kifutón','repülőgép-modell','slang','exaggeration'),
(1200,'hu','Imádja ezt a napsütéses reggelt.','Imádja ezt az esős reggelt.','napsütéses reggel','esős reggel','chill','guessing'),
(1202,'hu','Anya és baba: orr az orrhoz.','Anya és kutya: orr az orrhoz.','babáját felemelő anya','babáját etető anya','chill','none'),
(1203,'hu','Szikrázik a motorja!','Szikrázik a robogója!','motor a kanyarban','motor a garázsban','dramatic','exclamation'),
(1206,'hu','Mindenfelé repül a sár!','Mindenfelé repül a hó!','cipő mély sárban','cipő friss hóban','dramatic','exclamation'),
(1208,'hu','Dinoszaurusz a múzeumban!','Bálna a múzeumban!','dinoszaurusz a múzeumban','modern művészeti múzeum','dramatic','exclamation'),
(1211,'hu','Egy egész nemzet énekel egy emberként.','Egy egész nemzet táncol egy emberként.','együtt éneklő nemzet','kávéimádó nemzet','dramatic','cliche'),
(1213,'hu','Nagy hullámok, nagy hányinger.','Kis hullámok, nagy hányinger.','hányinger viharos tengeren','hányinger kiadós evés után','dramatic','none'),
(1214,'hu','Nyújtja a nyakát.','Nyújtja a lábát.','hosszan kinyújtott nyak','sál a nyak körül','chill','none'),
(1215,'hu','A szomszédok beszélgetnek.','A szomszédok veszekednek.','szomszédok a kerítésnél','hangos szomszéd','chill','none'),
(1216,'hu','Bicikli, tulipánok, szélmalmok. Igen, Hollandia.','Autó, tulipánok, szélmalmok. Igen, Hollandia.','tulipánok Hollandiában','piac Hollandiában','chill','cliche'),
(1221,'hu','A tiszt tiszteleg.','A tiszt táncol.','tisztelgő tiszt','autót vezető tiszt','chill','none'),
(1225,'hu','A festő nagyon odavan a kékeszöldért.','A festő nagyon odavan a rózsaszínért.','festő létrán','festő a festőállványnál','chill','guessing'),
(1227,'hu','Szülő üzemmód: kocogás.','Szülő üzemmód: alvás.','szülő a bicikli mellett','biciklit szerelő szülő','slang','cliche'),
(1230,'hu','Az utas mélyen alszik.','Az utas teljesen éber.','alvó vonatutas','utas egy taxiban','chill','none'),
(1232,'hu','A beteg mély levegőt vesz.','A beteg ebédel.','mélyen lélegző beteg','beteg az ágyban','chill','none'),
(1233,'hu','A gyalogosnál egy kávé van.','A gyalogosnál egy kutya van.','gyalogos kávéval','gyalogoshíd','chill','none'),
(1235,'hu','Az emberek ujjonganak!','Az emberek sírnak!','ujjongó emberek éjjel','ujjongó emberek a stadionban','dramatic','exclamation'),
(1237,'hu','Micsoda „forgalmas” kereszteződés: egy személy.','Micsoda „forgalmas” kereszteződés: egy kutya.','egy személy a zebrán','egy személy a buszon','ironic','understatement'),
(1238,'hu','A gyógyszertárban rengeteg tégely van.','A gyógyszertárban rengeteg játék van.','hangulatos régi gyógyszertár','vöröskeresztes gyógyszertár','chill','none'),
(1241,'hu','A fényképész a vizes utcán fekszik!','A fényképész a vizes utcán áll!','fényképész a földön','fényképész a stúdióban','dramatic','exclamation'),
(1242,'hu','Egy képet akaszt fel.','Egy tükröt akaszt fel.','kép a falon','kép a telefonján','chill','none'),
(1248,'hu','A bolygónak gyűrűi vannak!','A bolygónak nincsenek gyűrűi!','gyűrűs bolygó','bolygó a térképen','dramatic','exclamation'),
(1254,'hu','A vízvezeték-szerelő egy csövet javít.','A vízvezeték-szerelő egy ajtót javít.','vízvezeték-szerelő a mosdó alatt','vízvezeték-szerelő a tetőn','chill','none'),
(1255,'hu','Tél van Lengyelországban.','Nyár van Lengyelországban.','havas tér Lengyelországban','homokos strand Lengyelországban','chill','none'),
(1256,'hu','A rendőr mosolyog.','A rendőr sír.','valamire mutató rendőr','futó rendőr','chill','none'),
(1258,'hu','Lengyel pirogot csinált.','Lengyel kolbászt csinált.','lengyel pirogok sorban','lengyel kolbászok grillen','chill','none'),
(1260,'hu','Portugáliában fut.','Portugáliában biciklizik.','futás Portugáliában','villamosozás Portugáliában','chill','none'),
(1262,'hu','Fahéj a portugál kosárkákon!','Csoki a portugál kosárkákon!','portugál krémes kosárkák','portugál szardínia','dramatic','exclamation'),
(1263,'hu','A postás leveleket kézbesít.','A postás pizzát kézbesít.','postás az ajtóban','postás a furgonban','business','none'),
(1266,'hu','Az elnök beszél, és villognak a vakuk!','Az elnök énekel, és villognak a vakuk!','beszédet mondó elnök','kezet rázó elnök','dramatic','exclamation'),
(1267,'hu','Nagyon profinak tűnik.','Nagyon álmosnak tűnik.','profi megjelenés','profi sportoló','flirt','none'),
(1268,'hu','A professzor előadást tart.','A professzor alszik.','előadó professzor','a professzor irodája','chill','none'),
(1270,'hu','Beleugrál a tócsába.','Beleugrál a hóba.','beleugrás a tócsába','kiömlött tejtócsa','chill','none'),
(1274,'hu','Hatalmas szivárvány a dombok fölött.','Hatalmas szivárvány a tenger fölött.','szivárvány zöld dombok fölött','szivárvány a város fölött','chill','none'),
(1275,'hu','Vakarja a kiütését.','Vakarja a fejét.','piros kiütés vakarása','kiütés az arcán','chill','none'),
(1278,'hu','A recepción sárgaréz csengő van.','A recepción sárgaréz lámpa van.','kulcs a recepción','esküvői fogadás','business','none'),
(1286,'hu','Egy munkás takarítja a tetőt.','Egy munkás festi a tetőt.','cserepes háztető','állomás üvegteteje','business','none'),
(1287,'hu','Üres a szoba? Táncidő!','Üres a bolt? Táncidő!','üres, napos szoba','üres, napos strand','slang','exclamation'),
(1290,'hu','Ennyi kanyar ezen az útvonalon!','Ennyi kamion ezen az útvonalon!','útvonal fel a hegyre','útvonal a part mentén','dramatic','exclamation'),
(1299,'hu','Úgy tűnik, imádja ezt a felvételt.','Úgy tűnik, utálja ezt a felvételt.','MR-felvétel egy betegről','átvilágítás a reptéren','ironic','guessing'),
(1303,'hu','Micsoda stílusos robogózás!','Micsoda stílusos biciklizés!','robogó Olaszországban','robogó a tengerparton','flirt','exaggeration'),
(1304,'hu','A titkár nagyon elfoglalt!','A titkár nagyon unatkozik!','elfoglalt titkár','szabadságon lévő titkár','dramatic','exclamation'),
(1305,'hu','Egy babmag esik le.','Egy kis kő esik le.','babmag elültetése','magokat evő madár','chill','none'),
(1306,'hu','Az eladó nagyon boldog.','Az eladó nagyon dühös.','zöldségeladó','könyveladó','chill','none'),
(1307,'hu','A szolga ezüsttálcát tart.','A szolga ezüstcsengőt tart.','szolga tálcával','szolga a konyhában','chill','none'),
(1308,'hu','Még az árnyéka is táncol!','Még a barátja is táncol!','óriási árnyék a falon','árnyék a fa alatt','dramatic','exclamation'),
(1311,'hu','Egy hatalmas hajónak integet!','Egy apró hajónak integet!','integetés egy nagy hajónak','integetés egy nagy hajóról','dramatic','exclamation'),
(1312,'hu','Az eladón kabát van.','Az eladón kalap van.','eladó munka közben','eladó szünetben','business','none'),
(1314,'hu','A vállát meg kell vizsgálni.','A térdét meg kell vizsgálni.','váll vizsgálata','táska a vállán','business','none'),
(1315,'hu','Esőzuhany? Inkább vízesés!','Kerti zuhany? Inkább vízesés!','nagy esőzuhany','zuhanyfüggöny','dramatic','exaggeration'),
(1316,'hu','A testvérek nevetnek.','A testvérek veszekednek.','együtt nevető testvérek','játékon veszekedő testvérek','chill','none'),
(1317,'hu','Kőburkolatos járdán van.','Fapallós járdán van.','széles kőjárda','emberekkel teli járda','business','none'),
(1319,'hu','Szingli és boldog.','Szingli és szomorú.','boldog szingliként','egyetlen csésze tea','chill','none'),
(1321,'hu','Parancsoljon, az étele, uram.','Parancsoljon, a számlája, uram.','az étele, uram','a számlája, uram','business','none'),
(1323,'hu','Micsoda magas felhőkarcoló!','Micsoda magas világítótorony!','felnézés egy felhőkarcolóra','lenézés egy felhőkarcolóról','dramatic','exclamation'),
(1325,'hu','Alszik. A párna a barátja.','Alszik. A macska a barátja.','alvás az ágyon','alvás a vonaton','low_iq','guessing'),
(1326,'hu','Puha papucs, lusta reggel.','Puha zokni, lusta reggel.','puha papucs felvétele','puha papucsok a boltban','chill','none'),
(1327,'hu','A férfi szlovák népviseletben van.','A nő szlovák népviseletben van.','szlovák népviselet','szlovák focimez','chill','none'),
(1328,'hu','Szlovákiában táncol!','Szlovákiában úszik!','rét Szlovákiában','strand Szlovákiában','dramatic','exclamation'),
(1337,'hu','A kanapén játszanak.','A padlón játszanak.','barátok egy szürke kanapén','barátok egy szürke buszon','chill','none'),
(1340,'hu','Valaki titokban lelép.','Valaki titokban táncol.','elsétáló valaki','kutyát sétáltató valaki','gossip','guessing'),
(1342,'hu','Hazajött a fia!','Hazajött a lánya!','felnőtt fiát ölelve','fiának búcsút intve','dramatic','exclamation'),
(1344,'hu','A pók dolgozik.','A hangya dolgozik.','pók a hálójában','pók a kádban','business','none'),
(1346,'hu','A bokszoló vizet köp.','A bokszoló vizet iszik.','víz köpése vödörbe','rágó kiköpése','chill','none'),
(1347,'hu','Egy kéz kinyom egy szivacsot.','Egy kéz kinyom egy citromot.','kinyomott habos szivacs','piskóta','chill','none'),
(1350,'hu','Átmegy a téren. Csá, galambok!','Átmegy a folyón. Csá, galambok!','futás át a téren','üldögélés egy csendes téren','slang','none'),
(1353,'hu','Egy fényes csillag. Kívánj valamit!','Egy fényes hold. Kívánj valamit!','fényes csillagra mutatva','csillag a fa tetején','slang','exclamation'),
(1354,'hu','Már megint késésben a pályaudvaron!','Már megint késésben a reptéren!','rohanás a pályaudvaron át','alvás a pályaudvaron','dramatic','guessing'),
(1355,'hu','Kezek a kormánykeréken.','Kezek a telefonon.','kezek a kormánykeréken','hajó kormánykereke','chill','none'),
(1358,'hu','A mostohaanyja befonja a haját.','A mostohaanyja levágja a haját.','hajat fonó mostohaanya','mostohaanya az iskolában','chill','none'),
(1359,'hu','A mostohanővérek nem bírják abbahagyni a nevetést.','A mostohanővérek nem bírják abbahagyni a sírást.','együtt nevető mostohanővérek','egy ágyon osztozó mostohanővérek','gossip','exaggeration'),
(1360,'hu','Sztetoszkópot használ. Pszt!','Lázmérőt használ. Pszt!','hallgatózás sztetoszkóppal','sztetoszkóp az asztalon','dramatic','exclamation'),
(1362,'hu','Öltésekkel varrják össze a vágást.','Ragtapaszt tesznek a vágásra.','öltések az alkaron','öltések egy ingen','chill','none'),
(1363,'hu','Ez a kő úszni fog, ugye?','Ez a levél úszni fog, ugye?','kő a tó fölött','kő a falban','low_iq','guessing'),
(1365,'hu','Egy idegen megállítja.','Egy rendőr megállítja.','kapucnis idegen','idegen kutyával','dramatic','none'),
(1366,'hu','Egy levél szörfözik a patakon.','Egy béka szörfözik a patakon.','tiszta erdei patak','halakkal teli patak','low_iq','exaggeration'),
(1367,'hu','Átkel egy forgalmas utcán.','Átkel egy forgalmas hídon.','forgalmas nagyvárosi utca','csendes falusi utca','business','none'),
(1369,'hu','Eső? Egy utcai lámpával táncol!','Eső? Egy közlekedési lámpával táncol!','égő utcai lámpák sora','égő gyertyák sora','dramatic','exclamation'),
(1371,'hu','A metró szupergyors.','A metró szuperlassú.','elsuhanó metrószerelvény','metrótérkép','slang','exaggeration'),
(1372,'hu','A bőröndje szürke és praktikus.','A bőröndje piros és praktikus.','szürke bőrönd húzása','szürke bőrönd bepakolása','business','none'),
(1373,'hu','Nyári vibe: nagy ugrás a tóba.','Nyári vibe: nagy ugrás a medencébe.','nyári ugrás a tóba','nyári medencés buli','slang','none'),
(1375,'hu','Repül az izzadság a kesztyűjéről!','Repül az izzadság a cipőjéről!','izzadság a karján','izzadság egy ingen','dramatic','exclamation'),
(1378,'hu','Svájci fondüt eszik.','Svájci csokit eszik.','svájci sajtfondü','svájci csokifondü','chill','none'),
(1379,'hu','Valaki megtalálta a kapcsolót. Hűha.','Valaki megtalálta a telefont. Hűha.','villanykapcsoló','vasúti váltó','low_iq','exaggeration'),
(1380,'hu','Svájc: itt még a tehenek is zenét kapnak.','Svájc: itt még a kecskék is zenét kapnak.','alpesi kürt Svájcban','kolompbolt Svájcban','chill','exaggeration'),
(1381,'hu','Spriccel a fecskendő!','Spriccel az üveg!','spriccelő fecskendő','fecskendő feltöltése','dramatic','exclamation'),
(1383,'hu','A szabó egy zakót javít.','A szabó egy cipőt javít.','szabó mérőszalaggal','cipőt árusító szabó','chill','none'),
(1385,'hu','Víz a csapból! Hűha!','Víz a slagból! Hűha!','csap megnyitása','vállveregetés','low_iq','exclamation'),
(1386,'hu','A taxisofőr integet!','A taxisofőr alszik!','integető taxisofőr','taxisofőr éjjel','slang','exclamation'),
(1389,'hu','A nő könnycseppjei hullanak.','A férfi könnycseppjei hullanak.','könnycsepp az arcán','szakadás a ruháján','dramatic','none'),
(1390,'hu','Meg akarja érinteni a holdat.','Meg akarja érinteni a napot.','nyúlás a hold felé','hold a tenger fölött','dramatic','guessing'),
(1394,'hu','Nagy narancssárga nap a tenger fölött.','Nagy narancssárga nap a havas táj fölött.','nap a tenger fölött','nap a hegyek fölött','chill','none'),
(1396,'hu','Az egész színház a nőé!','Az egész színház a férfié!','üres régi színház','emberekkel teli színház','dramatic','exaggeration'),
(1398,'hu','Hatalmas a hőmérője!','Hatalmas a fogkeféje!','nagy üveghőmérő','hőmérő a falon','dramatic','exclamation'),
(1400,'hu','A torkát vizsgálják.','A fülét vizsgálják.','fény a torokban','torokköszörülés','business','none'),
(1403,'hu','Ezek a lábujjak imádják a strandot!','Ezek a lábujjak imádják a havat!','lábujjak nedves homokban','lábujjak puha fűben','dramatic','exaggeration'),
(1404,'hu','A nyelvével havat fog ebédre.','A kezével havat fog ebédre.','kinyújtott nyelv','megharapott nyelv','low_iq','guessing'),
(1405,'hu','Minden egyes fogat megvizsgálnak.','Minden egyes körmöt megvizsgálnak.','fog vizsgálata','fogtündér','business','none'),
(1406,'hu','Nézd a fogkefémet!','Nézd a hajkefémet!','habos fogkefe','fogkefe egy pohárban','dramatic','exclamation'),
(1410,'hu','Egy közlekedési lámpánál áll.','Egy buszmegállóban áll.','várakozás a közlekedési lámpánál','várakozás a vasútállomáson','chill','none'),
(1411,'hu','Régi villamos, nagy mosoly, szuper stílus.','Régi busz, nagy mosoly, szuper stílus.','régi zöld villamos','régi zöld busz','flirt','none'),
(1413,'hu','Futópad: futás a semmibe.','Futópad: séta a semmibe.','futás futópadon','elromlott futópad javítása','ironic','cliche'),
(1414,'hu','Hű, a tölgy hatalmas!','Hű, a pálma hatalmas!','hatalmas tölgyfa','hatalmas piknikkosár','low_iq','exclamation'),
(1415,'hu','Beszáll a kamionjába.','Beszáll az autójába.','nagy ezüst kamion','nagy ezüst busz','chill','none'),
(1416,'hu','Kihajt egy alagútból.','Kihajt egy garázsból.','kifelé egy közúti alagútból','befelé egy vasúti alagútba','chill','none'),
(1419,'hu','Ikrek, ugyanaz a ruha. Megbeszélték?','Ikrek, ugyanaz a kalap. Megbeszélték?','egyforma ruhás ikrek','ikrek babakocsiban','gossip','guessing'),
(1420,'hu','A világ legjobb nagybácsija!','A világ legjobb nagynénje!','a nagybácsi vállán','a nagybácsi biciklijén','slang','exaggeration'),
(1422,'hu','Egy kéz a képernyőre mutat.','Egy kéz az ablakra mutat.','mutatni a képernyőre','mutatni az ajtóra','chill','none'),
(1423,'hu','Egy oszlopdiagramra mutat.','Egy kördiagramra mutat.','oszlop- és vonaldiagramok','diagram papíron','business','none'),
(1424,'hu','Az álló kolléga kéket visel.','Az álló kolléga pirosat visel.','kolléga kék ingben','kolléga piros ingben','chill','none'),
(1425,'hu','Találd ki, ki van pórázon.','Találd ki, ki van a kanapén.','kutya pórázon','póráz nélküli kutya','gossip','none'),
(1427,'hu','Kötélen egyensúlyoz!','Egy farönkön egyensúlyoz!','egyensúlyozás vékony kötélen','egyensúlyozás vékony ágon','dramatic','exclamation'),
(1429,'hu','Énekel a barátainak.','Táncol a barátainak.','éneklés mikrofonba','éneklés a zuhany alatt','chill','none'),
(1432,'hu','Jelmezben énekel. Az üvegcipő készen áll.','Jelmezben táncol. Az üvegcipő készen áll.','éneklés jelmezben','jelmezvásárlás','gossip','guessing'),
(1434,'hu','Senki sem látja a tolvajt a csilláron.','Senki sem látja a tolvajt a tetőn.','tolvaj zsákkal','tolvaj pisztollyal','ironic','guessing'),
(1435,'hu','Nem adja át a mikrofont.','Nem adja át a gitárt.','mikrofon állványon','mikrofon a telefonban','ironic','guessing'),
(1436,'hu','Korban sokszínű a társaság.','A társaság csupa tinédzser.','öt sokszínű portré','öt sokszínű tájkép','chill','none'),
(1438,'hu','A férfi podcastot vesz fel.','A nő podcastot vesz fel.','podcastfelvétel','podcasthallgatás','chill','none'),
(1441,'hu','A győzelme megérte az erőfeszítést.','A győzelme megérte a pénzt.','megéri az erőfeszítést','erőfeszítés, hogy ébren maradjon','chill','none'),
(1442,'hu','Ez az iroda tele van növényekkel.','Ez az iroda tele van kutyákkal.','világos egyterű iroda','sötét, üres iroda','business','none'),
(1446,'hu','Dugig van a konferencia!','Üres a konferencia!','zsúfolt konferenciaterem','videokonferencia-hívás','dramatic','exclamation'),
(1447,'hu','A vakcina kicsit fáj.','A vakcina kicsit csiklandoz.','vakcina a karba','vakcina a lábba','chill','understatement'),
(1450,'hu','Virág egy látogatótól. Cuki.','Cukorka egy látogatótól. Cuki.','látogató virággal','látogató a múzeumban','flirt','none'),
(1451,'hu','Ettől a vitamintól nevet.','Ettől a vitamintól sír.','narancssárga gumivitamin','zöld gumivitamin','gossip','guessing'),
(1452,'hu','A vulkán kicsit ideges.','A vulkán kicsit álmos.','éjjel kitörő vulkán','hóval borított vulkán','ironic','understatement'),
(1453,'hu','A hajó hosszú tengeri utazáson van.','A hajó folyami utazáson van.','tengeri utazás az óceánon át','utazás a folyó mentén','chill','none'),
(1454,'hu','A derekát méri.','A karját méri.','mérőszalag a derék körül','öv a derék körül','business','none'),
(1457,'hu','A pincérnő turmixot szolgál fel.','A pincérnő pizzát szolgál fel.','reggelit felszolgáló pincérnő','reggeliző pincérnő','business','none'),
(1458,'hu','A gyaloglónak aranyszínű kutyája van.','A gyaloglónak fekete kutyája van.','gyalogló túrabotokkal','gyalogló babakocsival','chill','none'),
(1459,'hu','Fehérre festi a falat.','Kékre festi a falat.','nagy, csupasz fal','fal egy kert körül','chill','none'),
(1466,'hu','Eső vagy nap? Az időjárás nem tud dönteni.','Hó vagy nap? Az időjárás nem tud dönteni.','változó időjárás egy dombon','napos időjárás a strandon','ironic','guessing'),
(1467,'hu','Egy szerelő egy kereket gurít.','Egy szerelő egy kereket mos.','autókerék gurítása','kerék egy biciklin','business','none'),
(1468,'hu','Teljes sebesség egy verseny-kerekesszékben!','Teljes sebesség egy versenygokartban!','verseny-kerekesszék','rámpa kerekesszékeseknek','dramatic','exclamation'),
(1473,'hu','A munkás egy gerendát tart.','A munkás egy csövet tart.','munkás védőszemüvegben','munkás öltönyben','chill','none'),
(1476,'hu','Az író éjjel gépel, hát persze.','Az író délben gépel, hát persze.','író az írógépnél','író a laptopnál','ironic','cliche'),
(1477,'hu','A röntgenfelvételen kézcsontok látszanak.','A röntgenfelvételen lábcsontok látszanak.','kéz röntgenfelvétele','láb röntgenfelvétele','nerd','none'),
(1479,'hu','Ebédfelszolgálás az állatkertben.','Ebédfelszolgálás a tanyán.','zsiráf az állatkertben','oroszlán az állatkertben','business','none'),
(1481,'hu','A várnak két boltíves átjárója van.','A várnak négy boltíves átjárója van.','boltíves átjáró a lépcső alatt','boltíves átjáró a folyó fölött','chill','none'),
(1482,'hu','Szuper arany fülbevalók!','Szuper ezüst fülbevalók!','nagy arany karikafülbevalók','fülbevalók díszdobozban','flirt','exclamation'),
(1483,'hu','Pirosak az eprek.','Zöldek az eprek.','epertő','epres turmix','chill','none'),
(1485,'hu','El akarják adni a házat.','El akarják adni az autót.','fehér ház eladása','piros autó eladása','chill','none'),
(1487,'hu','Az istennek arany trónusa van.','Az istennek ezüst trónusa van.','isten a trónon','király lóháton','chill','none'),
(1488,'hu','Lovak húznak egy hintót.','Ökrök húznak egy hintót.','aranyozott királyi hintó','aranyozott vasúti kocsi','chill','none'),
(1489,'hu','A tündér legjobb barátja egy béka.','A tündér legjobb barátja egy macska.','tündér a mohán','tündér az égen','gossip','guessing'),
(1491,'hu','Ennyi pillangó!','Ennyi madár!','pillangók a virágok fölött','pillangók egy ingen','dramatic','exaggeration'),
(1495,'hu','Tény: az egyszarvúnak egy szarva van.','Tény: az egyszarvúnak két szarva van.','ágaskodó egyszarvú','alvó egyszarvú','nerd','cliche'),
(1497,'hu','A hegedű régi kottán fekszik.','A gitár régi kottán fekszik.','hegedű rózsákkal','hegedűóra','chill','none'),
(1498,'hu','Két srác egy hőlégballonban. Csá!','Két srác egy lovon. Csá!','hőlégballon két férfival','hőlégballon két kutyával','slang','none'),
(1499,'hu','A szárak hosszúak és kunkorodók.','A szárak rövidek és vastagok.','hosszú, kunkorodó szárak','virágszárak vázában','nerd','none'),
(1501,'hu','Zöld folyadékot önt.','Piros folyadékot önt.','öntés széles tálból','tea öntése csészébe','chill','none'),
(1502,'hu','Naplemente kettesben. De édes.','Reggeli kettesben. De édes.','közös naplemente-nézés','naplemente a hegyekben','gossip','none'),
(1504,'hu','A filozófusnak szakálla van.','A filozófusnak kalapja van.','szakállas filozófus','nevető filozófus','chill','none'),
(1505,'hu','Szupermarket-túra, ötvenes évek stílusban.','Pékség-túra, ötvenes évek stílusban.','szupermarket-pénztár','szupermarket parkolója','slang','cliche'),
(1508,'hu','A templomnak magas tornya van.','A templomnak apró tornya van.','régi kőtemplom','régi kőhíd','business','none'),
(1510,'hu','Miért sikít az alak?','Miért énekel az alak?','sikítás egy hídon','sikítás hullámvasúton','low_iq','guessing'),
(1513,'hu','Összeteszi a kezét, hogy imádkozzon.','Összeteszi a kezét, hogy tapsoljon.','imádkozásra összetett kezek','imádkozás nyitott tenyérrel','chill','none'),
(1514,'hu','Vallás egy régi festményen.','Vallás egy modern rajzfilmben.','festmény a vallásról','könyv a vallásról','nerd','none'),
(1519,'hu','Olyan csinosak a virágai!','Olyan csinosak a tollai!','csinos virágok a hajában','csinos szalagok a hajában','flirt','none'),
(1520,'hu','Göndör haj és gyöngyök? Elegáns.','Rövid haj és gyöngyök? Elegáns.','hosszú, göndör szőke haj','göndör szőrű kutya','flirt','none'),
(1522,'hu','Egy kosár cseresznye van nála.','Egy kosár alma van nála.','kosár cseresznye','kutya egy kosárban','chill','none'),
(1523,'hu','Virágokkal teli szőke haj.','Virágokkal teli fekete haj.','hosszú, hullámos szőke haj','rövid szőke haj','chill','none'),
(1524,'hu','Stoppol, és egy ufó fékez le neki.','Stoppol, és egy busz fékez le neki.','stoppolás hegyi úton','stoppolás az autópályán','gossip','guessing'),
(1525,'hu','Felénk jön a vonat!','Felénk jön a kamion!','fekete gőzvonat','edzés egy versenyre','dramatic','exclamation'),
(1526,'hu','A harcosnak sisakja van.','A harcosnak pajzsa van.','szamurájharcos','lovas harcos','chill','none'),
(1527,'hu','A székesegyháznak hatalmas kupolája van.','A székesegyháznak lapos teteje van.','barokk székesegyház kupolája','éneklő székesegyházi kórus','chill','none'),
(1528,'hu','Léggömbök Japán fölött!','Madarak Japán fölött!','Japán jelképei','Japán térképe','dramatic','exclamation'),
(1529,'hu','Két torony, egy vulkán.','Két torony, két vulkán.','két kerek vártorony','két magas víztorony','chill','none'),
(1530,'hu','A kisváros dombon fekszik. Állítólag szép a kilátás.','A kisváros a tenger mellett fekszik. Állítólag szép a kilátás.','régi dombtetői kisváros','új tengerparti kisváros','gossip','none'),
(1531,'hu','Egy boltív keretezi a templomot.','Egy fa keretezi a templomot.','nagy csúcsos boltív','nagy csúcsos torony','chill','none'),
(1534,'hu','Hű, minden lónak egy szarva van!','Hű, minden lónak két szarva van!','egyszarvú hosszú szarva','autó hangos dudája','low_iq','exclamation'),
(1535,'hu','Fejjel lefelé áll. Semmiség.','Hanyatt fekszik. Semmiség.','egyensúlyozás fejjel lefelé','lógás fejjel lefelé','slang','understatement'),
(1537,'hu','Egyiptom fáraója íjat tart.','Egyiptom fáraója kardot tart.','Egyiptom fáraója','piramis Egyiptomban','chill','none'),
(1538,'hu','Két oszlop között áll.','Két fa között áll.','két díszített oszlop','rovat egy újságban','chill','none'),
(1541,'hu','Pici kápolna, havas vibe.','Pici kápolna, napos vibe.','havas fehér kápolna','vendégekkel teli kápolna','slang','none'),
(1543,'hu','Egy nagy káposztát tart.','Egy nagy tököt tart.','káposztával teli kert','káposzta egy fazékban','chill','none'),
(1544,'hu','Kiteregeti a mosott ruhát.','Kiteregeti a zászlókat.','fehér ruha teregetése','fehér ruha hajtogatása','chill','none'),
(1545,'hu','Hatalmas a királynő gallérja!','Hatalmas a királynő kutyája!','királynő jogarral','királynő karddal','gossip','none'),
(1547,'hu','A szent ember mélyen gondolkodik.','A szent ember hangosan nevet.','gondolkodó szent ember','imádkozó szent ember','chill','none'),
(1548,'hu','Minden ablakban emberek vannak.','Minden ablakban macskák vannak.','egy család minden ablakban','egy macska minden ablakban','chill','none'),
(1549,'hu','Valaki kiborította az összes festéket!','Valaki kiborította az összes tejet!','festékcseppek','egy doboz festék','dramatic','blaming_someone'),
(1551,'hu','Az ég egy gitárt küldött nekünk!','Az ég egy hegedűt küldött nekünk!','gitár a magasba emelve','gitárhangolás','dramatic','exclamation'),
(1554,'hu','A szerzetesnél piros esernyő van.','A szerzetesnél fekete esernyő van.','rózsaszín ruhás szerzetes','fekete ruhás szerzetes','chill','none'),
(1555,'hu','Az alak egy nagy kardot tart.','Az alak egy nagy lándzsát tart.','függőlegesen tartott kard','kard a falon','chill','none'),
(1559,'hu','Egy sárga váza tele napraforgóval.','Egy sárga váza tele rózsával.','napraforgók vázában','napraforgók a mezőn','chill','none'),
(1560,'hu','Egy hintánál áll.','Egy kapunál áll.','kötélhinta','szvingtánc','chill','none'),
(1562,'hu','A cowboy belovagol a naplementébe.','A cowboy belovagol a tengerbe.','cowboy lóháton','cowboy bikán','dramatic','cliche'),
(1565,'hu','Rozsdás fogaskerekekből áll.','Rozsdás láncokból áll.','rozsdás fém fogaskerekek','rozsdás fém láncok','chill','none'),
(1567,'hu','A repülőgép emelkedik!','A repülőgép zuhan!','emelkedő repülőgép','leereszkedő repülőgép','dramatic','exclamation'),
(1568,'hu','A hold alatt vitorlázik.','A nap alatt vitorlázik.','vitorlázni éjjel','vitorlázni a napsütésben','chill','none'),
(1569,'hu','Ez egy sraffozott portré.','Ez egy akvarell portré.','tussal rajzolt portré','olajjal festett portré','nerd','none'),
(1574,'hu','Egy ágról lámpás lóg.','Egy tetőről lámpás lóg.','lámpás láncon','lámpás a kezében','chill','none'),
(1575,'hu','A pár ölelkezik.','A pár veszekszik.','pár a hold alatt','pár a tengerparton','chill','none'),
(1576,'hu','Álmában a holdon hintázik.','Álmában egy fán hintázik.','álom a holdról','álom a tengerről','chill','guessing'),
(1579,'hu','Az okostelefonok házat építettek.','A könyvek házat építettek.','okostelefonokból épült ház','okostelefon a zsebben','chill','exaggeration'),
(1581,'hu','Furgonélet, bébi!','Sátorélet, bébi!','furgon szörfdeszkával','furgon biciklivel','slang','exclamation'),
(1583,'hu','Az űrhajós elrepül!','A pilóta elrepül!','űrhajós az űrben','űrhajós a Holdon','dramatic','exclamation'),
(1584,'hu','A szoknyája is táncol.','A kutyája is táncol.','táncolás piros szoknyában','táncolni az esőben','chill','exaggeration'),
(1585,'hu','Öt fehér rózsa van.','Öt piros rózsa van.','öt fehér rózsavirág','fehér rózsák vázában','chill','none'),
(1586,'hu','Szennyezés, amerre csak nézel.','Virágok, amerre csak nézel.','gyár okozta szennyezés','hajó okozta szennyezés','dramatic','exaggeration'),
(1589,'hu','Ez a személy szomorúnak tűnik.','Ez a személy boldognak tűnik.','szomorú, narancssárga hajú alak','szomorú, kék hajú alak','chill','none'),
(1590,'hu','A csuklya tele van csillagokkal.','A csuklya tele van virágokkal.','csillagos csuklya','szemébe húzott csuklya','chill','none'),
(1591,'hu','Ez a világítótorony csíkos.','Ez a világítótorony pöttyös.','csíkos világítótorony','csíkos strandház','chill','none'),
(1592,'hu','A robotnak kék az ajka. Fázik?','A robotnak piros az ajka. Fázik?','fém robotfej','robotporszívó','low_iq','guessing'),
(1593,'hu','Imádom ezt a kék hajvágást!','Imádom ezt a kék sapkát!','kékeszöld bubi hajvágás','hajvágás a fodrászatban','flirt','exclamation'),
(1595,'hu','Két piramis. Nagyon hegyes.','Két torony. Nagyon hegyes.','két barna piramis','narancsokból rakott piramis','low_iq','none'),
(1596,'hu','A hold ragyog Oroszország fölött.','A nap ragyog Oroszország fölött.','templom Oroszországban','palota Oroszországban','chill','none'),
(1597,'hu','Hoppá, az arca víz alatt van!','Hoppá, az arca a homokban van!','kutya a víz alatt','kutya a víz fölött','dramatic','exclamation'),
(1598,'hu','Jézus felemeli az egyik kezét.','Jézus felemeli mindkét kezét.','áldást adó Jézus','keresztet vivő Jézus','chill','none'),
(1600,'hu','Egy kis csónak van a csatornán.','Egy nagy hajó van a csatornán.','csónak a csatornán','csónak a tavon','chill','none'),
(1603,'hu','Kint a tengeren kőolajat fúrnak.','Egy dombon kőolajat fúrnak.','tengeri kőolajfúró platform','olaj egy serpenyőben','business','none'),
(1609,'hu','Balettozik egy sziklán!','Balettozik egy hajón!','balett egy sziklán','balett a stúdióban','dramatic','exclamation'),
(1610,'hu','A hold megvilágítja az erkélyt.','Egy lámpa megvilágítja az erkélyt.','holdfényes erkély','napos erkély','dramatic','none'),
(1611,'hu','Egy galamb repül a fényben.','Egy varjú repül a fényben.','kitárt szárnyú galamb','galamb kalitkában','chill','none'),
(1612,'hu','Gyerekek Dél-Koreából integetnek.','Gyerekek Dél-Koreából táncolnak.','integető gyerekek Dél-Koreából','éneklő gyerekek Dél-Koreából','chill','none'),
(1613,'hu','Három rakéta száll fel!','Két rakéta száll fel!','naplementében emelkedő rakéták','naplementében leszálló rakéta','dramatic','exclamation'),
(1614,'hu','Bikák futnak Spanyolországban!','Lovak futnak Spanyolországban!','futó bikák Spanyolországban','lóverseny Spanyolországban','dramatic','exclamation'),
(1617,'hu','Az angyal egy gyermeket vezet.','Az angyal egy bárányt vezet.','gyermeket vezető angyal','hárfázó angyal','chill','none'),
(1618,'hu','Angyalok repkednek körülötte.','Madarak repkednek körülötte.','szárnyas angyalok a felhőkben','angyalok a karácsonyfán','chill','none'),
(1619,'hu','A nagy hajónak duzzadnak a vitorlái.','A nagy hajónak nincsenek vitorlái.','duzzadó vitorlák a szélben','szakadt vitorlák a szélben','chill','none'),
(1620,'hu','A mennyország ma nagyon zsúfoltnak tűnik.','A mennyország ma nagyon üresnek tűnik.','repkedő angyalkák a mennyországban','szentekkel teli mennyország','ironic','exaggeration'),
(1623,'hu','Ennyi felhőkarcoló!','Ennyi híd!','felhőkarcolók alkonyatkor','épülő felhőkarcoló','dramatic','exclamation'),
(1625,'hu','A szörfös egy szörfdeszkát tart.','A szörfös egy gitárt tart.','függőlegesen tartott szörfdeszka','hullámlovaglás szörfdeszkán','chill','none'),
(1629,'hu','Csak egy ananász. Olyan magányos.','Csak egy banán. Olyan magányos.','egyetlen álló ananász','szeletekre vágott ananász','dramatic','exaggeration'),
(1630,'hu','A polipnak nyolc karja van. Megszámoltam.','A polipnak hat karja van. Megszámoltam.','nyolckarú polip','polip egy befőttesüvegben','low_iq','none'),
(1631,'hu','A boszorkánynak seprűje van. Okos.','A boszorkánynak macskája van. Okos.','boszorkány a seprűjével','boszorkány a seprűjén','low_iq','none'),
(1633,'hu','Ez a szobor téged figyel.','Ez a kutya téged figyel.','vízköpő szobor','lószobor','gossip','guessing'),
(1635,'hu','Sellőfarok? Totál zöld.','Sellőfarok? Totál kék.','mosolygó rajzfilmsellő','sellő egy sziklán','slang','none'),
(1638,'hu','Függönyök keretezik a holdfényes tengert.','Függönyök keretezik a napfényes tengert.','nehéz lila függönyök','nehéz lila szőnyegek','dramatic','none'),
(1639,'hu','Tény: a kisbaba egy istállóban van.','Tény: a kisbaba egy kastélyban van.','kisbaba az istállóban','ló az istállóban','nerd','none'),
(1641,'hu','Egy ijesztő bohóc és egy varjú.','Egy ijesztő bohóc és egy macska.','ijesztő szemek az égen','ijesztő filmek estéje','chill','none'),
(1642,'hu','A falu fölött vörös az ég.','A falu fölött kék az ég.','falu naplementekor','hóba temetett falu','business','none'),
(1643,'hu','Cowboykalap van rajta.','Baseballsapka van rajta.','széles cowboykalap','széles szalmakalap','chill','none'),
(1644,'hu','A lovag teljes páncélt visel.','A lovag nem visel páncélt.','fémpáncélos lovag','páncél nélküli lovag','chill','none'),
(1647,'hu','Egy nő van a képeslapon.','Egy férfi van a képeslapon.','régi, szakadt képeslap','tengerparti képeslap','chill','none'),
(1649,'hu','Itt minden színes!','Itt minden szürke!','színes szivárványút','színes esernyő','dramatic','exclamation'),
(1650,'hu','Szép kastély, ijesztő szikla.','Szép kastély, ijesztő híd.','kastély egy sziklán','szikla a tenger fölött','gossip','understatement'),
(1651,'hu','Csillagos a kék köpenye.','Csillagos a piros köpenye.','csillagos kék köpeny','tollakból készült köpeny','chill','none'),
(1652,'hu','Mindjárt megérinti a pillangót!','Mindjárt megérinti a madarat!','megérinteni egy világító pillangót','elkapni egy világító pillangót','dramatic','guessing'),
(1653,'hu','A macska az aranyhalat akarja...','A macska a madarat akarja...','aranyhal gömbakváriumban','aranyhal egy tóban','dramatic','guessing'),
(1655,'hu','Hű, milyen magas a koronája!','Hű, milyen kicsi a koronája!','magas arany korona','kis ezüst korona','low_iq','exclamation'),
(1656,'hu','Az ajkai pirosak.','Az ajkai kékek.','fényes piros ajkak','ajkak egy pohár szélén','chill','none'),
(1658,'hu','Sötét kő, vörös rózsák, menő.','Sötét kő, fehér rózsák, menő.','sötét gótikus boltív','sötét erdei ösvény','slang','none'),
(1660,'hu','Egy láda tele kinccsel!','Egy láda tele üvegekkel!','nyitott kincsesláda','papírra rajzolt kincses térkép','dramatic','exclamation'),
(1661,'hu','Az idő kicsit nehezen olvasható le.','A térkép kicsit nehezen olvasható le.','az idő leolvasása','időgép','chill','understatement'),
(1664,'hu','A pap figyelmesen hallgat.','A pap énekel.','pap a gyóntatószékben','pap egy esküvőn','chill','none'),
(1665,'hu','Egy ősi templomban van.','Egy ősi várban van.','ősi egyiptomi templom','ősi görög templom','chill','none'),
(1666,'hu','A fáraó fején kobra ül.','A fáraó fején sólyom ül.','fáraó profilból','fáraó a trónon','nerd','none'),
(1667,'hu','Párizs éjjel. Tiszta varázslat!','Párizs délben. Tiszta varázslat!','Párizs éjjel','Párizs esőben','dramatic','exclamation'),
(1669,'hu','Két szárny, mégsem tud repülni a szobor.','Négy szárny, mégsem tud repülni a szobor.','két tollas szárny','két repülőszárny','low_iq','understatement'),
(1670,'hu','Piros busz Londonban. Klasszikus.','Piros autó Londonban. Klasszikus.','piros busz Londonban','piros busz Párizsban','chill','cliche'),
(1672,'hu','Prága alkonyatkor ragyog.','Prága délben ragyog.','a prágai vár alkonyatkor','a prágai vár hóban','chill','none'),
(1674,'hu','Lila ég, lila dombok.','Lila ég, zöld dombok.','lila csillagos ég','lila virágmező','chill','none'),
(1675,'hu','Egyedül áll egy fa mellett.','Egyedül áll egy ház mellett.','egyedül egy üres mezőn','egyedül egy üres szobában','dramatic','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
