begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(1676,'hu','Egy kávéval ülni? Micsoda vibe.','Egy könyvvel ülni? Micsoda vibe.','fotelben ülni','íróasztalnál ülni','slang','cliche'),
(1677,'hu','Épp nem a várost nézik.','Épp nem a telefonjukat nézik.','város alkonyatkor','város délben','ironic','cliche'),
(1679,'hu','A templom arany színű.','A templom ezüst színű.','templom egy tó mellett','templom egy városban','chill','none'),
(1681,'hu','Páva, milyen hosszú a farktollad!','Páva, milyen rövid a farktollad!','páva egy ágon','páva a földön','dramatic','exclamation'),
(1684,'hu','Már a Mona Lisa is maszkot hord.','Már a Mona Lisa is kalapot hord.','fehér orvosi maszk','bulis maszk','gossip','exaggeration'),
(1685,'hu','A tömeg elmenekül!','A tömeg berohan!','a templomból menekülő tömeg','bent imádkozó tömeg','dramatic','exclamation'),
(1686,'hu','Saját magát tölti.','A telefonját tölti.','töltés a konnektorból','autóakkumulátor töltése','low_iq','none'),
(1689,'hu','Jézus egy barlang mellett áll.','Jézus egy tó mellett áll.','Jézus egy barlangnál','Jézus a tengernél','chill','none'),
(1693,'hu','Egy lovag karddal suhint.','Egy lovag fejszével suhint.','páncélos lovag','lovag lóháton','chill','none'),
(1694,'hu','A törzsfőnök tollat visel.','A törzsfőnök koronát visel.','törzsfőnök tollal','törzsfőnök koronával','chill','none'),
(1695,'hu','Pisztolyt tart a kezében.','Telefont tart a kezében.','lefelé tartott pisztoly','felfelé tartott pisztoly','chill','none'),
(1696,'hu','A sas két fiókát menedzsel.','A sas négy fiókát menedzsel.','sas a fészke fölött','halat fogó sas','business','exaggeration'),
(1697,'hu','Legyező és kimonó: nagyon elegáns.','Könyv és kimonó: nagyon elegáns.','nyitott legyező','ventilátor nyáron','flirt','none'),
(1699,'hu','Valaki a zenére úszik.','Valaki a zenére repül.','átúszni a csendes vizet','úszni a medencében','chill','none'),
(1701,'hu','Egy liliom nő ki egy kancsóból.','Egy rózsa nő ki egy kancsóból.','liliom egy kancsóban','liliom egy tóban','chill','none'),
(1703,'hu','A levegőben olvas.','A levegőben alszik.','világító könyvet olvasni','üzenetet olvasni','chill','none'),
(1704,'hu','Az áll rajta: „boldog karácsonyt”.','Az áll rajta: „boldog születésnapot”.','régi karácsonyi képeslap','régi karácsonyfa','chill','none'),
(1706,'hu','Menő kutya, menő napszemüveg.','Menő kutya, menő kalap.','husky napszemüvegben','napszemüveg a strandtörölközőn','slang','none'),
(1707,'hu','A növények megeszik a házikót.','A növények megeszik a templomot.','benőtt kőházikó','házikó a tengerparton','ironic','exaggeration'),
(1709,'hu','A tanár magyaráz.','A tanár alszik.','tanár a táblánál','tanár az asztalánál','chill','none'),
(1710,'hu','A tábla üres.','A tábla tele van.','üres tábla','jegyzetekkel teli tábla','chill','none'),
(1711,'hu','A csontváz nagyon boldognak tűnik.','A csontváz nagyon szomorúnak tűnik.','csontváz masnival','csontváz a múzeumban','ironic','none'),
(1713,'hu','Több száz toll a tetején.','Több száz virág a tetején.','hosszú tollakból álló fejdísz','tollakkal teli párna','chill','exaggeration'),
(1716,'hu','Az űrruha fehér.','Az űrruha narancssárga.','fehér űrruha','űrruha a vállfán','chill','none'),
(1717,'hu','Ez a hangszer egy hegedű.','Ez a hangszer egy gitár.','vonós hangszer','fúvós hangszer','nerd','none'),
(1718,'hu','A Buddha 100%-ig nyugodt.','A Buddha 100%-ig dühös.','nyugodt arc','nyugodt tenger','nerd','exaggeration'),
(1724,'hu','A holdat tartja!','A napot tartja!','a holdat tartva','pipacsot tartva','dramatic','exclamation'),
(1725,'hu','Egy kereszt fekszik a földön.','Egy létra fekszik a földön.','kereszt a földön','kereszt egy templomon','chill','none'),
(1726,'hu','Piros köpenyt pörget.','Piros sálat pörget.','piros köpenyt pörgetve','köpenyben és maszkban','chill','none'),
(1728,'hu','Piros legyező fel, láb fel!','Piros kalap fel, láb fel!','piros legyezőt lengetve','mennyezeti ventilátor','dramatic','exclamation'),
(1729,'hu','Két háziállata van.','Három háziállata van.','lány a háziállataival','lány háziállatot vesz','chill','none'),
(1731,'hu','Egy nyíl eltalálta a zászlaját!','Egy nyíl eltalálta a lovát!','nyilak egy zászlóban','nyilak egy céltáblában','dramatic','exclamation'),
(1733,'hu','Na, mit tart a tünde? Egy fényt.','Na, mit tart a tünde? Egy kardot.','hegyes fülű tünde','tünde íjjal','gossip','guessing'),
(1734,'hu','Ez a szuperhős Pókember.','Ez a szuperhős Batman.','maszkos szuperhős','köpenyes szuperhős','chill','none'),
(1738,'hu','Hosszú sötét fátylat visel.','Hosszú fehér fátylat visel.','hosszú sötét fátyol','menyasszonyi fátyol','chill','none'),
(1741,'hu','A császár babérkoszorút visel.','A császár koronát visel.','császár babérkoszorúval','császár lóháton','nerd','none'),
(1742,'hu','Az angyal pajzsot tart.','Az angyal kardot tart.','nagy kerek pajzs','pajzs a földön','chill','none'),
(1743,'hu','Fagyi Olaszországban? Naná.','Pizza Olaszországban? Naná.','ferde torony Olaszországban','pizzakemence Olaszországban','chill','cliche'),
(1747,'hu','Tökéletes hely a sátornak!','Tökéletes hely a strandolásnak!','sátor egy dombon','sátor a tengerparton','slang','exaggeration'),
(1751,'hu','Minden tábla egy tájat mutat.','Minden tábla egy várost mutat.','nyíl alakú táblák tájképekkel','nyíl alakú táblák árakkal','chill','none'),
(1752,'hu','A szélmalom ablakai világítanak.','A szélmalom ablakai nyitva vannak.','szélmalom egy tó mellett','szélmalom egy mezőn','chill','none'),
(1756,'hu','Telefonon veszekednek.','Telefonon énekelnek.','telefonon veszekedni','a konyhában veszekedni','chill','none'),
(1757,'hu','Zene a virágok alatt? Romantikus.','Tánc a virágok alatt? Romantikus.','rózsaszín cseresznyevirágok','cseresznyevirág-tea','flirt','none'),
(1762,'hu','Egy férfi bálnába zuhan!','Egy férfi csónakba zuhan!','egy bálna szája','bálna egy akváriumban','dramatic','exclamation'),
(1766,'hu','Fekete és piros szedrek.','Fekete és zöld szedrek.','érett szeder egy ágon','szeder egy pitében','chill','none'),
(1777,'hu','Ez a csávó bendzsón játszik.','Ez a csávó dobon játszik.','bendzsón játszani','bendzsót hangolni','slang','none'),
(1779,'hu','Elszabadult a lánca!','Elszabadult a kötele!','körülötte csapkodó lánc','lánc a nyakában','dramatic','exaggeration'),
(1780,'hu','Egy kutya üldözi a biciklijét!','Egy macska üldözi a biciklijét!','biciklivel lefelé a lejtőn','biciklivel felfelé a lejtőn','dramatic','exclamation'),
(1781,'hu','Ebben a házban minden nap Halloween van.','Ebben a kastélyban minden nap Halloween van.','halloweeni kísértetház','halloweeni buli a suliban','chill','exaggeration'),
(1785,'hu','Ez egy gyönyörű rajz.','Ez egy gyönyörű fotó.','gyönyörű portré','gyönyörű naplemente','chill','none'),
(1786,'hu','Esőként hullanak a meteorok.','Esőként hullanak a levelek.','zuhogó meteorok','meteor egy múzeumban','nerd','none'),
(1787,'hu','Piros sál egy utcai lámpa alatt. Stílusos.','Kék sál egy utcai lámpa alatt. Stílusos.','világító utcai lámpa','törött utcai lámpa','flirt','none'),
(1788,'hu','Egy tengeri szörny utasokkal!','Egy tengeri teknős utasokkal!','felemelkedő tengeri szörny','szörny az ágy alatt','dramatic','exclamation'),
(1792,'hu','Egy tornyot építenek.','Egy hajót építenek.','hatalmas tornyot építeni','kis házat építeni','chill','none'),
(1794,'hu','Mennyi pávatoll!','Mennyi hattyútoll!','csillogó pávatollak','toll egy párnában','dramatic','exclamation'),
(1799,'hu','A cselló a legnagyobb.','A hegedű a legnagyobb.','nagy, sötét cselló','kicsi, sötét cselló','nerd','none'),
(1800,'hu','Egy mosolyt rejtenek el.','Egy telefont rejtenek el.','elbújni egy könyv mögött','elbújni az asztal alatt','chill','guessing'),
(1802,'hu','Hangjegyek ömlenek a gitárból!','Érmék ömlenek a gitárból!','hangjegyek vízesése','egy halom jegyzet','dramatic','exclamation'),
(1803,'hu','Mindjárt eldobja a labdát.','Mindjárt belerúg a labdába.','labdát dobni készül','házibulit tartani','chill','none'),
(1806,'hu','Két konty? Nagyon trendi.','Két masni? Nagyon trendi.','két kerek konty','két zsemle egy tányéron','gossip','none'),
(1807,'hu','Koponyák lebegnek körülötte.','Szívek lebegnek körülötte.','koponyák rózsaszín lángokban','koponyák egy kalózzászlón','chill','none'),
(1811,'hu','Az esőkabát hozza az elvárt teljesítményt.','Az esernyő hozza az elvárt teljesítményt.','hosszú sárga esőkabát','esőkabát egy fogason','business','none'),
(1812,'hu','A macska is kifelé néz.','A kutya is kifelé néz.','kinézni az ablakon','macskára vigyázni','chill','none'),
(1823,'hu','Ma este magányosnak érzi magát.','Ma reggel magányosnak érzi magát.','magányosan egy erkélyen','magányosan a tömegben','dramatic','none'),
(1827,'hu','A macska utálja a matekot.','A kutya utálja a matekot.','matekkal teleírt falak','matekkönyvek a padlón','low_iq','guessing'),
(1831,'hu','Egy faház van az izzóban.','Egy faház van a teáscsészében.','havas izzó','törött izzó','chill','none'),
(1832,'hu','Fényképet készít. Menő!','Telefonál. Menő!','fényképet készíteni éjjel','fényképet készíteni bent','slang','exclamation'),
(1833,'hu','Nekitámaszkodik a gitárjának.','Nekitámaszkodik a zongorájának.','nekitámaszkodni egy gitárnak','nekitámaszkodni egy fának','chill','none'),
(1834,'hu','Egy isten egy harcost tanít.','Egy isten egy gyereket tanít.','harcost tanítani','tömeget tanítani','chill','none'),
(1840,'hu','Egy óriási gép fogaskerekekből!','Egy óriási gép fából!','rozsdás fogaskerekekből álló gép','kávégép','dramatic','exaggeration'),
(1843,'hu','Havas környék éjjel.','Havas környék délben.','havas környék','környékbeli buli','chill','none'),
(1846,'hu','Egy daru repül a nap mellett.','Egy daru repül a hold mellett.','repülő fehér daru','dobozokat emelő daru','chill','none'),
(1847,'hu','Három karácsonyfát számolok.','Öt karácsonyfát számolok.','három kis karácsonyfa','karácsonyfa ajándékokkal','low_iq','none'),
(1849,'hu','Ragyog a varázslata!','Ragyog a haja!','ragyogó kék varázslat','kártyás bűvésztrükk','dramatic','exclamation'),
(1851,'hu','A köd elnyeli a völgyeket.','A hó elnyeli a völgyeket.','köd a völgyben','házakkal teli völgy','dramatic','none'),
(1853,'hu','A sárkány tüzet okád.','A sárkány jeget okád.','kis fehér sárkány','nagy zöld sárkány','chill','none'),
(1854,'hu','A gitárnak fehér húrjai vannak.','A gitárnak fekete húrjai vannak.','fehér húrok egy gitáron','fehér zsinór egy papírsárkányon','nerd','none'),
(1855,'hu','A páva farka óriási!','A páva farka rövid!','a farkát széttáró páva','a farkát rejtő páva','dramatic','exaggeration'),
(1856,'hu','Az alak pici. Az ég nagy.','Az alak óriási. Az ég nagy.','pici alak a füvön','pici polcfigura','low_iq','none'),
(1857,'hu','Ez egy húsvéti plakát.','Ez egy karácsonyi plakát.','húsvéti plakát','húsvéti tojáskeresés','chill','none'),
(1858,'hu','A gyereknél hosszú sál és nagy lufi van.','A gyereknél hosszú kard és nagy lufi van.','hosszú csíkos sál','sál egy fiókban','chill','none'),
(1860,'hu','A feje egy halom könyv.','A feje egy halom tányér.','egy halom könyv','egy halom doboz','ironic','none'),
(1861,'hu','Ezen az antik széken hattyú van.','Ezen az antik széken oroszlán van.','antik faragott szék','antik faragott óra','chill','none'),
(1862,'hu','A vázában rózsaszín rózsák vannak.','A vázában fehér rózsák vannak.','szürke klasszikus váza','törött klasszikus váza','chill','none'),
(1863,'hu','A hinta a holdról lóg!','A hinta egy fáról lóg!','a holdról lógva','egy fáról lógva','dramatic','exclamation'),
(1865,'hu','Azok a kék uszonyok? Maga a divat.','Azok a piros uszonyok? Maga a divat.','nagy, lebegő uszonyok','uszony egy búváron','gossip','exaggeration'),
(1866,'hu','Napszemüveg és pisztoly: klasszikus kém.','Napszemüveg és kés: klasszikus kém.','kém pisztollyal','kém fényképezőgéppel','ironic','cliche'),
(1868,'hu','Az igazságszolgáltatásnak rengeteg nehéz könyv kell.','Az igazságszolgáltatásnak rengeteg gyertya kell.','az igazságszolgáltatás mérlege','az igazságszolgáltatás kardja','chill','exaggeration'),
(1870,'hu','A haja a lábáig ér!','A haja az álláig ér!','nagyon hosszú sötét haj','hajszál a levesben','dramatic','exaggeration'),
(1871,'hu','Fehéren ragyog a szeme.','Pirosan ragyog a szeme.','fehéren ragyogó szem','fehéren ragyogó lámpa','chill','none'),
(1872,'hu','A fekete macska imádja a könyveket.','A fehér macska imádja a könyveket.','fekete macska könyveken','fekete macska kint','chill','guessing'),
(1874,'hu','A mólón ülnek.','A hajón ülnek.','egy mólón ülni','egy hídon ülni','chill','none'),
(1876,'hu','Olcsó sisak: egy gömbakvárium.','Olcsó sisak: egy vödör.','gömbakvárium a fején','gömbakvárium az asztalon','ironic','cheap_quality'),
(1878,'hu','A feje láthatatlan!','Az öltönye láthatatlan!','láthatatlan fej','láthatatlan kéz','dramatic','exclamation'),
(1879,'hu','A kupola aranyként ragyog.','A kupola ezüstként ragyog.','arany kupola','üvegkupola','dramatic','none'),
(1880,'hu','Minden idők legjobb találmánya: egy repülő hajó.','Minden idők legjobb találmánya: egy repülő autó.','repülő találmány','kerekes találmány','slang','exaggeration'),
(1881,'hu','Nyugodtan meditál.','Nyugodtan alszik.','lótuszülésben meditálni','vizsga előtt meditálni','chill','none'),
(1883,'hu','A tyúkok kint esznek.','A tyúkok bent esznek.','tyúkok a baromfiudvarban','tyúkok a konyhában','chill','none'),
(1884,'hu','A tükröződés fejjel lefelé áll.','A tükröződés nagyon elmosódott.','tükröződés a csendes vízben','tükröződés egy tükörben','nerd','none'),
(1885,'hu','A gazdag ember van legfelül.','A gazdag ember van legalul.','gazdag ember a csúcson','gazdag ember börtönben','chill','none'),
(1886,'hu','A fogyasztó tányérja üres.','A fogyasztó tányérja tele van.','éhes fogyasztó','fogyasztó egy boltban','business','none'),
(1887,'hu','Egy nehéz taligát tol.','Egy nehéz autót tol.','túlpakolt taligát tolni','babakocsit tolni','chill','none'),
(1889,'hu','Villámgyorsan mozog!','Szoborként ül!','a zenére mozogni','új lakásba költözni','slang','exaggeration'),
(1892,'hu','Az öreg férfinak vékony botja van.','Az öreg férfinak esernyője van.','az öreg férfi botja','az öreg férfi esernyője','chill','none'),
(1894,'hu','Jó éjszakát, kis sünök!','Jó éjszakát, kis nyuszik!','sündisznócsalád az ágyban','sün a kertben','chill','none'),
(1897,'hu','Ezek a tökök a varjúéi.','Ezek a tökök a macskáéi.','három egymásra rakott tök','tökös pite','low_iq','guessing'),
(1899,'hu','Két óriás ül a romok mellett.','Két oroszlán ül a romok mellett.','régi templomok romjai','egy vár romjai','chill','none'),
(1905,'hu','Ezek a macskák nagyon kíváncsiak!','Ezek a kutyák nagyon kíváncsiak!','három kíváncsi macska','három álmos macska','dramatic','exclamation'),
(1906,'hu','A haja kék.','A haja vörös.','hosszú kék haj','kék nyári ruha','chill','none'),
(1908,'hu','Tesó, a gém chillel.','Tesó, a hattyú chillel.','gém egy ágon','gém a vízben','slang','none'),
(1909,'hu','Ragyog a pengéje.','Rozsdás a pengéje.','hosszú acélpenge','rövid, törött penge','chill','none'),
(1910,'hu','Annyi rózsaszín szirma van.','Annyi rózsaszín tolla van.','nagy rózsaszín szirmok','szirmok a padlón','slang','exaggeration'),
(1911,'hu','Ennek a hercegnőnek nagyon jó stílusa van.','Ennek a hercegnek nagyon jó stílusa van.','kék ruhás hercegnő','piros ruhás hercegnő','flirt','none'),
(1912,'hu','A tetoválásai kékek.','A tetoválásai pirosak.','kavargó kék arctetoválások','tetoválás a kezén','chill','none'),
(1914,'hu','A zongora nyitva van. Éhes?','Az ajtó nyitva van. Éhes?','nyitott hangversenyzongora','zongoraóra','low_iq','guessing'),
(1915,'hu','A nagybőgőnek négy húrja van.','A nagybőgőnek hat húrja van.','négyhúros nagybőgő','hathúros nagybőgő','nerd','none'),
(1916,'hu','UFO-k vannak az égen.','Madarak vannak az égen.','UFO-k az égen','leszálló UFO','chill','none'),
(1917,'hu','Sebességre tervezett sisak.','Kerékpározásra tervezett sisak.','sebességre épített sisak','sebesség biciklin','business','none'),
(1919,'hu','A sikátor nagyon keskeny.','A sikátor nagyon széles.','keskeny macskaköves sikátor','hajszál híján megúszni','chill','none'),
(1921,'hu','Egy döbbent arc a víz mellett.','Egy döbbent arc az erdőben.','döbbent, sikoltó arc','a telefonszámlától döbbent','chill','none'),
(1922,'hu','Ha tanul, megfájdul a feje.','Ha főz, megfájdul a feje.','hatalmas könyvből tanulni','a kertben tanulni','dramatic','guessing'),
(1923,'hu','A könyvespolcok roskadásig tele vannak!','A könyvespolcok teljesen üresek!','magas, könyvekkel teli könyvespolcok','üres könyvespolc','dramatic','exaggeration'),
(1924,'hu','Mennyi élénk szín!','Mennyi fakó szín!','élénk színörvények','élénk álom','gossip','exclamation'),
(1926,'hu','A koponyának megvan az összes foga!','A koponyának egy foga sincs!','egy koponya vigyorgó fogai','egy kutya éles fogai','dramatic','exclamation'),
(1927,'hu','Arany gyökerek? Nem egy olcsó fa.','Arany levelek? Nem egy olcsó fa.','arany gyökerek ékkövekkel','arany levelek ékkövekkel','ironic','cheap_quality'),
(1928,'hu','A belváros pirosan izzik. Nagyon menő.','A belváros zölden izzik. Nagyon menő.','neonfényes belvárosi utca','csendes belvárosi reggel','slang','none'),
(1930,'hu','A középkori város hangulatos.','A modern város hangulatos.','középkori kőváros','középkori vásárnap','chill','none'),
(1931,'hu','Esős városi utca.','Napos városi utca.','esős utca','esős tengerpart','chill','none'),
(1932,'hu','A számítógép egy piros asztalon van.','A számítógép egy piros kanapén van.','számítógép egy asztalon','számítógép az ölben','chill','none'),
(1933,'hu','Ő egy fa szelleme.','Ő egy tó szelleme.','egy öreg fa szelleme','az óceán szelleme','chill','none'),
(1934,'hu','Ezek a polcok szürreálisak.','Ezek a polcok hétköznapiak.','szürreális, hajló könyvespolcok','szürreális olvadó óra','nerd','none'),
(1935,'hu','Naplemente van New Yorkban.','Éjszaka van New Yorkban.','New York naplementekor','New York éjjel','chill','none'),
(1936,'hu','Óriási a virágkoszorúja!','Óriási a tollkoszorúja!','virágkoszorút viselni','virágkoszorút fonni','dramatic','exclamation'),
(1937,'hu','A hacker kapucnit visel.','A hacker baseballsapkát visel.','kapucnis hacker','hacker a parkban','chill','none'),
(1938,'hu','Egy magányos bálna a tengerpart közelében.','Egy magányos cápa a tengerpart közelében.','homokos tengerpart felülről','sziklás tengerpart szirtekkel','dramatic','none'),
(1940,'hu','Pitypangok veszik körül a fejét.','Rózsák veszik körül a fejét.','fehér pitypangbóbiták','pitypangot fújni','chill','none'),
(1941,'hu','Ez az egér kalóz, full Jack Sparrow.','Ez a macska kalóz, full Jack Sparrow.','kalózegér','kalózhajó','slang','exaggeration'),
(1943,'hu','A gnóm sapkája zöld. Hűha.','A gnóm sapkája piros. Hűha.','zöld ruhás gnóm','piros ruhás gnóm','low_iq','none'),
(1945,'hu','Micsoda kísérteties vár!','Micsoda kísérteties templom!','kísérteties vár a sziklákon','kísérteties vár a hóban','dramatic','exclamation'),
(1946,'hu','Ez a macska túl menő.','Ez a kutya túl menő.','menő macska napszemüvegben','hűsítő nyári ital','slang','exaggeration'),
(1947,'hu','Csak egy teljesen átlagos szivárványsörény.','Csak egy teljesen átlagos fekete sörény.','szivárványos sörény','szivárvány egy oroszlán fölött','ironic','understatement'),
(1948,'hu','A hullámos haja mindenhol ott van!','A rövid haja mindenhol ott van!','hullámos haj tele levelekkel','hullámos haj tele virágokkal','dramatic','exclamation'),
(1949,'hu','Ez az erdő annyira elvarázsolt.','Ez az erdő annyira leégett.','elvarázsolt erdei ösvény','elvarázsolt kastély','slang','none'),
(1950,'hu','Ennek a gonosz toronynak lift kéne.','Ennek a gonosz templomnak lift kéne.','gonosz erőd','gonosz mostoha','ironic','exaggeration'),
(1951,'hu','Egy fotel olvasóra vár.','Egy kanapé olvasóra vár.','kopott bőrfotel','új műanyag fotel','chill','guessing'),
(1952,'hu','Telihold egyetlen fa mögött.','Telihold két fa mögött.','telihold egy fa mögött','telihold a tenger fölött','chill','none'),
(1953,'hu','Hópehely-korona? Királynői vibe.','Virágkorona? Királynői vibe.','hópelyhekből álló korona','hópelyhek az ablakon','flirt','exaggeration'),
(1955,'hu','Úristen, ez egy mesebeli ház.','Úristen, ez egy mesebeli hajó.','mesebeli házikó','mesebeli kastély','gossip','none'),
(1957,'hu','A macskakövek nedvesek.','A macskakövek havasak.','nedves macskakövek éjjel','macskakövek a tengerparton','chill','none'),
(1958,'hu','Kőlépcső és rózsaszín virágok.','Kőlépcső és piros virágok.','kőlépcső egy faluban','kőlépcső egy várban','chill','none'),
(1959,'hu','A fonata a derekáig ér.','A fonata a térdéig ér.','derékig érő fonat','rövid fonat','chill','none'),
(1960,'hu','Úgy jár, mint egy igazi szamuráj.','Úgy táncol, mint egy igazi szamuráj.','szamuráj karddal','szamuráj íjjal','flirt','none'),
(1961,'hu','Ezek a csontok imádnak egy jó könyvet.','Ezek a csontok imádnak egy jó filmet.','csontok egy nyitott könyv fölött','kutya egy csonttal','gossip','guessing'),
(1962,'hu','Ez az erőd ijesztő!','Ez a házikó ijesztő!','sötét erőd a dombtetőn','erőd a sivatagban','dramatic','exclamation'),
(1964,'hu','Ez a ház tuti kísértetjárta.','Ez a suli tuti kísértetjárta.','kísértetjárta régi ház','kísértetjárta régi hajó','gossip','guessing'),
(1965,'hu','Hangulatos faház. Egy kis hó.','Hangulatos faház. Egy kis homok.','havas faház','kabin egy hajón','ironic','understatement'),
(1966,'hu','Az ösvény kövekből van.','Az ösvény fából van.','macskaköves ösvény','erdei ösvény','chill','none'),
(1967,'hu','A rókakölyök nagyon aranyos!','A medvebocs nagyon aranyos!','aranyos rókakölyök','aranyos madárfióka','dramatic','exclamation'),
(1968,'hu','Szerintem azok hollók.','Szerintem azok papagájok.','körülötte repkedő hollók','hollók a karján','low_iq','guessing'),
(1969,'hu','Virágcsokor az űrből? Romantikus!','Virágcsokor a tengerből? Romantikus!','virágcsokrot szedni','virágcsokrot dobni','flirt','exclamation'),
(1970,'hu','A kunyhónak egy deszkaajtaja van. Alap, de stabil.','A kunyhónak egy üvegajtaja van. Alap, de stabil.','apró havas kunyhó','apró tengerparti kunyhó','business','cheap_quality'),
(1971,'hu','Csúcsok a felhők felett. Durva.','Csúcsok a felhők alatt. Durva.','havas csúcsok a felhők felett','erdővel borított csúcsok','slang','none'),
(1972,'hu','Az a turbán egy egész torony!','Az a korona egy egész torony!','magas, ékköves turbán','turbán a sivatagban','dramatic','exaggeration'),
(1973,'hu','Ez az istennő egyiptominak tűnik.','Ez az istennő japánnak tűnik.','istennő arany szárnyakkal','istennő íjjal','nerd','none'),
(1974,'hu','A balerina a lábujjhegyén áll.','A balerina a térdén áll.','balerina tütüben','balerinacipő','chill','none'),
(1976,'hu','Négy gyerek korcsolyázik, a mókusok meg pontoznak.','Négy gyerek korcsolyázik, a kutyák meg pontoznak.','befagyott tavon korcsolyázni','rámpán korcsolyázni','ironic','guessing'),
(1977,'hu','A denevérektől még hátborzongatóbb!','A baglyoktól még hátborzongatóbb!','hátborzongató romos ház','hátborzongató régi baba','dramatic','exclamation'),
(1979,'hu','Lilára festette. Merész!','Zöldre festette. Merész!','élénklilára festett haj','élénkzöldre festett haj','gossip','exclamation'),
(1980,'hu','Örökzöld fenyők veszik körül a kunyhót.','Örökzöld pálmák veszik körül a kunyhót.','havas fenyők','fenyőasztal','nerd','none'),
(1981,'hu','A hullámok a világítótoronynak csapódnak!','A hullámok a kikötőnek csapódnak!','sziklákra csapódó hullámok','egy haver kanapéján aludni','dramatic','exclamation'),
(1982,'hu','A szoba „kicsit” zsúfolt.','A szoba „kicsit” üres.','zsúfolt polcok','zsúfolt íróasztal','ironic','understatement'),
(1983,'hu','Nagyon hosszúak a szempillái.','Nagyon rövidek a szempillái.','hosszú sötét szempillák','műszempilla egy dobozban','chill','none'),
(1984,'hu','Nagyon sápadt az arca.','Nagyon sötét az arca.','sápadt fehér arc','halványkék ég','chill','none'),
(1985,'hu','A fa élénkpiros!','A fa élénkzöld!','élénkpiros levelek','élénkpiros almák','dramatic','exclamation'),
(1986,'hu','A fa csupasz. Olyan szomorú.','A fa zöld. Olyan szomorú.','csupasz fa éjjel','mezítláb a fűben','low_iq','none'),
(1987,'hu','Ez a város a jövőből jött.','Ez a város a múltból jött.','a jövő városa','a múlt városa','business','none'),
(1988,'hu','A kerítésnek éles tüskéi vannak.','A kerítésnek nincs kapuja.','tüskés vaskerítés','kerti fakerítés','chill','none'),
(1989,'hu','Régi bájitalok töltik meg a polcokat.','Régi cipők töltik meg a polcokat.','régi bájitalok a polcokon','bájital egy üstben','chill','none'),
(1990,'hu','Egy szuper kényelmes fotel.','Egy szuper kényelmes kanapé.','kényelmes arany fotel','kényelmes arany ágy','slang','none'),
(1991,'hu','Úgy gépel, mint egy gép!','Úgy fest, mint egy gép!','billentyűzeten gépelni','telefonon gépelni','slang','exclamation'),
(1992,'hu','Nagy zöld fejhallgatóban hallgat zenét.','Nagy piros fejhallgatóban hallgat zenét.','zenét hallgatni','egy tanárt hallgatni','chill','none'),
(1994,'hu','Egy macska ül a könyvek tetején.','Egy macska ül a sövény tetején.','a könyvek tetején','az autó tetején','chill','none'),
(1995,'hu','Ez az ajtónyílás egy másik világba vezet.','Ez az ajtónyílás egy sötét pincébe vezet.','világító íves ajtónyílás','ajtónyílás a konyhába','dramatic','guessing'),
(1997,'hu','Az a harci fejsze óriási!','Az a harci pajzs óriási!','harci fejszét tartva','harci zászlót tartva','dramatic','exclamation'),
(1998,'hu','Ebben a kastélyban gazdagok laknak.','Ebben a házikóban gazdagok laknak.','kastély alkonyatkor','kastély a tengerparton','gossip','guessing'),
(1999,'hu','Tesó, ez a bunda nagyon vastag.','Tesó, ez a bunda nagyon fekete.','vastag fehér bunda','fehér szőrmekabát','slang','none'),
(2000,'hu','Holdfény ragyog a vízen.','Napfény ragyog a vízen.','holdfény egy mocsáron','holdfény egy hálószobában','chill','none'),
(2001,'hu','A baglynak arany csőre van. Gazdag bagoly!','A baglynak piros csőre van. Gazdag bagoly!','bagoly arany csőre','bagoly törött csőre','low_iq','exaggeration'),
(2002,'hu','A macskának hosszú a bajusza.','A macskának rövid a bajusza.','hosszú bajuszú macska','hosszú bajuszú férfi','chill','none'),
(2005,'hu','A varjú hírekre vár.','A bagoly hírekre vár.','varjú egy ágon','varjú egy madárijesztőn','dramatic','guessing'),
(2008,'hu','A törzs hatalmas és csavarodott.','A törzs vékony és sima.','hatalmas, csavarodott fatörzs','elefántormány','chill','none'),
(2010,'hu','A történet életre kel!','A történet lángokban áll!','életre kelő történet','történet egy városról','dramatic','exclamation'),
(2011,'hu','Teljesen nyitott az ajtó.','Teljesen zárt az ajtó.','nyitott üvegajtó','nyitott laptop','chill','none'),
(2012,'hu','Virágok borítják a bejáratot.','Hó borítja a bejáratot.','virágos kerti bejárat','virágos szállodai bejárat','chill','none'),
(2013,'hu','A sminkje? Totál gótikus.','A sminkje? Totál rózsaszín.','gótikus stílus','gótikus templom','gossip','none'),
(2014,'hu','Egyedül a szürkületben. Olyan titokzatos.','Egyedül délben. Olyan titokzatos.','régi sikátor szürkületkor','szürkület egy üres tengerparton','dramatic','cliche'),
(2015,'hu','Tény: az emlékmű kőből van.','Tény: az emlékmű fából van.','régi kő emlékmű','emlékmű egy téren','nerd','none'),
(2016,'hu','Harry Potternek kell ez a varázspálca, tesó.','Harry Potternek kell ez a seprű, tesó.','világító varázspálca','törött varázspálca','slang','guessing'),
(2019,'hu','A mozdony gőzzel megy.','A mozdony dízellel megy.','régi gőzmozdony','régi dízelmozdony','nerd','none'),
(2021,'hu','Csillagképek töltik be az eget.','Szivárványok töltik be az eget.','csillagképek a ház fölött','csillagképek egy térképen','nerd','none'),
(2023,'hu','Ajándékokat hagytak a hóban!','Síléceket hagytak a hóban!','ajándékdobozok a hóban','ajándékdobozok az ágy alatt','dramatic','exclamation'),
(2024,'hu','Mindenhol neonfeliratok!','Mindenhol papírfeliratok!','rózsaszín és zöld neonfeliratok','neonzöld dzseki','slang','exclamation'),
(2025,'hu','Futurisztikus város, 3000-es év?','Futurisztikus falu, 3000-es év?','futurisztikus tornyok éjjel','futurisztikus repülő autó','nerd','guessing'),
(2026,'hu','Micsoda álomszép dolgozószoba!','Micsoda álomszép konyha!','virágokkal teli dolgozószoba','diákokkal teli dolgozószoba','slang','exclamation'),
(2028,'hu','Egy fehér kancsó van a könyvek között.','Egy fehér macska van a könyvek között.','kancsó egy könyvespolcon','kancsó egy asztalon','chill','none'),
(2029,'hu','Az ösvény eltűnik a ködben.','Az ösvény eltűnik a tengerben.','köves hegyi ösvény','lábnyomok sora','dramatic','none'),
(2031,'hu','Gallyak vannak a hajában. Fura.','Virágok vannak a hajában. Fura.','gallyak a hajában','gallyakból rakott fészek','low_iq','none'),
(2032,'hu','Portál egy arany városba.','Portál egy sötét erdőbe.','világító kerek portál','portál a tenger alatt','chill','none'),
(2033,'hu','A gitár egy örvényben van!','A gitár egy sivatagban van!','gitár egy örvényben','csónak egy örvényben','dramatic','exclamation'),
(2034,'hu','Ez a pipacs piros. Nagyon piros.','Ez a pipacs kék. Nagyon kék.','piros pipacsvirág','pipacsmező','low_iq','none'),
(2035,'hu','Ennek a románcnak rózsaszín szíve van.','Ennek a románcnak piros szíve van.','tavaszi románc','romantikus regény','flirt','none'),
(2036,'hu','Lándzsából láthatóan nincs hiány.','Kardból láthatóan nincs hiány.','lándzsákat emelő sereg','lándzsákat hajító sereg','business','understatement'),
(2037,'hu','Egy lény sötét szárnyakkal.','Egy lény hosszú szarvakkal.','sötét szárnyú lény','lény a tengerben','chill','none'),
(2038,'hu','Ijedt, és ezt a madarak is tudják.','Ijedt, és ezt a farkasok is tudják.','ijedten a sötét erdőben','egy nagy kutyától megijedve','dramatic','guessing'),
(2040,'hu','Minden tetőn díszek vannak.','Minden tetőn hóemberek vannak.','díszek a tetőkön','díszek egy dobozban','chill','none'),
(2041,'hu','Egy egész naplemente lakik ebben a palackban.','Egy egész óceán lakik ebben a palackban.','sötét üvegpalack','egy palack vörösbor','dramatic','exaggeration'),
(2042,'hu','Az a hold hatalmas!','Az a nap hatalmas!','hatalmas telihold','hatalmas régi vár','dramatic','exclamation'),
(2045,'hu','Ezek a kövek szuper magasak.','Ezek a fák szuper magasak.','magas álló kövek','magas fák egy mezőn','slang','exaggeration'),
(2046,'hu','Havas éjszaka az erdőben. Olyan csend van...','Havas éjszaka a városban. Olyan csend van...','havas erdő éjjel','havas utca éjjel','dramatic','none'),
(2048,'hu','Ez a farkas vad!','Ez a kutya vad!','vad farkas','vad buli','dramatic','exclamation'),
(2049,'hu','Az olvasósarok hangulatos.','A konyhasarok hangulatos.','hangulatos olvasósarok','kényelmes gyapjúpulcsi','chill','none'),
(2052,'hu','A bögre egy halom könyvön áll.','A bögre egy halom dobozon áll.','ezüst bögre könyveken','egy bögre hideg tej','chill','none'),
(2053,'hu','Minden polcot palackok töltenek meg.','Minden polcot könyvek töltenek meg.','polcok régi palackokkal','polcok régi könyvekkel','chill','none'),
(2055,'hu','A „Fiatalító” valójában méreg.','A „Fiatalító” valójában gyümölcslé.','egy üveg méreg','egy üveg bor','ironic','none'),
(2056,'hu','A polcok tele vannak könyvekkel.','A polcok tele vannak befőttesüvegekkel.','polcok tele régi könyvekkel','polcok tele régi játékokkal','chill','none'),
(2057,'hu','A kémény kőből van.','A kémény fémből van.','kőből rakott kémény a hóban','kéményt pucolni','chill','none'),
(2058,'hu','Egy medve próbál elérni egy csillagot.','Egy medve próbál elérni egy madarat.','elérni egy csillagot','elérni a mézet','chill','none'),
(2059,'hu','A napfény csak az egyik oldalt éri.','A holdfény csak az egyik oldalt éri.','ágak erős napfényben','napfény a vízen','nerd','none'),
(2060,'hu','Piros-sárga síléc, de menő.','Kék-fehér síléc, de menő.','hóban álló sílécek','sílécek egy autó tetején','slang','none'),
(2061,'hu','A galaxis nagyon felvág.','A hold nagyon felvág.','világító lila galaxis','galaxis egy pólón','slang','exaggeration'),
(2062,'hu','Valaki egymásra egyensúlyozta ezeket a köveket.','Valaki egymásra egyensúlyozta ezeket a csészéket.','toronnyá egyensúlyozott kövek','egy lábon egyensúlyozni','gossip','guessing'),
(2064,'hu','A hógömbben egy templom van.','A hógömbben egy vár van.','világító hógömb','törött hógömb','chill','none'),
(2067,'hu','Egy utcai lámpa, rengeteg hó.','Egy utcai lámpa, rengeteg eső.','világító utcai lámpa','kutya egy utcai lámpánál','chill','understatement'),
(2068,'hu','A piros ajtó nyitva van.','A kék ajtó nyitva van.','nyitott piros ajtó','piros garázsajtó','chill','none'),
(2069,'hu','A rénszarvasnak pocsék repülése volt.','A rénszarvasnak szuper repülése volt.','szélturbinán ragadt rénszarvas','szánt húzó rénszarvas','chill','understatement'),
(2070,'hu','Az elektromos gitár egy rakéta!','Az elektromos gitár süllyed!','felszálló elektromos gitár','elektromos gitár a színpadon','slang','exaggeration'),
(2071,'hu','Szép vintage autó, nagyon ünnepi.','Szép vintage furgon, nagyon ünnepi.','piros vintage autó','piros vintage ruha','flirt','none'),
(2072,'hu','Kábelek borítják az egész szobát!','Növények borítják az egész szobát!','világító kék kábelek','kábelek egy hídon','dramatic','exaggeration'),
(2073,'hu','Nézd, a nap ragyog be!','Nézd, a hold ragyog be!','beragyogó napfény','beragyogó holdfény','dramatic','exclamation'),
(2075,'hu','Könyvek vannak az ablakpárkányon.','Macskák vannak az ablakpárkányon.','könyvek egy ablakpárkányon','növények egy ablakpárkányon','chill','none'),
(2076,'hu','Ennyi irodalom, ilyen kevés idő.','Ennyi pizza, ilyen kevés idő.','polcnyi régi irodalom','irodalom telefonon','nerd','cliche'),
(2077,'hu','A bagoly engem bámul!','A macska engem bámul!','a nézőt bámulva','a holdat bámulva','dramatic','exclamation'),
(2078,'hu','Két láng világítja meg a könyvet.','Három láng világítja meg a könyvet.','két gyertyaláng','lángok a kandallóban','chill','none'),
(2079,'hu','Itt minden fából van.','Itt minden műanyagból van.','magas fa könyvszekrények','magas fa létrák','low_iq','exaggeration'),
(2080,'hu','Hó hull a pagodára.','Eső hull a pagodára.','piros pagoda a hóban','pagoda a dzsungelben','chill','none'),
(2081,'hu','Átkelőkövek vezetnek át egy tavon.','Átkelőkövek vezetnek át egy úton.','átkelőkövek a vízen át','átkelőkövek egy kertben','chill','none'),
(2082,'hu','Vékony sétabotot tart.','Vékony pipát tart.','sétabotot tartva','sétabot a hóban','chill','none'),
(2084,'hu','Vonat egy esőáztatta vasúti pályán.','Vonat egy száraz vasúti pályán.','vasút éjjel','vasút a sivatagban','chill','none'),
(2086,'hu','Az utca olyan ünnepi!','Az utca olyan napos!','ünnepi havas utca','ünnepi vacsoraasztal','slang','exclamation'),
(2087,'hu','Ködös steampunk városi látkép.','Ködös sivatagi városi látkép.','városi látkép a ködben','városi látkép éjfélkor','chill','none'),
(2088,'hu','A jóképű férfinak szakálla van.','A jóképű férfinak szemüvege van.','jóképű szakállas férfi','jóképű férfi szemüvegben','flirt','none'),
(2089,'hu','Haver, ez az agancs óriási.','Haver, ez az agancs apró.','hatalmas elágazó agancs','agancs a falon','slang','none'),
(2091,'hu','A fenyőfa egyedül áll.','A pálmafa egyedül áll.','zúzmarás fenyőfa','fenyőfa égősorral','dramatic','none'),
(2092,'hu','Micsoda bolyhos bagoly!','Micsoda bolyhos macska!','bolyhos kék bagoly','bolyhos kék takaró','dramatic','exclamation'),
(2093,'hu','Az egész város zöld.','Az egész város szürke.','fákkal teli zöld tornyok','zöld festék a tornyokon','business','none'),
(2095,'hu','A hosszú haja kékeszöld.','A hosszú haja fekete.','hosszú, lobogó kékeszöld haj','hosszú séta','chill','none'),
(2096,'hu','Még az ég is piros!','Még az ég is zöld!','piros sivatagi ég','piros sportautó','dramatic','exclamation'),
(2097,'hu','Azok a fülek nagyobbak, mint a feje!','Azok a szemek nagyobbak, mint a feje!','hatalmas kerek fülek','fülek egy sapka alatt','dramatic','exclamation'),
(2099,'hu','Ez a lombház nagyon menő!','Ez a kutyaház nagyon menő!','dzsungelbeli lombház','kerti lombház','slang','exclamation'),
(2100,'hu','A báli ruhája nagyobb, mint a kert!','A kalapja nagyobb, mint a kert!','hatalmas kék báli ruha','báli ruha egy vállfán','dramatic','exaggeration'),
(2101,'hu','Együtt sétálnak.','Együtt futnak.','szorosan együtt sétálni','együtt ülni egy kávézóban','chill','none'),
(2102,'hu','Micsoda könyvgyűjtemény!','Micsoda cipőgyűjtemény!','régi könyvek gyűjteménye','régi érmék gyűjteménye','dramatic','exclamation'),
(2104,'hu','Mennyi arany ékszer!','Mennyi ezüst ékszer!','arany ékszerekkel borítva','arany ékszereket árulni','gossip','exclamation'),
(2105,'hu','A könyvhalmok bármikor ledőlhetnek.','A csészehalmok bármikor ledőlhetnek.','dőlő könyvhalmok','egy halom ruha','chill','guessing'),
(2107,'hu','Hol van mindenki ezen az űrhajón?','Hol van mindenki ezen a vonaton?','egy űrhajó belsejében','leszálló űrhajó','low_iq','guessing'),
(2108,'hu','Csövek futnak a mennyezeten.','Vezetékek futnak a mennyezeten.','csövek a mennyezeten','csövek a padló alatt','chill','none'),
(2109,'hu','A könyvek rendezett sorokban állnak.','A csészék rendezett sorokban állnak.','rendezett könyvsorok','rendezett íróasztal','chill','none'),
(2110,'hu','Sötét sziluett, neonváros. Batman?','Sötét sziluett, napos tengerpart. Batman?','kabátos sziluett','macska sziluettje','slang','guessing'),
(2112,'hu','A blézere élénksárga.','A blézere sötétzöld.','élénksárga blézer','blézert levenni','chill','none'),
(2113,'hu','A virágok élénksárgák.','A virágok élénklilák.','galamb sárga virágokon','sárga virágok egy vázában','chill','none'),
(2114,'hu','Híd ível át a patakon.','Híd ível át az úton.','patakon átívelő híd','ház az utca túloldalán','chill','none'),
(2115,'hu','Nyugodt jógapóz.','Nyugodt táncpóz.','törökülésben végzett jógapóz','jóga egy SUP-deszkán','chill','none'),
(2116,'hu','Hínár lebeg körülötte.','Műanyag lebeg körülötte.','hínár a feje körül','hínár egy szusitekercsen','chill','none'),
(2117,'hu','Telefon nincs, csak egy zsebóra.','Telefon nincs, csak egy karóra.','arany zsebóra','zsebórára pillantani','ironic','understatement'),
(2118,'hu','Micsoda elegáns, aranyozott boltok!','Micsoda elegáns, ezüstözött boltok!','elegáns aranyozott kirakatok','jelmezbál','dramatic','exclamation'),
(2119,'hu','A baglyon piros minták vannak.','A baglyon zöld minták vannak.','tollminták','minták egy ruhán','chill','none'),
(2120,'hu','Egy madár egy vékony ágon ül.','Egy madár egy vezetéken ül.','virágzó ágon ül','ablakpárkányon ül','chill','none'),
(2121,'hu','Nehéz sziklák, tökéletes egyensúly.','Nehéz téglák, tökéletes egyensúly.','nehéz sziklákból álló torony','nehéz zsák kövekkel','business','none'),
(2123,'hu','Ez a gyár az eget súrolja.','Ez a gyár a tengert súrolja.','óriási steampunk gyár','apró steampunk gyár','dramatic','exaggeration'),
(2124,'hu','Egy nedves úton sétál.','Egy nedves tengerparton sétál.','vidéki úton sétálva','vidéki úton autózva','chill','none'),
(2126,'hu','A cica kiöntötte a kávét!','A cica kiöntötte a tejet!','kiöntött kávé az asztalon','festéket kiönteni a padlóra','low_iq','blaming_someone'),
(2127,'hu','Egy könyv van az asztalon.','Egy macska van az asztalon.','faragott faasztal','asztal a kandalló mellett','chill','none'),
(2128,'hu','Harci szekérről lő!','Csónakból lő!','nyilat lőni','fotót lőni','dramatic','exclamation'),
(2132,'hu','A könyvtár elhagyatott.','Az iskola elhagyatott.','elhagyatott könyvtár','elhagyatott autó','chill','none'),
(2133,'hu','Kőoszlopok a hóban.','Kőoszlopok a homokban.','egymásra rakott kövekből álló oszlopok','egy templom oszlopa','chill','none'),
(2134,'hu','A császárnőt ez egyáltalán nem mulattatja.','A császárnőt ez nagyon mulattatja.','szigorú császárnő','császárnő lóháton','ironic','understatement'),
(2135,'hu','Ez a macska örvényekből áll.','Ez a macska négyzetekből áll.','arany örvények','füstörvények','chill','none'),
(2136,'hu','A piros kesztyű nagyon jól áll.','A kék kesztyű nagyon jól áll.','piros űrkesztyű','piros bokszkesztyű','flirt','none'),
(2137,'hu','Arany glória? Nagyon stílusos.','Ezüst glória? Nagyon stílusos.','arany glóriakorona','sötét füstglória','flirt','none'),
(2139,'hu','Lézersugarak világítanak mögötte.','Gyertyák világítanak mögötte.','neon lézersugarak','lézermutató macskáknak','chill','none'),
(2140,'hu','Ez a hely egy nagy gép.','Ez a hely egy nagy kert.','hatalmas rozsdás gép','hatalmas mosógép','chill','none'),
(2141,'hu','Valami világít a pincében.','Valami ég a pincében.','nyitott pinceajtó','dobozokkal teli pince','gossip','none'),
(2143,'hu','Sziklatömbök egymásra rakva, mint a Lego.','Téglák egymásra rakva, mint a Lego.','sziklatömbökből álló torony','lefelé guruló sziklatömb','low_iq','exaggeration'),
(2144,'hu','Fehér póló van rajta.','Fekete póló van rajta.','fehér póló és dzseki','póló egy vállfán','chill','none'),
(2146,'hu','Franciaországban van egy lila torony.','Franciaországban van egy zöld torony.','torony Franciaországban','híd Franciaországban','low_iq','guessing'),
(2149,'hu','Gerincek egymás után, mind szürke.','Gerincek egymás után, mind zöld.','hegygerincek sorai','hóval borított gerinc','chill','none'),
(2150,'hu','Lófarok megvan. Ki fog menni.','Haja kiengedve. Ki fog menni.','lófarok az ablaknál','lófarok egy lovon','chill','guessing'),
(2151,'hu','A holdsarló chillel.','A telihold chillel.','holdsarló a felhők között','holdsarló délben','slang','none'),
(2152,'hu','A rúzsa élénkpiros.','A rúzsa élénk rózsaszín.','élénkpiros rúzs','élénk rózsaszín rúzs','chill','none'),
(2153,'hu','Kínának repülő sárkánya van!','Kínának alvó sárkánya van!','sárkány Kínából','tigris Kínából','dramatic','exclamation'),
(2154,'hu','A tábornok szakálla fehér.','A tábornok szakálla fekete.','öreg tábornok páncélban','fiatal tábornok páncélban','chill','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
