begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(2155,'hu','Ez a magabiztos mosoly működik.','Ez az ideges mosoly működik.','magabiztos félmosoly','magabiztos hangos nevetés','flirt','none'),
(2156,'hu','A nap a horizonton ül.','A hold a horizonton ül.','a nap a horizonton','hajó a horizonton','chill','none'),
(2157,'hu','Egy Indiából származó baba aranyat visel.','Egy Indiából származó baba pirosat visel.','festmény Indiából','szőnyeg Indiából','chill','none'),
(2158,'hu','Imádom a narancssárga fejkendőt!','Imádom a kék fejkendőt!','narancssárga fejkendő','fejkendő levétele','flirt','exclamation'),
(2159,'hu','A macska nagyon fenségesnek érzi magát.','A kutya nagyon fenségesnek érzi magát.','fenséges macska','fenséges oroszlán','ironic','guessing'),
(2161,'hu','A zseninek új ötlete van.','A zseninek új macskája van.','csillagokat bámuló zseni','képleteket író zseni','nerd','guessing'),
(2162,'hu','Tökéletes a vörös haja.','Tökéletes a fekete haja.','hosszú, hullámos vörös haj','kontyba fogott vörös haj','flirt','none'),
(2164,'hu','Egy ösvény vezet az erdőbe. Ki megy elsőként?','Egy folyó vezet az erdőbe. Ki megy elsőként?','ösvény az erdőn át','kunyhó az erdőben','dramatic','guessing'),
(2172,'hu','Sportautó egy festékviharban.','Sportautó egy hóviharban.','sötétkék sportautó','sötétkék családi autó','dramatic','exaggeration'),
(2174,'hu','Egy fa virágzik a hóban!','Egy fa ég a hóban!','éjjel virágzó fa','tavasszal virágzó virágok','dramatic','exclamation'),
(2175,'hu','Éjfél a fenyőerdőben.','Éjfél a sivatagban.','éjfél a csillagok alatt','buli éjfélkor','chill','none'),
(2176,'hu','Esik az eső a sorok közti folyosón!','Esik a hó a sorok közti folyosón!','esős könyvtári folyosó','zsúfolt szupermarketfolyosó','dramatic','exclamation'),
(2178,'hu','Pszt, két macska kukucskál.','Pszt, két kutya kukucskál.','kukucskálás a levelek mögül','kukucskálás az ablakon át','gossip','none'),
(2181,'hu','Az utca durván zsúfolt.','Az utca durván üres.','zsúfolt neonfényes utca','zsúfolt vasúti kocsi','slang','none'),
(2182,'hu','A túrázónak piros hátizsákja van.','A túrázónak kék hátizsákja van.','túrázó egy sziklapárkányon','túrázó egy sátorban','chill','none'),
(2184,'hu','A tigris üvölt!','Az oroszlán üvölt!','üvöltő tigris','alvó tigris','dramatic','exclamation'),
(2185,'hu','A zongoristának szőke haja van.','A zongoristának fekete haja van.','zongorista a zongoránál','zongorista a szintetizátornál','chill','none'),
(2186,'hu','Jézus töviskoronát visel.','Jézus aranykoronát visel.','töviskorona','tövises rózsa','chill','none'),
(2187,'hu','Buddha meditál.','Buddha táncol.','meditáló Buddha','fekvő Buddha','chill','none'),
(2188,'hu','A fiú sír, anya nem.','A fiú énekel, anya nem.','sírás a biciklin','sírás az ágyban','ironic','none'),
(2189,'hu','Valaki a vízbe esik a hajóról!','Valaki fejest ugrik a hajóról!','hanyatt esés a hajóról a vízbe','elalvás a csónakban','dramatic','exclamation'),
(2190,'hu','Ennek a gonosztevőnek lángoló szeme van.','Ennek a gonosztevőnek kék szeme van.','gonosztevő égő romok között','gonosztevő egy kastélyban','dramatic','none'),
(2191,'hu','Az androidnak emberi arca van.','Az androidnak hosszú szakálla van.','világító női android','android a konyhában','nerd','none'),
(2192,'hu','Harry Potter imádná ezeket a lombikokat.','Harry Potter imádná ezeket a seprűket.','világító üveglombikok','termosz','nerd','guessing'),
(2194,'hu','A trópusi levelek nagyok. Hű.','A trópusi levelek aprók. Hű.','sűrű trópusi levelek','trópusi strand','low_iq','none'),
(2195,'hu','Csöpög az akvarell.','Csöpög az olajfesték.','akvarell portré','akvarell tájkép','chill','none'),
(2199,'hu','Finom rózsák mindenhol!','Finom tulipánok mindenhol!','finom rózsaszín rózsák','finom üvegváza','dramatic','exaggeration'),
(2200,'hu','Elegáns az estélyijében.','Elegáns a kabátjában.','elegáns, omló estélyi','elegáns fekete öltöny','flirt','none'),
(2201,'hu','Szuper a narancssárga páncélja!','Szuper a rózsaszín páncélja!','narancssárga haj és páncél','narancs a kezében','flirt','exclamation'),
(2202,'hu','Elegáns a fehér zakója.','Elegáns a piros zakója.','elegáns fehér zakó','elegáns sötét öltöny','chill','none'),
(2204,'hu','Egy bárányt tart a kezében.','Egy kutyát tart a kezében.','bárány a karjában','bárány a mezőn','chill','none'),
(2207,'hu','A robotkéz mutat valamire.','A robotkéz integet valakinek.','a képernyőre mutat','az égre mutat','chill','none'),
(2208,'hu','A haja élénk rózsaszín.','A haja élénkzöld.','élénk rózsaszín haj','élénk rózsaszín ruha','business','none'),
(2211,'hu','Kitalálod, kinél van háromágú szigony? A tenger istenénél.','Kitalálod, kinél van kalapács? A tenger istenénél.','isten háromágú szigonnyal','háromágú szigony a homokban','gossip','guessing'),
(2212,'hu','Szép csíkok, tigris!','Szép pöttyök, tigris!','tigris fekete csíkokkal','zebra fekete csíkokkal','slang','exclamation'),
(2213,'hu','Tény: a kosoknak csavart szarvuk van.','Tény: a kosoknak lapos szarvuk van.','csavart szarvú kos','füvet legelő kos','nerd','cliche'),
(2214,'hu','Rajta keresztül egy kastélyt látok.','Rajta keresztül egy templomot látok.','kilátás egy sziklalyukon keresztül','kilátás egy ablakon keresztül','chill','none'),
(2216,'hu','Egy oltárnál imádkozik.','Egy oltárnál énekel.','imádkozás gyertyás oltárnál','esküvő az oltárnál','chill','none'),
(2217,'hu','Varázslatot szór. Menő.','Hálót vet. Menő.','varázslatot szór','varázskönyvet olvas','slang','none'),
(2218,'hu','Áramkörök vannak körülötte.','Virágok vannak körülötte.','világító áramköri vonalak','autóversenypálya','nerd','none'),
(2224,'hu','Kézen fogva mennek.','Kezet fognak.','kézen fogva az esőben','kézen fogva a napsütésben','flirt','none'),
(2225,'hu','Szegény lány bőrig ázott, a haja csurom víz.','Szegény lány, a haja teljesen száraz.','bőrig ázva a zuhogó esőben','ázás forró vízben','gossip','none'),
(2226,'hu','Arany karkötői vannak.','Arany kesztyűi vannak.','arany karkötők a csuklóján','karkötő egy boltban','chill','none'),
(2227,'hu','Hátrapillant. Rád?','Lepillant. Rád?','hátrapillant a válla fölött','a telefonjára pillant','gossip','guessing'),
(2228,'hu','A város fölött ül.','A tenger fölött ül.','magasan a város fölött','a felhők fölött','chill','none'),
(2231,'hu','Óriási arany szfinx.','Óriási ezüst szfinx.','arany szfinxszobor','alvó szfinx macska','chill','none'),
(2232,'hu','Buddha békésnek tűnik.','Buddha dühösnek tűnik.','békés arany Buddha','békés arany templom','chill','none'),
(2233,'hu','Két baseballkesztyű van nála.','Két baseballütő van nála.','baseballkesztyű mindkét kézben','baseball a tévében','chill','none'),
(2234,'hu','A harcosnak nagy izmai vannak.','A harcosnak nagy pajzsa van.','a harcos nagy izmai','a harcos nagy pajzsa','chill','none'),
(2235,'hu','Teljes profilból látjuk.','Hátulról látjuk.','férfi teljes profilból','profilkép online','nerd','none'),
(2236,'hu','Palota egy óriási hold alatt. Hű!','Palota egy óriási nap alatt. Hű!','palota a hegyekben','palota a sivatagban','dramatic','exclamation'),
(2237,'hu','Nézd ezt a fényes sárga autót!','Nézd ezt a fényes piros autót!','fényes sárga autó','fényes sárga busz','slang','exclamation'),
(2238,'hu','A mecsetnek sok kupolája van.','A mecsetnek egy kupolája van.','kupolás nagymecset','mecset a sivatagban','chill','none'),
(2242,'hu','A madárrajban nulla szabad hely van.','A madárrajban rengeteg szabad hely van.','apró madarak raja','birkanyáj','business','exaggeration'),
(2245,'hu','Csak egy kicsit benőtt.','Csak egy kicsit havas.','benőtt házikó','benőtt gyep','ironic','understatement'),
(2246,'hu','A kiállításon egy miniatűr házikó látható.','A kiállításon egy miniatűr kastély látható.','miniatűr éjszakai kert','miniatűr vasútmodell','business','none'),
(2247,'hu','Skóciában van egy magányos templom.','Skóciában van egy magányos kastély.','templom Skóciában','kastély Skóciában','chill','none'),
(2248,'hu','Kecsesen lebeg.','Kecsesen táncol.','kecses lebegés a levegőben','kecses tánc a színpadon','chill','none'),
(2249,'hu','Fogaskerekekből épült steampunk város.','Üvegből épült steampunk város.','réz steampunk tornyok','steampunk jelmezbuli','chill','none'),
(2250,'hu','A várost bámulja.','A tengert bámulja.','esős várost bámul','csillagos eget bámul','dramatic','none'),
(2251,'hu','A mennyei dress code: fehér köntös.','A mennyei dress code: fekete köntös.','hosszú fehér köntös','kapucnis köntös','business','cliche'),
(2254,'hu','Fagyott palota. Szia, Elza!','Fagyott tó. Szia, Elza!','fagyott, havas palota','fagyott borsó zacskóban','slang','exclamation'),
(2256,'hu','A lábai teljesen mechanikusak.','A lábai teljesen fából vannak.','mechanikus karok és lábak','mechanikus karóra','nerd','none'),
(2257,'hu','A szemöldöke nagyon sötét.','A szemöldöke nagyon világos.','sűrű, sötét szemöldök','vékony, szőke szemöldök','chill','none'),
(2258,'hu','A templomnak magas toronysisakja van.','A templomnak kerek kupolája van.','magas templomi toronysisak','toronysisak egy váron','chill','none'),
(2259,'hu','Vigyél el ehhez a lagúnához most!','Vigyél el ehhez a gleccserhez most!','türkiz lagúna pálmákkal','befagyott lagúna télen','dramatic','exclamation'),
(2260,'hu','Szegény evezős csónak, senki sem akarja.','Szegény hajó, senki sem akarja.','üres fa evezős csónak','emberekkel teli evezős csónak','dramatic','exaggeration'),
(2268,'hu','Kifeszített kötélen áll. Háló nélkül!','Létrán áll. Háló nélkül!','egyensúlyozás kifeszített kötélen','cirkuszi kötéltánc-szám','dramatic','exclamation'),
(2269,'hu','A blúza bő és fehér.','A ruhája bő és fehér.','bő fehér blúz','szűk fekete blúz','chill','none'),
(2271,'hu','Egy folyosón chillel.','Egy konyhában chillel.','űrhajófolyosó','kórházi folyosó','slang','none'),
(2273,'hu','Szakadt farmer, full farmeres szett.','Szakadt farmer, full fekete szett.','erősen szaggatott kék farmer','kék farmer vasalása','slang','none'),
(2274,'hu','Az a csipkegallér nagyon puccos!','Az a szőrmegallér nagyon puccos!','díszes csipkegallér','cipőfűző megkötése','gossip','none'),
(2275,'hu','Jó szett, nagy sneakerek!','Jó szett, apró sneakerek!','utcai stílusú szett','szett egy esküvőre','flirt','exclamation'),
(2278,'hu','Felnéz az égre.','Felnéz egy repülőre.','felnézni a felhőkre','kikeresni egy szót','chill','none'),
(2282,'hu','Vitorlázás naplementekor. Nagyon chill.','Szörfözés naplementekor. Nagyon chill.','vitorlázás naplementekor','vitorlázás viharban','slang','none'),
(2284,'hu','Tollak? Merész frizura.','Gyöngyök? Merész frizura.','tollakból álló frizura','rövid frizura','flirt','none'),
(2285,'hu','A pulcsija óriási.','A hátizsákja óriási.','nagy kék pulcsi','pulcsi egy széken','chill','exaggeration'),
(2287,'hu','Egyedül ül a gyászában.','Egyedül ül egy autóban.','gyász egy sötét kertben','gyász egy temetésen','dramatic','none'),
(2288,'hu','Crop top a kikötőben.','Crop top a síparadicsomban.','fekete crop top','fehér crop top','chill','none'),
(2291,'hu','Csak néhány aszteroida. Nyugi.','Csak néhány madár. Nyugi.','lebegő aszteroidák','Földbe csapódó aszteroida','ironic','understatement'),
(2295,'hu','Ezek a ruhaujjak hatalmasak!','Ezek a csizmák hatalmasak!','bő fehér ruhaujjak','rövid fekete ruhaujjak','dramatic','exclamation'),
(2296,'hu','A virágmintás ruhája passzol a falhoz!','A csíkos ruhája passzol a falhoz!','narancssárga virágmintás ruha','virágmintás stranding','gossip','exaggeration'),
(2297,'hu','A hullámok a partot csapkodják.','A hullámok a hajót csapkodják.','pálmafák a parton','csónak a parton','chill','none'),
(2300,'hu','Lángokban áll a gitár!','Lángokban áll a zongora!','lángokban álló gitár','lángokban álló ház','dramatic','exclamation'),
(2301,'hu','Fellövik az űrsiklót.','Fellövik a repülőgépet.','űrsikló fellövése','új termék bevezetése','chill','none'),
(2302,'hu','Súlytalan és nyugodt.','Súlytalan és rémült.','súlytalan űrhajós','súlytalan toll','chill','none'),
(2305,'hu','Sziklás út egy világítótoronyhoz.','Sziklás út egy kastélyhoz.','sziklás földnyelv','sziklás strand napágyakkal','chill','none'),
(2306,'hu','A vidék sosem ér véget.','A város sosem ér véget.','gyerekek vidéken','vidékről elköltöző gyerekek','chill','exaggeration'),
(2308,'hu','A viking pengét tart.','A viking baltát tart.','viking bundában','viking egy hajón','chill','none'),
(2310,'hu','Dallam száll a zongorából.','Dallam száll a dobból.','felszálló arany dallam','aláhulló arany dallam','dramatic','none'),
(2311,'hu','Az ólomüveg hatalmas.','Az ólomüveg apró.','magas ólomüveg ablakok','ólomüveg lámpa','chill','none'),
(2312,'hu','Versenyautó a pálmafák mellett.','Versenyautó a fenyőfák mellett.','piros versenyautó','piros versenyló','chill','none'),
(2313,'hu','Ott az otthon, ahol a lakóautó.','Ott az otthon, ahol a narancssárga sátor.','narancssárga lakóautó','lakóautó a városban','chill','cliche'),
(2314,'hu','A szellem jelmeze: egy régi lepedő.','A szellem jelmeze: egy régi törölköző.','fehér lepedős szellem','szellem egy kastélyban','low_iq','cheap_quality'),
(2315,'hu','Ez a tájkép papírból van!','Ez a tájkép üvegből van!','papír tájkép','tájképfotó','dramatic','exclamation'),
(2317,'hu','Fel van húzva a piros csuklyája.','Le van hajtva a piros csuklyája.','felhúzott piros csuklya','egy autó motorháztetője','chill','none'),
(2318,'hu','Nagyon hosszú kardja van.','Nagyon hosszú lándzsája van.','hosszú, ívelt kard','hosszú, egyenes kard','chill','none'),
(2322,'hu','Az üveg törött!','Az óra törött!','törött tükrös portré','begipszelt törött kar','dramatic','exclamation'),
(2324,'hu','Úgy énekel, mint egy sztár!','Úgy táncol, mint egy sztár!','énekel a mikrofonba','énekel a zuhany alatt','flirt','exaggeration'),
(2326,'hu','A hercegnek menő kék haja van.','A hercegnek menő rózsaszín haja van.','herceg koronával','herceg lóháton','slang','none'),
(2327,'hu','Ez az autó és a pálmafák nagyon menők.','Ez a bicikli és a pálmafák nagyon menők.','pálmafák naplementekor','pálmafák egy szigeten','slang','none'),
(2328,'hu','Micsoda „szerény” trónus!','Micsoda „szerény” ágy!','hatalmas arany trónus','üres arany trónus','ironic','exclamation'),
(2330,'hu','Virágot akar adni neked.','Tortát akar adni neked.','három sárga virágot ad','vörös rózsákat ad','flirt','guessing'),
(2333,'hu','Nagyon szerelmesek!','Nagyon dühösek!','szerelmesek az őszi levelek alatt','szerelmesek a tengerparton','dramatic','exclamation'),
(2340,'hu','Ez a ház kicsit furcsa.','Ez az autó kicsit furcsa.','furcsa magas ház','furcsa öreg csónak','chill','understatement'),
(2341,'hu','A virágoktól még a halál is szép.','A gyertyáktól még a halál is szép.','halál virágok között','halál autóbalesetben','ironic','none'),
(2344,'hu','A házak kicsit görbék.','A fák kicsit görbék.','magas görbe házak','görbe képkeret','ironic','understatement'),
(2345,'hu','Micsoda hosszú varázslószakáll!','Micsoda rövid varázslószakáll!','idős varázsló szürkében','idős varázsló pirosban','dramatic','exclamation'),
(2347,'hu','Egy exobolygót fedez fel.','Egy mély barlangot fedez fel.','idegen világ felfedezése','régi kastély felfedezése','nerd','none'),
(2349,'hu','Még a macska is beöltözött!','Még a kutya is beöltözött!','boszorkánynak beöltözve','kalóznak beöltözve','gossip','exclamation'),
(2350,'hu','Valaki arcokat faragott! Hű!','Valaki neveket faragott! Hű!','faragott tökarcok','faragott faarcok','low_iq','exclamation'),
(2351,'hu','Valaki egy zöld autót vezet.','Valaki egy sárga autót vezet.','vezetni az őszön át','vezetni a hóban','chill','none'),
(2353,'hu','A gombák óriásiak, tesó.','A gombák aprók, tesó.','óriási rózsaszín gombák','óriási rózsaszín virágok','slang','none'),
(2354,'hu','Hatalmas arany fejdísz!','Hatalmas ezüst fejdísz!','hatalmas arany fejdísz','fejdísz levétele','dramatic','exclamation'),
(2356,'hu','Az út egy bolygó felé vezet.','Az út egy kastély felé vezet.','egy óriási bolygó felé','egy óriási város felé','dramatic','none'),
(2357,'hu','A ház fekete-fehér.','A ház piros-fehér.','fekete-fehér rajz','fekete-fehér film','chill','none'),
(2358,'hu','A farmon piros tetők vannak.','A farmon kék tetők vannak.','farm egy domboldalon','farm tehenekkel','chill','none'),
(2359,'hu','Hagyományos ruhát viselnek.','Modern ruhát viselnek.','hagyományos indiai viselet','hagyományos esküvői torta','chill','none'),
(2360,'hu','Az a piros autó őrült gyorsnak tűnik.','Az a piros furgon őrült gyorsnak tűnik.','gyors piros autó','gyors piros hajó','slang','exaggeration'),
(2363,'hu','Titokzatos füstté változik.','Titokzatos vízzé változik.','titokzatos, füstös nő','titokzatos zárt ajtó','dramatic','none'),
(2364,'hu','Egy fehér bika áll mögötte.','Egy fehér ló áll mögötte.','görbe szarvú bika','bika egy arénában','chill','none'),
(2365,'hu','Olyan fényes a fémruhája.','Olyan koszos a fémruhája.','piros fémruha','piros fém autó','slang','none'),
(2367,'hu','Ez az autó egy kicsit piszkos.','Ez a busz egy kicsit piszkos.','régi, piszkos sportautó','piszkos öreg busz','ironic','understatement'),
(2368,'hu','Ez a strand maga a paradicsom.','Ez a sivatag maga a paradicsom.','trópusi paradicsom naplementekor','a síelők paradicsoma','slang','none'),
(2371,'hu','Az angyal elmerül a bánatában.','Az angyal elmerül a könyvében.','bánattal teli angyal','örömmel teli angyal','dramatic','none'),
(2372,'hu','Teljesen kimerültnek tűnik.','Teljesen izgatottnak tűnik.','kimerült munkás','lemerült telefonakku','slang','none'),
(2373,'hu','A világegyetem zsúfoltnak tűnik.','A világegyetem üresnek tűnik.','bolygókkal teli világegyetem','csillagok nélküli világegyetem','ironic','exaggeration'),
(2375,'hu','Félig szürke, félig sárga. Nem tud dönteni.','Félig szürke, félig zöld. Nem tud dönteni.','egy fél sárga autó','egy fél sárga busz','low_iq','guessing'),
(2378,'hu','Most teljesen lazít.','Most épp rohan.','lazítás a hold alatt','lazítás a strandon','slang','none'),
(2379,'hu','Piros levelek esnek.','Piros almák esnek.','esőben hulló levelek','autókra hulló hó','chill','none'),
(2380,'hu','Az autó menekül a tűz elől!','Az autó menekül az árvíz elől!','menekülés egy égő erdőből','menekülés egy égő házból','dramatic','exclamation'),
(2381,'hu','Ezek a karmok nagyon élesek!','Ezek a fogak nagyon élesek!','karmok egy ágon','karmok egy macskán','dramatic','exclamation'),
(2382,'hu','Nézd, a farkán kék pikkelyek vannak.','Nézd, a farkán rózsaszín pikkelyek vannak.','kék pikkelyes farok','fürdőszobai mérleg','gossip','none'),
(2383,'hu','Tűz és drágakövek mindenhol!','Jég és drágakövek mindenhol!','csillogó színes drágakövek','drágakövek egy sötét barlangban','dramatic','exaggeration'),
(2384,'hu','Apró királyság egy dombon.','Apró királyság egy szigeten.','mesebeli királyság','az állatok királysága','chill','none'),
(2385,'hu','Lila földönkívüli táj.','Zöld földönkívüli táj.','lila földönkívüli világ','földönkívüli egy űrhajóban','nerd','none'),
(2386,'hu','A korlát a naplemente felé néz.','A korlát egy hegy felé néz.','fém erkélykorlát','lépcsőkorlát','chill','none'),
(2387,'hu','A fa csavarodott. Menő.','A fa egyenes. Menő.','csavarodott öreg fa','csavarodott fémkerítés','low_iq','none'),
(2388,'hu','Ez a gamer imádja a rózsaszínt.','Ez a gamer imádja a zöldet.','gamer rózsaszínben','gamer kékben','gossip','none'),
(2389,'hu','Hittel imádkozik.','Kitárt karokkal imádkozik.','imádkozás mély hittel','elveszíti a hitét','chill','none'),
(2390,'hu','Ilyen stílusos a tengerparton!','Ilyen stílusos egy hajón!','stílusos strandszett','stílusos télikabát','flirt','exclamation'),
(2391,'hu','Epikus tájkép, vörös ég.','Epikus tájkép, kék ég.','tájkép hatalmas holddal','díszlet egy iskolai színdarabhoz','slang','none'),
(2392,'hu','Séta szalmakalapban? Stílusos.','Séta piros kalapban? Stílusos.','séta a virágok között','séta a tengerparton','flirt','none'),
(2393,'hu','Irodai szett magas sarkú cipővel.','Irodai szett sportcipővel.','fekete pántos magas sarkú cipő','magas sarkú cipő egy dobozban','business','none'),
(2394,'hu','Választania kell egy utat.','Választania kell egy hajót.','a jó út kiválasztása','a jó ruha kiválasztása','dramatic','guessing'),
(2395,'hu','A mellényén aranygombok vannak.','A mellényén ezüstgombok vannak.','fekete bőrmellény','mellény zakó alatt','chill','none'),
(2397,'hu','Ez a szoba olyan komor!','Ez a szoba olyan napos!','komor gótikus szoba','komor esős nap','dramatic','exclamation'),
(2398,'hu','A teraszról tengeri kilátás nyílik.','A teraszról városi kilátás nyílik.','csempézett tengerparti terasz','terasz a hegyekben','business','none'),
(2400,'hu','Ez aztán egy vad viking!','Ez aztán egy vad kalóz!','vad, dühös tekintet','vad vihar a tengeren','dramatic','exclamation'),
(2404,'hu','Ennek a lótusznak narancssárga a közepe.','Ennek a lótusznak lila a közepe.','fehér lótuszvirág','lótuszülés jógában','nerd','none'),
(2406,'hu','Egy terepjáró, túl sok táska!','Egy bicikli, túl sok táska!','táskákkal teli terepjáró','terepjáró a városban','dramatic','exaggeration'),
(2408,'hu','A képzelet valódi ösvényt nyit.','A képzelet valódi ajtót nyit.','a képzelet könyve','semmi képzelet','chill','none'),
(2411,'hu','Az a korona nagyon díszes!','Az a maszk nagyon díszes!','díszes aranykorona','díszes faajtó','gossip','none'),
(2412,'hu','Karonfogva sétálnak.','Karonfogva futnak.','karonfogva sétálva','karonfogva ülve','chill','none'),
(2413,'hu','Egy farkaskölyköt ölel!','Egy medvekölyköt ölel!','farkaskölyök ölelése','nagy farkas ölelése','dramatic','exclamation'),
(2415,'hu','Az isten virágfüzéreket visel.','Az isten papírfüzéreket visel.','vörös virágfüzérek','füzérek a karácsonyfán','chill','none'),
(2417,'hu','Sötét és világos harmóniában.','Piros és kék harmóniában.','a harmónia gömbje','éneklés harmóniában','nerd','none'),
(2418,'hu','Szerintem ez egy énekesmadár.','Szerintem ez egy galamb.','énekesmadár egy ágon','énekesmadár egy háztetőn','low_iq','guessing'),
(2420,'hu','Ez a rozoga torony „biztonságos”.','Ez a rozoga híd „biztonságos”.','házakból álló rozoga torony','rozoga öreg szék','ironic','understatement'),
(2421,'hu','Ez a gomba nagy. Nagyon nagy.','Ez a gomba kicsi. Nagyon kicsi.','óriási sápadt gomba','penész a régi kenyéren','low_iq','exaggeration'),
(2422,'hu','Kertésznadrágban olvas.','Kertésznadrágban alszik.','kék farmer kertésznadrág','festékes kertésznadrág','chill','none'),
(2424,'hu','Bal oldalon ciprusok nőnek.','Jobb oldalon ciprusok nőnek.','ciprusfasor','ciprus cserépben','nerd','none'),
(2425,'hu','Egy fekete macska egy kísérteties keretben!','Egy fehér macska egy kísérteties keretben!','keret fekete rózsákkal','szemüvegkeret','dramatic','exclamation'),
(2428,'hu','Három monitor, maximális fókusz.','Két monitor, maximális fókusz.','három nagy monitor','bébimonitor','business','exaggeration'),
(2429,'hu','Figyu, a szarvasbika a patakban áll.','Figyu, a szarvasbika a mezőn áll.','szarvasbika a patakban','szarvasbika a hóban','slang','none'),
(2430,'hu','A folyó sziklák mellett folyik el.','A folyó házak mellett folyik el.','sziklák között folyó folyó','városon átfolyó folyó','chill','none'),
(2432,'hu','Brutál ez a flamencopóz!','Brutál ez a balettpóz!','flamenco legyezővel','flamenco a színpadon','slang','exclamation'),
(2433,'hu','A ló felénk vágtázik!','A szamár felénk vágtázik!','vágtázó fehér ló','vágtázó fekete ló','dramatic','exclamation'),
(2434,'hu','A csendéleten virágzó ágak vannak.','A csendéleten narancsok vannak.','csendélet virágokkal','csendélet gyümölcsökkel','nerd','none'),
(2435,'hu','A patak tele van kavicsokkal.','A patak tele van halakkal.','sima, kerek kavicsok','kavicsok a strandon','chill','none'),
(2439,'hu','Az utca éjjel nedves.','Az utca éjjel száraz.','nedves éjszakai utca','nedves homokos strand','business','none'),
(2440,'hu','Mindenhol áram van!','Mindenhol víz van!','áramszikrák','áramszámla','dramatic','exaggeration'),
(2446,'hu','Nagy masnik, hosszú cipőfűzők!','Nagy masnik, rövid cipőfűzők!','hosszú sárga cipőfűzők','elszakadt sárga cipőfűzők','low_iq','exclamation'),
(2449,'hu','Csak „néhány” világító kirakat.','Csak „néhány” sötét kirakat.','világító kirakatok','betört kirakat','ironic','understatement'),
(2450,'hu','Zivatar a víz felett.','Zivatar a város felett.','zivatar a víz felett','zivatar egy kisváros felett','chill','none'),
(2451,'hu','Egy madár az Eiffel-torony közelében.','Egy repülő az Eiffel-torony közelében.','folyóparti Eiffel-torony','havas Eiffel-torony','chill','none'),
(2452,'hu','A havas séta romantikus!','Az esős séta romantikus!','romantikus havas séta','romantikus gyertyafényes vacsora','flirt','exclamation'),
(2454,'hu','A kanyargós ösvényen lámpások vannak.','Az egyenes ösvényen lámpák vannak.','kanyargós macskaköves ösvény','kanyargós hegyi folyó','chill','none'),
(2455,'hu','Zöld rövidnadrágot visel.','Zöld hosszúnadrágot visel.','zöld farmer rövidnadrág','zöld fürdőnadrág','chill','none'),
(2457,'hu','A nővérnek sztetoszkópja van.','A nővérnek csíptetős írótáblája van.','egyenruhás nővér','nővér egy babával','chill','none'),
(2458,'hu','Tanyaház kivilágított ablakokkal.','Tanyaház sötét ablakokkal.','tanyaház naplementekor','tanyaház a tenger mellett','chill','none'),
(2460,'hu','Vadvirágok egy kék cserépben, cuki.','Vadvirágok egy piros cserépben, cuki.','egy cserép vadvirág','vadvirágos mező','slang','none'),
(2462,'hu','A csillagos égen ott a hold.','A csillagos égen ott a szivárvány.','csillagos éjszakai égbolt','csillagos városi éjszaka','chill','none'),
(2463,'hu','A völgyet rózsaszín bazsarózsák díszítik.','A völgyet rózsaszín tulipánok díszítik.','rózsaszín bazsarózsák egy dombon','bazsarózsák vázában','business','none'),
(2464,'hu','A minták szimmetrikusak.','A minták színesek.','szimmetrikus levélminták','szimmetrikus épület','nerd','none'),
(2465,'hu','Lebeg. Semmi különös.','Úszik. Semmi különös.','lebegés a kék égen','lebegés a medencében','ironic','understatement'),
(2466,'hu','A ruhája kristályokból van.','A ruhája tollakból van.','világító kristályokból álló ruha','kristálypohár víz','chill','none'),
(2470,'hu','A szaxofonnak ívelt tölcsére van.','A szaxofonnak egyenes tölcsére van.','lebegő szaxofon','szaxofonos','nerd','none'),
(2471,'hu','Igazi könyvmoly.','Igazi gamer.','könyvmoly egy könyvvel','könyvmoly egy telefonnal','gossip','none'),
(2472,'hu','Az egyenruhája nagyon rendezett.','A kabátja nagyon rendezett.','iskolai egyenruha','rendőrségi egyenruha','chill','none'),
(2473,'hu','A koszorú egy piros ajtón van.','A koszorú egy kék ajtón van.','koszorú az ajtón','koszorú a fején','chill','none'),
(2474,'hu','Vad hab a viharos tengeren.','Vad hab a nyugodt tengeren.','hab a viharos hullámokon','kávé tejhabbal','dramatic','none'),
(2475,'hu','Mezítláb olvas.','Mezítláb táncol.','mezítláb egy heverőn','mezítláb a strandon','chill','none'),
(2477,'hu','A szél kócossá tette a haját.','Az eső kócossá tette a haját.','kócos barna haj','rendetlen hálószoba','low_iq','blaming_someone'),
(2478,'hu','Az orvos ránk mosolyog.','Az orvos ránk kiabál.','mosolygó rajzfilm-orvos','orvos műtét közben','chill','none'),
(2480,'hu','Túl sok ajándék van az autón!','Túl sok kutya van az autón!','ajándékok az autó tetején','ajándékok a fa alatt','dramatic','exaggeration'),
(2481,'hu','Egy földgömböt tart.','Egy labdát tart.','földgömböt tart','hógömb','chill','none'),
(2482,'hu','Ennyi tornyocska egy kastélyon!','Ennyi zászló egy kastélyon!','hegyes kastélytornyocskák','tank lövegtornya','gossip','exclamation'),
(2483,'hu','Szárított virágok vannak a könyvben.','Friss virágok vannak a könyvben.','szárított virágok egy könyvben','szárított gyümölcs egy tálban','chill','none'),
(2484,'hu','Ez egy magas templomtorony.','Ez egy magas kastélytorony.','templomtorony a hóban','templomtorony egy városban','chill','none'),
(2485,'hu','A varjúember baljósnak tűnik.','A macskaember baljósnak tűnik.','baljós varjúfejű alak','baljós fekete macska','dramatic','none'),
(2486,'hu','Hieroglifák borítják a falat.','Virágok borítják a falat.','hieroglifákkal teli fal','hieroglifák egy tankönyvben','chill','none'),
(2490,'hu','Szép kalap! Fázik a hóember?','Szép kalap! Fázik a kutya?','hóember kalapban','hóemberépítés','low_iq','guessing'),
(2492,'hu','Olyan forgalmas a falu!','Olyan csendes a falu!','forgalmas havas falu','forgalmas nyári strand','dramatic','exclamation'),
(2494,'hu','Viktoriánus utca. Az ott Sherlock?','Modern utca. Az ott Sherlock?','havas viktoriánus utca','viktoriánus teadélután','gossip','guessing'),
(2495,'hu','Két verebet számoltam.','Négy verebet számoltam.','két veréb egy ágon','két veréb a hóban','low_iq','none'),
(2497,'hu','A Mikulás szünetet tart.','A Mikulás fürdőt vesz.','Mikulás ajándékokkal','Mikulás rénszarvasokkal','gossip','guessing'),
(2498,'hu','Gyengéden átölelik egymást.','Gyengéden megcsókolják egymást.','gyengéd ölelés','gyengéd kézfogás','chill','none'),
(2499,'hu','Két plüssmaci ölelkezik.','Két plüssmaci verekszik.','plüssmacik a hóban','plüssmacik az ágyon','chill','none'),
(2500,'hu','Egy laptopon gépel.','Egy telefonon gépel.','gépelés laptopon','laptop cipelése','chill','none'),
(2501,'hu','Siva egy sziklán meditál.','Siva egy csónakban meditál.','Siva háromágú szigonnyal','Siva karddal','nerd','none'),
(2502,'hu','Mohával teli erdei szentély.','Homokkal teli sivatagi szentély.','mohás erdei szentély','szentély egy városban','chill','none'),
(2504,'hu','Krisnának pávatolla van.','Krisnának sastolla van.','Krisna koronával','Krisna fuvolával','nerd','none'),
(2505,'hu','Eső, egy puska és nulla panasz.','Napsütés, egy puska és nulla panasz.','hosszú, távcsöves puska','puska a földön','chill','understatement'),
(2506,'hu','Itt minden geometrikus.','Itt minden kék.','rózsaszín geometrikus formák','geometriadolgozat','chill','none'),
(2509,'hu','Egy ösvény vezet át a levendulán.','Egy ösvény vezet át a búzán.','lila levendulasorok','egy üveg levendulaolaj','chill','none'),
(2510,'hu','Lefekvés ideje egy fiúnak és egy macskának!','Lefekvés ideje egy fiúnak és egy kutyának!','lefekvés ideje a takaró alatt','esti mese egy könyvvel','dramatic','exclamation'),
(2511,'hu','Szikrák repkednek körülöttük.','Levelek repkednek körülöttük.','szikrák egy pár körül','szikra a konnektorból','flirt','none'),
(2512,'hu','Ez a kifestőkönyv rád vár.','Ez a fotóalbum rád vár.','kifestőkönyv-oldal','kifestőkönyv borítója','chill','guessing'),
(2514,'hu','Gyógynövényeket tesz egy tálba.','Sót tesz egy tálba.','szárított gyógynövények szórása','friss gyógynövények aprítása','chill','none'),
(2516,'hu','Ez a 2024-es év.','Ez a 2025-ös év.','az izzó 2024-es év','a 2025-ös év','chill','none'),
(2519,'hu','Láttad ezt a hátsó udvart? Egy flamingó!','Láttad ezt a hátsó udvart? Egy hinta!','nyüzsgő kis hátsó udvar','veteményes a hátsó udvarban','gossip','exclamation'),
(2520,'hu','Szent fény felülről!','Szent fény alulról!','szent fénysugár','szent folyó','dramatic','exclamation'),
(2522,'hu','A lóheréknek négy levelük van.','A lóheréknek három levelük van.','négylevelű lóherék','lóheremező tehenekkel','nerd','none'),
(2523,'hu','Ma éjjel erős a havazás.','Ma éjjel erős az esőzés.','erős havazás egy falu felett','enyhe havazás a városban','chill','none'),
(2524,'hu','Sétabotja van.','Nagy esernyője van.','sétabotra támaszkodik','sétabot túrázáshoz','chill','none'),
(2525,'hu','Anya felemeli a medvebocsát.','Anya felemeli a rókakölykét.','felemelni a bocsot','felemelni egy nehéz dobozt','chill','none'),
(2526,'hu','Poszeidónnak két lándzsája van.','Poszeidónnak két kardja van.','a hullámokból kiemelkedő Poszeidón','hajót elsüllyesztő Poszeidón','nerd','none'),
(2527,'hu','A DJ gázálarcot visel. Miért?','A DJ símaszkot visel. Miért?','gázálarc és fejhallgató','gázálarc és védőszemüveg','ironic','guessing'),
(2528,'hu','Lila cilinder? Merész választás.','Fekete cilinder? Merész választás.','fényes lila cilinder','bűvész cilindere','gossip','understatement'),
(2530,'hu','Gyertyafény ragyog a rózsák között.','Gyertyafény ragyog a könyvek között.','gyertyafény egy lámpásban','gyertyafény egy tortán','chill','none'),
(2531,'hu','Még az ég is csillog nekik.','Még a tenger is csillog nekik.','csillogó éjszakai égbolt','buborékos víz egy pohárban','flirt','none'),
(2532,'hu','A ruháján szürke fodrok vannak.','A ruháján piros fodrok vannak.','ruha szürke fodrokkal','fodrok egy piros kalapon','chill','none'),
(2533,'hu','A túlsó vége ködös.','A túlsó vége napos.','ködös régi utca','ködös hegyi tó','chill','none'),
(2536,'hu','Ez a csimpánz úgy néz ki, mint egy komoly motoros.','Ez a csimpánz úgy néz ki, mint egy komoly szörfös.','csimpánz motoron','csimpánz egy fán','gossip','cliche'),
(2537,'hu','A lány esti mesét olvas.','A fiú esti mesét olvas.','esti mese az ágyban','esti mese a tévében','chill','none'),
(2538,'hu','Piroska megbízik a farkasban.','Piroska megbízik a medvében.','Piroska farkasa','Piroska nagymamája','gossip','guessing'),
(2539,'hu','Mesterséges intelligencia él a fejében.','Mesterséges intelligencia él az autójában.','mesterséges intelligenciájú robot','mesterséges intelligencia app','nerd','none'),
(2540,'hu','Micsoda „hangulatos” tömlöc.','Micsoda „hangulatos” kert.','sötét tömlöc gyertyákkal','sötét pince borral','ironic','none'),
(2541,'hu','Ezt a lépcsőházat senki sem takarította.','Ezt a konyhát senki sem takarította.','omladozó kő lépcsőház','omladozó kőhíd','ironic','understatement'),
(2543,'hu','Az elefántnak hosszú agyarai vannak.','Az elefántnak rövid agyarai vannak.','két hosszú fehér agyar','rozmár agyarakkal','chill','none'),
(2544,'hu','Hanumánnak aranykoronája van.','Hanumánnak ezüstkoronája van.','Hanumán arany bottal','Hanumán karddal','nerd','none'),
(2545,'hu','A majom az istenét imádja.','A majom alszik.','imádat a kőlépcsőn','egy focisztár imádata','chill','none'),
(2546,'hu','Ez a terem „egészen” tágas.','Ez a terem „egészen” apró.','tágas terem','tágas autó','ironic','understatement'),
(2547,'hu','Ezek a légyölő galócák hatalmasak!','Ezek a légyölő galócák aprók!','óriási légyölő galócák','légyölő galócák egy kosárban','slang','exclamation'),
(2548,'hu','Mennyi hordó. Talán sör?','Mennyi bicikli. Talán sör?','egymásra rakott fahordók','egy hordó hideg sör','low_iq','guessing'),
(2550,'hu','Törökülésben ül, mezítláb.','Törökülésben ül, csizmában.','törökülésben ülve','törökülésben állva','chill','none'),
(2551,'hu','Miami vibe: pálmák és neon.','Miami vibe: hó és neon.','neonfényes miami utca','miami strand délben','slang','none'),
(2552,'hu','Virtuális valóságban van.','Egy uszodában van.','virtuálisvalóság-szemüveg','virtuális valóság az iskolában','chill','none'),
(2556,'hu','Tény: az agy világít.','Tény: a szív világít.','világító agy','agy egy befőttesüvegben','nerd','none'),
(2557,'hu','Várj, a vitorlás üvegből van?','Várj, a vitorlás fából van?','üveg vitorlás','palackba zárt vitorlás','low_iq','none'),
(2558,'hu','Repül. Tiszta szabadság!','Úszik. Tiszta szabadság!','szabadság a tenger fölött','szabadság a tenger alatt','dramatic','exclamation'),
(2559,'hu','Ezen a fán érmék nőnek!','Ezen a fán almák nőnek!','fáról hulló érmék','érmék egy malacperselyben','dramatic','exclamation'),
(2560,'hu','Vízen járni? Csoda!','Tűzön járni? Csoda!','csoda az óceánon','csodaszer megfázásra','dramatic','exclamation'),
(2562,'hu','Esős éjszaka, magányos nyomozó.','Napos nap, magányos nyomozó.','nyomozó az esőben','helyszínelő nyomozó','dramatic','cliche'),
(2563,'hu','Egy kereskedő gabonát ellenőriz.','Egy kereskedő érméket ellenőriz.','kereskedő gyertyafénynél','kereskedő a piacon','chill','none'),
(2564,'hu','Ez a hortenziafürt kék.','Ez a hortenziafürt rózsaszín.','kék hortenziafürt','hortenzia vázában','nerd','none'),
(2567,'hu','A szent fehér fátylat visel.','A szent piros fátylat visel.','szent glóriával','szent lóháton','chill','none'),
(2571,'hu','A fiú morcos. Megint.','A lány morcos. Megint.','morcos kisfiú','morcos öregember','ironic','guessing'),
(2572,'hu','A háromszögek világítanak.','A körök világítanak.','világító neon háromszögek','háromszög alakú közlekedési tábla','chill','none'),
(2575,'hu','A DJ teljesen névtelen.','A séf teljesen névtelen.','névtelen, kapucnis DJ','névtelen levél','slang','none'),
(2576,'hu','Összetört a szíve Párizsban.','Összetört a szíve Rómában.','összetört szívvel az esőben','összetört szívvel a hóban','dramatic','none'),
(2579,'hu','A szemüvege szuper fura.','A kalapja szuper fura.','fura retró gép','fura öreg autó','slang','exaggeration'),
(2580,'hu','Az íjász megfeszíti az íját.','Az íjász kardot ránt.','íjászszobor','íjászt ábrázoló festmény','chill','none'),
(2581,'hu','Bambuszfuvolán játszik.','Bambuszdobon játszik.','bambuszfuvolán játszik','bambuszfuvolát farag','chill','none'),
(2583,'hu','Nagyon élvezi a vibe-ot.','Nagyon élvezi a pizzát.','a zene élvezete','a napsütés élvezete','slang','none'),
(2584,'hu','Ez egy keresztelő a folyóban.','Ez egy keresztelő a templomban.','keresztelő a folyóban','templomi keresztelő','chill','none'),
(2594,'hu','A robot önmagáról tanul.','A robot a macskákról tanul.','olvasni tanuló robot','repülni tanuló robot','low_iq','guessing'),
(2595,'hu','Valaki kint hagyott egy koncertzongorát.','Valaki bent hagyott egy koncertzongorát.','koncertzongora a szabadban','koncertzongora egy teremben','ironic','guessing'),
(2600,'hu','Tesó, két bogár chillel.','Tesó, két csiga chillel.','leveleken mászó bogarak','virágok fölött repülő bogarak','slang','none'),
(2601,'hu','A férfi letérdel imádkozni.','A férfi leül imádkozni.','letérdelve a kőpadlón','letérdelve egy puha kanapén','chill','none'),
(2602,'hu','Olyan gyorsan síelnek lefelé.','Olyan gyorsan síelnek felfelé.','síelés meredek lejtőn','síelés sík úton','slang','none'),
(2603,'hu','A kotta kézzel írott.','A kotta nyomtatott.','régi kézzel írott kotta','új nyomtatott kotta','nerd','none'),
(2604,'hu','Élettelen fa, zöld hold.','Élettelen fa, fehér hold.','élettelen fa a sziklákon','élettelen cserepes fa','dramatic','none'),
(2605,'hu','Egy babát ringat a karjában.','Egy bárányt ringat a karjában.','babát ringatni a karjában','telefont tartani a kezében','chill','none'),
(2606,'hu','A feje színtiszta óramű.','A feje színtiszta üveg.','óraművel teli fej','óraműves játékegér','nerd','exaggeration'),
(2607,'hu','A macskák elegáns kabátot viselnek.','A kutyák elegáns kabátot viselnek.','hosszú kabátot viselő macskák','nyakörvet viselő macskák','business','none'),
(2611,'hu','Az övén fémcsat van.','A táskáján fémcsat van.','fém övcsat','biztonsági öv becsatolása','chill','none'),
(2612,'hu','Két bimbó még nem nyílt ki.','Két bimbó már kinyílt.','két zárt piros bimbó','két nyitott piros bimbó','nerd','none'),
(2614,'hu','Két fiú van egy minaret közelében.','Két lány van egy minaret közelében.','séta egy minaret felé','felmászás egy minaretre','chill','none'),
(2618,'hu','A kézírás folyóírás.','A kézírás nyomtatott betűs.','halvány, folyóírásos kézírás','szép, nyomtatott betűs kézírás','nerd','none'),
(2621,'hu','Az árbocon rengeteg kötélzet van.','Az árbocon rengeteg zászló van.','magas árboc kötélzettel','árboc kalózzászlókkal','nerd','none'),
(2622,'hu','Egy apró Szabadság-szobor!','Egy apró Eiffel-torony!','mini Szabadság-szobor','Szabadság-szobor jelmez','dramatic','exclamation'),
(2623,'hu','Borostyán borítja a könyvespolcot.','Hó borítja a könyvespolcot.','borostyánnal borított könyvespolc','borostyánnal borított kastély','chill','none'),
(2625,'hu','A mérnök darukról álmodik.','A mérnök lovakról álmodik.','egy mérnök védősisakja','mérnök a számítógépnél','nerd','guessing'),
(2626,'hu','Egy város él a kopasz fejében.','Egy farm él a kopasz fejében.','kopasz fej profilból','kopasz fej szemüveggel','chill','none'),
(2629,'hu','Két copfba van fonva a haja.','Két kontyba van fogva a haja.','két hosszú, fonott copf','két rövid, göndör copf','chill','none'),
(2631,'hu','A védőszemüvegének kerek lencséi vannak.','A védőszemüvegében nincs lencse.','kerek, színezett lencsék','lencse egy fényképezőgépen','chill','none'),
(2633,'hu','Az a fa egy diszkó. Nézd a fénysugarakat!','Az a fa egy diszkó. Nézd a madarakat!','színes fénysugarak','tetőgerendák','low_iq','exaggeration'),
(2634,'hu','Minden üvegben parafa dugó van.','Minden üvegben szívószál van.','parafa dugóval lezárt üvegek','parafatábla cetlikkel','chill','none'),
(2635,'hu','A magnólia krémfehér.','A magnólia élénksárga.','nyitott magnóliavirág','magnóliafa','chill','none'),
(2641,'hu','Sugarak töltik be az eget!','Sugarak töltik be a szobát!','arany fénysugarak','sugarak az ablakon át','dramatic','exclamation'),
(2648,'hu','Ez a hangya nagyobb nálam!','Ez a méh nagyobb nálam!','hatalmas fekete hangya','hatalmas hangyaboly','low_iq','exaggeration'),
(2649,'hu','Ez a védőszemüveg óriási!','Ezek a fülbevalók óriásiak!','világító védőszemüveg a szemén','úszószemüveg','dramatic','exclamation'),
(2651,'hu','A piros tetőn fehér pöttyök vannak.','A piros tetőn fekete pöttyök vannak.','sapka fehér pöttyökkel','kutya fehér pöttyökkel','chill','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
