begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(2652,'hu','Minden szürke, csak a kabátja nem!','Minden piros, csak a kabátja nem!','szürke kabátok az esőben','szürke kabátok a hóban','dramatic','exclamation'),
(2654,'hu','Pántok fel, irány a Hold.','Pántok fel, irány a tenger.','széles fehér pántok','bőr óraszíj','chill','guessing'),
(2656,'hu','Két piros busz. Nagyon London.','Két piros villamos. Nagyon London.','piros emeletes busz','piros emeletes villamos','slang','cliche'),
(2657,'hu','A madár egy kollázs része.','A macska egy kollázs része.','madár egy kollázsban','kollázs régi fotókból','chill','none'),
(2658,'hu','Felemeli az öklét!','Felemeli a kardját!','felemelt ököl','érmékkel teli ököl','dramatic','exclamation'),
(2660,'hu','Kúszónövények lógnak a boltív fölött.','Zászlók lógnak a boltív fölött.','kúszónövény a kőíven','kúszónövény tele szőlővel','chill','none'),
(2661,'hu','A csempék sakktáblát alkotnak.','A csempék szivárványt alkotnak.','fekete-fehér padlócsempe','kék-fehér falicsempe','nerd','none'),
(2663,'hu','Milyen hosszú az árnyéka!','Milyen rövid az árnyéka!','egy cowboy hosszú árnyéka','árnyék a falon','dramatic','exclamation'),
(2664,'hu','Valaki egyetlen új követőért fullad vízbe.','Valaki egyetlen új követőért úszik.','fuldoklás az óceánban','fuldoklás a házi feladatban','ironic','exaggeration'),
(2666,'hu','Virágcserepek szegélyezik a lépcsőt.','Gyertyák szegélyezik a lépcsőt.','virágcserepek a kőlépcsőn','virágcserepek az ablakpárkányon','chill','none'),
(2669,'hu','Esküszöm, egymillió teáskanna.','Esküszöm, egymillió lámpa.','porcelán teáskannák a polcokon','teáskanna a tűzhelyen','gossip','exaggeration'),
(2670,'hu','Az asztalnak egy fiókja van.','Az asztalnak három fiókja van.','gombos fiók','zoknival teli fiók','chill','none'),
(2673,'hu','Ő ül a kalitkában, a madár szabad.','A madár ül a kalitkában, ő szabad.','egy kalitkában ülve','egy kalitkát takarítva','ironic','none'),
(2675,'hu','A macska a könyvre teszi a mancsát, mint egy professzor.','A macska a csészére teszi a mancsát, mint egy professzor.','mancs a könyvön','mancs a ceruzán','nerd','exaggeration'),
(2678,'hu','A papír felfalja a laptopot.','A papír felfalja az ágyat.','papírhalmok','papírrepülő','dramatic','exaggeration'),
(2682,'hu','A tigris támad!','Az oroszlán támad!','támadó tigris','megtámadott tigris','dramatic','exclamation'),
(2683,'hu','Az arcfestése egy mandala.','Az arcfestése egy pók.','mandala arcfestéssel','arcfestés egy bohócon','nerd','none'),
(2684,'hu','Ezek a maszkok karneválra valók.','Ezek a maszkok műtétre valók.','karneváli szemmaszkok','karneváli felvonulás','chill','guessing'),
(2685,'hu','Az álarcosbál maszkjai aranyszínűek.','Az álarcosbál maszkjai pirosak.','arany álarcosbáli maszkok','meghívó egy álarcosbálra','business','none'),
(2686,'hu','A barna hajú nő olyan nyugodtnak tűnik.','A szőke nő olyan nyugodtnak tűnik.','barna hajú nő kékben','barna hajú nő pirosban','flirt','none'),
(2687,'hu','Villa medencével. Nagyon exkluzív.','Villa teniszpályával. Nagyon exkluzív.','türkizkék medence','fedett medence','business','none'),
(2688,'hu','Nagyon hosszú a rasztája.','Nagyon rövid a rasztája.','mellkasig érő raszta','rövid raszta sapka alatt','chill','none'),
(2690,'hu','A koronája tele van gyémánttal.','A koronája tele van tollal.','gyémántokkal kirakott korona','gyémántgyűrű','gossip','exaggeration'),
(2691,'hu','Ballonkabát van rajta.','Síkabát van rajta.','bézs ballonkabát','vizes ballonkabát','chill','none'),
(2693,'hu','Egy fa nő ki egy könyvből!','Egy fa nő ki egy bögréből!','kinő egy könyvből','kinő egy cserépből','dramatic','exclamation'),
(2694,'hu','Nagyon gondolkodik.','Nagyon nevet.','gondolkodás a sötétben','gondolkodás a vacsorán','chill','none'),
(2698,'hu','Nyitott spaletta, forró kávé, tökéletes.','Nyitott spaletta, hideg sör, tökéletes.','kinyitott zöld spaletták','éjszakára zárt spaletták','chill','cliche'),
(2702,'hu','Természetcsomag: a vízesés benne van.','Természetcsomag: a kastély benne van.','természet vízeséssel','természet forgalmas úttal','business','none'),
(2703,'hu','Óriási obeliszk a hóban.','Óriási obeliszk a sivatagban.','fekete obeliszk a hóban','obeliszk egy téren','dramatic','none'),
(2704,'hu','Csak törmelék és köd maradt.','Csak hó és köd maradt.','törmelék a ködben','törmelékhordás markolóval','dramatic','none'),
(2708,'hu','A majomisten erősnek tűnik.','A majomisten aprónak tűnik.','erős kar és mellkas','egy erős kávé','chill','none'),
(2709,'hu','Bársonyvirág-koszorút visel.','Rózsakoszorút visel.','bársonyvirág-koszorú','bársonyvirág cserépben','chill','none'),
(2711,'hu','Tavirózsalevelek úsznak körülötte.','Csónakok úsznak körülötte.','tavirózsalevelek a tavon','tavirózsalevelek békákkal','chill','none'),
(2712,'hu','Félig arc, félig anatómia.','Félig arc, félig virágok.','anatómiai rajz','anatómiavizsga','nerd','none'),
(2714,'hu','Citrom, tenger és szalmakalap.','Narancs, tenger és szalmakalap.','széles szalmakalap','madárijesztő szalmakalapja','chill','none'),
(2716,'hu','Big Ben a fák mögött, király.','Big Ben a hajók mögött, király.','kilátás a Big Benre','Big Ben éjfélkor','slang','none'),
(2717,'hu','A parlament a Temze partján áll.','A parlament a Szajna partján áll.','a londoni parlament épülete','parlament a tengerparton','nerd','none'),
(2718,'hu','A zongora félig műszaki rajz.','A hárfa félig műszaki rajz.','zongora műszaki rajza','ház műszaki rajza','nerd','none'),
(2722,'hu','A spirál a cowboy alatt van.','A spirál a cowboy fölött van.','csillagokból álló spirál','csigalépcső','chill','none'),
(2723,'hu','A férfi teljesen dühöng!','A nő teljesen dühöng!','dühöngő harcos','dühöngő sárkány','dramatic','exclamation'),
(2724,'hu','Ő uralja ezt a ködös dzsungelt.','Ő uralja ezt a ködös sivatagot.','ködös zöld dzsungel','tigrisekkel teli dzsungel','dramatic','none'),
(2725,'hu','Egy sziklán guggol.','Egy fán guggol.','magasan egy sziklán guggolva','mélyen egy barlangban guggolva','chill','none'),
(2726,'hu','Két sor gyöngyöt visel.','Két sor csengőt visel.','narancssárga gyöngysorok','gyöngyök számolása zsinóron','chill','none'),
(2728,'hu','Egy nyúl ölelget egy rókát.','Egy nyúl ölelget egy macskát.','rókakölyköt ölelgetni','nyuszikölyköt ölelgetni','chill','none'),
(2729,'hu','Izzik a kristálygömbje.','Törött a kristálygömbje.','kristálygömböt megérinteni','törött kristálygömb','chill','none'),
(2731,'hu','Tény: a pupilla fekete.','Tény: a pupilla fehér.','fekete pupilla','barna pupilla','nerd','none'),
(2732,'hu','Az unoka az ölében ül.','Az unoka egy széken ül.','unoka a nagypapa ölében','unoka a strandon','chill','none'),
(2733,'hu','A hadsereg rohamoz!','A hadsereg visszavonul!','lovas hadsereg','gyalogos hadsereg','dramatic','exclamation'),
(2734,'hu','A macskának pici rózsaszín orra van.','A macskának pici fekete orra van.','kis rózsaszín orr','kis fekete orr','chill','none'),
(2735,'hu','Ez a robbanás olyan jó buli!','Ez az árvíz olyan jó buli!','robbanás egy laborban','színrobbanás','dramatic','exclamation'),
(2736,'hu','A csillagász egy idős férfi.','A csillagász egy fiatal férfi.','idős csillagász','csillagász a távcsőnél','chill','none'),
(2737,'hu','Ez egy fekete lyuk az űrben.','Ez egy fekete hold az űrben.','fekete lyuk az űrben','az adósság fekete lyuka','nerd','none'),
(2738,'hu','Ez az egzotikus madár fejhallgatóval ignorál téged.','Ez az egzotikus madár napszemüveggel ignorál téged.','egzotikus madár fejhallgatóval','egzotikus madarak kalitkában','ironic','guessing'),
(2740,'hu','A bajusza fehér, mint a hó.','A bajusza fekete, mint a szén.','dús fehér bajusz','vékony fekete bajusz','dramatic','cliche'),
(2741,'hu','A programozó éjszaka kódol.','A programozó délben kódol.','kódot gépelő programozó','programozó az edzőteremben','nerd','cliche'),
(2742,'hu','A kódra összpontosít.','Egy könyvre összpontosít.','összpontosítás a képernyőre','összpontosítás egy játékra','nerd','none'),
(2743,'hu','Meredek sziklafalak? Kösz, nem.','Meredek homokfalak? Kösz, nem.','meredek sziklafalak','meredek városi utca','slang','guessing'),
(2744,'hu','Tény: a pávának van bóbitája.','Tény: a pávának nincs bóbitája.','vékony tollakból álló bóbita','tollforgó egy sisakon','nerd','cliche'),
(2745,'hu','A belső udvar tele van régi kövekkel.','A belső udvar tele van régi autókkal.','kövezett belső udvar','belső udvari kávézó asztalokkal','chill','none'),
(2747,'hu','A pufók kisgyereknél buzogány van.','A pufók kisgyereknél íj van.','pufók gyermekisten','pufók kiskutya','chill','none'),
(2749,'hu','Stílusosan ül a bárban.','Stílusosan ül egy autóban.','a bárban ülve','a bárban táncolva','flirt','none'),
(2750,'hu','A szobanövény könyveken áll.','A szobanövény egy tévén áll.','szobanövény a polcon','szobanövény a padlón','chill','none'),
(2751,'hu','Ez a növény brutál tüskés.','Ez a növény brutál puha.','tüskés cserepes növény','tüskés kaktuszgömb','slang','none'),
(2752,'hu','Az egér Németországnak játszik!','A macska Németországnak játszik!','Németország szurkolója','Németország térképe','low_iq','guessing'),
(2753,'hu','Ez a persely gazdag!','Ez a persely le van égve!','nagy rózsaszín malacpersely','törött malacpersely','slang','exaggeration'),
(2754,'hu','Mennyi gőz naplementében!','Mennyi hó naplementében!','fehér gőz a mozdonyból','fehér füst a házkéményből','dramatic','exclamation'),
(2757,'hu','Egy zongora tele inspirációval.','Egy konyha tele inspirációval.','az inspiráció szikrája','inspiráció egy könyvből','chill','none'),
(2758,'hu','Kő mellszobor a sivatagban.','Kő mellszobor a dzsungelben.','hatalmas kő mellszobor','mellszobor egy múzeumban','nerd','none'),
(2759,'hu','Úgy áll ott, mint egy igazi hős.','Úgy ül ott, mint egy igazi hős.','hős egy sziklán','hős egy lovon','dramatic','cliche'),
(2762,'hu','Egy alak sétál a búzában.','Egy alak sétál a hóban.','érett búzamező','egy vekni búzakenyér','chill','none'),
(2765,'hu','A baba mosolyog.','A baba sír.','furulyával mosolyogni','az anyjára mosolyogni','chill','none'),
(2766,'hu','Egy kobra van a vállánál!','Egy tigris van a vállánál!','ágaskodó kobra','kobra egy kosárban','dramatic','exclamation'),
(2770,'hu','A 3-as nagyon izzad!','A 7-es nagyon izzad!','izzadás futás után','izzadás a szaunában','dramatic','exclamation'),
(2771,'hu','Az egér fagyit eszik!','Az egér sajtot eszik!','tölcséres fagyit enni','sajtos szendvicset enni','dramatic','exclamation'),
(2774,'hu','Az építészet gótikus.','Az építészet modern.','gótikus katedrális építészete','modern üvegépítészet','nerd','none'),
(2776,'hu','Magasra tartja a fáklyát.','Magasra tartja a zászlót.','magasra tartott égő fáklya','fáklya egy barlangban','chill','none'),
(2777,'hu','A fejkendőjén nagy bross van.','A fejkendőjén nagy virág van.','nagy ezüst bross','bross egy kabáton','chill','none'),
(2779,'hu','Az írisze kékeszöld.','Az írisze sötétbarna.','kékeszöld írisz','lila íriszvirág','chill','none'),
(2781,'hu','A nő mennyi cuccot visz!','A férfi mennyi cuccot visz!','nehéz táskát vinni','nehéz dobozt vinni','dramatic','exclamation'),
(2782,'hu','Ez a metszet csupa vonal.','Ez a metszet csupa pötty.','finom vonalas metszet','vésés egy gyűrűn','nerd','none'),
(2788,'hu','Szirmokat fúj.','Gyertyákat fúj el.','szirmokat és pillangókat fújni','gyertyákat elfújni','chill','none'),
(2791,'hu','Átlátszó a feje. Menő!','Arany a feje. Menő!','átlátszó koponyakupola','átlátszó esőkabát','slang','exclamation'),
(2793,'hu','Két üzletember van a csúcson.','Öt üzletember van a csúcson.','lépcsőn mászó üzletember','üzletember a liftben','business','none'),
(2794,'hu','Az állatorvos egy macskát tart.','Az állatorvos egy kutyát tart.','macskát ölelő állatorvos','állatorvos a farmon','chill','none'),
(2795,'hu','Fejjel lefelé mászik!','Fejjel lefelé alszik!','mászás egy szikla alatt','mászás egy létrán','dramatic','exclamation'),
(2800,'hu','Kipukkaszthatom azt a nagy buborékot?','Kipukkaszthatom azt a nagy lufit?','buborék az égen','buborék egy pohárban','low_iq','guessing'),
(2801,'hu','Narancssárgán izzanak a fényszórói.','Kéken izzanak a fényszórói.','narancs fényszórók a hóban','fényszórók egy havas autón','chill','none'),
(2803,'hu','Az arca pszichedelikus!','Az arca szürke és unalmas!','pszichedelikus portré','pszichedelikus autó','dramatic','exclamation'),
(2805,'hu','Ez a srác biztos remekművet rajzol majd.','Ez a lány biztos remekművet rajzol majd.','képet rajzolni','térképet rajzolni','ironic','guessing'),
(2806,'hu','Kisgyerek arany turbánban.','Kisgyerek arany sisakban.','kisgyerek tollal','kisgyerek babakocsiban','chill','none'),
(2808,'hu','Az üzletasszony mosolyog.','Az üzletasszony sír.','üzletasszony az autójánál','üzletasszony a vonaton','business','none'),
(2809,'hu','Egy kis teáscsészét tart.','Egy kis teáskannát tart.','teáscsésze két kézben','teáscsésze csészealjon','chill','none'),
(2810,'hu','Két kávé egy munkasarokban!','Két laptop egy munkasarokban!','hangulatos munkasarok','közös irodai munkasarok','ironic','exclamation'),
(2811,'hu','Egy hologramautót érint.','Egy játékautót érint.','autó hologramja','hologram egy kártyán','nerd','none'),
(2812,'hu','Egy drón látszik a nagy kivetítőn.','Egy repülő látszik a nagy kivetítőn.','drón a képernyőn','drón a mező fölött','chill','none'),
(2814,'hu','Hátradől a felhők között.','Hátradől a tengerben.','hátradőlve egy faragott széken','hátradőlve a kanapén','chill','none'),
(2815,'hu','Készen áll a csatára.','Készen áll a lefekvésre.','csatára készen','tengeri csata','chill','none'),
(2817,'hu','A locsolókannán virágok vannak.','A teáskannán virágok vannak.','virágos locsolókanna','vízzel teli locsolókanna','chill','none'),
(2818,'hu','Pénz esik az égből!','Érmék esnek az égből!','pénzzel teli asztal','étellel teli asztal','dramatic','exaggeration'),
(2819,'hu','Aranyszínben izzanak a gyűrűi.','Zölden izzanak a gyűrűi.','izzó arany gyűrűk','izzó vörös szemek','chill','none'),
(2820,'hu','Megosztoznak egy könyvön.','Megosztoznak egy pizzán.','megosztozni egy könyvön','megosztozni egy padon','chill','none'),
(2823,'hu','Nulla szél: a víz mozdulatlan.','Nulla szél: a víz hullámos.','csónak mozdulatlan vízen','mozdulatlan éjszaka a városban','nerd','none'),
(2824,'hu','Az éjszakai klub most tele van.','Az éjszakai klub most üres.','neonfényes éjszakai klub','éjszakai klub kidobója','gossip','none'),
(2825,'hu','Könyvekkel van körülvéve!','Játékokkal van körülvéve!','könyvfalakkal körülvéve','játékfalakkal körülvéve','dramatic','exclamation'),
(2826,'hu','Jól áll neki a sárga szalag.','Jól áll neki a piros szalag.','sárga hajszalag','sárga ajándékszalag','flirt','none'),
(2827,'hu','Elbóbiskolt. A művészet fárasztó.','Elbóbiskolt. A matek fárasztó.','elbóbiskolni az asztalnál','elbóbiskolni a kanapén','gossip','bad_excuse'),
(2829,'hu','Egy könyvtárban böngészik.','Egy boltban böngészik.','könyvtári polcok böngészése','böngészés a neten','chill','none'),
(2831,'hu','Még a nap is vidám!','Még az eső is vidám!','vidám, mosolygó nap','vidám esős nap','low_iq','exclamation'),
(2833,'hu','Kiégés: gőzölög a feje.','Kiégés: gőzölög a teája.','kiégés az íróasztalnál','kiégés az edzőteremben','dramatic','exaggeration'),
(2837,'hu','Egy könyvesboltban van.','Egy játékboltban van.','zsúfolt könyvesbolt','könyvesbolti kávézópult','chill','none'),
(2838,'hu','Szivárványos csillám az arcán.','Fekete csillám az arcán.','szivárványos csillám az arcon','csillám egy képeslapon','chill','none'),
(2840,'hu','Egy egész város egyetlen tekercsen!','Egy egész erdő egyetlen tekercsen!','város egy tekercsen','tekercs egy palackban','gossip','exclamation'),
(2847,'hu','Tüdők, mint a fák. Mily költői.','Tüdők, mint a csillagok. Mily költői.','faágakra hasonlító tüdő','tüdő röntgenképen','ironic','none'),
(2850,'hu','Brutál nagy a dobszerkója!','Brutál nagy a gitárja!','nagy dobfelszerelés','egy kis játékdob','slang','exclamation'),
(2856,'hu','Mennyi légkondicionáló!','Mennyi virágláda!','légkondicionáló egységek','autós légkondicionáló','dramatic','exclamation'),
(2859,'hu','Egy barlangban meditál.','Egy tengerparton meditál.','barlangban meditálni','hegyen meditálni','chill','none'),
(2861,'hu','Találd ki, ki olvas könyvet?','Találd ki, ki olvas térképet?','olvasni a kanapén','olvasni az ágyban','gossip','none'),
(2867,'hu','Az a gömb tele van szikrákkal!','Az a gömb tele van vízzel!','óriási üveggömb','kőből készült gömb','dramatic','exclamation'),
(2877,'hu','Kötélen mászik fel.','Létrán mászik fel.','kötélen mászni','fára mászni','chill','none'),
(2887,'hu','A tűzijáték köszönti 2025-öt!','A tűzijáték köszönti 2024-et!','tűzijáték a háztetők fölött','tűzijáték a tenger fölött','dramatic','exclamation'),
(2890,'hu','Ma nincs rénszarvas, így a Mikulás síel.','Ma nincs rénszarvas, így a Mikulás gyalogol.','lesíelni a lejtőn','átsíelni a tavon','ironic','guessing'),
(2892,'hu','Csillagszórót tart.','Gyertyát tart.','égő csillagszóró a kézben','csillagszóró egy tortán','chill','none'),
(2894,'hu','A férfi egy bárányt visz.','A férfi egy kutyát visz.','fehér bárányt vinni','bárány az anyjával','chill','none'),
(2897,'hu','Hol a Mikulás? Itt hagyta a szánját.','Hol a Mikulás? Itt hagyta az autóját.','ajándékokkal teli szán','rénszarvasos szán','gossip','guessing'),
(2898,'hu','Egy szfinx őrzi a sivatagot.','Egy teve őrzi a sivatagot.','piramisok a sivatagban','sivatagi autós túra','dramatic','none'),
(2900,'hu','Egy óriási farkas néz vele szembe.','Egy óriási medve néz vele szembe.','óriási világító farkas','éjjel üvöltő farkasok','chill','none'),
(2906,'hu','Egy nagy dobozt visz.','Egy nagy növényt visz.','nagy dobozt vinni','babát vinni','chill','none'),
(2908,'hu','Egy óriási könyv lebeg.','Egy óriási lufi lebeg.','óriási lebegő könyv','mesebeli óriás','chill','none'),
(2909,'hu','A tudós imádja a lilát.','A tudós imádja a zöldet.','őrült tudós laborja','tudós a tévében','gossip','guessing'),
(2910,'hu','Mennyi könyv! Tele a könyvespolc!','Mennyi játék! Tele a könyvespolc!','színes könyvespolc','üres könyvespolc','low_iq','exclamation'),
(2914,'hu','Valaki magasra nyújtózik.','Valaki magasra ugrik.','felfelé nyújtózni','nyújtózni futás előtt','chill','none'),
(2915,'hu','A csapat virágot ültet.','A csapat virágot szed.','narancssárga virágokat ültetni','narancssárga virágokat szedni','business','none'),
(2925,'hu','Az a csőr hosszú. Nagyon hosszú.','Az a csőr rövid. Nagyon rövid.','hosszú hegyes csőr','rövid görbe csőr','low_iq','exaggeration'),
(2928,'hu','Egy űrhajó repül fölötte.','Egy nagy sárkány repül fölötte.','hatalmas halvány űrhajó','leszálló űrhajó a közelben','chill','none'),
(2937,'hu','Az űrhajós lebeg.','Az űrhajós fut.','űrhajós a mélyűrben','űrhajós a Holdon','chill','none'),
(2942,'hu','Van ott egy narancssárga bolygó.','Van ott egy zöld bolygó.','izzó narancssárga bolygó','gyűrűs bolygó','nerd','none'),
(2949,'hu','Egy űrhajós napfogyatkozást lát.','Egy űrhajós szivárványt lát.','napfogyatkozást nézni','holdfogyatkozás','nerd','none'),
(2950,'hu','Pillangók repülnek ki a rádióból!','Méhek repülnek ki a rádióból!','régi rádió','rádióállomás','dramatic','exclamation'),
(2951,'hu','Két kéz majdnem összeér!','Két láb majdnem összeér!','két majdnem összeérő kéz','két kéz kézfogás közben','dramatic','exclamation'),
(2952,'hu','Sárga köpeny = szuperhős. Egyszerű.','Piros köpeny = szuperhős. Egyszerű.','szuperhős fekete páncélban','szuperhős maszkban','low_iq','none'),
(2964,'hu','Csukott szemmel lélegzik.','Csukott szemmel alszik.','lélegzés a sötétben','rálehelni az ablakra','chill','none'),
(2967,'hu','Ennek az állatorvosnak full boldog a páciense!','Ennek az állatorvosnak full boldog a cicája!','állatorvos egy bulldoggal','állatorvos egy cicával','slang','exclamation'),
(2971,'hu','Rengeteg öntapadós cetli. Nagyon „szervezett”.','Rengeteg fotó. Nagyon „szervezett”.','öntapadós cetlik az ablakon','öntapadós cetlik a hűtőn','ironic','exaggeration'),
(2973,'hu','Valakinek most jött egy ötlete!','Valaki most ivott egy kávét!','ragyogó új ötlet','ötlet vacsorára','slang','exclamation'),
(2980,'hu','Egy hatalmas távcsövet használ.','Egy hatalmas fényképezőgépet használ.','hatalmas sárgaréz távcső','kis műanyag távcső','nerd','none'),
(2981,'hu','Ez a tornádó kódból van.','Ez a tornádó porból van.','kódból álló tornádó','tornádó egy farm fölött','nerd','none'),
(2987,'hu','Az aranyszínű robot „szerény”.','Az ezüstszínű robot „szerény”.','robot aranyszínű páncélban','arany jegygyűrű','ironic','understatement'),
(3003,'hu','A tömeg feltartja a kezét.','A tömeg leengedi a kezét.','feltartott kezű tömeg','tömeg a stadionban','chill','none'),
(3019,'hu','A lány ránk mosolyog.','A fiú ránk mosolyog.','a kamerába mosolyogni','egy kutyára mosolyogni','chill','none'),
(3022,'hu','A sakk egy kicsit nehéz.','A póker egy kicsit nehéz.','egy sakkjátszma','sakk-klub','ironic','understatement'),
(3024,'hu','Fogják egymás kezét.','Tapsolnak egymásnak.','hátulról fogni egymás kezét','fogni egymás kezét az asztalnál','flirt','none'),
(3027,'hu','Meggyógyítja az idős férfit.','Meggyógyítja a fiatal férfit.','idős férfi szemét meggyógyítani','fiatal férfi lábát meggyógyítani','chill','none'),
(3034,'hu','Egyedül tanul.','Egyedül alszik.','tanulás az osztályban','tanulás a könyvtárban','chill','none'),
(3035,'hu','A diákok dolgozatot írnak.','A diákok játszanak.','dolgozatot írni','jogsivizsga','chill','none'),
(3040,'hu','Ez a munkahalom beteg!','Ez a kajahalom beteg!','papírhalom','ruhahalom','slang','exclamation'),
(3041,'hu','Aggódónak tűnik az íróasztalánál.','Aggódónak tűnik az ágyában.','aggódó srác a munkahelyén','aggódás az időjárás miatt','chill','none'),
(3049,'hu','Van egy nagy kérdése.','Van egy nagy szendvicse.','kérdés egy szövegbuborékban','kérdés a dolgozatban','chill','none'),
(3052,'hu','Gondolkodik, nem dolgozik.','Alszik, nem dolgozik.','gondolkodás az iskolapadban','gondolkodás a konyhaasztalnál','slang','guessing'),
(3057,'hu','A parkban sétál.','A parkban fut.','sétálni egy ösvényen','sétálni a tengerparton','chill','none'),
(3059,'hu','Az északi fény nagyon ütős.','A tűzijáték nagyon ütős.','északi fény a hegyek fölött','északi fény egy város fölött','slang','none'),
(3061,'hu','Egy bakelitlemez fölött lebeg.','Egy zongora fölött lebeg.','pörgő bakelitlemez','törött bakelitlemez','chill','none'),
(3062,'hu','A DJ lemezeket kever.','A DJ lemezeket dedikál.','DJ a lemezjátszóknál','DJ a rádióban','slang','none'),
(3063,'hu','Zenét hallgat.','A kanapén hallgat valamit.','fejhallgatóval hallgatni','a tanárt hallgatni','chill','none'),
(3064,'hu','Kinyitja a függönyt!','Behúzza a függönyt!','a függöny kinyitása','a bejárati ajtó kinyitása','dramatic','exclamation'),
(3072,'hu','Várj. A macskák tudnak gereblyézni?','Várj. A kutyák tudnak gereblyézni?','őszi levelek gereblyézése','homok simára gereblyézése','low_iq','none'),
(3078,'hu','Úgy süti ki a tojást, mint egy profi.','Úgy süti ki a halat, mint egy profi.','tojást sütni serpenyőben','tojást főzni lábasban','slang','cliche'),
(3079,'hu','Bögréből iszik.','Üvegből iszik.','bögréből inni','üvegből inni','chill','none'),
(3082,'hu','A balerina egy lábujjon áll!','A balerina két lábon áll!','balerina egy lábujjhegyen','balerina a színpadon','dramatic','exclamation'),
(3087,'hu','Állateledelt önt.','Narancslét önt.','állateledelt önteni','forró teát önteni','business','none'),
(3089,'hu','Sütit sütött. Nekem?','Tortát sütött. Nekem?','frissen sütött csokis keksz','frissen sütött zsemle','flirt','guessing'),
(3090,'hu','Viszi a bevásárolt élelmiszert.','Viszi a szennyest.','egy szatyornyi élelmiszer','élelmiszer egy biciklin','chill','none'),
(3098,'hu','Két burger sül a barbecue-n.','Két steak sül a barbecue-n.','kerti barbecue','barbecue a tengerparton','chill','none'),
(3101,'hu','Brutál magasra ugrik!','Brutál gyorsan úszik!','kötelet átugrani','tóba ugrani','slang','exclamation'),
(3118,'hu','Lendíti a fejszéjét!','Lendíti az ütőjét!','fába vágott fejsze','fejsze a falon','dramatic','exclamation'),
(3119,'hu','A tündérnek arany szárnyai vannak.','A tündérnek fekete szárnyai vannak.','aranyszárnyú tündér','tündér varázspálcával','chill','none'),
(3122,'hu','Csak nyolc szelet pizza.','Csak hat szelet pizza.','nyolc szeletre vágott pizza','pizza dobozban','ironic','understatement'),
(3124,'hu','A hot dogon mustár van.','A hot dogon ketchup van.','mustáros hot dog','ketchupos hot dog','chill','none'),
(3125,'hu','Forró csokoládé tejszínhabbal!','Forró kávé tejszínhabbal!','egy bögre forró csokoládé','meleg csokoládétorta','dramatic','exclamation'),
(3126,'hu','A bokszoló halál komolynak tűnik.','A bokszoló halál álmosnak tűnik.','bokszoló piros kesztyűben','boxer kutyát sétáltatni','slang','none'),
(3127,'hu','Nagyon gyorsan fogja eldobni!','Nagyon gyorsan fogja elrúgni!','baseball-labdát dobni','eldobni a kesztyűt','dramatic','guessing'),
(3132,'hu','Bottal túrázik.','Kutyával túrázik.','túrázni a hegyekben','túrázni a tengerparton','chill','none'),
(3135,'hu','Megnyeri a futóversenyt!','Elveszíti a futóversenyt!','futóversenyt nyerni','úszóversenyt nyerni','dramatic','exclamation'),
(3136,'hu','Egy tóban úszik.','Egy medencében úszik.','tóban úszni','tengerben úszni','chill','none'),
(3141,'hu','A csoport megbeszélést tart.','A csoport bulit tart.','csoport körben','csoport sorban','business','none'),
(3143,'hu','Kékre festi az anyagot.','Pirosra festi az anyagot.','kékre festeni az anyagot','kékre festeni a hajat','chill','none'),
(3144,'hu','Anyagot sző.','Kosarat fon.','szövőszéken szőni','kosarat fonni','chill','none'),
(3145,'hu','Egy magas szövőszéken dolgozik.','Egy magas asztalnál dolgozik.','fa szövőszéken szőni','varrógépen varrni','chill','none'),
(3147,'hu','Kék kelme szárad egy kötélen a sikátor fölött.','Kék papír szárad egy kötélen a sikátor fölött.','kék kelme a kötélen','kelme asztalterítőnek','chill','none'),
(3148,'hu','Az asszonyok betakarítanak.','Az asszonyok táncolnak.','aranyló szárak betakarítása','almaszüret','chill','none'),
(3157,'hu','Egy piros téglát tart fel.','Egy piros sisakot tart fel.','félkész téglafal','téglaház a tengerparton','chill','none'),
(3158,'hu','A munkás acélt hegeszt.','A munkás acélt fest.','acéllemezt hegeszteni','törött biciklit hegeszteni','nerd','none'),
(3163,'hu','Kezet mos.','Arcot mos.','kezet mosni','edényt mosni','chill','none'),
(3164,'hu','Irány fogat mosni!','Irány hajat fésülni!','fogat mosni','hajat fésülni','dramatic','exclamation'),
(3171,'hu','Micsoda „segítőkész” útjelző tábla.','Micsoda „segítőkész” térkép.','régi fa útjelző tábla','régi fa kerítésoszlop','ironic','understatement'),
(3176,'hu','Egy fa alatt ül.','Egy fán ül.','ülni egy fa alatt','ülni egy ágon','chill','none'),
(3180,'hu','Egy lábon korcsolyázik!','Egy lábon síel!','tavon korcsolyázni','parkban korcsolyázni','dramatic','exclamation'),
(3188,'hu','Valaki egy szőnyegen imádkozik.','Valaki egy szőnyegen alszik.','szőnyegen imádkozni','templomban imádkozni','chill','none'),
(3191,'hu','A macska nem kérte, hogy megöleljék.','A kutya nem kérte, hogy megöleljék.','nagy macskát megölelni','nagy kutyát megölelni','chill','guessing'),
(3192,'hu','Csak a szemei látszanak.','Csak a szája látszik.','csak a szemek látszanak','álomban csukott szemek','business','none'),
(3194,'hu','A fogorvosnál fúró van. Segítség!','A fogorvosnál kés van. Segítség!','fogorvos fúróval','fogat mosó fogorvos','dramatic','exclamation'),
(3195,'hu','Még mindig dolgozik. Szegény srác.','Még mindig eszik. Szegény srác.','késő éjjel dolgozni','éjjel edzeni','slang','guessing'),
(3197,'hu','Teáról, könyvekről és zenéről ábrándozik.','Autókról, könyvekről és zenéről ábrándozik.','ábrándozni egy asztalnál','ábrándozni az ágyban','gossip','guessing'),
(3198,'hu','A tévéjük egy akvárium.','A tévéjük egy kandalló.','halak az akváriumban','hal a tányéron','ironic','understatement'),
(3199,'hu','Ez a kettős spirál a DNS.','Ez a kettős spirál egy kötél.','világító DNS-spirál','DNS-tesztkészlet','nerd','none'),
(3200,'hu','A levél középen van.','A telefon középen van.','kézzel írt levél','nyomtatott levél','chill','none'),
(3207,'hu','Kinek kell lámpa? A növény izzik.','Kinek kell lámpa? A könyv izzik.','izzó kis növény','izzó parázs','ironic','cheap_quality'),
(3216,'hu','Egymás mellett futnak.','Egymás mellett táncolnak.','egymás mellett futni','busz után futni','chill','none'),
(3222,'hu','Egy macska alszik, mint egy király.','Egy kutya alszik, mint egy király.','alvás egy fotelban','alvás egy kosárban','slang','cliche'),
(3235,'hu','Nézd, a koalánál rózsák vannak.','Nézd, a koalánál répák vannak.','rózsát tartó koala','leveleket evő koala','gossip','none'),
(3240,'hu','Ránk kiabál!','Nekünk énekel!','megafonba kiabálni','egy kutyára kiabálni','dramatic','exclamation'),
(3242,'hu','Popcorn az ágyban távirányítóval? Ezek a macskák vágják.','Pizza az ágyban távirányítóval? Ezek a macskák vágják.','popcorn az ágyban','popcorn a moziban','slang','cliche'),
(3243,'hu','A hálózat kéken világít.','A hálózat pirosan világít.','kéken izzó hálózat','tévéhálózat','chill','none'),
(3256,'hu','A zenekar szétszedi a klubot!','A zenekar szétszedi a strandot!','zenekar a színpadon','zenekar egy stadionban','slang','none'),
(3266,'hu','Az öböl mentén biciklizik.','A folyó mentén biciklizik.','biciklizni a tenger mentén','biciklizni a sínek mentén','chill','none'),
(3269,'hu','A tetőn lazít.','A tengerparton lazít.','lazítás nyugágyban','lazítani a kádban','chill','none'),
(3272,'hu','Tűsarok, aktatáska: igazi főnök!','Tűsarok, hátizsák: igazi főnök!','bőr aktatáskát vinni','pénzzel teli aktatáska','flirt','exclamation'),
(3274,'hu','Az asztalitenisz-ütő piros.','Az asztalitenisz-ütő fekete.','asztalitenisz-asztal','asztalitenisz a tévében','chill','none'),
(3277,'hu','A gyerek egy csillagot tart!','A gyerek egy lámpát tart!','izzó csillagot tartani','izzó lámpát tartani','dramatic','exclamation'),
(3278,'hu','A pár ölelkezik.','A pár táncol.','ölelkező pár','pár barát','flirt','none'),
(3281,'hu','A sárkány végzi az összes munkát.','A hajó végzi az összes munkát.','a sárkány húzza','sárkány a parkban','ironic','exaggeration'),
(3283,'hu','A sirály most már turista.','A galamb most már turista.','sirály a mólón','sirály egy hajón','chill','exaggeration'),
(3285,'hu','A jelmezén játék papagájok vannak!','A jelmezén játék kígyók vannak!','gyümölcsös fejdíszes jelmez','halloweeni jelmez','gossip','exclamation'),
(3288,'hu','Gólyalábon járnak.','Színpadon járnak.','magas gólyalábon járni','cölöpökre épült házak','chill','none'),
(3293,'hu','Ököllel ütött, magasra emelt kesztyűvel!','Ököllel ütött, mélyre engedett kesztyűvel!','ököllel ütni a ringben','ütni a boxzsákot','dramatic','exclamation'),
(3294,'hu','Mindjárt belerúg a labdába!','Mindjárt eldobja a labdát!','labdába rúgni készül','ajtót berúgni','dramatic','exclamation'),
(3301,'hu','Ő kormányozza a hajót.','Ő kormányozza az autót.','nagy hajót kormányozni','kis autót kormányozni','chill','none'),
(3303,'hu','Repül a papírrepülője!','Repül a sárkánya!','papírrepülőt dobni','papírrepülőt hajtogatni','dramatic','exclamation'),
(3306,'hu','A kakas uralja a világot.','A sas uralja a világot.','kakas egy földgömbön','kakas a kerítésen','dramatic','exaggeration'),
(3311,'hu','Egy alagútba sétál be.','Egy tóba sétál be.','sziklába vájt alagút','folyó alatti alagút','chill','none'),
(3313,'hu','Micsoda „zsúfolt” stadion.','Micsoda „zsúfolt” strand.','üres stadion','telt házas stadion','ironic','none'),
(3314,'hu','Fülhallgatóval kocog.','Kutyával kocog.','kocogás az úton','kocogás a tengerparton','chill','none'),
(3317,'hu','Az alpaka is rajta akar lenni a fotón.','A ló is rajta akar lenni a fotón.','kíváncsi barna alpaka','alvó barna alpaka','gossip','guessing'),
(3323,'hu','A vízilóbébi nagyon elfoglalt.','Az oroszlánkölyök nagyon elfoglalt.','pihenő vízilóbébi','úszó vízilóbébi','chill','understatement'),
(3325,'hu','Varázslat szikrázik egy régi könyvből!','Varázslat szikrázik egy régi bögréből!','varázslat egy régi könyvből','bűvészshow a színpadon','dramatic','exclamation'),
(3341,'hu','Az egyik srácnál arany trombita van.','Az egyik srácnál arany hegedű van.','arany trombita','trombitálás','chill','none'),
(3346,'hu','Két ember van egy könyvtárban.','Két ember van egy konyhában.','két ember a könyvtárban','könyvtári kártya','chill','none'),
(3357,'hu','Egy magas szék a háló mellett.','Egy magas létra a háló mellett.','háló a pálya közepén','halászháló','chill','none'),
(3362,'hu','Tesó, a mosómedve bámul.','Tesó, a macska bámul.','mosómedve egy párkányon','mosómedve a kukában','slang','none'),
(3368,'hu','A lajhár nem siet sehova.','A koala nem siet sehova.','mosolygó lajhár','alvó lajhár','chill','understatement'),
(3369,'hu','Egy kék virágot szagol.','Egy piros virágot szagol.','virágot szagolni','levest szagolni','chill','none'),
(3379,'hu','A labda felé fut.','A labda elől fut.','a labda felé futni','labda az égen','chill','none'),
(3382,'hu','Tesó, ez a papagáj egy kalóz.','Tesó, ez a papagáj egy séf.','szemkötős papagáj','papagáj kalitkában','slang','exaggeration'),
(3383,'hu','Egy csibe szörfözik a hullámon!','Egy kacsa szörfözik a hullámon!','szörföző csibe','csibe a tojásban','dramatic','exclamation'),
(3390,'hu','Rózsák között csókolják egymást.','Tengerparton csókolják egymást.','csókolózás a rózsakertben','csókolózás a hídon','flirt','none'),
(3392,'hu','A bagoly éjszakás műszakban van.','A bagoly nappalos műszakban van.','bagoly a hóban','repülő fehér bagoly','business','cliche'),
(3395,'hu','Köd takarja a hegyeket.','Köd takarja a várost.','sűrű köd a csúcsokon','köd a fürdőszobatükrön','chill','none'),
(3401,'hu','A közlekedési lámpán virágok vannak!','A közlekedési lámpán gyertyák vannak!','virágos közlekedési lámpa','elromlott közlekedési lámpa','low_iq','exclamation'),
(3406,'hu','Valaki egy tengeri szörnnyel merül!','Valaki egy cápával merül!','merülés egy zátony fölött','ugrás egy szikláról','dramatic','exaggeration'),
(3412,'hu','Piros ruhában emel súlyt!','Piros kabátban emel súlyt!','súlyzót emelni','bőröndöt emelni','dramatic','exclamation'),
(3418,'hu','Mindjárt megüti a dobokat.','Mindjárt megüti a gongot.','játszani a dobokon','cipelni a dobokat','chill','guessing'),
(3419,'hu','Trombitát fúj.','Sípot fúj.','arany trombitát fújni','arany trombitát tisztítani','chill','none'),
(3420,'hu','A nagybőgő magasabb nála.','A nagybőgő kisebb nála.','nagybőgőn játszani vonóval','nagybőgőt cipelni','nerd','none'),
(3422,'hu','Ő vezényli a zenekart.','Ő vezényli a kórust.','zenekart vezényelni','zenekarban játszani','business','none'),
(3423,'hu','Pengeti a hárfát.','Pengeti a gitárt.','magas hárfát pengetni','magas hárfát cipelni','chill','none'),
(3424,'hu','A karmesternél pálca van.','A karmesternél fuvola van.','frakkos karmester','karmester farmerben','business','none'),
(3428,'hu','Gyönyörűen játszik a hegedűn.','Gyönyörűen játszik a csellón.','hegedűn játszani','hegedűt hangolni','flirt','none'),
(3431,'hu','Klarinéton játszik.','Trombitán játszik.','klarinétba fújni','klarinétot tisztítani','chill','none'),
(3435,'hu','Két barlangbejárat a sziklafalban.','Két barlangbejárat a homokban.','tengeri barlang a sziklákban','denevérekkel teli barlang','chill','none'),
(3441,'hu','Görögdinnyéknek dől neki.','Tököknek dől neki.','egy láda görögdinnye','görögdinnyelé-árus','chill','none'),
(3447,'hu','Szobor a Tejút alatt.','Szobor a szivárvány alatt.','kőszobor éjjel','szobor a parkban','chill','none'),
(3458,'hu','Kőfejek a csillagok alatt.','Kőfejek a nap alatt.','csillagok kőfejek fölött','csillagok egy zászlón','chill','none'),
(3463,'hu','Kenuval evez.','Tutajjal evez.','kenuzás naplementében','kenucipelés naplementében','chill','none'),
(3469,'hu','A gepárd épp szünetet tart.','A gepárd épp fürdőt vesz.','gepárd naplementében','gyorsan futó gepárd','business','understatement'),
(3470,'hu','Egyetlen hatalmas narancssárga dűne.','Egyetlen hatalmas fehér dűne.','dűne ívelt gerince','dűne a tenger mellett','chill','none'),
(3472,'hu','Csodás ruha! Pörög benne.','Csodás kalap! Pörög benne.','pörgés piros ruhában','pörgés kék ruhában','flirt','none'),
(3473,'hu','A flamingó a vízben van.','A flamingó egy fán van.','flamingó a vízben','repülő flamingó','chill','none'),
(3479,'hu','Rózsaszín kézitáska, csendes kávézó.','Rózsaszín laptop, csendes kávézó.','kézitáska az asztalon','kézitáska egy boltban','chill','none'),
(3482,'hu','A lépcsőfokokon chillel.','A lépcsőfokokon alszik.','napos kő lépcsőfokok','tánclépések','slang','none'),
(3485,'hu','Megérinti az elefántot.','Megérinti a tigrist.','megérinteni egy elefántot','megérinteni egy fatörzset','chill','none'),
(3486,'hu','Kókuszdióból iszik.','Üvegből iszik.','kókuszdió szívószállal','kókuszdió feltörése','chill','none'),
(3489,'hu','Bor egy csónakban? Nevet.','Bor egy autóban? Nevet.','nevetni egy csónakban','kinevetni egy csónakot','gossip','guessing'),
(3493,'hu','Lábnyomokat hagy maga után.','Virágokat hagy maga után.','lábnyomok sora','lábnyomok a hóban','chill','none'),
(3494,'hu','A nő a nap felé nyújtózik.','A férfi a nap felé nyújtózik.','két karral felfelé nyújtózni','gumiszalagot nyújtani','chill','none'),
(3497,'hu','A naplementébe sétál. Klasszikus.','A tengerbe sétál. Klasszikus.','besétálni a naplementébe','naplemente nézése autóból','ironic','cliche'),
(3513,'hu','A menyasszony fátyla nagyon hosszú.','A menyasszony fátyla nagyon sötét.','menyasszony hosszú fátyla','menyasszony csokorral','gossip','none'),
(3516,'hu','A vázában egy szál virág van.','A vázában tíz szál virág van.','váza a polcon','váza az asztalon','chill','none'),
(3519,'hu','Az a fehér fülbevaló gyönyörű.','Az a fehér nyaklánc gyönyörű.','fehér csepp alakú fülbevaló','fülbevaló a padlón','flirt','none'),
(3522,'hu','Tény: ez a medúza világít.','Tény: ez a tengeri csillag világít.','világító medúza','medúza a parton','nerd','cliche'),
(3541,'hu','Magas vízesés, pici tó.','Magas vízesés, pici csónak.','sziklafalról zúduló vízesés','vízesés egy kertben','chill','none'),
(3548,'hu','Szmokingban dohányzik.','Estélyiben dohányzik.','cigarettával dohányozni','pipázni','chill','none'),
(3552,'hu','Japán tavasszal, háttérben a Fuji.','Japán télen, háttérben a Fuji.','tavaszi utcácska Japánban','útikönyv Japánról','chill','none'),
(3556,'hu','A lámák kiöltöztek a fotóhoz.','A kecskék kiöltöztek a fotóhoz.','lámák takarókkal','lámák a hóban','gossip','guessing'),
(3559,'hu','Pici sziget, nulla szomszéd.','Pici sziget, nulla kaktusz.','pici sziklás sziget','sziget szállodával','ironic','understatement'),
(3561,'hu','A szamár szállít házhoz.','A ló szállít házhoz.','megrakott szamarat vezetni','megrakott szamáron lovagolni','business','none'),
(3562,'hu','Az ókori Egyiptom a Nílus partján.','Az ókori Egyiptom a hóban.','ókori Egyiptom a Nílusnál','nyaralós fotó Egyiptomban','chill','none'),
(3564,'hu','A rénszarvasok a hóban vannak.','A rénszarvasok a tengerparton vannak.','rénszarvasok a hóban','szánt húzó rénszarvasok','chill','none'),
(3567,'hu','Vörös nap függ Peru fölött.','Sárga nap függ Peru fölött.','Peru romjai','Peru zászlaja','chill','none'),
(3572,'hu','Az asszonyok teát szednek.','Az asszonyok almát szednek.','tealevelet szedni','virágot szedni','chill','none'),
(3585,'hu','Az egyik zebra épp ebédel.','Az egyik zebra épp fürdik.','zebrák egy dombon','zebrák a folyóban','business','none'),
(3586,'hu','A teknős siet.','A rák siet.','óriásteknős','vízben úszó teknős','ironic','exaggeration'),
(3589,'hu','A gorilla csak chillel.','A gorilla csak eszik.','gorilla a bambusz között','mellét döngető gorilla','slang','none'),
(3590,'hu','Egy strucc sétál a homokon.','Egy teve sétál a homokon.','strucc a sivatagban','fejét homokba dugó strucc','chill','none'),
(3592,'hu','Mindketten keményen edzenek.','Mindketten keményen táncolnak.','együtt edzeni','kutyát idomítani','business','none'),
(3598,'hu','A göndör haja kék tollal van rajzolva.','A göndör haja piros tollal van rajzolva.','göndör haj kék tollal','göndör haj piros festékkel','chill','none'),
(3619,'hu','Egy sas van a folyó fölött.','Egy sas van a város fölött.','sas a folyó fölött','sas a hegyek fölött','chill','none'),
(3629,'hu','Úgy fognak kezet, mint a Star Warsban!','Úgy harcolnak, mint a Star Warsban!','kezet fogni egy földönkívülivel','kezet fogni egy robottal','dramatic','exclamation'),
(3633,'hu','Lebegés az űrben? Nem, egy medencében.','Lebegés az űrben? Nem, egy tóban.','a hátán lebegni','lebegni a nyílt űrben','ironic','none'),
(3638,'hu','Űrmeló: felmosni a padlót.','Űrmeló: kifesteni a padlót.','fényes padlót felmosni','kiömlött kávét felmosni','ironic','understatement'),
(3639,'hu','A legjobb hely az űrben: egy piros bárszék.','A legjobb hely az űrben: egy kék bárszék.','piros bárszéken ülni','bárszék a fürdőszobában','ironic','exaggeration'),
(3640,'hu','A lámpa ragyog az űrben.','A lámpa egy hajóra ragyog.','az űrbe ragyogó fénysugár','fény egy hajón','chill','none'),
(3641,'hu','Még ezen a bolygón is van automata!','Még ezen a bolygón is van kávézó!','kivilágított automata','elromlott automata','ironic','exclamation'),
(3642,'hu','Egy bolygót húz!','Egy rakétát húz!','zsinórt húzni','fogat húzni','dramatic','exaggeration'),
(3644,'hu','Egy pici növényt öntöz.','Egy magas fát öntöz.','pici palántát öntözni','nagy kertet öntözni','chill','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
