begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(3645,'hu','Messze otthonról, családi fénykép az asztalán.','Messze otthonról, családi kutya az asztalán.','családi fénykép az űrben','családi fényképalbum','dramatic','none'),
(3653,'hu','Megjavítja a Holdat!','Megjavítja a Napot!','megjavítja a törött Holdat','defektes gumit javít','dramatic','exaggeration'),
(3658,'hu','Olyan szeles az idő, hogy a fa feladta.','Olyan esős az idő, hogy a fa feladta.','szeles nap Patagóniában','szeles idő a tengeren','ironic','exaggeration'),
(3663,'hu','A láma téged stíröl.','A kecske téged stíröl.','láma a hegygerincen','láma az istállóban','slang','guessing'),
(3671,'hu','Szélesre széttárja a karját.','Keresztbe fonja a karját.','széttárt karok','keresztbe tett karok','chill','none'),
(3673,'hu','Hat hőlégballon van fent.','Két hőlégballon van fent.','hőlégballonok napfelkeltekor','hőlégballonok éjszaka','chill','none'),
(3676,'hu','Kilátás az öbölre, naplementével együtt.','Kilátás az öbölre, hóval együtt.','türkizkék, íves öböl','hajókkal teli öböl','business','cliche'),
(3685,'hu','Mennyi hőlégballon!','Mennyi helikopter!','hőlégballonok sziklák felett','hőlégballonok a tenger felett','dramatic','exclamation'),
(3706,'hu','A hullámvasút mindenkit megrémít!','Az óriáskerék mindenkit megrémít!','család a hullámvasúton','család a hullámvasút mellett','dramatic','exaggeration'),
(3709,'hu','A séf megkóstolja a levest.','A séf megkóstolja a salátát.','megkóstolja a levest','megkóstolja a bort','chill','none'),
(3718,'hu','Kapucnis pulóver, bomberdzseki, napszemcsi: menő.','Kapucnis pulóver, bomberdzseki, sapka: menő.','kapucnis pulóver bomber alatt','felhúzza a kapucnit','slang','none'),
(3724,'hu','A nő ruhája élénk színű.','A nő ruhája fekete.','élénk színekbe öltözött nő','sötét színekbe öltözött nő','chill','none'),
(3733,'hu','A skorpió farka fel van emelve.','A skorpió farka le van eresztve.','a skorpió felkunkorodó farka','skorpió egy kő alatt','chill','none'),
(3734,'hu','Az a szarv nagyon nagy. Hű.','Az a szarv nagyon kicsi. Hű.','hatalmas csavart szarv','kürtöt fúj','low_iq','exaggeration'),
(3735,'hu','Nézd, a szurikáta mosolyog!','Nézd, a szurikáta sír!','felágaskodó szurikáta','lyukat ásó szurikáta','gossip','none'),
(3740,'hu','Van nála egy úszógumi.','Van nála egy szörfdeszka.','fut egy úszógumival','ül egy úszógumiban','chill','none'),
(3741,'hu','Ezek a tulipánok durván narancssárgák.','Ezek a tulipánok durván lilák.','négy narancssárga tulipán','tulipánok a kertben','slang','none'),
(3747,'hu','A kiskutyán millió folt van!','A macskán millió folt van!','fekete foltok fehér bundán','folt az ingen','dramatic','exaggeration'),
(3750,'hu','Egy egyszarvú a tavacskánál.','Egy sárkány a tavacskánál.','csendes erdei tavacska','kacsákkal teli tavacska','chill','none'),
(3767,'hu','Ezek a szurkolók még ki is takarítanak!','Ezek a játékosok még ki is takarítanak!','kitakarítani a lelátót','kitakarítani a szobádat','gossip','exclamation'),
(3770,'hu','A varjú jobbra néz.','A varjú balra néz.','fényes fekete varjú','repülő varjú','chill','none'),
(3772,'hu','Ez a sárkány jégből van!','Ez a sárkány tűzből van!','egy jégsárkány feje','tüzet okádó sárkány','dramatic','exclamation'),
(3777,'hu','Lángolnak a szárnyai!','Vízben vannak a szárnyai!','szélesre tárt szárnyak','szorosan összecsukott szárnyak','dramatic','exclamation'),
(3779,'hu','A szegény játék egészen egyedül van.','A szegény kutya egészen egyedül van.','régi játéknyuszi','régi játékautó','dramatic','exaggeration'),
(3797,'hu','Kézállás a vízben!','Kézállás a hóban!','kézállás sekély vízben','kézállás a strandon','slang','none'),
(3803,'hu','Egy sárkány öleli a tornyot!','Egy kígyó öleli a tornyot!','sárkány a torony körül','magas víztorony','dramatic','exaggeration'),
(3806,'hu','Két cseresznye van az italban.','Három cseresznye van az italban.','két cseresznye egy száron','egy tál cseresznye','chill','none'),
(3809,'hu','Egy mentőöv majd segít!','Egy mentőmellény majd segít!','felnyúl segítségért','segíteni a leckében','dramatic','exclamation'),
(3813,'hu','Végignéz az ösvényen.','Végignéz a folyón.','színesre festett ösvény','sáros erdei ösvény','chill','none'),
(3825,'hu','A világűrből a Föld aprónak látszik.','A világűrből a Mars aprónak látszik.','a Föld a világűrből nézve','egy parkolóhely','chill','none'),
(3827,'hu','Egy szörny van közvetlenül mögötte!','Egy sárkány van közvetlenül mögötte!','szörny a fiú mögött','szörny az ágy alatt','dramatic','exclamation'),
(3828,'hu','A csimpánz és a gyufa: rossz ötlet.','A csimpánz és a kés: rossz ötlet.','égő gyufa a kézben','focimeccs a tévében','chill','guessing'),
(3832,'hu','Durran a tűzijáték!','Durrannak a lufik!','tűzijáték az éjszakai égen','tűzijáték a boltban','dramatic','exclamation'),
(3841,'hu','Repkednek a ruhák!','Repkednek a cipők!','levegőben lebegő ruhák','ruhák a mosógépben','dramatic','exclamation'),
(3842,'hu','Kidob egy poharat.','Kidob egy táskát.','kidobni egy poharat','eldobni egy labdát','business','none'),
(4001,'hu','Ez a vadászgép pirítóst csinál!','Ez a vadászgép kávét csinál!','kenyérpirító-vadászgép','harcos a bokszringben','slang','exclamation'),
(4002,'hu','Kézállás az asztalon? Szép egyensúly!','Kézállás a kanapén? Szép egyensúly!','egyensúly egy asztalon','elveszti az egyensúlyát a jégen','gossip','exclamation'),
(4003,'hu','Két pár szörnyes papucs.','Két pár szörnyes csizma.','egy pár sárga papucs','egy pár sárga kesztyű','chill','none'),
(4004,'hu','A vadászgép kenyeret melegít. Teljesen normális.','A vadászgép levest melegít. Teljesen normális.','kenyeret melegít egy vadászgépben','levest melegít a tűzhelyen','ironic','understatement'),
(4005,'hu','Fagyott fal? Nem probléma.','Sziklafal? Nem probléma.','fagyott falat mászik','fagyott tó korcsolyázáshoz','ironic','understatement'),
(4006,'hu','A víz átlátszó.','A víz sötétzöld.','átlátszó tóvíz','átlátszó nejlonzacskó','chill','none'),
(4007,'hu','Beugrott a sötétségbe, tesó.','Beugrott a medencébe, tesó.','szaltó a sötétségben','fél a sötétségtől','slang','none'),
(4009,'hu','A kacsák sorban vonulnak, mint egy osztálykiránduláson.','A tyúkok sorban vonulnak, mint egy osztálykiránduláson.','kacsák hosszú sorban','kacsák egy kis tóban','chill','exaggeration'),
(4010,'hu','Úgy mászik, mint egy profi!','Úgy úszik, mint egy profi!','fehér sziklafalon mászni','létrán mászni','flirt','cliche'),
(4011,'hu','A pandák a közönsége!','A majmok a közönsége!','pandákból álló közönség','gyerekekből álló közönség','dramatic','exclamation'),
(4013,'hu','Egy jéghegy úszik el a fedélzet mellett. Titanic-hangulat!','Egy bálna úszik el a fedélzet mellett. Titanic-hangulat!','bakancs a fa fedélzeten','egy pakli kártya','slang','exclamation'),
(4014,'hu','A bőrönd csak gurul tovább.','A bicikli csak gurul tovább.','gurul egy parkolón át','gurul lefelé a dombon','chill','none'),
(4015,'hu','A birkák a partra ugrálnak!','A kecskék a partra ugrálnak!','birkák a folyóparton','birkák egy bank előtt','dramatic','exclamation'),
(4016,'hu','A macska nemet mond a fürdőkádra.','A kutya nemet mond a fürdőkádra.','macska a fürdőkád szélén','macska a fürdőkádban','low_iq','guessing'),
(4017,'hu','Világít a piros lámpás.','Világít a kék lámpás.','világító papírlámpás','világító utcai lámpa','chill','none'),
(4018,'hu','Két kutya ül egy robogón!','Két macska ül egy robogón!','kutyák egy zöld robogón','kutyák egy zöld biciklin','dramatic','exclamation'),
(4019,'hu','Ennél a kiskutyánál van a legjobb karika.','Ennél a kiscicánál van a legjobb karika.','rózsaszín úszókarika','gyémántgyűrű','slang','exaggeration'),
(4020,'hu','A kutya egy békát figyel.','A kutya egy halat figyel.','figyelni a békát','figyelni a tévét','chill','none'),
(4021,'hu','Vágjuk a tortát? Én vagyok az első!','Vágjuk a kenyeret? Én vagyok az első!','kockákra vágni a tortát','félbevágni a tortát','slang','guessing'),
(4022,'hu','Csak egy kis séta egy éppen repülő gépen.','Csak egy kis séta egy éppen haladó vonaton.','repülni egy város felett','repülni a tenger felett','ironic','understatement'),
(4023,'hu','Jól szórakoznak egy hajón.','Jól szórakoznak egy buszon.','szórakozás a folyón','szórakozás a strandon','chill','none'),
(4024,'hu','Az egész farm követi a férfit!','Az egész farm követi a nőt!','férfit követő állatok','kutyát követő állatok','dramatic','exaggeration'),
(4025,'hu','Tesó, a kiscica kergeti.','Tesó, a kiskutya kergeti.','zöld labdát kerget','zöld madarat kerget','slang','none'),
(4026,'hu','A víz sima, mint az üveg.','Az út sima, mint az üveg.','siklás a sima vízen','sima landolás','chill','cliche'),
(4027,'hu','Ki ette meg a pitét? A tehén?','Ki ette meg a pitét? A kutya?','aranybarna almás pite','tortadiagram a melóban','gossip','blaming_someone'),
(4028,'hu','A bulldog úgy fordul, mint egy profi!','A bulldog úgy ugrik, mint egy profi!','fordulni gördeszkán','bekapcsolni a tévét','slang','exaggeration'),
(4030,'hu','Úszott egyet a parkban.','Szunyókált egyet a parkban.','tó egy parkban','gördeszkapark','ironic','understatement'),
(4031,'hu','A labda pont a legfelső helyre landolt!','A labda pont őrá landolt!','a halom legfelső eleme','a legfelső polc','dramatic','exclamation'),
(4032,'hu','Micsoda zöld rendetlenség!','Micsoda piros rendetlenség!','zöld slime-os rendetlenség','rendetlen hálószobapadló','gossip','exaggeration'),
(4033,'hu','Első próba golfütővel!','Első próba hokiütővel!','golfütőt lendít','golfklub tagoknak','dramatic','exclamation'),
(4034,'hu','Mezítláb, rengeteg csapda. Szuper.','Nagy bakancsban, rengeteg csapda. Szuper.','több tucat egércsapda','medvecsapda','ironic','understatement'),
(4035,'hu','Átlép a víz fölött.','Átlép a tűz fölött.','úszó kockákra lép','mozgó vonatra lép','chill','none'),
(4036,'hu','Nagy mosoly a kamerának!','Nagy mosoly a kutyának!','mosoly a fotóhoz','mosoly a fogorvosnak','dramatic','exclamation'),
(4038,'hu','Totál szeretik egymást.','Totál utálják egymást.','szeretik egymást','szeretik a gyors autókat','gossip','guessing'),
(4039,'hu','Kúszott, de a banda nyert.','Futott, de a banda nyert.','kúszás kézen és lábujjhegyen','kúszás az ágy alatt','gossip','blaming_someone'),
(4041,'hu','A lány ránézett a srácra. Mindent megvettek.','A lány ránézett a srácra. Semmit sem vettek.','vásárlás egy nagy plázában','kaját vesz a piacon','gossip','banter'),
(4042,'hu','Egy bolt előtt állnak.','Egy boltban állnak.','kivilágított bolt előtt','kókuszdiókkal teli bolt','chill','none'),
(4043,'hu','Bazsarózsával lepte meg a lányt.','Gyűrűvel lepte meg a lányt.','virággal lepi meg','meglepetés szülinapi buli','gossip','none'),
(4044,'hu','Golfot gyakorol.','Teniszt gyakorol.','éjszaka gyakorolni','zongorán gyakorolni','chill','none'),
(4045,'hu','Megtalálta a telefonját!','Megtalálta a pénztárcáját!','elveszett telefon megtalálása','elveszett kutya megtalálása','dramatic','exclamation'),
(4046,'hu','Visszautasítja. Ez a végső válasza.','Beleegyezik. Ez a végső válasza.','ujjával utasítja vissza','visszautasítja a vacsorát','ironic','cliche'),
(4047,'hu','Tökéletes nyaralás, de a telefonja még mindig a kezében.','Tökéletes nyaralás, de a könyve még mindig a kezében.','nyaralás a tengerparton','nyaralás a hóban','ironic','banter'),
(4048,'hu','Zuhanyt szereltek fel egy furgonba!','Kádat szereltek fel egy furgonba!','napelemek felszerelése','új app telepítése','gossip','exclamation'),
(4049,'hu','Micsoda teher a vállán!','Micsoda teher a biciklijén!','hatalmas terhet cipel','egy rakás téglát cipel','dramatic','exclamation'),
(4050,'hu','A barátoknak van egy kutyájuk.','A barátoknak van egy macskájuk.','barátok a tűz mellett','barátok egy bárban','chill','none'),
(4051,'hu','Egy teherautó motorkerékpárt szállít.','Egy teherautó biciklit szállít.','elektromos motorkerékpár','motorkerékpáros bukósisak','chill','none'),
(4052,'hu','Már megint felveszik. Tizedik próba?','Már megint táncolnak. Tizedik próba?','telefonnal felvenni','felvenni egy dalt','gossip','guessing'),
(4053,'hu','Még a kukorica is torta!','Még a répa is torta!','kukorica formájú torta','kukoricaföld naplementekor','dramatic','exclamation'),
(4054,'hu','A kutya késő estig dolgozik a billentyűzeten. Jön az előléptetés?','A macska késő estig dolgozik a billentyűzeten. Jön az előléptetés?','mancsok a billentyűzeten','zongora billentyűzete','gossip','guessing'),
(4055,'hu','Dinoszauruszok? A husky nemet mond!','Dinoszauruszok? A macska nemet mond!','egy kutya és két dinoszaurusz','egy kutya és két macska','slang','exclamation'),
(4056,'hu','Micsoda habos ünneplés!','Micsoda csendes ünneplés!','pezsgős ünneplés','születésnapi ünneplés','dramatic','exclamation'),
(4057,'hu','Mindene csupa kóla!','Mindene csupa víz!','egy üveg kóla','egy pohár kóla','dramatic','exclamation'),
(4058,'hu','Egyéjszakás utazás, tíz bőrönd!','Egyéjszakás utazás, két bőrönd!','pakolás egy rövid utazásra','elbotlik egy bőröndben','dramatic','banter'),
(4059,'hu','Egy banánnal nem lehet három páviánt etetni.','Egy banánnal nem lehet három zebrát etetni.','a páviánok etetése','a kacsák etetése','ironic','understatement'),
(4060,'hu','Szép áramlás, de az egy vízesés!','Szép áramlás, de az egy híd!','a folyó áramlása','a forgalom áramlása','dramatic','exclamation'),
(4061,'hu','Nézd annak a cápának az állkapcsát!','Nézd annak a bálnának az állkapcsát!','fogakkal teli állkapocs','fogatlan állkapocs','dramatic','exclamation'),
(4062,'hu','A tesó megmarkolja a kite kormányrúdját.','A tesó megmarkolja a hajó korlátját.','megmarkolja a kite rúdját','megmarkolja a kormánykereket','slang','none'),
(4063,'hu','A hevederek elengedték!','A repülő elengedte!','elengedve a felhők közé','madarat enged el','dramatic','exclamation'),
(4064,'hu','A fészek egy rúd tetején van.','A fészek egy fa tetején van.','fészek egy rúdon','zászló egy rúdon','chill','none'),
(4065,'hu','A sofőr egy kutya. Kérjük, csatolják be a biztonsági övüket.','A sofőr egy macska. Kérjük, csatolják be a biztonsági övüket.','kutya mint sofőr','kutya mint utas','business','cliche'),
(4066,'hu','Egy papagáj száguld a vörös földön. Legenda.','Egy papagáj száguld a nedves homokon. Legenda.','vörös földút','föld a fehér ingen','slang','exaggeration'),
(4067,'hu','A tó tükrözi a fákat.','A tó tükrözi a várost.','a fákat tükröző tó','tükrözni a táncmozdulatait','chill','none'),
(4068,'hu','Egy cápát simogat!','Egy delfint simogat!','cápa hátát simogatja','cápa hátán lovagol','dramatic','exclamation'),
(4069,'hu','A csibe egy rudat tart.','A galamb egy rudat tart.','vékony horgászrúd','rudat tartó galamb','chill','none'),
(4070,'hu','Két ejtőernyős van a szárnyon!','Két ejtőernyős van a gép farkán!','lóg a szárny alatt','ül a szárnyon','dramatic','exclamation'),
(4071,'hu','Leugrik egy roncsról!','Leugrik egy hídról!','beugrik a tengerbe','beugrik a medencébe','dramatic','exclamation'),
(4072,'hu','Három nő, titkos lagúna.','Három férfi, titkos lagúna.','türkizkék lagúna','hajókkal teli lagúna','gossip','none'),
(4073,'hu','Dráma: a tyúknál bot van.','Dráma: a tyúknál kanál van.','fabotot lenget','fabotot dob','gossip','none'),
(4074,'hu','A nap mögötte van.','A hold mögötte van.','a nap egy lagúna felett','a nap egy város felett','chill','none'),
(4075,'hu','Körös-körül cápák: veszély? Milyen veszély?','Körös-körül delfinek: veszély? Milyen veszély?','veszély körülötte mindenütt','veszély az úton','dramatic','understatement'),
(4076,'hu','Kiugranak az ajtón!','Kiugranak az ablakon!','nyitott helikopterajtó','nyitott autóajtó','dramatic','exclamation'),
(4077,'hu','Az egyik galamb még alvó üzemmódban van.','Mindkét galamb még alvó üzemmódban van.','alvó galamb a fészekben','alvó galamb a padon','chill','none'),
(4078,'hu','Hét párna egyetlen embernek!','Hét takaró egyetlen embernek!','fehér párnák sora','fehér törölközők halma','gossip','exclamation'),
(4079,'hu','Rohan a folyó. Durva!','Rohannak az autók. Durva!','rohan lefelé a folyón','rohan a reptérre','slang','exaggeration'),
(4080,'hu','A hajgumik a csuklóján voltak!','A hajgumik a fiókban voltak!','hajgumik a csuklóján','óra a csuklóján','dramatic','exclamation'),
(4081,'hu','Lábak kilógatva egy helikopterből a csúcsok felett. Kösz, nem.','Lábak kilógatva egy repülőből a csúcsok felett. Kösz, nem.','havas csúcsok felülről','csúcs egy kereszttel','slang','guessing'),
(4082,'hu','A lány fejjel lefelé lóg.','A fiú fejjel lefelé lóg.','fejjel lefelé lógni','fejjel lefelé fordítani a gépet','chill','none'),
(4083,'hu','Egy „kicsi” mopsz elfoglalta a közepét.','Egy „kicsi” macska elfoglalta a közepét.','az ágy közepe','a kanapé közepe','ironic','understatement'),
(4084,'hu','Haj nő a fején!','Haj nő az állán!','haj a kopasz fejen','egy fej saláta','dramatic','exclamation'),
(4085,'hu','A lány teljesen megváltoztatta a fiút.','A fiú teljesen megváltoztatta a lányt.','átöltözik öltönybe','autógumit cserél','gossip','exaggeration'),
(4087,'hu','A macskák nagyon komolyan veszik a munkájukat.','A kutyák nagyon komolyan veszik a munkájukat.','öltönyös macskák munkában','öltönyös macskák az iskolában','business','understatement'),
(4088,'hu','Ez a vízesés tényleg széles. Ne menj közelebb.','Ez a híd tényleg széles. Ne menj közelebb.','széles vízesés pereme','széles folyami híd','dramatic','guessing'),
(4089,'hu','A polipok táncolnak!','A rákok táncolnak!','klubban táncoló polipok','homokban rejtőző polipok','dramatic','exclamation'),
(4090,'hu','A rakéta gyorsan emelkedik!','A repülő gyorsan emelkedik!','gyorsan emelkedő rakéta','hajnalban felkelő nap','dramatic','exclamation'),
(4091,'hu','A lány alatt megreped a jég!','A fiú alatt megreped a jég!','a lába alatt repedő jég','tojást tör a jégen','dramatic','exclamation'),
(4092,'hu','Lebiciklizik a lépcsőn!','Felbiciklizik a lépcsőn!','le a sziklalépcsőn','le a sípályán','dramatic','exclamation'),
(4093,'hu','Hű, a hold olyan kerek.','Hű, a hold olyan piros.','kerek szürke hold','kerek évforduló','low_iq','none'),
(4095,'hu','Egy apró kamera forgatta ezt a filmet!','Egy hatalmas kamera forgatta ezt a filmet!','filmet forgat','filmszínház','dramatic','exclamation'),
(4096,'hu','A teknős szabad, és még csak meg sem köszöni.','A cápa szabad, és még csak meg sem köszöni.','szabadon engedett teknős','teknős ingyen','chill','guessing'),
(4097,'hu','Brutál gyorsan teker.','Brutál lassan teker.','gyorsan lefelé tekerni','böjtölni vacsora előtt','slang','exaggeration'),
(4098,'hu','Két tehén elállja az utat. Bunkók.','Két birka elállja az utat. Bunkók.','tehenek az útban','az út a strandra','ironic','blaming_someone'),
(4099,'hu','A kutya visszamászott a tetejére!','A macska visszamászott a tetejére!','vissza a matracokra','vissza a kanapéra','dramatic','exclamation'),
(4100,'hu','Azt a lyukat a rugó csinálta, nem én!','Azt a lyukat a macska csinálta, nem én!','lyuk a plafonon','lyuk a zokniján','low_iq','blaming_someone'),
(4102,'hu','Hívja a napsütés!','Hívja az eső!','napsütés az ablak előtt','napsütés az irodában','dramatic','exaggeration'),
(4103,'hu','A kiskutya türelme elfogyott.','A kiscica türelme elfogyott.','egy kiskutya türelme','türelem egy kiscicával','ironic','cliche'),
(4104,'hu','Egy csók, és olyan, mint egy paradicsom.','Egy csók, és olyan, mint egy szellem.','csók az arcra','csók a kézre','low_iq','exaggeration'),
(4105,'hu','A barátja virágot hozott.','A barátja tortát hozott.','a barátja virággal','a barátja gyűrűvel','flirt','none'),
(4106,'hu','Az éhes kutya ellopja.','Az éhes macska ellopja.','éhes kiskutya','egyedül evő éhes férfi','gossip','blaming_someone'),
(4108,'hu','Az autója szerint ő a férje.','Az autója szerint ő a bátyja.','férj egy autóban','autót mosó férj','gossip','none'),
(4109,'hu','Két kutya chillel a pázsiton.','Két macska chillel a pázsiton.','kutyák a zöld pázsiton','fűnyírás a pázsiton','slang','none'),
(4110,'hu','A bohóc nem számított tigrisre!','A bohóc nem számított oroszlánra!','a bohóc narancssárga parókája','a bohóc lila parókája','dramatic','guessing'),
(4111,'hu','A kos az idegesítő munkatársa.','A kutya az idegesítő munkatársa.','idegesítő kos','idegesítő légy','business','exaggeration'),
(4112,'hu','Egy szép lyuk a tömbben.','Egy szép lyuk az ajtóban.','fúrás egy tömbbe','egy tömb sajt','chill','none'),
(4113,'hu','Ékszerdráma az utcán!','Ékszerdráma a boltban!','rózsaszín ékszer egy galambon','rózsaszín ékszer egy kirakatban','gossip','exclamation'),
(4114,'hu','A bevásárlóközpont szabálya: a lány vásárol, a fiú cipel.','A bevásárlóközpont szabálya: a fiú vásárol, a lány cipel.','szatyrok a bevásárlóközpontból','a bevásárlóközpont parkolója','gossip','banter'),
(4115,'hu','Két turista jól szórakozik. Cukik!','Két turista ebédel. Cukik!','turisták éjszaka','turisták egy buszon','gossip','exclamation'),
(4116,'hu','Olyan kicsi az autója!','Olyan nagy az autója!','kicsi piros buborékautó','kicsi piros csónak','dramatic','exclamation'),
(4117,'hu','Csak egy kis keresés.','Csak egy kis szunyókálás.','keresés egy telefon után','keresés egy kutya után','chill','understatement'),
(4118,'hu','Ez a pálya hegyi panorámát kínál.','Ez a pálya gyönyörű tengeri panorámát kínál.','pálya a hegyek között','pálya a tenger mellett','business','none'),
(4119,'hu','A kőember összeomlott. RIP.','A kőkutya összeomlott. RIP.','összeomló kőalak','összeomló kőhíd','slang','none'),
(4120,'hu','Deszka diótöréshez.','Deszka tojásfeltöréshez.','lyukas deszka','kenyérvágó deszka','chill','none'),
(4121,'hu','Micsoda robbanásos jelenet!','Micsoda romantikus jelenet!','robbanásos akciójelenet','romantikus filmjelenet','dramatic','none'),
(4122,'hu','Rossz bankot jött kirabolni.','Rossz boltot jött kirabolni.','kirabolni egy bankot','kirabolni egy vonatot','ironic','bad_excuse'),
(4123,'hu','Könnyek egy ötös miatt? Komolyan?','Könnyek egy egyes miatt? Komolyan?','könnyek egy ötös miatt','könnyek a nevetéstől','ironic','guessing'),
(4124,'hu','Egy furgon, egy kutya és jó barátok.','Egy furgon, egy macska és jó barátok.','élet egy kempingfurgonban','költözés furgonnal','chill','none'),
(4125,'hu','Egy elefánt áll a színpadon!','Egy ló áll a színpadon!','elefánt a színpadon','énekes a színpadon','dramatic','exclamation'),
(4126,'hu','Több ezer épület világít.','Több ezer épület sötét.','kivilágított épületek a kikötőnél','régi épületek egy tónál','dramatic','none'),
(4127,'hu','A maki bundája nagyon puha.','A maki bundája nagyon fekete.','puha fehér bunda','puha fehér kenyér','chill','none'),
(4128,'hu','A kiskutya imádja ezt az udvart.','A kiscica imádja ezt az udvart.','kiskutya az udvaron','kiskutya az utcán','chill','guessing'),
(4130,'hu','A macska lapos frizurát csinált neki!','A kutya lapos frizurát csinált neki!','egy gorilla lapos fejteteje','egy macska lapos fejteteje','gossip','exclamation'),
(4131,'hu','Az üzlet sok zöldet használ.','Az üzlet sok pirosat használ.','zöldre festett fal','golfpálya zöldje','business','none'),
(4132,'hu','A macska kefével fésül egy oroszlánt!','A kutya kefével fésül egy oroszlánt!','nedves sörényt fésül kefével','fogat mos kefével','dramatic','exclamation'),
(4133,'hu','A kutya őrzi a hűtőt.','A macska őrzi a hűtőt.','fekszik a hűtő mellett','kinyitja a hűtőt','slang','guessing'),
(4134,'hu','A kövér sün elvesztette az összes tüskéjét. Nem boldog.','A kövér nyúl elvesztette az összes szőrét. Nem boldog.','kövér, gömbölyű sün','kövér szürke macska','gossip','understatement'),
(4135,'hu','Belerúgott a labdába, aztán leugrott a pályáról!','Elkapta a labdát, aztán leugrott a pályáról!','kapura rúgja a labdát','kézzel kapja el a labdát','dramatic','exclamation'),
(4136,'hu','Négy kutyával edzeni nem könnyű.','Négy macskával edzeni nem könnyű.','edzeni kutyákkal','edzeni a parkban','chill','understatement'),
(4137,'hu','Durva, mennyi sárga egy szobában!','Durva, mennyi zöld egy szobában!','élénksárga ruha','sárgára festett szoba','slang','exaggeration'),
(4138,'hu','Az öreg kutyát simogatja.','Az öreg macskát simogatja.','öreg kutyát simogatni','öreg kutyát sétáltatni','chill','none'),
(4139,'hu','Egy keskeny ösvényen mászik felfelé.','Egy meredek létrán mászik felfelé.','keskeny földes ösvény','ösvény a sivatagon át','chill','none'),
(4140,'hu','Leugrik egy párkányról. Kaland vagy rossz ötlet?','Leugrik egy hajóról. Kaland vagy rossz ötlet?','kaland a barátokkal','kalandfilm','dramatic','guessing'),
(4141,'hu','Öt srác fekszik a napon.','Öt srác fekszik a sárban.','fekszik a fűben','hazudik a barátainak','slang','none'),
(4142,'hu','Esik rá az eső. Buli!','Esik rá a hó. Buli!','pörög, miközben esik','bújik, miközben esik','slang','exclamation'),
(4143,'hu','Pszt, egy mosómedve van a kukában.','Pszt, egy macska van a kukában.','mosómedve a kukában','mosómedve a kukán','gossip','none'),
(4144,'hu','A görények imádják a csövet.','A macskák imádják a csövet.','görények egy csőben','egy tubus fogkrém','chill','guessing'),
(4145,'hu','Vetődik a labdáért!','Vetődik a frizbiért!','vetődés a labdáért','fejesugrás egy hajóról','dramatic','exclamation'),
(4146,'hu','Túl kimerült ahhoz, hogy levegye a cipőjét.','Túl kimerült ahhoz, hogy levegye az ingét.','kimerülten a nedves homokon','kimerülten egy forró fürdőben','ironic','exaggeration'),
(4147,'hu','Siet. Miért van ott az a tábla?','Alszik. Miért van ott az a tábla?','sietni az autóhoz','sietni a buszhoz','gossip','guessing'),
(4148,'hu','Tiszta luxus: egy piros sportkocsi.','Tiszta luxus: egy piros motor.','luxus sportautó','luxus szállodai szoba','flirt','exaggeration'),
(4149,'hu','Egy alvó óriáson landolt!','Egy alvó medvén landolt!','landolás egy óriáson','harc egy óriással','dramatic','exclamation'),
(4150,'hu','A zöld autó száguld.','A piros autó száguld.','száguld egy vidéki úton','száguld az autópályán','chill','none'),
(4151,'hu','Ez az autós művészet nagyon rózsaszín.','Ez az autós művészet nagyon zöld.','rózsaszín autós művészet','művészet egy múzeumban','ironic','understatement'),
(4152,'hu','Az utánfutó egy járművet rejt.','Az utánfutó egy lovat rejt.','jármű egy utánfutóban','jármű egy kompon','gossip','guessing'),
(4153,'hu','Egy kék autó az autópályán.','Egy piros autó az autópályán.','autópálya a hegyek felé','autópálya a tenger felé','chill','none'),
(4154,'hu','Éjszakai sport salakpályán.','Éjszakai sport füves pályán.','sport reflektorfényben','sport a tévében','chill','none'),
(4155,'hu','A tányérok most már „tiszták”.','A csészék most már „tiszták”.','tiszta fehér tányér','tiszta fehér törölköző','ironic','understatement'),
(4156,'hu','Egy robot közeledik felénk!','Egy kutya közeledik felénk!','közeledik a kamerához','közeledik a medencéhez','dramatic','exclamation'),
(4157,'hu','Mindenki versenyez, de az ő táblája nyer.','Mindenki versenyez, de az ő kutyája nyer.','versenyez egy vicces tábla mellett','versenyez egy sportautóban','gossip','exaggeration'),
(4158,'hu','Az a hal óriási. Hű.','Az a hal pici. Hű.','óriási vigyorgó hal','óriási vigyorgó vidra','low_iq','none'),
(4159,'hu','Milyen magasan a völgy felett!','Milyen magasan a város felett!','magasan a völgy felett','magasan a felhők felett','dramatic','exclamation'),
(4160,'hu','Puff! A piros autó eltűnt.','Puff! A piros furgon eltűnt.','eltűnni a homokban','eltűnni a hóban','slang','exaggeration'),
(4161,'hu','A két elülső rész majdnem összeér.','A két hátsó rész majdnem összeér.','egy autó elülső része','egy ház elülső része','chill','none'),
(4162,'hu','Egy autó. Az egész tér. Szép.','Egy busz. Az egész tér. Szép.','vizes kőburkolatú tér','tér piaci standokkal','slang','none'),
(4163,'hu','Az autójáról beszélget.','A kutyájáról beszélget.','beszélgetés egy autóról','beszélgetés egy autóval','chill','none'),
(4164,'hu','A fék nagy és piros.','A fék nagy és kék.','nagy piros fék','nagy piros gomb','chill','none'),
(4165,'hu','Ekkora sebességnél elmosódnak a fák.','Ekkora sebességnél elmosódnak a házak.','sebesség egy hegyi úton','sebesség egy versenypályán','dramatic','none'),
(4166,'hu','Úgy száll be abba a piros autóba, mint egy sztár.','Úgy száll be abba a kék autóba, mint egy sztár.','beszáll egy piros sportautóba','belép egy piros telefonfülkébe','flirt','exaggeration'),
(4168,'hu','A lassú teknős sosem áll meg.','A lassú nyúl sosem áll meg.','lassú teknős','lassú csiga','chill','none'),
(4169,'hu','Pillantást vet a medvére!','Halat dob a medvének!','pillantás a medvére','pillantás a térképre','dramatic','exclamation'),
(4170,'hu','A tyúk megmentette a csibéjét!','A tyúk megmentette a tojását!','megmenteni egy csibét','félretenni egy kis pénzt','dramatic','exclamation'),
(4171,'hu','A farkas egyre közelebb lopakodik.','A róka egyre közelebb lopakodik.','közelebb lopakodó farkas','elszaladó farkas','chill','none'),
(4172,'hu','A tyúk menekülése egy akciófilmbe illik.','A kacsa menekülése egy akciófilmbe illik.','menekülés a tűz elől','menekülés a börtönből','dramatic','exaggeration'),
(4173,'hu','Az üldözés egy hídon ért véget.','Az üldözés egy pajtában ért véget.','üldözés egy hídon át','üldözés egy erdőn át','chill','none'),
(4174,'hu','A tyúk úgy védi meg a csibéit, mint egy szuperhős.','A róka úgy védi meg a csibéit, mint egy szuperhős.','megvédi a csibéit','megvédi a tojásait','dramatic','exaggeration'),
(4175,'hu','Pszt, a tyúk lopakodik.','Pszt, a róka lopakodik.','alvó farkasok mellett lopakodik','ólba lopakodik','gossip','none'),
(4176,'hu','Egy szentjánosbogár ragyog egy befőttesüvegben.','Egy gyertya ragyog egy befőttesüvegben.','ragyogó szentjánosbogár','ragyogó lámpa','chill','none'),
(4177,'hu','A fiókák szája tátva van.','A fiókák szája csukva van.','tátott szájú fiókák','kitárt szárnyú fiókák','chill','none'),
(4178,'hu','A tyúk nagylelkű adományozó.','A róka nagylelkű adományozó.','nagylelkű tyúk','nagylelkű róka','business','exaggeration'),
(4179,'hu','Ez a 100. születésnapja!','Ez az 50. születésnapja!','torta a 100. születésnapra','születésnap a strandon','dramatic','exclamation'),
(4180,'hu','Összetévesztette az aligátort egy kutyával: nincs rajta szemüveg.','Összetévesztette a kígyót egy kutyával: nincs rajta szemüveg.','összetéveszt egy aligátort','összetéveszt egy kiskutyát','gossip','bad_excuse'),
(4181,'hu','Tortát ajánlanak fel neki.','Pizzát ajánlanak fel neki.','születésnapi tortát ajánl fel','egy csésze teát ajánl fel','chill','none'),
(4182,'hu','Az egész pázsitot telefestette!','Az egész házat telefestette!','óriási képet fest a gyepre','kerítést fest a kertben','dramatic','exaggeration'),
(4183,'hu','Egy férfi van az ajándékban!','Egy kutya van az ajándékban!','férfi egy ajándékban','óra egy ajándékban','dramatic','exclamation'),
(4184,'hu','A kiskutya visszahozza a labdát. Kinek kellenek emberek?','A kiskutya visszahozza a cipőt. Kinek kellenek emberek?','visszahozni a labdát','hazahozni a labdát','slang','exaggeration'),
(4185,'hu','Egy bögre nyomja az egeret.','Egy bögre nyomja a gofrit.','egeret nyomó bögre','egeret nyomó tányér','chill','none'),
(4186,'hu','A kutya visszatér a labdával.','A kutya visszatér a cipővel.','visszatérni a géphez','visszatérni az autóhoz','chill','none'),
(4188,'hu','Egy síelő, egy „kis” lejtő.','Két síelő, egy „kis” lejtő.','hosszú havas lejtő','lejtő sífelvonókkal','ironic','understatement'),
(4189,'hu','Üres tál, egy tabletta maradt.','Üres tál, két tabletta maradt.','üres kutyatál','üres hűtő','chill','none'),
(4190,'hu','A macska találkozik egy oroszlánnal. Semmi extra.','A kutya találkozik egy oroszlánnal. Semmi extra.','találkozni egy oroszlánnal','találkozni egy tigrissel','slang','understatement'),
(4191,'hu','A rakéta fölé tornyosul.','A busz fölé tornyosul.','fölé tornyosuló rakéta','fölé tornyosuló daru','chill','none'),
(4192,'hu','Tény: ez a sas halászik.','Tény: ez a bagoly halászik.','lábbal halászik','horgászbottal halászik','nerd','none'),
(4193,'hu','Batmannek kell ez a föld alatti garázs.','Batmannek kell ez a föld alatti medence.','föld alatti garázs','föld alatti vonat','dramatic','exaggeration'),
(4195,'hu','A roller eltört, darabokra hullott!','A bicikli eltört, darabokra hullott!','széteső roller','világrekordot dönt','dramatic','exclamation'),
(4196,'hu','Egy gyertya van a vödörben.','Egy virág van a vödörben.','gyertya egy vödörben','egy vödör víz','chill','none'),
(4197,'hu','Késő van! Fuss!','Korán van! Fuss!','későn kel','sokáig fennmarad','dramatic','exclamation'),
(4198,'hu','A lyuk mélyen lemegy a víz alá. Találkozunk a fenéken!','A kötél mélyen lemegy a víz alá. Találkozunk a fenéken!','mélyen lezuhan egy aknában','mélyen ás a homokban','slang','exclamation'),
(4200,'hu','Naplementekor aranyszínű a tenger.','Naplementekor vörös a tenger.','aranyszínű tenger és ég','aranygyűrű','chill','none'),
(4201,'hu','Menőzők! A biciklik függőlegesen állnak.','Menőzők! Az autók függőlegesen állnak.','függőleges bicikli egy keréken','egyenesen ül egy széken','ironic','exclamation'),
(4202,'hu','Nagyon elfoglalt kutyák, hassal felfelé.','Nagyon elfoglalt macskák, hassal felfelé.','hassal felfelé a napon','tele has','ironic','understatement'),
(4203,'hu','Megmentett egy cápát. Hős.','Megmentett egy delfint. Hős.','partra vetett cápa megmentése','partra vetett bálna megmentése','dramatic','exaggeration'),
(4205,'hu','Egy százszorszépet visz.','Egy rózsát visz.','virágot vinni','magot vinni','chill','none'),
(4206,'hu','Hörcsögnek kitűző van. Hörcsög a főnök.','Hörcsögnek telefon van. Hörcsög a főnök.','a hörcsög névkitűzője','rendőrjelvény','low_iq','exaggeration'),
(4207,'hu','Pizza kiszállítva: igaz szerelem!','Torta kiszállítva: igaz szerelem!','pizzásdobozt szállít ki','levelet szállít ki biciklivel','gossip','guessing'),
(4208,'hu','Ez a hörcsög megette az összes nasit.','Ez a nyúl megette az összes nasit.','nasi nasi után','nasi későbbre','low_iq','exaggeration'),
(4209,'hu','Az egyik hörcsög mély alvásban van.','Az egyik macska mély alvásban van.','hörcsög mély alvásban','alvás a hideg padlón','chill','none'),
(4210,'hu','Tádám! Fagyit tart.','Tádám! Répát tart.','két fagyit tart','két répát tart','dramatic','exclamation'),
(4211,'hu','Ez a hörcsög jobban ápolja az orcáit, mint én.','Ez a nyúl jobban ápolja az orcáit, mint én.','orcáit paskoló hörcsög','orcáit megtömő hörcsög','ironic','exaggeration'),
(4212,'hu','A barna szettjeik jól passzolnak.','A piros szettjeik jól passzolnak.','összeillő barna ruhák','barna bőrkanapé','business','none'),
(4213,'hu','Pirosban olyanok, mint a királynők!','Kékben olyanok, mint a királynők!','mélypirosba öltözve','vörösbor egy pohárban','dramatic','exaggeration'),
(4214,'hu','Mindketten világoskékben kezdenek.','Mindketten sötétzöldben kezdenek.','pár világoskékben','világoskék függöny','chill','none'),
(4215,'hu','Narancssárgában és fehérben van.','Zöldben és fehérben van.','narancssárga fehérrel','narancsot hámoz','chill','none'),
(4216,'hu','A fehér ruhája gyönyörű.','A sárga ruhája gyönyörű.','fehér pamutruha','fehér esküvői ruha','flirt','none'),
(4217,'hu','A rendőrség azt a corgit akarja!','A rendőrség azt a macskát akarja!','a rendőrség kutyát üldöz','a rendőrség tolvajt üldöz','slang','exclamation'),
(4218,'hu','A corgi keményen hajtja a motort.','A macska keményen hajtja a motort.','füstölgő traktormotor','füstölgő autómotor','ironic','blaming_someone'),
(4219,'hu','Az állat sebesen repül.','Az állat sebesen úszik.','repülő állaton lovagol','repülő állatot etet','chill','none'),
(4220,'hu','Egy fehér autót tisztít.','Egy fekete autót tisztít.','tisztítani a fényezést','takarítani a házat','business','none'),
(4221,'hu','A gyík chillel a kanapén.','A gyík chillel az asztalon.','gabonapehely a kanapén','gabonapehely a konyhaasztalon','slang','none'),
(4222,'hu','Tesó, a gekkó integet.','Tesó, a béka integet.','integet a kamerának','zászlót lenget','slang','none'),
(4223,'hu','Túl csípős! Tűz jön ki belőle!','Túl édes! Tűz jön ki belőle!','csípős piros chilipaprika','csípős curry rizzsel','dramatic','exclamation'),
(4224,'hu','Egy gyík használja a vécét.','Egy gyík használja a konyhát.','gyík a vécén','vécét takarító gyík','chill','none'),
(4225,'hu','Ebéd: egy szivacs egy tálban!','Ebéd: egy répa egy tálban!','kis fehér tál','egy tál sajt','low_iq','exclamation'),
(4226,'hu','A krokodil vadászik!','A dinoszaurusz vadászik!','vadászó krokodil','vadászó dinoszaurusz','dramatic','exclamation'),
(4227,'hu','A legbarátságosabb igazoltatás ever.','A legdühösebb igazoltatás ever.','barátságos rendőr','barátságos eladó','slang','exaggeration'),
(4228,'hu','Helikopterrel a partra, csak tojásért!','Hajóval a partra, csak tojásért!','a füves parton','a homokos parton','dramatic','exaggeration'),
(4229,'hu','Valaki kiszabadítja a majmot.','Valaki kiszabadítja a kutyát.','befagyott majmot szabadít ki','befagyott madarat szabadít ki','chill','none'),
(4230,'hu','Egy kutya ül a vezetőülésben.','Egy macska ül a vezetőülésben.','a vezetőülés','a hátsó ülés','chill','none'),
(4231,'hu','Két kutya az ablak mögött? Gyanús.','Két macska az ablak mögött? Gyanús.','bepárásodott teherautó-ablak','bepárásodott fürdőszobaablak','gossip','guessing'),
(4232,'hu','A delfin egy Ronaldo-rúgást csinált a bemutatón!','A fóka egy Ronaldo-rúgást csinált a bemutatón!','delfinbemutató','delfin a tévében','dramatic','exaggeration'),
(4233,'hu','Kőhíd: elég erős a vonatokhoz.','Fahíd: elég erős a vonatokhoz.','kőből épült vasúti híd','kőből épült vasúti alagút','business','none'),
(4234,'hu','A fiú pillanatok alatt szétszedte a lány gardróbját.','A lány pillanatok alatt szétszedte a fiú gardróbját.','bejárós gardrób','konyhai szekrény','gossip','banter'),
(4235,'hu','Szépen bedobta. Eddig nulla hal.','Szépen bedobta. Eddig három hal.','bedobni a horgászzsinórt','hosszú árnyékot vetni','ironic','understatement'),
(4236,'hu','A lány magára vonzotta a figyelmüket.','A fiú magára vonzotta a figyelmüket.','magára vonzza a figyelmüket','új vásárlókat vonz','gossip','none'),
(4237,'hu','Nézd, a fiú egy pajtában van.','Nézd, a fiú egy konyhában van.','ló a pajtában','ló a mezőn','gossip','none'),
(4238,'hu','Nincs sütő? Kövön sütöttek bordát.','Nincs sütő? Kövön sütöttek halat.','sült bárányborda','sült csirke','slang','none'),
(4239,'hu','Legjobb taxi ever: egy sirály a kikötő felett.','Legjobb taxi ever: egy sárkány a kikötő felett.','repülés egy nyüzsgő kikötő felett','jachtokkal teli kikötő','slang','exaggeration'),
(4240,'hu','Két azonos kutyát látok.','Két azonos macskát látok.','két azonos husky','két azonos macska','low_iq','none'),
(4241,'hu','A felhők között vezeti a repülőgépet!','A hóesésben vezeti a repülőgépet!','repülőgépet vezet a felhőkben','helikoptert vezet','dramatic','exclamation'),
(4242,'hu','Kapu? A macska akkor is átmegy.','Kapu? A kutya akkor is átmegy.','átmegy egy kapun','átad egy labdát','slang','understatement'),
(4243,'hu','Valaki kártyával fizet.','Valaki készpénzzel fizet.','fizet egy hot dogért','fizet egy pizzáért','chill','none'),
(4244,'hu','A bika rátámad az autóra!','A ló rátámad az autóra!','autóra rátámadó bika','autóakkumulátor töltése','dramatic','exclamation'),
(4246,'hu','A páva csupa kék.','A páva csupa zöld.','kék páva','kék papagáj','chill','none'),
(4247,'hu','Fiúk ugrálnak egy kútba!','Fiúk ugrálnak egy tóba!','kútba ugró fiúk','kútból ivó fiúk','dramatic','exclamation'),
(4248,'hu','Ezúttal a fedett hullám nyert.','Ezúttal az óceán hulláma nyert.','fedett hullámmedence','úszóóra a fedett uszodában','chill','none'),
(4249,'hu','Egy sárkány hátán ülök!','Egy ló hátán ülök!','egy sárkány háta','egy ló háta','dramatic','exclamation'),
(4250,'hu','A kutya szétszedte a raktárt.','A macska szétszedte a raktárt.','kutya egy raktárban','autókkal teli raktár','gossip','blaming_someone'),
(4251,'hu','Az ő helye? Egy üres polc.','Az ő helye? Egy teli polc.','hely a ruháinak','hely egy autónak','ironic','understatement'),
(4252,'hu','Csapatmunka: az egyik szürcsöl, a másik a betont súrolja.','Csapatmunka: az egyik szürcsöl, a másik a medencét súrolja.','betonterasz súrolása','friss beton öntése','ironic','exaggeration'),
(4253,'hu','Mossák a sárembert.','Mossák a sárkutyát.','vastag sár lemosása','edények elmosása','low_iq','exaggeration'),
(4254,'hu','Egy galamb van a pulton.','Egy galamb van a tetőn.','galamb a pulton','pult a bankban','chill','none'),
(4256,'hu','A kengurut vakarják, és imádja.','A koalát vakarják, és imádja.','kenguru vakarása','autóajtót karcol','chill','guessing'),
(4257,'hu','A teknős szoros ölelésben van.','A hal szoros ölelésben van.','szoros pandaölelés','szoros ölelés a víz alatt','chill','none'),
(4258,'hu','Egy őzgida egy acélcsúszdában van.','Egy őzgida egy facsúszdában van.','hosszú acélcsúszda','hosszú acélhíd','chill','none'),
(4259,'hu','Ennek a birkának hétfői arca van.','Ennek a tehénnek hétfői arca van.','dühös birkaarc','vidám birkaarc','ironic','cliche'),
(4260,'hu','A kutya ügyet sem vet az alakra.','A kutya ugat a sötét alakra.','alak az ajtóban','alak az ablakban','ironic','guessing'),
(4261,'hu','Napos nap van a medencénél.','Esős nap van a medencénél.','napos kerti medence','napos strand','chill','none'),
(4262,'hu','A strand tele van vadvilággal.','A strand tele van emberekkel.','vadvilág a parton','vadvilág az állatkertben','chill','exaggeration'),
(4263,'hu','Hű! A madarak csodálják.','Hű! A madarak ignorálják.','rózsaszín madarat csodálni','rózsaszín tortát csodálni','gossip','exclamation'),
(4264,'hu','Utcai röplabda, háló nélkül.','Strandröplabda, háló nélkül.','röplabda egy csendes utcán','röplabda a strandon','chill','understatement'),
(4265,'hu','Egy ölelés megnyugtatja a papagájt.','Egy dal megnyugtatja a papagájt.','megnyugtatni egy dühös papagájt','megnyugtatni egy síró babát','chill','none'),
(4266,'hu','Micsoda energikus kutya!','Micsoda energikus macska!','energikus kutya futás közben','energikus kutya úszás közben','dramatic','exclamation'),
(4267,'hu','Új look: a kutya olyan rendezett.','Új look: a macska olyan rendezett.','rendezett kerek bunda','kutyák rendezett sora','gossip','none'),
(4268,'hu','A kutya nagyobb szurkoló, nem vicc.','A macska nagyobb szurkoló, nem vicc.','futballszurkoló kutya','ventilátor forró napokra','slang','exaggeration'),
(4269,'hu','A száraz föld gyorsan issza a vizet.','A száraz homok gyorsan issza a vizet.','száraz föld locsolása','száraz levelek söprése','dramatic','exaggeration'),
(4270,'hu','Lassít egy kacsa miatt.','Lassít egy kutya miatt.','lassítani egy kacsa miatt','lassítani a lámpánál','chill','none'),
(4271,'hu','A sportoló durván gyors!','A sportoló durván lassú!','sportoló teljes sebességgel','sportoló a célban','slang','exclamation'),
(4272,'hu','Még több aranyat tesz fel!','Még több ezüstöt tesz fel!','arany karikafülbevaló','aranyérem','dramatic','exclamation'),
(4273,'hu','Itt ütközés volt.','Itt koncert volt.','ütközés egy kereszteződésben','ütközés az autópályán','dramatic','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
