begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(4594,'hu','Együtt sírnak!','Együtt táncolnak!','együtt sírva','együtt énekelve','dramatic','exaggeration'),
(4595,'hu','Nem bírja abbahagyni a sírást.','Nem bírja abbahagyni a nevetést.','sírás a kanapén','sírás a zuhany alatt','dramatic','none'),
(4596,'hu','Kifújja az orrát.','Buborékot fúj.','kifújja az orrát','befogja az orrát','chill','none'),
(4597,'hu','Ez a kultúra imádja a táncot.','Ez a kultúra imádja a focit.','a népi kultúra ünnepe','a gyorskaja-kultúra','chill','none'),
(4598,'hu','Már hatalmas a kávésbögréje!','Már hatalmas a teáskannája!','hatalmas kávésbögre','hatalmas kávészámla','dramatic','exclamation'),
(4599,'hu','Kifizetés érmékkel és bankjegyekkel.','Kifizetés csak bankjegyekkel.','kifizetés készpénzben','kifizetés kártyával','business','none'),
(4600,'hu','Pénzt cserél.','Kalapokat cserél.','külföldi pénzt cserél','ajándékokat cserél','business','none'),
(4601,'hu','Elrendezi a díszpárnákat.','Elrendezi a könyveket.','díszpárnák elrendezése','egy találkozó leszervezése','chill','none'),
(4602,'hu','A vámosok átkutatják a táskáját.','A vámosok átkutatják az autóját.','bőrönd átkutatása','elveszett kutya keresése','business','none'),
(4603,'hu','Az út dombok között kanyarog.','Az út egy városon át kanyarog.','kanyargós hegyi út','kanyargós hegyi folyó','chill','none'),
(4605,'hu','Szikrázik a drót.','Szikrázik a kerék.','a villamos felső drótja','drótkerítés a farmon','chill','none'),
(4606,'hu','Felnéz egy toronyra.','Felnéz egy repülőre.','óra a tornyon','óra a falon','chill','none'),
(4607,'hu','Nagy réztartályok mögötte.','Nagy műanyag tartályok mögötte.','fényes sörfőző réztartályok','rézérmék egy befőttesüvegben','chill','none'),
(4608,'hu','Az egész tömeg full bulizik!','Az egész tömeg alszik!','hatalmas táncoló tömeg','focidrukkerek tömege','slang','exclamation'),
(4610,'hu','Apu készen áll, hogy elkapja!','Anyu készen áll, hogy elkapja!','ugrás apu karjaiba','elszalad aputól','dramatic','exclamation'),
(4611,'hu','A lánya lerajzolta a családot.','A lánya lerajzolt egy lovat.','anya és lánya sütnek','anya és lánya vásárolnak','chill','none'),
(4613,'hu','Forgatja a sötét földet.','Forgatja a fehér homokot.','a sötét föld forgatása','ásás a homokban','chill','none'),
(4614,'hu','Papírfüzért akaszt fel.','Papírlampiont akaszt fel.','partidíszek felakasztása','a mosott ruha kiteregetése','chill','none'),
(4615,'hu','Ez a szoba szuper színes.','Ez a szoba szuper szürke.','színes partilufik','színes húsvéti tojások','slang','none'),
(4616,'hu','Vad szarvas a ködös erdőben.','Vaddisznó a ködös erdőben.','szarvas az erdőben','fából készült asztal','dramatic','none'),
(4617,'hu','Páncélos férfiak harcolnak.','Öltönyös férfiak harcolnak.','harc pajzsokkal','harc egy parkolóhelyért','dramatic','none'),
(4618,'hu','Itt jön a roham!','Itt jön az eső!','roham pajzsokkal','pótdíj extra csomagért','dramatic','exclamation'),
(4619,'hu','Nyers csirke, nyers hal, vacsora még sehol.','Nyers csirke, nyers marha, vacsora még sehol.','nyers fagyasztott csirke','egy nyers tojás','chill','understatement'),
(4620,'hu','Éjszakán át itt alszik.','Éjszakán át itt dolgozik.','éjszakán át a reptéren ragadva','éjszakai vonatút','chill','none'),
(4621,'hu','Az utasok úgy néznek, mint akik szerint a gép sosem jön meg.','A pilóták úgy néznek, mint akik szerint a gép sosem jön meg.','fáradt utasok várakoznak','utasok a repülőn','dramatic','guessing'),
(4622,'hu','A plafonra nézve sóhajt.','Az ablakra nézve sóhajt.','sóhajtás a kapunál','megkönnyebbült sóhaj','chill','none'),
(4623,'hu','Kihullanak a szavazatok.','Kihullanak az érmék.','a szavazatok számlálása','szavazat leadása','chill','none'),
(4624,'hu','Egyértelmű többség!','Egyértelmű kisebbség!','egyértelmű többség','üres székek többsége','dramatic','exclamation'),
(4625,'hu','A nő úgy szavaz, mint egy bajnok!','A férfi úgy szavaz, mint egy bajnok!','boldogan szavazni','levélben szavazni','dramatic','exaggeration'),
(4627,'hu','Mindenki elmegy. Ő integet!','Mindenki marad. Ő integet!','integet az elmenő hajónak','biciklivel elmenni','dramatic','exaggeration'),
(4628,'hu','Elmaradt a piknik. A srác szomorú.','Elmaradt a piknik. A lány szomorú.','szomorú az eső miatt','szomorú a hó miatt','chill','none'),
(4629,'hu','Végtelen homok, egy apró vándor.','Végtelen homok, egy apró teve.','végtelen dűnesorok','végtelen autósor','dramatic','none'),
(4630,'hu','Először a hajvágást rajzolta meg.','Először a szakállt rajzolta meg.','éles átmenetes hajvágás','hajvágás hosszú oldalakkal','chill','none'),
(4631,'hu','Megtervezett egy madárodút.','Megtervezett egy kutyaházat.','madárodút tervez','weboldalt tervez','chill','none'),
(4632,'hu','Kész a munkasarok.','Kész a konyha.','munkasarok berendezése','közös munkasarok','business','none'),
(4634,'hu','Végre elérte a várost!','Végre elérte a tavat!','a tengerparti város elérése','a telefonért nyúl','dramatic','exclamation'),
(4635,'hu','Elérte az úti célját.','Elérte a szállodáját.','eléri az úti célját','repülős úti cél','chill','none'),
(4636,'hu','Megtalálta az igazi világítótornyot!','Megtalálta az igazi kastélyt!','piros-fehér világítótorony','világítótorony viharban','dramatic','exclamation'),
(4637,'hu','Lerombolják a házat, ő meg filmezi.','Lerombolják az autót, ő meg filmezi.','régi ház lerombolása','régi autó szétverése','gossip','none'),
(4638,'hu','Viszlát, ház. Most már csak törmelék.','Viszlát, pajta. Most már csak törmelék.','egy halom törmelék','a törmelék eltakarítása','gossip','none'),
(4639,'hu','A folyékony szappan kékeszöld.','A folyékony szappan élénkpiros.','csorgó folyékony szappan','folyékony festék az ecseten','chill','none'),
(4640,'hu','Kék tisztítószer, fehér ing!','Rózsaszín tisztítószer, fehér ing!','tisztítószer öntése','tisztítószer a mosogatáshoz','slang','exclamation'),
(4641,'hu','Viszlát, fánkok. Helló, új étrend.','Viszlát, saláta. Helló, fánkok.','előre főzött kaja az étrendhez','fánkokból álló étrend','dramatic','cliche'),
(4642,'hu','Legjobb gödör ever. A kutya segített.','Legjobb gödör ever. A macska segített.','mély homokgödör','kígyókkal teli gödör','low_iq','none'),
(4644,'hu','Munka? Micsoda gyenge kifogás.','Eső? Micsoda gyenge kifogás.','gyenge kifogás a lelépésre','kifogás a késésre','dramatic','bad_excuse'),
(4645,'hu','Kezek golyókat rögzítenek.','Kezek kerekeket rögzítenek.','golyók rögzítése rudakra','rudak rögzítése a falra','chill','none'),
(4646,'hu','Lekerültek a gyűrűk: ez válás.','Lekerültek a gyűrűk: ez esküvő.','gyűrűk a válás után','válóperes ügyvéd irodája','dramatic','none'),
(4647,'hu','Túl sokat pörgött. Irány a padló.','Túl sokat futott. Irány a padló.','pörgés irodai széken','pörgés a táncparketten','slang','understatement'),
(4648,'hu','Megvizsgál egy kisfiút.','Megvizsgál egy kiskutyát.','egy aggódó kisfiú megvizsgálása','egy aggódó macska megvizsgálása','business','none'),
(4649,'hu','A plüssmackó bátrabb nála.','A kiskutya bátrabb nála.','barna plüssmackót ölel','barna kiskutyát ölel','ironic','guessing'),
(4650,'hu','A reakció habot termel!','A reakció füstöt termel!','habzó kémiai reakció','gyors allergiás reakció','dramatic','exclamation'),
(4651,'hu','Tengeri élet naplementekor.','Tengeri élet délben.','ugráló tengeri állatok','egyenruhás tengerészgyalogos','nerd','none'),
(4652,'hu','Egy férfival versenyez.','Egy gyerekkel versenyez.','szkanderben versenyezni','főzőshow-ban versenyezni','chill','none'),
(4653,'hu','A sarat a lábtörlőn hagyta. Nagyjából.','A havat a lábtörlőn hagyta. Nagyjából.','sárral borított csizma','sár a konyhaasztalon','ironic','understatement'),
(4654,'hu','Kétségei vannak ezzel kapcsolatban.','Semmi kétsége ezzel kapcsolatban.','kétségek egy polc miatt','kétségek a festék miatt','gossip','understatement'),
(4655,'hu','Öltönybe öltözik fel.','Kapucnis pulcsiba öltözik fel.','felöltözik öltönybe','salátát öntetez','chill','none'),
(4656,'hu','Felszerelt két polcot.','Felszerelt két tükröt.','polcok felszerelése a falra','felülni a lóra','chill','none'),
(4657,'hu','Kókuszvizet iszik.','Narancslevet iszik.','szívószállal inni','csapból inni','chill','none'),
(4658,'hu','A tenger mellett vezet.','Egy tó mellett vezet.','vezetni a part mentén','vezetni egy folyó mentén','chill','none'),
(4659,'hu','Ezek az emberek mind autóban ülnek.','Ezek az emberek mind biciklin ülnek.','emberek az autójukban','emberek az ágyukban','chill','none'),
(4660,'hu','A bevásárlása egyetlen nagy halom.','A bevásárlása egyetlen szatyorban van.','egy halom doboz','egy halom szennyes','chill','none'),
(4661,'hu','Megjött az ősz a parkba!','Megjött a tavasz a parkba!','sárga levelek ősszel','őszi divat egy boltban','dramatic','none'),
(4662,'hu','Egy repülő látja el a falut.','Egy teherautó látja el a falut.','falu ellátása légi úton','falu ellátása hajóval','chill','none'),
(4663,'hu','Egy csepp mindjárt landol.','Egy méh mindjárt landol.','egyetlen tiszta csepp','egy esőcsepp','chill','guessing'),
(4664,'hu','Cseppenként méri ki az adagot.','Kanalanként méri ki az adagot.','egy adag sárga olaj','egy adag köhögés elleni szirup','nerd','none'),
(4665,'hu','Egyik baleset a másik után!','Egyik gól a másik után!','kisebb balesetek sorozata','autóbaleset','dramatic','exclamation'),
(4666,'hu','A tök szétzúzódott. Hoppá!','A tojás szétzúzódott. Hoppá!','betonon szétzúzódó tök','ablakot betörő tök','ironic','exclamation'),
(4667,'hu','A repülőgép dobozokat dob le. Légi szállítás!','A repülőgép leveleket dob le. Légi szállítás!','ládákat ledobó repülőgép','füvön leszálló repülőgép','slang','none'),
(4668,'hu','Megszagolja a mosott ruhát.','Kivasalja a mosott ruhát.','tiszta ruha szagolgatása','a tengeri levegő szagolása','chill','none'),
(4669,'hu','Mosott ruha tengerre néző kilátással!','Mosott ruha városra néző kilátással!','fehér ruhák a szárítókötélen','egy zsák mosnivaló','slang','exclamation'),
(4670,'hu','A tetőn van.','A kertben van.','ruhaszárítás lapos tetőn','macska a tetőn','chill','none'),
(4671,'hu','A takaró a gépben van.','A törölköző a gépben van.','mosógép','kávégép','chill','none'),
(4672,'hu','Mindkét parton nád nő.','Mindkét parton fák nőnek.','magas nád a víz mellett','fonott nádkosár','nerd','none'),
(4673,'hu','Ehhez ő túl gyenge, tesó!','Ehhez ő túl erős, tesó!','gyenge, vékony kar','gyenge tea','slang','exclamation'),
(4674,'hu','Leporolja a polcokat.','Lefesti a polcokat.','polcok leporolása','polcok összeszerelése','chill','none'),
(4675,'hu','A srác egyáltalán nem óvatos!','A lány egyáltalán nem óvatos!','nem óvatos a hídon','óvatos a tulipánokkal','dramatic','understatement'),
(4676,'hu','Itt hagyomány a sajt cipelése.','Itt hagyomány a hal cipelése.','régi sajtos hagyomány','régi tánchagyomány','chill','none'),
(4679,'hu','Ezek a tacók nagyon finomak!','Ezek a burgerek nagyon finomak!','két finom taco','egy finom hideg leves','dramatic','exclamation'),
(4680,'hu','Egy lovas felszáll egy tevére.','Egy lovas felszáll egy lóra.','tevére szálló lovas','lovas lóháton','chill','none'),
(4681,'hu','Mennyi üveglámpa!','Mennyi üvegpalack!','kék üveglámpa','kék üvegváza','dramatic','exclamation'),
(4682,'hu','A kereskedő fűszert tölt.','A kereskedő teát tölt.','fűszerkereskedő','tőzsdei kereskedő','chill','none'),
(4683,'hu','Tele van a pult rizzsel.','Tele van a pult sóval.','egy tál főtt rizs','egy zacskó nyers rizs','gossip','exaggeration'),
(4684,'hu','Könyökpacsi: az új kézfogás.','Ökölpacsi: az új kézfogás.','könyökpacsi a munkahelyen','könyök az asztalon','business','cliche'),
(4685,'hu','Megjavítja a biztosítékdobozt.','Megjavítja az autót.','a biztosítékdoboz megjavítása','defektes gumi megjavítása','business','none'),
(4686,'hu','Javítás kész, van fény!','Javítás kész, van víz!','javítás a sötétben','autójavító műhely','dramatic','exclamation'),
(4687,'hu','A nagykövetségnél van.','A nagykövetség épületében van.','iratok a nagykövetségre','éjszakai nagykövetségi buli','chill','none'),
(4688,'hu','Csak egy hatalmas bálna, semmi különös.','Csak egy hatalmas cápa, semmi különös.','hatalmas púpos bálna','hatalmas vihar a tengeren','ironic','understatement'),
(4689,'hu','Egy bálna a csónak mellett!','Egy cápa a csónak mellett!','bálna a csónak mellett','delfin a csónak mellett','dramatic','exclamation'),
(4690,'hu','A munkahelye egy irodafülke.','A munkahelye egy konyha.','nyüzsgő egyterű munkahely','munkahely egy farmon','business','none'),
(4691,'hu','Üdvözöl egy kollégát.','Üdvözöl egy kutyát.','kolléga üdvözlése','kolléga szabadságon','chill','none'),
(4692,'hu','Polcra pakolja a termékeket.','Polcra pakolja a könyveket.','termékek a polcon','termékek egy teherautóban','business','none'),
(4693,'hu','A főnök épp felvette.','A főnök épp kirúgta.','új dolgozó felvétele','autóbérlés a nyaralásra','business','none'),
(4694,'hu','Aláírta a szerződést!','Széttépte a szerződést!','szerződés aláírása','szerződés olvasása otthon','dramatic','exclamation'),
(4695,'hu','Ezt az egész káoszt ő csinálta.','Ezt az egész káoszt ő takarította el.','káosz a padlón','káosz a konyhában','gossip','blaming_someone'),
(4696,'hu','Bátorítják őt!','Kinevetik őt!','egy mászó bátorítása','gyerek bátorítása olvasásra','dramatic','exclamation'),
(4697,'hu','Villámgyors a rajtja!','Lassú a rajtja!','rajt a startgépből','az iskolakezdés','dramatic','exaggeration'),
(4698,'hu','Micsoda hatalmas motor!','Micsoda hatalmas gumi!','hatalmas V8-as motor','hatalmas csónakmotor','dramatic','exclamation'),
(4699,'hu','Átvizsgálja a gépezetet.','Megjavítja a gépezetet.','régi gyári gépezet','régi mezőgazdasági gépezet','business','none'),
(4700,'hu','A robot egy bögrét nyújtott neki.','A robot egy telefont nyújtott neki.','bögrét tartó robot','robotporszívó','chill','none'),
(4701,'hu','A tenger lerombolta. Kösz, tenger.','A kutya lerombolta. Kösz, kutya.','lerombolt homokvár','lerombolt régi templom','ironic','blaming_someone'),
(4702,'hu','A kecske megszökött. Csá, gazda!','A tehén megszökött. Csá, gazda!','megszökni a kecskekarámból','megszökni egy róka elől','slang','blaming_someone'),
(4703,'hu','Felemel egy zöld zászlót.','Felemel egy piros zászlót.','zászló felemelése','gyereknevelés','chill','none'),
(4704,'hu','Szőrmekalapot visel a szaunában!','Baseballsapkát visel a szaunában!','szőrmekalapot visel','szalmakalapot visel','slang','exclamation'),
(4705,'hu','Az egész város imádja a zenekart!','Az egész város utálja a zenekart!','játszó utcai zenekar','zenekar egy stadionban','gossip','exaggeration'),
(4706,'hu','Az egész stadion kiabál.','Az egész stadion ül.','kiabáló szurkolók a stadionban','kiabálás a könyvtárban','chill','none'),
(4707,'hu','A legjobb beteg ever. Mosolyog.','A legjobb beteg ever. Alszik.','beteg egy ápolóval','beteg a mentőautóban','gossip','exaggeration'),
(4708,'hu','Egy férfi vezeti a csoportot.','Egy kutya vezeti a csoportot.','turistacsoport vezetése','hajó bevezetése a kikötőbe','chill','none'),
(4709,'hu','Az egész csoport ujjong!','Az egész csoport sír!','csoport egyforma sapkában','csoport egyforma pólóban','dramatic','none'),
(4710,'hu','Lóbálják a karjukat.','Lóbálják a lábukat.','karok a fej fölött','keresztbe font karok','business','none'),
(4711,'hu','Az arca maga a tiszta erőfeszítés.','Az arca maga a tiszta unalom.','evezés teljes erőfeszítéssel','futás teljes erőfeszítéssel','dramatic','none'),
(4712,'hu','Elfújja az összes gyertyát!','Felfújja az összes lufit!','szülinapi gyertyák elfújása','lufik felfújása','dramatic','exclamation'),
(4713,'hu','Búcsút intenek.','Üdvözlésül intenek.','búcsúintés a rakpartról','búcsúlevél','chill','none'),
(4714,'hu','A szakértő szerint eredeti.','A szakértő szerint hamisítvány.','szakértő egy vázával','szakértő egy autóval','chill','none'),
(4715,'hu','Felrobbant a görögdinnye!','Felrobbant a tök!','szétrobbanó görögdinnye','felszeletelt görögdinnye','dramatic','exclamation'),
(4716,'hu','Úgy fedezi fel a dzsungelt, mint Indiana Jones.','Úgy fedezi fel a sivatagot, mint Indiana Jones.','dzsungelbarlang felfedezése','nagyváros felfedezése','dramatic','exaggeration'),
(4717,'hu','Nagyon sötét van az alagútban!','Nagyon sötét van a házban!','sötét sziklaalagút','sötét éjszakai égbolt','dramatic','exclamation'),
(4718,'hu','A barna szeme betölti a képet.','A kék szeme betölti a képet.','zseblámpafény a szemben','szem a szemüveg mögött','chill','none'),
(4719,'hu','Az álla kerek.','Az álla hegyes.','kerek áll','kéz az állon','business','none'),
(4720,'hu','Vicces fejek, nulla szégyen!','Vicces kalapok, nulla szégyen!','vicces fejek a telefonnak','vicces fejek a tanárnak','slang','exaggeration'),
(4721,'hu','Neee, elhalványul a szivárvány!','Neee, egyre nagyobb a szivárvány!','elhalványuló szivárvány','elhalványuló fénykép','dramatic','exclamation'),
(4722,'hu','Még a napszemüveges nők is elájulnak!','Még a napszemüveges nők is táncolnak!','nők sötét napszemüvegben','napszemüveg a napos strandon','dramatic','exaggeration'),
(4723,'hu','Az emberek beleesnek a habba.','Az emberek beleesnek a vízbe.','beleesni egy habgödörbe','beleesni egy medencébe','chill','none'),
(4724,'hu','Nem bírja abbahagyni a nevetést.','Nem bírja abbahagyni a sírást.','nevetés a habgödörben','nevetés a labdamedencében','chill','none'),
(4725,'hu','Az egész család pizzát csinált.','Az egész család tésztát csinált.','pizzatészta készítése','pizza rendelése online','chill','none'),
(4726,'hu','A gazda répát húz.','A gazda hagymát húz.','boldog gazda naplementekor','fáradt gazda hajnalban','chill','none'),
(4727,'hu','Ez az apa sosem fárad el.','Ez az anya sosem fárad el.','labdázó apa','tévéző apa','gossip','exaggeration'),
(4728,'hu','A kanapén alszik. Hosszú nap volt!','A padlón alszik. Hosszú nap volt!','alvás a kanapén','alvás a munkahelyen','slang','guessing'),
(4729,'hu','A maszktól ijedtek meg ennyire!','A bohóctól ijedtek meg ennyire!','ijedten egy kísértetházban','ijedt a póktól','dramatic','exclamation'),
(4730,'hu','A bizottság kilenc főből áll.','A bizottság öt főből áll.','bizottság egy asztal körül','bizottság a színpadon','business','none'),
(4731,'hu','Minden nemzet zászlaja emelkedik.','Minden nemzet zászlaja süllyed.','minden nemzet zászlaja','egy nemzet hadserege','business','none'),
(4732,'hu','Fakerítést épít.','Fészert épít.','kerti kerítés építése','homokvár építése','chill','none'),
(4733,'hu','Az egekben van a hőmérséklete!','Nagyon alacsony a hőmérséklete!','hőmérséklet mérése','a kinti hőmérséklet','dramatic','exaggeration'),
(4734,'hu','Gondoskodik róla.','Egy kutyáról gondoskodik.','szerető gondoskodás a kanapén','bőrápolás a fürdőszobában','chill','none'),
(4735,'hu','Ökölcsapásokat oszt.','Ökölcsapásokat hárít.','ökölcsapások a fogópárnára','egy tál gyümölcspuncs','chill','none'),
(4736,'hu','A hadsereg homokon edz.','A hadsereg hóban edz.','együtt edző hadsereg','háborúzó hadsereg','chill','none'),
(4737,'hu','Kancsóból tölt.','Üvegből tölt.','vizet tölt kancsóból','egy kancsó narancslé','chill','none'),
(4738,'hu','Mindenhol a ruhái!','Mindenhol a könyvei!','ruhák mindenhol','útlevelek mindenhol','dramatic','exclamation'),
(4739,'hu','Felfedezett egy hatalmas gyémántot!','Felfedezett egy hatalmas gyűrűt!','rejtett gyémánt felfedezése','új ország felfedezése','dramatic','exclamation'),
(4740,'hu','Most kitisztítja a sebet.','Most kitisztítja a biciklit.','vérző seb tisztítása','seb az arcon','chill','none'),
(4741,'hu','Egy halat húz ki!','Egy csizmát húz ki!','halat kihúzni','csónakot partra húzni','dramatic','exclamation'),
(4742,'hu','Milyen erős a köteleken!','Milyen erős a biciklin!','erős karok és lábak','egy erős kávé','flirt','exclamation'),
(4743,'hu','Gyümölcslé! Minden idők legjobb repülése!','Pizza! Minden idők legjobb repülése!','repülés naplementekor','egy emeletnyi lépcső','slang','exaggeration'),
(4744,'hu','A vízen lazít.','A homokon lazít.','lazítani a sós vízen','lazítás egy forró fürdőben','chill','none'),
(4745,'hu','A folyó kavicsok mellett folyik.','A folyó házak mellett folyik.','lefelé folyó víz','csapból folyó víz','chill','none'),
(4746,'hu','A sugárhajtású gép a fényképészek fölött repül!','A madár a fényképészek fölött repül!','fényképészek a kifutónál','fényképészek egy esküvőn','dramatic','exclamation'),
(4747,'hu','A sirályok a kenyerét akarják!','A sirályok a kalapját akarják!','sirályok egy komp körül','sirályok a strandon','dramatic','guessing'),
(4748,'hu','Csak felhők a szárny alatt.','Csak hegyek a szárny alatt.','felhők a repülő alatt','felhők a tenger fölött','chill','none'),
(4749,'hu','Alakzatban zuhannak!','Alakzatban úsznak!','ejtőernyősök kör alakzatban','focicsapat alakzata','dramatic','exclamation'),
(4750,'hu','Kastélyt épített a ruhákból.','Kastélyt épített a könyvekből.','tiszta ruhák hajtogatása','koszos ruhák mosása','low_iq','none'),
(4751,'hu','Idegenvezető sárga esernyővel.','Idegenvezető piros esernyővel.','idegenvezető esernyővel','idegenvezető a múzeumban','chill','none'),
(4752,'hu','Kudarc! A sütő tehet róla.','Siker! A sütő tehet róla.','sütési kudarc','kudarc matekból','dramatic','blaming_someone'),
(4753,'hu','Csavar a sztoriban: megbocsátott neki.','Csavar a sztoriban: levegőnek nézte.','megbocsátás egy régi barátnak','megbocsátás az öccsének','gossip','cliche'),
(4754,'hu','A srác tiltakozik: „Nem én voltam!”','A lány tiltakozik: „Nem én voltam!”','tiltakozás a bírónál','tiltakozás az utcán','dramatic','bad_excuse'),
(4755,'hu','A röntgenen csonttörés látszik a kézben.','A röntgenen csonttörés látszik a lábban.','csonttörés a röntgenképen','csonttörés a lábban','nerd','none'),
(4756,'hu','Bagett a biciklin? Ez Franciaország!','Pizza a biciklin? Ez Franciaország!','biciklizés Franciaországban','síelés Franciaországban','slang','cliche'),
(4757,'hu','Végre nyári szabadság!','Végre téli szabadság!','szabadság a nyílt úton','szabadság a nagyvárosban','dramatic','exclamation'),
(4758,'hu','Most már tele a hűtő, tesó!','Most már üres a hűtő, tesó!','hűtő tele kajával','tele mosógép','slang','exclamation'),
(4759,'hu','A pék egy bagettbe beszél.','A pék egy croissant-ba beszél.','pék bagettel','pizzát készítő pék','low_iq','none'),
(4760,'hu','Megosztanak egymással egy fagyit.','Megosztanak egymással egy pizzát.','fagyit megosztani','villamosjegyet megosztani','chill','none'),
(4761,'hu','Szalonna a befagyott tavon!','Szalonna a homokos strandon!','szalonnasütés a jégen','szalonna egy szendvicsben','slang','exclamation'),
(4762,'hu','Imádja ezt a galériát!','Utálja ezt a galériát!','nagy művészeti galéria','autókkal teli galéria','dramatic','exclamation'),
(4763,'hu','Ezek a gamerek teljesen megőrülnek!','Ezek a gamerek mind alszanak!','gamerek egy arénában','gamer egy osztályteremben','slang','exaggeration'),
(4764,'hu','Teljesen bepörög a kanapén.','Teljesen bepörög az ágyon.','ugrálás a kanapén','alvás a kanapén','slang','exaggeration'),
(4765,'hu','A kertben üvegház is található.','A kertben úszómedence is található.','kis üvegház','nagy fóliaház','business','none'),
(4766,'hu','Imád kertészkedni.','Imád úszni.','kertészkedni a virágok közt','kertészkedni az esőben','chill','none'),
(4767,'hu','A kertésznek nagy metszőollója van.','A kertésznek nagy fejszéje van.','kertész metszőollóval','kertész slaggal','chill','none'),
(4768,'hu','Nála vannak a nyerő kártyák.','Nála vannak a nyerő kockák.','két kártyalap','szülinapi képeslap','gossip','guessing'),
(4769,'hu','Egy kerítés mellett áll.','Egy kerítésen ül.','kerítés a perem mentén','kerítés egy kert körül','chill','none'),
(4770,'hu','A beszállás folyamatban van.','A leszállás folyamatban van.','beszállás utashídon át','beszállás a vasútállomáson','business','none'),
(4771,'hu','Kapu, kapu, kapu... palota!','Kapu, kapu, kapu... templom!','kapu egy palotához','palota a városban','dramatic','exclamation'),
(4772,'hu','Hatalmas madárraj az égen.','Hatalmas madárraj a vízen.','seregélyekből álló madárraj','madárraj egy tavon','chill','none'),
(4773,'hu','A zene csődületet csinált.','A zene verekedést csinált.','csődület egy utcazenész körül','családi összejövetel otthon','chill','none'),
(4774,'hu','Minden generáció nevet az almafa alatt.','Minden generáció nevet a pálmafa alatt.','generációk egy kertben','generációk az ebédlőasztalnál','chill','none'),
(4775,'hu','Az újszülöttnek már négy rajongója van.','Az újszülöttnek már két rajongója van.','alvó újszülött baba','újszülött bárány','gossip','exaggeration'),
(4776,'hu','Milyen udvarias: megemeli a kalapját.','Milyen udvarias: megemeli a sétapálcáját.','udvarias köszönés','udvarias levél','flirt','none'),
(4777,'hu','Mindenkivel segítőkész.','Mindenkivel bunkó.','segítőkész idős úr','segítőkész fiatal pincér','chill','none'),
(4778,'hu','Ez a műhely órákat készít.','Ez a műhely cipőket készít.','kis órásműhely','kis íróműhely','business','none'),
(4779,'hu','A srác jól érzi magát Németországban!','A lány jól érzi magát Németországban!','körutazás Németországban','munka Németországban','dramatic','exclamation'),
(4780,'hu','Két különálló ajtón mennek ki.','Ugyanazon az ajtón mennek ki.','két különálló ajtó','két különálló asztal','dramatic','none'),
(4781,'hu','Összeházasodnak!','Szakítanak!','összeházasodni egy kertben','összeházasodni a tengerparton','dramatic','exclamation'),
(4782,'hu','Övé a játszótér!','Övé az osztályterem!','játék a játszótéren','üres játszótér','slang','exaggeration'),
(4783,'hu','A pár csupa torta!','A pár csupa sár!','tortás arcú pár','pár egy biciklin','dramatic','exclamation'),
(4784,'hu','Ajándékot ad neki.','Telefont ad neki.','becsomagolt ajándékot ad','nagy beszédet tart','chill','none'),
(4785,'hu','Egészségünkre a teraszon!','Egészségünkre a konyhában!','gyümölcslé a napos teraszon','tetőterasz-buli','slang','exclamation'),
(4786,'hu','Kéken csillog a homok!','Pirosan csillog a homok!','éjjel csillogó homok','napfényben csillogó homok','dramatic','exclamation'),
(4787,'hu','Ez a serpenyő nagyon értékes.','Ez a serpenyő teljesen üres.','értékes serpenyőnyi arany','értékes régi festmény','chill','none'),
(4788,'hu','Szalonpletyka. Mindenki döbbent.','Szalonpletyka. Mindenki unatkozik.','döbbenten a pletykától','döbbenten az ár láttán','gossip','exaggeration'),
(4789,'hu','A nőnek teljes hatalma van.','A férfinak teljes hatalma van.','hatalommal bíró nő','hatalom egy hadsereg felett','business','none'),
(4790,'hu','Konfliktus a nagy asztalnál, és repkednek a papírok!','Béke a nagy asztalnál, és repkednek a papírok!','konfliktus az asztalnál','konfliktus az utcán','gossip','exclamation'),
(4791,'hu','Iratokat tesz le.','Virágokat tesz le.','egy mappa irat','iratok a padlón','business','none'),
(4792,'hu','Virágokat ültetnek.','Virágokat szednek.','fiatal virág ültetése','zászlót tűz ki','chill','none'),
(4793,'hu','Egy madárodút csiszolnak.','Egy madárodút festenek.','fatető csiszolása','fapadló csiszolása','chill','none'),
(4794,'hu','Nagymama sütije nyer.','Nagymama pizzája nyer.','süti a nagymamától','süti a boltból','slang','cliche'),
(4795,'hu','Sütit sütött. Legjobb nap!','Pitét sütött. Legjobb nap!','frissen sütött csokis sütik','frissen sütött almás piték','dramatic','exclamation'),
(4796,'hu','Két kártyát egyensúlyoz. Óvatosan!','Két csészét egyensúlyoz. Óvatosan!','kártyalapok egyensúlyozása','egyensúlyozás egy lábon','dramatic','exclamation'),
(4797,'hu','Csak egy kevés sajtot tesz rá.','Csak egy kevés szószt tesz rá.','egy kevés extra sajt','egy kevés extra bors','chill','understatement'),
(4798,'hu','Egy templomhoz sétál.','Egy kápolnához sétál.','régi templom a hegytetőn','régi vár a hegytetőn','chill','none'),
(4799,'hu','Csokornyakkendőt köt? Idegőrlő meló!','A cipőjét köti? Idegőrlő meló!','fekete csokornyakkendő megkötése','bőrönd átkötése','dramatic','exclamation'),
(4800,'hu','A vőlegény nagyon ideges!','A menyasszony nagyon ideges!','ideges vőlegény','lovat etető vőlegény','gossip','exclamation'),
(4801,'hu','Milyen magas ez a napraforgó!','Milyen magas ez a kaktusz!','magas napraforgó','magas fa','dramatic','exclamation'),
(4802,'hu','Ez az őr a múzeum főnöke.','Ez a szakács a múzeum főnöke.','múzeumi őr','őr egy bankban','ironic','guessing'),
(4803,'hu','Virágcsokrot hozott.','Tortát hozott.','virágcsokor a háziaknak','virágcsokor egy menyasszonynak','chill','none'),
(4804,'hu','Egy kék várost járnak be.','Egy piros várost járnak be.','kék város bejárása','turné egy rockbandával','chill','none'),
(4805,'hu','Egy templomra mutat.','Egy hajóra mutat.','kupolás templom','fatemplom','chill','none'),
(4806,'hu','Egy kupola van a könyve mögött.','Egy daru van a könyve mögött.','kupola a láthatáron','kupolasátor kempingezéshez','chill','none'),
(4807,'hu','Narancssárga felsőt visel.','Narancssárga sapkát visel.','narancssárga sportfelső','narancssárga sportautó','chill','none'),
(4808,'hu','A fodrász fonatot készít.','A fodrász kontyot készít.','hosszú fonat fonása','hosszú fonat levágása','chill','none'),
(4809,'hu','Csúcsforgalom van a folyosón.','Csúcsforgalom van a fürdőszobában.','cipőkkel teli folyosó','hosszú szállodai folyosó','ironic','exaggeration'),
(4810,'hu','Beveri a cölöpöt.','Beveri a szöget.','cölöp a földben','poszt a közösségi médián','chill','none'),
(4811,'hu','A csapattársak be vannak pörögve.','A csapattársak verekednek.','kezek középen a csapattársakkal','vita a csapattársakkal','slang','none'),
(4812,'hu','A gardróbja szuper rendezett.','A gardróbja szuper rendetlen.','rendezett ingsor','rendezett cipőkupac','slang','none'),
(4813,'hu','Nyüzsög a kikötő.','Üres a kikötő.','nyüzsgő kikötő napfelkeltekor','kikötő viharban','chill','none'),
(4814,'hu','A csapat paradicsomot szed.','A csapat almát szed.','piros paradicsomot szed','piros almát szed','business','none'),
(4815,'hu','Irodai stressz: a halántékát dörzsöli.','Irodai stressz: a lábát dörzsöli.','a halántékát dörzsöli','a kezét dörzsöli','business','none'),
(4816,'hu','Hevesen ver a szíve!','Nyugodtan pihen a szíve!','kéz a szíven','szív a pólóján','dramatic','exclamation'),
(4817,'hu','Ebben az aszályban még a fa is olvad.','Ebben az aszályban még a kutya is olvad.','aszály repedezett földdel','az aszály vége','dramatic','exaggeration'),
(4818,'hu','Tüskék a sarok alatt? Őrület!','Kerekek a sarok alatt? Őrület!','tüske a sarok alatt','a cipő sarka','slang','exclamation'),
(4819,'hu','Az idős nő hálás.','Az idős férfi hálás.','hálás az esernyőért','hálás a taxiért','chill','none'),
(4820,'hu','Ugyanaz a ruhájuk!','Ugyanaz a táskájuk!','ugyanaz a mintás ruha','ugyanaz a cipő','dramatic','exclamation'),
(4821,'hu','Megjött a naplementés pizza!','Megjött a naplementés sushi!','pizzaszállítás naplementekor','naplemente a hegyek fölött','flirt','exclamation'),
(4822,'hu','Az üzenet nagyon boldoggá tette.','Az üzenet nagyon szomorúvá tette.','örömteli üzenet olvasása','üzenet a hűtőn','chill','guessing'),
(4823,'hu','Nagy mélységbe merül.','Kis mélységbe merül.','merülés nagy mélységbe','a medence mélysége','chill','none'),
(4824,'hu','A lova kamu, de jól színlel.','A lova kamu, de jól úszik.','lovaglást színlel','alvást színlel','ironic','cheap_quality'),
(4825,'hu','Pult áttörölve. Konyha kész.','Ablak áttörölve. Konyha kész.','a fehér munkalap áttörlése','könnyek letörlése','business','none'),
(4826,'hu','Túlcsordul a gát!','Túlcsordul a medence!','túlcsorduló gát','kiszáradt gát nyáron','dramatic','exclamation'),
(4827,'hu','Ez a narancssárga festék vastag.','Ez a kék festék vastag.','vastag festékcsík','friss festékréteg','chill','none'),
(4828,'hu','A fal fele már zöld.','A fal fele már kék.','félig zöld fal','zöld kerti fal','business','none'),
(4829,'hu','Festékszilánkok potyognak le.','Festékcseppek potyognak le.','régi festék szilánkjai','régi üveg szilánkjai','chill','none'),
(4830,'hu','Két búvár úszik felfelé.','Három búvár úszik felfelé.','úszás fel a felszínre','átúszni a folyót','chill','none'),
(4831,'hu','Micsoda nagy ütés!','Micsoda nagy kihagyás!','ütés az ütőállványról','sláger a rádióban','dramatic','exclamation'),
(4832,'hu','Keskeny gerinc a felhők fölött.','Széles gerinc a felhők fölött.','keskeny havas gerinc','zöld dombok gerince','dramatic','none'),
(4833,'hu','Úgy gördeszkázik a tengerpart mentén, mintha semmiség lenne.','Úgy biciklizik a tengerpart mentén, mintha semmiség lenne.','gördeszkázás a tengerparti úton','vitorlázás a tengerpart mentén','flirt','cliche'),
(4834,'hu','Ez a játékcsata epikus!','Ez a kártyacsata epikus!','pörgő játék','játékautó','slang','exaggeration'),
(4835,'hu','Üldözés zajlik a városban!','Felvonulás zajlik a városban!','városi utca éjjel','városi utca délben','dramatic','exclamation'),
(4836,'hu','Egy medvét fűrészel ki.','Egy lovat fűrészel ki.','medve kifűrészelése fából','deszka kettéfűrészelése','chill','none'),
(4837,'hu','Az asztal tele van étellel.','Az asztal tele van könyvekkel.','étellel teli asztal','társasjátékokkal teli asztal','chill','none'),
(4838,'hu','Labdát dob.','Labdát rúg.','strandlabdát dobni','bulit dobni','chill','none'),
(4839,'hu','Egyedül is megmozdít egy autót!','Egyedül is megmozdít egy buszt!','nehéz dolgok mozgatása','költözés új városba','dramatic','exaggeration'),
(4840,'hu','Elbújtak a meglepetés kedvéért!','Elbújtak egy kutya elől!','elbújni a kanapé mögött','elbújni az ágy alatt','dramatic','exclamation'),
(4841,'hu','Megtalálta a kulcsot! Végre!','Megtalálta a telefont! Végre!','kis kulcs megtalálása','kis kulcs elvesztése','dramatic','exclamation'),
(4842,'hu','Egy régi autón dolgozik.','Egy régi biciklin dolgozik.','autómotoron dolgozni','irodában dolgozni','chill','none'),
(4843,'hu','Ez aztán egy nagy, fából készült szerkezet!','Ez aztán egy nagy, fémből készült szerkezet!','egy ház fa szerkezete','a mondat szerkezete','dramatic','exclamation'),
(4844,'hu','Félbevágta a tököt.','Félbevágta a tortát.','félbevágott tök','fél tökös pite','chill','none'),
(4845,'hu','Kezek varrják a kelmét.','Kezek vágják a kelmét.','kelme varrása','törlés egy ronggyal','chill','none'),
(4846,'hu','Vasalás kész: egy sima lepedő.','Vasalás kész: egy sima törölköző.','fehér lepedő vasalása','probléma elsimítása','business','none'),
(4847,'hu','Milyen tiszta a padló!','Milyen koszos a padló!','a padló felmosása','a padló festése','dramatic','exclamation'),
(4848,'hu','Nézd, mit termesztett: egy tököt!','Nézd, mit termesztett: egy dinnyét!','nagy tök termesztése','hosszú szakáll növesztése','dramatic','exclamation'),
(4849,'hu','Nyár: víz mindenkinek!','Nyár: torta mindenkinek!','nyári kerti locsoló','nyári strandnap','slang','exclamation'),
(4850,'hu','Fényképezőgépet szegez ránk!','Telefont szegez ránk!','fényképezőgép állványon','fényképezőgép egy boltban','dramatic','exclamation'),
(4851,'hu','Egy ősi táblát talált!','Egy ősi kardot talált!','ősi kőtábla','ősi hajó','dramatic','exclamation'),
(4852,'hu','Hatalmas fogaskerekek a végén!','Apró fogaskerekek a végén!','egymásba kapó hatalmas fogaskerekek','bicikli fogaskerekei','dramatic','exclamation'),
(4853,'hu','Az a fogaskerék szuper pici.','Az a csavar szuper pici.','pici réz fogaskerék','pici konyha','low_iq','none'),
(4854,'hu','Egy óriási problémát old meg!','Egy apró problémát old meg!','matekfeladat megoldása a táblán','bűntény megoldása','dramatic','exclamation'),
(4855,'hu','Minden szóra emlékezni akar a világon.','Minden szót el akar felejteni a világon.','emlékezni a kártyák szavaira','emlékezni egy születésnapra','dramatic','exaggeration'),
(4856,'hu','A tanár egy papírfal mögött van.','A tanár egy könyvfal mögött van.','dolgozatokat javító tanár','könyvet olvasó tanár','dramatic','exaggeration'),
(4857,'hu','A munkás megrázta, és most működik!','A munkás megrúgta, és most működik!','munkás szkennerrel','munkás kalapáccsal','low_iq','cheap_quality'),
(4858,'hu','Óriási a dominóspirálja!','Óriási a dominótornya!','dominóspirál','spirálfüzet','slang','exaggeration'),
(4859,'hu','A darabok elfoglalták a szobát.','A játékok elfoglalták a szobát.','kirakós darabok illesztése','egy darab torta','dramatic','exaggeration'),
(4860,'hu','A tabletta buborékokat termel.','A tabletta szikrákat termel.','buborékok egy pohárban','rágógumi-buborék','nerd','none'),
(4861,'hu','Pszt, figyelmesen hallgat!','Pszt, alszik!','egy madarat hallgat','a tanárt hallgatja','dramatic','exclamation'),
(4862,'hu','Nem tud tököt választani.','Nem tud kalapot választani.','választás két alma közül','választás két ruha közül','gossip','guessing'),
(4863,'hu','A terve az egész falat betölti.','A terve az egész asztalt betölti.','terv a falon','egy ház terve','business','none'),
(4864,'hu','A zenekar egyenruhában van!','A zenekar pizsamában van!','egyenruhás zenekar','iskolai egyenruha','dramatic','exclamation'),
(4865,'hu','A fényképezőgépén hosszú lencse van.','A fényképezőgépén rövid lencse van.','hosszú kameralencse','lencse a szemüvegében','nerd','none'),
(4866,'hu','Egy drón lebeg alacsonyan. Szép felvétel!','Egy madár lebeg alacsonyan. Szép felvétel!','drón a fű fölött','drón a stúdióban','dramatic','exclamation'),
(4867,'hu','Mindkét hüvelykujjával felfelé mutat.','Mindkét hüvelykujjával lefelé mutat.','két hüvelykujj felfelé','hüvelykujj a gitárhúrokon','chill','none'),
(4868,'hu','Beprogramozták. Működik!','Beprogramozták. Elromlott!','új app programozása','mosógép beprogramozása','dramatic','exclamation'),
(4869,'hu','A tervezés az egész élete.','A foci az egész élete.','logóterv','tetoválásterv','chill','exaggeration'),
(4870,'hu','Az arca csupa hab.','Az arca csupa sár.','hab az arcán','hab a sörön','chill','none'),
(4872,'hu','Micsoda „szigorú” értékelés: mindig öt csillag.','Micsoda „szigorú” értékelés: mindig egy csillag.','ötcsillagos értékelés','egycsillagos értékelés','ironic','understatement'),
(4873,'hu','Teljesen elmerült a tanulásban.','Teljesen eltévedt az erdőben.','elmerülve a tanulásban','orvosi tanulmány','chill','none'),
(4874,'hu','Megállt egy közlekedési lámpánál.','Megállt egy forgalmas benzinkútnál.','megállva a közlekedési lámpánál','piros közlekedési lámpa','chill','none'),
(4875,'hu','A csapat pakolja a kamiont.','A csapat pakolja a hajót.','dobozokkal teli kamion','homokkal teli kamion','business','none'),
(4876,'hu','Esik, de ő mosolyog.','Esik, de ő sír.','kiskutyára mosolyog','a buszsofőrre mosolyog','chill','none'),
(4877,'hu','Most már mindenki ül!','Most már mindenki áll!','ülés egy teli teremben','ülés egy üres buszon','dramatic','exclamation'),
(4878,'hu','Ez a srác fejest ugrik a mólóról.','Ez a srác fejest ugrik a hajóról.','fejes a fa mólóról','horgászat a fa mólóról','slang','none'),
(4879,'hu','Egy autót emel ezen a versenyen!','Egy biciklit emel ezen a versenyen!','erős nők versenye','tévés énekverseny','dramatic','exclamation'),
(4880,'hu','Vizes palack a tetőről? Durva.','Egy szék a tetőről? Totál durva.','nagy vizes palack','cumisüveg babának','slang','exclamation'),
(4881,'hu','Az emberek egy buszt tolnak!','Az emberek egy vonatot tolnak!','városi busz tolása','városi busz elérése','dramatic','exclamation'),
(4882,'hu','Egy egész légi járművet húznak!','Egy egész kamiont húznak!','hatalmas légi jármű húzása','felszálló légi jármű','dramatic','exclamation'),
(4883,'hu','Az ajtók zöld dombokat fednek fel.','Az ajtók kék tengert fednek fel.','zöld völgyet fed fel','titkot fed fel','chill','none'),
(4884,'hu','Mindenki felfelé mutat!','Mindenki lefelé mutat!','az égre mutat','a térképre mutat','dramatic','exclamation'),
(4885,'hu','Felfelé mennek az utcán.','Felfelé mennek a lépcsőn.','napos macskaköves utca','forgalmas bevásárlóutca','business','none'),
(4886,'hu','Olyan meredek az ösvény!','Olyan sík az ösvény!','meredek füves ösvény','meredek ár','dramatic','none'),
(4887,'hu','Hűha, milyen keskeny ez az ösvény!','Hűha, milyen széles ez az ösvény!','keskeny kanyonösvény','keskeny bolti ajtó','dramatic','exclamation'),
(4888,'hu','Mindenki mezítláb sétál!','Mindenki mezítláb fut!','mezítláb sétálni a homokban','mezítláb forró köveken','gossip','exaggeration'),
(4889,'hu','A platform kör alakú.','A platform négyzet alakú.','kör alakú fehér platform','körlevél','business','none'),
(4890,'hu','Mindenki a búgócsiga körül köröz.','Mindenki a fa körül köröz.','körözés egy pörgő csiga körül','körözés egy focilabda körül','chill','none'),
(4891,'hu','Az egész kampusz oldalra dől!','Az egész kampusz ugrál!','diákok a kampusz gyepén','kampusz a hóban','dramatic','exaggeration'),
(4892,'hu','Ez a rövidnadrág iszonyú gyors!','Ez az uszony iszonyú gyors!','színes úszó-rövidnadrág','rövidnadrág focihoz','slang','exaggeration'),
(4893,'hu','Zsúfolt egészen a tetejéig!','Csak alul zsúfolt!','zsúfolt baseballstadion','zsúfolt éjszakai busz','dramatic','exclamation'),
(4894,'hu','Mindenki mozdulatlan. Teljesen normális.','Mindenki táncol. Teljesen normális.','mozdulatlan diákok a teremben','mozdulatlan víz a tóban','ironic','understatement'),
(4895,'hu','Egymással szemközti oldalon állnak.','Ugyanazon az oldalon állnak.','szemközti oldalakon','az ellenkező irány','chill','none'),
(4896,'hu','Mindenkinek hosszú az árnyéka!','Mindenkinek hosszú a sála!','hosszú árnyékok a köveken','árnyékok a falon','slang','none'),
(4897,'hu','Mindenki csatlakozik az öleléshez!','Mindenki csatlakozik a tánchoz!','csatlakozás egy csoportos öleléshez','csatlakozás egy tánckurzushoz','dramatic','exaggeration'),
(4898,'hu','Üvegpaneleket szerelnek be.','Fapaneleket szerelnek be.','üvegpanelek beszerelése','üvegpanelek tisztítása','chill','none'),
(4899,'hu','Ez a retek hatalmas, tesó!','Ez a dinnye hatalmas, tesó!','hatalmas fehér retek','hatalmas tök','slang','exclamation'),
(4900,'hu','A magas halom ledőlt!','A magas fa ledőlt!','magas halom raklap','egy halom palacsinta','dramatic','exclamation'),
(4901,'hu','Kék tenger, kék ég, nagy ugrás.','Kék medence, kék ég, nagy ugrás.','fejes a kék vízbe','fejes egy kék medencébe','slang','none'),
(4902,'hu','Egy tengeralattjáró, aztán egy bálna. Ússz gyorsabban!','Egy tengeralattjáró, aztán egy cápa. Ússz gyorsabban!','tengeralattjáró egy tóban','tengeralattjáró a kikötőben','dramatic','guessing'),
(4903,'hu','Mindenki összezsúfolódik a téren. Miért?','Az autók összezsúfolódnak a téren. Miért?','összezsúfolódás a téren','tolongás egy színpad körül','gossip','guessing')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
