begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(4904,'hu','Azok a székek kicsit kockázatosnak tűnnek.','Azok az asztalok kicsit kockázatosnak tűnnek.','kockázatos széktorony','kockázatos lóversenyfogadás','ironic','understatement'),
(4905,'hu','A híd átível a kanyon felett.','A híd átível az utca felett.','kanyont átívelő boltívek','rövid figyelmi idő','business','none'),
(4906,'hu','Egyedül a sátor élte túl.','Egyedül a boltív élte túl.','fehér partisátor','sátor az erdőben','dramatic','exaggeration'),
(4907,'hu','Nagy hangszóró, táncoló víz.','Nagy hangszóró, táncoló tej.','nagy klubhangszóró','előadó egy konferencián','slang','exaggeration'),
(4908,'hu','Valaki meghajlít egy ágat.','Valaki levág egy ágat.','almafaág meghajlítása','egy bankfiók','chill','none'),
(4909,'hu','Úgy filmezik, mintha híres lenne.','Úgy festik, mintha híres lenne.','egy percig híres','híres a dalairól','chill','exaggeration'),
(4910,'hu','Ordít a szurkolói sáljában!','Alszik a szurkolói sáljában!','csíkos szurkolói sál','meleg téli sál','dramatic','exclamation'),
(4911,'hu','Képzeld, egy nő az új tulajdonos!','Képzeld, egy férfi az új tulajdonos!','a kávézó új tulajdonosa','a kávézó új szakácsa','gossip','exclamation'),
(4912,'hu','Az oktató rúg.','Az oktató táncol.','egy karateoktató','egy autósoktató','chill','none'),
(4913,'hu','Karkötőt csatol fel.','Nyakláncot csatol fel.','fonott gyöngyös karkötő','aranykarkötő vásárlása','chill','none'),
(4914,'hu','Mindenki imádja a gitáros srácot.','Mindenki imádja a dobos srácot.','akusztikus gitáron játszik','akusztikus gitárt javít','gossip','guessing'),
(4915,'hu','Vállt vállnak vetve sétálnak.','Vállt vállnak vetve ülnek.','kar a vállakon','táska a vállon','chill','none'),
(4916,'hu','Megcsináltuk! Két kerékpár, egy naplemente.','Megcsináltuk! Két roller, egy naplemente.','kerékpárok a mólón','kerékpárok a vonaton','dramatic','exclamation'),
(4917,'hu','A piros lelőtte a kéket. Megvagy!','A kék lelőtte a pirosat. Megvagy!','festéket lő egy játékosra','kosárra lő','dramatic','exclamation'),
(4918,'hu','Felmegy a lépcsőn.','Lecsúszik a lépcsőn.','fel a lépcsőn csomagokkal','le a lépcsőn egyedül','chill','none'),
(4919,'hu','Jelentkezett a tagságra.','Jelentkezett a jógára.','fotóklub-tagság','edzőtermi tagsági kártya','chill','none'),
(4920,'hu','A közösség ujjong!','A közösség sír!','közösségi kert táblája','online közösség','slang','exclamation'),
(4921,'hu','Az ösvény tele van gyökerekkel.','Az ösvény tele van hóval.','göröngyös erdei ösvény','lábnyomok sora','chill','none'),
(4922,'hu','A házigazda üdvözli a vendégeit.','A házigazda levegőnek nézi a vendégeit.','poharát emelő házigazda','talkshow-műsorvezető','business','none'),
(4923,'hu','Két vendéget ültet le.','Négy vendéget ültet le.','fiatal pár leültetése','leül a bárpulthoz','chill','none'),
(4924,'hu','Ismerős arcot lát.','Ismerős kutyát lát.','ismerős arc','ismerős dal','chill','none'),
(4925,'hu','Egy beteget ápol.','Egy kisbabát ápol.','kórházi beteg ápolása','kert ápolása','business','none'),
(4926,'hu','A fogorvosnál tükör van.','A fogorvosnál telefon van.','fogorvos tükörrel','fogat húzó fogorvos','chill','none'),
(4927,'hu','Az ügyvéd kezet ráz.','Az ügyvéd valakinek a kezét fogja.','ügyvéd aktatáskával','ügyvéd laptoppal','chill','none'),
(4928,'hu','Egyedül javította meg a szivárgást!','Egyedül javította meg az autót!','csöpögő mosdó javítása','lerobbant autó javítása','dramatic','exclamation'),
(4929,'hu','Találd ki, ki kapta a legjobb jegyet!','Találd ki, ki kapott rossz jegyet!','a legjobb jegy','rossz jegy','gossip','exclamation'),
(4930,'hu','A jutalma egy aranycsillag!','A jutalma egy ezüstcsillag!','aranycsillag jutalmul','jutalom az elveszett kulcsokért','dramatic','exclamation'),
(4931,'hu','Egy ábrát magyaráz.','Egy verset magyaráz.','krétával rajzolt ábra','tankönyvi ábra','nerd','none'),
(4932,'hu','Menő sapka! Taxit kormányoz.','Menő sapka! Hajót kormányoz.','sárga taxit kormányoz','sárga hajót kormányoz','flirt','none'),
(4933,'hu','Egyik keze végig a kormánykeréken marad.','Egyik keze végig a telefonon marad.','busz kormánykereke','busz pótkereke','business','none'),
(4934,'hu','Headsetet vesz fel.','Sisakot vesz fel.','zöld pilóta-headset','VR-headset játékhoz','chill','none'),
(4935,'hu','Megérinti az iránytűt.','Megérinti a rádiót.','réz hajóiránytű','körző körök rajzolásához','nerd','none'),
(4936,'hu','Egy konyhában főz.','Egy kertben főz.','profi konyha','otthoni konyha','chill','none'),
(4937,'hu','Csenget a pultcsengővel.','Csenget a kapucsengővel.','csenget a pultnál','felhívja egy barátját','business','none'),
(4938,'hu','Ez egy nagyon elfoglalt pincérnő.','Ez egy nagyon elfoglalt ápolónő.','pincérnő a teraszon','pincérnő a konyhában','chill','none'),
(4939,'hu','Aranyszínű héj. Szép munka, pék!','Égett héj. Remek munka, pék!','aranyszínű croissant-ok','aranyszínű jegygyűrű','flirt','none'),
(4940,'hu','A hentes húst csomagol.','A hentes ajándékokat csomagol.','steaket csomagoló hentes','csirkét daraboló hentes','chill','none'),
(4941,'hu','A tűzoltó megmentett egy macskát!','A tűzoltó megmentett egy kutyát!','macskát mentő tűzoltó','tüzet oltó tűzoltó','dramatic','exclamation'),
(4942,'hu','Egy táska az egész poggyász? Legenda!','Öt táska az egész poggyász? Legenda!','poggyász a vállán','poggyász egy csomagkocsin','slang','exclamation'),
(4943,'hu','Imádja ezt a sok dicséretet.','Utálja ezt a sok dicséretet.','dicséret a stábtól','dicséret a tanárától','gossip','guessing'),
(4944,'hu','Reflektorfény, rózsák és egy arany báli ruha!','Reflektorfény, rózsák és egy piros báli ruha!','hosszú halványarany báli ruha','menyasszonyi ruha felpróbálása','dramatic','exclamation'),
(4945,'hu','A mikrofonba énekel.','Egy telefonba énekel.','mikrofonba énekel','kórusban énekel','chill','none'),
(4946,'hu','A lófarka is táncol.','A sálja is táncol.','lengő lófarok','lófarok sapka alatt','chill','exaggeration'),
(4947,'hu','Kész a portré. Kezek a magasba!','Kész a tájkép. Kezek a magasba!','elkészült portré','macskaportré','dramatic','none'),
(4948,'hu','Sminkelés városi látképpel. Puccos.','Sminkelés tengerparti kilátással. Puccos.','városi látkép mögötte','városi látkép naplementekor','gossip','none'),
(4949,'hu','Havas csúcsok: csodás tájkép.','Homokdűnék: csodás tájkép.','hegyi tájkép a csúcsról','tájkép a vonatablakból','chill','none'),
(4950,'hu','Kéz a csípőn. Nagyon komoly.','Kéz a fejen. Nagyon komoly.','kezek a csípőn','csípőringatás','ironic','understatement'),
(4951,'hu','Hazaért, és a kutya boldog!','Hazaért, és a macska boldog!','hazaérkezés a kutyához','munkába indul hazulról','dramatic','exclamation'),
(4952,'hu','Nagyon hiányzott neki az ágya.','Nagyon hiányzott neki az autója.','ledől az ágyra','beveti az ágyat','dramatic','guessing'),
(4953,'hu','Fotoszintézist remél.','Zivatart remél.','csírát remél','szivárványt remél','nerd','exaggeration'),
(4954,'hu','A látogatás nagyon boldoggá teszi!','A látogatás nagyon szomorúvá teszi!','kórházi látogatás','állatkerti látogatás','dramatic','exclamation'),
(4955,'hu','Itt csak a szekrények rendesek.','Itt csak az emeletes ágyak rendesek.','szürke öltözőszekrények sora','szekrény az uszodában','ironic','exaggeration'),
(4956,'hu','A recepcióhoz sétál.','A konyhához sétál.','a hostel recepciós pultja','esküvői fogadás','chill','none'),
(4957,'hu','A szállodaárak az olcsótól 2000 euróig terjednek.','A szállodaárak az olcsótól 20 euróig terjednek.','háromféle szálloda','szálloda a tengerparton','business','cheap_quality'),
(4958,'hu','Kunyhóból üvegvillába!','Kunyhóból favillába!','hatalmas üvegvilla','kiadó nyaralóvilla','dramatic','exclamation'),
(4959,'hu','Házikó napraforgóval.','Házikó almafával.','kis faházikó','házikó a tóparton','chill','none'),
(4960,'hu','Ölelgetik egymást az érkezési csarnokban!','Verekednek az érkezési csarnokban!','csoportos ölelgetés az érkezőknél','plüssmaci ölelgetése','dramatic','exclamation'),
(4961,'hu','A háziállat egy játékra vadászik.','A háziállat egy labdára vadászik.','vadászó háziállat','alvó háziállat','chill','none'),
(4962,'hu','Távcsövet használ. Szarvasriadó!','Teleszkópot használ. Szarvasriadó!','távcsövön át néz','távcső az operában','dramatic','exclamation'),
(4963,'hu','Megütötte az ujját, aztán a lábujját!','Megütötte az ujját, aztán a fülét!','sérült ujj','ujjal mutogat rá','dramatic','exclamation'),
(4964,'hu','Levest kóstolni, utána virág. Ügyes húzás.','Levest kóstolni, utána csoki. Ügyes húzás.','levest kóstol a kanálról','bort kóstol egy buliban','flirt','cliche'),
(4965,'hu','A fürdőszobai rutin kész.','A konyhai rutin kész.','fogmosás a fürdőszobában','éneklés a fürdőszobában','business','none'),
(4966,'hu','A jég két darabra hasadt szét.','A jég három darabra hasadt szét.','jégtábla széthasítása','farönk széthasítása','nerd','none'),
(4967,'hu','Egy szkenner ellenőrzi a személyazonosságát.','Egy szkenner ellenőrzi a poggyászát.','személyazonosság ellenőrzése','személyazonosság elrejtése','nerd','none'),
(4968,'hu','Megkapta az új személyi kártyáját!','Megkapta az új telefonját!','új személyazonosító kártya','új születésnapi kártya','slang','exclamation'),
(4969,'hu','A kávézóban nála a könyv nyer.','A kávézóban nála a telefon nyer.','olvasás egy kávézóasztalnál','munka egy kávézó konyháján','gossip','banter'),
(4970,'hu','Tűzijáték a függetlenségért!','Gyertyák a függetlenségért!','a függetlenség ünneplése','harc a függetlenségért','dramatic','none'),
(4971,'hu','Tűzijáték világítja meg a kupolát.','Tűzijáték világítja meg a hidat.','tűzijáték egy kupola felett','tűzijáték egy tó felett','chill','none'),
(4972,'hu','Micsoda hazafias este!','Micsoda hazafias reggel!','hazafias tömeg','hazafias katonai parádé','dramatic','exclamation'),
(4973,'hu','Egy emlékműnél pózol.','Egy vízesésnél pózol.','póz egy fehér emlékműnél','emlékmű egy hegyen','chill','none'),
(4974,'hu','Az eladó profin tölt.','Az eladó profin zsonglőrködik.','teát töltő eladó','virágeladó','flirt','cliche'),
(4975,'hu','A csaj stílusa annyira más!','A srác stílusa annyira más!','más, mint a tömeg','más, mint a nővére','flirt','exclamation'),
(4976,'hu','Vízben gázol.','Hóban gázol.','gázolás a rizsföldeken','gázolás mély hóban','chill','none'),
(4977,'hu','Egy kéz mutatja az utat.','Egy kutya mutatja az utat.','kinyújtott nyitott kéz','rizzsel teli kéz','chill','none'),
(4978,'hu','A szakács a tűzzel játszik!','A szakács a jéggel játszik!','szakács a woknál','szakács a grillnél','slang','cliche'),
(4979,'hu','Az egész iroda beteg!','Az egész iroda alszik!','köhögés az irodában','éneklés az irodában','dramatic','exaggeration'),
(4980,'hu','Mélyen lélegeznek be.','Hangosan kiabálnak.','friss levegőt lélegezni','víz alatt lélegezni','chill','none'),
(4981,'hu','Mindenki megkapta a vakcinát. Hurrá!','Senki nem kapta meg a vakcinát. Hurrá!','vakcina a felkarba','vakcina a lábba','dramatic','exclamation'),
(4982,'hu','A bokáját fogja.','A fejét fogja.','sérült boka','karkötő a bokán','chill','none'),
(4983,'hu','A tiszt mindent átvizsgál, még a furgon alját is.','A tiszt mindent átvizsgál, még a busz alját is.','furgont ellenőrző tiszt','tiszt egy hajón','dramatic','exaggeration'),
(4984,'hu','Aktatáskával a kézben korcsolyázik!','Kávéspohárral a kézben korcsolyázik!','korcsolyázás aktatáskával','papírokkal teli aktatáska','gossip','exclamation'),
(4985,'hu','A képernyők rögzítve vannak.','A tükrök rögzítve vannak.','képernyők falra rögzítése','megbeszélés időpontjának rögzítése','business','none'),
(4987,'hu','Bemutatta a projektet. A kávé nyert.','Bemutatta a projektet. A pizza nyert.','bemutatja a munkáját','tévéműsort vezet','ironic','exaggeration'),
(4988,'hu','Kezdődik a támadás!','Kezdődik a piknik!','középkori támadás','szívroham','dramatic','exclamation'),
(4989,'hu','Lerohannak a dombról!','Lerohannak az úton!','roham lefelé a dombon','gurulás lefelé a dombon','dramatic','exclamation'),
(4990,'hu','Nehéz vasalót használ.','Nehéz kalapácsot használ.','nehéz gőzölős vasaló','vasserpenyő','chill','none'),
(4991,'hu','Micsoda rendetlen ruhakupac!','Micsoda rendetlen könyvkupac!','rendetlen ruhakupac','rendetlen konyhaasztal','dramatic','exclamation'),
(4992,'hu','Annyi vasalnivaló! Nagyon elfoglalt.','Annyi főznivaló! Nagyon elfoglalt.','a vasalással elfoglalt','a mosogatással elfoglalt','dramatic','exclamation'),
(4993,'hu','Teljesen egyedül van a tavon.','Teljesen egyedül van a tengerparton.','egyedül egy apró szigeten','egyedül egy nagyvárosban','chill','none'),
(4994,'hu','Fakanalat használ.','Fémkanalat használ.','hosszú fakanál','fa vágódeszka','chill','none'),
(4995,'hu','Szökőkút szoborral.','Szökőkút órával.','kőszobros szökőkút','esküvői jégszobor','chill','none'),
(4996,'hu','A galambok imádják a fagyitölcsérét.','A sirályok imádják a fagyitölcsérét.','fagyitölcsér','narancssárga terelőkúp','gossip','guessing'),
(4997,'hu','Hangos a nevetése.','Halk a nevetése.','nevetés a Colosseumnál','nevetés Párizsban','chill','none'),
(4998,'hu','Az alagút kapukból áll.','Az alagút fákból áll.','szentélykapukból álló alagút','alagút a tenger alatt','chill','none'),
(4999,'hu','Egy kardforgatóval harcol.','Egy íjásszal harcol.','harc egy kardforgatóval','harc egy csúnya megfázással','chill','none'),
(5000,'hu','Tökéletesek a vékony szeletei.','Tökéletesek a vastag szeletei.','vékony halszeletek','vékony kenyérszeletek','flirt','none'),
(5001,'hu','Megérte ezért a tájképért.','Megérte ezért a strandért.','hegyi tájkép','tájképfestmény','slang','cliche'),
(5002,'hu','Szürkületkor ugranak be.','Délben ugranak be.','erdei tó szürkületkor','szürkület a nagyvárosban','chill','none'),
(5003,'hu','Egy felfedező utat vág magának.','Egy felfedező fát vág.','felfedező machetével','felfedező térképpel','chill','none'),
(5004,'hu','A kenguru előre ugrik.','A kenguru hátra ugrik.','ugrani a homokon át','kiugrani az ágyból','chill','none'),
(5005,'hu','Ebben az öbölben mindent lát.','Ebben a parkban mindent lát.','hajók egy csendes öbölben','jéggel teli öböl','gossip','guessing'),
(5006,'hu','Keményen dolgozik a vízforralója.','Keményen dolgozik a kenyérpirítója.','víz forr a vízforralóban','vízforraló a tűzön','chill','exaggeration'),
(5007,'hu','Igen! A kulcsa a zárban van!','Igen! A kulcsa az autóban van!','kulcs a zárban','zár egy biciklin','dramatic','exclamation'),
(5008,'hu','Kinyitotta a faajtót.','Kinyitotta a garázsajtót.','kinyitni a faajtót','feloldani egy telefont','chill','none'),
(5009,'hu','A gyerek lecsúszik.','A gyerek felmászik.','gyerek a csúszdán','gyerek a hintán','chill','none'),
(5010,'hu','Éljen a király!','Éljen a királynő!','király egy erkélyen','király lóháton','dramatic','cliche'),
(5011,'hu','Az öreg pár csókolózik, de cuki!','Az öreg pár táncol, de cuki!','csókolózó öreg pár','táncoló öreg pár','gossip','exclamation'),
(5012,'hu','Párizs tele van románccal!','Párizs tele van hóval!','románc Párizsban','romantikus regény','dramatic','exaggeration'),
(5013,'hu','Az olcsó konyha régi.','Az olcsó konyha hatalmas.','olcsó, régi konyha','olcsó, gyors autó','chill','none'),
(5014,'hu','A gazdag szakácsnak van a legjobb kilátása.','A gazdag szakácsnak van a legjobb kutyája.','egy gazdag ember konyhája','egy gazdag ember autója','gossip','none'),
(5015,'hu','Házi kenyér, kézzel gyúrva.','Házi tészta, kézzel gyúrva.','házi kenyércipó','házi lekvár üvegekben','chill','none'),
(5016,'hu','Behajlítja a térdét.','Behajlítja a karját.','csupasz térdek guggolásban','fél térdre ereszkedve','business','none'),
(5017,'hu','Felvágott zöldségek szivárványa!','Felvágott gyümölcsök szivárványa!','felvágott zöldségek sorokban','vágott virágok vázában','dramatic','exclamation'),
(5018,'hu','Az a kaja nagyon ízletesnek tűnik!','Az a leves nagyon ízletesnek tűnik!','ízletes tál rizs','ízletes szelet torta','gossip','exclamation'),
(5020,'hu','Két ember kell egy izzó kicseréléséhez!','Öt ember kell egy izzó kicseréléséhez!','kiégett izzó kicserélése','defektes gumi kicserélése','low_iq','cliche'),
(5021,'hu','Milyen elegáns hölgy tölti a teát.','Milyen elegáns hölgy tölti a bort.','hölgy főkötőben','hölgy lóháton','flirt','none'),
(5022,'hu','Ragyog a csillár!','Ragyog a tükör!','ragyogó csillár','ragyogó cipő','dramatic','exclamation'),
(5023,'hu','Egy repülőgépnek ujjong!','Egy vonatnak ujjong!','alacsonyan leszálló repülőgép','felszálló repülőgép','dramatic','exclamation'),
(5024,'hu','Nála van az összes szótár!','Nála van az összes szakácskönyv!','egy halom szótár','szótáralkalmazás','dramatic','exaggeration'),
(5025,'hu','OMG, ez a vicc túl vicces!','OMG, ez a tanóra túl vicces!','vicc a telefonon','vicc a tanártól','gossip','exclamation'),
(5026,'hu','Ma nagyon vicces a telefonja.','Ma nagyon vicces a könyve.','nagyon vicces egy előadáson','nagyon vicces egy esküvőn','gossip','none'),
(5027,'hu','A bíró a kalapácsát használja.','A bíró a telefonját használja.','bíró kalapáccsal','parókás bíró','business','none'),
(5028,'hu','Nehéz ügy? Csak pár könyv.','Nehéz ügy? Csak pár toll.','nehéz bírósági ügy','nehéz vizsga','ironic','understatement'),
(5029,'hu','A srác gesztusa azt mondja: nyertem!','A lány gesztusa azt mondja: nyertem!','győztes ökölgesztus','durva kézgesztus','dramatic','guessing'),
(5030,'hu','A jelmezén minden szín ott van!','A kalapján minden szín ott van!','szivárványos tolljelmez','halloweeni jelmez','gossip','exaggeration'),
(5031,'hu','A vezető előre mutat.','A vezető leül.','vezető egy hegyen','vezető egy tengerparton','chill','none'),
(5032,'hu','Elöl vezeti a csapatot.','Visszafelé vezeti a csapatot.','elöl halad a csoport előtt','előre tervez az útra','business','none'),
(5033,'hu','A szomszédok hallják ezeket a dobokat.','A szomszédok hallják ezeket a kürtöket.','veri a dobokat','dobszóló','ironic','guessing'),
(5034,'hu','Otthon mindent kiönt!','Otthon mindent odaéget!','kiöntött tej az asztalon','kávét önt ki a laptopra','ironic','exaggeration'),
(5035,'hu','Ennek a zsonglőrnek van tehetsége!','Ennek az énekesnek van tehetsége!','tehetség a zsonglőrködéshez','tehetségkutató','slang','exclamation'),
(5036,'hu','A lány tanít, a srác tanul. Lassan.','A srác tanít, a lány tanul. Lassan.','zsonglőrködni tanul','táncolni tanul','chill','banter'),
(5037,'hu','Egy párizsi járdán van.','Egy párizsi hídon van.','széles, kövezett járda','járdai kávézóasztal','chill','none'),
(5038,'hu','Egyenletes tempó felfelé a kínai nagy falon.','Egyenletes tempó lefelé a kínai nagy falon.','egyenletes futótempó','lassú sétatempó','chill','none'),
(5039,'hu','Kinyitja a kalitkákat.','Becsukja a kalitkákat.','madárkalitkák kinyitása','madárkalitkák takarítása','chill','none'),
(5040,'hu','Fotel? Biciklin? Persze.','Kanapé? Biciklin? Persze.','sárga bársonyfotel','fotel egy autóban','ironic','understatement'),
(5041,'hu','Fehér villanás világítja meg a tetőt.','Zöld villanás világítja meg a tetőt.','vakító fehér villanás','vakuvillanás egy szobában','dramatic','none'),
(5042,'hu','A lábnap fájdalmas volt!','A karnap fájdalmas volt!','fájdalmasan merev lábak','fájdalmas leégés','dramatic','exclamation'),
(5043,'hu','Az oroszlán nem csendes.','Az oroszlán nem egyedül van.','nem túl csendes oroszlán','csendes oroszlán','ironic','understatement'),
(5044,'hu','Az ajtón keresztül is hall.','A falon keresztül is hall.','hallani az ajtón át','hallani a csengőt','chill','none'),
(5045,'hu','A hangszórók nagy hangot adnak!','A dobok nagy hangot adnak!','hang egy magnóból','hang az autórádióból','low_iq','exclamation'),
(5046,'hu','A televíziótól összerezzent!','A televíziótól elsírta magát!','televíziót néz','televíziót javít','slang','blaming_someone'),
(5047,'hu','Ma este senki nem hagyja el a nappalit.','Ma este senki nem hagyja el a konyhát.','hangulatos nappali','a nappali takarítása','gossip','guessing'),
(5048,'hu','Nagy lakat, az ajtók még mindig zártak.','Nagy lakat, az ajtók tárva-nyitva.','szorosan zárt ajtók','szorosan zárt szemek','ironic','understatement'),
(5049,'hu','Becsukja a bejárati ajtót.','Becsukja a garázsajtót.','bejárati ajtó becsukása','bolt bezárása','chill','none'),
(5050,'hu','Veszített, és a vendégek elmentek.','Nyert, és a vendégek elmentek.','választást veszít','elveszíti az autókulcsát','gossip','none'),
(5051,'hu','Elveszített valamit. Talán az útlevelét?','Megtalált valamit. Talán az útlevelét?','valami fontos elveszítése','focimeccs elveszítése','gossip','guessing'),
(5052,'hu','A táskák nem könnyűek.','A székek nem könnyűek.','nem könnyű bőröndök','könnyű kézipoggyász','chill','understatement'),
(5053,'hu','A címkén az ő fotója van.','A címkén a kutyája van.','címke a fotójával','címke egy befőttesüvegen','business','none'),
(5054,'hu','A tesó fél házat felemel.','A tesó fél sátrat felemel.','dobozok felemelése egy furgonba','súlyemelés edzőteremben','slang','exaggeration'),
(5056,'hu','A szobalány törölközőhattyút hajtogatott.','A szobalány törölközőkutyát hajtogatott.','törölközőt hajtogató szobalány','szobalány egy kastélyban','chill','none'),
(5058,'hu','A kisfiú most már imádja a postást.','A kisfiú most már imádja a tanárt.','postás levelekkel','postás kutyával','gossip','guessing'),
(5059,'hu','Rengeteg levelet kapott!','Rengeteg virágot kapott!','egy köteg levél','levél az iskolából','slang','exclamation'),
(5060,'hu','Ebben a videóban csak férfiak vannak.','Ebben a videóban csak lányok vannak.','férfiak minden korosztályból','férfiak egy focicsapatban','gossip','none'),
(5061,'hu','Hűha, micsoda akvárium!','Hűha, micsoda vulkán!','hatalmas akvárium','hatalmas medence','dramatic','exclamation'),
(5062,'hu','A főnök grafikont rajzol.','A főnök macskát rajzol.','utasításokat adó főnök','szünetet tartó főnök','business','none'),
(5063,'hu','A menetoszlop rendben halad.','A tömeg rendben halad.','menetelő sorok menetoszlopa','rovat egy újságban','business','none'),
(5064,'hu','Száz trombita. Szegény fülem!','Száz hegedű. Szegény fülem!','menetelés trombitákkal','trombita egy jazzklubban','dramatic','exaggeration'),
(5065,'hu','Hosszú folyosó csupa fűszerrel.','Hosszú folyosó csupa cipővel.','fűszerárusok közti folyosó','folyosó a repülőn','chill','none'),
(5066,'hu','Csak egy olajbogyó, mintának.','Csak egy datolya, mintának.','olajbogyó mintaként','fűszerminta','ironic','understatement'),
(5067,'hu','A házasság csókkal kezdődik!','A házasság veszekedéssel kezdődik!','házasság konfettivel','házasság a templomban','dramatic','exclamation'),
(5068,'hu','A menyasszony gyűrűt ad át.','A menyasszony beszédet mond.','menyasszony a tengerparton','menyasszony a templomban','chill','none'),
(5069,'hu','Hűha! Élvezi a masszázst.','Hűha! Élvezi a kávét.','élvezni egy nyakmasszázst','élvezni egy lábmasszázst','dramatic','exclamation'),
(5070,'hu','Minden matracot kipróbál.','Minden párnát kipróbál.','hanyatt fekve egy matracon','matracot cipel','chill','none'),
(5071,'hu','Szervizeli a járművet.','Szervizeli a biciklit.','ezüst autó szervizelése','mosógép szervizelése','business','none'),
(5072,'hu','A barna folyadék nagyon viszkózus.','A zöld folyadék nagyon viszkózus.','barna folyadékot önt','átlátszó folyadékot önt','nerd','none'),
(5073,'hu','Ez a gyógyszer borzalmas ízű!','Ez a gyógyszer isteni ízű!','egy kanál barna gyógyszer','gyógyszer kutyának','dramatic','exclamation'),
(5074,'hu','Mindenki bemutatkozik a lánynak.','Mindenki bemutatkozik a srácnak.','új kolléga bemutatása','új termék bemutatása','business','none'),
(5075,'hu','Ragacsos kéz, üres tölcsér. „Szuper.”','Ragacsos kéz, teli tölcsér. „Szuper.”','fagyitól ragacsos kéz','ragacsos szalag egy dobozon','ironic','understatement'),
(5076,'hu','Ő egy új klubtag.','Ő egy új zenekari tag.','új klubtag','egy zenekar tagja','business','none'),
(5077,'hu','A srác minden kártyát felidézett, könnyedén.','A csaj minden kártyát felidézett, könnyedén.','válaszok felidézése kártyákról','hibás autók visszahívása','slang','understatement'),
(5078,'hu','Sertéshúsos tacót készít.','Halas tacót készít.','sült sertéshús szeletelése','sertésszelet serpenyőben','chill','none'),
(5079,'hu','Előbb taco, aztán piramis.','Előbb taco, aztán strand.','piramis a dzsungelben','piramis a sivatagban','ironic','cliche'),
(5080,'hu','Nagyon jól áll a sárga ruha.','Nagyon jól áll a sárga kabát.','élénksárga nyári ruha','élénksárga esőkabát','flirt','none'),
(5081,'hu','A lila az ő színe.','A zöld az ő színe.','testhezálló lila ruha','lila selyemsál','flirt','none'),
(5082,'hu','Két konty? Remek frizura.','Két copf? Remek frizura.','kétkontyos frizura','frufrus frizura','flirt','none'),
(5083,'hu','Bogyókat adnak hozzá.','Diót adnak hozzá.','piros bogyók a tésztában','bogyószedés az erdőben','chill','none'),
(5084,'hu','Lenyűgöző a zöld estélyi!','Lenyűgöző a piros estélyi!','hosszú zöld estélyi','zöld estélyi táska','dramatic','exclamation'),
(5085,'hu','Úgy pózol, mint a szobor!','Úgy pózol, mint az őr!','szelfi egy szoborral','szelfi egy lóval','gossip','exclamation'),
(5086,'hu','A padló olyan fényes!','A padló olyan poros!','fényes kőpadló','fényes új telefon','dramatic','exclamation'),
(5087,'hu','A mancsok piszkossá tették a padlót.','A mancsok piszkossá tették a falat.','piszkos csempés padló','piszkos edények a mosogatóban','gossip','blaming_someone'),
(5088,'hu','A kisfiú ébren van és ásít.','A kisfiú ébren van és eszik.','ébren napkeltekor','ébren éjfélkor','chill','none'),
(5089,'hu','Ez az anya mindent megcsinál.','Ez az apa mindent megcsinál.','palacsintát forgató anya','palacsintát vásárló anya','chill','exaggeration'),
(5090,'hu','Hangulatos gyerekszoba tele játékkal.','Hangulatos konyha tele játékkal.','kiságyas gyerekszoba','faiskola','chill','none'),
(5091,'hu','A kis motor zöld.','A kis motor piros.','zöld motor a városban','eladó zöld motor','chill','none'),
(5092,'hu','A segítőnk profin pakolja a dobozokat.','A segítőnk profin pakolja a növényeket.','segítő egy dobozzal','segítő egy lámpával','slang','exaggeration'),
(5094,'hu','Megfeszíti a sovány karját.','Megfeszíti a sovány lábát.','sovány kar megfeszítése','szűk farmer viselése','chill','none'),
(5095,'hu','Ámulattal bámul felfelé!','Ámulattal bámul lefelé!','ámulat egy óriás csontváz előtt','ámulat egy apró érme előtt','dramatic','exclamation'),
(5096,'hu','A gomba a földben nő.','A gomba a vízben nő.','gomba a földön','gomba a pizzán','chill','none'),
(5097,'hu','A zenéje megállította az utcát.','A zenéje kiürítette az utcát.','utcai zene','zenebolt','chill','exaggeration'),
(5098,'hu','A srác imádja a nemzeti válogatottat.','A lány imádja a nemzeti válogatottat.','nemzeti színek egy arcon','nemzeti ünnep','chill','guessing'),
(5099,'hu','Mindenki hozzáad egy fényképet!','Mindenki hozzáad egy bélyeget!','fényképek egy világtérképen','fényképalbum','gossip','none'),
(5100,'hu','Fotókat rögzítenek egy térképen.','Fotókat rögzítenek egy ajtón.','fotók rögzítése térképre','térképek rögzítése a falra','chill','none'),
(5101,'hu','Ezen az úton a hányinger nyer.','Ezen a repülőúton a hányinger nyer.','hányinger a kompon','hányinger az autóban','dramatic','exaggeration'),
(5102,'hu','Ez a sikátor szuper szűk!','Ez a sikátor szuper széles!','szűk medinai sikátor','macskákkal teli sikátor','slang','exaggeration'),
(5103,'hu','Egy zsiráf nyaka hajol fölé!','Egy ló nyaka hajol fölé!','zsiráf hosszú nyaka','kígyó a nyaka körül','dramatic','exclamation'),
(5104,'hu','Barátságos a beszélgetésük.','Dühös a beszélgetésük.','beszélgetés a kerítés fölött','beszélgetés egy konferencián','chill','none'),
(5105,'hu','Kacsákkal teli árok.','Csónakokkal teli árok.','egyenes vizesárok','árok az autópálya mellett','chill','exaggeration'),
(5106,'hu','Szélmalom, tulipán, stroopwafel: pipa.','Szélmalom, tulipán, pizzaszelet: pipa.','forgó szélmalom','szélmalom a tengerparton','ironic','cliche'),
(5107,'hu','Mindketten a karjukban ringatják a babát.','Mindketten fürdetik a babát.','újszülöttet karjában ringat','teáscsészét dédelget','chill','none'),
(5108,'hu','A falu a vízen áll.','A falu a dombon áll.','cölöpökön álló falu','hóval borított falu','business','none'),
(5109,'hu','Egy tucat édes cupcake, és egyedül eszik.','Egy tucat édes keksz, és egyedül eszik.','egy tálca édes cupcake','egy csésze édes tea','ironic','guessing'),
(5110,'hu','A park nagyon csendes.','A strand nagyon csendes.','csendes, ködös park','csendes, ködös strand','chill','none'),
(5111,'hu','Egy beteg gyereket ápol.','Egy beteg kiskutyát ápol.','beteg gyerek ápolása','egy pohár víz kortyolgatása','chill','none'),
(5112,'hu','Szemcsék repülnek a levegőben.','Szemcsék repülnek egy csészébe.','hulló rizsszemcsék','egy homokszem','chill','none'),
(5113,'hu','Jó tanács: egyél több halat.','Jó tanács: egyél több tortát.','tanács az egészséges ételről','pénzügyi tanács','business','none'),
(5114,'hu','A flamingók elrepülnek.','A hattyúk elrepülnek.','flamingócsapat','flamingó az állatkertben','chill','none'),
(5115,'hu','Egy rovart tanulmányoz.','Egy virágot tanulmányoz.','kis rovar tanulmányozása','tanulás egy vizsgára','chill','none'),
(5116,'hu','Kinyitja az összes ablakot!','Becsukja az összes ablakot!','kinyitni az ablakokat','kinyitni egy ajándékot','dramatic','exclamation'),
(5117,'hu','Imádja ezt a könyvesboltot!','Utálja ezt a könyvesboltot!','zsúfolt régi könyvesbolt','bezáró könyvesbolt','slang','exclamation'),
(5118,'hu','Napfény ömlik rá. Micsoda reggel!','Eső ömlik rá. Micsoda reggel!','napfény az ablakon át','napfény a fák között','dramatic','none'),
(5119,'hu','A bejáratnál fakapuk vannak.','A bejáratnál üvegkapuk vannak.','a park bejárata','a múzeum bejárata','chill','none'),
(5120,'hu','Kész! A sebészek boldogok.','Kész! A pékek boldogok.','sebészek egy beteg körül','sebészek egy váróteremben','dramatic','exclamation'),
(5121,'hu','Kiveszi a muffinokat.','Kiveszi a kekszeket.','muffinos tálca kivétele','a sütőajtó leszerelése','chill','none'),
(5123,'hu','A kávé, a mosogató és a kád mindent eláraszt!','A kávé, a mosogató és a sütő mindent eláraszt!','fürdőszobát elárasztó kád','eső után elárasztott út','dramatic','exaggeration'),
(5124,'hu','Maraton az óvárosban.','Maraton az erdőben.','városi maraton futása','filmmaraton','chill','none'),
(5125,'hu','Forradalmat visznek színre!','Esküvőt visznek színre!','régi darab színre vitele','tüntetés megszervezése','dramatic','exclamation'),
(5126,'hu','Büszke a vállalkozására.','Büszke az autójára.','kis sarki vállalkozás','nagy online vállalkozás','chill','none'),
(5127,'hu','A bőröndöt nem lehet becsukni!','A bőröndöt nem lehet kinyitni!','tele bőrönd becsukása','ablak becsukása','dramatic','exclamation'),
(5128,'hu','A kanapé komoly sérülést okozott!','Az asztal komoly sérülést okozott!','sérülés a kanapé sarkától','sérülés egy focimeccsen','dramatic','blaming_someone'),
(5129,'hu','A bútorok takarók alatt vannak.','A bútorok törölközők alatt vannak.','szürke takarók a bútorokon','borító egy könyvön','business','none'),
(5130,'hu','Nagyon magasan száll a sárkánya!','Nagyon magasan száll a drónja!','sárkányeregetés','sárkány egy fán','slang','exaggeration'),
(5131,'hu','A labdára összpontosít.','A fiúkra összpontosít.','összpontosítás a labdára','összpontosítás a tömegre','chill','none'),
(5132,'hu','Önti a keveréket.','Kavarja a keveréket.','palacsintakeverék a serpenyőben','festékszínek keveréke','chill','none'),
(5133,'hu','A parkban sikít.','A medencében sikít.','sikítás egy szoborjátékban','sikítás egy horrorfilmnél','chill','none'),
(5134,'hu','A szülők kicsit elfoglaltak.','A kutyák kicsit elfoglaltak.','babát etető szülők','kacsákat etető szülők','ironic','understatement'),
(5135,'hu','Szűk hely, tökéletes parkolás.','Tág hely, tökéletes parkolás.','szűk parkolóhely','űrrakéta kilövése','flirt','none'),
(5136,'hu','Egyre hangosabb a vita!','Egyre csendesebb a vita!','hangos vita','tévévita','dramatic','exclamation'),
(5137,'hu','Ma tele van a parlament.','Ma üres a parlament.','teli parlament','üres parlament','business','none'),
(5138,'hu','Most a vonaton ül.','Most a buszon ül.','ülőhely a vonaton','ülőhely a repülőn','chill','none'),
(5139,'hu','Az oldalak eleinte üresek voltak.','Az oldalak eleinte tele voltak.','üres útlevéloldal','üres arckifejezés','chill','none'),
(5140,'hu','A pecsét megengedi, hogy belépjen.','A pecsét megengedi, hogy vezessen.','belépni engedik','dohányozni engedik','business','none'),
(5141,'hu','Az orvosnál sztetoszkóp van.','Az orvosnál fényképezőgép van.','orvos sztetoszkóppal','orvos a mentőautóban','chill','none'),
(5142,'hu','A környék fel van díszítve.','A környék üres.','feldíszített környék','környékbeli garázsvásár','chill','none'),
(5143,'hu','A katonák békét kötnek.','A katonák háborút viselnek.','békekötés','béke és nyugalom otthon','chill','none'),
(5144,'hu','A lányok galambokat engednek szabadon!','A fiúk galambokat engednek szabadon!','fehér galambok elengedése','fehér galambok etetése','dramatic','exclamation'),
(5145,'hu','A villamos közvetlenül mögötte van.','A busz közvetlenül mögötte van.','villamos a téren','villamos a hídon','chill','none'),
(5146,'hu','A héj egyetlen hosszú csík!','A héj két rövid csík!','hosszú héjcsík','ragasztószalag-csík','dramatic','exclamation'),
(5147,'hu','Annyi ember kel át!','Annyi autó kel át!','zebrát elárasztó emberek','buszra váró emberek','dramatic','exclamation'),
(5148,'hu','Jó reggelt, üres város!','Jó éjszakát, üres város!','üres reggeli utca','nyüzsgő reggeli utca','dramatic','exclamation'),
(5149,'hu','Micsoda nagy, régi gyógyszertár!','Micsoda nagy, régi pékség!','impozáns régi gyógyszertár','kórházi gyógyszertár','dramatic','exclamation'),
(5150,'hu','Receptet mutat fel.','Vonatjegyet mutat fel.','recept átadása','recept felírása','business','none'),
(5151,'hu','A keret ezüst.','A keret arany.','ezüst képkeret','ezüst ablakkeret','chill','none'),
(5152,'hu','A hálószobája csupa párna!','A hálószobája csupa könyv!','párnák a hálószobában','párnák a nappaliban','dramatic','exaggeration'),
(5153,'hu','A csapat beülteti az ágyást.','A csapat kifesti az ágyást.','magaságyás','bevetetlen ágy','business','none'),
(5154,'hu','A szobanövényei valóságos dzsungel.','A könyvei valóságos dzsungel.','szobanövényekkel teli szoba','eladó szobanövény','chill','exaggeration'),
(5155,'hu','Ebéd az egész családnak!','Ebéd csak két embernek!','nagy családi ebéd','gyors ebéd a munkahelyen','dramatic','exclamation'),
(5156,'hu','Gólt lőtt, ezért letérdel.','Hibázott, ezért letérdel.','letérdel a fűre','imához letérdel','dramatic','none'),
(5157,'hu','Az egész szomszédság focizik!','Az egész szomszédság röplabdázik!','szomszédsági focimeccs','szomszédsági biciklis verseny','dramatic','exaggeration'),
(5158,'hu','Összekapcsolja a kábeleket.','Elvágja a kábeleket.','gamer setup összekapcsolása','kapcsolattartás a barátokkal','nerd','none'),
(5160,'hu','Rohan az esőben.','Rohan a hóban.','rohanás a galambok mellett','rohanás a rendőrök mellett','chill','none'),
(5161,'hu','Egy székesegyház előtt áll.','Egy kastély előtt áll.','téglából épült székesegyháztorony','egy sötét székesegyház belseje','chill','none'),
(5162,'hu','Gyönyörű kilátás és gombócok.','Gyönyörű kilátás és palacsinta.','gyönyörű hegyi tó','gyönyörű tengerpart','chill','none'),
(5163,'hu','Politikusok, szokás szerint vitatkoznak.','Politikusok, szokás szerint ölelkeznek.','mutogató dühös politikusok','kezet rázó politikusok','ironic','cliche'),
(5164,'hu','Ebben a kampányban minden van: plakátok, viták, konfetti.','Ebben a kampányban minden van: plakátok, viták, tűzijáték.','választási kampány','dohányzásellenes kampány','gossip','exaggeration'),
(5165,'hu','A folyó tele van műanyaggal.','A folyó tele van hallal.','műanyag a folyóban','műanyag a szelektív kukában','dramatic','none'),
(5166,'hu','A villamos a síneken van.','A villamos a füvön van.','villamossín a macskakőben','villamossín egy alagútban','chill','none'),
(5167,'hu','Megérinti a kék csempéket.','Megérinti a piros csempéket.','kék-fehér falicsempék','csempék egy fürdőszobapadlón','chill','none'),
(5168,'hu','Ez az adag pudingos pite rendben van.','Ez az adag kenyér rendben van.','egy adag pudingos pite','egy adag keksz','chill','understatement'),
(5169,'hu','Egy képeslapot postáz.','Egy csomagot postáz.','képeslap postázása','csomag postázása','chill','none'),
(5170,'hu','Átad egy csomagot.','Átad egy pizzát.','becsomagolt születésnapi csomag','utazási csomag','chill','none'),
(5171,'hu','Alaplevet ad hozzá a fazékban lévő ételhez.','Tejet ad hozzá a fazékban lévő ételhez.','zöldség hozzáadása a fazékhoz','só hozzáadása a leveshez','chill','none'),
(5172,'hu','Szegény tészta! Csapkodja.','Szegény ajtó! Csapkodja.','kenyértészta csapkodása','a bejárati ajtó csapkodása','dramatic','exclamation'),
(5173,'hu','Még jó, hogy van esőkabátja.','Még jó, hogy van napkalapja.','piros kapucnis esőkabát','esőkabát egy fogason','chill','understatement'),
(5174,'hu','Ez egy vidám vacsora.','Ez egy vidám reggeli.','vidám családi vacsora','vidám irodai buli','chill','none'),
(5175,'hu','Szép bajusz, biztos kéz.','Szép szakáll, biztos kéz.','bajuszos pincér','bajszát borotváló pincér','flirt','none'),
(5176,'hu','Forró kávé egy nagy bögrében.','Forró tea egy nagy bögrében.','nagy fehér bögre','fül nélküli bögre','chill','none'),
(5177,'hu','Egy teáskannából tölt.','Egy üvegből tölt.','töltés egy fehér teáskannából','teáskanna a tűzhelyen','chill','none'),
(5178,'hu','Fejkendőben süt.','Kalapban süt.','sötétkék fejkendő','fejkendő a szélben','chill','none'),
(5180,'hu','A szónok a pulpitusnál áll.','A szónok a zongoránál áll.','szónok a pulpitusnál','szónok a közönség soraiban','business','none'),
(5183,'hu','Olyan szenvedélyes, hogy repül a kréta!','Olyan szenvedélyes, hogy repülnek a könyvek!','szenvedélyes idős tanár','szenvedélyes fiatal énekes','dramatic','exaggeration'),
(5184,'hu','Megkérte a kezét. Milyen romantikus!','Énekelt neki. Milyen romantikus!','romantikus lánykérés','romantikus vígjáték','flirt','exclamation'),
(5185,'hu','A kedvesség szárazon tartja a férfit.','A kedvesség szárazon tartja a kutyát.','kedvesség az esőben','kedvesség a napsütésben','chill','none'),
(5186,'hu','A nagyközönség a téren van.','A nagyközönség a templomban van.','nagyközönség a téren','nagyközönség a színházban','chill','none'),
(5188,'hu','Egy csizma? Totális csalódás.','Egy hal? Totális csalódás.','csalódás a stégen','csalódás az állatkertben','ironic','understatement'),
(5189,'hu','Időjárás-ellenőrzés: még mindig esik.','Időjárás-ellenőrzés: még mindig havazik.','időjárás ellenőrzése kézzel','időjárás a tévében','chill','none'),
(5190,'hu','Szeles? Imádja!','Napos? Imádja!','szeles tengerpart','szeles hegycsúcs','slang','exclamation'),
(5191,'hu','Zászló egy havas síkságon.','Zászló egy homokos strandon.','havas fehér síkság','havas városi utca','chill','none'),
(5192,'hu','Csak hó a horizontig.','Csak homok a horizontig.','hó a horizontig','tenger a horizonton','dramatic','none'),
(5193,'hu','Krém a kiütésre? Csíp!','Krém az égésre? Csíp!','krém egy piros kiütésen','kiütés az arcán','gossip','exclamation'),
(5194,'hu','Találd ki, ki imádja ezt a regényt?','Találd ki, ki imádja ezt a filmet?','vastag regényt olvas','regényt ír','gossip','none'),
(5195,'hu','A könyvei az egész padot elfoglalják.','A cipői az egész padot elfoglalják.','könyvek egy parki padon','kutya egy padon','gossip','exaggeration'),
(5196,'hu','A kontya és a könyve mindenhová vele megy.','A kontya és a kutyája mindenhová vele megy.','szőke konty a feje tetején','egy cukros kalács','chill','exaggeration'),
(5197,'hu','Az iroda fellázad!','Az iroda alszik!','fellázad a munka ellen','fellázad a szülei ellen','dramatic','exclamation'),
(5198,'hu','Átad neki egy lapot.','Átad neki egy csészét.','kis kézzel írt lap','lepedő az ágyon','chill','none'),
(5199,'hu','A receptet lépésről lépésre követte.','A térképet lépésről lépésre követte.','kézzel írt recept követése','egy barát követése online','business','none'),
(5200,'hu','Micsoda élénk társaság!','Micsoda élénk kutya!','élénk nappali','élénk táncklub','dramatic','exclamation'),
(5201,'hu','A víz mindent tükröz, még a vulkánt is.','A víz mindent tükröz, még a holdat is.','vízben tükröződő vulkán','arc a tükörben','business','none'),
(5202,'hu','Az egész boltot a hűtőbe tette!','Az egész boltot a sütőbe tette!','ételt tesz a hűtőbe','ételt tesz az asztalra','dramatic','exaggeration'),
(5203,'hu','Megérkeztek a rokonok!','Elmentek a rokonok!','rokonok a bejárati ajtónál','rokonok a reptéren','dramatic','exclamation'),
(5204,'hu','A szobát nagyon feljavították.','A kertet nagyon feljavították.','régi szoba feljavítása','angoltudás feljavítása','business','none'),
(5205,'hu','A nő leteszi az esküt.','A férfi leteszi az esküt.','esküt tesz','megszegi az esküt','chill','none'),
(5206,'hu','Megtalálta a bizonyítékot!','Elvesztette a bizonyítékot!','bizonyítékok kitűzése','a bizonyíték elrejtése','dramatic','guessing'),
(5207,'hu','Nagy hegyek, sok izzadság.','Nagy tavak, sok izzadság.','csurog az izzadság','izzadság szauna után','dramatic','none'),
(5208,'hu','Minden konyha lenyűgözi!','Minden ital lenyűgözi!','három különböző konyha','csak egyetlen konyha','gossip','exaggeration'),
(5209,'hu','Senki nem dolgozik, mindenki heverészik.','Senki nem dolgozik, mindenki táncol.','heverészés egy függőágyban','heverészés egy hajón','ironic','exaggeration')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
