begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(57,'de','Sie lieben die Plätze im hinteren Teil!','Sie lieben die Plätze im vorderen Teil!','im hinteren Teil sitzen','der hintere Teil der Bühne','dramatic','exclamation'),
(118,'de','Zusammenbauen erledigt, Zeit für ein High Five!','Zusammenbauen erledigt, Zeit für eine Gruppenumarmung!','ein Hochbeet zusammenbauen','ein hohes Bürogebäude','dramatic','exclamation'),
(138,'de','Eine Kappe, endlich Schatten.','Ein Baum, endlich Schatten.','korallenrote Kappe gegen die Sonne','eine Kappe auf der Flasche','chill','none'),
(184,'de','Sie befiehlt, alle rennen.','Sie befiehlt, alle schlafen.','einer Reihe Rekruten Befehle geben','ein Schiff befehligen','business','none'),
(196,'de','Mut hat sie rübergebracht!','Eine Seilrutsche hat sie rübergebracht!','Mut beim Überqueren','Mut beim Runterspringen','dramatic','exclamation'),
(222,'de','Diese Verspätung dauert ewig.','Dieser Zug braucht ewig.','eine Verspätung am Bahnhof','eine Verspätung am Flughafen','dramatic','exaggeration'),
(227,'de','Dieser Diamant funkelt wie verrückt!','Dieser Rubin funkelt wie verrückt!','ein funkelnder Diamantring','eine Diamantkette','dramatic','exclamation'),
(292,'de','Das Kissen hat den Kampf verloren.','Die Lampe hat den Kampf verloren.','eine Kissenschlacht im Bett','eine Schneeballschlacht','low_iq','cheap_quality'),
(347,'de','Für Klatsch sind sie immer zu haben.','Für Fußball sind sie immer zu haben.','saftigen Klatsch flüstern','Klatsch aus einer Zeitschrift','gossip','understatement'),
(383,'de','Wandern bis ganz nach oben!','Skifahren bis ganz nach oben!','auf einen Berg wandern','durch die Wüste wandern','dramatic','exclamation'),
(412,'de','Sie hat das Trikot mit der Nummer 7 bekommen!','Sie hat das Trikot mit der Nummer 9 bekommen!','neues Trikot mit Nummer 7','neues Trikot mit Nummer 10','dramatic','exclamation'),
(432,'de','Sie führt die Gruppe mit einer Laterne.','Sie führt die Gruppe mit einer Taschenlampe.','Wanderer mit einer Laterne führen','Wanderer mit einer Karte führen','chill','none'),
(479,'de','Sie ist mit ihrem Verstand zwei Züge voraus.','Sie ist mit ihrem Verstand zwei Züge hinterher.','Züge im Kopf planen','ihre Meinung ändern','nerd','exaggeration'),
(561,'de','Ein Croissant voller Genuss.','Ein Bagel voller Genuss.','der Genuss eines Croissants','der Genuss eines Muffins','dramatic','none'),
(862,'de','Fernsehabend: Beim Zuschauen muss Popcorn her.','Fernsehabend: Beim Zuschauen muss Pizza her.','gemütliches Zuschauen vorm Fernseher','gemütliches Vogelbeobachten im Wald','chill','cliche'),
(1009,'de','Der Kompass ist schlauer als ich.','Das alte Handy ist schlauer als ich.','ein Messingkompass in der Hand','eine Messinguhr in der Hand','low_iq','exaggeration'),
(1161,'de','Er kühlt sein Knie mit Eis.','Er kühlt seinen Kopf mit Eis.','Eis auf dem gebeugten Knie','auf ein Knie gehen','business','none'),
(1373,'de','Sommer-Vibes: großer Sprung in den See.','Sommer-Vibes: großer Sprung in den Pool.','sommerlicher Sprung in den See','eine sommerliche Poolparty','slang','none'),
(1413,'de','Laufband: Rennen ins Nirgendwo.','Laufband: Spazieren ins Nirgendwo.','auf dem Laufband rennen','ein kaputtes Laufband reparieren','ironic','cliche'),
(1535,'de','Er balanciert kopfüber. Voll easy.','Er liegt einfach rum. Voll easy.','kopfüber balancieren','kopfüber hängen','slang','understatement'),
(1855,'de','Der Pfau hat riesige Schwanzfedern!','Der Pfau hat kurze Schwanzfedern!','ein Pfau mit aufgestellten Schwanzfedern','ein Pfau mit angelegten Schwanzfedern','dramatic','exaggeration'),
(1919,'de','Die Gasse ist sehr schmal.','Die Gasse ist sehr breit.','eine schmale Kopfsteingasse','eine schmale Brücke','chill','none'),
(1974,'de','Die Ballerina steht auf den Zehenspitzen.','Die Ballerina kniet auf dem Boden.','eine Ballerina im Tutu','ein Ballettschuh','chill','none'),
(1992,'de','Sie hört Musik über große grüne Kopfhörer.','Sie hört Musik über große rote Kopfhörer.','Musik hören','einer Lehrerin zuhören','chill','none'),
(2013,'de','Ihr Make-up? Total Gothic.','Ihr Make-up? Total pink.','ein Gothic-Look','eine gotische Kirche','gossip','none'),
(2079,'de','Alles hier ist aus Holz.','Alles hier ist aus Plastik.','hohe hölzerne Bücherregale','hohe hölzerne Leitern','low_iq','exaggeration'),
(2156,'de','Die Sonne steht tief am Horizont.','Der Mond steht tief am Horizont.','die Sonne am Horizont','ein Schiff am Horizont','chill','none'),
(2161,'de','Das Genie hat eine neue Idee.','Das Genie hat eine neue Katze.','ein Genie, das Sterne beobachtet','ein Genie, das Formeln schreibt','nerd','guessing'),
(2162,'de','Rothaarig – und die Haare sitzen perfekt.','Schwarzhaarig – und die Haare sitzen perfekt.','rothaarig mit langen Locken','rothaarig mit Dutt','flirt','none'),
(2246,'de','In der Vitrine steht ein Miniaturhäuschen.','In der Vitrine steht ein Miniaturschloss.','ein Miniatur-Nachtgarten','eine Miniatur-Eisenbahn','business','none'),
(2310,'de','Eine Melodie steigt aus dem Klavier auf.','Eine Melodie steigt aus der Trommel auf.','eine aufsteigende goldene Melodie','eine sinkende goldene Melodie','dramatic','none'),
(2602,'de','Sie fahren Ski, mega schnell bergab.','Sie fahren Ski, mega schnell bergauf.','steil bergab Ski fahren','auf flacher Straße Ski fahren','slang','none'),
(2660,'de','Kletterpflanzen hängen über dem Bogen.','Fahnen hängen über dem Bogen.','Kletterpflanzen über einem Steinbogen','eine Kletterpflanze voller Trauben','chill','none'),
(2794,'de','Der Tierarzt hält eine Katze.','Der Tierarzt hält einen Hund.','Tierarzt beim Katzenknuddeln','Tierarzt auf dem Bauernhof','chill','none'),
(3061,'de','Sie schwebt über einer Schallplatte.','Sie schwebt über einem Klavier.','eine sich drehende Schallplatte','einen Weltrekord brechen','chill','none'),
(3589,'de','Der Gorilla chillt einfach.','Der Gorilla isst einfach.','ein Gorilla im Bambus','ein brusttrommelnder Gorilla','slang','none'),
(3590,'de','Ein Strauß läuft über den Sand.','Ein Kamel läuft über den Sand.','ein Strauß in der Wüste','ein Strauß mit verstecktem Kopf','chill','none'),
(3598,'de','Ihr lockiges Haar ist mit blauem Stift gemalt.','Ihr lockiges Haar ist mit rotem Stift gemalt.','lockiges Haar mit blauem Stift','lockiges Haar mit roter Farbe','chill','none'),
(3640,'de','Die Lampe leuchtet ins All.','Die Lampe leuchtet auf ein Schiff.','ins All leuchten','ein Licht auf einem Schiff','chill','none'),
(3828,'de','Der Schimpanse und das Streichholz: keine gute Idee.','Der Schimpanse und das Messer: keine gute Idee.','ein brennendes Streichholz in der Hand','ein Fußballspiel im Fernsehen','chill','guessing'),
(4035,'de','Er tritt auf die Blöcke über dem Wasser.','Er tritt auf die Blöcke über dem Feuer.','auf schwimmende Blöcke treten','auf einen fahrenden Zug steigen','chill','none'),
(4160,'de','Schwupps! Das rote Auto ist verschwunden.','Schwupps! Der rote Van ist verschwunden.','im Sand verschwinden','im Schnee verschwinden','slang','exaggeration'),
(4199,'de','Er lässt die Füße durch den See schleifen.','Er lässt die Hände durch den See schleifen.','die Füße durchs Wasser ziehen','ein Boot ins Wasser schleppen','chill','none'),
(4271,'de','Der Sportler ist so schnell!','Der Sportler ist so langsam!','ein Sportler mit Höchstgeschwindigkeit','ein Sportler im Ziel','slang','exclamation'),
(4285,'de','Als Erwachsener gibt''s nur Rechnungen.','Als Erwachsener gibt''s nur Games.','ein Erwachsener auf dem Arbeitsweg','ein Erwachsener beim Schlafengehen','slang','cliche'),
(4298,'de','Die Jungs stellen sich in einer geraden Reihe auf.','Die Mädchen stellen sich in einer geraden Reihe auf.','in gerader Reihe aufstellen','geradewegs nach Hause gehen','chill','none'),
(4316,'de','Es tut ihm leid. Tulpen helfen bestimmt.','Es tut ihm leid. Rosen helfen bestimmt.','Entschuldigung für den Kaffee','Entschuldigung für den Kuchen','ironic','guessing'),
(4319,'de','Die Streifen vermischen sich.','Die Streifen werden breiter.','Creme in die Haut einarbeiten','Obst im Mixer vermischen','chill','none'),
(4333,'de','Sie ist auf die Plattform gestiegen.','Sie ist in den Bus gestiegen.','ein belebter Bahnsteig','eine Sprungplattform','chill','none'),
(4384,'de','Sie ist vom Bett hochgefedert!','Sie ist vom Sofa hochgefedert!','auf dem Bett hüpfen','einen Ball abprallen lassen','dramatic','exclamation'),
(4418,'de','Der Dampf schoss ihr ins Gesicht.','Das Wasser schoss ihr ins Gesicht.','aus dem Topf schießender Dampf','ein geplatztes Wasserrohr','chill','none'),
(4425,'de','Der Roboter gibt ihnen Befehle.','Der Roboter bestellt eine große Pizza.','das Team herumkommandieren','einen Kaffee bestellen','dramatic','none'),
(4578,'de','Die Felder bilden ein Flickenmuster.','Die Parkplätze bilden ein Flickenmuster.','grüne Felder vor der Ernte','eine Apfelernte','nerd','none'),
(4627,'de','Alle gehen weg. Er winkt!','Alle bleiben. Er winkt!','winken, während das Schiff ablegt','mit dem Fahrrad wegfahren','dramatic','exaggeration'),
(4666,'de','Kürbis zerschmettert. Ups!','Ei zerschmettert. Ups!','ein auf Beton zerschmetterter Kürbis','ein vom Kürbis zerschmettertes Fenster','ironic','exclamation'),
(4711,'de','Sein Gesicht ist pure Anstrengung.','Sein Gesicht ist pure Langeweile.','mit aller Kraft rudern','mit aller Kraft rennen','dramatic','none'),
(4729,'de','Die Maske hat sie ganz ängstlich gemacht!','Der Clown hat sie ganz ängstlich gemacht!','ängstlich im Geisterhaus','Angst vor einer Spinne','dramatic','exclamation'),
(4757,'de','Endlich Freiheit im Sommer!','Endlich Freiheit im Winter!','Freiheit auf der offenen Landstraße','Freiheit in einer Großstadt','dramatic','exclamation'),
(4773,'de','Die Musik hat eine Menschenansammlung ausgelöst.','Die Musik hat eine Schlägerei ausgelöst.','eine Menschenansammlung um einen Straßenmusiker','ein Familientreffen zu Hause','chill','none'),
(4776,'de','So höflich: Er lüftet seinen Hut.','So höflich: Er hebt seinen Stock.','ein höflicher Gruß','ein höflicher Brief','flirt','none'),
(4799,'de','Eine Fliege binden? Nervensache!','Die Schuhe binden? Nervensache!','eine schwarze Fliege binden','den Koffer zubinden','dramatic','exclamation'),
(4835,'de','In der Stadt läuft eine Verfolgungsjagd!','In der Stadt läuft eine Parade!','eine Stadtstraße bei Nacht','eine Stadtstraße zur Mittagszeit','dramatic','exclamation'),
(4864,'de','Die Band ist in Uniform!','Die Band ist im Schlafanzug!','eine Band in Uniform','eine Schuluniform','dramatic','exclamation'),
(4865,'de','Seine Kamera hat ein langes Objektiv.','Seine Kamera hat ein kurzes Objektiv.','ein langes Kameraobjektiv','eine Linse in ihrer Brille','nerd','none'),
(4873,'de','Sie ist völlig ins Lernen vertieft.','Sie hat sich völlig im Wald verlaufen.','ins Lernen vertieft','eine medizinische Studie','chill','none'),
(4981,'de','Alle haben den Impfstoff bekommen. Juhu!','Keiner hat den Impfstoff bekommen. Juhu!','Impfstoff in den Oberarm','Impfstoff ins Bein','dramatic','exclamation'),
(5012,'de','Paris ist voller Romanzen!','Paris ist voller Schnee!','Romanze in Paris','ein Liebesroman','dramatic','exaggeration'),
(5032,'de','Sie geht dem Team voraus.','Sie geht dem Team hinterher.','der Gruppe vorausgehen','für die Reise vorausplanen','business','none'),
(5045,'de','Die Boxen machen ein lautes Geräusch!','Die Trommeln machen ein lautes Geräusch!','ein Geräusch aus einem Ghettoblaster','ein Geräusch aus einem Autoradio','low_iq','exclamation'),
(5146,'de','Die Schale besteht aus einem einzigen langen Streifen!','Die Schale besteht aus zwei kurzen Streifen!','ein langer Streifen Schale','ein Streifen Klebeband','dramatic','exclamation'),
(5186,'de','Das Publikum ist auf dem Platz.','Das Publikum ist in der Kirche.','das Publikum auf dem Platz','das Publikum im Theater','chill','none'),
(5196,'de','Ihr Dutt und ihr Buch sind immer dabei.','Ihr Dutt und ihr Hund sind immer dabei.','ein hoher blonder Dutt','ein süßes Brötchen','chill','exaggeration'),
(5199,'de','Das Rezept Schritt für Schritt befolgt.','Der Karte Schritt für Schritt gefolgt.','ein handgeschriebenes Rezept befolgen','einem Freund online folgen','business','none'),
(5226,'de','Er hat es in den Waggon geschafft!','Er hat es ins Taxi geschafft!','in einen Zugwaggon springen','eine Pferdekutsche','dramatic','exclamation'),
(5236,'de','Die Stadt ist in einiger Entfernung zu sehen.','Das Kamel ist in einiger Entfernung zu sehen.','Türme in einiger Entfernung','ein Ferngespräch','chill','none'),
(5256,'de','Ein Richter spricht zu ihnen.','Eine Krankenschwester spricht zu ihnen.','vor vollem Saal sprechen','einen Brief adressieren','chill','none'),
(5260,'de','Mit Kuchen erwischt. Vor Scham im Boden versinken!','Mit Pizza erwischt. Vor Scham im Boden versinken!','Scham wegen eines Kuchens','Scham wegen eines kaputten Tellers','dramatic','exclamation'),
(5300,'de','Die Viper ist eine echte Bedrohung.','Die Eidechse ist eine echte Bedrohung.','eine Bedrohung auf den Felsen','eine Drohung in einem Brief','dramatic','none'),
(5367,'de','Sie stopft sich den Mund voll!','Sie stopft ihre Tasche voll!','einen Cheeseburger reinstopfen','einen Truthahn füllen','gossip','exclamation'),
(5380,'de','Er hat sogar die Kiste genommen!','Sie hat sogar die Kiste genommen!','Sachen aus einer Kiste nehmen','eine Kiste zur Schule mitnehmen','gossip','exclamation'),
(5426,'de','Beide Delegationen haben sich geeinigt.','Keine der Delegationen hat sich geeinigt.','zwei Delegationen beim Treffen','eine Delegation am Flughafen','business','none'),
(5470,'de','Im Anzug schnell durch die Innenstadt.','In Jeans schnell durch die Innenstadt.','Arbeitsweg durch die Innenstadt','eine Rooftop-Bar in der Innenstadt','business','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
