begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(329,'de','Die Gasflamme ist blau.','Die Gasflamme ist grün.','eine blaue Gasflamme','Gas im Auto','business','none'),
(330,'de','Gerade noch rechtzeitig am Gate!','Zu spät fürs Gate!','zum Gate rennen','ein Tor im Garten','dramatic','exclamation'),
(331,'de','Ein Gentleman rettet die Orangen!','Ein Gentleman rettet die Äpfel!','ein Gentleman mit Regenschirm','ein Gentleman mit Hund','dramatic','exclamation'),
(332,'de','Die Giraffe macht Mittagspause.','Der Löwe macht Mittagspause.','eine Giraffe frisst Blätter','eine Giraffe frisst Gras','business','none'),
(333,'de','Dieses Mädchen kann einfach alles!','Dieser Junge kann einfach alles!','ein Mädchen beim Seilspringen','ein Mädchen beim Schuleschwänzen','dramatic','exaggeration'),
(334,'de','Ihr Glas ist eiskalt.','Ihr Glas ist heiß.','ein Glas Limonade','ein Glas Wein','chill','none'),
(336,'de','Brille auf, mehr Enten!','Brille auf, mehr Gänse!','eine runde Brille putzen','eine runde Brille zerbrechen','low_iq','exclamation'),
(338,'de','Sie umarmt ihren Globus!','Sie umarmt ihre Lampe!','einen Tischglobus drehen','einen Globus zeichnen','dramatic','exclamation'),
(339,'de','Sie geht die Straße hinunter.','Sie geht die Treppe hinauf.','die Straße hinuntergehen','nach Hause zurückgehen','chill','none'),
(340,'de','Sie haben ihr eigenes Tor mitgebracht!','Sie haben ihre eigene Bank mitgebracht!','ein Tor auf dem Platz','ein Ziel fürs nächste Jahr','dramatic','exclamation'),
(341,'de','Die Ziege frisst Wäsche!','Die Ziege frisst Blumen!','eine Ziege auf dem Dach','eine Ziege im Auto','dramatic','exclamation'),
(342,'de','Schwimmbrille auf, sitzt bombenfest!','Helm auf, sitzt bombenfest!','eine blaue Schwimmbrille','eine Skibrille im Schnee','slang','exclamation'),
(343,'de','Sie hat den Ring gepackt!','Sie hat die Münze gepackt!','unter Wasser einen Ring packen','die Poolleiter packen','dramatic','exclamation'),
(344,'de','Sie liebt Gold ein bisschen zu sehr.','Sie liebt Katzen ein bisschen zu sehr.','ein schwerer Goldbarren','eine Goldmedaille','gossip','understatement'),
(346,'de','Golfball im Loch. Ja!','Golfball im Wasser. Ja!','ein Golfputt bei Sonnenuntergang','ein Golfball im Wasser','dramatic','exclamation'),
(348,'de','Die Regierung hat mit Ja gestimmt.','Die Regierung hat mit Nein gestimmt.','eine Abstimmung der Regierung','die Schülervertretung','business','none'),
(349,'de','Angeln, Schach und eine Umarmung: bester Großvater ever.','Angeln, Schach und eine Umarmung: beste Großmutter ever.','Großvater und Enkel','Großvater und sein Hund','slang','cliche'),
(350,'de','Ihr Enkel ist zu Hause!','Ihr Mann ist zu Hause!','ihren Enkel umarmen','ihren Mann umarmen','dramatic','exclamation'),
(351,'de','Sie chillen im Gras.','Sie chillen im Sand.','im weichen Gras liegen','das weiche Gras mähen','slang','none'),
(352,'de','Der Käse hat Grillstreifen.','Das Brot hat Grillstreifen.','Käse auf dem heißen Grill','Fisch auf dem heißen Grill','chill','none'),
(353,'de','Der Gast kam mit einem Geschenk.','Der Gast kam mit einem Hund.','einen Gast begrüßen','ein Gästezimmer','chill','none'),
(354,'de','Der Reiseführer hatte recht!','Die Karte hatte recht!','ein dicker Reiseführer','ein dickes Telefonbuch','gossip','exclamation'),
(355,'de','Er kann nichts essen. Schuldgefühle!','Er kann nicht schlafen. Schuldgefühle!','Schuldgefühle wegen eines kaputten Krugs','Schuldgefühle wegen eines kaputten Handys','dramatic','exclamation'),
(356,'de','Sie wohnt ab jetzt in diesem Fitnessstudio.','Sie wohnt ab jetzt in dieser Kneipe.','ein helles neues Fitnessstudio','Sportunterricht in der Schule','low_iq','guessing'),
(357,'de','Ihre Haarbürste ist ein Mikro!','Ihr Kamm ist ein Mikro!','eine Haarbürste aus Holz','eine Haarbürste für Pferde','slang','exclamation'),
(358,'de','Sorgfältige Arbeit mit dem Hammer.','Sorgfältige Arbeit mit dem Löffel.','ein Hammer auf einem Nagel','ein Hammer im Werkzeugkasten','flirt','none'),
(359,'de','Volle Backen, glücklicher Hamster.','Leere Backen, glücklicher Hamster.','ein Hamster im Laufrad','ein Hamster in einer Laufkugel','slang','none'),
(360,'de','Erst Handdesinfektionsmittel, dann Samosas.','Erst Handcreme, dann Samosas.','ein Pumpstoß Handdesinfektionsmittel','Handdesinfektionsmittel an der Tür','business','none'),
(361,'de','Keine Blumen? Dann pack eben Lollis ein.','Keine Blumen? Dann pack eben Kekse ein.','Lollis in Papier einpacken','Kekse in Papier einpacken','ironic','cheap_quality'),
(362,'de','Sie ist so glücklich, voll unreal.','Sie ist so traurig, voll unreal.','ein glücklicher Strandspaziergang','eine glückliche Geburtstagsparty','slang','exaggeration'),
(363,'de','Er macht die ganze Nacht Recherche.','Er macht den ganzen Morgen Recherche.','Recherche in der Nacht','Recherche im Freien','chill','exaggeration'),
(364,'de','Er sagt, er sei kein Künstler.','Er sagt, er sei ein berühmter Künstler.','kein Künstler','das große Atelier eines Künstlers','chill','none'),
(365,'de','Ihre Kopfhörer sind zu laut!','Ihre Lautsprecher sind zu laut!','sich die Kopfhörer teilen','die Kopfhörer reparieren','slang','guessing'),
(366,'de','Ihr Arm ist geheilt. Ja!','Ihr Bein ist geheilt. Ja!','ein geheilter Arm','ein geheiltes Bein','dramatic','exclamation'),
(367,'de','Zu viel Hitze für ein Eis am Stiel!','Zu viel Regen für ein Eis am Stiel!','die Hitze in einem Dorf','die Hitze eines Feuers','dramatic','exaggeration'),
(368,'de','Lieferung per Hubschrauber? Cool!','Lieferung per Drohne? Cool!','eine Lieferung per rotem Hubschrauber','ein Hubschrauber auf einem Schiff','slang','exclamation'),
(369,'de','Er fährt Motorrad.','Er reitet ein Pferd.','ein Sportmotorrad fahren','im Auto fahren','chill','none'),
(370,'de','Der rote Helm hat seinen Job gemacht.','Der blaue Helm hat seinen Job gemacht.','ein roter Skaterhelm','ein Helm auf einem Motorrad','chill','understatement'),
(371,'de','Frische Kräuter für die Pasta, lecker.','Frische Kräuter für die Pizza, lecker.','frische Kräuter vom Fensterbrett','Kräutertee in der Tasse','slang','none'),
(372,'de','Er macht Tricks auf einem Dach.','Er macht Tricks an einem Strand.','Tricks mit dem Ball','Tricks mit Karten','chill','none'),
(373,'de','Ein Stadion voller roter Fans.','Ein Stadion voller blauer Fans.','ein volles Fußballstadion','ein leeres Stadion bei Nacht','chill','none'),
(374,'de','Er joggt im Morgengrauen.','Er radelt im Morgengrauen.','auf einer leeren Straße joggen','mit dem Hund joggen','chill','none'),
(375,'de','Er sieht im Rennwagen echt cool aus.','Er sieht im Taxi echt cool aus.','ein Rennwagen bei Sonnenaufgang','ein Rennwagen bei Nacht','flirt','none'),
(376,'de','Pure Wildnis, keine Menschen.','Pure Wüste, keine Menschen.','ein Fluss in der Wildnis','eine Straße durch die Wildnis','chill','none'),
(377,'de','Sie tritt in einem Studio auf.','Sie tritt in einer Kirche auf.','auftreten wie im Musikvideo','in einem großen Stadion auftreten','chill','none'),
(378,'de','Der Sonnenaufgang ist mega golden.','Der Sonnenaufgang ist mega grau.','in den Sonnenaufgang fliegen','vor Sonnenaufgang aufwachen','slang','none'),
(379,'de','Sie filmt einen Videoblog.','Sie filmt eine Hochzeit.','einen Morgen-Videoblog filmen','einen Reise-Videoblog schneiden','chill','none'),
(380,'de','Ihre Reise endete auf einem Dach.','Ihre Reise endete auf einem Boot.','eine lange Reise durch die Stadt','eine Reise mit dem Flugzeug','chill','none'),
(382,'de','Wow, die arbeiten so hoch oben!','Wow, die arbeiten so tief unten!','hoch über der Straße','hoch auf einem Berg','dramatic','exclamation'),
(385,'de','Sie hat ihn hoch in den Himmel geschlagen!','Sie hat ihn flach ins Gras geschlagen!','den Ball hoch schlagen','den Ball ins Wasser schlagen','dramatic','exaggeration'),
(386,'de','Sein Hobby ist, Modelle zu bauen.','Sein Hobby ist, Häuser zu bauen.','ein Hobby mit Schiffsmodellen','ein Hobby mit echten Schiffen','chill','none'),
(387,'de','Überwachungskamera: Der Hund war''s.','Überwachungskamera: Die Katze war''s.','nächtliche Bilder der Überwachungskamera','eine Überwachungskamera im Laden','gossip','blaming_someone'),
(388,'de','Ihre Hausaufgaben hören nie auf.','Ihre Ferien hören nie auf.','Hausaufgaben spät in der Nacht','Hausaufgaben im Bus','dramatic','exaggeration'),
(389,'de','Der Honig ist so langsam!','Der Honig ist so schnell!','Honig an einem Holzlöffel','Honig im Tee','slang','exclamation'),
(390,'de','Sein Hoodie ist mega gemütlich.','Seine Jacke ist mega gemütlich.','die Kapuze vom Hoodie aufsetzen','einen Hoodie waschen','slang','exaggeration'),
(391,'de','Das Boot ist zurück. Die Hoffnung siegt!','Das Flugzeug ist zurück. Die Hoffnung siegt!','Hoffnung auf das Boot','Hoffnung auf gutes Wetter','dramatic','exclamation'),
(392,'de','Sie reitet das Pferd.','Sie reitet das Kamel.','ein Pferd mit Reiterin','ein Pferd mit Kutsche','chill','none'),
(393,'de','Ein Bett im Hostel kostet zehn Euro.','Ein Bett im Hostel kostet sechs Euro.','ein Stockbett im Hostel','ein Zimmer im Hotel','business','none'),
(394,'de','Zu heiß! Er umarmt den Ventilator.','Zu heiß! Er umarmt den Hund.','ein heißer, sonniger Tag','eine heiße Tasse Tee','dramatic','exclamation'),
(395,'de','Bestes Haus der ganzen Welt!','Bestes Auto der ganzen Welt!','in ein gelbes Haus einziehen','in ein weißes Haus einziehen','slang','exaggeration'),
(396,'de','Das ist die Umarmung des Jahres!','Das ist der Streit des Jahres!','eine riesige Umarmung im Kreis','eine kurze Abschiedsumarmung','dramatic','exaggeration'),
(397,'de','Sie sind im Wald auf der Jagd.','Sie sind in der Wüste auf der Jagd.','Jagd im Herbstwald','Jagd im Schnee','chill','none'),
(398,'de','Erst Hygiene, dann Daumen hoch.','Erst Hygiene, dann High five.','gute Hygiene im Bad','gute Hygiene in der Küche','chill','none'),
(399,'de','Er verliert gegen sein Eis.','Er verliert gegen seinen Hotdog.','schmelzendes Eis','Eis im Becher','low_iq','exaggeration'),
(400,'de','Nummer 9 spielt Eishockey.','Nummer 7 spielt Eishockey.','Eishockey auf der Eisbahn','Eishockey auf einem Teich','chill','none'),
(401,'de','Schöner Stopp auf den Schlittschuhen.','Schöner Stopp auf dem Snowboard.','Schlittschuhe schnüren','Schlittschuhe im Regal','flirt','none'),
(402,'de','Sie rutscht übers Eis.','Sie rutscht übers Gras.','Blasen im Eis','Eis im Getränk','chill','none'),
(404,'de','Chaos im Klassenzimmer, aber er bleibt ruhig.','Chaos in der Küche, aber er bleibt ruhig.','ein lautes Klassenzimmer','ein stilles Klassenzimmer','gossip','understatement'),
(405,'de','Draußen Schnee, drinnen Freunde.','Draußen Schnee, drinnen Hunde.','warm drinnen in der Hütte','drinnen im Zelt','chill','none'),
(406,'de','Er hämmert heißes Eisen.','Er hämmert heißes Glas.','heißes Eisen hämmern','ein heißes Hemd bügeln','chill','none'),
(407,'de','Krass! Eine ganze Insel für zwei!','Krass! Eine ganze Insel für zehn!','eine kleine tropische Insel','eine Kücheninsel','dramatic','exaggeration'),
(408,'de','Jacke an. Viel besser.','Schal an. Viel besser.','eine braune Jacke zumachen','eine Jacke auf einem Stuhl','chill','none'),
(410,'de','Sie streicht die Marmelade dick auf.','Sie streicht die Marmelade dünn auf.','Marmelade auf Toast','Marmelade im Kuchen','chill','none'),
(411,'de','Wow, sie ist so eifersüchtig.','Wow, er ist so eifersüchtig.','eifersüchtig auf eine andere Tänzerin','eifersüchtig auf ihre Lehrerin','gossip','exaggeration'),
(413,'de','Der Saft ist rubinrot.','Der Saft ist knallorange.','frischer Granatapfelsaft','Orangensaft im Tetrapak','chill','none'),
(414,'de','Er ist über die Latte gesprungen!','Er ist über den Zaun gesprungen!','über die Latte springen','in den Pool springen','dramatic','exclamation'),
(415,'de','Dieses Känguru hat einen Passagier.','Dieser Koala hat einen Passagier.','ein Känguru mit Jungtier','ein Känguru mit Boxhandschuhen','chill','exaggeration'),
(416,'de','Der Ketchup hat endlich aufgegeben!','Der Senf hat endlich aufgegeben!','Ketchup auf Pommes','Ketchup auf einem Burger','dramatic','exaggeration'),
(418,'de','Sie hat ihren Schlüsselanhänger selbst gemacht.','Sie hat ihre Halskette selbst gemacht.','ein Schlüsselanhänger mit Bommel','ein Schlüsselanhänger mit Foto','chill','none'),
(419,'de','Sie kicken einen Ball.','Sie werfen einen Ball.','einen Ball herumkicken','eine Tür auftreten','chill','none'),
(423,'de','Sie küsst ihre Hand und pustet – er fängt den Kuss!','Er küsst seine Hand und pustet – sie fängt den Kuss!','einen Kuss zuwerfen','ein Gutenachtkuss','flirt','exclamation'),
(424,'de','Sein Messer schneidet Brot.','Sein Messer schneidet Käse.','ein großes Brotmesser','ein kleines Taschenmesser','business','none'),
(426,'de','Sie klettert, er hält nur die Leiter.','Sie klettert, er hält nur den Korb.','die Leiter festhalten','die Leiter streichen','gossip','banter'),
(427,'de','Der Marienkäfer fliegt weg.','Der Marienkäfer frisst ein Blatt.','ein Marienkäfer im Gras','ein Marienkäfer auf einer Hand','chill','none'),
(428,'de','Ein Kanu auf einem ruhigen See.','Ein Kanu auf einem ruhigen Meer.','ein ruhiger Bergsee','ein zugefrorener See','chill','none'),
(429,'de','Sie ist perfekt gelandet!','Sie ist im Wasser gelandet!','auf einer Wiese landen','ein Flugzeug landen','dramatic','exclamation'),
(430,'de','Er bringt ihr seine Sprache bei.','Sie bringt ihm ihre Sprache bei.','eine neue Sprache lernen','eine Lektion in der Sprach-App','chill','none'),
(431,'de','Faul? Nein, er ist ein „Genie“.','Faul? Nein, sie ist ein „Genie“.','ein fauler Mann zu Hause','eine faule Katze zu Hause','ironic','bad_excuse'),
(435,'de','Das Leder knarzt!','Der Boden knarzt!','Leder dehnen','ein Ledersofa','dramatic','exclamation'),
(436,'de','Alle machen einen Schritt nach links.','Alle machen einen Schritt nach rechts.','einen Schritt nach links machen','nach links springen','chill','none'),
(437,'de','Sie dehnt ihr Bein.','Sie dehnt ihren Arm.','ein Bein an der Wand','ein Bein im Gips','chill','none'),
(438,'de','Die Zitrone ist viel zu sauer!','Die Zitrone ist viel zu süß!','in eine Zitronenspalte beißen','ein Zitronenkuchen','slang','exclamation'),
(439,'de','Die Limonade ist mega kalt.','Die Limonade ist mega heiß.','Limonade im Einmachglas','Limonade in der Dose','slang','none'),
(440,'de','Er hebt eine Langhantel!','Er hebt ein Sofa!','eine schwere Langhantel heben','ein kleines Kind heben','dramatic','exclamation'),
(442,'de','Teamarbeit schlägt eine schwere Kiste.','Teamarbeit schlägt ein schweres Sofa.','Teamarbeit mit einer schweren Kiste','Teamarbeit auf dem Fußballplatz','business','cliche'),
(443,'de','Endlich Licht auf dem Dachboden!','Endlich Licht in der Küche!','Licht durchs Fenster','Licht von einer Kerze','dramatic','exclamation'),
(444,'de','Blitz! Hast du das gesehen?','Regenbogen! Hast du das gesehen?','nachts Blitze beobachten','ein Blitz am helllichten Tag','slang','exclamation'),
(445,'de','Ihre weiße Linie ist perfekt!','Ihre gelbe Linie ist perfekt!','eine weiße Linie malen','eine Schlange von Leuten','dramatic','exclamation'),
(446,'de','Der Löwe brüllt uns an!','Der Löwe rennt auf uns zu!','ein Löwe im Gras','ein Löwe im Käfig','dramatic','exclamation'),
(447,'de','Lippenbalsam rettet den Tag!','Handcreme rettet den Tag!','Lippenbalsam auftragen','Lippenbalsam kaufen','dramatic','cliche'),
(448,'de','Lipgloss, glänzend wie Glas.','Lipgloss, matt wie Papier.','glänzender rosa Lipgloss','dunkelroter Lipgloss','flirt','exaggeration'),
(449,'de','Pst, sie hören zu!','Pst, sie schlafen!','Zuhören im Wald','Musik hören','dramatic','exclamation'),
(450,'de','Die Eidechse sonnt sich.','Die Eidechse schwimmt.','eine Eidechse an der Wand','eine Eidechse in einer Kiste','chill','none'),
(451,'de','Sie schließt die Tür ab.','Sie macht die Tür auf.','eine Bootstür abschließen','eine Autotür abschließen','chill','none'),
(452,'de','Die haben das Logo sogar auf den Hund gepackt!','Die haben das Logo sogar auf die Katze gepackt!','ein Logo auf einem Halsband','ein Logo auf einem T-Shirt','gossip','exclamation'),
(453,'de','Er ist einsam in der Mensa.','Er ist einsam in der Bibliothek.','ein einsames Mittagessen','ein einsamer Heimweg','dramatic','none'),
(454,'de','Suppe und eine Decke: pure Liebe.','Tee und eine Decke: pure Liebe.','Liebe in einer Regennacht','Liebe auf den ersten Blick','flirt','exaggeration'),
(455,'de','Sie hat eine mega starke Lunge.','Er hat eine mega starke Lunge.','eine Lunge voller Luft','eine Lunge voller Rauch','chill','exaggeration'),
(456,'de','Die Zeitschrift gehört jetzt ihr.','Die Zeitung gehört jetzt ihr.','in einer Zeitschrift blättern','eine Zeitschrift im Zug','gossip','guessing'),
(457,'de','Ein Profi macht ihr Make-up.','Ein Profi macht ihr die Haare.','Make-up vor dem Spiegel auftragen','Make-up vor dem Spiegel entfernen','chill','none'),
(458,'de','Ein großer Mann trägt eine Kiste.','Ein großer Mann trägt einen Hund.','Männer beim Schach','Männer beim Kartenspielen','chill','none'),
(459,'de','Der Manager verteilt Befehle.','Der Manager verteilt Blumen.','ein Manager mit Klemmbrett','ein Manager im Fußball','business','none'),
(461,'de','Er macht die Schaufensterpuppe nach. Zwillinge!','Er bemalt die Schaufensterpuppe. Zwillinge!','eine Schaufensterpuppe anziehen','eine Schaufensterpuppe im Schaufenster','low_iq','exclamation'),
(462,'de','Die Karte hat den Brunnen gefunden!','Die Karte hat die Kirche gefunden!','eine große Papierkarte','eine Karte auf dem Handy','low_iq','exaggeration'),
(464,'de','Sie malt mit einem Marker.','Sie malt mit Kreide.','ein dicker pinker Marker','ein Marker am Whiteboard','chill','none'),
(465,'de','Sie kauft auf dem Markt ein.','Sie kauft im Einkaufszentrum ein.','ein belebter Straßenmarkt','ein belebtes Straßenfest','chill','none'),
(466,'de','Das Wimperntusche-Gesicht: Mund weit offen.','Das Wimperntusche-Gesicht: Augen fest zu.','schwarze Wimperntusche auftragen','verlaufene Wimperntusche auf den Wangen','gossip','cliche'),
(467,'de','Der Meister formt eine Vase.','Der Meister bemalt eine Vase.','ein Töpfermeister','ein Meister am Klavier','chill','none'),
(468,'de','Sie liegen auf ihren Yogamatten.','Sie liegen auf ihren Handtüchern.','eine lila Yogamatte','eine Fußmatte an der Tür','chill','none'),
(469,'de','Diese Streichhölzer zünden beim ersten Mal!','Dieses Feuerzeug zündet beim ersten Mal!','eine Schachtel Streichhölzer','nasse Streichhölzer','dramatic','exclamation'),
(470,'de','Sie sind in die Wiese gefallen.','Sie sind in den Fluss gefallen.','eine Wiese voller Mohnblumen','eine Wiese voller Kühe','chill','none'),
(471,'de','Der Hund will das Fleisch.','Die Katze will das Fleisch.','gegrilltes Fleisch auf einem Brett','rohes Fleisch im Laden','low_iq','guessing'),
(472,'de','Der Mechaniker repariert ein Auto.','Der Mechaniker repariert ein Fahrrad.','ein Mechaniker in der Werkstatt','ein Mechaniker auf der Straße','chill','none'),
(473,'de','Sie beißt in ihre Goldmedaille. Echtes Gold?','Sie beißt in ihren Goldring. Echtes Gold?','in eine Goldmedaille beißen','eine Medaille in einer Schachtel','dramatic','guessing'),
(474,'de','Gruppenmeditation bei Sonnenuntergang.','Gruppenmeditation am Strand.','Meditation auf einer Holzterrasse','Meditation im Tempel','chill','none'),
(475,'de','Jede Erinnerung bringt sie zum Lächeln.','Jede Erinnerung bringt sie zum Weinen.','eine Kiste voller Erinnerungen','eine Speicherkarte für die Kamera','chill','none'),
(476,'de','Er benutzt ein Mikroskop.','Er benutzt ein Teleskop.','ein Blatt unter dem Mikroskop','ein Käfer unter dem Mikroskop','nerd','none'),
(477,'de','Mikrowellen-TV ist die beste Sendung.','Backofen-TV ist die beste Sendung.','der Mikrowelle zuschauen','die Mikrowelle putzen','ironic','exaggeration'),
(478,'de','Alle haben einen Milchbart!','Keiner hat einen Milchbart!','ein Milchbart','Milch im Kühlschrank','dramatic','exaggeration'),
(480,'de','Das Mineralwasser kitzelt sie.','Der Orangensaft kitzelt sie.','sprudelndes Mineralwasser','stilles Mineralwasser','chill','none'),
(481,'de','Der Spiegel liebt ihn zurück.','Das Fenster liebt ihn zurück.','vor dem Spiegel posen','den Spiegel putzen','low_iq','guessing'),
(483,'de','Der Affe hat eine Banane geklaut!','Der Affe hat einen Hut geklaut!','ein Affe isst eine Banane','ein Affe verkauft eine Banane','dramatic','exclamation'),
(484,'de','Sie wischt mit dem Mopp den Boden.','Sie fegt mit dem Besen den Boden.','ein Mopp im Eimer','eine Mähne aus Locken','chill','none'),
(485,'de','Das Moos ist weich. Gutes Kissen.','Das Heu ist weich. Gutes Kissen.','weiches grünes Moos','Moos auf dem Dach','low_iq','none'),
(486,'de','Oben auf dem Berg, ja!','Unten am Berg, ja!','oben auf einem Berg','ein Bergsee','dramatic','exclamation'),
(487,'de','Die Maus hat den Käse gefunden.','Die Maus hat das Brot gefunden.','eine Maus in der Scheune','Maus und Tastatur','chill','none'),
(488,'de','Seine Muskeln sind riesig!','Seine Schuhe sind riesig!','dicke Muskeln zeigen','ein Muskel im Bein','dramatic','exclamation'),
(489,'de','Der Pilz hat weiße Punkte.','Der Pilz hat schwarze Punkte.','ein roter Pilz mit Punkten','eine rote Pilzsuppe','chill','none'),
(490,'de','Dieser Musiker wird berühmt.','Dieser Tänzer wird berühmt.','ein Straßenmusiker','ein Musiker in einer Band','gossip','guessing'),
(491,'de','Der Senf ist scharf.','Der Honig ist scharf.','ein Löffel Senf','ein Glas Senfkörner','chill','none'),
(492,'de','Ihr Nagellack ist noch nass!','Ihre Haare sind noch nass!','Nägel mit Nagellack lackieren','alten Nagellack entfernen','dramatic','exclamation'),
(495,'de','Sie entspannen in der Natur.','Sie rennen in der Natur.','in der Natur liegen','ein Naturfilm','chill','none'),
(496,'de','Schöne Halskette, gute Wahl.','Schönes Armband, gute Wahl.','eine bunte Perlen-Halskette','eine goldene Halskette','flirt','none'),
(498,'de','So nervös vor der Show!','So nervös vor der Prüfung!','ein nervöser Gitarrist','ein nervöser Schüler vor Prüfungen','dramatic','exclamation'),
(499,'de','Kuckuck mit der Zeitung!','Kuckuck mit der Speisekarte!','sich hinter einer Zeitung verstecken','Zeitung online lesen','slang','exclamation'),
(500,'de','Er dribbelt an ihm vorbei, als wäre er nicht da.','Er dribbelt an drei Leuten vorbei, als wären sie nicht da.','an einem Verteidiger vorbeidribbeln','am Torwart vorbeidribbeln','slang','exaggeration'),
(501,'de','Sie gehen in der Nacht spazieren.','Sie gehen am Mittag spazieren.','in der Nacht nach Hause gehen','in der Nacht arbeiten','chill','none'),
(502,'de','Sie gehen Richtung Norden.','Sie gehen Richtung Süden.','mit Kompass nach Norden','der Norden einer Stadt','business','none'),
(503,'de','Ein neues Notizbuch! Großer Moment.','Ein neuer Laptop! Großer Moment.','ein nagelneues Notizbuch','ein Notizbuch voller Notizen','ironic','exclamation'),
(505,'de','Er kämpft gegen eine winzige Nuss.','Er kämpft gegen ein winziges Ei.','eine Nuss knacken','eine Nuss in Schokolade','low_iq','exaggeration'),
(506,'de','Ihr Teller: reine gesunde Ernährung.','Ihr Teller: reiner Zucker.','ein Teller voll gesunder Ernährung','Nährwertangaben auf einer Packung','nerd','exaggeration'),
(507,'de','Sie beobachtet eine Libelle.','Sie beobachtet einen Schmetterling.','eine Libelle beobachten','eine Libelle fangen','nerd','none'),
(508,'de','Delfine im Ozean! Echt jetzt?','Haie im Ozean! Echt jetzt?','Delfine im Ozean','im Ozean schwimmen','dramatic','exclamation'),
(509,'de','Das Öl fließt langsam.','Die Milch fließt langsam.','Brot in Olivenöl','Öl in der Bratpfanne','chill','none'),
(511,'de','Er schneidet Zwiebeln mit Schwimmbrille. Genial!','Er schneidet Zwiebeln mit Sonnenbrille. Genial!','eine weiße Zwiebel hacken','eine weiße Zwiebel braten','low_iq','exclamation'),
(512,'de','Das Outfit passt endlich.','Die Frisur passt endlich.','ein Outfit zusammenstellen','ein Outfit für eine Hochzeit','chill','none'),
(513,'de','Sie essen draußen. Wer braucht schon ein Esszimmer?','Sie essen drinnen. Wer braucht schon ein Esszimmer?','draußen im Gras essen','draußen im Café essen','ironic','guessing'),
(514,'de','Der Backofen ist ihr neuer Fernseher.','Der Kühlschrank ist ihr neuer Fernseher.','Brot geht im Backofen auf','Pizza im Backofen','slang','exaggeration'),
(515,'de','Sie hat die Wand überwunden!','Sie hat den Fluss überwunden!','eine Kletterwand überwinden','die Angst vor Hunden überwinden','dramatic','exclamation'),
(516,'de','Das Waschbecken ist übergelaufen. Ups.','Die Badewanne ist übergelaufen. Ups.','ein überlaufendes Waschbecken','ein überlaufender Mülleimer','ironic','understatement'),
(517,'de','Tschüss, Camper! Er überholt!','Tschüss, Camper! Er parkt!','einen langsamen Camper überholen','einen schnellen Zug überholen','slang','exclamation'),
(518,'de','Die Eule beobachtet dich.','Die Krähe beobachtet dich.','eine Eule auf einem Ast','eine Eule im Käfig','dramatic','exaggeration'),
(519,'de','Die Tasche ist für die Schule gepackt.','Die Tasche ist für eine Reise gepackt.','eine Schultasche packen','einen Koffer packen','chill','none'),
(520,'de','Sie paddelt, er schläft.','Sie paddelt, er angelt.','mit dem Kanu paddeln','auf dem Surfbrett paddeln','gossip','banter'),
(521,'de','Sein Zeh: höllische Schmerzen!','Seine Hand: höllische Schmerzen!','Schmerzen im Zeh','Schmerzen im Rücken','dramatic','exclamation'),
(522,'de','Ihr Gemälde ist schöner als die echte Aussicht, sagt sie.','Ihr Gemälde ist schlechter als die echte Aussicht, sagt sie.','ein Gemälde vom Meer','eine Wand weiß streichen','gossip','exaggeration'),
(523,'de','Coole Moves mit der Pfanne!','Coole Moves mit dem Pizzateig!','Gemüse in der Pfanne','Pfannkuchen in der Pfanne','flirt','exclamation'),
(524,'de','Panikmodus: Der Zug ist ohne sie abgefahren!','Panikmodus: Der Bus ist ohne sie abgefahren!','Panik am Bahnsteig','Panik im Flugzeug','dramatic','exclamation'),
(525,'de','Eine kleine Büroklammer besiegt den großen Ventilator.','Ein kleiner Tacker besiegt den großen Ventilator.','eine Büroklammer an den Blättern','eine Büroklammer hält ein Foto','dramatic','exaggeration'),
(526,'de','Die Strahlenkanone hat ihn gelähmt!','Die Wasserpistole hat ihn gelähmt!','von einer Strahlenkanone gelähmt','vor Angst gelähmt','dramatic','exclamation'),
(527,'de','Sie hat ein Paket bekommen!','Sie hat einen Brief bekommen!','ein Paket öffnen','ein Paket verschicken','dramatic','exclamation'),
(528,'de','Sie parkt wie ein Profi!','Er parkt wie ein Profi!','zwischen zwei Autos parken','in einer Garage parken','slang','exaggeration'),
(530,'de','Der Papagei sagt Hallo.','Der Papagei sagt Tschüss.','ein Papagei auf einem Geländer','ein Papagei im Käfig','chill','none'),
(531,'de','Diese Gartenparty ist der Hammer.','Diese Poolparty ist der Hammer.','eine Gartenparty bei Sonnenuntergang','eine Poolparty','slang','none'),
(532,'de','Er spielt ab, sie trifft, easy.','Sie spielt ab, er trifft, easy.','den Ball zu ihr abspielen','ein langsames Auto überholen','slang','none'),
(533,'de','Sie hat ihren Reisepass geküsst!','Sie hat ihren Koffer geküsst!','ein Reisepass mit Stempeln','ein Passbildautomat','dramatic','exclamation'),
(535,'de','Der Pasta-Turm sieht professionell aus.','Der Tortenturm sieht professionell aus.','ein Turm aus Pasta','Pasta im Salat','business','none'),
(536,'de','Sie findet Ruhe in einer Hängematte.','Sie findet Ruhe in einer Badewanne.','Ruhe bei Sonnenaufgang','Ruhe um Mitternacht','chill','none'),
(537,'de','Sie schält einen roten Apfel.','Sie schält einen grünen Apfel.','in einer Spirale schälen','eine Banane schälen','chill','none'),
(538,'de','Sein Kugelschreiber hat viele Farben.','Sein Kugelschreiber hat nur eine Farbe.','ein Kugelschreiber mit vielen Farben','ein Kugelschreiber mit Licht','chill','none'),
(540,'de','Sie hat den Elfmeter verwandelt!','Sie hat den Elfmeter verschossen!','einen Elfmeter verwandeln','einen Elfmeter halten','dramatic','exclamation'),
(541,'de','Ihre Bleistiftzeichnung ist so gut.','Ihre Kugelschreiberzeichnung ist so gut.','mit einem gelben Bleistift zeichnen','einen gelben Bleistift spitzen','flirt','none'),
(542,'de','Bauchrutscher! Los, Pinguin!','Bauchrutscher! Los, Robbe!','ein Pinguin auf dem Eis','ein Pinguin im Zoo','slang','exclamation'),
(543,'de','Der Pfeffer hat ihn zum Niesen gebracht!','Die Zwiebel hat ihn zum Niesen gebracht!','schwarzen Pfeffer mahlen','Kaffeebohnen mahlen','dramatic','blaming_someone'),
(545,'de','Was für ein Jonglier-Auftritt!','Was für ein Tanz-Auftritt!','ein Jonglier-Auftritt auf der Straße','eine Prüfungsleistung in der Schule','dramatic','exclamation'),
(546,'de','Das ist viel zu viel Parfüm!','Das ist viel zu viel Wasser!','Parfüm auf eine Freundin sprühen','Parfüm auf ein Kleid sprühen','slang','exaggeration'),
(547,'de','Ihr Handy klingelt!','Ihre Türklingel klingelt!','ans Handy gehen','ein Handy in der Tasche','dramatic','exclamation'),
(548,'de','Das da! Fotografie macht Spaß.','Das da! Malen macht Spaß.','Straßenfotografie bei Sonnenuntergang','Hochzeitsfotografie drinnen','dramatic','exclamation'),
(549,'de','Eine goldene Creole für ihr Piercing.','Ein goldener Stecker für ihr Piercing.','ein Piercing mit goldener Creole','ein Piercing in der Nase','chill','none'),
(550,'de','Das Schwein wälzt sich im Schlamm.','Das Schwein wälzt sich im Schnee.','ein Schwein auf dem Hof','ein Schwein in der Badewanne','chill','none'),
(551,'de','Die Taube inspiziert das Café.','Die Taube inspiziert die Bank.','eine Taube auf einem Platz','eine Taube im Park','business','exaggeration'),
(553,'de','Er ist so stolz auf sein Spielfeld.','Er ist so stolz auf sein Auto.','das Spielfeld mähen','das Spielfeld anstreichen','gossip','none'),
(554,'de','Perfekter Platz am Strand.','Perfekter Platz im Park.','der perfekte Platz zum Sitzen','ein Platz in der Schlange','chill','none'),
(555,'de','Die Pflanze hat ein neues Blatt!','Die Pflanze hat eine neue Blüte!','eine Pflanze mit großen Blättern','eine Pflanze mit roten Blüten','dramatic','exclamation'),
(556,'de','Er hat ihr mit einem Pflaster das Leben gerettet.','Er hat ihr mit etwas Eis das Leben gerettet.','ein Pflaster auf der Fingerkuppe','Pflaster auf der Straße','ironic','exaggeration'),
(557,'de','Der Koch serviert den Teller.','Der Koch spült den Teller.','Spaghetti auf einem weißen Teller','ein Stapel leerer Teller','business','none'),
(558,'de','Er hat beim Volleyballspielen seinen Hut verloren.','Er hat beim Volleyballspielen seinen Schuh verloren.','im Park Volleyball spielen','im Park Karten spielen','chill','none'),
(559,'de','Dieser Spieler ist so glücklich!','Dieser Spieler ist so wütend!','ein Spieler in Gelb','ein Spieler auf der Bank','dramatic','exclamation'),
(560,'de','Erst das Selfie, dann der Springbrunnen.','Erst das Selfie, dann die Pizza.','der berühmte Trevi-Brunnen','ein Springbrunnen im Einkaufszentrum','chill','cliche'),
(562,'de','Der Stecker war das Problem.','Die Glühbirne war das Problem.','ein lockerer Stecker','ein Badewannenstöpsel','chill','understatement'),
(563,'de','Die Schlüssel waren in seiner Tasche!','Die Schlüssel waren in seinem Schuh!','Schlüssel in der Jackentasche','Schlüssel in der Autotür','low_iq','exclamation'),
(564,'de','Ihr Siegertreppchen ist aus Schaumstoff.','Ihr Siegertreppchen ist aus Gold.','ein Siegertreppchen aus Schaumstoff','ein Podium auf einer Konferenz','ironic','cheap_quality'),
(565,'de','In diesem Politikspiel hat Orange gewonnen.','In diesem Politikspiel hat Grün gewonnen.','Politik auf dem Marktplatz','Politik im Fernsehen','gossip','none'),
(566,'de','Er verschmutzt den Fluss. Schande!','Er säubert den Fluss. Schande!','einen sauberen Fluss verschmutzen','das Meer verschmutzen','dramatic','blaming_someone'),
(567,'de','In diesem Teich leben Goldfische.','In diesem Teich leben Frösche.','Goldfische im Teich','Enten auf dem Teich','chill','none'),
(568,'de','Sie wollte einen ruhigen Tag am Swimmingpool.','Sie wollte einen ruhigen Tag am See.','in den Swimmingpool platschen','ein Billardtisch','chill','guessing'),
(569,'de','Der Postmeister ist sehr herrisch.','Der Postmeister ist sehr schüchtern.','ein herrischer Postmeister','ein Postmeister im Urlaub','gossip','none'),
(571,'de','Das Wasser im Topf tanzt!','Das Wasser im Topf gefriert!','Kartoffeln in einem großen Topf','Blumen in einem großen Topf','low_iq','exaggeration'),
(572,'de','Sie haben jede Menge Kartoffeln gefunden!','Sie haben jede Menge Karotten gefunden!','Kartoffeln ausgraben','Kartoffeln schälen','dramatic','exclamation'),
(573,'de','Sein Eingießen zeigt echtes Können.','Sein Singen zeigt echtes Können.','Eingießen aus großer Höhe','strömender Regen draußen','business','none'),
(574,'de','Was für eine Wolke aus Puder!','Was für eine Wolke aus Rauch!','Puder aufs Gesicht pinseln','Puderzucker auf einem Kuchen','dramatic','exclamation'),
(575,'de','Ihre Powerbank hat den Tag gerettet!','Seine Powerbank hat den Tag gerettet!','an einer Powerbank laden','eine Powerbank zu Hause','dramatic','cliche'),
(576,'de','Sie betet für eine gute Note.','Sie betet für ein neues Handy.','für eine gute Note beten','in einer Kirche beten','dramatic','none'),
(577,'de','Sie hat den Regen vorhergesagt. Er nicht.','Sie hat den Schnee vorhergesagt. Er nicht.','den Regen vorhersagen','die Lottozahlen vorhersagen','gossip','banter'),
(578,'de','Sie strahlt vor Stolz.','Sie weint vor Stolz.','Stolz auf ihr Motorrad','Stolz auf ihr neues Auto','chill','none'),
(579,'de','Einen Roboter zu programmieren ist schwer.','Eine Drohne zu programmieren ist schwer.','einen kleinen Roboter programmieren','ein Videospiel programmieren','chill','understatement'),
(580,'de','Sie schützt sie vor dem Regen.','Sie schützt sie vor der Sonne.','jemanden vor Regen schützen','jemanden vor einem Hund schützen','chill','none'),
(581,'de','Protestieren mit Sonnenblumen!','Protestieren mit Regenschirmen!','für die Natur protestieren','im Regen protestieren','dramatic','exclamation'),
(582,'de','Sie ist stolz auf ihren Stuhl.','Sie ist stolz auf ihren Tisch.','stolz auf ihre Arbeit','stolz auf ihr Auto','chill','none'),
(584,'de','Sie hat ihm bewiesen, dass er falschliegt. Easy.','Er hat ihr bewiesen, dass sie falschliegt. Easy.','beweisen, dass er falschliegt','beweisen, dass sie falschliegt','ironic','understatement'),
(585,'de','Sie spielt öffentlich Musik.','Sie spielt öffentlich Schach.','öffentlich Musik machen','ein öffentliches Schwimmbad','chill','none'),
(587,'de','Gelb hat mit dem Puck getroffen!','Lila hat mit dem Puck getroffen!','ein Puck im Netz','ein Puck auf der Tribüne','dramatic','exclamation'),
(588,'de','Platsch! Ein großer Pfützensprung.','Platsch! Ein großer Poolsprung.','in eine Pfütze springen','um eine Pfütze herumgehen','slang','exclamation'),
(589,'de','Hartes Ziehen, Happy End.','Hartes Schieben, Happy End.','an einem dicken Seil ziehen','eine Tür aufziehen','chill','cliche'),
(590,'de','Sie schlägt zu wie ein Profi!','Sie tritt zu wie ein Profi!','auf die Pratzen schlagen','gegen die Wand schlagen','slang','exaggeration'),
(591,'de','Er ist verliebt in seinen Boxsack.','Er ist verliebt in seine Garagenleiter.','einen Boxsack aufhängen','gegen das Garagentor schlagen','gossip','guessing'),
(592,'de','Einen Transporter schieben? Easy!','Einen Bus schieben? Easy!','einen weißen Transporter schieben','ein weißes Auto schieben','ironic','understatement'),
(593,'de','Schlafanzüge im Partnerlook? So süß!','Jacken im Partnerlook? So süß!','karierte Partnerlook-Schlafanzüge','gestreifte Partnerlook-Schlafanzüge','flirt','exclamation'),
(594,'de','Mit dem Sprung hat sie sich qualifiziert.','Mit dem Schwimmen hat sie sich qualifiziert.','sich für die nächste Runde qualifizieren','sich als Ärztin qualifizieren','chill','none'),
(595,'de','Das Kaninchen sitzt aufrecht.','Das Kaninchen liegt flach.','ein Kaninchen in den Dünen','ein Kaninchen im Hut','chill','none'),
(596,'de','Los, los, los! Was für ein Rennen!','Los, los, los! Was für ein Wettschwimmen!','ein Rennen auf der Bahn','ein Rennen im Pool','dramatic','exclamation'),
(597,'de','Cooler Trick mit dem Schläger.','Cooler Trick mit der Flasche.','ein schwarzer Tennisschläger','ein Badmintonschläger','slang','none'),
(598,'de','Sie tanzt im Regen.','Sie tanzt im Schnee.','im Starkregen tanzen','sich vor dem Regen verstecken','chill','none'),
(599,'de','Diese Moves sind mega rasant.','Diese Moves sind mega langsam.','rasante Übersteiger','rasante Pässe','slang','none'),
(600,'de','Die Ratte klaut Pizza!','Die Ratte klaut Brot!','eine Ratte mit Pizza','eine Ratte im Käfig','dramatic','exclamation'),
(601,'de','Er rasiert sich mit einem Rasierer.','Er rasiert sich mit einem Messer.','ein elektrischer Rasierer','eine Rasierklinge','chill','none'),
(602,'de','Lesen im Zug bei Nacht.','Lesen auf einem Boot bei Nacht.','Lesen im Nachtzug','Lesen in der Bibliothek','chill','none'),
(604,'de','Dieser Kassenbon hört nie auf!','Diese Speisekarte hört nie auf!','ein sehr langer Kassenbon','ein sehr kurzer Kassenbon','slang','exaggeration'),
(606,'de','Laut Rezept: zuerst die Eier.','Laut Rezept: zuerst der Fisch.','eine handgezeichnete Rezeptkarte','ein Rezept für Suppe','business','none'),
(607,'de','Der Kühlschrank ist jetzt voll.','Der Backofen ist jetzt voll.','den Kühlschrank einräumen','den Kühlschrank putzen','chill','none'),
(608,'de','Eingeparkt! Was für eine Erleichterung!','Gecrasht! Was für eine Erleichterung!','Erleichterung nach dem Einparken','Erleichterung nach einem Unfall','dramatic','exclamation'),
(609,'de','Sie ruhen sich auf dem Hügel aus.','Sie rennen auf dem Hügel.','sich auf einem Hügel ausruhen','sich in einer Hängematte ausruhen','chill','none'),
(610,'de','Der Kürbis hat ein blaues Band bekommen. Sie ist geschockt!','Die Karotte hat ein blaues Band bekommen. Sie ist geschockt!','das blaue Band eines Kürbisses','ein Band in ihrem Haar','gossip','none'),
(612,'de','Sie zeigt nach rechts.','Sie zeigt zum Himmel.','rechts an den Ständen vorbei','an der Ampel rechts abbiegen','chill','none'),
(613,'de','Er hüpft im Ring.','Er hüpft im Pool.','in den Ring steigen','ein Ring am Finger','chill','none'),
(615,'de','Blätterrennen auf dem Fluss. Los, los!','Bootsrennen auf dem Fluss. Los, los!','Blätter auf einem klaren Fluss','ein Boot auf einem Fluss','slang','none'),
(616,'de','Fels: eins. Menschen: null.','Baum: eins. Menschen: null.','einen riesigen Felsen schieben','einen kleinen Stein werfen','slang','cliche'),
(617,'de','Sie kam auf Inlineskates, nur um ihm sein Getränk zu klauen!','Sie kam mit dem Fahrrad, nur um ihm sein Getränk zu klauen!','lila Inlineskates im Park','Inlineskates auf einer Eisbahn','dramatic','exaggeration'),
(618,'de','Das Seil hat den Karren gerettet!','Die Kette hat den Karren gerettet!','ein Seil um ein Rad','ein Seil zum Seilspringen','dramatic','exaggeration'),
(619,'de','Sie lässt einen Korb herab.','Sie lässt einen Eimer herab.','einen Korb am Seil herablassen','die Lautstärke senken','chill','none'),
(620,'de','Diese Rose duftet himmlisch.','Diese Tulpe duftet himmlisch.','an einer rosa Rose riechen','eine rosa Rose kaufen','dramatic','cliche'),
(621,'de','Die Reihe ist perfekt gerade.','Die Reihe ist perfekt rund.','in einer geraden Reihe pflanzen','in der ersten Reihe sitzen','business','none'),
(622,'de','Ein Gummiband hält die Kräuter zusammen.','Ein Gummiband hält den Lauch zusammen.','ein orangefarbenes Gummiband','ein Gummiband fürs Haar','business','none'),
(623,'de','Was für ein unhöflicher Typ!','Was für ein netter Typ!','ein unhöflicher Gast im Café','eine unhöfliche Kellnerin','slang','exclamation'),
(624,'de','Sie rennt ihrem Hut hinterher!','Sie rennt ihrem Hund hinterher!','einem Hut hinterherrennen','einem Bus hinterherrennen','dramatic','exclamation'),
(626,'de','Der Läufer trinkt Wasser.','Der Läufer isst eine Banane.','ein Läufer trinkt Wasser','ein Läufer auf dem Laufband','chill','none'),
(627,'de','Laufsteg im Wohnzimmer. Zeig''s uns!','Laufsteg in der Küche. Zeig''s uns!','ein Laufsteg im Wohnzimmer','eine Landebahn am Flughafen','slang','exclamation'),
(628,'de','Ihr Gesicht ist voller Traurigkeit.','Ihr Gesicht ist voller Freude.','Traurigkeit in einem leeren Laden','Traurigkeit auf einer Beerdigung','dramatic','none'),
(629,'de','Drinnen sicher, draußen Sturm.','Drinnen sicher, draußen Sonne.','sicher in einer Berghütte','ein Tresor an der Wand','chill','cliche'),
(630,'de','Der Matrose ist am Steuer!','Der Matrose ist am Tisch!','ein Matrose an Deck','ein Matrose in einer Bar','slang','exclamation'),
(631,'de','Er macht Salate supereffizient.','Er macht Kuchen supereffizient.','einen frischen Salat anmachen','ein Salat in der Box','business','none'),
(632,'de','Sie streuen Salz auf die Tomaten.','Sie streuen Salz auf die Kartoffeln.','Salz auf Tomatenscheiben','Salz auf einer verschneiten Straße','chill','none'),
(634,'de','Eine Welle hat ihre Sandkunst gefressen.','Ein Hund hat ihre Sandkunst gefressen.','in den Sand malen','eine Sandburg bauen','slang','exaggeration'),
(635,'de','Sandalen an, Zehen raus!','Stiefel an, Zehen raus!','hellbraune Sandalen zuschnallen','hellbraune Sandalen kaufen','slang','none'),
(636,'de','Sogar die Ente will das Sandwich.','Sogar der Hund will das Sandwich.','ein Sandwich mit Schinken und Käse','ein Sandwich in der Brotdose','chill','guessing'),
(637,'de','Ein Granatapfel: Hunderte Kerne.','Eine Wassermelone: Hunderte Kerne.','einen Granatapfel öffnen','Granatapfelsaft im Glas','nerd','exaggeration'),
(638,'de','Er hat viel zu viel Soße genommen!','Er hat viel zu viel Salz genommen!','ein Teller voller Soße','Soße in der Flasche','slang','exaggeration'),
(639,'de','Er brät Würste.','Er brät Eier.','Würste in der Pfanne braten','Würste auf der Pizza','chill','none'),
(640,'de','Die Waage muss kaputt sein!','Die Uhr muss kaputt sein!','eine große Waage mit Zeiger','eine Küchenwaage','low_iq','bad_excuse'),
(641,'de','Die Katze ist auf der Waage!','Der Hund ist auf der Waage!','eine Katze auf der Waage','eine Waage auf dem Markt','gossip','exclamation'),
(642,'de','Sie vergleichen Narben.','Sie vergleichen Tattoos.','ihre Narben vergleichen','ihre Narben verstecken','chill','none'),
(644,'de','Wer ist da? Sie ist verängstigt!','Wer ist da? Er ist verängstigt!','verängstigt im Parkhaus','verängstigt in der Achterbahn','dramatic','exclamation'),
(645,'de','Er organisiert seinen Zeitplan.','Er organisiert seinen Schreibtisch.','einen Zeitplan erstellen','ein Busfahrplan','business','none'),
(646,'de','Wissenschaft macht orangefarbenen Schaum!','Wissenschaft macht blauen Schaum!','ein Wissenschaftsexperiment','ein Wissenschaftsmuseum','dramatic','exclamation'),
(647,'de','Nur ein bisschen nachschneiden mit der Schere.','Nur ein bisschen nachschneiden mit dem Rasierer.','den Pony mit der Schere schneiden','Papier mit der Schere schneiden','ironic','understatement'),
(649,'de','Oma schimpft schon wieder mit ihm.','Oma umarmt ihn schon wieder.','mit dem Enkel schimpfen','mit dem Hund schimpfen','gossip','none'),
(650,'de','Er hat die letzte Schraube gefunden!','Er hat den letzten Nagel gefunden!','die letzte fehlende Schraube','die letzte fehlende Socke','dramatic','exclamation'),
(651,'de','Sie benutzt den Schraubendreher, er macht sich Sorgen.','Sie benutzt den Hammer, er macht sich Sorgen.','mit dem Schraubendreher festziehen','ein Schraubendreher in seiner Hand','gossip','banter'),
(652,'de','Iiih! Das Meer ist salzig!','Iiih! Der See ist salzig!','ins Meer springen','ein Meer von Menschen','dramatic','exclamation'),
(653,'de','So viel Suchen! Die Schlüssel waren in der Tür.','So viel Suchen! Die Schlüssel waren im Auto.','verlorene Schlüssel suchen','einen verlorenen Hund suchen','dramatic','exclamation'),
(654,'de','Sie flüstert ein Geheimnis.','Sie schreit ein Geheimnis heraus.','ein Geheimnis flüstern','ein Geheimnis aufschreiben','chill','none'),
(655,'de','Partyhüte? Sie bleibt ernst.','Partyhüte? Er bleibt ernst.','ein ernstes Gesicht bei der Arbeit','ein ernstes Gespräch beim Abendessen','ironic','understatement'),
(656,'de','Die ganze Menge kann sie nicht ablenken!','Die ganze Menge kann ihn nicht ablenken!','versuchen, sie abzulenken','versuchen, einen Hund abzulenken','dramatic','exclamation'),
(657,'de','Sie serviert Nudeln wie ein Profi.','Sie serviert Pizza wie ein Profi.','eine Nudelschüssel servieren','einen Tennisball aufschlagen','slang','none'),
(659,'de','Das ist eine Menge Shampoo!','Das ist eine Menge Creme!','ein Turm aus Shampoo-Schaum','ein Shampoo für Hunde','dramatic','exclamation'),
(660,'de','Wer braucht einen Salon? Eine Waschschüssel reicht.','Wer braucht einen Salon? Ein Eimer reicht.','Haare über einer Waschschüssel waschen','Geschirr in einer Waschschüssel spülen','ironic','cheap_quality'),
(661,'de','Der Hai lächelt dich an.','Der Delfin lächelt dich an.','ein Hai nah an der Kamera','ein Hai nah an einem Boot','dramatic','guessing'),
(662,'de','Der Spitzer funktioniert perfekt.','Der Spitzer funktioniert schlecht.','ein kleiner Bleistiftspitzer','ein kleiner Messerschärfer','business','none'),
(663,'de','Rasierschaum: Sofort-Bart!','Rasierschaum: Sofort-Hut!','eine Rasierschaum-Spirale','Rasierschaum auf einem Kuchen','low_iq','exaggeration'),
(664,'de','Rasieren von Hand, Old School.','Waxing von Hand, Old School.','mit dem Rasiermesser rasieren','mit dem Elektrorasierer rasieren','slang','cliche'),
(665,'de','Ist das Schaf sauer auf mich?','Ist die Ziege sauer auf mich?','ein Schaf am Hang','ein Schaf im Stall','low_iq','exaggeration'),
(666,'de','Er zieht ein blaues Hemd an.','Er zieht ein rotes Hemd an.','ein hellblaues Hemd zuknöpfen','ein hellblaues Hemd bügeln','chill','none'),
(667,'de','Der umgefallene Roller ist ein Schock.','Das umgefallene Fahrrad ist ein Schock.','Schock über einen umgefallenen Roller','ein elektrischer Schock','dramatic','none'),
(668,'de','Schuhe geschnürt. Bereit.','Stiefel geschnürt. Bereit.','braune Schuhe schnüren','braune Schuhe putzen','business','none'),
(669,'de','Mit drei Münzen kommt man in diesem Laden weit.','Mit zehn Münzen kommt man in diesem Laden weit.','ein kleiner Lebensmittelladen','ein kleiner Blumenladen','gossip','cheap_quality'),
(670,'de','Sie kauft effizient ein.','Sie schwimmt effizient.','im Supermarkt einkaufen','Kleidung einkaufen','business','none'),
(671,'de','Zu viel Schreien, jetzt sind alle heiser.','Zu viel Singen, jetzt sind alle heiser.','über ein Tal schreien','den Fernseher anschreien','chill','exaggeration'),
(672,'de','Duschen mit Eiswasser!','Duschen mit heißem Wasser!','am Strand duschen','im Badezimmer duschen','dramatic','exaggeration')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
