begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(1110,'de','Küsschen von der Enkelin!','Küsschen vom Enkel!','ein Kuss der Enkelin','eine Zeichnung der Enkelin','slang','exclamation'),
(1112,'de','Großmutter macht Brot.','Großmutter macht Suppe.','Backen mit Großmutter','Stricken mit Großmutter','chill','none'),
(1115,'de','Tanzen in Griechenland? Schicker Stil.','Tauchen in Griechenland? Schicker Stil.','Tanzen in Griechenland','Schwimmen in Griechenland','flirt','none'),
(1116,'de','Der Bräutigam trägt sie.','Der Bräutigam trägt eine Torte.','ein Bräutigam trägt seine Braut','ein Bräutigam striegelt ein Pferd','flirt','none'),
(1119,'de','Der Reiseführer leitet die Tour.','Der Reiseführer leitet das Rennen.','ein Reiseführer mit Regenschirm','ein Bergführer beim Klettern','business','none'),
(1120,'de','Dieser Typ wirft seine Schlüssel hoch, voll cool.','Dieser Typ wirft sein Handy hoch, voll cool.','ein Typ mit Pizza','ein Typ mit Gitarre','slang','none'),
(1123,'de','Ihr Flur ist eine Tanzfläche!','Ihre Küche ist eine Tanzfläche!','durch den Flur tanzen','durch den Flur rennen','slang','exclamation'),
(1125,'de','Boote ruhen im Hafen.','Boote ruhen am Strand.','Boote im Hafen','Boote im Kanal','chill','none'),
(1126,'de','Die Arbeit hat ihm Kopfschmerzen gemacht.','Die Musik hat ihm Kopfschmerzen gemacht.','Kopfschmerzen in der Nacht','Kopfschmerzen in der Sonne','chill','blaming_someone'),
(1127,'de','Pure Gesundheit und Freude!','Purer Regen und Dunkelheit!','voller Gesundheit und Freude','ein Gesundheitscheck','dramatic','cliche'),
(1129,'de','Der Arzt hält ein Herz!','Der Arzt hält ein Gehirn!','das Modell eines Herzens','das Modell eines Gehirns','dramatic','exclamation'),
(1131,'de','Beide Fersen heben vom Boden ab.','Beide Fersen stehen auf dem Boden.','beide Fersen anheben','High Heels tragen','chill','none'),
(1133,'de','Die Helferin hat ihre Tasche.','Die Helferin hat ihren Hund.','eine Helferin mit ihrer Tasche','eine Helferin in der Küche','chill','none'),
(1134,'de','Rate mal, wer auf dem Hügel zu Mittag isst? Die Schafe.','Rate mal, wer auf dem Hügel zu Mittag isst? Die Kühe.','ein Baum auf dem Hügel','ein Haus auf dem Hügel','gossip','guessing'),
(1135,'de','Ihre Hand liegt auf ihrer Hüfte.','Ihre Hand liegt auf ihrem Kopf.','eine Hand auf der Hüfte','eine Hand auf seiner Schulter','chill','none'),
(1136,'de','Er ist endlich zuhause!','Er ist endlich bei der Arbeit!','mit einer Tasche zuhause ankommen','mit einer Tasche von zuhause weggehen','dramatic','exclamation'),
(1138,'de','Ruhiger Tag im Krankenhaus.','Ruhiger Tag am Flughafen.','ein heller Krankenhausflur','eine volle Krankenstation','gossip','guessing'),
(1139,'de','Der Gastgeber bringt einen Toast aus.','Der Gastgeber backt einen Kuchen.','ein Gastgeber hebt sein Glas','ein TV-Moderator','business','none'),
(1141,'de','Ein Gast verlässt das Hotel.','Ein Gast betritt das Hotel.','ein Grandhotel verlassen','ein Hotel am Meer','business','none'),
(1143,'de','Hier ist genau ein Mensch.','Hier ist genau ein Kamel.','ein Mensch in der Wüste','eine Menschenmenge','ironic','understatement'),
(1144,'de','Der Jäger kniet.','Der Jäger rennt.','ein Jäger mit Fernglas','ein Jäger mit Gewehr','chill','none'),
(1147,'de','Sein Ellbogen hat eine Infektion.','Sein Knie hat eine Infektion.','eine Infektion am Ellbogen','eine Infektion im Auge','chill','none'),
(1148,'de','Die Injektion ist bereit. Lauf!','Der Verband ist bereit. Lauf!','ein Tablett für eine Injektion','ein Tablett fürs Abendessen','low_iq','exclamation'),
(1149,'de','Schlaflosigkeit: er gegen die Decke.','Schlaflosigkeit: er gegen den Kühlschrank.','Schlaflosigkeit in der Nacht','Schlaflosigkeit vor einer Prüfung','ironic','exaggeration'),
(1151,'de','Sein Bügeleisen dampft.','Sein Wasserkocher dampft.','ein dampfendes Bügeleisen','ein eisernes Tor','business','none'),
(1152,'de','Ein Bügelbrett wird aufgestellt.','Ein Liegestuhl wird aufgestellt.','ein Bügelbrett aufstellen','auf einem Bügelbrett sitzen','chill','none'),
(1154,'de','Der Journalist will Antworten.','Der Arzt will Antworten.','ein Journalist mit Aufnahmegerät','ein Journalist am Schreibtisch','gossip','guessing'),
(1156,'de','Der Papagei regiert diesen Dschungel.','Der Affe regiert diesen Dschungel.','ein Papagei im Dschungel','ein Papagei im Käfig','slang','exaggeration'),
(1158,'de','Wasser aus dem Wasserkocher ist heiß. Wer hätte das gedacht?','Wasser aus dem Hahn ist heiß. Wer hätte das gedacht?','aus dem Wasserkocher gießen','ein Wasserkocher auf dem Herd','low_iq','understatement'),
(1159,'de','Hier ist Ihr Zimmerschlüssel.','Hier ist Ihr Autoschlüssel.','ein Hotelzimmerschlüssel','ein Autoschlüssel','business','none'),
(1160,'de','Die Küche ist top ausgestattet.','Die Küche ist fast leer.','eine helle Küche','eine dunkle Küche','business','none'),
(1163,'de','Die Dame trägt weiße Handschuhe.','Die Dame trägt schwarze Handschuhe.','eine Dame auf der Treppe','eine Dame an der Bar','chill','none'),
(1166,'de','Sie verschiebt eine große Lampe.','Sie verschiebt eine große Pflanze.','eine Lampe für den Tisch','eine Lampe für den Garten','chill','none'),
(1167,'de','Der Anwalt hat viele Bücher.','Der Anwalt hat viele Katzen.','ein Anwalt mit Ordner','ein Anwalt im Gerichtssaal','chill','none'),
(1170,'de','Der Bibliothekar steht auf einer Leiter.','Der Bibliothekar steht auf einem Tisch.','ein Bibliothekar auf der Leiter','ein Bibliothekar am Computer','chill','none'),
(1173,'de','Ein Blitz schlägt ins Meer ein!','Ein Blitz schlägt in einen Baum ein!','Blitze über dem Meer','Blitze über einer Stadt','dramatic','exclamation'),
(1175,'de','Popcorn fliegt durchs ganze Wohnzimmer.','Popcorn fliegt durch die ganze Küche.','Freunde im Wohnzimmer','Freunde im Wartezimmer','slang','exaggeration'),
(1178,'de','Der Verlierer versteckt sich unter einem Handtuch.','Der Verlierer versteckt sich unter einem Tisch.','der Verlierer des Spiels','der Verlierer des Rennens','dramatic','none'),
(1179,'de','Zu viel Gepäck für einen Mann.','Zu viel Gepäck für ein Mädchen.','ein Wagen voller Gepäck','Gepäck auf dem Autodach','low_iq','exaggeration'),
(1180,'de','Der Kofferanhänger ist leer.','Der Kofferanhänger ist rot.','einen Kofferanhänger anbinden','einen Kofferanhänger abschneiden','chill','none'),
(1182,'de','Das Zimmermädchen macht das Bett.','Das Zimmermädchen macht Kaffee.','ein Zimmermädchen macht das Bett','ein Zimmermädchen auf einer Hochzeit','chill','none'),
(1183,'de','Ein männlicher Sportler rudert.','Eine weibliche Sportlerin rudert.','ein männlicher Ruderer','ein männlicher Schwimmer','chill','none'),
(1185,'de','Der Manager verteilt Aufgaben.','Der Manager verteilt Geschenke.','ein Manager mit Laptop','ein Manager mit Handy','business','none'),
(1188,'de','Frisch verheiratet und schon tanzen sie.','Frisch verheiratet und schon streiten sie.','ein verheiratetes Paar tanzt','ein verheiratetes Paar streitet','chill','none'),
(1189,'de','Sie tragen eine Matratze.','Sie tragen ein Klavier.','eine Matratze die Treppe hoch','eine Matratze auf dem Boden','chill','none'),
(1193,'de','Mund auf für die Medizin.','Mund auf für das Eis.','flüssige Medizin auf dem Löffel','Medizin in einer Pillendose','chill','cliche'),
(1195,'de','Eine fliegende mexikanische Tortilla!','Ein fliegender mexikanischer Taco!','ein mexikanischer Straßenstand','ein mexikanisches Restaurant','dramatic','exclamation'),
(1198,'de','Das Model rockt den Laufsteg.','Das Model rockt den Strand.','ein Model auf dem Laufsteg','das Modell eines Flugzeugs','slang','exaggeration'),
(1200,'de','Sie liebt diesen sonnigen Morgen.','Sie liebt diesen regnerischen Morgen.','ein sonniger Morgen','ein regnerischer Morgen','chill','guessing'),
(1202,'de','Mutter und Baby: Nase an Nase.','Mutter und Hund: Nase an Nase.','eine Mutter hebt ihr Baby hoch','eine Mutter füttert ihr Baby','chill','none'),
(1203,'de','Sein Motorrad sprüht Funken!','Sein Roller sprüht Funken!','ein Motorrad in der Kurve','ein Motorrad in der Garage','dramatic','exclamation'),
(1206,'de','Überall fliegt Schlamm!','Überall fliegt Schnee!','ein Schuh in tiefem Schlamm','ein Schuh in frischem Schnee','dramatic','exclamation'),
(1208,'de','Ein Dinosaurier im Museum!','Ein Wal im Museum!','ein Dinosaurier im Museum','ein Museum für moderne Kunst','dramatic','exclamation'),
(1211,'de','Eine ganze Nation singt im Einklang.','Eine ganze Nation tanzt im Einklang.','eine Nation singt gemeinsam','eine Nation von Kaffeeliebhabern','dramatic','cliche'),
(1213,'de','Große Wellen, große Übelkeit.','Kleine Wellen, große Übelkeit.','Übelkeit auf rauer See','Übelkeit nach einem großen Essen','dramatic','none'),
(1214,'de','Sie dehnt ihren Hals.','Sie dehnt ihr Bein.','ein lang gestreckter Hals','ein Schal um den Hals','chill','none'),
(1215,'de','Die Nachbarn plaudern.','Die Nachbarn streiten.','Nachbarn am Gartenzaun','ein lauter Nachbar','chill','none'),
(1216,'de','Fahrrad, Tulpen, Windmühlen. Ja, die Niederlande.','Auto, Tulpen, Windmühlen. Ja, die Niederlande.','Tulpen in den Niederlanden','ein Markt in den Niederlanden','chill','cliche'),
(1218,'de','Niemand ist auf dem Spielplatz. Gruselig!','Kinder sind auf dem Spielplatz. Gruselig!','niemand auf den Schaukeln','niemand am Strand','dramatic','exclamation'),
(1219,'de','Niemand ist gekommen. Tolle Party.','Alle sind gekommen. Tolle Party.','niemand am Tisch','ein voller Esstisch','ironic','understatement'),
(1221,'de','Der Offizier salutiert.','Der Offizier tanzt.','ein salutierender Offizier','ein Offizier am Steuer','chill','none'),
(1225,'de','Der Maler steht voll auf Petrol.','Der Maler steht voll auf Pink.','ein Maler auf der Leiter','ein Maler an der Staffelei','chill','guessing'),
(1227,'de','Elternteil-Modus: Joggen.','Elternteil-Modus: Schlafen.','ein Elternteil neben einem Fahrrad','ein Elternteil repariert ein Fahrrad','slang','cliche'),
(1230,'de','Der Fahrgast schläft tief und fest.','Der Fahrgast ist hellwach.','ein schlafender Fahrgast im Zug','ein Fahrgast im Taxi','chill','none'),
(1232,'de','Der Patient atmet ein.','Der Patient isst zu Mittag.','ein Patient atmet tief ein','ein Patient im Bett','chill','none'),
(1233,'de','Der Fußgänger hat einen Kaffee.','Der Fußgänger hat einen Hund.','ein Fußgänger mit Kaffee','eine Fußgängerbrücke','chill','none'),
(1235,'de','Die Menschen jubeln!','Die Menschen weinen!','jubelnde Menschen in der Nacht','jubelnde Menschen im Stadion','dramatic','exclamation'),
(1237,'de','So eine „belebte“ Kreuzung: eine Person.','So eine „belebte“ Kreuzung: ein Hund.','eine Person auf dem Zebrastreifen','eine Person im Bus','ironic','understatement'),
(1238,'de','Die Apotheke hat jede Menge Gläser.','Die Apotheke hat jede Menge Spielzeug.','eine gemütliche alte Apotheke','eine Apotheke mit rotem Kreuz','chill','none'),
(1241,'de','Der Fotograf liegt auf der nassen Straße!','Der Fotograf steht auf der nassen Straße!','ein Fotograf am Boden','ein Fotograf im Studio','dramatic','exclamation'),
(1242,'de','Sie hängt ein Bild auf.','Sie hängt einen Spiegel auf.','ein Bild an der Wand','ein Bild auf ihrem Handy','chill','none'),
(1248,'de','Der Planet hat Ringe!','Der Planet hat keine Ringe!','ein Planet mit Ringen','ein Planet auf einer Karte','dramatic','exclamation'),
(1254,'de','Der Klempner repariert ein Rohr.','Der Klempner repariert eine Tür.','ein Klempner unter dem Waschbecken','ein Klempner auf dem Dach','chill','none'),
(1255,'de','In Polen ist Winter.','In Polen ist Sommer.','ein verschneiter Platz in Polen','ein Sandstrand in Polen','chill','none'),
(1256,'de','Der Polizist lächelt.','Der Polizist weint.','ein zeigender Polizist','ein rennender Polizist','chill','none'),
(1258,'de','Sie hat polnische Piroggen gemacht.','Sie hat polnische Würste gemacht.','polnische Piroggen in Reihen','polnische Würste auf dem Grill','chill','none'),
(1260,'de','Sie joggt in Portugal.','Sie radelt in Portugal.','Joggen in Portugal','Straßenbahnfahren in Portugal','chill','none'),
(1262,'de','Zimt auf portugiesischen Törtchen!','Schokolade auf portugiesischen Törtchen!','portugiesische Puddingtörtchen','portugiesische Sardinen','dramatic','exclamation'),
(1263,'de','Der Briefträger bringt Briefe.','Der Briefträger bringt Pizzen.','ein Briefträger an der Tür','ein Briefträger im Lieferwagen','business','none'),
(1266,'de','Der Präsident spricht und die Kameras blitzen!','Der Präsident singt und die Kameras blitzen!','ein Präsident hält eine Rede','ein Präsident schüttelt Hände','dramatic','exclamation'),
(1267,'de','Sie sieht sehr professionell aus.','Sie sieht sehr müde aus.','ein professioneller Look','ein professioneller Sportler','flirt','none'),
(1268,'de','Der Professor hält eine Vorlesung.','Der Professor schläft.','ein Professor bei der Vorlesung','das Büro eines Professors','chill','none'),
(1270,'de','Sie stampft in eine Pfütze.','Sie stampft in den Schnee.','in eine Pfütze springen','eine Pfütze verschütteter Milch','chill','none'),
(1274,'de','Ein riesiger Regenbogen über den Hügeln.','Ein riesiger Regenbogen über dem Meer.','ein Regenbogen über grünen Hügeln','ein Regenbogen über einer Stadt','chill','none'),
(1275,'de','Er kratzt an seinem Ausschlag.','Er kratzt sich am Kopf.','einen roten Ausschlag kratzen','ein Ausschlag im Gesicht','chill','none'),
(1278,'de','Die Rezeption hat eine Messingglocke.','Die Rezeption hat eine Messinglampe.','ein Schlüssel an der Rezeption','ein Hochzeitsempfang','business','none'),
(1286,'de','Ein Arbeiter räumt das Dach frei.','Ein Arbeiter streicht das Dach.','ein Hausdach mit Ziegeln','ein gläsernes Bahnhofsdach','business','none'),
(1287,'de','Leeres Zimmer? Zeit zu tanzen!','Leerer Laden? Zeit zu tanzen!','ein leeres, sonniges Zimmer','ein leerer, sonniger Strand','slang','exclamation'),
(1290,'de','Diese Route hat so viele Kurven!','Diese Route hat so viele Lkw!','eine Route den Berg hinauf','eine Route entlang der Küste','dramatic','exclamation'),
(1299,'de','Er liebt seinen Scan. Angeblich.','Er hasst seinen Scan. Angeblich.','ein Patient beim Scan','ein Scan am Flughafen','ironic','guessing'),
(1303,'de','Was für eine stylische Fahrt mit dem Motorroller!','Was für eine stylische Fahrt mit dem Fahrrad!','ein Motorroller in Italien','ein Motorroller am Strand','flirt','exaggeration'),
(1304,'de','Der Sekretär ist total beschäftigt!','Der Sekretär ist total gelangweilt!','ein beschäftigter Sekretär','ein Sekretär im Urlaub','dramatic','exclamation'),
(1305,'de','Ein Bohnensamen fällt.','Ein kleiner Stein fällt.','einen Bohnensamen pflanzen','ein Vogel frisst Samen','chill','none'),
(1306,'de','Der Verkäufer ist super glücklich.','Der Verkäufer ist super wütend.','ein Gemüseverkäufer','ein Buchverkäufer','chill','none'),
(1307,'de','Der Diener hat ein Silbertablett.','Der Diener hat eine Silberglocke.','ein Diener mit Tablett','ein Diener in der Küche','chill','none'),
(1308,'de','Sogar ihr Schatten tanzt!','Sogar ihre Freundin tanzt!','ein riesiger Schatten an der Wand','ein Schatten unter einem Baum','dramatic','exclamation'),
(1311,'de','Sie winkt einem riesigen Schiff!','Sie winkt einem winzigen Schiff!','einem großen Schiff zuwinken','von einem großen Schiff winken','dramatic','exclamation'),
(1312,'de','Die Verkäuferin hat einen Mantel.','Die Verkäuferin hat einen Hut.','eine Verkäuferin bei der Arbeit','eine Verkäuferin in der Pause','business','none'),
(1314,'de','Ihre Schulter muss untersucht werden.','Ihr Knie muss untersucht werden.','eine Schulter untersuchen','eine Tasche auf ihrer Schulter','business','none'),
(1315,'de','Regendusche? Eher ein Wasserfall!','Gartendusche? Eher ein Wasserfall!','eine große Regendusche','ein Duschvorhang','dramatic','exaggeration'),
(1316,'de','Die Geschwister lachen.','Die Geschwister streiten.','Geschwister lachen zusammen','Geschwister streiten um ein Spielzeug','chill','none'),
(1317,'de','Er steht auf einem steinernen Bürgersteig.','Er steht auf einem hölzernen Bürgersteig.','ein breiter Bürgersteig aus Stein','ein Bürgersteig voller Menschen','business','none'),
(1319,'de','Sie ist Single und glücklich.','Sie ist Single und traurig.','glücklich als Single','eine einzelne Tasse Tee','chill','none'),
(1321,'de','Ihr Gericht, mein Herr.','Ihre Rechnung, mein Herr.','Ihr Gericht, mein Herr','Ihre Rechnung, mein Herr','business','none'),
(1323,'de','Was für ein hoher Wolkenkratzer!','Was für ein hoher Leuchtturm!','zu einem Wolkenkratzer hochschauen','von einem Wolkenkratzer runterschauen','dramatic','exclamation'),
(1325,'de','Sie schläft. Das Kissen ist ihr Freund.','Sie schläft. Die Katze ist ihr Freund.','auf einem Bett schlafen','im Zug schlafen','low_iq','guessing'),
(1326,'de','Flauschige Hausschuhe, fauler Morgen.','Flauschige Socken, fauler Morgen.','flauschige Hausschuhe anziehen','flauschige Hausschuhe im Laden','chill','none'),
(1327,'de','Er trägt slowakische Tracht.','Sie trägt slowakische Tracht.','slowakische Tracht','ein slowakisches Fußballtrikot','chill','none'),
(1328,'de','Sie tanzt in der Slowakei!','Sie schwimmt in der Slowakei!','eine Wiese in der Slowakei','ein Strand in der Slowakei','dramatic','exclamation'),
(1337,'de','Sie spielen auf dem Sofa.','Sie spielen auf dem Boden.','Freunde auf einem grauen Sofa','Freunde in einem grauen Bus','chill','none'),
(1340,'de','Jemand haut heimlich ab.','Jemand tanzt heimlich.','jemand geht weg','jemand führt einen Hund aus','gossip','guessing'),
(1342,'de','Sein Sohn ist wieder zu Hause!','Seine Tochter ist wieder zu Hause!','seinen erwachsenen Sohn umarmen','seinem Sohn zum Abschied winken','dramatic','exclamation'),
(1344,'de','Die Spinne ist bei der Arbeit.','Die Ameise ist bei der Arbeit.','eine Spinne in ihrem Netz','eine Spinne in der Badewanne','business','none'),
(1346,'de','Der Boxer spuckt Wasser.','Der Boxer trinkt Wasser.','Wasser in einen Eimer spucken','Kaugummi ausspucken','chill','none'),
(1347,'de','Eine Hand drückt einen Schwamm aus.','Eine Hand drückt eine Zitrone aus.','ein ausgedrückter Seifenschwamm','ein Naturschwamm im Meer','chill','none'),
(1350,'de','Sie überquert den Platz. Tschüss, Tauben!','Sie überquert den Fluss. Tschüss, Tauben!','über einen Platz rennen','auf einem ruhigen Platz sitzen','slang','none'),
(1353,'de','Ein heller Stern. Wünsch dir was!','Ein heller Mond. Wünsch dir was!','auf einen hellen Stern zeigen','ein Stern auf dem Baum','slang','exclamation'),
(1354,'de','Schon wieder zu spät am Bahnhof!','Schon wieder zu spät am Flughafen!','durch einen Bahnhof hetzen','am Bahnhof schlafen','dramatic','guessing'),
(1355,'de','Hände am Lenkrad.','Hände am Handy.','Hände am Lenkrad','das Steuerrad eines Boots','chill','none'),
(1358,'de','Ihre Stiefmutter flicht ihr die Haare.','Ihre Stiefmutter schneidet ihr die Haare.','eine Stiefmutter flicht Haare','eine Stiefmutter in der Schule','chill','none'),
(1359,'de','Die Stiefschwestern können nicht aufhören zu lachen.','Die Stiefschwestern können nicht aufhören zu weinen.','Stiefschwestern lachen zusammen','Stiefschwestern teilen sich ein Bett','gossip','exaggeration'),
(1360,'de','Sie benutzt ein Stethoskop. Psst!','Sie benutzt ein Thermometer. Psst!','mit dem Stethoskop abhören','ein Stethoskop auf dem Tisch','dramatic','exclamation'),
(1362,'de','Der Schnitt bekommt ein paar Stiche.','Der Schnitt bekommt ein Pflaster.','Stiche im Unterarm','Stiche in einem Hemd','chill','none'),
(1363,'de','Dieser Stein schwimmt, oder?','Dieses Blatt schwimmt, oder?','ein Stein über einem See','ein Stein in einer Mauer','low_iq','guessing'),
(1365,'de','Ein Fremder hält sie an.','Ein Polizist hält sie an.','ein Fremder mit Kapuze','ein Fremder mit Hund','dramatic','none'),
(1366,'de','Ein Blatt surft den Bach runter.','Ein Frosch surft den Bach runter.','ein klarer Waldbach','ein Bach voller Fische','low_iq','exaggeration'),
(1367,'de','Sie überquert eine belebte Straße.','Sie überquert eine belebte Brücke.','eine belebte Großstadtstraße','eine ruhige Dorfstraße','business','none'),
(1369,'de','Regen? Er tanzt mit einer Straßenlaterne!','Regen? Er tanzt mit einer Ampel!','eine Reihe leuchtender Straßenlaternen','eine Reihe brennender Kerzen','dramatic','exclamation'),
(1371,'de','Die U-Bahn ist mega schnell.','Die U-Bahn ist mega langsam.','eine U-Bahn rauscht vorbei','ein U-Bahn-Plan','slang','exaggeration'),
(1372,'de','Ihr Koffer ist grau und praktisch.','Ihr Koffer ist rot und praktisch.','einen grauen Koffer ziehen','einen grauen Koffer packen','business','none'),
(1375,'de','Schweiß fliegt von ihrem Handschuh!','Schweiß fliegt von ihrem Schuh!','Schweiß auf ihrem Arm','Schweiß auf einem Shirt','dramatic','exclamation'),
(1378,'de','Sie isst ein Schweizer Fondue.','Sie isst Schweizer Schokolade.','ein Schweizer Käsefondue','ein Schweizer Schokoladenfondue','chill','none'),
(1379,'de','Jemand hat den Lichtschalter gefunden. Wow.','Jemand hat das Handy gefunden. Wow.','ein Lichtschalter','eine Eisenbahnweiche','low_iq','exaggeration'),
(1380,'de','Schweiz: Sogar die Kühe kriegen Musik.','Schweiz: Sogar die Ziegen kriegen Musik.','ein Alphorn in der Schweiz','ein Kuhglockenladen in der Schweiz','chill','exaggeration'),
(1381,'de','Die Spritze spritzt!','Die Flasche spritzt!','Flüssigkeit aus einer Spritze','eine Spritze aufziehen','dramatic','exclamation'),
(1383,'de','Der Schneider flickt eine Jacke.','Der Schneider flickt einen Schuh.','ein Schneider mit Maßband','ein Schneider verkauft Schuhe','chill','none'),
(1385,'de','Wasser aus dem Wasserhahn! Wow!','Wasser aus dem Schlauch! Wow!','den Wasserhahn aufdrehen','einen Zapfhahn aufdrehen','low_iq','exclamation'),
(1386,'de','Der Taxifahrer winkt!','Der Taxifahrer pennt!','ein winkender Taxifahrer','ein Taxifahrer bei Nacht','slang','exclamation'),
(1389,'de','Ihre Tränen fließen.','Seine Tränen fließen.','eine Träne auf ihrer Wange','ein Riss in ihrem Kleid','dramatic','none'),
(1390,'de','Er will den Mond berühren.','Er will die Sonne berühren.','nach dem Mond greifen','ein Mond über dem Meer','dramatic','guessing'),
(1394,'de','Eine große orange Sonne über dem Meer.','Eine große orange Sonne über dem Schnee.','die Sonne über dem Meer','die Sonne über den Bergen','chill','none'),
(1396,'de','Das ganze Theater gehört ihr!','Das ganze Theater gehört ihm!','ein leeres altes Theater','ein Theater voller Menschen','dramatic','exaggeration'),
(1398,'de','Ihr Thermometer ist riesig!','Ihre Zahnbürste ist riesig!','ein großes Glasthermometer','ein Thermometer an der Wand','dramatic','exclamation'),
(1400,'de','Ihr Hals wird untersucht.','Ihr Ohr wird untersucht.','ein Licht im Hals','sich räuspern','business','none'),
(1403,'de','Diese Zehen lieben den Strand!','Diese Zehen lieben den Schnee!','Zehen im nassen Sand','Zehen im weichen Gras','dramatic','exaggeration'),
(1404,'de','Ihre Zunge fängt Schnee zum Mittagessen.','Ihre Hand fängt Schnee zum Mittagessen.','die Zunge rausstrecken','sich auf die Zunge beißen','low_iq','guessing'),
(1405,'de','Jeder einzelne Zahn wird kontrolliert.','Jeder einzelne Nagel wird kontrolliert.','einen Zahn untersuchen','eine Zahnfee','business','none'),
(1406,'de','Schau dir meine Zahnbürste an!','Schau dir meine Haarbürste an!','eine Zahnbürste mit Schaum','eine Zahnbürste im Becher','dramatic','exclamation'),
(1410,'de','Sie steht an einer Ampel.','Sie steht an einer Bushaltestelle.','an der Ampel warten','am Bahnhof warten','chill','none'),
(1411,'de','Alte Straßenbahn, breites Lächeln, super Style.','Alter Bus, breites Lächeln, super Style.','eine alte grüne Straßenbahn','ein alter grüner Bus','flirt','none'),
(1414,'de','Wow, die Eiche ist riesig!','Wow, die Palme ist riesig!','eine riesige Eiche','ein riesiger Picknickkorb','low_iq','exclamation'),
(1415,'de','Er steigt in seinen Lastwagen.','Er steigt in sein Auto.','ein großer silberner Lastwagen','ein großer silberner Bus','chill','none'),
(1416,'de','Er fährt aus einem Tunnel.','Er fährt aus einer Garage.','aus einem Straßentunnel heraus','in einen Zugtunnel hinein','chill','none'),
(1419,'de','Zwillinge, gleiches Kleid. Geplant?','Zwillinge, gleicher Hut. Geplant?','Zwillinge in gleichen Kleidern','Zwillinge im Kinderwagen','gossip','guessing'),
(1420,'de','Bester Onkel ever!','Beste Tante ever!','auf den Schultern seines Onkels','auf dem Fahrrad seines Onkels','slang','exaggeration'),
(1422,'de','Eine Hand zeigt auf den Bildschirm.','Eine Hand zeigt auf das Fenster.','auf einen Bildschirm zeigen','auf die Tür zeigen','chill','none'),
(1423,'de','Jemand zeigt auf ein Balkendiagramm.','Jemand zeigt auf ein Tortendiagramm.','Balken- und Liniendiagramme','ein Diagramm auf Papier','business','none'),
(1424,'de','Der stehende Kollege trägt Blau.','Der stehende Kollege trägt Rot.','Kollege im blauen Hemd','Kollege im roten Hemd','chill','none'),
(1425,'de','Rate mal, wer an der Leine ist.','Rate mal, wer auf dem Sofa ist.','ein Hund an der Leine','ein Hund ohne Leine','gossip','none'),
(1427,'de','Er balanciert auf einem Seil!','Er balanciert auf einem Baumstamm!','auf einem dünnen Seil balancieren','auf einem dünnen Ast balancieren','dramatic','exclamation'),
(1429,'de','Er singt für seine Freunde.','Er tanzt für seine Freunde.','ins Mikrofon singen','unter der Dusche singen','chill','none'),
(1432,'de','Er singt in einem Kostüm. Der gläserne Schuh liegt bereit.','Er tanzt in einem Kostüm. Der gläserne Schuh liegt bereit.','im Kostüm singen','ein Kostüm kaufen','gossip','guessing'),
(1433,'de','Ganz normaler Abend: Zu Hause wird getanzt.','Ganz normaler Abend: Zu Hause wird gegessen.','in Kostümen tanzen','auf einer Bühne tanzen','chill','understatement'),
(1434,'de','Niemand sieht den Dieb am Kronleuchter.','Niemand sieht den Dieb auf dem Dach.','ein Dieb mit Tasche','ein Dieb mit Pistole','ironic','guessing'),
(1435,'de','Er gibt das Mikrofon nicht mehr her.','Er gibt die Gitarre nicht mehr her.','ein Mikrofon auf einem Ständer','ein Mikrofon im Handy','ironic','guessing'),
(1436,'de','Die Menschen sind altersmäßig vielfältig.','Die Menschen sind alle Teenager.','fünf vielfältige Porträts','fünf vielfältige Landschaften','chill','none'),
(1438,'de','Er nimmt einen Podcast auf.','Sie nimmt einen Podcast auf.','einen Podcast aufnehmen','einen Podcast hören','chill','none'),
(1441,'de','Ihr Sieg war die Mühe wert.','Ihr Sieg war das Geld wert.','die Mühe wert','Mühe, wach zu bleiben','chill','none'),
(1442,'de','Dieses Büro ist voller Pflanzen.','Dieses Büro ist voller Hunde.','ein helles Großraumbüro','ein dunkles leeres Büro','business','none'),
(1446,'de','Die Konferenz ist rappelvoll!','Die Konferenz ist leer!','ein voller Konferenzsaal','eine Videokonferenz','dramatic','exclamation'),
(1447,'de','Der Impfstoff piekst ein bisschen.','Der Impfstoff kitzelt ein bisschen.','Impfstoff in den Arm','Impfstoff ins Bein','chill','understatement'),
(1450,'de','Blumen von einem Besucher. Süß.','Süßigkeiten von einem Besucher. Süß.','ein Besucher mit Blumen','ein Besucher im Museum','flirt','none'),
(1451,'de','Dieses Vitamin bringt sie zum Lachen.','Dieses Vitamin bringt sie zum Weinen.','ein orangefarbenes Gummi-Vitamin','ein grünes Gummi-Vitamin','gossip','guessing'),
(1452,'de','Der Vulkan ist ein bisschen sauer.','Der Vulkan ist ein bisschen müde.','ein Vulkan bricht nachts aus','ein schneebedeckter Vulkan','ironic','understatement'),
(1453,'de','Das Schiff ist auf einer langen Seereise.','Das Schiff ist auf einer Flussreise.','eine Seereise über den Ozean','eine Reise den Fluss entlang','chill','none'),
(1454,'de','Sie misst ihre Taille.','Sie misst ihren Arm.','ein Maßband um die Taille','ein Gürtel um die Taille','business','none'),
(1457,'de','Die Kellnerin serviert einen Milchshake.','Die Kellnerin serviert eine Pizza.','eine Kellnerin serviert Frühstück','eine Kellnerin frühstückt','business','none'),
(1458,'de','Der Spaziergänger hat einen goldfarbenen Hund.','Der Spaziergänger hat einen schwarzen Hund.','ein Spaziergänger mit Wanderstöcken','ein Spaziergänger mit Kinderwagen','chill','none'),
(1459,'de','Er streicht die Wand weiß.','Er streicht die Wand blau.','eine große kahle Wand','eine Mauer um einen Garten','chill','none'),
(1466,'de','Regen oder Sonne? Das Wetter kann sich nicht entscheiden.','Schnee oder Sonne? Das Wetter kann sich nicht entscheiden.','wechselhaftes Wetter auf einem Hügel','sonniges Wetter am Strand','ironic','guessing'),
(1467,'de','Ein Mechaniker rollt ein Rad.','Ein Mechaniker wäscht ein Rad.','ein Autorad rollen','ein Rad an einem Fahrrad','business','none'),
(1468,'de','Vollgas im Rennrollstuhl!','Vollgas im Renn-Gokart!','ein Rennrollstuhl','eine Rollstuhlrampe','dramatic','exclamation'),
(1473,'de','Der Arbeiter hält einen Balken.','Der Arbeiter hält ein Rohr.','ein Arbeiter mit Schutzbrille','ein Arbeiter im Anzug','chill','none'),
(1476,'de','Der Schriftsteller tippt nachts, natürlich.','Der Schriftsteller tippt mittags, natürlich.','ein Schriftsteller an der Schreibmaschine','ein Schriftsteller am Laptop','ironic','cliche'),
(1477,'de','Das Röntgenbild zeigt Handknochen.','Das Röntgenbild zeigt Fußknochen.','ein Röntgenbild einer Hand','ein Röntgenbild eines Fußes','nerd','none'),
(1479,'de','Mittagsservice im Zoo.','Mittagsservice auf dem Bauernhof.','eine Giraffe im Zoo','ein Löwe im Zoo','business','none'),
(1481,'de','Die Burg hat zwei Torbögen.','Die Burg hat vier Torbögen.','ein Torbogen unter der Treppe','ein Torbogen über dem Fluss','chill','none'),
(1482,'de','Tolle goldene Ohrringe!','Tolle silberne Ohrringe!','große goldene Ohrringe','Ohrringe in einer Geschenkbox','flirt','exclamation'),
(1483,'de','Die Erdbeeren sind rot.','Die Erdbeeren sind grün.','eine Erdbeerpflanze','ein Erdbeer-Milchshake','chill','none'),
(1484,'de','Diese Musik hat keinen Play-Button.','Dieses Gedicht hat keinen Play-Button.','alte Musiknoten','eine alte Spieluhr','ironic','exaggeration'),
(1485,'de','Sie wollen das Haus verkaufen.','Sie wollen das Auto verkaufen.','ein weißes Haus verkaufen','ein rotes Auto verkaufen','chill','none'),
(1487,'de','Der Gott hat einen goldenen Thron.','Der Gott hat einen silbernen Thron.','ein Gott auf einem Thron','ein König auf einem Pferd','chill','none'),
(1488,'de','Pferde ziehen eine Kutsche.','Ochsen ziehen eine Kutsche.','eine goldene Königskutsche','ein goldener Zugwaggon','chill','none'),
(1489,'de','Der beste Kumpel der Fee: ein Frosch.','Der beste Kumpel der Fee: eine Katze.','eine Fee auf dem Moos','eine Fee am Himmel','gossip','guessing'),
(1491,'de','So viele Schmetterlinge!','So viele Vögel!','Schmetterlinge über den Blumen','Schmetterlinge auf einem Shirt','dramatic','exaggeration'),
(1495,'de','Fakt: Ein Einhorn hat ein Horn.','Fakt: Ein Einhorn hat zwei Hörner.','ein sich aufbäumendes Einhorn','ein schlafendes Einhorn','nerd','cliche'),
(1497,'de','Die Geige liegt auf alten Noten.','Die Gitarre liegt auf alten Noten.','eine Geige mit Rosen','eine Geigenstunde','chill','none'),
(1498,'de','Zwei Typen im Heißluftballon. Ciao!','Zwei Typen auf einem Pferd. Ciao!','ein Heißluftballon mit zwei Männern','ein Heißluftballon mit zwei Hunden','slang','none'),
(1499,'de','Die Stängel sind lang und geschwungen.','Die Stängel sind kurz und dick.','lange, geschwungene Stängel','Stängel in einer Vase','nerd','none'),
(1501,'de','Sie gießt grüne Flüssigkeit.','Sie gießt rote Flüssigkeit.','aus einer weiten Schale gießen','Tee in eine Tasse gießen','chill','none'),
(1502,'de','Sonnenuntergang zu zweit. So süß.','Frühstück zu zweit. So süß.','gemeinsam den Sonnenuntergang ansehen','ein Sonnenuntergang in den Bergen','gossip','none'),
(1504,'de','Der Philosoph hat einen Bart.','Der Philosoph hat einen Hut.','ein bärtiger Philosoph','ein lachender Philosoph','chill','none'),
(1505,'de','Supermarkt-Trip im 50er-Jahre-Style.','Bäckerei-Trip im 50er-Jahre-Style.','eine Supermarktkasse','ein Supermarktparkplatz','slang','cliche'),
(1508,'de','Die Kirche hat einen hohen Turm.','Die Kirche hat einen winzigen Turm.','eine alte Steinkirche','eine alte Steinbrücke','business','none'),
(1510,'de','Warum schreit die Figur?','Warum singt die Figur?','auf einer Brücke schreien','in der Achterbahn schreien','low_iq','guessing'),
(1513,'de','Die Hände sind zum Beten aneinandergelegt.','Die Hände sind zum Klatschen aneinandergelegt.','Hände zum Beten gefaltet','mit offenen Händen beten','chill','none'),
(1514,'de','Religion in einem alten Gemälde.','Religion in einem modernen Comic.','ein Gemälde über Religion','ein Buch über Religion','nerd','none'),
(1519,'de','Ihre Blumen sind so hübsch.','Ihre Federn sind so hübsch.','hübsche Blumen im Haar','hübsche Schleifen im Haar','flirt','none'),
(1520,'de','Lockiges Haar und Perlen? Stilvoll.','Kurzes Haar und Perlen? Stilvoll.','langes, lockiges blondes Haar','ein Hund mit lockigem Fell','flirt','none'),
(1522,'de','Sie hat einen Korb Kirschen.','Sie hat einen Korb Äpfel.','ein Korb voller Kirschen','ein Hund im Korb','chill','none'),
(1523,'de','Blondes Haar voller Blumen.','Schwarzes Haar voller Blumen.','langes, welliges blondes Haar','kurzes blondes Haar','chill','none'),
(1524,'de','Er trampt – und ein UFO hält an.','Er trampt – und ein Bus hält an.','Trampen auf einer Bergstraße','Trampen auf der Autobahn','gossip','guessing'),
(1525,'de','Der Zug kommt direkt auf uns zu!','Der Lkw kommt direkt auf uns zu!','ein schwarzer Dampfzug','für ein Rennen trainieren','dramatic','exclamation'),
(1526,'de','Der Krieger hat einen Helm.','Der Krieger hat einen Schild.','ein Samurai-Krieger','ein Krieger zu Pferd','chill','none'),
(1527,'de','Die Kathedrale hat eine riesige Kuppel.','Die Kathedrale hat ein flaches Dach.','eine barocke Kathedralenkuppel','ein Kathedralenchor singt','chill','none'),
(1528,'de','Ballons über Japan!','Vögel über Japan!','Symbole Japans','eine Karte von Japan','dramatic','exclamation'),
(1529,'de','Zwei Türme, ein Vulkan.','Zwei Türme, zwei Vulkane.','zwei runde Burgtürme','zwei hohe Wassertürme','chill','none'),
(1530,'de','Die Kleinstadt liegt auf einem Hügel. Tolle Aussicht, sagt man.','Die Kleinstadt liegt am Meer. Tolle Aussicht, sagt man.','eine alte Kleinstadt auf dem Hügel','eine neue Kleinstadt am Meer','gossip','none'),
(1531,'de','Ein Bogen rahmt die Kirche ein.','Ein Baum rahmt die Kirche ein.','ein großer Spitzbogen','ein großer spitzer Turm','chill','none'),
(1534,'de','Wow, jedes Pferd hat ein Horn!','Wow, jedes Pferd hat zwei Hörner!','das lange Horn eines Einhorns','die laute Hupe eines Autos','low_iq','exclamation'),
(1537,'de','Ägyptens Pharao hat einen Bogen.','Ägyptens Pharao hat ein Schwert.','ein Pharao aus Ägypten','eine Pyramide in Ägypten','chill','none'),
(1538,'de','Sie steht zwischen zwei Säulen.','Sie steht zwischen zwei Bäumen.','zwei verzierte Säulen','eine Zeitungskolumne','chill','none'),
(1541,'de','Winzige Kapelle, Schnee-Vibes.','Winzige Kapelle, Sonnen-Vibes.','eine verschneite weiße Kapelle','eine Kapelle voller Gäste','slang','none'),
(1543,'de','Sie hält einen großen Kohlkopf.','Sie hält einen großen Kürbis.','ein Garten voller Kohl','ein Kohl im Topf','chill','none'),
(1544,'de','Sie hängt die Wäsche auf.','Sie hängt die Fahnen auf.','weiße Wäsche aufhängen','weiße Wäsche falten','chill','none'),
(1545,'de','Der Kragen der Königin ist riesig!','Der Hund der Königin ist riesig!','eine Königin mit Zepter','eine Königin mit Schwert','gossip','none'),
(1547,'de','Der heilige Mann denkt angestrengt nach.','Der heilige Mann lacht sich schlapp.','ein heiliger Mann denkt nach','ein heiliger Mann betet','chill','none'),
(1548,'de','In jedem Fenster sind Menschen.','In jedem Fenster sind Katzen.','eine Familie in jedem Fenster','eine Katze in jedem Fenster','chill','none'),
(1549,'de','Jemand hat die ganze Farbe verschüttet!','Jemand hat die ganze Milch verschüttet!','Farbtropfen','eine Dose Farbe','dramatic','blaming_someone'),
(1551,'de','Der Himmel hat uns eine Gitarre geschickt!','Der Himmel hat uns eine Geige geschickt!','eine Gitarre hochhalten','eine Gitarre stimmen','dramatic','exclamation'),
(1554,'de','Der Mönch hat einen roten Regenschirm.','Der Mönch hat einen schwarzen Regenschirm.','ein Mönch in Rosa','ein Mönch in Schwarz','chill','none'),
(1555,'de','Die Figur hält ein großes Schwert.','Die Figur hält einen großen Speer.','ein Schwert aufrecht halten','ein Schwert an der Wand','chill','none'),
(1559,'de','Sonnenblumen füllen eine gelbe Vase.','Rosen füllen eine gelbe Vase.','Sonnenblumen in einer Vase','Sonnenblumen auf einem Feld','chill','none'),
(1560,'de','Sie steht an einer Schaukel.','Sie steht an einem Tor.','eine Seilschaukel','ein Swing-Tanz','chill','none'),
(1562,'de','Der Cowboy reitet in den Sonnenuntergang.','Der Cowboy reitet ins Meer.','ein Cowboy auf einem Pferd','ein Cowboy auf einem Bullen','dramatic','cliche'),
(1565,'de','Sie besteht aus rostigen Zahnrädern.','Sie besteht aus rostigen Ketten.','rostige Zahnräder aus Metall','rostige Metallketten','chill','none'),
(1567,'de','Das Flugzeug steigt auf!','Das Flugzeug sinkt!','ein Flugzeug im Steigflug','ein Flugzeug im Sinkflug','dramatic','exclamation'),
(1568,'de','Es segelt im Mondschein.','Es segelt im Sonnenschein.','nachts segeln','in der Sonne segeln','chill','none'),
(1569,'de','Das ist ein Porträt in Kreuzschraffur.','Das ist ein Porträt in Aquarell.','ein Porträt in Feder und Tusche','ein Porträt in Öl','nerd','none'),
(1574,'de','Eine Laterne hängt an einem Ast.','Eine Laterne hängt an einem Dach.','eine Laterne an einer Kette','eine Laterne in ihrer Hand','chill','none'),
(1575,'de','Das Paar umarmt sich.','Das Paar streitet sich.','ein Paar unter dem Mond','ein Paar am Strand','chill','none'),
(1576,'de','In ihrem Traum schaukelt sie am Mond.','In ihrem Traum schaukelt sie an einem Baum.','ein Traum vom Mond','ein Traum vom Meer','chill','guessing'),
(1579,'de','Die Smartphones haben ein Haus gebaut.','Die Bücher haben ein Haus gebaut.','ein Haus aus Smartphones','ein Smartphone in der Tasche','chill','exaggeration'),
(1581,'de','Vanlife, Baby!','Zeltlife, Baby!','ein Van mit Surfbrett','ein Van mit Fahrrad','slang','exclamation'),
(1583,'de','Der Astronaut fliegt davon!','Der Pilot fliegt davon!','ein Astronaut im All','ein Astronaut auf dem Mond','dramatic','exclamation'),
(1584,'de','Ihr Rock tanzt auch mit.','Ihr Hund tanzt auch mit.','im roten Rock tanzen','im Regen tanzen','chill','exaggeration'),
(1585,'de','Da sind fünf weiße Rosen.','Da sind fünf rote Rosen.','fünf weiße Rosenblüten','weiße Rosen in einer Vase','chill','none'),
(1586,'de','Verschmutzung, wohin man schaut.','Blumen, wohin man schaut.','Verschmutzung durch eine Fabrik','Verschmutzung durch ein Schiff','dramatic','exaggeration'),
(1589,'de','Diese Person sieht traurig aus.','Diese Person sieht glücklich aus.','eine traurige Figur mit orangem Haar','eine traurige Figur mit blauem Haar','chill','none'),
(1590,'de','Die Kapuze ist voller Sterne.','Die Kapuze ist voller Blumen.','eine Kapuze voller Sterne','eine Kapuze über den Augen','chill','none'),
(1591,'de','Dieser Leuchtturm hat Streifen.','Dieser Leuchtturm hat Punkte.','ein gestreifter Leuchtturm','eine gestreifte Strandhütte','chill','none'),
(1592,'de','Der Roboter hat blaue Lippen. Friert er?','Der Roboter hat rote Lippen. Friert er?','ein Roboterkopf aus Metall','ein Staubsaugerroboter','low_iq','guessing'),
(1593,'de','Ich liebe diesen blauen Haarschnitt!','Ich liebe diesen blauen Hut!','ein petrolfarbener Bob-Haarschnitt','ein Haarschnitt im Salon','flirt','exclamation'),
(1595,'de','Zwei Pyramiden. Sehr spitz.','Zwei Türme. Sehr spitz.','zwei braune Pyramiden','eine Pyramide aus Orangen','low_iq','none'),
(1596,'de','Der Mond scheint über Russland.','Die Sonne scheint über Russland.','eine Kirche in Russland','ein Palast in Russland','chill','none'),
(1597,'de','Ups, sein Gesicht ist unter Wasser!','Ups, sein Gesicht ist im Sand!','ein Hund unter Wasser','ein Hund über dem Wasser','dramatic','exclamation'),
(1598,'de','Jesus hebt eine Hand.','Jesus hebt beide Hände.','Jesus spendet den Segen','Jesus trägt das Kreuz','chill','none'),
(1600,'de','Ein kleines Boot ist auf dem Kanal.','Ein großes Schiff ist auf dem Kanal.','ein Boot auf dem Kanal','ein Boot auf dem See','chill','none'),
(1603,'de','Sie bohren draußen auf dem Meer nach Erdöl.','Sie bohren auf einem Hügel nach Erdöl.','eine Erdölplattform auf See','Öl in einer Bratpfanne','business','none'),
(1609,'de','Sie tanzt Ballett auf einem Felsen!','Sie tanzt Ballett auf einem Boot!','Ballett auf einem Felsen','Ballett im Studio','dramatic','exclamation'),
(1610,'de','Der Mond beleuchtet den Balkon.','Eine Lampe beleuchtet den Balkon.','ein mondbeschienener Balkon','ein sonniger Balkon','dramatic','none'),
(1611,'de','Eine Taube fliegt im Licht.','Eine Krähe fliegt im Licht.','eine Taube mit ausgebreiteten Flügeln','eine Taube im Käfig','chill','none'),
(1612,'de','Kinder aus Korea winken.','Kinder aus Korea tanzen.','winkende Kinder aus Korea','singende Kinder aus Korea','chill','none'),
(1613,'de','Drei Raketen heben ab!','Zwei Raketen heben ab!','Raketen steigen im Abendrot auf','eine Rakete landet im Abendrot','dramatic','exclamation'),
(1614,'de','In Spanien rennen Stiere!','In Spanien rennen Pferde!','rennende Stiere in Spanien','Pferderennen in Spanien','dramatic','exclamation'),
(1617,'de','Der Engel führt ein Kind.','Der Engel führt ein Lamm.','ein Engel führt ein Kind','ein Engel spielt Harfe','chill','none'),
(1618,'de','Engel fliegen um ihn herum.','Vögel fliegen um ihn herum.','geflügelte Engel in den Wolken','Engel am Weihnachtsbaum','chill','none'),
(1619,'de','Das große Schiff hat volle Segel.','Das große Schiff hat keine Segel.','volle Segel im Wind','zerrissene Segel im Wind','chill','none'),
(1620,'de','Im Himmel herrscht heute ja Hochbetrieb.','Im Himmel herrscht heute ja tote Hose.','Putten fliegen im Himmel','ein Himmel voller Heiliger','ironic','exaggeration'),
(1623,'de','So viele Wolkenkratzer!','So viele Brücken!','Wolkenkratzer in der Dämmerung','ein Wolkenkratzer im Bau','dramatic','exclamation'),
(1625,'de','Der Surfer hält ein Surfbrett.','Der Surfer hält eine Gitarre.','ein Surfbrett aufrecht halten','auf einem Surfbrett Wellen reiten','chill','none'),
(1629,'de','Nur eine Ananas. So einsam.','Nur eine Banane. So einsam.','eine einzelne aufrechte Ananas','eine Ananas in Scheiben','dramatic','exaggeration'),
(1630,'de','Der Krake hat acht Arme. Ich hab gezählt.','Der Krake hat sechs Arme. Ich hab gezählt.','ein Krake mit acht Armen','ein Krake im Glas','low_iq','none'),
(1631,'de','Die Hexe hat einen Besen. Schlau.','Die Hexe hat eine Katze. Schlau.','eine Hexe mit ihrem Besen','eine Hexe auf ihrem Besen','low_iq','none'),
(1633,'de','Diese Statue beobachtet dich.','Dieser Hund beobachtet dich.','eine Wasserspeier-Statue','eine Pferdestatue','gossip','guessing'),
(1635,'de','Meerjungfrauenschwanz? Voll grün.','Meerjungfrauenschwanz? Voll blau.','eine lächelnde Comic-Meerjungfrau','eine Meerjungfrau auf einem Felsen','slang','none'),
(1638,'de','Vorhänge rahmen ein Meer im Mondlicht ein.','Vorhänge rahmen ein sonniges Meer ein.','schwere lila Vorhänge','schwere lila Teppiche','dramatic','none'),
(1639,'de','Fakt: Das Baby liegt in einem Stall.','Fakt: Das Baby liegt in einem Schloss.','ein Baby im Stall','ein Pferd im Stall','nerd','none'),
(1641,'de','Ein gruseliger Clown und eine Krähe.','Ein gruseliger Clown und eine Katze.','gruselige Augen am Himmel','ein gruseliger Filmabend','chill','none'),
(1642,'de','Der Himmel über dem Dorf ist rot.','Der Himmel über dem Dorf ist blau.','ein Dorf bei Sonnenuntergang','ein Dorf unter tiefem Schnee','business','none'),
(1643,'de','Er trägt einen Cowboyhut.','Er trägt eine Baseballkappe.','ein breiter Cowboyhut','ein breiter Strohhut','chill','none'),
(1644,'de','Der Ritter trägt eine komplette Rüstung.','Der Ritter trägt keine Rüstung.','ein Ritter in Metallrüstung','ein Ritter ohne Rüstung','chill','none'),
(1647,'de','Auf der Postkarte ist eine Frau.','Auf der Postkarte ist ein Mann.','eine alte, zerrissene Postkarte','eine Postkarte von einem Strand','chill','none'),
(1649,'de','Hier ist alles bunt!','Hier ist alles grau!','ein bunter Regenbogenweg','ein bunter Regenschirm','dramatic','exclamation'),
(1650,'de','Schönes Schloss, gruselige Klippe.','Schönes Schloss, gruselige Brücke.','ein Schloss auf einer Klippe','eine Klippe über dem Meer','gossip','understatement'),
(1651,'de','Ihr blauer Umhang hat Sterne.','Ihr roter Umhang hat Sterne.','ein blauer Umhang voller Sterne','ein Umhang aus Federn','chill','none'),
(1652,'de','Gleich berührt sie den Schmetterling!','Gleich berührt sie den Vogel!','einen leuchtenden Schmetterling berühren','einen leuchtenden Schmetterling fangen','dramatic','guessing'),
(1653,'de','Die Katze will den Goldfisch …','Die Katze will den Vogel …','ein Goldfisch im Glas','ein Goldfisch im Teich','dramatic','guessing'),
(1655,'de','Wow, ihre Krone ist so hoch!','Wow, ihre Krone ist so klein!','eine hohe goldene Krone','eine kleine silberne Krone','low_iq','exclamation'),
(1656,'de','Ihre Lippen sind rot.','Ihre Lippen sind blau.','glänzende rote Lippen','ein Lippenabdruck auf einem Glas','chill','none'),
(1658,'de','Dunkler Stein, rote Rosen, cool.','Dunkler Stein, weiße Rosen, cool.','ein dunkler gotischer Torbogen','ein dunkler Waldweg','slang','none'),
(1660,'de','Eine Truhe voller Schätze!','Eine Truhe voller Flaschen!','eine offene Schatztruhe','eine Schatzkarte auf Papier','dramatic','exclamation'),
(1661,'de','Die Zeit ist etwas unklar.','Die Karte ist etwas unklar.','die Uhrzeit ablesen','eine Zeitmaschine','chill','understatement'),
(1664,'de','Der Priester hört zu.','Der Priester singt.','ein Priester im Beichtstuhl','ein Priester bei einer Hochzeit','chill','none'),
(1665,'de','Sie ist in einem uralten Tempel.','Sie ist in einem uralten Schloss.','ein uralter ägyptischer Tempel','ein uralter griechischer Tempel','chill','none'),
(1666,'de','Auf dem Pharao sitzt eine Kobra.','Auf dem Pharao sitzt ein Falke.','ein Pharao im Profil','ein Pharao auf dem Thron','nerd','none'),
(1667,'de','Paris bei Nacht. Pure Magie!','Paris am Mittag. Pure Magie!','Paris bei Nacht','Paris im Regen','dramatic','exclamation'),
(1669,'de','Zwei Flügel, aber die Statue kann nicht fliegen.','Vier Flügel, aber die Statue kann nicht fliegen.','zwei gefiederte Flügel','zwei Flugzeugflügel','low_iq','understatement'),
(1670,'de','Ein roter Bus in London. Klassiker.','Ein rotes Auto in London. Klassiker.','ein roter Bus in London','ein roter Bus in Paris','chill','cliche'),
(1672,'de','Prag leuchtet in der Dämmerung.','Prag leuchtet am Mittag.','die Prager Burg in der Dämmerung','die Prager Burg im Schnee','chill','none'),
(1674,'de','Lila Himmel, lila Hügel.','Lila Himmel, grüne Hügel.','ein lila Sternenhimmel','ein lila Blumenfeld','chill','none'),
(1675,'de','Er steht allein an einem Baum.','Er steht allein an einem Haus.','allein auf einem leeren Feld','allein in einem leeren Raum','dramatic','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
