begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(2155,'de','Dieses selbstbewusste Lächeln wirkt.','Dieses nervöse Lächeln wirkt.','ein selbstbewusstes halbes Lächeln','ein selbstbewusstes lautes Lachen','flirt','none'),
(2157,'de','Ein Baby aus Indien trägt Gold.','Ein Baby aus Indien trägt Rot.','ein Gemälde aus Indien','ein Teppich aus Indien','chill','none'),
(2158,'de','Ich liebe das orange Kopftuch!','Ich liebe das blaue Kopftuch!','ein oranges Kopftuch','ein Kopftuch abnehmen','flirt','exclamation'),
(2159,'de','Die Katze fühlt sich sehr majestätisch.','Der Hund fühlt sich sehr majestätisch.','eine majestätische Katze','ein majestätischer Löwe','ironic','guessing'),
(2164,'de','Ein Weg führt in den Wald. Wer geht zuerst?','Ein Fluss führt in den Wald. Wer geht zuerst?','ein Weg durch den Wald','eine Hütte im Wald','dramatic','guessing'),
(2172,'de','Ein Sportwagen im Farbsturm.','Ein Sportwagen im Schneesturm.','ein dunkelblauer Sportwagen','ein dunkelblauer Familienwagen','dramatic','exaggeration'),
(2174,'de','Ein Baum blüht im Schnee!','Ein Baum brennt im Schnee!','ein blühender Baum bei Nacht','blühende Blumen im Frühling','dramatic','exclamation'),
(2175,'de','Mitternacht im Kiefernwald.','Mitternacht in der Wüste.','Mitternacht unter den Sternen','eine Party um Mitternacht','chill','none'),
(2176,'de','Es regnet im Gang!','Es schneit im Gang!','ein verregneter Gang in der Bibliothek','ein voller Gang im Supermarkt','dramatic','exclamation'),
(2177,'de','Sogar der Mond kam für den DJ!','Sogar die Sonne kam für den DJ!','ein DJ auf der Straße','ein DJ im Club','slang','exaggeration'),
(2178,'de','Psst, zwei Katzen spähen hervor.','Psst, zwei Hunde spähen hervor.','hinter Blättern hervorspähen','durch ein Fenster spähen','gossip','none'),
(2181,'de','Die Straße ist krass überfüllt.','Die Straße ist krass leer.','eine überfüllte Neonstraße','ein überfüllter Zugwaggon','slang','none'),
(2182,'de','Der Wanderer hat einen roten Rucksack.','Der Wanderer hat einen blauen Rucksack.','ein Wanderer auf einem Felsvorsprung','ein Wanderer im Zelt','chill','none'),
(2184,'de','Der Tiger brüllt!','Der Löwe brüllt!','ein brüllender Tiger','ein schlafender Tiger','dramatic','exclamation'),
(2185,'de','Der Pianist hat blonde Haare.','Der Pianist hat schwarze Haare.','ein Pianist am Klavier','ein Pianist am Keyboard','chill','none'),
(2186,'de','Jesus trägt eine Krone aus Dornen.','Jesus trägt eine Krone aus Gold.','eine Krone aus Dornen','eine Rose mit Dornen','chill','none'),
(2187,'de','Buddha meditiert.','Buddha tanzt.','Buddha beim Meditieren','Buddha im Liegen','chill','none'),
(2188,'de','Der Junge weint, Mama nicht.','Der Junge singt, Mama nicht.','weinen auf dem Fahrrad','weinen im Bett','ironic','none'),
(2189,'de','Jemand geht über Bord!','Jemand springt über Bord!','rückwärts über Bord gehen','im Boot einschlafen','dramatic','exclamation'),
(2190,'de','Dieser Bösewicht hat flammende Augen.','Dieser Bösewicht hat blaue Augen.','ein Bösewicht in brennenden Ruinen','ein Bösewicht in einer Burg','dramatic','none'),
(2191,'de','Der Android hat ein menschliches Gesicht.','Der Android hat einen langen Bart.','ein leuchtender weiblicher Android','ein Android in der Küche','nerd','none'),
(2192,'de','Harry Potter würde diese Kolben lieben.','Harry Potter würde diese Besen lieben.','leuchtende Glaskolben','eine Thermoskanne','nerd','guessing'),
(2194,'de','Tropische Blätter sind groß. Wow.','Tropische Blätter sind winzig. Wow.','dichte tropische Blätter','ein tropischer Strand','low_iq','none'),
(2195,'de','Das Aquarell tropft.','Die Ölfarbe tropft.','ein Porträt in Aquarell','eine Landschaft in Aquarell','chill','none'),
(2199,'de','Überall zarte Rosen!','Überall zarte Tulpen!','zarte rosa Rosen','eine zarte Glasvase','dramatic','exaggeration'),
(2200,'de','Sie sieht in ihrem Abendkleid elegant aus.','Sie sieht in ihrem Mantel elegant aus.','ein elegantes fließendes Kleid','ein eleganter schwarzer Anzug','flirt','none'),
(2201,'de','Ihre orange Rüstung ist so cool!','Ihre rosa Rüstung ist so cool!','orange Haare und Rüstung','eine Orange in ihrer Hand','flirt','exclamation'),
(2202,'de','Sein weißer Blazer sieht schick aus.','Sein roter Blazer sieht schick aus.','ein schicker weißer Blazer','ein schicker dunkler Anzug','chill','none'),
(2204,'de','Er hält ein Lamm.','Er hält einen Hund.','ein Lamm in seinen Armen','ein Lamm auf der Weide','chill','none'),
(2207,'de','Die Roboterhand zeigt auf etwas.','Die Roboterhand winkt.','auf einen Bildschirm zeigen','in den Himmel zeigen','chill','none'),
(2208,'de','Ihr Haar ist leuchtend rosa.','Ihr Haar ist leuchtend grün.','leuchtend rosa Haare','ein leuchtend rosa Kleid','business','none'),
(2211,'de','Rate mal, wer einen Dreizack hat? Der Meeresgott.','Rate mal, wer einen Hammer hat? Der Meeresgott.','ein Gott mit Dreizack','ein Dreizack im Sand','gossip','guessing'),
(2212,'de','Krasse Streifen, Tiger!','Krasse Flecken, Tiger!','ein Tiger mit schwarzen Streifen','ein Zebra mit schwarzen Streifen','slang','exclamation'),
(2213,'de','Fakt: Widder haben gedrehte Hörner.','Fakt: Widder haben flache Hörner.','ein Widder mit gedrehten Hörnern','ein grasender Widder','nerd','cliche'),
(2214,'de','Durch das Loch sehe ich eine Burg.','Durch das Loch sehe ich eine Kirche.','durch ein Felsloch schauen','durch ein Fenster schauen','chill','none'),
(2216,'de','Sie betet an einem Altar.','Sie singt an einem Altar.','an einem Altar mit Kerzen beten','vor dem Altar heiraten','chill','none'),
(2217,'de','Sie spricht einen Zauberspruch. Cool.','Sie wirft ein Netz aus. Cool.','einen Zauberspruch sprechen','einen Zaubertrank brauen','slang','none'),
(2218,'de','Schaltkreise sind überall um ihn herum.','Blumen sind überall um ihn herum.','leuchtende Linien von Schaltkreisen','eine Rennstrecke','nerd','none'),
(2220,'de','Er zählt das Geld sorgfältig.','Er zählt die Münzen sorgfältig.','einen Stapel Scheine zählen','die Sekunden herunterzählen','business','none'),
(2224,'de','Sie halten Händchen.','Sie schütteln sich die Hände.','Händchen halten im Regen','Händchen halten in der Sonne','flirt','none'),
(2225,'de','Das arme Mädchen, ihr Haar ist völlig durchnässt.','Das arme Mädchen, ihr Haar ist völlig trocken.','durchnässt vom Starkregen','durchnässt von heißem Wasser','gossip','none'),
(2226,'de','Er trägt goldene Armbänder.','Er trägt goldene Handschuhe.','goldene Armbänder an den Handgelenken','ein Armband im Laden','chill','none'),
(2227,'de','Sie blickt kurz zurück. Zu dir?','Sie blickt kurz nach unten. Zu dir?','kurz über die Schulter blicken','kurz aufs Handy blicken','gossip','guessing'),
(2228,'de','Sie sitzt hoch über der Stadt.','Sie sitzt hoch über dem Meer.','hoch über der Stadt','über den Wolken','chill','none'),
(2231,'de','Eine riesige goldene Sphinx.','Eine riesige silberne Sphinx.','eine goldene Sphinx-Statue','eine schlafende Sphinx-Katze','chill','none'),
(2232,'de','Der Buddha wirkt friedlich.','Der Buddha wirkt wütend.','ein friedlicher goldener Buddha','ein friedlicher goldener Tempel','chill','none'),
(2233,'de','Sie hat zwei Baseballhandschuhe.','Sie hat zwei Baseballschläger.','Baseballhandschuhe in beiden Händen','Baseball im Fernsehen','chill','none'),
(2234,'de','Der Krieger hat große Muskeln.','Der Krieger hat einen großen Schild.','die großen Muskeln eines Kriegers','der große Schild eines Kriegers','chill','none'),
(2235,'de','Er ist im vollen Profil zu sehen.','Er ist von hinten zu sehen.','ein Mann im Profil','ein Profilbild im Netz','nerd','none'),
(2236,'de','Ein Palast unter riesigem Mond. Wow!','Ein Palast unter riesiger Sonne. Wow!','ein Palast in den Bergen','ein Palast in der Wüste','dramatic','exclamation'),
(2237,'de','Schau dir dieses glänzende gelbe Auto an!','Schau dir dieses glänzende rote Auto an!','ein glänzendes gelbes Auto','ein glänzender gelber Bus','slang','exclamation'),
(2238,'de','Die Moschee hat viele Kuppeln.','Die Moschee hat eine Kuppel.','eine große Moschee mit Kuppeln','eine Moschee in der Wüste','chill','none'),
(2242,'de','Der Schwarm hat null freie Plätze.','Der Schwarm hat viele freie Plätze.','ein Schwarm kleiner Vögel','ein Schwarm Bienen','business','exaggeration'),
(2245,'de','Ist nur ein bisschen überwuchert.','Ist nur ein bisschen verschneit.','ein überwuchertes Häuschen','ein überwucherter Rasen','ironic','understatement'),
(2247,'de','Schottland hat eine einsame Kirche.','Schottland hat eine einsame Burg.','eine Kirche in Schottland','eine Burg in Schottland','chill','none'),
(2248,'de','Sie schwebt anmutig.','Sie tanzt anmutig.','anmutig in der Luft schweben','ein anmutiger Tanz auf der Bühne','chill','none'),
(2249,'de','Eine Steampunk-Stadt aus Zahnrädern.','Eine Steampunk-Stadt aus Glas.','Steampunk-Türme aus Messing','eine Steampunk-Kostümparty','chill','none'),
(2250,'de','Sie starrt auf die Stadt.','Sie starrt aufs Meer.','auf eine verregnete Stadt starren','in den Sternenhimmel starren','dramatic','none'),
(2251,'de','Dresscode im Himmel: ein weißes Gewand.','Dresscode im Himmel: ein schwarzes Gewand.','ein langes weißes Gewand','ein Gewand mit Kapuze','business','cliche'),
(2254,'de','Ein gefrorener Palast. Hi, Elsa!','Ein gefrorener See. Hi, Elsa!','ein gefrorener Schneepalast','gefrorene Erbsen in der Tüte','slang','exclamation'),
(2256,'de','Ihre Beine sind komplett mechanisch.','Ihre Beine sind komplett aus Holz.','mechanische Arme und Beine','eine mechanische Uhr','nerd','none'),
(2257,'de','Ihre Augenbrauen sind sehr dunkel.','Ihre Augenbrauen sind sehr hell.','dichte dunkle Augenbrauen','dünne blonde Augenbrauen','chill','none'),
(2258,'de','Die Kirche hat eine hohe Turmspitze.','Die Kirche hat eine runde Kuppel.','eine hohe Turmspitze','eine Turmspitze auf einer Burg','chill','none'),
(2259,'de','Bring mich sofort zu dieser Lagune!','Bring mich sofort zu diesem Gletscher!','eine türkise Lagune mit Palmen','eine gefrorene Lagune im Winter','dramatic','exclamation'),
(2260,'de','Armes Ruderboot, keiner will es.','Armes Schiff, keiner will es.','ein leeres Ruderboot aus Holz','ein Ruderboot voller Menschen','dramatic','exaggeration'),
(2262,'de','Punkte und Linien verbinden sie.','Punkte und Linien trennen sie.','Linien verbinden zwei Menschen','ein Kabel verbindet ein Handy','nerd','none'),
(2268,'de','Sie steht auf einem Drahtseil. Ohne Netz!','Sie steht auf einer Leiter. Ohne Netz!','auf einem Drahtseil balancieren','eine Drahtseilnummer im Zirkus','dramatic','exclamation'),
(2269,'de','Ihre Bluse ist locker und weiß.','Ihr Kleid ist locker und weiß.','eine lockere weiße Bluse','eine enge schwarze Bluse','chill','none'),
(2271,'de','Sie chillt in einem Korridor.','Sie chillt in einer Küche.','ein Korridor im Raumschiff','ein Korridor im Krankenhaus','slang','none'),
(2273,'de','Zerrissene Jeans, alles in Denim.','Zerrissene Jeans, alles in Schwarz.','stark zerrissene blaue Jeans','blaue Jeans bügeln','slang','none'),
(2274,'de','Dieser Kragen aus Spitze ist so edel!','Dieser Kragen aus Pelz ist so edel!','ein verzierter Kragen aus Spitze','einen Schnürsenkel binden','gossip','none'),
(2275,'de','Cooles Outfit, riesige Sneaker!','Cooles Outfit, winzige Sneaker!','ein Streetstyle-Outfit','ein Outfit für eine Hochzeit','flirt','exclamation'),
(2278,'de','Er schaut nach oben in den Himmel.','Er schaut nach oben zu einem Flugzeug.','nach oben zu den Wolken schauen','ein Wort nachschlagen','chill','none'),
(2280,'de','Er umarmt sie bei Sonnenuntergang.','Er umarmt sie im Auto.','sich auf einem Segelboot umarmen','einen Baum umarmen','flirt','none'),
(2282,'de','Segeln bei Sonnenuntergang. So chill.','Surfen bei Sonnenuntergang. So chill.','Segeln bei Sonnenuntergang','Segeln im Sturm','slang','none'),
(2284,'de','Federn? Mutige Frisur.','Perlen? Mutige Frisur.','eine Frisur aus Federn','eine kurze Frisur','flirt','none'),
(2285,'de','Ihr Sweatshirt ist riesig.','Ihr Rucksack ist riesig.','ein großes blaues Sweatshirt','ein Sweatshirt auf einem Stuhl','chill','exaggeration'),
(2287,'de','Er sitzt allein in seiner Trauer.','Er sitzt allein in einem Auto.','Trauer in einem dunklen Garten','Trauer bei einer Beerdigung','dramatic','none'),
(2288,'de','Crop-Top am Jachthafen.','Crop-Top im Skigebiet.','ein schwarzes Crop-Top','ein weißes Crop-Top','chill','none'),
(2291,'de','Nur ein paar Asteroiden. Entspann dich.','Nur ein paar Vögel. Entspann dich.','schwebende Asteroiden','ein Asteroid trifft die Erde','ironic','understatement'),
(2295,'de','Diese Ärmel sind riesig!','Diese Stiefel sind riesig!','weite weiße Ärmel','kurze schwarze Ärmel','dramatic','exclamation'),
(2296,'de','Ihr geblümtes Kleid passt zur Wand!','Ihr gestreiftes Kleid passt zur Wand!','ein oranges geblümtes Kleid','ein geblümtes Strandhemd','gossip','exaggeration'),
(2297,'de','Wellen schlagen ans Ufer.','Wellen schlagen ans Boot.','Palmen am Ufer','ein Boot am Ufer','chill','none'),
(2300,'de','Die Gitarre steht in Flammen!','Das Klavier steht in Flammen!','eine Gitarre in Flammen','ein Haus in Flammen','dramatic','exclamation'),
(2301,'de','Das Space Shuttle startet.','Das Flugzeug startet.','ein Space Shuttle starten','ein neues Produkt starten','chill','none'),
(2302,'de','Er ist schwerelos und entspannt.','Er ist schwerelos und verängstigt.','ein schwereloser Astronaut','eine schwerelose Feder','chill','none'),
(2305,'de','Ein felsiger Weg zu einem Leuchtturm.','Ein felsiger Weg zu einer Burg.','eine felsige Landzunge','ein felsiger Strand mit Liegen','chill','none'),
(2306,'de','Das Land nimmt kein Ende.','Die Stadt nimmt kein Ende.','Kinder auf dem Land','Kinder verlassen das Land','chill','exaggeration'),
(2308,'de','Der Wikinger hält eine Klinge.','Der Wikinger hält eine Axt.','ein Wikinger in Fell','ein Wikinger auf einem Schiff','chill','none'),
(2311,'de','Das Buntglas ist riesig.','Das Buntglas ist winzig.','hohe Fenster aus Buntglas','eine Lampe aus Buntglas','chill','none'),
(2312,'de','Ein Rennwagen bei den Palmen.','Ein Rennwagen bei den Kiefern.','ein roter Rennwagen','ein rotes Rennpferd','chill','none'),
(2313,'de','Zuhause ist, wo der Campingbus steht.','Zuhause ist, wo das orange Zelt steht.','ein oranger Campingbus','ein Campingbus in der Stadt','chill','cliche'),
(2314,'de','Das Kostüm des Geists: ein altes Laken.','Das Kostüm des Geists: ein altes Handtuch.','ein Geist aus weißem Laken','ein Geist in einer Burg','low_iq','cheap_quality'),
(2315,'de','Diese Landschaft ist aus Papier!','Diese Landschaft ist aus Glas!','eine Landschaft aus Papier','ein Landschaftsfoto','dramatic','exclamation'),
(2317,'de','Ihre rote Kapuze ist aufgesetzt.','Ihre rote Kapuze ist abgesetzt.','eine aufgesetzte rote Kapuze','die Motorhaube eines Autos','chill','none'),
(2318,'de','Sie hat ein sehr langes Schwert.','Sie hat einen sehr langen Speer.','ein langes gebogenes Schwert','ein langes gerades Schwert','chill','none'),
(2322,'de','Das Glas ist zerbrochen!','Die Uhr ist zerbrochen!','ein zerbrochenes Spiegelporträt','ein gebrochener Arm im Gips','dramatic','exclamation'),
(2324,'de','Er singt wie ein Star!','Er tanzt wie ein Star!','ins Mikrofon singen','unter der Dusche singen','flirt','exaggeration'),
(2326,'de','Der Prinz hat coole blaue Haare.','Der Prinz hat coole pinke Haare.','ein Prinz mit Krone','ein Prinz auf einem Pferd','slang','none'),
(2327,'de','Dieses Auto und die Palmen sehen so cool aus.','Dieses Fahrrad und die Palmen sehen so cool aus.','Palmen bei Sonnenuntergang','Palmen auf einer Insel','slang','none'),
(2328,'de','So ein „bescheidener“ Thron!','So ein „bescheidenes“ Bett!','ein riesiger goldener Thron','ein leerer goldener Thron','ironic','exclamation'),
(2330,'de','Sie will dir Blumen geben.','Sie will dir einen Kuchen geben.','drei gelbe Blumen geben','rote Rosen geben','flirt','guessing'),
(2333,'de','Sie sind so verliebt!','Sie sind so wütend!','verliebt unter Herbstlaub','verliebt am Strand','dramatic','exclamation'),
(2340,'de','Dieses Haus ist ein bisschen seltsam.','Dieses Auto ist ein bisschen seltsam.','ein seltsames hohes Haus','ein seltsames altes Boot','chill','understatement'),
(2341,'de','Blumen lassen den Tod hübsch aussehen.','Kerzen lassen den Tod hübsch aussehen.','der Tod zwischen Blumen','Tod bei einem Autounfall','ironic','none'),
(2344,'de','Die Häuser sind ein bisschen krumm.','Die Bäume sind ein bisschen krumm.','hohe krumme Häuser','ein krummer Bilderrahmen','ironic','understatement'),
(2345,'de','Der Zauberer hat so einen langen Bart!','Der Zauberer hat so einen kurzen Bart!','ein alter Zauberer in Grau','ein alter Zauberer in Rot','dramatic','exclamation'),
(2347,'de','Er erkundet einen Exoplaneten.','Er erkundet eine tiefe Höhle.','eine fremde Welt erkunden','eine alte Burg erkunden','nerd','none'),
(2349,'de','Sogar die Katze hat sich verkleidet!','Sogar der Hund hat sich verkleidet!','als Hexen verkleidet','als Piraten verkleidet','gossip','exclamation'),
(2350,'de','Jemand hat Gesichter geschnitzt! Wow!','Jemand hat Namen geschnitzt! Wow!','geschnitzte Kürbisgesichter','geschnitzte Holzgesichter','low_iq','exclamation'),
(2351,'de','Jemand fährt ein grünes Auto.','Jemand fährt ein gelbes Auto.','durch den Herbst fahren','durch den Schnee fahren','chill','none'),
(2353,'de','Die Pilze sind riesig, Bro.','Die Pilze sind winzig, Bro.','riesige rosa Pilze','riesige rosa Blumen','slang','none'),
(2354,'de','Ein riesiger goldener Kopfschmuck!','Ein riesiger silberner Kopfschmuck!','ein riesiger goldener Kopfschmuck','einen Kopfschmuck abnehmen','dramatic','exclamation'),
(2356,'de','Die Straße führt zu einem Planeten.','Die Straße führt zu einer Burg.','zu einem riesigen Planeten','zu einer riesigen Stadt','dramatic','none'),
(2357,'de','Das Haus ist schwarz-weiß.','Das Haus ist rot-weiß.','eine schwarz-weiße Zeichnung','ein Schwarz-Weiß-Film','chill','none'),
(2358,'de','Der Bauernhof hat rote Dächer.','Der Bauernhof hat blaue Dächer.','ein Bauernhof am Hang','ein Bauernhof mit Kühen','chill','none'),
(2359,'de','Sie tragen traditionelle Kleidung.','Sie tragen moderne Kleidung.','traditionelle indische Kleidung','eine traditionelle Hochzeitstorte','chill','none'),
(2360,'de','Dieses rote Auto sieht krass schnell aus.','Dieser rote Transporter sieht krass schnell aus.','ein schnelles rotes Auto','ein schnelles rotes Boot','slang','exaggeration'),
(2363,'de','Sie verwandelt sich in geheimnisvollen Rauch.','Sie verwandelt sich in geheimnisvolles Wasser.','eine geheimnisvolle Frau aus Rauch','eine geheimnisvolle verschlossene Tür','dramatic','none'),
(2364,'de','Hinter ihm steht ein weißer Stier.','Hinter ihm steht ein weißes Pferd.','ein Stier mit gebogenen Hörnern','ein Stier in der Arena','chill','none'),
(2365,'de','Sein Anzug aus Metall ist mega glänzend.','Sein Anzug aus Metall ist mega dreckig.','ein roter Anzug aus Metall','ein rotes Auto aus Metall','slang','none'),
(2367,'de','Dieses Auto ist ein kleines bisschen schmutzig.','Dieser Bus ist ein kleines bisschen schmutzig.','ein alter schmutziger Sportwagen','ein schmutziger alter Bus','ironic','understatement'),
(2368,'de','Dieser Strand ist das totale Paradies.','Diese Wüste ist das totale Paradies.','ein tropisches Paradies am Abend','ein Paradies für Skifahrer','slang','none'),
(2371,'de','Der Engel ist in Kummer versunken.','Der Engel ist in ein Buch versunken.','ein Engel voller Kummer','ein Engel voller Freude','dramatic','none'),
(2372,'de','Er sieht total erschöpft aus.','Er sieht total aufgeregt aus.','ein erschöpfter Arbeiter','ein leerer Handyakku','slang','none'),
(2373,'de','Das Universum wirkt überfüllt.','Das Universum wirkt leer.','ein Universum voller Planeten','ein Universum ohne Sterne','ironic','exaggeration'),
(2375,'de','Eine Hälfte grau, eine Hälfte gelb. Es kann sich nicht entscheiden.','Eine Hälfte grau, eine Hälfte grün. Es kann sich nicht entscheiden.','die Hälfte eines gelben Autos','die Hälfte eines gelben Busses','low_iq','guessing'),
(2378,'de','Sie entspannt gerade richtig.','Sie rennt gerade richtig.','unter dem Mond entspannen','am Strand entspannen','slang','none'),
(2379,'de','Rote Blätter fallen.','Rote Äpfel fallen.','Blätter fallen im Regen','Schnee fällt auf Autos','chill','none'),
(2380,'de','Das Auto entkommt dem Feuer!','Das Auto entkommt der Flut!','einem brennenden Wald entkommen','einem brennenden Haus entkommen','dramatic','exclamation'),
(2381,'de','Diese Krallen sind echt scharf!','Diese Zähne sind echt scharf!','Krallen auf einem Ast','Krallen einer Katze','dramatic','exclamation'),
(2382,'de','Schau, ihr Fischschwanz hat blaue Schuppen.','Schau, ihr Fischschwanz hat rosa Schuppen.','ein Schwanz mit blauen Schuppen','sich auf die Waage stellen','gossip','none'),
(2383,'de','Überall Feuer und Edelsteine!','Überall Eis und Edelsteine!','funkelnde bunte Edelsteine','Edelsteine in einer dunklen Höhle','dramatic','exaggeration'),
(2384,'de','Ein winziges Königreich auf einem Hügel.','Ein winziges Königreich auf einer Insel.','ein Königreich wie im Märchen','das Königreich der Tiere','chill','none'),
(2385,'de','Eine lila außerirdische Landschaft.','Eine grüne außerirdische Landschaft.','eine lila außerirdische Welt','ein Außerirdischer im Raumschiff','nerd','none'),
(2386,'de','Vom Geländer aus sieht man den Sonnenuntergang.','Vom Geländer aus sieht man einen Berg.','ein Balkongeländer aus Metall','ein Treppengeländer','chill','none'),
(2387,'de','Der Baum ist verdreht. Cool.','Der Baum ist gerade. Cool.','ein verdrehter alter Baum','ein verdrehter Metallzaun','low_iq','none'),
(2388,'de','Dieser Gamer liebt Pink.','Dieser Gamer liebt Grün.','ein Gamer in Pink','ein Gamer in Blau','gossip','none'),
(2389,'de','Sie betet voller Glauben.','Sie betet mit offenen Armen.','in tiefem Glauben beten','ihren Glauben verlieren','chill','none'),
(2390,'de','So stilvoll am Strand!','So stilvoll auf einem Schiff!','ein stilvoller Strandlook','ein stilvoller Wintermantel','flirt','exclamation'),
(2391,'de','Epische Landschaft, roter Himmel.','Epische Landschaft, blauer Himmel.','eine Landschaft mit riesigem Mond','die Kulisse fürs Schultheater','slang','none'),
(2392,'de','Ein Spaziergang mit Strohhut? Stilvoll.','Ein Spaziergang mit rotem Hut? Stilvoll.','ein Spaziergang zwischen Blumen','ein Spaziergang am Strand','flirt','none'),
(2393,'de','Büro-Look mit High Heels.','Büro-Look mit Turnschuhen.','schwarze High Heels mit Riemchen','High Heels im Karton','business','none'),
(2394,'de','Er muss einen Weg wählen.','Er muss ein Boot wählen.','den richtigen Weg wählen','das richtige Kleid wählen','dramatic','guessing'),
(2395,'de','Seine Weste hat goldene Knöpfe.','Seine Weste hat silberne Knöpfe.','eine schwarze Weste aus Leder','eine Weste unter einer Jacke','chill','none'),
(2396,'de','Dieses geschnürte Korsett ist umwerfend.','Dieser geschnürte Handschuh ist umwerfend.','ein geschnürtes Korsett','geschnürte Stiefel','flirt','none'),
(2397,'de','Dieser Raum ist so düster!','Dieser Raum ist so sonnig!','ein düsterer gotischer Raum','ein düsterer Regentag','dramatic','exclamation'),
(2398,'de','Die Terrasse bietet Meerblick.','Die Terrasse bietet Stadtblick.','eine geflieste Terrasse am Meer','eine Terrasse in den Bergen','business','none'),
(2400,'de','Das ist mal ein grimmiger Wikinger!','Das ist mal ein grimmiger Pirat!','ein grimmiger, wütender Blick','ein heftiger Sturm auf See','dramatic','exclamation'),
(2401,'de','Ein Weg in eine Welt der Fantasie.','Ein Weg in eine belebte Stadt.','ein Waldweg voller Fantasie','ein Fantasy-Buchcover','chill','none'),
(2404,'de','Dieser Lotus hat eine orange Mitte.','Dieser Lotus hat eine lila Mitte.','eine weiße Lotusblüte','der Lotussitz im Yoga','nerd','none'),
(2406,'de','Ein Jeep, viel zu viele Taschen!','Ein Fahrrad, viel zu viele Taschen!','ein Jeep voller Taschen','ein Jeep in der Stadt','dramatic','exaggeration'),
(2408,'de','Fantasie öffnet einen echten Weg.','Fantasie öffnet eine echte Tür.','ein Buch der Fantasie','überhaupt keine Fantasie','chill','none'),
(2411,'de','Diese Krone ist so reich verziert!','Diese Maske ist so reich verziert!','eine reich verzierte goldene Krone','eine reich verzierte Holztür','gossip','none'),
(2412,'de','Sie gehen Arm in Arm.','Sie rennen Arm in Arm.','Arm in Arm gehen','Arm in Arm sitzen','chill','none'),
(2413,'de','Sie umarmt ein Wolfsjunges!','Sie umarmt ein Bärenjunges!','ein Wolfsjunges umarmen','einen großen Wolf umarmen','dramatic','exclamation'),
(2415,'de','Der Gott trägt Girlanden aus Blumen.','Der Gott trägt Girlanden aus Papier.','Girlanden aus roten Blumen','Girlanden am Weihnachtsbaum','chill','none'),
(2417,'de','Dunkel und Hell in Harmonie.','Rot und Blau in Harmonie.','eine Kugel der Harmonie','in Harmonie singen','nerd','none'),
(2418,'de','Ich glaube, das ist ein Singvogel.','Ich glaube, das ist eine Taube.','ein Singvogel auf einem Ast','ein Singvogel auf einem Dach','low_iq','guessing'),
(2420,'de','Dieser wackelige Turm ist „sicher“.','Diese wackelige Brücke ist „sicher“.','ein wackeliger Turm aus Häusern','ein wackeliger alter Stuhl','ironic','understatement'),
(2421,'de','Dieser Pilz ist groß. Echt groß.','Dieser Pilz ist klein. Echt klein.','ein riesiger blasser Pilz','Schimmelpilz auf altem Brot','low_iq','exaggeration'),
(2422,'de','Sie liest in Latzhose.','Sie schläft in Latzhose.','eine blaue Jeans-Latzhose','eine Latzhose voller Farbe','chill','none'),
(2424,'de','Links wachsen Zypressen.','Rechts wachsen Zypressen.','eine Reihe Zypressen','eine Zypresse im Topf','nerd','none'),
(2425,'de','Eine schwarze Katze in einem gruseligen Rahmen!','Eine weiße Katze in einem gruseligen Rahmen!','ein Rahmen mit schwarzen Rosen','ein Fahrradrahmen','dramatic','exclamation'),
(2428,'de','Drei Monitore, maximaler Fokus.','Zwei Monitore, maximaler Fokus.','drei große Monitore','ein Babyfon','business','exaggeration'),
(2429,'de','Yo, der Hirsch steht im Bach.','Yo, der Hirsch steht auf einem Feld.','ein Hirsch im Bach','ein Hirsch im Schnee','slang','none'),
(2430,'de','Der Fluss fließt an Felsen vorbei.','Der Fluss fließt an Häusern vorbei.','ein Fluss fließt durch Felsen','ein Fluss fließt durch die Stadt','chill','none'),
(2432,'de','Ihre Flamenco-Pose ist der Hammer!','Ihre Ballett-Pose ist der Hammer!','Flamenco mit Fächer','Flamenco auf einer Bühne','slang','exclamation'),
(2433,'de','Das Pferd galoppiert auf uns zu!','Der Esel galoppiert auf uns zu!','ein galoppierendes weißes Pferd','ein galoppierendes schwarzes Pferd','dramatic','exclamation'),
(2434,'de','Das Stillleben zeigt Blüten.','Das Stillleben zeigt Orangen.','ein Stillleben mit Blüten','ein Stillleben mit Obst','nerd','none'),
(2435,'de','Der Bach ist voller Kiesel.','Der Bach ist voller Fische.','glatte runde Kiesel','Kiesel am Strand','chill','none'),
(2439,'de','Die Straße ist nachts nass.','Die Straße ist nachts trocken.','eine nasse Straße bei Nacht','ein nasser Sandstrand','business','none'),
(2440,'de','Der Strom ist überall!','Das Wasser ist überall!','Funken und Strom','eine Stromrechnung','dramatic','exaggeration'),
(2446,'de','Große Schleifen, lange Schnürsenkel!','Große Schleifen, kurze Schnürsenkel!','lange gelbe Schnürsenkel','gerissene gelbe Schnürsenkel','low_iq','exclamation'),
(2449,'de','Nur „ein paar“ leuchtende Schaufenster.','Nur „ein paar“ dunkle Schaufenster.','leuchtende Schaufenster','ein kaputtes Schaufenster','ironic','understatement'),
(2450,'de','Ein Gewitter über dem Wasser.','Ein Gewitter über der Stadt.','ein Gewitter über dem Wasser','ein Gewitter über einer Stadt','chill','none'),
(2451,'de','Ein Vogel am Eiffelturm.','Ein Flugzeug am Eiffelturm.','der Eiffelturm am Fluss','der Eiffelturm im Schnee','chill','none'),
(2452,'de','Der Spaziergang im Schnee ist romantisch!','Der Spaziergang im Regen ist romantisch!','ein romantischer Spaziergang im Schnee','ein romantisches Dinner bei Kerzenlicht','flirt','exclamation'),
(2454,'de','Der kurvenreiche Weg hat Laternen.','Der gerade Weg hat Lampen.','ein kurvenreicher Kopfsteinpflasterweg','ein kurvenreicher Bergfluss','chill','none'),
(2455,'de','Sie trägt grüne Shorts.','Sie trägt eine grüne Hose.','grüne Shorts aus Jeans','grüne Badeshorts','chill','none'),
(2457,'de','Die Krankenschwester hat ein Stethoskop.','Die Krankenschwester hat ein Klemmbrett.','eine Krankenschwester in Uniform','eine Krankenschwester mit Baby','chill','none'),
(2458,'de','Ein Bauernhaus mit erleuchteten Fenstern.','Ein Bauernhaus mit dunklen Fenstern.','ein Bauernhaus bei Sonnenuntergang','ein Bauernhaus am Meer','chill','none'),
(2460,'de','Wildblumen im blauen Topf, süß.','Wildblumen im roten Topf, süß.','ein Topf mit Wildblumen','ein Feld voller Wildblumen','slang','none'),
(2462,'de','Am sternenklaren Himmel steht ein Mond.','Am sternenklaren Himmel steht ein Regenbogen.','ein sternenklarer Nachthimmel','eine sternenklare Nacht in der Stadt','chill','none'),
(2463,'de','Das Tal punktet mit rosa Pfingstrosen.','Das Tal punktet mit rosa Tulpen.','rosa Pfingstrosen am Hang','Pfingstrosen in einer Vase','business','none'),
(2464,'de','Die Muster sind symmetrisch.','Die Muster sind bunt.','symmetrische Blattmuster','ein symmetrisches Gebäude','nerd','none'),
(2465,'de','Sie schwebt. Keine große Sache.','Sie schwimmt. Keine große Sache.','im blauen Himmel schweben','in einem Pool schweben','ironic','understatement'),
(2466,'de','Ihr Kleid ist aus Kristallen.','Ihr Kleid ist aus Federn.','ein Kleid aus leuchtenden Kristallen','ein Kristallglas mit Wasser','chill','none'),
(2470,'de','Das Saxofon hat einen gebogenen Schalltrichter.','Das Saxofon hat einen geraden Schalltrichter.','ein schwebendes Saxofon','ein Saxofonspieler','nerd','none'),
(2471,'de','Sie ist so eine Leseratte.','Sie ist so eine Gamerin.','eine Leseratte mit Buch','eine Leseratte mit Handy','gossip','none'),
(2472,'de','Ihre Uniform sieht echt ordentlich aus.','Ihr Mantel sieht echt ordentlich aus.','eine Schuluniform','eine Polizeiuniform','chill','none'),
(2473,'de','Der Kranz hängt an einer roten Tür.','Der Kranz hängt an einer blauen Tür.','ein Kranz an der Tür','ein Kranz auf ihrem Kopf','chill','none'),
(2474,'de','Wilder Schaum auf stürmischer See.','Wilder Schaum auf ruhiger See.','Schaum auf stürmischen Wellen','Kaffee mit Milchschaum','dramatic','none'),
(2475,'de','Sie liest barfuß.','Sie tanzt barfuß.','barfuß auf einem Tagesbett','barfuß am Strand','chill','none'),
(2477,'de','Der Wind hat seine Haare zerzaust.','Der Regen hat seine Haare zerzaust.','zerzauste braune Haare','ein unordentliches Schlafzimmer','low_iq','blaming_someone'),
(2478,'de','Der Arzt lächelt uns an.','Der Arzt schreit uns an.','ein lächelnder Cartoon-Arzt','ein Arzt im OP','chill','none'),
(2480,'de','Das Auto hat zu viele Geschenke!','Das Auto hat zu viele Hunde!','Geschenke auf dem Autodach','Geschenke unter dem Baum','dramatic','exaggeration'),
(2481,'de','Er hält einen Globus.','Er hält einen Ball.','einen Globus halten','eine Schneekugel','chill','none'),
(2482,'de','So viele Türmchen an einer Burg!','So viele Fahnen an einer Burg!','spitze Türmchen einer Burg','ein Panzerturm','gossip','exclamation'),
(2483,'de','Getrocknete Blumen liegen im Buch.','Frische Blumen liegen im Buch.','getrocknete Blumen in einem Buch','getrocknetes Obst in einer Schale','chill','none'),
(2484,'de','Die Kirche hat einen hohen Kirchturm.','Die Burg hat einen hohen Kirchturm.','ein Kirchturm im Schnee','ein Kirchturm in einer Stadt','chill','none'),
(2485,'de','Der Krähenmann sieht unheimlich aus.','Der Katzenmann sieht unheimlich aus.','eine unheimliche Gestalt mit Krähenkopf','eine unheimliche schwarze Katze','dramatic','none'),
(2486,'de','Hieroglyphen bedecken die Wand.','Blumen bedecken die Wand.','eine Wand voller Hieroglyphen','Hieroglyphen im Schulbuch','chill','none'),
(2490,'de','Schöner Hut! Ist dem Schneemann kalt?','Schöner Hut! Ist dem Hund kalt?','ein Schneemann mit Hut','einen Schneemann bauen','low_iq','guessing'),
(2492,'de','Das Dorf ist so belebt!','Das Dorf ist so ruhig!','ein belebtes verschneites Dorf','ein belebter Sommerstrand','dramatic','exclamation'),
(2493,'de','Der Bauernhof ist als Steppdecke genäht.','Der Bauernhof ist als Flagge genäht.','eine Steppdecke mit Bauernhof','eine Steppdecke auf einem Bett','nerd','none'),
(2494,'de','Viktorianische Straße. Ist das Sherlock?','Moderne Straße. Ist das Sherlock?','eine verschneite viktorianische Straße','eine viktorianische Teeparty','gossip','guessing'),
(2495,'de','Ich hab zwei Spatzen gezählt.','Ich hab vier Spatzen gezählt.','zwei Spatzen auf einem Ast','zwei Spatzen im Schnee','low_iq','none'),
(2497,'de','Der Weihnachtsmann macht Pause.','Der Weihnachtsmann nimmt ein Bad.','der Weihnachtsmann mit Geschenken','der Weihnachtsmann mit Rentieren','gossip','guessing'),
(2498,'de','Sie umarmen sich zärtlich.','Sie küssen sich zärtlich.','eine zärtliche Umarmung','ein zartes Steak','chill','none'),
(2499,'de','Zwei Teddybären kuscheln.','Zwei Teddybären kämpfen.','Teddybären im Schnee','Teddybären auf einem Bett','chill','none'),
(2500,'de','Er tippt auf einem Laptop.','Er tippt auf einem Handy.','auf einem Laptop tippen','einen Laptop tragen','chill','none'),
(2501,'de','Shiva meditiert auf einem Felsen.','Shiva meditiert in einem Boot.','Shiva mit Dreizack','Shiva mit Schwert','nerd','none'),
(2502,'de','Ein Schrein im Wald, voller Moos.','Ein Schrein in der Wüste, voller Sand.','ein bemooster Schrein im Wald','ein Schrein in einer Stadt','chill','none'),
(2504,'de','Krishna hat eine Pfauenfeder.','Krishna hat eine Adlerfeder.','Krishna mit Krone','Krishna mit Flöte','nerd','none'),
(2505,'de','Regen, ein Gewehr und null Beschwerden.','Sonne, ein Gewehr und null Beschwerden.','ein langes Gewehr mit Zielfernrohr','ein Gewehr auf dem Boden','chill','understatement'),
(2506,'de','Hier ist alles geometrisch.','Hier ist alles blau.','rosa geometrische Formen','ein Geometrietest in Mathe','chill','none'),
(2509,'de','Ein Weg führt durch Lavendel.','Ein Weg führt durch Weizen.','Reihen von lila Lavendel','eine Flasche Lavendelöl','chill','none'),
(2510,'de','Schlafenszeit für einen Jungen und eine Katze!','Schlafenszeit für einen Jungen und einen Hund!','Schlafenszeit unter der Decke','Schlafenszeit mit Vorlesebuch','dramatic','exclamation'),
(2511,'de','Um sie herum fliegen Funken.','Um sie herum fliegen Blätter.','Funken um ein Paar','ein Funke aus der Steckdose','flirt','none'),
(2512,'de','Dieses Malbuch braucht dich.','Dieses Fotobuch braucht dich.','eine Seite im Malbuch','das Cover eines Malbuchs','chill','guessing'),
(2514,'de','Sie gibt Kräuter in eine Schüssel.','Sie gibt Salz in eine Schüssel.','getrocknete Kräuter streuen','frische Kräuter hacken','chill','none'),
(2516,'de','Wir haben das Jahr 2024.','Wir haben das Jahr 2025.','das Jahr 2024 leuchtet','das Jahr 2025','chill','none'),
(2519,'de','Hast du diesen Hinterhof gesehen? Ein Flamingo!','Hast du diesen Hinterhof gesehen? Eine Schaukel!','ein belebter kleiner Hinterhof','ein Gemüsebeet im Hinterhof','gossip','exclamation'),
(2520,'de','Ein heiliges Licht von oben!','Ein heiliges Licht von unten!','ein heiliger Lichtstrahl','ein heiliger Fluss','dramatic','exclamation'),
(2522,'de','Der Klee hat vier Blätter.','Der Klee hat drei Blätter.','vierblättriger Klee','eine Kleewiese mit Kühen','nerd','none'),
(2523,'de','Der Schneefall ist heute Nacht heftig.','Der Regen ist heute Nacht heftig.','heftiger Schneefall über einem Dorf','leichter Schneefall in der Stadt','chill','none'),
(2524,'de','Er hat einen Gehstock.','Er hat einen großen Regenschirm.','sich auf einen Gehstock stützen','ein Gehstock zum Wandern','chill','none'),
(2525,'de','Mama hebt ihr Bärenbaby hoch.','Mama hebt ihr Fuchsbaby hoch.','das Junge hochheben','eine schwere Kiste heben','chill','none'),
(2526,'de','Poseidon hat zwei Speere.','Poseidon hat zwei Schwerter.','Poseidon steigt aus den Wellen','Poseidon versenkt ein Schiff','nerd','none'),
(2527,'de','Der DJ trägt eine Gasmaske. Warum?','Der DJ trägt eine Skimaske. Warum?','Gasmaske und Kopfhörer','Gasmaske und Schutzbrille','ironic','guessing'),
(2528,'de','Ein lila Zylinder? Mutige Wahl.','Ein schwarzer Zylinder? Mutige Wahl.','ein glänzender lila Zylinder','der Zylinder eines Zauberers','gossip','understatement'),
(2529,'de','Er hat ein sanftes Gesicht.','Er hat einen sanften Hund.','ein sanftes, ruhiges Gesicht','ein sanftes, ruhiges Meer','chill','none'),
(2530,'de','Kerzenschein leuchtet zwischen Rosen.','Kerzenschein leuchtet zwischen Büchern.','Kerzenschein in einer Laterne','Kerzenschein auf einer Torte','chill','none'),
(2531,'de','Sogar der Himmel funkelt für sie.','Sogar das Meer funkelt für sie.','ein funkelnder Nachthimmel','funkelndes Wasser im Glas','flirt','none'),
(2532,'de','Ihr Kleid hat graue Rüschen.','Ihr Kleid hat rote Rüschen.','ein Kleid mit grauen Rüschen','Rüschen an einem roten Hut','chill','none'),
(2533,'de','Das hintere Ende ist neblig.','Das hintere Ende ist sonnig.','eine neblige alte Straße','ein nebliger Bergsee','chill','none'),
(2536,'de','Dieser Schimpanse sieht aus wie ein ernster Biker.','Dieser Schimpanse sieht aus wie ein ernster Surfer.','ein Schimpanse auf einem Motorrad','ein Schimpanse auf einem Baum','gossip','cliche'),
(2537,'de','Das Mädchen liest eine Gutenachtgeschichte.','Der Junge liest eine Gutenachtgeschichte.','eine Gutenachtgeschichte im Bett','eine Gutenachtgeschichte im Fernsehen','chill','none'),
(2538,'de','Rotkäppchen vertraut dem Wolf.','Rotkäppchen vertraut dem Bären.','Rotkäppchens Wolf','Rotkäppchens Oma','gossip','guessing'),
(2539,'de','Künstliche Intelligenz lebt in ihrem Kopf.','Künstliche Intelligenz lebt in ihrem Auto.','ein Roboter mit künstlicher Intelligenz','eine App mit künstlicher Intelligenz','nerd','none'),
(2540,'de','Was für ein „gemütliches“ Verlies.','Was für ein „gemütlicher“ Garten.','ein dunkles Verlies mit Kerzen','ein dunkler Keller mit Wein','ironic','none'),
(2541,'de','Keiner hat dieses Treppenhaus geputzt.','Keiner hat diese Küche geputzt.','ein bröckelndes Treppenhaus aus Stein','eine bröckelnde Brücke aus Stein','ironic','understatement'),
(2543,'de','Der Elefant hat lange Stoßzähne.','Der Elefant hat kurze Stoßzähne.','zwei lange weiße Stoßzähne','ein Walross mit Stoßzähnen','chill','none'),
(2544,'de','Hanuman hat eine goldene Krone.','Hanuman hat eine silberne Krone.','Hanuman mit goldenem Stab','Hanuman mit Schwert','nerd','none'),
(2545,'de','Der Affe betet seinen Gott an.','Der Affe schläft.','auf Steinstufen einen Gott anbeten','einen Fußballstar anbeten','chill','none'),
(2546,'de','Diese Halle ist „ziemlich“ geräumig.','Diese Halle ist „ziemlich“ winzig.','eine geräumige Halle','ein geräumiges Auto','ironic','understatement'),
(2547,'de','Diese Fliegenpilze sind gigantisch!','Diese Fliegenpilze sind winzig!','riesige rote Fliegenpilze','Fliegenpilze im Korb','slang','exclamation'),
(2548,'de','So viele Fässer. Vielleicht Bier?','So viele Fahrräder. Vielleicht Bier?','gestapelte Fässer aus Holz','ein Fass kaltes Bier','low_iq','guessing'),
(2549,'de','Vater und Sohn jubeln!','Vater und Sohn weinen!','ein Vater trägt seinen Sohn','ein Vater trägt Einkäufe','dramatic','exclamation'),
(2550,'de','Sie sitzt im Schneidersitz, barfuß.','Sie sitzt im Schneidersitz, in Stiefeln.','im Schneidersitz sitzen','im Schneidersitz stehen','chill','none'),
(2551,'de','Miami-Vibes: Palmen und Neon.','Miami-Vibes: Schnee und Neon.','eine Neonstraße in Miami','ein Strand in Miami am Mittag','slang','none'),
(2552,'de','Sie ist in der virtuellen Realität.','Sie ist in einem Schwimmbad.','eine Brille für virtuelle Realität','virtuelle Realität in der Schule','chill','none'),
(2556,'de','Fakt: Das Gehirn leuchtet.','Fakt: Das Herz leuchtet.','ein leuchtendes Gehirn','ein Gehirn im Glas','nerd','none'),
(2557,'de','Moment, das Segelboot ist aus Glas?','Moment, das Segelboot ist aus Holz?','ein Segelboot aus Glas','ein Segelboot in der Flasche','low_iq','none'),
(2558,'de','Sie fliegt. Pure Freiheit!','Sie schwimmt. Pure Freiheit!','Freiheit über dem Meer','Freiheit unter dem Meer','dramatic','exclamation'),
(2559,'de','An diesem Baum wachsen Münzen!','An diesem Baum wachsen Äpfel!','Münzen fallen vom Baum','Münzen im Sparschwein','dramatic','exclamation'),
(2560,'de','Übers Wasser laufen? Ein Wunder!','Übers Feuer laufen? Ein Wunder!','ein Wunder auf dem Ozean','ein Wundermittel gegen Erkältung','dramatic','exclamation'),
(2562,'de','Regnerische Nacht, einsamer Detektiv.','Sonniger Tag, einsamer Detektiv.','ein Detektiv im Regen','ein Detektiv am Tatort','dramatic','cliche'),
(2563,'de','Ein Kaufmann prüft Getreide.','Ein Kaufmann prüft Münzen.','ein Kaufmann bei Kerzenschein','ein Kaufmann auf dem Markt','chill','none'),
(2564,'de','Diese Hortensienblüte ist blau.','Diese Hortensienblüte ist rosa.','eine blaue Hortensienblüte','eine Hortensie in einer Vase','nerd','none'),
(2567,'de','Die Heilige trägt einen weißen Schleier.','Die Heilige trägt einen roten Schleier.','eine Heilige mit Heiligenschein','ein Heiliger auf einem Pferd','chill','none'),
(2571,'de','Der Junge ist mürrisch. Mal wieder.','Das Mädchen ist mürrisch. Mal wieder.','ein mürrischer kleiner Junge','ein mürrischer alter Mann','ironic','guessing'),
(2572,'de','Die Dreiecke leuchten.','Die Kreise leuchten.','leuchtende Neon-Dreiecke','ein dreieckiges Verkehrsschild','chill','none'),
(2575,'de','Der DJ ist komplett anonym.','Der Koch ist komplett anonym.','ein anonymer DJ mit Kapuze','ein anonymer Brief','slang','none'),
(2576,'de','Er ist untröstlich in Paris.','Er ist untröstlich in Rom.','untröstlich im Regen','untröstlich im Schnee','dramatic','none'),
(2578,'de','Das Visier ist wie ein Spiegel.','Das Visier ist wie ein Fenster.','ein verspiegeltes Visier','eine Kappe mit Schirm','chill','none'),
(2579,'de','Ihre Brille ist mega seltsam.','Ihr Hut ist mega seltsam.','eine seltsame Retro-Maschine','ein seltsames altes Auto','slang','exaggeration'),
(2580,'de','Der Bogenschütze spannt seinen Bogen.','Der Bogenschütze zieht ein Schwert.','die Statue eines Bogenschützen','das Gemälde eines Bogenschützen','chill','none'),
(2581,'de','Er spielt eine Bambusflöte.','Er spielt eine Bambustrommel.','eine Bambusflöte spielen','eine Bambusflöte schnitzen','chill','none'),
(2583,'de','Sie genießt die Vibes.','Sie genießt die Pizza.','die Musik genießen','die Sonne genießen','slang','none'),
(2584,'de','Das ist eine Taufe im Fluss.','Das ist eine Taufe in der Kirche.','eine Taufe im Fluss','eine Taufe in der Kirche','chill','none'),
(2586,'de','Beste Freundschaft ever: ein Riesenroboter und ein kleines Mädchen.','Beste Freundschaft ever: ein Riesenhund und ein kleines Mädchen.','eine ungewöhnliche Freundschaft','ein Freundschaftsarmband','dramatic','exaggeration'),
(2594,'de','Der Roboter lernt etwas über sich selbst.','Der Roboter lernt etwas über Katzen.','ein Roboter lernt lesen','ein Roboter lernt fliegen','low_iq','guessing'),
(2595,'de','Jemand hat einen Flügel draußen stehen lassen.','Jemand hat einen Flügel drinnen stehen lassen.','ein Flügel im Freien','ein Flügel im Haus','ironic','guessing'),
(2600,'de','Bro, zwei Käfer chillen.','Bro, zwei Schnecken chillen.','Käfer krabbeln über Blätter','Käfer fliegen über Blumen','slang','none'),
(2601,'de','Der Mann kniet im Gebet.','Der Mann sitzt im Gebet.','auf Steinboden knien','auf einem weichen Sofa knien','chill','none'),
(2603,'de','Das Notenblatt ist handgeschrieben.','Das Notenblatt ist ausgedruckt.','ein altes handgeschriebenes Notenblatt','ein neues gedrucktes Notenblatt','nerd','none'),
(2604,'de','Ein lebloser Baum, ein grüner Mond.','Ein lebloser Baum, ein weißer Mond.','ein lebloser Baum auf Felsen','ein lebloser Baum im Topf','dramatic','none'),
(2605,'de','Er wiegt ein Baby in den Armen.','Er wiegt ein Lamm in den Armen.','ein Baby in den Armen wiegen','ein Handy in den Armen wiegen','chill','none'),
(2606,'de','Ihr Kopf ist pures Uhrwerk.','Ihr Kopf ist pures Glas.','ein Kopf voller Uhrwerk','eine Spielzeugmaus mit Uhrwerk','nerd','exaggeration'),
(2607,'de','Die Katzen tragen elegante Mäntel.','Die Hunde tragen elegante Mäntel.','Katzen tragen lange Mäntel','Katzen tragen Halsbänder','business','none'),
(2611,'de','Sein Gürtel hat eine Schnalle aus Metall.','Seine Tasche hat eine Schnalle aus Metall.','eine Gürtelschnalle aus Metall','einen Sicherheitsgurt anlegen','chill','none'),
(2612,'de','Zwei Knospen sind noch nicht aufgegangen.','Zwei Knospen sind schon aufgegangen.','zwei geschlossene rote Knospen','zwei offene rote Knospen','nerd','none'),
(2614,'de','Zwei Jungen sind in der Nähe eines Minaretts.','Zwei Mädchen sind in der Nähe eines Minaretts.','auf ein Minarett zugehen','auf ein Minarett klettern','chill','none'),
(2618,'de','Die Handschrift ist in Schreibschrift.','Die Handschrift ist in Druckschrift.','eine verblasste Handschrift','eine ordentliche Druckschrift','nerd','none'),
(2621,'de','Der Mast hat viel Takelage.','Der Mast hat viele Flaggen.','ein hoher Mast mit Takelage','ein Mast mit Piratenflaggen','nerd','none'),
(2622,'de','Eine winzige Freiheitsstatue!','Ein winziger Eiffelturm!','eine Mini-Freiheitsstatue','ein Freiheitsstatuen-Kostüm','dramatic','exclamation'),
(2623,'de','Efeu bedeckt das Bücherregal.','Schnee bedeckt das Bücherregal.','ein Bücherregal voller Efeu','eine Burg voller Efeu','chill','none'),
(2625,'de','Der Ingenieur träumt von Kränen.','Der Ingenieur träumt von Pferden.','der Schutzhelm eines Ingenieurs','ein Ingenieur am Computer','nerd','guessing'),
(2626,'de','Eine Stadt lebt in seinem kahlen Kopf.','Ein Bauernhof lebt in seinem kahlen Kopf.','ein kahler Kopf im Profil','ein kahler Kopf mit Brille','chill','none'),
(2629,'de','Ihr Haar ist zu zwei Zöpfen gebunden.','Ihr Haar ist zu zwei Dutts gebunden.','zwei lange geflochtene Zöpfe','zwei kurze lockige Zöpfe','chill','none'),
(2631,'de','Ihre Schutzbrille hat runde Linsen.','Ihre Schutzbrille hat keine Linsen.','runde getönte Linsen','eine Linse an einer Kamera','chill','none'),
(2633,'de','Der Baum ist eine Disco. Schau dir die Strahlen an!','Der Baum ist eine Disco. Schau dir die Vögel an!','Strahlen aus buntem Licht','Holzbalken eines Dachs','low_iq','exaggeration'),
(2634,'de','Jede Flasche hat einen Korken.','Jede Flasche hat einen Strohhalm.','mit Korken verschlossene Flaschen','eine Korkpinnwand mit Zetteln','chill','none'),
(2635,'de','Die Magnolie ist cremeweiß.','Die Magnolie ist knallgelb.','eine offene Magnolienblüte','ein Magnolienbaum','chill','none'),
(2641,'de','Strahlen erfüllen den Himmel!','Strahlen erfüllen den Raum!','goldene Lichtstrahlen','Strahlen durch ein Fenster','dramatic','exclamation'),
(2648,'de','Diese Ameise ist größer als ich!','Diese Biene ist größer als ich!','eine riesige schwarze Ameise','ein riesiger Ameisenhaufen','low_iq','exaggeration'),
(2649,'de','Diese Schutzbrille ist riesig!','Diese Ohrringe sind riesig!','eine leuchtende Schutzbrille','eine Schwimmbrille','dramatic','exclamation'),
(2651,'de','Das rote Dach hat weiße Punkte.','Das rote Dach hat schwarze Punkte.','eine Kappe mit weißen Punkten','ein Hund mit weißen Punkten','chill','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
