begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(2652,'de','Alles ist grau, nur ihr Mantel nicht!','Alles ist rot, nur ihr Mantel nicht!','graue Mäntel im Regen','graue Mäntel im Schnee','dramatic','exclamation'),
(2654,'de','Riemen fest, bereit für den Mond.','Riemen fest, bereit fürs Meer.','breite weiße Riemen','ein Uhrenriemen aus Leder','chill','guessing'),
(2656,'de','Zwei rote Busse. Sehr London.','Zwei rote Straßenbahnen. Sehr London.','ein roter Doppeldeckerbus','eine rote Doppeldecker-Straßenbahn','slang','cliche'),
(2657,'de','Der Vogel ist Teil einer Collage.','Die Katze ist Teil einer Collage.','ein Vogel in einer Collage','eine Collage aus alten Fotos','chill','none'),
(2658,'de','Er reckt die Faust!','Er reckt das Schwert!','eine erhobene Faust','eine Faust voller Münzen','dramatic','exclamation'),
(2661,'de','Die Fliesen bilden ein Schachbrett.','Die Fliesen bilden einen Regenbogen.','schwarz-weiße Bodenfliesen','blau-weiße Wandfliesen','nerd','none'),
(2663,'de','Sein Schatten ist so lang!','Sein Schatten ist so kurz!','der lange Schatten eines Cowboys','ein Schatten an der Wand','dramatic','exclamation'),
(2664,'de','Da ertrinkt jemand für einen neuen Follower.','Da schwimmt jemand für einen neuen Follower.','im Ozean ertrinken','in Hausaufgaben ertrinken','ironic','exaggeration'),
(2666,'de','Blumentöpfe säumen die Stufen.','Kerzen säumen die Stufen.','Blumentöpfe auf Steinstufen','Blumentöpfe auf der Fensterbank','chill','none'),
(2669,'de','Eine Million Teekannen, ich schwör''s.','Eine Million Lampen, ich schwör''s.','Regale voller Porzellan-Teekannen','eine Teekanne auf dem Herd','gossip','exaggeration'),
(2670,'de','Der Tisch hat eine Schublade.','Der Tisch hat drei Schubladen.','eine Schublade mit Knauf','eine Schublade voller Socken','chill','none'),
(2673,'de','Er sitzt im Käfig, der Vogel ist frei.','Der Vogel sitzt im Käfig, er ist frei.','im Käfig sitzen','einen Käfig putzen','ironic','none'),
(2675,'de','Die Katze hat eine Pfote auf dem Buch, wie ein Professor.','Die Katze hat eine Pfote auf der Tasse, wie ein Professor.','eine Pfote auf dem Buch','eine Pfote auf dem Bleistift','nerd','exaggeration'),
(2678,'de','Papier frisst den Laptop.','Papier frisst das Bett.','Stapel von Papier','ein Papierflieger','dramatic','exaggeration'),
(2679,'de','Er ist in riesiger Eile!','Er ist überhaupt nicht in Eile!','in Eile rennen','in Eile zum Essen','dramatic','exclamation'),
(2682,'de','Der Tiger greift an!','Der Löwe greift an!','ein angreifender Tiger','ein angegriffener Tiger','dramatic','exclamation'),
(2683,'de','Ihre Gesichtsbemalung ist ein Mandala.','Ihre Gesichtsbemalung ist eine Spinne.','ein Mandala als Gesichtsbemalung','Gesichtsbemalung bei einem Clown','nerd','none'),
(2684,'de','Diese Masken sind für den Karneval.','Diese Masken sind für die OP.','Augenmasken für den Karneval','ein Karnevalsumzug','chill','guessing'),
(2685,'de','Die Masken für den Maskenball sind golden.','Die Masken für den Maskenball sind rot.','goldene Masken für den Maskenball','eine Einladung zum Maskenball','business','none'),
(2686,'de','Die Brünette wirkt so entspannt.','Die Blondine wirkt so entspannt.','eine Brünette in Blau','eine Brünette in Rot','flirt','none'),
(2687,'de','Villa mit Schwimmbecken. Sehr exklusiv.','Villa mit Tennisplatz. Sehr exklusiv.','ein türkises Schwimmbecken','ein Schwimmbecken in der Halle','business','none'),
(2688,'de','Seine Dreadlocks sind sehr lang.','Seine Dreadlocks sind sehr kurz.','lange Dreadlocks bis über die Brust','kurze Dreadlocks unter einer Mütze','chill','none'),
(2690,'de','Ihre Krone ist voller Diamanten.','Ihre Krone ist voller Federn.','eine Krone aus Diamanten','ein Diamantring','gossip','exaggeration'),
(2691,'de','Sie trägt einen Trenchcoat.','Sie trägt eine Skijacke.','ein beiger Trenchcoat','ein nasser Trenchcoat','chill','none'),
(2693,'de','Ein Baum wächst aus einem Buch!','Ein Baum wächst aus einer Tasse!','aus einem Buch wachsen','aus einem Topf wachsen','dramatic','exclamation'),
(2694,'de','Sie denkt angestrengt nach.','Sie lacht herzhaft.','im Dunkeln denken','ans Abendessen denken','chill','none'),
(2698,'de','Offene Fensterläden, heißer Kaffee, perfekt.','Offene Fensterläden, kaltes Bier, perfekt.','grüne, aufgeklappte Fensterläden','nachts geschlossene Fensterläden','chill','cliche'),
(2702,'de','Natur-Paket: Wasserfall inklusive.','Natur-Paket: Schloss inklusive.','Natur mit Wasserfall','Natur mit viel befahrener Straße','business','none'),
(2703,'de','Ein riesiger Obelisk im Schnee.','Ein riesiger Obelisk in der Wüste.','ein schwarzer Obelisk im Schnee','ein Obelisk auf einem Platz','dramatic','none'),
(2704,'de','Nur Schutt und Nebel bleiben.','Nur Schnee und Nebel bleiben.','Schutt im Nebel','Schutt mit dem Bagger räumen','dramatic','none'),
(2708,'de','Der Affengott sieht stark aus.','Der Affengott sieht winzig aus.','starke Arme und Brust','ein starker Kaffee','chill','none'),
(2709,'de','Er trägt eine Girlande aus Ringelblumen.','Er trägt eine Girlande aus Rosen.','eine Girlande aus Ringelblumen','Ringelblumen im Topf','chill','none'),
(2711,'de','Seerosenblätter treiben um sie herum.','Boote treiben um sie herum.','Seerosenblätter auf einem Teich','Seerosenblätter mit Fröschen','chill','none'),
(2712,'de','Es ist halb Gesicht, halb Anatomie.','Es ist halb Gesicht, halb Blumen.','eine Anatomiezeichnung','eine Anatomieprüfung','nerd','none'),
(2714,'de','Zitronen, Meer und ein Strohhut.','Orangen, Meer und ein Strohhut.','ein breiter Strohhut','der Strohhut einer Vogelscheuche','chill','none'),
(2716,'de','Big Ben hinter den Bäumen, nice.','Big Ben hinter den Schiffen, nice.','Blick auf Big Ben','Big Ben um Mitternacht','slang','none'),
(2717,'de','Das Parlament liegt an der Themse.','Das Parlament liegt an der Seine.','das Parlament in London','ein Parlament am Meer','nerd','none'),
(2718,'de','Das Klavier ist halb Bauplan.','Die Harfe ist halb Bauplan.','ein Bauplan für ein Klavier','ein Bauplan für ein Haus','nerd','none'),
(2722,'de','Die Spirale ist unter dem Cowboy.','Die Spirale ist über dem Cowboy.','eine Spirale aus Sternen','eine Wendeltreppe','chill','none'),
(2723,'de','Er ist total wütend!','Sie ist total wütend!','ein wütender Krieger','ein wütender Drache','dramatic','exclamation'),
(2724,'de','Er herrscht über diesen nebligen Dschungel.','Er herrscht über diese neblige Wüste.','ein nebliger grüner Dschungel','ein Dschungel voller Tiger','dramatic','none'),
(2725,'de','Er kauert auf einem Felsen.','Er kauert auf einem Baum.','hoch oben auf einem Felsen kauern','tief in einer Höhle kauern','chill','none'),
(2726,'de','Er trägt zwei Ketten aus Perlen.','Er trägt zwei Ketten aus Glöckchen.','Ketten aus orangen Perlen','Perlen an einer Schnur zählen','chill','none'),
(2728,'de','Ein Hase kuschelt mit einem Fuchs.','Ein Hase kuschelt mit einer Katze.','mit einem Fuchsbaby kuscheln','mit einem Hasenbaby kuscheln','chill','none'),
(2729,'de','Ihre Kristallkugel leuchtet.','Ihre Kristallkugel ist kaputt.','eine Kristallkugel berühren','eine kaputte Kristallkugel','chill','none'),
(2731,'de','Fakt: Die Pupille ist schwarz.','Fakt: Die Pupille ist weiß.','eine schwarze Pupille','ein Schüler in der Klasse','nerd','none'),
(2732,'de','Der Enkel sitzt auf seinem Schoß.','Der Enkel sitzt auf einem Stuhl.','ein Enkel auf Opas Schoß','ein Enkel am Strand','chill','none'),
(2733,'de','Die Armee stürmt los!','Die Armee zieht sich zurück!','eine Armee zu Pferd','eine Armee zu Fuß','dramatic','exclamation'),
(2734,'de','Die Katze hat eine winzige rosa Nase.','Die Katze hat eine winzige schwarze Nase.','eine kleine rosa Nase','eine kleine schwarze Nase','chill','none'),
(2735,'de','Die Explosion macht so viel Spaß!','Die Flut macht so viel Spaß!','eine Explosion im Labor','eine Explosion von Farben','dramatic','exclamation'),
(2736,'de','Der Astronom ist ein alter Mann.','Der Astronom ist ein junger Mann.','ein alter Astronom','ein Astronom am Teleskop','chill','none'),
(2737,'de','Das ist ein Schwarzes Loch im All.','Das ist ein schwarzer Mond im All.','ein Schwarzes Loch im All','ein Schwarzes Loch aus Schulden','nerd','none'),
(2738,'de','Dieser exotische Vogel trägt Kopfhörer, um dich zu ignorieren.','Dieser exotische Vogel trägt eine Sonnenbrille, um dich zu ignorieren.','ein exotischer Vogel mit Kopfhörern','exotische Vögel im Käfig','ironic','guessing'),
(2740,'de','Sein Schnurrbart ist weiß wie Schnee.','Sein Schnurrbart ist schwarz wie Kohle.','ein dicker weißer Schnurrbart','ein dünner schwarzer Schnurrbart','dramatic','cliche'),
(2741,'de','Der Programmierer codet nachts.','Der Programmierer codet mittags.','ein Programmierer beim Coden','ein Programmierer im Fitnessstudio','nerd','cliche'),
(2742,'de','Er konzentriert sich auf Code.','Er konzentriert sich auf ein Buch.','sich auf einen Bildschirm konzentrieren','sich auf ein Spiel konzentrieren','nerd','none'),
(2743,'de','Steile Felswände? Nope.','Steile Sandwände? Nope.','steile Felswände','eine steile Straße in der Stadt','slang','guessing'),
(2744,'de','Fakt: Pfauen haben eine Federhaube.','Fakt: Pfauen haben keine Federhaube.','eine zarte Federhaube','eine Federhaube auf einem Helm','nerd','cliche'),
(2745,'de','Alte Steine füllen den Innenhof.','Alte Autos füllen den Innenhof.','ein gepflasterter Innenhof','ein Innenhof-Café mit Tischen','chill','none'),
(2747,'de','Das pummelige Kleinkind hat eine Keule.','Das pummelige Kleinkind hat einen Bogen.','ein pummeliger Babygott','ein pummeliger Welpe','chill','none'),
(2749,'de','Sie sitzt stilvoll an der Bar.','Sie sitzt stilvoll im Auto.','an einer Bar sitzen','ein Schokoriegel','flirt','none'),
(2750,'de','Die Zimmerpflanze steht auf Büchern.','Die Zimmerpflanze steht auf einem Fernseher.','eine Zimmerpflanze im Regal','eine Zimmerpflanze auf dem Boden','chill','none'),
(2751,'de','Diese Pflanze ist mega stachelig.','Diese Pflanze ist mega weich.','eine stachelige Topfpflanze','eine stachelige Kaktuskugel','slang','none'),
(2752,'de','Die Maus spielt für Deutschland!','Die Katze spielt für Deutschland!','ein Fan von Deutschland','eine Karte von Deutschland','low_iq','guessing'),
(2753,'de','Dieses Sparschwein ist reich!','Dieses Sparschwein ist pleite!','ein großes rosa Sparschwein','ein kaputtes Sparschwein','slang','exaggeration'),
(2754,'de','So viel Dampf im Sonnenuntergang!','So viel Schnee im Sonnenuntergang!','weißer Dampf aus dem Schlot','weißer Rauch aus dem Kamin','dramatic','exclamation'),
(2757,'de','Ein Klavier voller Inspiration.','Eine Küche voller Inspiration.','ein Funke Inspiration','Inspiration aus einem Buch','chill','none'),
(2758,'de','Eine Büste aus Stein in der Wüste.','Eine Büste aus Stein im Dschungel.','eine riesige Steinbüste','eine Büste im Museum','nerd','none'),
(2759,'de','Er steht da wie ein echter Held.','Er sitzt da wie ein echter Held.','ein Held auf einem Felsen','ein Held auf einem Pferd','dramatic','cliche'),
(2762,'de','Eine Gestalt läuft durch den Weizen.','Eine Gestalt läuft durch den Schnee.','ein Feld mit reifem Weizen','ein Laib Weizenbrot','chill','none'),
(2765,'de','Das Baby lächelt.','Das Baby weint.','mit einer Flöte lächeln','seine Mutter anlächeln','chill','none'),
(2766,'de','Eine Kobra ist an seiner Schulter!','Ein Tiger ist an seiner Schulter!','eine aufgerichtete Kobra','eine Kobra im Korb','dramatic','exclamation'),
(2770,'de','Nummer 3 schwitzt ohne Ende!','Nummer 7 schwitzt ohne Ende!','nach dem Laufen schwitzen','in der Sauna schwitzen','dramatic','exclamation'),
(2771,'de','Die Maus isst Eis!','Die Maus isst Käse!','eine Eiswaffel essen','ein Käsesandwich essen','dramatic','exclamation'),
(2774,'de','Die Architektur ist gotisch.','Die Architektur ist modern.','gotische Kathedralen-Architektur','moderne Glasarchitektur','nerd','none'),
(2776,'de','Sie hält die Fackel hoch in die Luft.','Sie hält die Fahne hoch in die Luft.','eine hochgehaltene brennende Fackel','eine Fackel in einer Höhle','chill','none'),
(2777,'de','Ihr Kopftuch hat eine große Brosche.','Ihr Kopftuch hat eine große Blume.','eine große Silberbrosche','eine Brosche am Mantel','chill','none'),
(2779,'de','Ihre Iris ist blaugrün.','Ihre Iris ist dunkelbraun.','eine blaugrüne Iris','eine lila Irisblüte','chill','none'),
(2781,'de','Sie trägt so viel Zeug!','Er trägt so viel Zeug!','eine schwere Tasche tragen','eine schwere Kiste tragen','dramatic','exclamation'),
(2782,'de','Dieser Kupferstich besteht nur aus Linien.','Dieser Kupferstich besteht nur aus Punkten.','ein feiner Kupferstich','eine Gravur auf einem Ring','nerd','none'),
(2788,'de','Sie pustet Blütenblätter.','Sie pustet Kerzen aus.','Blütenblätter und Schmetterlinge pusten','Kerzen auspusten','chill','none'),
(2791,'de','Ihr Kopf ist durchsichtig. Cool!','Ihr Kopf ist golden. Cool!','eine durchsichtige Schädelkuppel','eine durchsichtige Regenjacke','slang','exclamation'),
(2793,'de','Zwei Geschäftsmänner stehen ganz oben.','Fünf Geschäftsmänner stehen ganz oben.','ein Geschäftsmann auf der Treppe','ein Geschäftsmann im Aufzug','business','none'),
(2795,'de','Er klettert kopfüber!','Er schläft kopfüber!','unter einer Klippe klettern','eine Leiter hochklettern','dramatic','exclamation'),
(2800,'de','Darf ich die große Seifenblase platzen lassen?','Darf ich den großen Luftballon platzen lassen?','eine Seifenblase am Himmel','eine Seifenblase im Glas','low_iq','guessing'),
(2801,'de','Seine Scheinwerfer leuchten orange.','Seine Scheinwerfer leuchten blau.','orange Scheinwerfer im Schnee','Scheinwerfer an einem verschneiten Auto','chill','none'),
(2803,'de','Sein Gesicht sieht psychedelisch aus!','Sein Gesicht sieht grau und öde aus!','ein psychedelisches Porträt','ein psychedelisches Auto','dramatic','exclamation'),
(2805,'de','Er zeichnet gleich ein Meisterwerk.','Sie zeichnet gleich ein Meisterwerk.','ein Bild zeichnen','die Vorhänge zuziehen','ironic','guessing'),
(2806,'de','Ein Kleinkind mit goldenem Turban.','Ein Kleinkind mit goldenem Helm.','ein Kleinkind mit Feder','ein Kleinkind im Buggy','chill','none'),
(2808,'de','Die Geschäftsfrau lächelt.','Die Geschäftsfrau weint.','eine Geschäftsfrau an ihrem Auto','eine Geschäftsfrau im Zug','business','none'),
(2809,'de','Sie hält eine kleine Teetasse.','Sie hält eine kleine Teekanne.','eine Teetasse in beiden Händen','eine Teetasse auf einer Untertasse','chill','none'),
(2810,'de','Zwei Kaffees an einem Arbeitsplatz!','Zwei Laptops an einem Arbeitsplatz!','ein gemütlicher Arbeitsplatz','ein Arbeitsplatz im Großraumbüro','ironic','exclamation'),
(2811,'de','Er berührt ein Hologramm-Auto.','Er berührt ein Spielzeugauto.','ein Hologramm eines Autos','ein Hologramm auf einer Karte','nerd','none'),
(2812,'de','Eine Drohne ist auf der großen Leinwand.','Ein Flugzeug ist auf der großen Leinwand.','eine Drohne auf dem Bildschirm','eine Drohne über einem Feld','chill','none'),
(2814,'de','Er lehnt sich in den Wolken zurück.','Er lehnt sich im Meer zurück.','sich auf einem geschnitzten Sitz zurücklehnen','sich auf dem Sofa zurücklehnen','chill','none'),
(2815,'de','Er ist bereit für die Schlacht.','Er ist bereit fürs Bett.','bereit für die Schlacht','eine Schlacht auf See','chill','none'),
(2817,'de','Die Gießkanne hat Blumen.','Die Teekanne hat Blumen.','eine Gießkanne mit Blumen','eine Gießkanne voll Wasser','chill','none'),
(2818,'de','Es regnet Geld!','Es regnet Münzen!','ein Tisch voller Geld','ein Tisch voller Essen','dramatic','exaggeration'),
(2819,'de','Ihre Ringe sind leuchtend golden.','Ihre Ringe sind leuchtend grün.','leuchtende goldene Ringe','leuchtende rote Augen','chill','none'),
(2820,'de','Sie teilen sich ein Buch.','Sie teilen sich eine Pizza.','ein Buch teilen','einen Tisch teilen','chill','none'),
(2823,'de','Null Wind: Das Wasser ist still.','Null Wind: Das Wasser ist wellig.','ein Boot auf stillem Wasser','eine stille Nacht in der Stadt','nerd','none'),
(2824,'de','Der Nachtclub ist jetzt voll.','Der Nachtclub ist jetzt leer.','ein Neon-Nachtclub','ein Türsteher vom Nachtclub','gossip','none'),
(2825,'de','Er ist von Büchern umgeben!','Er ist von Spielzeug umgeben!','von Wänden aus Büchern umgeben','von Wänden aus Spielzeug umgeben','dramatic','exclamation'),
(2826,'de','Das gelbe Band steht ihr.','Das rote Band steht ihr.','ein gelbes Haarband','ein gelbes Geschenkband','flirt','none'),
(2827,'de','Er ist eingedöst. Kunst ist anstrengend.','Er ist eingedöst. Mathe ist anstrengend.','am Schreibtisch eindösen','auf dem Sofa eindösen','gossip','bad_excuse'),
(2829,'de','Sie stöbert in einer Bibliothek.','Sie stöbert in einem Laden.','in Bibliotheksregalen stöbern','im Internet stöbern','chill','none'),
(2831,'de','Sogar die Sonne ist fröhlich!','Sogar der Regen ist fröhlich!','eine fröhlich lächelnde Sonne','ein fröhlicher Regentag','low_iq','exclamation'),
(2833,'de','Burnout: Sein Kopf dampft.','Burnout: Sein Tee dampft.','Burnout am Schreibtisch','Burnout im Fitnessstudio','dramatic','exaggeration'),
(2837,'de','Sie ist in einer Buchhandlung.','Sie ist in einem Spielzeugladen.','eine volle Buchhandlung','die Café-Theke einer Buchhandlung','chill','none'),
(2838,'de','Regenbogen-Glitzer auf ihren Wangen.','Schwarzer Glitzer auf ihren Wangen.','Regenbogen-Glitzer auf den Wangen','Glitzer auf einer Karte','chill','none'),
(2840,'de','Eine ganze Stadt auf einer Schriftrolle!','Ein ganzer Wald auf einer Schriftrolle!','eine Stadt auf einer Schriftrolle','eine Schriftrolle in einer Flasche','gossip','exclamation'),
(2847,'de','Lungenflügel wie Bäume. Sehr poetisch.','Lungenflügel wie Sterne. Sehr poetisch.','Lungenflügel wie Äste','Lungenflügel auf dem Röntgenbild','ironic','none'),
(2850,'de','Seine Trommeln sind riesig!','Seine Gitarre ist riesig!','ein großes Set Trommeln','eine Öltrommel','slang','exclamation'),
(2856,'de','So viele Klimaanlagen!','So viele Blumenkästen!','Klimaanlagen an der Wand','eine Klimaanlage im Auto','dramatic','exclamation'),
(2859,'de','Sie meditiert in einer Höhle.','Sie meditiert am Strand.','in einer Höhle meditieren','auf einem Berg meditieren','chill','none'),
(2861,'de','Rate mal, wer ein Buch liest?','Rate mal, wer eine Karte liest?','auf dem Sofa lesen','im Bett lesen','gossip','none'),
(2867,'de','Die Kugel ist voller Funken!','Die Kugel ist voller Wasser!','eine riesige Glaskugel','eine Kugel aus Stein','dramatic','exclamation'),
(2877,'de','Er klettert am Seil hoch.','Er klettert eine Leiter hoch.','an einem Seil klettern','auf einen Baum klettern','chill','none'),
(2887,'de','Das Feuerwerk begrüßt 2025!','Das Feuerwerk begrüßt 2024!','Feuerwerk über den Dächern','Feuerwerk über dem Meer','dramatic','exclamation'),
(2890,'de','Heute keine Rentiere, also fährt der Weihnachtsmann Ski.','Heute keine Rentiere, also geht der Weihnachtsmann zu Fuß.','einen Hang hinunter Ski fahren','über einen See Ski fahren','ironic','guessing'),
(2892,'de','Er hält eine Wunderkerze.','Er hält eine Kerze.','eine brennende Wunderkerze halten','eine Wunderkerze auf einer Torte','chill','none'),
(2894,'de','Der Mann trägt ein Lamm.','Der Mann trägt einen Hund.','ein weißes Lamm tragen','ein Lamm mit seiner Mutter','chill','none'),
(2897,'de','Wo ist der Weihnachtsmann? Er hat seinen Schlitten stehen lassen.','Wo ist der Weihnachtsmann? Er hat sein Auto stehen lassen.','ein Schlitten voller Geschenke','ein Schlitten mit Rentieren','gossip','guessing'),
(2898,'de','Eine Sphinx bewacht die Wüste.','Ein Kamel bewacht die Wüste.','Pyramiden in der Wüste','ein Roadtrip durch die Wüste','dramatic','none'),
(2900,'de','Ein riesiger Wolf steht ihr gegenüber.','Ein riesiger Bär steht ihr gegenüber.','ein riesiger leuchtender Wolf','nachts heulende Wölfe','chill','none'),
(2906,'de','Sie trägt eine große Kiste.','Sie trägt eine große Pflanze.','eine große Kiste tragen','ein Baby tragen','chill','none'),
(2908,'de','Ein riesiges Buch schwebt.','Ein riesiger Ballon schwebt.','ein riesiges schwebendes Buch','ein Riese aus dem Märchen','chill','none'),
(2909,'de','Der Wissenschaftler liebt Lila.','Der Wissenschaftler liebt Grün.','das Labor eines verrückten Wissenschaftlers','ein Wissenschaftler im Fernsehen','gossip','guessing'),
(2910,'de','So viele Bücher! Das Bücherregal ist voll!','So viele Spielsachen! Das Bücherregal ist voll!','ein buntes Bücherregal','ein leeres Bücherregal','low_iq','exclamation'),
(2914,'de','Jemand dehnt sich ganz nach oben.','Jemand springt ganz nach oben.','die Arme nach oben dehnen','sich vor dem Laufen dehnen','chill','none'),
(2915,'de','Das Team pflanzt Blumen.','Das Team pflückt Blumen.','orange Blumen pflanzen','orange Blumen pflücken','business','none'),
(2925,'de','Der Schnabel ist lang. So lang.','Der Schnabel ist kurz. So kurz.','ein langer spitzer Schnabel','ein kurzer gebogener Schnabel','low_iq','exaggeration'),
(2928,'de','Ein Raumschiff fliegt über sie hinweg.','Ein großer Drache fliegt über sie hinweg.','ein riesiges blasses Raumschiff','ein landendes Raumschiff','chill','none'),
(2937,'de','Der Astronaut schwebt.','Der Astronaut rennt.','ein Astronaut im tiefen All','ein Astronaut auf dem Mond','chill','none'),
(2942,'de','Da ist ein orangefarbener Planet.','Da ist ein grüner Planet.','ein leuchtend orangefarbener Planet','ein Planet mit Ringen','nerd','none'),
(2949,'de','Ein Astronaut sieht eine Sonnenfinsternis.','Ein Astronaut sieht einen Regenbogen.','eine Sonnenfinsternis beobachten','eine Mondfinsternis','nerd','none'),
(2950,'de','Schmetterlinge fliegen aus dem Radio!','Bienen fliegen aus dem Radio!','ein altes Radio','ein Radiosender','dramatic','exclamation'),
(2951,'de','Zwei Hände berühren sich fast!','Zwei Füße berühren sich fast!','zwei Hände, die sich fast berühren','zwei Hände beim Händeschütteln','dramatic','exclamation'),
(2952,'de','Gelber Umhang heißt Superheld. Easy.','Roter Umhang heißt Superheld. Easy.','ein Superheld in schwarzer Rüstung','ein Superheld mit Maske','low_iq','none'),
(2964,'de','Sie atmet mit geschlossenen Augen.','Sie schläft mit geschlossenen Augen.','im Dunkeln atmen','gegen eine Fensterscheibe atmen','chill','none'),
(2967,'de','Dieser Tierarzt hat einen glücklichen Patienten!','Dieser Tierarzt hat ein glückliches Kätzchen!','ein Tierarzt mit einer Bulldogge','ein Tierarzt mit einem Kätzchen','slang','exclamation'),
(2971,'de','So viele Haftnotizen. So „organisiert“.','So viele Fotos. So „organisiert“.','Haftnotizen am Fenster','Haftnotizen am Kühlschrank','ironic','exaggeration'),
(2973,'de','Jemand hatte gerade eine Idee!','Jemand hatte gerade einen Kaffee!','eine geniale neue Idee','eine Idee fürs Abendessen','slang','exclamation'),
(2980,'de','Er benutzt ein riesiges Teleskop.','Er benutzt eine riesige Kamera.','ein riesiges Messingteleskop','ein kleines Plastikteleskop','nerd','none'),
(2981,'de','Dieser Tornado besteht aus Code.','Dieser Tornado besteht aus Staub.','ein Tornado aus Code','ein Tornado über einem Bauernhof','nerd','none'),
(2987,'de','Der goldene Roboter ist „bescheiden“.','Der silberne Roboter ist „bescheiden“.','ein Roboter in goldener Rüstung','ein goldener Ehering','ironic','understatement'),
(3003,'de','Die Menschenmenge hat die Hände oben.','Die Menschenmenge hat die Hände unten.','eine Menschenmenge mit erhobenen Händen','eine Menschenmenge im Stadion','chill','none'),
(3019,'de','Das Mädchen lächelt uns an.','Der Junge lächelt uns an.','in die Kamera lächeln','einen Hund anlächeln','chill','none'),
(3022,'de','Schach ist ein kleines bisschen schwierig.','Poker ist ein kleines bisschen schwierig.','eine Partie Schach','ein Schachclub','ironic','understatement'),
(3024,'de','Sie halten Händchen.','Sie klatschen in die Hände.','von hinten Händchen halten','am Tisch Händchen halten','flirt','none'),
(3027,'de','Er heilt den alten Mann.','Er heilt den jungen Mann.','die Augen eines alten Mannes heilen','das Bein eines jungen Mannes heilen','chill','none'),
(3034,'de','Sie lernt allein.','Sie schläft allein.','im Unterricht lernen','in der Bibliothek lernen','chill','none'),
(3035,'de','Die Schüler schreiben einen Test.','Die Schüler spielen ein Spiel.','einen Test schreiben','eine Führerscheinprüfung','chill','none'),
(3040,'de','Dieser Stapel Arbeit ist krass!','Dieser Stapel Essen ist krass!','ein Stapel Papiere','ein Stapel Klamotten','slang','exclamation'),
(3041,'de','Er sieht an seinem Schreibtisch besorgt aus.','Er sieht in seinem Bett besorgt aus.','ein besorgter Junge bei der Arbeit','besorgt wegen des Wetters','chill','none'),
(3049,'de','Er hat eine große Frage.','Er hat ein großes Sandwich.','eine Frage in einer Sprechblase','eine Frage im Test','chill','none'),
(3052,'de','Er denkt nach, statt zu arbeiten.','Er schläft, statt zu arbeiten.','an einem Schultisch denken','an einem Küchentisch denken','slang','guessing'),
(3057,'de','Er geht durch den Park.','Er rennt durch den Park.','einen Weg entlanggehen','einen Strand entlanggehen','chill','none'),
(3059,'de','Nordlichter sind ein Vibe.','Das Feuerwerk ist ein Vibe.','Nordlichter über Bergen','Nordlichter über einer Stadt','slang','none'),
(3062,'de','Der DJ mixt Platten.','Der DJ signiert Platten.','ein DJ an den Plattentellern','ein DJ im Radio','slang','none'),
(3063,'de','Sie hört Musik.','Sie hört auf dem Sofa Musik.','mit Kopfhörern Musik hören','einem Lehrer zuhören','chill','none'),
(3064,'de','Sie öffnet die Vorhänge!','Sie schließt die Vorhänge!','die Vorhänge öffnen','die Haustür öffnen','dramatic','exclamation'),
(3070,'de','Über den Händen ist ein Baum.','Über den Händen ist eine Katze.','zwei offene, hohle Hände','zwei Hände in den Hosentaschen','chill','none'),
(3072,'de','Moment. Katzen können Laub harken?','Moment. Hunde können Laub harken?','Herbstlaub harken','den Sand glatt harken','low_iq','none'),
(3078,'de','Sie brät Eier wie ein Profi.','Sie brät Fisch wie ein Profi.','Eier in der Pfanne braten','Eier im Topf kochen','slang','cliche'),
(3079,'de','Er trinkt aus einem Becher.','Er trinkt aus einer Flasche.','aus einem Becher trinken','aus der Flasche trinken','chill','none'),
(3082,'de','Die Ballerina steht auf einer Zehenspitze!','Die Ballerina steht auf beiden Füßen!','eine Ballerina auf einer Zehenspitze','eine Ballerina auf der Bühne','dramatic','exclamation'),
(3087,'de','Sie schüttet Tierfutter ein.','Sie schüttet Orangensaft ein.','Tierfutter einschütten','heißen Tee eingießen','business','none'),
(3089,'de','Sie hat Kekse gebacken. Für mich?','Sie hat einen Kuchen gebacken. Für mich?','gebackene Schokokekse','gebackene Brötchen','flirt','guessing'),
(3090,'de','Sie trägt ihre Lebensmittel nach Hause.','Sie trägt ihre Wäsche nach Hause.','eine Tüte mit Lebensmitteln','Lebensmittel auf dem Fahrrad','chill','none'),
(3098,'de','Zwei Burger beim Barbecue.','Zwei Steaks beim Barbecue.','ein Barbecue im Garten','ein Barbecue am Strand','chill','none'),
(3101,'de','Sie springt so hoch!','Sie schwimmt so schnell!','über ein Seil springen','in einen See springen','slang','exclamation'),
(3118,'de','Er schwingt seine Axt!','Er schwingt seinen Schläger!','eine Axt im Baum','eine Axt an der Wand','dramatic','exclamation'),
(3119,'de','Die Fee hat goldene Flügel.','Die Fee hat schwarze Flügel.','eine Fee mit goldenen Flügeln','eine Fee mit Zauberstab','chill','none'),
(3122,'de','Nur acht Stücke Pizza.','Nur sechs Stücke Pizza.','eine Pizza in acht Stücken','eine Pizza im Karton','ironic','understatement'),
(3124,'de','Der Hotdog hat Senf.','Der Hotdog hat Ketchup.','ein Hotdog mit Senf','ein Hotdog mit Ketchup','chill','none'),
(3125,'de','Heiße Schokolade mit Sahne!','Heißer Kaffee mit Sahne!','ein Becher heiße Schokolade','ein heißer Schokoladenkuchen','dramatic','exclamation'),
(3126,'de','Der Boxer guckt mega ernst.','Der Boxer guckt mega müde.','ein Boxer mit roten Handschuhen','mit einem Boxer Gassi gehen','slang','none'),
(3127,'de','Er wirft ihn gleich superschnell!','Er tritt ihn gleich superschnell!','einen Baseball werfen','den Handschuh wegwerfen','dramatic','guessing'),
(3132,'de','Er wandert mit einem Stock.','Er wandert mit einem Hund.','einen Berg hinaufwandern','am Strand entlangwandern','chill','none'),
(3135,'de','Sie gewinnt das Rennen!','Sie verliert das Rennen!','ein Laufrennen gewinnen','ein Schwimmrennen gewinnen','dramatic','exclamation'),
(3136,'de','Sie schwimmt in einem See.','Sie schwimmt in einem Pool.','in einem See schwimmen','im Meer schwimmen','chill','none'),
(3141,'de','Die Gruppe hat ein Meeting.','Die Gruppe hat eine Party.','eine Gruppe im Kreis','eine Gruppe in einer Reihe','business','none'),
(3143,'de','Er färbt Stoff blau.','Er färbt Stoff rot.','Stoff blau färben','sich die Haare blau färben','chill','none'),
(3144,'de','Er webt Stoff.','Er webt einen Korb.','am Webstuhl weben','sich durch den Stau schlängeln','chill','none'),
(3145,'de','Er arbeitet an einem hohen Webstuhl.','Er arbeitet an einem hohen Schreibtisch.','an einem Holzwebstuhl weben','an einer Nähmaschine nähen','chill','none'),
(3147,'de','Blaues Tuch trocknet auf einer Leine über der Gasse.','Blaues Papier trocknet auf einer Leine über der Gasse.','blaues Tuch auf der Leine','ein Tuch für den Tisch','chill','none'),
(3148,'de','Die Frauen ernten.','Die Frauen tanzen.','goldene Halme ernten','Äpfel ernten','chill','none'),
(3157,'de','Er hält einen roten Ziegel hoch.','Er hält einen roten Helm hoch.','eine halb fertige Ziegelmauer','ein Ziegelhaus am Meer','chill','none'),
(3158,'de','Der Arbeiter schweißt Stahl.','Der Arbeiter lackiert Stahl.','eine Stahlplatte schweißen','ein kaputtes Fahrrad schweißen','nerd','none'),
(3163,'de','Sie wäscht sich die Hände.','Sie wäscht sich das Gesicht.','sich die Hände waschen','das Geschirr abwaschen','chill','none'),
(3164,'de','Zeit, dir die Zähne zu putzen!','Zeit, dir die Haare zu bürsten!','sich die Zähne putzen','sich die Haare bürsten','dramatic','exclamation'),
(3171,'de','So ein „hilfreicher“ Wegweiser.','So eine „hilfreiche“ Karte.','ein alter hölzerner Wegweiser','ein alter hölzerner Zaunpfahl','ironic','understatement'),
(3176,'de','Sie sitzt unter einem Baum.','Sie sitzt in einem Baum.','unter einem Baum sitzen','auf einem Ast sitzen','chill','none'),
(3180,'de','Sie läuft auf einem Bein Schlittschuh!','Sie fährt auf einem Bein Ski!','auf einem See Schlittschuh laufen','im Park Schlittschuh laufen','dramatic','exclamation'),
(3188,'de','Jemand betet auf einer Matte.','Jemand schläft auf einer Matte.','auf einer Matte beten','in einer Kirche beten','chill','none'),
(3191,'de','Die Katze wollte nicht umarmt werden.','Der Hund wollte nicht umarmt werden.','eine große Katze umarmen','einen großen Hund umarmen','chill','guessing'),
(3192,'de','Nur ihre Augen sind zu sehen.','Nur ihr Mund ist zu sehen.','nur die Augen sichtbar','im Schlaf geschlossene Augen','business','none'),
(3194,'de','Der Zahnarzt hat einen Bohrer. Hilfe!','Der Zahnarzt hat ein Messer. Hilfe!','ein Zahnarzt mit Bohrer','eine Zahnärztin beim Zähneputzen','dramatic','exclamation'),
(3195,'de','Er arbeitet immer noch. Armer Kerl.','Er isst immer noch. Armer Kerl.','spätabends arbeiten','spätabends trainieren','slang','guessing'),
(3197,'de','Sie tagträumt von Tee, Büchern und Musik.','Sie tagträumt von Autos, Büchern und Musik.','am Tisch tagträumen','im Bett tagträumen','gossip','guessing'),
(3198,'de','Ihr Fernseher ist ein Aquarium.','Ihr Fernseher ist ein Kamin.','Fische im Aquarium','Fisch auf dem Teller','ironic','understatement'),
(3199,'de','Diese Doppelspirale ist DNA.','Diese Doppelspirale ist ein Seil.','eine leuchtende DNA-Spirale','ein DNA-Testkit','nerd','none'),
(3200,'de','Der Brief ist in der Mitte.','Das Handy ist in der Mitte.','ein handgeschriebener Brief','ein gedruckter Brief','chill','none'),
(3207,'de','Wer braucht eine Lampe? Die Pflanze leuchtet.','Wer braucht eine Lampe? Das Buch leuchtet.','eine leuchtende kleine Pflanze','ein leuchtendes Feuer','ironic','cheap_quality'),
(3216,'de','Sie rennen Seite an Seite.','Sie tanzen Seite an Seite.','Seite an Seite rennen','zum Bus rennen','chill','none'),
(3222,'de','Eine Katze schläft wie ein König.','Ein Hund schläft wie ein König.','im Sessel schlafen','im Körbchen schlafen','slang','cliche'),
(3235,'de','Guck mal, der Koala hat Rosen.','Guck mal, der Koala hat Karotten.','ein Koala mit Rosen','ein Koala, der Blätter frisst','gossip','none'),
(3240,'de','Er schreit uns an!','Er singt uns an!','in ein Megafon schreien','einen Hund anschreien','dramatic','exclamation'),
(3242,'de','Popcorn im Bett mit Fernbedienung? Diese Katzen haben''s verstanden.','Pizza im Bett mit Fernbedienung? Diese Katzen haben''s verstanden.','Popcorn im Bett','Popcorn im Kino','slang','cliche'),
(3243,'de','Das Netzwerk leuchtet blau.','Das Netzwerk leuchtet rot.','ein leuchtend blaues Netzwerk','ein TV-Netzwerk','chill','none'),
(3256,'de','Die Band rockt den Club!','Die Band rockt den Strand!','eine Band auf der Bühne','eine Band im Stadion','slang','none'),
(3266,'de','Sie fährt an der Bucht entlang.','Sie fährt am Fluss entlang.','am Meer entlangfahren','an den Gleisen entlangfahren','chill','none'),
(3269,'de','Sie entspannt auf dem Dach.','Sie entspannt am Strand.','im Liegestuhl entspannen','in der Badewanne entspannen','chill','none'),
(3272,'de','High Heels, Aktentasche: absolute Chefin!','High Heels, Rucksack: absolute Chefin!','eine Aktentasche aus Leder tragen','eine Aktentasche voller Geld','flirt','exclamation'),
(3274,'de','Der Tischtennisschläger ist rot.','Der Tischtennisschläger ist schwarz.','eine Tischtennisplatte','Tischtennis im Fernsehen','chill','none'),
(3277,'de','Das Kind hält einen Stern!','Das Kind hält eine Lampe!','einen leuchtenden Stern halten','eine leuchtende Lampe halten','dramatic','exclamation'),
(3278,'de','Das Paar umarmt sich.','Das Paar tanzt.','ein Paar, das sich umarmt','ein paar Freunde','flirt','none'),
(3281,'de','Der Drachen macht die ganze Arbeit.','Das Boot macht die ganze Arbeit.','von einem Drachen gezogen','ein Drachen im Park','ironic','exaggeration'),
(3283,'de','Die Möwe ist jetzt Touristin.','Die Taube ist jetzt Touristin.','eine Möwe auf dem Steg','eine Möwe auf einem Boot','chill','exaggeration'),
(3285,'de','Ihr Kostüm hat Spielzeugpapageien!','Ihr Kostüm hat Spielzeugschlangen!','ein Kostüm mit Obst-Kopfschmuck','ein Halloween-Kostüm','gossip','exclamation'),
(3288,'de','Sie laufen auf Stelzen.','Sie laufen auf einer Bühne.','auf hohen Stelzen laufen','Häuser auf Stelzen','chill','none'),
(3293,'de','Sie boxt, Handschuh ganz oben!','Sie boxt, Handschuh ganz unten!','im Ring boxen','ein Ticket entwerten','dramatic','exclamation'),
(3294,'de','Er tritt gleich gegen den Ball!','Er wirft gleich den Ball!','kurz davor, den Ball zu treten','eine Tür auftreten','dramatic','exclamation'),
(3301,'de','Er steuert das Schiff.','Er steuert das Auto.','ein großes Schiff steuern','ein kleines Auto steuern','chill','none'),
(3303,'de','Sein Papierflieger fliegt!','Sein Drachen fliegt!','einen Papierflieger werfen','einen Papierflieger falten','dramatic','exclamation'),
(3304,'de','Der Hockeyschläger ist für den Puck, glaub ich.','Der Hockeyschläger ist für den Ball, glaub ich.','ein Hockeyschläger auf dem Eis','ein kaputter Hockeyschläger','low_iq','guessing'),
(3306,'de','Dem Hahn gehört die Welt.','Dem Adler gehört die Welt.','ein Hahn auf einem Globus','ein Hahn auf einem Zaun','dramatic','exaggeration'),
(3311,'de','Sie geht in einen Tunnel.','Sie geht in einen See.','ein Tunnel aus Fels','ein Tunnel unter einem Fluss','chill','none'),
(3313,'de','Was für ein „volles“ Stadion.','Was für ein „voller“ Strand.','ein leeres Stadion','ein volles Stadion','ironic','none'),
(3314,'de','Sie joggt mit Kopfhörern.','Sie joggt mit einem Hund.','eine Straße entlangjoggen','am Strand entlangjoggen','chill','none'),
(3317,'de','Das Alpaka will mit aufs Foto.','Das Pferd will mit aufs Foto.','ein neugieriges braunes Alpaka','ein schlafendes braunes Alpaka','gossip','guessing'),
(3323,'de','Das kleine Nilpferd ist sehr beschäftigt.','Der kleine Löwe ist sehr beschäftigt.','ein ruhendes Nilpferdbaby','ein schwimmendes Nilpferdbaby','chill','understatement'),
(3325,'de','Magie sprüht aus einem alten Buch!','Magie sprüht aus einer alten Tasse!','Magie aus einem alten Buch','eine Zaubershow auf der Bühne','dramatic','exclamation'),
(3341,'de','Ein Typ hat eine goldene Trompete.','Ein Typ hat eine goldene Geige.','eine goldene Trompete','Trompete spielen','chill','none'),
(3346,'de','Zwei Leute sind in einer Bibliothek.','Zwei Leute sind in einer Küche.','zwei Leute in einer Bibliothek','ein Bibliotheksausweis','chill','none'),
(3357,'de','Ein hoher Stuhl am Netz.','Eine hohe Leiter am Netz.','ein Netz quer über den Platz','ein Netz zum Fischen','chill','none'),
(3362,'de','Bro, der Waschbär starrt.','Bro, die Katze starrt.','ein Waschbär auf einem Sims','ein Waschbär in der Mülltonne','slang','none'),
(3368,'de','Das Faultier hat keine Eile.','Der Koala hat keine Eile.','ein lächelndes Faultier','ein schlafendes Faultier','chill','understatement'),
(3369,'de','Es riecht an einer blauen Blume.','Es riecht an einer roten Blume.','an einer Blume riechen','an der Suppe riechen','chill','none'),
(3379,'de','Er rennt zum Ball.','Er rennt vom Ball weg.','zum Ball rennen','ein Ball am Himmel','chill','none'),
(3382,'de','Yo, dieser Papagei ist ein Pirat.','Yo, dieser Papagei ist ein Koch.','ein Papagei mit Augenklappe','ein Papagei im Käfig','slang','exaggeration'),
(3383,'de','Ein Küken surft auf einer Welle!','Eine Ente surft auf einer Welle!','ein surfendes Küken','ein Küken im Ei','dramatic','exclamation'),
(3390,'de','Sie küssen sich zwischen Rosen.','Sie küssen sich am Strand.','sich im Rosengarten küssen','sich auf einer Brücke küssen','flirt','none'),
(3392,'de','Die Eule hat Nachtschicht.','Die Eule hat Tagschicht.','eine Eule im Schnee','eine weiße Eule im Flug','business','cliche'),
(3395,'de','Nebel verhüllt die Berge.','Nebel verhüllt die Stadt.','dichter Nebel auf den Gipfeln','Nebel auf dem Badezimmerspiegel','chill','none'),
(3401,'de','Die Ampel hat Blumen!','Die Ampel hat Kerzen!','eine Ampel mit Blumen','eine kaputte Ampel','low_iq','exclamation'),
(3406,'de','Jemand taucht mit einem Seeungeheuer!','Jemand taucht mit einem Hai!','über einem Riff tauchen','von einer Klippe springen','dramatic','exaggeration'),
(3412,'de','Sie hebt Gewichte im roten Kleid!','Sie hebt Gewichte im roten Mantel!','eine Langhantel heben','einen Koffer heben','dramatic','exclamation'),
(3418,'de','Sie haut gleich aufs Schlagzeug.','Sie haut gleich auf den Gong.','Schlagzeug spielen','das Schlagzeug tragen','chill','guessing'),
(3419,'de','Er bläst in eine Trompete.','Er bläst in eine Pfeife.','eine goldene Trompete blasen','eine goldene Trompete putzen','chill','none'),
(3420,'de','Der Kontrabass ist größer als sie.','Der Kontrabass ist kleiner als sie.','einen Kontrabass streichen','einen Kontrabass tragen','nerd','none'),
(3422,'de','Sie leitet das Orchester.','Sie leitet den Chor.','ein Orchester leiten','in einem Orchester spielen','business','none'),
(3423,'de','Sie zupft die Harfe.','Sie zupft die Gitarre.','eine große Harfe zupfen','eine große Harfe tragen','chill','none'),
(3424,'de','Der Dirigent hält einen Taktstock.','Der Dirigent hält eine Flöte.','ein Dirigent im Frack','ein Dirigent im Zug','business','none'),
(3428,'de','Sie spielt wunderschön Geige.','Sie spielt wunderschön Cello.','Geige spielen','die Geige stimmen','flirt','none'),
(3431,'de','Sie spielt Klarinette.','Sie spielt Trompete.','in eine Klarinette blasen','eine Klarinette putzen','chill','none'),
(3435,'de','Zwei Höhlen in der Klippe.','Zwei Höhlen im Sand.','eine Meereshöhle in den Klippen','eine Höhle voller Fledermäuse','chill','none'),
(3441,'de','Sie lehnt an Wassermelonen.','Sie lehnt an Kürbissen.','eine Kiste Wassermelonen','ein Stand mit Wassermelonensaft','chill','none'),
(3447,'de','Eine Statue unter der Milchstraße.','Eine Statue unter einem Regenbogen.','eine Steinstatue bei Nacht','eine Statue im Park','chill','none'),
(3458,'de','Steinköpfe unter den Sternen.','Steinköpfe unter der Sonne.','Sterne über Steinköpfen','Sterne auf einer Flagge','chill','none'),
(3463,'de','Er paddelt ein Kanu.','Er paddelt ein Floß.','ein Kanu im Sonnenuntergang paddeln','ein Kanu im Sonnenuntergang tragen','chill','none'),
(3469,'de','Der Gepard macht Pause.','Der Gepard nimmt ein Bad.','ein Gepard im Sonnenuntergang','ein rennender Gepard','business','understatement'),
(3470,'de','Eine riesige orange Düne aus Sand.','Eine riesige weiße Düne aus Sand.','der geschwungene Kamm einer Düne','eine Düne am Meer','chill','none'),
(3472,'de','Schönes Kleid! Sie dreht sich darin.','Schöner Hut! Sie dreht sich darin.','sich im roten Kleid drehen','sich im blauen Kleid drehen','flirt','none'),
(3473,'de','Der Flamingo steht im Wasser.','Der Flamingo steht in einem Baum.','ein Flamingo im Wasser','ein Flamingo im Flug','chill','none'),
(3479,'de','Eine pinke Handtasche, ein ruhiges Café.','Ein pinker Laptop, ein ruhiges Café.','eine Handtasche auf dem Tisch','eine Handtasche im Laden','chill','none'),
(3482,'de','Sie chillt auf den Stufen.','Sie schläft auf den Stufen.','sonnige Steinstufen','Stufen einer Rolltreppe','slang','none'),
(3485,'de','Sie berührt den Elefanten.','Sie berührt den Tiger.','einen Elefanten berühren','einen Baumstamm berühren','chill','none'),
(3486,'de','Sie trinkt aus einer Kokosnuss.','Sie trinkt aus einer Flasche.','eine Kokosnuss mit Strohhalm','eine Kokosnuss öffnen','chill','none'),
(3489,'de','Wein im Boot? Sie lacht.','Wein im Auto? Sie lacht.','im Boot lachen','über ein Boot lachen','gossip','guessing'),
(3493,'de','Sie hinterlässt Fußspuren.','Sie hinterlässt Blumen.','eine Reihe Fußspuren','Fußspuren im Schnee','chill','none'),
(3494,'de','Sie dehnt sich Richtung Sonne.','Er dehnt sich Richtung Sonne.','beide Arme nach oben dehnen','ein Gummiband dehnen','chill','none'),
(3497,'de','Sie läuft in den Sonnenuntergang. Klassiker.','Sie läuft ins Meer. Klassiker.','in den Sonnenuntergang laufen','Sonnenuntergang vom Auto aus','ironic','cliche'),
(3513,'de','Der Schleier der Braut ist sehr lang.','Der Schleier der Braut ist sehr dunkel.','der lange Schleier einer Braut','eine Braut mit Brautstrauß','gossip','none'),
(3516,'de','In der Vase steht eine Blume.','In der Vase stehen zehn Blumen.','eine Vase im Regal','eine Vase auf dem Tisch','chill','none'),
(3519,'de','Der weiße Ohrring ist wunderschön.','Die weiße Kette ist wunderschön.','ein weißer Tropfen-Ohrring','ein Ohrring auf dem Boden','flirt','none'),
(3522,'de','Fakt: Diese Qualle leuchtet.','Fakt: Dieser Seestern leuchtet.','eine leuchtende Qualle','eine Qualle am Strand','nerd','cliche'),
(3541,'de','Ein hoher Wasserfall, ein winziger See.','Ein hoher Wasserfall, ein winziges Boot.','ein Wasserfall von einer Klippe','ein Wasserfall im Garten','chill','none'),
(3548,'de','Sie raucht im Smoking.','Sie raucht im Kleid.','eine Zigarette rauchen','Pfeife rauchen','chill','none'),
(3552,'de','Japan im Frühling, der Fuji dahinter.','Japan im Winter, der Fuji dahinter.','eine Frühlingsgasse in Japan','ein Reiseführer für Japan','chill','none'),
(3556,'de','Die Lamas haben sich fürs Foto schick gemacht.','Die Ziegen haben sich fürs Foto schick gemacht.','Lamas mit Decken','Lamas im Schnee','gossip','guessing'),
(3559,'de','Winzige Insel, null Nachbarn.','Winzige Insel, null Kakteen.','eine winzige Felseninsel','eine Insel mit Hotel','ironic','understatement'),
(3561,'de','Der Esel macht die Lieferungen.','Das Pferd macht die Lieferungen.','einen beladenen Esel führen','auf einem beladenen Esel reiten','business','none'),
(3562,'de','Das alte Ägypten am Nil.','Das alte Ägypten im Schnee.','das alte Ägypten am Nil','ein Urlaubsfoto aus Ägypten','chill','none'),
(3564,'de','Die Rentiere sind im Schnee.','Die Rentiere sind am Strand.','Rentiere im Schnee','Rentiere vor einem Schlitten','chill','none'),
(3567,'de','Eine rote Sonne hängt über Peru.','Eine gelbe Sonne hängt über Peru.','die Ruinen von Peru','die Flagge von Peru','chill','none'),
(3572,'de','Die Frauen pflücken Tee.','Die Frauen pflücken Äpfel.','Teeblätter pflücken','Blumen pflücken','chill','none'),
(3585,'de','Ein Zebra macht Mittagspause.','Ein Zebra nimmt ein Bad.','Zebras auf einem Hügel','Zebras in einem Fluss','business','none'),
(3586,'de','Die Landschildkröte hat es eilig.','Die Krabbe hat es eilig.','eine riesige Landschildkröte','eine Landschildkröte im Wasser','ironic','exaggeration'),
(3592,'de','Beide trainieren richtig hart.','Beide tanzen richtig wild.','zusammen trainieren','einen Hund trainieren','business','none'),
(3619,'de','Ein Adler ist über dem Fluss.','Ein Adler ist über der Stadt.','ein Adler über dem Fluss','ein Adler über den Bergen','chill','none'),
(3629,'de','Sie schütteln sich die Hand wie in Star Wars!','Sie kämpfen wie in Star Wars!','einem Alien die Hand schütteln','einem Roboter die Hand schütteln','dramatic','exclamation'),
(3633,'de','Im All treiben? Nein, im Pool.','Im All treiben? Nein, in einem See.','auf dem Rücken treiben','im offenen All treiben','ironic','none'),
(3638,'de','Job im All: den Boden wischen.','Job im All: den Boden streichen.','einen glänzenden Boden wischen','verschütteten Kaffee aufwischen','ironic','understatement'),
(3639,'de','Bester Platz im All: ein roter Hocker.','Bester Platz im All: ein blauer Hocker.','auf einem roten Hocker sitzen','ein Hocker im Bad','ironic','exaggeration'),
(3641,'de','Sogar auf diesem Planeten: ein Verkaufsautomat!','Sogar auf diesem Planeten: ein Café!','ein beleuchteter Verkaufsautomat','ein kaputter Verkaufsautomat','ironic','exclamation'),
(3642,'de','Er zieht einen Planeten!','Er zieht eine Rakete!','an einer Schnur ziehen','einen Zahn ziehen','dramatic','exaggeration'),
(3644,'de','Er gießt eine winzige Pflanze.','Er gießt einen hohen Baum.','einen winzigen Setzling gießen','einen großen Garten gießen','chill','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
