begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(3645,'de','Weit weg von zu Hause: ein Familienfoto auf seinem Schreibtisch.','Weit weg von zu Hause: ein Familienhund auf seinem Schreibtisch.','ein Familienfoto im Weltall','ein Familienfotoalbum','dramatic','none'),
(3647,'de','Er wischt den Mond blitzblank ab.','Er wischt die Sonne blitzblank ab.','den Mond abwischen','sein Helmvisier abwischen','chill','none'),
(3653,'de','Er repariert den Mond!','Er repariert die Sonne!','einen kaputten Mond reparieren','einen platten Reifen reparieren','dramatic','exaggeration'),
(3658,'de','So windig, dass der Baum aufgegeben hat.','So regnerisch, dass der Baum aufgegeben hat.','ein windiger Tag in Patagonien','windiges Wetter auf See','ironic','exaggeration'),
(3663,'de','Das Lama checkt dich ab.','Die Ziege checkt dich ab.','ein Lama auf einem Grat','ein Lama in einer Scheune','slang','guessing'),
(3671,'de','Es hat die Arme weit ausgebreitet.','Es hat die Arme verschränkt.','die Arme weit ausbreiten','die Arme verschränken','chill','none'),
(3673,'de','Sechs Heißluftballons sind in der Luft.','Zwei Heißluftballons sind in der Luft.','Heißluftballons bei Sonnenaufgang','Heißluftballons bei Nacht','chill','none'),
(3676,'de','Blick auf die Bucht, Sonnenuntergang inklusive.','Blick auf die Bucht, Schnee inklusive.','eine geschwungene türkise Bucht','eine Bucht voller Boote','business','cliche'),
(3685,'de','So viele Heißluftballons!','So viele Hubschrauber!','Heißluftballons über Felsen','Heißluftballons über dem Meer','dramatic','exclamation'),
(3706,'de','Die Achterbahn macht allen Angst!','Das Riesenrad macht allen Angst!','eine Familie in der Achterbahn','eine Familie neben der Achterbahn','dramatic','exaggeration'),
(3709,'de','Der Koch probiert die Suppe.','Der Koch probiert den Salat.','die Suppe probieren','den Wein probieren','chill','none'),
(3718,'de','Hoodie, Bomberjacke, Sonnenbrille: cool.','Hoodie, Bomberjacke, Cap: cool.','ein Hoodie unter der Bomberjacke','den Hoodie hochziehen','slang','none'),
(3724,'de','Das Kleid der Frau ist knallig.','Das Kleid der Frau ist schwarz.','eine Frau in knalligen Farben','eine Frau in dunklen Farben','chill','none'),
(3733,'de','Der Skorpion hat den Schwanz oben.','Der Skorpion hat den Schwanz unten.','ein Skorpion mit gekrümmtem Schwanz','ein Skorpion unter einem Stein','chill','none'),
(3734,'de','Das Horn ist so groß. Wow.','Das Horn ist so klein. Wow.','ein riesiges gedrehtes Horn','ins Horn blasen','low_iq','exaggeration'),
(3735,'de','Guck mal, das Erdmännchen lächelt.','Guck mal, das Erdmännchen weint.','ein aufrecht stehendes Erdmännchen','ein grabendes Erdmännchen','gossip','none'),
(3740,'de','Sie hat einen Schwimmreifen.','Sie hat ein Surfbrett.','mit Schwimmreifen rennen','im Schwimmreifen sitzen','chill','none'),
(3741,'de','Diese Tulpen sind so krass orange.','Diese Tulpen sind so krass lila.','vier orange Tulpen','Tulpen im Garten','slang','none'),
(3747,'de','Der Welpe hat eine Million Flecken!','Die Katze hat eine Million Flecken!','schwarze Flecken auf weißem Fell','ein Fleck auf dem Hemd','dramatic','exaggeration'),
(3750,'de','Ein Einhorn am Teich.','Ein Drache am Teich.','ein stiller Waldteich','ein Teich voller Enten','chill','none'),
(3767,'de','Diese Fans räumen sogar auf!','Diese Spieler räumen sogar auf!','die Sitzreihen aufräumen','dein Zimmer aufräumen','gossip','exclamation'),
(3770,'de','Die Krähe schaut nach rechts.','Die Krähe schaut nach links.','eine glänzend schwarze Krähe','eine fliegende Krähe','chill','none'),
(3772,'de','Dieser Drache ist aus Eis!','Dieser Drache ist aus Feuer!','das Gesicht eines Eisdrachen','ein feuerspeiender Drache','dramatic','exclamation'),
(3777,'de','Seine Flügel brennen!','Seine Flügel sind im Wasser!','weit ausgebreitete Flügel','eng angelegte Flügel','dramatic','exclamation'),
(3779,'de','Das arme Spielzeug ist ganz allein.','Der arme Hund ist ganz allein.','ein alter Spielzeughase','ein altes Spielzeugauto','dramatic','exaggeration'),
(3797,'de','Ein Handstand im Wasser!','Ein Handstand im Schnee!','ein Handstand im flachen Wasser','ein Handstand am Strand','slang','none'),
(3803,'de','Ein Drache umarmt den Turm!','Eine Schlange umarmt den Turm!','ein Drache um den Turm','ein hoher Wasserturm','dramatic','exaggeration'),
(3806,'de','Im Drink sind zwei Kirschen.','Im Drink sind drei Kirschen.','zwei Kirschen an einem Stiel','eine Schale Kirschen','chill','none'),
(3809,'de','Ein Rettungsring wird helfen!','Eine Schwimmweste wird helfen!','Hilfe suchend nach oben greifen','Hilfe bei den Hausaufgaben','dramatic','exclamation'),
(3813,'de','Er schaut den Pfad entlang.','Er schaut den Fluss entlang.','ein bunt bemalter Pfad','ein matschiger Waldpfad','chill','none'),
(3825,'de','Aus dem Weltraum sieht die Erde winzig aus.','Aus dem Weltraum sieht der Mars winzig aus.','die Erde aus dem Weltraum','die Erde aus dem Flugzeug','chill','none'),
(3827,'de','Direkt hinter ihm ist ein Monster!','Direkt hinter ihm ist ein Drache!','ein Monster hinter dem Jungen','ein Monster unter dem Bett','dramatic','exclamation'),
(3832,'de','Das Feuerwerk explodiert!','Die Luftballons explodieren!','Feuerwerk am Nachthimmel','Feuerwerk im Laden','dramatic','exclamation'),
(3841,'de','Die Kleidung fliegt durch die Gegend!','Die Schuhe fliegen durch die Gegend!','in der Luft schwebende Kleidung','Kleidung in der Waschmaschine','dramatic','exclamation'),
(3842,'de','Er wirft einen Becher weg.','Er wirft eine Tüte weg.','einen Becher wegwerfen','einen Ball wegwerfen','business','none'),
(4001,'de','Dieser Kampfjet macht Toast!','Dieser Kampfjet macht Kaffee!','ein Toaster-Kampfjet','ein Kämpfer im Boxring','slang','exclamation'),
(4002,'de','Handstand auf dem Tisch? Starkes Gleichgewicht!','Handstand auf dem Sofa? Starkes Gleichgewicht!','das Gleichgewicht auf dem Tisch halten','das Gleichgewicht auf Eis verlieren','gossip','exclamation'),
(4003,'de','Zwei Paar Monster-Hausschuhe.','Zwei Paar Monster-Stiefel.','ein Paar gelbe Hausschuhe','ein Paar gelbe Handschuhe','chill','none'),
(4004,'de','Der Jet erhitzt Brot. Ganz normal.','Der Jet erhitzt Suppe. Ganz normal.','Brot im Jet erhitzen','Suppe auf dem Herd erhitzen','ironic','understatement'),
(4005,'de','Gefrorene Wand? Kein Problem.','Felswand? Kein Problem.','eine gefrorene Wand hochklettern','ein gefrorener See zum Eislaufen','ironic','understatement'),
(4006,'de','Das Wasser ist durchsichtig.','Das Wasser ist dunkelgrün.','durchsichtiges Seewasser','eine durchsichtige Plastiktüte','chill','none'),
(4007,'de','Er ist in die Dunkelheit gesprungen, Bro.','Er ist in den Pool gesprungen, Bro.','ein Salto in der Dunkelheit','Angst vor der Dunkelheit','slang','none'),
(4008,'de','Er schüttelt den Apfelbaum!','Er klettert auf den Apfelbaum!','einen Ast schütteln','Hände schütteln','dramatic','exclamation'),
(4009,'de','Die Enten laufen in einer Reihe wie auf Klassenfahrt.','Die Hühner laufen in einer Reihe wie auf Klassenfahrt.','Enten in einer langen Reihe','Enten in einem kleinen Teich','chill','exaggeration'),
(4010,'de','Sie klettert wie ein Profi!','Sie schwimmt wie ein Profi!','auf eine weiße Klippe klettern','auf eine Leiter klettern','flirt','cliche'),
(4011,'de','Die Pandas sind sein Publikum!','Die Affen sind sein Publikum!','ein Publikum aus Pandas','ein Publikum aus Kindern','dramatic','exclamation'),
(4013,'de','Ein Eisberg zieht am Deck vorbei. Titanic-Vibes!','Ein Wal zieht am Deck vorbei. Titanic-Vibes!','Stiefel auf einem Holzdeck','ein Deck Spielkarten','slang','exclamation'),
(4014,'de','Der Koffer rollt dahin.','Das Fahrrad rollt dahin.','über einen Parkplatz rollen','einen Hügel hinunterrollen','chill','none'),
(4015,'de','Schafe springen ans Ufer!','Ziegen springen ans Ufer!','Schafe am Flussufer','Schafe vor einer Bank','dramatic','exclamation'),
(4016,'de','Die Katze sagt Nein zur Badewanne.','Der Hund sagt Nein zur Badewanne.','eine Katze auf der Badewanne','eine Katze in der Badewanne','low_iq','guessing'),
(4017,'de','Die rote Laterne leuchtet.','Die blaue Laterne leuchtet.','eine leuchtende Papierlaterne','eine leuchtende Straßenlaterne','chill','none'),
(4018,'de','Zwei Hunde sitzen auf einem Motorroller!','Zwei Katzen sitzen auf einem Motorroller!','Hunde auf einem grünen Motorroller','Hunde auf einem grünen Fahrrad','dramatic','exclamation'),
(4019,'de','Dieser Welpe hat den besten Ring.','Dieses Kätzchen hat den besten Ring.','ein rosa Schwimmring','ein Diamantring','slang','exaggeration'),
(4020,'de','Der Hund beobachtet einen Frosch.','Der Hund beobachtet einen Fisch.','den Frosch beobachten','die Fische beobachten','chill','none'),
(4021,'de','Kuchen schneiden? Ich zuerst!','Brot schneiden? Ich zuerst!','den Kuchen in Quadrate schneiden','den Kuchen in zwei Hälften schneiden','slang','guessing'),
(4022,'de','Nur ein kleiner Spaziergang auf einem fliegenden Flugzeug.','Nur ein kleiner Spaziergang auf einem fahrenden Zug.','über eine Stadt fliegen','über das Meer fliegen','ironic','understatement'),
(4023,'de','Sie haben Spaß auf einem Boot.','Sie haben Spaß in einem Bus.','Spaß auf dem Fluss','Spaß am Strand','chill','none'),
(4024,'de','Der ganze Bauernhof folgt ihm!','Der ganze Bauernhof folgt ihr!','Tiere folgen einem Mann','Tiere folgen einem Hund','dramatic','exaggeration'),
(4025,'de','Yo, das Kätzchen jagt es.','Yo, der Welpe jagt es.','einen grünen Ball jagen','einen grünen Vogel jagen','slang','none'),
(4026,'de','Das Wasser ist glatt wie Glas.','Die Straße ist glatt wie Glas.','über glattes Wasser gleiten','eine glatte Landung','chill','cliche'),
(4027,'de','Wer hat den Pie gegessen? Die Kuh?','Wer hat den Pie gegessen? Der Hund?','ein goldener Apple Pie','ein Tortendiagramm im Büro','gossip','blaming_someone'),
(4028,'de','Die Bulldogge wendet wie ein Profi!','Die Bulldogge springt wie ein Profi!','auf dem Skateboard wenden','mit dem Auto wenden','slang','exaggeration'),
(4029,'de','Die Flasche hat ihn runtergestoßen!','Der Ball hat ihn runtergestoßen!','von einem Block gestoßen','an eine Tür klopfen','slang','exclamation'),
(4030,'de','Er war im Park schwimmen.','Er hat im Park ein Nickerchen gemacht.','ein Teich in einem Park','ein Skatepark','ironic','understatement'),
(4031,'de','Der Ball ist genau auf dem obersten Punkt gelandet!','Der Ball ist genau auf ihm gelandet!','das oberste Teil des Stapels','das oberste Regal','dramatic','exclamation'),
(4032,'de','Was für ein grünes Durcheinander!','Was für ein rotes Durcheinander!','ein grünes Schleim-Durcheinander','ein unordentlicher Zimmerboden','gossip','exaggeration'),
(4033,'de','Erster Versuch mit einem Golfschläger!','Erster Versuch mit einem Hockeyschläger!','einen Golfschläger schwingen','ein Golfclub für Mitglieder','dramatic','exclamation'),
(4034,'de','Barfuß, jede Menge Fallen. Super.','Dicke Stiefel, jede Menge Fallen. Super.','Dutzende Mausefallen','eine Falle für einen Bären','ironic','understatement'),
(4036,'de','Ein breites Lächeln für die Kamera!','Ein breites Lächeln für den Hund!','ein Lächeln fürs Foto','ein Lächeln für den Zahnarzt','dramatic','exclamation'),
(4037,'de','Jemand hat ein Omelett gekocht.','Jemand hat einen Pfannkuchen gekocht.','ein Omelett kochen','Nudeln kochen','chill','none'),
(4038,'de','Die zwei lieben sich total.','Die zwei hassen sich total.','sich gegenseitig lieben','schnelle Autos lieben','gossip','guessing'),
(4039,'de','Sie ist gekrochen, aber die Band hat gewonnen.','Sie ist gerannt, aber die Band hat gewonnen.','auf Händen und Zehen kriechen','unter ein Bett kriechen','gossip','blaming_someone'),
(4040,'de','Ihre Mahlzeit: Salat. Seine Mahlzeit: ein riesiger Burger.','Ihre Mahlzeit: Pizza. Seine Mahlzeit: ein riesiger Burger.','eine Mahlzeit am Strand','eine Mahlzeit in der Küche','gossip','banter'),
(4041,'de','Sie hat ihn angesehen. Sie haben alles gekauft.','Sie hat ihn angesehen. Sie haben nichts gekauft.','im großen Einkaufszentrum einkaufen','Essen auf dem Markt kaufen','gossip','banter'),
(4042,'de','Sie stehen vor einem Laden.','Sie sind in einem Laden.','vor einem beleuchteten Laden','ein Laden voller Kokosnüsse','chill','none'),
(4043,'de','Er hat sie mit Pfingstrosen überrascht.','Er hat sie mit einem Ring überrascht.','sie mit Blumen überraschen','eine Überraschungsparty zum Geburtstag','gossip','none'),
(4044,'de','Sie übt Golf.','Sie übt Tennis.','nachts üben','Klavier üben','chill','none'),
(4045,'de','Er hat sein Handy gefunden!','Er hat seine Brieftasche gefunden!','ein verlorenes Handy finden','einen verlorenen Hund finden','dramatic','exclamation'),
(4046,'de','Er lehnt ab. Endgültige Antwort.','Er stimmt zu. Endgültige Antwort.','mit dem Finger ablehnen','das Abendessen ablehnen','ironic','cliche'),
(4047,'de','Perfekter Urlaub, aber er hält immer noch sein Handy.','Perfekter Urlaub, aber er hält immer noch sein Buch.','Urlaub am Strand','Urlaub im Schnee','ironic','banter'),
(4048,'de','Sie haben eine Dusche im Van installiert!','Sie haben eine Badewanne im Van installiert!','Solarmodule installieren','eine neue App installieren','gossip','exclamation'),
(4049,'de','Was für eine Last auf seinen Schultern!','Was für eine Last auf seinem Fahrrad!','eine riesige Last tragen','eine Ladung Ziegel tragen','dramatic','exclamation'),
(4050,'de','Die Freunde haben einen Hund.','Die Freunde haben eine Katze.','Freunde am Feuer','Freunde in einer Bar','chill','none'),
(4051,'de','Ein Lkw transportiert ein Motorrad.','Ein Lkw transportiert ein Fahrrad.','ein Elektro-Motorrad','ein Motorradhelm','chill','none'),
(4052,'de','Sie nehmen schon wieder auf. Take zehn?','Sie tanzen schon wieder. Take zehn?','mit dem Handy aufnehmen','einen Song aufnehmen','gossip','guessing'),
(4053,'de','Sogar der Mais ist ein Kuchen!','Sogar die Karotte ist ein Kuchen!','ein Kuchen in Maisform','ein Maisfeld bei Sonnenuntergang','dramatic','exclamation'),
(4054,'de','Der Hund macht Überstunden an der Tastatur. Bald Beförderung?','Die Katze macht Überstunden an der Tastatur. Bald Beförderung?','Pfoten auf einer Tastatur','eine Klaviertastatur','gossip','guessing'),
(4055,'de','Dinosaurier? Der Husky sagt Nein!','Dinosaurier? Die Katze sagt Nein!','ein Hund und zwei Dinosaurier','ein Hund und zwei Katzen','slang','exclamation'),
(4056,'de','Was für eine schäumende Feier!','Was für eine ruhige Feier!','eine Feier mit Champagner','eine Geburtstagsfeier','dramatic','exclamation'),
(4057,'de','Die Cola läuft ihr überall runter!','Das Wasser läuft ihr überall runter!','eine Flasche Cola','ein Glas Cola','dramatic','exclamation'),
(4058,'de','Reise für eine Nacht, zehn Koffer!','Reise für eine Nacht, zwei Koffer!','für eine kurze Reise packen','über einen Koffer stolpern','dramatic','banter'),
(4059,'de','Eine Banane reicht nicht, um drei Paviane zu füttern.','Eine Banane reicht nicht, um drei Zebras zu füttern.','die Paviane füttern','die Enten füttern','ironic','understatement'),
(4060,'de','Starke Strömung, aber das ist ein Wasserfall!','Starke Strömung, aber das ist eine Brücke!','die Strömung des Flusses','der Fluss des Verkehrs','dramatic','exclamation'),
(4061,'de','Schau dir den Kiefer von dem Hai an!','Schau dir den Kiefer von dem Wal an!','ein Kiefer voller Zähne','ein Kiefer ohne Zähne','dramatic','exclamation'),
(4062,'de','Bro hält sich an der Kite-Bar fest.','Bro hält sich an der Bootsreling fest.','sich an der Kite-Bar festhalten','sich am Lenkrad festhalten','slang','none'),
(4063,'de','Die Gurte haben ihn losgelassen!','Das Flugzeug hat ihn losgelassen!','in die Wolken losgelassen','einen Vogel loslassen','dramatic','exclamation'),
(4064,'de','Das Nest ist oben auf einer Stange.','Das Nest ist oben auf einem Baum.','ein Nest auf einer Stange','eine Fahne an einer Stange','chill','none'),
(4065,'de','Der Fahrer ist ein Hund. Bitte schnallen Sie sich an.','Der Fahrer ist eine Katze. Bitte schnallen Sie sich an.','ein Hund als Fahrer','ein Hund als Beifahrer','business','cliche'),
(4066,'de','Ein Papagei reitet auf der roten Erde. Legende.','Ein Papagei reitet auf dem nassen Sand. Legende.','eine Piste aus roter Erde','Erde auf einem weißen Hemd','slang','exaggeration'),
(4067,'de','Der See spiegelt die Bäume.','Der See spiegelt die Stadt.','ein See, der die Bäume spiegelt','ihre Tanzschritte spiegeln','chill','none'),
(4068,'de','Sie streichelt einen Hai!','Sie streichelt einen Delfin!','den Rücken eines Hais streicheln','auf dem Rücken eines Hais reiten','dramatic','exclamation'),
(4069,'de','Das Küken hält einen Stab.','Die Taube hält einen Stab.','ein dünner Stab zum Angeln','die Taube mit dem Stab','chill','none'),
(4070,'de','Zwei Fallschirmspringer sind auf der Tragfläche!','Zwei Fallschirmspringer sind auf dem Heck!','unter der Tragfläche hängen','auf der Tragfläche sitzen','dramatic','exclamation'),
(4071,'de','Sie springt von einem Wrack!','Sie springt von einer Brücke!','ins Meer springen','in einen Pool springen','dramatic','exclamation'),
(4072,'de','Drei Frauen, geheime Lagune.','Drei Männer, geheime Lagune.','eine türkise Lagune','eine Lagune voller Boote','gossip','none'),
(4073,'de','Drama: Das Huhn hat einen Stock.','Drama: Das Huhn hat einen Löffel.','einen Holzstock schwingen','einen Holzstock werfen','gossip','none'),
(4074,'de','Die Sonne ist hinter ihr.','Der Mond ist hinter ihr.','die Sonne über einer Lagune','die Sonne über einer Stadt','chill','none'),
(4075,'de','Überall Haie: Gefahr? Welche Gefahr?','Überall Delfine: Gefahr? Welche Gefahr?','Gefahr rund um sie herum','Gefahr auf der Straße','dramatic','understatement'),
(4076,'de','Sie springen aus der Tür!','Sie springen aus dem Fenster!','eine offene Hubschraubertür','eine offene Autotür','dramatic','exclamation'),
(4077,'de','Eine Taube liegt noch schlafend da.','Beide Tauben liegen noch schlafend da.','schlafend in einem Nest','schlafend auf einer Bank','chill','none'),
(4078,'de','Sieben Kissen für eine Person!','Sieben Decken für eine Person!','eine Reihe weißer Kissen','ein Stapel weißer Handtücher','gossip','exclamation'),
(4079,'de','Der Fluss rast vorbei. Krass!','Die Autos rasen vorbei. Krass!','einen Fluss hinunterrasen','zum Flughafen rasen','slang','exaggeration'),
(4080,'de','Die Haargummis waren an ihrem Handgelenk!','Die Haargummis waren in der Schublade!','Haargummis am Handgelenk','eine Uhr am Handgelenk','dramatic','exclamation'),
(4081,'de','Beine aus dem Hubschrauber über den Gipfeln. Nö.','Beine aus dem Flugzeug über den Gipfeln. Nö.','verschneite Gipfel von oben','ein Gipfel mit Kreuz','slang','guessing'),
(4082,'de','Sie hängt kopfüber.','Er hängt kopfüber.','kopfüber hängen','das Flugzeug kopfüber drehen','chill','none'),
(4083,'de','Ein „kleiner“ Mops hat die Mitte erobert.','Eine „kleine“ Katze hat die Mitte erobert.','die Mitte des Bettes','die Mitte des Sofas','ironic','understatement'),
(4084,'de','Auf seinem Kopf wachsen Haare!','An seinem Kinn wachsen Haare!','Haare auf einem kahlen Kopf','ein Kopf Salat','dramatic','exclamation'),
(4085,'de','Sie hat ihn komplett verändert.','Er hat sie komplett verändert.','sich in einen Anzug werfen','einen Autoreifen wechseln','gossip','exaggeration'),
(4086,'de','Die Mücke wird gleich zubeißen.','Die Spinne wird gleich zubeißen.','einen schlafenden Mann beißen','einen schlafenden Hund beißen','chill','guessing'),
(4087,'de','Die Katzen nehmen ihre Arbeit sehr ernst.','Die Hunde nehmen ihre Arbeit sehr ernst.','Katzen in Anzügen bei der Arbeit','Katzen in Anzügen in der Schule','business','understatement'),
(4088,'de','Dieser Wasserfall ist richtig breit. Geh nicht näher ran.','Diese Brücke ist richtig breit. Geh nicht näher ran.','eine breite Wasserfallkante','eine breite Flussbrücke','dramatic','guessing'),
(4089,'de','Die Kraken tanzen!','Die Krabben tanzen!','Kraken tanzen im Club','Kraken verstecken sich im Sand','dramatic','exclamation'),
(4090,'de','Die Rakete steigt schnell auf!','Das Flugzeug steigt schnell auf!','die schnell aufsteigende Rakete','die aufgehende Sonne im Morgengrauen','dramatic','exclamation'),
(4091,'de','Das Eis reißt unter ihr!','Das Eis reißt unter ihm!','Eis reißt unter ihren Füßen','Eier auf dem Eis aufschlagen','dramatic','exclamation'),
(4092,'de','Er fährt die Stufen hinunter!','Er fährt die Stufen hinauf!','die Klippenstufen hinunter','die Skipiste hinunter','dramatic','exclamation'),
(4093,'de','Wow, der Mond ist so rund.','Wow, der Mond ist so rot.','ein runder grauer Mond','eine Runde Applaus','low_iq','none'),
(4094,'de','Die Futtersäcke sind bunt.','Die Futtersäcke sind ganz weiß.','Säcke mit Tierfutter','Säcke mit Kartoffeln','chill','none'),
(4095,'de','Eine winzige Kamera hat diesen Film gedreht!','Eine riesige Kamera hat diesen Film gedreht!','einen Film drehen','ein Kino','dramatic','exclamation'),
(4096,'de','Die Schildkröte ist frei und sagt nicht mal Danke.','Der Hai ist frei und sagt nicht mal Danke.','eine freigelassene Schildkröte','eine kostenlose Schildkröte','chill','guessing'),
(4097,'de','Er fährt mega schnell.','Er fährt mega langsam.','schnell bergab fahren','vor dem Abendessen fasten','slang','exaggeration'),
(4098,'de','Zwei Kühe versperren den Weg. Unverschämt.','Zwei Schafe versperren den Weg. Unverschämt.','Kühe im Weg','der Weg zum Strand','ironic','blaming_someone'),
(4099,'de','Der Hund ist zurück an der Spitze!','Die Katze ist zurück an der Spitze!','zurück auf den Matratzen','zurück auf dem Sofa','dramatic','exclamation'),
(4100,'de','Die Feder hat das Loch gemacht, nicht ich!','Die Katze hat das Loch gemacht, nicht ich!','ein Loch in der Decke','ein Loch in seiner Socke','low_iq','blaming_someone'),
(4101,'de','Ein Performer zeigt einen Pfauenschwanz.','Ein Performer zeigt eine Flagge.','ein riesiges Pfauenrad zeigen','eine weiße Flagge zeigen','chill','none'),
(4102,'de','Der Sonnenschein ruft nach ihm!','Der Regen ruft nach ihm!','Sonnenschein vor dem Fenster','Sonnenschein im Büro','dramatic','exaggeration'),
(4103,'de','Die Geduld des Welpen ist am Ende.','Die Geduld des Kätzchens ist am Ende.','die Geduld eines Welpen','Geduld mit einem Kätzchen','ironic','cliche'),
(4104,'de','Ein Kuss und er ist eine Tomate.','Ein Kuss und er ist ein Gespenst.','ein Kuss auf die Wange','ein Kuss auf die Hand','low_iq','exaggeration'),
(4105,'de','Ihr Freund hat Blumen mitgebracht.','Ihr Freund hat einen Kuchen mitgebracht.','ein Freund mit Blumen','ein Freund mit Ring','flirt','none'),
(4106,'de','Der hungrige Hund klaut es.','Die hungrige Katze klaut es.','ein hungriger kleiner Hund','ein hungriger Mann, allein beim Essen','gossip','blaming_someone'),
(4107,'de','Sie haben einen Elefanten bedeckt und einen Tiger bekommen!','Sie haben einen Elefanten bedeckt und einen Löwen bekommen!','den Elefanten bedecken','den Tiger bedecken','dramatic','exclamation'),
(4108,'de','Sein Auto sagt: Er ist ihr Ehemann.','Sein Auto sagt: Er ist ihr Bruder.','ein Ehemann im Auto','ein Ehemann beim Autowaschen','gossip','none'),
(4109,'de','Zwei Hunde chillen auf dem Rasen.','Zwei Katzen chillen auf dem Rasen.','Hunde auf grünem Rasen','den Rasen mähen','slang','none'),
(4110,'de','Der Clown hat nicht mit einem Tiger gerechnet!','Der Clown hat nicht mit einem Löwen gerechnet!','die orange Perücke des Clowns','die lila Perücke des Clowns','dramatic','guessing'),
(4111,'de','Der Widder ist sein nerviger Kollege.','Der Hund ist sein nerviger Kollege.','ein nerviger Widder','eine nervige Fliege','business','exaggeration'),
(4112,'de','Ein sauberes Loch im Block.','Ein sauberes Loch in der Tür.','in einen Block bohren','ein Block Käse','chill','none'),
(4113,'de','Schmuck-Drama auf der Straße!','Schmuck-Drama im Laden!','rosa Schmuck an einer Taube','rosa Schmuck im Schaufenster','gossip','exclamation'),
(4114,'de','Regeln im Einkaufszentrum: Sie shoppt, er trägt.','Regeln im Einkaufszentrum: Er shoppt, sie trägt.','Einkaufstüten aus dem Einkaufszentrum','ein Parkplatz am Einkaufszentrum','gossip','banter'),
(4115,'de','Zwei Touristen haben Spaß. So süß!','Zwei Touristen essen zu Mittag. So süß!','Touristen bei Nacht','Touristen im Bus','gossip','exclamation'),
(4116,'de','Sein Auto ist sooo klein!','Sein Auto ist sooo groß!','ein kleiner roter Kabinenroller','ein kleines rotes Boot','dramatic','exclamation'),
(4117,'de','Nur eine kleine Suche.','Nur ein kleines Nickerchen.','die Suche nach einem Handy','die Suche nach einem Hund','chill','understatement'),
(4118,'de','Dieser Platz bietet Bergblick.','Dieser Platz bietet einen schönen Meerblick.','ein Platz in den Bergen','ein Platz am Meer','business','none'),
(4119,'de','Der Steinmann ist eingestürzt. RIP.','Der Steinhund ist eingestürzt. RIP.','eine einstürzende Steinfigur','eine einstürzende Steinbrücke','slang','none'),
(4120,'de','Ein Brett zum Knacken von Walnüssen.','Ein Brett zum Aufschlagen von Eiern.','ein Brett mit Loch','ein Brett zum Brotschneiden','chill','none'),
(4121,'de','Was für eine explosive Szene!','Was für eine romantische Szene!','eine explosive Actionszene','eine romantische Filmszene','dramatic','none'),
(4122,'de','Er wollte die falsche Bank ausrauben.','Er wollte den falschen Laden ausrauben.','eine Bank ausrauben','einen Zug ausrauben','ironic','bad_excuse'),
(4123,'de','Tränen wegen einer A+? Echt jetzt?','Tränen wegen einer F? Echt jetzt?','Tränen wegen einer A+','Tränen vor Lachen','ironic','guessing'),
(4124,'de','Ein Van, ein Hund und gute Freunde.','Ein Van, eine Katze und gute Freunde.','Leben im Campervan','Umzug mit dem Van','chill','none'),
(4125,'de','Ein Elefant steht auf der Bühne!','Ein Pferd steht auf der Bühne!','ein Elefant auf der Bühne','ein Sänger auf der Bühne','dramatic','exclamation'),
(4126,'de','Tausende Gebäude leuchten.','Tausende Gebäude sind dunkel.','beleuchtete Gebäude am Hafen','alte Gebäude an einem See','dramatic','none'),
(4127,'de','Das Fell des Lemurs ist sooo weich.','Das Fell des Lemurs ist sooo schwarz.','weiches weißes Fell','weiches Weißbrot','chill','none'),
(4128,'de','Der Welpe liebt diesen Hof.','Das Kätzchen liebt diesen Hof.','ein Welpe im Hof','ein Welpe auf der Straße','chill','guessing'),
(4129,'de','Der Welpe verlässt sein Zuhause.','Der Welpe kommt nach Hause.','mit Hut das Zuhause verlassen','mit Hut nach Hause kommen','chill','none'),
(4130,'de','Die Katze hat ihm einen flachen Kopf verpasst!','Der Hund hat ihm einen flachen Kopf verpasst!','der flache Kopf eines Gorillas','der flache Kopf einer Katze','gossip','exclamation'),
(4131,'de','Der Laden setzt voll auf Grün.','Der Laden setzt voll auf Rot.','eine Wand in Grün','ein Grün auf dem Golfplatz','business','none'),
(4132,'de','Die Katze bürstet einen Löwen!','Der Hund bürstet einen Löwen!','eine nasse Mähne bürsten','seine Zähne bürsten','dramatic','exclamation'),
(4133,'de','Der Hund bewacht den Kühlschrank.','Die Katze bewacht den Kühlschrank.','neben dem Kühlschrank liegen','den Kühlschrank öffnen','slang','guessing'),
(4134,'de','Der dicke Igel hat alle Stacheln verloren. Er ist nicht glücklich.','Das dicke Kaninchen hat sein ganzes Fell verloren. Es ist nicht glücklich.','ein dicker runder Igel','eine dicke graue Katze','gossip','understatement'),
(4135,'de','Sie hat den Ball geschossen und ist dann vom Platz gesprungen!','Sie hat den Ball gefangen und ist dann vom Platz gesprungen!','den Ball aufs Tor schießen','den Ball mit den Händen fangen','dramatic','exclamation'),
(4136,'de','Mit vier Hunden trainieren ist nicht leicht.','Mit vier Katzen trainieren ist nicht leicht.','mit Hunden trainieren','im Park trainieren','chill','understatement'),
(4137,'de','So viel Gelb in einem Zimmer!','So viel Grün in einem Zimmer!','ein Kleid in knalligem Gelb','ein gelb gestrichenes Zimmer','slang','exaggeration'),
(4138,'de','Er streichelt den alten Hund.','Er streichelt die alte Katze.','einen alten Hund streicheln','mit einem alten Hund Gassi gehen','chill','none'),
(4139,'de','Er steigt einen schmalen Pfad hinauf.','Er steigt eine steile Leiter hinauf.','ein schmaler Erdpfad','ein Pfad durch die Wüste','chill','none'),
(4140,'de','Er springt von einem Felsvorsprung. Abenteuer oder dumme Idee?','Er springt von einem Boot. Abenteuer oder dumme Idee?','ein Abenteuer mit Freunden','ein Abenteuerfilm','dramatic','guessing'),
(4141,'de','Fünf Jungs liegen in der Sonne.','Fünf Jungs liegen im Schlamm.','im Gras liegen','seine Freunde anlügen','slang','none'),
(4142,'de','Es regnet auf sie. Spaß!','Es schneit auf sie. Spaß!','sich drehen, während es regnet','sich verstecken, während es regnet','slang','exclamation'),
(4143,'de','Psst, ein Waschbär ist in der Tonne.','Psst, eine Katze ist in der Tonne.','ein Waschbär in einer Tonne','ein Waschbär auf einer Tonne','gossip','none'),
(4144,'de','Die Frettchen lieben das Rohr.','Die Katzen lieben das Rohr.','Frettchen in einem Rohr','eine Tube Zahnpasta','chill','guessing'),
(4145,'de','Er hechtet nach dem Ball!','Er hechtet nach dem Frisbee!','nach dem Ball hechten','von einem Boot hechten','dramatic','exclamation'),
(4146,'de','Zu erschöpft, um die Schuhe auszuziehen.','Zu erschöpft, um das Hemd auszuziehen.','erschöpft im nassen Sand','erschöpft in einem heißen Bad','ironic','exaggeration'),
(4147,'de','Er beeilt sich. Warum dieses Schild?','Er schläft. Warum dieses Schild?','sich zum Auto beeilen','sich zum Bus beeilen','gossip','guessing'),
(4148,'de','Purer Luxus: ein roter Sportwagen.','Purer Luxus: ein rotes Motorrad.','ein Luxus-Sportwagen','ein Luxus-Hotelzimmer','flirt','exaggeration'),
(4149,'de','Es ist auf einem schlafenden Riesen gelandet!','Es ist auf einem schlafenden Bären gelandet!','auf einem Riesen landen','gegen einen Riesen kämpfen','dramatic','exclamation'),
(4150,'de','Das grüne Auto rast.','Das rote Auto rast.','über eine Landstraße rasen','über die Autobahn rasen','chill','none'),
(4151,'de','Diese Autokunst ist sehr pink.','Diese Autokunst ist sehr grün.','Autokunst in Pink','Kunst im Museum','ironic','understatement'),
(4152,'de','Der Anhänger versteckt ein Fahrzeug.','Der Anhänger versteckt ein Pferd.','ein Fahrzeug in einem Anhänger','ein Fahrzeug auf einer Fähre','gossip','guessing'),
(4153,'de','Ein blaues Auto auf der Autobahn.','Ein rotes Auto auf der Autobahn.','eine Autobahn in die Berge','eine Autobahn ans Meer','chill','none'),
(4154,'de','Sport bei Nacht auf dem Sandplatz.','Sport bei Nacht auf dem Rasenplatz.','Sport unter Flutlicht','Sport im Fernsehen','chill','none'),
(4155,'de','Die Teller sind jetzt „sauber“.','Die Tassen sind jetzt „sauber“.','ein sauberer weißer Teller','ein sauberes weißes Handtuch','ironic','understatement'),
(4156,'de','Ein Roboter nähert sich uns!','Ein Hund nähert sich uns!','sich der Kamera nähern','sich dem Pool nähern','dramatic','exclamation'),
(4157,'de','Alle rennen, aber ihr Schild gewinnt.','Alle rennen, aber ihr Hund gewinnt.','an einem lustigen Schild vorbeirennen','im Sportwagen Rennen fahren','gossip','exaggeration'),
(4158,'de','Der Fisch ist riesig. Wow.','Der Fisch ist winzig. Wow.','ein riesiger grinsender Fisch','ein riesiger grinsender Otter','low_iq','none'),
(4159,'de','So hoch über dem Tal!','So hoch über der Stadt!','hoch über dem Tal','hoch über den Wolken','dramatic','exclamation'),
(4161,'de','Die zwei Vorderseiten berühren sich fast.','Die zwei Rückseiten berühren sich fast.','die Vorderseite eines Autos','die Vorderseite eines Hauses','chill','none'),
(4162,'de','Ein Auto. Ganzer Platz. Nice.','Ein Bus. Ganzer Platz. Nice.','ein nasser gepflasterter Platz','ein Platz mit Marktständen','slang','none'),
(4163,'de','Er redet über sein Auto.','Er redet über seinen Hund.','über ein Auto reden','mit einem Auto reden','chill','none'),
(4164,'de','Die Bremse ist groß und rot.','Die Bremse ist groß und blau.','eine große rote Bremse','ein großer roter Knopf','chill','none'),
(4165,'de','Bei dieser Geschwindigkeit verschwimmen die Bäume.','Bei dieser Geschwindigkeit verschwimmen die Häuser.','Geschwindigkeit auf einer Bergstraße','Geschwindigkeit auf der Rennstrecke','dramatic','none'),
(4166,'de','Er steigt in das rote Auto ein wie ein Star.','Er steigt in das blaue Auto ein wie ein Star.','in einen roten Sportwagen einsteigen','in eine rote Telefonzelle eintreten','flirt','exaggeration'),
(4167,'de','Dunkle Höhle, heller Ausgang.','Dunkle Höhle, kein Ausgang.','ein heller Höhlenausgang','ein Schild zur Autobahnausfahrt','dramatic','none'),
(4168,'de','Die langsame Schildkröte hält nie an.','Der langsame Hase hält nie an.','eine langsame Schildkröte','eine langsame Schnecke','chill','none'),
(4169,'de','Er wirft dem Bären einen Blick zu!','Er wirft dem Bären einen Fisch zu!','ein Blick auf den Bären','ein Blick auf die Karte','dramatic','exclamation'),
(4170,'de','Die Henne hat ihr Küken gerettet!','Die Henne hat ihr Ei gerettet!','ein Küken retten','ein Kätzchen retten','dramatic','exclamation'),
(4171,'de','Der Wolf schleicht sich näher.','Der Fuchs schleicht sich näher.','ein Wolf schleicht sich näher','ein Wolf rennt weg','chill','none'),
(4172,'de','Die Henne hat eine Flucht wie im Actionfilm hingelegt.','Die Ente hat eine Flucht wie im Actionfilm hingelegt.','die Flucht vor dem Feuer','die Flucht aus dem Gefängnis','dramatic','exaggeration'),
(4173,'de','Die Verfolgungsjagd endete auf einer Brücke.','Die Verfolgungsjagd endete in einer Scheune.','eine Verfolgungsjagd über eine Brücke','eine Verfolgungsjagd durch den Wald','chill','none'),
(4174,'de','Die Henne verteidigt ihre Küken wie eine Superheldin.','Die Füchsin verteidigt ihre Küken wie eine Superheldin.','ihre Küken verteidigen','ihre Eier verteidigen','dramatic','exaggeration'),
(4175,'de','Psst, die Henne schleicht sich an.','Psst, der Fuchs schleicht sich an.','an schlafenden Wölfen vorbeischleichen','sich in einen Hühnerstall schleichen','gossip','none'),
(4176,'de','Ein Glühwürmchen leuchtet im Glas.','Eine Kerze leuchtet im Glas.','ein leuchtendes Glühwürmchen','eine leuchtende Lampe','chill','none'),
(4177,'de','Die Küken haben die Münder weit offen.','Die Küken haben die Münder fest zu.','Küken mit offenen Mündern','Küken mit offenen Flügeln','chill','none'),
(4178,'de','Die Henne ist eine großzügige Spenderin.','Der Fuchs ist ein großzügiger Spender.','eine großzügige Henne','ein großzügiger Fuchs','business','exaggeration'),
(4179,'de','Es ist ihr 100. Geburtstag!','Es ist ihr 50. Geburtstag!','eine Torte zum 100. Geburtstag','ein Geburtstag am Strand','dramatic','exclamation'),
(4180,'de','Sie hat den Alligator mit einem Hund verwechselt: keine Brille.','Sie hat die Schlange mit einem Hund verwechselt: keine Brille.','einen Alligator verwechseln','einen Welpen verwechseln','gossip','bad_excuse'),
(4181,'de','Sie bieten ihr einen Kuchen an.','Sie bieten ihr eine Pizza an.','eine Geburtstagstorte anbieten','eine Tasse Tee anbieten','chill','none'),
(4182,'de','Er hat ein Bild auf den ganzen Rasen gemalt!','Er hat ein Bild auf das ganze Haus gemalt!','ein riesiges Rasenbild malen','einen Gartenzaun streichen','dramatic','exaggeration'),
(4183,'de','Im Geschenk steckt ein Mann!','Im Geschenk steckt ein Hund!','ein Mann in einem Geschenk','eine Uhr in einem Geschenk','dramatic','exclamation'),
(4184,'de','Der Welpe bringt den Ball zurück. Wer braucht schon Menschen?','Der Welpe bringt den Schuh zurück. Wer braucht schon Menschen?','den Ball zurückbringen','den Ball nach Hause bringen','slang','exaggeration'),
(4185,'de','Ein Becher drückt auf die Maus.','Ein Becher drückt auf die Waffeln.','ein Becher drückt auf eine Maus','ein Teller drückt auf eine Maus','chill','none'),
(4186,'de','Der Hund kehrt mit dem Ball zurück.','Der Hund kehrt mit dem Schuh zurück.','zur Maschine zurückkehren','zum Auto zurückkehren','chill','none'),
(4187,'de','Die Papageien stellen sich tot!','Die Papageien spielen Ball!','Papageien stellen sich tot','Papageien spielen Karten','dramatic','exclamation'),
(4188,'de','Ein Skifahrer, ein „kleiner“ Hang.','Zwei Skifahrer, ein „kleiner“ Hang.','ein langer verschneiter Hang','ein Hang mit Skiliften','ironic','understatement'),
(4189,'de','Leerer Napf, eine Tablette übrig.','Leerer Napf, zwei Tabletten übrig.','ein leerer Hundenapf','ein leerer Kühlschrank','chill','none'),
(4190,'de','Die Katze trifft sich mit einem Löwen. Keine große Sache.','Der Hund trifft sich mit einem Löwen. Keine große Sache.','sich mit einem Löwen treffen','sich mit einem Tiger treffen','slang','understatement'),
(4191,'de','Die Rakete ragt über ihm auf.','Der Bus ragt über ihm auf.','eine Rakete ragt über ihm auf','ein Kran ragt über ihm auf','chill','none'),
(4192,'de','Fakt: Dieser Adler fischt.','Fakt: Diese Eule fischt.','mit den Füßen fischen','mit einer Angel fischen','nerd','none'),
(4193,'de','Batman braucht diese unterirdische Garage.','Batman braucht diesen unterirdischen Pool.','eine unterirdische Garage','ein unterirdischer Zug','dramatic','exaggeration'),
(4194,'de','Was für eine Fahrt im winzigen Jeep!','Was für eine Fahrt im winzigen Boot!','eine Fahrt im Spielzeugjeep','eine Fahrt im Spielzeugboot','dramatic','exclamation'),
(4195,'de','Der Roller ist kaputtgegangen, in tausend Stücke!','Das Fahrrad ist kaputtgegangen, in tausend Stücke!','ein Roller geht kaputt','einen Weltrekord brechen','dramatic','exclamation'),
(4196,'de','Im Eimer steht eine Kerze.','Im Eimer steht eine Blume.','eine Kerze in einem Eimer','ein Eimer Wasser','chill','none'),
(4197,'de','Es ist spät! Lauf!','Es ist früh! Lauf!','spät aufwachen','bis spät aufbleiben','dramatic','exclamation'),
(4198,'de','Das Loch geht tief unter Wasser. Wir sehen uns unten!','Das Seil geht tief unter Wasser. Wir sehen uns unten!','tief in einen Schacht fallen','tief im Sand graben','slang','exclamation'),
(4200,'de','Das Meer leuchtet bei Sonnenuntergang in Gold.','Das Meer leuchtet bei Sonnenuntergang in Rot.','Meer und Himmel in Gold','ein Ring aus Gold','chill','none'),
(4201,'de','Angeber! Die Bikes stehen aufrecht.','Angeber! Die Autos stehen aufrecht.','Bikes aufrecht auf einem Rad','aufrecht auf einem Stuhl sitzen','ironic','exclamation'),
(4202,'de','Sehr beschäftigte Hunde, Bauch nach oben.','Sehr beschäftigte Katzen, Bauch nach oben.','Bauch nach oben in der Sonne','ein Bauch voller Essen','ironic','understatement'),
(4203,'de','Er hat einen Hai gerettet. Held.','Er hat einen Delfin gerettet. Held.','einen gestrandeten Hai retten','einen gestrandeten Wal retten','dramatic','exaggeration'),
(4205,'de','Es trägt ein Gänseblümchen.','Es trägt eine Rose.','eine Blume tragen','einen Samen tragen','chill','none'),
(4206,'de','Hamster hat Abzeichen. Hamster ist Chef.','Hamster hat Handy. Hamster ist Chef.','das Namensabzeichen eines Hamsters','ein Polizeiabzeichen','low_iq','exaggeration'),
(4207,'de','Pizza geliefert: wahre Liebe!','Kuchen geliefert: wahre Liebe!','einen Pizzakarton liefern','Briefe mit dem Fahrrad liefern','gossip','guessing'),
(4208,'de','Dieser Hamster hat jeden Snack gegessen.','Dieses Kaninchen hat jeden Snack gegessen.','Snack um Snack','ein Snack für später','low_iq','exaggeration'),
(4209,'de','Ein Hamster liegt in tiefem Schlaf.','Eine Katze liegt in tiefem Schlaf.','ein Hamster in tiefem Schlaf','Schlaf auf kaltem Boden','chill','none'),
(4210,'de','Tadaa! Es hält Eiscreme.','Tadaa! Es hält Karotten.','zwei Eis halten','zwei Karotten halten','dramatic','exclamation'),
(4211,'de','Dieser Hamster pflegt seine Wangen besser als ich.','Dieses Kaninchen pflegt seine Wangen besser als ich.','ein Hamster tätschelt seine Wangen','ein Hamster stopft seine Wangen voll','ironic','exaggeration'),
(4212,'de','Ihre braunen Looks passen gut zusammen.','Ihre roten Looks passen gut zusammen.','passende braune Outfits','ein braunes Ledersofa','business','none'),
(4213,'de','In Rot sehen sie aus wie Königinnen!','In Blau sehen sie aus wie Königinnen!','in tiefes Rot gekleidet','Rotwein im Glas','dramatic','exaggeration'),
(4214,'de','Beide starten in hellem Blau.','Beide starten in dunklem Grün.','ein Paar in hellem Blau','hellblaue Vorhänge','chill','none'),
(4215,'de','Sie trägt Orange und Weiß.','Sie trägt Grün und Weiß.','Orange mit Weiß','eine Orange schälen','chill','none'),
(4216,'de','Ihr weißes Kleid ist umwerfend.','Ihr gelbes Kleid ist umwerfend.','ein weißes Baumwollkleid','ein weißes Hochzeitskleid','flirt','none'),
(4217,'de','Die Polizei will diesen Corgi!','Die Polizei will diese Katze!','Polizei jagt einen Hund','Polizei jagt einen Dieb','slang','exclamation'),
(4218,'de','Der Corgi holt alles aus dem Motor raus.','Die Katze holt alles aus dem Motor raus.','ein rauchender Traktormotor','ein rauchender Automotor','ironic','blaming_someone'),
(4219,'de','Das Tier fliegt schnell.','Das Tier schwimmt schnell.','auf einem fliegenden Tier reiten','ein fliegendes Tier füttern','chill','none'),
(4220,'de','Er putzt ein weißes Auto.','Er putzt ein schwarzes Auto.','den Lack putzen','das Haus putzen','business','none'),
(4221,'de','Die Echse chillt auf der Couch.','Die Echse chillt auf dem Tisch.','Müsli auf der Couch','Müsli auf dem Küchentisch','slang','none'),
(4222,'de','Yo, der Gecko winkt.','Yo, der Frosch winkt.','in die Kamera winken','mit einer Fahne winken','slang','none'),
(4223,'de','Zu scharf! Da kommt Feuer raus!','Zu süß! Da kommt Feuer raus!','scharfe rote Chilischoten','ein scharfes Curry mit Reis','dramatic','exclamation'),
(4224,'de','Eine Echse benutzt die Toilette.','Eine Echse benutzt die Küche.','eine Echse auf der Toilette','eine Echse putzt eine Toilette','chill','none'),
(4225,'de','Mittagessen ist ein Schwamm in einer Schale!','Mittagessen ist eine Karotte in einer Schale!','eine kleine weiße Schale','eine Schale Käse','low_iq','exclamation'),
(4226,'de','Das Krokodil jagt!','Der Dinosaurier jagt!','ein jagendes Krokodil','ein jagender Dinosaurier','dramatic','exclamation'),
(4227,'de','Freundlichste Polizeikontrolle ever.','Wütendste Polizeikontrolle ever.','ein freundlicher Polizist','ein freundlicher Verkäufer','slang','exaggeration'),
(4228,'de','Mit dem Hubschrauber ans Ufer, nur für Eier!','Mit dem Boot ans Ufer, nur für Eier!','am grasbewachsenen Ufer','am sandigen Ufer','dramatic','exaggeration'),
(4229,'de','Jemand befreit den Affen.','Jemand befreit den Hund.','einen eingefrorenen Affen befreien','einen eingefrorenen Vogel befreien','chill','none'),
(4230,'de','Ein Hund sitzt auf dem Fahrersitz.','Eine Katze sitzt auf dem Fahrersitz.','der Fahrersitz','der Rücksitz','chill','none'),
(4231,'de','Zwei Hunde hinterm Fenster? Verdächtig.','Zwei Katzen hinterm Fenster? Verdächtig.','ein beschlagenes Lkw-Fenster','ein beschlagenes Badezimmerfenster','gossip','guessing'),
(4232,'de','Der Delfin hat in der Show einen Ronaldo-Kick gemacht!','Die Robbe hat in der Show einen Ronaldo-Kick gemacht!','eine Delfinshow','ein Delfin im Fernsehen','dramatic','exaggeration'),
(4233,'de','Steinbrücke: stark genug für Züge.','Holzbrücke: stark genug für Züge.','eine Eisenbahnbrücke aus Stein','ein Eisenbahntunnel aus Stein','business','none'),
(4234,'de','Er hat ihren Wandschrank in Sekunden verwüstet.','Sie hat seinen Wandschrank in Sekunden verwüstet.','ein begehbarer Wandschrank','ein Küchenschrank','gossip','banter'),
(4235,'de','Super ausgeworfen. Bisher null Fische.','Super ausgeworfen. Bisher drei Fische.','eine Angelschnur auswerfen','einen langen Schatten werfen','ironic','understatement'),
(4236,'de','Sie hat die Aufmerksamkeit aller angezogen.','Er hat die Aufmerksamkeit aller angezogen.','ihre Aufmerksamkeit anziehen','neue Kunden anziehen','gossip','none'),
(4237,'de','Guck mal, der Junge ist in einer Scheune.','Guck mal, der Junge ist in einer Küche.','ein Pferd in einer Scheune','ein Pferd auf einer Weide','gossip','none'),
(4238,'de','Kein Ofen? Die haben Rippchen auf einem Stein gebraten.','Kein Ofen? Die haben Fisch auf einem Stein gebraten.','gebratene Lammrippchen','gebratenes Hähnchen','slang','none'),
(4239,'de','Bestes Taxi ever: eine Möwe über dem Hafen.','Bestes Taxi ever: ein Drache über dem Hafen.','über einen belebten Hafen fliegen','ein Hafen voller Jachten','slang','exaggeration'),
(4240,'de','Ich sehe zwei identische Hunde.','Ich sehe zwei identische Katzen.','zwei identische Huskys','zwei identische Katzen','low_iq','none'),
(4241,'de','Er fliegt durch die Wolken!','Er fliegt durch den Schnee!','durch die Wolken fliegen','einen Hubschrauber fliegen','dramatic','exclamation'),
(4242,'de','Ein Tor? Die Katze geht trotzdem durch.','Ein Tor? Der Hund geht trotzdem durch.','durch ein Tor durchgehen','einen Ball passen','slang','understatement'),
(4243,'de','Jemand bezahlt mit Karte.','Jemand bezahlt bar.','einen Hotdog bezahlen','eine Pizza bezahlen','chill','none'),
(4244,'de','Der Stier greift das Auto an!','Das Pferd greift das Auto an!','ein Stier greift ein Auto an','eine Autobatterie laden','dramatic','exclamation'),
(4245,'de','Die rutschen umsonst!','Die fahren umsonst Ski!','eine Wasserrinne entlangrutschen','einen verschneiten Hügel hinunterrutschen','dramatic','cheap_quality'),
(4246,'de','Der Pfau ist ganz in Blau.','Der Pfau ist ganz in Grün.','ein Pfau in Blau','ein Papagei in Blau','chill','none'),
(4247,'de','Jungs springen in einen Brunnen!','Jungs springen in einen See!','Jungs springen in einen Brunnen','Jungs trinken aus einem Brunnen','dramatic','exclamation'),
(4248,'de','Die Welle im überdachten Becken hat diesmal gewonnen.','Die Welle im Ozean hat diesmal gewonnen.','ein überdachtes Wellenbad','Schwimmunterricht in der Halle','chill','none'),
(4249,'de','Ich sitze auf dem Rücken eines Drachen!','Ich sitze auf dem Rücken eines Pferdes!','der Rücken eines Drachen','der Rücken eines Pferdes','dramatic','exclamation'),
(4250,'de','Der Hund hat die Lagerhalle verwüstet.','Die Katze hat die Lagerhalle verwüstet.','ein Hund in einer Lagerhalle','eine Lagerhalle voller Autos','gossip','blaming_someone'),
(4251,'de','Sein Platz? Ein leeres Regalfach.','Sein Platz? Ein volles Regalfach.','Platz für seine Klamotten','Platz für ein Auto','ironic','understatement'),
(4252,'de','Teamwork: Einer schlürft, einer schrubbt den Beton.','Teamwork: Einer schlürft, einer schrubbt den Pool.','eine Betonterrasse schrubben','frischen Beton gießen','ironic','exaggeration'),
(4253,'de','Sie waschen den Schlamm-Mann.','Sie waschen den Schlamm-Hund.','dicken Schlamm abwaschen','das Geschirr abwaschen','low_iq','exaggeration'),
(4254,'de','Eine Taube sitzt auf der Theke.','Eine Taube sitzt auf dem Dach.','eine Taube auf der Theke','eine Theke in der Bank','chill','none'),
(4256,'de','Das Känguru wird gekratzt und liebt es.','Der Koala wird gekratzt und liebt es.','ein Känguru kratzen','an einer Autotür kratzen','chill','guessing'),
(4257,'de','Die Schildkröte steckt in einer engen Umarmung.','Der Fisch steckt in einer engen Umarmung.','eine enge Panda-Umarmung','eine enge Umarmung unter Wasser','chill','none'),
(4258,'de','Ein Rehkitz sitzt in einer Rutsche aus Stahl.','Ein Rehkitz sitzt in einer Rutsche aus Holz.','eine lange Stahlrutsche','eine lange Stahlbrücke','chill','none'),
(4259,'de','Dieses Schaf hat ein Montagsgesicht.','Diese Kuh hat ein Montagsgesicht.','ein wütendes Schafgesicht','ein fröhliches Schafgesicht','ironic','cliche'),
(4260,'de','Der Hund ignoriert die Gestalt.','Der Hund bellt die dunkle Gestalt an.','eine Gestalt in der Tür','eine Gestalt am Fenster','ironic','guessing'),
(4261,'de','Ein sonniger Tag am Pool.','Ein regnerischer Tag am Pool.','ein sonniger Gartenpool','ein sonniger Strand','chill','none'),
(4262,'de','Der Strand gehört ganz der Tierwelt.','Der Strand gehört ganz den Badegästen.','Tierwelt am Ufer','Tierwelt im Zoo','chill','exaggeration'),
(4263,'de','Wow! Die Vögel bewundern sie.','Wow! Die Vögel ignorieren sie.','einen rosa Vogel bewundern','einen rosa Kuchen bewundern','gossip','exclamation'),
(4264,'de','Straßen-Volleyball, ohne Netz.','Beachvolleyball, ohne Netz.','Volleyball auf einer ruhigen Straße','Volleyball am Strand','chill','understatement'),
(4265,'de','Eine Umarmung beruhigt den Papagei.','Ein Lied beruhigt den Papagei.','einen wütenden Papagei beruhigen','ein weinendes Baby beruhigen','chill','none'),
(4266,'de','Was für ein energiegeladener Hund!','Was für eine energiegeladene Katze!','ein energiegeladener Hund rennt','ein energiegeladener Hund schwimmt','dramatic','exclamation'),
(4267,'de','Neuer Look: Der Hund ist so ordentlich.','Neuer Look: Die Katze ist so ordentlich.','ein ordentliches rundes Fell','eine ordentliche Reihe Hunde','gossip','none'),
(4268,'de','Der Hund ist der größere Fan, kein Witz.','Die Katze ist der größere Fan, kein Witz.','ein Hund als Fußballfan','ein Ventilator für heiße Tage','slang','exaggeration'),
(4269,'de','Der trockene Boden trinkt schnell.','Der trockene Sand trinkt schnell.','trockenen Boden gießen','trockenes Laub fegen','dramatic','exaggeration'),
(4270,'de','Es bremst für eine Ente ab.','Es bremst für einen Hund ab.','für eine Ente abbremsen','an der Ampel abbremsen','chill','none'),
(4272,'de','Sie legt noch mehr goldenen Schmuck an!','Sie legt noch mehr silbernen Schmuck an!','goldene Kreolen','eine goldene Medaille','dramatic','exclamation'),
(4273,'de','Hier gab es einen Zusammenstoß.','Hier gab es ein Konzert.','ein Zusammenstoß an einer Kreuzung','ein Zusammenstoß auf der Autobahn','dramatic','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
