begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(4274,'de','Nur ein „kleiner“ Schaden.','Nur ein „bisschen“ Schnee.','Schaden an einem geparkten Auto','Schaden an einem Fahrrad','ironic','understatement'),
(4275,'de','Sie beschwert sich über das Auto.','Sie beschwert sich über das Fahrrad.','sich über einen Unfall beschweren','sich über das Essen beschweren','dramatic','none'),
(4276,'de','Eine betagte Dame geht nach Hause.','Ein betagter Mann geht nach Hause.','eine betagte Frau beim Spazieren','eine betagte Frau beim Tanzen','chill','none'),
(4277,'de','Der Buchhalter hat es gefunden!','Der Buchhalter hat es verloren!','ein Buchhalter mit Belegen','ein Buchhalter im Urlaub','dramatic','exclamation'),
(4279,'de','Niemand kam ins Theater!','Niemand kam ins Stadion!','eine Theaterbühne','eine Theaterkarte','dramatic','exaggeration'),
(4280,'de','Dreharbeiten: Sie ist in Tränen aufgelöst.','Dreharbeiten: Sie lacht sich kaputt.','Dreharbeiten für eine traurige Szene','Dreharbeiten für eine Kochshow','dramatic','none'),
(4281,'de','Die Veränderung der Farbe ist der Wahnsinn.','Die Veränderung der Größe ist der Wahnsinn.','eine Veränderung der Farbe','ein Wechsel der Kleidung','chill','none'),
(4282,'de','Sie haben einen Hund aus dem Tierheim geholt.','Sie haben eine Katze aus dem Tierheim geholt.','ein Hund aus dem Tierheim','Schutz vor dem Regen','chill','none'),
(4283,'de','Für ihr Kochen gibt''s Applaus!','Für ihr Singen gibt''s Applaus!','ein Kochkurs','ein Kochwettbewerb','dramatic','exclamation'),
(4284,'de','Er haut in aller Eile ab!','Er haut im Auto ab!','die morgendliche Eile','die Rushhour','dramatic','exclamation'),
(4286,'de','Sie fächelt sich Luft zu.','Sie fächelt der Katze Luft zu.','sich bei Hitze Luft fächeln','einem Grillfeuer Luft fächeln','chill','none'),
(4287,'de','Sie betrachten die Wohnung.','Sie betrachten das Auto.','eine leere Wohnung betrachten','einen Gebrauchtwagen betrachten','business','none'),
(4288,'de','Sie konzentriert sich auf die Zielscheibe.','Sie konzentriert sich auf die Kamera.','drei runde Zielscheiben','eine Zielscheibe an der Wand','business','none'),
(4289,'de','Die Kälte drückt sie zurück!','Die Hitze drückt sie zurück!','ein Schwall Kälte','ein kaltes Getränk','dramatic','exclamation'),
(4290,'de','Kalte Luft kühlt ihn ab.','Kaltes Bier kühlt ihn ab.','sich unter der Lüftung abkühlen','ein Getränk mit Eis kühlen','chill','none'),
(4291,'de','Er kühlt sich die Stirn. So heiß!','Er kühlt sich die Füße. So heiß!','ein Glas an seiner Stirn','ein Kuss auf die Stirn','dramatic','exclamation'),
(4292,'de','Eine Brise bewegt ihr Haar.','Ein Ventilator bewegt ihr Haar.','eine Brise auf der Wiese','eine Brise am Meer','chill','none'),
(4293,'de','Der Jet hebt ab!','Der Jet landet!','ein abhebender Jet','ein Wasserstrahl','dramatic','exclamation'),
(4294,'de','Das Flugzeug fliegt echt tief!','Der Drachen fliegt echt tief!','tief über ihm fliegen','tief über dem Meer fliegen','dramatic','exclamation'),
(4295,'de','Schau, er fotografiert ein Flugzeug!','Schau, er fotografiert ein Kamel!','einen landenden Jet fotografieren','den Wüstensand fotografieren','gossip','exclamation'),
(4296,'de','Erhobene Leuchtstäbe senden ein Signal.','Erhobene Flaggen senden ein Signal.','ein Signal an den Piloten','ein schwaches Handysignal','nerd','none'),
(4297,'de','Die Abflugtafel ist riesig!','Die Ankunftstafel ist riesig!','eine riesige Abflugtafel','eine Abreise mit dem Zug','dramatic','exclamation'),
(4299,'de','Er reagiert auf Katzen. Der Arme.','Er reagiert auf Hunde. Der Arme.','auf eine Katze reagieren','auf schlechte Nachrichten reagieren','gossip','none'),
(4300,'de','Überall Müll!','Überall Blumen!','Tonnen voller Müll','Müll am Strand','dramatic','exclamation'),
(4301,'de','Er quetscht sich durch eine Lücke.','Er krabbelt durch eine Lücke.','sich durch eine enge Lücke quetschen','eine Lücke im Zaun','chill','none'),
(4302,'de','Ein Notfall im Regen.','Ein Notfall im Schnee.','ein Notfall in der Nacht','eine Notausgangstür','chill','none'),
(4303,'de','Ein medizinisches Team überquert die Straße.','Ein Polizeiteam überquert die Straße.','ein medizinisches Team beim Überqueren','ein medizinischer Test in der Schule','chill','none'),
(4304,'de','Er hat den Football geworfen, stark.','Er hat den Football gekickt, stark.','ein ovaler Football in der Luft','ein runder Ball auf dem Rasen','slang','none'),
(4305,'de','Der Junge hat einen riesigen Burger bekommen.','Der Junge hat eine riesige Pizza bekommen.','ein Junge kriegt einen Burger','ein Junge brät einen Burger','chill','exaggeration'),
(4306,'de','Sie verlassen das Gefängnis!','Sie gehen ins Gefängnis!','das Gefängnis verlassen','ein Gefängnis besuchen','dramatic','exclamation'),
(4307,'de','Oben wehen vier Banner.','Oben wehen zwei Banner.','Banner über der Tribüne','Banner über dem Laden','chill','none'),
(4308,'de','Diese Anhänger hören nie auf zu singen.','Diese Anhänger hören nie auf zu tanzen.','singende Anhänger','schlafende Anhänger','dramatic','exaggeration'),
(4309,'de','Die Hymne bringt sie zum Weinen.','Das Tor bringt sie zum Weinen.','die Hymne singen','die Hymne schreiben','dramatic','none'),
(4310,'de','Der emotionale Spieler weint!','Der emotionale Spieler lacht!','ein emotionales Teamlied','ein emotionales Hochzeitslied','dramatic','exclamation'),
(4311,'de','Sogar Oma spielt mit dem jungen Mann.','Sogar Opa spielt mit dem jungen Mann.','ein junger Basketballspieler','ein junger Tennisspieler','gossip','none'),
(4312,'de','Er ist laut, aber keiner hört''s.','Er ist leise, aber keiner hört''s.','ein lauter Ruf','eine laute Party','ironic','none'),
(4313,'de','Die ganze Kneipe singt!','Die ganze Kneipe pennt!','Karaoke in einer Kneipe','ein Quizabend in der Kneipe','slang','exclamation'),
(4314,'de','Vier Orangen liegen in der Schale.','Vier Äpfel liegen in der Schale.','eine Schale Orangen','ein Glas Orangensaft','chill','none'),
(4315,'de','Der Preis steigt und steigt!','Der Preis sinkt und sinkt!','der Preis einer Wohnung','der Preis eines Autos','dramatic','exclamation'),
(4317,'de','Er entschuldigt sich mit Kaffee.','Er entschuldigt sich mit Kuchen.','sich für Verschüttetes entschuldigen','sich fürs Zuspätkommen entschuldigen','chill','none'),
(4318,'de','Sein Applaus wird immer lauter.','Sein Lachen wird immer lauter.','Applaus für den Künstler','Applaus für das Team','chill','none'),
(4320,'de','Er zeichnet einen Bauplan.','Er zeichnet ein Gesicht.','einen Bauplan fürs Haus zeichnen','einen Urlaubsplan machen','chill','none'),
(4321,'de','Sie repariert das Modell einer Stadt.','Sie repariert das Modell eines Autos.','ein Modell einer Stadt','ein Model auf dem Laufsteg','nerd','none'),
(4322,'de','Was für ein schöner Tanz!','Was für ein schönes Auto!','ein Tango-Tanz','ein Tanzkurs','flirt','exclamation'),
(4323,'de','Coole Tanzmoves in der Gasse!','Coole Biketricks in der Gasse!','eine schmale bemalte Gasse','eine Überholspur','flirt','exclamation'),
(4324,'de','Riesiger Gletscher, winziger Mensch.','Riesiger Gletscher, winziger Pinguin.','eine riesige Wand aus Eis','eine riesige Menschenmenge','dramatic','none'),
(4325,'de','Fakt: Die Rinder grasen.','Fakt: Die Pferde grasen.','grasende Rinder in der Ebene','Rinder im Stall','nerd','none'),
(4326,'de','Das Holz brennt.','Die Kohle brennt.','brennendes Holz','Holz hacken','chill','none'),
(4327,'de','Alle lieben sein Barbecue!','Alle lieben seinen Salat!','ein Sunset-Barbecue mit Freunden','ein Barbecue im Regen','gossip','exaggeration'),
(4328,'de','Der Teppich hat Fransen.','Der Teppich hat ein Loch.','ein Teppich mit Fransen','ein Teppich an der Wand','chill','none'),
(4329,'de','Sie sitzen auf Möbeln.','Sie sitzen auf dem Boden.','auf weichen Möbeln sitzen','die Möbel tragen','chill','none'),
(4330,'de','Die Soldaten marschieren.','Die Soldaten tanzen.','im Gleichschritt marschierende Soldaten','nachts marschierende Soldaten','chill','none'),
(4331,'de','Das ist ein sehr präziser Marsch.','Das ist ein sehr chaotischer Marsch.','ein Marsch die Straße entlang','ein Marsch im Wald','business','none'),
(4332,'de','Er verhaftet einen Einbrecher mit Gummihühnern.','Er verhaftet einen Einbrecher mit Golduhren.','einen Einbrecher verhaften','einen Polizisten verhaften','gossip','none'),
(4334,'de','Sie malt in ihrem Atelier.','Sie tanzt in ihrem Atelier.','das volle Atelier einer Malerin','ein Tonstudio','chill','none'),
(4335,'de','Der ganze Saal will was fragen!','Der ganze Saal will gehen!','den Redner etwas fragen','nach Geld fragen','dramatic','exaggeration'),
(4336,'de','Er liest die Anleitung, sie baut.','Er liest die Zeitung, sie baut.','die Anleitung lesen','die Anleitung ignorieren','gossip','banter'),
(4337,'de','Sie ruft an und rennt dabei!','Sie ruft an und tanzt dabei!','beim Laufen anrufen','beim Autofahren anrufen','dramatic','exclamation'),
(4338,'de','Der Automat spuckt Bargeld aus.','Der Automat spuckt Karten aus.','herausfliegendes Bargeld','Bargeld im Portemonnaie','slang','none'),
(4339,'de','Ihre Bankkarte funktioniert! Danke, Bank!','Ihre Bankkarte ist kaputt! Danke, Bank!','eine Reihe Bankautomaten','eine Bank am Fluss','slang','exclamation'),
(4340,'de','Die Möwen wollen seine Pommes!','Die Hunde wollen seine Pommes!','seine Pommes vor Möwen schützen','Pommes mit Freunden teilen','dramatic','exclamation'),
(4341,'de','Er flieht vor den Möwen!','Er flieht vor den Hunden!','vor den Möwen fliehen','vor einem Sturm fliehen','dramatic','exclamation'),
(4342,'de','Sie schleppt eine schwere Truhe.','Sie schleppt einen schweren Stuhl.','eine schwere Truhe schleppen','ein Fischernetz schleppen','chill','none'),
(4343,'de','Überall Lachen!','Überall Tränen!','Lachen im Spielzimmer','Lachen im Kino','dramatic','exclamation'),
(4344,'de','Mehl, Gebäck und Zuneigung.','Mehl, Pizza und Zuneigung.','Zuneigung in der Küche','Zuneigung zu einem Haustier','chill','none'),
(4345,'de','Geschenke, Kuchen, pure Freude!','Geschenke, Pizza, pure Freude!','Freude auf einer Geburtstagsparty','Freude auf einer Hochzeitsfeier','dramatic','exclamation'),
(4346,'de','Yo, Kängurus hüpfen vorbei.','Yo, Kaninchen hüpfen vorbei.','vorbeihüpfende Kängurus','auf einem Bein hüpfen','slang','none'),
(4347,'de','Ein Boot befördert sie ans andere Ufer.','Ein Bus befördert sie ans andere Ufer.','Menschen übers Wasser befördern','Waren flussaufwärts befördern','chill','none'),
(4348,'de','Sie sieht so athletisch aus!','Er sieht so athletisch aus!','eine athletische Surferin','ein Treffen des Athletikclubs','flirt','exclamation'),
(4349,'de','Dieser Wächter kann echt surfen.','Dieser Wächter kann echt Ski fahren.','ein Wächter auf einem Surfbrett','ein Wächter auf einem Pferd','flirt','none'),
(4350,'de','Jede Kuh hat eine große Glocke.','Jede Kuh hat ein großes Horn.','eine Glocke an einer Kuh','eine Glocke an einer Kirche','chill','none'),
(4351,'de','Sie lehnt am Marmor.','Sie lehnt am Klavier.','ein poliertes Marmorgeländer','eine Gartenstatue aus Marmor','chill','none'),
(4352,'de','Sie macht eine scharfe Kurve.','Sie macht einen hohen Sprung.','eine scharfe Kurve auf Skiern','eine falsche Abzweigung auf Skiern','chill','none'),
(4353,'de','Tolles Dessert, Chef.','Toller Salat, Chef.','ein Schokokuchen als Dessert','ein Dessert aus frischem Obst','flirt','none'),
(4354,'de','Ihr Tritt lässt Blätter fliegen.','Ihr Tritt lässt Eicheln fliegen.','ein Tritt ins Laub','ein Tritt gegen einen Fußball','chill','none'),
(4355,'de','Ein bezauberndes Baby strampelt mit den Füßen.','Ein bezaubernder Welpe strampelt mit den Füßen.','ein bezauberndes lächelndes Baby','ein bezauberndes schlafendes Kätzchen','chill','none'),
(4356,'de','Schmerzender Rücken? Trotzdem Huckepack!','Schmerzender Nacken? Trotzdem Huckepack!','einen schmerzenden Rücken reiben','ein schmerzender Hals im Bett','slang','exclamation'),
(4357,'de','In ihren Rucksack aus Segeltuch würde ein Sofa passen.','In ihren Rucksack aus Leder würde ein Sofa passen.','ein großer Rucksack aus Segeltuch','eine Leinwand zum Malen','chill','exaggeration'),
(4358,'de','Die Tasche sieht ein bisschen schwer aus.','Das Fahrrad sieht ein bisschen schwer aus.','ein schwerer Rucksack','ein schweres Gewitter','ironic','understatement'),
(4359,'de','Die Dosen fallen raus.','Die Eier fallen raus.','aus der Tüte fallende Dosen','eine Dose Farbe','chill','none'),
(4360,'de','Sie hat mehr als eine Handtasche gekauft.','Sie hat mehr als eine Handtasche verkauft.','eine neue Handtasche vorführen','ihre Handtasche verlieren','ironic','understatement'),
(4361,'de','Sie kauft ein wie ein Profi.','Er kauft ein wie ein Profi.','mit vielen Tüten einkaufen','Lebensmittel einkaufen','slang','exaggeration'),
(4362,'de','Ein Koffer liegt auf dem Förderband.','Ein Koffer liegt im Bus.','ein laufendes Förderband fürs Gepäck','ein Ledergürtel','chill','none'),
(4363,'de','Sein Rucksack ist endlich erschienen!','Sein Koffer ist endlich erschienen!','auf dem Band erscheinen','im Fernsehen erscheinen','dramatic','exclamation'),
(4364,'de','Teig rein, Croissants raus!','Teig rein, Pizzen raus!','Kugeln aus rohem Teig','Teig für einen Pizzaboden','slang','exclamation'),
(4365,'de','So viel frisches Brot!','So viel frischer Fisch!','frisches Brot aus dem Ofen','frischer Fisch aus dem Meer','dramatic','exclamation'),
(4366,'de','Er liebt seine Arbeit.','Er hasst seine Arbeit.','Arbeit in einer Bäckerei','Arbeit in einer Bank','chill','none'),
(4367,'de','Laken trocknen im Wind.','Laken trocknen auf einem Boot.','im Wind trocknende Laken','auf dem Gestell trocknendes Geschirr','chill','none'),
(4368,'de','Sie beleuchtet alles mit Glühbirnen.','Sie beleuchtet alles mit Kerzen.','mit einer Lichterkette beleuchten','eine Kerze anzünden','chill','none'),
(4369,'de','Zu viel Klebeband? Vielleicht ein bisschen.','Zu viel Kleber? Vielleicht ein bisschen.','in weißes Klebeband gewickelt','Klebeband auf einem Karton','ironic','understatement'),
(4370,'de','Der große Tresor ist offen.','Der große Tresor ist zu.','ein offener Banktresor','ein sicheres Versteck','business','none'),
(4371,'de','Die Eingangshalle der Bank ist riesig.','Die Eingangshalle der Bank ist winzig.','eine Eingangshalle aus Marmor','eine volle Hotellobby','business','none'),
(4373,'de','Die Crew hat sich auf einem Dach versammelt.','Die Crew hat sich auf einem Boot versammelt.','auf dem Dach versammelte Freunde','Holz fürs Feuer sammeln','slang','none'),
(4374,'de','Der Barbier benutzt einen elektrischen Haarschneider.','Der Barbier benutzt einen elektrischen Ventilator.','ein elektrischer Haarschneider','eine elektrische Gitarre','chill','none'),
(4375,'de','Die Rinde ist rau und rissig.','Die Rinde ist glatt und sauber.','raue Baumrinde','raue See','nerd','none'),
(4376,'de','Der kleinste Hund macht den größten Lärm!','Die kleinste Katze macht den größten Lärm!','ganz viel Lärm','ganz viel Musik','dramatic','exaggeration'),
(4377,'de','Der Keller hat ein Kino!','Der Keller hat einen Pool!','ein Heimkino im Keller','ein Keller voller Wasser','dramatic','exclamation'),
(4378,'de','Zwei Duschen in einem Bad? Wow!','Zwei Toiletten in einem Bad? Wow!','eine Dusche an der Wand','eine Dusche im Garten','dramatic','exclamation'),
(4379,'de','Die Wanne schäumt über!','Das Waschbecken schäumt über!','die Wanne schrubben','eine Packung Eiscreme','dramatic','exclamation'),
(4380,'de','Sie füllt die Badewanne.','Sie füllt das Waschbecken.','eine Wanne mit Schaum füllen','ein Glas mit Wasser füllen','chill','none'),
(4381,'de','Ein warmer Tag am Strand.','Ein kalter Tag am Strand.','ein warmer, sonniger Strand','ein warmer Wintermantel','chill','none'),
(4382,'de','Der Bär schnappt sich einen Lachs.','Der Bär schnappt sich einen Vogel.','ein springender Lachs','ein Lachs auf dem Teller','chill','none'),
(4383,'de','Was für ein dicker Bart!','Was für ein dünner Bart!','ein dicker schwarzer Bart','ein dicker Wintermantel','dramatic','exclamation'),
(4385,'de','Das große Bett kostet 20.000 Euro. „Billig.“','Das große Bett kostet 200 Euro. „Billig.“','20.000 Euro kosten','50 Cent kosten','ironic','understatement'),
(4386,'de','Poster bedecken sein ganzes Zimmer.','Landkarten bedecken sein ganzes Zimmer.','Wände voller Poster','Poster am Kühlschrank','chill','exaggeration'),
(4387,'de','Wir vergleichen drei Schlafzimmer.','Wir vergleichen drei Küchen.','drei Schlafzimmer vergleichen','drei Küchen vergleichen','business','none'),
(4388,'de','Eine Biene bestäubt Gänseblümchen.','Ein Vogel bestäubt Gänseblümchen.','eine Biene über Gänseblümchen','eine Gänseblümchenkette','nerd','none'),
(4389,'de','Es hat ohne ihn angefangen. Ups.','Der Bus ist ohne ihn abgefahren. Ups.','den Anfang verpassen','ein Auto starten','ironic','understatement'),
(4390,'de','Die Aufregung ist echt!','Die Langeweile ist echt!','Aufregung vor einem Konzert','Aufregung vor einer Prüfung','slang','exclamation'),
(4391,'de','Allein mit einer ganzen Pizza? Ja!','Allein mit einem ganzen Kuchen? Ja!','allein zu Haus mit Pizza','allein im Restaurant','slang','exclamation'),
(4392,'de','Was für ein Sturz im Park!','Was für ein Sturz in der Küche!','ein Sturz über eine Bank','ein Sturz von der Leiter','dramatic','exclamation'),
(4393,'de','Die alten Jungs plaudern.','Die alten Jungs prügeln sich.','auf einer Bank plaudern','am Telefon plaudern','slang','none'),
(4394,'de','Sie biegt alles!','Sie zerbricht alles!','einen Ast biegen','einen Löffel biegen','dramatic','exaggeration'),
(4395,'de','Sie greift ihren Gegner an.','Sie umarmt ihren Gegner.','ein hinterhältiger Gegner','ein Gegner im Ring','dramatic','none'),
(4396,'de','Ihr Move hat ihn total schockiert!','Ihr Move hat ihn total gelangweilt!','von ihrem Move schockiert','vom Preis schockiert','gossip','exclamation'),
(4397,'de','Er fährt in Amsterdam Rad.','Er fährt im Wald Rad.','an einer Gracht entlang Rad fahren','am Strand entlang Rad fahren','chill','none'),
(4398,'de','Überall Werbung!','Überall Bäume!','riesige leuchtende Werbung','Werbung in der Zeitung','dramatic','exaggeration'),
(4399,'de','Sie träumt von einem Burger.','Sie träumt von einer Pizza.','von einem großen Haus träumen','nachts im Bett träumen','chill','none'),
(4400,'de','Sie hat Vögel auf dem Meer erspäht.','Sie hat Schiffe auf dem Meer erspäht.','Vögel in der Ferne erspähen','einen Fehler entdecken','chill','none'),
(4401,'de','Sie schaut auf das ferne Ufer.','Sie schaut auf die ferne Stadt.','das ferne Seeufer','ein fernes Land','chill','none'),
(4402,'de','Apfel, Burger, Melone: krasser Appetit!','Apfel, Pizza, Melone: krasser Appetit!','riesiger Appetit beim Picknick','überhaupt kein Appetit','slang','exaggeration'),
(4403,'de','Nur noch eine Schicht.','Nur noch ein Kissen.','Schicht um Schicht Decken','eine Schicht Neuschnee','ironic','understatement'),
(4404,'de','Er hat eine Verletzung am Finger.','Er hat eine Verletzung am Knie.','eine Verletzung am Finger','eine Sportverletzung','chill','none'),
(4405,'de','Sein Freund ist eine große Hilfe.','Sein Hund ist eine große Hilfe.','Hilfe von einem Freund','Hilfe bei den Hausaufgaben','chill','none'),
(4406,'de','Der Künstler glättet Linien.','Der Künstler zeichnet Linien.','harte Linien glätten','ein Bettlaken glätten','chill','none'),
(4407,'de','Spinat hält ihn gesund.','Schokolade hält ihn gesund.','ein gesunder junger Mann','ein gesundes Bankkonto','chill','none'),
(4408,'de','Der Smoothie? Geschmack: perfekt!','Der Kaffee? Geschmack: perfekt!','der Geschmack eines Smoothies','guter Geschmack bei Musik','slang','exclamation'),
(4409,'de','Die ganze Party ist blind!','Die ganze Party schläft!','blind für ein Partyspiel','ein Blind Date','low_iq','exaggeration'),
(4410,'de','Wettbewerb im Anstarren! Nicht blinzeln!','Wettbewerb im Essen! Nicht blinzeln!','ein Wettbewerb im Anstarren','ein Gesangswettbewerb','slang','exclamation'),
(4411,'de','Die Behandlung ist ein Pflaster.','Die Behandlung ist eine Spritze.','Behandlung einer Blase','Behandlung gegen Kopfschmerzen','chill','none'),
(4412,'de','Schafe blockieren die Straße!','Kühe blockieren die Straße!','eine Bergstraße blockieren','eine Telefonnummer blockieren','dramatic','exclamation'),
(4413,'de','Sie liebt den Geruch.','Sie hasst den Geruch.','der Geruch von Blüten','der Geruch von Kaffee','chill','none'),
(4414,'de','Bergauf ist es ein echter Kampf.','Bergab ist es ein echter Kampf.','ein Kampf gegen den Wind','ein Kampf mit den Hausaufgaben','dramatic','none'),
(4415,'de','Hör auf! Zu viele Komplimente!','Hör auf! Zu viele Fragen!','rot werden bei einem Kompliment','ein Kompliment an den Koch','dramatic','exclamation'),
(4416,'de','Grünes Licht, Ticket passt!','Grünes Licht, Reisepass passt!','ein Ticket scannen','ein Zugticket kaufen','slang','exclamation'),
(4417,'de','Reisen mit Tram, Boot, Flugzeug.','Reisen mit Bus, Boot, Flugzeug.','Reisen mit dem Boot','Reisen mit dem Auto','chill','none'),
(4419,'de','Sie rudert mit ihrem Welpen.','Sie rudert mit ihrem Kätzchen.','auf einem ruhigen Teich rudern','auf wilder See rudern','chill','none'),
(4420,'de','Die Illustration zeigt einen Knochen.','Die Illustration zeigt eine Hand.','eine Illustration eines Knochens','eine Illustration einer Hand','nerd','none'),
(4421,'de','Sie hält einen kleinen Knochen.','Sie hält einen kleinen Stein.','ein langer Oberschenkelknochen','ein Hundeknochen','chill','none'),
(4423,'de','Die Barriere ist oben. Lauf!','Die Barriere ist unten. Lauf!','eine hochgeklappte Barriere','eine Sprachbarriere','dramatic','exclamation'),
(4424,'de','Die Grenze ist nur ein Streifen.','Die Grenze ist nur ein Zaun.','die Grenze zu Fuß überqueren','eine Umrandung um ein Bild','nerd','understatement'),
(4426,'de','Die Besprechung lief gut.','Die Besprechung lief schlecht.','eine Besprechung im Büro','eine Besprechung im Park','business','none'),
(4427,'de','Sie verbeugen sich bei einer Zeremonie.','Sie essen bei einer Zeremonie.','eine förmliche Zeremonie mit Verbeugung','eine Hochzeitszeremonie','business','none'),
(4429,'de','Ramen in einem Nudelrestaurant!','Ramen in einem Burgerrestaurant!','ein Nudelrestaurant','eine Restaurantküche','dramatic','exclamation'),
(4430,'de','Das Kind ist so glücklich!','Das Kind ist so traurig!','ein schnell rennendes Kind','ein still sitzendes Kind','dramatic','exclamation'),
(4431,'de','Er hat gepunktet, jetzt will der Hund ran.','Er hat gepunktet, jetzt will die Katze ran.','mit einem Tor punkten','mit einem Korb punkten','gossip','guessing'),
(4432,'de','Alle ignorieren ihn.','Alle umarmen ihn.','den Verkäufer ignorieren','einen Anruf ignorieren','dramatic','none'),
(4433,'de','Sie wird diesen Strauß lieben.','Sie wird diesen Kuchen lieben.','ein Strauß Rosen','ein Schlüsselbund','flirt','guessing'),
(4434,'de','Der Jahrmarkt macht zu zweit Spaß.','Der Zoo macht zu zweit Spaß.','ein Date auf dem Jahrmarkt','ein fairer Preis','flirt','none'),
(4435,'de','Krass, eine Ausstellung über Gehirne!','Krass, eine Ausstellung über Autos!','eine Ausstellung über Gehirne','eine Kunstausstellung','slang','exclamation'),
(4436,'de','Ein Schuss wie von Ronaldo – riesiger Jubel!','Ein Kopfball wie von Ronaldo – riesiger Jubel!','Jubel für den Schuss','Jubel für die Sängerin','dramatic','exclamation'),
(4438,'de','Sie führt die Parade an!','Sie führt den Marathon an!','eine Karnevalsparade','eine Militärparade','gossip','exaggeration'),
(4439,'de','Das Fest ist laut!','Das Fest ist leise!','ein Straßenfest','ein Filmfestival','dramatic','exclamation'),
(4440,'de','Sie schlägt auf Beton!','Sie schlägt auf Glas!','auf einen Stapel Platten schlagen','ein Streichholz anzünden','dramatic','none'),
(4441,'de','Wow, ihr Atem macht Wolken.','Wow, ihr Atem macht Blasen.','eine Wolke aus warmem Atem','ein Hauch frischer Luft','low_iq','none'),
(4442,'de','Ihre Schuhe sind weiß.','Ihre Schuhe sind rot.','schlichte weiße Schuhe','weiße Laufschuhe','chill','none'),
(4443,'de','Die Hochzeit beginnt und alle drehen sich um.','Die Hochzeit endet und alle drehen sich um.','Einzug bei der Hochzeit','Tanzen auf der Hochzeitsfeier','chill','none'),
(4445,'de','Wow, diese Brücke ist riesig!','Wow, dieses Boot ist riesig!','eine rote Hängebrücke','eine Brücke über eine Straße','dramatic','exclamation'),
(4446,'de','Die Kneipe hat mattiertes Glas.','Die Kneipe hat kaputtes Glas.','Scheiben aus Milchglas','ein Glas Rotwein','chill','none'),
(4447,'de','Heute nur ein bisschen nass.','Heute nur ein bisschen verschneit.','eine nasse Bushaltestelle','ein nasser Hund','ironic','understatement'),
(4448,'de','Sie packt den Griff.','Sie packt die Leiter.','ein langer blauer Griff','ein Türgriff','chill','none'),
(4450,'de','Seine Latzhose hat Flicken.','Seine Stiefel haben Flicken.','Flicken auf der Latzhose','ein Fleckchen Gras','chill','none'),
(4451,'de','Zwei Teenager zocken, voll intensiv.','Zwei Teenager tanzen, voll intensiv.','Teenager beim Zocken','Teenager beim Fußballspielen','slang','exaggeration'),
(4452,'de','Das Schienbein muss echt wehtun!','Der Arm muss echt wehtun!','ein Schienbein, das wehtut','ein Arm, der wehtut','dramatic','guessing'),
(4454,'de','Sie kippt die Äpfel aus.','Sie kippt die Eier aus.','einen Eimer Äpfel auskippen','dem Kellner Trinkgeld geben','chill','none'),
(4455,'de','Er arbeitet auf dem Grundstück.','Er schläft auf dem Grundstück.','ein Baugrundstück','ein Campingplatz','chill','none'),
(4456,'de','Der Turm ist sehr modern.','Der Turm ist sehr alt.','ein moderner Glasturm','ein modernes Handy aus Glas','business','none'),
(4457,'de','Sie kauert am Feuer.','Sie kauert am Auto.','über einem Feuer kauern','hinter einem Felsen kauern','chill','none'),
(4458,'de','Totale Katastrophe in der Küche!','Totale Katastrophe im Garten!','eine verqualmte Küchenkatastrophe','eine Naturkatastrophe im Fernsehen','dramatic','exclamation'),
(4459,'de','Ein bisschen Verbrennen gehört dazu, kein Problem.','Ein bisschen Regen gehört dazu, kein Problem.','das Verbrennen eines Marshmallows','das Verbrennen alter Briefe','ironic','understatement'),
(4460,'de','Sie wärmt sich die Handflächen.','Sie wärmt sich die Füße.','Handflächen zum Feuer gestreckt','Palmen am Strand','chill','none'),
(4461,'de','Sie graben. Er kann nicht entkommen.','Sie schwimmen. Er kann nicht entkommen.','im Sand graben','im Garten graben','dramatic','guessing'),
(4462,'de','Eine weiße Rose bei der Beerdigung.','Eine rote Rose bei der Beerdigung.','eine Beerdigung auf dem Friedhof','eine Beerdigung in der Kirche','chill','none'),
(4463,'de','Der Fahrer begrüßt sie.','Der Pilot begrüßt sie.','Leute im Bus begrüßen','Leute im Flugzeug begrüßen','chill','none'),
(4464,'de','Sie liest, sie wartet nicht.','Sie isst, sie wartet nicht.','an der Bushaltestelle lesen','im Zug lesen','ironic','guessing'),
(4465,'de','Er ist nach oben gegangen, bester Tag ever!','Er ist nach unten gegangen, bester Tag ever!','oben im Bus','oben im Haus','dramatic','exaggeration'),
(4466,'de','Alle an Bord des Tourbusses!','Alle an Bord der Fähre!','an Bord eines Stadtbusses','an Bord eines Kreuzfahrtschiffs','dramatic','cliche'),
(4467,'de','Schinken hängen an der Wand.','Hüte hängen an der Wand.','ganze Schinken an Haken','ein Schinkenbrot','chill','none'),
(4468,'de','Der Gepäckträger trägt ganz schön viel.','Der Gepäckträger hält gar nichts.','ein schwer beladener Gepäckträger','ein Gepäckträger im Hotel','ironic','understatement'),
(4469,'de','Der Schrank greift ihn an!','Der Kühlschrank greift ihn an!','den Küchenschrank öffnen','den Küchenschrank abschließen','dramatic','exaggeration'),
(4470,'de','Teller, nach Farben geordnet aufbewahrt.','Tassen, nach Farben geordnet aufbewahrt.','Teller im Schrank aufbewahren','Dateien auf dem Laptop speichern','nerd','none'),
(4471,'de','Der Mast hat eine furchterregende Höhe!','Die Brücke hat eine furchterregende Höhe!','die große Höhe des Mastes','die Höhe einer Brücke','dramatic','exclamation'),
(4472,'de','Er kann die Höhe nicht fassen!','Er kann die Hitze nicht fassen!','eine Seilbahn in großer Höhe','die Flughöhe eines Flugzeugs','dramatic','exclamation'),
(4473,'de','Der Kaktus hat ihn zum Schreien gebracht!','Die Schlange hat ihn zum Schreien gebracht!','in der Wüste schreien','im Schnee schreien','gossip','blaming_someone'),
(4474,'de','Die Speisekarte hängt an der Wand.','Die Speisekarte liegt auf dem Tisch.','eine Speisekarte auf Tafeln','eine Speisekarte auf dem Handy','chill','none'),
(4475,'de','Tassen sind in Regalen ausgestellt.','Einmachgläser sind in Regalen ausgestellt.','in Regalen ausgestellte Tassen','eine Preisliste aushängen','chill','none'),
(4476,'de','Was für ein riesiger Café-Saal!','Was für ein winziger Café-Saal!','ein riesiger verzierter Saal','eine Schulsporthalle','dramatic','exclamation'),
(4477,'de','Er blättert zum neuen Monat um.','Er blättert in einem neuen Buch.','zum neuen Monat umblättern','ein Monat am Strand','chill','none'),
(4478,'de','Sie hat ein Datum markiert. Großer Tag!','Sie hat einen Namen markiert. Großer Tag!','ein rot markiertes Datum','ein Date im Restaurant','dramatic','guessing'),
(4479,'de','Diese Radeinheit ist echt schwer!','Diese Radeinheit ist echt leicht!','ein schwerer Spinning-Kurs','ein harter Fahrradsattel','dramatic','none'),
(4480,'de','Die Düne macht eine lange Kurve.','Der Fluss macht eine lange Kurve.','die Kurve einer Düne','eine Kurve in der Straße','chill','none'),
(4481,'de','Sie fokussiert wie ein Profi.','Sie kocht wie ein Profi.','das Objektiv fokussieren','sich auf Hausaufgaben fokussieren','slang','cliche'),
(4482,'de','Sie fotografiert die Dächer.','Sie fotografiert den Strand.','in der Stadt fotografieren','auf eine Zielscheibe schießen','chill','none'),
(4483,'de','Die Hütte ist aus Baumstämmen gebaut.','Die Hütte ist aus Ziegeln gebaut.','eine Hütte aus Baumstämmen','ein Baumstamm auf dem Eis','chill','none'),
(4484,'de','Die Morgendämmerung beleuchtet zuerst die Gipfel.','Die Morgendämmerung beleuchtet zuerst die Bäume.','das erste Licht der Morgendämmerung','Morgendämmerung in der Großstadt','nerd','none'),
(4485,'de','Mächtige Wasserfälle, Gratisdusche!','Mächtiger Regen, Gratisdusche!','ein mächtiger Wasserfall','ein mächtiger Kanumotor','slang','exaggeration'),
(4487,'de','Was für ein freundlicher Typ!','Was für ein fauler Typ!','ein freundlicher junger Mann','eine Art Pfannkuchen','flirt','exclamation'),
(4488,'de','Jedes Dokument bekommt ein rotes X. Schlechter Tag im Büro.','Jedes Dokument bekommt ein grünes Häkchen. Schlechter Tag im Büro.','ein Dokument stempeln','ein Dokument ausdrucken','ironic','exaggeration'),
(4489,'de','Überall ist geschmolzenes Wachs.','Überall ist geschmolzene Butter.','geschmolzenes Kerzenwachs','eine Wachsfigur','chill','none'),
(4490,'de','Sie bereitet den Tisch vor.','Sie putzt den Tisch.','einen Esstisch vorbereiten','sich auf einen Test vorbereiten','chill','none'),
(4491,'de','Der Fluss ist weit unten.','Die Sonne ist weit unten.','ein Fluss weit unten','Wolken weit unten','chill','none'),
(4492,'de','Die goldene Kuppel ist beeindruckend.','Die silberne Kuppel ist beeindruckend.','eine beeindruckende goldene Kuppel','ein beeindruckendes Prüfungsergebnis','chill','none'),
(4493,'de','Er kämpft am Steuer.','Er schläft am Steuer.','mit dem Steuer kämpfen','mit einer schweren Tasche kämpfen','dramatic','none'),
(4495,'de','Die Kosten für das alte Auto liegen bei 500 Euro.','Die Kosten für das alte Auto liegen bei 5.000 Euro.','die Kosten eines Autos','die Kosten einer Wohnung','business','none'),
(4496,'de','Er hat den Teppich auf den Boden gelegt.','Er hat den Teppich aufs Bett gelegt.','einen Teppich hinlegen','den Tisch decken','chill','none'),
(4497,'de','Er reicht eine Münze rüber.','Er reicht einen Schlüssel rüber.','das Wechselgeld reichen','ein Geschenk überreichen','chill','none'),
(4498,'de','Freunde unterschreiben auf seinem Gips.','Freunde unterschreiben auf seinem Shirt.','auf einem Gips unterschreiben','einen Vertrag unterschreiben','chill','none'),
(4499,'de','Burgen: Er besucht sie alle.','Bauernhöfe: Er besucht sie alle.','alte Burgen besuchen','alte Freunde besuchen','slang','exaggeration'),
(4500,'de','Schnelle Hände retten den Tag.','Schnelle Hunde retten den Tag.','ein schneller Fang','ein schnelles Nickerchen','dramatic','cliche'),
(4501,'de','Dieses Insekt hatte einen Snack.','Dieser Vogel hatte einen Snack.','ein Insekt auf einem Blatt','ein Insekt auf einer Blume','chill','understatement'),
(4502,'de','Decken sind soooo interessant.','Fußböden sind soooo interessant.','zur Decke hochschauen','die Decke streichen','ironic','exaggeration'),
(4503,'de','Sie wünscht sich etwas.','Sie backt einen Kuchen.','sich zum Geburtstag etwas wünschen','sich Regen wünschen','chill','none'),
(4504,'de','Was für ein Erfolg!','Was für eine Pleite!','einen großen Erfolg feiern','ein Erfolg auf der Bühne','dramatic','exclamation'),
(4505,'de','Er kippt rückwärts um!','Er kippt vorwärts um!','rückwärts vom Stuhl fallen','rückwärts zum Tisch gehen','dramatic','exclamation'),
(4506,'de','Behaglichkeit? Der grüne Sessel gewinnt.','Behaglichkeit? Der weiße Sessel gewinnt.','Behaglichkeit in einem großen Sessel','Behaglichkeit auf einem Küchenstuhl','business','none'),
(4507,'de','Der Mitarbeiter bringt einen Anhänger an.','Der Mitarbeiter bringt ein Schloss an.','ein Anhänger am Koffer','ein Namensschild an der Jacke','business','none'),
(4508,'de','Er lädt Taschen wie ein Boss.','Er lädt Essen wie ein Boss.','Taschen aufs Band laden','einen Lkw mit Kisten beladen','slang','exaggeration'),
(4509,'de','Die Tasche wiegt 12,95 kg. Akzeptiert.','Die Tasche wiegt 21,95 kg. Akzeptiert.','eine Tasche wiegen','das Obst wiegen','business','none'),
(4510,'de','Sie prüft ihr Ticket. Falsches Gate?','Sie prüft ihr Handy. Falsches Gate?','die Abflugtafel prüfen','ihre Tasche prüfen','dramatic','guessing'),
(4511,'de','Der Service hier ist top.','Der Service hier ist unhöflich.','freundlicher Service am Schalter','Zimmerservice im Hotel','business','none'),
(4512,'de','Er checkt seine Liste.','Er checkt sein Handy.','eine Liste abhaken','eine Einkaufsliste schreiben','chill','none'),
(4513,'de','Alles gut: Koffer und Ticket.','Alles gut: Rucksack und Ticket.','ein Koffer am Flughafen','ein Koffer im Zug','chill','none'),
(4514,'de','Der Koch hat krasse Fähigkeiten.','Der Kellner hat krasse Fähigkeiten.','die Fähigkeiten eines Kochs','Jonglier-Fähigkeiten','slang','exaggeration'),
(4515,'de','Er hat eine Medaille gewonnen. Na klar!','Er hat einen Pokal gewonnen. Na klar!','eine Medaille gewinnen','ein Auto gewinnen','slang','none'),
(4516,'de','Der Scheunenboden ist voller Heu.','Der Scheunenboden ist voller Schlamm.','ein Nest aus Heu','Heuballen auf einem Lkw','chill','none'),
(4517,'de','Er macht einen kräftigen Zug am Seil.','Er macht einen kräftigen Schnitt ins Seil.','ein Zug am Seil','die Anziehungskraft des Mondes','chill','none'),
(4519,'de','Er stapelt Holzscheite auf die Asche.','Er stapelt Holzscheite auf den Teppich.','eine dicke Schicht Asche','eine alte Esche','chill','none'),
(4520,'de','Die Mauer erstreckt sich endlos.','Der Fluss erstreckt sich endlos.','sich über die Berge erstrecken','sich vor dem Laufen dehnen','dramatic','exaggeration'),
(4521,'de','Türme verschwinden in der Ferne.','Häuser verschwinden in der Ferne.','Türme in der Ferne','ein Ferngespräch','chill','none'),
(4522,'de','Ihre Rundreise: Mauer, Boot und Teigtaschen!','Ihre Rundreise: Mauer, Boot und Pizza!','eine Rundreise durch China','eine Rundreise durch Italien','slang','exclamation'),
(4524,'de','Perfekt gefaltete Teigtaschen.','Perfekt gefaltete Servietten.','Ränder von Teigtaschen falten','saubere Wäsche falten','business','none'),
(4525,'de','Sie hat ihm geholfen, wieder zu atmen.','Sie hat ihm geholfen, wieder aufzustehen.','einem sich verschluckenden Mann helfen','beim Abwasch helfen','chill','none'),
(4526,'de','Sie denkt sehr angestrengt über diese Wahl nach.','Er denkt sehr angestrengt über diese Wahl nach.','bei einer Wahl abstimmen','eine Wahl gewinnen','ironic','exaggeration'),
(4527,'de','Er schneidet Gemüse!','Er schneidet Fleisch!','Gemüse schneiden','Gemüse waschen','dramatic','exclamation'),
(4528,'de','Alte Gräber umgeben die Kirche.','Alte Gräber umgeben die Burg.','Gräber rund um eine Kirche','Gräber auf einem Schlachtfeld','dramatic','none'),
(4529,'de','Der Boden voller Farbe. Magie!','Der Boden voller Wasser. Magie!','Farben auf einem Steinboden','Farben auf einer bemalten Wand','dramatic','none'),
(4530,'de','Beim Film fliegt Popcorn!','Beim Film fliegen Getränke!','einen Film schauen','einen Film drehen','dramatic','exaggeration'),
(4531,'de','Mit Popcorn ist sie bereit.','Mit Pizza ist sie bereit.','ein großer Eimer Popcorn','Popcorn zu Hause machen','chill','none'),
(4532,'de','Parkdienst: Müll aufsammeln.','Parkdienst: Blumen aufsammeln.','Müll im Park aufsammeln','eine volle Mülltonne','business','none'),
(4533,'de','Sie feiern im Gerichtssaal.','Sie weinen im Gerichtssaal.','eine glückliche Familie im Gerichtssaal','eine Party auf dem Tennisplatz','chill','none'),
(4534,'de','Der Beamte trägt eine Kette.','Der Beamte trägt eine Krone.','ein Beamter mit Amtskette','ein Beamter beim Passstempeln','chill','none'),
(4535,'de','Er wirft in der Unterrichtsstunde mit Papier!','Er wirft in der Unterrichtsstunde mit Kreide!','eine Unterrichtsstunde in Mathe','eine Schwimmstunde','dramatic','exclamation'),
(4536,'de','Das Handwerk hier ist Töpfern.','Das Handwerk hier ist Malen.','das Handwerk des Töpferns','das Handwerk der Glasbläserei','nerd','none'),
(4537,'de','Sie hat die ganze Wohnung geräumt. Dann ist sie zusammengebrochen.','Sie hat die ganze Wohnung geräumt. Dann hat sie getanzt.','die Regale leer räumen','sich räuspern','dramatic','exaggeration'),
(4538,'de','Aufgabe erledigt. Zeit für etwas Ruhe.','Aufgabe erledigt. Zeit für einen Lauf.','Ruhe auf dem Sofa','ein Rastplatz an der Autobahn','business','cliche'),
(4539,'de','Der Mann in der Karikatur wischt.','Der Mann in der Karikatur kocht.','eine Karikatur einer Putzkraft','eine Karikatur eines Kochs','chill','none'),
(4540,'de','Ordentliche Sicherheitsausrüstung.','Ordentliche Tauchausrüstung.','Ausrüstung zum Fensterputzen','Ausrüstung in einer Turnhalle','business','none'),
(4541,'de','Das Waschbecken war dreckig und voller Haare!','Das Waschbecken war dreckig und voller Schlamm!','ein dreckiges, haariges Becken','dreckige Stiefel an der Tür','dramatic','exclamation'),
(4542,'de','Sie haben eine Vereinbarung erzielt.','Sie haben den Flughafen erreicht.','Handschlag auf eine Vereinbarung','ein Mietvertrag','business','none'),
(4543,'de','Das dünne Seil ist ein winziges Risiko.','Die Leiter ist ein winziges Risiko.','Risiko an einer Steilküste','Risiko im Casino','ironic','understatement'),
(4544,'de','Sand und Eis. Kleiner Kontrast.','Meer und Eis. Kleiner Kontrast.','Sand und Eis im Kontrast','Tag und Nacht im Kontrast','ironic','understatement'),
(4545,'de','Sie hat enorme Kraft in den Fingern.','Er hat enorme Kraft in den Fingern.','Kraft in ihren Fingern','Kraft in ihren Beinen','chill','exaggeration'),
(4546,'de','Die Praxis hat eine grüne Liege.','Die Praxis hat eine rote Liege.','ein Junge in der Praxis','ein Junge bei einer OP','chill','none'),
(4547,'de','Sie sind im Wartezimmer.','Sie sind im Esszimmer.','im Wartezimmer sitzen','im Wohnzimmer sitzen','chill','none'),
(4548,'de','Oh nein, er ist zu spät aufgewacht!','Oh nein, er ist zu früh aufgewacht!','spät aufwachen','bis spät arbeiten','dramatic','exclamation'),
(4549,'de','Er schaufelt Brennstoff.','Er schaufelt Schnee.','schwarzen Brennstoff schaufeln','Treibstoff für eine Rakete','chill','none'),
(4550,'de','Endlich Kaffee. Sie lebt wieder.','Endlich Tee. Sie lebt wieder.','endlich Kaffee trinken','endlich ins Bett gehen','slang','exaggeration'),
(4551,'de','Billiges Zelt. Super zum Zelten!','Billiges Auto. Super zum Zelten!','am See zelten','im Schnee zelten','ironic','cheap_quality'),
(4553,'de','Eine Bürste für ihre Haare, dann dieselbe für den Hund.','Eine Bürste für ihre Haare, dann dieselbe für die Katze.','lange dunkle Haare bürsten','Hundehaare auf dem Sofa','gossip','cheap_quality'),
(4554,'de','Eine Wand aus Flammen, und er kocht weiter.','Eine Wand aus Wasser, und er kocht weiter.','eine Wand aus orangen Flammen','eine Kerzenflamme beim Abendessen','ironic','understatement'),
(4555,'de','Kiefern unten, Gipfel vorn.','Palmen unten, Gipfel vorn.','Reihen verschneiter Kiefern','ein Küchentisch aus Kiefer','chill','none'),
(4556,'de','Das ganze Team lobt ihn.','Das ganze Team ignoriert ihn.','einen Kollegen loben','einen Hund loben','gossip','none'),
(4557,'de','Der Hund hat seinen Schoß geklaut!','Die Katze hat seinen Schoß geklaut!','ein Hund auf seinem Schoß','eine Runde auf der Bahn','dramatic','exclamation'),
(4558,'de','Seine Freunde sind seine Unterstützung.','Seine Eltern sind seine Unterstützung.','Unterstützung von Freunden','Unterstützung von seinen Eltern','chill','none'),
(4559,'de','Freunde trösten ihn.','Freunde ärgern ihn.','einen weinenden Freund trösten','auf einer Konsole zocken','chill','none'),
(4560,'de','Die Besatzung rudert im Takt.','Die Besatzung singt im Takt.','eine rudernde Besatzung','eine Filmcrew','chill','none'),
(4561,'de','Sie brüllt Befehle.','Sie flüstert Befehle.','Befehle brüllen','Befehle eintippen','dramatic','none'),
(4562,'de','Sie checkt die Richtung. Ernstes Gesicht.','Sie checkt die Uhrzeit. Ernstes Gesicht.','die richtige Richtung finden','nach dem Weg fragen','dramatic','none'),
(4563,'de','Das Gesetzbuch hat goldene Ecken.','Das Gesetzbuch hat eiserne Ecken.','ein riesiges Buch voller Gesetze','das Gesetz brechen','nerd','none'),
(4564,'de','Die Scheune braucht Zusammenarbeit.','Das Boot braucht Zusammenarbeit.','Zusammenarbeit beim Scheunenbau','Zusammenarbeit zwischen Ländern','business','none'),
(4565,'de','Die Erde sieht aus wie eine Kugel.','Der Mond sieht aus wie eine Kugel.','eine blau-grüne Kugel','ein Globus auf dem Schreibtisch','chill','none'),
(4566,'de','Sie erreicht den Gipfel!','Sie erreicht den Fluss!','den Gipfel erreichen','ein Gipfel der Staatschefs','dramatic','exclamation'),
(4567,'de','Sie sieht ein bisschen krank aus.','Sie sieht sehr glücklich aus.','krank und hustend','krank im Bett','chill','understatement'),
(4568,'de','Sie springt auf jedem Kontinent. Billig reisen!','Er springt auf jedem Kontinent. Billig reisen!','auf einem Kontinent springen','einen Kontinent zeichnen','slang','cheap_quality'),
(4569,'de','Er brät Fisch. Vanlife!','Er brät Eier. Vanlife!','Fisch im Van braten','Fisch auf einem Boot braten','slang','cliche'),
(4570,'de','Der Chefkoch richtet Schweinefleisch an.','Der Chefkoch richtet Fisch an.','ein Chefkoch beim Anrichten','ein Chefkoch beim Essen','business','none'),
(4571,'de','Alle schieben das Boot.','Alle schieben das Auto.','ein Boot ins Meer schieben','ein Auto bergauf schieben','chill','none'),
(4572,'de','Sie wird sie ewig korrigieren.','Er wird sie ewig korrigieren.','Klausuren korrigieren','ihre Haltung korrigieren','dramatic','exaggeration'),
(4573,'de','Ein geheimer Deal mit Bargeld.','Ein geheimer Deal mit Kaffee.','ein geheimer Bargeld-Deal','ein geheimer Liebesbrief','gossip','guessing'),
(4575,'de','Ihre Erkältung ist mit in die Bibliothek gekommen.','Ihre Erkältung ist mit ins Kino gekommen.','eine Erkältung in der Bibliothek','eine Erkältung im Schnee','chill','none'),
(4576,'de','Sie zählt einen Berg Papier.','Sie zählt einen Berg Münzen.','Blätter Papier zählen','Münzen auf einem Tisch zählen','dramatic','exaggeration'),
(4577,'de','Sie zeigt uns ihr Land.','Sie zeigt uns ihr Schiff.','ein Land voller Felder','ein Landhaus','chill','none'),
(4579,'de','Sie ist ständig im Ausland unterwegs!','Sie ist ständig zu Hause!','im Ausland reisen','im Ausland studieren','dramatic','exclamation'),
(4580,'de','Bei ihrem Date gibt''s nur einen Milchshake.','Bei ihrem Date gibt''s nur eine Pizza.','ein Milchshake-Date','das Datum im Kalender','gossip','none'),
(4581,'de','Eine Deckenhöhle voller Bonbons.','Eine Deckenhöhle voller Bücher.','eine Schale Bonbons','das Schaufenster eines Bonbonladens','chill','none'),
(4582,'de','Ein Erwachsener misst sie.','Ein Erwachsener füttert sie.','messen, wer größer ist','einen Raum ausmessen','chill','none'),
(4583,'de','Au! Er hält sich die Wade.','Au! Er hält sich den Kopf.','ein Krampf in der Wade','ein Kalb auf der Weide','dramatic','exclamation'),
(4584,'de','Die Schildkröte hat eine Spur hinterlassen.','Die Krabbe hat eine Spur hinterlassen.','eine Spur von Flossenabdrücken','ein Wanderweg','chill','none'),
(4585,'de','Baskenmütze, Baguette, stylische Überquerung.','Baskenmütze, Gitarre, stylische Überquerung.','eine Überquerung mit Baguette','ein Grenzübergang mit dem Auto','flirt','none'),
(4586,'de','Sie ist auf dem Zebrastreifen.','Sie ist auf der Brücke.','ein belebter Zebrastreifen in Paris','ein Zebrastreifen im Schnee','chill','none'),
(4587,'de','Echt jetzt?! Der Radfahrer ist überrascht.','Echt jetzt?! Der Radfahrer schläft.','ein Radfahrer an einer Kreuzung','ein Radfahrer bei einem Rennen','dramatic','exclamation'),
(4588,'de','Der Verkehr steht.','Der Verkehr fließt.','stehender Verkehr bei Nacht','dichter Verkehr am Tag','business','none'),
(4589,'de','So viele Fußgänger!','So viele Radfahrer!','Fußgänger auf einer Kreuzung','eine Fußgängerzone mit Läden','dramatic','exclamation'),
(4590,'de','Urlaub heißt: großer Platsch!','Urlaub heißt: langes Nickerchen!','Urlaub auf einem Schiff','Urlaub in einem Zug','slang','exclamation'),
(4591,'de','Das Schiff bietet einen Pool auf dem Oberdeck.','Das Schiff bietet ein Kino auf dem Oberdeck.','ein großes Passagierschiff','ein großes Frachtschiff','business','none'),
(4592,'de','Wein, mit Füßen gemacht. Lecker?','Bier, mit Füßen gemacht. Lecker?','nackte Füße in Trauben','nackte Füße im Sand','ironic','guessing'),
(4593,'de','Er geht durchs Krankenhaus.','Er rennt durchs Krankenhaus.','ein langer Krankenhausflur','ein Krankenhausparkplatz','chill','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
