begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(4594,'de','Sie weinen zusammen!','Sie tanzen zusammen!','zusammen weinen','zusammen singen','dramatic','exaggeration'),
(4595,'de','Er kann nicht aufhören zu weinen.','Er kann nicht aufhören zu lachen.','auf dem Sofa weinen','unter der Dusche weinen','dramatic','none'),
(4596,'de','Sie putzt sich die Nase.','Sie macht eine Kaugummiblase.','sich die Nase putzen','sich die Nase zuhalten','chill','none'),
(4597,'de','Diese Kultur liebt das Tanzen.','Diese Kultur liebt Fußball.','ein Fest der Volkskultur','eine Fast-Food-Kultur','chill','none'),
(4598,'de','Ihr Kaffeebecher ist jetzt riesig!','Ihre Teekanne ist jetzt riesig!','ein riesiger Kaffeebecher','eine riesige Kaffeerechnung','dramatic','exclamation'),
(4599,'de','Zahlung in Münzen und Scheinen.','Zahlung nur in Scheinen.','eine Zahlung in bar','eine Zahlung mit Karte','business','none'),
(4600,'de','Er tauscht Geld.','Er tauscht Hüte.','ausländisches Geld tauschen','Geschenke tauschen','business','none'),
(4601,'de','Sie ordnet die Kissen an.','Sie ordnet die Bücher an.','Sofakissen anordnen','ein Meeting organisieren','chill','none'),
(4602,'de','Der Zoll durchsucht ihre Tasche.','Der Zoll durchsucht ihr Auto.','einen Koffer durchsuchen','nach einem verlorenen Hund suchen','business','none'),
(4603,'de','Die Straße schlängelt sich durch Hügel.','Die Straße schlängelt sich durch eine Stadt.','eine kurvige Bergstraße','ein kurviger Gebirgsfluss','chill','none'),
(4605,'de','Der Draht sprüht Funken.','Das Rad sprüht Funken.','ein Oberleitungsdraht der Tram','ein Drahtzaun auf dem Bauernhof','chill','none'),
(4606,'de','Er schaut zu einem Turm hoch.','Er schaut zu einem Flugzeug hoch.','eine Uhr an einem Turm','eine Uhr an einer Wand','chill','none'),
(4607,'de','Große Tanks aus Kupfer hinter ihr.','Große Tanks aus Plastik hinter ihr.','glänzende Braukessel aus Kupfer','Kupfermünzen in einem Glas','chill','none'),
(4608,'de','Die ganze Menschenmenge feiert voll!','Die ganze Menschenmenge pennt!','eine riesige tanzende Menschenmenge','eine Menschenmenge beim Fußball','slang','exclamation'),
(4610,'de','Papa ist bereit, sie aufzufangen!','Mama ist bereit, sie aufzufangen!','in Papas Arme springen','vor Papa weglaufen','dramatic','exclamation'),
(4611,'de','Ihre Tochter hat die Familie gemalt.','Ihre Tochter hat ein Pferd gemalt.','eine Tochter backt mit Mama','eine Tochter shoppt mit Mama','chill','none'),
(4612,'de','Er verkauft die besten Pfirsiche.','Er verkauft die besten Äpfel.','Pfirsiche auf dem Markt verkaufen','Äpfel auf dem Markt verkaufen','gossip','cliche'),
(4613,'de','Er gräbt die dunkle Erde um.','Er gräbt den weißen Sand um.','dunkle Erde umgraben','im Sand graben','chill','none'),
(4614,'de','Er hängt eine Papiergirlande auf.','Er hängt eine Papierlaterne auf.','Partydeko aufhängen','die Wäsche aufhängen','chill','none'),
(4615,'de','Dieses Zimmer ist mega bunt.','Dieses Zimmer ist mega grau.','bunte Partyballons','bunte Ostereier','slang','none'),
(4616,'de','Ein wilder Hirsch in einem nebligen Wald.','Ein Wildschwein in einem nebligen Wald.','ein Hirsch im Wald','ein Tisch aus Holz','dramatic','none'),
(4617,'de','Männer in Rüstung kämpfen.','Männer in Anzügen kämpfen.','mit Schilden kämpfen','um einen Parkplatz kämpfen','dramatic','none'),
(4618,'de','Da kommt der Angriff!','Da kommt der Regen!','ein Angriff mit Schilden','eine Gebühr für Extragepäck','dramatic','exclamation'),
(4619,'de','Rohes Hähnchen, roher Fisch, noch kein Abendessen.','Rohes Hähnchen, rohes Rindfleisch, noch kein Abendessen.','ein rohes gefrorenes Hähnchen','ein rohes Ei','chill','understatement'),
(4620,'de','Er schläft hier über Nacht.','Er arbeitet hier über Nacht.','über Nacht am Flughafen festsitzen','eine Zugfahrt über Nacht','chill','none'),
(4621,'de','Die Fahrgäste sehen aus, als käme der Flug nie.','Die Piloten sehen aus, als käme der Flug nie.','müde Fahrgäste warten','Fahrgäste im Flugzeug','dramatic','guessing'),
(4622,'de','Sie seufzt zur Decke hoch.','Sie seufzt zum Fenster hin.','am Gate seufzen','vor Erleichterung seufzen','chill','none'),
(4623,'de','Die Stimmen purzeln heraus.','Die Münzen purzeln heraus.','die Stimmen auszählen','seine Stimme abgeben','chill','none'),
(4624,'de','Eine klare Mehrheit!','Eine klare Minderheit!','eine klare Mehrheit','eine Mehrheit leerer Stühle','dramatic','exclamation'),
(4625,'de','Sie wählt wie ein Champion!','Er wählt wie ein Champion!','voller Freude wählen','per Brief wählen','dramatic','exaggeration'),
(4628,'de','Picknick abgesagt. Er ist traurig.','Picknick abgesagt. Sie ist traurig.','traurig wegen des Regens','traurig wegen des Schnees','chill','none'),
(4629,'de','Endloser Sand, ein winziger Wanderer.','Endloser Sand, ein winziges Kamel.','endlose Reihen von Dünen','eine endlose Autoschlange','dramatic','none'),
(4630,'de','Er hat zuerst den Haarschnitt gezeichnet.','Er hat zuerst den Bart gezeichnet.','ein scharfer Fade-Haarschnitt','ein Haarschnitt mit langen Seiten','chill','none'),
(4631,'de','Er hat ein Vogelhaus entworfen.','Er hat eine Hundehütte entworfen.','ein Vogelhaus entwerfen','eine Website entwerfen','chill','none'),
(4632,'de','Der Arbeitsplatz ist jetzt fertig.','Die Küche ist jetzt fertig.','einen Arbeitsplatz einrichten','sich einen Arbeitsplatz teilen','business','none'),
(4633,'de','Wegen des alten Autos ist er verzweifelt.','Wegen des alten Transporters ist er verzweifelt.','verzweifelt im Regen','verzweifelt ohne Kaffee','dramatic','cheap_quality'),
(4634,'de','Sie hat die Stadt endlich erreicht!','Sie hat den See endlich erreicht!','die Küstenstadt erreichen','nach dem Handy greifen','dramatic','exclamation'),
(4635,'de','Sie hat ihr Reiseziel erreicht.','Sie hat ihr Hotel erreicht.','ihr Reiseziel erreichen','ein Reiseziel per Flugzeug','chill','none'),
(4636,'de','Sie hat den echten Leuchtturm gefunden!','Sie hat die echte Burg gefunden!','ein rot-weißer Leuchtturm','ein Leuchtturm im Sturm','dramatic','exclamation'),
(4637,'de','Sie zerstören das Haus, und sie filmt es.','Sie zerstören das Auto, und sie filmt es.','ein altes Haus zerstören','ein altes Auto zerstören','gossip','none'),
(4638,'de','Tschüss, Haus. Jetzt nur noch Schutt.','Tschüss, Scheune. Jetzt nur noch Schutt.','ein Haufen Schutt','den Schutt wegräumen','gossip','none'),
(4639,'de','Die flüssige Seife ist blaugrün.','Die flüssige Seife ist knallrot.','flüssige Seife läuft heraus','flüssige Farbe am Pinsel','chill','none'),
(4640,'de','Blaues Reinigungsmittel, weißes Hemd!','Rosa Reinigungsmittel, weißes Hemd!','Reinigungsmittel eingießen','Reinigungsmittel fürs Geschirr','slang','exclamation'),
(4641,'de','Tschüss, Donuts. Hallo, gesunde Ernährung.','Tschüss, Salat. Hallo, Donuts.','Meal Prep für gesunde Ernährung','eine Ernährung aus Donuts','dramatic','cliche'),
(4642,'de','Beste Grube ever. Der Hund hat geholfen.','Beste Grube ever. Die Katze hat geholfen.','eine tiefe Sandgrube','eine Grube voller Schlangen','low_iq','none'),
(4643,'de','Die Produktion läuft super!','Die Produktion läuft mies!','eine Filmproduktion zu Hause','eine Produktionslinie in der Fabrik','dramatic','exclamation'),
(4644,'de','Arbeit? Was für eine schlechte Ausrede.','Regen? Was für eine schlechte Ausrede.','eine schlechte Ausrede fürs Gehen','eine Ausrede fürs Zuspätkommen','dramatic','bad_excuse'),
(4645,'de','Hände befestigen Kugeln.','Hände befestigen Räder.','Kugeln an Stäben befestigen','Stäbe an der Wand befestigen','chill','none'),
(4646,'de','Ringe ab: Das ist eine Scheidung.','Ringe ab: Das ist eine Hochzeit.','Ringe nach einer Scheidung','das Büro eines Scheidungsanwalts','dramatic','none'),
(4647,'de','Er hat sich zu viel gedreht. Ab auf den Boden.','Er ist zu viel gerannt. Ab auf den Boden.','sich auf dem Bürostuhl drehen','sich auf der Tanzfläche drehen','slang','understatement'),
(4648,'de','Sie untersucht einen kleinen Jungen.','Sie untersucht einen kleinen Hund.','einen besorgten Jungen untersuchen','eine besorgte Katze untersuchen','business','none'),
(4649,'de','Der Teddybär ist mutiger als er.','Der Welpe ist mutiger als er.','einen braunen Teddybären umarmen','einen braunen Welpen umarmen','ironic','guessing'),
(4650,'de','Die Reaktion macht Schaum!','Die Reaktion macht Rauch!','eine schäumende chemische Reaktion','eine schnelle allergische Reaktion','dramatic','exclamation'),
(4651,'de','Marine Tierwelt bei Sonnenuntergang.','Marine Tierwelt zur Mittagszeit.','springende marine Tiere','ein Marinesoldat in Uniform','nerd','none'),
(4652,'de','Sie tritt gegen einen Mann an.','Sie tritt gegen ein Kind an.','beim Armdrücken antreten','in einer Kochshow antreten','chill','none'),
(4653,'de','Er hat den Schlamm auf der Matte gelassen. Größtenteils.','Er hat den Schnee auf der Matte gelassen. Größtenteils.','Stiefel voller Schlamm','Schlamm auf dem Küchentisch','ironic','understatement'),
(4654,'de','Sie hat Zweifel daran.','Sie hat keine Zweifel daran.','Zweifel an einem Regal','Zweifel an der Farbe','gossip','understatement'),
(4655,'de','Er zieht sich einen Anzug an.','Er zieht sich einen Hoodie an.','sich einen Anzug anziehen','einen Salat anmachen','chill','none'),
(4656,'de','Sie hat zwei Regale montiert.','Sie hat zwei Spiegel montiert.','Regale an die Wand montieren','auf ein Pferd steigen','chill','none'),
(4657,'de','Sie trinkt Kokoswasser.','Sie trinkt Orangensaft.','durch einen Strohhalm trinken','aus dem Wasserhahn trinken','chill','none'),
(4658,'de','Sie fährt am Meer entlang.','Sie fährt an einem See entlang.','die Küste entlangfahren','an einem Fluss entlangfahren','chill','none'),
(4659,'de','All diese Leute sitzen in Autos.','All diese Leute sitzen auf Fahrrädern.','Leute in ihren Autos','Leute in ihren Betten','chill','none'),
(4660,'de','Ihr Einkauf ist ein großer Stapel.','Ihr Einkauf ist in einer Tüte.','ein Stapel Kartons','ein Stapel Wäsche','chill','none'),
(4661,'de','Der Herbst ist im Park angekommen!','Der Frühling ist im Park angekommen!','gelbe Blätter im Herbst','Herbstmode im Laden','dramatic','none'),
(4662,'de','Ein Flugzeug versorgt das Dorf.','Ein Lastwagen versorgt das Dorf.','ein Dorf aus der Luft versorgen','ein Dorf per Boot versorgen','chill','none'),
(4663,'de','Gleich landet ein Tropfen.','Gleich landet eine Biene.','ein einzelner klarer Tropfen','ein Tropfen Regen','chill','guessing'),
(4664,'de','Sie zählt die Dosis Tropfen für Tropfen ab.','Sie zählt die Dosis Löffel für Löffel ab.','eine Dosis gelbes Öl','eine Dosis Hustensaft','nerd','none'),
(4665,'de','Ein Unfall nach dem anderen!','Ein Tor nach dem anderen!','eine Serie kleiner Unfälle','ein Autounfall','dramatic','exclamation'),
(4667,'de','Das Flugzeug wirft Kisten ab. Lieferung per Luftpost!','Das Flugzeug wirft Briefe ab. Lieferung per Luftpost!','ein Flugzeug wirft Kisten ab','ein Flugzeug landet auf Gras','slang','none'),
(4668,'de','Sie riecht an der Wäsche.','Sie bügelt die Wäsche.','an frischer Wäsche riechen','die Meeresluft riechen','chill','none'),
(4669,'de','Wäsche mit Meerblick!','Wäsche mit Stadtblick!','weiße Wäsche an der Leine','ein Sack dreckige Wäsche','slang','exclamation'),
(4670,'de','Sie ist auf dem Dach.','Sie ist im Garten.','Wäsche auf einem Flachdach','eine Katze auf dem Dach','chill','none'),
(4671,'de','Die Decke ist in der Maschine.','Das Handtuch ist in der Maschine.','eine Waschmaschine','eine Kaffeemaschine','chill','none'),
(4672,'de','An beiden Ufern wächst Schilf.','An beiden Ufern wachsen Bäume.','hohes Schilf am Wasser','ein geflochtener Schilfkorb','nerd','none'),
(4673,'de','Er ist viel zu schwach dafür!','Er ist viel zu stark dafür!','ein schwacher dünner Arm','ein schwacher Tee','slang','exclamation'),
(4674,'de','Er staubt die Regale ab.','Er streicht die Regale.','die Regale abstauben','die Regale aufbauen','chill','none'),
(4675,'de','Er ist überhaupt nicht vorsichtig!','Sie ist überhaupt nicht vorsichtig!','nicht vorsichtig auf der Brücke','vorsichtig mit den Tulpen','dramatic','understatement'),
(4676,'de','Käse schleppen ist hier Tradition.','Fisch schleppen ist hier Tradition.','eine alte Käse-Tradition','eine alte Tanz-Tradition','chill','none'),
(4678,'de','Alle essen etwas.','Alle trinken Tee.','einen dreifachen Burger essen','eine Salatbowl essen','chill','none'),
(4679,'de','Diese Tacos sind köstlich!','Diese Burger sind köstlich!','zwei köstliche Tacos','eine köstliche kalte Suppe','dramatic','exclamation'),
(4680,'de','Ein Reiter steigt auf ein Kamel.','Ein Reiter steigt auf ein Pferd.','ein Reiter steigt aufs Kamel','ein Reiter auf einem Pferd','chill','none'),
(4681,'de','So viele Lampen aus Glas!','So viele Flaschen aus Glas!','eine blaue Lampe aus Glas','eine blaue Vase aus Glas','dramatic','exclamation'),
(4682,'de','Der Händler schüttet Gewürz aus.','Der Händler schüttet Tee aus.','ein Gewürzhändler','ein Börsenhändler','chill','none'),
(4683,'de','Überall auf der Arbeitsplatte liegt Reis.','Überall auf der Arbeitsplatte liegt Salz.','eine Schüssel gekochter Reis','eine Tüte roher Reis','gossip','exaggeration'),
(4684,'de','Ellbogen an Ellbogen: der neue Händedruck.','Faust an Faust: der neue Händedruck.','Ellbogen aneinander im Büro','Ellbogen auf dem Schreibtisch','business','cliche'),
(4685,'de','Er repariert den Sicherungskasten.','Er repariert das Auto.','den Sicherungskasten reparieren','einen platten Reifen reparieren','business','none'),
(4686,'de','Reparatur fertig, Licht an!','Reparatur fertig, Wasser an!','eine Reparatur im Dunkeln','eine Reparaturwerkstatt für Autos','dramatic','exclamation'),
(4687,'de','Sie ist bei der Botschaft.','Sie ist in der Botschaft.','Unterlagen für die Botschaft','eine nächtliche Party in der Botschaft','chill','none'),
(4688,'de','Nur ein massiver Wal, halb so wild.','Nur ein massiver Hai, halb so wild.','ein massiver Buckelwal','ein massiver Sturm auf See','ironic','understatement'),
(4689,'de','Ein Wal direkt neben dem Boot!','Ein Hai direkt neben dem Boot!','ein Wal am Boot','ein Delfin am Boot','dramatic','exclamation'),
(4690,'de','Sein Arbeitsplatz ist eine Bürokabine.','Sein Arbeitsplatz ist eine Küche.','ein offener, belebter Arbeitsplatz','ein Arbeitsplatz auf dem Bauernhof','business','none'),
(4691,'de','Er begrüßt einen Kollegen.','Er begrüßt einen Hund.','einen Kollegen begrüßen','ein Kollege im Urlaub','chill','none'),
(4692,'de','Er räumt die Produkte ins Regal.','Er räumt die Bücher ins Regal.','Produkte im Regal','Produkte im Lastwagen','business','none'),
(4693,'de','Der Chef hat ihn gerade eingestellt.','Der Chef hat ihn gerade gefeuert.','einen neuen Mitarbeiter einstellen','ein Auto für den Urlaub mieten','business','none'),
(4694,'de','Er hat den Vertrag unterschrieben!','Er hat den Vertrag zerrissen!','einen Vertrag unterschreiben','einen Vertrag zu Hause lesen','dramatic','exclamation'),
(4695,'de','Er hat dieses ganze Chaos angerichtet.','Er hat dieses ganze Chaos aufgeräumt.','Chaos auf dem Boden','Chaos in der Küche','gossip','blaming_someone'),
(4696,'de','Sie ermutigen sie!','Sie lachen sie aus!','eine Kletterin ermutigen','ein Kind zum Lesen ermutigen','dramatic','exclamation'),
(4697,'de','Er hat einen Blitzstart!','Er hat einen lahmen Start!','ein Start aus dem Block','der Schulbeginn','dramatic','exaggeration'),
(4698,'de','Was für ein riesiger Motor!','Was für ein riesiger Reifen!','ein riesiger V8-Motor','ein riesiger Bootsmotor','dramatic','exclamation'),
(4699,'de','Er inspiziert die Maschinerie.','Er repariert die Maschinerie.','alte Maschinerie in der Fabrik','alte Maschinerie vom Bauernhof','business','none'),
(4700,'de','Der Roboter hat ihm eine Tasse gereicht.','Der Roboter hat ihm ein Handy gereicht.','ein Roboter mit einer Tasse','ein Saugroboter','chill','none'),
(4701,'de','Das Meer hat alles zerstört. Danke, Meer.','Der Hund hat alles zerstört. Danke, Hund.','eine zerstörte Sandburg','eine zerstörte alte Kirche','ironic','blaming_someone'),
(4702,'de','Die Ziege ist entkommen. Tschüss, Bauer!','Die Kuh ist entkommen. Tschüss, Bauer!','aus dem Ziegengehege entkommen','einem Fuchs entkommen','slang','blaming_someone'),
(4703,'de','Er hebt eine grüne Fahne hoch.','Er hebt eine rote Fahne hoch.','eine Fahne heben','ein Kind großziehen','chill','none'),
(4704,'de','Er trägt einen Hut aus Fell in der Sauna!','Er trägt eine Basecap in der Sauna!','einen Hut aus Fell tragen','einen Hut aus Stroh tragen','slang','exclamation'),
(4705,'de','Die ganze Stadt liebt die Band!','Die ganze Stadt hasst die Band!','eine Band spielt auf der Straße','eine Band im Stadion','gossip','exaggeration'),
(4706,'de','Das ganze Stadion schreit.','Das ganze Stadion sitzt.','Fans schreien im Stadion','in der Bibliothek schreien','chill','none'),
(4707,'de','Bester Patient ever. Er lächelt.','Bester Patient ever. Er schläft.','ein Patient mit einer Pflegerin','ein Patient im Krankenwagen','gossip','exaggeration'),
(4708,'de','Ein Mann führt die Gruppe.','Ein Hund führt die Gruppe.','eine Reisegruppe führen','ein Schiff in den Hafen führen','chill','none'),
(4709,'de','Die ganze Gruppe jubelt!','Die ganze Gruppe weint!','eine Gruppe mit gleichen Hüten','eine Gruppe mit gleichen Shirts','dramatic','none'),
(4710,'de','Sie schwingen die Arme.','Sie schwingen die Beine.','Arme hoch über den Kopf','Arme vor der Brust verschränkt','business','none'),
(4712,'de','Er pustet alle Kerzen aus!','Er pustet alle Luftballons auf!','Geburtstagskerzen auspusten','Luftballons aufpusten','dramatic','exclamation'),
(4713,'de','Sie winken zum Abschied.','Sie winken zur Begrüßung.','am Kai zum Abschied winken','ein Abschiedsbrief','chill','none'),
(4714,'de','Der Experte sagt, es ist echt.','Der Experte sagt, es ist gefälscht.','ein Experte mit einer Vase','ein Experte mit einem Auto','chill','none'),
(4715,'de','Die Wassermelone ist explodiert!','Der Kürbis ist explodiert!','eine platzende Wassermelone','eine aufgeschnittene Wassermelone','dramatic','exclamation'),
(4716,'de','Er erkundet den Dschungel wie Indiana Jones.','Er erkundet die Wüste wie Indiana Jones.','eine Dschungelhöhle erkunden','eine Großstadt erkunden','dramatic','exaggeration'),
(4717,'de','Im Tunnel ist es so dunkel!','Im Haus ist es so dunkel!','ein dunkler Felstunnel','ein dunkler Nachthimmel','dramatic','exclamation'),
(4718,'de','Ihr braunes Auge füllt das ganze Bild.','Ihr blaues Auge füllt das ganze Bild.','eine Taschenlampe am Auge','ein Auge hinter der Brille','chill','none'),
(4719,'de','Das Kinn ist rund.','Das Kinn ist spitz.','ein rundes Kinn','eine Hand am Kinn','business','none'),
(4720,'de','Lustige Grimassen und null Scham!','Lustige Hüte und null Scham!','lustige Grimassen fürs Handy','lustige Grimassen für den Lehrer','slang','exaggeration'),
(4721,'de','Neiiin, der Regenbogen verblasst!','Neiiin, der Regenbogen wird größer!','ein verblassender Regenbogen','ein verblassendes Foto','dramatic','exclamation'),
(4722,'de','Sogar die Frauen mit Sonnenbrille fallen in Ohnmacht!','Sogar die Frauen mit Sonnenbrille tanzen!','Frauen mit dunklen Sonnenbrillen','Sonnenbrillen am sonnigen Strand','dramatic','exaggeration'),
(4723,'de','Leute fallen in Schaumstoff.','Leute fallen ins Wasser.','in eine Schaumstoffgrube fallen','in einen Pool fallen','chill','none'),
(4724,'de','Sie kann nicht aufhören zu lachen.','Sie kann nicht aufhören zu weinen.','in der Schaumstoffgrube lachen','im Bällebad lachen','chill','none'),
(4725,'de','Die ganze Familie hat Pizza gemacht.','Die ganze Familie hat Pasta gemacht.','Pizzateig machen','Pizza online bestellen','chill','none'),
(4726,'de','Der Bauer zieht Möhren aus der Erde.','Der Bauer zieht Zwiebeln aus der Erde.','ein glücklicher Bauer bei Sonnenuntergang','ein müder Bauer im Morgengrauen','chill','none'),
(4727,'de','Dieser Vater wird nie müde.','Diese Mutter wird nie müde.','ein Vater spielt Fangen','ein Vater guckt fern','gossip','exaggeration'),
(4728,'de','Sie schläft auf dem Sofa. Langer Tag!','Sie schläft auf dem Boden. Langer Tag!','auf dem Sofa schlafen','bei der Arbeit schlafen','slang','guessing'),
(4730,'de','Der Ausschuss hat neun Mitglieder.','Der Ausschuss hat fünf Mitglieder.','ein Ausschuss um einen Tisch','ein Ausschuss auf einer Bühne','business','none'),
(4731,'de','Die Flagge jeder Nation steigt.','Die Flagge jeder Nation sinkt.','die Flagge jeder Nation','die Armee einer Nation','business','none'),
(4732,'de','Er baut einen Holzzaun.','Er baut einen Holzschuppen.','einen Gartenzaun bauen','eine Sandburg bauen','chill','none'),
(4733,'de','Seine Temperatur ist extrem hoch!','Seine Temperatur ist sehr niedrig!','seine Temperatur messen','die Temperatur draußen','dramatic','exaggeration'),
(4734,'de','Pflege mit Herz: Sie kümmert sich um sie.','Pflege mit Herz: Sie kümmert sich um einen Hund.','liebevolle Pflege auf dem Sofa','Hautpflege im Bad','chill','none'),
(4735,'de','Sie verteilt Faustschläge.','Sie blockt Faustschläge.','Faustschläge auf ein Schlagpolster','eine Schüssel Fruchtpunsch','chill','none'),
(4736,'de','Die Armee trainiert im Sand.','Die Armee trainiert im Schnee.','eine Armee beim Training','eine Armee im Krieg','chill','none'),
(4737,'de','Sie gießt aus einem Krug ein.','Sie gießt aus einer Flasche ein.','Wasser aus einem Krug gießen','ein Krug Orangensaft','chill','none'),
(4738,'de','Ihre Klamotten liegen überall!','Ihre Bücher liegen überall!','überall Klamotten','überall Reisepässe','dramatic','exclamation'),
(4739,'de','Sie hat einen riesigen Diamanten entdeckt!','Sie hat einen riesigen Ring entdeckt!','einen versteckten Diamanten entdecken','ein neues Land entdecken','dramatic','exclamation'),
(4740,'de','Er macht jetzt die Wunde sauber.','Er macht jetzt das Fahrrad sauber.','eine blutende Wunde säubern','eine Wunde im Gesicht','chill','none'),
(4741,'de','Er zieht einen Fisch raus!','Er zieht einen Stiefel raus!','einen Fisch hochziehen','ein Boot an Land ziehen','dramatic','exclamation'),
(4742,'de','An den Seilen ist sie richtig stark!','Auf dem Rad ist sie richtig stark!','starke Arme und Beine','ein starker Kaffee','flirt','exclamation'),
(4743,'de','Saft! Bester Flug ever!','Pizza! Bester Flug ever!','ein Flug bei Sonnenuntergang','ein Flug bei Nacht','slang','exaggeration'),
(4744,'de','Sie entspannt auf dem Wasser.','Sie entspannt im Sand.','auf Salzwasser entspannen','in der heißen Badewanne entspannen','chill','none'),
(4745,'de','Der Fluss fließt an Kieseln vorbei.','Der Fluss fließt an Häusern vorbei.','Wasser fließt flussabwärts','Wasser fließt aus dem Hahn','chill','none'),
(4746,'de','Der Jet fliegt über die Fotografen!','Der Vogel fliegt über die Fotografen!','Fotografen an der Landebahn','Fotografen auf einer Hochzeit','dramatic','exclamation'),
(4747,'de','Die Möwen wollen sein Brot!','Die Möwen wollen seinen Hut!','Möwen um eine Fähre','Möwen am Strand','dramatic','guessing'),
(4748,'de','Unter dem Flügel nur Wolken.','Unter dem Flügel nur Berge.','Wolken unter einem Flugzeug','Wolken über dem Meer','chill','none'),
(4749,'de','Sie fallen in Formation!','Sie schwimmen in Formation!','Fallschirmspringer in Ring-Formation','die Formation einer Fußballmannschaft','dramatic','exclamation'),
(4750,'de','Sie hat eine Burg aus Kleidung gebaut.','Sie hat eine Burg aus Büchern gebaut.','saubere Kleidung falten','schmutzige Kleidung waschen','low_iq','none'),
(4751,'de','Reiseführer mit gelbem Regenschirm.','Reiseführer mit rotem Regenschirm.','ein Reiseführer mit Regenschirm','ein Reiseführer im Museum','chill','none'),
(4752,'de','Misserfolg! Der Ofen war''s.','Erfolg! Der Ofen war''s.','ein Misserfolg beim Backen','ein Misserfolg in Mathe','dramatic','blaming_someone'),
(4753,'de','Plot-Twist: Er hat ihm vergeben.','Plot-Twist: Er hat ihn ignoriert.','einem alten Freund vergeben','seinem kleinen Bruder vergeben','gossip','cliche'),
(4754,'de','Er protestiert: „Ich war''s nicht!“','Sie protestiert: „Ich war''s nicht!“','beim Schiri protestieren','auf der Straße protestieren','dramatic','bad_excuse'),
(4755,'de','Das Röntgenbild zeigt einen Knochenbruch in der Hand.','Das Röntgenbild zeigt einen Knochenbruch im Bein.','ein Knochenbruch auf dem Röntgenbild','ein Knochenbruch im Bein','nerd','none'),
(4756,'de','Ein Baguette auf dem Fahrrad? Das ist Frankreich!','Eine Pizza auf dem Fahrrad? Das ist Frankreich!','Radfahren in Frankreich','Skifahren in Frankreich','slang','cliche'),
(4758,'de','Jetzt ist der Kühlschrank voll, Bro!','Jetzt ist der Kühlschrank leer, Bro!','ein Kühlschrank voller Essen','eine volle Waschmaschine','slang','exclamation'),
(4759,'de','Der Bäcker spricht in ein Baguette.','Der Bäcker spricht in ein Croissant.','ein Bäcker mit Baguette','ein Bäcker macht Pizza','low_iq','none'),
(4760,'de','Sie teilen sich ein Eis.','Sie teilen sich eine Pizza.','sich ein Eis teilen','sich ein Straßenbahnticket teilen','chill','none'),
(4761,'de','Speck auf einem zugefrorenen See!','Speck an einem Sandstrand!','Speck auf dem Eis braten','Speck im Sandwich','slang','exclamation'),
(4762,'de','Er liebt diese Galerie!','Er hasst diese Galerie!','eine große Kunstgalerie','eine Galerie voller Autos','dramatic','exclamation'),
(4763,'de','Diese Gamer drehen völlig durch!','Diese Gamer schlafen alle!','Gamer in einer Arena','ein Gamer im Klassenzimmer','slang','exaggeration'),
(4764,'de','Sie flippt auf dem Sofa total aus.','Sie flippt auf dem Bett total aus.','auf dem Sofa springen','auf dem Sofa schlafen','slang','exaggeration'),
(4765,'de','Zum Garten gehört ein Gewächshaus.','Zum Garten gehört ein Swimmingpool.','ein kleines Gewächshaus aus Glas','ein großes Gewächshaus aus Plastik','business','none'),
(4766,'de','Sie gärtnert total gern.','Sie schwimmt total gern.','zwischen Blumen gärtnern','im Regen gärtnern','chill','none'),
(4767,'de','Der Gärtner hat eine große Schere.','Der Gärtner hat eine große Axt.','ein Gärtner mit Heckenschere','ein Gärtner mit Schlauch','chill','none'),
(4768,'de','Mit diesen Karten gewinnt er.','Mit diesen Würfeln gewinnt er.','zwei Spielkarten','eine Geburtstagskarte','gossip','guessing'),
(4769,'de','Sie steht an einem Zaun.','Sie sitzt auf einem Zaun.','ein Zaun am Rand entlang','ein Zaun um einen Garten','chill','none'),
(4770,'de','Das Boarding läuft.','Die Landung läuft.','Boarding über die Fluggastbrücke','Boarding am Bahnhof','business','none'),
(4771,'de','Tor, Tor, Tor ... Palast!','Tor, Tor, Tor ... Kirche!','ein Tor zu einem Palast','ein Palast in einer Stadt','dramatic','exclamation'),
(4772,'de','Ein riesiger Schwarm am Himmel.','Ein riesiger Schwarm auf dem Wasser.','ein Schwarm Stare','ein Schwarm auf einem See','chill','none'),
(4774,'de','Jede Generation lacht unter dem Apfelbaum.','Jede Generation lacht unter der Palme.','Generationen im Garten','Generationen am Esstisch','chill','none'),
(4775,'de','Das Neugeborene hat schon vier Fans.','Das Neugeborene hat schon zwei Fans.','ein neugeborenes Baby schläft','ein neugeborenes Lamm','gossip','exaggeration'),
(4777,'de','Er ist zu allen hilfsbereit.','Er ist zu allen unhöflich.','ein hilfsbereiter älterer Herr','ein hilfsbereiter junger Kellner','chill','none'),
(4778,'de','Diese Werkstatt stellt Uhren her.','Diese Werkstatt stellt Schuhe her.','eine kleine Uhrenwerkstatt','eine kleine Schreibwerkstatt','business','none'),
(4779,'de','Er hat Spaß in Deutschland!','Sie hat Spaß in Deutschland!','eine Reise durch Deutschland','ein Job in Deutschland','dramatic','exclamation'),
(4780,'de','Sie gehen durch getrennte Türen.','Sie gehen durch dieselbe Tür.','zwei getrennte Türen','zwei getrennte Tische','dramatic','none'),
(4781,'de','Sie heiratet ihn!','Sie verlässt ihn!','im Garten heiraten','am Strand heiraten','dramatic','exclamation'),
(4782,'de','Sie regiert den Spielplatz!','Sie regiert das Klassenzimmer!','auf dem Spielplatz spielen','ein leerer Spielplatz','slang','exaggeration'),
(4783,'de','Das Paar ist voller Torte!','Das Paar ist voller Schlamm!','ein Paar mit Tortengesichtern','ein Paar auf dem Fahrrad','dramatic','exclamation'),
(4784,'de','Er gibt ihr ein Geschenk.','Er gibt ihr ein Handy.','ein verpacktes Geschenk geben','eine große Rede halten','chill','none'),
(4785,'de','Prost auf der Terrasse!','Prost in der Küche!','Saft auf der sonnigen Terrasse','eine Party auf der Dachterrasse','slang','exclamation'),
(4786,'de','Der Sand funkelt blau!','Der Sand funkelt rot!','Sand funkelt bei Nacht','Sand funkelt in der Sonne','dramatic','exclamation'),
(4787,'de','Diese Pfanne ist sehr wertvoll.','Diese Pfanne ist komplett leer.','eine wertvolle Pfanne voller Gold','ein wertvolles altes Gemälde','chill','none'),
(4788,'de','Klatsch im Salon. Alle sind schockiert.','Klatsch im Salon. Alle sind gelangweilt.','schockiert vom Salon-Klatsch','schockiert vom Preis','gossip','exaggeration'),
(4789,'de','Sie hat volle Autorität.','Er hat volle Autorität.','eine Frau mit Autorität','Autorität über eine Armee','business','none'),
(4790,'de','Konflikt am großen Tisch, und Papiere fliegen!','Frieden am großen Tisch, und Papiere fliegen!','ein Konflikt am Tisch','ein Konflikt auf der Straße','gossip','exclamation'),
(4791,'de','Sie legt Unterlagen ab.','Sie legt Blumen ab.','ein Ordner mit Unterlagen','Unterlagen auf dem Boden','business','none'),
(4792,'de','Sie pflanzen Blumen.','Sie pflücken Blumen.','eine junge Blume pflanzen','eine Fahne aufstellen','chill','none'),
(4793,'de','Sie schleifen ein Vogelhaus ab.','Sie streichen ein Vogelhaus an.','ein Holzdach schleifen','einen Holzboden schleifen','chill','none'),
(4794,'de','Großmutters Kekse gewinnen.','Großmutters Pizza gewinnt.','Kekse von Großmutter','Kekse aus dem Laden','slang','cliche'),
(4795,'de','Sie hat Kekse gebacken. Bester Tag!','Sie hat einen Kuchen gebacken. Bester Tag!','gebackene Schokokekse','gebackene Apfelkuchen','dramatic','exclamation'),
(4796,'de','Er balanciert zwei Karten. Vorsicht!','Er balanciert zwei Tassen. Vorsicht!','Spielkarten balancieren','auf einem Bein balancieren','dramatic','exclamation'),
(4797,'de','Er gibt nur ein wenig Käse dazu.','Er gibt nur ein wenig Soße dazu.','ein wenig extra Käse','ein wenig extra Pfeffer','chill','understatement'),
(4798,'de','Sie geht zu einem Tempel.','Sie geht zu einer Kirche.','ein alter Tempel auf dem Hügel','eine alte Burg auf dem Hügel','chill','none'),
(4800,'de','Der Bräutigam ist so nervös!','Die Braut ist so nervös!','ein nervöser Bräutigam','ein Bräutigam füttert ein Pferd','gossip','exclamation'),
(4801,'de','Diese Sonnenblume ist so hoch!','Dieser Kaktus ist so hoch!','eine hohe Sonnenblume','ein hoher Baum','dramatic','exclamation'),
(4802,'de','Dieser Wachmann ist der Chef vom Museum.','Dieser Koch ist der Chef vom Museum.','ein Wächter im Museum','ein Wächter in der Bank','ironic','guessing'),
(4803,'de','Sie hat einen Blumenstrauß mitgebracht.','Sie hat einen Kuchen mitgebracht.','ein Blumenstrauß für die Gastgeberin','ein Blumenstrauß für die Braut','chill','none'),
(4804,'de','Sie besichtigen eine blaue Stadt.','Sie besichtigen eine rote Stadt.','eine blaue Stadt besichtigen','mit einer Rockband auf Tour','chill','none'),
(4805,'de','Er zeigt auf eine Kirche.','Er zeigt auf ein Boot.','eine Kirche mit Kuppel','eine Kirche aus Holz','chill','none'),
(4806,'de','Hinter seinem Buch ist eine Kuppel.','Hinter seinem Buch ist ein Kran.','eine Kuppel in der Skyline','ein Kuppelzelt zum Campen','chill','none'),
(4807,'de','Sein Sportshirt ist orange.','Seine Cap ist orange.','ein Sportshirt in Orange','ein Sportwagen in Orange','chill','none'),
(4808,'de','Die Stylistin flicht einen Zopf.','Die Stylistin macht einen Dutt.','einen langen Zopf flechten','einen langen Zopf abschneiden','chill','none'),
(4809,'de','Im Korridor ist Rushhour.','Im Badezimmer ist Rushhour.','ein Korridor voller Schuhe','ein langer Hotelkorridor','ironic','exaggeration'),
(4810,'de','Er schlägt einen Pfosten ein.','Er schlägt einen Nagel ein.','ein Pfosten im Boden','ein Post auf Social Media','chill','none'),
(4811,'de','Die Teamkollegen sind voll gehypt.','Die Teamkollegen streiten sich.','Hände rein mit den Teamkollegen','Streit mit den Teamkollegen','slang','none'),
(4812,'de','Sein Kleiderschrank ist mega ordentlich.','Sein Kleiderschrank ist mega chaotisch.','eine ordentliche Reihe Hemden','ein ordentlicher Stapel Schuhe','slang','none'),
(4813,'de','Der Hafen ist belebt.','Der Hafen ist leer.','ein belebter Hafen bei Sonnenaufgang','ein Hafen im Sturm','chill','none'),
(4814,'de','Das Team pflückt Tomaten.','Das Team pflückt Äpfel.','eine rote Tomate pflücken','einen roten Apfel pflücken','business','none'),
(4815,'de','Bürostress: Sie reibt sich die Schläfen.','Bürostress: Sie reibt sich die Füße.','sich die Schläfen reiben','sich die Hände reiben','business','none'),
(4816,'de','Ihr Herz rast!','Ihr Herz ruht!','eine Hand aufs Herz','ein Herz auf ihrem Shirt','dramatic','exclamation'),
(4817,'de','Bei dieser Dürre schmilzt sogar der Baum.','Bei dieser Dürre schmilzt sogar der Hund.','Dürre mit rissigem Boden','das Ende einer Dürre','dramatic','exaggeration'),
(4818,'de','Spikes unter der Ferse? Verrückt!','Rollen unter der Ferse? Verrückt!','ein Spike unter der Ferse','der Absatz eines Schuhs','slang','exclamation'),
(4819,'de','Die alte Frau ist dankbar.','Der alte Mann ist dankbar.','dankbar für den Schirm','dankbar für das Taxi','chill','none'),
(4820,'de','Sie haben das gleiche Kleid!','Sie haben die gleiche Tasche!','das gleiche gemusterte Kleid','die gleichen Schuhe','dramatic','exclamation'),
(4821,'de','Pizza zum Sonnenuntergang ist da!','Sushi zum Sonnenuntergang ist da!','Pizzalieferung bei Sonnenuntergang','ein Sonnenuntergang über den Bergen','flirt','exclamation'),
(4822,'de','Die Nachricht hat sie so glücklich gemacht.','Die Nachricht hat sie so traurig gemacht.','eine fröhliche Nachricht lesen','eine Nachricht am Kühlschrank','chill','guessing'),
(4823,'de','Er taucht in große Tiefe.','Er taucht in geringe Tiefe.','in große Tiefe tauchen','die Tiefe eines Pools','chill','none'),
(4824,'de','Ihr Pferd ist fake, aber sie tut sehr gut so, als ob.','Ihr Pferd ist fake, aber sie schwimmt sehr gut.','so tun, als ob man reitet','so tun, als ob man schläft','ironic','cheap_quality'),
(4825,'de','Arbeitsplatte abgewischt. Küche fertig.','Fenster abgewischt. Küche fertig.','die weiße Arbeitsplatte abwischen','Tränen abwischen','business','none'),
(4826,'de','Der Staudamm läuft über!','Der Pool läuft über!','ein überlaufender Staudamm','ein trockener Staudamm im Sommer','dramatic','exclamation'),
(4827,'de','Diese Farbe in Orange ist richtig dick.','Diese Farbe in Blau ist richtig dick.','eine dicke Schicht Farbe','frische Farbe an der Wand','chill','none'),
(4828,'de','Die Hälfte der Wand ist jetzt grün.','Die Hälfte der Wand ist jetzt blau.','eine halb grüne Wand','eine grüne Gartenmauer','business','none'),
(4829,'de','Farbsplitter fallen ab.','Farbtropfen fallen ab.','Splitter von alter Farbe','Splitter von altem Glas','chill','none'),
(4830,'de','Zwei Taucher schwimmen nach oben.','Drei Taucher schwimmen nach oben.','zur Oberfläche schwimmen','über den Fluss schwimmen','chill','none'),
(4831,'de','Was für ein starker Schlag!','Was für ein Fehlschlag!','ein Schlag vom Tee','ein Hit im Radio','dramatic','exclamation'),
(4832,'de','Ein schmaler Bergkamm über den Wolken.','Ein breiter Bergkamm über den Wolken.','ein schmaler Bergkamm im Schnee','ein grüner Hügelkamm','dramatic','none'),
(4833,'de','Er skatet an der Küste entlang, als wäre es nichts.','Er radelt an der Küste entlang, als wäre es nichts.','die Küstenstraße runterskaten','an der Küste entlangsegeln','flirt','cliche'),
(4834,'de','Dieser Spielzeug-Kampf ist episch!','Dieser Karten-Kampf ist episch!','ein Kreiselspielzeug','ein Spielzeugauto','slang','exaggeration'),
(4836,'de','Er sägt einen Bären aus.','Er sägt ein Pferd aus.','einen Bären aus Holz sägen','ein Brett durchsägen','chill','none'),
(4837,'de','Der Tisch ist voller Essen.','Der Tisch ist voller Bücher.','ein Tisch voller Essen','ein Tisch voller Spiele','chill','none'),
(4838,'de','Sie wirft einen Ball.','Sie kickt einen Ball.','einen Wasserball werfen','eine Party schmeißen','chill','none'),
(4839,'de','Er kann allein ein Auto bewegen!','Er kann allein einen Bus bewegen!','schwere Dinge bewegen','in eine neue Stadt ziehen','dramatic','exaggeration'),
(4840,'de','Sie haben sich für eine Überraschung versteckt!','Sie haben sich vor einem Hund versteckt!','sich hinter dem Sofa verstecken','sich unter dem Bett verstecken','dramatic','exclamation'),
(4841,'de','Sie hat den Schlüssel gefunden! Endlich!','Sie hat das Handy gefunden! Endlich!','einen kleinen Schlüssel finden','einen kleinen Schlüssel verlieren','dramatic','exclamation'),
(4842,'de','Er arbeitet an einem alten Auto.','Er arbeitet an einem alten Fahrrad.','am Automotor arbeiten','im Büro arbeiten','chill','none'),
(4843,'de','Das ist mal eine riesige Holzkonstruktion!','Das ist mal eine riesige Metallkonstruktion!','eine Hauskonstruktion aus Holz','die Konstruktion eines Satzes','dramatic','exclamation'),
(4844,'de','Sie hat den Kürbis in zwei Hälften geschnitten.','Sie hat den Kuchen in zwei Hälften geschnitten.','ein Kürbis in zwei Hälften','ein halber Kürbiskuchen','chill','none'),
(4845,'de','Hände nähen das Tuch.','Hände schneiden das Tuch.','das Tuch nähen','mit einem Tuch wischen','chill','none'),
(4846,'de','Bügeln erledigt: ein glattes Laken.','Bügeln erledigt: ein glattes Handtuch.','ein weißes Laken bügeln','ein Problem ausbügeln','business','none'),
(4847,'de','Was für ein sauberer Boden!','Was für ein dreckiger Boden!','den Boden wischen','den Boden streichen','dramatic','exclamation'),
(4848,'de','Schau, was bei ihr gewachsen ist: ein Kürbis!','Schau, was bei ihr gewachsen ist: eine Melone!','einen großen Kürbis wachsen lassen','sich einen langen Bart wachsen lassen','dramatic','exclamation'),
(4849,'de','Sommer: Wasser für alle!','Sommer: Kuchen für alle!','ein Rasensprenger im Sommer','ein Sommertag am Strand','slang','exclamation'),
(4850,'de','Er richtet eine Kamera auf uns!','Er richtet ein Handy auf uns!','eine Kamera auf einem Stativ','eine Kamera im Laden','dramatic','exclamation'),
(4851,'de','Sie hat eine uralte Tafel gefunden!','Sie hat ein uraltes Schwert gefunden!','eine uralte Steintafel','ein uraltes Schiff','dramatic','exclamation'),
(4852,'de','Riesige Zahnräder am Ende!','Winzige Zahnräder am Ende!','riesige ineinandergreifende Zahnräder','Zahnräder am Fahrrad','dramatic','exclamation'),
(4853,'de','Das Zahnrad ist mega winzig.','Die Schraube ist mega winzig.','ein winziges Zahnrad aus Messing','eine winzige Küche','low_iq','none'),
(4854,'de','Er löst ein riesiges Problem!','Er löst ein winziges Problem!','Mathe an der Tafel lösen','einen Kriminalfall lösen','dramatic','exclamation'),
(4855,'de','Er will sich an jedes Wort der Welt erinnern.','Er will jedes Wort der Welt vergessen.','sich an Wörter auf Karten erinnern','sich an einen Geburtstag erinnern','dramatic','exaggeration'),
(4856,'de','Der Lehrer sitzt hinter einer Wand aus Papier.','Der Lehrer sitzt hinter einer Wand aus Büchern.','ein Lehrer korrigiert Arbeiten','ein Lehrer liest ein Buch','dramatic','exaggeration'),
(4857,'de','Der Arbeiter hat es geschüttelt, und jetzt geht es!','Der Arbeiter hat es getreten, und jetzt geht es!','ein Arbeiter mit Scanner','ein Arbeiter mit Hammer','low_iq','cheap_quality'),
(4858,'de','Seine Domino-Spirale ist riesig!','Sein Domino-Turm ist riesig!','eine Spirale aus Dominosteinen','ein Spiralblock','slang','exaggeration'),
(4859,'de','Die Puzzlestücke haben das Zimmer erobert.','Die Spielsachen haben das Zimmer erobert.','Puzzlestücke zusammensetzen','ein Stück Kuchen','dramatic','exaggeration'),
(4860,'de','Die Tablette macht Bläschen.','Die Tablette macht Funken.','Bläschen in einem Glas','eine Kaugummiblase','nerd','none'),
(4861,'de','Pssst, sie hört zu!','Pssst, sie schläft!','einem Vogel zuhören','dem Lehrer zuhören','dramatic','exclamation'),
(4862,'de','Sie kann einfach keinen Kürbis wählen.','Sie kann einfach keinen Hut wählen.','zwischen zwei Äpfeln wählen','zwischen zwei Kleidern wählen','gossip','guessing'),
(4863,'de','Ihr Plan füllt die ganze Wand.','Ihr Plan füllt den ganzen Schreibtisch.','ein Plan an der Wand','ein Plan für ein Haus','business','none'),
(4866,'de','Eine Drohne schwebt tief. Starke Aufnahme!','Ein Vogel schwebt tief. Starke Aufnahme!','eine Drohne über dem Gras','eine Drohne im Studio','dramatic','exclamation'),
(4867,'de','Sie zeigt zwei Daumen hoch.','Sie zeigt zwei Daumen runter.','zwei Daumen hoch','ein Daumen auf Gitarrensaiten','chill','none'),
(4868,'de','Sie haben es programmiert. Es läuft!','Sie haben es programmiert. Es ist kaputt!','eine neue App programmieren','eine Waschmaschine programmieren','dramatic','exclamation'),
(4869,'de','Design ist ihr ganzes Leben.','Fußball ist ihr ganzes Leben.','ein Logo-Design','ein Tattoo-Design','chill','exaggeration'),
(4870,'de','Sein Gesicht ist voller Schaum.','Sein Gesicht ist voller Schlamm.','Schaum auf seiner Wange','Schaum auf einem Bier','chill','none'),
(4871,'de','Die Schlange bei der Anmeldung ist endlos.','Die Schlange bei der Anmeldung ist leer.','der Schalter für die Anmeldung','die Anmeldung fürs Auto','dramatic','exaggeration'),
(4872,'de','So eine „strenge“ Bewertung: immer fünf Sterne.','So eine „strenge“ Bewertung: immer ein Stern.','eine Fünf-Sterne-Bewertung','eine Ein-Stern-Bewertung','ironic','understatement'),
(4874,'de','Sie hat an einer Ampel gehalten.','Sie hat an einer vollen Tankstelle gehalten.','an einer Ampel halten','eine rote Ampel','chill','none'),
(4875,'de','Das Team belädt den Lastwagen.','Das Team belädt das Boot.','ein Lastwagen voller Kisten','ein Lastwagen voller Sand','business','none'),
(4876,'de','Regen, aber sie lächelt.','Regen, aber sie weint.','einen Welpen anlächeln','den Busfahrer anlächeln','chill','none'),
(4877,'de','Jetzt sitzen alle!','Jetzt stehen alle!','in einem vollen Saal sitzen','in einem leeren Bus sitzen','dramatic','exclamation'),
(4878,'de','Der Typ springt vom Steg.','Der Typ springt vom Boot.','vom Holzsteg springen','vom Holzsteg angeln','slang','none'),
(4879,'de','Sie hebt bei diesem Wettbewerb ein Auto hoch!','Sie hebt bei diesem Wettbewerb ein Fahrrad hoch!','ein Strongwoman-Wettbewerb','ein Gesangswettbewerb im TV','dramatic','exclamation'),
(4880,'de','Eine Wasserflasche vom Dach? Krass.','Ein Stuhl vom Dach? Total krass.','eine große Wasserflasche','eine Babymilchflasche','slang','exclamation'),
(4881,'de','Leute schieben einen Bus!','Leute schieben einen Zug!','einen Stadtbus schieben','einen Stadtbus erwischen','dramatic','exclamation'),
(4882,'de','Sie ziehen ein Luftfahrzeug!','Sie ziehen einen Lastwagen!','ein riesiges Luftfahrzeug ziehen','ein startendes Luftfahrzeug','dramatic','exclamation'),
(4883,'de','Die Türen enthüllen grüne Hügel.','Die Türen enthüllen ein blaues Meer.','ein grünes Tal enthüllen','ein Geheimnis enthüllen','chill','none'),
(4884,'de','Alle zeigen nach oben!','Alle zeigen nach unten!','auf den Himmel zeigen','auf eine Karte zeigen','dramatic','exclamation'),
(4885,'de','Sie gehen die Straße hinauf.','Sie gehen die Treppe hinauf.','eine sonnige Straße mit Kopfsteinpflaster','eine belebte Einkaufsstraße','business','none'),
(4886,'de','Der Weg ist so steil.','Der Weg ist so flach.','ein steiler Grasweg','ein steiler Preisanstieg','dramatic','none'),
(4887,'de','Wow, dieser Weg ist schmal!','Wow, dieser Weg ist breit!','ein schmaler Canyonweg','eine schmale Ladentür','dramatic','exclamation'),
(4888,'de','Alle laufen barfuß!','Alle rennen barfuß!','barfuß über den Sand laufen','barfuß auf heißen Steinen','gossip','exaggeration'),
(4889,'de','Die Plattform ist kreisförmig.','Die Plattform ist quadratisch.','eine kreisförmige weiße Plattform','ein Rundschreiben','business','none'),
(4890,'de','Alle umkreisen den Kreisel.','Alle umkreisen den Baum.','einen Kreisel umkreisen','einen Fußball umkreisen','chill','none'),
(4891,'de','Der ganze Campus lehnt sich zur Seite!','Der ganze Campus springt!','Studierende auf dem Campus-Rasen','ein Campus im Schnee','dramatic','exaggeration'),
(4892,'de','Diese Badeshorts sind so schnell!','Diese Schwimmflossen sind so schnell!','bunte Badeshorts','Shorts für Fußball','slang','exaggeration'),
(4893,'de','Bis ganz oben überfüllt!','Nur unten überfüllt!','ein überfülltes Baseballstadion','ein überfüllter Nachtbus','dramatic','exclamation'),
(4894,'de','Alle stehen still. Ganz normal.','Alle tanzen. Ganz normal.','stille Studierende in einer Halle','stilles Wasser in einem See','ironic','understatement'),
(4895,'de','Sie stehen auf gegenüberliegenden Seiten.','Sie stehen auf derselben Seite.','auf gegenüberliegenden Seiten','die entgegengesetzte Richtung','chill','none'),
(4896,'de','Alle haben einen langen Schatten!','Alle haben einen langen Schal!','lange Schatten auf Steinen','Schatten an einer Wand','slang','none'),
(4897,'de','Alle schließen sich der Umarmung an!','Alle schließen sich dem Tanz an!','sich einer Gruppenumarmung anschließen','sich einem Tanzkurs anschließen','dramatic','exaggeration'),
(4898,'de','Sie setzen Glasplatten ein.','Sie setzen Holzplatten ein.','Glasplatten einsetzen','Glasplatten putzen','chill','none'),
(4899,'de','Der Rettich ist riesig, Alter!','Die Melone ist riesig, Alter!','ein riesiger weißer Rettich','ein riesiger Kürbis','slang','exclamation'),
(4900,'de','Der hohe Stapel ist umgefallen!','Der hohe Baum ist umgefallen!','ein hoher Stapel Paletten','ein Stapel Pfannkuchen','dramatic','exclamation'),
(4901,'de','Blaues Meer, blauer Himmel, großer Sprung.','Blauer Pool, blauer Himmel, großer Sprung.','ins blaue Wasser springen','in einen blauen Pool springen','slang','none'),
(4902,'de','Ein U-Boot, dann ein Wal. Schneller schwimmen!','Ein U-Boot, dann ein Hai. Schneller schwimmen!','ein U-Boot im See','ein U-Boot im Hafen','dramatic','guessing'),
(4903,'de','Alle drängen sich auf dem Platz zusammen. Warum?','Autos drängen sich auf dem Platz zusammen. Warum?','sich auf dem Platz zusammendrängen','sich um eine Bühne zusammendrängen','gossip','guessing')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
