begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(5210,'de','Eine „gefährliche“ Gans lässt sie zurückweichen.','Ein „gefährlicher“ Hund lässt sie zurückweichen.','vor einer Gans zurückweichen','vor dem Regen zurückweichen','ironic','exaggeration'),
(5211,'de','Was für eine glückliche Rückkehr nach Hause!','Was für eine traurige Rückkehr nach Hause!','eine glückliche Rückkehr nach Hause','eine Rückkehr in die Schule','dramatic','exclamation'),
(5212,'de','Große Umarmungen am Bahnhof!','Große Umarmungen am Flughafen!','Umarmungen am Bahnhof','eine Radiostation','dramatic','exclamation'),
(5213,'de','Ein roter Zug ist auf der Eisenbahnstrecke.','Eine rote Straßenbahn ist auf der Eisenbahnstrecke.','ein Bahnsteig der Eisenbahn','eine Eisenbahn in den Bergen','chill','none'),
(5214,'de','Fahrrad, Roller, dann Wüste!','Fahrrad, Roller, dann Dschungel!','ein Kamel in der Wüste','ein Kamel im Zoo','dramatic','exclamation'),
(5215,'de','Sie ist beim Radfahren an einem Fjord.','Sie ist beim Radfahren in einer Stadt.','Radfahren am Fjord','Radfahren in der Stadt','chill','none'),
(5216,'de','Sie macht einen langsamen Spaziergang.','Sie macht eine langsame Schwimmrunde.','ein Spaziergang an Blumenständen vorbei','ein Spaziergang am Strand','chill','none'),
(5217,'de','Er trägt eine gelbe Weste.','Er trägt eine orange Weste.','eine gelbe Warnweste','eine Weste unter dem Hemd','chill','none'),
(5218,'de','Sie checkt jedes Zimmer.','Sie putzt jedes Zimmer.','ein Zimmer mit Bogenfenstern','ein Zimmer mit Kamin','chill','none'),
(5219,'de','Die Mitbewohner haben Pasta gemacht. Lecker.','Die Mitbewohner haben Pizza gemacht. Lecker.','zwei Mitbewohner in einer WG','zwei Mitbewohner beim Auszug','low_iq','none'),
(5220,'de','Jemand schneidet die Rose ab.','Jemand gießt die Rose.','einen Rosenstiel abschneiden','einem Hund die Krallen schneiden','chill','none'),
(5221,'de','Der Weg windet sich die Hügel hinauf.','Der Fluss windet sich die Hügel hinauf.','ein Weg, der sich bergauf windet','ein Fluss, der sich bergab windet','chill','none'),
(5222,'de','Sie steigt steinerne Stufen hinauf.','Sie steigt hölzerne Stufen hinauf.','Steinstufen einen Berg hinauf','Steinstufen zu einem Strand','chill','none'),
(5223,'de','Ihre Route ist rot markiert.','Ihre Route ist blau markiert.','eine Route auf einer Karte','eine Busroute durch die Stadt','chill','none'),
(5224,'de','Er hat eine königliche Kapelle.','Er hat ein königliches Pferd.','ein königlicher Thron','eine königliche Hochzeit','chill','none'),
(5225,'de','Sie beendet das Rennen mit Mega-Vorsprung!','Sie beendet das Rennen mit Mega-Rückstand!','ein Rennen beenden','ihre Hausaufgaben beenden','slang','none'),
(5227,'de','Sie hat mehrere neue Fans.','Sie hat mehrere neue Katzen.','mehrere rennende Hunde','mehrere fahrende Autos','gossip','exaggeration'),
(5228,'de','Es schneit heftig!','Es regnet heftig!','es schneit auf einem Stadtplatz','es schneit an einem Strand','dramatic','exclamation'),
(5229,'de','Sie hat eine Handvoll Schnee geworfen.','Sie hat eine Handvoll Sand geworfen.','eine Handvoll Pulverschnee','eine Handvoll Münzen','chill','none'),
(5230,'de','In der Puppe steckt noch eine Puppe!','In der Puppe steckt eine Münze!','eine bemalte Holzpuppe','ein Puppenhaus','dramatic','exclamation'),
(5231,'de','Zu ihrer Gastfreundschaft gehört Tee.','Zu ihrer Gastfreundschaft gehört Bier.','Gastfreundschaft mit Tee und Essen','ein Job im Gastgewerbe','business','none'),
(5232,'de','Sie segelt eine Jacht.','Sie putzt eine Jacht.','eine klassische Segeljacht','eine Jacht im Hafen','chill','none'),
(5233,'de','Die militärische Parade ist riesig.','Die militärische Parade ist winzig.','eine militärische Parade','ein militärisches Krankenhaus','chill','none'),
(5234,'de','Jede Reihe steht perfekt gerade.','Jede Reihe ist ein totales Chaos.','Reihen salutierender Frauen','Reihen rennender Männer','business','none'),
(5235,'de','Sie stempelt die Fracht ab.','Sie bemalt die Fracht.','Fracht in einem Containerhafen','Fracht an einem Flughafen','chill','none'),
(5237,'de','Tee unter einem Himmel voller Sterne.','Tee unter einem Himmel voller Vögel.','Sterne über einem Wüstencamp','Sterne über einer Stadt','chill','none'),
(5238,'de','Selfie auf der roten Düne? Ikonisch.','Selfie auf der weißen Düne? Ikonisch.','ein Selfie auf der roten Düne','eine Fahrt im Dünenbuggy','slang','none'),
(5239,'de','Was für eine perfekte Freilassung!','Was für eine perfekte Landung!','die Freilassung eines Falken','die Veröffentlichung eines Albums','dramatic','exclamation'),
(5240,'de','Die Flügel des Falken sind ausgebreitet.','Die Flügel des Falken sind angelegt.','beide Flügel ausbreiten','Hähnchenflügel auf einem Teller','chill','none'),
(5241,'de','Sie gleitet in eine Kammer.','Er gleitet in eine Kammer.','eine leuchtende medizinische Kammer','ein Kammermusikkonzert','chill','none'),
(5242,'de','Ihr Satin-Morgenmantel sieht elegant aus.','Ihr Woll-Morgenmantel sieht elegant aus.','ein eleganter Satin-Morgenmantel','eine elegante Abendparty','flirt','none'),
(5243,'de','Sie hat den ganzen Monat eingeplant.','Sie hat die ganze Woche eingeplant.','den ganzen Monat einplanen','ein Meeting einplanen','business','none'),
(5244,'de','Die Mitschüler haben einen Deal gemacht.','Die Lehrer haben einen Deal gemacht.','zwei Mitschüler treffen sich','die Party eines Mitschülers','chill','guessing'),
(5245,'de','Die Chemikalie leuchtet lila!','Die Chemikalie leuchtet orange!','eine lila leuchtende Chemikalie','eine Chemikalie in einem Tank','dramatic','exclamation'),
(5246,'de','Sie hält einen rosa Kolben.','Sie hält ein rosa Handy.','ein Kolben mit blauer Flüssigkeit','ein Kolben mit heißem Tee','nerd','none'),
(5247,'de','Nonna ist sauer wegen der Fußspuren.','Nonna ist sauer wegen der kaputten Vase.','schlammige Fußspuren im Flur','schlammige Fußspuren im Garten','gossip','blaming_someone'),
(5248,'de','Sie zahlt die Miete für den Roller.','Sie zahlt die Miete für das Fahrrad.','die Miete für einen Roller','die Miete für eine Wohnung','chill','none'),
(5249,'de','Er wäscht eine Pfanne, die schon bessere Tage gesehen hat.','Er wäscht eine Tasse, die schon bessere Tage gesehen hat.','einen verrußten Topf waschen','sein Gesicht waschen','ironic','cliche'),
(5250,'de','Sie führt einen geschäftlichen Anruf.','Sie führt einen Videoanruf.','ein Anruf am Bürotelefon','ein Videoanruf am Laptop','business','none'),
(5251,'de','Sie tippt und telefoniert gleichzeitig!','Sie tippt und isst gleichzeitig!','beim Telefonieren tippen','eine SMS tippen','dramatic','exclamation'),
(5252,'de','Tropisches Obst ist im Angebot.','Tiefkühlobst ist im Angebot.','ein Haufen tropischer Früchte','ein tropisches Aquarium','business','none'),
(5253,'de','Diese älteren Leute tanzen besser als ich.','Diese älteren Leute schwimmen besser als ich.','ältere Tänzer im Park','ältere Schwimmer im Becken','slang','exaggeration'),
(5254,'de','Guck dir die beiden Partner beim Tanzen an!','Guck dir die beiden Partner beim Schwimmen an!','mit dem Partner tanzen','mit dem Partner Karten spielen','flirt','exclamation'),
(5255,'de','Er sieht sehr schuldig aus – und total geschockt.','Sie sieht sehr schuldig aus – und total geschockt.','ein schuldiger junger Mann','ein schuldiger Richter','gossip','guessing'),
(5257,'de','Der Butler trägt Tee.','Der Butler trägt Wein.','ein Butler mit Tee','ein Butler öffnet die Tür','chill','none'),
(5258,'de','Rooftop-Bar, Shaker-Party!','Keller-Bar, Shaker-Party!','eine Rooftop-Bar bei Sonnenuntergang','ein Schokoriegel','slang','exclamation'),
(5259,'de','Der große Hund schüttelt sein nasses Fell. Dusche für alle.','Die große Katze schüttelt ihr nasses Fell. Dusche für alle.','das nasse Fell schütteln','das nasse Fell bürsten','ironic','exaggeration'),
(5261,'de','Sogar der Jogger hat seinen Anteil bekommen!','Sogar der Radfahrer hat seinen Anteil bekommen!','ein Anteil an der Pizza','ein Anteil an der Firma','gossip','exclamation'),
(5262,'de','So ein „stabiles“ Regal!','So ein „stabiler“ Tisch!','ein nicht sehr stabiles Regal','ein stabiler Holzstuhl','ironic','exclamation'),
(5263,'de','Ein Foto steht auf dem Regal.','Ein Spiegel steht auf dem Regal.','ein gerahmtes Familienfoto','ein Familienfoto machen','chill','none'),
(5264,'de','Sie verschiebt das Sofa.','Sie verschiebt den Kühlschrank.','Möbel verschieben','im Auto die Gänge wechseln','chill','none'),
(5265,'de','Das Schiff transportiert Container.','Das Schiff transportiert Autos.','ein Schiff mit Containern','ein Lkw mit Containern','chill','none'),
(5266,'de','Sie hat das Telefon fallen lassen!','Sie hat die Teetasse fallen lassen!','ein heruntergefallenes Telefon','eine Telefonzelle','dramatic','exclamation'),
(5267,'de','Ihre Pistole liegt auf einem Ständer.','Ihre Pistole liegt auf einem Stuhl.','eine Pistole auf einem Ständer','eine Pistole im Holster','business','none'),
(5268,'de','Sie zielt mit ihrem Gewehr.','Sie putzt ihr Gewehr.','im Liegen mit dem Gewehr schießen','ein Gewehr auf Skiern tragen','chill','none'),
(5269,'de','Sie hat einen Mantel gekauft.','Sie hat ein Kleid gekauft.','einen olivgrünen Mantel kaufen','ein neues Auto kaufen','business','none'),
(5270,'de','Sie kauft dem Supermarkt das ganze Müsli weg!','Sie kauft dem Supermarkt die ganze Suppe weg!','ein Einkaufswagen im Supermarkt','ein Supermarktparkplatz','gossip','exaggeration'),
(5271,'de','Ihr Schrei erfüllt den Canyon!','Ihr Lied erfüllt den Canyon!','ein Schrei über dem Canyon','ein Hilfeschrei','dramatic','exclamation'),
(5272,'de','Die Wanderer rasten total aus.','Die Wanderer gehen nach Hause.','jubelnde Wanderer am Canyon','Wanderer ruhen im Zelt','slang','none'),
(5273,'de','Das Model rockt die grüne Hose.','Das Model rockt die orange Hose.','ein Model auf dem Laufsteg','ein Modellflugzeug','slang','none'),
(5274,'de','Dusche an. Jetzt ist er durchnässt.','Dusche aus. Jetzt ist er durchnässt.','durchnässt unter der Dusche','durchnässt im Regen','low_iq','none'),
(5275,'de','Zwei egoistische Kids, eine Fernbedienung.','Zwei egoistische Kids, ein Handy.','egoistische Kinder streiten sich','ein egoistischer Fahrer beim Parken','gossip','none'),
(5276,'de','Ein Keks, zwei Geschwister: Krieg.','Ein Kuchen, zwei Geschwister: Krieg.','Geschwister bauen eine Höhle','Geschwister machen Hausaufgaben','dramatic','exaggeration'),
(5277,'de','Sie haben zugestimmt: halbe-halbe.','Sie haben zugestimmt: alles für ihn.','dem Teilen eines Kekses zustimmen','dem Teilen eines Zimmers zustimmen','chill','none'),
(5278,'de','Ecke erreicht. Weiter geht''s.','Fluss erreicht. Weiter geht''s.','die Ecke zweier Straßen','eine Ecke im Zimmer','business','none'),
(5279,'de','Er unterschreibt eine riesige Schriftrolle mit einem riesigen Stift!','Er unterschreibt eine riesige Schriftrolle mit einem winzigen Stift!','eine riesige Schriftrolle unterschreiben','eine alte Schriftrolle lesen','dramatic','exclamation'),
(5280,'de','Sie liest den Wegweiser.','Sie streicht den Wegweiser an.','einen hölzernen Wegweiser lesen','einen hölzernen Wegweiser streichen','chill','none'),
(5281,'de','Der Star singt auf der Bühne.','Der Star tanzt auf der Bühne.','ein Star auf der Bühne','ein Stern am Himmel','chill','none'),
(5282,'de','Alle singen ein Lied.','Alle schreiben ein Lied.','ein Lied singen','ein Lied im Radio','gossip','none'),
(5283,'de','Nur ein kleiner Turm aus Tellern.','Nur ein kleiner Turm aus Tassen.','ein Turm aus Tellern','ein Turm aus Gläsern','chill','understatement'),
(5284,'de','Schicke metallische Rüstung, Ritter.','Schicke metallische Krone, Ritter.','eine komplette metallische Rüstung','eine Metal-Band','flirt','none'),
(5285,'de','Pures Glück im Garten.','Pures Glück in der Küche.','Glück in einem sonnigen Garten','Glück an einem sonnigen Strand','chill','none'),
(5286,'de','Beide wollen das Sweatshirt!','Beide wollen den Teddybären!','an einem lila Sweatshirt ziehen','ein lila Sweatshirt waschen','dramatic','exclamation'),
(5287,'de','Fünfzehn Mädchen, null Stille!','Fünfzehn Jungs, null Stille!','ein Raum ohne Stille','eine Minute Stille','dramatic','exaggeration'),
(5288,'de','Er fliegt auf seinen Skiern den Hang hinunter!','Er fliegt auf seinem Schlitten den Hang hinunter!','Carven auf Skiern','Skier an einer Wand','dramatic','exaggeration'),
(5289,'de','Der Haut fehlt Feuchtigkeit.','Der Haut fehlen Poren.','Haut ohne Feuchtigkeit','Feuchtigkeit am Fenster','nerd','none'),
(5290,'de','Was für ein hoher Wolkenkratzer!','Was für ein hoher Leuchtturm!','ein Wolkenkratzer mit Spitze','ein Wolkenkratzer im Bau','dramatic','exclamation'),
(5291,'de','Jeder Geschäftsmann schläft.','Jeder Geschäftsmann liest.','schlafende Geschäftsmänner im Flugzeug','schlafende Geschäftsmänner im Zug','chill','none'),
(5292,'de','Niemand hier ist besonders produktiv.','Alle hier sind sehr produktiv.','kein produktiver Tag','ein produktives Teammeeting','ironic','understatement'),
(5293,'de','Der Ball ist jetzt in seinem Handschuh.','Der Ball ist jetzt in seiner Kappe.','ein Baseballhandschuh aus Leder','ein Handschuh für den Winter','chill','none'),
(5294,'de','Ihre Füße lieben die Hausschuhe.','Ihre Füße lieben die Socken.','flauschige Schaf-Hausschuhe','Hausschuhe unter dem Bett','chill','exaggeration'),
(5295,'de','Er bläst ein riesiges Horn.','Er bläst ein winziges Horn.','ein langes Horn blasen','ein Horn an einem Schaf','chill','none'),
(5296,'de','Er kocht traditionelles Essen!','Er kauft traditionelles Essen!','traditionelles Essen kochen','ein traditioneller Tanz','dramatic','exclamation'),
(5297,'de','Die alte Burg ist dem Verfall preisgegeben.','Die alte Brücke ist dem Verfall preisgegeben.','eine Burg im Verfall','eine Burg im Schnee','chill','none'),
(5298,'de','Ihr Blazer ist beige.','Ihr Blazer ist schwarz.','ein taillierter beiger Blazer','einen Blazer anprobieren','chill','none'),
(5299,'de','Ihre Würstchen sind hier illegal!','Ihre Bücher sind hier illegal!','illegales Essen im Koffer','illegales Parken am Flughafen','gossip','exclamation'),
(5301,'de','Ihre Allergie hasst diese Wiese.','Ihre Allergie hasst diesen Strand.','eine Allergie gegen Pollen','eine Allergie gegen Hunde','low_iq','exaggeration'),
(5302,'de','Die Blüten haben ihn zum Niesen gebracht!','Die Blüten haben ihn zum Weinen gebracht!','Niesen unter Blüten','Kirschblüten malen','dramatic','blaming_someone'),
(5303,'de','Schneeflocken auf ihrem Fäustling.','Schneeflocken auf ihrem Schuh.','eine Schneeflocke auf einem Fäustling','eine Schneeflocke am Fenster','chill','none'),
(5304,'de','Iiih! Schmutz überall an ihren Händen!','Iiih! Farbe überall an ihren Händen!','Schmutz an ihren Händen','Schmutz an ihren Schuhen','dramatic','exclamation'),
(5305,'de','Ihre Gesellschaft arbeitet hart.','Ihre Gesellschaft ist im Urlaub.','eine ganze Gesellschaft bei der Arbeit','eine Gesellschaft auf einer Party','business','none'),
(5306,'de','So bequem auf einem Sofa!','So bequem in einem Bett!','bequem auf einem vollen Sofa','bequem in einem großen Bett','dramatic','exclamation'),
(5307,'de','Das Zimmer ist sehr geräumig.','Das Zimmer ist sehr klein.','ein geräumiges Wohnzimmer','ein geräumiger Kofferraum','business','none'),
(5308,'de','Ein Mann bringt ihr Sonnenblumen.','Ein Mann bringt ihr Rosen.','ein Strauß Sonnenblumen','ein Feld voller Sonnenblumen','chill','none'),
(5309,'de','Jemand hat ihr eine süße Notiz hinterlassen.','Jemand hat ihr eine traurige Notiz hinterlassen.','eine Notiz mit Smiley','eine Notiz am Kühlschrank','gossip','none'),
(5310,'de','Ein Sohn hilft, das Auto zu reparieren.','Ein Sohn hilft, das Auto zu waschen.','ein Sohn mit einem Schraubenschlüssel','ein Sohn wäscht das Auto','chill','none'),
(5311,'de','Jetzt ist die ganze Gruppe ruhig.','Jetzt ist die ganze Gruppe wütend.','ruhig unter Decken','ruhig unter Druck','chill','none'),
(5312,'de','Grillen im Hinterhof? Los geht''s!','Poolparty im Hinterhof? Los geht''s!','Grillen im Hinterhof','ein Pool im Hinterhof','slang','exclamation'),
(5313,'de','Neonfarbene Schilder bedecken jede Wand.','Papierschilder bedecken jede Wand.','leuchtende neonfarbene Schilder','neonfarbene Lichter in einem Club','chill','none'),
(5314,'de','In ihrem Korb steckt ganz Paris!','In ihrer Tasche steckt ganz Paris!','ein Korb voller Souvenirs','ein Korb voller Obst','slang','exaggeration'),
(5315,'de','Sie hat jede Menge Postkarten. Für wen wohl?','Sie hat jede Menge Briefmarken. Für wen wohl?','Postkarten von Paris','eine Postkarte schreiben','gossip','guessing'),
(5316,'de','Ich liebe ihr wippendes, lockiges Haar.','Ich liebe ihr wippendes, glattes Haar.','dunkles, eng lockiges Haar','langes, lockiges blondes Haar','flirt','none'),
(5317,'de','Ihre Rüschen fliegen!','Ihre Schuhe fliegen!','Lagen roter Rüschen','Rüschen an einem Hemdkragen','dramatic','exclamation'),
(5318,'de','Sie spricht vor Publikum.','Sie singt vor Publikum.','ins Mikrofon sprechen','am Telefon sprechen','business','none'),
(5319,'de','Die Spinne sitzt unter ihrem Spinnennetz.','Die Spinne sitzt über ihrem Spinnennetz.','ein Spinnennetz zwischen Ästen','ein Spinnennetz in einer Ecke','chill','none'),
(5320,'de','Sie führt eine Wirbelsäule vor.','Sie führt ein Herz vor.','etwas am Wirbelsäulenmodell vorführen','auf der Straße demonstrieren','business','none'),
(5321,'de','Er läuft Schlittschuh wie ein Profi.','Er fährt Ski wie ein Profi.','auf einem Bein Schlittschuh laufen','auf der Straße Schlittschuh laufen','slang','cliche'),
(5322,'de','Eklige Suppe! Er hat sie ausgespuckt.','Ekliger Tee! Er hat ihn ausgespuckt.','grüne Suppe ausspucken','einen Kirschkern ausspucken','low_iq','none'),
(5323,'de','Dieser Stein hat einen Mega-Platscher gemacht.','Dieses Boot hat einen Mega-Platscher gemacht.','einen großen Stein werfen','einen flachen Stein hüpfen lassen','slang','exaggeration'),
(5324,'de','Der Schwamm hat die Soße besiegt!','Der Schwamm hat den Käse besiegt!','ein seifiger Schwamm','ein Biskuitkuchen','dramatic','exclamation'),
(5325,'de','Die Ehepartner haben ein Dokument unterschrieben.','Die Ehepartner haben ein Dokument verbrannt.','Ehepartner unterschreiben Papiere','Ehepartner streiten zu Hause','business','none'),
(5326,'de','Der Trainer tapt ihr den Knöchel.','Der Trainer tapt ihr das Handgelenk.','ein Trainer hilft einer Turnerin','ein Trainer brüllt Spieler an','chill','none'),
(5327,'de','Die Kundin trägt einen schwarzen Umhang.','Die Kundin trägt einen weißen Umhang.','ein schwarzer Friseurumhang','ein Superheldenumhang','chill','none'),
(5328,'de','Sie schnuppert an einer pfirsichfarbenen Bluse.','Sie schnuppert an einer weißen Bluse.','eine pfirsichfarbene Rüschenbluse','eine pfirsichfarbene Bluse bügeln','chill','none'),
(5329,'de','Der Samen hat eine winzige Wurzel!','Der Samen hat eine winzige Blüte!','ein Samen mit Wurzel','ein Samen im Schnabel','dramatic','exclamation'),
(5330,'de','Der „geheime“ Spion hat ein Loch in seiner Zeitung.','Der „geheime“ Spion hat ein Loch in seinem Hut.','ein Spion hinter einer Zeitung','ein Spion hinter einer Tür','ironic','none'),
(5331,'de','Ihre Fitness? Sie zerdrückt Wassermelonen!','Ihre Fitness? Sie zerdrückt Kokosnüsse!','Fitness an einer Strandbar','eine Fitness-App','slang','exaggeration'),
(5332,'de','Das Personal tritt als starke Einheit auf.','Die Gäste treten als starke Einheit auf.','die Einheit des Teams','die Einheit des Landes','business','none'),
(5333,'de','Jedes Treppenhaus ist noch edler!','Jedes Treppenhaus ist noch dreckiger!','ein prächtiges Treppenhaus aus Marmor','ein Treppenhaus im Leuchtturm','dramatic','exclamation'),
(5334,'de','Die Fans respektieren diesen Moment.','Die Fans ignorieren diesen Moment.','den Moment respektieren','das Tempolimit respektieren','chill','none'),
(5335,'de','Sie ist ein begeisterter Fan.','Sie ist eine begeisterte Spielerin.','ein begeisterter Fußballfan','ein begeisterter Tennisfan','chill','none'),
(5336,'de','Seine Kappe zeigt seine Treue.','Sein Schal zeigt seine Treue.','Treue zum Verein','Treue zum König','dramatic','none'),
(5337,'de','Croissant im Mund, er fährt mit der Bahn.','Pizza im Mund, er fährt mit der Bahn.','mit der Bahn reisen','mit dem Flugzeug reisen','gossip','none'),
(5338,'de','Du kannst für 10 Euro bleiben oder für 10.000 Euro.','Du kannst für 10 Euro bleiben oder für 1.000 Euro.','im Hostel bleiben','zu Hause bleiben','business','cheap_quality'),
(5339,'de','Sie steuert einen Bus.','Sie steuert eine Straßenbahn.','einen Stadtbus steuern','eine Drohne steuern','chill','none'),
(5340,'de','Ein Karton kommt in die Garage.','Ein Karton kommt ins Auto.','eine offene Garage','eine Garage voller Autos','business','none'),
(5341,'de','Der Junge nagelt ein Brett fest.','Der Junge streicht ein Brett an.','ein Brett nageln','ein Poster annageln','chill','none'),
(5342,'de','Zuckerguss auf ihrer Zunge. Yummy!','Ketchup auf ihrer Zunge. Yummy!','Zuckerguss auf ihrer Zunge','sich am Tee die Zunge verbrennen','slang','exclamation'),
(5343,'de','Die Mädchen haben zwei gleiche Betten.','Die Mädchen haben ein Etagenbett.','zwei gleiche Einzelbetten','ein Hotel-Zweibettzimmer','chill','none'),
(5344,'de','Sie haben eine große Steppdecke genäht!','Sie haben eine große Flagge genäht!','eine fertige Patchwork-Steppdecke','eine Steppdecke auf dem Bett','dramatic','exclamation'),
(5345,'de','Sie lehnt am Geländer.','Sie lehnt an einem Baum.','am Brückengeländer lehnen','am Gartenzaun lehnen','chill','none'),
(5346,'de','Er klopft sich auf den Magen.','Er klopft sich auf den Kopf.','ein voller Magen','ein Magen voller Suppe','chill','none'),
(5347,'de','Der Verkehr kommt zum Halt.','Die Züge kommen zum Halt.','ein Halt für den Verkehr','ein Halt für einen Kaffee','chill','none'),
(5348,'de','Sie dankt dem Mann mit dem Regenschirm.','Sie dankt dem Mann mit dem Hund.','einem netten Fremden danken','dem Busfahrer danken','chill','none'),
(5349,'de','Sie verleiht schon wieder eine Medaille!','Sie verleiht schon wieder einen Pokal!','eine Medaille verleihen','einen Musikpreis verleihen','dramatic','exaggeration'),
(5350,'de','Mitten in der Luft über dem Bach. Mutig!','Mitten in der Luft über dem See. Mutig!','über einen Bach springen','in einem Bach schwimmen','dramatic','exclamation'),
(5351,'de','Orange Straßenlaternen, so gemütlich.','Blaue Straßenlaternen, so gemütlich.','eine Reihe Straßenlaternen','eine kaputte Straßenlaterne','slang','none'),
(5352,'de','Ihre Frustration liegt bei 1000 %.','Ihre Frustration liegt bei 0 %.','Frustration am Laptop','Frustration über einen Lehrer','nerd','exaggeration'),
(5353,'de','Der Papierkram gewinnt.','Der Papierkram schrumpft.','Türme aus Papierkram','Papierkram am Laptop','dramatic','exaggeration'),
(5354,'de','Die Klasse folgt ihr gut.','Die Klasse folgt ihm gut.','eine Klasse im Park','eine Klasse in einer Schule','business','none'),
(5355,'de','Sogar die Katze macht den Trainer nach!','Sogar der Hund macht den Trainer nach!','ein Trainer im Park','ein Hundetrainer mit Leckerlis','gossip','exclamation'),
(5356,'de','Yoga auf dem Dach bei Sonnenuntergang: Goals.','Yoga am Strand bei Sonnenuntergang: Goals.','Yoga auf einem Dach','Yoga im Fitnesskurs','slang','exaggeration'),
(5357,'de','Der Hund hat einen vornehmeren Kinderwagen als die meisten Babys.','Die Katze hat einen vornehmeren Kinderwagen als die meisten Babys.','ein vornehmer Chrom-Kinderwagen','eine Kostümparty','dramatic','exaggeration'),
(5358,'de','Sie späht zwischen Büchern hindurch.','Sie späht durch die Jalousien.','durch eine Lücke spähen','in ein Buch spähen','gossip','none'),
(5359,'de','Das Nilpferd versteckt sich vor ihr.','Die Ente versteckt sich vor ihr.','ein Nilpferd im Fluss','ein Nilpferd auf dem Steg','chill','guessing'),
(5360,'de','Die U-Bahn ist „ein bisschen“ voll.','Die U-Bahn ist „ein bisschen“ leer.','eine überfüllte U-Bahn-Station','eine leere U-Bahn-Station','ironic','understatement'),
(5361,'de','Sechs Taschen sind „einfach“ zu schieben.','Sechs Kisten sind „einfach“ zu schieben.','keine einfache Reise','keine einfache Prüfung','ironic','understatement'),
(5362,'de','Die albernste Brille der Insel!','Der albernste Hut der Insel!','alberne Herz-Sonnenbrille','alberne Herzluftballons','dramatic','exaggeration'),
(5363,'de','Sie helfen dem Läufer.','Sie helfen dem Radfahrer.','einem erschöpften Läufer helfen','einem verirrten Touristen helfen','chill','none'),
(5364,'de','Zwei Helden unterstützen sie!','Zwei Krankenschwestern unterstützen sie!','eine müde Läuferin unterstützen','einen müden Fahrer unterstützen','dramatic','exaggeration'),
(5365,'de','Er senkt seine Waffe.','Er reinigt seine Waffe.','eine Paintball-Waffe senken','eine Paintball-Waffe laden','chill','none'),
(5366,'de','Er ergibt sich!','Er greift an!','sich mit erhobenen Händen ergeben','seinen Reisepass abgeben','dramatic','exclamation'),
(5368,'de','Die Hitze lässt sie leiden.','Die Kälte lässt sie leiden.','in der Hitze leiden','an einer Erkältung leiden','dramatic','none'),
(5369,'de','Harter Boxer, schweißgebadet.','Harter Boxer, vom Regen durchnässt.','ein harter junger Boxer','ein hartes Stück Fleisch','chill','none'),
(5370,'de','Er paddelt ein gelbes Kanu.','Er paddelt ein rotes Kanu.','ein gelbes Kanu paddeln','ein Kanu nach Hause tragen','chill','none'),
(5371,'de','Mit Blumengirlanden sehen sie cool aus.','Mit Papierkronen sehen sie cool aus.','Blumengirlanden tragen','drinnen eine Girlande aufhängen','slang','none'),
(5372,'de','Sein Besen schiebt Laub.','Sein Besen schiebt Schnee.','ein Besen und trockenes Laub','ein Besen in der Küche','chill','none'),
(5373,'de','Alles dehnt sich aus!','Alles schrumpft!','eine Hüpfburg dehnt sich aus','eine Firma expandiert ins Ausland','dramatic','exclamation'),
(5374,'de','Das Wasser ist ein bisschen flach.','Das Wasser ist ein bisschen tief.','im flachen Wasser schwimmen','ein flacher Suppenteller','ironic','understatement'),
(5375,'de','Sie schwingt wie ein Profi.','Sie schwimmt wie ein Profi.','einen Golfschläger schwingen','einen Baseballschläger schwingen','flirt','cliche'),
(5376,'de','Er hat den Lichtschalter gedrückt. Licht!','Er hat gegen den Lichtschalter getreten. Licht!','einen Lichtschalter drücken','eine Weiche an der Bahnstrecke','dramatic','exclamation'),
(5377,'de','Sie hat die Teller eingesammelt.','Sie hat die Äpfel eingesammelt.','eingesammelte schmutzige Teller','rote Äpfel sammeln','business','none'),
(5378,'de','Sie stellt Teller auf den Tisch.','Sie stellt den Wecker.','Teller auf den Tisch stellen','einen Wecker stellen','business','none'),
(5379,'de','Der Schneider hat die Jacke geändert.','Der Schneider hat das Hemd geändert.','ein dunkelblaues Sakko ändern','die Reisepläne ändern','chill','none'),
(5381,'de','Kaffee und ein langes Gespräch.','Bier und ein langes Gespräch.','ein Gespräch bei Kaffee','ein Gespräch per E-Mail','chill','none'),
(5382,'de','Alle am Tisch diskutieren gleichzeitig!','Alle im Bus diskutieren gleichzeitig!','am Cafétisch diskutieren','am Telefon diskutieren','dramatic','exaggeration'),
(5383,'de','So viele Taxis auf dem Boulevard!','So viele Busse auf dem Boulevard!','ein breiter Boulevard voller Taxis','ein Boulevard mit alten Bäumen','slang','exclamation'),
(5384,'de','Die Meister rasten total aus.','Die Meister gehen nach Hause.','Meister in gestreiften Trikots','ein Meister auf dem Podest','slang','none'),
(5385,'de','Der Ballwechsel endet mit einem Sieg.','Der Ballwechsel endet mit einer Niederlage.','ein Sieg im Beachvolleyball','ein Sieg beim Kartenspiel','chill','none'),
(5386,'de','Sie zerreißt den Vertrag.','Sie zerreißt die Vorhänge.','einen Vertrag mittendurch reißen','Seiten aus einem Buch reißen','business','none'),
(5387,'de','Sie teilen ihren Kummer.','Sie teilen ihre Pizza.','Kummer auf dem Sofa','Kummer auf einer Beerdigung','dramatic','none'),
(5388,'de','Sie hat die Packung Chips gewonnen!','Sie hat die Packung Süßigkeiten gewonnen!','eine Packung Chips schnappen','eine Packung Samen','slang','banter'),
(5389,'de','Er weicht ihr aus wie Messi.','Sie weicht ihm aus wie Messi.','ihren Händen ausweichen','einem Fußball ausweichen','slang','exaggeration'),
(5390,'de','Ein Jugendlicher skatet, voll cool.','Ein Jugendlicher fährt Rad, voll cool.','ein Jugendlicher auf dem Skateboard','ein Jugendlicher auf dem Fahrrad','slang','none'),
(5391,'de','Schöner Sonnenuntergang, sie starren aufs Handy.','Schöner Sonnenuntergang, sie starren in ein Buch.','aufs Handy starren','in den Sonnenuntergang starren','ironic','none'),
(5392,'de','Sie schreien vor Schrecken!','Sie schreien in einem Auto!','vor Schrecken schreien','vor Freude schreien','dramatic','exclamation'),
(5393,'de','Der T-Rex hat ihr die Ruhe geraubt.','Der Hund hat ihr die Ruhe geraubt.','die Ruhe verlieren','die Ruhe bewahren','gossip','blaming_someone'),
(5394,'de','Jemand hat es zuerst beansprucht!','Niemand hat es zuerst beansprucht!','das gefrorene Land beanspruchen','eine verlorene Tasche beanspruchen','gossip','exclamation'),
(5395,'de','Ein Ranch-Arbeiter reitet am Zaun entlang.','Ein Ranch-Arbeiter reitet am Fluss entlang.','ein reitender Ranch-Arbeiter','eine Ranch voller Rinder','chill','none'),
(5396,'de','Orange Fahnen markieren die Linie.','Blaue Fahnen markieren die Linie.','eine Linie mit Fahnen markieren','eine Klassenarbeit korrigieren','business','none'),
(5397,'de','Eine gewaltige Welle, vier entspannte Möwen.','Eine gewaltige Welle, vier entspannte Enten.','eine gewaltige brechende Welle','ein mächtiger König','ironic','understatement'),
(5398,'de','Menschen bilden eine menschliche Kette.','Menschen bilden einen menschlichen Turm.','eine Menschenkette um die Erde','eine goldene Halskette','chill','none'),
(5399,'de','Zwei Schauspieler spielen in einem Theaterstück.','Zwei Hunde spielen in einem Theaterstück.','ein Theaterstück im Theater','ein Theaterstück in der Schule','chill','none'),
(5400,'de','Sie ist stilvoll in der Oper.','Sie ist stilvoll im Kino.','ein Abend in der Oper','eine Opernsängerin','flirt','none'),
(5401,'de','Alle fragen sich, was los ist.','Alle schlafen.','sich fragen, was los ist','sich fragen, wie das Wetter wird','chill','none'),
(5402,'de','Sie untersucht seinen Hals.','Sie untersucht seine Ohren.','eine Untersuchung seines Halses','ein Schal um seinen Hals','chill','none'),
(5403,'de','Sie checkt die Uhrzeit.','Sie checkt die Karte.','die Uhrzeit checken','Zeit verschwenden','chill','none'),
(5404,'de','Er ist so gierig beim Toast!','Er ist so gierig beim Kuchen!','ein gieriger Toastesser','ein gieriger Kuchenesser','dramatic','exclamation'),
(5405,'de','Das Kleinkind läuft!','Das Kleinkind krabbelt!','die ersten Schritte eines Kleinkinds','die ersten Wörter eines Kleinkinds','dramatic','exclamation'),
(5406,'de','Ihre Zehen sind neben einer Muschel.','Ihre Zehen sind neben einer Krabbe.','gespreizte Zehen im Sand','Zehen in einem Flip-Flop','chill','none'),
(5407,'de','Alle müssen jetzt dringend auf die Toilette.','Alle müssen jetzt dringend zum Ausgang.','eine Schlange vor der Toilette','die Toilette putzen','gossip','exaggeration'),
(5408,'de','Das Set hat das Stuhlproblem gelöst.','Das Set hat das Tischproblem gelöst.','ein rotes Werkzeugset','ein Erste-Hilfe-Set','business','none'),
(5409,'de','Sie zeigt ihre Zähne.','Sie zeigt ihre Zunge.','Vorderzähne in Nahaufnahme','ein fehlender Vorderzahn','chill','none'),
(5410,'de','Er hat eine grüne Zahnbürste.','Er hat eine blaue Zahnbürste.','eine grüne Zahnbürste','eine elektrische Zahnbürste','chill','none'),
(5411,'de','Er kriegt einen Klecks, sie kriegt Wirbel.','Er kriegt Wirbel, sie kriegt einen Klecks.','ein Wirbel aus Zahnpasta','ein Wirbel aus Schlagsahne','gossip','banter'),
(5412,'de','Griechische Säulen, kannelierter Marmor.','Griechische Säulen, rosa Marmor.','riesige kannelierte Marmorsäulen','eine Säule im Parkhaus','nerd','none'),
(5413,'de','Überall Autos. Hoffnungslos!','Überall Fahrräder. Hoffnungslos!','ein hoffnungsloser Stau','ein hoffnungsloses Fußballteam','low_iq','exclamation'),
(5414,'de','Er hält sich am Metallgeländer fest.','Er hält sich am Metalltor fest.','das Geländer einer Fußgängerbrücke','ein Zug auf der Schiene','chill','none'),
(5415,'de','Er wartet an einer roten Ampel.','Er wartet an einer Bushaltestelle.','eine rote Ampel','ein rotes Stoppschild','chill','none'),
(5416,'de','Sie liebt diese Lokomotive.','Sie liebt diesen Hubschrauber.','eine orange Elektrolokomotive','eine orange Dampflokomotive','gossip','guessing'),
(5417,'de','Die Straßenbahn landet im Depot.','Die Straßenbahn landet in einem Museum.','Straßenbahnen in einem Depot','Busse in einem Depot','chill','none'),
(5418,'de','Der Innenraum ist komplett aus Holz.','Der Innenraum ist komplett aus Plastik.','ein hölzerner Straßenbahn-Innenraum','ein moderner Auto-Innenraum','chill','none'),
(5419,'de','Er schafft jeden Transfer.','Er verpasst jeden Transfer.','ein Transfer zur Fähre','eine Banküberweisung','chill','none'),
(5420,'de','Er geht an Bord eines weißen Schiffs.','Er geht an Bord eines roten Schiffs.','ein kleines Passagierschiff','ein riesiges Frachtschiff','chill','none'),
(5421,'de','Der Müll ist überall!','Die Blumen sind überall!','eine Tonne voller Müll','eine Tonne voller Blumen','dramatic','exaggeration'),
(5422,'de','Recycling wie LeBron.','Recycling wie Messi.','in Recyclingtonnen werfen','alte Klamotten recyceln','slang','exaggeration'),
(5423,'de','Sein Rucksack reist weltweit.','Sein Rucksack bleibt in einer Stadt.','weltweit reisen','ein weltweites Handynetz','chill','none'),
(5424,'de','Sie haben den Vertrag unterschrieben.','Sie haben den Vertrag zerrissen.','Handschlag auf einen Vertrag','einen Vertrag zerreißen','business','none'),
(5425,'de','Das Geschäft ist unter Dach und Fach.','Das Geschäft ist geplatzt.','ein großes Geschäft abschließen','ein Geschäft auf dem Markt','business','none'),
(5427,'de','Der Umschlag hat ein rotes Siegel.','Der Umschlag hat ein blaues Siegel.','ein rotes Wachssiegel','eine Robbe am Strand','chill','none'),
(5428,'de','Der Lkw bringt Fracht.','Der Zug bringt Fracht.','Fracht auf einem großen Lkw','Fracht auf einem Schiff','chill','none'),
(5429,'de','Sie vertraut ihnen, mit geschlossenen Augen.','Sie vertraut ihnen, mit offenen Augen.','dem Team beim Auffangen vertrauen','einem Fremden online vertrauen','chill','none'),
(5430,'de','Sie ist schnell auf ihrem Rennrad.','Sie ist schnell auf ihrem Skateboard.','eine schnelle Fahrt durch Tunnel','eine schnelle Fahrt durch die Stadt','chill','none'),
(5431,'de','Sie fliegt in einem Heißluftballon.','Sie fliegt in einem Flugzeug.','ein Heißluftballon über Felsen','ein Luftballon für die Party','chill','none'),
(5432,'de','Er trickst den armen Kerl aus!','Er trickst den armen Hund aus!','einen Kunden austricksen','einen Lehrer austricksen','dramatic','exclamation'),
(5433,'de','Er schaltet die Lichter ein.','Er schaltet die Lichter aus.','eine Lichterkette einschalten','den Fernseher einschalten','chill','none'),
(5434,'de','Sie verschwendet Strom!','Sie verschwendet Papier!','viel Strom verbrauchen','Strom aus Solarzellen','dramatic','exaggeration'),
(5435,'de','OMG, ihre Outfits sind sich zum Verwechseln ähnlich.','OMG, ihre Outfits sind total verschieden.','zum Verwechseln ähnlich angezogen','ähnlich in Schuluniformen','gossip','none'),
(5436,'de','Das Team dreht Teigstränge.','Das Team schneidet Teigstränge.','einen Teigstrang drehen','einen Wollstrang drehen','business','none'),
(5437,'de','Party im Innenhof!','Party in der Küche!','eine Innenhofparty mit Lichtern','ein Schulhof in der Pause','slang','exclamation'),
(5438,'de','Eine Schüssel rote Füllung.','Eine Schüssel grüne Füllung.','rote Fruchtfüllung','eine Füllung beim Zahnarzt','chill','none'),
(5439,'de','Vier Männer, ein grauer Schirm!','Vier Männer, ein roter Schirm!','eine graue, verregnete Stadt','ein grauer Wintermantel','dramatic','exclamation'),
(5440,'de','Drachentag mit seinem Neffen.','Drachentag mit seinem Hund.','mit dem Neffen Drachen steigen lassen','mit dem Neffen angeln','chill','none'),
(5441,'de','Der Onkel hat sie gewinnen lassen.','Der Onkel hat ihn gewinnen lassen.','Armdrücken mit einem Onkel','Boxen mit einem Onkel','gossip','guessing'),
(5442,'de','Er kämpft mit jedem Ärmel!','Er kämpft mit jedem Reißverschluss!','Arme aus den Ärmeln ziehen','die Ärmel hochkrempeln','dramatic','exaggeration'),
(5443,'de','Solidarität füllt die Straße.','Solidarität füllt das Stadion.','eine Kette der Solidarität','eine Ladenkette','dramatic','none'),
(5444,'de','Sie arbeiten an einer Karte zusammen.','Sie arbeiten an einem Auto zusammen.','an einem Puzzle zusammenarbeiten','mit der Polizei zusammenarbeiten','chill','none'),
(5445,'de','Sein Schirm ist jetzt nutzlos.','Seine Aktentasche ist jetzt nutzlos.','ein nutzloser Schirm','ein nutzloser Schirm im Sonnenschein','dramatic','none'),
(5446,'de','Die Hügel sind neblig.','Die Hügel sind sonnig.','neblige Hügel über einem See','feuchte Augen bei einer Hochzeit','chill','none'),
(5447,'de','Diese Straße ist sehr abgelegen.','Diese Straße ist sehr belebt.','eine abgelegene Wüstenstraße','eine Fernbedienung','chill','none'),
(5448,'de','Werbetafeln an jeder Wand!','Gemälde an jeder Wand!','riesige beleuchtete Werbetafeln','eine Werbetafel auf einem Feld','dramatic','exaggeration'),
(5449,'de','Endlich steht sie in der Türöffnung.','Endlich steht sie im Garten.','eine offene steinerne Türöffnung','eine Türöffnung mit Vorhang','chill','none'),
(5450,'de','Geld sparen: Sie zieht bei den Geräten den Stecker.','Geld sparen: Sie steckt die Geräte ein.','bei jedem Gerät den Stecker ziehen','jedes Gerät aufladen','business','none'),
(5451,'de','Eine Injektion, jetzt ist er Hulk!','Eine Pille, jetzt ist er Hulk!','eine Injektion in den Arm','eine Injektion ins Bein','slang','exaggeration'),
(5452,'de','Ein friedlicher See im Nebel.','Ein friedlicher Strand im Nebel.','ein friedlicher Bergsee','ein friedliches Bergdorf','chill','none'),
(5453,'de','Sie füllt eine blaue Vase.','Sie füllt eine rote Vase.','Blumen in eine Vase stellen','eine Blumenvase zerbrechen','chill','none'),
(5454,'de','Tinte spritzt über den ganzen Pass.','Wasser spritzt über den ganzen Pass.','schwarze Tintentropfen','blaue Tinte an den Fingern','slang','exaggeration'),
(5455,'de','Er hat die Genehmigung bekommen!','Er hat keine Genehmigung bekommen!','eine Genehmigung für den Pass','eine Genehmigung von seinen Eltern','dramatic','exclamation'),
(5456,'de','Er hat die Erlaubnis bekommen.','Er hat keine Erlaubnis bekommen.','Erlaubnis zum Reisen','Erlaubnis zum Parken','chill','none'),
(5457,'de','Die Besucher haben einen Kuchen mitgebracht.','Die Besucher haben einen Hund mitgebracht.','Besucher mit Kuchen','Besucher in einem Museum','chill','none'),
(5458,'de','Das Vitamin sprudelt wie verrückt!','Die Milch sprudelt wie verrückt!','eine sprudelnde Vitamintablette','ein schmelzendes Vitamin-Gummibärchen','slang','exclamation'),
(5459,'de','Lava an jedem Hang.','Schnee an jedem Hang.','glühende Lavaströme','Lava in einer Lampe','dramatic','none'),
(5460,'de','Die Teetassen verursachen Übelkeit!','Das Riesenrad verursacht Übelkeit!','Übelkeit nach einer Fahrt','Übelkeit auf einem Schiff','dramatic','exclamation'),
(5461,'de','Alle werfen einen Stimmzettel ein.','Alle werfen einen Brief ein.','einen gefalteten Stimmzettel einwerfen','einen langen Stimmzettel lesen','chill','none'),
(5462,'de','Demokratie in einer Plastikbox.','Demokratie in einer Holzbox.','Demokratie in Aktion','Demokratie im Fernsehen','ironic','understatement'),
(5463,'de','Er schreibt Tagebuch auf See. Vibes.','Er schreibt Tagebuch im Bett. Vibes.','ein Reisetagebuch schreiben','eine Fachzeitschrift lesen','slang','none'),
(5464,'de','Sie ist schlank.','Er ist schlank.','eine schlanke Frau in Jeans','eine schlanke Frau in Shorts','chill','none'),
(5465,'de','Taille gemessen. Gürtel angepasst.','Arm gemessen. Gürtel angepasst.','ihre Taille messen','eine Schürze um ihre Taille','business','none'),
(5466,'de','Der Kellner wirkt sehr förmlich.','Der Kellner wirkt sehr lässig.','eine förmliche Kellneruniform','ein förmlicher Beschwerdebrief','chill','none'),
(5467,'de','Der Junge wacht geschockt auf!','Der Hund wacht geschockt auf!','im Etagenbett aufwachen','im Zelt aufwachen','dramatic','exclamation'),
(5468,'de','Die Schilder leuchten.','Die Bäume leuchten.','riesige leuchtende Schilder','ein Stoppschild','chill','none'),
(5469,'de','Dieser Spaziergänger hat 10.000 Schritte geschafft!','Dieser Spaziergänger hat 100 Schritte geschafft!','ein Spaziergänger mit Nordic-Walking-Stöcken','ein Spaziergänger in den Bergen','gossip','exclamation'),
(5471,'de','Die Blase zeigt: Es ist waagerecht.','Die Blase zeigt: Es ist schief.','ein waagerechter Bilderrahmen','eine waagerechte Straße','nerd','none'),
(5472,'de','Die Geldscheine fallen heraus.','Die Schlüssel fallen heraus.','Geldscheine fallen aus dem Portemonnaie','Geldscheine im Geldautomaten','chill','none'),
(5473,'de','Ein „wohlhabender“ Mann mit leerem Portemonnaie.','Ein „wohlhabender“ Mann mit vollem Portemonnaie.','ein nicht so wohlhabender Mann','die Villa eines wohlhabenden Mannes','ironic','understatement'),
(5474,'de','Er sortiert seine Münzen.','Er sortiert seine Karten.','Münzen aus einem Portemonnaie','Münzen in einem Brunnen','chill','none'),
(5475,'de','Hinter ihnen kommt ein Panzer!','Hinter ihnen kommt ein Pferd!','ein Panzer im Rauch','ein Tank voller Wasser','dramatic','exclamation'),
(5476,'de','Sie läuft über Trümmer.','Sie läuft über Blumen.','durch Trümmer laufen','die Trümmer zusammenfegen','chill','none'),
(5477,'de','Beste Schlacht um die Schneefestung ever.','Beste Schlacht um die Sandfestung ever.','eine Festung aus Schnee','eine Festung aus Stein','slang','exaggeration'),
(5478,'de','Ihr Zeug greift sie an!','Ihre Bücher greifen sie an!','Zeug fällt heraus','Zeug unter dem Bett','dramatic','exaggeration'),
(5479,'de','Ein Gewand und ein „winziger“ Kleiderschrank.','Ein Gewand und eine „winzige“ Küche.','ein langes Satingewand','ein Bademantel im Hotel-Spa','ironic','understatement'),
(5480,'de','Seine Aufgabe ist ein Turm aus Tellern.','Seine Aufgabe ist ein Turm aus Schuhen.','eine schwere Küchenaufgabe','eine Aufgabe am Computer','low_iq','none'),
(5481,'de','Rosa Haare, weißes Shirt. Puh.','Rosa Haare, rosa Shirt. Puh.','lange, knallrosa Haare','eine rosa Waschmaschine','gossip','guessing'),
(5482,'de','Der Hund nimmt ein Bad. Spa-Tag!','Die Katze nimmt ein Bad. Spa-Tag!','ein Hund im Schaumbad','ein Hund im Pool','slang','cliche'),
(5483,'de','Sie sucht den Strand ab. Nach wem wohl?','Sie sucht den Wald ab. Nach wem wohl?','das Ufer absuchen','einen Barcode scannen','gossip','guessing'),
(5484,'de','Sie starren auf das Feuerwerk.','Sie starren aufs Meer.','in den Himmel starren','auf den Bildschirm starren','chill','none'),
(5485,'de','Sie benutzt eine Gießkanne.','Sie benutzt einen Gartenschlauch.','eine grüne Gießkanne','eine leere Gießkanne','chill','none'),
(5486,'de','Er gießt den Blumentopf.','Er bemalt den Blumentopf.','ein Blumentopf auf der Fensterbank','ein zerbrochener Blumentopf','chill','none'),
(5487,'de','Surfen im Inneren einer Welle ist mega!','Tauchen im Inneren einer Welle ist mega!','Surfen auf einer Riesenwelle','Surfen im Internet','slang','exclamation'),
(5488,'de','Dieser Abschied dauert ewig.','Diese Begrüßung dauert ewig.','ein Abschied am Hafen','ein Abschied am Flughafen','dramatic','exaggeration'),
(5489,'de','Sie trägt jeden Mantel so gut.','Sie trägt jeden Anzug so gut.','einen Federhut tragen','einen Strohhut tragen','flirt','none'),
(5490,'de','Er hat ein riesiges Unkraut rausgezogen!','Er hat eine riesige Karotte rausgezogen!','Unkraut ausreißen','Unkraut im Gehweg','dramatic','exaggeration'),
(5491,'de','Er ist hier so willkommen!','Er ist hier so einsam!','ein willkommener Gast','eine willkommene Pause von der Arbeit','dramatic','exclamation'),
(5492,'de','Das Rad hat dünne Speichen.','Das Rad hat keine Speichen.','dünne Metallspeichen','dünne Holzspeichen','chill','none'),
(5493,'de','Er liebt jede Nabe, die er sieht.','Er liebt jedes Auto, das er sieht.','die Nabe eines Rades','das Zentrum einer Stadt','gossip','guessing'),
(5494,'de','Ein Mann mit Behinderung rollt schnell.','Ein Mann mit Behinderung rollt langsam.','ein Mann mit Behinderung im Rollstuhl','ein Mann mit Behinderung auf Krücken','chill','none'),
(5495,'de','Ein Gerücht in der Bibliothek!','Ein Gerücht in der Küche!','ein Gerücht weitererzählen','online ein Gerücht starten','dramatic','exclamation'),
(5496,'de','Sie rückt seine Krawatte zurecht.','Sie rückt seinen Hut zurecht.','einen Krawattenknoten zurechtrücken','eine Uhr stellen','flirt','none'),
(5497,'de','Der Kandidat hat gewonnen!','Der Kandidat hat verloren!','ein siegreicher Kandidat','ein unterlegener Kandidat','dramatic','exclamation'),
(5498,'de','Jedes Fenster, ein neuer Ausblick!','Jede Tür, ein neuer Ausblick!','sich aus dem Fenster lehnen','ein Fenster putzen','slang','exaggeration'),
(5499,'de','Eine Frau in Rot dreht sich.','Eine Frau in Rot joggt.','eine Frau gießt ihre Blumen','eine Frau kauft Blumen','chill','none'),
(5500,'de','Frisches Bauholz liegt auf einem Stapel.','Frisches Bauholz liegt auf einem Lkw.','ein Stapel frisches Bauholz','ein Lkw voll frischem Bauholz','chill','none'),
(5501,'de','Er arbeitet in der Schwerindustrie.','Er arbeitet in einem Blumenladen.','eine Fabrik der Schwerindustrie','die Tourismusindustrie','business','none'),
(5502,'de','Die Kartons kommen zur Lagerung weg.','Die Kartons kommen in den Müll.','Kartons zur Lagerung','Speicherplatz auf dem Handy','business','none'),
(5503,'de','Sie ist in der Plank-Haltung.','Sie ist in der Lotus-Haltung.','eine hohe Plank-Haltung','eine Position in der Firma','chill','none'),
(5504,'de','Sie schickt einen Brief.','Sie schickt ein Paket.','einen handgeschriebenen Brief schicken','eine SMS schicken','chill','none'),
(5505,'de','Sie studiert einen Röntgenfilm.','Sie studiert eine Papierkarte.','ein Röntgenfilm','ein Film im Kino','nerd','none'),
(5506,'de','Wirklich alle sind zu dieser Tanzparty gekommen.','Wirklich niemand ist zu dieser Tanzparty gekommen.','eine Straßen-Tanzparty bei Sonnenuntergang','ein Tanzkurs in der Schule','slang','exaggeration'),
(5507,'de','Er hat Spaß im Zoo.','Er hat Spaß am Strand.','ein Tag im Zoo','ein Tag auf dem Bauernhof','chill','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
