-- Rollback for the r2 listening questions of 23 Sept 2026 (decision 67). NOT RUN.
-- Deletes exactly the 86 rows added in r2; the 188 original rows are not touched.
-- Run BEFORE rollback_eligibility_r2_20260923.sql. The schema change (unique (media_id, question)) is kept;
-- to restore unique (media_id) as well, run after this delete:
--   alter table public.listening_questions drop constraint listening_questions_media_id_question_key;
--   alter table public.listening_questions add constraint listening_questions_media_id_key unique (media_id);
begin;
delete from public.listening_questions q
using (values
  (23, $Q$What did they change, she says?$Q$),
  (23, $Q$How many years does she toast to?$Q$),
  (32, $Q$Which sport does one of them shout?$Q$),
  (41, $Q$How is it here, according to the other one?$Q$),
  (46, $Q$How does she describe the apple?$Q$),
  (52, $Q$What does the photographer call his assistant?$Q$),
  (71, $Q$What does he compare the thick bark to?$Q$),
  (86, $Q$What does she call the bill?$Q$),
  (86, $Q$How much was the meal worth, he says?$Q$),
  (129, $Q$What does he use the calculator for?$Q$),
  (188, $Q$What does the politician say he already is?$Q$),
  (193, $Q$What kind of problem does the official see?$Q$),
  (230, $Q$What's wrong with his acting, according to her?$Q$),
  (230, $Q$How should he move, according to her?$Q$),
  (265, $Q$What's the young worker's name?$Q$),
  (283, $Q$How much fabric does she want?$Q$),
  (285, $Q$What does grandpa tell everyone to do on the porch?$Q$),
  (318, $Q$What does she call her friend at the end?$Q$),
  (331, $Q$What does he call the old lady?$Q$),
  (336, $Q$How many ducks does she guess at first?$Q$),
  (347, $Q$What shouldn't her friend do right now?$Q$),
  (350, $Q$What does Gran call him?$Q$),
  (352, $Q$How long does he need, according to him?$Q$),
  (380, $Q$What does she hope about the train?$Q$),
  (397, $Q$When were the tracks made, according to him?$Q$),
  (423, $Q$What was the best ever, according to her?$Q$),
  (423, $Q$How long is the kiss his, in his words?$Q$),
  (435, $Q$What does she say the leather is?$Q$),
  (452, $Q$What do they call their design?$Q$),
  (465, $Q$What does the vendor call her?$Q$),
  (467, $Q$What should they watch, according to him?$Q$),
  (477, $Q$What do they call the food in the microwave?$Q$),
  (478, $Q$What kind of moustache does she say it is?$Q$),
  (492, $Q$What does she call her hands?$Q$),
  (492, $Q$What does she tell her friend not to do?$Q$),
  (548, $Q$What numbers does she count down?$Q$),
  (548, $Q$What does she tell him to do after counting?$Q$),
  (571, $Q$What won't help, according to them?$Q$),
  (609, $Q$What does she call the view?$Q$),
  (612, $Q$What should he walk past, according to her?$Q$),
  (636, $Q$What does she call the top slice?$Q$),
  (642, $Q$When did she get her scar?$Q$),
  (663, $Q$What does he say the foam is not?$Q$),
  (669, $Q$What does the shopkeeper call her?$Q$),
  (681, $Q$Which verse do they sing next?$Q$),
  (717, $Q$What does the hot soup warm, according to the speaker?$Q$),
  (734, $Q$What does he tell us to listen to?$Q$),
  (769, $Q$Besides tiny, what does she call the spoon?$Q$),
  (787, $Q$What does she say she doesn't do to her friend?$Q$),
  (790, $Q$What is the tomato still, he says?$Q$),
  (794, $Q$Where is the champion, according to the announcer?$Q$),
  (834, $Q$What does a guest call her?$Q$),
  (835, $Q$What does the homeowner call the plumber?$Q$),
  (849, $Q$How long does she ask him to wait?$Q$),
  (891, $Q$What does he call the car when he apologizes?$Q$),
  (4028, $Q$Which way are they going, he says?$Q$),
  (4028, $Q$What's the dog's name?$Q$),
  (4050, $Q$What is home, according to him?$Q$),
  (4050, $Q$What is he living out on the road?$Q$),
  (4058, $Q$What does she go back for?$Q$),
  (4111, $Q$What season is right around the corner?$Q$),
  (4113, $Q$Where does she say the other pigeon belongs?$Q$),
  (4122, $Q$What mistake does the robber say he made?$Q$),
  (4124, $Q$How long has he been on the road?$Q$),
  (4124, $Q$Who is his message for?$Q$),
  (4156, $Q$What does he ask the robot to do?$Q$),
  (4163, $Q$What has he always loved, he says?$Q$),
  (4165, $Q$What does every action get, he says?$Q$),
  (4165, $Q$How does he describe the car?$Q$),
  (4183, $Q$What does he call grandma?$Q$),
  (4183, $Q$What does he say the gift is?$Q$),
  (4212, $Q$How does mocha with ivory look?$Q$),
  (4212, $Q$How does plum with grey look?$Q$),
  (4213, $Q$What's black with gold, according to her?$Q$),
  (4213, $Q$How does black with deep green look?$Q$),
  (4214, $Q$How does chocolate with cream look?$Q$),
  (4214, $Q$How does forest green with camel look?$Q$),
  (4215, $Q$How does powder pink with grey look?$Q$),
  (4216, $Q$What does she call the black, tan and chocolate look?$Q$),
  (4216, $Q$What does she call the red and all-black look?$Q$),
  (4230, $Q$What code does the officer call in?$Q$),
  (4239, $Q$Where does the rider want to be taken?$Q$),
  (4250, $Q$What does the little dog say he's doing at the end?$Q$),
  (4254, $Q$What drink does the pigeon order?$Q$),
  (5044, $Q$What does he tell her to save that for?$Q$),
  (5310, $Q$What does the boy say he did?$Q$)
) as x(media_id, question)
where q.media_id = x.media_id and q.question = x.question;
commit;
