-- A50 backup: the old cards' tables (generated by backup.py)

-- tinder_sentences
create table public.tinder_sentences (
  "id" bigint generated always as identity not null,
  "media_id" bigint not null,
  "language_code" text not null,
  "true_sentence" text not null,
  "false_sentence" text not null,
  "true_phrase" text not null,
  "false_phrase" text not null,
  "tone" text,
  "device" text,
  "created_at" timestamp with time zone default now() not null,
  constraint "tinder_sentences_media_id_fkey" FOREIGN KEY (media_id) REFERENCES media(id) ON DELETE CASCADE,
  constraint "tinder_sentences_pkey" PRIMARY KEY (id),
  constraint "tinder_sentences_media_id_language_code_key" UNIQUE (media_id, language_code)
);
alter table public.tinder_sentences enable row level security;
create policy "Enable read access for all users" on public.tinder_sentences as permissive for select to public using (true);
grant SELECT on public.tinder_sentences to anon;
grant SELECT on public.tinder_sentences to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.tinder_sentences to service_role;

-- tinder_word_distractors
create table public.tinder_word_distractors (
  "media_id" bigint not null,
  "concept_id" bigint not null,
  "group_id" bigint not null,
  "level" text not null,
  "distractor_concept_ids" bigint[] not null,
  "fallback_concept_ids" bigint[] default '{}'::bigint[] not null,
  constraint "tinder_word_distractors_level_check" CHECK ((level = ANY (ARRAY['A'::text, 'B'::text]))),
  constraint "tinder_word_distractors_concept_id_fkey" FOREIGN KEY (concept_id) REFERENCES word_concepts(id) ON DELETE CASCADE,
  constraint "tinder_word_distractors_group_id_fkey" FOREIGN KEY (group_id) REFERENCES media_groups(id) ON DELETE CASCADE,
  constraint "tinder_word_distractors_media_id_fkey" FOREIGN KEY (media_id) REFERENCES media(id) ON DELETE CASCADE,
  constraint "tinder_word_distractors_pkey" PRIMARY KEY (media_id)
);
CREATE INDEX tinder_word_distractors_concept_idx ON public.tinder_word_distractors USING btree (concept_id);
alter table public.tinder_word_distractors enable row level security;
create policy "Tinder word distractors are viewable by everyone" on public.tinder_word_distractors as permissive for select to public using (true);
grant SELECT on public.tinder_word_distractors to anon;
grant SELECT on public.tinder_word_distractors to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.tinder_word_distractors to service_role;

-- media_line_translations
create table public.media_line_translations (
  "id" bigint generated always as identity not null,
  "media_id" bigint not null,
  "kind" text not null,
  "ref" text not null,
  "language_code" text not null,
  "text" text not null,
  "created_at" timestamp with time zone default now() not null,
  constraint "media_line_translations_kind_check" CHECK ((kind = ANY (ARRAY['listening_question'::text, 'speech_line'::text]))),
  constraint "media_line_translations_text_check" CHECK (((char_length(text) >= 1) AND (char_length(text) <= 400))),
  constraint "media_line_translations_media_id_fkey" FOREIGN KEY (media_id) REFERENCES media(id) ON DELETE CASCADE,
  constraint "media_line_translations_pkey" PRIMARY KEY (id),
  constraint "media_line_translations_media_id_kind_ref_language_code_key" UNIQUE (media_id, kind, ref, language_code)
);
CREATE INDEX media_line_translations_lang_idx ON public.media_line_translations USING btree (language_code, kind);
alter table public.media_line_translations enable row level security;
create policy "Enable read access for all users" on public.media_line_translations as permissive for select to public using (true);
grant SELECT on public.media_line_translations to anon;
grant SELECT on public.media_line_translations to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.media_line_translations to service_role;

-- listening_questions
create table public.listening_questions (
  "id" bigint generated always as identity not null,
  "media_id" bigint not null,
  "question" text not null,
  "correct_answer" text not null,
  "accepted_answers" jsonb default '[]'::jsonb not null,
  "created_at" timestamp with time zone default now() not null,
  constraint "listening_questions_accepted_answers_check" CHECK ((jsonb_typeof(accepted_answers) = 'array'::text)),
  constraint "listening_questions_media_id_fkey" FOREIGN KEY (media_id) REFERENCES media(id) ON DELETE CASCADE,
  constraint "listening_questions_pkey" PRIMARY KEY (id),
  constraint "listening_questions_media_id_question_key" UNIQUE (media_id, question)
);
CREATE INDEX listening_questions_media_id_idx ON public.listening_questions USING btree (media_id);
alter table public.listening_questions enable row level security;
create policy "Enable read access for all users" on public.listening_questions as permissive for select to public using (true);
grant SELECT on public.listening_questions to anon;
grant SELECT on public.listening_questions to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.listening_questions to service_role;
