#!/usr/bin/env python3
"""Fills the "2G VERBATIM" block of run_2h.py with source segments copied byte for byte (ast line ranges) from
phase2g/partB/run_2g_cz.py and run_2g_lk.py (read only).  Idempotent.  Asserted: every required name is present,
the lk prompt sha16 is 5fa910459c078539, the result compiles.  0 model calls."""
import ast, os, re, sys, json, hashlib
H = os.path.dirname(os.path.abspath(__file__))
G2 = os.path.join(os.path.dirname(H), "phase2g", "partB")
CZ, LK, RUN = os.path.join(G2, "run_2g_cz.py"), os.path.join(G2, "run_2g_lk.py"), os.path.join(H, "run_2h.py")
BEGIN = "# >>>> 2G VERBATIM (generated by make_2h.py; do not edit by hand) >>>>\n"
END = "# <<<< 2G VERBATIM <<<<\n"
EXCL = {"SEL", "BYN", "BATCHES", "BATCH_IDS", "SELECTED", "MATCHED", "SID_RE", "load_selection", "batches_of", "line", "chunks", "F2_ROWS"}
TAKE = {"toks", "machine_check", "words", "derive_batch", "assemble", "usage_total"}
def names(n):
    if isinstance(n, (ast.FunctionDef, ast.ClassDef)): return {n.name}
    if isinstance(n, ast.Assign): return {t.id for t in n.targets if isinstance(t, ast.Name)}
    return set()
def uses_A(n): return any(isinstance(x, ast.Name) and x.id == "A" for x in ast.walk(n))
out = []
src = open(CZ, encoding="utf-8").read(); L = src.splitlines(keepends=True)
for n in ast.parse(src).body:
    nm = names(n)
    rng = n.lineno >= 185 and n.end_lineno <= 362 and isinstance(n, (ast.Assign, ast.FunctionDef))
    if (rng and nm and not (nm & EXCL) and not uses_A(n)) or (nm & TAKE):
        seg = "".join(L[n.lineno - 1:n.end_lineno])
        if "PROMPT_SHA" in nm: seg = re.sub(r"\bPROMPT_SHA\b", "ANN_PROMPT_SHA", seg)
        out.append("# run_2g_cz.py l.%d-%d\n%s" % (n.lineno, n.end_lineno, seg))
src2 = open(LK, encoding="utf-8").read(); L2 = src2.splitlines(keepends=True)
for n in ast.parse(src2).body:
    if n.lineno >= 80 and n.end_lineno <= 103 and not isinstance(n, (ast.Import, ast.ImportFrom)):
        seg = re.sub(r"\bPROMPT_SHA\b", "LK_PROMPT_SHA", "".join(L2[n.lineno - 1:n.end_lineno]))
        out.append("# run_2g_lk.py l.%d-%d (PROMPT_SHA renamed LK_PROMPT_SHA)\n%s" % (n.lineno, n.end_lineno, seg))
sha = lambda p: hashlib.sha256(open(p, "rb").read()).hexdigest()
blk = BEGIN + "# sources: run_2g_cz.py sha256 %s ; run_2g_lk.py sha256 %s\n" % (sha(CZ), sha(LK)) + "\n".join(out) + END
for need in ("VPROMPT", "REWRITE", "LK_2D", "LK_PROMPT_SHA", "assemble", "derive_batch", "alt_for", "REQ_V", "ANN_PROMPT_SHA", "usage_total", "words"):
    assert re.search(r"^(def )?%s\b" % need, blk, re.M), "missing " + need
t = open(RUN, encoding="utf-8").read()
i, j = t.index(BEGIN), t.index(END) + len(END)
t2 = t[:i] + blk + t[j:]
compile(t2, RUN, "exec")
open(RUN, "w", encoding="utf-8").write(t2)
print(json.dumps({"segments": [s.split("\n", 1)[0] for s in out], "block_chars": len(blk), "run_2h_sha256": sha(RUN)}))
