begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(94,'tr','İlk göz kırpan oğlan oldu. Kız kazandı!','İlk göz kırpan kız oldu. Oğlan kazandı!','ilk göz kırpan olmak','güneşe karşı göz kırpmak','dramatic','exclamation'),
(137,'tr','Kanyon yankıyla cevap veriyor!','Orman yankıyla cevap veriyor!','dar bir kanyon','yukarıdan bir kanyon','dramatic','exaggeration'),
(196,'tr','Karşıya cesareti sayesinde geçti!','Karşıya zipline sayesinde geçti!','cesaretle karşıya geçmek','aşağı atlama cesareti','dramatic','exclamation'),
(220,'tr','Balığın buzunu çözdü.','Tavuğun buzunu çözdü.','buzu çözülmüş balık filetosu','araba camının buzunu çözmek','chill','none'),
(274,'tr','Herkes ayakta!','Herkes yerinde oturuyor!','aynı anda coşan herkes','erkenden giden herkes','dramatic','exclamation'),
(327,'tr','Burada bahçe işleri ekip işi.','Burada yemek yapmak ekip işi.','yükseltilmiş tarhta bahçe işleri','balkonda bahçe işleri','business','none'),
(385,'tr','Topu gökyüzüne doğru yükseğe vurdu!','Topu çimenlere doğru alçaktan vurdu!','topa yükseğe vurmak','topa vurup suya göndermek','dramatic','exaggeration'),
(440,'tr','Halteri havaya kaldırıyor! Ağırlık kaldırma bu!','Kanepeyi havaya kaldırıyor! Ağırlık kaldırma bu!','ağır halter kaldırmak','küçük bir çocuğu kaldırmak','dramatic','exclamation'),
(506,'tr','Tabakları tam sağlıklı beslenme.','Tabakları tamamen şeker.','sağlıklı beslenme tabağı','kutudaki besin değerleri','nerd','exaggeration'),
(584,'tr','Kız, oğlanın haksız olduğunu kanıtladı. Kolay.','Oğlan, kızın haksız olduğunu kanıtladı. Kolay.','oğlanın haksız olduğunu kanıtlamak','kızın haksız olduğunu kanıtlamak','ironic','understatement'),
(621,'tr','Sıra kusursuz şekilde düz.','Sıra kusursuz şekilde yuvarlak.','düz bir sıraya dikmek','ön sırada oturmak','business','none'),
(631,'tr','Salataları çok seri yapıyor.','Pastaları çok seri yapıyor.','taze salata karıştırmak','kutuda salata','business','none'),
(654,'tr','Bir sırrı fısıldayarak söylüyor.','Bir sırrı bağıra bağıra söylüyor.','sır fısıldamak','sır yazmak','chill','none'),
(660,'tr','Kuaförü kim ne yapsın? Leğen yeter.','Kuaförü kim ne yapsın? Kova yeter.','leğende saç yıkamak','leğende bulaşık yıkamak','ironic','cheap_quality'),
(718,'tr','Kazlar güneye uçuyor.','Kazlar güneye yürüyor.','kuşların peşinden güneye gitmek','güneye araba sürmek','chill','none'),
(787,'tr','Arkadaşını yargılamıyor.','Köpeğini yargılamıyor.','arkadaşını yargılamamak','yemek yarışmasında jüri olmak','chill','none'),
(840,'tr','Sırf bir selfie için doğa yürüyüşü yaptı.','Sırf bir selfie için açığa yüzdü.','göle kadar doğa yürüyüşü yapmak','plaja inen doğa yürüyüşü','ironic','guessing'),
(912,'tr','Mimarın elinde bir plan var.','Mimarın elinde bir çekiç var.','elinde planlarla bir mimar','plajda bir mimar','business','none'),
(913,'tr','Kolu havada.','Kolu aşağıda.','yukarı uzanmış bir kol','kol askısında bir kol','chill','none'),
(981,'tr','Yeşil araba, deniz manzarası, tam stil.','Yeşil araba, şehir manzarası, tam stil.','yeşil klasik bir araba','yeşil bir aile arabası','flirt','exaggeration'),
(1119,'tr','Rehber turu yönetiyor.','Rehber yarışta en önde.','şemsiyeli bir rehber','tırmanan bir dağ rehberi','business','none'),
(1127,'tr','Sağlık ve mutluluk dolu!','Yağmur ve karanlık dolu!','sağlık ve neşe dolu','bir sağlık kontrolü','dramatic','cliche'),
(1149,'tr','Uykusuzluk: o ve tavan, karşı karşıya.','Uykusuzluk: o ve buzdolabı, karşı karşıya.','gece uykusuzluğu','sınav öncesi uykusuzluk','ironic','exaggeration'),
(1161,'tr','Dizine buz koyuyor.','Başına buz koyuyor.','bükük dizde buz','tek diz üstünde','business','none'),
(1230,'tr','Yolcu mışıl mışıl uyuyor.','Yolcu tamamen uyanık.','uyuyan bir tren yolcusu','takside bir yolcu','chill','none'),
(1262,'tr','Portekiz tartlarına tarçın!','Portekiz tartlarına çikolata!','muhallebili Portekiz tartları','Portekiz sardalyaları','dramatic','exclamation'),
(1275,'tr','Kızarıklığını kaşıyor.','Başını kaşıyor.','kaşıntılı kızarıklığı kaşımak','yüzünde kızarıklık','chill','none'),
(1323,'tr','Ne kadar yüksek bir gökdelen!','Ne kadar yüksek bir deniz feneri!','gökdelene aşağıdan bakmak','gökdelenden aşağı bakmak','dramatic','exclamation'),
(1413,'tr','Koşu bandı: koşuyorsun ama hiçbir yere varamıyorsun.','Koşu bandı: yürüyorsun ama hiçbir yere varamıyorsun.','koşu bandında koşmak','bozuk koşu bandını tamir etmek','ironic','cliche'),
(1436,'tr','İnsanlar çeşitli yaşlarda.','İnsanların hepsi ergen.','çeşitli yaşlardan beş portre','çeşitli yerlerden beş manzara','chill','none'),
(1497,'tr','Keman eski notaların üstünde duruyor.','Gitar eski notaların üstünde duruyor.','güllerin yanında bir keman','bir keman dersi','chill','none'),
(1569,'tr','Bu, çapraz taramalı bir portre.','Bu, suluboya bir portre.','mürekkeple çizilmiş bir portre','yağlı boya bir portre','nerd','none'),
(1696,'tr','Kartal iki yavrusuyla ilgileniyor.','Kartal dört yavrusuyla ilgileniyor.','yuvasının üstünde bir kartal','balık yakalayan bir kartal','business','exaggeration'),
(1751,'tr','Her tabelada bir manzara var.','Her tabelada bir şehir var.','manzaralı ok tabelaları','fiyatlı ok tabelaları','chill','none'),
(2114,'tr','Derenin üstünden geçen bir köprü.','Yolun üstünden geçen bir köprü.','derenin üstünde bir köprü','sokağın karşısında bir ev','chill','none'),
(2174,'tr','Karda bir ağaç çiçek açıyor!','Karda bir ağaç yanıyor!','gece çiçek açan bir ağaç','baharda açan çiçekler','dramatic','exclamation'),
(2242,'tr','Sürüde boş koltuk: sıfır.','Sürüde boş koltuk: bol.','küçük bir kuş sürüsü','bir koyun sürüsü','business','exaggeration'),
(2365,'tr','Metal kıyafeti pırıl pırıl.','Metal kıyafeti çok kirli.','kırmızı metal bir kıyafet','kırmızı metal bir araba','slang','none'),
(2375,'tr','Yarısı gri, yarısı sarı. Karar veremiyor.','Yarısı gri, yarısı yeşil. Karar veremiyor.','yarım sarı bir araba','yarım sarı bir otobüs','low_iq','guessing'),
(2550,'tr','Yalınayak, bağdaş kurarak oturuyor.','Botlarıyla bağdaş kurarak oturuyor.','bağdaş kurarak oturmak','bağdaş kurarak uzanmak','chill','none'),
(2625,'tr','Mühendis vinçlerin hayalini kuruyor.','Mühendis atların hayalini kuruyor.','bir mühendisin bareti','bilgisayar başında bir mühendis','nerd','guessing'),
(2708,'tr','Maymun tanrı güçlü görünüyor.','Maymun tanrı minicik görünüyor.','güçlü kollar ve göğüs','sert bir fincan kahve','chill','none'),
(2766,'tr','Omzunun dibinde bir kobra var!','Omzunun dibinde bir kaplan var!','başını kaldırmış bir kobra','sepette bir kobra','dramatic','exclamation'),
(2774,'tr','Mimarisi gotik.','Mimarisi modern.','gotik katedral mimarisi','modern cam mimarisi','nerd','none'),
(2914,'tr','Biri yukarı doğru geriniyor.','Biri yukarı doğru zıplıyor.','kollarını yukarı uzatarak gerinmek','koşudan önce esneme yapmak','chill','none'),
(3424,'tr','Orkestra şefinin elinde baton var.','Orkestra şefinin elinde flüt var.','fraklı bir orkestra şefi','trende bir kondüktör','business','none'),
(3494,'tr','Kadın güneşe doğru geriniyor.','Adam güneşe doğru geriniyor.','iki kolunu yukarı uzatıp gerinmek','lastik bant germek','chill','none'),
(4085,'tr','Kadın adamı tamamen değiştirdi.','Adam kadını tamamen değiştirdi.','üstünü değiştirip takım elbise giymek','araba lastiği değiştirmek','gossip','exaggeration'),
(4142,'tr','Üstüne yağmur yağıyor. Ne eğlenceli!','Üstüne kar yağıyor. Ne eğlenceli!','yağmur yağarken dönmek','yağmur yağarken saklanmak','slang','exclamation'),
(4180,'tr','Timsahı köpekle karıştırdı: gözlüğü yok.','Yılanı köpekle karıştırdı: gözlüğü yok.','timsahı köpekle karıştırmak','yavru köpeği kediyle karıştırmak','gossip','bad_excuse'),
(4242,'tr','Kapı mı? Kedi yine de geçiyor.','Kapı mı? Köpek yine de geçiyor.','bir kapıdan geçmek','pas vermek','slang','understatement'),
(4319,'tr','Çizgiler birbirine karışıyor.','Çizgiler giderek genişliyor.','kremi cilde yedirmek','meyveyi blenderda karıştırmak','chill','none'),
(4331,'tr','Çok düzenli bir yürüyüş.','Çok dağınık bir yürüyüş.','caddede bir yürüyüş','ormanda bir yürüyüş','business','none'),
(4349,'tr','Bu bekçi sörfte resmen döktürüyor.','Bu bekçi kayakta resmen döktürüyor.','sörf tahtasında bir bekçi','at üstünde bir bekçi','flirt','none'),
(4356,'tr','Bel ağrıyor mu? Yine de sırtında taşıyor!','Boyun ağrıyor mu? Yine de sırtında taşıyor!','ağrıyan sırtı ovmak','yatakta ağrıyan boğaz','slang','exclamation'),
(4369,'tr','Bant fazla mı oldu? Belki biraz.','Yapıştırıcı fazla mı oldu? Belki biraz.','beyaz banta sarılmış','karton kutuda bant','ironic','understatement'),
(4384,'tr','Yatağında zıpladı!','Kanepede zıpladı!','yatakta zıplamak','top sektirmek','dramatic','exclamation'),
(4425,'tr','Robot onlara durmadan emrediyor.','Robot büyük bir pizza sipariş ediyor.','takıma emirler yağdırmak','kahve sipariş etmek','dramatic','none'),
(4443,'tr','Düğün başlıyor ve herkes arkasını dönüyor.','Düğün bitiyor ve herkes arkasını dönüyor.','nikâh masasına yürümek','düğünde dans etmek','chill','none'),
(4477,'tr','Takvimde yeni aya geçiyor.','Kitapta yeni bölüme geçiyor.','takvimde yeni aya geçmek','sahilde bir ay','chill','none'),
(4512,'tr','Listesini kontrol ediyor.','Telefonunu kontrol ediyor.','listedekileri tek tek işaretlemek','alışveriş listesi yazmak','chill','none'),
(4520,'tr','Sur sonsuza kadar uzanıyor.','Nehir sonsuza kadar uzanıyor.','dağlar boyunca uzanmak','koşudan önce esnemek','dramatic','exaggeration'),
(4521,'tr','Kuleler uzakta kayboluyor.','Evler uzakta kayboluyor.','uzaktaki kuleler','şehirlerarası telefon görüşmesi','chill','none'),
(4530,'tr','Film sırasında patlamış mısırlar uçuşuyor!','Film sırasında içecekler uçuşuyor!','film izlemek','film çekmek','dramatic','exaggeration'),
(4567,'tr','Biraz hasta görünüyor.','Çok mutlu görünüyor.','hasta ve öksüren','yatakta hasta','chill','understatement'),
(4572,'tr','Kız onları sonsuza dek düzeltecek.','Adam onları sonsuza dek düzeltecek.','sınav kâğıtlarındaki hataları düzeltmek','duruşunu düzeltmek','dramatic','exaggeration'),
(4584,'tr','Kaplumbağa bir iz bıraktı.','Yengeç bir iz bıraktı.','yüzgeç izlerinden oluşan bir iz','bir yürüyüş parkuru','chill','none'),
(4600,'tr','Döviz bozduruyor.','Şapkasını başka bir şapkayla takas ediyor.','döviz bozdurmak','hediye takas etmek','business','none'),
(4637,'tr','Evi yıkıyorlar, o da videoya çekiyor.','Arabayı parçalıyorlar, o da videoya çekiyor.','eski bir evi yıkmak','eski bir arabayı parçalamak','gossip','none'),
(4831,'tr','Ne büyük bir vuruş!','Ne büyük bir ıska!','sabit topa vuruş','radyoda bir hit','dramatic','exclamation'),
(4844,'tr','Balkabağını ikiye böldü.','Pastayı ikiye böldü.','yarım bir balkabağı','yarım bir balkabağı turtası','chill','none'),
(4873,'tr','Kendini ders çalışmaya kaptırmış.','Ormanda yolunu kaybetmiş.','ders çalışmaya gömülmüş','tıbbi bir araştırma','chill','none'),
(4894,'tr','Herkes kıpırtısız. Gayet normal.','Herkes dans ediyor. Gayet normal.','salonda kıpırdamayan öğrenciler','gölde durgun su','ironic','understatement'),
(4923,'tr','İki misafiri masaya oturtuyor.','Dört misafiri masaya oturtuyor.','genç bir çifti masaya oturtmak','bara geçip oturmak','chill','none'),
(4950,'tr','Eller kalçada. Çok ciddi.','Eller başın üstünde. Çok ciddi.','eller kalçada','kalça sallamak','ironic','understatement'),
(4999,'tr','Bir kılıç ustasıyla dövüşüyor.','Bir okçuyla dövüşüyor.','bir kılıç ustasıyla dövüşmek','soğuk algınlığıyla savaşmak','chill','none'),
(5034,'tr','Onun evinde her şey dökülüyor!','Onun evinde her şey yanıyor!','masaya dökülen süt','dizüstü bilgisayara kahve dökmek','ironic','exaggeration'),
(5093,'tr','Bahçe birazcık otlarla kaplıydı.','Havuz birazcık otlarla kaplıydı.','uzamış çimleri biçmek','uzamış bir çit','ironic','understatement'),
(5143,'tr','Askerler barış yapıyor.','Askerler savaşıyor.','barış yapmak','evde huzur ve sükûn','chill','none'),
(5193,'tr','Kızarıklığa krem mi? Yakıyor!','Yanığa krem mi? Yakıyor!','kaşıntılı kızarıklığa krem','yanağında bir kızarıklık','gossip','exclamation'),
(5234,'tr','Her sıra kusursuz hizada.','Her sıra tam bir kaos.','selam veren kadın sıraları','koşan erkek sıraları','business','none'),
(5294,'tr','Ayakları terliklere bayılıyor.','Ayakları çoraplara bayılıyor.','tüylü koyun terlikleri','yatağın altında terlikler','chill','exaggeration'),
(5320,'tr','Bir omurgayı gösteriyor.','Bir kalbi gösteriyor.','omurga maketi üzerinde göstermek','sokakta gösteri yapmak','business','none'),
(5347,'tr','Trafik durma noktasına geliyor.','Trenler durma noktasına geliyor.','trafikte bir duruş','kahve için bir mola','chill','none'),
(5368,'tr','Sıcaktan acı çekiyorlar.','Soğuktan acı çekiyorlar.','sıcakta acı çekmek','soğuk algınlığıyla boğuşmak','dramatic','none'),
(5379,'tr','Terzi ceket üzerinde değişiklik yaptı.','Terzi gömlek üzerinde değişiklik yaptı.','lacivert bir cekette değişiklik yapmak','seyahat planlarını değiştirmek','chill','none'),
(5394,'tr','Biri çoktan sahiplenmiş!','Henüz kimse sahiplenmemiş!','donmuş toprakları sahiplenmek','kayıp bir çantayı sahiplenmek','gossip','exclamation'),
(5401,'tr','Herkes merak ediyor.','Herkes uyuyor.','bir sorunun çözümünü merak etmek','havanın nasıl olacağını merak etmek','chill','none'),
(5413,'tr','Her yer araba. Umutsuz vaka!','Her yer bisiklet. Umutsuz vaka!','umutsuz bir trafik sıkışıklığı','umutsuz bir futbol takımı','low_iq','exclamation'),
(5423,'tr','Sırt çantası dünya çapında bir gezgin.','Sırt çantası tek bir şehirde kalıyor.','dünya çapında geziler','dünya çapında bir telefon ağı','chill','none'),
(5449,'tr','Sonunda kapı eşiğinde.','Sonunda bahçede.','açık bir taş kapı girişi','perdeli bir kapı girişi','chill','none'),
(5502,'tr','Kutular depolama için kaldırılıyor.','Kutular çöpe atılıyor.','depolama kutuları','telefonda depolama alanı','business','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
