begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(329,'tr','Gaz alevi mavi.','Gaz alevi yeşil.','mavi bir gaz alevi','arabada gaz','business','none'),
(330,'tr','Kapıya tam vaktinde!','Kapı için çok geç!','biniş kapısına koşmak','bahçede bir kapı','dramatic','exclamation'),
(331,'tr','Bir centilmen portakalları kurtarıyor!','Bir centilmen elmaları kurtarıyor!','şemsiyeli bir centilmen','köpekli bir centilmen','dramatic','exclamation'),
(332,'tr','Zürafa öğle yemeği yiyor.','Aslan öğle yemeği yiyor.','yaprak yiyen bir zürafa','çimen yiyen bir zürafa','business','none'),
(333,'tr','Bu kız her şeyi yapabilir!','Bu oğlan her şeyi yapabilir!','ip atlayan bir kız','okulu asan bir kız','dramatic','exaggeration'),
(334,'tr','Bardağı buz gibi.','Bardağı sıcak.','bir bardak limonata','bir bardak şarap','chill','none'),
(336,'tr','Gözlük takıldı, ördekler çoğaldı!','Gözlük takıldı, kazlar çoğaldı!','yuvarlak gözlük silmek','yuvarlak gözlük kırmak','low_iq','exclamation'),
(338,'tr','Küresine sarılıyor!','Lambasına sarılıyor!','masa küresini çevirmek','küre çizmek','dramatic','exclamation'),
(339,'tr','Sokaktan aşağı gidiyor.','Merdivenlerden yukarı gidiyor.','sokaktan aşağı gitmek','eve geri gitmek','chill','none'),
(340,'tr','Kendi kalelerini getirmişler!','Kendi banklarını getirmişler!','meydanda bir kale','tarihi bir kale','dramatic','exclamation'),
(341,'tr','Keçi çamaşırları yiyor!','Keçi çiçekleri yiyor!','çatıda bir keçi','arabada bir keçi','dramatic','exclamation'),
(342,'tr','Koruyucu gözlükler takıldı, sımsıkı!','Kask takıldı, sımsıkı!','mavi yüzücü gözlüğü','karda kayak gözlüğü','slang','exclamation'),
(343,'tr','Yüzüğü kaptı!','Madeni parayı kaptı!','su altında yüzük kapmak','havuz merdivenini kapmak','dramatic','exclamation'),
(344,'tr','Altını biraz fazla seviyor.','Kedileri biraz fazla seviyor.','ağır bir altın külçe','bir altın madalya','gossip','understatement'),
(346,'tr','Golf topu delikte. Evet!','Golf topu suda. Evet!','gün batımında golf vuruşu','suda bir golf topu','dramatic','exclamation'),
(347,'tr','Biraz dedikoduya bayılırlar.','Biraz futbola bayılırlar.','kulağa dedikodu fısıldamak','dergide dedikodu','gossip','understatement'),
(348,'tr','Hükümet evet oyu verdi.','Hükümet hayır oyu verdi.','bir hükümet oylaması','bir öğrenci meclisi','business','none'),
(349,'tr','Balık, satranç, bir de sarılma: efsane büyükbaba.','Balık, satranç, bir de sarılma: efsane büyükanne.','büyükbaba ve torunu','büyükbaba ve köpeği','slang','cliche'),
(350,'tr','Torunu eve geldi!','Kocası eve geldi!','torununa sarılmak','kocasına sarılmak','dramatic','exclamation'),
(351,'tr','Çimlerde takılıyorlar.','Kumda takılıyorlar.','yumuşak çimlerde uzanmak','yumuşak çimleri biçmek','slang','none'),
(352,'tr','Peynirde ızgara izleri var.','Ekmekte ızgara izleri var.','sıcak ızgarada peynir','sıcak ızgarada balık','chill','none'),
(353,'tr','Misafir hediyeyle geldi.','Misafir köpekle geldi.','misafiri karşılamak','misafir odası','chill','none'),
(354,'tr','Gezi rehberi haklı çıktı!','Harita haklı çıktı!','kalın bir gezi rehberi','kalın bir telefon rehberi','gossip','exclamation'),
(355,'tr','Yemek yiyemiyor. Suçluluk!','Uyuyamıyor. Suçluluk!','kırık sürahi yüzünden suçluluk','kırık telefon yüzünden suçluluk','dramatic','exclamation'),
(356,'tr','Artık bu spor salonunda yaşayacak.','Artık bu barda yaşayacak.','aydınlık yeni bir spor salonu','okulda beden dersi','low_iq','guessing'),
(357,'tr','Saç fırçası artık mikrofon!','Tarak artık mikrofon!','tahta bir saç fırçası','at için saç fırçası','slang','exclamation'),
(358,'tr','O çekiçle ne özenli iş.','O kaşıkla ne özenli iş.','çivinin üstünde çekiç','alet çantasında çekiç','flirt','none'),
(359,'tr','Yanaklar dolu, hamster mutlu.','Yanaklar boş, hamster mutlu.','çarkta bir hamster','topun içinde hamster','slang','none'),
(360,'tr','Önce el dezenfektanı, sonra samosa.','Önce el kremi, sonra samosa.','bir pompa el dezenfektanı','kapıda el dezenfektanı','business','none'),
(361,'tr','Çiçek yok mu? Lolipop sar gitsin.','Çiçek yok mu? Bisküvi sar gitsin.','lolipopları kâğıda sarmak','bisküvileri kâğıda sarmak','ironic','cheap_quality'),
(362,'tr','O kadar mutlu ki inanılmaz.','O kadar üzgün ki inanılmaz.','sahilde mutlu bir yürüyüş','mutlu bir doğum günü partisi','slang','exaggeration'),
(363,'tr','Bütün gece araştırma yapıyor.','Bütün sabah araştırma yapıyor.','gece araştırma yapmak','dışarıda araştırma yapmak','chill','exaggeration'),
(364,'tr','Sanatçı olmadığını söylüyor.','Ünlü bir sanatçı olduğunu söylüyor.','sanatçı değil','bir sanatçının büyük atölyesi','chill','none'),
(365,'tr','Kulaklığı çok yüksek sesli!','Hoparlörleri çok yüksek sesli!','kulaklığı paylaşmak','kulaklığı tamir etmek','slang','guessing'),
(366,'tr','Kolu iyileşti. Yaşasın!','Bacağı iyileşti. Yaşasın!','iyileşmiş bir kol','iyileşmiş bir bacak','dramatic','exclamation'),
(367,'tr','Bu sıcak meyveli buza fazla!','Bu yağmur meyveli buza fazla!','köyde bunaltıcı sıcak','ateşin sıcağı','dramatic','exaggeration'),
(368,'tr','Helikopterle teslimat mı? Süper!','Dronla teslimat mı? Süper!','kırmızı helikopterle teslimat','gemide bir helikopter','slang','exclamation'),
(369,'tr','Motosiklet sürüyor.','Ata biniyor.','spor motosiklet sürmek','arabayla gitmek','chill','none'),
(370,'tr','Kırmızı kask işini yaptı.','Mavi kask işini yaptı.','kırmızı bir kaykay kaskı','motosiklette bir kask','chill','understatement'),
(371,'tr','Makarna için taze otlar, nefis.','Pizza için taze otlar, nefis.','pencere önünden taze otlar','fincanda bitki çayı','slang','none'),
(372,'tr','Çatıda numaralar yapıyor.','Plajda numaralar yapıyor.','topla numaralar yapmak','kartlarla numaralar yapmak','chill','none'),
(373,'tr','Kırmızılı taraftarlarla dolu bir stadyum.','Mavili taraftarlarla dolu bir stadyum.','tıklım tıklım futbol stadyumu','gece boş bir stadyum','chill','none'),
(374,'tr','Şafakta koşu yapıyor.','Şafakta bisiklet sürüyor.','boş yolda koşu yapmak','köpekle koşu yapmak','chill','none'),
(375,'tr','Yarış arabasında çok havalı duruyor.','Takside çok havalı duruyor.','gün doğumunda yarış arabası','gece yarış arabası','flirt','none'),
(376,'tr','Saf vahşi doğa, insan yok.','Saf çöl, insan yok.','vahşi doğada bir nehir','vahşi doğadan geçen yol','chill','none'),
(377,'tr','Stüdyoda sahne alıyor.','Kilisede sahne alıyor.','klipteki gibi sahne almak','dev bir stadyumda sahne almak','chill','none'),
(378,'tr','Gün doğumu resmen altın gibi.','Gün doğumu resmen gri.','gün doğumuna doğru uçmak','gün doğmadan uyanmak','slang','none'),
(379,'tr','Video günlüğü çekiyor.','Düğün çekiyor.','sabah video günlüğü çekmek','gezi video günlüğü kurgulamak','chill','none'),
(380,'tr','Yolculuğu bir çatıda bitti.','Yolculuğu bir teknede bitti.','uzun bir şehir yolculuğu','uçakla yolculuk','chill','none'),
(381,'tr','Bir tane üzüm bile onu korkutuyor.','Bir tane elma bile onu korkutuyor.','arkadaşı korkutmak','kuşları korkutup kaçırmak','low_iq','guessing'),
(382,'tr','Vay, çok yüksekte çalışıyorlar!','Vay, çok alçakta çalışıyorlar!','sokağın üstünde, yüksekte','dağda, yüksekte','dramatic','exclamation'),
(383,'tr','Zirveye kadar doğa yürüyüşü!','Zirveye kadar kayak!','dağda doğa yürüyüşü','çölde doğa yürüyüşü','dramatic','exclamation'),
(386,'tr','Hobisi maket yapmak.','Hobisi ev yapmak.','maket gemilerle bir hobi','gerçek gemilerle bir hobi','chill','none'),
(387,'tr','Güvenlik kamerası: köpek yapmış.','Güvenlik kamerası: kedi yapmış.','gece güvenlik kamerası görüntüsü','mağaza güvenlik kamerası','gossip','blaming_someone'),
(388,'tr','Ödevi hiç bitmiyor.','Tatili hiç bitmiyor.','gece geç saatte ödev','otobüste ödev','dramatic','exaggeration'),
(389,'tr','Bal amma yavaş akıyor!','Bal amma hızlı akıyor!','tahta bal kaşığında bal','çayda bal','slang','exclamation'),
(390,'tr','Kapüşonlu sweatshirt''ü aşırı rahat.','Montu aşırı rahat.','kapüşonlu sweatshirt giymek','kapüşonlu sweatshirt yıkamak','slang','exaggeration'),
(391,'tr','Tekne döndü. Umut kazandı!','Uçak döndü. Umut kazandı!','tekne için umut','güzel hava için umut','dramatic','exclamation'),
(392,'tr','Ata biniyor.','Deveye biniyor.','at ve binicisi','at ve arabası','chill','none'),
(393,'tr','Hostelde bir yatak on euro.','Hostelde bir yatak altı euro.','hostelde bir ranza','otelde bir oda','business','none'),
(394,'tr','Çok sıcak! Vantilatöre sarılıyor.','Çok sıcak! Köpeğe sarılıyor.','sıcak, güneşli bir gün','bir fincan sıcak çay','dramatic','exclamation'),
(395,'tr','Dünyanın en iyi evi!','Dünyanın en iyi arabası!','sarı bir eve taşınmak','beyaz bir eve taşınmak','slang','exaggeration'),
(396,'tr','Yılın sarılması bu!','Yılın kavgası bu!','dönerek kocaman sarılma','hızlı bir veda sarılması','dramatic','exaggeration'),
(397,'tr','Ormanda avcılık yapıyorlar.','Çölde avcılık yapıyorlar.','sonbahar ormanında avcılık','karda avcılık','chill','none'),
(398,'tr','Önce hijyen, sonra başparmak havaya.','Önce hijyen, sonra çak bir beşlik.','banyoda iyi hijyen','mutfakta iyi hijyen','chill','none'),
(399,'tr','Dondurmasına yenik düşüyor.','Sosisli sandviçine yenik düşüyor.','eriyen dondurma','bardakta dondurma','low_iq','exaggeration'),
(400,'tr','9 numara buz hokeyi oynuyor.','7 numara buz hokeyi oynuyor.','pistte buz hokeyi','gölette buz hokeyi','chill','none'),
(401,'tr','O patenlerle ne güzel fren!','O snowboardla ne güzel fren!','paten bağcıklarını bağlamak','rafta paten','flirt','none'),
(402,'tr','Buzda kayıyor.','Çimde kayıyor.','buzun içinde kabarcıklar','içecekte buz','chill','none'),
(404,'tr','Derslik kaos, ama o sakin.','Mutfak kaos, ama o sakin.','gürültülü bir derslik','sessiz bir derslik','gossip','understatement'),
(405,'tr','Dışarıda kar, içeride arkadaşlar.','Dışarıda kar, içeride köpekler.','kulübenin içinde sıcacık','çadırın içinde','chill','none'),
(406,'tr','Kızgın demiri dövüyor.','Kızgın camı dövüyor.','kızgın demir dövmek','sıcak gömlek ütülemek','chill','none'),
(407,'tr','Olamaz! Koca bir ada iki kişiye!','Olamaz! Koca bir ada on kişiye!','küçük tropik bir ada','mutfakta bir ada','dramatic','exaggeration'),
(408,'tr','Ceket giyildi. Çok daha iyi.','Atkı takıldı. Çok daha iyi.','kahverengi ceketin fermuarını çekmek','sandalyede bir ceket','chill','none'),
(410,'tr','Reçeli kalın kalın sürüyor.','Reçeli ince ince sürüyor.','kızarmış ekmeğe reçel','kızarmış ekmeğe fıstık ezmesi','chill','none'),
(411,'tr','Vay, kız çok kıskanç.','Vay, oğlan çok kıskanç.','diğer dansçıyı kıskanmak','öğretmenini kıskanmak','gossip','exaggeration'),
(412,'tr','7 numaralı forma onun!','9 numaralı forma onun!','yeni 7 numaralı forma','yeni 10 numaralı forma','dramatic','exclamation'),
(413,'tr','Meyve suyu yakut kırmızısı.','Meyve suyu parlak turuncu.','taze nar suyu','kutuda portakal suyu','chill','none'),
(414,'tr','Çıtanın üstünden atladı!','Çitin üstünden atladı!','çıtanın üstünden atlamak','havuza atlamak','dramatic','exclamation'),
(415,'tr','Bu kangurunun bir yolcusu var.','Bu koalanın bir yolcusu var.','yavrusuyla bir kanguru','boks eldivenli bir kanguru','chill','exaggeration'),
(416,'tr','Ketçap sonunda pes etti!','Hardal sonunda pes etti!','patates kızartmasına ketçap','hamburgere ketçap','dramatic','exaggeration'),
(418,'tr','Kendi anahtarlığını yaptı.','Kendi kolyesini yaptı.','ponponlu bir anahtarlık','fotoğraflı bir anahtarlık','chill','none'),
(419,'tr','Topa şut atıyorlar.','Topu fırlatıyorlar.','topa şut atmak','kapıyı tekmeyle açmak','chill','none'),
(422,'tr','Tekme atması acayip yüksek.','Tekme atması acayip alçak.','kum torbasına tekme atma','futbol topuna tekme atma','slang','none'),
(423,'tr','Oğlan, kızın öpücüğünü yakaladı!','Kız, oğlanın öpücüğünü yakaladı!','öpücük göndermek','iyi geceler öpücüğü','flirt','exclamation'),
(424,'tr','Bıçağı ekmek kesiyor.','Bıçağı peynir kesiyor.','büyük bir ekmek bıçağı','küçük bir çakı','business','none'),
(426,'tr','Kız tırmanıyor, oğlan sadece merdiveni tutuyor.','Kız tırmanıyor, oğlan sadece sepeti tutuyor.','merdiveni sabit tutmak','merdiveni boyamak','gossip','banter'),
(427,'tr','Uğur böceği uçup gidiyor.','Uğur böceği yaprak yiyor.','çimenlerde bir uğur böceği','elde bir uğur böceği','chill','none'),
(428,'tr','Sakin bir gölde kano.','Sakin bir denizde kano.','sakin bir dağ gölü','donmuş bir göl','chill','none'),
(429,'tr','Kusursuz indi!','Suya indi!','çimenli bir alana inmek','uçağı indirmek','dramatic','exclamation'),
(430,'tr','Oğlan kıza kendi dilini öğretiyor.','Kız oğlana kendi dilini öğretiyor.','yeni bir dil öğrenmek','dil uygulamasında ders','chill','none'),
(431,'tr','Tembel mi? Hayır, adam bir "dâhi".','Tembel mi? Hayır, kadın bir "dâhi".','evde tembel bir adam','evde tembel bir kedi','ironic','bad_excuse'),
(432,'tr','Fenerle yol gösteriyor.','Meşaleyle yol gösteriyor.','yürüyüşçülere fenerle yol göstermek','yürüyüşçülere haritayla yol göstermek','chill','none'),
(435,'tr','Deri gıcırdıyor!','Döşeme gıcırdıyor!','deri germek','deri bir kanepe','dramatic','exclamation'),
(436,'tr','Herkes sola adım atıyor.','Herkes sağa adım atıyor.','sola adım atmak','sola zıplamak','chill','none'),
(437,'tr','Bacağını esnetiyor.','Kolunu esnetiyor.','duvarda bir bacak','alçıda bir bacak','chill','none'),
(438,'tr','Limon aşırı ekşi!','Limon aşırı tatlı!','limon dilimi ısırmak','limonlu kek','slang','exclamation'),
(439,'tr','Limonata acayip soğuk.','Limonata acayip sıcak.','bir kavanoz limonata','bir kutu limonata','slang','none'),
(442,'tr','Takım çalışması ağır kutuyu yener.','Takım çalışması ağır kanepeyi yener.','ağır kutuyla takım çalışması','futbol sahasında takım çalışması','business','cliche'),
(443,'tr','Sonunda çatı katında ışık!','Sonunda mutfakta ışık!','pencereden gelen ışık','mumdan gelen ışık','dramatic','exclamation'),
(444,'tr','Şimşek! Gördün mü onu?','Gökkuşağı! Gördün mü onu?','gece şimşek izlemek','gündüz şimşek','slang','exclamation'),
(445,'tr','Beyaz çizgisi kusursuz!','Sarı çizgisi kusursuz!','beyaz çizgi boyamak','uzun bir insan kuyruğu','dramatic','exclamation'),
(446,'tr','Aslan bize kükrüyor!','Aslan bize koşuyor!','çimenlerde bir aslan','kafeste bir aslan','dramatic','exclamation'),
(447,'tr','Dudak balsamı günü kurtarıyor!','El kremi günü kurtarıyor!','dudak balsamı sürmek','dudak balsamı almak','dramatic','cliche'),
(448,'tr','Cam gibi parlak dudak parlatıcısı.','Kâğıt gibi mat dudak parlatıcısı.','parlak pembe dudak parlatıcısı','koyu kırmızı dudak parlatıcısı','flirt','exaggeration'),
(449,'tr','Şşş, dinliyorlar!','Şşş, uyuyorlar!','ormanda sesleri dinlemek','müzik dinlemek','dramatic','exclamation'),
(450,'tr','Kertenkele güneşleniyor.','Kertenkele yüzüyor.','duvarda bir kertenkele','kutuda bir kertenkele','chill','none'),
(451,'tr','Kapıyı kilitliyor.','Kapıyı açıyor.','tekne kapısını kilitlemek','araba kapısını kilitlemek','chill','none'),
(452,'tr','Logoyu köpeğe bile basmışlar!','Logoyu kediye bile basmışlar!','tasmada bir logo','tişörtte bir logo','gossip','exclamation'),
(453,'tr','Kantinde yalnız hissediyor.','Kütüphanede yalnız hissediyor.','yalnız bir öğle yemeği','eve yalnız yürümek','dramatic','none'),
(454,'tr','Çorba ve battaniye: saf sevgi.','Çay ve battaniye: saf sevgi.','yağmurlu gecede sevgi','ilk görüşte aşk','flirt','exaggeration'),
(455,'tr','Kızın akciğerleri süper güçlü.','Oğlanın akciğerleri süper güçlü.','hava dolu akciğerler','duman dolu akciğerler','chill','exaggeration'),
(456,'tr','Dergi artık onun.','Gazete artık onun.','dergi karıştırmak','trende bir dergi','gossip','guessing'),
(457,'tr','Bir uzman makyajını yapıyor.','Bir uzman saçını yapıyor.','aynada makyaj yapmak','aynada makyaj silmek','chill','none'),
(458,'tr','İri bir adam kasa taşıyor.','İri bir adam köpek taşıyor.','satranç oynayan adamlar','kâğıt oynayan adamlar','chill','none'),
(459,'tr','Yönetici talimat veriyor.','Yönetici çiçek veriyor.','klipbordlu bir yönetici','futbol takımı yöneticisi','business','none'),
(461,'tr','Mankeni taklit ediyor. İkiz!','Mankeni boyuyor. İkiz!','mankeni giydirmek','vitrinde bir manken','low_iq','exclamation'),
(462,'tr','Harita çeşmeyi buldu!','Harita kiliseyi buldu!','büyük bir kâğıt harita','telefonda harita','low_iq','exaggeration'),
(464,'tr','Keçeli kalemle çiziyor.','Tebeşirle çiziyor.','kalın pembe bir keçeli kalem','beyaz tahtada keçeli kalem','chill','none'),
(465,'tr','Pazarda alışveriş yapıyor.','AVM''de alışveriş yapıyor.','kalabalık bir sokak pazarı','kalabalık bir sokak partisi','chill','none'),
(466,'tr','Maskara yüzü: ağız ardına kadar açık.','Maskara yüzü: gözler sımsıkı kapalı.','siyah maskara sürmek','yanaklardan akan maskara','gossip','cliche'),
(467,'tr','Usta bir vazo şekillendiriyor.','Usta bir vazo boyuyor.','bir çömlek ustası','piyanoda bir usta','chill','none'),
(468,'tr','Yoga matlarının üstündeler.','Havlularının üstündeler.','mor bir yoga matı','kapının önünde paspas','chill','none'),
(469,'tr','Bu kibritler ilk seferde yanıyor!','Bu çakmak ilk seferde yanıyor!','bir kutu kibrit','bir kutu kürdan','dramatic','exclamation'),
(470,'tr','Çayıra düştüler.','Nehre düştüler.','gelinciklerle dolu çayır','ineklerle dolu çayır','chill','none'),
(471,'tr','Köpek o eti istiyor.','Kedi o eti istiyor.','tahtada ızgara et','kasapta çiğ et','low_iq','guessing'),
(472,'tr','Tamirci araba tamir ediyor.','Tamirci bisiklet tamir ediyor.','garajda bir tamirci','yolda bir tamirci','chill','none'),
(473,'tr','Altın madalyasını ısırıyor. Gerçek altın mı?','Altın yüzüğünü ısırıyor. Gerçek altın mı?','altın madalya ısırmak','kutuda bir madalya','dramatic','guessing'),
(474,'tr','Gün batımında grup meditasyonu.','Plajda grup meditasyonu.','ahşap terasta meditasyon','tapınakta meditasyon','chill','none'),
(475,'tr','Her anı onu gülümsetiyor.','Her anı onu ağlatıyor.','bir kutu eski anı','fotoğraf makinesi hafıza kartı','chill','none'),
(476,'tr','Mikroskop kullanıyor.','Teleskop kullanıyor.','mikroskop altında bir yaprak','mikroskop altında bir böcek','nerd','none'),
(477,'tr','Mikrodalga kanalı: en iyi dizi.','Fırın kanalı: en iyi dizi.','mikrodalgayı izlemek','mikrodalgayı temizlemek','ironic','exaggeration'),
(478,'tr','Herkesin süt bıyığı var!','Kimsenin süt bıyığı yok!','süt bıyığı','buzdolabında süt','dramatic','exaggeration'),
(479,'tr','Zihni iki hamle önde.','Zihni iki hamle geride.','zihninde hamle planlamak','fikrini değiştirmek','nerd','exaggeration'),
(480,'tr','Maden suyu onu gıdıklıyor.','Portakal suyu onu gıdıklıyor.','gazlı maden suyu','gazsız maden suyu','chill','none'),
(481,'tr','Ayna da onu seviyor.','Pencere de onu seviyor.','aynada kas göstermek','aynayı silmek','low_iq','guessing'),
(483,'tr','Maymun muz çaldı!','Maymun şapka çaldı!','muz yiyen bir maymun','muz satan bir maymun','dramatic','exclamation'),
(484,'tr','Yeri paspaslıyor.','Yeri süpürüyor.','kovada bir paspas','kovada bir süpürge','chill','none'),
(485,'tr','Yosun yumuşacık. Süper yastık.','Saman yumuşacık. Süper yastık.','yumuşak yeşil yosun','çatıda yosun','low_iq','none'),
(486,'tr','Dağın zirvesi, evet!','Dağın eteği, evet!','bir dağın tepesinde','bir dağ gölü','dramatic','exclamation'),
(487,'tr','Fare peyniri buldu.','Fare ekmeği buldu.','ahırda bir fare','fare ve klavye','chill','none'),
(488,'tr','Kasları devasa!','Ayakkabıları devasa!','kocaman kasları sıkmak','bacakta bir kas','dramatic','exclamation'),
(489,'tr','Mantarın beyaz benekleri var.','Mantarın siyah benekleri var.','benekli kırmızı mantar','kırmızı mantar çorbası','chill','none'),
(490,'tr','Bu müzisyen ünlü olacak.','Bu dansçı ünlü olacak.','bir sokak müzisyeni','gruptaki bir müzisyen','gossip','guessing'),
(491,'tr','Hardal çok keskin.','Bal çok keskin.','bir kaşık hardal','bir kavanoz hardal tohumu','chill','none'),
(492,'tr','Ojesi hâlâ yaş!','Saçı hâlâ ıslak!','tırnaklara oje sürmek','eski ojeyi silmek','dramatic','exclamation'),
(495,'tr','Doğada dinleniyorlar.','Doğada koşuyorlar.','doğada uzanmak','bir doğa belgeseli','chill','none'),
(496,'tr','Güzel kolye, harika seçim.','Güzel bilezik, harika seçim.','renkli boncuklu bir kolye','altın zincir kolye','flirt','none'),
(498,'tr','Gösteriden önce çok gergin!','Sınavdan önce çok gergin!','gergin bir gitarist','sınav öncesi gergin öğrenci','dramatic','exclamation'),
(499,'tr','Gazeteyle ce-ee!','Menüyle ce-ee!','gazetenin arkasına saklanmak','internetten gazete okumak','slang','exclamation'),
(500,'tr','Adamı yokmuş gibi top sürerek geçiyor.','Üç adamı yokmuşlar gibi top sürerek geçiyor.','defans oyuncusunu top sürerek geçmek','kaleciyi top sürerek geçmek','slang','exaggeration'),
(501,'tr','Gece yürüyorlar.','Öğlen yürüyorlar.','gece eve yürümek','gece çalışmak','chill','none'),
(502,'tr','Kuzeye gidiyorlar.','Güneye gidiyorlar.','pusulayla kuzeye gitmek','şehrin kuzeyi','business','none'),
(503,'tr','Yeni defter! Büyük an.','Yeni laptop! Büyük an.','yepyeni bir defter','notlarla dolu bir defter','ironic','exclamation'),
(505,'tr','Minik bir cevizle savaşıyor.','Minik bir yumurtayla savaşıyor.','ceviz kırmak','cıvatada bir somun','low_iq','exaggeration'),
(507,'tr','Bir yusufçuğu gözlemliyor.','Bir kelebeği gözlemliyor.','yusufçuk gözlemlemek','yusufçuk yakalamak','nerd','none'),
(508,'tr','Okyanusta yunuslar! Olamaz!','Okyanusta köpekbalıkları! Olamaz!','okyanusta yunuslar','okyanusta yüzmek','dramatic','exclamation'),
(509,'tr','Yağ yavaşça dökülüyor.','Süt yavaşça dökülüyor.','zeytinyağına banılmış ekmek','tavada yağ','chill','none'),
(511,'tr','Yüzücü gözlüğüyle soğan doğruyor. Dâhi!','Güneş gözlüğüyle soğan doğruyor. Dâhi!','beyaz soğan doğramak','beyaz soğan kavurmak','low_iq','exclamation'),
(512,'tr','Kombin sonunda oldu.','Saç kesimi sonunda oldu.','kombin hazırlamak','düğün için kombin','chill','none'),
(513,'tr','Dışarıda yemek yiyorlar. Yemek odası kimin umurunda?','İçeride yemek yiyorlar. Yemek odası kimin umurunda?','dışarıda çimenlerde yemek','dışarıda kafede yemek','ironic','guessing'),
(514,'tr','Fırın onların yeni televizyonu.','Buzdolabı onların yeni televizyonu.','fırında kabaran ekmek','fırında pizza','slang','exaggeration'),
(515,'tr','Duvarın üstesinden geldi!','Nehrin üstesinden geldi!','tırmanma duvarının üstesinden gelmek','köpek korkusunun üstesinden gelmek','dramatic','exclamation'),
(516,'tr','Lavabo taştı. Hoppala.','Küvet taştı. Hoppala.','taşan bir lavabo','taşan bir çöp kutusu','ironic','understatement'),
(517,'tr','Güle güle karavan! Solluyor!','Güle güle karavan! Park ediyor!','yavaş karavanı sollamak','hızlı treni sollamak','slang','exclamation'),
(518,'tr','Baykuş seni izliyor.','Karga seni izliyor.','dalda bir baykuş','kafeste bir baykuş','dramatic','exaggeration'),
(519,'tr','Çanta okul için hazırlandı.','Çanta gezi için hazırlandı.','okul çantası hazırlamak','valiz hazırlamak','chill','none'),
(520,'tr','Kız kürek çekiyor, oğlan uyuyor.','Kız kürek çekiyor, oğlan balık tutuyor.','kanoda kürek çekmek','sörf tahtasında kürek çekmek','gossip','banter'),
(521,'tr','Ayak parmağında ciddi ağrı var!','Elinde ciddi ağrı var!','ayak parmağında ağrı','sırtta ağrı','dramatic','exclamation'),
(522,'tr','Tablosu gerçek manzaradan daha güzelmiş, öyle diyor.','Tablosu gerçek manzaradan daha kötüymüş, öyle diyor.','deniz tablosu yapmak','duvarı beyaza boyamak','gossip','exaggeration'),
(523,'tr','O tavayla ne hareketler!','O pizza hamuruyla ne hareketler!','tavada sebzeler','tavada pankekler','flirt','exclamation'),
(524,'tr','Panik modu: tren onu bırakıp gitti!','Panik modu: otobüs onu bırakıp gitti!','perondaki panik','uçaktaki panik','dramatic','exclamation'),
(525,'tr','Minicik bir ataş koca vantilatörü yeniyor.','Minicik bir zımba koca vantilatörü yeniyor.','kâğıtlarda bir ataş','fotoğraf tutan bir ataş','dramatic','exaggeration'),
(526,'tr','Işın tabancası onu felç etti!','Su tabancası onu felç etti!','ışın tabancasıyla felç edilmiş','korkudan felç olmuş','dramatic','exclamation'),
(527,'tr','Ona paket geldi!','Ona mektup geldi!','paket açmak','paket göndermek','dramatic','exclamation'),
(528,'tr','Kız profesyonel gibi park ediyor!','Oğlan profesyonel gibi park ediyor!','iki araba arasına park etmek','garaja park etmek','slang','exaggeration'),
(530,'tr','Papağan merhaba diyor.','Papağan hoşça kal diyor.','korkulukta bir papağan','kafeste bir papağan','chill','none'),
(531,'tr','Bu bahçe partisi olay.','Bu havuz partisi olay.','gün batımında bahçe partisi','bir havuz partisi','slang','none'),
(532,'tr','Oğlan pas verdi, kız attı, çok kolay.','Kız pas verdi, oğlan attı, çok kolay.','kıza pas vermek','yavaş arabayı geçmek','slang','none'),
(533,'tr','Pasaportunu öptü!','Valizini öptü!','damgalı bir pasaport','pasaport fotoğrafı kabini','dramatic','exclamation'),
(535,'tr','Makarna kulesi profesyonel görünüyor.','Pasta kulesi profesyonel görünüyor.','makarnadan bir kule','salatada makarna','business','none'),
(536,'tr','Huzuru hamakta buluyor.','Huzuru küvette buluyor.','gün doğumunda huzur','gece yarısı huzur','chill','none'),
(537,'tr','Kırmızı bir elma soyuyor.','Yeşil bir elma soyuyor.','tek spiralde soymak','muz soymak','chill','none'),
(538,'tr','Kaleminde birçok renk var.','Kaleminde tek renk var.','çok renkli bir kalem','ışıklı bir kalem','chill','none'),
(540,'tr','Penaltıyı attı!','Penaltıyı kaçırdı!','penaltıyı gole çevirmek','penaltı kurtarmak','dramatic','exclamation'),
(541,'tr','Kurşun kalem çizimi çok iyi.','Tükenmez kalem çizimi çok iyi.','sarı kurşun kalemle çizmek','sarı kurşun kalemi açmak','flirt','none'),
(542,'tr','Göbek kaydırağı! Hadi penguen!','Göbek kaydırağı! Hadi fok!','buzda bir penguen','hayvanat bahçesinde penguen','slang','exclamation'),
(543,'tr','Karabiber onu hapşırttı!','Soğan onu hapşırttı!','karabiber öğütmek','kahve çekirdeği öğütmek','dramatic','blaming_someone'),
(545,'tr','Ne jonglörlük gösterisi ama!','Ne dans gösterisi ama!','sokakta jonglörlük gösterisi','okulda sınav performansı','dramatic','exclamation'),
(546,'tr','Bu kadar parfüm çok fazla!','Bu kadar su çok fazla!','arkadaşa parfüm sıkmak','elbiseye parfüm sıkmak','slang','exaggeration'),
(547,'tr','Telefonu çalıyor!','Kapı zili çalıyor!','telefona cevap vermek','cepte bir telefon','dramatic','exclamation'),
(548,'tr','Şu! Fotoğrafçılık çok eğlenceli.','Şu! Resim çok eğlenceli.','gün batımında sokak fotoğrafçılığı','salonda düğün fotoğrafçılığı','dramatic','exclamation'),
(549,'tr','Piercing''ine altın bir halka.','Piercing''ine altın bir çivi küpe.','altın halka piercing','burnunda piercing','chill','none'),
(550,'tr','Domuz çamurda yuvarlanıyor.','Domuz karda yuvarlanıyor.','çiftlikte bir domuz','küvette bir domuz','chill','none'),
(551,'tr','Güvercin kafeyi denetliyor.','Güvercin bankayı denetliyor.','meydanda bir güvercin','parkta bir güvercin','business','exaggeration'),
(553,'tr','Sahasıyla çok gurur duyuyor.','Arabasıyla çok gurur duyuyor.','sahayı biçmek','sahayı boyamak','gossip','none'),
(554,'tr','Sahilde mükemmel yer.','Parkta mükemmel yer.','oturmak için mükemmel yer','kuyrukta bir yer','chill','none'),
(555,'tr','Bitkinin yeni yaprağı var!','Bitkinin yeni çiçeği var!','büyük yapraklı bir bitki','kırmızı çiçekli bir bitki','dramatic','exclamation'),
(556,'tr','Hayatını bir yara bandıyla kurtardı.','Hayatını biraz buzla kurtardı.','parmak ucunda yara bandı','duvarda sıva','ironic','exaggeration'),
(557,'tr','Şef tabağı servis ediyor.','Şef tabağı yıkıyor.','beyaz tabakta spagetti','üst üste boş tabaklar','business','none'),
(558,'tr','Voleybol oynarken şapkasını kaybetti.','Voleybol oynarken ayakkabısını kaybetti.','parkta voleybol oynamak','parkta kâğıt oynamak','chill','none'),
(559,'tr','Bu oyuncu çok mutlu!','Bu oyuncu çok kızgın!','sarılı bir oyuncu','yedek kulübesinde bir oyuncu','dramatic','exclamation'),
(560,'tr','Önce selfie, sonra çeşme.','Önce selfie, sonra pizza.','ünlü Trevi Çeşmesi','AVM''de bir çeşme','chill','cliche'),
(561,'tr','Saf keyiften bir kruvasan.','Saf keyiften bir simit.','kruvasan keyfi','sabah kahvesi keyfi','dramatic','none'),
(562,'tr','Sorun fişteymiş.','Sorun ampuldeymiş.','gevşek bir fiş','küvet tıpası','chill','understatement'),
(563,'tr','Anahtarlar cebindeymiş!','Anahtarlar ayakkabısındaymış!','ceket cebinde anahtarlar','araba kapısında anahtarlar','low_iq','exclamation'),
(564,'tr','Ödül kürsüleri süngerden.','Ödül kürsüleri altından.','süngerden ödül kürsüsü','konferansta bir kürsü','ironic','cheap_quality'),
(565,'tr','Bu siyaset oyununda turuncu kazandı.','Bu siyaset oyununda yeşil kazandı.','kasaba meydanında siyaset','televizyonda siyaset','gossip','none'),
(566,'tr','Nehri kirletiyor. Ayıp!','Nehri temizliyor. Ayıp!','temiz nehri kirletmek','denizi kirletmek','dramatic','blaming_someone'),
(567,'tr','Bu gölette japon balıkları yaşıyor.','Bu gölette kurbağalar yaşıyor.','gölette japon balıkları','gölette ördekler','chill','none'),
(568,'tr','Havuzda sakin bir gün istemişti.','Gölde sakin bir gün istemişti.','havuza şap diye atlamak','bilardo masası','chill','guessing'),
(569,'tr','Postane müdürü çok buyurgan.','Postane müdürü çok utangaç.','buyurgan bir postane müdürü','tatildeki postane müdürü','gossip','none'),
(571,'tr','Tenceredeki su dans ediyor!','Tenceredeki su donuyor!','büyük tencerede patates','büyük saksıda çiçekler','low_iq','exaggeration'),
(572,'tr','Bir sürü patates buldular!','Bir sürü havuç buldular!','patates çıkarmak','patates soymak','dramatic','exclamation'),
(573,'tr','Onun dökme tekniği gerçek ustalık.','Onun şarkı tekniği gerçek ustalık.','yüksekten dökme','dışarıda sağanak yağmur','business','none'),
(574,'tr','Ne pudra bulutu ama!','Ne duman bulutu ama!','yüze pudra sürmek','beyaz tozla kek yapmak','dramatic','exclamation'),
(575,'tr','Kızın taşınabilir şarj cihazı günü kurtardı!','Oğlanın taşınabilir şarj cihazı günü kurtardı!','taşınabilir şarj cihazından şarj','evde taşınabilir şarj cihazı','dramatic','cliche'),
(576,'tr','İyi not için dua ediyor.','Yeni telefon için dua ediyor.','iyi not için dua etmek','kilisede dua etmek','dramatic','none'),
(577,'tr','Kız yağmuru tahmin etti. Oğlan edemedi.','Kız karı tahmin etti. Oğlan edemedi.','yağmuru tahmin etmek','piyango numaralarını tahmin etmek','gossip','banter'),
(578,'tr','Gururla ışıl ışıl parlıyor.','Gururdan ağlıyor.','motosikletiyle gurur','yeni arabasıyla gurur','chill','none'),
(579,'tr','Robot programlama zor iş.','Drone programlama zor iş.','küçük bir robot programlamak','video oyunu programlamak','chill','understatement'),
(580,'tr','Onu yağmurdan koruyor.','Onu güneşten koruyor.','birini yağmurdan korumak','birini köpekten korumak','chill','none'),
(581,'tr','Ayçiçekleriyle protesto ediyorlar!','Şemsiyelerle protesto ediyorlar!','doğa için protesto etmek','yağmurda protesto etmek','dramatic','exclamation'),
(582,'tr','Sandalyesi için çok gururlu.','Masası için çok gururlu.','işiyle gururlu','arabasıyla gururlu','chill','none'),
(585,'tr','Herkese açık alanda müzik çalıyor.','Herkese açık alanda satranç oynuyor.','herkese açık alanda müzik','herkese açık yüzme havuzu','chill','none'),
(587,'tr','Sarı takım pukla gol attı!','Mor takım pukla gol attı!','ağlarda bir puk','tribünde bir puk','dramatic','exclamation'),
(588,'tr','Şap! Koca bir su birikintisine atlayış.','Şap! Koca bir havuza atlayış.','su birikintisine atlamak','su birikintisinin etrafından dolaşmak','slang','exclamation'),
(589,'tr','Sıkı çekme, mutlu son.','Sıkı itme, mutlu son.','kalın halatı çekme','kapıyı çekip açma','chill','cliche'),
(590,'tr','Profesyonel gibi yumruk atıyor!','Profesyonel gibi tekme atıyor!','antrenör pedlerine yumruk atmak','duvara yumruk atmak','slang','exaggeration'),
(591,'tr','Kum torbasına âşık olmuş.','Garaj merdivenine âşık olmuş.','kum torbası asmak','garaj kapısını yumruklamak','gossip','guessing'),
(592,'tr','Kamyonet itmek mi? Çocuk oyuncağı!','Otobüs itmek mi? Çocuk oyuncağı!','beyaz kamyoneti itme','beyaz arabayı itme','ironic','understatement'),
(593,'tr','Eş pijamalar mı? Çok tatlı!','Eş ceketler mi? Çok tatlı!','eş ekose pijamalar','eş çizgili pijamalar','flirt','exclamation'),
(594,'tr','Atlayışı ona tur atlattı.','Yüzüşü ona tur atlattı.','atlayışla tur atlamak','doktor olmaya hak kazanmak','chill','none'),
(595,'tr','Tavşan dik oturuyor.','Tavşan yatıyor.','kumullarda bir tavşan','şapkada bir tavşan','chill','none'),
(596,'tr','Hadi, hadi, hadi! Ne yarış ama!','Hadi, hadi, hadi! Ne yüzüş ama!','pistte bir yarış','havuzda bir yarış','dramatic','exclamation'),
(597,'tr','Raketle süper numara.','Şişeyle süper numara.','siyah bir tenis raketi','badminton raketi','slang','none'),
(598,'tr','Yağmurda dans ediyor.','Karda dans ediyor.','sağanak yağmurda dans','yağmurdan saklanmak','chill','none'),
(599,'tr','Bu hareketler aşırı hızlı.','Bu hareketler aşırı yavaş.','hızlı top çalımları','hızlı paslar','slang','none'),
(600,'tr','Sıçan pizza çalıyor!','Sıçan ekmek çalıyor!','pizzalı bir sıçan','kafeste bir sıçan','dramatic','exclamation'),
(601,'tr','Tıraş makinesiyle tıraş oluyor.','Bıçakla tıraş oluyor.','elektrikli tıraş makinesi','bir tıraş bıçağı','chill','none'),
(602,'tr','Gece trende okuma.','Gece teknede okuma.','gece treninde okuma','kütüphanede okuma','chill','none'),
(604,'tr','Bu fiş bitmiyor!','Bu menü bitmiyor!','upuzun bir fiş','kısacık bir fiş','slang','exaggeration'),
(606,'tr','Tarif diyor ki: önce yumurta.','Tarif diyor ki: önce balık.','elle çizilmiş tarif kartı','çorba tarifi','business','none'),
(607,'tr','Buzdolabı artık dolu.','Fırın artık dolu.','buzdolabını doldurmak','buzdolabını temizlemek','chill','none'),
(608,'tr','Park etti! Ne büyük rahatlama!','Çarptı! Ne büyük rahatlama!','park sonrası rahatlama','kaza sonrası rahatlama','dramatic','exclamation'),
(609,'tr','Tepede dinleniyorlar.','Tepede koşuyorlar.','tepede dinlenmek','hamakta dinlenmek','chill','none'),
(610,'tr','Balkabağı mavi kurdele aldı. Kız şokta!','Havuç mavi kurdele aldı. Kız şokta!','balkabağının mavi kurdelesi','saçında bir kurdele','gossip','none'),
(612,'tr','Parmağıyla sağa işaret ediyor.','Parmağıyla gökyüzüne işaret ediyor.','tezgâhların yanından sağa gitmek','ışıklardan sağa dönmek','chill','none'),
(613,'tr','Ringde zıplıyor.','Havuzda zıplıyor.','ringe çıkmak','parmakta bir yüzük','chill','none'),
(615,'tr','Nehirde yaprak yarışı. Hadi hadi!','Nehirde tekne yarışı. Hadi hadi!','berrak nehirde yapraklar','nehirde bir tekne','slang','none'),
(616,'tr','Kaya: bir. İnsanlar: sıfır.','Ağaç: bir. İnsanlar: sıfır.','dev bir kayayı itmek','küçük bir kaya atmak','slang','cliche'),
(617,'tr','Sırf onun içeceğini almak için patenle geldi!','Sırf onun içeceğini almak için bisikletle geldi!','parkta mor patenler','buz pistinde patenler','dramatic','exaggeration'),
(618,'tr','Halat arabayı kurtardı!','Zincir arabayı kurtardı!','tekerleğe sarılı halat','ip atlamak için halat','dramatic','exaggeration'),
(619,'tr','Bir sepet indiriyor.','Bir kova indiriyor.','iple sepet indirmek','bayrağı indirmek','chill','none'),
(620,'tr','Bu gül cennet gibi kokuyor.','Bu lale cennet gibi kokuyor.','pembe bir gülü koklamak','pembe bir gül almak','dramatic','cliche'),
(622,'tr','Bir lastik otları bir arada tutuyor.','Bir lastik pırasaları bir arada tutuyor.','turuncu bir lastik','saç lastiği','business','none'),
(623,'tr','Ne kaba adam ya!','Ne kibar adam ya!','kaba bir kafe müşterisi','kaba bir garson','slang','exclamation'),
(624,'tr','Şapkasının peşinden koşuyor!','Köpeğinin peşinden koşuyor!','şapkanın peşinden koşmak','otobüsün peşinden koşmak','dramatic','exclamation'),
(626,'tr','Koşucu su içiyor.','Koşucu muz yiyor.','su içen bir koşucu','koşu bandında bir koşucu','chill','none'),
(627,'tr','Salon podyumu. Döktür!','Mutfak podyumu. Döktür!','oturma odasında podyum','havalimanında bir pist','slang','exclamation'),
(628,'tr','Yüzü üzüntüyle dolu.','Yüzü neşeyle dolu.','boş dükkânda üzüntü','cenazede üzüntü','dramatic','none'),
(629,'tr','İçeride güvende, dışarıda fırtına.','İçeride güvende, dışarıda güneş.','dağ kulübesinde güvende','duvardaki kasa','chill','cliche'),
(630,'tr','Denizci dümende!','Denizci masada!','güvertede bir denizci','barda bir denizci','slang','exclamation'),
(632,'tr','Domateslere tuz serpiyorlar.','Patateslere tuz serpiyorlar.','domates dilimlerinde tuz','karlı yolda tuz','chill','none'),
(634,'tr','Bir dalga kumdaki eserini yuttu.','Bir köpek kumdaki eserini yuttu.','kuma resim çizmek','kumdan kale yapmak','slang','exaggeration'),
(635,'tr','Sandaletler giyildi, parmaklar dışarıda!','Botlar giyildi, parmaklar dışarıda!','ten rengi sandaletleri bağlamak','ten rengi sandalet almak','slang','none'),
(636,'tr','Ördek bile o sandviçi istiyor.','Köpek bile o sandviçi istiyor.','jambonlu peynirli sandviç','beslenme çantasında sandviç','chill','guessing'),
(637,'tr','Nar: yüzlerce çekirdek.','Karpuz: yüzlerce çekirdek.','nar açmak','bardakta nar suyu','nerd','exaggeration'),
(638,'tr','Sosu fena abartmış!','Tuzu fena abartmış!','sos dolu bir tabak','şişede sos','slang','exaggeration'),
(639,'tr','Sosis kızartıyor.','Yumurta kızartıyor.','tavada sosis kızartmak','pizzada sosis','chill','none'),
(640,'tr','Bu terazi kesin bozuk!','Bu saat kesin bozuk!','kadranlı büyük bir terazi','mutfak terazisi','low_iq','bad_excuse'),
(641,'tr','Kedi terazinin üstünde!','Köpek terazinin üstünde!','terazide bir kedi','iş yerinde maaş skalası','gossip','exclamation'),
(642,'tr','Yara izlerini karşılaştırıyorlar.','Dövmelerini karşılaştırıyorlar.','yara izlerini karşılaştırmak','yara izlerini saklamak','chill','none'),
(644,'tr','Kim var orada? Kız korkmuş!','Kim var orada? Oğlan korkmuş!','otoparkta korkmuş','hız treninde korkmuş','dramatic','exclamation'),
(645,'tr','Programını düzenliyor.','Masasını düzenliyor.','program planlamak','otobüs saatleri','business','none'),
(646,'tr','Bilim turuncu köpük yapıyor!','Bilim mavi köpük yapıyor!','bir bilim deneyi','bir bilim müzesi','dramatic','exclamation'),
(647,'tr','Makasla ucundan azıcık.','Tıraş makinesiyle ucundan azıcık.','makasla kakül kesmek','makasla kâğıt kesmek','ironic','understatement'),
(649,'tr','Babaanne yine onu azarlıyor.','Babaanne yine ona sarılıyor.','torunu azarlamak','köpeği azarlamak','gossip','none'),
(650,'tr','Son vidayı buldu!','Son çiviyi buldu!','kayıp son vida','kayıp son çorap','dramatic','exclamation'),
(651,'tr','Tornavida kızda, oğlan endişede.','Çekiç kızda, oğlan endişede.','tornavidayla sıkıştırmak','elinde bir tornavida','gossip','banter'),
(652,'tr','Iyy! Deniz tuzlu!','Iyy! Göl tuzlu!','denize atlamak','insan denizi','dramatic','exclamation'),
(653,'tr','Bunca arama! Anahtarlar kapıdaymış.','Bunca arama! Anahtarlar arabadaymış.','kayıp anahtarları aramak','kayıp köpeği aramak','dramatic','exclamation'),
(655,'tr','Parti şapkaları mı? Kız ciddi kalıyor.','Parti şapkaları mı? Oğlan ciddi kalıyor.','işte ciddi bir surat','akşam yemeğinde ciddi konuşma','ironic','understatement'),
(656,'tr','Koca kalabalık bile kızın dikkatini dağıtamıyor!','Koca kalabalık bile oğlanın dikkatini dağıtamıyor!','kızın dikkatini dağıtmaya çalışmak','köpeğin dikkatini dağıtmaya çalışmak','dramatic','exclamation'),
(657,'tr','Erişteyi profesyonel gibi servis ediyor.','Pizzayı profesyonel gibi servis ediyor.','bir kase erişte servis etmek','tenis servisi atmak','slang','none'),
(659,'tr','Bu çok fazla şampuan!','Bu çok fazla krem!','şampuan köpüğünden kule','köpek şampuanı','dramatic','exclamation'),
(661,'tr','Köpekbalığı sana gülümsüyor.','Yunus sana gülümsüyor.','kameranın yakınında köpekbalığı','teknenin yakınında köpekbalığı','dramatic','guessing'),
(662,'tr','Kalemtıraş mükemmel çalışıyor.','Kalemtıraş kötü çalışıyor.','küçük bir kalemtıraş','küçük bir bıçak bileyici','business','none'),
(663,'tr','Tıraş köpüğü: anında sakal!','Tıraş köpüğü: anında şapka!','girdap gibi tıraş köpüğü','pastada tıraş köpüğü','low_iq','exaggeration'),
(664,'tr','Elle tıraş olmak, eski usul.','Elle ağda yapmak, eski usul.','ustura ile tıraş olmak','elektrikli makineyle tıraş olmak','slang','cliche'),
(665,'tr','Koyun bana kızgın mı?','Keçi bana kızgın mı?','yamaçta bir koyun','ahırda bir koyun','low_iq','exaggeration'),
(666,'tr','Mavi bir gömlek giyiyor.','Kırmızı bir gömlek giyiyor.','açık mavi gömleği iliklemek','açık mavi gömleği ütülemek','chill','none'),
(667,'tr','Devrilen scooter tam bir şok.','Devrilen bisiklet tam bir şok.','devrilen scooter şoku','elektrik şoku','dramatic','none'),
(668,'tr','Ayakkabılar bağlandı. Hazırım.','Botlar bağlandı. Hazırım.','kahverengi ayakkabıları bağlamak','kahverengi ayakkabıları boyamak','business','none'),
(669,'tr','Bu dükkânda üç bozuk para çok şey alıyor.','Bu dükkânda on bozuk para çok şey alıyor.','küçük bir bakkal dükkânı','küçük bir çiçekçi dükkânı','gossip','cheap_quality'),
(670,'tr','Çok verimli alışveriş yapıyor.','Çok verimli yüzüyor.','süpermarkette alışveriş yapmak','kıyafet alışverişi yapmak','business','none'),
(671,'tr','Çok bağırmaktan boğazlar ağrıdı.','Çok şarkı söylemekten boğazlar ağrıdı.','vadiye doğru bağırmak','televizyona bağırmak','chill','exaggeration'),
(672,'tr','Buz gibi suyla duş almak!','Sıcak suyla duş almak!','sahilde duş almak','banyoda duş almak','dramatic','exaggeration')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
