begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(673,'tr','Kazağı küçüldü. Hem de nasıl!','Atkısı küçüldü. Hem de nasıl!','küçülmüş kırmızı kazak','korkudan geri çekilmek','dramatic','exclamation'),
(674,'tr','Hasta ve evde.','Hasta ve işte.','kanepede hasta','hastane yatağında hasta','chill','none'),
(675,'tr','Teknenin bir yanı bitti.','Evin bir yanı bitti.','teknenin yanını boyamak','gölün bir yanı','business','none'),
(676,'tr','Venedik''te şehir turu yapıyorlar.','Paris''te şehir turu yapıyorlar.','gondolla şehir turu','otobüsle şehir turu','chill','none'),
(678,'tr','İpek yerinde durmayı reddediyor.','Kedi yerinde durmayı reddediyor.','parlak yeşil ipek','ipek bir kravat','ironic','none'),
(679,'tr','Gümüş yine parlıyor!','Altın yine parlıyor!','eski gümüşleri parlatmak','arabada gümüş boya','dramatic','exclamation'),
(680,'tr','Şarkıcı keyif yapıyor.','Şarkıcı öğle yemeği yiyor.','stüdyoda bir şarkıcı','sahnede bir şarkıcı','chill','none'),
(681,'tr','Arabada avaz avaz şarkı söylemek!','Duşta avaz avaz şarkı söylemek!','arabada şarkı söylemek','sahnede şarkı söylemek','dramatic','exclamation'),
(683,'tr','Evye köpük dağına döndü!','Küvet köpük dağına döndü!','köpük dolu bir evye','oyuncak dolu bir evye','low_iq','exaggeration'),
(684,'tr','Kız kardeşi sonunda evde!','Erkek kardeşi sonunda evde!','kız kardeşine sarılmak','kız kardeşiyle kavga etmek','dramatic','exclamation'),
(685,'tr','Sonunda doğru beden.','Sonunda doğru ayakkabı.','doğru şapka bedeni','doğru ayakkabı numarası','chill','none'),
(687,'tr','Gün batımında kaykay? Çok havalı.','Gün batımında bisiklet? Çok havalı.','kaykay sürmek','dükkânda bir kaykay','slang','none'),
(688,'tr','Cildine iyi bakıyor.','Köpeğine iyi bakıyor.','cildine krem sürmek','cildini sabunla yıkamak','chill','none'),
(689,'tr','Harika etek, harika dönüş!','Harika şapka, harika dönüş!','sarı pliseli etek','uzun siyah etek','flirt','exclamation'),
(690,'tr','Gökyüzü ne kadar büyük.','Deniz ne kadar büyük.','gökyüzüne bakmak','yıldız dolu gökyüzü','chill','none'),
(691,'tr','Arabasını koruyor. Pek beceremeden.','Arabasını yıkıyor. Pek beceremeden.','park halindeki arabayı korumak','bir bankayı korumak','ironic','none'),
(692,'tr','Uyumak mı? Adam profesyonel.','Okumak mı? Adam profesyonel.','battaniyenin altında uyumak','çadırda uyumak','slang','cliche'),
(693,'tr','Beş dakika daha. Çok uykuluyum.','Beş dakika daha. Çok zindeyim.','uykulu bir gece yolculuğu','uykulu bir sabah dersi','ironic','bad_excuse'),
(694,'tr','Domates dilimliyor.','Salatalık dilimliyor.','domatesi ince dilimlemek','pasta dilimlemek','chill','none'),
(695,'tr','Az sonra herkes gülümsüyor.','Az sonra herkes ağlıyor.','vapurda gülümsemek','kameraya gülümsemek','chill','none'),
(696,'tr','Dumanın içinde kayboldu!','Karın içinde kayboldu!','gri bir duman bulutu','bacadan çıkan duman','dramatic','exaggeration'),
(697,'tr','Sigara içme alanı kalabalık.','Sigara içme alanı bomboş.','barın önünde sigara içmek','sigara içilmez tabelası','chill','none'),
(698,'tr','Smoothie resmen mor.','Smoothie resmen yeşil.','koyu orman meyveli smoothie','yeşil bir smoothie','slang','none'),
(699,'tr','Nöbetçinin burnunun dibinden peynir kaçakçılığı yaptı!','Nöbetçinin burnunun dibinden şarap kaçakçılığı yaptı!','samanın içinde peynir kaçakçılığı','teknede peynir kaçakçılığı','gossip','exclamation'),
(700,'tr','Salyangozun hiç acelesi yok.','Kurbağanın hiç acelesi yok.','yaprağın üstünde salyangoz','tabakta salyangoz','chill','understatement'),
(701,'tr','Yılan siyah bir kayanın üstünde.','Yılan beyaz bir kayanın üstünde.','kumda bir yılan','çimenlerde bir yılan','chill','none'),
(702,'tr','Spor ayakkabılar giyildi, sıra merdivende.','Sandaletler giyildi, sıra merdivende.','petrol mavisi spor ayakkabı bağlamak','petrol mavisi spor ayakkabı temizlemek','slang','none'),
(704,'tr','Hapşırınca şapkası uçtu!','Hapşırınca ayakkabısı uçtu!','karahindibalara hapşırmak','bir kediye hapşırmak','dramatic','exaggeration'),
(705,'tr','Hapşırması bir türlü bitmiyor.','Şarkı söylemesi bir türlü bitmiyor.','dirseğine hapşırmak','mendile hapşırmak','dramatic','none'),
(706,'tr','Dilinde kar? Nefis!','Dilinde yağmur? Nefis!','diliyle kar yakalamak','arabadaki karı temizlemek','slang','exclamation'),
(707,'tr','Havalı turuncu snowboard, kanka.','Havalı mavi snowboard, kanka.','snowboard''u ayağa bağlamak','dükkânda bir snowboard','slang','none'),
(708,'tr','Eller çamur mu? Sabun zamanı!','Ayaklar çamur mu? Sabun zamanı!','bir kalıp sabun','bir şişe sabun','slang','exclamation'),
(710,'tr','Ellerinde bir köpük bulutu.','Başında bir köpük bulutu.','kocaman bir köpük bulutu','çamaşır makinesinde köpük','chill','exaggeration'),
(711,'tr','Telefon %1. Priz bulundu!','Telefon %50. Priz bulundu!','gizli bir duvar prizi','bir ampul duyu','dramatic','exclamation'),
(712,'tr','Gazozundan korkuyor.','Sandviçinden korkuyor.','bir kutu portakallı gazoz','bir bardak kola','low_iq','guessing'),
(713,'tr','Aa, merhaba! Toprakta bir solucan!','Aa, merhaba! Toprakta bir madeni para!','koyu toprağa dikim yapmak','halıda toprak','dramatic','exclamation'),
(714,'tr','Asker yine evde!','Asker yine denizde!','eve dönen bir asker','evden ayrılan bir asker','dramatic','exclamation'),
(715,'tr','Biri ona kahve bırakmış.','Biri ona pizza bırakmış.','birinden gelen not','birinin doğum günü kartı','chill','none'),
(716,'tr','Çorba kaşığıyla yiyor.','Yemek çubuklarıyla yiyor.','çorba kaşığıyla yemek','çorba kaşığıyla karıştırmak','chill','none'),
(717,'tr','Çorba cehennem gibi sıcak!','Çorba buz gibi soğuk!','sıcak domates çorbası','soğuk domates çorbası','dramatic','exclamation'),
(719,'tr','Vay, uzay bomboş!','Vay, deniz bomboş!','uzayda yıldızlar','boş bir park yeri','dramatic','exclamation'),
(720,'tr','Bu baharat gerçekten çok sert.','Bu baharat gerçekten çok yeşil.','külahta kırmızı baharat','bir kavanoz kuru baharat','chill','none'),
(721,'tr','Her şeyi o döktü!','Her şeyi çocuk döktü!','bir bardak su dökmek','bir fincan kahve dökmek','dramatic','blaming_someone'),
(723,'tr','Doktor ona omurgayı kemik kemik gösteriyor.','Doktor ona kafatasını kemik kemik gösteriyor.','omurganın kemikleri','bir balığın omurgası','nerd','none'),
(724,'tr','Her su sıçraması daha büyük!','Her su sıçraması daha küçük!','kocaman bir su sıçraması','bir süt sıçraması','dramatic','exclamation'),
(726,'tr','İlkbahar geldi, ceketler çıktı.','Kış geldi, ceketler çıktı.','kiraz ağaçları altında ilkbahar','şehirde ilkbahar yağmuru','chill','none'),
(727,'tr','Finişe sprint attı!','Finişe yürüdü!','bitiş çizgisine sprint atmak','otobüse sprint atmak','dramatic','exclamation'),
(729,'tr','Sincap kış için plan yapıyor.','Tavşan kış için plan yapıyor.','palamutlu bir sincap','pizzalı bir sincap','business','guessing'),
(730,'tr','Personel topluca poz veriyor.','Personel topluca yemek yiyor.','iş başında restoran personeli','trende personel','chill','none'),
(731,'tr','Üstüne pul koyuyor.','Üstüne bozuk para koyuyor.','zarfın üstünde pul','bir pul albümü','chill','none'),
(733,'tr','İki devlet antlaşma imzaladı.','Üç devlet antlaşma imzaladı.','antlaşma imzalayan iki devlet','kaos içinde bir devlet','business','none'),
(734,'tr','Köpek o bifteği istiyor.','Kedi o bifteği istiyor.','içi pembe bir biftek','dondurucuda bir biftek','gossip','guessing'),
(735,'tr','Buhar gözlüğünü buğuladı!','Yağmur gözlüğünü buğuladı!','bir buhar bulutu','bir duman bulutu','dramatic','exclamation'),
(736,'tr','Selam, yeni üvey erkek kardeş!','Selam, yeni üvey kız kardeş!','yeni üvey erkek kardeşle tanışmak','üvey erkek kardeşle kavga etmek','dramatic','exclamation'),
(737,'tr','Yılın üvey babası bisikleti tamir etti.','Yılın üvey babası arabayı tamir etti.','bisiklet tamir eden üvey baba','düğünde bir üvey baba','gossip','exaggeration'),
(738,'tr','Yapışkanlı nota bir kalp çizdi.','Yapışkanlı nota bir yıldız çizdi.','kalpli yapışkanlı not','ekranda yapışkanlı notlar','flirt','none'),
(739,'tr','Pizza için durdu. Kural kuraldır.','Suşi için durdu. Kural kuraldır.','pizza için durmak','benzin için durmak','ironic','cliche'),
(740,'tr','Bu kronometre kesin bozuk!','Bu telefon kesin bozuk!','kronometreye basmak','telefon kamerasına basmak','ironic','bad_excuse'),
(741,'tr','Dışarıda koca fırtına, içeride çay.','Dışarıda koca güneş, içeride çay.','çay eşliğinde fırtınayı izlemek','fırtınada yürümek','chill','none'),
(742,'tr','Ocağın dört gözü de açık.','Ocağın sadece bir gözü açık.','ocakta dört göz','küçük bir kamp ocağı','business','none'),
(743,'tr','Yol tamamen düz.','Yol tamamen virajlı.','düz bir sıra tuğla','düz bir cevap','slang','none'),
(744,'tr','Şemsiyeli bir yabancıyla tanıştı.','Kocaman köpekli bir yabancıyla tanıştı.','şemsiyeli bir yabancı','bisikletli bir yabancı','gossip','none'),
(746,'tr','Dereyi atlıyorlar!','Çiti atlıyorlar!','derenin üstünden atlamak','derede yüzmek','dramatic','exclamation'),
(747,'tr','Sadece birazcık stres.','Sadece birazcık yağmur.','ofiste stres','spor salonunda stres','ironic','understatement'),
(749,'tr','Birlikte esneme yapıyorlar.','Birlikte dans ediyorlar.','koşudan önce esnemek','bir lastiği germek','chill','none'),
(750,'tr','İp kutuyu sımsıkı tutuyor.','İp çantayı sımsıkı tutuyor.','iple bağlanmış kutu','bir gitar teli','business','none'),
(751,'tr','Uyumlu kombin mi? Onun stili değil.','Mor bot mu? Onun stili değil.','kendine has cesur stili','bir müzik stili','gossip','guessing'),
(752,'tr','Kahvesini şeker kurtardı!','Kahvesini süt kurtardı!','sade kahvede şeker','pastanın üstünde şeker','dramatic','exaggeration'),
(753,'tr','O mavi takım elbise ona çok yakışıyor.','O gri takım elbise ona çok yakışıyor.','mavi takım elbise denemek','mavi takım elbise yıkamak','flirt','none'),
(754,'tr','Arkadaşı onu destekliyor.','Arkadaşı onu görmezden geliyor.','arkadaşını desteklemek','bir futbol takımını desteklemek','chill','none'),
(755,'tr','Buradaki her yüzey pürüzsüz.','Buradaki her yüzey pürüzlü.','pürüzsüz parlak bir yüzey','çizik dolu bir yüzey','chill','none'),
(756,'tr','Sörf tahtasında harika gidiyorsun.','Jet skide harika gidiyorsun.','beyaz sörf tahtasını mumlamak','dükkânda bir sörf tahtası','flirt','none'),
(757,'tr','Kutuda bir köpek yavrusu! Ne büyük sürpriz!','Kutuda bir kedi yavrusu! Ne büyük sürpriz!','kutuda bir sürpriz','evde sürpriz parti','dramatic','exclamation'),
(758,'tr','Kuğu kendini temizliyor.','Kuğu balık yiyor.','gölde bir kuğu','çimenlerde bir kuğu','chill','none'),
(759,'tr','Dışarıda yağmur, içeride kazak.','Dışarıda güneş, içeride kazak.','rahat bir kazak giymek','rahat bir kazak örmek','chill','none'),
(760,'tr','Eyvah! Ayak bileği şişiyor!','Eyvah! El bileği şişiyor!','şişen bir ayak bileği','şişen bir el bileği','dramatic','none'),
(761,'tr','Ayağında büyük bir şişlik var.','Elinde büyük bir şişlik var.','ayak bileğinde şişlik','dizde şişlik','chill','none'),
(762,'tr','Yok, yok, belki... şu tişört!','Yok, yok, belki... şu ceket!','petrol mavisi tişört giymek','petrol mavisi tişört katlamak','slang','none'),
(763,'tr','Masa örtüsü havaya uçuyor.','Perde havaya uçuyor.','masa örtüsünü havaya atmak','şarap lekeli masa örtüsü','chill','none'),
(764,'tr','Tablete çizim yapıyor.','Peçeteye çizim yapıyor.','tablete çizim yapmak','bir ilaç tableti','chill','none'),
(766,'tr','Bu dövme sonsuza kadar!','Bu çıkartma sonsuza kadar!','yeni yapılmış kuş dövmesi','bacakta bir dövme','dramatic','exclamation'),
(767,'tr','Çay yaprakları dans ediyor!','Çay poşetleri dans ediyor!','naneli çay koymak','sütlü çay','dramatic','exclamation'),
(768,'tr','Takım uyum içinde kürek çekiyor.','Takım uyum içinde koşuyor.','gün doğumunda kürek takımı','ofiste bir takım','business','none'),
(769,'tr','Çay kaşıkları minicik.','Çay kaşıkları kocaman.','çay kaşığıyla karıştırmak','bir çay kaşığı şeker','chill','none'),
(770,'tr','Tenis topu için kendini attı!','Golf topu için kendini attı!','tenis maçında atlayış','çim kortta tenis','dramatic','exclamation'),
(771,'tr','Terminal devasa.','Terminal minicik.','devasa cam terminal','küçük bir otobüs terminali','chill','none'),
(772,'tr','Terapi danışana iyi geliyor.','Yoga danışana iyi geliyor.','bir terapi seansı','bir yoga seansı','business','none'),
(773,'tr','Termometresi çıldırdı!','Saati çıldırdı!','ağızda termometre','duvarda termometre','slang','exaggeration'),
(775,'tr','Tek hamle için bu kadar düşünmek mi?!','Tek gol için bu kadar düşünmek mi?!','satranç başında derin düşünme','kartlar başında derin düşünme','slang','exclamation'),
(776,'tr','Koca susuzluğa tek damla.','Koca susuzluğa tek bisküvi.','korkunç bir susuzluk','çölde susuzluk','ironic','understatement'),
(777,'tr','Fena susamış!','Fena acıkmış!','pazarda susamış','koşudan sonra susamış','slang','none'),
(778,'tr','Kilometrelerce uzun bir iplik!','Kilometrelerce uzun bir halat!','uzun kırmızı bir iplik','bir makara mavi iplik','dramatic','exaggeration'),
(779,'tr','Bu su samuru biraz şekerleme istiyor.','Bu kedi biraz şekerleme istiyor.','uykulu bir su samuru','nehirde bir su samuru','chill','guessing'),
(780,'tr','Kediler asker gibi ayakta duruyor!','Köpekler asker gibi ayakta duruyor!','yatakta ayakta duran kediler','masada ayakta duran kediler','dramatic','exaggeration'),
(781,'tr','Bir, iki, üç... gök gürültüsü!','Bir, iki, üç... gökkuşağı!','gök gürültüsünü beklemek','futbol stadında gök gürültüsü','dramatic','exclamation'),
(782,'tr','İkinci deneme, kusursuz kravat.','İkinci deneme, kusursuz pasta.','koyu kırmızı kravat bağlamak','koyu kırmızı kravat almak','business','none'),
(783,'tr','Islak kaplan, sinirler tavan!','Islak aslan, sinirler tavan!','nehirde bir kaplan','ağaçta bir kaplan','slang','guessing'),
(784,'tr','Şemsiyeyi eğiyor.','Şemsiyeyi kapatıyor.','şemsiyeyi eğmek','başını eğmek','chill','none'),
(785,'tr','Tarifeye bakıyor.','Gazeteye bakıyor.','büyük bir tren tarifesi','bir ders programı','business','none'),
(786,'tr','Birazcık yorgun.','Hiç yorgun değil.','işten sonra yorgun','beklemekten yorgun','ironic','understatement'),
(788,'tr','Sırada mikrodalgada ısıtmak isteyen o.','Sırada fırında ısıtmak isteyen o.','noodle kasesini mikrodalgada ısıtmak','sütü mikrodalgada ısıtmak','gossip','none'),
(789,'tr','Ekmek kızartma makinesi tostu fırlattı!','Fırın tostu fırlattı!','ekmek fırlatan kızartma makinesi','mini bir fırın','slang','exaggeration'),
(790,'tr','O domatesle harika iş çıkardın.','O soğanla harika iş çıkardın.','olgun bir domatesi dilimlemek','domates fidesi dikmek','flirt','none'),
(791,'tr','Önce yanlış aleti seçti.','Önce doğru aleti seçti.','doğru aleti seçmek','bahçe için bir alet','chill','none'),
(792,'tr','Bu ne kadar çok diş macunu!','Bu ne kadar çok şampuan!','diş macunundan bir kule','bir tüp diş macunu','dramatic','exaggeration'),
(793,'tr','Son taşı tepeye koydu.','Son deniz kabuğunu tepeye koydu.','tepede bir taş','arabanın tepesi','chill','none'),
(794,'tr','Turnuvayı çocuk kazandı!','Turnuvayı denizci kazandı!','bilek güreşi turnuvası','satranç turnuvası','dramatic','exclamation'),
(795,'tr','Havlu köpeğe de var!','Havlu kediye de var!','havluyla kurulanmak','plaj havlusunda uzanmak','dramatic','exclamation'),
(797,'tr','Pistte yarışıyorlar!','Havuzda yarışıyorlar!','kırmızı bir koşu pisti','bir uçak pisti','dramatic','exclamation'),
(798,'tr','Eşofman çetesi ara sokakta!','Eşofman çetesi plajda!','uyumlu turkuaz eşofmanlar','koşu pistinde eşofmanlılar','slang','exclamation'),
(800,'tr','Antrenman bitti, bacaklar gitti.','Maç bitti, bacaklar gitti.','projektör altında antrenman','köpek yavrusuyla antrenman','slang','exaggeration'),
(801,'tr','Trambolinde uçuyor!','Yatakta uçuyor!','trambolinde zıplamak','trambolinin altına saklanmak','dramatic','exaggeration'),
(802,'tr','Çöp kovasına LeBron''luk yapıyor.','Küvete LeBron''luk yapıyor.','çöp kovasından pota','çöp kovası kapağı','slang','guessing'),
(804,'tr','Seyahat etmeye bayılıyor.','Seyahat etmekten nefret ediyor.','uçakla seyahat etmek','otobüsle seyahat etmek','slang','none'),
(805,'tr','Trenle seyahat, tam zamanında!','Otobüsle seyahat, tam zamanında!','Alpler''de seyahat','gemiyle seyahat','dramatic','exclamation'),
(806,'tr','Tepsileri profesyonel gibi taşıyor.','Kutuları profesyonel gibi taşıyor.','havada tutulan tepsi','yerde bir tepsi','slang','cliche'),
(807,'tr','Koşu bandı az kalsın kazanıyordu, kanka.','Kondisyon bisikleti az kalsın kazanıyordu, kanka.','koşu bandında koşmak','koşu bandında yürümek','slang','guessing'),
(808,'tr','Ağaç devasa!','Kaya devasa!','devasa yaşlı bir ağaç','bir ağaç ev','dramatic','exclamation'),
(809,'tr','Korgi bile trende uyuyor!','Kedi bile trende uyuyor!','sarı şapka trendine uymak','yeni bir trend başlatmak','gossip','exaggeration'),
(811,'tr','Kupa yukarı, konfeti aşağı!','Madalya yukarı, konfeti aşağı!','altın kupayı kaldırmak','altın kupayı temizlemek','slang','exclamation'),
(812,'tr','Tam güven: kayayı bırakıyor!','Tam güven: ipi bırakıyor!','partnerine güven','şansına güven','dramatic','exclamation'),
(813,'tr','Hindi yıldız gibi poz veriyor.','Kaz yıldız gibi poz veriyor.','samanın üstünde bir hindi','tabakta bir hindi','chill','exaggeration'),
(814,'tr','Vantilatörü kapatıyor.','Televizyonu kapatıyor.','ışığı kapatmak','yolu kapatmak','chill','none'),
(815,'tr','Kaplumbağa artık denizde.','Kaplumbağa artık havuzda.','sahilde bir kaplumbağa','akvaryumda bir kaplumbağa','chill','none'),
(816,'tr','Smokinle harika görünüyor.','Eşofmanla harika görünüyor.','smokin giymek','smokin kiralamak','flirt','none'),
(817,'tr','İki kedi yan yana.','İki köpek yan yana.','yan yana iki kedi','karşı karşıya iki kedi','chill','none'),
(818,'tr','Klavyede yazması çok hızlı!','Okuması çok hızlı!','klavyede hızlı yazma','telefondan mesaj yazmak','slang','exclamation'),
(819,'tr','Güzel şemsiye. Bana da yer var mı?','Güzel araba. Bana da yer var mı?','şemsiyeyi paylaşmak','plajda bir şemsiye','flirt','banter'),
(821,'tr','Eve dönüş: iç çamaşırı saati!','Eve dönüş: pijama saati!','iç çamaşırına kadar soyunmak','yeni iç çamaşırı almak','slang','exclamation'),
(823,'tr','Ekran rakamları gösteriyor.','Ekran hava durumunu gösteriyor.','ekranı işaret etmek','ekranı silmek','business','none'),
(825,'tr','Köpek de manzaraya bayılıyor.','Kedi de manzaraya bayılıyor.','kayalık zirve manzarası','deniz manzarası','low_iq','guessing'),
(826,'tr','Ofiste film çekiyorlar.','Ormanda film çekiyorlar.','kamera dolly''siyle çekim yapmak','bir düğünü çekmek','chill','none'),
(827,'tr','Burada bir sürü hayvan var.','Burada iki hayvan var.','masal kitabında hayvanlar','gerçek bir hayvanat bahçesinde hayvanlar','chill','none'),
(828,'tr','Sıcak haber mi? Kadın şaşırmış görünüyor.','Sıcak haber mi? Adam şaşırmış görünüyor.','kafede şaşırmış','kapıda şaşırmış','gossip','guessing'),
(830,'tr','Değişiklikleri açıklıyor.','Menüyü açıklıyor.','uygulama tasarımını açıklamak','bir matematik problemini açıklamak','business','none'),
(831,'tr','Bir konuşma yapıyor.','Bir konser veriyor.','kürsüde bir konuşma','düğünde bir konuşma','business','none'),
(832,'tr','Bavulu boşaltıyor: dünyanın en uzun atkısı çıkıyor.','Bavulu boşaltıyor: dünyanın en uzun çorabı çıkıyor.','bavulu boşaltmak','alışveriş poşetlerini boşaltmak','low_iq','exaggeration'),
(833,'tr','Bavul boşaltma: deniz kabuğu sağ salim!','Bavul boşaltma: kupa sağ salim!','yolculuktan sonra bavul boşaltma','yeni telefonu kutusundan çıkarmak','dramatic','exclamation'),
(834,'tr','Ev sahibesi onlardan bıktı.','Garson onlardan bıktı.','misafirlere servis yapan ev sahibesi','bir hostes','gossip','guessing'),
(835,'tr','Sahte tesisatçı sırılsıklam oldu!','Sahte tesisatçı zengin oldu!','lavabonun başında tesisatçı','çatıda bir tesisatçı','dramatic','exclamation'),
(836,'tr','Adam çok hazırlıklı. Fazla hazırlıklı.','Kadın çok hazırlıklı. Fazla hazırlıklı.','hazırlıklı bir öğrenci','hazır bir yemek','ironic','exaggeration'),
(837,'tr','Bu taksi her ara sokağa sığar.','Bu otobüs her ara sokağa sığar.','ara sokakta bir taksi','havalimanında bir taksi','ironic','exaggeration'),
(838,'tr','Pilot kendini yıldız sanıyor.','Aşçı kendini yıldız sanıyor.','ceketli bir pilot','uçakta bir pilot','gossip','guessing'),
(839,'tr','Masasını uzatıyor!','Yatağını uzatıyor!','yemek masasını uzatmak','vizeyi uzatmak','dramatic','exclamation'),
(841,'tr','Buzu eritti. Şimdi ne olacak?','Suyu dondurdu. Şimdi ne olacak?','buz küplerini eritmek','çikolata eritmek','ironic','guessing'),
(842,'tr','Bebek her harfi istiyor.','Bebek her bisküviyi istiyor.','harflerle oynayan bebek','yemekle oynayan bebek','gossip','guessing'),
(843,'tr','Daha yüksek! Sepet yukarı çıkıyor!','Daha yüksek! Kova yukarı çıkıyor!','sepeti yukarı çekmek','tekneyi yukarı çekmek','dramatic','exclamation'),
(844,'tr','Ne kocaman yeşil bir vadi!','Ne kocaman yeşil bir çöl!','aşağıda yeşil bir vadi','kar altında bir vadi','dramatic','exclamation'),
(845,'tr','Bir kaybolma daha! Sağ ol, deniz.','Bir kaybolma daha! Sağ ol, köpek.','bir çizimin kaybolması','bir geminin kaybolması','ironic','blaming_someone'),
(847,'tr','Zaferleri çok net.','Yenilgileri çok net.','tekne yarışında zafer','satranç maçında zafer','chill','none'),
(848,'tr','Sirke mi? Yüzü hayır diyor!','Bal mı? Yüzü hayır diyor!','bir damla sirke','sirkeyle temizlik yapmak','slang','exclamation'),
(849,'tr','Vizesini aldı!','Vizesini kaybetti!','pasaportta bir vize','tatil için vize','dramatic','exclamation'),
(850,'tr','Yanardağ tütüyor. Kimse panik yapmasın.','Baca tütüyor. Kimse panik yapmasın.','tüten bir yanardağ','deniz altında bir yanardağ','ironic','understatement'),
(851,'tr','Bekliyor. Bekliyor da bekliyor.','Dans ediyor. Dans ediyor da dans ediyor.','otobüs beklemek','taksi beklemek','low_iq','exaggeration'),
(852,'tr','Garson çok hızlı!','Garson çok yavaş!','tabaklı bir garson','menülü bir garson','slang','exclamation'),
(853,'tr','Parkta yürüyor.','Parkta koşuyor.','göl kenarında yürümek','köpeği yürüyüşe çıkarmak','chill','none'),
(855,'tr','Deniz kenarında yürüyüş yapıyorlar.','Deniz kenarında koşu yapıyorlar.','deniz kenarında yürüyüş','dağlarda yürüyüş','chill','none'),
(857,'tr','Cüzdanını buldu, karşılığında çiçek aldı.','Cüzdanını buldu, karşılığında pasta aldı.','kayıp bir cüzdanı geri vermek','kayıp bir cüzdanı çalmak','gossip','none'),
(859,'tr','Gardırop ona saldırdı!','Buzdolabı ona saldırdı!','montlarla dolu gardırop','ayakkabıyla dolu gardırop','dramatic','blaming_someone'),
(860,'tr','Arabanın "biraz" yıkamaya ihtiyacı vardı.','Bisikletin "biraz" yıkamaya ihtiyacı vardı.','çamurlu bir arabayı yıkama','çamurlu bir köpeği yıkama','ironic','understatement'),
(861,'tr','Kol saati diyor ki: geç kaldın!','Telefonu diyor ki: geç kaldın!','kol saatine bakmak','kol saati almak','dramatic','exclamation'),
(862,'tr','TV izleme keyfi patlamış mısır ister.','TV izleme keyfi pizza ister.','TV izleme gecesi','kuş izleme gecesi','chill','cliche'),
(863,'tr','Matarası metal.','Matarası plastik.','matarayı doldurmak','yatakta bir matara','chill','none'),
(864,'tr','Bu su aşırı berrak.','Bu süt aşırı berrak.','şişede berrak su','plastik bardakta su','slang','exaggeration'),
(866,'tr','Şelalede gökkuşağı!','Gölde gökkuşağı!','İzlanda''da yüksek bir şelale','bahçede bir şelale','dramatic','exclamation'),
(867,'tr','Fesleğen sulamadan hoşlanıyor.','Gül sulamadan hoşlanıyor.','domatesleri sulamak','çimleri sulamak','chill','guessing'),
(868,'tr','Minicik bir dalga sadece.','Minicik bir köpekbalığı sadece.','yüzücülere çarpan dalga','kumsalda küçük dalgalar','ironic','understatement'),
(869,'tr','Bir ağırlık taşıyor.','Bir kutu taşıyor.','ağır, yuvarlak bir ağırlık','hızla kilo vermek','chill','none'),
(870,'tr','Güneş batıdan batar.','Güneş doğudan batar.','güneşin batıya inişini izlemek','gece batıya gitmek','chill','none'),
(871,'tr','Tekerlekli sandalyesinden sayı attı!','Tekerlekli sandalyesinden sayıyı kaçırdı!','sahada spor tekerlekli sandalyesi','hastanede bir tekerlekli sandalye','dramatic','exclamation'),
(872,'tr','Sonunda ıslık çalmayı başardı!','Sonunda şarkı söylemeyi başardı!','bahçe masasında ıslık çalma','futbol maçında ıslık çalma','dramatic','exclamation'),
(873,'tr','Eşi krep çevirebiliyor!','Eşi burger çevirebiliyor!','krep çeviren bir eş','kek pişiren bir eş','flirt','exclamation'),
(874,'tr','Pembe peruk ona çok yakışmış.','Pembe şapka ona çok yakışmış.','pembe peruk takmak','pembe peruğu taramak','flirt','none'),
(875,'tr','Rüzgâr atkısını çaldı!','Rüzgâr şapkasını çaldı!','rüzgârda bir atkı','karı savuran rüzgâr','dramatic','blaming_someone'),
(876,'tr','Gün batımında kırmızı şarap? Klas hareket.','Gün batımında soğuk bira? Klas hareket.','bir kadeh kırmızı şarap','bir şişe beyaz şarap','flirt','cliche'),
(877,'tr','Çamurlu kazanan? Efsane!','Tertemiz kazanan? Efsane!','çamur koşusunun kazananı','yüzme yarışının kazananı','slang','none'),
(878,'tr','Kızaklarla kış eğlencesi!','Kayaklarla kış eğlencesi!','kızaklarla bir kış günü','evde bir kış günü','slang','exclamation'),
(879,'tr','Kurt uluyor!','Kurt uyuyor!','karda bir kurt','kumsalda bir kurt','dramatic','exclamation'),
(880,'tr','Kuzu kendi yününü giyiyor!','Kuzu yün bere takıyor!','bir yumak yün','yün bir battaniye','dramatic','exaggeration'),
(882,'tr','Köpek onun antrenman koçu.','Kedi onun antrenman koçu.','tam bir antrenman','kumsalda antrenman','low_iq','exaggeration'),
(884,'tr','Ona dünyayı gösteriyor.','Ona haritayı gösteriyor.','şehir ışıklarından bir dünya','bir dünya haritası','chill','exaggeration'),
(885,'tr','Solucan toprağın altına iniyor.','Solucan ağaca çıkıyor.','toprakta bir solucan','oltada bir solucan','chill','none'),
(886,'tr','Büyükanne kırışıklıklarını hak etti.','Kız kırışıklıklarını hak etti.','yüzünde derin kırışıklıklar','gömlekte kırışıklıklar','chill','none'),
(887,'tr','Günlüğüne yazıyor.','Laptopuna yazıyor.','günlüğe yazmak','duvara yazmak','chill','none'),
(888,'tr','Esnemek bulaşıcıdır, köpekler için bile.','Gülmek bulaşıcıdır, köpekler için bile.','mutfakta esnemek','arabada esnemek','nerd','cliche'),
(889,'tr','Yoğurdu akmıyor!','Balı akmıyor!','bir kavanoz koyu yoğurt','kavanozdan yoğurt içmek','dramatic','exclamation'),
(891,'tr','Eyvah, o araba pahalı!','Eyvah, o bisiklet pahalı!','pahalı bir araba süsü','pahalı bir araba yıkama','slang','exclamation'),
(892,'tr','Üstündeki deniz suyunu duruluyor.','Üstündeki boyayı duruluyor.','deniz suyunu durulamak','bulaşıkları durulamak','chill','none'),
(893,'tr','Fermuar çekildi, kar için hazır.','Fermuar çekildi, güneş için hazır.','ceketin fermuarını çekmek','bavulun fermuarını çekmek','chill','none'),
(894,'tr','Fermuar sıkıştı!','Kayak sıkıştı!','sıkışmış ceket fermuarı','çadırdaki fermuar','dramatic','exclamation'),
(895,'tr','Büyük sıkışıklık. Kaza mı var acaba?','Büyük parti. Kaza mı var acaba?','otoyolda kaza','mutfakta kaza','dramatic','guessing'),
(898,'tr','Kadın oyuncu fırıl fırıl dönüyor.','Kadın oyuncu mışıl mışıl uyuyor.','sette bir kadın oyuncu','afişte bir kadın oyuncu','chill','none'),
(899,'tr','Güneşli bir öğleden sonra.','Karlı bir öğleden sonra.','parkta bir öğleden sonra','plajda bir öğleden sonra','chill','none'),
(900,'tr','Temsilci telefonda.','Temsilci otobüste.','telefonda bir temsilci','bir seyahat acentesi ofisi','business','none'),
(901,'tr','Kollarını açmış, temiz havayı içine çekiyor.','Kollarını açmış, şehir havasını içine çekiyor.','temiz dağ havası','şehirde temiz hava','chill','none'),
(902,'tr','Uçağa el sallıyor!','Trene el sallıyor!','alçaktan geçen bir uçak','kâğıttan bir uçak','dramatic','exclamation'),
(904,'tr','Polen alerjisi var.','Toz alerjisi var.','polene alerji','kedilere alerji','chill','none'),
(905,'tr','Bir kedi ara sokaktan geçiyor.','Bir köpek ara sokaktan geçiyor.','dar, parke taşlı ara sokak','dükkânlarla dolu ara sokak','chill','none'),
(907,'tr','Kimse var mı? Sadece güvercinler.','Kimse var mı? Sadece kediler.','istasyonda hiç kimse','partide hiç kimse','chill','understatement'),
(909,'tr','Adam, evde herhangi biri var mı diye soruyor.','Kadın, evde herhangi biri var mı diye soruyor.','evde herhangi biri var mı','herhangi biri aç mı','chill','none'),
(911,'tr','Aydınlık, güneşli bir daire.','Karanlık, kasvetli bir daire.','aydınlık modern bir daire','aydınlık modern bir ofis','chill','none'),
(914,'tr','Bu koltuğa bayılıyor!','Bu kanepeye bayılıyor!','koltuğa kendini bırakmak','havuza kendini bırakmak','dramatic','exclamation'),
(916,'tr','Bankamatik kullanıyor.','Telefon kullanıyor.','yağmurda bir bankamatik','dükkânda bir bankamatik','chill','none'),
(917,'tr','Tavan arası ıvır zıvır dolu.','Tavan arası su dolu.','tozlu eski bir tavan arası','aydınlık yeni bir tavan arası','slang','none'),
(918,'tr','Seyirciler alkışlıyor.','Seyirciler gidiyor.','alkışlayan seyirciler','televizyon seyircisi','business','none'),
(919,'tr','Teyzesi tam bir eğlence.','Dayısı tam bir eğlence.','teyzesiyle dans etmek','teyzesiyle alışveriş yapmak','slang','none'),
(920,'tr','Avusturya''da salıncakta sallanmak? Hayalim!','Avusturya''da kayak yapmak? Hayalim!','Avusturya''da salıncakta sallanmak','Avusturya''da kayak yapmak','slang','cliche'),
(921,'tr','Avusturya usulü pasta servis ediyor.','Avusturya usulü bira servis ediyor.','bir Avusturya kahvehanesi','bir Avusturya birahanesi','business','none'),
(925,'tr','Çantası bagaj alım bandında.','Çantası check-in''de.','bagaj alım bandında bir çanta','güvenlikte bir çanta','chill','none'),
(926,'tr','Fırıncının ekmeği hazır!','Fırıncının pizzası hazır!','fırının başında bir fırıncı','kasada bir fırıncı','dramatic','exclamation'),
(927,'tr','Balkonda halı silkeliyor.','Balkonda havlu silkeliyor.','balkondan sarkan halı','balkonda bir bitki','chill','none'),
(929,'tr','Bandaj sarıyor.','Hediye paketliyor.','beyaz bandaj sarmak','beyaz atkı dolamak','chill','none'),
(933,'tr','O banyoda.','O mutfakta.','banyoda yıkanmak','banyoyu temizlemek','chill','none'),
(934,'tr','Şlap! Küvette keyif yapıyor.','Şlap! Havuzda keyif yapıyor.','küvette su sıçratmak','su birikintisinde şapırdamak','slang','exclamation'),
(938,'tr','Yatağı topluyor.','Pasta yapıyor.','yatağı toplamak','yatağa girmek','chill','none'),
(939,'tr','Yastıklar havada! Yatak odası partisi!','Yastıklar havada! Mutfak partisi!','aydınlık, dağınık bir yatak odası','aydınlık, dağınık bir mutfak','slang','exclamation'),
(941,'tr','Güvercinler bankına saldırdı!','Ördekler bankına saldırdı!','bankta oturan bir kadın','istasyonda bir bank','dramatic','exaggeration'),
(942,'tr','Bisiklete biniyor.','Scooter''a biniyor.','sonbaharda bir bisiklet','karda bir bisiklet','chill','none'),
(943,'tr','Reklam panosuna afiş yapıştırıyor.','Reklam panosunu boyuyor.','boş, dev bir reklam panosu','otobüs üstünde reklam panosu','chill','none'),
(944,'tr','Dürbününü kullanmayı unuttu.','Teleskobunu kullanmayı unuttu.','göğsünde siyah dürbün','masada siyah dürbün','ironic','guessing'),
(947,'tr','Burnu kanıyor.','Dizi kanıyor.','kanayan bir burun','kanayan bir diz','chill','none'),
(948,'tr','Karıştırıcıya orman meyvesi? Nefis!','Karıştırıcıya kiraz? Nefis!','karıştırıcıyı doldurmak','karıştırıcıyı temizlemek','slang','none'),
(949,'tr','Ay, topukta su toplaması!','Ay, ayak parmağında su toplaması!','topukta su toplaması','elde su toplaması','dramatic','exclamation'),
(950,'tr','Kan veriyor.','Konuşma yapıyor.','bir torba bağışlanmış kan','beyaz gömlekte kan','chill','none'),
(952,'tr','Ahşap bir kayıkta kürek çekiyor.','Şişme bir kayıkta kürek çekiyor.','ahşap kayıkla kürek çekmek','limanda bir kayık','chill','none'),
(953,'tr','Sınır araba için açık.','Sınır otobüs için açık.','sınır kontrol noktası','çiçekli bir bahçe sınırı','business','none'),
(954,'tr','Patron konuşma yapıyor.','Patron hediye veriyor.','toplantıda bir patron','partide bir patron','business','none'),
(956,'tr','Bir beyin modelini inceliyor.','Bir kalp modelini inceliyor.','bir beyin maketi','bir beyin resmi','chill','none'),
(957,'tr','Dalda bir kızılgerdan oturuyor.','Dalda bir baykuş oturuyor.','dalda bir salıncak','parkta bir salıncak','chill','none'),
(958,'tr','Gelin hazır!','Damat hazır!','beyaz güllü bir gelin','kırmızı güllü bir gelin','dramatic','exclamation'),
(959,'tr','Köprünün altından yürüyor.','Köprünün üstünden yürüyor.','devasa bir asma köprü','küçük ahşap bir köprü','chill','none'),
(960,'tr','Süpürgeyle süpürüyor.','Tırmıkla süpürüyor.','saman bir süpürge','cadı süpürgesi','chill','none'),
(961,'tr','Büyük erkek kardeş yine kazanıyor.','Büyük kız kardeş yine kazanıyor.','kafa kilidinde bir erkek kardeş','erkek kardeşle boks yapmak','slang','cliche'),
(962,'tr','Dizinde kocaman bir çürük var.','Kolunda kocaman bir çürük var.','dizde bir çürük','gözde bir çürük','chill','none'),
(963,'tr','İnşaatçı duvar örüyor.','İnşaatçı çatı yapıyor.','malalı bir inşaatçı','çekiçli bir inşaatçı','chill','none'),
(965,'tr','İnşaatçının malası dolu.','İnşaatçının kovası dolu.','harç dolu bir mala','toprak dolu bir mala','chill','none'),
(967,'tr','Bu otobüs şoförü fazla mutlu.','Bu taksi şoförü fazla mutlu.','gülümseyen bir otobüs şoförü','grevdeki bir otobüs şoförü','ironic','exaggeration'),
(970,'tr','Kasap dana eti kesiyor.','Kasap ekmek kesiyor.','dana eti dilimleyen kasap','balık satan bir kasap','chill','none'),
(973,'tr','Kaktüse bir kuş kondu.','Kaktüse bir arı kondu.','kaktüsün üstünde bir kuş','saksıda bir kaktüs','chill','none'),
(974,'tr','Kalabalık, küçük bir kafe.','Boş, küçük bir kafe.','güneşli, şirin bir kafe','kapalı bir kafe','chill','none'),
(977,'tr','Fotoğraf makinesini doğrultuyor.','Telefonunu doğrultuyor.','eski model bir fotoğraf makinesi','bir güvenlik kamerası','chill','none'),
(980,'tr','Kaptan dümende.','Kaptan barda.','dümende bir kaptan','futbol takımı kaptanı','chill','none'),
(983,'tr','Kasiyer bir kavanozu okutuyor.','Kasiyer bir konserveyi okutuyor.','kasada bir kasiyer','bankada bir kasiyer','chill','none'),
(984,'tr','Alçı hâlâ ıslak.','Alçı kupkuru.','yeni takılmış kol alçısı','yeni takılmış bacak alçısı','nerd','none'),
(986,'tr','Bir tırtıl öğle yemeği yiyor.','Bir salyangoz öğle yemeği yiyor.','yaprak yiyen bir tırtıl','çiçekte bir tırtıl','chill','understatement'),
(989,'tr','Bavulunun check-in''ini yapıyor.','Köpeğinin check-in''ini yapıyor.','havalimanında check-in yapmak','otelde check-in yapmak','business','none'),
(990,'tr','Şef cımbız kullanıyor.','Şef kaşık kullanıyor.','tabak süsleyen bir şef','çorba tadan bir şef','chill','none'),
(991,'tr','Göğsü çıplak.','Göğsü örtülü.','çıplak bir göğüs','bir hazine sandığı','chill','none'),
(995,'tr','Sınıf arkadaşı bir sır biliyor.','Öğretmeni bir sır biliyor.','sınıf arkadaşına fısıldamak','tahtada bir sınıf arkadaşı','chill','guessing'),
(996,'tr','Eller ıslak kile şekil veriyor.','Eller ıslak kuma şekil veriyor.','kilden çömlek şekillendirmek','kil çömlek boyamak','chill','none'),
(998,'tr','Kâğıtlar uçuşuyor, memur hâlâ mühür basıyor.','Kâğıtlar uçuşuyor, memur hâlâ uyuyor.','evrak mühürleyen memur','otel resepsiyon görevlisi','dramatic','exaggeration'),
(1000,'tr','İklim ısınıyor.','İklim soğuyor.','değişen bir dağ iklimi','tropik bir ada iklimi','nerd','none'),
(1001,'tr','Klinik sana hazır.','Okul sana hazır.','aydınlık bir klinik bekleme salonu','köpekler için bir klinik','business','none'),
(1003,'tr','Bugün tek bir bulut var.','Bugün iki bulut var.','kocaman beyaz tek bulut','gri bir yağmur bulutu','chill','understatement'),
(1004,'tr','Antrenör fısıldamıyor.','Antrenör bağırmıyor.','düdüklü bir antrenör','turistlerle dolu otobüs','chill','understatement'),
(1006,'tr','Kahve makinesi çok yavaş.','Ekmek kızartma makinesi çok yavaş.','damlatan bir kahve makinesi','yeni bir kahve makinesi','chill','blaming_someone'),
(1007,'tr','İki iş arkadaşı konuşuyor.','İki iş arkadaşı yemek yiyor.','beyaz tahta başında iş arkadaşları','partide iş arkadaşları','chill','none'),
(1008,'tr','Topluluk fidan dikiyor.','Topluluk boya yapıyor.','bir topluluk bahçesi','bir oyuncu topluluğu','business','none'),
(1009,'tr','Pusula benden akıllı.','Eski telefon benden akıllı.','elde pirinç bir pusula','elde pirinç bir saat','low_iq','exaggeration'),
(1010,'tr','İşine yarayacak bir bağlantı kurdu.','İşine yarayacak bir telefon görüşmesi yaptı.','yeni bir iş bağlantısı','rehberinde bir bağlantı','business','none'),
(1011,'tr','Bu aşçının iki kaşığa ihtiyacı var!','Bu aşçının iki tencereye ihtiyacı var!','yemeği tadan bir aşçı','tarif okuyan bir aşçı','dramatic','exclamation'),
(1012,'tr','Öyle bir öksürüyor ki!','Öyle bir gülüyor ki!','dirseğe öksürmek','mendile öksürmek','dramatic','exclamation'),
(1013,'tr','İki kuzen katıla katıla gülüyor.','İki kuzen hüngür hüngür ağlıyor.','çimenlerde iki kuzen','masada iki kuzen','chill','none'),
(1015,'tr','Baldırını tutuyor.','Başını tutuyor.','baldırını tutmak','bir buzağıyı beslemek','chill','none'),
(1017,'tr','Yaya geçidinde bir kadın var.','Yaya geçidinde bir köpek var.','yaya geçidinden karşıya geçmek','yağmurda bir yaya geçidi','chill','none'),
(1022,'tr','Bu minder kavgayı kaybetti.','Bu kanepe kavgayı kaybetti.','minderi kabartmak','mindere oturmak','ironic','exaggeration'),
(1025,'tr','O bisikletçi aşırı cesur.','O koşucu aşırı cesur.','virajı hızla alan bisikletçi','şehirde bir bisikletçi','slang','none'),
(1026,'tr','Çek birası mı? Evet, lütfen!','Çek şarabı mı? Evet, lütfen!','bir Çek birahanesi','bir Çek şarap mahzeni','slang','exclamation'),
(1028,'tr','Kadın şu an Çekya''da.','Adam şu an Çekya''da.','Çekya''da gün batımı','Çekya''da kar','chill','none'),
(1030,'tr','Kız evladından çiçekler!','Oğlundan çiçekler!','kız evlattan çiçekler','kız evlada çiçekler','dramatic','exclamation'),
(1033,'tr','Çölün sonu yok!','Ormanın sonu yok!','çölde develer','çölde kar','dramatic','exaggeration'),
(1035,'tr','Varış noktasını göremiyor.','Trafiği göremiyor.','varış noktasından çok uzakta','varış noktasına ulaşmak','ironic','guessing'),
(1037,'tr','Ekstra deterjan, ekstra köpük.','Ekstra deterjan, sıfır köpük.','bulaşık deterjanı dökmek','çamaşır deterjanı','slang','cliche'),
(1040,'tr','Yakında boşanmış olacaklar.','Yakında evli olacaklar.','boşanmak üzere','evlenmek üzere','gossip','guessing'),
(1041,'tr','Baş dönmesi kadını fena vurdu.','Baş dönmesi adamı fena vurdu.','ani bir baş dönmesi','teknede baş dönmesi','dramatic','none'),
(1043,'tr','Yunusun çizdiği yay on puan alır!','Fokun çizdiği yay on puan alır!','yunusun sıçrayış yayı','gökkuşağının yayı','slang','exaggeration'),
(1048,'tr','O dambıl aşırı ağır.','O dambıl aşırı hafif.','ağır dambılla çalışmak','yerde bir dambıl','slang','exaggeration'),
(1050,'tr','Bisiklette laleler? Tam Hollandalı!','Bisiklette peynir? Tam Hollandalı!','uzun, dar Hollanda evleri','bir Hollanda peynir pazarı','slang','cliche'),
(1057,'tr','İşveren el sıkışıyor.','İşveren el yıkıyor.','güler yüzlü bir işveren','sinirli bir işveren','business','none'),
(1064,'tr','Herkes tezahürat yapıyor!','Herkes uyuyor!','kolları havada herkes','yere oturmuş herkes','dramatic','exclamation'),
(1067,'tr','Gerçek bir saat uzmanı.','Gerçek bir şarap uzmanı.','bir saat uzmanı','televizyonda bir uzman','chill','none'),
(1069,'tr','Bu göz yeşil-kahverengi.','Bu göz parlak mavi.','açık bir göz','kapalı bir göz','chill','none'),
(1070,'tr','Gülen bir yüzü var.','Ağlayan bir yüzü var.','gülen bir yüz','uyuyan bir yüz','chill','none'),
(1071,'tr','Çiftçi geç saate kadar çalışıyor.','Çiftçi geç saate kadar uyuyor.','yabalı bir çiftçi','inekli bir çiftçi','chill','guessing'),
(1072,'tr','Bu iki adam çok mutlu.','Bu iki adam çok sinirli.','el sıkışan iki adam','el sallayan bir okul arkadaşı','slang','none'),
(1073,'tr','Kadın tırmanıcı uçuyor!','Erkek tırmanıcı uçuyor!','kadın bir tırmanıcı','kadın bir koşucu','dramatic','exaggeration'),
(1074,'tr','Ateşine bakıyor.','Telefonuna bakıyor.','ateşini ölçmek','nabzını ölçmek','chill','none'),
(1076,'tr','Bir parmak bir damlaya dokunuyor.','Bir parmak bir arıya dokunuyor.','damlaya dokunan parmak','arının yanında bir parmak','chill','none'),
(1078,'tr','İtfaiyeci görev başında.','İtfaiyeci tatilde.','hortumlu bir itfaiyeci','kedili bir itfaiyeci','business','none'),
(1079,'tr','İlk yardım yapıyor.','Yol tarif ediyor.','açık bir ilk yardım çantası','bir ilk yardım kursu','chill','none'),
(1082,'tr','Balıkçı bir sürü balık tuttu!','Balıkçı hiçbir şey tutamadı!','ağlı bir balıkçı','oltalı bir balıkçı','slang','exclamation'),
(1084,'tr','Uçuş şimdi başlıyor.','Uçuş şimdi bitiyor.','kalkıştan sonra bir uçuş','inişe geçen bir uçuş','business','none'),
(1085,'tr','Ahşap zemini paspaslıyor.','Taş zemini paspaslıyor.','geniş ahşap bir zemin','zemin kat','business','none'),
(1088,'tr','Çimenlerde çıplak bir ayak.','Karda çıplak bir ayak.','çimende çıplak ayak','çorap giymiş bir ayak','chill','none'),
(1093,'tr','Bacakta bir kırık var.','Kolda bir kırık var.','bacak kemiğinde kırık','bilek kemiğinde kırık','nerd','none'),
(1096,'tr','Beyaz bir galeride.','Beyaz bir mutfakta.','galeride dolaşmak','bir dükkânda dolaşmak','chill','none'),
(1097,'tr','Garajı kapatıyor.','Pencereyi kapatıyor.','garaj kapısını kapatmak','garaj kapısını açmak','chill','none'),
(1100,'tr','Bahçıvan gülleri kesiyor.','Bahçıvan çimleri kesiyor.','güllü bir bahçıvan','çim makineli bir bahçıvan','chill','none'),
(1104,'tr','Ne centilmen ama!','Ne hanımefendi ama!','şapkasını kaldıran centilmen','kapıyı kapatan bir centilmen','flirt','exclamation'),
(1107,'tr','Kız arkadaşına sarılıyor.','Kız arkadaşını taşıyor.','kız arkadaşına sarılmak','telefonda bir kız arkadaş','flirt','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
