begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(1110,'tr','Kız torundan öpücükler!','Erkek torundan öpücükler!','kız torunun öpücüğü','kız torunun çizimi','slang','exclamation'),
(1112,'tr','Büyükanne ekmek yapıyor.','Büyükanne çorba yapıyor.','büyükanneyle ekmek pişirmek','büyükanneyle örgü örmek','chill','none'),
(1115,'tr','Yunanistan''da dans mı? Tarzın güzel.','Yunanistan''da dalış mı? Tarzın güzel.','Yunanistan''da dans','Yunanistan''da yüzmek','flirt','none'),
(1116,'tr','Damat onu kucağında taşıyor.','Damat bir pasta taşıyor.','gelinini taşıyan damat','at tımarlayan damat','flirt','none'),
(1120,'tr','Bu adam anahtarlarını havaya atıyor, çok havalı.','Bu adam telefonunu havaya atıyor, çok havalı.','pizzalı bir adam','gitarlı bir adam','slang','none'),
(1123,'tr','Onun koridoru resmen dans pisti!','Onun mutfağı resmen dans pisti!','koridorda dans etmek','koridorda koşmak','slang','exclamation'),
(1125,'tr','Tekneler limanda dinleniyor.','Tekneler kumsalda dinleniyor.','limandaki tekneler','kanaldaki tekneler','chill','none'),
(1126,'tr','İş ona baş ağrısı yaptı.','Müzik ona baş ağrısı yaptı.','gece baş ağrısı','güneşte baş ağrısı','chill','blaming_someone'),
(1129,'tr','Doktor bir kalp tutuyor!','Doktor bir beyin tutuyor!','bir kalp maketi','bir beyin maketi','dramatic','exclamation'),
(1131,'tr','İki topuk da yerden kalkmış.','İki topuk da yerde.','iki topuğu kaldırmak','yüksek topuklu giymek','chill','none'),
(1133,'tr','Yardımcının yanında çantası var.','Yardımcının yanında köpeği var.','çantasıyla bir yardımcı','mutfakta bir yardımcı','chill','none'),
(1134,'tr','Bil bakalım tepede kim öğle yemeği yiyor? Koyunlar.','Bil bakalım tepede kim öğle yemeği yiyor? İnekler.','tepede bir ağaç','tepede bir ev','gossip','guessing'),
(1135,'tr','Eli kalçasında.','Eli başında.','kalçasında bir el','omzunda bir el','chill','none'),
(1136,'tr','Sonunda evde!','Sonunda işte!','çantayla eve gelmek','çantayla evden çıkmak','dramatic','exclamation'),
(1138,'tr','Hastanede sakin bir gün.','Havalimanında sakin bir gün.','aydınlık bir hastane koridoru','dolu bir hastane koğuşu','gossip','guessing'),
(1139,'tr','Ev sahibi kadeh kaldırıyor.','Ev sahibi pasta yapıyor.','kadeh kaldıran ev sahibi','bir TV programı sunucusu','business','none'),
(1141,'tr','Bir misafir otelden çıkıyor.','Bir misafir otele giriyor.','görkemli bir otelden çıkmak','deniz kenarında bir otel','business','none'),
(1143,'tr','Burada sadece tek bir insan var.','Burada sadece tek bir deve var.','çölde tek bir insan','bir insan kalabalığı','ironic','understatement'),
(1144,'tr','Avcı diz çökmüş.','Avcı koşuyor.','dürbünlü bir avcı','tüfekli bir avcı','chill','none'),
(1147,'tr','Dirseğinde enfeksiyon var.','Dizinde enfeksiyon var.','dirsekte bir enfeksiyon','gözde bir enfeksiyon','chill','none'),
(1148,'tr','Enjeksiyon hazır. Kaç!','Bandaj hazır. Kaç!','enjeksiyon için bir tepsi','yemeğe hazır bir tepsi','low_iq','exclamation'),
(1151,'tr','Ütüsü buhar çıkarıyor.','Su ısıtıcısı buhar çıkarıyor.','buhar çıkaran bir ütü','demir bir kapı','business','none'),
(1152,'tr','Bir ütü masası kuruluyor.','Bir şezlong kuruluyor.','ütü masası kurmak','ütü masasına oturmak','chill','none'),
(1154,'tr','Gazeteci cevap istiyor.','Doktor cevap istiyor.','ses kayıt cihazlı gazeteci','masa başında bir gazeteci','gossip','guessing'),
(1156,'tr','Bu cangılın patronu papağan.','Bu cangılın patronu maymun.','cangılda bir papağan','kafeste bir papağan','slang','exaggeration'),
(1158,'tr','Su ısıtıcısındaki su sıcakmış. Kimin aklına gelirdi?','Musluk suyu sıcakmış. Kimin aklına gelirdi?','su ısıtıcısından dökmek','ocakta bir su ısıtıcısı','low_iq','understatement'),
(1159,'tr','Buyurun, oda anahtarınız.','Buyurun, araba anahtarınız.','bir otel odası anahtarı','bir araba anahtarı','business','none'),
(1160,'tr','Mutfak çok iyi donanımlı.','Mutfak neredeyse boş.','aydınlık bir mutfak','karanlık bir mutfak','business','none'),
(1163,'tr','Hanımefendi beyaz eldiven giymiş.','Hanımefendi siyah eldiven giymiş.','merdivende bir hanımefendi','barda bir hanımefendi','chill','none'),
(1166,'tr','Büyük bir lambayı taşıyor.','Büyük bir bitkiyi taşıyor.','bir masa lambası','bir bahçe lambası','chill','none'),
(1167,'tr','Avukatın bir sürü kitabı var.','Avukatın bir sürü kedisi var.','dosyalı bir avukat','mahkeme salonunda bir avukat','chill','none'),
(1170,'tr','Kütüphaneci merdivenin üstünde.','Kütüphaneci masanın üstünde.','merdivende bir kütüphaneci','bilgisayar başında bir kütüphaneci','chill','none'),
(1173,'tr','Şimşek denize çarpıyor!','Şimşek bir ağaca çarpıyor!','denizin üstünde şimşek','şehrin üstünde şimşek','dramatic','exclamation'),
(1175,'tr','Patlamış mısır oturma odasının her yerinde uçuşuyor.','Patlamış mısır mutfağın her yerinde uçuşuyor.','oturma odasında arkadaşlar','bekleme salonunda arkadaşlar','slang','exaggeration'),
(1178,'tr','Kaybeden havlunun altında.','Kaybeden masanın altında.','maçı kaybeden','yarışı kaybeden','dramatic','none'),
(1179,'tr','Tek bir adam için fazla bagaj.','Tek bir kız için fazla bagaj.','bagaj dolu bir el arabası','araba tavanında bagaj','low_iq','exaggeration'),
(1180,'tr','Bagaj etiketi boş.','Bagaj etiketi kırmızı.','bagaj etiketi bağlamak','bagaj etiketini kesip çıkarmak','chill','none'),
(1182,'tr','Oda görevlisi yatağı yapıyor.','Oda görevlisi kahve yapıyor.','yatak yapan oda görevlisi','düğünde bir oda görevlisi','chill','none'),
(1183,'tr','Erkek bir sporcu kürek çekiyor.','Kadın bir sporcu kürek çekiyor.','erkek bir kürekçi','erkek bir yüzücü','chill','none'),
(1185,'tr','Yönetici talimat veriyor.','Yönetici hediye veriyor.','laptoplu bir yönetici','telefonlu bir yönetici','business','none'),
(1188,'tr','Yeni evliler ve şimdiden dans ediyorlar.','Yeni evliler ve şimdiden kavga ediyorlar.','dans eden evli bir çift','tartışan evli bir çift','chill','none'),
(1189,'tr','Bir yatak taşıyorlar.','Bir piyano taşıyorlar.','merdivenden çıkan bir yatak','yerde bir yatak','chill','none'),
(1193,'tr','Aç ağzını, ilaç geliyor.','Aç ağzını, dondurma geliyor.','kaşıkta sıvı ilaç','hap kutusunda ilaç','chill','cliche'),
(1195,'tr','Uçan bir Meksika tortillası!','Uçan bir Meksika tacosu!','bir Meksika sokak tezgâhı','bir Meksika restoranı','dramatic','exclamation'),
(1198,'tr','Manken podyumun hakimi.','Manken plajın hakimi.','podyumda bir manken','bir uçak maketi','slang','exaggeration'),
(1200,'tr','Bu güneşli sabaha bayılıyor.','Bu yağmurlu sabaha bayılıyor.','güneşli bir sabah','yağmurlu bir sabah','chill','guessing'),
(1202,'tr','Anne ve bebek: burun buruna.','Anne ve köpek: burun buruna.','bebeğini havaya kaldıran anne','bebeğini besleyen anne','chill','none'),
(1203,'tr','Motosikletinden kıvılcımlar çıkıyor!','Scooter''ından kıvılcımlar çıkıyor!','virajda bir motosiklet','garajda bir motosiklet','dramatic','exclamation'),
(1206,'tr','Çamur her yere uçuşuyor!','Kar her yere uçuşuyor!','derin çamurda bir ayakkabı','taze karda bir ayakkabı','dramatic','exclamation'),
(1208,'tr','Müzede bir dinozor!','Müzede bir balina!','müzede bir dinozor','bir modern sanat müzesi','dramatic','exclamation'),
(1211,'tr','Koca bir millet hep bir ağızdan şarkı söylüyor.','Koca bir millet hep birlikte dans ediyor.','birlikte şarkı söyleyen millet','kahve tutkunu bir millet','dramatic','cliche'),
(1213,'tr','Büyük dalgalar, büyük mide bulantısı.','Küçük dalgalar, büyük mide bulantısı.','dalgalı denizde mide bulantısı','ağır yemekten sonra mide bulantısı','dramatic','none'),
(1214,'tr','Boynunu esnetiyor.','Bacağını esnetiyor.','uzun, esnetilmiş bir boyun','boyunda bir atkı','chill','none'),
(1215,'tr','Komşular sohbet ediyor.','Komşular kavga ediyor.','bahçe çitinde komşular','gürültücü bir komşu','chill','none'),
(1216,'tr','Bisiklet, lale, yel değirmeni. Evet, Hollanda.','Araba, lale, yel değirmeni. Evet, Hollanda.','Hollanda''da laleler','Hollanda''da bir pazar','chill','cliche'),
(1218,'tr','Oyun parkında hiç kimse yok. Ürkütücü!','Oyun parkında çocuklar var. Ürkütücü!','salıncaklarda hiç kimse yok','plajda hiç kimse yok','dramatic','exclamation'),
(1219,'tr','Hiç kimse gelmedi. Süper parti.','Herkes geldi. Süper parti.','masada hiç kimse yok','kalabalık bir yemek masası','ironic','understatement'),
(1221,'tr','Subay selam veriyor.','Subay dans ediyor.','selam veren bir subay','araba süren bir subay','chill','none'),
(1225,'tr','Boyacı petrol mavisine bayılıyor.','Boyacı pembeye bayılıyor.','merdivende bir boyacı','şövale başında bir boyacı','chill','guessing'),
(1227,'tr','Ebeveyn modu: koşu.','Ebeveyn modu: uyku.','bisikletin yanında bir ebeveyn','bisiklet tamir eden ebeveyn','slang','cliche'),
(1232,'tr','Hasta nefes alıyor.','Hasta öğle yemeği yiyor.','derin nefes alan bir hasta','yatakta bir hasta','chill','none'),
(1233,'tr','Yayanın kahvesi var.','Yayanın köpeği var.','kahveli bir yaya','bir yaya köprüsü','chill','none'),
(1235,'tr','İnsanlar tezahürat yapıyor!','İnsanlar ağlıyor!','gece tezahürat yapan insanlar','stadyumda tezahürat yapan insanlar','dramatic','exclamation'),
(1237,'tr','Ne "kalabalık" bir yaya geçidi: tek kişi.','Ne "kalabalık" bir yaya geçidi: tek köpek.','yaya geçidinde tek kişi','otobüste tek kişi','ironic','understatement'),
(1238,'tr','Eczanede bir sürü kavanoz var.','Eczanede bir sürü oyuncak var.','şirin, eski bir eczane','kızıl haçlı bir eczane','chill','none'),
(1241,'tr','Fotoğrafçı ıslak sokakta yatıyor!','Fotoğrafçı ıslak sokakta ayakta duruyor!','yerde bir fotoğrafçı','stüdyoda bir fotoğrafçı','dramatic','exclamation'),
(1242,'tr','Bir tablo asıyor.','Bir ayna asıyor.','duvarda bir tablo','telefonunda bir tablo','chill','none'),
(1248,'tr','Gezegenin halkaları var!','Gezegenin hiç halkası yok!','halkalı bir gezegen','haritada bir gezegen','dramatic','exclamation'),
(1254,'tr','Tesisatçı bir boruyu tamir ediyor.','Tesisatçı bir kapıyı tamir ediyor.','lavabonun altında bir tesisatçı','çatıda bir tesisatçı','chill','none'),
(1255,'tr','Polonya''da kış var.','Polonya''da yaz var.','Polonya''da karlı bir meydan','Polonya''da kumlu bir plaj','chill','none'),
(1256,'tr','Polis memuru gülümsüyor.','Polis memuru ağlıyor.','işaret eden bir polis memuru','koşan bir polis memuru','chill','none'),
(1258,'tr','Polonya mantısı yapmış.','Polonya sucuğu yapmış.','sıra sıra Polonya mantısı','ızgarada Polonya sucuğu','chill','none'),
(1260,'tr','Portekiz''de koşuyor.','Portekiz''de bisiklet sürüyor.','Portekiz''de koşu','Portekiz''de tramvaya binmek','chill','none'),
(1263,'tr','Postacı mektup dağıtıyor.','Postacı pizza dağıtıyor.','kapıda bir postacı','kamyonette bir postacı','business','none'),
(1266,'tr','Başkan konuşuyor, flaşlar patlıyor!','Başkan şarkı söylüyor, flaşlar patlıyor!','konuşma yapan bir başkan','tokalaşan bir başkan','dramatic','exclamation'),
(1267,'tr','Çok profesyonel görünüyor.','Çok uykulu görünüyor.','profesyonel bir görünüm','profesyonel bir sporcu','flirt','none'),
(1268,'tr','Profesör ders anlatıyor.','Profesör uyuyor.','ders anlatan bir profesör','profesörün odası','chill','none'),
(1270,'tr','Su birikintisinde tepiniyor.','Karda tepiniyor.','su birikintisine zıplamak','dökülmüş süt birikintisi','chill','none'),
(1274,'tr','Tepelerin üstünde kocaman bir gökkuşağı.','Denizin üstünde kocaman bir gökkuşağı.','yeşil tepelerde gökkuşağı','şehrin üstünde gökkuşağı','chill','none'),
(1278,'tr','Resepsiyonda pirinç bir zil var.','Resepsiyonda pirinç bir lamba var.','resepsiyonda bir anahtar','bir düğün resepsiyonu','business','none'),
(1286,'tr','Bir işçi çatıyı temizliyor.','Bir işçi çatıyı boyuyor.','kiremitli bir ev çatısı','camlı bir istasyon çatısı','business','none'),
(1287,'tr','Boş bir oda mı? Dans zamanı!','Boş bir dükkân mı? Dans zamanı!','boş, güneşli bir oda','boş, güneşli bir plaj','slang','exclamation'),
(1290,'tr','Bu güzergâhta ne çok viraj var!','Bu güzergâhta ne çok kamyon var!','dağa çıkan bir güzergâh','sahil boyunca bir güzergâh','dramatic','exclamation'),
(1299,'tr','Taramaya bayılıyor, belli ki.','Taramadan nefret ediyor, belli ki.','taramaya giren bir hasta','havalimanında tarama','ironic','guessing'),
(1303,'tr','Ne şık bir scooter turu!','Ne şık bir bisiklet turu!','İtalya''da bir scooter','plajda bir scooter','flirt','exaggeration'),
(1304,'tr','Sekreter çok yoğun!','Sekreter çok sıkılmış!','yoğun bir sekreter','tatildeki bir sekreter','dramatic','exclamation'),
(1305,'tr','Bir fasulye tohumu düşüyor.','Küçük bir taş düşüyor.','fasulye tohumu ekmek','tohum yiyen bir kuş','chill','none'),
(1306,'tr','Satıcı çok mutlu.','Satıcı çok kızgın.','bir sebze satıcısı','bir kitap satıcısı','chill','none'),
(1307,'tr','Hizmetçinin gümüş bir tepsisi var.','Hizmetçinin gümüş bir zili var.','tepsili bir hizmetçi','mutfakta bir hizmetçi','chill','none'),
(1308,'tr','Gölgesi bile dans ediyor!','Arkadaşı bile dans ediyor!','duvarda dev bir gölge','ağacın altında bir gölge','dramatic','exclamation'),
(1311,'tr','Kocaman bir gemiye el sallıyor!','Minicik bir gemiye el sallıyor!','büyük bir gemiye el sallamak','büyük bir gemiden el sallamak','dramatic','exclamation'),
(1312,'tr','Tezgâhtarın bir paltosu var.','Tezgâhtarın bir şapkası var.','iş başında bir tezgâhtar','moladaki bir tezgâhtar','business','none'),
(1314,'tr','Omzunun kontrol edilmesi gerekiyor.','Dizinin kontrol edilmesi gerekiyor.','omuz muayenesi','omzunda bir çanta','business','none'),
(1315,'tr','Yağmur duşu mu? Resmen şelale!','Bahçe duşu mu? Resmen şelale!','büyük bir yağmur duşu','bir duş perdesi','dramatic','exaggeration'),
(1316,'tr','Kardeşler gülüyor.','Kardeşler tartışıyor.','birlikte gülen kardeşler','oyuncak kavgası yapan kardeşler','chill','none'),
(1317,'tr','Taş bir kaldırımda duruyor.','Ahşap bir kaldırımda duruyor.','geniş, taş bir kaldırım','insan dolu bir kaldırım','business','none'),
(1319,'tr','O bekâr ve mutlu.','O bekâr ve mutsuz.','bekâr ve mutlu','tek bir fincan çay','chill','none'),
(1321,'tr','Buyurun yemeğiniz, beyefendi.','Buyurun hesabınız, beyefendi.','yemeğiniz, beyefendi','hesabınız, beyefendi','business','none'),
(1325,'tr','Uyuyor. Yastık onun en iyi arkadaşı.','Uyuyor. Kedi onun en iyi arkadaşı.','yatakta uyumak','trende uyumak','low_iq','guessing'),
(1326,'tr','Pofuduk terlikler, tembel bir sabah.','Pofuduk çoraplar, tembel bir sabah.','pofuduk terlikleri giymek','mağazada pofuduk terlikler','chill','none'),
(1327,'tr','Adam Slovak halk kıyafeti giyiyor.','Kadın Slovak halk kıyafeti giyiyor.','Slovak halk kıyafeti','bir Slovak futbol forması','chill','none'),
(1328,'tr','Slovakya''da dans ediyor!','Slovakya''da yüzüyor!','Slovakya''da bir çayır','Slovakya''da bir plaj','dramatic','exclamation'),
(1337,'tr','Kanepede oynuyorlar.','Yerde oynuyorlar.','gri bir kanepede arkadaşlar','gri bir otobüste arkadaşlar','chill','none'),
(1340,'tr','Biri gizlice gidiyor.','Biri gizlice dans ediyor.','uzaklaşan biri','köpek gezdiren biri','gossip','guessing'),
(1342,'tr','Oğlu eve döndü!','Kızı eve döndü!','yetişkin oğluna sarılmak','oğluna el sallayıp vedalaşmak','dramatic','exclamation'),
(1344,'tr','Örümcek iş başında.','Karınca iş başında.','ağındaki bir örümcek','küvette bir örümcek','business','none'),
(1346,'tr','Boksör su tükürüyor.','Boksör su içiyor.','kovaya su tükürmek','sakız tükürmek','chill','none'),
(1347,'tr','Bir el süngeri sıkıyor.','Bir el limonu sıkıyor.','sıkılan köpüklü bir sünger','bir dilim pandispanya','chill','none'),
(1350,'tr','Meydandan geçiyor. Hoşça kalın, güvercinler!','Nehirden geçiyor. Hoşça kalın, güvercinler!','meydanda koşmak','sessiz bir meydanda oturmak','slang','none'),
(1353,'tr','Tek bir parlak yıldız. Dilek tut!','Tek bir parlak ay. Dilek tut!','parlak bir yıldızı göstermek','ağaçta bir yıldız','slang','exclamation'),
(1354,'tr','İstasyonda yine geç kaldık!','Havalimanında yine geç kaldık!','istasyonda koşturmak','istasyonda uyumak','dramatic','guessing'),
(1355,'tr','Eller direksiyonda.','Eller telefonda.','direksiyonda eller','bir teknenin dümeni','chill','none'),
(1358,'tr','Üvey annesi saçını örüyor.','Üvey annesi saçını kesiyor.','saç ören bir üvey anne','okulda bir üvey anne','chill','none'),
(1359,'tr','Üvey kız kardeşler gülmekten kendilerini alamıyor.','Üvey kız kardeşler ağlamaktan kendilerini alamıyor.','birlikte gülen üvey kız kardeşler','yatak paylaşan üvey kız kardeşler','gossip','exaggeration'),
(1360,'tr','Stetoskop kullanıyor. Şşş!','Termometre kullanıyor. Şşş!','stetoskopla dinlemek','masada bir stetoskop','dramatic','exclamation'),
(1362,'tr','Kesiğe dikiş atılıyor.','Kesiğe yara bandı yapıştırılıyor.','ön kolda dikişler','gömlekte dikişler','chill','none'),
(1363,'tr','Bu taş yüzer, değil mi?','Bu yaprak yüzer, değil mi?','gölün üstünde bir taş','duvarda bir taş','low_iq','guessing'),
(1365,'tr','Bir yabancı onu durduruyor.','Bir polis onu durduruyor.','kapüşonlu bir yabancı','köpekli bir yabancı','dramatic','none'),
(1366,'tr','Bir yaprak derede sörf yapıyor.','Bir kurbağa derede sörf yapıyor.','berrak bir orman deresi','balık dolu bir dere','low_iq','exaggeration'),
(1367,'tr','Kalabalık bir sokaktan karşıya geçiyor.','Kalabalık bir köprüden karşıya geçiyor.','büyük şehirde kalabalık sokak','sessiz bir köy sokağı','business','none'),
(1369,'tr','Yağmur mu? Sokak lambasıyla dans ediyor!','Yağmur mu? Trafik ışığıyla dans ediyor!','sıra sıra yanan sokak lambaları','sıra sıra yanan mumlar','dramatic','exclamation'),
(1371,'tr','Metro treni aşırı hızlı.','Metro treni aşırı yavaş.','hızla geçen bir metro treni','bir metro haritası','slang','exaggeration'),
(1372,'tr','Valizi gri ve pratik.','Valizi kırmızı ve pratik.','gri bir valiz çekmek','gri bir valiz hazırlamak','business','none'),
(1373,'tr','Yaz modu: göle koca bir atlayış.','Yaz modu: havuza koca bir atlayış.','yazın göle atlamak','bir yaz havuz partisi','slang','none'),
(1375,'tr','Eldiveninden ter saçılıyor!','Ayakkabısından ter saçılıyor!','kolunda ter','bir gömlekte ter','dramatic','exclamation'),
(1378,'tr','İsviçre fondüsü yiyor.','İsviçre çikolatası yiyor.','İsviçre peynir fondüsü','İsviçre çikolata fondüsü','chill','none'),
(1379,'tr','Biri ışık düğmesini buldu. Vay be.','Biri telefonu buldu. Vay be.','bir ışık düğmesi','bir demiryolu makası','low_iq','exaggeration'),
(1380,'tr','İsviçre: inekler bile müzik dinliyor.','İsviçre: keçiler bile müzik dinliyor.','İsviçre''de bir alp borusu','İsviçre''de inek çanı dükkânı','chill','exaggeration'),
(1381,'tr','Şırınga fışkırtıyor!','Şişe fışkırtıyor!','şırıngadan fışkırtmak','şırınga doldurmak','dramatic','exclamation'),
(1383,'tr','Terzi bir ceketi düzeltiyor.','Terzi bir ayakkabıyı düzeltiyor.','mezuralı bir terzi','ayakkabı satan bir terzi','chill','none'),
(1385,'tr','Musluktan su! Vay!','Hortumdan su! Vay!','musluğu açmak','omza hafifçe vurmak','low_iq','exclamation'),
(1386,'tr','Taksi şoförü el sallıyor!','Taksi şoförü uyuyor!','el sallayan bir taksi şoförü','gece bir taksi şoförü','slang','exclamation'),
(1389,'tr','Kadının gözyaşları akıyor.','Adamın gözyaşları akıyor.','yanağında bir gözyaşı','elbisesinde bir yırtık','dramatic','none'),
(1390,'tr','Ay''a dokunmak istiyor.','Güneşe dokunmak istiyor.','aya uzanmak','denizin üstünde ay','dramatic','guessing'),
(1394,'tr','Denizin üstünde kocaman turuncu bir güneş.','Karın üstünde kocaman turuncu bir güneş.','denizin üstünde güneş','dağların üstünde güneş','chill','none'),
(1396,'tr','Koca tiyatro bu kıza kaldı!','Koca tiyatro bu adama kaldı!','boş, eski bir tiyatro','insan dolu bir tiyatro','dramatic','exaggeration'),
(1398,'tr','Termometresi kocaman!','Diş fırçası kocaman!','büyük, cam bir termometre','duvarda bir termometre','dramatic','exclamation'),
(1400,'tr','Boğazı kontrol ediliyor.','Kulağı kontrol ediliyor.','boğaza tutulan ışık','boğazını temizlemek','business','none'),
(1403,'tr','Bu ayak parmakları kumsala bayılıyor!','Bu ayak parmakları kara bayılıyor!','ıslak kumda ayak parmakları','yumuşak çimde ayak parmakları','dramatic','exaggeration'),
(1404,'tr','Dili öğle yemeği için kar yakalıyor.','Eli öğle yemeği için kar yakalıyor.','dilini çıkarmak','dilini ısırmak','low_iq','guessing'),
(1405,'tr','Her bir diş tek tek kontrol ediliyor.','Her bir tırnak tek tek kontrol ediliyor.','bir dişi kontrol etmek','diş perisi','business','none'),
(1406,'tr','Şu diş fırçama bak!','Şu saç fırçama bak!','köpüklü bir diş fırçası','bardakta bir diş fırçası','dramatic','exclamation'),
(1410,'tr','Trafik ışığında bekliyor.','Otobüs durağında bekliyor.','trafik ışığında beklemek','tren istasyonunda beklemek','chill','none'),
(1411,'tr','Eski tramvay, kocaman gülüş, harika tarz.','Eski otobüs, kocaman gülüş, harika tarz.','eski, yeşil bir tramvay','eski, yeşil bir otobüs','flirt','none'),
(1414,'tr','Vay, meşe kocaman!','Vay, palmiye kocaman!','kocaman bir meşe ağacı','kocaman bir piknik sepeti','low_iq','exclamation'),
(1415,'tr','Kamyonuna biniyor.','Arabasına biniyor.','büyük, gümüş bir kamyon','büyük, gümüş bir otobüs','chill','none'),
(1416,'tr','Motoruyla tünelden çıkıyor.','Motoruyla garajdan çıkıyor.','karayolu tünelinden çıkış','tren tüneline giriş','chill','none'),
(1419,'tr','İkizler, aynı elbise. Planlı mı?','İkizler, aynı şapka. Planlı mı?','aynı elbiseli ikizler','bebek arabasında ikizler','gossip','guessing'),
(1420,'tr','Dünyanın en iyi amcası!','Dünyanın en iyi teyzesi!','amcasının omuzlarında','amcasının bisikletinde','slang','exaggeration'),
(1422,'tr','Bir el ekranı gösteriyor.','Bir el pencereyi gösteriyor.','ekranı göstermek','kapıyı göstermek','chill','none'),
(1423,'tr','Bir sütun grafiğini gösteriyor.','Bir pasta grafiğini gösteriyor.','sütun ve çizgi grafikleri','kâğıtta bir grafik','business','none'),
(1424,'tr','Ayaktaki iş arkadaşı mavi giymiş.','Ayaktaki iş arkadaşı kırmızı giymiş.','mavi gömlekli iş arkadaşı','kırmızı gömlekli iş arkadaşı','chill','none'),
(1425,'tr','Bil bakalım kim tasmalı.','Bil bakalım kim kanepede.','tasmalı bir köpek','tasmasız bir köpek','gossip','none'),
(1427,'tr','İpin üstünde dengede duruyor!','Kütüğün üstünde dengede duruyor!','ince bir ipte dengede durmak','ince bir dalda dengede durmak','dramatic','exclamation'),
(1429,'tr','Arkadaşları için şarkı söylüyor.','Arkadaşları için dans ediyor.','mikrofona şarkı söylemek','duşta şarkı söylemek','chill','none'),
(1432,'tr','Kostümle şarkı söylüyor. Cam ayakkabı hazır.','Kostümle dans ediyor. Cam ayakkabı hazır.','kostümle şarkı söylemek','kostüm alışverişi','gossip','guessing'),
(1433,'tr','Evde normal normal dans ediyorlar, o kadar.','Evde normal normal yemek yiyorlar, o kadar.','kostümlerle dans etmek','sahnede dans etmek','chill','understatement'),
(1434,'tr','Avizedeki hırsızı kimse görmüyor.','Çatıdaki hırsızı kimse görmüyor.','çantalı bir hırsız','silahlı bir hırsız','ironic','guessing'),
(1435,'tr','Mikrofonu kimseyle paylaşmıyor.','Gitarı kimseyle paylaşmıyor.','ayaklı bir mikrofon','telefondaki mikrofon','ironic','guessing'),
(1438,'tr','Adam bir podcast kaydediyor.','Kadın bir podcast kaydediyor.','podcast kaydetmek','podcast dinlemek','chill','none'),
(1441,'tr','Kazandığı zafer çabaya değdi.','Kazandığı zafer paraya değdi.','çabaya değer','uyanık kalma çabası','chill','none'),
(1442,'tr','Bu ofis bitki dolu.','Bu ofis köpek dolu.','aydınlık, açık bir ofis','karanlık, boş bir ofis','business','none'),
(1446,'tr','Konferans tıklım tıklım!','Konferans bomboş!','kalabalık bir konferans salonu','görüntülü konferans görüşmesi','dramatic','exclamation'),
(1447,'tr','Aşı biraz acıtıyor.','Aşı biraz gıdıklıyor.','koldan aşı','bacaktan aşı','chill','understatement'),
(1450,'tr','Bir ziyaretçiden çiçekler. Ne tatlı.','Bir ziyaretçiden şekerler. Ne tatlı.','çiçekli bir ziyaretçi','müzede bir ziyaretçi','flirt','none'),
(1451,'tr','Bu vitamin onu güldürüyor.','Bu vitamin onu ağlatıyor.','turuncu jelibon vitamin','yeşil jelibon vitamin','gossip','guessing'),
(1452,'tr','Yanardağ biraz sinirli.','Yanardağ biraz uykulu.','gece patlayan bir yanardağ','karla kaplı bir yanardağ','ironic','understatement'),
(1453,'tr','Gemi uzun bir deniz yolculuğunda.','Gemi bir nehir yolculuğunda.','okyanusu aşan deniz yolculuğu','nehir boyunca bir yolculuk','chill','none'),
(1454,'tr','Belini ölçüyor.','Kolunu ölçüyor.','bele sarılı bir mezura','bele takılı bir kemer','business','none'),
(1457,'tr','Kadın garson milkshake servis ediyor.','Kadın garson pizza servis ediyor.','kahvaltı servis eden kadın garson','kahvaltı yapan kadın garson','business','none'),
(1458,'tr','Yürüyüşçünün altın sarısı bir köpeği var.','Yürüyüşçünün siyah bir köpeği var.','batonlu bir yürüyüşçü','bebek arabalı bir yürüyüşçü','chill','none'),
(1459,'tr','Duvarı beyaza boyuyor.','Duvarı maviye boyuyor.','büyük, çıplak bir duvar','bahçeyi çevreleyen bir duvar','chill','none'),
(1466,'tr','Yağmur mu, güneş mi? Hava karar veremiyor.','Kar mı, güneş mi? Hava karar veremiyor.','tepede değişken hava','plajda güneşli hava','ironic','guessing'),
(1467,'tr','Bir tamirci tekerlek yuvarlıyor.','Bir tamirci tekerlek yıkıyor.','araba tekerleği yuvarlamak','bisikletteki bir tekerlek','business','none'),
(1468,'tr','Yarış tekerlekli sandalyesiyle son hız!','Yarış go-kartıyla son hız!','yarış tekerlekli sandalyesi','tekerlekli sandalye rampası','dramatic','exclamation'),
(1473,'tr','İşçi bir kiriş tutuyor.','İşçi bir boru tutuyor.','koruyucu gözlüklü bir işçi','takım elbiseli bir işçi','chill','none'),
(1476,'tr','Yazar gece yazıyor, tabii ki.','Yazar öğlen yazıyor, tabii ki.','daktilo başında bir yazar','laptop başında bir yazar','ironic','cliche'),
(1477,'tr','Röntgende el kemikleri görünüyor.','Röntgende ayak kemikleri görünüyor.','bir elin röntgeni','bir ayağın röntgeni','nerd','none'),
(1479,'tr','Hayvanat bahçesinde öğle yemeği servisi.','Çiftlikte öğle yemeği servisi.','hayvanat bahçesinde bir zürafa','hayvanat bahçesinde bir aslan','business','none'),
(1481,'tr','Şatonun iki kemerli geçidi var.','Şatonun dört kemerli geçidi var.','merdiven altında kemerli geçit','nehrin üstünde kemerli geçit','chill','none'),
(1482,'tr','Harika altın küpeler!','Harika gümüş küpeler!','büyük altın halka küpeler','hediye kutusunda küpeler','flirt','exclamation'),
(1483,'tr','Çilekler kırmızı.','Çilekler yeşil.','bir çilek fidesi','çilekli bir milkshake','chill','none'),
(1484,'tr','Bu müziğin oynat tuşu yok.','Bu şiirin oynat tuşu yok.','eski müzik notaları','eski bir müzik kutusu','ironic','exaggeration'),
(1485,'tr','Evi satmak istiyorlar.','Arabayı satmak istiyorlar.','beyaz bir ev satmak','kırmızı bir araba satmak','chill','none'),
(1487,'tr','Tanrının altın bir tahtı var.','Tanrının gümüş bir tahtı var.','tahtında bir tanrı','at üstünde bir kral','chill','none'),
(1488,'tr','At arabasını atlar çekiyor.','At arabasını öküzler çekiyor.','yaldızlı bir kraliyet at arabası','yaldızlı bir tren vagonu','chill','none'),
(1489,'tr','Perinin en iyi arkadaşı bir kurbağa.','Perinin en iyi arkadaşı bir kedi.','yosunların üstünde bir peri','gökyüzünde bir peri','gossip','guessing'),
(1491,'tr','Ne çok kelebek!','Ne çok kuş!','çiçeklerin üstünde kelebekler','gömlekteki kelebekler','dramatic','exaggeration'),
(1495,'tr','Bilgi: tek boynuzlu atın bir boynuzu var.','Bilgi: tek boynuzlu atın iki boynuzu var.','şaha kalkmış tek boynuzlu at','uyuyan tek boynuzlu at','nerd','cliche'),
(1498,'tr','Balonda iki adam. Ciao!','Atın üstünde iki adam. Ciao!','iki adamlı bir balon','iki köpekli bir balon','slang','none'),
(1499,'tr','Saplar uzun ve kıvrımlı.','Saplar kısa ve kalın.','uzun, kıvrımlı saplar','vazoda saplar','nerd','none'),
(1501,'tr','Yeşil bir sıvı döküyor.','Kırmızı bir sıvı döküyor.','geniş bir kâseden dökmek','fincana çay dökmek','chill','none'),
(1502,'tr','İki kişilik gün batımı. Çok tatlı.','İki kişilik kahvaltı. Çok tatlı.','birlikte gün batımını izlemek','dağlarda gün batımı','gossip','none'),
(1504,'tr','Filozofun sakalı var.','Filozofun şapkası var.','sakallı bir filozof','gülen bir filozof','chill','none'),
(1505,'tr','Süpermarket alışverişi, 1950''ler tarzı.','Fırın alışverişi, 1950''ler tarzı.','süpermarket kasası','süpermarket otoparkı','slang','cliche'),
(1508,'tr','Kilisenin yüksek bir kulesi var.','Kilisenin minicik bir kulesi var.','eski, taş bir kilise','eski, taş bir köprü','business','none'),
(1510,'tr','Figür neden çığlık atıyor?','Figür neden şarkı söylüyor?','köprüde çığlık atmak','hız treninde çığlık atmak','low_iq','guessing'),
(1513,'tr','Eller dua etmek için birleşmiş.','Eller alkışlamak için birleşmiş.','dua etmek için birleşen eller','açık ellerle dua etmek','chill','none'),
(1514,'tr','Eski bir tabloda din.','Modern bir karikatürde din.','din üzerine bir tablo','din üzerine bir kitap','nerd','none'),
(1519,'tr','Çiçekleri çok güzel.','Tüyleri çok güzel.','saçında güzel çiçekler','saçında güzel kurdeleler','flirt','none'),
(1520,'tr','Kıvırcık saç ve inciler? Klas.','Kısa saç ve inciler? Klas.','uzun, kıvırcık sarı saç','kıvırcık tüylü bir köpek','flirt','none'),
(1522,'tr','Bir sepet kirazı var.','Bir sepet elması var.','bir sepet kiraz','sepette bir köpek','chill','none'),
(1523,'tr','Sarışın kızın saçları çiçek dolu.','Esmer kızın saçları çiçek dolu.','uzun dalgalı saçlı bir sarışın','kısa saçlı bir sarışın','chill','none'),
(1524,'tr','Otostop yapıyor ve bir UFO duruyor.','Otostop yapıyor ve bir otobüs duruyor.','dağ yolunda otostop yapmak','otobanda otostop yapmak','gossip','guessing'),
(1525,'tr','Tren üstümüze geliyor!','Kamyon üstümüze geliyor!','siyah bir buharlı tren','yarış için antrenman yapmak','dramatic','exclamation'),
(1526,'tr','Savaşçının miğferi var.','Savaşçının kalkanı var.','bir samuray savaşçı','at üstünde bir savaşçı','chill','none'),
(1527,'tr','Katedralin kocaman bir kubbesi var.','Katedralin düz bir çatısı var.','barok bir katedral kubbesi','şarkı söyleyen katedral korosu','chill','none'),
(1528,'tr','Japonya''nın üstünde balonlar!','Japonya''nın üstünde kuşlar!','Japonya''nın simgeleri','bir Japonya haritası','dramatic','exclamation'),
(1529,'tr','İki kule, bir yanardağ.','İki kule, iki yanardağ.','iki yuvarlak şato kulesi','iki yüksek su kulesi','chill','none'),
(1530,'tr','Kasaba bir tepede. Manzarası güzelmiş, öyle diyorlar.','Kasaba deniz kenarında. Manzarası güzelmiş, öyle diyorlar.','tepede eski bir kasaba','yeni bir sahil kasabası','gossip','none'),
(1531,'tr','Bir kemer kiliseyi çerçeveliyor.','Bir ağaç kiliseyi çerçeveliyor.','büyük, sivri bir kemer','büyük, sivri bir kule','chill','none'),
(1534,'tr','Vay, her atta bir boynuz var!','Vay, her atta iki boynuz var!','tek boynuzlu atın uzun boynuzu','arabanın yüksek sesli kornası','low_iq','exclamation'),
(1535,'tr','Baş aşağı duruyor. Çok kolay.','Sırtüstü yatıyor. Çok kolay.','baş aşağı dengede durmak','baş aşağı asılı durmak','slang','understatement'),
(1537,'tr','Mısır firavununun bir yayı var.','Mısır firavununun bir kılıcı var.','bir Mısır firavunu','Mısır''da bir piramit','chill','none'),
(1538,'tr','İki sütunun arasında duruyor.','İki ağacın arasında duruyor.','süslü iki sütun','gazetede bir sütun','chill','none'),
(1541,'tr','Minik şapel, kış modu.','Minik şapel, yaz modu.','karlı, beyaz bir şapel','misafir dolu bir şapel','slang','none'),
(1543,'tr','Kocaman bir lahana tutuyor.','Kocaman bir balkabağı tutuyor.','lahana dolu bir bahçe','saksıda bir lahana','chill','none'),
(1544,'tr','Çamaşırları asıyor.','Bayrakları asıyor.','beyaz çamaşır asmak','beyaz çamaşır katlamak','chill','none'),
(1545,'tr','Kraliçenin yakası kocaman!','Kraliçenin köpeği kocaman!','asalı bir kraliçe','kılıçlı bir kraliçe','gossip','none'),
(1547,'tr','Kutsal adam derin derin düşünüyor.','Kutsal adam kahkahalarla gülüyor.','düşünen kutsal bir adam','dua eden kutsal bir adam','chill','none'),
(1548,'tr','Her pencerede insanlar var.','Her pencerede kediler var.','her pencerede bir aile','her pencerede bir kedi','chill','none'),
(1549,'tr','Biri bütün boyayı dökmüş!','Biri bütün sütü dökmüş!','boya damlaları','bir kutu boya','dramatic','blaming_someone'),
(1551,'tr','Gökler bize bir gitar gönderdi!','Gökler bize bir keman gönderdi!','gitarı havaya kaldırmak','gitar akort etmek','dramatic','exclamation'),
(1554,'tr','Keşişin kırmızı bir şemsiyesi var.','Keşişin siyah bir şemsiyesi var.','pembe giysili bir keşiş','siyah giysili bir keşiş','chill','none'),
(1555,'tr','Figür büyük bir kılıç tutuyor.','Figür büyük bir mızrak tutuyor.','kılıcı dik tutmak','duvarda bir kılıç','chill','none'),
(1559,'tr','Ayçiçekleri sarı bir vazoyu dolduruyor.','Güller sarı bir vazoyu dolduruyor.','vazoda ayçiçekleri','tarlada ayçiçekleri','chill','none'),
(1560,'tr','Bir salıncağın yanında duruyor.','Bir kapının yanında duruyor.','halattan bir salıncak','bir swing dansı','chill','none'),
(1562,'tr','Kovboy gün batımına doğru at sürüyor.','Kovboy denize doğru at sürüyor.','at üstünde bir kovboy','boğa üstünde bir kovboy','dramatic','cliche'),
(1565,'tr','Kadın paslı dişli çarklardan yapılmış.','Kadın paslı zincirlerden yapılmış.','paslı metal dişli çarklar','paslı metal zincirler','chill','none'),
(1567,'tr','Uçak yükseliyor!','Uçak alçalıyor!','yükselen bir uçak','alçalan bir uçak','dramatic','exclamation'),
(1568,'tr','Ayın altında yelkenle gidiyor.','Güneşin altında yelkenle gidiyor.','gece yelkenle gitmek','güneşte yelkenle gitmek','chill','none'),
(1574,'tr','Bir daldan bir fener sarkıyor.','Bir çatıdan bir fener sarkıyor.','zincirde bir fener','elinde bir fener','chill','none'),
(1575,'tr','Çift sarılıyor.','Çift kavga ediyor.','ayın altında bir çift','plajda bir çift','chill','none'),
(1576,'tr','Rüyasında aydan sallanıyor.','Rüyasında bir ağaçtan sallanıyor.','ayla ilgili bir rüya','denizle ilgili bir rüya','chill','guessing'),
(1579,'tr','Akıllı telefonlar bir ev yapmış.','Kitaplar bir ev yapmış.','akıllı telefonlardan bir ev','cepte bir akıllı telefon','chill','exaggeration'),
(1581,'tr','Minibüste yaşam, işte bu!','Çadırda yaşam, işte bu!','sörf tahtalı bir minibüs','bisikletli bir minibüs','slang','exclamation'),
(1583,'tr','Astronot uçup gidiyor!','Pilot uçup gidiyor!','uzayda bir astronot','Ay''da bir astronot','dramatic','exclamation'),
(1584,'tr','Eteği de dans ediyor.','Köpeği de dans ediyor.','kırmızı etekle dans etmek','yağmurda dans etmek','chill','exaggeration'),
(1585,'tr','Beş beyaz gül var.','Beş kırmızı gül var.','beş beyaz gül çiçeği','vazoda beyaz güller','chill','none'),
(1586,'tr','Nereye baksan kirlilik.','Nereye baksan çiçek.','fabrikadan gelen kirlilik','gemiden gelen kirlilik','dramatic','exaggeration'),
(1589,'tr','Bu kişi üzgün görünüyor.','Bu kişi mutlu görünüyor.','turuncu saçlı üzgün bir figür','mavi saçlı üzgün bir figür','chill','none'),
(1590,'tr','Kapüşon yıldızlarla dolu.','Kapüşon çiçeklerle dolu.','yıldızlı bir kapüşon','gözlere inen bir kapüşon','chill','none'),
(1591,'tr','Bu deniz feneri çizgili.','Bu deniz feneri puantiyeli.','çizgili bir deniz feneri','çizgili bir plaj kulübesi','chill','none'),
(1592,'tr','Robotun dudakları mavi. Üşüyor mu?','Robotun dudakları kırmızı. Üşüyor mu?','metal bir robot kafası','bir robot süpürge','low_iq','guessing'),
(1593,'tr','Bu mavi saç kesimine bayıldım!','Bu mavi şapkaya bayıldım!','turkuaz küt saç kesimi','kuaförde saç kesimi','flirt','exclamation'),
(1595,'tr','İki piramit. Çok sivri.','İki kule. Çok sivri.','iki kahverengi piramit','portakallardan bir piramit','low_iq','none'),
(1596,'tr','Ay, Rusya''nın üstünde parlıyor.','Güneş, Rusya''nın üstünde parlıyor.','Rusya''da bir kilise','Rusya''da bir saray','chill','none'),
(1597,'tr','Eyvah, yüzü su altında!','Eyvah, yüzü kumda!','su altında bir köpek','suyun üstünde bir köpek','dramatic','exclamation'),
(1598,'tr','İsa bir elini kaldırıyor.','İsa iki elini de kaldırıyor.','kutsayan İsa','haç taşıyan İsa','chill','none'),
(1600,'tr','Kanalda küçük bir tekne var.','Kanalda büyük bir gemi var.','kanalda bir tekne','gölde bir tekne','chill','none'),
(1603,'tr','Açık denizde petrol sondajı yapıyorlar.','Bir tepede petrol sondajı yapıyorlar.','denizde bir petrol platformu','tavada yağ','business','none'),
(1609,'tr','Kayanın üstünde bale yapıyor!','Teknenin üstünde bale yapıyor!','kayanın üstünde bale','stüdyoda bale','dramatic','exclamation'),
(1610,'tr','Ay balkonu aydınlatıyor.','Bir lamba balkonu aydınlatıyor.','ay ışığında bir balkon','güneşli bir balkon','dramatic','none'),
(1611,'tr','Işığın içinde bir güvercin uçuyor.','Işığın içinde bir karga uçuyor.','kanatlarını açmış bir güvercin','kafeste bir güvercin','chill','none'),
(1612,'tr','Kore''den çocuklar el sallıyor.','Kore''den çocuklar dans ediyor.','Kore''den el sallayan çocuklar','Kore''den şarkı söyleyen çocuklar','chill','none'),
(1613,'tr','Üç roket havalanıyor!','İki roket havalanıyor!','gün batımında yükselen roketler','gün batımında inen bir roket','dramatic','exclamation'),
(1614,'tr','İspanya''da boğalar koşuyor!','İspanya''da atlar koşuyor!','İspanya''da koşan boğalar','İspanya''da yarışan atlar','dramatic','exclamation'),
(1617,'tr','Melek bir çocuğa yol gösteriyor.','Melek bir kuzuya yol gösteriyor.','çocuğa yol gösteren bir melek','arp çalan bir melek','chill','none'),
(1618,'tr','Etrafında melekler uçuşuyor.','Etrafında kuşlar uçuşuyor.','bulutlarda kanatlı melekler','yılbaşı ağacında melekler','chill','none'),
(1619,'tr','Büyük geminin yelkenleri fora.','Büyük geminin hiç yelkeni yok.','rüzgârla şişmiş yelkenler','rüzgârda yırtık yelkenler','chill','none'),
(1620,'tr','Cennet bugün epey kalabalık görünüyor.','Cennet bugün epey boş görünüyor.','cennette uçan melekçikler','azizlerle dolu bir cennet','ironic','exaggeration'),
(1623,'tr','Ne çok gökdelen!','Ne çok köprü!','alacakaranlıkta gökdelenler','inşa halindeki bir gökdelen','dramatic','exclamation'),
(1625,'tr','Sörfçü bir sörf tahtası tutuyor.','Sörfçü bir gitar tutuyor.','sörf tahtasını dik tutmak','dalgalarda sörf tahtasıyla kaymak','chill','none'),
(1629,'tr','Tek bir ananas. Çok yalnız.','Tek bir muz. Çok yalnız.','dik duran tek bir ananas','dilimlenmiş bir ananas','dramatic','exaggeration'),
(1630,'tr','Ahtapotun sekiz kolu var. Saydım.','Ahtapotun altı kolu var. Saydım.','sekiz kollu bir ahtapot','kavanozda bir ahtapot','low_iq','none'),
(1631,'tr','Cadının bir süpürgesi var. Zekice.','Cadının bir kedisi var. Zekice.','süpürgesiyle bir cadı','süpürgesinin üstünde bir cadı','low_iq','none'),
(1633,'tr','Bu heykel seni izliyor.','Bu köpek seni izliyor.','bir gargoyl heykeli','bir at heykeli','gossip','guessing'),
(1635,'tr','Deniz kızı kuyruğu mu? Tamamen yeşil.','Deniz kızı kuyruğu mu? Tamamen mavi.','gülümseyen çizgi film deniz kızı','kayanın üstünde bir deniz kızı','slang','none'),
(1638,'tr','Perdeler ay ışıklı bir denizi çerçeveliyor.','Perdeler güneşli bir denizi çerçeveliyor.','ağır, mor perdeler','ağır, mor halılar','dramatic','none'),
(1639,'tr','Bilgi: bebek bir ahırda.','Bilgi: bebek bir şatoda.','ahırda bir bebek','ahırda bir at','nerd','none'),
(1641,'tr','Korkutucu bir palyaço ve bir karga.','Korkutucu bir palyaço ve bir kedi.','gökyüzünde korkutucu gözler','korkutucu bir film gecesi','chill','none'),
(1642,'tr','Köyün gökyüzü kırmızı.','Köyün gökyüzü mavi.','gün batımında bir köy','karlar altında bir köy','business','none'),
(1643,'tr','Kovboy şapkası takıyor.','Beyzbol şapkası takıyor.','geniş bir kovboy şapkası','geniş bir hasır şapka','chill','none'),
(1644,'tr','Şövalye tam zırh giymiş.','Şövalyenin üstünde hiç zırh yok.','metal zırhlı bir şövalye','zırhsız bir şövalye','chill','none'),
(1647,'tr','Kartpostalda bir kadın var.','Kartpostalda bir adam var.','eski, yırtık bir kartpostal','plajlı bir kartpostal','chill','none'),
(1649,'tr','Burada her şey çok renkli!','Burada her şey gri!','renkli bir gökkuşağı yolu','renkli bir şemsiye','dramatic','exclamation'),
(1650,'tr','Şato güzel, uçurum korkutucu.','Şato güzel, köprü korkutucu.','uçurumda bir şato','denizin üstünde bir uçurum','gossip','understatement'),
(1651,'tr','Mavi pelerininde yıldızlar var.','Kırmızı pelerininde yıldızlar var.','yıldızlarla kaplı mavi pelerin','tüylerden bir pelerin','chill','none'),
(1652,'tr','Kelebeğe dokunacak!','Kuşa dokunacak!','parlayan bir kelebeğe dokunmak','parlayan bir kelebeği yakalamak','dramatic','guessing'),
(1653,'tr','Kedi japon balığını istiyor...','Kedi kuşu istiyor...','fanusta bir japon balığı','havuzda bir japon balığı','dramatic','guessing'),
(1655,'tr','Vay, tacı ne kadar uzun!','Vay, tacı ne kadar küçük!','uzun, altın bir taç','küçük, gümüş bir taç','low_iq','exclamation'),
(1656,'tr','Dudakları kırmızı.','Dudakları mavi.','parlak kırmızı dudaklar','bardağa değen dudaklar','chill','none'),
(1660,'tr','Hazine dolu bir sandık!','Şişe dolu bir sandık!','açık bir hazine sandığı','kâğıtta bir hazine haritası','dramatic','exclamation'),
(1661,'tr','Zaman biraz belirsiz.','Harita biraz belirsiz.','zamanı göstermek','bir zaman makinesi','chill','understatement'),
(1664,'tr','Rahip dinliyor.','Rahip şarkı söylüyor.','günah çıkarma odasında rahip','düğünde bir rahip','chill','none'),
(1665,'tr','Antik bir tapınakta duruyor.','Antik bir şatoda duruyor.','antik bir Mısır tapınağı','antik bir Yunan tapınağı','chill','none'),
(1666,'tr','Firavunun üstünde bir kobra duruyor.','Firavunun üstünde bir şahin duruyor.','profilden bir firavun','tahtında bir firavun','nerd','none'),
(1667,'tr','Geceleri Paris. Büyü gibi!','Öğlen Paris. Büyü gibi!','gece Paris','yağmurda Paris','dramatic','exclamation'),
(1669,'tr','İki kanat var ama heykel uçamıyor.','Dört kanat var ama heykel uçamıyor.','iki tüylü kanat','iki uçak kanadı','low_iq','understatement'),
(1670,'tr','Londra''da kırmızı bir otobüs. Klasik.','Londra''da kırmızı bir araba. Klasik.','Londra''da kırmızı bir otobüs','Paris''te kırmızı bir otobüs','chill','cliche'),
(1672,'tr','Prag alacakaranlıkta parlıyor.','Prag öğlen parlıyor.','alacakaranlıkta Prag Kalesi','karda Prag Kalesi','chill','none'),
(1674,'tr','Mor gökyüzü, mor tepeler.','Mor gökyüzü, yeşil tepeler.','mor, yıldızlı bir gökyüzü','mor bir çiçek tarlası','chill','none'),
(1675,'tr','Bir ağacın yanında yalnız duruyor.','Bir evin yanında yalnız duruyor.','boş bir tarlada yalnız','boş bir odada yalnız','dramatic','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
