begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(2155,'tr','Bu kendine güvenen gülüş işe yarıyor.','Bu gergin gülüş işe yarıyor.','kendine güvenen bir yarım gülüş','kendine güvenen yüksek bir kahkaha','flirt','none'),
(2156,'tr','Güneş ufukta duruyor.','Ay ufukta duruyor.','ufukta güneş','ufukta bir gemi','chill','none'),
(2157,'tr','Hindistan''dan bir bebek, altınlar içinde.','Hindistan''dan bir bebek, kırmızılar içinde.','Hindistan''dan bir tablo','Hindistan''dan bir halı','chill','none'),
(2158,'tr','Turuncu başörtüsüne bayıldım!','Mavi başörtüsüne bayıldım!','turuncu bir başörtüsü','başörtüsünü çıkarmak','flirt','exclamation'),
(2159,'tr','Kedi kendini çok görkemli hissediyor.','Köpek kendini çok görkemli hissediyor.','görkemli bir kedi','görkemli bir aslan','ironic','guessing'),
(2161,'tr','Dâhinin yeni bir fikri var.','Dâhinin yeni bir kedisi var.','yıldızlara bakan bir dâhi','formül yazan bir dâhi','nerd','guessing'),
(2162,'tr','Kızıl saçları kusursuz görünüyor.','Siyah saçları kusursuz görünüyor.','dalga dalga uzun kızıl saçlar','topuz yapılmış kızıl saçlar','flirt','none'),
(2164,'tr','Ormana bir patika uzanıyor. Kim önden gidiyor?','Ormana bir nehir uzanıyor. Kim önden gidiyor?','ormanın içinden geçen bir patika','ormanda bir kulübe','dramatic','guessing'),
(2172,'tr','Boya fırtınasında bir spor araba.','Kar fırtınasında bir spor araba.','lacivert bir spor araba','lacivert bir aile arabası','dramatic','exaggeration'),
(2175,'tr','Çam ormanında gece yarısı.','Çölde gece yarısı.','yıldızların altında gece yarısı','gece yarısı parti','chill','none'),
(2176,'tr','Koridorda yağmur yağıyor!','Koridorda kar yağıyor!','yağmurlu bir kütüphane koridoru','kalabalık bir market koridoru','dramatic','exclamation'),
(2177,'tr','DJ için ay bile geldi!','DJ için güneş bile geldi!','sokakta bir DJ','kulüpte bir DJ','slang','exaggeration'),
(2178,'tr','Pşşt, iki kedi gizlice bakıyor.','Pşşt, iki köpek gizlice bakıyor.','yaprakların arkasından gizlice bakmak','pencereden gizlice bakmak','gossip','none'),
(2181,'tr','Sokak resmen tıklım tıklım.','Sokak resmen bomboş.','tıklım tıklım neon bir sokak','tıklım tıklım bir tren vagonu','slang','none'),
(2182,'tr','Yürüyüşçünün kırmızı bir sırt çantası var.','Yürüyüşçünün mavi bir sırt çantası var.','kaya çıkıntısında bir yürüyüşçü','çadırda bir yürüyüşçü','chill','none'),
(2184,'tr','Kaplan kükrüyor!','Aslan kükrüyor!','kükreyen bir kaplan','uyuyan bir kaplan','dramatic','exclamation'),
(2185,'tr','Piyanistin sarı saçları var.','Piyanistin siyah saçları var.','piyano başında bir piyanist','klavye başında bir piyanist','chill','none'),
(2186,'tr','İsa dikenlerden bir taç takıyor.','İsa altından bir taç takıyor.','dikenlerden bir taç','dikenli bir gül','chill','none'),
(2187,'tr','Buda meditasyon yapıyor.','Buda dans ediyor.','meditasyon yapan Buda','uzanmış Buda','chill','none'),
(2188,'tr','Oğlan ağlıyor, annesi ağlamıyor.','Oğlan şarkı söylüyor, annesi söylemiyor.','bisiklette ağlamak','yatakta ağlamak','ironic','none'),
(2189,'tr','Biri denize düşüyor!','Biri denize atlıyor!','sırtüstü denize düşmek','teknede uyuyakalmak','dramatic','exclamation'),
(2190,'tr','Bu kötü adamın gözleri alev alev.','Bu kötü adamın gözleri masmavi.','yanan yıkıntılarda bir kötü adam','şatoda bir kötü adam','dramatic','none'),
(2191,'tr','Androidin insan yüzü var.','Androidin uzun sakalı var.','parlayan bir kadın android','mutfakta bir android','nerd','none'),
(2192,'tr','Harry Potter bu cam şişelere bayılırdı.','Harry Potter bu süpürgelere bayılırdı.','parlayan cam şişeler','bir termos','nerd','guessing'),
(2194,'tr','Tropikal yapraklar büyük. Vay.','Tropikal yapraklar minicik. Vay.','sık tropikal yapraklar','tropikal bir plaj','low_iq','none'),
(2195,'tr','Suluboya akıyor.','Yağlı boya akıyor.','suluboya bir portre','suluboya bir manzara','chill','none'),
(2199,'tr','Her yerde narin güller!','Her yerde narin laleler!','narin pembe güller','narin bir cam vazo','dramatic','exaggeration'),
(2200,'tr','Gece elbisesiyle çok şık görünüyor.','Montuyla çok şık görünüyor.','şık, dökümlü bir gece elbisesi','şık siyah bir takım elbise','flirt','none'),
(2201,'tr','Turuncu zırhı çok havalı!','Pembe zırhı çok havalı!','turuncu saç ve zırh','elinde bir portakal','flirt','exclamation'),
(2202,'tr','Beyaz blazer ceketi çok şık duruyor.','Kırmızı blazer ceketi çok şık duruyor.','şık beyaz bir blazer','şık koyu bir takım','chill','none'),
(2204,'tr','Kucağında bir kuzu tutuyor.','Kucağında bir köpek tutuyor.','kollarında bir kuzu','tarlada bir kuzu','chill','none'),
(2207,'tr','Robot el işaret ediyor.','Robot el sallıyor.','ekranı işaret etmek','gökyüzünü işaret etmek','chill','none'),
(2208,'tr','Saçı parlak pembe.','Saçı parlak yeşil.','parlak pembe saç','parlak pembe bir elbise','business','none'),
(2211,'tr','Bil bakalım kimde üç dişli mızrak var? Deniz tanrısında.','Bil bakalım kimde çekiç var? Deniz tanrısında.','üç dişli mızraklı bir tanrı','kumda üç dişli bir mızrak','gossip','guessing'),
(2212,'tr','Güzel çizgiler, kaplan!','Güzel benekler, kaplan!','siyah çizgili bir kaplan','siyah çizgili bir zebra','slang','exclamation'),
(2213,'tr','Bilgi: koçların kıvrık boynuzları var.','Bilgi: koçların düz boynuzları var.','kıvrık boynuzlu bir koç','ot yiyen bir koç','nerd','cliche'),
(2214,'tr','İçinden bir şato görebiliyorum.','İçinden bir kilise görebiliyorum.','kaya deliğinin içinden bakmak','pencereden bakmak','chill','none'),
(2216,'tr','Bir sunakta dua ediyor.','Bir sunakta şarkı söylüyor.','mumlu bir sunakta dua etmek','sunakta evlenmek','chill','none'),
(2217,'tr','Büyü yapıyor. Havalı.','Ağ atıyor. Havalı.','sihirli bir büyü yapmak','bir büyü kitabı okumak','slang','none'),
(2218,'tr','Etrafı devrelerle dolu.','Etrafı çiçeklerle dolu.','parlayan devre hatları','bir yarış pisti','nerd','none'),
(2220,'tr','Parayı dikkatle sayıyor.','Bozuk paraları dikkatle sayıyor.','bir deste banknot saymak','saniyeleri geri saymak','business','none'),
(2224,'tr','El ele tutuşuyorlar.','Tokalaşıyorlar.','yağmurda el ele tutuşmak','güneşte el ele tutuşmak','flirt','none'),
(2225,'tr','Zavallı kız, saçları sırılsıklam.','Zavallı kız, saçları kupkuru.','sağanakta sırılsıklam','sıcak suda sırılsıklam','gossip','none'),
(2226,'tr','Altın bileklikleri var.','Altın eldivenleri var.','bileklerde altın bileklikler','dükkânda bir bileklik','chill','none'),
(2227,'tr','Arkasına göz atıyor. Sana mı?','Aşağıya göz atıyor. Sana mı?','omzunun üstünden göz atmak','telefonuna göz atmak','gossip','guessing'),
(2228,'tr','Şehrin üstünde oturuyor.','Denizin üstünde oturuyor.','şehrin çok üstünde','bulutların üstünde','chill','none'),
(2231,'tr','Dev bir altın sfenks.','Dev bir gümüş sfenks.','altın bir sfenks heykeli','uyuyan bir sfenks kedisi','chill','none'),
(2232,'tr','Buda huzurlu görünüyor.','Buda kızgın görünüyor.','huzurlu, altın bir Buda','huzurlu, altın bir tapınak','chill','none'),
(2233,'tr','İki beyzbol eldiveni var.','İki beyzbol sopası var.','iki elinde beyzbol eldiveni','televizyonda beyzbol','chill','none'),
(2234,'tr','Savaşçının kasları kocaman.','Savaşçının kalkanı kocaman.','bir savaşçının iri kasları','bir savaşçının iri kalkanı','chill','none'),
(2235,'tr','Tam profilden gösterilmiş.','Arkadan gösterilmiş.','tam profilden bir adam','internette bir profil fotoğrafı','nerd','none'),
(2236,'tr','Dev bir ayın altında saray. Vay!','Dev bir güneşin altında saray. Vay!','dağlarda bir saray','çölde bir saray','dramatic','exclamation'),
(2237,'tr','Şu parlak sarı arabaya bak!','Şu parlak kırmızı arabaya bak!','parlak sarı bir araba','parlak sarı bir otobüs','slang','exclamation'),
(2238,'tr','Caminin birçok kubbesi var.','Caminin tek kubbesi var.','kubbeli görkemli bir cami','çölde bir cami','chill','none'),
(2245,'tr','Azıcık otlarla kaplı, o kadar.','Azıcık karla kaplı, o kadar.','otlarla kaplı bir kulübe','otlarla kaplı bir çimenlik','ironic','understatement'),
(2246,'tr','Vitrinde minyatür bir kulübe sergileniyor.','Vitrinde minyatür bir şato sergileniyor.','minyatür bir gece bahçesi','minyatür bir tren seti','business','none'),
(2247,'tr','İskoçya''da yalnız bir kilise var.','İskoçya''da yalnız bir şato var.','İskoçya''da bir kilise','İskoçya''da bir şato','chill','none'),
(2248,'tr','Zarifçe süzülüyor.','Zarifçe dans ediyor.','havada zarifçe süzülmek','sahnede zarif bir dans','chill','none'),
(2249,'tr','Dişlilerden bir steampunk şehir.','Camdan bir steampunk şehir.','pirinç steampunk kuleler','steampunk kostüm partisi','chill','none'),
(2250,'tr','Şehre uzun uzun bakıyor.','Denize uzun uzun bakıyor.','yağmurlu şehre uzun uzun bakmak','yıldızlı göğe uzun uzun bakmak','dramatic','none'),
(2251,'tr','Cennetin kıyafet kuralı: beyaz cübbe.','Cennetin kıyafet kuralı: siyah cübbe.','uzun beyaz bir cübbe','kapüşonlu bir cübbe','business','cliche'),
(2254,'tr','Donmuş bir saray. Selam Elsa!','Donmuş bir göl. Selam Elsa!','donmuş karlı bir saray','poşette donmuş bezelye','slang','exclamation'),
(2256,'tr','Bacakları tamamen mekanik.','Bacakları tamamen tahta.','mekanik kollar ve bacaklar','mekanik bir saat','nerd','none'),
(2257,'tr','Kaşları çok koyu.','Kaşları çok açık.','kalın koyu kaşlar','ince sarı kaşlar','chill','none'),
(2258,'tr','Kilisenin yüksek bir sivri kulesi var.','Kilisenin yuvarlak bir kubbesi var.','kilisenin yüksek sivri kulesi','şatoda bir sivri kule','chill','none'),
(2259,'tr','Beni hemen bu lagüne götür!','Beni hemen bu buzula götür!','palmiyeli turkuaz bir lagün','kışın donmuş bir lagün','dramatic','exclamation'),
(2260,'tr','Zavallı kayık, kimse onu istemiyor.','Zavallı gemi, kimse onu istemiyor.','boş, ahşap bir kayık','insan dolu bir kayık','dramatic','exaggeration'),
(2262,'tr','Noktalar ve çizgiler onları bağlıyor.','Noktalar ve çizgiler onları ayırıyor.','iki insanı bağlayan çizgiler','telefona bağlı bir kablo','nerd','none'),
(2268,'tr','Gergin bir ipin üstünde. Güvenlik ağı yok!','Bir merdivenin üstünde. Güvenlik ağı yok!','gergin ipte denge kurmak','sirkte gergin ip gösterisi','dramatic','exclamation'),
(2269,'tr','Bluzu bol ve beyaz.','Elbisesi bol ve beyaz.','bol beyaz bir bluz','dar siyah bir bluz','chill','none'),
(2271,'tr','Bir koridorda takılıyor.','Bir mutfakta takılıyor.','bir uzay gemisi koridoru','bir hastane koridoru','slang','none'),
(2273,'tr','Yırtık kot pantolon, tepeden tırnağa denim.','Yırtık kot pantolon, tepeden tırnağa siyah.','bol yırtıklı mavi kot pantolon','mavi kot pantolon ütülemek','slang','none'),
(2274,'tr','O dantel yaka ne kadar gösterişli!','O kürk yaka ne kadar gösterişli!','süslü bir dantel yaka','ayakkabı bağcığı bağlamak','gossip','none'),
(2275,'tr','Kombin güzel, spor ayakkabılar kocaman!','Kombin güzel, spor ayakkabılar minicik!','sokak stili bir kombin','düğün için bir kombin','flirt','exclamation'),
(2278,'tr','Yukarı, gökyüzüne bakıyor.','Yukarı, bir uçağa bakıyor.','yukarı, bulutlara bakmak','sözlükte kelimeye bakmak','chill','none'),
(2280,'tr','Gün batımında ona sarılıyor.','Arabada ona sarılıyor.','yelkenlide sarılmak','yeni bir fikre sarılmak','flirt','none'),
(2282,'tr','Gün batımında yelkencilik. Tam kafa dinlemelik.','Gün batımında sörf. Tam kafa dinlemelik.','gün batımında yelkencilik','fırtınada yelkencilik','slang','none'),
(2284,'tr','Tüyler mi? Cesur bir saç modeli.','İnciler mi? Cesur bir saç modeli.','tüylerden bir saç modeli','kısa bir saç modeli','flirt','none'),
(2285,'tr','Sweatshirt''ü kocaman.','Sırt çantası kocaman.','büyük mavi bir sweatshirt','sandalyede bir sweatshirt','chill','exaggeration'),
(2287,'tr','Kederle tek başına oturuyor.','Arabada tek başına oturuyor.','karanlık bir bahçede keder','cenazede keder','dramatic','none'),
(2288,'tr','Marinada crop top.','Kayak merkezinde crop top.','siyah bir crop top','beyaz bir crop top','chill','none'),
(2291,'tr','Sadece birkaç asteroit. Rahat ol.','Sadece birkaç kuş. Rahat ol.','süzülen asteroitler','Dünya''ya çarpan bir asteroit','ironic','understatement'),
(2295,'tr','Şu elbise kolları devasa!','Şu çizmeler devasa!','geniş beyaz kollar','kısa siyah kollar','dramatic','exclamation'),
(2296,'tr','Çiçekli elbisesi duvarla uyumlu!','Çizgili elbisesi duvarla uyumlu!','turuncu çiçekli bir elbise','çiçekli bir plaj gömleği','gossip','exaggeration'),
(2297,'tr','Dalgalar kıyıya çarpıyor.','Dalgalar tekneye çarpıyor.','kıyıda palmiyeler','kıyıda bir tekne','chill','none'),
(2300,'tr','Gitar alevler içinde!','Piyano alevler içinde!','alevler içinde bir gitar','alevler içinde bir ev','dramatic','exclamation'),
(2301,'tr','Mekik fırlatılıyor.','Uçak fırlatılıyor.','uzay mekiği fırlatmak','kâğıttan uçak fırlatmak','chill','none'),
(2302,'tr','Ağırlıksız ve rahat görünüyor.','Ağırlıksız ve korkmuş görünüyor.','ağırlıksız bir astronot','ağırlıksız bir tüy','chill','none'),
(2305,'tr','Deniz fenerine giden kayalık bir yol.','Şatoya giden kayalık bir yol.','kayalık bir burun','şezlonglu kayalık bir plaj','chill','none'),
(2306,'tr','Kırsal bölge hiç bitmiyor.','Şehir hiç bitmiyor.','kırsalda çocuklar','kırsaldan ayrılan çocuklar','chill','exaggeration'),
(2308,'tr','Viking bir kılıç tutuyor.','Viking bir balta tutuyor.','kürkler içinde bir Viking','gemide bir Viking','chill','none'),
(2310,'tr','Piyanodan bir ezgi yükseliyor.','Davuldan bir ezgi yükseliyor.','yükselen altın bir ezgi','düşen altın bir ezgi','dramatic','none'),
(2311,'tr','Vitray kocaman.','Vitray minicik.','yüksek vitray pencereler','vitray bir lamba','chill','none'),
(2312,'tr','Palmiyelerin yanında bir yarış arabası.','Çamların yanında bir yarış arabası.','kırmızı bir yarış arabası','kırmızı bir yarış atı','chill','none'),
(2313,'tr','Karavan neredeyse ev oradadır.','Turuncu çadır neredeyse ev oradadır.','turuncu bir karavan','şehirde bir karavan','chill','cliche'),
(2314,'tr','Hayaletin kostümü: tek bir eski çarşaf.','Hayaletin kostümü: tek bir eski havlu.','beyaz çarşaftan bir hayalet','şatoda bir hayalet','low_iq','cheap_quality'),
(2315,'tr','Bu manzara kâğıttan!','Bu manzara camdan!','kâğıttan bir manzara','bir manzara fotoğrafı','dramatic','exclamation'),
(2317,'tr','Kırmızı kapüşonu başında.','Kırmızı kapüşonu indirilmiş.','başa çekilmiş kırmızı kapüşon','bir arabanın kaputu','chill','none'),
(2318,'tr','Çok uzun bir kılıcı var.','Çok uzun bir mızrağı var.','uzun, kıvrık bir kılıç','uzun, düz bir kılıç','chill','none'),
(2322,'tr','Cam kırık!','Saat kırık!','kırık bir ayna portresi','alçıda kırık bir kol','dramatic','exclamation'),
(2324,'tr','Bir yıldız gibi şarkı söylüyor!','Bir yıldız gibi dans ediyor!','mikrofona şarkı söylemek','duşta şarkı söylemek','flirt','exaggeration'),
(2326,'tr','Prensin havalı mavi saçları var.','Prensin havalı pembe saçları var.','taçlı bir prens','at üstünde bir prens','slang','none'),
(2327,'tr','Bu araba ve palmiyeler çok havalı duruyor.','Bu bisiklet ve palmiyeler çok havalı duruyor.','gün batımında palmiyeler','bir adada palmiyeler','slang','none'),
(2328,'tr','Ne "mütevazı" bir taht!','Ne "mütevazı" bir yatak!','kocaman altın bir taht','boş, altın bir taht','ironic','exclamation'),
(2330,'tr','Sana çiçek vermek istiyor.','Sana pasta vermek istiyor.','üç sarı çiçek vermek','kırmızı güller vermek','flirt','guessing'),
(2333,'tr','Birbirlerine çok âşıklar!','Birbirlerine çok kızgınlar!','sonbahar yaprakları altında âşık','kumsalda âşık','dramatic','exclamation'),
(2340,'tr','Bu ev biraz tuhaf.','Bu araba biraz tuhaf.','tuhaf, uzun bir ev','tuhaf, eski bir tekne','chill','understatement'),
(2341,'tr','Çiçekler ölümü güzel gösteriyor.','Mumlar ölümü güzel gösteriyor.','çiçekler arasında ölüm','trafik kazasında ölüm','ironic','none'),
(2344,'tr','Evler biraz eğri.','Ağaçlar biraz eğri.','uzun, eğri evler','eğri bir resim çerçevesi','ironic','understatement'),
(2345,'tr','Ne uzun bir büyücü sakalı!','Ne kısa bir büyücü sakalı!','griler içinde yaşlı bir büyücü','kırmızılar içinde yaşlı bir büyücü','dramatic','exclamation'),
(2347,'tr','Bir ötegezegeni keşfediyor.','Derin bir mağarayı keşfediyor.','yabancı bir dünyayı keşfetmek','eski bir şatoyu keşfetmek','nerd','none'),
(2349,'tr','Kedi bile kostüm giymiş!','Köpek bile kostüm giymiş!','cadı kostümü giymiş','korsan kostümü giymiş','gossip','exclamation'),
(2350,'tr','Biri yüzler oymuş! Vay!','Biri isimler oymuş! Vay!','oyulmuş balkabağı yüzleri','oyulmuş tahta yüzler','low_iq','exclamation'),
(2351,'tr','Biri yeşil bir araba sürüyor.','Biri sarı bir araba sürüyor.','sonbahar yollarında araba sürmek','karda araba sürmek','chill','none'),
(2353,'tr','Mantarlar devasa, kanka.','Mantarlar minicik, kanka.','devasa pembe mantarlar','devasa pembe çiçekler','slang','none'),
(2354,'tr','Kocaman altın bir tören başlığı!','Kocaman gümüş bir tören başlığı!','kocaman altın tören başlığı','tören başlığını çıkarmak','dramatic','exclamation'),
(2356,'tr','Yol bir gezegene doğru uzanıyor.','Yol bir şatoya doğru uzanıyor.','dev bir gezegene doğru','dev bir şehre doğru','dramatic','none'),
(2357,'tr','Ev siyah beyaz.','Ev kırmızı beyaz.','siyah beyaz bir çizim','siyah beyaz bir film','chill','none'),
(2358,'tr','Çiftliğin kırmızı çatıları var.','Çiftliğin mavi çatıları var.','yamaçta bir çiftlik','inekli bir çiftlik','chill','none'),
(2359,'tr','Geleneksel kıyafetler giyiyorlar.','Modern kıyafetler giyiyorlar.','geleneksel Hint kıyafeti','geleneksel bir düğün pastası','chill','none'),
(2360,'tr','O kırmızı araba aşırı hızlı duruyor.','O kırmızı minibüs aşırı hızlı duruyor.','hızlı kırmızı bir araba','hızlı kırmızı bir tekne','slang','exaggeration'),
(2363,'tr','Gizemli bir dumana dönüşüyor.','Gizemli bir suya dönüşüyor.','dumandan gizemli bir kadın','kilitli, gizemli bir kapı','dramatic','none'),
(2364,'tr','Arkasında beyaz bir boğa var.','Arkasında beyaz bir at var.','kıvrık boynuzlu bir boğa','arenada bir boğa','chill','none'),
(2367,'tr','Bu araba azıcık kirli.','Bu otobüs azıcık kirli.','eski, kirli bir spor araba','kirli, eski bir otobüs','ironic','understatement'),
(2368,'tr','Bu plaj tam bir cennet.','Bu çöl tam bir cennet.','gün batımında tropikal bir cennet','kayakçılar için bir cennet','slang','none'),
(2371,'tr','Melek kedere gömülmüş.','Melek kitaba gömülmüş.','kederle dolu bir melek','neşeyle dolu bir melek','dramatic','none'),
(2372,'tr','Tamamen bitkin görünüyor.','Tamamen heyecanlı görünüyor.','bitkin bir işçi','şarjı bitmiş bir telefon','slang','none'),
(2373,'tr','Evren kalabalık görünüyor.','Evren bomboş görünüyor.','gezegenlerle dolu bir evren','yıldızsız bir evren','ironic','exaggeration'),
(2378,'tr','Şu an resmen rahatlıyor.','Şu an resmen koşuyor.','ayın altında rahatlamak','kumsalda rahatlamak','slang','none'),
(2379,'tr','Kırmızı yapraklar düşüyor.','Kırmızı elmalar düşüyor.','yağmurda düşen yapraklar','arabalara düşen kar','chill','none'),
(2380,'tr','Araba yangından kaçıyor!','Araba selden kaçıyor!','yanan bir ormandan kaçmak','yanan bir evden kaçmak','dramatic','exclamation'),
(2381,'tr','O pençeler gerçekten keskin!','O dişler gerçekten keskin!','dalda pençeler','bir kedinin pençeleri','dramatic','exclamation'),
(2382,'tr','Bak, kuyruğunda mavi pullar var.','Bak, kuyruğunda pembe pullar var.','mavi pullu bir kuyruk','terazide tartılmak','gossip','none'),
(2383,'tr','Her yerde ateş ve mücevher taşları!','Her yerde buz ve mücevher taşları!','ışıldayan renkli mücevher taşları','karanlık mağarada mücevher taşları','dramatic','exaggeration'),
(2384,'tr','Tepede minicik bir krallık.','Adada minicik bir krallık.','masallardan çıkmış bir krallık','hayvanlar âlemi','chill','none'),
(2385,'tr','Mor, uzaylı bir manzara.','Yeşil, uzaylı bir manzara.','mor bir uzaylı dünyası','uzay gemisinde bir uzaylı','nerd','none'),
(2386,'tr','Korkuluk gün batımına bakıyor.','Korkuluk bir dağa bakıyor.','metal bir balkon korkuluğu','merdivende bir korkuluk','chill','none'),
(2387,'tr','Ağaç bükülmüş. Havalı.','Ağaç dümdüz. Havalı.','bükülmüş yaşlı bir ağaç','bükülmüş metal bir çit','low_iq','none'),
(2388,'tr','Bu oyuncu pembeye bayılıyor.','Bu oyuncu yeşile bayılıyor.','pembeler içinde bir oyuncu','maviler içinde bir oyuncu','gossip','none'),
(2389,'tr','İnançla dua ediyor.','Kollarını açarak dua ediyor.','derin bir inançla dua etmek','inancını kaybetmek','chill','none'),
(2390,'tr','Kumsalda bu kadar şık olunur mu!','Gemide bu kadar şık olunur mu!','şık bir plaj stili','şık bir kışlık mont','flirt','exclamation'),
(2391,'tr','Efsane manzara, kızıl gökyüzü.','Efsane manzara, mavi gökyüzü.','kocaman aylı bir manzara','okul oyunu için bir dekor','slang','none'),
(2392,'tr','Hasır şapkayla bir gezinti mi? Şık.','Kırmızı şapkayla bir gezinti mi? Şık.','çiçekler arasında bir gezinti','kumsalda bir gezinti','flirt','none'),
(2393,'tr','Yüksek topuklu ayakkabılarla ofis stili.','Spor ayakkabılarla ofis stili.','bantlı siyah yüksek topuklu ayakkabılar','kutuda yüksek topuklu ayakkabılar','business','none'),
(2394,'tr','Bir yol seçmek zorunda.','Bir tekne seçmek zorunda.','doğru yolu seçmek','doğru elbiseyi seçmek','dramatic','guessing'),
(2395,'tr','Yeleğinin altın düğmeleri var.','Yeleğinin gümüş düğmeleri var.','siyah deri bir yelek','ceketin altında bir yelek','chill','none'),
(2396,'tr','O bağcıklı korse büyüleyici.','O bağcıklı eldiven büyüleyici.','bağcıklı bir korse','bağcıklı botlar','flirt','none'),
(2397,'tr','Bu oda çok kasvetli!','Bu oda çok güneşli!','kasvetli gotik bir oda','kasvetli, yağmurlu bir gün','dramatic','exclamation'),
(2398,'tr','Teras deniz manzarası sunuyor.','Teras şehir manzarası sunuyor.','deniz kenarında karo döşeli teras','dağlarda bir teras','business','none'),
(2400,'tr','İşte vahşi bir Viking!','İşte vahşi bir korsan!','vahşi, öfkeli bir bakış','denizde vahşi bir fırtına','dramatic','exclamation'),
(2401,'tr','Fantezi bir dünyaya giden yol.','Kalabalık bir şehre giden yol.','fantezi bir orman yolu','fantezi bir kitap kapağı','chill','none'),
(2404,'tr','Bu lotusun ortası turuncu.','Bu lotusun ortası mor.','beyaz bir lotus çiçeği','lotus yoga pozu','nerd','none'),
(2406,'tr','Bir cip, bir sürü çanta!','Bir bisiklet, bir sürü çanta!','çantalarla dolu bir cip','şehirde bir cip','dramatic','exaggeration'),
(2408,'tr','Hayal gücü gerçek bir yol açıyor.','Hayal gücü gerçek bir kapı açıyor.','bir hayal gücü kitabı','sıfır hayal gücü','chill','none'),
(2411,'tr','O taç ne kadar süslü!','O maske ne kadar süslü!','süslü altın bir taç','süslü ahşap bir kapı','gossip','none'),
(2412,'tr','Kol kola yürüyorlar.','Kol kola koşuyorlar.','kol kola yürümek','kol kola oturmak','chill','none'),
(2413,'tr','Bir kurt yavrusuna sarılıyor!','Bir ayı yavrusuna sarılıyor!','bir kurt yavrusuna sarılmak','kocaman bir kurda sarılmak','dramatic','exclamation'),
(2415,'tr','Tanrı çiçek çelenkleri takıyor.','Tanrı kâğıt çelenkler takıyor.','kırmızı çiçeklerden çelenkler','Noel ağacında çelenkler','chill','none'),
(2417,'tr','Karanlık ve aydınlık uyum içinde.','Kırmızı ve mavi uyum içinde.','bir uyum küresi','uyum içinde şarkı söylemek','nerd','none'),
(2418,'tr','Bence bu bir ötücü kuş.','Bence bu bir güvercin.','dalda bir ötücü kuş','çatıda bir ötücü kuş','low_iq','guessing'),
(2420,'tr','Bu köhne kule "güvenli".','Bu köhne köprü "güvenli".','evlerden köhne bir kule','köhne, eski bir sandalye','ironic','understatement'),
(2421,'tr','Bu mantar büyük. Hem de çok büyük.','Bu mantar küçük. Hem de çok küçük.','dev, soluk bir mantar','bayat ekmekte küf mantarı','low_iq','exaggeration'),
(2422,'tr','Tulumla kitap okuyor.','Tulumla uyuyor.','mavi kot tulum','boyaya bulanmış tulum','chill','none'),
(2424,'tr','Serviler sol tarafta yükseliyor.','Serviler sağ tarafta yükseliyor.','bir sıra servi ağacı','saksıda bir servi','nerd','none'),
(2425,'tr','Ürkütücü bir çerçevede kara bir kedi!','Ürkütücü bir çerçevede beyaz bir kedi!','siyah güllü bir çerçeve','bir bisiklet kadrosu','dramatic','exclamation'),
(2428,'tr','Üç monitör, maksimum odak.','İki monitör, maksimum odak.','üç büyük monitör','bir bebek monitörü','business','exaggeration'),
(2429,'tr','Kanka, erkek geyik derede.','Kanka, erkek geyik tarlada.','derede bir erkek geyik','karda bir erkek geyik','slang','none'),
(2430,'tr','Nehir kayaların yanından akıyor.','Nehir evlerin yanından akıyor.','kayaların arasından akan bir nehir','kasabanın içinden akan bir nehir','chill','none'),
(2432,'tr','Flamenko pozu ateş gibi!','Bale pozu ateş gibi!','yelpazeyle flamenko','sahnede flamenko','slang','exclamation'),
(2433,'tr','At dörtnala üstümüze koşuyor!','Eşek dörtnala üstümüze koşuyor!','dörtnala koşan beyaz bir at','dörtnala koşan siyah bir at','dramatic','exclamation'),
(2434,'tr','Natürmort çiçekleri gösteriyor.','Natürmort portakalları gösteriyor.','çiçekli bir natürmort','meyveli bir natürmort','nerd','none'),
(2435,'tr','Dere çakıl taşlarıyla dolu.','Dere balıklarla dolu.','pürüzsüz, yuvarlak çakıl taşları','kumsalda çakıl taşları','chill','none'),
(2439,'tr','Gece sokak ıslak.','Gece sokak kuru.','ıslak bir gece sokağı','ıslak, kumlu bir plaj','business','none'),
(2440,'tr','Elektrik her yerde!','Su her yerde!','elektrik kıvılcımları','bir elektrik faturası','dramatic','exaggeration'),
(2446,'tr','Kocaman fiyonklar, uzun ayakkabı bağcıkları!','Kocaman fiyonklar, kısa ayakkabı bağcıkları!','uzun sarı ayakkabı bağcıkları','kopmuş sarı ayakkabı bağcıkları','low_iq','exclamation'),
(2449,'tr','Sadece "birkaç" ışıl ışıl vitrin.','Sadece "birkaç" karanlık vitrin.','ışıl ışıl vitrinler','kırık bir vitrin','ironic','understatement'),
(2450,'tr','Suyun üstünde gök gürültülü fırtına.','Şehrin üstünde gök gürültülü fırtına.','su üstünde gök gürültülü fırtına','kasaba üstünde gök gürültülü fırtına','chill','none'),
(2451,'tr','Eyfel Kulesi''nin yanında bir kuş.','Eyfel Kulesi''nin yanında bir uçak.','nehir kıyısındaki Eyfel Kulesi','karlar altında Eyfel Kulesi','chill','none'),
(2452,'tr','Karlı yürüyüş çok romantik!','Yağmurlu yürüyüş çok romantik!','romantik, karlı bir yürüyüş','romantik bir akşam yemeği','flirt','exclamation'),
(2454,'tr','Dolambaçlı yolda fenerler var.','Düz yolda lambalar var.','dolambaçlı, taş döşeli bir yol','dolambaçlı bir dağ nehri','chill','none'),
(2455,'tr','Yeşil bir şort giyiyor.','Yeşil bir pantolon giyiyor.','yeşil kot şort','yeşil deniz şortu','chill','none'),
(2457,'tr','Hemşirenin stetoskopu var.','Hemşirenin not panosu var.','üniformalı bir hemşire','bebekli bir hemşire','chill','none'),
(2458,'tr','Pencereleri ışıklı bir çiftlik evi.','Pencereleri karanlık bir çiftlik evi.','gün batımında bir çiftlik evi','deniz kenarında bir çiftlik evi','chill','none'),
(2460,'tr','Mavi saksıda kır çiçekleri, tatlış.','Kırmızı saksıda kır çiçekleri, tatlış.','bir saksı kır çiçeği','bir tarla dolusu kır çiçeği','slang','none'),
(2462,'tr','Yıldızlı gökyüzünde bir ay var.','Yıldızlı gökyüzünde bir gökkuşağı var.','yıldızlı bir gece göğü','yıldızlı bir şehir gecesi','chill','none'),
(2463,'tr','Vadide pembe şakayıklar öne çıkıyor.','Vadide pembe laleler öne çıkıyor.','tepede pembe şakayıklar','vazoda şakayıklar','business','none'),
(2464,'tr','Desenler simetrik.','Desenler rengârenk.','simetrik yaprak desenleri','simetrik bir bina','nerd','none'),
(2465,'tr','Havada süzülüyor. Ne var bunda?','Yüzüyor. Ne var bunda?','masmavi gökte süzülmek','havuzda süzülmek','ironic','understatement'),
(2466,'tr','Elbisesi kristallerden yapılmış.','Elbisesi tüylerden yapılmış.','parlayan kristallerden bir elbise','kristal bir bardak su','chill','none'),
(2470,'tr','Saksofonun ağzı kıvrık.','Saksofonun ağzı düz.','havada süzülen bir saksofon','bir saksofoncu','nerd','none'),
(2471,'tr','Tam bir kitap kurdu.','Tam bir oyun bağımlısı.','elinde kitapla bir kitap kurdu','elinde telefonla bir kitap kurdu','gossip','none'),
(2472,'tr','Üniforması çok derli toplu duruyor.','Montu çok derli toplu duruyor.','bir okul üniforması','bir polis üniforması','chill','none'),
(2473,'tr','Çelenk kırmızı bir kapıda.','Çelenk mavi bir kapıda.','kapıda bir çelenk','başında bir çelenk','chill','none'),
(2474,'tr','Fırtınalı denizde çılgın köpükler.','Sakin denizde çılgın köpükler.','fırtınalı dalgalarda köpük','süt köpüklü kahve','dramatic','none'),
(2475,'tr','Çıplak ayaklı kız kitap okuyor.','Çıplak ayaklı kız dans ediyor.','divanda çıplak ayaklı bir kız','kumsalda çıplak ayaklı bir kız','chill','none'),
(2477,'tr','Rüzgâr yüzünden saçları dağınık.','Yağmur yüzünden saçları dağınık.','dağınık kahverengi saçlar','dağınık bir yatak odası','low_iq','blaming_someone'),
(2478,'tr','Doktor bize gülümsüyor.','Doktor bize bağırıyor.','gülümseyen çizgi film doktoru','ameliyatta bir doktor','chill','none'),
(2480,'tr','Arabada çok fazla hediye var!','Arabada çok fazla köpek var!','araba tavanında hediyeler','ağacın altında hediyeler','dramatic','exaggeration'),
(2481,'tr','Elinde bir küre tutuyor.','Elinde bir top tutuyor.','bir küre tutmak','bir kar küresi','chill','none'),
(2482,'tr','Bir şatoda bu kadar çok küçük kule!','Bir şatoda bu kadar çok bayrak!','sivri küçük şato kuleleri','bir tank kulesi','gossip','exclamation'),
(2483,'tr','Kitabın içinde kurutulmuş çiçekler var.','Kitabın içinde taze çiçekler var.','kitapta kurutulmuş çiçekler','kasede kurutulmuş meyveler','chill','none'),
(2484,'tr','Kilisenin yüksek bir çan kulesi var.','Şatonun yüksek bir çan kulesi var.','karda bir kilise çan kulesi','şehirde bir çan kulesi','chill','none'),
(2485,'tr','Karga adam uğursuz görünüyor.','Kedi adam uğursuz görünüyor.','karga başlı uğursuz bir figür','uğursuz bir kara kedi','dramatic','none'),
(2486,'tr','Hiyeroglifler duvarı kaplıyor.','Çiçekler duvarı kaplıyor.','hiyerogliflerle dolu bir duvar','ders kitabında hiyeroglifler','chill','none'),
(2490,'tr','Güzel şapka! Kardan adam üşüyor mu?','Güzel şapka! Köpek üşüyor mu?','şapkalı bir kardan adam','kardan adam yapmak','low_iq','guessing'),
(2492,'tr','Köy çok kalabalık!','Köy çok sessiz!','kalabalık, karlı bir köy','kalabalık bir yaz plajı','dramatic','exclamation'),
(2493,'tr','Çiftlik bir yorgan gibi dikilmiş.','Çiftlik bir bayrak gibi dikilmiş.','çiftlik desenli bir yorgan','yatakta bir yorgan','nerd','none'),
(2494,'tr','Viktorya dönemine ait bir sokak. Bu Sherlock mu?','Modern bir sokak. Bu Sherlock mu?','karlı, Viktorya dönemine ait bir sokak','Viktorya dönemi çay partisi','gossip','guessing'),
(2495,'tr','İki serçe saydım.','Dört serçe saydım.','dalda iki serçe','karda iki serçe','low_iq','none'),
(2497,'tr','Noel Baba mola veriyor.','Noel Baba banyo yapıyor.','hediyeleriyle Noel Baba','ren geyikleriyle Noel Baba','gossip','guessing'),
(2498,'tr','Aralarında şefkatli bir sarılma var.','Aralarında şefkatli bir öpücük var.','şefkatli bir kucaklaşma','yumuşacık bir biftek','chill','none'),
(2499,'tr','İki oyuncak ayı sarmaş dolaş.','İki oyuncak ayı kavga ediyor.','karda oyuncak ayılar','yatakta oyuncak ayılar','chill','none'),
(2500,'tr','Dizüstü bilgisayarda yazı yazıyor.','Telefonda yazı yazıyor.','dizüstü bilgisayarda yazmak','dizüstü bilgisayar taşımak','chill','none'),
(2501,'tr','Şiva bir kayanın üstünde meditasyon yapıyor.','Şiva bir teknede meditasyon yapıyor.','üç dişli mızraklı Şiva','kılıçlı Şiva','nerd','none'),
(2502,'tr','Ormanda yosunlarla kaplı kutsal bir mekân.','Çölde kumlarla kaplı kutsal bir mekân.','ormanda yosunlu kutsal mekân','şehirde kutsal bir mekân','chill','none'),
(2504,'tr','Krişna''nın tavus kuşu tüyü var.','Krişna''nın kartal tüyü var.','taçlı Krişna','flütlü Krişna','nerd','none'),
(2505,'tr','Yağmur, bir tüfek ve sıfır şikâyet.','Güneş, bir tüfek ve sıfır şikâyet.','uzun, dürbünlü bir tüfek','yerde bir tüfek','chill','understatement'),
(2506,'tr','Burada her şey geometrik.','Burada her şey mavi.','pembe geometrik şekiller','bir geometri sınavı','chill','none'),
(2509,'tr','Lavantaların arasından bir yol geçiyor.','Buğdayların arasından bir yol geçiyor.','sıra sıra mor lavantalar','bir şişe lavanta yağı','chill','none'),
(2510,'tr','Bir oğlan ve bir kedi için uyku vakti!','Bir oğlan ve bir köpek için uyku vakti!','battaniye altında uyku vakti','uyku vakti kitap okumak','dramatic','exclamation'),
(2511,'tr','Etraflarında kıvılcımlar uçuşuyor.','Etraflarında yapraklar uçuşuyor.','bir çiftin etrafında kıvılcımlar','prizden çıkan bir kıvılcım','flirt','none'),
(2512,'tr','Bu boyama kitabı seni bekliyor.','Bu fotoğraf albümü seni bekliyor.','bir boyama kitabı sayfası','bir boyama kitabı kapağı','chill','guessing'),
(2514,'tr','Kaseye otlar ekliyor.','Kaseye tuz ekliyor.','kurutulmuş otlar serpmek','taze otlar doğramak','chill','none'),
(2516,'tr','Yıl 2024.','Yıl 2025.','parlayan 2024 yılı','2025 yılı','chill','none'),
(2519,'tr','Bu arka bahçeyi gördün mü? Flamingo var!','Bu arka bahçeyi gördün mü? Salıncak var!','hareketli, küçük bir arka bahçe','arka bahçede sebze tarhı','gossip','exclamation'),
(2520,'tr','Yukarıdan kutsal bir ışık!','Aşağıdan kutsal bir ışık!','kutsal bir ışık huzmesi','kutsal bir nehir','dramatic','exclamation'),
(2522,'tr','Yoncaların dört yaprağı var.','Yoncaların üç yaprağı var.','dört yapraklı yoncalar','inekli bir yonca tarlası','nerd','none'),
(2523,'tr','Bu gece kar yağışı çok yoğun.','Bu gece yağmur yağışı çok yoğun.','köyün üstünde yoğun kar yağışı','şehirde hafif kar yağışı','chill','none'),
(2524,'tr','Elinde bir baston var.','Elinde kocaman bir şemsiye var.','bastona yaslanmak','doğa yürüyüşü için baston','chill','none'),
(2525,'tr','Anne, yavru ayısını kaldırıyor.','Anne, yavru tilkisini kaldırıyor.','yavruyu yukarı kaldırmak','ağır bir kutu kaldırmak','chill','none'),
(2526,'tr','Poseidon''un iki mızrağı var.','Poseidon''un iki kılıcı var.','dalgalardan yükselen Poseidon','gemi batıran Poseidon','nerd','none'),
(2527,'tr','DJ gaz maskesi takıyor. Neden?','DJ kar maskesi takıyor. Neden?','gaz maskesi ve kulaklık','gaz maskesi ve koruyucu gözlük','ironic','guessing'),
(2528,'tr','Mor silindir şapka mı? Cesur tercih.','Siyah silindir şapka mı? Cesur tercih.','parlak mor bir silindir şapka','sihirbazın silindir şapkası','gossip','understatement'),
(2529,'tr','Nazik bir yüzü var.','Nazik bir köpeği var.','nazik, sakin bir yüz','sakin, dingin bir deniz','chill','none'),
(2530,'tr','Güllerin arasında mum ışığı parlıyor.','Kitapların arasında mum ışığı parlıyor.','fenerde mum ışığı','pastada mum ışığı','chill','none'),
(2531,'tr','Gökyüzü bile onlar için parıldıyor.','Deniz bile onlar için parıldıyor.','parıldayan bir gece göğü','bardakta parıldayan su','flirt','none'),
(2532,'tr','Elbisesinin gri fırfırları var.','Elbisesinin kırmızı fırfırları var.','gri fırfırlı bir elbise','kırmızı bir şapkada fırfırlar','chill','none'),
(2533,'tr','Uzak taraf sisli.','Uzak taraf güneşli.','sisli, eski bir sokak','sisli bir dağ gölü','chill','none'),
(2536,'tr','Bu şempanze ciddi bir motorcuya benziyor.','Bu şempanze ciddi bir sörfçüye benziyor.','motosiklette bir şempanze','ağaçta bir şempanze','gossip','cliche'),
(2537,'tr','Kız bir uyku masalı okuyor.','Oğlan bir uyku masalı okuyor.','yatakta bir uyku masalı','televizyonda bir uyku masalı','chill','none'),
(2538,'tr','Kırmızı Başlıklı Kız kurda güveniyor.','Kırmızı Başlıklı Kız ayıya güveniyor.','Kırmızı Başlıklı Kız''ın kurdu','Kırmızı Başlıklı Kız''ın ninesi','gossip','guessing'),
(2539,'tr','Yapay zekâ onun kafasında yaşıyor.','Yapay zekâ onun arabasında yaşıyor.','yapay zekâlı bir robot','bir yapay zekâ uygulaması','nerd','none'),
(2540,'tr','Ne "rahat" bir zindan.','Ne "rahat" bir bahçe.','mumlu, karanlık bir zindan','şaraplı, karanlık bir mahzen','ironic','none'),
(2541,'tr','Bu merdiveni kimse temizlememiş.','Bu mutfağı kimse temizlememiş.','dökülen taş bir merdiven','dökülen taş bir köprü','ironic','understatement'),
(2543,'tr','Filin uzun fildişleri var.','Filin kısa fildişleri var.','iki uzun beyaz fildişi','uzun dişli bir mors','chill','none'),
(2544,'tr','Hanuman''ın altın bir tacı var.','Hanuman''ın gümüş bir tacı var.','altın asalı Hanuman','kılıçlı Hanuman','nerd','none'),
(2545,'tr','Maymun tapınıyor.','Maymun uyuyor.','taş basamaklarda tapınmak','bir futbol yıldızına tapmak','chill','none'),
(2546,'tr','Bu salon "epey" ferah.','Bu salon "epey" minicik.','ferah bir salon','ferah bir araba','ironic','understatement'),
(2547,'tr','Bu sinek mantarları devasa!','Bu sinek mantarları minicik!','dev kırmızı sinek mantarları','sepette sinek mantarları','slang','exclamation'),
(2548,'tr','Bir sürü fıçı. Bira mı acaba?','Bir sürü bisiklet. Bira mı acaba?','üst üste ahşap fıçılar','bir fıçı soğuk bira','low_iq','guessing'),
(2549,'tr','Baba oğul tezahürat yapıyor!','Baba oğul ağlıyor!','oğlunu taşıyan bir baba','alışveriş torbası taşıyan baba','dramatic','exclamation'),
(2551,'tr','Miami havası: palmiyeler ve neon.','Miami havası: kar ve neon.','neon ışıklı bir Miami sokağı','öğlen vakti Miami plajı','slang','none'),
(2552,'tr','Sanal gerçekliğin içinde.','Bir yüzme havuzunun içinde.','bir sanal gerçeklik gözlüğü','okulda sanal gerçeklik','chill','none'),
(2556,'tr','Bilgi: beyin parlıyor.','Bilgi: kalp parlıyor.','parlayan bir beyin','kavanozda bir beyin','nerd','none'),
(2557,'tr','Dur, yelkenli camdan mı?','Dur, yelkenli tahtadan mı?','camdan bir yelkenli','şişede bir yelkenli','low_iq','none'),
(2558,'tr','Uçuyor. Saf özgürlük!','Yüzüyor. Saf özgürlük!','denizin üstünde özgürlük','denizin altında özgürlük','dramatic','exclamation'),
(2559,'tr','Bu ağaçta madenî para yetişiyor!','Bu ağaçta elma yetişiyor!','ağaçtan düşen madenî paralar','kumbarada madenî paralar','dramatic','exclamation'),
(2560,'tr','Su üstünde yürümek mi? Mucize!','Ateş üstünde yürümek mi? Mucize!','okyanusta bir mucize','soğuk algınlığına mucize ilaç','dramatic','exclamation'),
(2562,'tr','Yağmurlu gece, yalnız dedektif.','Güneşli gün, yalnız dedektif.','yağmurda bir dedektif','olay yerinde bir dedektif','dramatic','cliche'),
(2563,'tr','Bir tüccar tahılı kontrol ediyor.','Bir tüccar paraları kontrol ediyor.','mum ışığında bir tüccar','pazarda bir tüccar','chill','none'),
(2564,'tr','Bu ortanca salkımı mavi.','Bu ortanca salkımı pembe.','mavi bir ortanca salkımı','vazoda bir ortanca','nerd','none'),
(2567,'tr','Azizenin başında beyaz bir örtü var.','Azizenin başında kırmızı bir örtü var.','haleli bir aziz','at üstünde bir aziz','chill','none'),
(2571,'tr','Oğlan huysuz. Yine.','Kız huysuz. Yine.','huysuz küçük bir oğlan','huysuz yaşlı bir adam','ironic','guessing'),
(2572,'tr','Üçgenler parlıyor.','Daireler parlıyor.','parlayan neon üçgenler','üçgen bir trafik levhası','chill','none'),
(2575,'tr','DJ tamamen anonim.','Şef tamamen anonim.','kapüşonlu anonim bir DJ','anonim bir mektup','slang','none'),
(2576,'tr','Paris''te kalbi kırık.','Roma''da kalbi kırık.','yağmurda kalbi kırık','karda kalbi kırık','dramatic','none'),
(2578,'tr','Vizör ayna gibi.','Vizör pencere gibi.','aynalı bir kask vizörü','vizörlü bir kep','chill','none'),
(2579,'tr','Gözlükleri aşırı tuhaf.','Şapkası aşırı tuhaf.','tuhaf, retro bir makine','tuhaf, eski bir araba','slang','exaggeration'),
(2580,'tr','Okçu yayını geriyor.','Okçu kılıcını çekiyor.','bir okçu heykeli','bir okçu tablosu','chill','none'),
(2581,'tr','Bambu flüt çalıyor.','Bambu davul çalıyor.','bambu flüt çalmak','bambu flüt oymak','chill','none'),
(2583,'tr','Ortamdan keyif alıyor.','Pizzadan keyif alıyor.','müzikten keyif almak','güneşten keyif almak','slang','none'),
(2584,'tr','Nehirde bir vaftiz bu.','Kilisede bir vaftiz bu.','nehirde vaftiz','kilisede vaftiz','chill','none'),
(2586,'tr','Gelmiş geçmiş en iyi dostluk: dev bir robot ve küçük bir kız.','Gelmiş geçmiş en iyi dostluk: dev bir köpek ve küçük bir kız.','beklenmedik bir dostluk','bir dostluk bilekliği','dramatic','exaggeration'),
(2594,'tr','Robot kendisi hakkında bir şeyler öğreniyor.','Robot kediler hakkında bir şeyler öğreniyor.','okumayı öğrenen bir robot','uçmayı öğrenen bir robot','low_iq','guessing'),
(2595,'tr','Biri kuyruklu piyanoyu dışarıda unutmuş.','Biri kuyruklu piyanoyu içeride unutmuş.','dışarıda bir kuyruklu piyano','içeride bir kuyruklu piyano','ironic','guessing'),
(2600,'tr','Kanka, iki böcek takılıyor.','Kanka, iki salyangoz takılıyor.','yapraklarda gezinen böcekler','çiçeklerin üstünde uçan böcekler','slang','none'),
(2601,'tr','Adam diz çökmüş, dua ediyor.','Adam oturmuş, dua ediyor.','taş zeminde diz çökmek','yumuşak bir kanepede diz çökmek','chill','none'),
(2602,'tr','Aşağı doğru çok hızlı kayak yapıyorlar.','Yukarı doğru çok hızlı kayak yapıyorlar.','dik bir yamaçta kayak yapmak','düz bir yolda kayak yapmak','slang','none'),
(2603,'tr','Notalar elle yazılmış.','Notalar yazıcıdan çıkmış.','eski, elle yazılmış notalar','yeni basılmış notalar','nerd','none'),
(2604,'tr','Cansız bir ağaç, yeşil bir ay.','Cansız bir ağaç, beyaz bir ay.','kayalarda cansız bir ağaç','saksıda cansız bir ağaç','dramatic','none'),
(2605,'tr','Bir bebeği kucağında sallıyor.','Bir kuzuyu kucağında sallıyor.','bebeği kucağında sallamak','telefonu kucağında tutmak','chill','none'),
(2606,'tr','Kafası baştan sona saat mekanizması.','Kafası baştan sona cam.','saat mekanizmasıyla dolu bir kafa','kurmalı oyuncak bir fare','nerd','exaggeration'),
(2607,'tr','Kediler resmi paltolar giyiyor.','Köpekler resmi paltolar giyiyor.','uzun palto giymiş kediler','tasma takmış kediler','business','none'),
(2611,'tr','Kemerinde metal bir toka var.','Çantasında metal bir toka var.','metal bir kemer tokası','emniyet kemeri takmak','chill','none'),
(2612,'tr','İki tomurcuk henüz açmamış.','İki tomurcuk çoktan açmış.','kapalı iki kırmızı tomurcuk','açık iki kırmızı tomurcuk','nerd','none'),
(2614,'tr','İki oğlan bir minarenin yanında.','İki kız bir minarenin yanında.','bir minareye doğru yürümek','bir minareye tırmanmak','chill','none'),
(2618,'tr','El yazısı bitişik harflerle.','El yazısı düz harflerle.','solmuş, bitişik el yazısı','düzgün, düz harfli el yazısı','nerd','none'),
(2621,'tr','Direkte bir sürü halat var.','Direkte bir sürü bayrak var.','halatlı, yüksek bir direk','korsan bayraklı bir direk','nerd','none'),
(2622,'tr','Minicik bir Özgürlük Anıtı!','Minicik bir Eyfel Kulesi!','mini bir Özgürlük Anıtı','Özgürlük Anıtı kostümü','dramatic','exclamation'),
(2623,'tr','Sarmaşık kitaplığı kaplıyor.','Kar kitaplığı kaplıyor.','sarmaşık kaplı bir kitaplık','sarmaşık kaplı bir şato','chill','none'),
(2626,'tr','Kel kafasında bir şehir yaşıyor.','Kel kafasında bir çiftlik yaşıyor.','profilden kel bir kafa','gözlüklü kel bir kafa','chill','none'),
(2629,'tr','Saçı iki örgü yapılmış.','Saçı iki topuz yapılmış.','iki uzun örgü','iki kısa, kıvırcık örgü','chill','none'),
(2631,'tr','Gözlüğünün yuvarlak mercekleri var.','Gözlüğünün hiç merceği yok.','yuvarlak, renkli mercekler','bir kamera merceği','chill','none'),
(2633,'tr','O ağaç tam bir disko. Işınlara bak!','O ağaç tam bir disko. Kuşlara bak!','renkli ışık ışınları','bir çatının ahşap kirişleri','low_iq','exaggeration'),
(2634,'tr','Her şişenin bir mantar tıpası var.','Her şişenin bir pipeti var.','mantar tıpalı şişeler','notlu bir mantar pano','chill','none'),
(2635,'tr','Manolya krem beyazı.','Manolya parlak sarı.','açmış bir manolya çiçeği','bir manolya ağacı','chill','none'),
(2641,'tr','Işınlar gökyüzünü dolduruyor!','Işınlar odayı dolduruyor!','altın ışık ışınları','pencereden giren ışınlar','dramatic','exclamation'),
(2648,'tr','Bu karınca benden büyük!','Bu arı benden büyük!','kocaman siyah bir karınca','kocaman bir karınca yuvası','low_iq','exaggeration'),
(2649,'tr','Şu koruyucu gözlükler devasa!','Şu küpeler devasa!','gözlerinde parlayan koruyucu gözlük','bir yüzme gözlüğü','dramatic','exclamation'),
(2651,'tr','Kırmızı çatıda beyaz benekler var.','Kırmızı çatıda siyah benekler var.','beyaz benekli bir şapka','beyaz benekli bir köpek','chill','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
