begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(2652,'tr','Paltosu hariç her şey gri!','Paltosu hariç her şey kırmızı!','yağmurda gri paltolar','karda gri paltolar','dramatic','exclamation'),
(2654,'tr','Kayışlar takıldı, Ay''a hazırız.','Kayışlar takıldı, denize hazırız.','geniş beyaz kayışlar','deri bir saat kayışı','chill','guessing'),
(2656,'tr','İki kırmızı otobüs. Tam Londra.','İki kırmızı tramvay. Tam Londra.','kırmızı çift katlı otobüs','kırmızı çift katlı tramvay','slang','cliche'),
(2657,'tr','Kuş bir kolajın parçası.','Kedi bir kolajın parçası.','kolajda bir kuş','eski fotoğraflardan kolaj','chill','none'),
(2658,'tr','Yumruğunu havaya kaldırıyor!','Kılıcını havaya kaldırıyor!','havaya kalkmış bir yumruk','bozuk para dolu bir yumruk','dramatic','exclamation'),
(2660,'tr','Sarmaşıklar kemerin üstünden sarkıyor.','Bayraklar kemerin üstünden sarkıyor.','taş kemerde sarmaşıklar','üzüm dolu bir sarmaşık','chill','none'),
(2661,'tr','Karolar bir satranç tahtası oluşturuyor.','Karolar bir gökkuşağı oluşturuyor.','siyah beyaz yer karoları','mavi beyaz duvar karoları','nerd','none'),
(2663,'tr','Gölgesi ne kadar uzun!','Gölgesi ne kadar kısa!','bir kovboyun uzun gölgesi','duvarda bir gölge','dramatic','exclamation'),
(2664,'tr','Biri tek bir yeni takipçi için boğuluyor.','Biri tek bir yeni takipçi için yüzüyor.','okyanusta boğulmak','ödevlere boğulmak','ironic','exaggeration'),
(2666,'tr','Basamaklar boyunca saksılar dizilmiş.','Basamaklar boyunca mumlar dizilmiş.','taş basamaklarda saksılar','pencere önünde saksılar','chill','none'),
(2669,'tr','Bir milyon demlik var, yemin ederim.','Bir milyon lamba var, yemin ederim.','porselen demlik rafları','ocakta bir demlik','gossip','exaggeration'),
(2670,'tr','Masanın tek bir çekmecesi var.','Masanın üç çekmecesi var.','topuzlu bir çekmece','çorap dolu bir çekmece','chill','none'),
(2673,'tr','O kafeste, kuş özgür.','Kuş kafeste, o özgür.','kafeste oturmak','kafes temizlemek','ironic','none'),
(2675,'tr','Kedi bir pençesini kitaba koymuş, tıpkı bir profesör gibi.','Kedi bir pençesini fincana koymuş, tıpkı bir profesör gibi.','kitabın üstünde bir pençe','kalemin üstünde bir pençe','nerd','exaggeration'),
(2678,'tr','Kâğıtlar laptopu yiyip bitiriyor.','Kâğıtlar yatağı yiyip bitiriyor.','kâğıt yığınları','kâğıttan bir uçak','dramatic','exaggeration'),
(2679,'tr','Müthiş aceleyle koşturuyor!','Hiç acele etmiyor!','aceleyle koşmak','aceleyle yemek yemek','dramatic','exclamation'),
(2682,'tr','Kaplan saldırıyor!','Aslan saldırıyor!','saldıran bir kaplan','saldırıya uğrayan bir kaplan','dramatic','exclamation'),
(2683,'tr','Yüz boyası bir mandala.','Yüz boyası bir örümcek.','yüz boyasıyla mandala','palyaçoda yüz boyası','nerd','none'),
(2684,'tr','Bu maskeler karnaval için.','Bu maskeler ameliyat için.','karnaval göz maskeleri','karnaval geçit töreni','chill','guessing'),
(2685,'tr','Maskeli balo maskeleri altın rengi.','Maskeli balo maskeleri kırmızı.','altın maskeli balo maskeleri','maskeli balo davetiyesi','business','none'),
(2686,'tr','Esmer kadın çok sakin görünüyor.','Sarışın kadın çok sakin görünüyor.','mavili bir esmer kadın','kırmızılı bir esmer kadın','flirt','none'),
(2687,'tr','Yüzme havuzlu villa. Çok seçkin.','Tenis kortlu villa. Çok seçkin.','turkuaz bir yüzme havuzu','kapalı bir yüzme havuzu','business','none'),
(2688,'tr','Rastaları çok uzun.','Rastaları çok kısa.','göğsü geçen uzun rastalar','şapka altında kısa rastalar','chill','none'),
(2690,'tr','Tacı elmas dolu.','Tacı tüy dolu.','elmaslarla dolu bir taç','bir elmas yüzük','gossip','exaggeration'),
(2691,'tr','Trençkot giyiyor.','Kayak montu giyiyor.','bej bir trençkot','ıslak bir trençkot','chill','none'),
(2693,'tr','Kitaptan bir ağaç büyüyor!','Fincandan bir ağaç büyüyor!','kitaptan büyümek','saksıdan büyümek','dramatic','exclamation'),
(2694,'tr','Kafa patlatarak düşünüyor.','Katıla katıla gülüyor.','karanlıkta düşünmek','akşam yemeğini düşünmek','chill','none'),
(2698,'tr','Açık panjurlar, sıcak kahve, mükemmel.','Açık panjurlar, soğuk bira, mükemmel.','açılmış yeşil panjurlar','gece için kapanmış panjurlar','chill','cliche'),
(2702,'tr','Doğa paketi: şelale dahil.','Doğa paketi: kale dahil.','şelaleli bir doğa','işlek yollu bir doğa','business','none'),
(2703,'tr','Karda dev bir dikilitaş.','Çölde dev bir dikilitaş.','karda siyah bir dikilitaş','meydanda bir dikilitaş','dramatic','none'),
(2704,'tr','Geriye sadece moloz ve sis kaldı.','Geriye sadece kar ve sis kaldı.','sisin içinde moloz','kepçeyle moloz temizlemek','dramatic','none'),
(2709,'tr','Kadife çiçeğinden bir çelenk takmış.','Gülden bir çelenk takmış.','kadife çiçeği çelengi','saksıda kadife çiçekleri','chill','none'),
(2711,'tr','Nilüfer yaprakları etrafında yüzüyor.','Tekneler etrafında yüzüyor.','gölette nilüfer yaprakları','kurbağalı nilüfer yaprakları','chill','none'),
(2712,'tr','Yarısı yüz, yarısı anatomi.','Yarısı yüz, yarısı çiçek.','bir anatomi çizimi','bir anatomi sınavı','nerd','none'),
(2714,'tr','Limonlar, deniz ve hasır şapka.','Portakallar, deniz ve hasır şapka.','geniş bir hasır şapka','korkuluğun hasır şapkası','chill','none'),
(2716,'tr','Ağaçların arkasında Big Ben, efsane.','Gemilerin arkasında Big Ben, efsane.','Big Ben manzarası','gece yarısı Big Ben','slang','none'),
(2717,'tr','Parlamento, Thames kıyısında.','Parlamento, Seine kıyısında.','İngiliz Parlamento Binası','deniz kenarında bir parlamento','nerd','none'),
(2718,'tr','Piyanonun yarısı teknik çizim.','Arpın yarısı teknik çizim.','bir piyanonun teknik çizimi','bir evin teknik çizimi','nerd','none'),
(2722,'tr','Sarmal, kovboyun altında.','Sarmal, kovboyun üstünde.','yıldızlardan bir sarmal','sarmal bir merdiven','chill','none'),
(2723,'tr','Adam resmen çok öfkeli!','Kadın resmen çok öfkeli!','çok öfkeli bir savaşçı','çok öfkeli bir ejderha','dramatic','exclamation'),
(2724,'tr','Bu sisli cangılın hâkimi o.','Bu sisli çölün hâkimi o.','sisli yeşil bir cangıl','kaplan dolu bir cangıl','dramatic','none'),
(2725,'tr','Bir kayanın üstünde çömelmiş.','Bir ağacın üstünde çömelmiş.','kayanın tepesinde çömelmek','mağarada yere çömelmek','chill','none'),
(2726,'tr','İki sıra boncuk takmış.','İki sıra çıngırak takmış.','turuncu boncuklu kolyeler','ipteki boncukları saymak','chill','none'),
(2728,'tr','Bir tavşan bir tilkiye sarılıyor.','Bir tavşan bir kediye sarılıyor.','yavru bir tilkiye sarılmak','yavru bir tavşana sarılmak','chill','none'),
(2729,'tr','Kristal küresi parlıyor.','Kristal küresi kırık.','kristal küreye dokunmak','kırık bir kristal küre','chill','none'),
(2731,'tr','Bilgi: gözbebeği siyahtır.','Bilgi: gözbebeği beyazdır.','siyah bir gözbebeği','ailenin gözbebeği','nerd','none'),
(2732,'tr','Torun, dedesinin kucağında oturuyor.','Torun bir sandalyede oturuyor.','dedesinin kucağında torun','plajda bir torun','chill','none'),
(2733,'tr','Ordu hücuma geçiyor!','Ordu geri çekiliyor!','atlı bir ordu','yaya bir ordu','dramatic','exclamation'),
(2734,'tr','Kedinin minicik pembe bir burnu var.','Kedinin minicik siyah bir burnu var.','küçük pembe bir burun','küçük siyah bir burun','chill','none'),
(2735,'tr','Patlama çok eğlenceli!','Sel çok eğlenceli!','laboratuvarda bir patlama','bir renk patlaması','dramatic','exclamation'),
(2736,'tr','Gökbilimci yaşlı bir adam.','Gökbilimci genç bir adam.','yaşlı bir gökbilimci','teleskop başında bir gökbilimci','chill','none'),
(2737,'tr','Bu, uzayda bir kara delik.','Bu, uzayda kara bir ay.','uzayda bir kara delik','bütçedeki kara delik','nerd','none'),
(2738,'tr','Bu egzotik kuş seni takmamak için kulaklık takmış.','Bu egzotik kuş seni takmamak için güneş gözlüğü takmış.','kulaklıklı egzotik bir kuş','kafeste egzotik kuşlar','ironic','guessing'),
(2740,'tr','Bıyığı kar gibi bembeyaz.','Bıyığı kömür gibi simsiyah.','kalın beyaz bir bıyık','ince siyah bir bıyık','dramatic','cliche'),
(2741,'tr','Programcı gece kod yazıyor.','Programcı öğlen kod yazıyor.','kod yazan bir programcı','spor salonunda bir programcı','nerd','cliche'),
(2742,'tr','Koda odaklanmış.','Bir kitaba odaklanmış.','ekrana odaklanmak','oyuna odaklanmak','nerd','none'),
(2743,'tr','Dik kaya duvarları mı? Yok, sağ ol.','Dik kum duvarları mı? Yok, sağ ol.','dik kaya yüzeyleri','dik bir kasaba sokağı','slang','guessing'),
(2744,'tr','Bilgi: tavus kuşlarının tepeliği vardır.','Bilgi: tavus kuşlarının tepeliği yoktur.','ince tüylerden bir tepelik','bir miğfer tepeliği','nerd','cliche'),
(2745,'tr','Avluyu eski taşlar dolduruyor.','Avluyu eski arabalar dolduruyor.','taş döşeli bir avlu','masalı bir avlu kafesi','chill','none'),
(2747,'tr','Tombul bebeğin elinde bir gürz var.','Tombul bebeğin elinde bir yay var.','tombul bir bebek tanrı','tombul bir köpek yavrusu','chill','none'),
(2749,'tr','Barda şıkça oturuyor.','Arabada şıkça oturuyor.','barda oturmak','bir protein bar','flirt','none'),
(2750,'tr','Ev bitkisi kitapların üstünde duruyor.','Ev bitkisi bir televizyonun üstünde duruyor.','rafta bir ev bitkisi','yerde bir ev bitkisi','chill','none'),
(2751,'tr','Bu bitki aşırı dikenli.','Bu bitki aşırı yumuşak.','saksıda dikenli bir bitki','dikenli top kaktüs','slang','none'),
(2752,'tr','Fare Almanya için oynuyor!','Kedi Almanya için oynuyor!','bir Almanya taraftarı','bir Almanya haritası','low_iq','guessing'),
(2753,'tr','Bu kumbara zengin!','Bu kumbara meteliksiz!','büyük pembe bir kumbara','kırık bir kumbara','slang','exaggeration'),
(2754,'tr','Gün batımında ne çok buhar!','Gün batımında ne çok kar!','gemi bacasından beyaz buhar','ev bacasından beyaz duman','dramatic','exclamation'),
(2757,'tr','İlham dolu bir piyano.','İlham dolu bir mutfak.','ani bir ilham','bir kitaptan ilham','chill','none'),
(2758,'tr','Çölde taştan bir büst.','Cangılda taştan bir büst.','devasa bir taş büst','müzede bir büst','nerd','none'),
(2759,'tr','Gerçek bir kahraman gibi dikiliyor.','Gerçek bir kahraman gibi oturuyor.','kayanın üstünde bir kahraman','at üstünde bir kahraman','dramatic','cliche'),
(2762,'tr','Bir figür buğdayların içinde yürüyor.','Bir figür karın içinde yürüyor.','olgun bir buğday tarlası','bir somun buğday ekmeği','chill','none'),
(2765,'tr','Bebek gülümsüyor.','Bebek ağlıyor.','flütle gülümsemek','annesine gülümsemek','chill','none'),
(2770,'tr','3 numara fena terliyor!','7 numara fena terliyor!','koşudan sonra terlemek','saunada terlemek','dramatic','exclamation'),
(2771,'tr','Fare dondurma yiyor!','Fare peynir yiyor!','külah dondurma yemek','peynirli sandviç yemek','dramatic','exclamation'),
(2776,'tr','Meşaleyi havaya kaldırmış.','Bayrağı havaya kaldırmış.','havada yanan bir meşale','mağarada bir meşale','chill','none'),
(2777,'tr','Baş sargısında büyük bir broş var.','Baş sargısında büyük bir çiçek var.','büyük gümüş bir broş','palto üstünde bir broş','chill','none'),
(2779,'tr','İrisi mavi-yeşil.','İrisi koyu kahverengi.','mavi-yeşil bir iris','mor bir iris çiçeği','chill','none'),
(2781,'tr','Kadın bir sürü eşya taşıyor!','Adam bir sürü eşya taşıyor!','ağır bir çanta taşımak','ağır bir kutu taşımak','dramatic','exclamation'),
(2782,'tr','Bu gravür baştan sona çizgi.','Bu gravür baştan sona nokta.','ince çizgili bir gravür','yüzük üstünde bir gravür','nerd','none'),
(2788,'tr','Taç yapraklarını üflüyor.','Mumları üflüyor.','yaprak ve kelebek üflemek','mumları üflemek','chill','none'),
(2791,'tr','Kafası şeffaf. Havalı!','Kafası altın. Havalı!','şeffaf bir kafatası kubbesi','şeffaf bir yağmurluk','slang','exclamation'),
(2793,'tr','Tepede iki iş adamı var.','Tepede beş iş adamı var.','merdiven çıkan bir iş adamı','asansörde bir iş adamı','business','none'),
(2794,'tr','Veteriner bir kedi tutuyor.','Veteriner bir köpek tutuyor.','kediye sarılan bir veteriner','çiftlikte bir veteriner','chill','none'),
(2795,'tr','Baş aşağı tırmanıyor!','Baş aşağı uyuyor!','uçurumun altında tırmanmak','merdivene tırmanmak','dramatic','exclamation'),
(2800,'tr','O büyük baloncuğu patlatabilir miyim?','O büyük balonu patlatabilir miyim?','gökyüzünde bir baloncuk','bardakta bir baloncuk','low_iq','guessing'),
(2801,'tr','Farları turuncu yanıyor.','Farları mavi yanıyor.','karda turuncu farlar','karlı bir arabada farlar','chill','none'),
(2803,'tr','Yüzü psikedelik görünüyor!','Yüzü gri ve donuk görünüyor!','psikedelik bir portre','psikedelik bir araba','dramatic','exclamation'),
(2805,'tr','Bu adam bir şaheser çizecek, kesin.','Bu kadın bir şaheser çizecek, kesin.','resim çizmek','harita çizmek','ironic','guessing'),
(2806,'tr','Yürümeye başlayan çocuk altın bir sarık takmış.','Yürümeye başlayan çocuk altın bir miğfer takmış.','tüylü minik bir çocuk','pusetteki minik bir çocuk','chill','none'),
(2808,'tr','İş kadını gülümsüyor.','İş kadını ağlıyor.','arabasının yanında bir iş kadını','trende bir iş kadını','business','none'),
(2809,'tr','Küçük bir fincan tutuyor.','Küçük bir demlik tutuyor.','iki elinde bir fincan','tabağında bir fincan','chill','none'),
(2810,'tr','Tek çalışma alanında iki kahve!','Tek çalışma alanında iki laptop!','rahat bir çalışma alanı','ortak ofis çalışma alanı','ironic','exclamation'),
(2811,'tr','Hologram bir arabaya dokunuyor.','Oyuncak bir arabaya dokunuyor.','bir arabanın hologramı','kart üstünde bir hologram','nerd','none'),
(2812,'tr','Dev ekranda bir drone var.','Dev ekranda bir uçak var.','ekranda bir drone','tarlanın üstünde bir drone','chill','none'),
(2814,'tr','Bulutların içinde arkaya yaslanmış.','Denizin içinde arkaya yaslanmış.','oymalı koltukta arkaya yaslanmak','kanepede arkaya yaslanmak','chill','none'),
(2815,'tr','Savaşa hazır.','Yatmaya hazır.','savaşa hazır','denizde bir savaş','chill','none'),
(2817,'tr','Sulama kabının üstünde çiçekler var.','Demliğin üstünde çiçekler var.','çiçekli bir sulama kabı','su dolu bir sulama kabı','chill','none'),
(2818,'tr','Para yağıyor!','Madeni para yağıyor!','para dolu bir masa','yemek dolu bir masa','dramatic','exaggeration'),
(2819,'tr','Parlayan yüzükleri altın rengi.','Parlayan yüzükleri yeşil.','parlayan altın yüzükler','parlayan kırmızı gözler','chill','none'),
(2820,'tr','Bir kitabı paylaşıyorlar.','Bir pizzayı paylaşıyorlar.','kitap paylaşmak','sıra paylaşmak','chill','none'),
(2823,'tr','Rüzgâr sıfır: su durgun.','Rüzgâr sıfır: su dalgalı.','durgun suda bir tekne','kasabada durgun bir gece','nerd','none'),
(2824,'tr','Gece kulübü şimdi tıklım tıklım.','Gece kulübü şimdi bomboş.','neon ışıklı bir gece kulübü','gece kulübü fedaisi','gossip','none'),
(2825,'tr','Etrafı kitaplarla çevrili!','Etrafı oyuncaklarla çevrili!','kitap duvarlarıyla çevrili','oyuncak duvarlarıyla çevrili','dramatic','exclamation'),
(2826,'tr','Sarı kurdele ona çok yakışmış.','Kırmızı kurdele ona çok yakışmış.','sarı bir saç kurdelesi','sarı bir hediye kurdelesi','flirt','none'),
(2827,'tr','Adam uyukluyor. Sanat yorucu iş.','Adam uyukluyor. Matematik yorucu iş.','masada uyuklamak','kanepede uyuklamak','gossip','bad_excuse'),
(2829,'tr','Kütüphanede raflara göz gezdiriyor.','Bir dükkânda raflara göz gezdiriyor.','kütüphane raflarına göz gezdirmek','internete göz gezdirmek','chill','none'),
(2831,'tr','Güneş bile neşeli!','Yağmur bile neşeli!','gülümseyen neşeli bir güneş','neşeli, yağmurlu bir gün','low_iq','exclamation'),
(2833,'tr','Tükenmişlik: kafasından buhar çıkıyor.','Tükenmişlik: çayından buhar çıkıyor.','masa başında tükenmişlik','spor salonunda tükenmişlik','dramatic','exaggeration'),
(2837,'tr','Kız bir kitapçıda.','Kız bir oyuncakçıda.','tıklım tıklım bir kitapçı','kitapçı kafesinin tezgâhı','chill','none'),
(2838,'tr','Yanaklarında gökkuşağı renkli sim.','Yanaklarında siyah sim.','yanaklarda gökkuşağı simi','bir kartın üstünde sim','chill','none'),
(2840,'tr','Koca bir şehir tek bir tomarda!','Koca bir orman tek bir tomarda!','tomarda bir şehir','şişede bir tomar','gossip','exclamation'),
(2847,'tr','Ağaç gibi akciğerler. Pek şiirsel.','Yıldız gibi akciğerler. Pek şiirsel.','ağaç dalı gibi akciğerler','röntgende akciğerler','ironic','none'),
(2850,'tr','Adamın davul seti dev gibi!','Adamın gitarı dev gibi!','büyük bir davul seti','tek bir mehter davulu','slang','exclamation'),
(2856,'tr','Ne çok klima var!','Ne çok çiçeklik var!','klima dış üniteleri','bir araba kliması','dramatic','exclamation'),
(2859,'tr','Mağarada meditasyon yapıyor.','Sahilde meditasyon yapıyor.','mağarada meditasyon yapmak','dağda meditasyon yapmak','chill','none'),
(2861,'tr','Bil bakalım kim kitap okuyor?','Bil bakalım kim harita okuyor?','kanepede okumak','yatakta okumak','gossip','none'),
(2867,'tr','O küre kıvılcım dolu!','O küre su dolu!','dev bir cam küre','taştan bir küre','dramatic','exclamation'),
(2877,'tr','Halata tırmanıyor.','Merdivene tırmanıyor.','halata tırmanmak','ağaca tırmanmak','chill','none'),
(2887,'tr','Havai fişekler 2025''i karşılıyor!','Havai fişekler 2024''ü karşılıyor!','çatıların üstünde havai fişekler','denizin üstünde havai fişekler','dramatic','exclamation'),
(2890,'tr','Bugün ren geyiği yok, Noel Baba kayak yapıyor.','Bugün ren geyiği yok, Noel Baba yürüyor.','yamaçta kayak yapmak','göl boyunca kayak yapmak','ironic','guessing'),
(2892,'tr','Elinde bir maytap var.','Elinde bir mum var.','yanan bir maytap tutmak','pastada bir maytap','chill','none'),
(2894,'tr','Adam bir kuzu taşıyor.','Adam bir köpek taşıyor.','beyaz bir kuzu taşımak','annesiyle bir kuzu','chill','none'),
(2897,'tr','Noel Baba nerede? Kızağını bırakıp gitmiş.','Noel Baba nerede? Arabasını bırakıp gitmiş.','hediye dolu bir kızak','ren geyikli bir kızak','gossip','guessing'),
(2898,'tr','Çölü bir sfenks koruyor.','Çölü bir deve koruyor.','çölde piramitler','çölde yol gezisi','dramatic','none'),
(2900,'tr','Karşısında dev bir kurt duruyor.','Karşısında dev bir ayı duruyor.','parlayan dev bir kurt','gece uluyan kurtlar','chill','none'),
(2906,'tr','Büyük bir kutu taşıyor.','Büyük bir bitki taşıyor.','büyük bir kutu taşımak','bebek taşımak','chill','none'),
(2908,'tr','Devasa bir kitap havada süzülüyor.','Devasa bir balon havada süzülüyor.','havada süzülen devasa bir kitap','bir masal devi','chill','none'),
(2909,'tr','Bilim insanı moru çok seviyor.','Bilim insanı yeşili çok seviyor.','çılgın bir bilim insanının laboratuvarı','televizyonda bir bilim insanı','gossip','guessing'),
(2910,'tr','Ne çok kitap! Kitaplık dolu!','Ne çok oyuncak! Kitaplık dolu!','rengârenk bir kitaplık','boş bir kitaplık','low_iq','exclamation'),
(2915,'tr','Ekip çiçek dikiyor.','Ekip çiçek topluyor.','turuncu çiçekler dikmek','turuncu çiçekler toplamak','business','none'),
(2925,'tr','Şu gaga uzun. Hem de çok uzun.','Şu gaga kısa. Hem de çok kısa.','uzun sivri bir gaga','kısa kıvrık bir gaga','low_iq','exaggeration'),
(2928,'tr','Üstünde bir uzay gemisi uçuyor.','Üstünde büyük bir ejderha uçuyor.','devasa soluk bir uzay gemisi','yakına inen bir uzay gemisi','chill','none'),
(2937,'tr','Astronot süzülüyor.','Astronot koşuyor.','derin uzayda bir astronot','Ay''da bir astronot','chill','none'),
(2942,'tr','Turuncu bir gezegen var.','Yeşil bir gezegen var.','parlayan turuncu bir gezegen','halkalı bir gezegen','nerd','none'),
(2949,'tr','Bir astronot güneş tutulması görüyor.','Bir astronot gökkuşağı görüyor.','güneş tutulması izlemek','bir ay tutulması','nerd','none'),
(2950,'tr','Radyodan kelebekler uçuşuyor!','Radyodan arılar uçuşuyor!','eski bir radyo','bir radyo istasyonu','dramatic','exclamation'),
(2951,'tr','İki el neredeyse birbirine değiyor!','İki ayak neredeyse birbirine değiyor!','neredeyse değen iki el','tokalaşan iki el','dramatic','exclamation'),
(2952,'tr','Sarı pelerin, süper kahraman demek. Basit.','Kırmızı pelerin, süper kahraman demek. Basit.','siyah zırhlı bir süper kahraman','maskeli bir süper kahraman','low_iq','none'),
(2964,'tr','Gözleri kapalı, nefes alıyor.','Gözleri kapalı, uyuyor.','karanlıkta nefes almak','cama hohlamak','chill','none'),
(2967,'tr','Bu veterinerin mutlu bir hastası var!','Bu veterinerin mutlu bir kedi yavrusu var!','bulldoglu bir veteriner','kedi yavrulu bir veteriner','slang','exclamation'),
(2971,'tr','Bir sürü yapışkanlı not. Ne kadar da "düzenli".','Bir sürü fotoğraf. Ne kadar da "düzenli".','camda yapışkanlı notlar','buzdolabında yapışkanlı notlar','ironic','exaggeration'),
(2973,'tr','Birinin aklına az önce bir fikir geldi!','Biri az önce bir kahve kaptı!','parlak, yeni bir fikir','akşam yemeği için bir fikir','slang','exclamation'),
(2980,'tr','Dev bir teleskop kullanıyor.','Dev bir kamera kullanıyor.','dev bir pirinç teleskop','küçük plastik bir teleskop','nerd','none'),
(2981,'tr','Bu hortum koddan yapılmış.','Bu hortum tozdan yapılmış.','koddan yapılmış bir hortum','çiftliğin üstünde bir hortum','nerd','none'),
(2987,'tr','Altın rengi robot pek "alçakgönüllü".','Gümüş rengi robot pek "alçakgönüllü".','altın rengi zırhlı bir robot','altın bir alyans','ironic','understatement'),
(3003,'tr','Kalabalık ellerini kaldırmış.','Kalabalık ellerini indirmiş.','elleri havada bir kalabalık','stadyumda bir kalabalık','chill','none'),
(3019,'tr','Kız bize gülümsüyor.','Oğlan bize gülümsüyor.','kameraya gülümsemek','bir köpeğe gülümsemek','chill','none'),
(3022,'tr','Satranç birazcık zor, o kadar.','Poker birazcık zor, o kadar.','bir satranç oyunu','bir satranç kulübü','ironic','understatement'),
(3024,'tr','El ele tutuşuyorlar.','El çırpıyorlar.','arkadan el ele tutuşmak','masada el ele tutuşmak','flirt','none'),
(3027,'tr','Yaşlı adamı iyileştiriyor.','Genç adamı iyileştiriyor.','yaşlı adamın gözlerini iyileştirmek','genç adamın bacağını iyileştirmek','chill','none'),
(3034,'tr','Tek başına ders çalışıyor.','Tek başına uyuyor.','sınıfta ders çalışmak','kütüphanede ders çalışmak','chill','none'),
(3035,'tr','Öğrenciler sınav oluyor.','Öğrenciler oyun oynuyor.','sınav olmak','ehliyet sınavı','chill','none'),
(3040,'tr','Bu iş yığını çılgınlık!','Bu yemek yığını çılgınlık!','bir kâğıt yığını','bir kıyafet yığını','slang','exclamation'),
(3041,'tr','Masasında endişeli görünüyor.','Yatağında endişeli görünüyor.','işte endişeli bir çocuk','hava için endişeli','chill','none'),
(3049,'tr','Büyük bir sorusu var.','Büyük bir sandviçi var.','baloncukta bir soru','sınavda bir soru','chill','none'),
(3052,'tr','Düşünüyor, çalışmıyor.','Uyuyor, çalışmıyor.','okul sırasında düşünmek','mutfak masasında düşünmek','slang','guessing'),
(3057,'tr','Parkta yürüyor.','Parkta koşuyor.','patikada yürümek','sahilde yürümek','chill','none'),
(3059,'tr','Kuzey ışıkları başka bir vibe.','Havai fişekler başka bir vibe.','dağların üstünde kuzey ışıkları','şehrin üstünde kuzey ışıkları','slang','none'),
(3061,'tr','Bir plağın üstünde süzülüyor.','Bir piyanonun üstünde süzülüyor.','dönen bir plak','kırık bir plak','chill','none'),
(3062,'tr','DJ plak miksliyor.','DJ plak imzalıyor.','pikap başında bir DJ','radyoda bir DJ','slang','none'),
(3063,'tr','Müzik dinliyor.','Kanepede dinliyor.','kulaklıkla dinlemek','öğretmeni dinlemek','chill','none'),
(3064,'tr','Perdeleri açıyor!','Perdeleri kapatıyor!','perdeleri açmak','ön kapıyı açmak','dramatic','exclamation'),
(3070,'tr','Ellerin üstünde bir ağaç var.','Ellerin üstünde bir kedi var.','avuç açmış iki el','cepte iki el','chill','none'),
(3072,'tr','Dur. Kediler yaprak tırmıklayabiliyor mu?','Dur. Köpekler yaprak tırmıklayabiliyor mu?','sonbahar yapraklarını tırmıklamak','kumu tırmıklayıp düzeltmek','low_iq','none'),
(3078,'tr','Usta gibi yumurta kızartıyor.','Usta gibi balık kızartıyor.','tavada yumurta kızartmak','tencerede yumurta haşlamak','slang','cliche'),
(3079,'tr','Kupadan içiyor.','Şişeden içiyor.','kupadan içmek','şişeden içmek','chill','none'),
(3082,'tr','Balerin tek parmak ucunda!','Balerin iki ayağının üstünde!','tek parmak ucunda bir balerin','sahnede bir balerin','dramatic','exclamation'),
(3087,'tr','Evcil hayvan maması döküyor.','Portakal suyu döküyor.','mama dökmek','sıcak çay dökmek','business','none'),
(3089,'tr','Fırında kurabiye pişirmiş. Benim için mi?','Fırında kek pişirmiş. Benim için mi?','fırında pişmiş çikolatalı kurabiyeler','fırında pişmiş ekmekler','flirt','guessing'),
(3090,'tr','Market alışverişini taşıyor.','Çamaşırlarını taşıyor.','bir poşet market alışverişi','bisiklette market alışverişi','chill','none'),
(3098,'tr','Barbeküde iki burger var.','Barbeküde iki biftek var.','bahçede bir barbekü','sahilde bir barbekü','chill','none'),
(3101,'tr','Ne kadar yükseğe atlıyor!','Ne kadar hızlı yüzüyor!','ipin üstünden atlamak','göle atlamak','slang','exclamation'),
(3118,'tr','Baltasını savuruyor!','Sopasını savuruyor!','ağaca saplanmış bir balta','duvarda asılı bir balta','dramatic','exclamation'),
(3119,'tr','Perinin altın rengi kanatları var.','Perinin siyah kanatları var.','altın kanatlı bir peri','asalı bir peri','chill','none'),
(3122,'tr','Sadece sekiz dilim pizza.','Sadece altı dilim pizza.','sekiz dilim bir pizza','kutuda bir pizza','ironic','understatement'),
(3124,'tr','Sosisli sandviçte hardal var.','Sosisli sandviçte ketçap var.','hardallı sosisli sandviç','ketçaplı sosisli sandviç','chill','none'),
(3125,'tr','Kremalı sıcak çikolata!','Kremalı sıcak kahve!','bir kupa sıcak çikolata','sıcak çikolatalı kek','dramatic','exclamation'),
(3126,'tr','Boksör aşırı ciddi görünüyor.','Boksör aşırı uykulu görünüyor.','kırmızı eldivenli bir boksör','boksör köpek gezdirmek','slang','none'),
(3127,'tr','Çok hızlı atacak!','Çok hızlı tekmeleyecek!','beyzbol topu atmak','eldiveni fırlatıp atmak','dramatic','guessing'),
(3132,'tr','Bastonla doğa yürüyüşü yapıyor.','Köpekle doğa yürüyüşü yapıyor.','dağda doğa yürüyüşü yapmak','sahilde doğa yürüyüşü yapmak','chill','none'),
(3135,'tr','Yarışı kazanıyor!','Yarışı kaybediyor!','koşu yarışını kazanmak','yüzme yarışını kazanmak','dramatic','exclamation'),
(3136,'tr','Gölde yüzüyor.','Havuzda yüzüyor.','gölde yüzmek','denizde yüzmek','chill','none'),
(3141,'tr','Grup toplantı yapıyor.','Grup parti yapıyor.','çember olmuş bir grup','sıraya girmiş bir grup','business','none'),
(3143,'tr','Kumaşı maviye boyuyor.','Kumaşı kırmızıya boyuyor.','kumaşı maviye boyamak','saçını maviye boyamak','chill','none'),
(3144,'tr','Kumaş dokuyor.','Sepet dokuyor.','tezgâhta dokumak','halı dokumak','chill','none'),
(3145,'tr','Uzun bir dokuma tezgâhında çalışıyor.','Uzun bir masada çalışıyor.','ahşap dokuma tezgâhında dokumak','dikiş makinesinde dikmek','chill','none'),
(3147,'tr','Sokağın üstündeki ipte mavi kumaş kuruyor.','Sokağın üstündeki ipte mavi kâğıt kuruyor.','ipte mavi kumaş','masa örtüsü kumaşı','chill','none'),
(3148,'tr','Kadınlar hasat ediyor.','Kadınlar dans ediyor.','altın başakları hasat etmek','elma hasat etmek','chill','none'),
(3157,'tr','Kırmızı bir tuğlayı havaya kaldırıyor.','Kırmızı bir kaskı havaya kaldırıyor.','yarım kalmış bir tuğla duvar','deniz kenarında tuğla bir ev','chill','none'),
(3158,'tr','İşçi çeliğe kaynak yapıyor.','İşçi çeliği boyuyor.','çelik levhaya kaynak yapmak','kırık bisiklete kaynak yapmak','nerd','none'),
(3163,'tr','Ellerini yıkıyor.','Yüzünü yıkıyor.','ellerini yıkamak','bulaşık yıkamak','chill','none'),
(3164,'tr','Dişlerini fırçalama vakti!','Saçını fırçalama vakti!','dişlerini fırçalamak','saçını fırçalamak','dramatic','exclamation'),
(3171,'tr','Ne kadar da "yardımsever" bir yön levhası.','Ne kadar da "yardımsever" bir harita.','eski ahşap bir yön levhası','eski ahşap bir çit direği','ironic','understatement'),
(3176,'tr','Bir ağacın altında oturuyor.','Bir ağacın üstünde oturuyor.','ağacın altında oturmak','dalın üstünde oturmak','chill','none'),
(3180,'tr','Tek ayak üstünde paten kayıyor!','Tek ayak üstünde kayak yapıyor!','gölde paten kaymak','parkta paten kaymak','dramatic','exclamation'),
(3188,'tr','Biri seccadede dua ediyor.','Biri seccadede uyuyor.','seccadede dua etmek','kilisede dua etmek','chill','none'),
(3191,'tr','Kedi bu sarılmayı hiç istememişti.','Köpek bu sarılmayı hiç istememişti.','büyük bir kediye sarılmak','büyük bir köpeğe sarılmak','chill','guessing'),
(3192,'tr','Sadece gözleri görünüyor.','Sadece ağzı görünüyor.','yalnızca gözler görünüyor','uykuda kapalı gözler','business','none'),
(3194,'tr','Diş hekiminin elinde matkap var. İmdat!','Diş hekiminin elinde bıçak var. İmdat!','matkaplı bir diş hekimi','dişini fırçalayan bir diş hekimi','dramatic','exclamation'),
(3195,'tr','Hâlâ çalışıyor. Garibim.','Hâlâ yemek yiyor. Garibim.','gece geç saate kadar çalışmak','gece antrenman yapmak','slang','guessing'),
(3197,'tr','Çay, kitap ve müzik hayali kuruyor.','Araba, kitap ve müzik hayali kuruyor.','masada hayal kurmak','yatakta hayal kurmak','gossip','guessing'),
(3198,'tr','Televizyonları bir akvaryum.','Televizyonları bir şömine.','akvaryumda balıklar','tabakta balıklar','ironic','understatement'),
(3199,'tr','Bu çift sarmal bir DNA.','Bu çift sarmal bir halat.','parlayan bir DNA sarmalı','DNA test kiti','nerd','none'),
(3200,'tr','Mektup ortada.','Telefon ortada.','el yazısı bir mektup','basılı bir mektup','chill','none'),
(3207,'tr','Lambaya ne gerek var? Bitki parlıyor.','Lambaya ne gerek var? Kitap parlıyor.','parlayan küçük bir bitki','parlayan bir ateş','ironic','cheap_quality'),
(3216,'tr','Yan yana koşuyorlar.','Yan yana dans ediyorlar.','yan yana koşmak','otobüse yetişmek için koşmak','chill','none'),
(3222,'tr','Bir kedi kral gibi uyuyor.','Bir köpek kral gibi uyuyor.','koltukta uyumak','sepette uyumak','slang','cliche'),
(3235,'tr','Bak, koalanın elinde güller var.','Bak, koalanın elinde havuçlar var.','gül tutan bir koala','yaprak yiyen bir koala','gossip','none'),
(3240,'tr','Bize bağırıyor!','Bize şarkı söylüyor!','megafona bağırmak','köpeğe bağırmak','dramatic','exclamation'),
(3242,'tr','Yatakta kumandayla patlamış mısır mı? Bu kediler olayı çözmüş.','Yatakta kumandayla pizza mı? Bu kediler olayı çözmüş.','yatakta patlamış mısır','sinemada patlamış mısır','slang','cliche'),
(3243,'tr','Ağ mavi parlıyor.','Ağ kırmızı parlıyor.','parlayan mavi bir ağ','bir TV yayın ağı','chill','none'),
(3256,'tr','Grup kulübü sallıyor!','Grup sahili sallıyor!','sahnede bir grup','stadyumda bir grup','slang','none'),
(3269,'tr','Çatıda rahatlıyor.','Plajda rahatlıyor.','şezlongda rahatlamak','küvette rahatlamak','chill','none'),
(3272,'tr','Topuklular, evrak çantası: tam bir patron!','Topuklular, sırt çantası: tam bir patron!','deri evrak çantası taşımak','para dolu bir evrak çantası','flirt','exclamation'),
(3274,'tr','Masa tenisi raketi kırmızı.','Masa tenisi raketi siyah.','bir masa tenisi masası','televizyonda masa tenisi','chill','none'),
(3277,'tr','Çocuk bir yıldız tutuyor!','Çocuk bir lamba tutuyor!','parlayan bir yıldız tutmak','parlayan bir lamba tutmak','dramatic','exclamation'),
(3278,'tr','Çift birbirine sarılmış.','Çift dans ediyor.','sarmaş dolaş bir çift','bir çift arkadaş','flirt','none'),
(3281,'tr','Bütün işi uçurtma yapıyor.','Bütün işi tekne yapıyor.','uçurtmayla çekilmek','parkta bir uçurtma','ironic','exaggeration'),
(3283,'tr','Martı artık turist oldu.','Güvercin artık turist oldu.','iskelede bir martı','teknede bir martı','chill','exaggeration'),
(3285,'tr','Kostümünde oyuncak papağanlar var!','Kostümünde oyuncak yılanlar var!','meyveli başlıklı bir kostüm','bir Cadılar Bayramı kostümü','gossip','exclamation'),
(3288,'tr','Ayaklıklarla yürüyorlar.','Bir sahnede yürüyorlar.','uzun ayaklıklarla yürümek','kazıklar üstünde evler','chill','none'),
(3293,'tr','Yumruk attı, eldiven yukarıda!','Yumruk attı, eldiven aşağıda!','ringde yumruk atmak','kum torbasına yumruk atmak','dramatic','exclamation'),
(3294,'tr','Topu tekmelemek üzere!','Topu fırlatmak üzere!','topu tekmelemek üzere','kapıyı tekmeleyip açmak','dramatic','exclamation'),
(3301,'tr','Geminin dümenini tutuyor.','Arabanın direksiyonunu tutuyor.','büyük bir gemide dümen tutmak','küçük bir arabada direksiyon tutmak','chill','none'),
(3303,'tr','Kâğıt uçağı uçuyor!','Uçurtması uçuyor!','kâğıt uçak atmak','kâğıt uçak katlamak','dramatic','exclamation'),
(3304,'tr','Hokey sopası diske vurmak için, sanırım.','Hokey sopası topa vurmak için, sanırım.','buzda bir hokey sopası','kırık bir hokey sopası','low_iq','guessing'),
(3306,'tr','Dünyanın sahibi horoz.','Dünyanın sahibi kartal.','dünya küresinde bir horoz','çitte bir horoz','dramatic','exaggeration'),
(3311,'tr','Bir tünele doğru yürüyor.','Bir göle doğru yürüyor.','kayadan bir tünel','nehir altında bir tünel','chill','none'),
(3313,'tr','Ne kadar da "dolu" bir stadyum.','Ne kadar da "dolu" bir plaj.','boş bir stadyum','dolu bir stadyum','ironic','none'),
(3314,'tr','Kulaklıkla koşu yapıyor.','Köpeğiyle koşu yapıyor.','yol boyunca koşu yapmak','sahil boyunca koşu yapmak','chill','none'),
(3317,'tr','Alpaka fotoğrafa girmek istiyor.','At fotoğrafa girmek istiyor.','meraklı kahverengi bir alpaka','uyuyan kahverengi bir alpaka','gossip','guessing'),
(3323,'tr','Yavru su aygırı çok meşgul.','Yavru aslan çok meşgul.','dinlenen yavru bir su aygırı','yüzen yavru bir su aygırı','chill','understatement'),
(3325,'tr','Eski bir kitaptan sihir fışkırıyor!','Eski bir fincandan sihir fışkırıyor!','eski bir kitaptan sihir','sahnede sihir gösterisi','dramatic','exclamation'),
(3341,'tr','Birinin elinde altın bir trompet var.','Birinin elinde altın bir keman var.','altın bir trompet','trompet çalmak','chill','none'),
(3346,'tr','İki kişi bir kütüphanede.','İki kişi bir mutfakta.','kütüphanede iki kişi','bir kütüphane kartı','chill','none'),
(3357,'tr','Filenin yanında yüksek bir sandalye.','Filenin yanında yüksek bir merdiven.','kortta gerili bir file','bir balıkçı filesi','chill','none'),
(3362,'tr','Kanka, rakun bize dik dik bakıyor.','Kanka, kedi bize dik dik bakıyor.','pervazda bir rakun','çöp kutusunda bir rakun','slang','none'),
(3368,'tr','Tembel hayvanın hiç acelesi yok.','Koalanın hiç acelesi yok.','gülümseyen bir tembel hayvan','uyuyan bir tembel hayvan','chill','understatement'),
(3369,'tr','Mavi bir çiçeği kokluyor.','Kırmızı bir çiçeği kokluyor.','bir çiçeği koklamak','çorbayı koklamak','chill','none'),
(3379,'tr','Topa doğru koşuyor.','Toptan kaçıyor.','topa doğru koşmak','gökyüzünde bir top','chill','none'),
(3382,'tr','Kanka, bu papağan resmen korsan.','Kanka, bu papağan resmen aşçı.','göz bantlı bir papağan','kafeste bir papağan','slang','exaggeration'),
(3383,'tr','Bir civciv dalga sörfü yapıyor!','Bir ördek dalga sörfü yapıyor!','sörf yapan bir civciv','yumurtada bir civciv','dramatic','exclamation'),
(3390,'tr','Güllerin arasında birbirlerini öpüyorlar.','Bir plajda birbirlerini öpüyorlar.','gül bahçesinde öpüşmek','köprüde öpüşmek','flirt','none'),
(3392,'tr','Baykuş gece vardiyasında.','Baykuş gündüz vardiyasında.','karda bir baykuş','uçan beyaz bir baykuş','business','cliche'),
(3395,'tr','Sis dağları saklıyor.','Sis şehri saklıyor.','zirvelerde yoğun sis','banyo aynasında sis','chill','none'),
(3401,'tr','Trafik ışığında çiçekler var!','Trafik ışığında mumlar var!','çiçekli bir trafik ışığı','bozuk bir trafik ışığı','low_iq','exclamation'),
(3406,'tr','Biri bir deniz canavarıyla dalıyor!','Biri bir köpekbalığıyla dalıyor!','resifin üstünde dalmak','uçurumdan suya dalmak','dramatic','exaggeration'),
(3412,'tr','Kırmızı elbiseyle ağırlık kaldırıyor!','Kırmızı paltoyla ağırlık kaldırıyor!','halter kaldırmak','bavul kaldırmak','dramatic','exclamation'),
(3418,'tr','Bateriye vurmak üzere.','Gonga vurmak üzere.','bateri çalmak','bateri taşımak','chill','guessing'),
(3419,'tr','Trompet üflüyor.','Düdük üflüyor.','altın bir trompet üflemek','altın bir trompet temizlemek','chill','none'),
(3420,'tr','Kontrbas ondan daha uzun.','Kontrbas ondan daha kısa.','kontrbası yayla çalmak','kontrbas taşımak','nerd','none'),
(3422,'tr','Orkestrayı o yönetiyor.','Koroyu o yönetiyor.','orkestra yönetmek','orkestrada çalmak','business','none'),
(3423,'tr','Arp çalıyor.','Gitar çalıyor.','uzun bir arp çalmak','uzun bir arp taşımak','chill','none'),
(3428,'tr','Kemanı ne güzel çalıyor.','Çelloyu ne güzel çalıyor.','keman çalmak','keman akort etmek','flirt','none'),
(3431,'tr','Klarnet çalıyor.','Trompet çalıyor.','klarnete üflemek','klarnet temizlemek','chill','none'),
(3435,'tr','Uçurumda iki mağara ağzı.','Kumda iki mağara ağzı.','kayalıklarda bir deniz mağarası','yarasa dolu bir mağara','chill','none'),
(3441,'tr','Karpuzlara yaslanmış.','Balkabaklarına yaslanmış.','bir kasa karpuz','karpuz suyu tezgâhı','chill','none'),
(3447,'tr','Samanyolu''nun altında bir heykel.','Gökkuşağının altında bir heykel.','gece taş bir heykel','parkta bir heykel','chill','none'),
(3458,'tr','Yıldızların altında taş kafalar.','Güneşin altında taş kafalar.','taş kafaların üstünde yıldızlar','bayraktaki yıldızlar','chill','none'),
(3463,'tr','Kanoyla kürek çekiyor.','Salla kürek çekiyor.','gün batımında kano sürmek','gün batımında kano taşımak','chill','none'),
(3469,'tr','Çita mola veriyor.','Çita banyo yapıyor.','gün batımında bir çita','hızla koşan bir çita','business','understatement'),
(3470,'tr','Kocaman turuncu bir kum tepesi.','Kocaman beyaz bir kum tepesi.','kum tepesinin kıvrık sırtı','deniz kenarında bir kum tepesi','chill','none'),
(3472,'tr','Ne güzel elbise! İçinde dönüyor.','Ne güzel şapka! İçinde dönüyor.','kırmızı elbiseyle dönmek','mavi elbiseyle dönmek','flirt','none'),
(3473,'tr','Flamingo suyun içinde.','Flamingo bir ağaçta.','suda bir flamingo','uçan bir flamingo','chill','none'),
(3479,'tr','Pembe bir el çantası, sakin bir kafe.','Pembe bir laptop, sakin bir kafe.','masada bir el çantası','mağazada bir el çantası','chill','none'),
(3482,'tr','Basamaklarda takılıyor.','Basamaklarda uyuyor.','güneşli taş basamaklar','dans adımları','slang','none'),
(3485,'tr','File dokunuyor.','Kaplana dokunuyor.','file dokunmak','ağaç gövdesine dokunmak','chill','none'),
(3486,'tr','Hindistan cevizinden içiyor.','Şişeden içiyor.','pipetli bir hindistan cevizi','hindistan cevizi açmak','chill','none'),
(3489,'tr','Teknede şarap mı? Gülüyor.','Arabada şarap mı? Gülüyor.','teknede gülmek','bir tekneye gülmek','gossip','guessing'),
(3493,'tr','Arkasında ayak izleri bırakıyor.','Arkasında çiçekler bırakıyor.','bir sıra ayak izi','karda ayak izleri','chill','none'),
(3497,'tr','Gün batımına doğru yürüyor. Klasik.','Denize doğru yürüyor. Klasik.','gün batımına yürümek','arabadan gün batımı izlemek','ironic','cliche'),
(3513,'tr','Gelinin duvağı çok uzun.','Gelinin duvağı çok koyu.','gelinin uzun duvağı','buketli bir gelin','gossip','none'),
(3516,'tr','Vazoda tek bir çiçek var.','Vazoda on çiçek var.','rafta bir vazo','masada bir vazo','chill','none'),
(3519,'tr','O beyaz küpe çok güzel.','O beyaz kolye çok güzel.','beyaz damla bir küpe','yerde bir küpe','flirt','none'),
(3522,'tr','Bilgi: bu denizanası ışık saçıyor.','Bilgi: bu denizyıldızı ışık saçıyor.','parlayan bir denizanası','sahilde bir denizanası','nerd','cliche'),
(3541,'tr','Yüksek bir şelale, minik bir göl.','Yüksek bir şelale, minik bir tekne.','uçurumdan dökülen bir şelale','bahçede bir şelale','chill','none'),
(3548,'tr','Smokinle sigara içiyor.','Elbiseyle sigara içiyor.','sigara içmek','pipo içmek','chill','none'),
(3552,'tr','İlkbaharda Japonya, arkada Fuji.','Kışın Japonya, arkada Fuji.','Japonya''da bir bahar sokağı','bir Japonya gezi rehberi','chill','none'),
(3556,'tr','Lamalar fotoğraf için süslenmiş.','Keçiler fotoğraf için süslenmiş.','battaniyeli lamalar','karda lamalar','gossip','guessing'),
(3559,'tr','Minik ada, sıfır komşu.','Minik ada, sıfır kaktüs.','minik kayalık bir ada','otelli bir ada','ironic','understatement'),
(3561,'tr','Kuryelik işini eşek yapıyor.','Kuryelik işini at yapıyor.','yüklü bir eşeği çekmek','yüklü bir eşeğe binmek','business','none'),
(3562,'tr','Nil kıyısında Antik Mısır.','Karlar içinde Antik Mısır.','Nil''de antik Mısır','Mısır''da bir tatil fotoğrafı','chill','none'),
(3564,'tr','Ren geyikleri karda.','Ren geyikleri plajda.','karda ren geyikleri','kızak çeken ren geyikleri','chill','none'),
(3567,'tr','Peru''nun üstünde kırmızı bir güneş asılı.','Peru''nun üstünde sarı bir güneş asılı.','Peru''daki kalıntılar','Peru bayrağı','chill','none'),
(3572,'tr','Kadınlar çay topluyor.','Kadınlar elma topluyor.','çay yaprağı toplamak','çiçek toplamak','chill','none'),
(3585,'tr','Bir zebra öğle yemeği yiyor.','Bir zebra banyo yapıyor.','tepede zebralar','nehirde zebralar','business','none'),
(3586,'tr','Kaplumbağanın acelesi var.','Yengecin acelesi var.','dev bir kaplumbağa','suda yüzen bir kaplumbağa','ironic','exaggeration'),
(3589,'tr','Goril resmen takılıyor.','Goril resmen yemek yiyor.','bambular arasında bir goril','göğsünü döven bir goril','slang','none'),
(3590,'tr','Bir devekuşu kumda yürüyor.','Bir deve kumda yürüyor.','çölde bir devekuşu','başını saklayan bir devekuşu','chill','none'),
(3592,'tr','İkisi de sıkı egzersiz yapıyor.','İkisi de sıkı dans ediyor.','birlikte egzersiz yapmak','köpeğe egzersiz yaptırmak','business','none'),
(3598,'tr','Kıvırcık saçları mavi tükenmezle çizilmiş.','Kıvırcık saçları kırmızı tükenmezle çizilmiş.','mavi tükenmezle kıvırcık saç','kırmızı boyayla kıvırcık saç','chill','none'),
(3619,'tr','Nehrin üstünde bir kartal var.','Şehrin üstünde bir kartal var.','nehrin üstünde bir kartal','dağların üstünde bir kartal','chill','none'),
(3629,'tr','Star Wars''taki gibi el sıkışıyorlar!','Star Wars''taki gibi dövüşüyorlar!','bir uzaylıyla el sıkışmak','bir robotla el sıkışmak','dramatic','exclamation'),
(3633,'tr','Uzayda mı? Yok, havuzda suyun üstünde duruyor.','Uzayda mı? Yok, gölde suyun üstünde duruyor.','sırtüstü suyun üstünde durmak','uzay boşluğunda süzülmek','ironic','none'),
(3638,'tr','Uzay işi: yeri paspaslamak.','Uzay işi: yeri boyamak.','parlak zemini paspaslamak','dökülen kahveyi paspaslamak','ironic','understatement'),
(3639,'tr','Uzaydaki en iyi koltuk: kırmızı bir tabure.','Uzaydaki en iyi koltuk: mavi bir tabure.','kırmızı taburede oturmak','banyoda bir tabure','ironic','exaggeration'),
(3640,'tr','Lamba uzaya doğru parlıyor.','Lamba bir gemiye doğru parlıyor.','uzaya ışık tutmak','gemide bir ışık','chill','none'),
(3641,'tr','Bu gezegende bile otomat var!','Bu gezegende bile kahve dükkânı var!','ışıklı bir otomat','bozuk bir otomat','ironic','exclamation'),
(3642,'tr','Bir gezegeni çekiyor!','Bir roketi çekiyor!','ipten çekmek','diş çekmek','dramatic','exaggeration'),
(3644,'tr','Minicik bir bitkiyi suluyor.','Upuzun bir ağacı suluyor.','minik bir fideyi sulamak','büyük bir bahçeyi sulamak','chill','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
