begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(3645,'tr','Evden çok uzakta, masasında bir aile fotoğrafı.','Evden çok uzakta, masasında bir aile köpeği.','uzayda bir aile fotoğrafı','bir aile fotoğraf albümü','dramatic','none'),
(3647,'tr','Ay''ı silip tertemiz yapıyor.','Güneş''i silip tertemiz yapıyor.','ayın yüzeyini silmek','kask vizörünü silmek','chill','none'),
(3653,'tr','Ay''ı tamir ediyor!','Güneş''i tamir ediyor!','kırık Ay''ı tamir etmek','patlak lastiği tamir etmek','dramatic','exaggeration'),
(3658,'tr','O kadar rüzgârlı ki ağaç pes etti.','O kadar yağmurlu ki ağaç pes etti.','rüzgârlı bir Patagonya günü','denizde rüzgârlı hava','ironic','exaggeration'),
(3663,'tr','Lama seni süzüyor.','Keçi seni süzüyor.','tepede bir lama','ahırda bir lama','slang','guessing'),
(3671,'tr','Kollarını ardına kadar açmış.','Kollarını kavuşturmuş.','kollarını iki yana açmak','kollarını kavuşturmak','chill','none'),
(3673,'tr','Gökyüzünde altı sıcak hava balonu var.','Gökyüzünde iki sıcak hava balonu var.','gün doğarken sıcak hava balonları','gece sıcak hava balonları','chill','none'),
(3676,'tr','Koy manzarası, gün batımı dahil.','Koy manzarası, kar dahil.','turkuaz, kıvrımlı bir koy','teknelerle dolu bir koy','business','cliche'),
(3685,'tr','Ne çok sıcak hava balonu!','Ne çok helikopter!','kayaların üstünde sıcak hava balonları','denizin üstünde sıcak hava balonları','dramatic','exclamation'),
(3706,'tr','Hız treni herkesi korkutuyor!','Dönme dolap herkesi korkutuyor!','hız trenindeki bir aile','hız treninin yanındaki bir aile','dramatic','exaggeration'),
(3709,'tr','Şef çorbayı tadıyor.','Şef salatayı tadıyor.','çorbayı tatmak','şarabı tatmak','chill','none'),
(3718,'tr','Kapüşonlu sweatshirt, bomber ceket, güneş gözlüğü: tam havalı.','Kapüşonlu sweatshirt, bomber ceket, kep: tam havalı.','bomber altında kapüşonlu sweatshirt','kapüşonu başına çekmek','slang','none'),
(3724,'tr','Kadının elbisesi rengârenk.','Kadının elbisesi simsiyah.','canlı renkler içinde bir kadın','koyu renkler içinde bir kadın','chill','none'),
(3733,'tr','Akrebin kuyruğu havada.','Akrebin kuyruğu aşağıda.','akrebin kıvrık kuyruğu','taşın altında bir akrep','chill','none'),
(3734,'tr','Bu boynuz çok büyük. Vay.','Bu boynuz çok küçük. Vay.','kocaman sarmal bir boynuz','boru çalmak','low_iq','exaggeration'),
(3735,'tr','Bak bak, mirket gülümsüyor.','Bak bak, mirket ağlıyor.','dimdik duran bir mirket','çukur kazan bir mirket','gossip','none'),
(3740,'tr','Elinde bir can simidi var.','Elinde bir sörf tahtası var.','can simidiyle koşmak','can simidinde oturmak','chill','none'),
(3741,'tr','Bu laleler fena turuncu.','Bu laleler fena mor.','dört turuncu lale','bahçede laleler','slang','none'),
(3747,'tr','Köpek yavrusunun milyonlarca beneği var!','Kedinin milyonlarca beneği var!','beyaz tüyde siyah benekler','gömlekte bir leke','dramatic','exaggeration'),
(3750,'tr','Göletin başında bir tek boynuzlu at.','Göletin başında bir ejderha.','durgun bir orman göleti','ördeklerle dolu bir gölet','chill','none'),
(3767,'tr','Bu taraftarlar ortalığı bile temizliyor!','Bu oyuncular ortalığı bile temizliyor!','koltukları temizlemek','odanı temizlemek','gossip','exclamation'),
(3770,'tr','Karga sağa bakıyor.','Karga sola bakıyor.','parlak siyah bir karga','uçan bir karga','chill','none'),
(3772,'tr','Bu ejderha buzdan!','Bu ejderha ateşten!','bir buz ejderhasının yüzü','ateş püskürten bir ejderha','dramatic','exclamation'),
(3777,'tr','Kanatları alev alev yanıyor!','Kanatları suyun içinde!','ardına kadar açık kanatlar','sıkıca katlanmış kanatlar','dramatic','exclamation'),
(3779,'tr','Zavallı oyuncak yapayalnız.','Zavallı köpek yapayalnız.','eski bir oyuncak tavşan','eski bir oyuncak araba','dramatic','exaggeration'),
(3797,'tr','Suda amuda kalkıyor, helal!','Karda amuda kalkıyor, helal!','sığ suda amuda kalkma','kumsalda amuda kalkma','slang','none'),
(3803,'tr','Bir ejderha kuleye sarılıyor!','Bir yılan kuleye sarılıyor!','kulenin etrafında bir ejderha','yüksek bir su kulesi','dramatic','exaggeration'),
(3806,'tr','İçecekte iki kiraz var.','İçecekte üç kiraz var.','sapında iki kiraz','bir kâse kiraz','chill','none'),
(3809,'tr','Bir can simidi yardım eder!','Bir can yeleği yardım eder!','yardım için elini uzatmak','ödevde yardım','dramatic','exclamation'),
(3813,'tr','Patika boyunca bakıyor.','Nehir boyunca bakıyor.','rengârenk boyanmış bir patika','çamurlu bir orman patikası','chill','none'),
(3825,'tr','Dünya uzaydan minicik görünüyor.','Mars uzaydan minicik görünüyor.','uzaydan görülen Dünya','bir park yeri','chill','none'),
(3827,'tr','Bir canavar tam arkasında!','Bir ejderha tam arkasında!','çocuğun arkasında bir canavar','yatağın altında bir canavar','dramatic','exclamation'),
(3828,'tr','Şempanze ve kibrit: kötü fikir.','Şempanze ve bıçak: kötü fikir.','elde yanan bir kibrit','televizyonda bir futbol maçı','chill','guessing'),
(3832,'tr','Havai fişekler patlıyor!','Balonlar patlıyor!','gece gökyüzünde havai fişekler','dükkânda havai fişekler','dramatic','exclamation'),
(3841,'tr','Kıyafetler havada uçuşuyor!','Ayakkabılar havada uçuşuyor!','havada süzülen kıyafetler','çamaşır makinesinde kıyafetler','dramatic','exclamation'),
(3842,'tr','Bir bardağı çöpe atıyor.','Bir poşeti çöpe atıyor.','bir bardağı çöpe atmak','bir topu uzağa atmak','business','none'),
(4001,'tr','Bu savaş uçağı tost yapıyor!','Bu savaş uçağı kahve yapıyor!','tost makinesi savaş uçağı','boks ringinde bir dövüşçü','slang','exclamation'),
(4002,'tr','Masada amuda kalkmak mı? Denge süper!','Kanepede amuda kalkmak mı? Denge süper!','masada dengede durmak','buzda dengeyi kaybetmek','gossip','exclamation'),
(4003,'tr','İki çift canavar terlik.','İki çift canavar bot.','bir çift sarı terlik','bir çift sarı eldiven','chill','none'),
(4004,'tr','Jet ekmek ısıtıyor. Normal.','Jet çorba ısıtıyor. Normal.','jette ekmek ısıtmak','ocakta çorba ısıtmak','ironic','understatement'),
(4005,'tr','Donmuş duvar mı? Sorun değil.','Kaya duvar mı? Sorun değil.','donmuş bir duvara tırmanmak','paten için donmuş bir göl','ironic','understatement'),
(4006,'tr','Su tamamen şeffaf.','Su koyu yeşil.','şeffaf göl suyu','şeffaf bir naylon poşet','chill','none'),
(4007,'tr','Karanlığa atladı kanka.','Havuza atladı kanka.','karanlıkta salto atmak','karanlıktan korkmak','slang','none'),
(4008,'tr','Elma ağacını sallıyor!','Elma ağacına tırmanıyor!','bir ağaç dalını sallamak','el sıkışmak','dramatic','exclamation'),
(4009,'tr','Ördekler okul gezisindeymiş gibi sıra halinde yürüyor.','Tavuklar okul gezisindeymiş gibi sıra halinde yürüyor.','uzun bir sıra halinde ördekler','küçük bir gölette ördekler','chill','exaggeration'),
(4010,'tr','Profesyonel gibi tırmanıyor!','Profesyonel gibi yüzüyor!','beyaz bir kayalığa tırmanmak','bir merdivene tırmanmak','flirt','cliche'),
(4011,'tr','Pandalar onun seyircisi!','Maymunlar onun seyircisi!','pandalardan oluşan seyirci','çocuklardan oluşan seyirci','dramatic','exclamation'),
(4013,'tr','Güvertenin yanından bir buzdağı geçiyor. Tam Titanik!','Güvertenin yanından bir balina geçiyor. Tam Titanik!','ahşap güvertede botlar','bir deste iskambil kâğıdı','slang','exclamation'),
(4014,'tr','Bavul yuvarlanarak ilerliyor.','Bisiklet yuvarlanarak ilerliyor.','otoparkta yuvarlanmak','tepeden aşağı yuvarlanmak','chill','none'),
(4015,'tr','Koyunlar kıyıya atlıyor!','Keçiler kıyıya atlıyor!','nehir kıyısında koyunlar','banka önünde koyunlar','dramatic','exclamation'),
(4016,'tr','Kedi küvete hayır diyor.','Köpek küvete hayır diyor.','küvetin üstünde bir kedi','küvetin içinde bir kedi','low_iq','guessing'),
(4017,'tr','Kırmızı fener parlıyor.','Mavi fener parlıyor.','parlayan bir kâğıt fener','parlayan bir sokak lambası','chill','none'),
(4018,'tr','İki köpek bir scooter''da!','İki kedi bir scooter''da!','yeşil scooter''da köpekler','yeşil bisiklette köpekler','dramatic','exclamation'),
(4019,'tr','Bu yavru köpeğin halkası efsane.','Bu yavru kedinin halkası efsane.','pembe bir yüzme halkası','pırlanta bir yüzük','slang','exaggeration'),
(4020,'tr','Köpek bir kurbağayı izliyor.','Köpek bir balığı izliyor.','kurbağayı izlemek','televizyon izlemek','chill','none'),
(4021,'tr','Pastayı mı kesiyoruz? İlk ben!','Ekmeği mi kesiyoruz? İlk ben!','pastayı kare kare kesmek','pastayı ikiye kesmek','slang','guessing'),
(4022,'tr','Uçan bir uçağın üstünde ufak bir yürüyüş.','Giden bir trenin üstünde ufak bir yürüyüş.','bir şehrin üstünden uçmak','denizin üstünden uçmak','ironic','understatement'),
(4023,'tr','Teknede eğlence tam gaz.','Otobüste eğlence tam gaz.','nehirde eğlence','plajda eğlence','chill','none'),
(4024,'tr','Bütün çiftlik adamı takip ediyor!','Bütün çiftlik kadını takip ediyor!','bir adamı takip eden hayvanlar','bir köpeği takip eden hayvanlar','dramatic','exaggeration'),
(4025,'tr','Kanka, yavru kedi onu kovalıyor.','Kanka, yavru köpek onu kovalıyor.','yeşil bir topu kovalamak','yeşil bir kuşu kovalamak','slang','none'),
(4026,'tr','Su cam gibi pürüzsüz.','Yol cam gibi pürüzsüz.','pürüzsüz suda süzülmek','pürüzsüz bir iniş','chill','cliche'),
(4027,'tr','Turtayı kim yedi? İnek mi?','Turtayı kim yedi? Köpek mi?','altın rengi elmalı turta','iş yerinde pasta grafiği','gossip','blaming_someone'),
(4028,'tr','Buldog profesyonel gibi dönüyor!','Buldog profesyonel gibi zıplıyor!','kaykayla dönmek','televizyonu açmak','slang','exaggeration'),
(4029,'tr','Şişe ona vurup onu düşürdü!','Top ona vurup onu düşürdü!','vurulup bloktan düşmek','kapıya vurmak','slang','exclamation'),
(4030,'tr','Parkta biraz yüzdü.','Parkta biraz kestirdi.','parkta bir gölet','bir kaykay parkı','ironic','understatement'),
(4031,'tr','Top tam en üstteki yere kondu!','Top tam onun üstüne kondu!','yığının en üstteki kısmı','en üstteki raf','dramatic','exclamation'),
(4032,'tr','Ne yeşil bir dağınıklık!','Ne kırmızı bir dağınıklık!','yeşil slime dağınıklığı','dağınık bir yatak odası','gossip','exaggeration'),
(4033,'tr','Golf sopasıyla ilk deneme!','Hokey sopasıyla ilk deneme!','golf sopası sallamak','üyelere özel golf kulübü','dramatic','exclamation'),
(4034,'tr','Çıplak ayak, bir sürü tuzak. Harika.','Kocaman botlar, bir sürü tuzak. Harika.','düzinelerce fare tuzağı','ayı için bir tuzak','ironic','understatement'),
(4035,'tr','Suyun üstüne adım atıyor.','Ateşin üstüne adım atıyor.','yüzen bloklara adım atmak','hareket eden trene adım atmak','chill','none'),
(4036,'tr','Kameraya kocaman bir gülümseme!','Köpeğe kocaman bir gülümseme!','fotoğraf için bir gülümseme','dişçi için bir gülümseme','dramatic','exclamation'),
(4037,'tr','Biri omlet pişirmiş.','Biri krep pişirmiş.','omlet pişirmek','makarna pişirmek','chill','none'),
(4038,'tr','Birbirlerini deli gibi seviyorlar.','Birbirlerinden deli gibi nefret ediyorlar.','birbirini sevmek','hızlı arabaları sevmek','gossip','guessing'),
(4039,'tr','Sürünerek gitti ama grup kazandı.','Koşarak gitti ama grup kazandı.','eller ve parmak uçlarında sürünmek','yatağın altında sürünmek','gossip','blaming_someone'),
(4040,'tr','Kızın yemeği: salata. Oğlanın yemeği: dev bir burger.','Kızın yemeği: pizza. Oğlanın yemeği: dev bir burger.','plajda bir yemek','mutfakta bir yemek','gossip','banter'),
(4041,'tr','Kız ona bir baktı. Her şeyi satın aldılar.','Kız ona bir baktı. Hiçbir şey satın almadılar.','büyük bir AVM''den satın almak','pazardan yiyecek satın almak','gossip','banter'),
(4042,'tr','Bir mağazanın önündeler.','Bir mağazanın içindeler.','ışıklı bir mağazanın önünde','hindistan cevizleriyle dolu bir mağaza','chill','none'),
(4043,'tr','Onu şakayıklarla şaşırttı.','Onu bir yüzükle şaşırttı.','onu çiçeklerle şaşırtmak','sürpriz doğum günü partisi','gossip','none'),
(4044,'tr','Golf pratiği yapıyor.','Tenis pratiği yapıyor.','gece pratik yapmak','piyano pratiği yapmak','chill','none'),
(4045,'tr','Telefonunu buldu!','Cüzdanını buldu!','kayıp bir telefonu bulmak','kayıp bir köpeği bulmak','dramatic','exclamation'),
(4046,'tr','Reddediyor. Son cevap.','Kabul ediyor. Son cevap.','parmakla reddetmek','akşam yemeğini reddetmek','ironic','cliche'),
(4047,'tr','Mükemmel bir tatil ama elinde hâlâ telefon.','Mükemmel bir tatil ama elinde hâlâ kitap.','plajda tatil','karda tatil','ironic','banter'),
(4048,'tr','Bir minibüse duş kurmuşlar!','Bir minibüse küvet kurmuşlar!','güneş paneli kurmak','yeni bir uygulama kurmak','gossip','exclamation'),
(4049,'tr','Omuzlarında ne yük var!','Bisikletinde ne yük var!','dev bir yük taşımak','bir yük tuğla taşımak','dramatic','exclamation'),
(4050,'tr','Arkadaşların bir köpeği var.','Arkadaşların bir kedisi var.','ateş başında arkadaşlar','barda arkadaşlar','chill','none'),
(4051,'tr','Bir kamyon motosiklet taşıyor.','Bir kamyon bisiklet taşıyor.','elektrikli bir motosiklet','bir motosiklet kaskı','chill','none'),
(4052,'tr','Yine kaydediyorlar. Onuncu çekim mi?','Yine dans ediyorlar. Onuncu çekim mi?','telefonla kaydetmek','bir şarkı kaydetmek','gossip','guessing'),
(4053,'tr','Mısır bile pasta çıktı!','Havuç bile pasta çıktı!','mısır şeklinde bir pasta','gün batımında mısır tarlası','dramatic','exclamation'),
(4054,'tr','Köpek geç saate kadar klavye başında çalışıyor. Terfi yakın mı?','Kedi geç saate kadar klavye başında çalışıyor. Terfi yakın mı?','klavyede patiler','bir piyano klavyesi','gossip','guessing'),
(4055,'tr','Dinozor mu? Husky hayır diyor!','Dinozor mu? Kedi hayır diyor!','bir köpek ve iki dinozor','bir köpek ve iki kedi','slang','exclamation'),
(4056,'tr','Ne köpüklü bir kutlama!','Ne sessiz bir kutlama!','şampanyalı bir kutlama','bir doğum günü kutlaması','dramatic','exclamation'),
(4057,'tr','Kola üstüne başına bulaştı!','Su üstüne başına bulaştı!','bir şişe kola','bir bardak kola','dramatic','exclamation'),
(4058,'tr','Bir gecelik gezi, on bavul!','Bir gecelik gezi, iki bavul!','kısa gezi için hazırlanmak','bavula takılıp düşmek','dramatic','banter'),
(4059,'tr','Bir muz üç babunu besleyemez.','Bir muz üç zebrayı besleyemez.','babunları beslemek','ördekleri beslemek','ironic','understatement'),
(4060,'tr','Akıntı güzel ama orası şelale!','Akıntı güzel ama orası köprü!','nehrin akıntısı','trafiğin akışı','dramatic','exclamation'),
(4061,'tr','Şu köpekbalığının çenesine bak!','Şu balinanın çenesine bak!','diş dolu bir çene','dişsiz bir çene','dramatic','exclamation'),
(4062,'tr','Kanka uçurtma barını sıkı kavramış.','Kanka tekne korkuluğunu sıkı kavramış.','uçurtma barını kavramak','direksiyonu kavramak','slang','none'),
(4063,'tr','Kayışlar onu bıraktı!','Uçak onu bıraktı!','bulutların içine bırakılmak','bir kuşu serbest bırakmak','dramatic','exclamation'),
(4064,'tr','Yuva bir sırığın tepesinde.','Yuva bir ağacın tepesinde.','sırık üstünde bir yuva','sırık üstünde bir bayrak','chill','none'),
(4065,'tr','Sürücü bir köpek. Lütfen emniyet kemerlerinizi bağlayın.','Sürücü bir kedi. Lütfen emniyet kemerlerinizi bağlayın.','sürücü olarak bir köpek','yolcu olarak bir köpek','business','cliche'),
(4066,'tr','Papağan kırmızı toprakta sürüyor. Efsane.','Papağan ıslak kumda sürüyor. Efsane.','kırmızı topraktan bir parkur','beyaz gömlekte toprak lekesi','slang','exaggeration'),
(4067,'tr','Göl ağaçları yansıtıyor.','Göl şehri yansıtıyor.','ağaçları yansıtan bir göl','onun dans hareketlerini taklit etmek','chill','none'),
(4068,'tr','Bir köpekbalığını okşuyor!','Bir yunusu okşuyor!','köpekbalığının sırtını okşamak','köpekbalığının sırtına binmek','dramatic','exclamation'),
(4069,'tr','Civciv bir çubuk tutuyor.','Güvercin bir çubuk tutuyor.','ince bir olta çubuğu','çubuk tutan güvercin','chill','none'),
(4070,'tr','İki paraşütçü kanadın üstünde!','İki paraşütçü kuyruğun üstünde!','kanadın altında asılı durmak','kanadın üstünde oturmak','dramatic','exclamation'),
(4071,'tr','Bir batıktan sıçrıyor!','Bir köprüden sıçrıyor!','denize sıçramak','havuza sıçramak','dramatic','exclamation'),
(4072,'tr','Üç kadın, gizli lagün.','Üç erkek, gizli lagün.','turkuaz bir lagün','teknelerle dolu bir lagün','gossip','none'),
(4073,'tr','Olay: tavuğun elinde sopa var.','Olay: tavuğun elinde kaşık var.','tahta bir sopa sallamak','tahta bir sopa fırlatmak','gossip','none'),
(4074,'tr','Güneş onun arkasında.','Ay onun arkasında.','lagünün üstünde güneş','şehrin üstünde güneş','chill','none'),
(4075,'tr','Her yer köpekbalığı: tehlike mi? Ne tehlikesi?','Her yer yunus: tehlike mi? Ne tehlikesi?','etrafını saran tehlike','yoldaki tehlike','dramatic','understatement'),
(4076,'tr','Kapıdan dışarı atlıyorlar!','Pencereden dışarı atlıyorlar!','açık bir helikopter kapısı','açık bir araba kapısı','dramatic','exclamation'),
(4077,'tr','Bir güvercin hâlâ uykuda.','İki güvercin de hâlâ uykuda.','yuvada uykuda','bankta uykuda','chill','none'),
(4078,'tr','Tek kişiye yedi yastık!','Tek kişiye yedi battaniye!','bir sıra beyaz yastık','bir yığın beyaz havlu','gossip','exclamation'),
(4079,'tr','Nehir hızla ilerliyor. Çılgın!','Arabalar hızla ilerliyor. Çılgın!','nehirde hızla ilerlemek','havalimanına hızla ilerlemek','slang','exaggeration'),
(4080,'tr','Tokalar el bileğindeymiş!','Tokalar çekmecedeymiş!','el bileğinde saç tokaları','el bileğinde bir saat','dramatic','exclamation'),
(4081,'tr','Zirvelerin üstünde helikopterden sarkan bacaklar. Asla.','Zirvelerin üstünde uçaktan sarkan bacaklar. Asla.','yukarıdan karlı zirveler','tepesinde haç olan bir zirve','slang','guessing'),
(4082,'tr','Kadın baş aşağı asılı duruyor.','Adam baş aşağı asılı duruyor.','baş aşağı asılı durmak','uçağı baş aşağı çevirmek','chill','none'),
(4083,'tr','"Küçük" bir pug ortayı kaptı.','"Küçük" bir kedi ortayı kaptı.','yatağın ortası','kanepenin ortası','ironic','understatement'),
(4084,'tr','Başında saç çıkıyor!','Çenesinde saç çıkıyor!','kel bir başta saçlar','bir baş marul','dramatic','exclamation'),
(4086,'tr','Sivrisinek ısırmak üzere.','Örümcek ısırmak üzere.','uyuyan bir adamı ısırmak','uyuyan bir köpeği ısırmak','chill','guessing'),
(4087,'tr','Kediler işlerini çok ciddiye alıyor.','Köpekler işlerini çok ciddiye alıyor.','iş başında takım elbiseli kediler','okulda takım elbiseli kediler','business','understatement'),
(4088,'tr','Bu şelale gerçekten çok geniş. Daha fazla yaklaşma.','Bu köprü gerçekten çok geniş. Daha fazla yaklaşma.','geniş bir şelale kenarı','geniş bir nehir köprüsü','dramatic','guessing'),
(4089,'tr','Ahtapotlar dans ediyor!','Yengeçler dans ediyor!','kulüpte dans eden ahtapotlar','kuma saklanan ahtapotlar','dramatic','exclamation'),
(4090,'tr','Roket hızla yükseliyor!','Uçak hızla yükseliyor!','hızla yükselen roket','şafakta yükselen güneş','dramatic','exclamation'),
(4091,'tr','Buz kızın altında çatlıyor!','Buz oğlanın altında çatlıyor!','ayaklarının altında çatlayan buz','buzun üstünde yumurta kırmak','dramatic','exclamation'),
(4092,'tr','Basamaklardan aşağı sürüyor!','Basamaklardan yukarı sürüyor!','uçurum basamaklarından aşağı','kayak pistinden aşağı','dramatic','exclamation'),
(4093,'tr','Vay, ay çok yuvarlak.','Vay, ay çok kırmızı.','yuvarlak gri bir ay','bir tur alkış','low_iq','none'),
(4094,'tr','Yem çuvalları rengârenk.','Yem çuvalları bembeyaz.','çuval çuval hayvan yemi','çuval çuval patates','chill','none'),
(4095,'tr','Bu filmi minicik bir kamera çekti!','Bu filmi kocaman bir kamera çekti!','film çekmek','bir sinema salonu','dramatic','exclamation'),
(4096,'tr','Kaplumbağa özgür ve teşekkür bile etmiyor.','Köpekbalığı özgür ve teşekkür bile etmiyor.','özgür bırakılan bir kaplumbağa','bedava bir kaplumbağa','chill','guessing'),
(4097,'tr','Aşırı hızlı sürüyor.','Aşırı yavaş sürüyor.','yokuş aşağı hızlı sürmek','yemekten önce oruç tutmak','slang','exaggeration'),
(4098,'tr','İki inek yolu kesmiş. Ayıp.','İki koyun yolu kesmiş. Ayıp.','yolu kesen inekler','plaja giden yol','ironic','blaming_someone'),
(4099,'tr','Köpek geri geldi, yine en tepede!','Kedi geri geldi, yine en tepede!','şiltelerin üstüne geri dönmek','kanepeye geri dönmek','dramatic','exclamation'),
(4100,'tr','O deliği yay açtı, ben değil!','O deliği kedi açtı, ben değil!','tavanda bir delik','çorabında bir delik','low_iq','blaming_someone'),
(4101,'tr','Bir sanatçı bir kuyruk gösteriyor.','Bir sanatçı bir bayrak gösteriyor.','dev bir tavus kuyruğu göstermek','beyaz bir bayrak göstermek','chill','none'),
(4102,'tr','Güneş ışığı onu çağırıyor!','Yağmur onu çağırıyor!','pencerenin dışında güneş ışığı','ofiste güneş ışığı','dramatic','exaggeration'),
(4103,'tr','Yavru köpeğin sabrı taştı.','Yavru kedinin sabrı taştı.','yavru bir köpeğin sabrı','yavru bir kediye sabır','ironic','cliche'),
(4104,'tr','Tek öpücük, adam domates oldu.','Tek öpücük, adam hayalet oldu.','yanağa bir öpücük','ele bir öpücük','low_iq','exaggeration'),
(4105,'tr','Erkek arkadaşı çiçek getirmiş.','Erkek arkadaşı pasta getirmiş.','çiçekli bir erkek arkadaş','yüzüklü bir erkek arkadaş','flirt','none'),
(4106,'tr','Aç köpek onu çalıyor.','Aç kedi onu çalıyor.','aç küçük bir köpek','yalnız yiyen aç bir adam','gossip','blaming_someone'),
(4107,'tr','Bir fili örttüler, kaplan çıktı!','Bir fili örttüler, aslan çıktı!','fili örtmek','kaplanı örtmek','dramatic','exclamation'),
(4108,'tr','Arabasına bakılırsa kızın kocası o.','Arabasına bakılırsa kızın abisi o.','arabadaki bir koca','araba yıkayan bir koca','gossip','none'),
(4109,'tr','İki köpek çimenlikte takılıyor.','İki kedi çimenlikte takılıyor.','yeşil çimenlikte köpekler','çimenliği biçmek','slang','none'),
(4110,'tr','Palyaço kaplan beklemiyordu!','Palyaço aslan beklemiyordu!','palyaçonun turuncu peruğu','palyaçonun mor peruğu','dramatic','guessing'),
(4111,'tr','Koç, onun sinir bozucu iş arkadaşı.','Köpek, onun sinir bozucu iş arkadaşı.','sinir bozucu bir koç','sinir bozucu bir sinek','business','exaggeration'),
(4112,'tr','Blokta düzgün bir delik.','Kapıda düzgün bir delik.','bir bloğu delmek','bir blok peynir','chill','none'),
(4113,'tr','Sokakta mücevher dramı!','Dükkânda mücevher dramı!','güvercinde pembe mücevherler','vitrinde pembe mücevherler','gossip','exclamation'),
(4114,'tr','Alışveriş merkezi kuralı: kadın alır, adam taşır.','Alışveriş merkezi kuralı: adam alır, kadın taşır.','alışveriş merkezinden poşetler','alışveriş merkezi otoparkı','gossip','banter'),
(4115,'tr','İki turist eğleniyor. Çok tatlılar!','İki turist öğle yemeği yiyor. Çok tatlılar!','gece turistler','otobüste turistler','gossip','exclamation'),
(4116,'tr','Arabası çok küçük!','Arabası çok büyük!','küçük kırmızı bir balon araba','küçük kırmızı bir tekne','dramatic','exclamation'),
(4117,'tr','Ufak bir arama, o kadar.','Ufak bir şekerleme, o kadar.','kayıp telefon için arama','kayıp köpek için arama','chill','understatement'),
(4118,'tr','Bu kort dağ manzarası sunuyor.','Bu kort güzel bir deniz manzarası sunuyor.','dağlarda bir kort','deniz kenarında bir kort','business','none'),
(4119,'tr','Taş adam çöktü. Huzur içinde yat.','Taş köpek çöktü. Huzur içinde yat.','çöken bir taş figür','çöken bir taş köprü','slang','none'),
(4120,'tr','Ceviz kırmak için bir tahta.','Yumurta kırmak için bir tahta.','delikli bir tahta','ekmek kesme tahtası','chill','none'),
(4121,'tr','Ne patlamalı bir sahne!','Ne romantik bir sahne!','patlamalı bir aksiyon sahnesi','romantik bir film sahnesi','dramatic','none'),
(4122,'tr','Yanlış bankayı soymaya geldi.','Yanlış dükkânı soymaya geldi.','bir banka soymak','bir tren soymak','ironic','bad_excuse'),
(4123,'tr','Yüz alınca gözyaşları mı? Cidden mi?','Zayıf alınca gözyaşları mı? Cidden mi?','yüz alınca gözyaşları','gülmekten gözyaşları','ironic','guessing'),
(4124,'tr','Bir minibüs, bir köpek ve iyi arkadaşlar.','Bir minibüs, bir kedi ve iyi arkadaşlar.','kamp minibüsünde hayat','minibüsle ev taşımak','chill','none'),
(4125,'tr','Sahnede bir fil var!','Sahnede bir at var!','sahnede bir fil','sahnede bir şarkıcı','dramatic','exclamation'),
(4126,'tr','Binlerce bina ışıl ışıl.','Binlerce bina karanlık.','limanın yanında ışıklı binalar','gölün yanında eski binalar','dramatic','none'),
(4127,'tr','Lemurun tüyleri çok yumuşak.','Lemurun tüyleri çok siyah.','yumuşak beyaz tüy','yumuşak beyaz ekmek','chill','none'),
(4128,'tr','Yavru köpek bu avluya bayılıyor.','Yavru kedi bu avluya bayılıyor.','avluda bir yavru köpek','sokakta bir yavru köpek','chill','guessing'),
(4129,'tr','Yavru köpek evden ayrılıyor.','Yavru köpek eve geliyor.','şapkayla evden ayrılmak','şapkayla eve gelmek','chill','none'),
(4130,'tr','Kedi onun tepesini düz kesmiş!','Köpek onun tepesini düz kesmiş!','gorilin düz tepesi','kedinin düz tepesi','gossip','exclamation'),
(4131,'tr','Dükkân bolca yeşil kullanıyor.','Dükkân bolca kırmızı kullanıyor.','yeşile boyanmış bir duvar','golf sahasının yeşil alanı','business','none'),
(4132,'tr','Kedi bir aslanı fırçalıyor!','Köpek bir aslanı fırçalıyor!','ıslak bir yeleyi fırçalamak','dişlerini fırçalamak','dramatic','exclamation'),
(4133,'tr','Köpek buzdolabını koruyor.','Kedi buzdolabını koruyor.','buzdolabının yanında yatmak','buzdolabını açmak','slang','guessing'),
(4134,'tr','Şişman kirpi bütün dikenlerini kaybetti. Hiç mutlu değil.','Şişman tavşan bütün tüylerini kaybetti. Hiç mutlu değil.','şişman, yuvarlak bir kirpi','şişman gri bir kedi','gossip','understatement'),
(4135,'tr','Topa vurdu, sonra sahadan fırladı!','Topu tuttu, sonra sahadan fırladı!','topu kaleye vurmak','topu elle tutmak','dramatic','exclamation'),
(4136,'tr','Dört köpekle egzersiz yapmak kolay değil.','Dört kediyle egzersiz yapmak kolay değil.','köpeklerle egzersiz yapmak','parkta egzersiz yapmak','chill','understatement'),
(4137,'tr','Tek odada bu kadar sarı!','Tek odada bu kadar yeşil!','parlak sarı bir elbise','sarıya boyanmış bir oda','slang','exaggeration'),
(4138,'tr','Yaşlı köpeği okşuyor.','Yaşlı kediyi okşuyor.','yaşlı bir köpeği okşamak','yaşlı bir köpeği gezdirmek','chill','none'),
(4139,'tr','Dar bir patikadan tırmanıyor.','Dik bir merdivenden tırmanıyor.','dar bir toprak patika','çölden geçen bir patika','chill','none'),
(4140,'tr','Bir çıkıntıdan atlıyor. Macera mı, kötü fikir mi?','Bir tekneden atlıyor. Macera mı, kötü fikir mi?','arkadaşlarla bir macera','bir macera filmi','dramatic','guessing'),
(4141,'tr','Beş kanka güneşte uzanmış.','Beş kanka çamurda uzanmış.','çimenlerde uzanmak','arkadaşlarına yalan söylemek','slang','none'),
(4143,'tr','Pst, çöp kutusunda bir rakun var.','Pst, çöp kutusunda bir kedi var.','çöp kutusunda bir rakun','çöp kutusunun üstünde bir rakun','gossip','none'),
(4144,'tr','Gelincikler boruya bayılıyor.','Kediler boruya bayılıyor.','boruda gelincikler','bir tüp diş macunu','chill','guessing'),
(4145,'tr','Top için atlıyor!','Frizbi için atlıyor!','top için atlamak','tekneden atlamak','dramatic','exclamation'),
(4146,'tr','Ayakkabılarını çıkaramayacak kadar bitkin.','Gömleğini çıkaramayacak kadar bitkin.','ıslak kumda bitkin','sıcak küvette bitkin','ironic','exaggeration'),
(4147,'tr','Acele ediyor. O tabela da ne?','Uyuyor. O tabela da ne?','arabaya doğru acele etmek','otobüse doğru acele etmek','gossip','guessing'),
(4148,'tr','Saf lüks: kırmızı bir spor araba.','Saf lüks: kırmızı bir motosiklet.','lüks bir spor araba','lüks bir otel odası','flirt','exaggeration'),
(4149,'tr','Uyuyan bir devin üstüne kondu!','Uyuyan bir ayının üstüne kondu!','bir devin üstüne konmak','bir devle savaşmak','dramatic','exclamation'),
(4150,'tr','Yeşil araba hız yapıyor.','Kırmızı araba hız yapıyor.','köy yolunda hız yapmak','otoyolda hız yapmak','chill','none'),
(4151,'tr','Bu araba sanatı fazlasıyla pembe.','Bu araba sanatı fazlasıyla yeşil.','pembe araba sanatı','müzede sanat','ironic','understatement'),
(4152,'tr','Römork bir aracı saklıyor.','Römork bir atı saklıyor.','römorkun içinde bir araç','feribotta bir araç','gossip','guessing'),
(4153,'tr','Otoyolda mavi bir araba.','Otoyolda kırmızı bir araba.','dağlara giden bir otoyol','denize giden bir otoyol','chill','none'),
(4154,'tr','Toprak kortta gece sporu.','Çim kortta gece sporu.','projektör ışığında spor','televizyonda spor','chill','none'),
(4155,'tr','Tabaklar artık "temiz".','Fincanlar artık "temiz".','temiz beyaz bir tabak','temiz beyaz bir havlu','ironic','understatement'),
(4156,'tr','Bir robot bize yaklaşıyor!','Bir köpek bize yaklaşıyor!','kameraya yaklaşmak','havuza yaklaşmak','dramatic','exclamation'),
(4157,'tr','Herkes yarışıyor ama onun tabelası kazanıyor.','Herkes yarışıyor ama onun köpeği kazanıyor.','komik bir tabelanın önünde yarışmak','spor arabayla yarışmak','gossip','exaggeration'),
(4158,'tr','O balık devasa. Vay.','O balık minicik. Vay.','sırıtan devasa bir balık','sırıtan devasa bir su samuru','low_iq','none'),
(4159,'tr','Vadinin üstünde, o kadar yüksekte!','Şehrin üstünde, o kadar yüksekte!','vadinin üstünde yüksekte','bulutların üstünde yüksekte','dramatic','exclamation'),
(4160,'tr','Puf! Kırmızı araba kayboldu.','Puf! Kırmızı minibüs kayboldu.','kumda kaybolmak','karda kaybolmak','slang','exaggeration'),
(4161,'tr','İki ön taraf neredeyse birbirine değiyor.','İki arka taraf neredeyse birbirine değiyor.','bir arabanın ön tarafı','bir evin ön tarafı','chill','none'),
(4162,'tr','Tek araba. Koca meydan. Harika.','Tek otobüs. Koca meydan. Harika.','ıslak taş bir meydan','pazar tezgâhlı bir meydan','slang','none'),
(4163,'tr','Arabası hakkında konuşuyor.','Köpeği hakkında konuşuyor.','bir araba hakkında konuşmak','bir arabayla konuşmak','chill','none'),
(4164,'tr','Fren büyük ve kırmızı.','Fren büyük ve mavi.','büyük kırmızı bir fren','büyük kırmızı bir düğme','chill','none'),
(4165,'tr','Bu hızda ağaçlar bulanıklaşıyor.','Bu hızda evler bulanıklaşıyor.','dağ yolunda hız','yarış pistinde hız','dramatic','none'),
(4166,'tr','O kırmızı arabaya bir yıldız gibi giriyor.','O mavi arabaya bir yıldız gibi giriyor.','kırmızı bir spor arabaya girmek','kırmızı bir telefon kulübesine girmek','flirt','exaggeration'),
(4167,'tr','Karanlık mağara, aydınlık çıkış.','Karanlık mağara, çıkış yok.','aydınlık bir mağara çıkışı','otoyol çıkış tabelası','dramatic','none'),
(4168,'tr','Yavaş kaplumbağa hiç durmuyor.','Yavaş tavşan hiç durmuyor.','yavaş bir kaplumbağa','yavaş bir salyangoz','chill','none'),
(4169,'tr','Ayıya bir bakış atıyor!','Ayıya bir balık atıyor!','ayıya bir bakış','haritaya bir bakış','dramatic','exclamation'),
(4170,'tr','Tavuk civcivini kurtardı!','Tavuk yumurtasını kurtardı!','bir civcivi kurtarmak','biraz para biriktirmek','dramatic','exclamation'),
(4171,'tr','Kurt sinsice sokuluyor.','Tilki sinsice sokuluyor.','sinsice sokulan bir kurt','kaçıp giden bir kurt','chill','none'),
(4172,'tr','Tavuk aksiyon filmlerine layık bir kaçış yaptı.','Ördek aksiyon filmlerine layık bir kaçış yaptı.','yangından kaçış','hapisten kaçış','dramatic','exaggeration'),
(4173,'tr','Kovalamaca bir köprüde bitti.','Kovalamaca bir ahırda bitti.','köprü üstünde kovalamaca','ormanda kovalamaca','chill','none'),
(4174,'tr','Tavuk civcivlerini süper kahraman gibi koruyor.','Tilki civcivlerini süper kahraman gibi koruyor.','civcivlerini korumak','yumurtalarını korumak','dramatic','exaggeration'),
(4175,'tr','Pst, tavuk gizlice geçiyor.','Pst, tilki gizlice geçiyor.','uyuyan kurtların yanından gizlice geçmek','kümese gizlice girmek','gossip','none'),
(4176,'tr','Kavanozda bir ateş böceği parıldıyor.','Kavanozda bir mum parıldıyor.','parıldayan bir ateş böceği','parıldayan bir lamba','chill','none'),
(4177,'tr','Civcivlerin ağızları açık.','Civcivlerin ağızları kapalı.','ağzı açık civcivler','kanatları açık civcivler','chill','none'),
(4178,'tr','Tavuk cömert bir bağışçı.','Tilki cömert bir bağışçı.','cömert bir tavuk','cömert bir tilki','business','exaggeration'),
(4179,'tr','Bugün onun 100. doğum günü!','Bugün onun 50. doğum günü!','100. doğum günü pastası','plajda doğum günü','dramatic','exclamation'),
(4181,'tr','Ona bir pasta sunuyorlar.','Ona bir pizza sunuyorlar.','doğum günü pastası sunmak','bir fincan çay sunmak','chill','none'),
(4182,'tr','Bütün çimenin üstüne resim yaptı!','Bütün evin üstüne resim yaptı!','çimene dev bir resim yapmak','bahçe çitini boyamak','dramatic','exaggeration'),
(4183,'tr','Hediyenin içinde bir adam var!','Hediyenin içinde bir köpek var!','hediyenin içinde bir adam','hediyenin içinde bir saat','dramatic','exclamation'),
(4184,'tr','Yavru köpek topu geri getiriyor. İnsana ne gerek var?','Yavru köpek ayakkabıyı geri getiriyor. İnsana ne gerek var?','topu geri getirmek','topu eve getirmek','slang','exaggeration'),
(4185,'tr','Bir kupa fareye bastırıyor.','Bir kupa waffle''lara bastırıyor.','fareye bastıran bir kupa','fareye bastıran bir tabak','chill','none'),
(4186,'tr','Köpek topla geri dönüyor.','Köpek ayakkabıyla geri dönüyor.','makineye geri dönmek','arabaya geri dönmek','chill','none'),
(4187,'tr','Papağanlar ölü taklidi yapıyor!','Papağanlar top oynuyor!','ölü taklidi yapan papağanlar','kâğıt oynayan papağanlar','dramatic','exclamation'),
(4188,'tr','Bir kayakçı, bir "küçük" yamaç.','İki kayakçı, bir "küçük" yamaç.','uzun, karlı bir yamaç','teleferikli bir yamaç','ironic','understatement'),
(4189,'tr','Kâse boş, bir hap kaldı.','Kâse boş, iki hap kaldı.','boş bir köpek kabı','boş bir buzdolabı','chill','none'),
(4190,'tr','Kedi bir aslanla buluşuyor. Ne var bunda?','Köpek bir aslanla buluşuyor. Ne var bunda?','bir aslanla buluşmak','bir kaplanla buluşmak','slang','understatement'),
(4191,'tr','Roket yanında dev gibi yükseliyor.','Otobüs yanında dev gibi yükseliyor.','önünde yükselen bir roket','önünde yükselen bir vinç','chill','none'),
(4192,'tr','Bilgi: bu kartal balık tutuyor.','Bilgi: bu baykuş balık tutuyor.','ayaklarıyla balık tutmak','oltayla balık tutmak','nerd','none'),
(4193,'tr','Batman''e bu yeraltı garajı lazım.','Batman''e bu yeraltı havuzu lazım.','bir yeraltı garajı','bir yeraltı treni','dramatic','exaggeration'),
(4194,'tr','Minicik bir ciple ne gezinti ama!','Minicik bir tekneyle ne gezinti ama!','oyuncak ciple gezinti','oyuncak tekneyle gezinti','dramatic','exclamation'),
(4195,'tr','Scooter kırılıp paramparça oldu!','Bisiklet kırılıp paramparça oldu!','kırılıp dağılan bir scooter','dünya rekorunu kırmak','dramatic','exclamation'),
(4196,'tr','Kovada bir mum var.','Kovada bir çiçek var.','kovada bir mum','bir kova su','chill','none'),
(4197,'tr','Saat geç! Koş!','Saat erken! Koş!','geç uyanmak','geç yatmak','dramatic','exclamation'),
(4198,'tr','Delik suyun altında derine iniyor. Dipte görüşürüz!','Halat suyun altında derine iniyor. Dipte görüşürüz!','bir bacadan derine inmek','kumu derine kazmak','slang','exclamation'),
(4199,'tr','Ayaklarını gölde sürüklüyor.','Ellerini gölde sürüklüyor.','ayaklarını suda sürüklemek','bir tekneyi suya sürüklemek','chill','none'),
(4200,'tr','Gün batımında deniz altın rengi.','Gün batımında deniz kırmızı.','altın rengi deniz ve gökyüzü','altından bir yüzük','chill','none'),
(4201,'tr','Gösterişçiler! Bisikletler dik duruyor.','Gösterişçiler! Arabalar dik duruyor.','tek tekerde dik duran bisikletler','sandalyede dik oturmak','ironic','exclamation'),
(4202,'tr','Çok meşgul köpekler, karınlar havada.','Çok meşgul kediler, karınlar havada.','güneşte karınlar havada','tıka basa dolu bir karın','ironic','understatement'),
(4203,'tr','Bir köpekbalığını kurtardı. Kahraman.','Bir yunusu kurtardı. Kahraman.','karaya vurmuş köpekbalığını kurtarmak','karaya vurmuş balinayı kurtarmak','dramatic','exaggeration'),
(4205,'tr','Bir papatya taşıyor.','Bir gül taşıyor.','bir çiçek taşımak','bir tohum taşımak','chill','none'),
(4206,'tr','Hamsterın rozeti var. Hamster patron.','Hamsterın telefonu var. Hamster patron.','hamsterın kimlik rozeti','bir polis rozeti','low_iq','exaggeration'),
(4207,'tr','Pizza teslim edildi: gerçek aşk!','Pasta teslim edildi: gerçek aşk!','pizza kutusu teslim etmek','bisikletle mektup teslim etmek','gossip','guessing'),
(4208,'tr','Bu hamster bütün atıştırmalıkları yedi.','Bu tavşan bütün atıştırmalıkları yedi.','atıştırmalık üstüne atıştırmalık','sonrası için bir atıştırmalık','low_iq','exaggeration'),
(4209,'tr','Bir hamster derin uykuda.','Bir kedi derin uykuda.','derin uykuda bir hamster','soğuk zeminde uyku','chill','none'),
(4210,'tr','Ta-da! Dondurma tutuyor.','Ta-da! Havuç tutuyor.','iki dondurma tutmak','iki havuç tutmak','dramatic','exclamation'),
(4211,'tr','Bu hamster yanaklarına benden daha çok özen gösteriyor.','Bu tavşan yanaklarına benden daha çok özen gösteriyor.','yanaklarını pıtpıtlayan bir hamster','yanaklarını dolduran bir hamster','ironic','exaggeration'),
(4212,'tr','Kahverengi kombinleri birbirine çok uyuyor.','Kırmızı kombinleri birbirine çok uyuyor.','uyumlu kahverengi kıyafetler','kahverengi deri bir kanepe','business','none'),
(4213,'tr','Kırmızılar içinde kraliçe gibiler!','Maviler içinde kraliçe gibiler!','koyu kırmızı giyinmiş','kadehte kırmızı şarap','dramatic','exaggeration'),
(4214,'tr','İkisi de açık maviyle başlıyor.','İkisi de koyu yeşille başlıyor.','açık mavili bir çift','açık mavi perdeler','chill','none'),
(4215,'tr','Üstünde turuncu ve beyaz var.','Üstünde yeşil ve beyaz var.','turuncuyla beyaz','portakal soymak','chill','none'),
(4216,'tr','Beyaz elbisesi muhteşem.','Sarı elbisesi muhteşem.','beyaz pamuklu bir elbise','beyaz bir gelinlik','flirt','none'),
(4217,'tr','Polis o corgiyi istiyor!','Polis o kediyi istiyor!','köpek kovalayan polis','hırsız kovalayan polis','slang','exclamation'),
(4218,'tr','Corgi motoru fena zorluyor.','Kedi motoru fena zorluyor.','duman çıkaran bir traktör motoru','duman çıkaran bir araba motoru','ironic','blaming_someone'),
(4219,'tr','Hayvan hızla uçuyor.','Hayvan hızla yüzüyor.','uçan bir hayvana binmek','uçan bir hayvanı beslemek','chill','none'),
(4220,'tr','Beyaz bir arabayı temizliyor.','Siyah bir arabayı temizliyor.','boyayı temizlemek','evi temizlemek','business','none'),
(4221,'tr','Kertenkele kanepede takılıyor.','Kertenkele masada takılıyor.','kanepede mısır gevreği','mutfak masasında mısır gevreği','slang','none'),
(4222,'tr','Kanka, geko el sallıyor.','Kanka, kurbağa el sallıyor.','kameraya el sallamak','bayrak sallamak','slang','none'),
(4223,'tr','Çok acı! Ağzından ateş çıkıyor!','Çok tatlı! Ağzından ateş çıkıyor!','acı kırmızı biberler','pilavlı acı bir köri','dramatic','exclamation'),
(4224,'tr','Bir kertenkele tuvaleti kullanıyor.','Bir kertenkele mutfağı kullanıyor.','tuvalette bir kertenkele','tuvaleti temizleyen bir kertenkele','chill','none'),
(4225,'tr','Öğle yemeği tabakta bir sünger!','Öğle yemeği tabakta bir havuç!','küçük beyaz bir tabak','bir tabak peynir','low_iq','exclamation'),
(4226,'tr','Timsah avlanıyor!','Dinozor avlanıyor!','avlanan bir timsah','avlanan bir dinozor','dramatic','exclamation'),
(4227,'tr','Gelmiş geçmiş en arkadaş canlısı polis çevirmesi.','Gelmiş geçmiş en sinirli polis çevirmesi.','arkadaş canlısı bir polis','arkadaş canlısı bir tezgâhtar','slang','exaggeration'),
(4228,'tr','Kıyıya helikopter, sırf yumurta için!','Kıyıya tekne, sırf yumurta için!','çimenli kıyıda','kumlu kıyıda','dramatic','exaggeration'),
(4229,'tr','Biri maymunu serbest bırakıyor.','Biri köpeği serbest bırakıyor.','donmuş bir maymunu serbest bırakmak','donmuş bir kuşu serbest bırakmak','chill','none'),
(4230,'tr','Sürücü koltuğunda bir köpek var.','Sürücü koltuğunda bir kedi var.','sürücü koltuğu','arka koltuk','chill','none'),
(4231,'tr','Pencerenin ardında iki köpek mi? Şüpheli.','Pencerenin ardında iki kedi mi? Şüpheli.','buğulu bir kamyon penceresi','buğulu bir banyo penceresi','gossip','guessing'),
(4232,'tr','Yunus gösteride Ronaldo vuruşu yaptı!','Fok gösteride Ronaldo vuruşu yaptı!','bir yunus gösterisi','televizyonda bir yunus','dramatic','exaggeration'),
(4233,'tr','Taş köprü: trenleri taşıyacak kadar sağlam.','Ahşap köprü: trenleri taşıyacak kadar sağlam.','taş bir demiryolu köprüsü','taş bir demiryolu tüneli','business','none'),
(4234,'tr','Adam kadının dolabını saniyeler içinde darmadağın etti.','Kadın adamın dolabını saniyeler içinde darmadağın etti.','gömme bir giyinme dolabı','bir mutfak dolabı','gossip','banter'),
(4235,'tr','Oltayı harika attı. Şimdilik sıfır balık.','Oltayı harika attı. Şimdiden üç balık.','olta atmak','uzun bir gölge düşürmek','ironic','understatement'),
(4236,'tr','Kız onların dikkatini çekti.','Oğlan onların dikkatini çekti.','onların dikkatini çekmek','yeni müşteri çekmek','gossip','none'),
(4237,'tr','Bak, çocuk bir ahırda.','Bak, çocuk bir mutfakta.','ahırda bir at','tarlada bir at','gossip','none'),
(4238,'tr','Fırın yok mu? Kaburgaları taşta kızarttılar.','Fırın yok mu? Balığı taşta kızarttılar.','kızartılmış kuzu kaburga','kızarmış tavuk','slang','none'),
(4239,'tr','Efsane taksi: limanın üstünde bir martı.','Efsane taksi: limanın üstünde bir ejderha.','hareketli bir limanın üstünden uçmak','yatlarla dolu bir liman','slang','exaggeration'),
(4240,'tr','Tıpatıp aynı iki köpek görüyorum.','Tıpatıp aynı iki kedi görüyorum.','tıpatıp aynı iki husky','tıpatıp aynı iki kedi','low_iq','none'),
(4241,'tr','Uçağı bulutların içinden uçuruyor!','Uçağı karın içinden uçuruyor!','bulutların içinden uçurmak','helikopter uçurmak','dramatic','exclamation'),
(4243,'tr','Biri kartla ödüyor.','Biri nakit ödüyor.','sosisliyi ödemek','pizzayı ödemek','chill','none'),
(4244,'tr','Boğa arabaya saldırıyor!','At arabaya saldırıyor!','arabaya saldıran bir boğa','araba aküsünü şarj etmek','dramatic','exclamation'),
(4245,'tr','Bedavaya kayıyorlar!','Bedavaya kayak yapıyorlar!','su kanalında kaymak','karlı tepeden aşağı kaymak','dramatic','cheap_quality'),
(4246,'tr','Tavus kuşu baştan aşağı mavi.','Tavus kuşu baştan aşağı yeşil.','mavili bir tavus kuşu','mavili bir papağan','chill','none'),
(4247,'tr','Oğlanlar bir kuyuya atlıyor!','Oğlanlar bir göle atlıyor!','kuyuya atlayan oğlanlar','kuyudan su içen oğlanlar','dramatic','exclamation'),
(4248,'tr','Bu sefer kapalı havuzun dalgası kazandı.','Bu sefer okyanusun dalgası kazandı.','kapalı dalga havuzu','kapalı havuzda yüzme dersi','chill','none'),
(4249,'tr','Bir ejderhanın sırtındayım!','Bir atın sırtındayım!','bir ejderhanın sırtı','bir atın sırtı','dramatic','exclamation'),
(4250,'tr','Köpek depoyu darmadağın etti.','Kedi depoyu darmadağın etti.','depoda bir köpek','arabalarla dolu bir depo','gossip','blaming_someone'),
(4251,'tr','Onun yeri mi? Tek bir boş raf.','Onun yeri mi? Tek bir dolu raf.','kıyafetleri için yer','araba için yer','ironic','understatement'),
(4252,'tr','Takım çalışması: biri yudumluyor, biri betonu ovuyor.','Takım çalışması: biri yudumluyor, biri havuzu ovuyor.','beton bir verandayı ovmak','taze beton dökmek','ironic','exaggeration'),
(4253,'tr','Çamur adamı yıkıyorlar.','Çamur köpeği yıkıyorlar.','kalın çamuru yıkamak','bulaşıkları yıkamak','low_iq','exaggeration'),
(4254,'tr','Tezgâhta bir güvercin var.','Çatıda bir güvercin var.','tezgâhta bir güvercin','bankadaki bir tezgâh','chill','none'),
(4256,'tr','Kanguruyu kaşıyorlar, o da bayılıyor.','Koalayı kaşıyorlar, o da bayılıyor.','bir kanguruyu kaşımak','bir araba kapısını çizmek','chill','guessing'),
(4257,'tr','Kaplumbağaya sıkı sıkı sarılmışlar.','Balığa sıkı sıkı sarılmışlar.','sıkı bir panda sarılması','su altında sıkı bir sarılma','chill','none'),
(4258,'tr','Çelik bir kaydırakta bir yavru geyik var.','Ahşap bir kaydırakta bir yavru geyik var.','uzun çelik bir kaydırak','uzun çelik bir köprü','chill','none'),
(4259,'tr','Bu koyunda tam bir pazartesi yüzü var.','Bu inekte tam bir pazartesi yüzü var.','kızgın bir koyun yüzü','mutlu bir koyun yüzü','ironic','cliche'),
(4260,'tr','Köpek silueti hiç takmıyor.','Köpek karanlık siluete havlıyor.','kapı eşiğinde bir siluet','pencerede bir siluet','ironic','guessing'),
(4261,'tr','Havuzda güneşli bir gün.','Havuzda yağmurlu bir gün.','güneşli bir bahçe havuzu','güneşli bir plaj','chill','none'),
(4262,'tr','Plaj yaban hayatıyla dolu.','Plaj insanlarla dolu.','kıyıda yaban hayatı','hayvanat bahçesinde yaban hayatı','chill','exaggeration'),
(4263,'tr','Vay! Kuşlar ona hayran olmuş.','Vay! Kuşlar onu görmezden gelmiş.','pembe bir kuşa hayran olmak','pembe bir pastaya hayran olmak','gossip','exclamation'),
(4264,'tr','Sokak voleybolu, file yok.','Plaj voleybolu, file yok.','sakin bir sokakta voleybol','plajda voleybol','chill','understatement'),
(4265,'tr','Bir sarılma papağanı sakinleştiriyor.','Bir şarkı papağanı sakinleştiriyor.','kızgın bir papağanı sakinleştirmek','ağlayan bir bebeği sakinleştirmek','chill','none'),
(4266,'tr','Ne enerjik bir köpek!','Ne enerjik bir kedi!','koşan enerjik bir köpek','yüzen enerjik bir köpek','dramatic','exclamation'),
(4267,'tr','Yeni tarz: köpek pek bir düzgün.','Yeni tarz: kedi pek bir düzgün.','düzgün yuvarlak tüyler','düzgün bir sıra köpek','gossip','none'),
(4268,'tr','Köpek daha büyük taraftar, şaka yok.','Kedi daha büyük taraftar, şaka yok.','futbol taraftarı bir köpek','sıcak günler için vantilatör','slang','exaggeration'),
(4269,'tr','Kuru toprak suyu hızla içiyor.','Kuru kum suyu hızla içiyor.','kuru toprağı sulamak','kuru yaprakları süpürmek','dramatic','exaggeration'),
(4270,'tr','Bir ördek için yavaşlıyor.','Bir köpek için yavaşlıyor.','ördek için yavaşlamak','ışıkta yavaşlamak','chill','none'),
(4271,'tr','Atlet çok hızlı!','Atlet çok yavaş!','son sürat giden bir atlet','bitiş çizgisinde bir atlet','slang','exclamation'),
(4272,'tr','Daha fazla altın ekliyor!','Daha fazla gümüş ekliyor!','altın halka küpeler','bir altın madalya','dramatic','exclamation'),
(4273,'tr','Burada bir çarpışma olmuş.','Burada bir konser olmuş.','kavşakta bir çarpışma','otoyolda bir çarpışma','dramatic','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
