begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(4904,'tr','Şu sandalyeler biraz riskli duruyor.','Şu masalar biraz riskli duruyor.','riskli bir sandalye yığını','atlara riskli bir bahis','ironic','understatement'),
(4905,'tr','Köprü kanyonun üzerinden geçiyor.','Köprü caddenin üzerinden geçiyor.','kanyonun üzerinden geçen kemerler','kısa bir dikkat süresi','business','none'),
(4906,'tr','Hayatta kalan tek şey çadır.','Hayatta kalan tek şey kemer.','beyaz bir parti çadırı','ormanda bir çadır','dramatic','exaggeration'),
(4907,'tr','Dev hoparlör, dans eden su.','Dev hoparlör, dans eden süt.','büyük bir kulüp hoparlörü','konferansta bir konuşmacı','slang','exaggeration'),
(4908,'tr','Biri bir dalı büküyor.','Biri bir dalı kesiyor.','elma dalını bükmek','bir banka şubesi','chill','none'),
(4909,'tr','Herkes onu ünlüymüş gibi çekiyor.','Herkes onu ünlüymüş gibi resmediyor.','bir dakikalığına ünlü','şarkılarıyla ünlü','chill','exaggeration'),
(4910,'tr','Takım atkısıyla bağırıyor!','Takım atkısıyla uyuyor!','çizgili bir takım atkısı','sıcak bir kışlık atkı','dramatic','exclamation'),
(4911,'tr','Yeni sahibi bu kadın!','Yeni sahibi bu adam!','kafenin yeni sahibi','kafenin yeni aşçısı','gossip','exclamation'),
(4912,'tr','Eğitmen tekme atıyor.','Eğitmen dans ediyor.','bir karate eğitmeni','bir direksiyon eğitmeni','chill','none'),
(4913,'tr','Bir bileklik takıyor.','Bir kolye takıyor.','boncuklu örgü bir bileklik','altın bir bileklik almak','chill','none'),
(4914,'tr','Herkes gitar çalan çocuğa bayılıyor.','Herkes davul çalan çocuğa bayılıyor.','akustik gitar çalmak','akustik gitar tamir etmek','gossip','guessing'),
(4915,'tr','Omuz omuza yürüyorlar.','Omuz omuza oturuyorlar.','omuzlarda kollar','omuzda bir çanta','chill','none'),
(4916,'tr','Başardık! İki bisiklet, bir gün batımı.','Başardık! İki scooter, bir gün batımı.','iskelede bisikletler','trende bisikletler','dramatic','exclamation'),
(4917,'tr','Kırmızı maviye ateş etti. Yakalandın!','Mavi kırmızıya ateş etti. Yakalandın!','oyuncuya boyayla ateş etmek','basket atışı yapmak','dramatic','exclamation'),
(4918,'tr','Merdivenleri çıkıyor.','Merdivenlerden kayarak iniyor.','çantalarla merdivenden yukarı','tek başına merdivenden aşağı','chill','none'),
(4919,'tr','Üyelik için kaydoldu.','Yoga için kaydoldu.','fotoğraf kulübü üyeliği','spor salonu üyelik kartı','chill','none'),
(4920,'tr','Topluluk tezahürat yapıyor!','Topluluk ağlıyor!','topluluk bahçesi tabelası','çevrimiçi bir topluluk','slang','exclamation'),
(4921,'tr','Patika köklerle dolu.','Patika karla dolu.','engebeli bir orman patikası','bir ayak izi dizisi','chill','none'),
(4922,'tr','Ev sahibi misafirlerini karşılıyor.','Ev sahibi misafirlerini görmezden geliyor.','kadeh kaldıran ev sahibi','bir talk show sunucusu','business','none'),
(4924,'tr','Tanıdık bir yüz görüyor.','Tanıdık bir köpek görüyor.','tanıdık bir yüz','tanıdık bir şarkı','chill','none'),
(4925,'tr','Bir hastaya bakıyor.','Bir bebeğe bakıyor.','hastanede bir hastaya bakmak','bir bahçeye bakmak','business','none'),
(4926,'tr','Diş hekiminin elinde ayna var.','Diş hekiminin elinde telefon var.','aynalı bir diş hekimi','diş çeken bir diş hekimi','chill','none'),
(4927,'tr','Avukat tokalaşıyor.','Avukat el ele tutuşuyor.','evrak çantalı bir avukat','dizüstü bilgisayarlı bir avukat','chill','none'),
(4928,'tr','Sızıntıyı kendisi tamir etti!','Arabayı kendisi tamir etti!','akan bir lavaboyu tamir etmek','bozuk bir arabayı tamir etmek','dramatic','exclamation'),
(4929,'tr','Bil bakalım kim en yüksek notu aldı!','Bil bakalım kim kötü not aldı!','en yüksek not','kötü bir not','gossip','exclamation'),
(4930,'tr','Ödülü altın bir yıldız!','Ödülü gümüş bir yıldız!','altın yıldız ödülü','kayıp anahtarlar için ödül','dramatic','exclamation'),
(4931,'tr','Bir diyagramı anlatıyor.','Bir şiiri anlatıyor.','tebeşirle çizilmiş bir diyagram','ders kitabında bir diyagram','nerd','none'),
(4932,'tr','Havalı kasket! Taksinin direksiyonunu o çeviriyor.','Havalı kasket! Teknenin dümenini o tutuyor.','sarı bir taksinin direksiyonunda','sarı bir teknenin dümeninde','flirt','none'),
(4933,'tr','Bir el hep direksiyonda.','Bir el hep telefonda.','otobüs direksiyonu','otobüsün yedek tekerleği','business','none'),
(4934,'tr','Kulaklığını takıyor.','Kaskını takıyor.','yeşil bir pilot kulaklığı','oyun için VR başlığı','chill','none'),
(4935,'tr','Pusulaya dokunuyor.','Telsize dokunuyor.','pirinç bir gemi pusulası','çizim için bir pergel','nerd','none'),
(4936,'tr','Mutfakta yemek yapıyor.','Bahçede yemek yapıyor.','profesyonel bir mutfak','bir ev mutfağı','chill','none'),
(4937,'tr','Zili çalıyor.','Kapı zilini çalıyor.','servis zilini çalmak','bir arkadaşı telefonla aramak','business','none'),
(4938,'tr','İşi başından aşkın bir kadın garson.','İşi başından aşkın bir hemşire.','terasta bir kadın garson','mutfakta bir kadın garson','chill','none'),
(4939,'tr','Altın rengi kabuk. Eline sağlık, fırıncı.','Yanık kabuk. Eline sağlık, fırıncı.','altın rengi kruvasanlar','altın rengi bir alyans','flirt','none'),
(4940,'tr','Kasap eti paketliyor.','Kasap hediyeleri paketliyor.','biftek saran bir kasap','tavuk kesen bir kasap','chill','none'),
(4941,'tr','İtfaiyeci bir kediyi kurtardı!','İtfaiyeci bir köpeği kurtardı!','kedi kurtaran bir itfaiyeci','yangın söndüren bir itfaiyeci','dramatic','exclamation'),
(4942,'tr','Tek parça bagaj mı? Efsane!','Beş parça bagaj mı? Efsane!','omzunda bagaj','bavul arabasında bagaj','slang','exclamation'),
(4943,'tr','Bu kadar övgüye bayılıyor.','Bu kadar övgüden nefret ediyor.','film ekibinden övgü','öğretmeninden övgü','gossip','guessing'),
(4944,'tr','Spot ışığı, güller ve altın bir balo elbisesi!','Spot ışığı, güller ve kırmızı bir balo elbisesi!','açık altın rengi uzun balo elbisesi','gelinlik denemek','dramatic','exclamation'),
(4945,'tr','Mikrofona şarkı söylüyor.','Telefona şarkı söylüyor.','mikrofona şarkı söylemek','koroda şarkı söylemek','chill','none'),
(4946,'tr','At kuyruğu da dans ediyor.','Atkısı da dans ediyor.','sallanan bir at kuyruğu','şapkanın altında at kuyruğu','chill','exaggeration'),
(4947,'tr','Portre bitti. Eller havaya!','Manzara resmi bitti. Eller havaya!','bitmiş bir portre','bir kedi portresi','dramatic','none'),
(4948,'tr','Şehir silueti eşliğinde makyaj. Ne lüks.','Plaj manzarası eşliğinde makyaj. Ne lüks.','arkasında şehir silueti','gün batımında şehir silueti','gossip','none'),
(4949,'tr','Karlı zirveler: muhteşem manzara.','Kum tepeleri: muhteşem manzara.','zirveden dağ manzarası','tren penceresinden manzara','chill','none'),
(4951,'tr','Eve geldi, köpek de havalara uçuyor!','Eve geldi, kedi de havalara uçuyor!','eve, köpeğin yanına dönmek','işe gitmek için evden çıkmak','dramatic','exclamation'),
(4952,'tr','Yatağını çok özlemiş.','Arabasını çok özlemiş.','kendini yatağa atmak','yatağı toplamak','dramatic','guessing'),
(4953,'tr','Fotosentez olmasını umuyor.','Gök gürültülü fırtına olmasını umuyor.','filiz çıkmasını ummak','gökkuşağı çıkmasını ummak','nerd','exaggeration'),
(4954,'tr','Bu ziyaret onu çok mutlu ediyor!','Bu ziyaret onu çok üzüyor!','bir hastane ziyareti','hayvanat bahçesi ziyareti','dramatic','exclamation'),
(4955,'tr','Burada sadece dolaplar düzenli görünüyor.','Burada sadece ranzalar düzenli görünüyor.','bir sıra gri dolap','havuzda bir dolap','ironic','exaggeration'),
(4956,'tr','Resepsiyona yürüyor.','Mutfağa yürüyor.','hostelin resepsiyon masası','bir düğün resepsiyonu','chill','none'),
(4957,'tr','Otel fiyatları ucuzdan 2.000 euroya kadar.','Otel fiyatları ucuzdan 20 euroya kadar.','üç tür otel','deniz kenarında bir otel','business','cheap_quality'),
(4958,'tr','Kulübeden cam villaya!','Kulübeden ahşap villaya!','kocaman bir cam villa','kiralık bir tatil villası','dramatic','exclamation'),
(4959,'tr','Ayçiçekli bir kulübe.','Elma ağaçlı bir kulübe.','küçük ahşap bir kulübe','göl kenarında bir kulübe','chill','none'),
(4960,'tr','Varış salonunda sarılıyorlar!','Varış salonunda kavga ediyorlar!','varış salonunda toplu sarılma','oyuncak ayıya sarılmak','dramatic','exclamation'),
(4961,'tr','Evcil hayvan bir oyuncağın peşinde.','Evcil hayvan bir topun peşinde.','avlanan evcil bir kedi','uyuyan evcil bir kedi','chill','none'),
(4962,'tr','Dürbün kullanıyor. Geyik alarmı!','Teleskop kullanıyor. Geyik alarmı!','dürbünle bakmak','operada dürbün','dramatic','exclamation'),
(4963,'tr','Önce parmağını incitti, sonra ayak parmağını!','Önce parmağını incitti, sonra kulağını!','incinmiş bir parmak','onu parmakla göstermek','dramatic','exclamation'),
(4964,'tr','Önce çorba tadılır, sonra çiçekler gelir. Usta işi.','Önce çorba tadılır, sonra çikolata gelir. Usta işi.','kaşıktan çorba tatmak','partide şarap tatmak','flirt','cliche'),
(4965,'tr','Banyo rutini tamam.','Mutfak rutini tamam.','banyoda diş fırçalamak','banyoda şarkı söylemek','business','none'),
(4966,'tr','Buz ikiye yarıldı.','Buz üçe yarıldı.','bir buz kalıbını yarmak','bir kütüğü yarmak','nerd','none'),
(4967,'tr','Bir tarayıcı kimliğini kontrol ediyor.','Bir tarayıcı bagajını kontrol ediyor.','kimliğini kontrol etmek','kimliğini gizlemek','nerd','none'),
(4968,'tr','Yeni kimlik kartını aldı!','Yeni telefonunu aldı!','yeni bir kimlik kartı','yeni bir doğum günü kartı','slang','exclamation'),
(4969,'tr','Kafede kazanan: kızın kitabı.','Kafede kazanan: oğlanın telefonu.','kafe masasında kitap okumak','kafe mutfağında çalışmak','gossip','banter'),
(4970,'tr','Bağımsızlık için havai fişekler!','Bağımsızlık için mumlar!','bağımsızlığı kutlamak','bağımsızlık için savaşmak','dramatic','none'),
(4971,'tr','Havai fişekler kubbeyi aydınlatıyor.','Havai fişekler köprüyü aydınlatıyor.','kubbenin üstünde havai fişekler','gölün üstünde havai fişekler','chill','none'),
(4972,'tr','Ne vatansever bir gece!','Ne vatansever bir sabah!','vatansever bir kalabalık','vatansever bir askeri geçit töreni','dramatic','exclamation'),
(4973,'tr','Bir anıtın önünde poz veriyor.','Bir şelalenin önünde poz veriyor.','beyaz bir anıtta poz vermek','dağda bir anıt','chill','none'),
(4974,'tr','Satıcı çayı usta gibi dolduruyor.','Satıcı usta gibi hokkabazlık yapıyor.','çay dolduran bir satıcı','bir çiçek satıcısı','flirt','cliche'),
(4975,'tr','Kızın tarzı çok farklı!','Oğlanın tarzı çok farklı!','kalabalıktan farklı','kız kardeşinden farklı','flirt','exclamation'),
(4976,'tr','Suda yürüyerek ilerliyor.','Karda yürüyerek ilerliyor.','pirinç tarlalarında suda yürümek','derin karda yürümek','chill','none'),
(4977,'tr','Bir el yolu gösteriyor.','Bir köpek yolu gösteriyor.','uzatılmış açık bir el','pirinç dolu bir el','chill','none'),
(4978,'tr','Aşçı ateşle oynuyor!','Aşçı buzla oynuyor!','wok başında bir aşçı','ızgara başında bir aşçı','slang','cliche'),
(4979,'tr','Bütün ofis hasta!','Bütün ofis uyuyor!','ofiste öksürmek','ofiste şarkı söylemek','dramatic','exaggeration'),
(4980,'tr','Derin nefes alıyorlar.','Yüksek sesle bağırıyorlar.','temiz havada nefes almak','su altında nefes almak','chill','none'),
(4981,'tr','Herkes aşısını oldu. Yaşasın!','Kimse aşı olmadı. Yaşasın!','üst kollarda aşılar','bacakta bir aşı','dramatic','exclamation'),
(4982,'tr','Ayak bileğini tutuyor.','Başını tutuyor.','incinmiş bir ayak bileği','ayak bileğinde bir halhal','chill','none'),
(4983,'tr','Subay her yeri kontrol ediyor, minibüsün altını bile!','Subay her yeri kontrol ediyor, otobüsün altını bile!','minibüsü kontrol eden bir subay','gemideki bir subay','dramatic','exaggeration'),
(4984,'tr','Elinde evrak çantasıyla kayıyor!','Elinde kahve bardağıyla kayıyor!','evrak çantasıyla kaymak','kâğıt dolu bir evrak çantası','gossip','exclamation'),
(4985,'tr','Ekranlar yerine sabitlenmiş.','Aynalar yerine sabitlenmiş.','ekranları duvara sabitlemek','toplantı tarihini sabitlemek','business','none'),
(4986,'tr','Duvar biraz parlak.','Duvar biraz karanlık.','parlak mavi ekranlar','parlak güneşli bir gün','ironic','understatement'),
(4987,'tr','Projesini sundu. Kazanan kahve oldu.','Projesini sundu. Kazanan pizza oldu.','çalışmasını sunmak','bir TV programı sunmak','ironic','exaggeration'),
(4988,'tr','Saldırı başlıyor!','Piknik başlıyor!','bir ortaçağ saldırısı','bir kalp krizi','dramatic','exclamation'),
(4989,'tr','Tepeden aşağı hücum ediyorlar!','Yoldan aşağı hücum ediyorlar!','tepeden aşağı hücum','tepeden aşağı yuvarlanmak','dramatic','exclamation'),
(4990,'tr','Ağır bir ütü kullanıyor.','Ağır bir çekiç kullanıyor.','ağır bir buharlı ütü','demir bir tava','chill','none'),
(4991,'tr','Ne dağınık bir kıyafet yığını!','Ne dağınık bir kitap yığını!','dağınık bir kıyafet yığını','dağınık bir mutfak masası','dramatic','exclamation'),
(4992,'tr','Bu kadar ütü! Çok meşgul.','Bu kadar yemek! Çok meşgul.','ütüyle meşgul','bulaşıkla meşgul','dramatic','exclamation'),
(4993,'tr','Gölde yapayalnız.','Sahilde yapayalnız.','minik bir adada yalnız','büyük bir şehirde yalnız','chill','none'),
(4994,'tr','Ahşap bir kaşık kullanıyor.','Metal bir kaşık kullanıyor.','uzun ahşap bir kaşık','ahşap bir kesme tahtası','chill','none'),
(4995,'tr','Heykelli bir çeşme.','Saatli bir çeşme.','taş bir çeşme heykeli','düğün için buz heykeli','chill','none'),
(4996,'tr','Güvercinler dondurma külahına bayılıyor.','Martılar dondurma külahına bayılıyor.','bir dondurma külahı','turuncu bir trafik konisi','gossip','guessing'),
(4997,'tr','Kahkahası çok gür.','Kahkahası çok sessiz.','Kolezyum''da bir kahkaha','Paris''te bir kahkaha','chill','none'),
(4998,'tr','Tünel kapılardan oluşuyor.','Tünel ağaçlardan oluşuyor.','tapınak kapılarından bir tünel','denizin altında bir tünel','chill','none'),
(5000,'tr','İnce dilimleri kusursuz görünüyor.','Kalın dilimleri kusursuz görünüyor.','ince balık dilimleri','ince ekmek dilimleri','flirt','none'),
(5001,'tr','Bu manzaraya değdi.','Bu plaja değdi.','bir dağ manzarası','bir manzara tablosu','slang','cliche'),
(5002,'tr','Alacakaranlıkta suya atlıyorlar.','Öğlen suya atlıyorlar.','alacakaranlıkta bir orman gölü','büyük bir şehirde alacakaranlık','chill','none'),
(5003,'tr','Bir kâşif kendine yol açıyor.','Bir kâşif ağaç kesiyor.','palalı bir kâşif','haritalı bir kâşif','chill','none'),
(5004,'tr','Kanguru ileri sıçrıyor.','Kanguru geri sıçrıyor.','kumun üstünde sıçramak','yataktan sıçramak','chill','none'),
(5005,'tr','Bu koyda her şeyi görüyor.','Bu parkta her şeyi görüyor.','sakin bir koyda tekneler','buzla dolu bir koy','gossip','guessing'),
(5006,'tr','Su ısıtıcısı var gücüyle çalışıyor.','Ekmek kızartma makinesi var gücüyle çalışıyor.','su ısıtıcısında su kaynatmak','ateşin üstünde bir su ısıtıcısı','chill','exaggeration'),
(5007,'tr','Evet! Anahtarı kilitte!','Evet! Anahtarı arabada!','kilitte bir anahtar','bisiklette bir kilit','dramatic','exclamation'),
(5008,'tr','Ahşap kapının kilidini açtı.','Garaj kapısının kilidini açtı.','ahşap kapının kilidini açmak','bir telefonun kilidini açmak','chill','none'),
(5009,'tr','Çocuk kaydıraktan kayıyor.','Çocuk yukarı tırmanıyor.','kaydırakta bir çocuk','salıncakta bir çocuk','chill','none'),
(5010,'tr','Yaşasın kral!','Yaşasın kraliçe!','balkonda bir kral','at üstünde bir kral','dramatic','cliche'),
(5011,'tr','Yaşlı çift öpüşüyor, çok tatlı!','Yaşlı çift dans ediyor, çok tatlı!','öpüşen yaşlı bir çift','dans eden yaşlı bir çift','gossip','exclamation'),
(5012,'tr','Paris aşk dolu!','Paris kar dolu!','Paris''te aşk','bir aşk romanı','dramatic','exaggeration'),
(5013,'tr','Ucuz mutfak eski.','Ucuz mutfak kocaman.','ucuz, eski bir mutfak','ucuz, hızlı bir araba','chill','none'),
(5014,'tr','Zengin aşçının manzarası en iyisi.','Zengin aşçının köpeği en iyisi.','zengin bir adamın mutfağı','zengin bir adamın arabası','gossip','none'),
(5015,'tr','Ev yapımı ekmek, elde yoğrulmuş.','Ev yapımı makarna, elde yoğrulmuş.','ev yapımı bir somun ekmek','kavanozda ev yapımı reçel','chill','none'),
(5016,'tr','Dizlerini büküyor.','Kollarını büküyor.','çömelirken çıplak dizler','tek diz üstünde','business','none'),
(5017,'tr','Doğranmış sebzelerden bir gökkuşağı!','Doğranmış meyvelerden bir gökkuşağı!','sıra sıra doğranmış sebzeler','vazoda kesilmiş çiçekler','dramatic','exclamation'),
(5018,'tr','O yemek çok lezzetli görünüyor!','O çorba çok lezzetli görünüyor!','lezzetli bir kase pilav','lezzetli bir dilim pasta','gossip','exclamation'),
(5019,'tr','Sığır eti ızgara yapıyor.','Balık ızgara yapıyor.','ızgara sığır eti dilimleri','patates kızartmalı dana burger','chill','none'),
(5020,'tr','Bir ampulü değiştirmek için iki kişi!','Bir ampulü değiştirmek için beş kişi!','yanmış bir ampulü değiştirmek','patlak bir lastiği değiştirmek','low_iq','cliche'),
(5021,'tr','Çay dolduran ne zarif bir hanımefendi.','Şarap dolduran ne zarif bir hanımefendi.','boneli bir hanımefendi','at üstünde bir hanımefendi','flirt','none'),
(5022,'tr','Avize parlıyor!','Ayna parlıyor!','parlayan bir avize','parlayan ayakkabılar','dramatic','exclamation'),
(5023,'tr','Bir uçağa tezahürat yapıyor!','Bir trene tezahürat yapıyor!','alçaktan inen bir uçak','havalanan bir uçak','dramatic','exclamation'),
(5024,'tr','Bütün sözlükler onda!','Bütün yemek kitapları onda!','bir yığın sözlük','bir sözlük uygulaması','dramatic','exaggeration'),
(5025,'tr','Aman tanrım, bu şaka çok komik!','Aman tanrım, bu ders çok komik!','telefonda bir şaka','öğretmenden bir şaka','gossip','exclamation'),
(5026,'tr','Telefonu bugün çok komik.','Kitabı bugün çok komik.','derste çok komik','düğünde çok komik','gossip','none'),
(5027,'tr','Hâkim tokmağını kullanıyor.','Hâkim telefonunu kullanıyor.','tokmaklı bir hâkim','peruklu bir hâkim','business','none'),
(5028,'tr','Zor dava mı? Sadece birkaç kitap.','Zor dava mı? Sadece birkaç kalem.','zor bir mahkeme davası','zor bir sınav','ironic','understatement'),
(5029,'tr','Oğlanın jesti diyor ki: Kazandım!','Kızın jesti diyor ki: Kazandım!','zafer yumruğu jesti','kaba bir el jesti','dramatic','guessing'),
(5030,'tr','Kostümünde her renk var!','Şapkasında her renk var!','gökkuşağı renkli tüylü kostüm','Cadılar Bayramı kostümü','gossip','exaggeration'),
(5031,'tr','Lider ileriyi gösteriyor.','Lider oturuyor.','dağda bir lider','sahilde bir lider','chill','none'),
(5032,'tr','Önde yürüyüp takımı ileri götürüyor.','Önde yürüyüp takımı geri götürüyor.','grubun önünde yürümek','gezi için önceden plan yapmak','business','none'),
(5033,'tr','Komşular bu davulları duyuyordur.','Komşular bu boruları duyuyordur.','davul çalmak','bir davul solosu','ironic','guessing'),
(5035,'tr','Bu hokkabazın yeteneği var ya!','Bu şarkıcının yeteneği var ya!','hokkabazlık yeteneği','bir yetenek yarışması','slang','exclamation'),
(5036,'tr','Kız öğretiyor, oğlan öğreniyor. Yavaş yavaş.','Oğlan öğretiyor, kız öğreniyor. Yavaş yavaş.','hokkabazlık öğrenmek','dans öğrenmek','chill','banter'),
(5037,'tr','Bir Paris kaldırımında.','Bir Paris köprüsünde.','geniş, döşeli bir kaldırım','kaldırımda bir kafe masası','chill','none'),
(5038,'tr','Çin Seddi''nde yukarı doğru sabit tempo.','Çin Seddi''nde aşağı doğru sabit tempo.','sabit bir koşu temposu','yavaş bir yürüyüş temposu','chill','none'),
(5039,'tr','Kafesleri açıyor.','Kafesleri kapatıyor.','kuş kafeslerini açmak','kuş kafeslerini temizlemek','chill','none'),
(5040,'tr','Koltuk mu? Bisikletle mi? Tabii canım.','Kanepe mi? Bisikletle mi? Tabii canım.','sarı kadife bir koltuk','arabada bir koltuk','ironic','understatement'),
(5041,'tr','Beyaz bir parlama çatıyı aydınlatıyor.','Yeşil bir parlama çatıyı aydınlatıyor.','kör edici beyaz bir parlama','kapalı alanda flaş parlaması','dramatic','none'),
(5042,'tr','Bacak günü acı vericiydi!','Kol günü acı vericiydi!','bacaklarda acı verici tutulma','acı verici bir güneş yanığı','dramatic','exclamation'),
(5043,'tr','Aslan hiç sessiz değil.','Aslan hiç yalnız değil.','hiç sessiz olmayan bir aslan','sessiz bir aslan','ironic','understatement'),
(5044,'tr','Kapının arkasından duyabiliyor.','Duvarın arkasından duyabiliyor.','kapının ardından duymak','kapı zilinin çaldığını duymak','chill','none'),
(5045,'tr','Hoparlörler kocaman ses çıkarıyor!','Davullar kocaman ses çıkarıyor!','bir teypten gelen ses','araba radyosundan gelen ses','low_iq','exclamation'),
(5046,'tr','Televizyon onu yerinden zıplattı!','Televizyon onu ağlattı!','televizyon izlemek','televizyonu tamir etmek','slang','blaming_someone'),
(5047,'tr','Bu gece kimse oturma odasından çıkmıyor.','Bu gece kimse mutfaktan çıkmıyor.','sıcacık bir oturma odası','oturma odasını temizlemek','gossip','guessing'),
(5048,'tr','Kocaman asma kilit, kapılar hâlâ kapalı.','Kocaman asma kilit, kapılar ardına kadar açık.','sımsıkı kapalı kapılar','sımsıkı kapalı gözler','ironic','understatement'),
(5049,'tr','Sokak kapısını kapatıyor.','Garaj kapısını kapatıyor.','sokak kapısını kapatmak','bir dükkânı kapatmak','chill','none'),
(5050,'tr','Kaybetti ve misafirler gitti.','Kazandı ve misafirler gitti.','seçimi kaybetmek','araba anahtarlarını kaybetmek','gossip','none'),
(5051,'tr','Onu kaybetti. Pasaport mu acaba?','Onu buldu. Pasaport mu acaba?','önemli bir şeyi kaybetmek','bir futbol maçını kaybetmek','gossip','guessing'),
(5052,'tr','Çantalar hiç hafif değil.','Sandalyeler hiç hafif değil.','hiç hafif olmayan bavullar','hafif bir kabin bagajı','chill','understatement'),
(5053,'tr','Etikette onun fotoğrafı var.','Etikette onun köpeği var.','fotoğraflı bir etiket','kavanozda bir etiket','business','none'),
(5054,'tr','Kanka evin yarısını kaldırıyor.','Kanka çadırın yarısını kaldırıyor.','kolileri minibüse kaldırmak','spor salonunda ağırlık kaldırmak','slang','exaggeration'),
(5055,'tr','İki pembe organ: akciğerler.','İki pembe organ: böbrekler.','bir çift solunum organı','çalan bir kilise orgu','nerd','none'),
(5056,'tr','Oda görevlisi havludan kuğu yaptı.','Oda görevlisi havludan köpek yaptı.','havlu katlayan oda görevlisi','şatoda bir oda görevlisi','chill','none'),
(5057,'tr','Postası her yere uçuşuyor!','Parası her yere uçuşuyor!','posta kutusundan çıkan postalar','bilgisayarda e-posta','dramatic','exaggeration'),
(5058,'tr','Çocuk artık postacıya bayılıyor.','Çocuk artık öğretmene bayılıyor.','mektup getiren bir postacı','köpekli bir postacı','gossip','guessing'),
(5059,'tr','Bir sürü mektup almış!','Bir sürü çiçek almış!','bir deste mektup','okuldan bir mektup','slang','exclamation'),
(5060,'tr','Bu videoda sadece erkekler var.','Bu videoda sadece kızlar var.','her yaştan erkekler','futbol takımındaki erkekler','gossip','none'),
(5061,'tr','Vay canına, ne akvaryum ama!','Vay canına, ne yanardağ ama!','kocaman bir akvaryum','kocaman bir yüzme havuzu','dramatic','exclamation'),
(5062,'tr','Patron grafik çiziyor.','Patron kedi çiziyor.','talimat veren bir patron','mola veren bir patron','business','none'),
(5063,'tr','Kortej düzen içinde ilerliyor.','Kalabalık düzen içinde ilerliyor.','tören adımıyla yürüyen bir kortej','gazetede bir köşe yazısı','business','none'),
(5064,'tr','Yüz trompet. Zavallı kulaklarım!','Yüz keman. Zavallı kulaklarım!','trompetlerle yürümek','caz kulübünde bir trompet','dramatic','exaggeration'),
(5065,'tr','Uzun bir baharat koridoru.','Uzun bir ayakkabı koridoru.','baharat tezgâhları arasında koridor','uçağın koridoru','chill','none'),
(5066,'tr','Numune olarak sadece bir zeytin.','Numune olarak sadece bir hurma.','numune olarak bir zeytin','bir baharat numunesi','ironic','understatement'),
(5067,'tr','Evlilik bir öpücükle başlar!','Evlilik bir kavgayla başlar!','konfetili bir evlilik','kilisede bir evlilik','dramatic','exclamation'),
(5068,'tr','Gelin yüzüğü veriyor.','Gelin konuşma yapıyor.','sahilde bir gelin','kilisede bir gelin','chill','none'),
(5069,'tr','Vay be! Masajdan keyif alıyor.','Vay be! Kahveden keyif alıyor.','boyun masajından keyif almak','ayak masajından keyif almak','dramatic','exclamation'),
(5070,'tr','Her yatağı tek tek deniyor.','Her yastığı tek tek deniyor.','yatağa sırtüstü uzanmak','yatak taşımak','chill','none'),
(5071,'tr','Aracın bakımını yapıyor.','Bisikletin bakımını yapıyor.','gümüş bir arabanın bakımını yapmak','çamaşır makinesinin bakımını yapmak','business','none'),
(5072,'tr','Kahverengi sıvı çok viskoz.','Yeşil sıvı çok viskoz.','kahverengi bir sıvı dökmek','berrak bir sıvı dökmek','nerd','none'),
(5073,'tr','Bu ilacın tadı berbat!','Bu ilacın tadı harika!','bir kaşık kahverengi ilaç','köpek için bir ilaç','dramatic','exclamation'),
(5074,'tr','Herkes kadına kendini tanıtıyor.','Herkes adama kendini tanıtıyor.','yeni bir iş arkadaşını tanıtmak','yeni bir ürünü tanıtmak','business','none'),
(5075,'tr','Yapışkan eller, boş külah. "Harika."','Yapışkan eller, dolu külah. "Harika."','dondurmadan yapışkan eller','kolide yapışkan bant','ironic','understatement'),
(5076,'tr','Kulübün yeni üyesi o.','Müzik grubunun yeni üyesi o.','kulübün yeni üyesi','bir müzik grubunun üyesi','business','none'),
(5077,'tr','Oğlan her kartı hatırladı, çantada keklik.','Kız her kartı hatırladı, çantada keklik.','kartlardaki cevapları hatırlamak','arızalı arabayı geri çağırmak','slang','understatement'),
(5078,'tr','Domuz etli taco yapıyor.','Balıklı taco yapıyor.','kızarmış domuz eti dilimlemek','tavada domuz pirzolası','chill','none'),
(5079,'tr','Önce taco, sonra piramit.','Önce taco, sonra plaj.','ormanda bir piramit','çölde bir piramit','ironic','cliche'),
(5080,'tr','Sarı elbise çok yakışmış.','Sarı kaban çok yakışmış.','parlak sarı bir yazlık elbise','parlak sarı bir yağmurluk','flirt','none'),
(5081,'tr','Mor tam onun rengi.','Yeşil tam onun rengi.','vücuda oturan mor bir elbise','mor ipek bir eşarp','flirt','none'),
(5082,'tr','İki topuz mu? Harika saç modeli.','İki örgü mü? Harika saç modeli.','iki topuzlu bir saç modeli','kâküllü bir saç modeli','flirt','none'),
(5083,'tr','Orman meyvesi ekliyorlar.','Kuruyemiş ekliyorlar.','hamurda kırmızı orman meyveleri','ormanda böğürtlen toplamak','chill','none'),
(5084,'tr','Yeşil gece elbisesi büyüleyici!','Kırmızı gece elbisesi büyüleyici!','uzun yeşil bir gece elbisesi','yeşil bir gece çantası','dramatic','exclamation'),
(5085,'tr','Heykel gibi poz veriyor!','Muhafız gibi poz veriyor!','heykelle bir selfie','atla bir selfie','gossip','exclamation'),
(5086,'tr','Zemin ne kadar parlak!','Zemin ne kadar tozlu!','parlak bir taş zemin','parlak yeni bir telefon','dramatic','exclamation'),
(5087,'tr','Patiler yüzünden zemin kirli.','Patiler yüzünden duvar kirli.','kirli, fayanslı bir zemin','lavaboda kirli bulaşıklar','gossip','blaming_someone'),
(5088,'tr','Çocuk uyanık ve esniyor.','Çocuk uyanık ve yemek yiyor.','gün doğumunda uyanık','gece yarısı uyanık','chill','none'),
(5089,'tr','Bu anne her şeyi yapıyor.','Bu baba her şeyi yapıyor.','krep çeviren bir anne','krep satın alan bir anne','chill','exaggeration'),
(5090,'tr','Oyuncak dolu, sıcacık bir bebek odası.','Oyuncak dolu, sıcacık bir mutfak.','beşikli bir bebek odası','bir fidanlık','chill','none'),
(5091,'tr','Küçük motosiklet yeşil.','Küçük motosiklet kırmızı.','şehirde yeşil bir motosiklet','satılık yeşil bir motosiklet','chill','none'),
(5092,'tr','Yardımcımız kolileri profesyonel gibi taşıyor.','Yardımcımız bitkileri profesyonel gibi taşıyor.','koli taşıyan bir yardımcı','lamba taşıyan bir yardımcı','slang','exaggeration'),
(5094,'tr','Sıska kolunu kasıyor.','Sıska bacağını kasıyor.','sıska bir kolu kasmak','dar kot pantolon giymek','chill','none'),
(5095,'tr','Hayranlıkla yukarı bakıyor!','Hayranlıkla aşağı bakıyor!','dev bir iskelete hayranlık','minik bir madeni paraya hayranlık','dramatic','exclamation'),
(5096,'tr','Mantarlar yerden bitiyor.','Mantarlar sudan bitiyor.','yerde bir mantar','pizzada bir mantar','chill','none'),
(5097,'tr','Müziği sokağı durdurdu.','Müziği sokağı boşalttı.','sokak müziği','bir müzik dükkânı','chill','exaggeration'),
(5098,'tr','Adam ulusal takımına bayılıyor.','Kadın ulusal takımına bayılıyor.','yüzde ulusal renkler','ulusal bir bayram','chill','guessing'),
(5099,'tr','Herkes bir fotoğraf ekliyor!','Herkes bir pul ekliyor!','dünya haritasında fotoğraflar','bir fotoğraf albümü','gossip','none'),
(5100,'tr','Fotoğrafları haritaya tutturuyorlar.','Fotoğrafları kapıya tutturuyorlar.','fotoğrafları haritaya tutturmak','haritaları duvara tutturmak','chill','none'),
(5101,'tr','Bu yolculukta mide bulantısı önde.','Bu uçuşta mide bulantısı önde.','vapurda mide bulantısı','arabada mide bulantısı','dramatic','exaggeration'),
(5102,'tr','Bu ara sokak aşırı dar!','Bu ara sokak aşırı geniş!','dar bir medine ara sokağı','kedilerle dolu bir ara sokak','slang','exaggeration'),
(5103,'tr','Bir zürafanın boynu tam üstünde!','Bir atın boynu tam üstünde!','zürafanın uzun boynu','boynunda bir yılan','dramatic','exclamation'),
(5104,'tr','Sohbetleri dostça.','Sohbetleri öfkeli.','çitin üstünden sohbet','konferansta bir konuşma','chill','none'),
(5105,'tr','Ördek dolu bir hendek.','Tekne dolu bir hendek.','düz bir su hendeği','otoyol kenarında bir hendek','chill','exaggeration'),
(5106,'tr','Yel değirmeni, laleler, stroopwafel: tamam.','Yel değirmeni, laleler, pizza dilimi: tamam.','dönen bir yel değirmeni','sahilde bir yel değirmeni','ironic','cliche'),
(5107,'tr','İkisi de bebeği kucağında sallıyor.','İkisi de bebeği yıkıyor.','yeni doğanı kucağında sallamak','bir çay fincanını iki eliyle tutmak','chill','none'),
(5108,'tr','Köy suyun üstünde.','Köy tepenin üstünde.','kazıklar üstünde bir köy','karlar içinde bir köy','business','none'),
(5109,'tr','Bir düzine tatlı kek, o da tek başına yiyor.','Bir düzine tatlı kurabiye, o da tek başına yiyor.','bir tepsi tatlı kek','tatlı bir fincan çay','ironic','guessing'),
(5110,'tr','Park çok sakin.','Sahil çok sakin.','sisli, sakin bir park','sisli, sakin bir sahil','chill','none'),
(5111,'tr','Hasta bir çocuğa bakıyor.','Hasta bir yavru köpeğe bakıyor.','hasta bir çocuğa bakmak','bir bardak suya bakmak','chill','none'),
(5112,'tr','Taneler havada uçuşuyor.','Taneler bir fincanın içine uçuşuyor.','düşen pirinç taneleri','bir kum tanesi','chill','none'),
(5113,'tr','İyi bir tavsiye: daha çok balık ye.','İyi bir tavsiye: daha çok pasta ye.','sağlıklı beslenme tavsiyesi','para konusunda tavsiye','business','none'),
(5114,'tr','Flamingolar uçup gidiyor.','Kuğular uçup gidiyor.','bir flamingo sürüsü','hayvanat bahçesinde bir flamingo','chill','none'),
(5115,'tr','Bir böceği inceliyor.','Bir çiçeği inceliyor.','küçük bir böceği incelemek','sınav için ders çalışmak','chill','none'),
(5116,'tr','Bütün pencereleri açıyor!','Bütün pencereleri kapatıyor!','pencereleri açmak','bir hediye açmak','dramatic','exclamation'),
(5117,'tr','Bu kitapçıya bayılıyor!','Bu kitapçıdan nefret ediyor!','tıklım tıklım eski bir kitapçı','kapanan bir kitapçı','slang','exclamation'),
(5118,'tr','Üstüne gün ışığı yağıyor. Ne sabah ama!','Üstüne yağmur yağıyor. Ne sabah ama!','pencereden gelen gün ışığı','ağaçların arasından gün ışığı','dramatic','none'),
(5119,'tr','Girişte ahşap kapılar var.','Girişte cam kapılar var.','park girişi','müze girişi','chill','none'),
(5120,'tr','Bitti! Cerrahlar mutlu.','Bitti! Fırıncılar mutlu.','hastanın başında cerrahlar','bekleme salonunda cerrahlar','dramatic','exclamation'),
(5121,'tr','Muffinleri fırından çıkarıyor.','Kurabiyeleri fırından çıkarıyor.','bir tepsi muffini çıkarmak','fırın kapağını çıkarmak','chill','none'),
(5122,'tr','Hepsi başardı, hedeflerine ulaştılar.','Hepsi kaçırdı, hedeflerine ulaşamadılar.','zor bir hedefi başarmak','iyi notlar almayı başarmak','chill','none'),
(5123,'tr','Kahve, lavabo ve küvet taşıp her yeri sular altında bırakıyor!','Kahve, lavabo ve fırın taşıp her yeri sular altında bırakıyor!','banyoyu sular altında bırakan küvet','yağmurdan sonra sular altında kalan yol','dramatic','exaggeration'),
(5124,'tr','Eski şehirde maraton.','Ormanda maraton.','şehir maratonu koşmak','bir film maratonu','chill','none'),
(5125,'tr','Bir devrim sahneliyorlar!','Bir düğün sahneliyorlar!','eski bir oyunu sahnelemek','bir protesto sahnelemek','dramatic','exclamation'),
(5126,'tr','İşletmesiyle gurur duyuyor.','Arabasıyla gurur duyuyor.','köşede küçük bir işletme','büyük bir online işletme','chill','none'),
(5127,'tr','Bavulu bir türlü kapatamıyor!','Bavulu bir türlü açamıyor!','dolu bir bavulu kapatmak','bir pencereyi kapatmak','dramatic','exclamation'),
(5128,'tr','Kanepe gerçek bir yara açtı!','Masa gerçek bir yara açtı!','kanepe köşesinden yara','futbol maçından yara','dramatic','blaming_someone'),
(5129,'tr','Mobilyalar örtülerin altında.','Mobilyalar havluların altında.','mobilyalarda gri örtüler','bir kitap kabı','business','none'),
(5130,'tr','Uçurtması öyle yüksekte uçuyor ki!','Dronu öyle yüksekte uçuyor ki!','uçurtma uçurmak','ağaca takılmış bir uçurtma','slang','exaggeration'),
(5131,'tr','Topa odaklanıyor.','Çocuklara odaklanıyor.','topa odaklanmak','kalabalığa odaklanmak','chill','none'),
(5132,'tr','Karışımı döküyor.','Karışımı karıştırıyor.','tavada krep karışımı','boya renklerinin karışımı','chill','none'),
(5133,'tr','Parkta çığlık atıyor.','Havuzda çığlık atıyor.','heykel oyununda çığlık atmak','korku filminde çığlık atmak','chill','none'),
(5134,'tr','Ebeveynler biraz meşgul.','Köpekler biraz meşgul.','bebeği besleyen ebeveynler','ördekleri besleyen ebeveynler','ironic','understatement'),
(5135,'tr','Dar yer, kusursuz park.','Geniş yer, kusursuz park.','dar bir park yeri','uzay roketi fırlatma','flirt','none'),
(5136,'tr','Tartışmanın sesi yükseliyor!','Tartışmanın sesi alçalıyor!','gürültülü bir tartışma','televizyonda bir tartışma','dramatic','exclamation'),
(5137,'tr','Parlamento bugün dolu.','Parlamento bugün boş.','dolu bir parlamento','boş bir parlamento','business','none'),
(5138,'tr','Şu an trende.','Şu an otobüste.','trende bir koltuk','uçakta bir koltuk','chill','none'),
(5139,'tr','Sayfalar başta boştu.','Sayfalar başta doluydu.','boş bir pasaport sayfası','boş bir yüz ifadesi','chill','none'),
(5140,'tr','Damga girmesine izin veriyor.','Damga araba kullanmasına izin veriyor.','girişe izin verilmiş','sigaraya izin verilmiş','business','none'),
(5141,'tr','Doktorun elinde stetoskop var.','Doktorun elinde kamera var.','stetoskoplu bir doktor','ambulansta bir doktor','chill','none'),
(5142,'tr','Mahalle süslenmiş.','Mahalle bomboş.','süslenmiş bir mahalle','mahallede ikinci el pazarı','chill','none'),
(5144,'tr','Kızlar güvercinleri uçuruyor!','Oğlanlar güvercinleri uçuruyor!','beyaz güvercinleri uçurmak','beyaz güvercinleri beslemek','dramatic','exclamation'),
(5145,'tr','Tramvay tam arkasında.','Otobüs tam arkasında.','meydanda bir tramvay','köprüde bir tramvay','chill','none'),
(5146,'tr','Kabuk tek, uzun bir şerit!','Kabuk iki kısa şerit!','uzun bir kabuk şeridi','bir bant şeridi','dramatic','exclamation'),
(5147,'tr','Ne çok insan karşıya geçiyor!','Ne çok araba karşıya geçiyor!','yaya geçidini dolduran insanlar','otobüs bekleyen insanlar','dramatic','exclamation'),
(5148,'tr','Hayırlı sabahlar, bomboş şehir!','Hayırlı geceler, bomboş şehir!','bomboş bir sabah sokağı','kalabalık bir sabah sokağı','dramatic','exclamation'),
(5149,'tr','Ne büyük, eski bir eczane!','Ne büyük, eski bir fırın!','görkemli, eski bir eczane','hastanede bir eczane','dramatic','exclamation'),
(5150,'tr','Reçetesini ibraz ediyor.','Tren biletini ibraz ediyor.','reçeteyi uzatmak','reçete yazmak','business','none'),
(5151,'tr','Çerçeve gümüş.','Çerçeve altın.','gümüş bir resim çerçevesi','gümüş bir pencere çerçevesi','chill','none'),
(5152,'tr','Yatak odası baştan aşağı yastık!','Yatak odası baştan aşağı kitap!','yatak odasında yastıklar','oturma odasında yastıklar','dramatic','exaggeration'),
(5153,'tr','Ekip tarhı ekiyor.','Ekip tarhı boyuyor.','yükseltilmiş bir bahçe tarhı','toplanmamış bir yatak','business','none'),
(5154,'tr','Ev bitkileri resmen orman olmuş.','Kitapları resmen orman olmuş.','ev bitkileriyle dolu bir oda','satılık bir ev bitkisi','chill','exaggeration'),
(5155,'tr','Bütün aileye öğle yemeği!','Sadece iki kişiye öğle yemeği!','kalabalık bir aile öğle yemeği','işte hızlı bir öğle yemeği','dramatic','exclamation'),
(5156,'tr','Gol attı, o yüzden diz çöküyor.','Kaçırdı, o yüzden diz çöküyor.','çimlere diz çökmek','dua etmek için diz çökmek','dramatic','none'),
(5157,'tr','Bütün semt futbol oynuyor!','Bütün semt voleybol oynuyor!','semtte bir futbol maçı','semtte bir bisiklet yarışı','dramatic','exaggeration'),
(5158,'tr','Kabloları bağlıyor.','Kabloları kesiyor.','oyun sistemini bağlamak','arkadaşlarla bağ kurmak','nerd','none'),
(5159,'tr','Boru onu bilerek ıslattı.','Köpek onu bilerek ıslattı.','tesisatçının yüzünü ıslatmak','mutfaktaki bitkileri ıslatmak','ironic','blaming_someone'),
(5160,'tr','Yağmurda koşturuyor.','Karda koşturuyor.','güvercinlerin yanından koşturmak','polisin yanından koşturmak','chill','none'),
(5161,'tr','Bir katedralin önünde duruyor.','Bir şatonun önünde duruyor.','tuğla bir katedral kulesi','karanlık bir katedralin içi','chill','none'),
(5162,'tr','Güzel manzaralar ve mantı.','Güzel manzaralar ve krep.','güzel bir dağ gölü','güzel bir plaj','chill','none'),
(5163,'tr','Politikacılar, her zamanki gibi tartışıyor.','Politikacılar, her zamanki gibi sarılıyor.','parmak sallayan öfkeli politikacılar','tokalaşan politikacılar','ironic','cliche'),
(5164,'tr','Bu kampanyada her şey var: afişler, tartışmalar, konfeti.','Bu kampanyada her şey var: afişler, tartışmalar, havai fişekler.','bir seçim kampanyası','sigara karşıtı bir kampanya','gossip','exaggeration'),
(5165,'tr','Nehir plastikle dolu.','Nehir balıkla dolu.','nehirde plastik','geri dönüşüm kutusunda plastik','dramatic','none'),
(5166,'tr','Tramvay rayların üstünde.','Tramvay çimlerin üstünde.','parke taşlarında tramvay rayları','tünelde tramvay rayları','chill','none'),
(5167,'tr','Mavi karolara dokunuyor.','Kırmızı karolara dokunuyor.','mavi beyaz duvar karoları','banyo zemininde karolar','chill','none'),
(5168,'tr','Bu parti tartlar fena değil.','Bu parti ekmekler fena değil.','bir parti muhallebili tart','bir parti kurabiye','chill','understatement'),
(5169,'tr','Bir kartpostal postalıyor.','Bir paket postalıyor.','kartpostal postalamak','koli postalamak','chill','none'),
(5170,'tr','Bir paket uzatıyor.','Bir pizza uzatıyor.','sarılı bir doğum günü paketi','bir tur paketi','chill','none'),
(5171,'tr','Tencereye et suyu ekliyor.','Tencereye süt ekliyor.','tencereye sebze eklemek','çorbaya tuz eklemek','chill','none'),
(5172,'tr','Zavallı hamur! Ona vurup duruyor.','Zavallı kapı! Ona vurup duruyor.','ekmek hamuruna vurmak','sokak kapısına vurmak','dramatic','exclamation'),
(5173,'tr','İyi ki yağmurluğu var.','İyi ki güneş şapkası var.','kırmızı kapüşonlu bir yağmurluk','askıda bir yağmurluk','chill','understatement'),
(5174,'tr','Neşeli bir akşam yemeği.','Neşeli bir kahvaltı.','neşeli bir aile yemeği','neşeli bir ofis partisi','chill','none'),
(5175,'tr','Güzel bıyık, sağlam eller.','Güzel sakal, sağlam eller.','bıyıklı bir garson','bıyığını tıraş eden garson','flirt','none'),
(5176,'tr','Büyük bir kupada sıcak kahve.','Büyük bir kupada sıcak çay.','büyük beyaz bir kupa','kulpsuz bir kupa','chill','none'),
(5177,'tr','Demlikten dolduruyor.','Şişeden dolduruyor.','beyaz bir demlikten doldurmak','ocakta bir demlik','chill','none'),
(5178,'tr','Başörtüsüyle ekmek pişiriyor.','Şapkasıyla ekmek pişiriyor.','lacivert bir başörtüsü','rüzgârda bir başörtüsü','chill','none'),
(5179,'tr','Fırının içine uzanıyor.','Buzdolabının içine uzanıyor.','sıcak fırına uzanmak','en üst rafa uzanmak','chill','none'),
(5180,'tr','Konuşmacı kürsüde.','Konuşmacı piyanonun başında.','kürsüde bir konuşmacı','seyirciler arasında bir konuşmacı','business','none'),
(5181,'tr','İmzası mavi mürekkeple.','İmzası kırmızı mürekkeple.','taze mavi bir imza','çekte bir imza','business','none'),
(5182,'tr','Bak, o duvar resmi kızın başarısı.','Bak, o duvar resmi oğlanın başarısı.','büyük bir duvar resmi başarısı','bir video oyunu başarısı','gossip','none'),
(5183,'tr','Öyle tutkulu ki tebeşir uçuşuyor!','Öyle tutkulu ki kitaplar uçuşuyor!','tutkulu yaşlı bir öğretmen','tutkulu genç bir şarkıcı','dramatic','exaggeration'),
(5184,'tr','Evlenme teklif etti. Çok romantik!','Şarkı söyledi. Çok romantik!','romantik bir evlenme teklifi','romantik bir komedi filmi','flirt','exclamation'),
(5185,'tr','Nezaket adamı kuru tutuyor.','Nezaket köpeği kuru tutuyor.','yağmurda nezaket','güneşte nezaket','chill','none'),
(5186,'tr','Halk meydanda.','Halk kilisede.','meydandaki halk','tiyatrodaki halk','chill','none'),
(5187,'tr','Güçlü çocuk! Yük arabası çekiyor!','Güçlü çocuk! Otomobil çekiyor!','çiftlik yük arabası çekmek','at arabası çekmek','low_iq','exclamation'),
(5188,'tr','Bot mu? Tam bir hayal kırıklığı.','Balık mı? Tam bir hayal kırıklığı.','iskelede hayal kırıklığı','hayvanat bahçesinde hayal kırıklığı','ironic','understatement'),
(5189,'tr','Hava kontrolü: yağmur hâlâ yağıyor.','Hava kontrolü: kar hâlâ yağıyor.','havayı elle kontrol etmek','televizyonda hava durumu','chill','none'),
(5190,'tr','Rüzgârlı mı? Bayılıyor!','Güneşli mi? Bayılıyor!','rüzgârlı bir sahil','rüzgârlı bir dağ zirvesi','slang','exclamation'),
(5191,'tr','Karlı bir ovada bir bayrak.','Kumlu bir sahilde bir bayrak.','karlı, bembeyaz bir ova','karlı bir şehir sokağı','chill','none'),
(5192,'tr','Ufka kadar sadece kar.','Ufka kadar sadece kum.','ufka kadar kar','ufukta deniz','dramatic','none'),
(5194,'tr','Bil bakalım bu romana kim bayılıyor?','Bil bakalım bu filme kim bayılıyor?','kalın bir roman okumak','roman yazmak','gossip','none'),
(5195,'tr','Kitapları bütün bankı kaplamış.','Ayakkabıları bütün bankı kaplamış.','park bankında kitaplar','bankta bir köpek','gossip','exaggeration'),
(5196,'tr','Topuzu ve kitabı her yere onunla gidiyor.','Topuzu ve köpeği her yere onunla gidiyor.','tepede sarı bir topuz','tatlı bir çörek','chill','exaggeration'),
(5197,'tr','Ofis isyan ediyor!','Ofis uyuyor!','işe isyan etmek','ebeveynlere isyan etmek','dramatic','exclamation'),
(5198,'tr','Ona bir kâğıt yaprağı uzatıyor.','Ona bir fincan uzatıyor.','küçük, yazılı bir kâğıt yaprağı','yatakta bir çarşaf','chill','none'),
(5199,'tr','Tarife adım adım uyuldu.','Haritaya adım adım uyuldu.','el yazısı bir tarife uymak','bir arkadaşı internette takip etmek','business','none'),
(5200,'tr','Ne canlı bir grup!','Ne canlı bir köpek!','canlı bir oturma odası','canlı bir dans kulübü','dramatic','exclamation'),
(5201,'tr','Su her şeyi yansıtıyor, yanardağı bile.','Su her şeyi yansıtıyor, ayı bile.','yanardağı yansıtan su','aynada bir yüz','business','none'),
(5202,'tr','Bütün dükkânı buzdolabına koydu!','Bütün dükkânı fırına koydu!','yiyecekleri buzdolabına koymak','yiyecekleri masaya koymak','dramatic','exaggeration'),
(5203,'tr','Akrabalar geldi!','Akrabalar gitti!','kapıda akrabalar','havalimanında akrabalar','dramatic','exclamation'),
(5204,'tr','Odayı epey iyileştirmişler.','Bahçeyi epey iyileştirmişler.','eski bir odayı iyileştirmek','İngilizcelerini iyileştirmek','business','none'),
(5205,'tr','Kadın yemin ediyor.','Adam yemin ediyor.','yemin etmek','yeminini bozmak','chill','none'),
(5206,'tr','Kanıtı buldu!','Kanıtı kaybetti!','kanıtları panoya iğnelemek','kanıtları saklamak','dramatic','guessing'),
(5207,'tr','Koca dağlar, bol ter.','Koca göller, bol ter.','terden sırılsıklam','saunadan sonra ter','dramatic','none'),
(5208,'tr','Her mutfak onu büyülüyor!','Her içecek onu büyülüyor!','üç farklı mutfak','tek bir mutfak','gossip','exaggeration'),
(5209,'tr','Kimse çalışmıyor; herkes yayılmış yatıyor.','Kimse çalışmıyor; herkes dans ediyor.','hamakta yayılmak','teknede yayılmak','ironic','exaggeration')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
