begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(673,'cz','Její svetr se srazil. Hodně!','Její šála se srazila. Hodně!','sražený červený svetr','krčit se strachy','dramatic','exclamation'),
(674,'cz','Je nemocná a doma.','Je nemocná a v práci.','nemocná na gauči','nemocná v nemocniční posteli','chill','none'),
(675,'cz','Jeden bok lodi je hotový.','Jeden bok domu je hotový.','natírání boku lodi','břeh jezera','business','none'),
(676,'cz','Jsou na prohlídce památek v Benátkách.','Jsou na prohlídce památek v Paříži.','prohlídka památek gondolou','prohlídka památek autobusem','chill','none'),
(678,'cz','Hedvábí odmítá zůstat na místě.','Kočka odmítá zůstat na místě.','lesklé zelené hedvábí','hedvábná kravata','ironic','none'),
(679,'cz','Stříbro zase září!','Zlato zase září!','leštění starého stříbra','stříbrná barva na autě','dramatic','exclamation'),
(680,'cz','Zpěvák si to užívá.','Zpěvák si dává oběd.','zpěvák ve studiu','zpěvák na pódiu','chill','none'),
(681,'cz','Zpívat nahlas v autě!','Zpívat nahlas ve sprše!','zpívat si v autě','zpívat na pódiu','dramatic','exclamation'),
(683,'cz','Dřez je hora pěny!','Vana je hora pěny!','dřez plný pěny','dřez plný hraček','low_iq','exaggeration'),
(684,'cz','Její sestra je konečně doma!','Její bratr je konečně doma!','objímání se sestrou','hádka se sestrou','dramatic','exclamation'),
(685,'cz','Konečně správná velikost.','Konečně správné boty.','správná velikost klobouku','správná velikost bot','chill','none'),
(687,'cz','Skateboard při západu slunce? Pecka.','Kolo při západu slunce? Pecka.','jízda na skateboardu','skateboard v obchodě','slang','none'),
(688,'cz','Stará se o svou kůži.','Stará se o svého psa.','mazání kůže krémem','mytí kůže mýdlem','chill','none'),
(689,'cz','Skvělá sukně, skvělá otočka!','Skvělý klobouk, skvělá otočka!','žlutá skládaná sukně','dlouhá černá sukně','flirt','exclamation'),
(690,'cz','Obloha je tak velká.','Moře je tak velké.','pohled vzhůru na oblohu','obloha plná hvězd','chill','none'),
(691,'cz','Hlídá své auto. Mizerně.','Myje své auto. Mizerně.','hlídání zaparkovaného auta','hlídání banky','ironic','none'),
(692,'cz','Spát? V tom je profík.','Číst? V tom je profík.','spát pod dekou','spát ve stanu','slang','cliche'),
(693,'cz','Ještě pět minut. Tak ospalý.','Ještě pět minut. Tak čilý.','ospalá noční jízda','ospalá ranní hodina','ironic','bad_excuse'),
(695,'cz','Brzy se všichni usmívají.','Brzy všichni pláčou.','usmívat se na trajektu','usmívat se do kamery','chill','none'),
(696,'cz','Ztratil se v kouři!','Ztratil se ve sněhu!','oblak šedého kouře','kouř z komína','dramatic','exaggeration'),
(697,'cz','Na místě pro kouření je narváno.','Na místě pro kouření je prázdno.','kouřit před barem','cedule „Zákaz kouření“','chill','none'),
(698,'cz','To smoothie je tak fialové.','To smoothie je tak zelené.','husté lesní smoothie','zelené smoothie','slang','none'),
(699,'cz','Propašoval sýr kolem strážného!','Propašoval víno kolem strážného!','pašování sýra v seně','pašování sýra na lodi','gossip','exclamation'),
(700,'cz','Šnek nikam nespěchá.','Žába nikam nespěchá.','šnek na listu','šnek na talíři','chill','understatement'),
(701,'cz','Had je na černém kameni.','Had je na bílém kameni.','had v písku','had v trávě','chill','none'),
(702,'cz','Tenisky nazout, jdeme na schody.','Sandály nazout, jdeme na schody.','šněrování tyrkysových tenisek','čištění tyrkysových tenisek','slang','none'),
(704,'cz','Kýchl si tak, že mu spadl klobouk!','Kýchl si tak, že mu spadla bota!','kýchat u pampelišek','kýchat u kočky','dramatic','exaggeration'),
(705,'cz','To kýchání nikdy nepřestane.','Ten zpěv nikdy nepřestane.','kýchat do lokte','kýchat do kapesníku','dramatic','none'),
(706,'cz','Sníh na jazyk? Mňam!','Déšť na jazyk? Mňam!','chytání sněhu na jazyk','odhrabování sněhu z auta','slang','exclamation'),
(707,'cz','Hustý oranžový snowboard, kámo.','Hustý modrý snowboard, kámo.','připínání snowboardu','snowboard v obchodě','slang','none'),
(708,'cz','Ruce od bláta? Čas na mýdlo!','Nohy od bláta? Čas na mýdlo!','kostka mýdla','lahvička mýdla','slang','exclamation'),
(710,'cz','Oblak pěny v jejích rukou.','Oblak pěny na její hlavě.','obrovský oblak pěny','pěna v pračce','chill','exaggeration'),
(711,'cz','Mobil na 1 %. Zásuvka nalezena!','Mobil na 50 %. Zásuvka nalezena!','schovaná zásuvka ve zdi','objímka žárovky','dramatic','exclamation'),
(712,'cz','Bojí se své limonády.','Bojí se svého sendviče.','plechovka pomerančové limonády','sklenice koly','low_iq','guessing'),
(713,'cz','Á, ahoj! Žížala v půdě!','Á, ahoj! Mince v půdě!','sázení do tmavé půdy','hlína na koberci','dramatic','exclamation'),
(714,'cz','Voják je zase doma!','Voják je zase na moři!','voják se vrací domů','voják odchází z domova','dramatic','exclamation'),
(715,'cz','Někdo jí nechal kafe.','Někdo jí nechal pizzu.','vzkaz od někoho','něčí přání k narozeninám','chill','none'),
(716,'cz','Jí polévkovou lžící.','Jí hůlkami.','jídlo polévkovou lžící','míchání polévkovou lžící','chill','none'),
(717,'cz','Polévka je horká jak peklo!','Polévka je ledová!','horká rajská polévka','studená rajská polévka','dramatic','exclamation'),
(718,'cz','Husy letí na jih.','Husy jdou pěšky na jih.','za ptáky na jih','jízda autem na jih','chill','none'),
(719,'cz','Páni, vesmír je tak prázdný!','Páni, moře je tak prázdné!','hvězdy ve vesmíru','parkovací místo','dramatic','exclamation'),
(720,'cz','To koření je fakt ostré.','To koření je fakt zelené.','červené koření v kornoutu','sklenička sušeného koření','chill','none'),
(721,'cz','Rozlévání má na svědomí ona!','Rozlévání má na svědomí ten kluk!','rozlévání sklenice vody','rozlévání hrnku kávy','dramatic','blaming_someone'),
(723,'cz','Doktor mu ukazuje páteř, kost po kosti.','Doktor mu ukazuje lebku, kost po kosti.','kosti páteře','hřbet knihy','nerd','none'),
(724,'cz','Každý cákanec je větší!','Každý cákanec je menší!','obří cákanec','cákanec mléka','dramatic','exclamation'),
(726,'cz','Je tu jaro, bundu dolů.','Je tu zima, bundu dolů.','jaro pod třešněmi','jarní déšť ve městě','chill','none'),
(727,'cz','Sprintovala do cíle!','Do cíle došla krokem!','sprintovat do cíle','sprintovat na autobus','dramatic','exclamation'),
(729,'cz','Veverka má plán na zimu.','Králík má plán na zimu.','veverka se žaludem','veverka s pizzou','business','guessing'),
(730,'cz','Personál společně pózuje.','Personál společně jí.','personál restaurace v práci','personál ve vlaku','chill','none'),
(731,'cz','Dává na to poštovní známku.','Dává na to minci.','poštovní známka na obálce','razítko v pasu','chill','none'),
(733,'cz','Dva státy podepsaly smlouvu.','Tři státy podepsaly smlouvu.','dva státy podepisují smlouvu','stav chaosu','business','none'),
(734,'cz','Pes chce ten steak.','Kočka chce ten steak.','steak s růžovým středem','steak v mrazáku','gossip','guessing'),
(735,'cz','Pára mu zamlžila brýle!','Déšť mu zamlžil brýle!','oblak páry','oblak kouře','dramatic','exclamation'),
(736,'cz','Ahoj, můj nový nevlastní bratře!','Ahoj, moje nová nevlastní sestro!','seznámení s nevlastním bratrem','hádka s nevlastním bratrem','dramatic','exclamation'),
(737,'cz','Nevlastní otec roku opravil kolo.','Nevlastní otec roku opravil auto.','nevlastní otec opravuje kolo','nevlastní otec na svatbě','gossip','exaggeration'),
(738,'cz','Nakreslil srdíčko na lepicí lístek.','Nakreslil hvězdičku na lepicí lístek.','lepicí lístek se srdíčkem','lepicí lístky na monitoru','flirt','none'),
(739,'cz','Zastavil na pizzu. Pravidla jsou pravidla.','Zastavil na sushi. Pravidla jsou pravidla.','zastavit na pizzu','zastavit na benzín','ironic','cliche'),
(740,'cz','Ty stopky musí být rozbité!','Ten mobil musí být rozbitý!','cvaknutí stopek','cvaknutí foťáku v mobilu','ironic','bad_excuse'),
(741,'cz','Venku velká bouře, uvnitř čaj.','Venku velké slunce, uvnitř čaj.','sledování bouře s čajem','procházka v bouři','chill','none'),
(742,'cz','Všechny čtyři hořáky sporáku hoří.','Hoří jen jeden hořák sporáku.','čtyři hořáky na sporáku','malý kempinkový vařič','business','none'),
(743,'cz','Ta silnice je úplně rovná.','Ta silnice je úplně klikatá.','rovná řada cihel','přímá odpověď','slang','none'),
(744,'cz','Potkala cizince s deštníkem.','Potkala cizince s velkým psem.','cizinec s deštníkem','cizinec s kolem','gossip','none'),
(746,'cz','Skáčou přes potok!','Skáčou přes plot!','skok přes potok','koupání v potoce','dramatic','exclamation'),
(747,'cz','To je jen trocha stresu.','To je jen trocha deště.','stres v kanceláři','stres v posilovně','ironic','understatement'),
(749,'cz','Protahují se spolu.','Tančí spolu.','protáhnout se před během','natahovat gumičku','chill','none'),
(750,'cz','Provázek drží krabici pevně.','Provázek drží tašku pevně.','krabice převázaná provázkem','struna na kytaru','business','none'),
(751,'cz','Ladit oblečení? To není její styl.','Fialové boty? To není její styl.','její vlastní odvážný styl','hudební styl','gossip','guessing'),
(752,'cz','Cukr jí zachránil kafe!','Mléko jí zachránilo kafe!','cukr do černého kafe','cukr na dortu','dramatic','exaggeration'),
(753,'cz','Ten modrý oblek mu sedí.','Ten šedý oblek mu sedí.','zkoušení modrého obleku','praní modrého obleku','flirt','none'),
(754,'cz','Kamarádka ji podporuje.','Kamarádka ji ignoruje.','podporovat kamarádku','podporovat fotbalový tým','chill','none'),
(755,'cz','Každý povrch tady je hladký.','Každý povrch tady je drsný.','hladký lesklý povrch','povrch plný škrábanců','chill','none'),
(756,'cz','Pěkná jízda na tom surfovém prkně.','Pěkná jízda na tom vodním skútru.','voskování bílého surfového prkna','surfové prkno v obchodě','flirt','none'),
(757,'cz','Štěně v krabici! To je ale překvapení!','Kotě v krabici! To je ale překvapení!','překvapení v krabici','večírek s překvapením doma','dramatic','exclamation'),
(758,'cz','Labuť se čistí.','Labuť jí rybu.','labuť na jezeře','labuť na trávě','chill','none'),
(759,'cz','Venku déšť, uvnitř svetr.','Venku slunce, uvnitř svetr.','oblékání útulného svetru','pletení útulného svetru','chill','none'),
(760,'cz','Ale ne! Kotník mu otéká!','Ale ne! Zápěstí mu otéká!','otékající kotník','otékající zápěstí','dramatic','none'),
(761,'cz','Má na noze velký otok.','Má na ruce velký otok.','otok na kotníku','otok na koleni','chill','none'),
(762,'cz','Ne, ne, možná... tohle tričko!','Ne, ne, možná... tahle bunda!','oblékání tyrkysového trička','skládání tyrkysového trička','slang','none'),
(763,'cz','Ubrus letí nahoru.','Záclona letí nahoru.','vyhození ubrusu nahoru','ubrus s fleky od vína','chill','none'),
(764,'cz','Kreslí na tablet.','Kreslí na ubrousek.','kreslení na tabletu','tableta proti bolesti','chill','none'),
(766,'cz','Tohle tetování je navždy!','Tahle nálepka je navždy!','čerstvé tetování ptáka','tetování na noze','dramatic','exclamation'),
(767,'cz','Čajové lístky tančí!','Čajové sáčky tančí!','nalévání mátového čaje','čaj s mlékem','dramatic','exclamation'),
(768,'cz','Tým vesluje v dokonalé souhře.','Tým běží v dokonalé souhře.','veslařský tým za úsvitu','tým v kanceláři','business','none'),
(769,'cz','Lžičky jsou maličké.','Lžičky jsou obrovské.','míchání lžičkou','lžička cukru','chill','none'),
(770,'cz','Skočila po tenisovém míčku!','Skočila po golfovém míčku!','skok v tenisovém zápase','tenis na trávě','dramatic','exclamation'),
(771,'cz','Terminál je obrovský.','Terminál je maličký.','obrovský skleněný terminál','malý autobusový terminál','chill','none'),
(772,'cz','Terapie klientovi pomáhá.','Jóga klientovi pomáhá.','sezení na terapii','lekce jógy','business','none'),
(773,'cz','Jeho teploměr se zbláznil!','Jeho hodinky se zbláznily!','teploměr v puse','teploměr na zdi','slang','exaggeration'),
(775,'cz','Tolik přemýšlení kvůli jednomu tahu!','Tolik přemýšlení kvůli jednomu gólu!','hluboké přemýšlení nad šachy','hluboké přemýšlení nad kartami','slang','exclamation'),
(776,'cz','Jedna kapka na velkou žízeň.','Jedna sušenka na velkou žízeň.','strašná žízeň','žízeň po dobrodružství','ironic','understatement'),
(777,'cz','Je hrozně žíznivý!','Je hrozně hladový!','žíznivý na trhu','žíznivý po běhu','slang','none'),
(778,'cz','Nit dlouhá celé kilometry!','Lano dlouhé celé kilometry!','dlouhá červená nit','vlákno v chatu','dramatic','exaggeration'),
(779,'cz','Tahle vydra chce šlofíka.','Tahle kočka chce šlofíka.','ospalá vydra','vydra v řece','chill','guessing'),
(780,'cz','Kočky stojí jako vojáci!','Psi stojí jako vojáci!','kočky stojící na posteli','kočky stojící na stole','dramatic','exaggeration'),
(781,'cz','Jedna, dva, tři... hrom!','Jedna, dva, tři... duha!','čekání na hrom','hrom na fotbalovém stadionu','dramatic','exclamation'),
(782,'cz','Druhý pokus, dokonalá kravata.','Druhý pokus, dokonalý dort.','vázání tmavě červené kravaty','koupě tmavě červené kravaty','business','none'),
(783,'cz','Mokrý tygr, blbá nálada!','Mokrý lev, blbá nálada!','tygr v řece','tygr na stromě','slang','guessing'),
(784,'cz','Naklání deštník.','Zavírá deštník.','naklánění deštníku','naklánění hlavy','chill','none'),
(785,'cz','Kouká do jízdního řádu.','Kouká do novin.','velký vlakový jízdní řád','školní rozvrh','business','none'),
(786,'cz','Je trošku unavený.','Není vůbec unavený.','unavený po práci','unavený z čekání','ironic','understatement'),
(787,'cz','Nesoudí svou kamarádku.','Nesoudí svého psa.','nesoudit kamarádku','posuzovat kuchařskou soutěž','chill','none'),
(788,'cz','Hned potom si chce ohřát jídlo v mikrovlnce.','Hned potom si chce ohřát jídlo v troubě.','ohřát nudle v mikrovlnce','ohřát hrnek mléka v mikrovlnce','gossip','none'),
(789,'cz','Toustovač vystřelil toust!','Trouba vystřelila toust!','vyskakující toustovač','minitrouba','slang','exaggeration'),
(790,'cz','S tím rajčetem ti to jde.','S tou cibulí ti to jde.','krájení zralého rajčete','sázení rajčete','flirt','none'),
(791,'cz','Nejdřív vzal špatný nástroj.','Nejdřív vzal správný nástroj.','výběr správného nástroje','nástroj na zahradu','chill','none'),
(792,'cz','Až moc zubní pasty!','Až moc šamponu!','věž ze zubní pasty','tuba zubní pasty','dramatic','exaggeration'),
(793,'cz','Poslední kámen dala na vrchol.','Poslední mušli dala na vrchol.','kámen na vrcholu','střecha auta','chill','none'),
(794,'cz','Kluk vyhrál turnaj!','Námořník vyhrál turnaj!','turnaj v páce','šachový turnaj','dramatic','exclamation'),
(795,'cz','Pes dostane ručník taky!','Kočka dostane ručník taky!','utírání ručníkem','ležení na plážovém ručníku','dramatic','exclamation'),
(797,'cz','Závodí na dráze!','Závodí v bazénu!','červená běžecká dráha','železniční trať','dramatic','exclamation'),
(798,'cz','Parta v teplákových soupravách v uličce!','Parta v teplákových soupravách na pláži!','stejné tyrkysové teplákové soupravy','teplákové soupravy na dráze','slang','exclamation'),
(800,'cz','Trénink hotový, nohy v háji.','Zápas hotový, nohy v háji.','trénink pod reflektory','výcvik štěněte','slang','exaggeration'),
(801,'cz','Létá na trampolíně!','Létá na posteli!','skákání na trampolíně','schovávání pod trampolínou','dramatic','exaggeration'),
(802,'cz','Hraje si na LeBrona nad košem na odpadky.','Hraje si na LeBrona nad vanou.','koš na odpadky jako koš','víko koše na odpadky','slang','guessing'),
(804,'cz','Hrozně ráda cestuje.','Hrozně nerada cestuje.','cestovat letadlem','cestovat autobusem','slang','none'),
(805,'cz','Cestování vlakem, tak tak včas!','Cestování autobusem, tak tak včas!','cestování přes Alpy','cestování lodí','dramatic','exclamation'),
(806,'cz','Nosí podnosy jako profík.','Nosí krabice jako profík.','podnos držený vysoko','podnos na zemi','slang','cliche'),
(807,'cz','Běžecký pás skoro vyhrál, brácho.','Rotoped skoro vyhrál, brácho.','běh na běžeckém pásu','chůze na běžeckém pásu','slang','guessing'),
(808,'cz','Ten strom je obrovský!','Ten kámen je obrovský!','obrovský starý strom','domek na stromě','dramatic','exclamation'),
(809,'cz','Dokonce i corgi sleduje trend!','Dokonce i kočka sleduje trend!','trend žlutých klobouků','založení nového trendu','gossip','exaggeration'),
(811,'cz','Trofej nahoru, konfety dolů!','Medaile nahoru, konfety dolů!','zvedání zlaté trofeje','leštění zlaté trofeje','slang','exclamation'),
(812,'cz','Totální důvěra: pouští se skály!','Totální důvěra: pouští se lana!','důvěra v parťáka','důvěra ve štěstí','dramatic','exclamation'),
(813,'cz','Krocan pózuje jako hvězda.','Husa pózuje jako hvězda.','krocan na seně','krocan na talíři','chill','exaggeration'),
(814,'cz','Vypíná větrák.','Vypíná televizi.','vypnout světlo','sjet ze silnice','chill','none'),
(815,'cz','Želva je teď v moři.','Želva je teď v bazénu.','želva na pláži','želva v akváriu','chill','none'),
(816,'cz','Ve smokingu mu to moc sluší.','V teplákovce mu to moc sluší.','oblékání smokingu','půjčení smokingu','flirt','none'),
(817,'cz','Dvě kočky jsou vedle sebe.','Dva psi jsou vedle sebe.','dvě kočky vedle sebe','dvě kočky tváří v tvář','chill','none'),
(818,'cz','Její psaní na klávesnici je bleskové!','Její čtení je bleskové!','rychlé psaní na klávesnici','psaní esemesky','slang','exclamation'),
(819,'cz','Pěkný deštník. Vejdu se tam?','Pěkné auto. Vejdu se tam?','jeden deštník pro dva','deštník na pláži','flirt','banter'),
(821,'cz','Zase doma: čas na spodní prádlo!','Zase doma: čas na pyžamo!','svlékání do spodního prádla','nákup nového spodního prádla','slang','exclamation'),
(823,'cz','Obrazovka ukazuje čísla.','Obrazovka ukazuje počasí.','ukazování na obrazovku','čištění obrazovky','business','none'),
(825,'cz','Pes ten výhled taky miluje.','Kočka ten výhled taky miluje.','výhled na skalnaté štíty','výhled na moře','low_iq','guessing'),
(826,'cz','Natáčejí v kanceláři.','Natáčejí v lese.','natáčení s kamerovým vozíkem','natáčení svatby','chill','none'),
(827,'cz','Je tu spousta zvířat.','Jsou tu dvě zvířata.','zvířata v pohádkové knížce','zvířata ve skutečné zoo','chill','none'),
(828,'cz','Horká novinka? Ona vypadá překvapeně.','Horká novinka? On vypadá překvapeně.','překvapená v kavárně','překvapená u dveří','gossip','guessing'),
(830,'cz','Vysvětluje změny.','Vysvětluje menu.','vysvětlování designu aplikace','vysvětlování příkladu z matiky','business','none'),
(831,'cz','Má projev.','Má koncert.','projev u řečnického pultu','projev na svatbě','business','none'),
(832,'cz','Vybaluje nejdelší šálu všech dob.','Vybaluje nejdelší ponožku všech dob.','vybalení kufru','vybalení nákupu','low_iq','exaggeration'),
(833,'cz','Vybalování: mušle přežila!','Vybalování: hrnek přežil!','vybalování po výletě','vybalování nového mobilu','dramatic','exclamation'),
(834,'cz','Hostitelka už toho má s nimi dost.','Číšník už toho má s nimi dost.','hostitelka obsluhuje hosty','letuška','gossip','guessing'),
(835,'cz','Falešný instalatér skončil promočený!','Falešný instalatér skončil v balíku!','instalatér u dřezu','instalatér na střeše','dramatic','exclamation'),
(836,'cz','Je hodně připravený. Až moc.','Je hodně připravená. Až moc.','připravený student','připravené jídlo','ironic','exaggeration'),
(837,'cz','Tohle taxi projede každou uličkou.','Tenhle autobus projede každou uličkou.','taxi v uličce','taxi na letišti','ironic','exaggeration'),
(838,'cz','Pilot si myslí, že je hvězda.','Kuchař si myslí, že je hvězda.','pilot v bundě','pilot v letadle','gossip','guessing'),
(839,'cz','Prodlužuje si stůl!','Prodlužuje si postel!','prodloužení jídelního stolu','prodloužení víza','dramatic','exclamation'),
(840,'cz','Šel na túru až nahoru jen kvůli selfie.','Plaval až tam jen kvůli selfie.','túra nahoru k jezeru','túra dolů na pláž','ironic','guessing'),
(841,'cz','Nechala led roztát. A co teď?','Nechala vodu zmrznout. A co teď?','nechat roztát kostky ledu','rozpustit čokoládu','ironic','guessing'),
(842,'cz','Miminko chce všechna písmenka.','Miminko chce všechny sušenky.','miminko si hraje s písmenky','miminko si hraje s jídlem','gossip','guessing'),
(843,'cz','Výš! Koš jede nahoru!','Výš! Kbelík jede nahoru!','vytáhnout koš nahoru','vytáhnout loďku nahoru','dramatic','exclamation'),
(844,'cz','Jaké obrovské zelené údolí!','Jaká obrovská zelená poušť!','zelené údolí dole','údolí pod sněhem','dramatic','exclamation'),
(845,'cz','Zase něco mizí! Díky, moře.','Zase něco mizí! Díky, pejsku.','mizející kresba','mizející loď','ironic','blaming_someone'),
(847,'cz','Jejich vítězství je jasné.','Jejich porážka je jasná.','vítězství v závodě lodí','vítězství v šachové partii','chill','none'),
(848,'cz','Ocet? Její obličej říká ne!','Med? Její obličej říká ne!','šplouchnutí octa','úklid octem','slang','exclamation'),
(849,'cz','Dostal vízum!','Ztratil vízum!','vízum v pasu','vízum na dovolenou','dramatic','exclamation'),
(850,'cz','Sopka kouří. Hlavně klid.','Komín kouří. Hlavně klid.','kouřící sopka','sopka pod mořem','ironic','understatement'),
(851,'cz','Čeká. A čeká.','Tančí. A tančí.','čekat na autobus','čekat na taxi','low_iq','exaggeration'),
(852,'cz','Číšník je hrozně rychlý!','Číšník je hrozně pomalý!','číšník s talíři','číšník s jídelním lístkem','slang','exclamation'),
(853,'cz','Kráčí parkem.','Běží parkem.','kráčet kolem jezera','venčit psa','chill','none'),
(855,'cz','Jsou na procházce u moře.','Běhají u moře.','procházka u moře','procházka v horách','chill','none'),
(857,'cz','Našel její peněženku a dostal kytku.','Našel její peněženku a dostal dort.','vrácení ztracené peněženky','krádež ztracené peněženky','gossip','none'),
(859,'cz','Skříň na ni zaútočila!','Lednice na ni zaútočila!','skříň plná kabátů','skříň plná bot','dramatic','blaming_someone'),
(860,'cz','Auto potřebovalo „malé“ mytí.','Kolo potřebovalo „malé“ mytí.','mytí zablaceného auta','mytí zablaceného psa','ironic','understatement'),
(861,'cz','Jeho hodinky hlásí: pozdě!','Jeho mobil hlásí: pozdě!','pohled na hodinky','koupě hodinek','dramatic','exclamation'),
(862,'cz','Sledování televize chce popcorn.','Sledování televize chce pizzu.','večer sledování televize','večer pozorování ptáků','chill','cliche'),
(863,'cz','Její láhev na vodu je kovová.','Její láhev na vodu je plastová.','plnění láhve na vodu','láhev na vodu v posteli','chill','none'),
(864,'cz','Tahle voda je šíleně čistá.','Tohle mléko je šíleně čisté.','čistá voda v láhvi','voda v plastovém kelímku','slang','exaggeration'),
(866,'cz','Duha u vodopádu!','Duha u jezera!','vysoký vodopád na Islandu','vodopád na zahradě','dramatic','exclamation'),
(867,'cz','Bazalce zalévání chutná.','Růži zalévání chutná.','zalévání rajčat','zalévání trávníku','chill','guessing'),
(868,'cz','Jen taková malá vlna.','Jen takový malý žralok.','vlna se valí na plavce','mávnutí rukou','ironic','understatement'),
(869,'cz','Nese závaží.','Nese krabici.','těžké kulaté závaží','rychlé hubnutí','chill','none'),
(870,'cz','Slunce zapadá na západě.','Slunce zapadá na východě.','slunce mířící na západ','noční jízda na západ','chill','none'),
(871,'cz','Skóroval z invalidního vozíku!','Minul z invalidního vozíku!','sportovní invalidní vozík','invalidní vozík v nemocnici','dramatic','exclamation'),
(872,'cz','Její pískání konečně funguje!','Její zpěv konečně funguje!','pískání u zahradního stolu','pískání na fotbale','dramatic','exclamation'),
(873,'cz','Jeho manželka umí obracet palačinky!','Jeho manželka umí obracet burgery!','manželka obrací palačinky','manželka peče dort','flirt','exclamation'),
(874,'cz','Růžová paruka jí sluší.','Růžový klobouk jí sluší.','nasazování růžové paruky','česání růžové paruky','flirt','none'),
(875,'cz','Vítr jí ukradl šálu!','Vítr jí ukradl čepici!','šála ve větru','vítr žene sníh','dramatic','blaming_someone'),
(876,'cz','Červené víno při západu slunce? To má styl.','Vychlazené pivo při západu slunce? To má styl.','sklenka červeného vína','láhev bílého vína','flirt','cliche'),
(877,'cz','Zablácený vítěz? Legenda!','Čistý vítěz? Legenda!','vítěz bahenního závodu','vítěz plaveckého závodu','slang','none'),
(878,'cz','Zima a jízda na sáňkách? Paráda!','Zima a jízda na lyžích? Paráda!','v zimě na sáňkách','v zimě doma','slang','exclamation'),
(879,'cz','Vlk vyje!','Vlk spí!','vlk ve sněhu','vlk na pláži','dramatic','exclamation'),
(880,'cz','Jehně nosí svou vlastní vlnu!','Jehně nosí vlněnou čepici!','klubko vlny','vlněná deka','dramatic','exaggeration'),
(882,'cz','Pes jí dělá trenéra při tréninku.','Kočka jí dělá trenéra při tréninku.','celý trénink','trénink na pláži','low_iq','exaggeration'),
(884,'cz','Ukazuje mu svět.','Ukazuje mu mapu.','svět městských světel','mapa světa','chill','exaggeration'),
(885,'cz','Žížala leze pod zem.','Žížala leze na strom.','žížala v hlíně','žížala na háčku','chill','none'),
(886,'cz','Babička si své vrásky zasloužila.','Holka si své vrásky zasloužila.','hluboké vrásky na tváři','pomačkaná košile','chill','none'),
(887,'cz','Píše si do deníku.','Píše na notebooku.','psát do deníku','psát na zeď','chill','none'),
(888,'cz','Zívání je nakažlivé, i pro psy.','Smích je nakažlivý, i pro psy.','zívat v kuchyni','zívat v autě','nerd','cliche'),
(889,'cz','Její jogurt nejde nalít!','Její med nejde nalít!','sklenice hustého jogurtu','pití jogurtu ze sklenice','dramatic','exclamation'),
(891,'cz','Ups, to auto je drahé!','Ups, to kolo je drahé!','drahá ozdoba na auto','drahé mytí auta','slang','exclamation'),
(893,'cz','Zapnout na zip a hurá do sněhu.','Zapnout na zip a hurá na slunce.','zapnout bundu na zip','zapnout kufr na zip','chill','none'),
(894,'cz','Zip se zasekl!','Lyže se zasekla!','zaseknutý zip u bundy','zip na stanu','dramatic','exclamation'),
(895,'cz','Velká zácpa. Možná nehoda?','Velká párty. Možná nehoda?','nehoda na dálnici','nehoda v kuchyni','dramatic','guessing'),
(898,'cz','Herečka se točí.','Herečka spí.','herečka na place','herečka na plakátu','chill','none'),
(899,'cz','Je slunečné odpoledne.','Je zasněžené odpoledne.','odpoledne v parku','odpoledne na pláži','chill','none'),
(900,'cz','Agent telefonuje.','Agent jede autobusem.','agent u telefonu','kancelář cestovní agentury','business','none'),
(901,'cz','Dýchá čerstvý vzduch, ruce doširoka roztažené.','Dýchá městský vzduch, ruce doširoka roztažené.','čerstvý horský vzduch','čerstvý vzduch ve městě','chill','none'),
(902,'cz','Mává letadlu!','Mává vlaku!','nízko letící letadlo','papírové letadlo','dramatic','exclamation'),
(904,'cz','Má alergii na pyl.','Má alergii na prach.','alergie na pyl','alergie na kočky','chill','none'),
(905,'cz','Uličku přechází kočka.','Uličku přechází pes.','úzká dlážděná ulička','ulička plná obchodů','chill','none'),
(907,'cz','Je tu někdo? Jen holubi.','Je tu někdo? Jen kočky.','někdo na nádraží','někdo na večírku','chill','understatement'),
(909,'cz','On se ptá, jestli je vůbec kdokoli doma.','Ona se ptá, jestli je vůbec kdokoli doma.','ptát se, jestli je kdokoli doma','ptát se, jestli má kdokoli hlad','chill','none'),
(911,'cz','Světlý, slunný byt.','Tmavý, ponurý byt.','světlý moderní byt','světlá moderní kancelář','chill','none'),
(912,'cz','Architekt má výkres.','Architekt má kladivo.','architekt s plány','architekt na pláži','business','none'),
(913,'cz','Její paže je vysoko nahoře.','Její paže je dole.','paže natažená nahoru','paže na pásce','chill','none'),
(914,'cz','Tohle křeslo miluje!','Tuhle pohovku miluje!','svalit se do křesla','svalit se do bazénu','dramatic','exclamation'),
(916,'cz','Používá bankomat.','Používá mobil.','bankomat v dešti','bankomat v obchodě','chill','none'),
(917,'cz','Půda je plná haraburdí.','Půda je plná vody.','zaprášená stará půda','světlá nová půda','slang','none'),
(918,'cz','Publikum tleská.','Publikum odchází.','tleskající publikum','televizní publikum','business','none'),
(919,'cz','Její teta je fakt zábavná.','Její strejda je fakt zábavný.','tanec s tetou','nákupy s tetou','slang','none'),
(920,'cz','Houpačka v Rakousku? Sen.','Lyžování v Rakousku? Sen.','houpání v Rakousku','lyžování v Rakousku','slang','cliche'),
(921,'cz','Podává rakouský dort.','Podává rakouské pivo.','rakouská kavárna','rakouská pivnice','business','none'),
(925,'cz','Její taška je u výdeje zavazadel.','Její taška je u odbavení.','taška u výdeje zavazadel','taška u bezpečnostní kontroly','chill','none'),
(926,'cz','Pekařův chleba je hotový!','Pekařova pizza je hotová!','pekař u pece','pekař u pokladny','dramatic','exclamation'),
(927,'cz','Vytřepává na balkoně koberec.','Vytřepává na balkoně ručník.','koberec přes zábradlí balkonu','květina na balkoně','chill','none'),
(933,'cz','Je v koupelně.','Je v kuchyni.','mytí v koupelně','úklid koupelny','chill','none'),
(934,'cz','Šplouch! Je ve vaně.','Šplouch! Je v bazénu.','cákání ve vaně','cákání v louži','slang','exclamation'),
(938,'cz','Stele postel.','Peče dort.','stlát postel','jít do postele','chill','none'),
(939,'cz','Polštář nahoru! Párty v ložnici!','Polštář nahoru! Párty v kuchyni!','světlá neuklizená ložnice','světlá neuklizená kuchyně','slang','exclamation'),
(941,'cz','Holubi napadli její lavičku!','Kachny napadly její lavičku!','žena na lavičce','lavička na nádraží','dramatic','exaggeration'),
(942,'cz','Jede na kole.','Jede na koloběžce.','kolo na podzim','kolo ve sněhu','chill','none'),
(943,'cz','Lepí plakát na billboard.','Maluje billboard.','prázdný obří billboard','billboard na autobusu','chill','none'),
(944,'cz','Zapomněl použít dalekohled.','Zapomněl použít teleskop.','černý dalekohled na hrudi','černý dalekohled na stole','ironic','guessing'),
(947,'cz','Má krvácející nos.','Má krvácející koleno.','krvácející nos','krvácející koleno','chill','none'),
(948,'cz','Lesní ovoce v mixéru? Mňam!','Třešně v mixéru? Mňam!','plnění mixéru','mytí mixéru','slang','none'),
(949,'cz','Au, puchýř na patě!','Au, puchýř na prstu u nohy!','puchýř na patě','puchýř na ruce','dramatic','exclamation'),
(950,'cz','Daruje krev.','Pronáší projev.','vak darované krve','krev na bílé košili','chill','none'),
(952,'cz','Vesluje na dřevěné loďce.','Vesluje na nafukovací loďce.','veslování na dřevěné loďce','loďka v přístavu','chill','none'),
(953,'cz','Hranice je pro auto otevřená.','Hranice je pro autobus otevřená.','kontrola na hranici','lem z květin','business','none'),
(954,'cz','Šéf má proslov.','Šéf dává dárek.','šéf na poradě','šéf na večírku','business','none'),
(956,'cz','Studuje model mozku.','Studuje model srdce.','model mozku','obrázek mozku','chill','none'),
(957,'cz','Na větvi sedí červenka.','Na větvi sedí sova.','houpačka na větvi','houpačka v parku','chill','none'),
(958,'cz','Nevěsta je připravená!','Ženich je připravený!','nevěsta s bílými růžemi','nevěsta s rudými růžemi','dramatic','exclamation'),
(959,'cz','Jde pod mostem.','Jde po mostě.','obrovský visutý most','malý dřevěný most','chill','none'),
(960,'cz','Zametá koštětem.','Zametá hráběmi.','slaměné koště','čarodějnické koště','chill','none'),
(961,'cz','Starší bratr zase vítězí.','Starší sestra zase vítězí.','bratr držený pod krkem','box s bratrem','slang','cliche'),
(962,'cz','Má na koleni velkou modřinu.','Má na paži velkou modřinu.','modřina na koleni','modřina na oku','chill','none'),
(963,'cz','Zedník staví zeď.','Zedník staví střechu.','zedník se zednickou lžící','zedník s kladivem','chill','none'),
(965,'cz','Zednická lžíce je plná malty.','Kbelík je plný malty.','zednická lžíce plná malty','zednická lžíce plná hlíny','chill','none'),
(967,'cz','Tenhle řidič autobusu je až moc šťastný.','Tenhle taxikář je až moc šťastný.','usměvavý řidič autobusu','řidič autobusu ve stávce','ironic','exaggeration'),
(970,'cz','Řezník krájí hovězí.','Řezník krájí chleba.','řezník krájí hovězí','řezník prodává ryby','chill','none'),
(973,'cz','Na kaktus přistál pták.','Na kaktus přistála včela.','pták na kaktusu','kaktus v květináči','chill','none'),
(974,'cz','Je to rušná malá kavárna.','Je to prázdná malá kavárna.','útulná prosluněná kavárna','zavřená kavárna','chill','none'),
(977,'cz','Míří fotoaparátem.','Míří mobilem.','retro fotoaparát','bezpečnostní kamera','chill','none'),
(980,'cz','Kapitán je u kormidla.','Kapitán je u baru.','kapitán u kormidla','kapitán fotbalového týmu','chill','none'),
(981,'cz','Zelené auto, výhled na moře, čistý styl.','Zelené auto, výhled na město, čistý styl.','zelené klasické auto','zelené rodinné auto','flirt','exaggeration'),
(983,'cz','Pokladní skenuje sklenici.','Pokladní skenuje plechovku.','pokladní u pokladny','pokladní v bance','chill','none'),
(984,'cz','Sádra je ještě mokrá.','Sádra je už suchá.','čerstvá sádra na ruce','čerstvá sádra na noze','nerd','none'),
(986,'cz','Housenka obědvá.','Šnek obědvá.','housenka žere list','housenka na květu','chill','understatement'),
(989,'cz','Nechává si odbavit tašku.','Nechává si odbavit psa.','odbavit se na letišti','ubytovat se v hotelu','business','none'),
(990,'cz','Šéfkuchař používá pinzetu.','Šéfkuchař používá lžíci.','šéfkuchař servíruje jídlo','šéfkuchař ochutnává polévku','chill','none'),
(991,'cz','Má holou hruď.','Má zakrytou hruď.','holá hruď','truhla s pokladem','chill','none'),
(995,'cz','Její spolužák ví tajemství.','Její učitel ví tajemství.','šeptání spolužákovi','spolužák u tabule','chill','guessing'),
(996,'cz','Ruce tvarují mokrou hlínu.','Ruce tvarují mokrý písek.','tvarování hliněného hrnce','malování hliněného hrnce','chill','none'),
(998,'cz','Papíry lítají, úředník dál razítkuje.','Papíry lítají, úředník dál spí.','úředník razítkuje papíry','recepční v hotelu','dramatic','exaggeration'),
(1000,'cz','Podnebí se otepluje.','Podnebí se ochlazuje.','měnící se horské podnebí','tropické ostrovní podnebí','nerd','none'),
(1001,'cz','Klinika je pro tebe připravená.','Škola je pro tebe připravená.','světlá čekárna kliniky','klinika pro psy','business','none'),
(1003,'cz','Dnes jen jeden mrak.','Dnes jen dva mraky.','jeden velký bílý mrak','šedý dešťový mrak','chill','understatement'),
(1004,'cz','Trenér nešeptá.','Trenér nekřičí.','trenér s píšťalkou','autobus plný turistů','chill','understatement'),
(1006,'cz','Kávovar je moc pomalý.','Toustovač je moc pomalý.','kapající kávovar','nový kávovar','chill','blaming_someone'),
(1007,'cz','Dva kolegové si povídají.','Dva kolegové jedí.','kolegové u tabule','kolegové na večírku','chill','none'),
(1008,'cz','Komunita sází.','Komunita maluje.','komunitní zahrada','herní komunita','business','none'),
(1009,'cz','Kompas je chytřejší než já.','Starý mobil je chytřejší než já.','mosazný kompas v ruce','mosazné hodinky v ruce','low_iq','exaggeration'),
(1010,'cz','Získala užitečný kontakt.','Uskutečnila užitečný telefonát.','nový obchodní kontakt','kontakt v jejím mobilu','business','none'),
(1011,'cz','Tenhle kuchař potřebuje dvě lžíce!','Tenhle kuchař potřebuje dva hrnce!','kuchař ochutnává jídlo','kuchař čte recept','dramatic','exclamation'),
(1012,'cz','Kašle jako o život!','Směje se jako o život!','kašlat do lokte','kašlat do kapesníku','dramatic','exclamation'),
(1013,'cz','Dva bratranci se hrozně smějí.','Dva bratranci hrozně pláčou.','dva bratranci na trávě','dva bratranci u stolu','chill','none'),
(1015,'cz','Drží se za lýtko.','Drží se za hlavu.','držet se za lýtko','krmení telete','chill','none'),
(1017,'cz','Na přechodu pro chodce je žena.','Na přechodu pro chodce je pes.','přecházení po přechodu pro chodce','přechod pro chodce v dešti','chill','none'),
(1022,'cz','Tenhle polštář prohrál souboj.','Tahle pohovka prohrála souboj.','načechrat polštář','sedět na polštáři','ironic','exaggeration'),
(1025,'cz','Ten cyklista je šíleně odvážný.','Ten běžec je šíleně odvážný.','cyklista v rychlé zatáčce','cyklista ve městě','slang','none'),
(1026,'cz','České pivo? Jasně, prosím!','České víno? Jasně, prosím!','česká pivnice','český vinný sklep','slang','exclamation'),
(1028,'cz','Ona je v Česku.','On je v Česku.','západ slunce v Česku','sníh v Česku','chill','none'),
(1030,'cz','Kytky od jeho dcery!','Kytky od jeho syna!','kytky od dcery','kytky pro dceru','dramatic','exclamation'),
(1033,'cz','Poušť nemá konce!','Les nemá konce!','velbloudi v poušti','sníh v poušti','dramatic','exaggeration'),
(1035,'cz','Nevidí cíl své cesty.','Nevidí provoz.','daleko od cíle cesty','příjezd do cíle cesty','ironic','guessing'),
(1037,'cz','Víc čisticího prostředku, víc pěny.','Víc čisticího prostředku, žádná pěna.','čisticí prostředek na nádobí','prací prostředek','slang','cliche'),
(1040,'cz','Brzy budou rozvedení.','Brzy budou svoji.','rozvádět se','brát se','gossip','guessing'),
(1041,'cz','Závrať ji pořádně chytla.','Závrať ho pořádně chytla.','vlna závratě','závrať na lodi','dramatic','none'),
(1043,'cz','Oblouk delfína dostává desítku!','Oblouk tuleně dostává desítku!','oblouk skákajícího delfína','duhový oblouk','slang','exaggeration'),
(1048,'cz','Ta činka je šíleně těžká.','Ta činka je šíleně lehká.','zvedání těžké činky','činka na podlaze','slang','exaggeration'),
(1057,'cz','Zaměstnavatel podává ruku.','Zaměstnavatel si myje ruce.','vstřícný zaměstnavatel','naštvaný zaměstnavatel','business','none'),
(1064,'cz','Všichni jásají!','Všichni spí!','všichni zvedají ruce','všichni si sedají','dramatic','exclamation'),
(1067,'cz','Je to skutečný odborník na hodinky.','Je to skutečný odborník na víno.','odborník na hodinky','odborník v televizi','chill','none'),
(1069,'cz','Tohle oko je zelenohnědé.','Tohle oko je jasně modré.','otevřené oko','zavřené oko','chill','none'),
(1070,'cz','Má smějící se obličej.','Má plačící obličej.','smějící se obličej','spící obličej','chill','none'),
(1071,'cz','Farmář pracuje dlouho do noci.','Farmář spí dlouho do rána.','farmář s vidlemi','farmář s krávou','chill','guessing'),
(1072,'cz','Tihle dva chlapíci jsou fakt šťastní.','Tihle dva chlapíci jsou fakt naštvaní.','dva chlapíci si podávají ruku','mávající spolužák','slang','none'),
(1073,'cz','Lezkyně z ženské kategorie letí!','Lezec z mužské kategorie letí!','lezkyně v ženské kategorii','běžkyně v ženské kategorii','dramatic','exaggeration'),
(1074,'cz','Měří jí horečku.','Kontroluje jí mobil.','měření horečky','měření tepu','chill','none'),
(1076,'cz','Prst se dotýká kapky.','Prst se dotýká včely.','prst dotýkající se kapky','prst u včely','chill','none'),
(1078,'cz','Hasič je ve službě.','Hasič je na dovolené.','hasič s hadicí','hasič s kočkou','business','none'),
(1079,'cz','Poskytuje první pomoc.','Ukazuje cestu.','otevřená lékárnička první pomoci','kurz první pomoci','chill','none'),
(1082,'cz','Rybář toho chytil spoustu!','Rybář nechytil nic!','rybář se sítí','rybář s prutem','slang','exclamation'),
(1084,'cz','Let právě začíná.','Let právě přistává.','let po vzletu','schodiště','business','none'),
(1085,'cz','Vytírá dřevěnou podlahu.','Vytírá kamennou podlahu.','široká dřevěná podlaha','první patro','business','none'),
(1088,'cz','Bosé chodidlo v trávě.','Bosé chodidlo ve sněhu.','bosé chodidlo v trávě','chodidlo v ponožce','chill','none'),
(1093,'cz','V noze je zlomenina.','V ruce je zlomenina.','zlomenina kosti nohy','zlomenina zápěstí','nerd','none'),
(1096,'cz','Je v bílé galerii.','Je v bílé kuchyni.','procházka galerií','procházka obchodem','chill','none'),
(1097,'cz','Zavírá garáž.','Zavírá okno.','zavírání garážových vrat','otevírání garážových vrat','chill','none'),
(1100,'cz','Zahradník stříhá růže.','Zahradník seká trávu.','zahradník s růžemi','zahradník se sekačkou','chill','none'),
(1104,'cz','To je ale gentleman!','To je ale dáma!','gentleman smeká klobouk','gentleman zavírá dveře','flirt','exclamation'),
(1107,'cz','Objímá svou přítelkyni.','Nese svou přítelkyni.','objímání přítelkyně','přítelkyně na telefonu','flirt','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
