begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(1676,'cz','Sedět s kafem? Pohodička.','Sedět s knížkou? Pohodička.','sedí v křesle','sedí u stolu','slang','cliche'),
(1677,'cz','Na město se nedívají.','Na mobily se nedívají.','město za soumraku','město v poledne','ironic','cliche'),
(1679,'cz','Chrám je zlatý.','Chrám je stříbrný.','chrám u rybníka','chrám ve městě','chill','none'),
(1681,'cz','Páve, ty máš ale dlouhý ocas!','Páve, ty máš ale krátký ocas!','páv na větvi','páv na zemi','dramatic','exclamation'),
(1684,'cz','I Mona Lisa už nosí roušku.','I Mona Lisa už nosí klobouk.','bílá lékařská rouška','maska na večírek','gossip','exaggeration'),
(1685,'cz','Dav utíká pryč!','Dav utíká dovnitř!','dav prchá z chrámu','dav se modlí uvnitř','dramatic','exclamation'),
(1686,'cz','Nabíjí sám sebe.','Nabíjí si mobil.','nabíjení ze zásuvky','nabíjení autobaterie','low_iq','none'),
(1689,'cz','Ježíš stojí u jeskyně.','Ježíš stojí u jezera.','Ježíš u jeskyně','Ježíš u moře','chill','none'),
(1693,'cz','Rytíř máchá mečem.','Rytíř máchá sekerou.','rytíř v brnění','rytíř na koni','chill','none'),
(1694,'cz','Náčelník má na hlavě pero.','Náčelník má na hlavě korunu.','náčelník s perem','náčelník s korunou','chill','none'),
(1695,'cz','Drží v ruce zbraň.','Drží v ruce mobil.','drží zbraň sklopenou','drží zbraň zvednutou','chill','none'),
(1696,'cz','Orel má na starosti dvě mláďata.','Orel má na starosti čtyři mláďata.','orel nad hnízdem','orel chytá rybu','business','exaggeration'),
(1697,'cz','Vějíř a kimono: moc elegantní.','Kniha a kimono: moc elegantní.','otevřený skládací vějíř','elektrický větrák v létě','flirt','none'),
(1699,'cz','Někdo plave do rytmu hudby.','Někdo letí do rytmu hudby.','plave po klidné vodě','plave v bazénu','chill','none'),
(1701,'cz','Ze džbánu roste lilie.','Ze džbánu roste růže.','lilie ve džbánu','lilie v rybníku','chill','none'),
(1703,'cz','Čte si ve vzduchu.','Spí ve vzduchu.','čte zářící knihu','čte zprávu v mobilu','chill','none'),
(1704,'cz','Stojí tam „Veselé Vánoce“.','Stojí tam „Všechno nejlepší“.','stará vánoční pohlednice','starý vánoční stromek','chill','none'),
(1706,'cz','Cool pes, cool sluneční brýle.','Cool pes, cool klobouk.','husky ve slunečních brýlích','sluneční brýle na osušce','slang','none'),
(1707,'cz','Rostliny žerou chalupu.','Rostliny žerou kostel.','zarostlá kamenná chalupa','chalupa u moře','ironic','exaggeration'),
(1709,'cz','Učitel vysvětluje.','Učitel spí.','učitel u tabule','učitel za katedrou','chill','none'),
(1710,'cz','Tabule je prázdná.','Tabule je popsaná.','prázdná tabule','tabule plná poznámek','chill','none'),
(1711,'cz','Kostra vypadá strašně šťastně.','Kostra vypadá strašně smutně.','kostra s mašlí','kostra v muzeu','ironic','none'),
(1713,'cz','Nahoře stovky pírek.','Nahoře stovky květin.','čelenka z dlouhých pírek','polštář plný peří','chill','exaggeration'),
(1716,'cz','Skafandr je bílý.','Skafandr je oranžový.','bílý skafandr','skafandr na ramínku','chill','none'),
(1718,'cz','Buddha je na 100 % klidný.','Buddha je na 100 % naštvaný.','klidná tvář','klidné moře','nerd','exaggeration'),
(1724,'cz','Drží v rukou Měsíc!','Drží v rukou Slunce!','drží Měsíc','drží mák','dramatic','exclamation'),
(1725,'cz','Na zemi leží kříž.','Na zemi leží žebřík.','kříž na zemi','kříž na kostele','chill','none'),
(1726,'cz','Víří červeným pláštěm.','Víří červeným šátkem.','víří červeným pláštěm','v plášti a masce','chill','none'),
(1728,'cz','Červený vějíř nahoru, noha nahoru!','Červený klobouk nahoru, noha nahoru!','mává červeným vějířem','stropní ventilátor','dramatic','exclamation'),
(1729,'cz','Má dva domácí mazlíčky.','Má tři domácí mazlíčky.','holka s domácími mazlíčky','holka kupuje mazlíčka','chill','none'),
(1731,'cz','Šíp zasáhl její vlajku!','Šíp zasáhl jejího koně!','šípy ve vlajce','šípy v terči','dramatic','exclamation'),
(1733,'cz','Hádej, co drží ten elf? Světlo.','Hádej, co drží ten elf? Meč.','elf se špičatýma ušima','elf s lukem','gossip','guessing'),
(1734,'cz','Tenhle superhrdina je Spider-Man.','Tenhle superhrdina je Batman.','superhrdina v masce','superhrdina s pláštěm','chill','none'),
(1738,'cz','Má dlouhý tmavý závoj.','Má dlouhý bílý závoj.','dlouhý tmavý závoj','svatební závoj','chill','none'),
(1741,'cz','Císař má na hlavě věnec.','Císař má na hlavě korunu.','císař s věncem','císař na koni','nerd','none'),
(1742,'cz','Anděl drží štít.','Anděl drží meč.','velký kulatý štít','štít na zemi','chill','none'),
(1743,'cz','Zmrzlina v Itálii? No jasně.','Pizza v Itálii? No jasně.','šikmá věž v Itálii','pec na pizzu v Itálii','chill','cliche'),
(1747,'cz','Nejlepší místo pro stan vůbec!','Nejlepší místo na pláži vůbec!','stan na kopci','stan na pláži','slang','exaggeration'),
(1751,'cz','Každá značka ukazuje krajinu.','Každá značka ukazuje město.','směrové značky s krajinou','směrové značky s cenami','chill','none'),
(1752,'cz','Okna větrného mlýna svítí.','Okna větrného mlýna jsou otevřená.','větrný mlýn u jezera','větrný mlýn v poli','chill','none'),
(1756,'cz','Hádají se po telefonu.','Zpívají si po telefonu.','hádají se po telefonu','hádají se v kuchyni','chill','none'),
(1757,'cz','Hudba pod květy třešní? Romantika.','Tanec pod květy třešní? Romantika.','růžové květy třešní','čaj z třešňových květů','flirt','none'),
(1762,'cz','Muž padá do velryby!','Muž padá do lodi!','tlama velryby','velryba v akváriu','dramatic','exclamation'),
(1765,'cz','Tak chamtivý! Ruce pryč od zlata!','Tak chamtivý! Ruce pryč od dortu!','chamtivý muž s mincemi','chamtivý pes s jídlem','dramatic','exclamation'),
(1766,'cz','Černé a červené ostružiny.','Černé a zelené ostružiny.','zralé ostružiny na větvi','ostružiny v koláči','chill','none'),
(1777,'cz','Tenhle týpek hraje na banjo.','Tenhle týpek hraje na bicí.','hraje na banjo','ladí banjo','slang','none'),
(1779,'cz','Jeho řetěz se vymkl kontrole!','Jeho lano se vymklo kontrole!','řetěz svištící kolem něj','řetěz na krku','dramatic','exaggeration'),
(1780,'cz','Pes honí jeho kolo!','Kočka honí jeho kolo!','jízda na kole z kopce','jízda na kole do kopce','dramatic','exclamation'),
(1781,'cz','V tomhle domě je Halloween každý den.','V tomhle hradě je Halloween každý den.','halloweenský strašidelný dům','halloweenská párty ve škole','chill','exaggeration'),
(1783,'cz','Čtyři děti, jeden klín, objetí pro každé dítě.','Čtyři děti, jeden klín, dárek pro každé dítě.','muž objímá každé dítě','muž učí každé dítě','chill','none'),
(1785,'cz','Tohle je krásná kresba.','Tohle je krásná fotka.','krásný portrét','krásný západ slunce','chill','none'),
(1786,'cz','Meteory padají jako déšť.','Listí padá jako déšť.','déšť meteorů','meteor v muzeu','nerd','none'),
(1787,'cz','Červená šála pod pouliční lampou. Stylové.','Modrá šála pod pouliční lampou. Stylové.','zářící pouliční lampa','rozbitá pouliční lampa','flirt','none'),
(1788,'cz','Mořské monstrum s pasažéry!','Mořská želva s pasažéry!','mořské monstrum se vynořuje','monstrum pod postelí','dramatic','exclamation'),
(1792,'cz','Staví věž.','Staví loď.','stavět obří věž','stavět malý domek','chill','none'),
(1794,'cz','Tolik pavích pírek!','Tolik labutích pírek!','třpytivá paví pírka','pírko v polštáři','dramatic','exclamation'),
(1799,'cz','Violoncello je z nich největší.','Housle jsou z nich největší.','velké tmavé violoncello','malé tmavé violoncello','nerd','none'),
(1800,'cz','Schovávají úsměv.','Schovávají mobil.','schovává se za knihou','schovává se pod stolem','chill','guessing'),
(1802,'cz','Z kytary se valí noty!','Z kytary se valí mince!','vodopád not','štos poznámek','dramatic','exclamation'),
(1803,'cz','Chystá se hodit míč.','Chystá se kopnout do míče.','chystá se hodit míč','uspořádat párty','chill','none'),
(1806,'cz','Dva drdoly? Ta je tak in.','Dvě mašle? Ta je tak in.','vlasy ve dvou drdolech','dvě buchty na talíři','gossip','none'),
(1807,'cz','Kolem ní se vznášejí lebky.','Kolem ní se vznášejí srdíčka.','lebky v růžových plamenech','lebky na pirátské vlajce','chill','none'),
(1808,'cz','Ta jeho náhlavní souprava je obří, kámo.','Ta jeho čepice je obří, kámo.','masivní náhlavní souprava','pilot s náhlavní soupravou','slang','none'),
(1811,'cz','Pláštěnka plní svou funkci.','Deštník plní svou funkci.','dlouhá žlutá pláštěnka','pláštěnka na věšáku','business','none'),
(1812,'cz','Kočka se taky dívá ven.','Pes se taky dívá ven.','dívá se z okna','hlídá kočku','chill','none'),
(1823,'cz','Dnes večer se cítí osamělá.','Dnes ráno se cítí osamělá.','osamělá na balkoně','osamělá v davu','dramatic','none'),
(1827,'cz','Kočka nesnáší matematiku.','Pes nesnáší matematiku.','stěny popsané matematikou','učebnice matematiky na podlaze','low_iq','guessing'),
(1831,'cz','V žárovce je chatka.','V šálku je chatka.','zasněžená žárovka','rozbitá žárovka','chill','none'),
(1832,'cz','Fotí si to. Paráda!','Telefonuje. Paráda!','fotí v noci','fotí uvnitř','slang','exclamation'),
(1833,'cz','Opírá se o kytaru.','Opírá se o klavír.','opřený o kytaru','opřený o strom','chill','none'),
(1834,'cz','Bůh učí válečníka.','Bůh učí dítě.','učí válečníka','učí dav','chill','none'),
(1840,'cz','Obří stroj z ozubených kol!','Obří stroj ze dřeva!','stroj z rezavých ozubených kol','kávovar','dramatic','exaggeration'),
(1843,'cz','Zasněžená čtvrť v noci.','Zasněžená čtvrť v poledne.','zasněžená čtvrť','párty ve čtvrti','chill','none'),
(1846,'cz','Jeřáb letí před sluncem.','Jeřáb letí před měsícem.','letící bílý jeřáb','jeřáb zvedá bedny','chill','none'),
(1847,'cz','Počítám tři vánoční stromky.','Počítám pět vánočních stromků.','tři malé vánoční stromky','vánoční stromek s dárky','low_iq','none'),
(1849,'cz','Její magie září!','Její vlasy září!','zářící modrá magie','karetní kouzlo','dramatic','exclamation'),
(1851,'cz','Mlha polyká údolí.','Sníh polyká údolí.','mlha v údolí','údolí plné domů','dramatic','none'),
(1853,'cz','Drak chrlí oheň.','Drak chrlí led.','malý bílý drak','velký zelený drak','chill','none'),
(1854,'cz','Kytara má bílé struny.','Kytara má černé struny.','bílé struny na kytaře','bílé provázky na draku','nerd','none'),
(1855,'cz','Páv má obrovský ocas!','Páv má krátký ocas!','páv ukazuje ocas','páv schovává ocas','dramatic','exaggeration'),
(1856,'cz','Postavička je maličká. Nebe je velké.','Postavička je obří. Nebe je velké.','maličká postavička v trávě','maličká figurka na poličce','low_iq','none'),
(1857,'cz','Tohle je plakát na Velikonoce.','Tohle je plakát na Vánoce.','plakát k Velikonocům','hledání velikonočních vajíček','chill','none'),
(1858,'cz','Dítě má dlouhou šálu a velký balónek.','Dítě má dlouhý meč a velký balónek.','dlouhá pruhovaná šála','šála v šuplíku','chill','none'),
(1860,'cz','Jeho hlava je hromada knih.','Jeho hlava je hromada talířů.','hromada knih','hromada krabic','ironic','none'),
(1861,'cz','Na téhle starožitné židli je labuť.','Na téhle starožitné židli je lev.','starožitná vyřezávaná židle','starožitné vyřezávané hodiny','chill','none'),
(1862,'cz','Ve váze jsou růžové růže.','Ve váze jsou bílé růže.','šedá klasická váza','rozbitá klasická váza','chill','none'),
(1863,'cz','Houpačka visí z Měsíce!','Houpačka visí ze stromu!','visí z Měsíce','visí ze stromu','dramatic','exclamation'),
(1865,'cz','Ty modré ploutve? Čistá móda.','Ty červené ploutve? Čistá móda.','velké vlající ploutve','ploutve na potápěči','gossip','exaggeration'),
(1866,'cz','Sluneční brýle a pistole: klasický špion.','Sluneční brýle a nůž: klasický špion.','špion s pistolí','špion s foťákem','ironic','cliche'),
(1868,'cz','Spravedlnost potřebuje spoustu tlustých knih.','Spravedlnost potřebuje spoustu svíček.','váhy spravedlnosti','meč spravedlnosti','chill','exaggeration'),
(1870,'cz','Vlasy jí sahají až k nohám!','Vlasy jí sahají až k bradě!','velmi dlouhé tmavé vlasy','vlas v polévce','dramatic','exaggeration'),
(1871,'cz','Oko jí září bíle.','Oko jí září červeně.','bíle zářící oko','bíle zářící lampa','chill','none'),
(1872,'cz','Černá kočka miluje knihy.','Bílá kočka miluje knihy.','černá kočka na knihách','černá kočka venku','chill','guessing'),
(1874,'cz','Sedí na molu.','Sedí na lodi.','sedí na molu','sedí na mostě','chill','none'),
(1876,'cz','Levná helma: kulaté akvárium.','Levná helma: kbelík.','kulaté akvárium na hlavě','kulaté akvárium na stole','ironic','cheap_quality'),
(1878,'cz','Jeho hlava je neviditelná!','Jeho oblek je neviditelný!','neviditelná hlava','neviditelná ruka','dramatic','exclamation'),
(1879,'cz','Kupole se leskne jako zlato.','Kupole se leskne jako stříbro.','zlatá kupole','skleněná kupole','dramatic','none'),
(1880,'cz','Nejlepší vynález všech dob: létající loď.','Nejlepší vynález všech dob: létající auto.','létající vynález','vynález na kolečkách','slang','exaggeration'),
(1881,'cz','Klidně medituje.','Klidně spí.','medituje v lotosovém sedu','medituje před zkouškou','chill','none'),
(1883,'cz','Slepice zobou venku.','Slepice zobou uvnitř.','slepice na dvoře','slepice v kuchyni','chill','none'),
(1884,'cz','Odraz je vzhůru nohama.','Odraz je hodně rozmazaný.','odraz na klidné hladině','odraz v zrcadle','nerd','none'),
(1885,'cz','Bohatý muž je nahoře.','Bohatý muž je dole.','bohatý muž nahoře','bohatý muž ve vězení','chill','none'),
(1886,'cz','Talíř spotřebitele je prázdný.','Talíř spotřebitele je plný.','hladový spotřebitel','spotřebitel v obchodě','business','none'),
(1887,'cz','Tlačí těžký vozík.','Tlačí těžké auto.','tlačí přeplněný vozík','tlačí kočárek','chill','none'),
(1889,'cz','Hýbe se jako blesk!','Sedí jako socha!','hýbe se do rytmu','stěhuje se do nového bytu','slang','exaggeration'),
(1892,'cz','Starý muž má tenkou hůl.','Starý muž má deštník.','hůl starého muže','deštník starého muže','chill','none'),
(1894,'cz','Dobrou noc, malí ježci.','Dobrou noc, malí králíčci.','rodinka ježků v posteli','ježek na zahradě','chill','none'),
(1897,'cz','Tyhle dýně patří vráně.','Tyhle dýně patří kočce.','tři dýně na sobě','dýňový koláč','low_iq','guessing'),
(1899,'cz','U ruin sedí dva obři.','U ruin sedí dva lvi.','ruiny starých chrámů','ruiny hradu','chill','none'),
(1905,'cz','Ty kočky jsou tak zvědavé!','Ti psi jsou tak zvědaví!','tři zvědavé kočky','tři ospalé kočky','dramatic','exclamation'),
(1906,'cz','Vlasy má modré.','Vlasy má červené.','dlouhé modré vlasy','modré letní šaty','chill','none'),
(1908,'cz','Brácho, volavka si dává chill.','Brácho, labuť si dává chill.','volavka na větvi','volavka ve vodě','slang','none'),
(1909,'cz','Její čepel se blýská.','Její čepel je rezavá.','dlouhá ocelová čepel','krátká zlomená čepel','chill','none'),
(1910,'cz','Má fakt hodně růžových okvětních lístků.','Má fakt hodně růžových pírek.','velké růžové okvětní lístky','okvětní lístky na zemi','slang','exaggeration'),
(1911,'cz','Tahle princezna má skvělý styl.','Tenhle princ má skvělý styl.','princezna v modrém','princezna v červeném','flirt','none'),
(1914,'cz','Klavír je otevřený. Hlad?','Dveře jsou otevřené. Hlad?','otevřený koncertní klavír','hodina klavíru','low_iq','guessing'),
(1915,'cz','Kontrabas má čtyři struny.','Kontrabas má šest strun.','kontrabas se čtyřmi strunami','kontrabas se šesti strunami','nerd','none'),
(1916,'cz','Na obloze jsou UFO.','Na obloze jsou ptáci.','UFO na obloze','přistávající UFO','chill','none'),
(1917,'cz','Helma navržená pro rychlost.','Helma navržená pro cyklistiku.','helma stavěná na rychlost','rychlost na kole','business','none'),
(1919,'cz','Ulička je hodně úzká.','Ulička je hodně široká.','úzká dlážděná ulička','únik o vlásek','chill','none'),
(1920,'cz','Kyborg má zářící hlavu.','Kyborg má zářící ocas.','kyborg z neonového města','kyborg v lese','nerd','none'),
(1921,'cz','Šokovaný obličej u vody.','Šokovaný obličej v lese.','šokovaný křičící obličej','šokovaný z účtu za telefon','chill','none'),
(1922,'cz','Ze studování ji bolí hlava.','Z vaření ji bolí hlava.','studuje obří knihu','studuje na zahradě','dramatic','guessing'),
(1923,'cz','Police na knihy jsou narvané!','Police na knihy jsou prázdné!','vysoké plné police na knihy','prázdná police na knihy','dramatic','exaggeration'),
(1924,'cz','Tolik zářivých barev!','Tolik mdlých barev!','zářivé víry barev','živý sen','gossip','exclamation'),
(1926,'cz','Lebka má všechny zuby!','Lebka nemá žádné zuby!','vyceněné zuby lebky','ostré psí zuby','dramatic','exclamation'),
(1927,'cz','Zlaté kořeny? Levný strom to nebude.','Zlaté listy? Levný strom to nebude.','zlaté kořeny s drahokamy','zlaté listy s drahokamy','ironic','cheap_quality'),
(1928,'cz','Centrum města září červeně. Pecka.','Centrum města září zeleně. Pecka.','neonová ulice v centru města','klidné ráno v centru města','slang','none'),
(1930,'cz','Středověké městečko vypadá útulně.','Moderní město vypadá útulně.','středověké kamenné městečko','středověký jarmark','chill','none'),
(1931,'cz','Deštivá ulice ve městě.','Slunečná ulice ve městě.','deštivá ulice','deštivá pláž','chill','none'),
(1932,'cz','Počítač je na červeném stole.','Počítač je na červené pohovce.','počítač na stole','počítač na klíně','chill','none'),
(1933,'cz','Je duchem stromu.','Je duchem vody.','starý duch stromu','duch oceánu','chill','none'),
(1934,'cz','Tyhle police jsou surreální.','Tyhle police jsou obyčejné.','surreální prohnuté knihovny','surreální tekoucí hodiny','nerd','none'),
(1935,'cz','V New Yorku zapadá slunce.','V New Yorku je noc.','New York při západu slunce','New York v noci','chill','none'),
(1936,'cz','Její květinový věnec je obří!','Její věnec z peří je obří!','nosí květinový věnec','plete květinový věnec','dramatic','exclamation'),
(1937,'cz','Hacker má kapuci.','Hacker má kšiltovku.','hacker v kapuci','hacker v parku','chill','none'),
(1938,'cz','Osamělá velryba u pobřeží.','Osamělý žralok u pobřeží.','písečné pobřeží z výšky','skalnaté pobřeží s útesy','dramatic','none'),
(1940,'cz','Pampelišky jí obklopují hlavu.','Růže jí obklopují hlavu.','bílé chmýří pampelišek','foukání do pampelišky','chill','none'),
(1941,'cz','Tahle myš pirát vypadá jak Jack Sparrow.','Tahle kočka pirát vypadá jak Jack Sparrow.','myš pirát','pirátská loď','slang','exaggeration'),
(1943,'cz','Skřítek má zelenou čepici. Páni.','Skřítek má červenou čepici. Páni.','skřítek v zeleném','skřítek v červeném','low_iq','none'),
(1944,'cz','Fakt: jsou mu vidět žebra.','Fakt: je mu vidět srdce.','klec z žeber','žebra na grilu','nerd','none'),
(1945,'cz','Jaký strašidelný hrad!','Jaký strašidelný kostel!','strašidelný hrad na skalách','strašidelný hrad ve sněhu','dramatic','exclamation'),
(1946,'cz','Tahle kočka je až moc stylová.','Tenhle pes je až moc stylový.','stylová kočka ve slunečních brýlích','osvěžující letní drink','slang','exaggeration'),
(1947,'cz','Jen normální duhová hříva.','Jen normální černá hříva.','duhová hříva','duha nad lvem','ironic','understatement'),
(1948,'cz','Její vlnité vlasy jsou všude!','Její krátké vlasy jsou všude!','vlnité vlasy plné listí','vlnité vlasy plné květin','dramatic','exclamation'),
(1949,'cz','Tenhle les je fakt začarovaný.','Tenhle les je fakt spálený.','cesta začarovaným lesem','začarovaný hrad','slang','none'),
(1950,'cz','Tahle zlá věž by potřebovala výtah.','Tenhle zlý kostel by potřeboval výtah.','zlá pevnost','zlá macecha','ironic','exaggeration'),
(1951,'cz','Křeslo čeká na čtenáře.','Pohovka čeká na čtenáře.','ošoupané kožené křeslo','nové plastové křeslo','chill','guessing'),
(1952,'cz','Úplněk za jedním stromem.','Úplněk za dvěma stromy.','úplněk za stromem','úplněk nad mořem','chill','none'),
(1953,'cz','Koruna ze sněhových vloček? Královna.','Koruna z květin? Královna.','koruna ze sněhových vloček','sněhové vločky na okně','flirt','exaggeration'),
(1955,'cz','Ty jo, to je domeček jak z pohádky.','Ty jo, to je loďka jak z pohádky.','chaloupka jak z pohádky','zámek jak z pohádky','gossip','none'),
(1957,'cz','Dlažební kostky jsou mokré.','Dlažební kostky jsou zasněžené.','mokré dlažební kostky v noci','dlažební kostky na pláži','chill','none'),
(1958,'cz','Kamenné schody a růžové květy.','Kamenné schody a červené květy.','kamenné schody ve vesnici','kamenné schody na hradě','chill','none'),
(1959,'cz','Cop jí sahá do pasu.','Cop jí sahá ke kolenům.','cop až do pasu','krátký cop','chill','none'),
(1960,'cz','Kráčí jako pravý samuraj.','Tančí jako pravý samuraj.','samuraj s mečem','samuraj s lukem','flirt','none'),
(1961,'cz','Tyhle kosti milují dobrou knížku.','Tyhle kosti milují dobrý film.','kosti nad otevřenou knihou','pes s kostí','gossip','guessing'),
(1962,'cz','Tahle pevnost vypadá děsivě!','Tahle chalupa vypadá děsivě!','temná pevnost na kopci','pevnost v poušti','dramatic','exclamation'),
(1964,'cz','Ten dům musí být strašidelný.','Ta škola musí být strašidelná.','strašidelný starý dům','strašidelná stará loď','gossip','guessing'),
(1965,'cz','Útulná chata. Trochu sněhu.','Útulná chata. Trochu písku.','zasněžená dřevěná chata','kajuta na lodi','ironic','understatement'),
(1966,'cz','Pěšina je z kamenů.','Pěšina je ze dřeva.','dlážděná pěšina','lesní pěšina','chill','none'),
(1967,'cz','Liščí mládě je tak roztomilé!','Medvídě je tak roztomilé!','roztomilé liščátko','roztomilé ptáče','dramatic','exclamation'),
(1968,'cz','Myslím, že to jsou krkavci.','Myslím, že to jsou papoušci.','krkavci létají kolem ní','krkavci jí sedí na ruce','low_iq','guessing'),
(1969,'cz','Kytice z vesmíru? Romantika!','Kytice z moře? Romantika!','skládá kytici','hází kytici','flirt','exclamation'),
(1971,'cz','Vrcholy nad mraky. Neskutečné.','Vrcholy pod mraky. Neskutečné.','zasněžené vrcholy nad mraky','vrcholy porostlé lesem','slang','none'),
(1972,'cz','Ten turban je celá věž!','Ta koruna je celá věž!','vysoký turban s drahokamy','turban v poušti','dramatic','exaggeration'),
(1973,'cz','Tahle bohyně vypadá egyptsky.','Tahle bohyně vypadá japonsky.','bohyně se zlatými křídly','bohyně s lukem','nerd','none'),
(1974,'cz','Baletka je na špičkách.','Baletka je na kolenou.','baletka v tylové sukýnce','baletní špička','chill','none'),
(1976,'cz','Čtyři děti bruslí a veverky je hodnotí.','Čtyři děti bruslí a psi je hodnotí.','bruslení na zamrzlém rybníku','bruslení v U-rampě','ironic','guessing'),
(1977,'cz','Kvůli netopýrům je to extra děsivé!','Kvůli sovám je to extra děsivé!','děsivý rozpadlý dům','děsivá stará panenka','dramatic','exclamation'),
(1979,'cz','Nabarvila si je nafialovo. Odvážné!','Nabarvila si je nazeleno. Odvážné!','vlasy nabarvené zářivě fialově','vlasy nabarvené zářivě zeleně','gossip','exclamation'),
(1980,'cz','Chýši obklopují stálezelené borovice.','Chýši obklopují stálezelené palmy.','zasněžené borovice','borovicový stůl','nerd','none'),
(1981,'cz','Vlny narážejí do majáku!','Vlny narážejí do přístavu!','vlny narážejí na skály','přespávání u kámoše na gauči','dramatic','exclamation'),
(1982,'cz','Pokoj je „trochu“ přeplněný.','Pokoj je „trochu“ prázdný.','přeplněné police','přeplněný stůl','ironic','understatement'),
(1983,'cz','Její řasy jsou hodně dlouhé.','Její řasy jsou hodně krátké.','dlouhé tmavé řasy','umělé řasy v krabičce','chill','none'),
(1984,'cz','Její obličej je velmi bledý.','Její obličej je velmi tmavý.','bledý bílý obličej','bledě modrá obloha','chill','none'),
(1985,'cz','Strom má zářivou červenou barvu!','Strom má zářivou zelenou barvu!','zářivé červené listí','zářivá červená jablka','dramatic','exclamation'),
(1986,'cz','Strom je holý. Smutné.','Strom je zelený. Smutné.','holý strom v noci','bosé nohy v trávě','low_iq','none'),
(1987,'cz','Tohle město je z budoucnosti.','Tohle město je z minulosti.','město budoucnosti','město minulosti','business','none'),
(1988,'cz','Plot má ostré hroty.','Plot nemá bránu.','železný plot s hroty','dřevěný zahradní plot','chill','none'),
(1989,'cz','Police jsou plné starých lektvarů.','Police jsou plné starých bot.','police se starými lektvary','lektvar v kotli','chill','none'),
(1990,'cz','Super pohodlné křeslo.','Super pohodlná pohovka.','pohodlné zlaté křeslo','pohodlná zlatá postel','slang','none'),
(1991,'cz','Píše na klávesnici jak stroj!','Maluje jak stroj!','psaní na klávesnici','psaní na mobilu','slang','exclamation'),
(1992,'cz','Poslouchá přes velká zelená sluchátka.','Poslouchá přes velká červená sluchátka.','poslouchá hudbu','poslouchá učitele','chill','none'),
(1994,'cz','Kočka je na vrchu hromady knih.','Kočka je na vrchu živého plotu.','na vrchu knih','na vrchu auta','chill','none'),
(1995,'cz','Tenhle dveřní otvor vede do jiného světa.','Tenhle dveřní otvor vede do temného sklepa.','zářící klenutý dveřní otvor','dveřní otvor do kuchyně','dramatic','guessing'),
(1997,'cz','Ta bojová sekera je obří!','Ten bojový štít je obří!','drží bojovou sekeru','drží bojovou vlajku','dramatic','exclamation'),
(1998,'cz','V téhle vile bydlí boháči.','V téhle chalupě bydlí boháči.','vila za soumraku','vila na pláži','gossip','guessing'),
(1999,'cz','Kámo, ta srst je fakt hustá.','Kámo, ta srst je fakt černá.','hustá bílá srst','bílý kožich','slang','none'),
(2000,'cz','Na vodě se třpytí měsíční svit.','Na vodě se třpytí sluneční světlo.','měsíční svit na mokřadu','měsíční svit v ložnici','chill','none'),
(2001,'cz','Sova má zlatý zobák. Bohatá sova!','Sova má červený zobák. Bohatá sova!','zlatý zobák sovy','zlomený zobák sovy','low_iq','exaggeration'),
(2002,'cz','Kočka má dlouhé vousky.','Kočka má krátké vousky.','kočka s dlouhými vousky','muž s dlouhým knírem','chill','none'),
(2005,'cz','Vrána čeká na zprávy.','Sova čeká na zprávy.','vrána na větvi','vrána na strašákovi','dramatic','guessing'),
(2008,'cz','Kmen je obrovský a pokroucený.','Kmen je tenký a hladký.','mohutný pokroucený kmen','sloní chobot','chill','none'),
(2010,'cz','Příběh ožívá!','Příběh hoří!','ožívající příběh','příběh o městě','dramatic','exclamation'),
(2011,'cz','Dveře jsou otevřené dokořán.','Dveře jsou zavřené.','otevřené skleněné dveře','otevřený notebook','chill','none'),
(2012,'cz','Vchod zakrývají květiny.','Vchod zakrývá sníh.','vchod do zahrady s květinami','vchod do hotelu s květinami','chill','none'),
(2013,'cz','Její make-up? Totálně gotický.','Její make-up? Totálně růžový.','gotický styl','gotický kostel','gossip','none'),
(2014,'cz','Samota za soumraku. Tak tajemné.','Samota v poledne. Tak tajemné.','stará ulička za soumraku','soumrak na prázdné pláži','dramatic','cliche'),
(2015,'cz','Fakt: památník je z kamene.','Fakt: památník je ze dřeva.','starý kamenný památník','památník na náměstí','nerd','none'),
(2016,'cz','Harry Potter potřebuje tuhle kouzelnou hůlku, kámo.','Harry Potter potřebuje tohle koště, kámo.','zářící kouzelná hůlka','zlomená kouzelná hůlka','slang','guessing'),
(2019,'cz','Lokomotiva jezdí na páru.','Lokomotiva jezdí na naftu.','stará parní lokomotiva','stará dieselová lokomotiva','nerd','none'),
(2021,'cz','Oblohu plní souhvězdí.','Oblohu plní duhy.','souhvězdí nad domem','souhvězdí na mapě','nerd','none'),
(2023,'cz','Někdo nechal dárky ve sněhu!','Někdo nechal lyže ve sněhu!','krabice s dárky ve sněhu','krabice s dárky pod postelí','dramatic','exclamation'),
(2024,'cz','Všude neonové nápisy!','Všude papírové nápisy!','růžové a zelené neonové nápisy','neonově zelená bunda','slang','exclamation'),
(2025,'cz','Futuristické město, rok 3000?','Futuristická vesnice, rok 3000?','futuristické věže v noci','futuristické létající auto','nerd','guessing'),
(2026,'cz','Jaká snová pracovna!','Jaká snová kuchyně!','pracovna plná květin','pracovna plná studentů','slang','exclamation'),
(2028,'cz','Mezi knihami je bílý džbán.','Mezi knihami je bílá kočka.','džbán v knihovně','džbán na stole','chill','none'),
(2029,'cz','Stezka mizí v mlze.','Stezka mizí v moři.','kamenitá horská stezka','stezka ze stop','dramatic','none'),
(2031,'cz','Má ve vlasech větvičky. Divné.','Má ve vlasech květiny. Divné.','větvičky ve vlasech','hnízdo z větviček','low_iq','none'),
(2032,'cz','Portál do zlatého města.','Portál do temného lesa.','zářící kulatý portál','portál pod mořem','chill','none'),
(2033,'cz','Kytara je ve víru!','Kytara je v poušti!','kytara ve víru','loďka ve víru','dramatic','exclamation'),
(2034,'cz','Tenhle mák je červený. Hodně červený.','Tenhle mák je modrý. Hodně modrý.','červený květ máku','pole máku','low_iq','none'),
(2035,'cz','Tahle romance má růžové srdce.','Tahle romance má červené srdce.','jarní romance','romantický román','flirt','none'),
(2037,'cz','Stvoření s tmavými křídly.','Stvoření s dlouhými rohy.','temné okřídlené stvoření','stvoření v moři','chill','none'),
(2038,'cz','Je vystrašená a ptáci to vědí.','Je vystrašená a vlci to vědí.','vystrašená v temném lese','vystrašená z velkého psa','dramatic','guessing'),
(2040,'cz','Na každé střeše jsou ozdoby.','Na každé střeše jsou sněhuláci.','ozdoby na střechách','ozdoby v krabici','chill','none'),
(2041,'cz','V téhle láhvi žije celý západ slunce.','V téhle láhvi žije celý oceán.','tmavá skleněná láhev','láhev červeného vína','dramatic','exaggeration'),
(2042,'cz','Ten měsíc je obrovský!','To slunce je obrovské!','obrovský úplněk','obrovský starý hrad','dramatic','exclamation'),
(2045,'cz','Tyhle kameny jsou super vysoké.','Tyhle stromy jsou super vysoké.','vysoké stojící kameny','vysoké stromy v poli','slang','exaggeration'),
(2046,'cz','Zasněžená noc v lese. Takové ticho...','Zasněžená noc ve městě. Takové ticho...','zasněžený les v noci','zasněžená ulice v noci','dramatic','none'),
(2048,'cz','Tenhle vlk je divoký!','Tenhle pes je divoký!','divoký vlk','divoký mejdan','dramatic','exclamation'),
(2049,'cz','Čtecí koutek vypadá útulně.','Kuchyňský kout vypadá útulně.','útulný čtecí koutek','útulný vlněný svetr','chill','none'),
(2052,'cz','Hrnek stojí na hromadě knih.','Hrnek stojí na hromadě krabic.','stříbrný hrnek na knihách','hrnek studeného mléka','chill','none'),
(2053,'cz','Lahve zaplňují každou polici.','Knihy zaplňují každou polici.','police se starými lahvemi','police se starými knihami','chill','none'),
(2055,'cz','To „Omlazení“ je jed.','To „Omlazení“ je džus.','láhev jedu','láhev vína','ironic','none'),
(2056,'cz','Police jsou plné knih.','Police jsou plné sklenic.','police plné starých knih','police plné starých hraček','chill','none'),
(2057,'cz','Komín je z kamene.','Komín je z kovu.','kamenný komín ve sněhu','čištění komína','chill','none'),
(2058,'cz','Medvěd sahá po hvězdě.','Medvěd sahá po ptákovi.','sahá po hvězdě','sahá po medu','chill','none'),
(2059,'cz','Sluneční světlo dopadá jen na jednu stranu.','Měsíční světlo dopadá jen na jednu stranu.','větve v jasném slunečním světle','sluneční světlo na vodě','nerd','none'),
(2060,'cz','Červeno-žluté lyže, fakt cool.','Modro-bílé lyže, fakt cool.','lyže zapíchnuté ve sněhu','lyže na střeše auta','slang','none'),
(2061,'cz','Galaxie se předvádí.','Měsíc se předvádí.','zářící fialová galaxie','galaxie na tričku','slang','exaggeration'),
(2062,'cz','Někdo tyhle kameny vybalancoval.','Někdo tyhle hrnky vybalancoval.','vybalancovaná věž z kamenů','balancovat na jedné noze','gossip','guessing'),
(2064,'cz','Ve sněžítku je kostel.','Ve sněžítku je hrad.','zářící sněžítko','rozbité sněžítko','chill','none'),
(2067,'cz','Jedna pouliční lampa, spousta sněhu.','Jedna pouliční lampa, spousta deště.','zářící pouliční lampa','pes u pouliční lampy','chill','understatement'),
(2068,'cz','Červené dveře jsou otevřené.','Modré dveře jsou otevřené.','otevřené červené dveře','červená vrata od garáže','chill','none'),
(2069,'cz','Sob měl špatný let.','Sob měl zábavný let.','sob uvízlý na větrné turbíně','sob táhne saně','chill','understatement'),
(2070,'cz','Elektrická kytara je raketa!','Elektrická kytara se potápí!','elektrická kytara vzlétá','elektrická kytara na pódiu','slang','exaggeration'),
(2071,'cz','Pěkné vintage auto, tak sváteční.','Pěkná vintage dodávka, tak sváteční.','červené vintage auto','červené vintage šaty','flirt','none'),
(2072,'cz','Kabely pokrývají celou místnost!','Rostliny pokrývají celou místnost!','zářící modré kabely','kabely na mostě','dramatic','exaggeration'),
(2073,'cz','Koukej, dovnitř svítí slunce!','Koukej, dovnitř svítí měsíc!','dovnitř svítí slunce','dovnitř svítí měsíc','dramatic','exclamation'),
(2075,'cz','Na okenním parapetu jsou knihy.','Na okenním parapetu jsou kočky.','knihy na okenním parapetu','rostliny na okenním parapetu','chill','none'),
(2076,'cz','Tolik literatury, tak málo času.','Tolik pizzy, tak málo času.','police staré literatury','literatura v mobilu','nerd','cliche'),
(2077,'cz','Ta sova na mě zírá!','Ta kočka na mě zírá!','zírá na diváka','zírá na měsíc','dramatic','exclamation'),
(2078,'cz','Knihu osvětlují dva plameny.','Knihu osvětlují tři plameny.','dva plameny svíček','plameny v krbu','chill','none'),
(2079,'cz','Všechno tady je dřevěné.','Všechno tady je plastové.','vysoké dřevěné knihovny','vysoké dřevěné žebříky','low_iq','exaggeration'),
(2080,'cz','Na pagodu padá sníh.','Na pagodu padá déšť.','červená pagoda ve sněhu','pagoda v džungli','chill','none'),
(2081,'cz','Nášlapné kameny vedou přes jezero.','Nášlapné kameny vedou přes silnici.','nášlapné kameny přes vodu','nášlapné kameny v zahradě','chill','none'),
(2082,'cz','Drží tenkou hůl.','Drží tenkou dýmku.','drží vycházkovou hůl','hůl ve sněhu','chill','none'),
(2084,'cz','Vlak na mokré železnici.','Vlak na suché železnici.','železnice v noci','železnice v poušti','chill','none'),
(2086,'cz','Ta ulice je fakt sváteční!','Ta ulice je fakt slunečná!','sváteční zasněžená ulice','sváteční večeře','slang','exclamation'),
(2087,'cz','Zamlžené steampunkové panorama města.','Zamlžené pouštní panorama města.','panorama města v mlze','panorama města o půlnoci','chill','none'),
(2088,'cz','Ten hezký muž má plnovous.','Ten hezký muž má brýle.','hezký muž s plnovousem','hezký muž s brýlemi','flirt','none'),
(2089,'cz','Kámo, ty parohy jsou obří.','Kámo, ty parohy jsou maličké.','obří rozvětvené parohy','parohy na zdi','slang','none'),
(2091,'cz','Borovice stojí osamoceně.','Palma stojí osamoceně.','ojíněná borovice','borovice se světýlky','dramatic','none'),
(2092,'cz','Jaká chlupatá sova!','Jaká chlupatá kočka!','chlupatá modrá sova','chlupatá modrá deka','dramatic','exclamation'),
(2093,'cz','Celé město je zelené.','Celé město je šedé.','zelené věže plné stromů','zelená barva na věžích','business','none'),
(2095,'cz','Její dlouhé vlasy jsou modrozelené.','Její dlouhé vlasy jsou černé.','dlouhé vlající modrozelené vlasy','dlouhá procházka','chill','none'),
(2096,'cz','I obloha je červená!','I obloha je zelená!','červená pouštní obloha','červené sportovní auto','dramatic','exclamation'),
(2097,'cz','Ty uši jsou větší než jeho hlava!','Ty oči jsou větší než jeho hlava!','obrovské kulaté uši','uši pod čepicí','dramatic','exclamation'),
(2099,'cz','Tenhle domek na stromě je fakt cool!','Tahle psí bouda je fakt cool!','domek na stromě v džungli','domek na stromě na zahradě','slang','exclamation'),
(2100,'cz','Její večerní šaty jsou větší než zahrada!','Její klobouk je větší než zahrada!','obří modré večerní šaty','večerní šaty na ramínku','dramatic','exaggeration'),
(2102,'cz','To je ale sbírka knih!','To je ale sbírka bot!','sbírka starých knih','sbírka starých mincí','dramatic','exclamation'),
(2104,'cz','Tolik zlatých šperků!','Tolik stříbrných šperků!','ověšená zlatými šperky','prodává zlaté šperky','gossip','exclamation'),
(2105,'cz','Hromady knih můžou spadnout.','Hromady hrnků můžou spadnout.','nakloněné hromady knih','hromada oblečení','chill','guessing'),
(2107,'cz','Kde jsou všichni na téhle vesmírné lodi?','Kde jsou všichni v tomhle vlaku?','uvnitř vesmírné lodi','přistávající vesmírná loď','low_iq','guessing'),
(2108,'cz','Po stropě vedou trubky.','Po stropě vedou dráty.','trubky podél stropu','trubky pod podlahou','chill','none'),
(2109,'cz','Knihy jsou uklizené v řadách.','Hrnky jsou uklizené v řadách.','uklizené řady knih','uklizený stůl','chill','none'),
(2110,'cz','Temná silueta, neonové město. Batman?','Temná silueta, slunná pláž. Batman?','silueta v kabátě','silueta kočky','slang','guessing'),
(2112,'cz','Její sako je jasně žluté.','Její sako je tmavě zelené.','jasně žluté sako','svléká si sako','chill','none'),
(2113,'cz','Květiny jsou jasně žluté.','Květiny jsou jasně fialové.','holubice na žlutých květech','žluté květiny ve váze','chill','none'),
(2114,'cz','Most přes potok.','Most přes silnici.','most přes potok','dům přes ulici','chill','none'),
(2115,'cz','Klidná pozice z jógy.','Klidná pozice z tance.','jóga v tureckém sedu','jóga na paddleboardu','chill','none'),
(2116,'cz','Kolem ní plavou mořské řasy.','Kolem ní plavou plasty.','mořské řasy kolem hlavy','mořské řasy na sushi','chill','none'),
(2117,'cz','Žádný mobil, jen kapesní hodinky.','Žádný mobil, jen náramkové hodinky.','zlaté kapesní hodinky','kouká na kapesní hodinky','ironic','understatement'),
(2118,'cz','Takové nóbl zlaté obchody!','Takové nóbl stříbrné obchody!','nóbl zlaté výlohy','maškarní večírek','dramatic','exclamation'),
(2119,'cz','Sova má červené vzory.','Sova má zelené vzory.','vzory na peří','vzory na šatech','chill','none'),
(2120,'cz','Pták sedí na tenké větvi.','Pták sedí na drátě.','sedí na rozkvetlé větvi','sedí na parapetu','chill','none'),
(2121,'cz','Těžké kameny, dokonalá rovnováha.','Těžké cihly, dokonalá rovnováha.','věž z těžkých kamenů','těžká taška kamenů','business','none'),
(2123,'cz','Tahle továrna se dotýká nebe.','Tahle továrna se dotýká moře.','obří steampunková továrna','malinká steampunková továrna','dramatic','exaggeration'),
(2124,'cz','Jde po mokré silnici.','Jde po mokré pláži.','jde po venkovské silnici','jede po venkovské silnici','chill','none'),
(2126,'cz','Kotě rozlilo kafe!','Kotě rozlilo mléko!','rozlité kafe na stole','rozlitá barva na podlaze','low_iq','blaming_someone'),
(2127,'cz','Na stole je kniha.','Na stole je kočka.','vyřezávaný dřevěný stůl','stůl u krbu','chill','none'),
(2128,'cz','Střílí z válečného vozu!','Střílí z lodi!','střílí šíp','cvaká fotku','dramatic','exclamation'),
(2132,'cz','Knihovna je opuštěná.','Škola je opuštěná.','opuštěná knihovna','opuštěné auto','chill','none'),
(2133,'cz','Kamenné sloupy ve sněhu.','Kamenné sloupy v písku.','sloupy z naskládaných kamenů','sloup chrámu','chill','none'),
(2134,'cz','Císařovna nevypadá pobaveně.','Císařovna vypadá hodně pobaveně.','přísná císařovna','císařovna na koni','ironic','understatement'),
(2136,'cz','Ty červené rukavice vypadají skvěle.','Ty modré rukavice vypadají skvěle.','červené vesmírné rukavice','červené boxerské rukavice','flirt','none'),
(2137,'cz','Zlatá svatozář? Hodně stylové.','Stříbrná svatozář? Hodně stylové.','zlatá svatozář jako koruna','svatozář z tmavého kouře','flirt','none'),
(2139,'cz','Za ní září paprsky laserů.','Za ní září svíčky.','neonové paprsky laserů','laserové ukazovátko pro kočky','chill','none'),
(2140,'cz','Tohle místo je jeden velký stroj.','Tohle místo je jedna velká zahrada.','obří rezavý stroj','obří pračka','chill','none'),
(2141,'cz','Ve sklepě něco svítí.','Ve sklepě něco hoří.','otevřené dveře do sklepa','sklep plný krabic','gossip','none'),
(2143,'cz','Balvany naskládané jako lego.','Cihly naskládané jako lego.','věž z balvanů','balvan valící se z kopce','low_iq','exaggeration'),
(2144,'cz','Má na sobě bílé tričko.','Má na sobě černé tričko.','bílé tričko a bunda','tričko na ramínku','chill','none'),
(2146,'cz','Francie má fialovou věž.','Francie má zelenou věž.','věž ve Francii','most ve Francii','low_iq','guessing'),
(2149,'cz','Hřeben za hřebenem, všechno šedé.','Hřeben za hřebenem, všechno zelené.','řady horských hřebenů','hřeben pod sněhem','chill','none'),
(2150,'cz','Culík nahoru. Vyrazí ven.','Rozpuštěné vlasy. Vyrazí ven.','culík u okna','koňský ocas','chill','guessing'),
(2151,'cz','Půlměsíc si dává chill.','Úplněk si dává chill.','půlměsíc v mracích','půlměsíc v poledne','slang','none'),
(2152,'cz','Její rtěnka je jasně červená.','Její rtěnka je jasně růžová.','jasně červená rtěnka','jasně růžová rtěnka','chill','none'),
(2153,'cz','Čína má létajícího draka!','Čína má spícího draka!','drak z Číny','tygr z Číny','dramatic','exclamation'),
(2154,'cz','Generál má bílé vousy.','Generál má černé vousy.','starý generál v brnění','mladý generál v brnění','chill','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
