begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(2155,'cz','Ten sebevědomý úsměv funguje.','Ten nervózní úsměv funguje.','sebevědomý poloúsměv','sebevědomý hlasitý smích','flirt','none'),
(2156,'cz','Slunce sedí na horizontu.','Měsíc sedí na horizontu.','slunce na horizontu','loď na horizontu','chill','none'),
(2157,'cz','Mimino z Indie má na sobě zlato.','Mimino z Indie má na sobě červenou.','obraz z Indie','koberec z Indie','chill','none'),
(2158,'cz','Ten oranžový šátek na hlavu je super!','Ten modrý šátek na hlavu je super!','oranžový šátek na hlavu','sundávání šátku z hlavy','flirt','exclamation'),
(2159,'cz','Kočka si připadá hodně majestátně.','Pes si připadá hodně majestátně.','majestátní kočka','majestátní lev','ironic','guessing'),
(2161,'cz','Génius má nový nápad.','Génius má novou kočku.','génius hledící na hvězdy','génius píšící vzorce','nerd','guessing'),
(2162,'cz','Její zrzavé vlasy vypadají dokonale.','Její černé vlasy vypadají dokonale.','dlouhé zrzavé vlnité vlasy','zrzavé vlasy v drdolu','flirt','none'),
(2164,'cz','Do lesa vede cesta. Kdo půjde první?','Do lesa teče řeka. Kdo půjde první?','cesta lesem','chata v lese','dramatic','guessing'),
(2172,'cz','Sportovní auto v bouři barev.','Sportovní auto ve sněhové bouři.','tmavě modré sportovní auto','tmavě modré rodinné auto','dramatic','exaggeration'),
(2174,'cz','Strom kvete ve sněhu!','Strom hoří ve sněhu!','strom kvetoucí v noci','květiny kvetoucí na jaře','dramatic','exclamation'),
(2175,'cz','Půlnoc v borovém lese.','Půlnoc v poušti.','půlnoc pod hvězdami','párty o půlnoci','chill','none'),
(2176,'cz','V uličce prší!','V uličce sněží!','deštivá ulička v knihovně','plná ulička v supermarketu','dramatic','exclamation'),
(2177,'cz','I měsíc přišel kvůli dýdžejovi!','I slunce přišlo kvůli dýdžejovi!','dýdžej na ulici','dýdžej v klubu','slang','exaggeration'),
(2178,'cz','Pst, dvě kočky koukají.','Pst, dva psi koukají.','koukání zpoza listí','koukání z okna','gossip','none'),
(2181,'cz','Ulice je fakt moc přeplněná.','Ulice je fakt moc prázdná.','přeplněná neonová ulice','přeplněný vagon vlaku','slang','none'),
(2182,'cz','Turista má červený batoh.','Turista má modrý batoh.','turista na skalní římse','turista ve stanu','chill','none'),
(2184,'cz','Tygr řve!','Lev řve!','řvoucí tygr','spící tygr','dramatic','exclamation'),
(2185,'cz','Klavírista má blond vlasy.','Klavírista má černé vlasy.','klavírista u klavíru','klavírista u keyboardu','chill','none'),
(2186,'cz','Ježíš nosí korunu z trnů.','Ježíš nosí korunu ze zlata.','koruna z trnů','růže s trny','chill','none'),
(2187,'cz','Buddha medituje.','Buddha tančí.','meditující Buddha','ležící Buddha','chill','none'),
(2188,'cz','Kluk pláče, máma ne.','Kluk zpívá, máma ne.','plakat na kole','plakat v posteli','ironic','none'),
(2189,'cz','Někdo padá přes palubu!','Někdo skáče přes palubu!','spadnout přes palubu pozpátku','usnout v lodi','dramatic','exclamation'),
(2190,'cz','Tenhle padouch má planoucí oči.','Tenhle padouch má modré oči.','padouch v hořících troskách','padouch na hradě','dramatic','none'),
(2191,'cz','Android má lidskou tvář.','Android má dlouhé vousy.','zářící ženský android','android v kuchyni','nerd','none'),
(2192,'cz','Harry Potter by tyhle baňky miloval.','Harry Potter by tahle košťata miloval.','zářící skleněné baňky','termoska na čaj','nerd','guessing'),
(2194,'cz','Tropické listy jsou velké. Wow.','Tropické listy jsou malinké. Wow.','husté tropické listy','tropická pláž','low_iq','none'),
(2199,'cz','Všude jemné růže!','Všude jemné tulipány!','jemné růžové růže','jemná skleněná váza','dramatic','exaggeration'),
(2200,'cz','V té róbě vypadá elegantně.','V tom kabátě vypadá elegantně.','elegantní splývavá róba','elegantní černý oblek','flirt','none'),
(2201,'cz','Její oranžové brnění je tak cool!','Její růžové brnění je tak cool!','oranžové vlasy a brnění','pomeranč v její ruce','flirt','exclamation'),
(2202,'cz','Jeho bílé sako vypadá elegantně.','Jeho červené sako vypadá elegantně.','elegantní bílé sako','elegantní tmavý oblek','chill','none'),
(2204,'cz','Drží jehně.','Drží psa.','jehně v náručí','jehně na louce','chill','none'),
(2207,'cz','Robotická ruka ukazuje.','Robotická ruka mává.','ukazování na obrazovku','ukazování na nebe','chill','none'),
(2208,'cz','Její vlasy jsou zářivě růžové.','Její vlasy jsou zářivě zelené.','zářivě růžové vlasy','zářivě růžové šaty','business','none'),
(2211,'cz','Hádej, kdo má trojzubec? Bůh moře.','Hádej, kdo má kladivo? Bůh moře.','bůh s trojzubcem','trojzubec v písku','gossip','guessing'),
(2212,'cz','Pěkné pruhy, tygře!','Pěkné skvrny, tygře!','tygr s černými pruhy','zebra s černými pruhy','slang','exclamation'),
(2213,'cz','Fakt: berani mají zatočené rohy.','Fakt: berani mají ploché rohy.','beran se zatočenými rohy','beran spásající trávu','nerd','cliche'),
(2214,'cz','Skrz to vidím hrad.','Skrz to vidím kostel.','pohled skrz díru ve skále','pohled skrz okno','chill','none'),
(2216,'cz','Modlí se u oltáře.','Zpívá u oltáře.','modlitba u oltáře se svíčkami','svatba u oltáře','chill','none'),
(2217,'cz','Sesílá kouzlo. Hustý.','Nahazuje síť. Hustý.','sesílání kouzla','kouzlo s kartami','slang','none'),
(2218,'cz','Všude kolem něj jsou obvody.','Všude kolem něj jsou květiny.','zářící linky obvodů','závodní okruh','nerd','none'),
(2220,'cz','Pečlivě počítá peníze.','Pečlivě počítá mince.','počítání štosu bankovek','odpočítávání sekund','business','none'),
(2224,'cz','Drží se za ruce.','Podávají si ruce.','drží se za ruce v dešti','drží se za ruce na slunci','flirt','none'),
(2225,'cz','Chudák holka, vlasy má promočené.','Chudák holka, vlasy má suché.','promočená v silném dešti','promočená v horké vodě','gossip','none'),
(2226,'cz','Má zlaté náramky.','Má zlaté rukavice.','zlaté náramky na zápěstích','náramek v obchodě','chill','none'),
(2227,'cz','Letmo pohlíží dozadu. Na tebe?','Letmo pohlíží dolů. Na tebe?','letmý pohled přes rameno','letmý pohled na mobil','gossip','guessing'),
(2228,'cz','Sedí nad městem.','Sedí nad mořem.','vysoko nad městem','nad mraky','chill','none'),
(2231,'cz','Obří zlatá sfinga.','Obří stříbrná sfinga.','socha zlaté sfingy','spící kočka sfinga','chill','none'),
(2232,'cz','Buddha vypadá klidně.','Buddha vypadá naštvaně.','klidný zlatý Buddha','klidný zlatý chrám','chill','none'),
(2233,'cz','Má dvě baseballové rukavice.','Má dvě baseballové pálky.','baseballové rukavice v obou rukou','baseball v televizi','chill','none'),
(2234,'cz','Válečník má velké svaly.','Válečník má velký štít.','velké svaly válečníka','velký štít válečníka','chill','none'),
(2235,'cz','Je zobrazen přesně z profilu.','Je zobrazen zezadu.','muž z profilu','profilová fotka na sítích','nerd','none'),
(2236,'cz','Palác pod obřím měsícem. Páni!','Palác pod obřím sluncem. Páni!','palác v horách','palác v poušti','dramatic','exclamation'),
(2237,'cz','Koukni na tohle lesklé žluté auto!','Koukni na tohle lesklé červené auto!','lesklé žluté auto','lesklý žlutý autobus','slang','exclamation'),
(2238,'cz','Mešita má spoustu kopulí.','Mešita má jednu kopuli.','velkolepá mešita s kopulemi','mešita v poušti','chill','none'),
(2242,'cz','Hejno má nula volných míst.','Hejno má spoustu volných míst.','hejno malých ptáků','stádo ovcí','business','exaggeration'),
(2245,'cz','Je to jen trochu zarostlé.','Je to jen trochu zasněžené.','zarostlá chalupa','zarostlý trávník','ironic','understatement'),
(2246,'cz','Expozice představuje miniaturní chaloupku.','Expozice představuje miniaturní hrad.','miniaturní noční zahrada','miniaturní vláčkodráha','business','none'),
(2247,'cz','Skotsko má osamělý kostel.','Skotsko má osamělý hrad.','kostel ve Skotsku','hrad ve Skotsku','chill','none'),
(2248,'cz','Půvabně se vznáší.','Půvabně tančí.','půvabné vznášení ve vzduchu','půvabný tanec na pódiu','chill','none'),
(2249,'cz','Steampunkové město z ozubených kol.','Steampunkové město ze skla.','mosazné steampunkové věže','steampunková kostýmová párty','chill','none'),
(2250,'cz','Upřeně hledí na město.','Upřeně hledí na moře.','upřeně hledět na deštivé město','upřeně hledět na hvězdné nebe','dramatic','none'),
(2251,'cz','Dress code v nebi: bílé roucho.','Dress code v nebi: černé roucho.','dlouhé bílé roucho','roucho s kapucí','business','cliche'),
(2254,'cz','Zmrzlý palác. Ahoj, Elso!','Zmrzlé jezero. Ahoj, Elso!','zmrzlý zasněžený palác','zmrzlý hrášek v sáčku','slang','exclamation'),
(2256,'cz','Její nohy jsou úplně mechanické.','Její nohy jsou úplně dřevěné.','mechanické ruce a nohy','mechanické hodinky','nerd','none'),
(2257,'cz','Její obočí je hodně tmavé.','Její obočí je hodně světlé.','husté tmavé obočí','tenké blond obočí','chill','none'),
(2258,'cz','Kostel má vysokou špičatou věž.','Kostel má kulatou kopuli.','vysoká špičatá věž kostela','špičatá věž na hradě','chill','none'),
(2259,'cz','Vezmi mě k téhle laguně, hned!','Vezmi mě k tomuhle ledovci, hned!','tyrkysová laguna s palmami','zamrzlá laguna v zimě','dramatic','exclamation'),
(2260,'cz','Chudák veslice, nikdo ji nechce.','Chudák loď, nikdo ji nechce.','prázdná dřevěná veslice','veslice plná lidí','dramatic','exaggeration'),
(2262,'cz','Tečky a čáry je spojují.','Tečky a čáry je rozdělují.','čáry spojující dva lidi','kabel spojující telefon','nerd','none'),
(2268,'cz','Je na napnutém laně. Bez sítě!','Je na žebříku. Bez sítě!','balancování na napnutém laně','cirkusové číslo na laně','dramatic','exclamation'),
(2269,'cz','Její halenka je volná a bílá.','Její šaty jsou volné a bílé.','volná bílá halenka','upnutá černá halenka','chill','none'),
(2271,'cz','Chilluje na chodbě.','Chilluje v kuchyni.','chodba vesmírné lodi','nemocniční chodba','slang','none'),
(2273,'cz','Roztrhané džíny a celý outfit z denimu.','Roztrhané džíny a celý outfit černý.','hodně roztrhané modré džíny','žehlení modrých džínů','slang','none'),
(2274,'cz','Ten límec z krajky je tak nóbl!','Ten límec z kožešiny je tak nóbl!','zdobný límec z krajky','zavazování tkaničky','gossip','none'),
(2275,'cz','Pěkný outfit, obří tenisky!','Pěkný outfit, maličké tenisky!','streetový outfit','outfit na svatbu','flirt','exclamation'),
(2278,'cz','Dívá se nahoru na nebe.','Dívá se nahoru na letadlo.','podívat se nahoru na mraky','vyhledat slovo ve slovníku','chill','none'),
(2280,'cz','Objímá ji při západu slunce.','Objímá ji v autě.','objetí na plachetnici','přijmout nový nápad','flirt','none'),
(2282,'cz','Plachtění při západu slunce. Pohodička.','Surfování při západu slunce. Pohodička.','plachtění při západu slunce','plachtění v bouři','slang','none'),
(2284,'cz','Peří? Odvážný účes.','Perly? Odvážný účes.','účes z peří','krátký účes','flirt','none'),
(2285,'cz','Její mikina je obří.','Její batoh je obří.','velká modrá mikina','mikina na židli','chill','exaggeration'),
(2287,'cz','Sedí sám, ponořený v žalu.','Sedí sám v autě.','žal v temné zahradě','žal na pohřbu','dramatic','none'),
(2288,'cz','Crop top v přístavu.','Crop top na sjezdovce.','černý crop top','bílý crop top','chill','none'),
(2291,'cz','Jen pár asteroidů. V klidu.','Jen pár ptáků. V klidu.','poletující asteroidy','asteroid dopadající na Zemi','ironic','understatement'),
(2295,'cz','Ty rukávy jsou obrovské!','Ty boty jsou obrovské!','široké bílé rukávy','krátké černé rukávy','dramatic','exclamation'),
(2296,'cz','Její květinové šaty ladí se zdí!','Její pruhované šaty ladí se zdí!','oranžové květinové šaty','květinová plážová košile','gossip','exaggeration'),
(2297,'cz','Vlny narážejí na břeh.','Vlny narážejí na loď.','palmy na břehu','loď na břehu','chill','none'),
(2300,'cz','Kytara je v plamenech!','Klavír je v plamenech!','kytara v plamenech','dům v plamenech','dramatic','exclamation'),
(2301,'cz','Raketoplán právě vypouštějí.','Letadlo právě vypouštějí.','vypuštění raketoplánu','uvedení nového produktu','chill','none'),
(2302,'cz','Je beztížný a uvolněný.','Je beztížný a vyděšený.','beztížný astronaut','beztížné pírko','chill','none'),
(2305,'cz','Skalnatá cesta k majáku.','Skalnatá cesta k hradu.','skalnatý mys','skalnatá pláž s lehátky','chill','none'),
(2306,'cz','Venkov nemá konce.','Město nemá konce.','děti na venkově','děti odcházející z venkova','chill','exaggeration'),
(2308,'cz','Viking drží čepel.','Viking drží sekeru.','viking v kožešině','viking na lodi','chill','none'),
(2310,'cz','Z klavíru stoupá melodie.','Z bubnu stoupá melodie.','stoupající zlatá melodie','klesající zlatá melodie','dramatic','none'),
(2311,'cz','Vitráž je obrovská.','Vitráž je maličká.','vysoká okna s vitrážemi','lampa s vitráží','chill','none'),
(2312,'cz','Závodní auto u palem.','Závodní auto u borovic.','červené závodní auto','červený dostihový kůň','chill','none'),
(2313,'cz','Domov je tam, kde je obytná dodávka.','Domov je tam, kde je oranžový stan.','oranžová obytná dodávka','obytná dodávka ve městě','chill','cliche'),
(2314,'cz','Kostým ducha: jedno staré prostěradlo.','Kostým ducha: jeden starý ručník.','duch z bílého prostěradla','duch na hradě','low_iq','cheap_quality'),
(2315,'cz','Tahle krajina je z papíru!','Tahle krajina je ze skla!','papírová krajina','fotka krajiny','dramatic','exclamation'),
(2317,'cz','Má nasazenou červenou kapuci.','Má sundanou červenou kapuci.','nasazená červená kapuce','kapota auta','chill','none'),
(2318,'cz','Má hodně dlouhý meč.','Má hodně dlouhé kopí.','dlouhý zahnutý meč','dlouhý rovný meč','chill','none'),
(2322,'cz','Sklo je rozbité!','Hodiny jsou rozbité!','portrét v rozbitém zrcadle','zlomená ruka v sádře','dramatic','exclamation'),
(2324,'cz','Zpívá jako hvězda!','Tančí jako hvězda!','zpívání do mikrofonu','zpívání ve sprše','flirt','exaggeration'),
(2326,'cz','Princ má cool modré vlasy.','Princ má cool růžové vlasy.','princ s korunou','princ na koni','slang','none'),
(2327,'cz','To auto a ty palmy vypadají fakt cool.','To kolo a ty palmy vypadají fakt cool.','palmy při západu slunce','palmy na ostrově','slang','none'),
(2328,'cz','Takový „skromný“ trůn!','Taková „skromná“ postel!','obrovský zlatý trůn','prázdný zlatý trůn','ironic','exclamation'),
(2330,'cz','Chce ti dát květiny.','Chce ti dát dort.','dávat tři žluté květiny','dávat rudé růže','flirt','guessing'),
(2333,'cz','Jsou tak zamilovaní!','Jsou tak naštvaní!','zamilovaní pod podzimním listím','zamilovaní na pláži','dramatic','exclamation'),
(2340,'cz','Tenhle dům je trochu zvláštní.','Tohle auto je trochu zvláštní.','zvláštní vysoký dům','zvláštní stará loď','chill','understatement'),
(2341,'cz','Díky květinám vypadá smrt hezky.','Díky svíčkám vypadá smrt hezky.','smrt mezi květinami','smrt při autonehodě','ironic','none'),
(2344,'cz','Domy jsou trochu křivé.','Stromy jsou trochu křivé.','vysoké křivé domy','křivý rámeček obrazu','ironic','understatement'),
(2345,'cz','Ten čaroděj má ale dlouhé vousy!','Ten čaroděj má ale krátké vousy!','starý čaroděj v šedém','starý čaroděj v červeném','dramatic','exclamation'),
(2347,'cz','Prozkoumává exoplanetu.','Prozkoumává hlubokou jeskyni.','prozkoumávání cizího světa','prozkoumávání starého hradu','nerd','none'),
(2349,'cz','Dokonce i kočka se převlékla do kostýmu!','Dokonce i pes se převlékl do kostýmu!','převlečení za čarodějnice','převlečení za piráty','gossip','exclamation'),
(2350,'cz','Někdo vyřezal obličeje! Páni!','Někdo vyřezal jména! Páni!','vyřezané obličeje v dýních','vyřezávané dřevěné obličeje','low_iq','exclamation'),
(2353,'cz','Ty houby jsou obrovské, kámo.','Ty houby jsou maličké, kámo.','obrovské růžové houby','obrovské růžové květiny','slang','none'),
(2354,'cz','Obrovská zlatá slavnostní pokrývka hlavy!','Obrovská stříbrná slavnostní pokrývka hlavy!','zlatá slavnostní pokrývka hlavy','sundávání pokrývky hlavy','dramatic','exclamation'),
(2356,'cz','Cesta vede k planetě.','Cesta vede k hradu.','k obrovské planetě','k obrovskému městu','dramatic','none'),
(2357,'cz','Dům je černobílý.','Dům je červenobílý.','černobílá kresba','černobílý film','chill','none'),
(2358,'cz','Farma má červené střechy.','Farma má modré střechy.','farma na svahu','farma s kravami','chill','none'),
(2359,'cz','Mají na sobě tradiční oděv.','Mají na sobě moderní oděv.','tradiční indický oděv','tradiční svatební dort','chill','none'),
(2360,'cz','To červené auto vypadá šíleně rychle.','Ta červená dodávka vypadá šíleně rychle.','rychlé červené auto','rychlý červený člun','slang','exaggeration'),
(2363,'cz','Mění se v záhadný kouř.','Mění se v záhadnou vodu.','záhadná žena z kouře','záhadné zamčené dveře','dramatic','none'),
(2364,'cz','Za ním je bílý býk.','Za ním je bílý kůň.','býk se zahnutými rohy','býk v aréně','chill','none'),
(2365,'cz','Jeho oblek z kovu je tak lesklý.','Jeho oblek z kovu je tak špinavý.','červený oblek z kovu','červené kovové auto','slang','none'),
(2367,'cz','Tohle auto je trošku špinavé.','Tenhle autobus je trošku špinavý.','staré špinavé sportovní auto','špinavý starý autobus','ironic','understatement'),
(2368,'cz','Tahle pláž je totální ráj.','Tahle poušť je totální ráj.','tropický ráj při západu slunce','ráj pro lyžaře','slang','none'),
(2371,'cz','Anděl je celý pohlcený žalem.','Anděl je celý pohlcený knihou.','anděl plný žalu','anděl plný radosti','dramatic','none'),
(2372,'cz','Vypadá totálně vyčerpaně.','Vypadá totálně nadšeně.','vyčerpaný dělník','vybitá baterka mobilu','slang','none'),
(2373,'cz','Vesmír vypadá přeplněně.','Vesmír vypadá prázdně.','vesmír plný planet','vesmír bez hvězd','ironic','exaggeration'),
(2375,'cz','Polovina šedá, polovina žlutá. Nemůže se rozhodnout.','Polovina šedá, polovina zelená. Nemůže se rozhodnout.','polovina žlutého auta','polovina žlutého autobusu','low_iq','guessing'),
(2378,'cz','Teď naplno relaxuje.','Teď naplno běží.','relaxování pod měsícem','relaxování na pláži','slang','none'),
(2379,'cz','Padá červené listí.','Padají červená jablka.','listí padající v dešti','sníh padající na auta','chill','none'),
(2381,'cz','Ty drápy jsou fakt ostré!','Ty zuby jsou fakt ostré!','drápy na větvi','drápy kočky','dramatic','exclamation'),
(2382,'cz','Koukej, její ocas má modré šupiny.','Koukej, její ocas má růžové šupiny.','ocas s modrými šupinami','vážení na váze','gossip','none'),
(2383,'cz','Všude oheň a drahokamy!','Všude led a drahokamy!','třpytivé barevné drahokamy','drahokamy v temné jeskyni','dramatic','exaggeration'),
(2384,'cz','Malinké království na kopci.','Malinké království na ostrově.','pohádkové království','říše zvířat','chill','none'),
(2385,'cz','Fialová mimozemská krajina.','Zelená mimozemská krajina.','fialový mimozemský svět','mimozemšťan ve vesmírné lodi','nerd','none'),
(2386,'cz','Zábradlí míří k západu slunce.','Zábradlí míří k hoře.','kovové zábradlí balkonu','zábradlí na schodišti','chill','none'),
(2387,'cz','Strom je pokroucený. Hustý.','Strom je rovný. Hustý.','pokroucený starý strom','pokroucený kovový plot','low_iq','none'),
(2388,'cz','Tenhle gamer miluje růžovou.','Tenhle gamer miluje zelenou.','gamer v růžovém','gamer v modrém','gossip','none'),
(2389,'cz','Modlí se s vírou.','Modlí se s rozpřaženýma rukama.','modlitba s hlubokou vírou','ztráta víry','chill','none'),
(2390,'cz','Stylový look na pláži!','Stylový look na lodi!','stylový plážový look','stylový zimní kabát','flirt','exclamation'),
(2391,'cz','Epická scenérie, rudé nebe.','Epická scenérie, modré nebe.','scenérie s obřím měsícem','scenérie školního divadla','slang','none'),
(2392,'cz','Procházka ve slaměném klobouku? Stylové.','Procházka v červeném klobouku? Stylové.','procházka mezi květinami','procházka po pláži','flirt','none'),
(2393,'cz','Kancelářský look s botami na vysokém podpatku.','Kancelářský look s teniskami.','černé páskové boty na podpatku','podpatky v krabici','business','none'),
(2394,'cz','Musí si vybrat cestu.','Musí si vybrat loď.','výběr správné cesty','výběr správných šatů','dramatic','guessing'),
(2395,'cz','Jeho vesta má zlaté knoflíky.','Jeho vesta má stříbrné knoflíky.','černá kožená vesta','vesta pod sakem','chill','none'),
(2396,'cz','Ten šněrovaný korzet je úchvatný.','Ta šněrovaná rukavice je úchvatná.','šněrovaný korzet','šněrovací boty','flirt','none'),
(2397,'cz','Tenhle pokoj je tak ponurý!','Tenhle pokoj je tak slunný!','ponurý gotický pokoj','ponurý deštivý den','dramatic','exclamation'),
(2398,'cz','Terasa nabízí výhled na moře.','Terasa nabízí výhled na město.','dlážděná terasa u moře','terasa v horách','business','none'),
(2400,'cz','To je ale zuřivý viking!','To je ale zuřivý pirát!','zuřivý rozzlobený pohled','zuřivá bouře na moři','dramatic','exclamation'),
(2401,'cz','Cesta do světa fantazie.','Cesta do rušného města.','lesní cesta ve světě fantazie','obálka fantasy knihy','chill','none'),
(2404,'cz','Tenhle lotos má oranžový střed.','Tenhle lotos má fialový střed.','bílý květ lotosu','jógová pozice lotosu','nerd','none'),
(2406,'cz','Jeden džíp, příliš mnoho tašek!','Jedno kolo, příliš mnoho tašek!','džíp plný tašek','džíp ve městě','dramatic','exaggeration'),
(2408,'cz','Představivost otevírá skutečnou cestu.','Představivost otevírá skutečné dveře.','kniha představivosti','žádná představivost','chill','none'),
(2411,'cz','Ta koruna je tak zdobná!','Ta maska je tak zdobná!','zdobná zlatá koruna','zdobné dřevěné dveře','gossip','none'),
(2412,'cz','Jdou zavěšení do sebe.','Běží zavěšení do sebe.','jdou zavěšení do sebe','sedí zavěšení do sebe','chill','none'),
(2413,'cz','Objímá vlčí mládě!','Objímá medvědí mládě!','objímání vlčího mláděte','objímání velkého vlka','dramatic','exclamation'),
(2415,'cz','Bůh nosí girlandy z květin.','Bůh nosí girlandy z papíru.','girlandy z červených květů','girlandy na vánočním stromku','chill','none'),
(2417,'cz','Tma a světlo v harmonii.','Červená a modrá v harmonii.','koule harmonie','zpívání v harmonii','nerd','none'),
(2418,'cz','Myslím, že je to zpěvný pták.','Myslím, že je to holub.','zpěvný pták na větvi','zpěvný pták na střeše','low_iq','guessing'),
(2420,'cz','Tahle rozviklaná věž je „bezpečná“.','Tenhle rozviklaný most je „bezpečný“.','rozviklaná věž z domů','rozviklaná stará židle','ironic','understatement'),
(2421,'cz','Tahle houba je velká. Fakt velká.','Tahle houba je malá. Fakt malá.','obří bledá houba','plíseň na starém chlebu','low_iq','exaggeration'),
(2422,'cz','Čte si v laclových kalhotách.','Spí v laclových kalhotách.','modré džínové laclové kalhoty','laclové kalhoty od barvy','chill','none'),
(2424,'cz','Vlevo rostou cypřiše.','Vpravo rostou cypřiše.','řada cypřišů','cypřiš v květináči','nerd','none'),
(2425,'cz','Černá kočka ve strašidelném rámu!','Bílá kočka ve strašidelném rámu!','rám s černými růžemi','rám jízdního kola','dramatic','exclamation'),
(2428,'cz','Tři monitory, maximální soustředění.','Dva monitory, maximální soustředění.','tři velké monitory','dětská chůvička','business','exaggeration'),
(2429,'cz','Hele, jelen je v potoce.','Hele, jelen je na louce.','jelen v potoce','jelen ve sněhu','slang','none'),
(2430,'cz','Řeka teče kolem skal.','Řeka teče kolem domů.','řeka tekoucí mezi skalami','řeka tekoucí městem','chill','none'),
(2432,'cz','Její póza z flamenca je pecka!','Její póza z baletu je pecka!','flamenco s vějířem','flamenco na pódiu','slang','exclamation'),
(2433,'cz','Kůň na nás cválá!','Osel na nás cválá!','cválající bílý kůň','cválající černý kůň','dramatic','exclamation'),
(2434,'cz','Zátiší zobrazuje květy.','Zátiší zobrazuje pomeranče.','zátiší s květy','zátiší s ovocem','nerd','none'),
(2435,'cz','Potok je plný oblázků.','Potok je plný ryb.','hladké kulaté oblázky','oblázky na pláži','chill','none'),
(2439,'cz','Ulice je v noci mokrá.','Ulice je v noci suchá.','mokrá noční ulice','mokrá písečná pláž','business','none'),
(2440,'cz','Elektřina je všude!','Voda je všude!','jiskry elektřiny','účet za elektřinu','dramatic','exaggeration'),
(2446,'cz','Velké mašle, dlouhé tkaničky!','Velké mašle, krátké tkaničky!','dlouhé žluté tkaničky','roztrhané žluté tkaničky','low_iq','exclamation'),
(2449,'cz','Jen „pár“ zářících výloh.','Jen „pár“ tmavých výloh.','zářící výlohy','rozbitá výloha','ironic','understatement'),
(2450,'cz','Bouřka nad vodou.','Bouřka nad městem.','bouřka nad vodou','bouřka nad městečkem','chill','none'),
(2451,'cz','Pták u Eiffelovy věže.','Letadlo u Eiffelovy věže.','Eiffelova věž u řeky','Eiffelova věž ve sněhu','chill','none'),
(2452,'cz','Ta procházka ve sněhu je romantická!','Ta procházka v dešti je romantická!','romantická procházka ve sněhu','romantická večeře při svíčkách','flirt','exclamation'),
(2454,'cz','Na klikaté cestě jsou lucerny.','Na rovné cestě jsou lampy.','klikatá dlážděná cesta','klikatá horská řeka','chill','none'),
(2455,'cz','Má na sobě zelené šortky.','Má na sobě zelené kalhoty.','zelené džínové šortky','zelené plavecké šortky','chill','none'),
(2457,'cz','Zdravotní sestra má stetoskop.','Zdravotní sestra má psací desky.','zdravotní sestra v uniformě','zdravotní sestra s miminkem','chill','none'),
(2458,'cz','Statek s rozsvícenými okny.','Statek s tmavými okny.','statek při západu slunce','statek u moře','chill','none'),
(2460,'cz','Polní květiny v modrém květináči, jak roztomilé.','Polní květiny v červeném květináči, jak roztomilé.','květináč s polními květinami','louka polních květin','slang','none'),
(2462,'cz','Na hvězdnatém nebi je měsíc.','Na hvězdnatém nebi je duha.','hvězdnatá noční obloha','hvězdnatá noc ve městě','chill','none'),
(2463,'cz','V údolí se nacházejí růžové pivoňky.','V údolí se nacházejí růžové tulipány.','růžové pivoňky na kopci','pivoňky ve váze','business','none'),
(2464,'cz','Vzory jsou symetrické.','Vzory jsou barevné.','symetrické vzory listů','symetrická budova','nerd','none'),
(2465,'cz','Vznáší se. Nic zvláštního.','Plave. Nic zvláštního.','vznášení na modrém nebi','vznášení se v bazénu','ironic','understatement'),
(2466,'cz','Její šaty jsou z krystalů.','Její šaty jsou z peří.','šaty ze zářících krystalů','křišťálová sklenice vody','chill','none'),
(2470,'cz','Saxofon má zahnutý ozvučník.','Saxofon má rovný ozvučník.','vznášející se saxofon','saxofonista','nerd','none'),
(2471,'cz','Ta je ale knihomol.','Ta je ale gamerka.','knihomol s knížkou','knihomol s mobilem','gossip','none'),
(2472,'cz','Její uniforma vypadá fakt úhledně.','Její kabát vypadá fakt úhledně.','školní uniforma','policejní uniforma','chill','none'),
(2473,'cz','Věnec visí na červených dveřích.','Věnec visí na modrých dveřích.','věnec na dveřích','věnec na hlavě','chill','none'),
(2474,'cz','Divoká pěna na rozbouřeném moři.','Divoká pěna na klidném moři.','pěna na bouřlivých vlnách','káva s mléčnou pěnou','dramatic','none'),
(2475,'cz','Čte si bosá.','Tančí bosá.','bosá na lehátku','bosá na pláži','chill','none'),
(2477,'cz','Kvůli větru má rozcuchané vlasy.','Kvůli dešti má rozcuchané vlasy.','rozcuchané hnědé vlasy','nepořádek v ložnici','low_iq','blaming_someone'),
(2478,'cz','Lékař se na nás usmívá.','Lékař na nás křičí.','usměvavý kreslený lékař','lékař na operačním sále','chill','none'),
(2480,'cz','To auto veze moc dárků!','To auto veze moc psů!','dárky na střeše auta','dárky pod stromečkem','dramatic','exaggeration'),
(2481,'cz','Drží globus.','Drží míč.','držení globusu','sněžítko','chill','none'),
(2482,'cz','Tolik věžiček na jednom hradu!','Tolik vlajek na jednom hradu!','špičaté hradní věžičky','tanková věž','gossip','exclamation'),
(2483,'cz','V knize leží usušené květiny.','V knize leží čerstvé květiny.','usušené květiny v knize','sušené ovoce v misce','chill','none'),
(2484,'cz','Kostelní věž je vysoká.','Hradní věž je vysoká.','kostelní věž ve sněhu','kostelní věž ve městě','chill','none'),
(2485,'cz','Havraní muž vypadá zlověstně.','Kočičí muž vypadá zlověstně.','zlověstná postava s hlavou vrány','zlověstná černá kočka','dramatic','none'),
(2486,'cz','Hieroglyfy pokrývají zeď.','Květiny pokrývají zeď.','zeď plná hieroglyfů','hieroglyfy v učebnici','chill','none'),
(2490,'cz','Pěkný klobouk! Není sněhulákovi zima?','Pěkný klobouk! Není pejskovi zima?','sněhulák v klobouku','stavění sněhuláka','low_iq','guessing'),
(2492,'cz','Ta vesnice je tak rušná!','Ta vesnice je tak tichá!','rušná zasněžená vesnice','rušná letní pláž','dramatic','exclamation'),
(2493,'cz','Farma je ušitá jako prošívaná deka.','Farma je ušitá jako vlajka.','farma jako prošívaná deka','prošívaná deka na posteli','nerd','none'),
(2494,'cz','Viktoriánská ulice. Je to Sherlock?','Moderní ulice. Je to Sherlock?','zasněžená viktoriánská ulice','viktoriánský čajový dýchánek','gossip','guessing'),
(2495,'cz','Napočítal jsem dva vrabce.','Napočítal jsem čtyři vrabce.','dva vrabci na větvi','dva vrabci ve sněhu','low_iq','none'),
(2497,'cz','Santa Claus si dává pauzu.','Santa Claus si dává koupel.','Santa Claus s dárky','Santa Claus se soby','gossip','guessing'),
(2498,'cz','Je to něžné objetí.','Je to něžný polibek.','něžné objetí','křehký steak','chill','none'),
(2499,'cz','Dva plyšoví medvídci se mazlí.','Dva plyšoví medvídci se perou.','plyšoví medvídci ve sněhu','plyšoví medvídci na posteli','chill','none'),
(2500,'cz','Píše na notebooku.','Píše na mobilu.','psaní na notebooku','nošení notebooku','chill','none'),
(2501,'cz','Šiva medituje na skále.','Šiva medituje v loďce.','Šiva s trojzubcem','Šiva s mečem','nerd','none'),
(2502,'cz','Lesní svatyně plná mechu.','Pouštní svatyně plná písku.','mechem porostlá lesní svatyně','svatyně ve městě','chill','none'),
(2504,'cz','Kršna má paví pero.','Kršna má orlí pero.','Kršna s korunou','Kršna s flétnou','nerd','none'),
(2505,'cz','Déšť, puška a nula stížností.','Slunce, puška a nula stížností.','dlouhá puška s puškohledem','puška na zemi','chill','understatement'),
(2506,'cz','Všechno tady je geometrické.','Všechno tady je modré.','růžové geometrické tvary','geometrický test z matiky','chill','none'),
(2509,'cz','Cesta vede levandulí.','Cesta vede pšenicí.','řady fialové levandule','lahvička levandulového oleje','chill','none'),
(2510,'cz','Čas spánku pro kluka a kočku!','Čas spánku pro kluka a psa!','čas spánku pod dekou','pohádka na dobrou noc z knížky','dramatic','exclamation'),
(2511,'cz','Kolem nich létají jiskry.','Kolem nich létají listy.','jiskry kolem páru','jiskra ze zásuvky','flirt','none'),
(2512,'cz','Tahle omalovánka potřebuje tebe.','Tohle fotoalbum potřebuje tebe.','stránka z omalovánky','obal omalovánky','chill','guessing'),
(2514,'cz','Přidává bylinky do misky.','Přidává sůl do misky.','sypání sušených bylinek','sekání čerstvých bylinek','chill','none'),
(2516,'cz','Je rok 2024.','Je rok 2025.','zářící rok 2024','rok 2025','chill','none'),
(2519,'cz','Viděls ten dvorek za domem? Plameňák!','Viděls ten dvorek za domem? Houpačka!','rušný malý dvorek za domem','zeleninový záhon za domem','gossip','exclamation'),
(2520,'cz','Posvátné světlo shora!','Posvátné světlo zdola!','posvátný paprsek světla','posvátná řeka','dramatic','exclamation'),
(2522,'cz','Jetel má čtyři lístky.','Jetel má tři lístky.','čtyřlistý jetel','pole jetele s kravami','nerd','none'),
(2523,'cz','Sněžení je dnes v noci husté.','Déšť je dnes v noci hustý.','husté sněžení nad vesnicí','slabé sněžení ve městě','chill','none'),
(2524,'cz','Má vycházkovou hůl.','Má velký deštník.','opírání o vycházkovou hůl','trekingová hůl na túru','chill','none'),
(2525,'cz','Máma zvedá své medvídě.','Máma zvedá své lišče.','zvednout mládě','zvednout těžkou krabici','chill','none'),
(2526,'cz','Poseidón má dvě kopí.','Poseidón má dva meče.','Poseidón vystupující z vln','Poseidón potápějící loď','nerd','none'),
(2527,'cz','Dýdžej má plynovou masku. Proč?','Dýdžej má lyžařskou kuklu. Proč?','plynová maska a sluchátka','plynová maska a brýle','ironic','guessing'),
(2528,'cz','Fialový cylindr? Odvážná volba.','Černý cylindr? Odvážná volba.','lesklý fialový cylindr','kouzelníkův cylindr','gossip','understatement'),
(2529,'cz','Má jemnou tvář.','Má jemného psa.','jemná klidná tvář','jemné klidné moře','chill','none'),
(2530,'cz','Světlo svíčky září mezi růžemi.','Světlo svíčky září mezi knihami.','světlo svíčky v lucerně','světlo svíčky na dortu','chill','none'),
(2531,'cz','I nebe se pro ně třpytí.','I moře se pro ně třpytí.','třpytící se noční obloha','perlivá voda ve sklenici','flirt','none'),
(2532,'cz','Její šaty mají šedé volány.','Její šaty mají červené volány.','šaty se šedými volány','volány na červeném klobouku','chill','none'),
(2533,'cz','Vzadu je to mlhavé.','Vzadu je to slunečné.','mlhavá stará ulice','mlhavé horské jezero','chill','none'),
(2536,'cz','Tenhle šimpanz vypadá jako vážný motorkář.','Tenhle šimpanz vypadá jako vážný surfař.','šimpanz na motorce','šimpanz na stromě','gossip','cliche'),
(2537,'cz','Holka čte pohádku na dobrou noc.','Kluk čte pohádku na dobrou noc.','pohádka na dobrou noc v posteli','pohádka na dobrou noc v televizi','chill','none'),
(2538,'cz','Červená karkulka věří vlkovi.','Červená karkulka věří medvědovi.','vlk Červené karkulky','babička Červené karkulky','gossip','guessing'),
(2539,'cz','V její hlavě žije umělá inteligence.','V jejím autě žije umělá inteligence.','robot s umělou inteligencí','aplikace s umělou inteligencí','nerd','none'),
(2540,'cz','Jaký „útulný“ žalář.','Jaká „útulná“ zahrada.','temný žalář se svíčkami','temný sklep s vínem','ironic','none'),
(2541,'cz','Tohle schodiště nikdo neuklízel.','Tuhle kuchyň nikdo neuklízel.','rozpadající se kamenné schodiště','rozpadající se kamenný most','ironic','understatement'),
(2543,'cz','Slon má dlouhé kly.','Slon má krátké kly.','dva dlouhé bílé kly','mrož s kly','chill','none'),
(2544,'cz','Hanuman má zlatou korunu.','Hanuman má stříbrnou korunu.','Hanuman se zlatým žezlem','Hanuman s mečem','nerd','none'),
(2545,'cz','Opice uctívá boha.','Opice spí.','uctívání na kamenných schodech','uctívání fotbalové hvězdy','chill','none'),
(2546,'cz','Tahle hala je „docela“ prostorná.','Tahle hala je „docela“ malinká.','prostorná hala','prostorné auto','ironic','understatement'),
(2547,'cz','Ty muchomůrky jsou obří!','Ty muchomůrky jsou maličké!','obří červené muchomůrky','muchomůrky v košíku','slang','exclamation'),
(2548,'cz','Tolik sudů. Že by pivo?','Tolik kol. Že by pivo?','naskládané dřevěné sudy','sud studeného piva','low_iq','guessing'),
(2549,'cz','Otec se synem fandí!','Otec se synem pláčou!','otec nesoucí syna','otec nesoucí nákup','dramatic','exclamation'),
(2550,'cz','Sedí se zkříženýma nohama, bosá.','Sedí se zkříženýma nohama, v botách.','sedět se zkříženýma nohama','stát se zkříženýma nohama','chill','none'),
(2551,'cz','Miami vibes: palmy a neony.','Miami vibes: sníh a neony.','neonová ulice v Miami','pláž v Miami v poledne','slang','none'),
(2552,'cz','Je ve virtuální realitě.','Je v bazénu.','headset pro virtuální realitu','virtuální realita ve škole','chill','none'),
(2556,'cz','Fakt: mozek září.','Fakt: srdce září.','zářící mozek','mozek ve sklenici','nerd','none'),
(2557,'cz','Počkat, ta plachetnice je ze skla?','Počkat, ta plachetnice je ze dřeva?','skleněná plachetnice','plachetnice v lahvi','low_iq','none'),
(2558,'cz','Letí. Čistá svoboda!','Plave. Čistá svoboda!','svoboda nad mořem','svoboda pod mořem','dramatic','exclamation'),
(2559,'cz','Na tomhle stromě rostou mince!','Na tomhle stromě rostou jablka!','mince padající ze stromu','mince v prasátku','dramatic','exclamation'),
(2560,'cz','Chůze po vodě? Zázrak!','Chůze po ohni? Zázrak!','zázrak na oceánu','zázračný lék na rýmu','dramatic','exclamation'),
(2562,'cz','Deštivá noc, osamělý detektiv.','Slunečný den, osamělý detektiv.','detektiv v dešti','detektiv na místě činu','dramatic','cliche'),
(2563,'cz','Kupec kontroluje obilí.','Kupec kontroluje mince.','kupec při světle svíčky','kupec na trhu','chill','none'),
(2564,'cz','Tenhle květ hortenzie je modrý.','Tenhle květ hortenzie je růžový.','modrý květ hortenzie','hortenzie ve váze','nerd','none'),
(2567,'cz','Světice má bílý závoj.','Světice má červený závoj.','světice se svatozáří','světec na koni','chill','none'),
(2571,'cz','Ten kluk je mrzutý. Zase.','Ta holka je mrzutá. Zase.','mrzutý malý kluk','mrzutý starý pán','ironic','guessing'),
(2572,'cz','Trojúhelníky září.','Kruhy září.','zářící neonové trojúhelníky','výstražný trojúhelník','chill','none'),
(2575,'cz','Ten dýdžej je totálně anonymní.','Ten kuchař je totálně anonymní.','anonymní dýdžej v kapuci','anonymní dopis','slang','none'),
(2576,'cz','V Paříži je zlomený žalem.','V Římě je zlomený žalem.','zlomený žalem v dešti','zlomený žalem ve sněhu','dramatic','none'),
(2578,'cz','Hledí je jako zrcadlo.','Hledí je jako okno.','zrcadlové hledí helmy','čepice s kšiltem','chill','none'),
(2579,'cz','Její brýle jsou fakt divné.','Její klobouk je fakt divný.','divný retro stroj','divné staré auto','slang','exaggeration'),
(2580,'cz','Lukostřelec napíná luk.','Lukostřelec tasí meč.','socha lukostřelce','obraz lukostřelce','chill','none'),
(2581,'cz','Hraje na bambusovou flétnu.','Hraje na bambusový buben.','hraní na bambusovou flétnu','vyřezávání bambusové flétny','chill','none'),
(2583,'cz','Užívá si tu atmošku.','Užívá si tu pizzu.','užívat si hudbu','užívat si sluníčko','slang','none'),
(2584,'cz','Je to křest v řece.','Je to křest v kostele.','křest v řece','křest v kostele','chill','none'),
(2586,'cz','Nejlepší přátelství na světě: obří robot a malá holka.','Nejlepší přátelství na světě: obří pes a malá holka.','nečekané přátelství','náramek přátelství','dramatic','exaggeration'),
(2594,'cz','Robot se učí o sobě.','Robot se učí o kočkách.','robot se učí číst','robot se učí létat','low_iq','guessing'),
(2595,'cz','Někdo nechal koncertní křídlo venku.','Někdo nechal koncertní křídlo uvnitř.','koncertní křídlo venku','koncertní křídlo uvnitř','ironic','guessing'),
(2600,'cz','Kámo, dva brouci chillují.','Kámo, dva šneci chillují.','brouci lezoucí po listech','brouci létající nad květy','slang','none'),
(2601,'cz','Muž si klekl k modlitbě.','Muž si sedl k modlitbě.','kleknout si na kamennou zem','kleknout si na měkkou pohovku','chill','none'),
(2602,'cz','Lyžují dolů hrozně rychle.','Lyžují nahoru hrozně rychle.','lyžování dolů prudkým svahem','lyžování po rovné silnici','slang','none'),
(2603,'cz','Noty jsou psané ručně.','Noty jsou vytištěné.','staré ručně psané noty','nové tištěné noty','nerd','none'),
(2604,'cz','Bezživotný strom, zelený měsíc.','Bezživotný strom, bílý měsíc.','bezživotný strom na skalách','bezživotný strom v květináči','dramatic','none'),
(2605,'cz','Chová v náručí miminko.','Chová v náručí jehně.','chovat miminko v náručí','chovat telefon v náručí','chill','none'),
(2606,'cz','Její hlava je čistý hodinový strojek.','Její hlava je čisté sklo.','hlava plná hodinových strojků','mechanická myška na klíček','nerd','exaggeration'),
(2611,'cz','Jeho pásek má kovovou přezku.','Jeho taška má kovovou přezku.','kovová přezka opasku','zapínání bezpečnostního pásu','chill','none'),
(2612,'cz','Dvě poupata se ještě neotevřela.','Dvě poupata se už otevřela.','dvě zavřená červená poupata','dvě otevřená červená poupata','nerd','none'),
(2614,'cz','Dva kluci jsou u minaretu.','Dvě holky jsou u minaretu.','chůze k minaretu','lezení na minaret','chill','none'),
(2618,'cz','Rukopis je psacím písmem.','Rukopis je tiskacím písmem.','vybledlý psací rukopis','úhledný tiskací rukopis','nerd','none'),
(2621,'cz','Stěžeň má spoustu lanoví.','Stěžeň má spoustu vlajek.','vysoký stěžeň s lanovím','stěžeň s pirátskými vlajkami','nerd','none'),
(2622,'cz','Malinká Socha svobody!','Malinká Eiffelova věž!','mini Socha svobody','kostým Sochy svobody','dramatic','exclamation'),
(2623,'cz','Knihovnu pokrývá břečťan.','Knihovnu pokrývá sníh.','knihovna porostlá břečťanem','hrad porostlý břečťanem','chill','none'),
(2625,'cz','Inženýr sní o jeřábech.','Inženýr sní o koních.','přilba inženýra','inženýr u počítače','nerd','guessing'),
(2626,'cz','V jeho plešaté hlavě žije město.','V jeho plešaté hlavě žije farma.','plešatá hlava z profilu','plešatá hlava s brýlemi','chill','none'),
(2629,'cz','Má vlasy ve dvou culících.','Má vlasy ve dvou drdolech.','dva dlouhé pletené culíky','dva krátké kudrnaté culíky','chill','none'),
(2631,'cz','Její brýle mají kulaté čočky.','Její brýle nemají čočky.','kulaté tónované čočky','čočka na foťáku','chill','none'),
(2633,'cz','Ten strom je diskotéka. Koukej na ty paprsky!','Ten strom je diskotéka. Koukej na ty ptáky!','paprsky barevného světla','dřevěné trámy střechy','low_iq','exaggeration'),
(2634,'cz','Každá láhev má korkovou zátku.','Každá láhev má brčko.','láhve zavřené korkovými zátkami','korková nástěnka s lístečky','chill','none'),
(2635,'cz','Magnólie je krémově bílá.','Magnólie je jasně žlutá.','rozkvetlý květ magnólie','strom magnólie','chill','none'),
(2641,'cz','Paprsky zaplňují oblohu!','Paprsky zaplňují pokoj!','zlaté paprsky světla','paprsky oknem','dramatic','exclamation'),
(2648,'cz','Tenhle mravenec je větší než já!','Tahle včela je větší než já!','obří černý mravenec','obří mraveniště','low_iq','exaggeration'),
(2649,'cz','Ty ochranné brýle jsou obří!','Ty náušnice jsou obří!','zářící ochranné brýle na očích','brýle na plavání','dramatic','exclamation'),
(2651,'cz','Červená střecha má bílé tečky.','Červená střecha má černé tečky.','čepice s bílými tečkami','pes s bílými tečkami','chill','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
