begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(3645,'cz','Daleko od domova a na stole rodinná fotka.','Daleko od domova a na stole rodinný pes.','rodinná fotka ve vesmíru','rodinné fotoalbum','dramatic','none'),
(3647,'cz','Utírá Měsíc dočista.','Utírá Slunce dočista.','utírat Měsíc dočista','utírat hledí helmy','chill','none'),
(3653,'cz','Opravuje Měsíc!','Opravuje Slunce!','opravovat rozbitý Měsíc','opravovat píchlou pneumatiku','dramatic','exaggeration'),
(3658,'cz','Tak větrný den, že to strom vzdal.','Tak deštivý den, že to strom vzdal.','větrný den v Patagonii','větrné počasí na moři','ironic','exaggeration'),
(3663,'cz','Lama tě čekuje.','Koza tě čekuje.','lama na hřebeni','lama ve stáji','slang','guessing'),
(3671,'cz','Má doširoka rozpažené ruce.','Má ruce založené na prsou.','doširoka rozpažit ruce','založit ruce na prsou','chill','none'),
(3673,'cz','Ve vzduchu je šest horkovzdušných balonů.','Ve vzduchu jsou dva horkovzdušné balony.','horkovzdušné balony za úsvitu','horkovzdušné balony v noci','chill','none'),
(3676,'cz','Výhled na zátoku, západ slunce v ceně.','Výhled na zátoku, sníh v ceně.','tyrkysová zakřivená zátoka','zátoka plná lodí','business','cliche'),
(3685,'cz','Tolik horkovzdušných balonů!','Tolik vrtulníků!','horkovzdušné balony nad skalami','horkovzdušné balony nad mořem','dramatic','exclamation'),
(3706,'cz','Horská dráha děsí všechny!','Ruské kolo děsí všechny!','rodina na horské dráze','rodina u horské dráhy','dramatic','exaggeration'),
(3709,'cz','Kuchař ochutnává polévku.','Kuchař ochutnává salát.','ochutnávat polévku','ochutnávat víno','chill','none'),
(3718,'cz','Mikina s kapucí, bomber, brýle: pecka.','Mikina s kapucí, bomber, kšiltovka: pecka.','mikina s kapucí pod bomberem','natahovat si mikinu s kapucí','slang','none'),
(3724,'cz','Šaty té ženy jsou pestré.','Šaty té ženy jsou černé.','žena v pestrých barvách','žena v tmavých barvách','chill','none'),
(3733,'cz','Štír má ocas nahoře.','Štír má ocas dole.','stočený ocas štíra','štír pod kamenem','chill','none'),
(3734,'cz','Ten roh je fakt velký. Páni.','Ten roh je fakt malý. Páni.','obrovský spirálovitý roh','troubit na roh','low_iq','exaggeration'),
(3735,'cz','Hele, surikata se usmívá.','Hele, surikata pláče.','surikata stojící vzpřímeně','surikata hrabající díru','gossip','none'),
(3740,'cz','Má nafukovací kruh.','Má surfovací prkno.','běží s nafukovacím kruhem','sedí v nafukovacím kruhu','chill','none'),
(3741,'cz','Ty tulipány jsou fakt oranžové.','Ty tulipány jsou fakt fialové.','čtyři oranžové tulipány','tulipány na zahradě','slang','none'),
(3747,'cz','To štěně má milion skvrn!','Ta kočka má milion skvrn!','černé skvrny na bílé srsti','skvrna na košili','dramatic','exaggeration'),
(3750,'cz','Jednorožec u rybníka.','Drak u rybníka.','tichý lesní rybník','rybník plný kachen','chill','none'),
(3767,'cz','Tihle fanoušci po sobě i uklidí!','Tihle hráči po sobě i uklidí!','uklidit sedačky','uklidit si pokoj','gossip','exclamation'),
(3770,'cz','Vrána se dívá doprava.','Vrána se dívá doleva.','lesklá černá vrána','vrána v letu','chill','none'),
(3772,'cz','Tenhle drak je z ledu!','Tenhle drak je z ohně!','tvář ledového draka','drak chrlící oheň','dramatic','exclamation'),
(3777,'cz','Jeho křídla hoří!','Jeho křídla jsou ve vodě!','doširoka roztažená křídla','pevně složená křídla','dramatic','exclamation'),
(3797,'cz','Stojka na rukou ve vodě!','Stojka na rukou ve sněhu!','stojka na rukou v mělké vodě','stojka na rukou na pláži','slang','none'),
(3803,'cz','Drak objímá věž!','Had objímá věž!','drak kolem věže','vysoká vodárenská věž','dramatic','exaggeration'),
(3806,'cz','V drinku jsou dvě třešně.','V drinku jsou tři třešně.','dvě třešně na stopce','miska třešní','chill','none'),
(3809,'cz','Záchranný kruh pomůže!','Záchranná vesta pomůže!','natahuje ruku pro pomoc','pomoc s úkoly','dramatic','exclamation'),
(3813,'cz','Dívá se dál po pěšině.','Dívá se dál po řece.','barevně malovaná pěšina','blátivá lesní pěšina','chill','none'),
(3825,'cz','Z vesmíru vypadá Země malinká.','Z vesmíru vypadá Mars malinký.','Země viděná z vesmíru','parkovací místo','chill','none'),
(3827,'cz','Hned za ním je monstrum!','Hned za ním je drak!','monstrum za klukem','monstrum pod postelí','dramatic','exclamation'),
(3828,'cz','Šimpanz a zápalka: špatný nápad.','Šimpanz a nůž: špatný nápad.','hořící zápalka v ruce','fotbalový zápas v televizi','chill','guessing'),
(3832,'cz','Ohňostroj vybuchuje!','Balonky vybuchují!','ohňostroj na noční obloze','ohňostroj v obchodě','dramatic','exclamation'),
(3841,'cz','Oblečení lítá všude kolem!','Boty lítají všude kolem!','oblečení vznášející se ve vzduchu','oblečení v pračce','dramatic','exclamation'),
(3842,'cz','Vyhazuje kelímek.','Vyhazuje tašku.','vyhodit kelímek','odhodit míč','business','none'),
(4001,'cz','Tahle stíhačka dělá toasty!','Tahle stíhačka dělá kafe!','stíhačka-toustovač','boxer v ringu','slang','exclamation'),
(4002,'cz','Stojka na stole? Dobrá rovnováha!','Stojka na gauči? Dobrá rovnováha!','udržet rovnováhu na stole','ztratit rovnováhu na ledu','gossip','exclamation'),
(4003,'cz','Dva páry příšerkových bačkor.','Dva páry příšerkových bot.','pár žlutých bačkor','pár žlutých rukavic','chill','none'),
(4004,'cz','Stíhačka ohřívá chleba. Normálka.','Stíhačka ohřívá polévku. Normálka.','ohřát chleba ve stíhačce','ohřát polévku na sporáku','ironic','understatement'),
(4005,'cz','Zmrzlá stěna? Žádný problém.','Skalní stěna? Žádný problém.','lézt po zmrzlé stěně','zmrzlé jezero na bruslení','ironic','understatement'),
(4006,'cz','Voda je průhledná.','Voda je tmavě zelená.','průhledná voda jezera','průhledný igelitový sáček','chill','none'),
(4007,'cz','Skočil do tmy, brácho.','Skočil do bazénu, brácho.','salto ve tmě','strach ze tmy','slang','none'),
(4008,'cz','Třese jabloní!','Leze na jabloň!','třást větví','potřást si rukou','dramatic','exclamation'),
(4009,'cz','Kachny jdou v řadě jako na školním výletě.','Slepice jdou v řadě jako na školním výletě.','kachny v dlouhé řadě','kachny v malém rybníčku','chill','exaggeration'),
(4010,'cz','Leze jako profík!','Plave jako profík!','lézt po bílém útesu','lézt po žebříku','flirt','cliche'),
(4011,'cz','Pandy jsou jeho publikum!','Opice jsou jeho publikum!','publikum z pand','publikum z dětí','dramatic','exclamation'),
(4013,'cz','Kolem paluby pluje ledovec. Titanic vajb!','Kolem paluby pluje velryba. Titanic vajb!','boty na dřevěné palubě','balíček hracích karet','slang','exclamation'),
(4014,'cz','Kufr se kutálí dál.','Bicykl se kutálí dál.','kutálet se přes parkoviště','kutálet se z kopce','chill','none'),
(4015,'cz','Ovce skáčou na břeh!','Kozy skáčou na břeh!','ovce na břehu řeky','ovce před bankou','dramatic','exclamation'),
(4016,'cz','Kočka říká vaně ne.','Pes říká vaně ne.','kočka na vaně','kočka ve vaně','low_iq','guessing'),
(4017,'cz','Červená lucerna svítí.','Modrá lucerna svítí.','svítící papírová lucerna','svítící pouliční lampa','chill','none'),
(4018,'cz','Dva psi na skútru!','Dvě kočky na skútru!','psi na zeleném skútru','psi na zeleném kole','dramatic','exclamation'),
(4019,'cz','Tohle štěně má nejlepší kruh.','Tohle kotě má nejlepší kruh.','růžový plavecký kruh','prsten s diamantem','slang','exaggeration'),
(4020,'cz','Pes sleduje žábu.','Pes sleduje rybu.','sledovat žábu','sledovat televizi','chill','none'),
(4021,'cz','Krájíte dort? Já první!','Krájíte chleba? Já první!','krájet dort na čtverce','krájet dort napůl','slang','guessing'),
(4022,'cz','Jen malá procházka po letícím letadle.','Jen malá procházka po jedoucím vlaku.','letět nad městem','letět nad mořem','ironic','understatement'),
(4023,'cz','Na lodi si užívají zábavu.','V autobuse si užívají zábavu.','zábava na řece','zábava na pláži','chill','none'),
(4024,'cz','Celá farma ho následuje!','Celá farma ji následuje!','zvířata následují muže','zvířata následují psa','dramatic','exaggeration'),
(4025,'cz','Hele, kotě to honí.','Hele, štěně to honí.','honit zelený míček','honit zeleného ptáka','slang','none'),
(4026,'cz','Voda je hladká jako sklo.','Silnice je hladká jako sklo.','klouzání po hladké vodě','hladké přistání','chill','cliche'),
(4027,'cz','Kdo snědl koláč? Kráva?','Kdo snědl koláč? Pes?','zlatavý jablečný koláč','koláčový graf v práci','gossip','blaming_someone'),
(4028,'cz','Buldok se otáčí jako profík!','Buldok skáče jako profík!','otočit se na skateboardu','otočit se na gauči','slang','exaggeration'),
(4029,'cz','Láhev ho udeřila a shodila!','Míč ho udeřil a shodil!','shozený z kvádru','klepat na dveře','slang','exclamation'),
(4030,'cz','Zaplaval si v parku.','Zdříml si v parku.','rybník v parku','skatepark','ironic','understatement'),
(4031,'cz','Míč přistál přímo na horní straně!','Míč přistál přímo na něm!','horní část hromady','horní police','dramatic','exclamation'),
(4032,'cz','Takový zelený nepořádek!','Takový červený nepořádek!','nepořádek ze zeleného slizu','nepořádek na podlaze pokoje','gossip','exaggeration'),
(4033,'cz','Poprvé s golfovou holí!','Poprvé s hokejkou!','švih golfovou holí','golfový klub pro členy','dramatic','exclamation'),
(4034,'cz','Bosé nohy, spousta pastí. Super.','Velké boty, spousta pastí. Super.','desítky pastí na myši','past na medvěda','ironic','understatement'),
(4036,'cz','Velký úsměv do kamery!','Velký úsměv pro psa!','úsměv na fotku','úsměv pro zubaře','dramatic','exclamation'),
(4037,'cz','Někdo uvařil omeletu.','Někdo uvařil palačinku.','vařit omeletu','vařit těstoviny','chill','none'),
(4038,'cz','Totálně se milují.','Totálně se nenávidí.','milovat se navzájem','milovat rychlá auta','gossip','guessing'),
(4039,'cz','Plazila se, ale kapela vyhrála.','Běžela, ale kapela vyhrála.','plazit se po rukou a špičkách','plazit se pod postelí','gossip','blaming_someone'),
(4040,'cz','Její jídlo: salát. Jeho jídlo: obří burger.','Její jídlo: pizza. Jeho jídlo: obří burger.','jídlo na pláži','jídlo v kuchyni','gossip','banter'),
(4041,'cz','Podívala se na něj. Koupili všechno.','Podívala se na něj. Nekoupili nic.','kupovat ve velkém nákupáku','kupovat jídlo na trhu','gossip','banter'),
(4042,'cz','Jsou před obchodem.','Jsou v obchodě.','před rozsvíceným obchodem','obchod plný kokosů','chill','none'),
(4043,'cz','Překvapil ji pivoňkami.','Překvapil ji prstenem.','překvapit ji květinami','narozeninová oslava s překvapením','gossip','none'),
(4044,'cz','Trénuje golf.','Trénuje tenis.','trénovat v noci','trénovat hru na klavír','chill','none'),
(4045,'cz','Našel svůj mobil!','Našel svou peněženku!','najít ztracený mobil','najít ztraceného psa','dramatic','exclamation'),
(4046,'cz','Odmítá. Konečná odpověď.','Souhlasí. Konečná odpověď.','odmítat prstem','odmítat večeři','ironic','cliche'),
(4047,'cz','Dokonalá dovolená, ale mobil pořád v ruce.','Dokonalá dovolená, ale knížka pořád v ruce.','dovolená na pláži','dovolená ve sněhu','ironic','banter'),
(4048,'cz','Nainstalovali do dodávky sprchu!','Nainstalovali do dodávky vanu!','instalovat solární panely','instalovat novou appku','gossip','exclamation'),
(4049,'cz','Takový náklad na jeho ramenou!','Takový náklad na jeho kole!','nese obrovský náklad','nese náklad cihel','dramatic','exclamation'),
(4050,'cz','Kamarádi mají psa.','Kamarádi mají kočku.','kamarádi u ohně','kamarádi v baru','chill','none'),
(4051,'cz','Náklaďák veze motocykl.','Náklaďák veze kolo.','elektrický motocykl','helma na motocykl','chill','none'),
(4052,'cz','Zase nahrávají. Pokus číslo deset?','Zase tancují. Pokus číslo deset?','nahrávat na mobil','nahrávat písničku','gossip','guessing'),
(4053,'cz','I ta kukuřice je dort!','I ta mrkev je dort!','dort ve tvaru kukuřice','kukuřičné pole při západu slunce','dramatic','exclamation'),
(4054,'cz','Pes dělá na klávesnici přesčasy. Brzy povýšení?','Kočka dělá na klávesnici přesčasy. Brzy povýšení?','tlapky na klávesnici','klaviatura piana','gossip','guessing'),
(4055,'cz','Dinosauři? Husky říká ne!','Dinosauři? Kočka říká ne!','pes a dva dinosauři','pes a dvě kočky','slang','exclamation'),
(4056,'cz','Taková pěnivá oslava!','Taková tichá oslava!','oslava se šampaňským','narozeninová oslava','dramatic','exclamation'),
(4057,'cz','Celá je politá kolou!','Celá je politá vodou!','láhev koly','sklenice koly','dramatic','exclamation'),
(4058,'cz','Výlet na jednu noc, deset kufrů!','Výlet na jednu noc, dva kufry!','balení na krátký výlet','zakopnout o kufr','dramatic','banter'),
(4059,'cz','Jeden banán tři paviány nenakrmí.','Jeden banán tři zebry nenakrmí.','krmit paviány','krmit kachny','ironic','understatement'),
(4060,'cz','Pěkný proud, ale to je vodopád!','Pěkný proud, ale to je most!','proud řeky','proud dopravy','dramatic','exclamation'),
(4061,'cz','Koukni na čelist toho žraloka!','Koukni na čelist té velryby!','čelist plná zubů','čelist bez zubů','dramatic','exclamation'),
(4062,'cz','Brácha svírá hrazdu draka.','Brácha svírá zábradlí lodi.','svírat hrazdu draka','svírat volant','slang','none'),
(4064,'cz','Hnízdo je na vrcholu tyče.','Hnízdo je na vrcholu stromu.','hnízdo na tyči','vlajka na tyči','chill','none'),
(4065,'cz','Řidičem je pes. Připoutejte se, prosím.','Řidičem je kočka. Připoutejte se, prosím.','pes jako řidič','pes jako spolujezdec','business','cliche'),
(4066,'cz','Papoušek jede po červené hlíně. Legenda.','Papoušek jede po mokrém písku. Legenda.','dráha z červené hlíny','hlína na bílé košili','slang','exaggeration'),
(4067,'cz','Jezero zrcadlí stromy.','Jezero zrcadlí město.','jezero zrcadlící stromy','zrcadlit její taneční pohyby','chill','none'),
(4068,'cz','Hladí žraloka!','Hladí delfína!','hladit žraloka po hřbetě','jezdit na hřbetě žraloka','dramatic','exclamation'),
(4069,'cz','Kuřátko drží prut.','Holub drží prut.','tenký rybářský prut','holub držící prut','chill','none'),
(4070,'cz','Dva parašutisté jsou na křídle!','Dva parašutisté jsou na ocasu!','visí pod křídlem','sedí na křídle','dramatic','exclamation'),
(4071,'cz','Skáče z vraku!','Skáče z mostu!','skákat do moře','skákat do bazénu','dramatic','exclamation'),
(4072,'cz','Tři ženy, tajná laguna.','Tři muži, tajná laguna.','tyrkysová laguna','laguna plná lodí','gossip','none'),
(4073,'cz','Drama: slepice má klacek.','Drama: slepice má lžíci.','mávat dřevěným klackem','házet dřevěný klacek','gossip','none'),
(4074,'cz','Slunce je za ní.','Měsíc je za ní.','slunce nad lagunou','slunce nad městem','chill','none'),
(4075,'cz','Všude kolem žraloci: nebezpečí? Jaké nebezpečí?','Všude kolem delfíni: nebezpečí? Jaké nebezpečí?','nebezpečí všude kolem ní','nebezpečí na silnici','dramatic','understatement'),
(4076,'cz','Skáčou ze dveří!','Skáčou z okna!','otevřené dveře vrtulníku','otevřené dveře auta','dramatic','exclamation'),
(4077,'cz','Jeden holub pořád spí.','Oba holubi pořád spí.','spící v hnízdě','spící na lavičce','chill','none'),
(4078,'cz','Sedm polštářů pro jednoho člověka!','Sedm dek pro jednoho člověka!','řada bílých polštářů','hromada bílých ručníků','gossip','exclamation'),
(4079,'cz','Řeka se řítí kolem. Šílené!','Auta se řítí kolem. Šílené!','řítit se dolů po řece','řítit se na letiště','slang','exaggeration'),
(4080,'cz','Gumičky byly na zápěstí!','Gumičky byly v šuplíku!','gumičky do vlasů na zápěstí','hodinky na zápěstí','dramatic','exclamation'),
(4081,'cz','Nohy z vrtulníku nad vrcholy hor. Tak to ne.','Nohy z letadla nad vrcholy hor. Tak to ne.','zasněžené vrcholy shora','vrchol s křížem','slang','guessing'),
(4082,'cz','Ona visí vzhůru nohama.','On visí vzhůru nohama.','viset vzhůru nohama','otočit letadlo vzhůru nohama','chill','none'),
(4083,'cz','„Malý“ mops zabral střed.','„Malá“ kočka zabrala střed.','střed postele','střed gauče','ironic','understatement'),
(4084,'cz','Na hlavě mu rostou vlasy!','Na bradě mu rostou vlasy!','vlasy na holé hlavě','hlávka salátu','dramatic','exclamation'),
(4085,'cz','Úplně ho změnila.','Úplně ji změnil.','převléct se do obleku','vyměnit pneumatiku','gossip','exaggeration'),
(4086,'cz','Komár se chystá kousnout.','Pavouk se chystá kousnout.','kousat spícího muže','kousat spícího psa','chill','guessing'),
(4087,'cz','Kočky berou svou práci velmi vážně.','Psi berou svou práci velmi vážně.','kočky v oblecích v práci','kočky v oblecích ve škole','business','understatement'),
(4088,'cz','Tenhle vodopád je fakt široký. Nechoďte blíž.','Tenhle most je fakt široký. Nechoďte blíž.','široká hrana vodopádu','široký most přes řeku','dramatic','guessing'),
(4089,'cz','Chobotnice tancují!','Krabi tancují!','chobotnice tancující v klubu','chobotnice schovávající se v písku','dramatic','exclamation'),
(4090,'cz','Raketa rychle stoupá!','Letadlo rychle stoupá!','rychle stoupající raketa','slunce vycházející za úsvitu','dramatic','exclamation'),
(4091,'cz','Led pod ní praská!','Led pod ním praská!','led praskající pod jejíma nohama','rozbíjet vejce na ledu','dramatic','exclamation'),
(4092,'cz','Sjíždí dolů po schodech!','Vyjíždí nahoru po schodech!','dolů po schodech v útesu','dolů po sjezdovce','dramatic','exclamation'),
(4093,'cz','Páni, Měsíc je tak kulatý.','Páni, Měsíc je tak červený.','kulatý šedý Měsíc','kulatý šedý kámen','low_iq','none'),
(4094,'cz','Pytle s krmivem jsou barevné.','Pytle s krmivem jsou celé bílé.','pytle krmiva pro zvířata','pytle brambor','chill','none'),
(4095,'cz','Tenhle film natočila malinká kamera!','Tenhle film natočila obří kamera!','natáčení filmu','kino','dramatic','exclamation'),
(4096,'cz','Želva je svobodná a ani nepoděkuje.','Žralok je svobodný a ani nepoděkuje.','želva vypuštěná na svobodu','želva zadarmo','chill','guessing'),
(4097,'cz','Jede mega rychle.','Jede mega pomalu.','jet rychle z kopce','postit se před večeří','slang','exaggeration'),
(4098,'cz','Dvě krávy blokují cestu. Drzost.','Dvě ovce blokují cestu. Drzost.','krávy v cestě','cesta na pláž','ironic','blaming_someone'),
(4099,'cz','Pes je zpátky nahoře!','Kočka je zpátky nahoře!','zpátky na matracích','zpátky na gauči','dramatic','exclamation'),
(4100,'cz','Tu díru udělala pružina, ne já!','Tu díru udělala kočka, ne já!','díra ve stropě','díra v ponožce','low_iq','blaming_someone'),
(4101,'cz','Umělec ukazuje ocas.','Umělec ukazuje vlajku.','ukazovat obří paví ocas','ukazovat bílou vlajku','chill','none'),
(4102,'cz','Sluneční svit ho volá!','Déšť ho volá!','sluneční svit za oknem','sluneční svit v kanceláři','dramatic','exaggeration'),
(4103,'cz','Štěněti došla trpělivost.','Koťátku došla trpělivost.','trpělivost štěněte','trpělivost s koťátkem','ironic','cliche'),
(4104,'cz','Jeden polibek a je z něj rajče.','Jeden polibek a je z něj duch.','polibek na tvář','polibek na ruku','low_iq','exaggeration'),
(4105,'cz','Její přítel přinesl květiny.','Její přítel přinesl dort.','přítel s květinami','přítel s prstenem','flirt','none'),
(4106,'cz','Hladový pes to krade.','Hladová kočka to krade.','hladový pejsek','hladový muž jí sám','gossip','blaming_someone'),
(4107,'cz','Přikryli slona a vyšel z toho tygr!','Přikryli slona a vyšel z toho lev!','přikrýt slona','přikrýt tygra','dramatic','exclamation'),
(4108,'cz','Podle auta je to její manžel.','Podle auta je to její brácha.','manžel v autě','manžel myje auto','gossip','none'),
(4109,'cz','Dva psi chillují na trávníku.','Dvě kočky chillují na trávníku.','psi na zeleném trávníku','sekat trávník','slang','none'),
(4110,'cz','Klaun nečekal tygra!','Klaun nečekal lva!','klaunova oranžová paruka','klaunova fialová paruka','dramatic','guessing'),
(4111,'cz','Beran je jeho otravný kolega.','Pes je jeho otravný kolega.','otravný beran','otravná moucha','business','exaggeration'),
(4112,'cz','Úhledná díra v tvárnici.','Úhledná díra ve dveřích.','vrtání do tvárnice','blok sýra','chill','none'),
(4113,'cz','Drama se šperky na ulici!','Drama se šperky v obchodě!','růžové šperky na holubovi','růžové šperky ve výloze','gossip','exclamation'),
(4114,'cz','Pravidla obchodního centra: ona nakupuje, on nosí.','Pravidla obchodního centra: on nakupuje, ona nosí.','tašky z obchodního centra','parkoviště obchodního centra','gossip','banter'),
(4115,'cz','Dva turisté se skvěle baví. Tak roztomilí!','Dva turisté obědvají. Tak roztomilí!','turisté v noci','turisté v autobuse','gossip','exclamation'),
(4116,'cz','Jeho auto je tak malé!','Jeho auto je tak velké!','malé červené bublinkové auto','malá červená loďka','dramatic','exclamation'),
(4117,'cz','Jen takové malé hledání.','Jen takový malý šlofík.','hledání mobilu','hledání psa','chill','understatement'),
(4118,'cz','Tento kurt nabízí výhled na hory.','Tento kurt nabízí krásný výhled na moře.','kurt v horách','kurt u moře','business','none'),
(4119,'cz','Kamenný chlap se zhroutil. RIP.','Kamenný pes se zhroutil. RIP.','hroutící se kamenná postava','hroutící se kamenný most','slang','none'),
(4120,'cz','Prkno na rozbíjení vlašských ořechů.','Prkno na rozbíjení vajec.','prkno s dírou','prkno na krájení chleba','chill','none'),
(4121,'cz','Taková výbušná scéna!','Taková romantická scéna!','výbušná akční scéna','romantická filmová scéna','dramatic','none'),
(4122,'cz','Přišel vyloupit tu špatnou banku.','Přišel vyloupit ten špatný obchod.','vyloupit banku','vyloupit vlak','ironic','bad_excuse'),
(4123,'cz','Slzy kvůli jedničce? Vážně?','Slzy kvůli pětce? Vážně?','slzy kvůli jedničce','slzy smíchu','ironic','guessing'),
(4124,'cz','Dodávka, pes a dobří kamarádi.','Dodávka, kočka a dobří kamarádi.','život v obytné dodávce','stěhování s dodávkou','chill','none'),
(4125,'cz','Na jevišti je slon!','Na jevišti je kůň!','slon na jevišti','zpěvák na jevišti','dramatic','exclamation'),
(4126,'cz','Tisíce budov svítí.','Tisíce budov jsou potmě.','osvětlené budovy u přístavu','staré budovy u jezera','dramatic','none'),
(4127,'cz','Lemur má tak měkkou srst.','Lemur má tak černou srst.','měkká bílá srst','měkký bílý chleba','chill','none'),
(4128,'cz','Štěně tenhle dvůr miluje.','Kotě tenhle dvůr miluje.','štěně na dvoře','štěně na ulici','chill','guessing'),
(4129,'cz','Štěně odchází z domova.','Štěně se vrací domů.','odchod z domova v klobouku','návrat domů v klobouku','chill','none'),
(4130,'cz','Kočka mu udělala plochý sestřih!','Pes mu udělal plochý sestřih!','plochý sestřih gorily','plochý sestřih kočky','gossip','exclamation'),
(4131,'cz','Obchod používá hodně zelené.','Obchod používá hodně červené.','zeď natřená zelenou','golfový green','business','none'),
(4132,'cz','Kočka kartáčuje lva!','Pes kartáčuje lva!','kartáčovat mokrou hřívu','kartáčovat si zuby','dramatic','exclamation'),
(4133,'cz','Pes hlídá lednici.','Kočka hlídá lednici.','ležet u lednice','otevírat lednici','slang','guessing'),
(4134,'cz','Tlustý ježek přišel o všechny bodliny. Není nadšený.','Tlustý králík přišel o všechnu srst. Není nadšený.','tlustý kulatý ježek','tlustá šedá kočka','gossip','understatement'),
(4135,'cz','Kopla do míče a pak skočila mimo hřiště!','Chytila míč a pak skočila mimo hřiště!','kopat míč na bránu','chytat míč rukama','dramatic','exclamation'),
(4136,'cz','Cvičit se čtyřmi psy není snadné.','Cvičit se čtyřmi kočkami není snadné.','cvičit se psy','cvičit v parku','chill','understatement'),
(4137,'cz','Tolik žluté v jednom pokoji!','Tolik zelené v jednom pokoji!','šaty v zářivě žluté','pokoj natřený na žluto','slang','exaggeration'),
(4138,'cz','Hladí starého psa.','Hladí starou kočku.','hladit starého psa','venčit starého psa','chill','none'),
(4139,'cz','Stoupá po úzké pěšině.','Stoupá po strmém žebříku.','úzká hliněná pěšina','pěšina přes poušť','chill','none'),
(4140,'cz','Skáče z římsy. Dobrodružství, nebo blbý nápad?','Skáče z lodi. Dobrodružství, nebo blbý nápad?','dobrodružství s kamarády','dobrodružný film','dramatic','guessing'),
(4141,'cz','Pět kluků leží na sluníčku.','Pět kluků leží v bahně.','ležet v trávě','lhát kamarádům','slang','none'),
(4142,'cz','Prší na ni. Paráda!','Sněží na ni. Paráda!','točit se, zatímco prší','schovávat se, zatímco prší','slang','exclamation'),
(4143,'cz','Psst, v popelnici je mýval.','Psst, v popelnici je kočka.','mýval v popelnici','mýval na popelnici','gossip','none'),
(4144,'cz','Fretky tu trubku milují.','Kočky tu trubku milují.','fretky v trubce','tuba zubní pasty','chill','guessing'),
(4145,'cz','Vrhá se po míči!','Vrhá se po frisbee!','vrhnout se po míči','vrhnout se z lodi','dramatic','exclamation'),
(4146,'cz','Moc vyčerpaný na to, aby si zul boty.','Moc vyčerpaný na to, aby si svlékl triko.','vyčerpaný na mokrém písku','vyčerpaný v horké vaně','ironic','exaggeration'),
(4147,'cz','Spěchá. Proč ta cedule?','Spí. Proč ta cedule?','spěchat k autu','spěchat na autobus','gossip','guessing'),
(4148,'cz','Čistý luxus: červený sporťák.','Čistý luxus: červená motorka.','luxusní sporťák','luxusní hotelový pokoj','flirt','exaggeration'),
(4149,'cz','Přistálo to na spícím obrovi!','Přistálo to na spícím medvědovi!','přistání na obrovi','boj s obrem','dramatic','exclamation'),
(4150,'cz','Zelené auto uhání.','Červené auto uhání.','uhánět po venkovské silnici','uhánět po dálnici','chill','none'),
(4151,'cz','Tohle umění na autě je hodně růžové.','Tohle umění na autě je hodně zelené.','umění na autě v růžové','umění v muzeu','ironic','understatement'),
(4152,'cz','Přívěs skrývá vozidlo.','Přívěs skrývá koně.','vozidlo v přívěsu','vozidlo na trajektu','gossip','guessing'),
(4153,'cz','Modré auto na dálnici.','Červené auto na dálnici.','dálnice do hor','dálnice k moři','chill','none'),
(4154,'cz','Noční sport na antukovém kurtu.','Noční sport na travnatém kurtu.','sport pod reflektory','sport v televizi','chill','none'),
(4155,'cz','Talíře jsou teď „čisté“.','Hrnky jsou teď „čisté“.','čistý bílý talíř','čistý bílý ručník','ironic','understatement'),
(4156,'cz','Přibližuje se k nám robot!','Přibližuje se k nám pes!','přibližovat se ke kameře','přibližovat se k bazénu','dramatic','exclamation'),
(4157,'cz','Všichni závodí, ale vyhrává její cedule.','Všichni závodí, ale vyhrává její pes.','závodit kolem vtipné cedule','závodit ve sporťáku','gossip','exaggeration'),
(4158,'cz','Ta ryba je obrovská. Páni.','Ta ryba je malinká. Páni.','obrovská šklebící se ryba','obrovská šklebící se vydra','low_iq','none'),
(4159,'cz','Tak vysoko nad údolím!','Tak vysoko nad městem!','vysoko nad údolím','vysoko nad mraky','dramatic','exclamation'),
(4160,'cz','Puf! Červené auto zmizelo.','Puf! Červená dodávka zmizela.','zmizet v písku','zmizet ve sněhu','slang','exaggeration'),
(4161,'cz','Obě přední části se skoro dotýkají.','Obě zadní části se skoro dotýkají.','přední část auta','přední část domu','chill','none'),
(4162,'cz','Jedno auto. Celé náměstí. Pecka.','Jeden autobus. Celé náměstí. Pecka.','mokré dlážděné náměstí','náměstí s tržními stánky','slang','none'),
(4163,'cz','Povídá si o svém autě.','Povídá si o svém psovi.','povídat si o autě','povídat si s autem','chill','none'),
(4164,'cz','Brzda je velká a červená.','Brzda je velká a modrá.','velká červená brzda','velké červené tlačítko','chill','none'),
(4165,'cz','Při téhle rychlosti se stromy rozmazávají.','Při téhle rychlosti se domy rozmazávají.','rychlost na horské silnici','rychlost na závodním okruhu','dramatic','none'),
(4166,'cz','Vstupuje do toho červeného auta jako hvězda.','Vstupuje do toho modrého auta jako hvězda.','vstupovat do červeného sporťáku','vstupovat do červené telefonní budky','flirt','exaggeration'),
(4167,'cz','Temná jeskyně, zářivý východ.','Temná jeskyně, žádný východ.','zářivý východ z jeskyně','cedule dálničního výjezdu','dramatic','none'),
(4168,'cz','Pomalá želva nikdy nezastaví.','Pomalý zajíc nikdy nezastaví.','pomalá želva','pomalý šnek','chill','none'),
(4169,'cz','Věnuje medvědovi pohled!','Věnuje medvědovi rybu!','pohled na medvěda','pohled do mapy','dramatic','exclamation'),
(4170,'cz','Slepice zachránila své kuře!','Slepice zachránila své vejce!','zachránit kuře','ušetřit peníze','dramatic','exclamation'),
(4171,'cz','Vlk se plíží blíž.','Liška se plíží blíž.','vlk plížící se blíž','vlk utíkající pryč','chill','none'),
(4172,'cz','Slepice předvedla útěk jak z akčního filmu.','Kachna předvedla útěk jak z akčního filmu.','útěk před ohněm','útěk z vězení','dramatic','exaggeration'),
(4173,'cz','Honička skončila na mostě.','Honička skončila ve stodole.','honička přes most','honička lesem','chill','none'),
(4174,'cz','Slepice brání svá kuřata jako superhrdina.','Liška brání svá kuřata jako superhrdina.','bránit svá kuřata','bránit svá vejce','dramatic','exaggeration'),
(4175,'cz','Psst, slepice se plíží.','Psst, liška se plíží.','plížit se kolem spících vlků','plížit se do kurníku','gossip','none'),
(4176,'cz','Ve sklenici září světluška.','Ve sklenici září svíčka.','zářící světluška','zářící lampa','chill','none'),
(4177,'cz','Kuřata mají otevřená ústa.','Kuřata mají zavřená ústa.','kuřata s otevřenými ústy','kuřata s roztaženými křídly','chill','none'),
(4178,'cz','Slepice je štědrá dárkyně.','Liška je štědrá dárkyně.','štědrá slepice','štědrá liška','business','exaggeration'),
(4179,'cz','Slaví sté narozeniny!','Slaví padesáté narozeniny!','dort ke stým narozeninám','narozeniny na pláži','dramatic','exclamation'),
(4180,'cz','Zaměnila aligátora za psa: bez brýlí.','Zaměnila hada za psa: bez brýlí.','zaměnit aligátora','zaměnit štěně','gossip','bad_excuse'),
(4181,'cz','Nabízejí jí dort.','Nabízejí jí pizzu.','nabízet narozeninový dort','nabízet šálek čaje','chill','none'),
(4182,'cz','Namaloval celý trávník!','Namaloval celý dům!','malovat obří obraz na trávník','malovat zahradní plot','dramatic','exaggeration'),
(4183,'cz','V dárku je chlap!','V dárku je pes!','muž v dárku','hodinky v dárku','dramatic','exclamation'),
(4184,'cz','Štěně přináší míček zpátky. Kdo potřebuje lidi?','Štěně přináší botu zpátky. Kdo potřebuje lidi?','přinést míček zpátky','přinést míček domů','slang','exaggeration'),
(4185,'cz','Hrnek stlačuje myš.','Hrnek stlačuje vafle.','hrnek stlačující myš','talíř stlačující myš','chill','none'),
(4186,'cz','Pes vrací míček.','Pes vrací botu.','vrátit se ke stroji','vrátit se k autu','chill','none'),
(4187,'cz','Papoušci si hrají na mrtvé!','Papoušci si hrají s míčem!','papoušci hrající si na mrtvé','papoušci hrající karty','dramatic','exclamation'),
(4188,'cz','Jeden lyžař, jeden „malý“ svah.','Dva lyžaři, jeden „malý“ svah.','dlouhý zasněžený svah','svah s vleky','ironic','understatement'),
(4189,'cz','Prázdná miska, zbývá jedna pilulka.','Prázdná miska, zbývají dvě pilulky.','prázdná psí miska','prázdná lednice','chill','none'),
(4190,'cz','Kočka se setkává se lvem. V pohodě.','Pes se setkává se lvem. V pohodě.','setkat se se lvem','setkat se s tygrem','slang','understatement'),
(4191,'cz','Raketa se nad ním tyčí.','Autobus se nad ním tyčí.','raketa tyčící se nad ním','jeřáb tyčící se nad ním','chill','none'),
(4192,'cz','Fakt: tenhle orel rybaří.','Fakt: tahle sova rybaří.','rybařit pomocí pařátů','rybařit s prutem','nerd','none'),
(4193,'cz','Batman potřebuje tuhle podzemní garáž.','Batman potřebuje tenhle podzemní bazén.','podzemní garáž','podzemní vlak','dramatic','exaggeration'),
(4194,'cz','Taková jízda v malinkém džípu!','Taková jízda v malinké lodičce!','jízda v džípu na hraní','jízda v lodičce na hraní','dramatic','exclamation'),
(4195,'cz','Koloběžka se rozbila na kusy!','Kolo se rozbilo na kusy!','koloběžka se rozbíjí','překonat světový rekord','dramatic','exclamation'),
(4196,'cz','V kbelíku je svíčka.','V kbelíku je květina.','svíčka v kbelíku','kbelík vody','chill','none'),
(4198,'cz','Díra vede hluboko pod vodu. Uvidíme se na dně!','Lano vede hluboko pod vodu. Uvidíme se na dně!','pád hluboko do šachty','kopat hluboko v písku','slang','exclamation'),
(4199,'cz','Nohy se mu táhnou jezerem.','Ruce se mu táhnou jezerem.','táhnout nohy vodou','táhnout loď k vodě','chill','none'),
(4200,'cz','Při západu slunce má moře zlatou barvu.','Při západu slunce má moře červenou barvu.','moře a nebe ve zlaté barvě','prsten ze zlata','chill','none'),
(4201,'cz','Frajeři! Bicykly stojí vzpřímeně.','Frajeři! Auta stojí vzpřímeně.','bicykly vzpřímeně na jednom kole','sedět vzpřímeně na židli','ironic','exclamation'),
(4202,'cz','Hodně zaneprázdnění psi, břicha nahoru.','Hodně zaneprázdněné kočky, břicha nahoru.','břicha nahoru na sluníčku','břicho plné jídla','ironic','understatement'),
(4203,'cz','Zachránil žraloka. Hrdina.','Zachránil delfína. Hrdina.','zachránit uvízlého žraloka','zachránit uvízlou velrybu','dramatic','exaggeration'),
(4205,'cz','Nese sedmikrásku.','Nese růži.','nést květinu','nést semínko','chill','none'),
(4206,'cz','Křeček má odznak. Křeček je šéf.','Křeček má mobil. Křeček je šéf.','křečkův odznak se jménem','policejní odznak','low_iq','exaggeration'),
(4207,'cz','Pizza doručena: pravá láska!','Dort doručen: pravá láska!','doručovat krabici s pizzou','doručovat dopisy na kole','gossip','guessing'),
(4208,'cz','Tenhle křeček snědl každou svačinu.','Tenhle králík snědl každou svačinu.','svačina za svačinou','svačina na později','low_iq','exaggeration'),
(4209,'cz','Jeden křeček je v hlubokém spánku.','Jedna kočka je v hlubokém spánku.','křeček v hlubokém spánku','spánek na studené podlaze','chill','none'),
(4210,'cz','Ta-dá! Drží zmrzlinu.','Ta-dá! Drží mrkev.','držet dvě zmrzliny','držet dvě mrkve','dramatic','exclamation'),
(4211,'cz','Tenhle křeček pečuje o své tváře víc než já.','Tenhle králík pečuje o své tváře víc než já.','křeček poplácávající si tváře','křeček cpoucí si tváře','ironic','exaggeration'),
(4212,'cz','Jejich hnědé outfity k sobě ladí.','Jejich červené outfity k sobě ladí.','sladěné hnědé outfity','hnědá kožená pohovka','business','none'),
(4213,'cz','V červené vypadají jako královny!','V modré vypadají jako královny!','oblečené v sytě červené','červené víno ve sklenici','dramatic','exaggeration'),
(4214,'cz','Oba začínají ve světle modrém oblečení.','Oba začínají v tmavě zeleném oblečení.','pár ve světle modrém oblečení','světle modré závěsy','chill','none'),
(4215,'cz','Je v oranžové a bílé.','Je v zelené a bílé.','oranžová s bílou','loupání pomeranče','chill','none'),
(4216,'cz','Její bílé šaty jsou nádherné.','Její žluté šaty jsou nádherné.','bílé bavlněné šaty','bílé svatební šaty','flirt','none'),
(4218,'cz','Korgi dává motoru pořádně zabrat.','Kočka dává motoru pořádně zabrat.','kouřící motor traktoru','kouřící motor auta','ironic','blaming_someone'),
(4219,'cz','Zvíře rychle letí.','Zvíře rychle plave.','jízda na létajícím zvířeti','krmení létajícího zvířete','chill','none'),
(4220,'cz','Čistí bílé auto.','Čistí černé auto.','čistit lak','uklízet dům','business','none'),
(4221,'cz','Ještěrka chilluje na gauči.','Ještěrka chilluje na stole.','cereálie na gauči','cereálie na kuchyňském stole','slang','none'),
(4222,'cz','Hele, gekon mává.','Hele, žába mává.','mávat do kamery','mávat vlajkou','slang','none'),
(4223,'cz','Moc pálivé! Šlehá z toho oheň!','Moc sladké! Šlehá z toho oheň!','pálivé červené chilli papričky','pálivé kari s rýží','dramatic','exclamation'),
(4224,'cz','Ještěrka používá záchod.','Ještěrka používá kuchyň.','ještěrka na záchodě','ještěrka čistí záchod','chill','none'),
(4225,'cz','Oběd je houbička v míse!','Oběd je mrkev v míse!','malá bílá mísa','mísa se sýrem','low_iq','exclamation'),
(4226,'cz','Krokodýl loví!','Dinosaurus loví!','lovící krokodýl','lovící dinosaurus','dramatic','exclamation'),
(4227,'cz','Nejpřátelštější policejní kontrola ever.','Nejnaštvanější policejní kontrola ever.','přátelský policista','přátelská prodavačka','slang','exaggeration'),
(4228,'cz','Vrtulníkem na břeh, jen kvůli vajíčkům!','Lodí na břeh, jen kvůli vajíčkům!','na travnatém břehu','na písečném břehu','dramatic','exaggeration'),
(4229,'cz','Někdo osvobozuje opici.','Někdo osvobozuje psa.','osvobodit zmrzlou opici','osvobodit zmrzlého ptáka','chill','none'),
(4230,'cz','Na sedadle řidiče je pes.','Na sedadle řidiče je kočka.','sedadlo řidiče','zadní sedadlo','chill','none'),
(4231,'cz','Dva psi za oknem? Podezřelé.','Dvě kočky za oknem? Podezřelé.','zamlžené okno náklaďáku','zamlžené okno koupelny','gossip','guessing'),
(4232,'cz','Delfín v představení kopl jako Ronaldo!','Tuleň v představení kopl jako Ronaldo!','představení s delfíny','delfín v televizi','dramatic','exaggeration'),
(4233,'cz','Most z kamene: dost pevný pro vlaky.','Most ze dřeva: dost pevný pro vlaky.','železniční most z kamene','železniční tunel z kamene','business','none'),
(4234,'cz','Zničil jí šatnu během pár vteřin.','Zničila mu šatnu během pár vteřin.','prostorná šatna','kuchyňská spíž','gossip','banter'),
(4235,'cz','Skvěle nahozeno. Zatím nula ryb.','Skvěle nahozeno. Zatím tři ryby.','nahodit udici','vrhat dlouhý stín','ironic','understatement'),
(4236,'cz','Přitáhla jejich pozornost.','Přitáhl jejich pozornost.','přitahovat jejich pozornost','přitahovat nové zákazníky','gossip','none'),
(4237,'cz','Hele, kluk je ve stodole.','Hele, kluk je v kuchyni.','kůň ve stodole','kůň na poli','gossip','none'),
(4238,'cz','Žádná trouba? Upekli žebra na kameni.','Žádná trouba? Upekli rybu na kameni.','pečená jehněčí žebírka','pečené kuře','slang','none'),
(4239,'cz','Nejlepší taxík ever: racek nad přístavem.','Nejlepší taxík ever: drak nad přístavem.','let nad rušným přístavem','přístav plný jachet','slang','exaggeration'),
(4240,'cz','Vidím dva identické psy.','Vidím dvě identické kočky.','dva identičtí huskyové','dvě identické kočky','low_iq','none'),
(4241,'cz','Pilotuje skrz mraky!','Pilotuje skrz sníh!','pilotovat skrz mraky','pilotovat vrtulník','dramatic','exclamation'),
(4242,'cz','Brána? Kočka stejně projde.','Brána? Pes stejně projde.','procházet branou','přihrát míč','slang','understatement'),
(4243,'cz','Někdo platí kartou.','Někdo platí hotově.','platit za hot dog','platit za pizzu','chill','none'),
(4244,'cz','Býk útočí na auto!','Kůň útočí na auto!','býk útočící na auto','nabíjení autobaterie','dramatic','exclamation'),
(4245,'cz','Kloužou se zadarmo!','Lyžují zadarmo!','klouzat se vodním kanálem','klouzat se ze zasněženého kopce','dramatic','cheap_quality'),
(4246,'cz','Páv je celý v modré barvě.','Páv je celý v zelené barvě.','páv v modré barvě','papoušek v modré barvě','chill','none'),
(4247,'cz','Kluci skáčou do studny!','Kluci skáčou do jezera!','kluci skákající do studny','kluci pijící ze studny','dramatic','exclamation'),
(4248,'cz','Tentokrát vyhrála vlna v krytém bazénu.','Tentokrát vyhrála vlna v oceánu.','krytý bazén s vlnami','lekce plavání v krytém bazénu','chill','none'),
(4249,'cz','Jsem na zádech draka!','Jsem na zádech koně!','záda draka','záda koně','dramatic','exclamation'),
(4250,'cz','Pes zdemoloval sklad.','Kočka zdemolovala sklad.','pes ve skladu','sklad plný aut','gossip','blaming_someone'),
(4251,'cz','Jeho prostor? Jedna prázdná police.','Jeho prostor? Jedna plná police.','prostor na jeho oblečení','prostor pro auto','ironic','understatement'),
(4252,'cz','Týmová práce: jeden usrkává, druhý drhne beton.','Týmová práce: jeden usrkává, druhý drhne bazén.','drhnout terasu z betonu','lít čerstvý beton','ironic','exaggeration'),
(4253,'cz','Myjí blátivého chlapa.','Myjí blátivého psa.','smývat silnou vrstvu bláta','mýt nádobí','low_iq','exaggeration'),
(4254,'cz','Na pultu je holub.','Na střeše je holub.','holub na pultu','pult v bance','chill','none'),
(4256,'cz','Klokana někdo škrábe a on to miluje.','Koalu někdo škrábe a ona to miluje.','škrábat klokana','škrábat dveře auta','chill','guessing'),
(4257,'cz','Želva je v těsném objetí.','Ryba je v těsném objetí.','těsné pandí objetí','těsné objetí pod vodou','chill','none'),
(4258,'cz','Srnče je na skluzavce z oceli.','Srnče je na skluzavce ze dřeva.','dlouhá skluzavka z oceli','dlouhý most z oceli','chill','none'),
(4259,'cz','Tahle ovce má pondělní obličej.','Tahle kráva má pondělní obličej.','naštvaný ovčí obličej','šťastný ovčí obličej','ironic','cliche'),
(4260,'cz','Pes tu postavu ignoruje.','Pes štěká na tu temnou postavu.','postava ve dveřích','postava u okna','ironic','guessing'),
(4261,'cz','U bazénu je slunečný den.','U bazénu je deštivý den.','slunečný zahradní bazén','slunečná pláž','chill','none'),
(4263,'cz','Páni! Ptáci ji obdivují.','Páni! Ptáci ji ignorují.','obdivovat růžového ptáka','obdivovat růžový dort','gossip','exclamation'),
(4264,'cz','Pouliční volejbal, bez sítě.','Plážový volejbal, bez sítě.','volejbal na klidné ulici','volejbal na pláži','chill','understatement'),
(4265,'cz','Objetí uklidňuje papouška.','Písnička uklidňuje papouška.','uklidnit naštvaného papouška','uklidnit plačící miminko','chill','none'),
(4266,'cz','Ten pes je tak plný energie!','Ta kočka je tak plná energie!','pes plný energie běží','pes plný energie plave','dramatic','exclamation'),
(4267,'cz','Nový look: pes je tak úhledný.','Nový look: kočka je tak úhledná.','úhledná kulatá srst','úhledná řada psů','gossip','none'),
(4268,'cz','Pes je větší fanoušek, bez legrace.','Kočka je větší fanoušek, bez legrace.','psí fotbalový fanoušek','větrák na horké dny','slang','exaggeration'),
(4269,'cz','Vyschlá půda rychle pije.','Vyschlý písek rychle pije.','zalévání vyschlé půdy','zametání vyschlého listí','dramatic','exaggeration'),
(4270,'cz','Zpomaluje kvůli kachně.','Zpomaluje kvůli psovi.','zpomalit kvůli kachně','zpomalit na semaforu','chill','none'),
(4271,'cz','Ten atlet je tak rychlý!','Ten atlet je tak pomalý!','atlet v plné rychlosti','atlet v cíli','slang','exclamation'),
(4272,'cz','Přidává další zlaté šperky!','Přidává další stříbrné šperky!','zlaté kruhové náušnice','zlatá medaile','dramatic','exclamation'),
(4273,'cz','Tady se stala srážka.','Tady se konal koncert.','srážka na křižovatce','srážka na dálnici','dramatic','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
