begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(5211,'cz','Jaký šťastný návrat domů!','Jaký smutný návrat domů!','šťastný návrat domů','návrat do školy','dramatic','exclamation'),
(5212,'cz','Velké objímání na nádraží!','Velké objímání na letišti!','objímání na nádraží','rozhlasová stanice','dramatic','exclamation'),
(5213,'cz','Na železnici stojí červený vlak.','Na železnici stojí červená tramvaj.','nástupiště železniční stanice','železnice v horách','chill','none'),
(5214,'cz','Kolo, koloběžka, pak poušť!','Kolo, koloběžka, pak džungle!','velbloud v poušti','velbloud v zoo','dramatic','exclamation'),
(5215,'cz','Cyklistika u fjordu: ona to dává.','Cyklistika ve městě: ona to dává.','cyklistika u fjordu','cyklistika ve městě','chill','none'),
(5216,'cz','Jde na pomalou procházku.','Jde si pomalu zaplavat.','procházka kolem stánků s květinami','procházka po pláži','chill','none'),
(5217,'cz','Má na sobě žlutou vestu.','Má na sobě oranžovou vestu.','žlutá reflexní vesta','vesta pod košilí','chill','none'),
(5218,'cz','Kontroluje každý pokoj.','Uklízí každý pokoj.','pokoj s klenutými okny','pokoj s krbem','chill','none'),
(5219,'cz','Spolubydlící udělali těstoviny. Mňam.','Spolubydlící udělali pizzu. Mňam.','dva spolubydlící v bytě','dva spolubydlící se stěhují','low_iq','none'),
(5220,'cz','Někdo odstřihává růži.','Někdo zalévá růži.','odstřihnout stonek růže','stříhat psovi drápky','chill','none'),
(5221,'cz','Cesta se vine do kopců.','Řeka se vine do kopců.','cesta vinoucí se horami','řeka vinoucí se z kopce','chill','none'),
(5222,'cz','Stoupá po kamenných schodech.','Stoupá po dřevěných schodech.','kamenné schody do hor','kamenné schody k pláži','chill','none'),
(5223,'cz','Její trasa je vyznačená červeně.','Její trasa je vyznačená modře.','trasa na mapě','autobusová trasa městem','chill','none'),
(5224,'cz','Má královskou kapelu.','Má královského koně.','královský trůn','královská svatba','chill','none'),
(5226,'cz','Stihl naskočit do vagonu!','Stihl naskočit do taxíku!','skok do vagonu vlaku','kočár tažený koňmi','dramatic','exclamation'),
(5227,'cz','Má několik nových fanoušků.','Má několik nových koček.','několik běžících psů','několik jedoucích aut','gossip','exaggeration'),
(5228,'cz','Hustě sněží!','Hustě prší!','sněží na náměstí','sněží na pláži','dramatic','exclamation'),
(5229,'cz','Hodila hrst sněhu.','Hodila hrst písku.','hrst prašanu','hrst mincí','chill','none'),
(5230,'cz','Panenka má uvnitř panenku!','Panenka má uvnitř minci!','malovaná dřevěná panenka','domeček pro panenky','dramatic','exclamation'),
(5231,'cz','Její pohostinnost zahrnuje čaj.','Její pohostinnost zahrnuje pivo.','pohostinnost s čajem a jídlem','práce v pohostinství','business','none'),
(5232,'cz','Pluje na jachtě.','Uklízí jachtu.','klasická plachetní jachta','jachta v přístavu','chill','none'),
(5233,'cz','Vojenská přehlídka je obrovská.','Vojenská přehlídka je maličká.','vojenská přehlídka','vojenská nemocnice','chill','none'),
(5234,'cz','Každá řada je dokonale rovná.','Každá řada je totální chaos.','řady salutujících žen','řady běžících mužů','business','none'),
(5235,'cz','Razítkuje náklad.','Natírá náklad.','náklad v kontejnerovém přístavu','náklad na letišti','chill','none'),
(5236,'cz','Město je v dálce.','Velbloud je v dálce.','věže v dálce','dálkový hovor','chill','none'),
(5237,'cz','Čaj pod nebem plným hvězd.','Čaj pod nebem plným ptáků.','hvězdy nad pouštním táborem','hvězdy nad městem','chill','none'),
(5238,'cz','Selfie na rudé duně? Ikonické.','Selfie na bílé duně? Ikonické.','selfie na rudé duně','jízda bugynou po dunách','slang','none'),
(5239,'cz','Jaké dokonalé vypuštění!','Jaké dokonalé přistání!','vypuštění sokola','vydání alba','dramatic','exclamation'),
(5240,'cz','Sokol má roztažená křídla.','Sokol má složená křídla.','obě křídla roztažená','kuřecí křídla na talíři','chill','none'),
(5241,'cz','Žena zajíždí do komory.','Muž zajíždí do komory.','zářící lékařská komora','koncert komorní hudby','chill','none'),
(5242,'cz','Její saténový župan vypadá elegantně.','Její vlněný župan vypadá elegantně.','elegantní saténový župan','elegantní večírek','flirt','none'),
(5243,'cz','Naplánovala celý měsíc.','Naplánovala celý týden.','naplánovat celý měsíc','naplánovat schůzku','business','none'),
(5244,'cz','Spolužáci se dohodli.','Učitelé se dohodli.','setkání dvou spolužáků','večírek spolužáka','chill','guessing'),
(5245,'cz','Chemikálie svítí fialově!','Chemikálie svítí oranžově!','svítící fialová chemikálie','chemikálie v nádrži','dramatic','exclamation'),
(5246,'cz','Drží růžovou baňku.','Drží růžový telefon.','baňka s modrou kapalinou','baňka s horkým čajem','nerd','none'),
(5247,'cz','Babička zuří kvůli šlépějím.','Babička zuří kvůli rozbité váze.','zablácené šlépěje v předsíni','zablácené šlépěje na zahradě','gossip','blaming_someone'),
(5248,'cz','Platí nájemné za koloběžku.','Platí nájemné za kolo.','nájemné za koloběžku','nájemné za byt','chill','none'),
(5249,'cz','Myje pánev, která zažila lepší časy.','Myje hrnek, který zažil lepší časy.','mýt začouzený hrnec','mýt si obličej','ironic','cliche'),
(5250,'cz','Má pracovní hovor.','Má videohovor.','hovor přes stolní telefon','videohovor na notebooku','business','none'),
(5251,'cz','Píše na klávesnici a telefonuje!','Píše na klávesnici a jí!','psaní na klávesnici při telefonování','psaní SMS zprávy','dramatic','exclamation'),
(5252,'cz','Tropické ovoce je ve slevě.','Mražené ovoce je ve slevě.','hromada tropického ovoce','akvárium s tropickými rybami','business','none'),
(5253,'cz','Tihle starší lidi tancujou líp než já.','Tihle starší lidi plavou líp než já.','starší tanečníci v parku','starší plavci v bazénu','slang','exaggeration'),
(5254,'cz','Koukni, jak ti partneři tancujou!','Koukni, jak ti partneři plavou!','tanec s partnerem','karty s partnerem','flirt','exclamation'),
(5255,'cz','Ten kluk vypadá hodně vinně a hodně v šoku.','Ta holka vypadá hodně vinně a hodně v šoku.','vinný mladý muž','vinný soudce','gossip','guessing'),
(5256,'cz','Soudce k nim promlouvá.','Zdravotní sestra k nim promlouvá.','promlouvat k plnému sálu','psát adresu na dopis','chill','none'),
(5257,'cz','Komorník nese čaj.','Komorník nese víno.','komorník nesoucí čaj','komorník otevírá dveře','chill','none'),
(5258,'cz','Bar na střeše, párty se šejkrem!','Bar ve sklepě, párty se šejkrem!','střešní bar při západu slunce','tabulka čokolády','slang','exclamation'),
(5259,'cz','Velký pes si otřepává mokrou srst. Sprcha pro všechny.','Velká kočka si otřepává mokrou srst. Sprcha pro všechny.','otřepávání mokré srsti','kartáčování mokré srsti','ironic','exaggeration'),
(5260,'cz','Přistižen s dortem. Ten stud!','Přistižen s pizzou. Ten stud!','stud kvůli dortu','stud kvůli rozbitému talíři','dramatic','exclamation'),
(5261,'cz','I běžec dostal svůj podíl!','I cyklista dostal svůj podíl!','podíl z pizzy','podíl ve firmě','gossip','exclamation'),
(5263,'cz','Na polici je fotografie.','Na polici je zrcadlo.','zarámovaná rodinná fotografie','focení rodinné fotografie','chill','none'),
(5264,'cz','Přesouvá gauč.','Přesouvá lednici.','přesouvání nábytku','řazení rychlostí v autě','chill','none'),
(5265,'cz','Loď veze kontejnery.','Loď veze auta.','loď s kontejnery','náklaďák s kontejnery','chill','none'),
(5266,'cz','Upustila telefon!','Upustila šálek!','upuštěný telefon','telefonní budka','dramatic','exclamation'),
(5267,'cz','Její zbraň leží na stojanu.','Její zbraň leží na židli.','zbraň na stojanu','zbraň v pouzdře','business','none'),
(5268,'cz','Míří puškou.','Čistí pušku.','střelba z pušky vleže','puška na zádech na lyžích','chill','none'),
(5269,'cz','Koupila si kabát.','Koupila si šaty.','kupuje olivový kabát','kupuje nové auto','business','none'),
(5270,'cz','Vykupuje všechny cereálie v supermarketu!','Vykupuje všechny polévky v supermarketu!','nákupní vozík ze supermarketu','parkoviště u supermarketu','gossip','exaggeration'),
(5271,'cz','Jejich výkřik plní kaňon!','Jejich píseň plní kaňon!','výkřik nad kaňonem','výkřik o pomoc','dramatic','exclamation'),
(5272,'cz','Turisti úplně šílí.','Turisti jdou domů.','turisti jásají u kaňonu','turisti odpočívají ve stanu','slang','none'),
(5273,'cz','Modelka válí v zelených kalhotách.','Modelka válí v oranžových kalhotách.','modelka na molu','model letadla','slang','none'),
(5274,'cz','Sprcha puštěná. Teď je promočený.','Sprcha vypnutá. Teď je promočený.','promočený ve sprše','promočený v dešti','low_iq','none'),
(5275,'cz','Dvě sobecké děti, jeden ovladač.','Dvě sobecké děti, jeden mobil.','hádající se sobecké děti','sobecký řidič parkuje','gossip','none'),
(5276,'cz','Jedna sušenka, dva sourozenci: válka.','Jeden dort, dva sourozenci: válka.','sourozenci stavějí bunkr','sourozenci dělají úkoly','dramatic','exaggeration'),
(5277,'cz','Souhlasili: každý půlku.','Souhlasili: všechno pro něj.','souhlasit s půlkou sušenky','souhlasit se společným pokojem','chill','none'),
(5278,'cz','Roh dosažen. Pokračujeme.','Řeka dosažena. Pokračujeme.','roh dvou ulic','roh pokoje','business','none'),
(5279,'cz','Podepisuje obří svitek obřím perem!','Podepisuje obří svitek maličkým perem!','podepisování obřího svitku','čtení starého svitku','dramatic','exclamation'),
(5280,'cz','Čte rozcestník.','Natírá rozcestník.','čtení dřevěného rozcestníku','natírání dřevěného rozcestníku','chill','none'),
(5281,'cz','Hvězda zpívá na pódiu.','Hvězda tančí na pódiu.','hvězda na pódiu','hvězda na obloze','chill','none'),
(5282,'cz','Všichni zpívají píseň.','Všichni píšou píseň.','zpívání písně','píseň v rádiu','gossip','none'),
(5283,'cz','Je to jen malá věž z talířů.','Je to jen malá věž z hrnků.','věž z talířů','věž ze skleniček','chill','understatement'),
(5284,'cz','Ta kovová zbroj ti sluší, rytíři.','Ta kovová koruna ti sluší, rytíři.','celá kovová zbroj','celá metalová kapela','flirt','none'),
(5285,'cz','Čisté štěstí na zahradě.','Čisté štěstí v kuchyni.','štěstí na slunné zahradě','štěstí na slunné pláži','chill','none'),
(5286,'cz','Oba chtějí tu mikinu!','Oba chtějí toho plyšáka!','tahání o šeříkovou mikinu','praní šeříkové mikiny','dramatic','exclamation'),
(5287,'cz','Patnáct holek, nula ticha!','Patnáct kluků, nula ticha!','místnost bez ticha','minuta ticha','dramatic','exaggeration'),
(5288,'cz','Letí dolů na lyžích!','Letí dolů na sáňkách!','carving na lyžích','lyže opřené o zeď','dramatic','exaggeration'),
(5289,'cz','Pleti chybí vlhkost.','Pleti chybí póry.','pleť bez vlhkosti','vlhkost na okně','nerd','none'),
(5290,'cz','To je ale vysoký mrakodrap!','To je ale vysoký maják!','mrakodrap se špicí','stavba mrakodrapu','dramatic','exclamation'),
(5291,'cz','Každý podnikatel spí.','Každý podnikatel čte.','podnikatelé spící v letadle','podnikatelé spící ve vlaku','chill','none'),
(5292,'cz','Nikdo tu není moc produktivní.','Všichni tu jsou velmi produktivní.','ne moc produktivní den','produktivní porada týmu','ironic','understatement'),
(5293,'cz','Míček je teď v jeho rukavici.','Míček je teď v jeho čepici.','kožená baseballová rukavice','rukavice na zimu','chill','none'),
(5294,'cz','Její nohy milujou ty papuče.','Její nohy milujou ty ponožky.','chlupaté ovečkové papuče','papuče pod postelí','chill','exaggeration'),
(5295,'cz','Troubí na obrovský roh.','Troubí na maličký roh.','troubení na dlouhý roh','roh na hlavě ovce','chill','none'),
(5296,'cz','Vaří tradiční jídlo!','Kupuje tradiční jídlo!','vaření tradičního jídla','tradiční tanec','dramatic','exclamation'),
(5297,'cz','Starý hrad je v úplném rozpadu.','Starý most je v úplném rozpadu.','hrad v rozpadu','hrad ve sněhu','chill','none'),
(5298,'cz','Její sako je béžové.','Její sako je černé.','béžové sako na míru','zkoušení saka','chill','none'),
(5299,'cz','Její klobásy jsou tady nelegální!','Její knížky jsou tady nelegální!','nelegální jídlo v kufru','nelegální parkování na letišti','gossip','exclamation'),
(5300,'cz','Zmije je skutečná hrozba.','Ještěrka je skutečná hrozba.','hrozba na skalách','hrozba v dopise','dramatic','none'),
(5301,'cz','Její alergie nesnáší tuhle louku.','Její alergie nesnáší tuhle pláž.','alergie na pyl','alergie na psy','low_iq','exaggeration'),
(5302,'cz','Květy ho rozkýchaly!','Květy ho rozplakaly!','kýchání pod květy','malování třešňových květů','dramatic','blaming_someone'),
(5303,'cz','Sněhové vločky na jejím palčáku.','Sněhové vločky na její botě.','sněhová vločka na palčáku','sněhová vločka na okně','chill','none'),
(5304,'cz','Fuj! Špína po celých rukou!','Fuj! Barva po celých rukou!','špína na rukou','špína na botách','dramatic','exclamation'),
(5305,'cz','Jejich společnost tvrdě pracuje.','Jejich společnost je na dovolené.','celá společnost při práci','společnost na večírku','business','none'),
(5306,'cz','Tak pohodlně na jednom gauči!','Tak pohodlně na jedné posteli!','pohodlně na plném gauči','pohodlně ve velké posteli','dramatic','exclamation'),
(5307,'cz','Pokoj je velmi prostorný.','Pokoj je velmi malý.','prostorný obývák','prostorný kufr auta','business','none'),
(5308,'cz','Muž jí nese slunečnice.','Muž jí nese růže.','kytice slunečnic','pole slunečnic','chill','none'),
(5309,'cz','Někdo jí nechal sladký vzkaz.','Někdo jí nechal smutný vzkaz.','vzkaz se smajlíkem','vzkaz na lednici','gossip','none'),
(5310,'cz','Syn pomáhá opravovat auto.','Syn pomáhá mýt auto.','syn s klíčem v ruce','syn myje auto','chill','none'),
(5311,'cz','Celá skupina je teď klidná.','Celá skupina je teď naštvaná.','klidní pod dekami','klidný pod tlakem','chill','none'),
(5312,'cz','Grilovačka na dvorku za domem? Jdem do toho!','Bazénová párty na dvorku za domem? Jdem do toho!','grilování na dvorku za domem','bazén na dvorku za domem','slang','exclamation'),
(5313,'cz','Neonové nápisy pokrývají každou zeď.','Papírové nápisy pokrývají každou zeď.','zářící neonové nápisy','neonová světla v klubu','chill','none'),
(5314,'cz','V jejím košíku je celá Paříž!','V její tašce je celá Paříž!','košík suvenýrů','košík ovoce','slang','exaggeration'),
(5315,'cz','Má spoustu pohlednic. Pro koho?','Má spoustu známek. Pro koho?','pohlednice Paříže','psaní pohlednice','gossip','guessing'),
(5316,'cz','Zbožňuju její pružné kudrnaté vlasy.','Zbožňuju její pružné rovné vlasy.','hustě kudrnaté tmavé vlasy','dlouhé kudrnaté blond vlasy','flirt','none'),
(5317,'cz','Její volány lítají!','Její boty lítají!','vrstvy červených volánů','volány na límečku košile','dramatic','exclamation'),
(5318,'cz','Mluví k veřejnosti.','Zpívá veřejnosti.','mluví do mikrofonu','mluví do telefonu','business','none'),
(5319,'cz','Pavouk je pod svou pavučinou.','Pavouk je nad svou pavučinou.','pavučina mezi větvemi','pavučina v rohu','chill','none'),
(5320,'cz','Předvádí páteř.','Předvádí srdce.','předvádění na modelu páteře','demonstrace na ulici','business','none'),
(5321,'cz','Bruslí jak profík.','Lyžuje jak profík.','bruslení na jedné noze','bruslení na silnici','slang','cliche'),
(5322,'cz','Hnusná polívka! Vyplivl ji.','Hnusnej čaj! Vyplivl ho.','vyplivnout zelenou polívku','vyplivnout pecku z třešně','low_iq','none'),
(5323,'cz','Ten kámen udělal pořádný šplouch.','Ta loďka udělala pořádný šplouch.','házení velkého kamene','házení žabek plochým kamenem','slang','exaggeration'),
(5324,'cz','Houba porazila omáčku!','Houba porazila sýr!','houba plná pěny','piškotový korpus','dramatic','exclamation'),
(5325,'cz','Manželé podepsali dokument.','Manželé spálili dokument.','manželé podepisují papíry','manželé se hádají doma','business','none'),
(5326,'cz','Trenér jí tejpuje kotník.','Trenér jí tejpuje zápěstí.','trenér pomáhá gymnastce','trenér křičí na hráče','chill','none'),
(5327,'cz','Klientka má černý plášť.','Klientka má bílý plášť.','černý kadeřnický plášť','plášť superhrdiny','chill','none'),
(5328,'cz','Čichá k broskvové halence.','Čichá k bílé halence.','broskvová halenka s volány','žehlení broskvové halenky','chill','none'),
(5329,'cz','Semínko má malinký kořínek!','Semínko má malinkou kytičku!','semínko s kořínkem','semínko v zobáku','dramatic','exclamation'),
(5331,'cz','Její kondice? Drtí melouny!','Její kondice? Drtí kokosy!','kondice u plážového baru','aplikace na kondici','slang','exaggeration'),
(5332,'cz','Personál projevuje silnou jednotu.','Hosté projevují silnou jednotu.','jednota týmu','jednota země','business','none'),
(5333,'cz','Každé schodiště je luxusnější!','Každé schodiště je špinavější!','velkolepé mramorové schodiště','schodiště v majáku','dramatic','exclamation'),
(5334,'cz','Fanoušci tuhle chvíli respektují.','Fanoušci tuhle chvíli ignorují.','respektovat tu chvíli','respektovat rychlostní limit','chill','none'),
(5335,'cz','Je nadšená fanynka.','Je nadšená hráčka.','nadšená fotbalová fanynka','nadšená tenisová fanynka','chill','none'),
(5336,'cz','Jeho kšiltovka ukazuje jeho věrnost.','Jeho šála ukazuje jeho věrnost.','věrnost klubu','věrnost králi','dramatic','none'),
(5337,'cz','S croissantem v puse cestuje po železnici.','S pizzou v puse cestuje po železnici.','cestování po železnici','cestování letadlem','gossip','none'),
(5338,'cz','Zůstat můžeš za 10 eur, nebo za 10 000 eur.','Zůstat můžeš za 10 eur, nebo za 1 000 eur.','zůstat v hostelu','zůstat doma','business','cheap_quality'),
(5339,'cz','Ovládá autobus.','Ovládá tramvaj.','ovládání městského autobusu','ovládání dronu','chill','none'),
(5340,'cz','Krabice jede do garáže.','Krabice jede do auta.','otevřená garáž','garáž plná aut','business','none'),
(5341,'cz','Kluk přibíjí prkno.','Kluk natírá prkno.','přibíjení prkna','přibíjení plakátu','chill','none'),
(5342,'cz','Poleva na jazyku. Mňam!','Kečup na jazyku. Mňam!','poleva na jazyku','spálený jazyk od čaje','slang','exclamation'),
(5343,'cz','Holky mají stejné postele.','Holky mají patrové postele.','dvě stejné oddělené postele','dvoulůžkový pokoj v hotelu','chill','none'),
(5344,'cz','Ušili velkou prošívanou deku!','Ušili velkou vlajku!','hotová prošívaná deka','prošívaná deka na posteli','dramatic','exclamation'),
(5345,'cz','Opírá se o zábradlí.','Opírá se o strom.','opírat se o zábradlí mostu','opírat se o zahradní plot','chill','none'),
(5346,'cz','Poplácává se po žaludku.','Poplácává se po hlavě.','plný žaludek','žaludek plný polévky','chill','none'),
(5347,'cz','Provoz se blíží k zastavení.','Vlaky se blíží k zastavení.','zastavení dopravy','zastavení na kafe','chill','none'),
(5348,'cz','Děkuje muži s deštníkem.','Děkuje muži se psem.','poděkovat laskavému cizinci','poděkovat řidiči autobusu','chill','none'),
(5349,'cz','Uděluje už další medaili!','Uděluje už další pohár!','udělení medaile','udělení ceny za píseň','dramatic','exaggeration'),
(5350,'cz','Ve vzduchu nad potokem. Odvaha!','Ve vzduchu nad jezerem. Odvaha!','skok přes potok','plavání v potoce','dramatic','exclamation'),
(5351,'cz','Oranžové pouliční lampy, taková pohoda.','Modré pouliční lampy, taková pohoda.','řada pouličních lamp','rozbitá pouliční lampa','slang','none'),
(5352,'cz','Její frustrace je na 1000 %.','Její frustrace je na 0 %.','frustrace u notebooku','frustrace z učitele','nerd','exaggeration'),
(5353,'cz','Papírování vyhrává.','Papírování ubývá.','věže papírování','papírování na notebooku','dramatic','exaggeration'),
(5354,'cz','Třída ji dobře sleduje.','Třída ho dobře sleduje.','třída v parku','třída ve škole','business','none'),
(5355,'cz','I kočka napodobuje trenéra!','I pes napodobuje trenéra!','trenér v parku','cvičitel psů s pamlsky','gossip','exclamation'),
(5356,'cz','Jóga na střeše při západu slunce? Tohle chci.','Jóga na pláži při západu slunce? Tohle chci.','jóga na střeše','jóga v posilovně','slang','exaggeration'),
(5357,'cz','Pes má nóblovější kočárek než většina miminek.','Kočka má nóblovější kočárek než většina miminek.','nóbl chromovaný kočárek','nóbl kostýmní večírek','dramatic','exaggeration'),
(5358,'cz','Kouká mezi knihami.','Kouká mezi žaluziemi.','koukat škvírou','koukat do knihy','gossip','none'),
(5359,'cz','Hroch se před ní schovává.','Kachna se před ní schovává.','hroch v řece','hroch na molu','chill','guessing'),
(5362,'cz','Nejpraštěnější brýle na ostrově!','Nejpraštěnější klobouk na ostrově!','praštěné brýle se srdíčky','praštěné balonky se srdíčky','dramatic','exaggeration'),
(5363,'cz','Pomáhají běžci.','Pomáhají cyklistovi.','pomáhat vyčerpanému běžci','pomáhat ztracenému turistovi','chill','none'),
(5364,'cz','Asistují jí dva hrdinové!','Asistují jí dvě zdravotní sestry!','asistovat unavené běžkyni','asistovat unavenému řidiči','dramatic','exaggeration'),
(5365,'cz','Sklání zbraň.','Čistí zbraň.','sklánění paintballové zbraně','nabíjení paintballové zbraně','chill','none'),
(5366,'cz','Vzdává se!','Útočí!','vzdává se s rukama nahoře','odevzdává pas','dramatic','exclamation'),
(5367,'cz','Nacpává si pusu!','Nacpává si tašku!','nacpat do sebe cheeseburger','plnit krocana','gossip','exclamation'),
(5368,'cz','Trpí kvůli horku.','Trpí kvůli zimě.','trpět v horku','trpět nachlazením','dramatic','none'),
(5369,'cz','Tvrdý boxer, zalitý potem.','Tvrdý boxer, zalitý deštěm.','tvrdý mladý boxer','tvrdý kus masa','chill','none'),
(5370,'cz','Pádluje na žluté kánoi.','Pádluje na červené kánoi.','pádlování na žluté kánoi','nesení kánoe domů','chill','none'),
(5371,'cz','V květinových girlandách vypadají super.','V papírových korunách vypadají super.','s květinovými girlandami','věšení girlandy doma','slang','none'),
(5372,'cz','Jeho koště shrnuje listí.','Jeho koště shrnuje sníh.','koště a suché listí','koště v kuchyni','chill','none'),
(5373,'cz','Všechno se zvětšuje!','Všechno se zmenšuje!','skákací hrad se zvětšuje','firma expandující do zahraničí','dramatic','exclamation'),
(5374,'cz','Voda je trochu mělká.','Voda je trochu hluboká.','plavání v mělké vodě','mělká miska na polévku','ironic','understatement'),
(5375,'cz','Švihá jako profík.','Plave jako profík.','švihnout golfovou holí','švihnout baseballovou pálkou','flirt','cliche'),
(5376,'cz','Zmáčkl vypínač. Světlo!','Kopl do vypínače. Světlo!','mačkání vypínače světla','výhybka na železnici','dramatic','exclamation'),
(5377,'cz','Sesbírala talíře.','Sesbírala jablka.','sesbírané špinavé talíře','sbírání červených jablek','business','none'),
(5378,'cz','Prostírá stůl.','Nastavuje budík.','prostřít stůl','nastavit budík','business','none'),
(5379,'cz','Krejčí upravil sako.','Krejčí upravil košili.','úprava tmavomodrého saka','úprava cestovních plánů','chill','none'),
(5380,'cz','Dokonce vzal i tu krabici!','Dokonce vzala i tu krabici!','brát věci z krabice','brát krabici do školy','gossip','exclamation'),
(5381,'cz','Káva a pořádná konverzace.','Pivo a pořádná konverzace.','konverzace u kávy','konverzace přes e-mail','chill','none'),
(5382,'cz','Všichni u stolu o tom diskutují naráz!','Všichni v autobuse o tom diskutují naráz!','diskutovat u stolku v kavárně','diskutovat po telefonu','dramatic','exaggeration'),
(5383,'cz','Tolik taxíků na bulváru!','Tolik autobusů na bulváru!','široký bulvár plný taxíků','bulvár lemovaný stromy','slang','exclamation'),
(5384,'cz','Šampioni úplně šílí.','Šampioni jdou domů.','šampioni v pruhovaných dresech','šampion na stupních vítězů','slang','none'),
(5385,'cz','Výměna končí vítězstvím.','Výměna končí prohrou.','vítězství v plážovém volejbale','vítězství v kartách','chill','none'),
(5386,'cz','Trhá smlouvu.','Trhá záclony.','roztrhnout smlouvu napůl','vytrhávat stránky z knihy','business','none'),
(5387,'cz','Sdílejí svůj žal.','Sdílejí svou pizzu.','žal na gauči','žal na pohřbu','dramatic','none'),
(5388,'cz','Vyhrála balíček chipsů!','Vyhrála balíček bonbonů!','chňapnout balíček chipsů','balíček semínek','slang','banter'),
(5389,'cz','On jí uhýbá jak Messi.','Ona mu uhýbá jak Messi.','uhýbat jejím rukám','uhnout fotbalovému míči','slang','exaggeration'),
(5390,'cz','Mladík jezdí na skejtu, fakt cool.','Mladík jezdí na kole, fakt cool.','mladík na skejtu','mladík na kole','slang','none'),
(5391,'cz','Krásný západ slunce, a oni zírají do mobilu.','Krásný západ slunce, a oni zírají do knížky.','zírat do mobilu','zírat na západ slunce','ironic','none'),
(5392,'cz','Křičí hrůzou!','Křičí v autě!','křik hrůzou','křik radostí','dramatic','exclamation'),
(5393,'cz','Tyranosaurus jí vzal klid.','Pes jí vzal klid.','přichází o klid','udržuje si klid','gossip','blaming_someone'),
(5394,'cz','Někdo si to nárokoval jako první!','Nikdo si to nenárokoval jako první!','nárokovat si zamrzlou zemi','nárokovat si ztracenou tašku','gossip','exclamation'),
(5395,'cz','Pomocník z ranče jede podél plotu.','Pomocník z ranče jede podél řeky.','jezdec z ranče','ranč plný dobytka','chill','none'),
(5396,'cz','Oranžové vlajky označují čáru.','Modré vlajky označují čáru.','označování čáry vlajkami','opravování písemky','business','none'),
(5397,'cz','Jedna mohutná vlna, čtyři klidní rackové.','Jedna mohutná vlna, čtyři klidné kachny.','lámající se mohutná vlna','mohutný král','ironic','understatement'),
(5398,'cz','Lidé tvoří lidský řetěz.','Lidé tvoří lidskou věž.','lidský řetěz kolem Země','zlatý řetízek na krk','chill','none'),
(5399,'cz','Dva herci hrají v divadelní hře.','Dva psi hrají v divadelní hře.','divadelní hra v divadle','divadelní hra ve škole','chill','none'),
(5401,'cz','Všichni přemýšlejí.','Všichni spí.','přemýšlení o problému','přemýšlení o počasí','chill','none'),
(5402,'cz','Kontroluje mu krk.','Kontroluje mu uši.','prohlídka krku','šála kolem krku','chill','none'),
(5403,'cz','Kontroluje čas.','Kontroluje mapu.','kontrola času','ztráta času','chill','none'),
(5404,'cz','Je tak chamtivý na toasty!','Je tak chamtivý na dort!','chamtivý jedlík toastů','chamtivý jedlík dortů','dramatic','exclamation'),
(5405,'cz','Batole chodí!','Batole leze!','první krůčky batolete','první slůvka batolete','dramatic','exclamation'),
(5406,'cz','Její prsty u nohou jsou vedle mušle.','Její prsty u nohou jsou vedle kraba.','roztažené prsty u nohou v písku','prsty u nohou v žabce','chill','none'),
(5407,'cz','Všichni teď nutně potřebují na záchod.','Všichni teď nutně potřebují k východu.','fronta na záchod','čištění záchodu','gossip','exaggeration'),
(5408,'cz','Sada vyřešila problém se židlí.','Sada vyřešila problém se stolem.','červená sada nářadí','sada první pomoci','business','none'),
(5409,'cz','Ukazuje zuby.','Ukazuje jazyk.','přední zuby zblízka','chybějící přední zub','chill','none'),
(5410,'cz','Má zelený zubní kartáček.','Má modrý zubní kartáček.','zelený zubní kartáček','elektrický zubní kartáček','chill','none'),
(5411,'cz','On dostane šmouhu, ona spirálky.','On dostane spirálky, ona šmouhu.','spirálka zubní pasty','spirálka šlehačky','gossip','banter'),
(5412,'cz','Řecké sloupy, kanelovaný mramor.','Řecké sloupy, růžový mramor.','obří kanelované mramorové sloupy','sloup v parkovacím domě','nerd','none'),
(5413,'cz','Všude auta. Beznadějné!','Všude kola. Beznadějné!','beznadějná zácpa','beznadějný fotbalový tým','low_iq','exclamation'),
(5414,'cz','Drží se kovového zábradlí.','Drží se kovové brány.','zábradlí lávky','vlak na kolejích','chill','none'),
(5415,'cz','Čeká na červenou.','Čeká na zastávce.','červené světlo na semaforu','červená stopka','chill','none'),
(5416,'cz','Tu lokomotivu miluje.','Tu helikoptéru miluje.','oranžová elektrická lokomotiva','oranžová parní lokomotiva','gossip','guessing'),
(5417,'cz','Tramvaj skončí v depu.','Tramvaj skončí v muzeu.','tramvaje v depu','autobusy v depu','chill','none'),
(5418,'cz','Interiér je celý ze dřeva.','Interiér je celý z plastu.','dřevěný interiér tramvaje','moderní interiér auta','chill','none'),
(5419,'cz','Stihne každý přesun.','Zmešká každý přesun.','přesun na trajekt','bankovní převod','chill','none'),
(5420,'cz','Nastupuje na bílé plavidlo.','Nastupuje na červené plavidlo.','malé osobní plavidlo','obří nákladní plavidlo','chill','none'),
(5421,'cz','Odpadky jsou všude!','Květiny jsou všude!','koš plný odpadků','koš plný květin','dramatic','exaggeration'),
(5422,'cz','Recyklace jak LeBron.','Recyklace jak Messi.','házení do košů na recyklaci','recyklace starého oblečení','slang','exaggeration'),
(5423,'cz','Jeho batoh je na celosvětovém turné.','Jeho batoh zůstává v jednom městě.','celosvětové cestování','celosvětová telefonní síť','chill','none'),
(5424,'cz','Podepsali smlouvu.','Roztrhali smlouvu.','podání ruky nad smlouvou','trhání smlouvy','business','none'),
(5425,'cz','Obchod je domluvený.','Obchod je zrušený.','podpis velkého obchodu','obchod na trhu','business','none'),
(5426,'cz','Obě delegace mají dohodu.','Žádná delegace nemá dohodu.','setkání dvou delegací','delegace na letišti','business','none'),
(5427,'cz','Obálka má červenou pečeť.','Obálka má modrou pečeť.','červená vosková pečeť','tuleň na pláži','chill','none'),
(5428,'cz','Náklaďák veze náklad.','Vlak veze náklad.','náklad na velkém kamionu','náklad na lodi','chill','none'),
(5429,'cz','Důvěřuje jim, se zavřenýma očima.','Důvěřuje jim, s otevřenýma očima.','důvěřovat týmu, že chytí','důvěřovat cizinci na internetu','chill','none'),
(5430,'cz','Na silničce je rychlá.','Na skejtu je rychlá.','rychlá jízda tunely','rychlá jízda městem','chill','none'),
(5431,'cz','Letí v balonu.','Letí v letadle.','balon nad skalami','balonek na párty','chill','none'),
(5432,'cz','Napaluje toho chudáka!','Napaluje toho chudáka psa!','napálit zákazníka','napálit učitele','dramatic','exclamation'),
(5433,'cz','Zapíná světla.','Vypíná světla.','zapnout světelný řetěz','zapnout televizi','chill','none'),
(5434,'cz','Plýtvá elektřinou!','Plýtvá papírem!','spotřeba spousty elektřiny','elektřina ze solárních panelů','dramatic','exaggeration'),
(5436,'cz','Tým kroutí těsto.','Tým krájí těsto.','kroucení provazu z těsta','kroucení provazu z vlny','business','none'),
(5437,'cz','Párty na nádvoří!','Párty v kuchyni!','párty na nádvoří se světýlky','školní nádvoří o přestávce','slang','exclamation'),
(5438,'cz','Miska červené náplně.','Miska zelené náplně.','červená ovocná náplň','plomba u zubaře','chill','none'),
(5439,'cz','Čtyři chlapi, jeden šedý deštník!','Čtyři chlapi, jeden červený deštník!','šedé deštivé město','šedý zimní kabát','dramatic','exclamation'),
(5440,'cz','Den s draky se synovcem.','Den s draky se psem.','pouštění draků se synovcem','rybaření se synovcem','chill','none'),
(5441,'cz','Strýc ji nechal vyhrát.','Strýc ho nechal vyhrát.','páka se strýcem','box se strýcem','gossip','guessing'),
(5442,'cz','Bojuje s každým rukávem!','Bojuje s každým zipem!','vytahování rukou z rukávů','vyhrnování rukávů','dramatic','exaggeration'),
(5443,'cz','Ulici naplňuje solidarita.','Stadion naplňuje solidarita.','řetěz solidarity','řetězec obchodů','dramatic','none'),
(5444,'cz','Spolupracují na mapě.','Spolupracují na autě.','spolupracovat na puzzle','spolupracovat s policií','chill','none'),
(5445,'cz','Jeho deštník je teď nepoužitelný.','Jeho aktovka je teď nepoužitelná.','nepoužitelný deštník','nepoužitelný deštník za slunce','dramatic','none'),
(5446,'cz','Kopce jsou mlhavé.','Kopce jsou slunné.','mlhavé kopce nad jezerem','zamžené oči na svatbě','chill','none'),
(5447,'cz','Tahle silnice je hodně odlehlá.','Tahle silnice je hodně rušná.','odlehlá pouštní silnice','dálkové ovládání','chill','none'),
(5448,'cz','Billboardy na každé zdi!','Obrazy na každé zdi!','obří osvětlené billboardy','billboard na poli','dramatic','exaggeration'),
(5449,'cz','Konečně stojí ve dveřním otvoru.','Konečně stojí na zahradě.','otevřený kamenný dveřní otvor','dveřní otvor se závěsem','chill','none'),
(5450,'cz','Šetří peníze: odpojuje zařízení ze zásuvky.','Šetří peníze: zapojuje zařízení do zásuvky.','odpojování všech zařízení','nabíjení všech zařízení','business','none'),
(5451,'cz','Jedna injekce a je z něj Hulk!','Jedna pilulka a je z něj Hulk!','injekce do ruky','injekce do nohy','slang','exaggeration'),
(5452,'cz','Klidné jezero v mlze.','Klidná pláž v mlze.','klidné horské jezero','klidná horská vesnice','chill','none'),
(5453,'cz','Plní modrou vázu.','Plní červenou vázu.','dávání květin do vázy','rozbití vázy na květiny','chill','none'),
(5454,'cz','Inkoust stříká po celém pasu.','Voda stříká po celém pasu.','kapky černého inkoustu','modrý inkoust na prstech','slang','exaggeration'),
(5455,'cz','Dostal schválení!','Nedostal schválení!','schválení pasu','schválení od rodičů','dramatic','exclamation'),
(5456,'cz','Dostal povolení.','Nedostal povolení.','povolení k cestě','povolení k parkování','chill','none'),
(5457,'cz','Návštěvníci přinesli dort.','Návštěvníci přinesli psa.','návštěvníci s dortem','návštěvníci v muzeu','chill','none'),
(5458,'cz','Vitamin šumí jako šílený!','Mléko šumí jako šílené!','šumivá vitaminová tableta','tající vitaminový bonbon','slang','exclamation'),
(5459,'cz','Láva na každém svahu.','Sníh na každém svahu.','zářící proudy lávy','láva v lampě','dramatic','none'),
(5460,'cz','Kolotoč s hrnky způsobuje nevolnost!','Ruské kolo způsobuje nevolnost!','nevolnost po jízdě','nevolnost na lodi','dramatic','exclamation'),
(5461,'cz','Všichni vhazují hlasovací lístek.','Všichni vhazují dopis.','vhazování složeného hlasovacího lístku','čtení dlouhého hlasovacího lístku','chill','none'),
(5462,'cz','Demokracie v jedné plastové krabici.','Demokracie v jedné dřevěné krabici.','demokracie v akci','demokracie v televizi','ironic','understatement'),
(5463,'cz','Píše deník na moři. Pohodička.','Píše deník v posteli. Pohodička.','psaní cestovního deníku','čtení vědeckého časopisu','slang','none'),
(5465,'cz','Pas změřen. Opasek padne.','Paže změřena. Opasek padne.','měření jejího pasu','zástěra kolem pasu','business','none'),
(5466,'cz','Číšník vypadá velmi formálně.','Číšník vypadá velmi neformálně.','formální uniforma číšníka','formální stížnost','chill','none'),
(5467,'cz','Kluk se probouzí v šoku!','Pes se probouzí v šoku!','probouzení na palandě','probouzení ve stanu','dramatic','exclamation'),
(5468,'cz','Reklamní poutače září.','Stromy září.','obří zářící reklamy','značka stop','chill','none'),
(5469,'cz','Tenhle chodec dal 10 000 kroků!','Tenhle chodec dal 100 kroků!','chodec s trekovými holemi','chodec v horách','gossip','exclamation'),
(5471,'cz','Podle bublinky je to vodorovné.','Podle bublinky je to křivé.','vodorovný rám obrazu','vodorovná silnice','nerd','none'),
(5472,'cz','Bankovky vypadávají.','Klíče vypadávají.','bankovky padající z peněženky','bankovky v bankomatu','chill','none'),
(5474,'cz','Třídí své mince.','Třídí své karty.','mince z peněženky','mince ve fontáně','chill','none'),
(5475,'cz','Za nimi jede tank!','Za nimi jede kůň!','tank v kouři','nádrž plná vody','dramatic','exclamation'),
(5476,'cz','Jde přes trosky.','Jde přes květiny.','chůze troskami','zametání trosek','chill','none'),
(5477,'cz','Nejlepší bitva o sněhovou pevnost ever.','Nejlepší bitva o pískovou pevnost ever.','pevnost ze sněhu','pevnost z kamene','slang','exaggeration'),
(5478,'cz','Její věci na ni útočí!','Její knížky na ni útočí!','vypadávající věci','věci pod postelí','dramatic','exaggeration'),
(5480,'cz','Jeho úkol je věž z talířů.','Jeho úkol je věž z bot.','těžký úkol v kuchyni','úkol u počítače','low_iq','none'),
(5481,'cz','Růžové vlasy, bílá košile. Uf.','Růžové vlasy, růžová košile. Uf.','dlouhé zářivě růžové vlasy','růžová pračka','gossip','guessing'),
(5482,'cz','Pes si dává koupel. Wellness den!','Kočka si dává koupel. Wellness den!','pes v koupeli','pes v bazénu','slang','cliche'),
(5483,'cz','Zkoumá pláž. Koho asi hledá?','Zkoumá les. Koho asi hledá?','zkoumání pobřeží','skenování čárového kódu','gossip','guessing'),
(5484,'cz','Upřeně hledí na ohňostroj.','Upřeně hledí na moře.','upřeně hledět na oblohu','upřeně hledět na obrazovku','chill','none'),
(5485,'cz','Používá konev.','Používá zahradní hadici.','zelená konev','prázdná konev','chill','none'),
(5486,'cz','Zalévá květináč.','Natírá květináč.','květináč na parapetu','rozbitý květináč','chill','none'),
(5487,'cz','Surfování uvnitř vlny je pecka!','Potápění uvnitř vlny je pecka!','surfování na obří vlně','surfování po internetu','slang','exclamation'),
(5488,'cz','Tohle rozloučení trvá věčnost.','Tohle přivítání trvá věčnost.','rozloučení v přístavu','rozloučení na letišti','dramatic','exaggeration'),
(5489,'cz','Každý kabát nosí tak dobře.','Každý oblek nosí tak dobře.','nosí klobouk s pery','nosí slaměný klobouk','flirt','none'),
(5490,'cz','Vytrhl obří plevel!','Vytrhl obří mrkev!','vytrhávání plevele','plevel v chodníku','dramatic','exaggeration'),
(5491,'cz','Je tu tak vítaný!','Je tu tak osamělý!','vítaný host','vítaná pauza od práce','dramatic','exclamation'),
(5492,'cz','Kolo má tenké paprsky.','Kolo nemá žádné paprsky.','tenké kovové paprsky','tenké dřevěné paprsky','chill','none'),
(5493,'cz','Miluje každý náboj, který uvidí.','Miluje každé auto, které uvidí.','náboj kola','dopravní uzel města','gossip','guessing'),
(5494,'cz','Zdravotně postižený muž jede rychle.','Zdravotně postižený muž jede pomalu.','zdravotně postižený vozíčkář','zdravotně postižený muž o berlích','chill','none'),
(5495,'cz','Drb v knihovně!','Drb v kuchyni!','předávání drbu','šíření drbu na internetu','dramatic','exclamation'),
(5496,'cz','Upravuje mu kravatu.','Upravuje mu klobouk.','úprava uzlu kravaty','seřizování hodinek','flirt','none'),
(5497,'cz','Kandidát vyhrál!','Kandidát prohrál!','vítězný kandidát','poražený kandidát','dramatic','exclamation'),
(5498,'cz','Každé okno, nový výhled!','Každé dveře, nový výhled!','vyklánění z okna','mytí okna','slang','exaggeration'),
(5499,'cz','Žena v červeném se točí.','Žena v červeném běhá.','žena zalévá květiny','žena kupuje květiny','chill','none'),
(5500,'cz','Čerstvé řezivo leží na hromadě.','Čerstvé řezivo leží na náklaďáku.','hromada čerstvého řeziva','náklaďák čerstvého řeziva','chill','none'),
(5501,'cz','Pracuje v těžkém průmyslu.','Pracuje v květinářství.','továrna těžkého průmyslu','turistický průmysl','business','none'),
(5502,'cz','Krabice se chystají ke skladování.','Krabice se chystají do popelnice.','krabice ke skladování','úložiště v telefonu','business','none'),
(5503,'cz','Je v poloze prkna.','Je v lotosové poloze.','vysoká poloha prkna','pozice ve firmě','chill','none'),
(5504,'cz','Posílá dopis.','Posílá balík.','posílání ručně psaného dopisu','posílání SMS','chill','none'),
(5505,'cz','Studuje rentgenový film.','Studuje papírovou mapu.','rentgenový film','film v kině','nerd','none'),
(5507,'cz','V zoo se skvěle baví.','Na pláži se skvěle baví.','den v zoo','den na farmě','chill','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
