-- rollback for mismatch_fix/part3_en; NOT run. Restores the backed-up values where the row still holds
-- exactly what this pass wrote.
begin;
update exercise_localizations l set intro_text = v.n_intro_text, correct_answer = v.n_correct_answer, distractor_1 = v.n_distractor_1, distractor_2 = v.n_distractor_2, full_sentence = v.n_full_sentence, chunks = v.n_chunks, correct_alternative = v.n_correct_alternative
from (values
(1865,208,'en','She has not looked down at her notes once, so she ... this presentation for weeks.'::text,'must have been practising'::text,'must be practising'::text,'can have been practising'::text,'She has not looked down at her notes once, so she must have been practising this presentation for weeks.'::text,'["She has not looked down", "at her notes once,", "so she", "must have been practising", "this presentation", "for weeks."]'::jsonb,'[]'::jsonb,'Her hands are shaking on the clicker, so she ... as calm as she sounds.'::text,'can''t be'::text,'mustn''t be'::text,'shouldn''t be'::text,'Her hands are shaking on the clicker, so she can''t be as calm as she sounds.'::text,'["Her hands are shaking", "on the clicker,", "so she", "can''t be", "as calm", "as she sounds."]'::jsonb,'[]'::jsonb),
(198992,22111,'en','He circles one date in ... schedule with a marker.'::text,'his'::text,'her'::text,'their'::text,'He circles one date in his schedule with a marker.'::text,'["He circles", "one date", "in his schedule", "with a marker."]'::jsonb,'[]'::jsonb,'He circles one date in ... schedule.'::text,'his'::text,'her'::text,'their'::text,'He circles one date in his schedule.'::text,'["He circles", "one date", "in his schedule."]'::jsonb,'[]'::jsonb)
) v(id, eid, lang, n_intro_text, n_correct_answer, n_distractor_1, n_distractor_2, n_full_sentence, n_chunks, n_correct_alternative, o_intro_text, o_correct_answer, o_distractor_1, o_distractor_2, o_full_sentence, o_chunks, o_correct_alternative)
where l.id = v.id and l.exercise_id = v.eid and l.language_code = v.lang and l.intro_text is not distinct from v.o_intro_text and l.correct_answer is not distinct from v.o_correct_answer and l.distractor_1 is not distinct from v.o_distractor_1 and l.distractor_2 is not distinct from v.o_distractor_2 and l.full_sentence is not distinct from v.o_full_sentence and l.chunks is not distinct from v.o_chunks and l.correct_alternative is not distinct from v.o_correct_alternative
returning l.id;
commit;
