begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(673,'es','Su jersey ha encogido. ¡Y mucho!','Su bufanda ha encogido. ¡Y mucho!','un jersey rojo encogido','encogerse de miedo','dramatic','exclamation'),
(674,'es','Está enferma y en casa.','Está enferma y en el trabajo.','enferma en el sofá','enferma en una cama de hospital','chill','none'),
(675,'es','Un costado del barco ya está listo.','Un costado de la casa ya está listo.','pintando el costado del barco','el costado de un lago','business','none'),
(676,'es','Están haciendo turismo en Venecia.','Están haciendo turismo en París.','turismo en góndola','turismo en autobús','chill','none'),
(678,'es','La seda no se queda en su sitio.','El gato no se queda en su sitio.','seda verde brillante','una corbata de seda','ironic','none'),
(679,'es','¡La plata vuelve a brillar!','¡El oro vuelve a brillar!','puliendo plata antigua','pintura plata en un coche','dramatic','exclamation'),
(680,'es','El cantante se lo está pasando en grande.','El cantante está almorzando.','un cantante en un estudio','un cantante en el escenario','chill','none'),
(681,'es','¡Cantando a todo pulmón en el coche!','¡Cantando a todo pulmón en la ducha!','cantando en el coche','cantando en un escenario','dramatic','exclamation'),
(683,'es','¡El fregadero es una montaña de espuma!','¡La bañera es una montaña de espuma!','un fregadero lleno de espuma','un fregadero lleno de juguetes','low_iq','exaggeration'),
(684,'es','¡Su hermana por fin está en casa!','¡Su hermano por fin está en casa!','abrazando a su hermana','peleándose con su hermana','dramatic','exclamation'),
(685,'es','Por fin, la talla correcta.','Por fin, los zapatos correctos.','la talla de sombrero correcta','la talla de zapato correcta','chill','none'),
(687,'es','¿Monopatín al atardecer? Qué guay.','¿Bici al atardecer? Qué guay.','montando en monopatín','un monopatín en una tienda','slang','none'),
(688,'es','Ella cuida su piel.','Ella cuida a su perro.','poniéndose crema en la piel','lavándose la piel con jabón','chill','none'),
(689,'es','¡Qué falda, y qué vuelta!','¡Qué sombrero, y qué vuelta!','una falda plisada amarilla','una falda larga negra','flirt','exclamation'),
(690,'es','El cielo es enorme.','El mar es enorme.','mirando al cielo','un cielo lleno de estrellas','chill','none'),
(691,'es','Está vigilando su coche. Fatal.','Está lavando su coche. Fatal.','vigilando un coche aparcado','vigilando un banco','ironic','none'),
(692,'es','¿Dormir? Es un crack.','¿Leer? Es un crack.','dormir bajo una manta','dormir en una tienda de campaña','slang','cliche'),
(693,'es','Cinco minutitos más. Muy somnoliento.','Cinco minutitos más. Muy despierto.','un viaje nocturno somnoliento','una clase matinal somnolienta','ironic','bad_excuse'),
(694,'es','Está cortando un tomate en rodajas.','Está cortando un pepino en rodajas.','cortar un tomate en rodajas finas','cortar una tarta','chill','none'),
(695,'es','Pronto todos están sonriendo.','Pronto todos están llorando.','sonriendo en un ferry','sonriendo a la cámara','chill','none'),
(696,'es','¡Se ha perdido entre el humo!','¡Se ha perdido entre la nieve!','una nube de humo gris','humo saliendo de una chimenea','dramatic','exaggeration'),
(698,'es','El smoothie está morado a tope.','El smoothie está verde a tope.','un smoothie espeso de frutos rojos','un smoothie verde','slang','none'),
(699,'es','¡Contrabandeó queso delante del guardia!','¡Contrabandeó vino delante del guardia!','contrabandeando queso en la paja','contrabandeando queso en un barco','gossip','exclamation'),
(700,'es','El caracol no tiene ninguna prisa.','La rana no tiene ninguna prisa.','un caracol en una hoja','un caracol en un plato','chill','understatement'),
(701,'es','La serpiente está sobre una roca negra.','La serpiente está sobre una roca blanca.','una serpiente en la arena','una serpiente en la hierba','chill','none'),
(702,'es','Zapatillas puestas, ahora las escaleras.','Sandalias puestas, ahora las escaleras.','atando unas zapatillas turquesa','limpiando unas zapatillas turquesa','slang','none'),
(704,'es','¡Estornudó y se le voló el gorro!','¡Estornudó y se le voló el zapato!','estornudando por los dientes de león','estornudando por un gato','dramatic','exaggeration'),
(705,'es','No para de estornudar.','No para de cantar.','estornudando en el codo','estornudando en un pañuelo','dramatic','none'),
(706,'es','¿Nieve en la lengua? ¡Qué rica!','¿Lluvia en la lengua? ¡Qué rica!','atrapando nieve con la lengua','quitando nieve de un coche','slang','exclamation'),
(707,'es','Qué snowboard naranja más guapo, tío.','Qué snowboard azul más guapo, tío.','abrochándose el snowboard','un snowboard en una tienda','slang','none'),
(708,'es','¿Manos llenas de barro? ¡Hora del jabón!','¿Pies llenos de barro? ¡Hora del jabón!','una pastilla de jabón','un bote de jabón','slang','exclamation'),
(710,'es','Una nube de espuma en sus manos.','Una nube de espuma en su cabeza.','una enorme nube de espuma','espuma en una lavadora','chill','exaggeration'),
(711,'es','Móvil al 1 %. ¡Enchufe encontrado!','Móvil al 50 %. ¡Enchufe encontrado!','un enchufe escondido en la pared','un portalámparas','dramatic','exclamation'),
(712,'es','Le da miedo su refresco.','Le da miedo su bocadillo.','una lata de refresco de naranja','un vaso de refresco de cola','low_iq','guessing'),
(713,'es','¡Anda, hola! ¡Una lombriz en la tierra!','¡Anda, hola! ¡Una moneda en la tierra!','plantando en tierra oscura','tierra en la alfombra','dramatic','exclamation'),
(714,'es','¡El soldado vuelve a estar en casa!','¡El soldado vuelve a estar en el mar!','un soldado volviendo a casa','un soldado saliendo de casa','dramatic','exclamation'),
(715,'es','Alguien le ha dejado un café.','Alguien le ha dejado una pizza.','una nota de alguien','la tarjeta de cumpleaños de alguien','chill','none'),
(716,'es','Come con una cuchara sopera.','Come con palillos.','comiendo con cuchara sopera','removiendo con una cuchara sopera','chill','none'),
(717,'es','¡La sopa está ardiendo!','¡La sopa está helada!','sopa de tomate caliente','sopa de tomate fría','dramatic','exclamation'),
(718,'es','Los gansos vuelan hacia el sur.','Los gansos caminan hacia el sur.','siguiendo a los pájaros al sur','conduciendo hacia el sur','chill','none'),
(719,'es','¡Hala, qué vacío está el espacio!','¡Hala, qué vacío está el mar!','estrellas en el espacio','un espacio de aparcamiento','dramatic','exclamation'),
(720,'es','Esa especia es muy fuerte.','Esa especia es muy verde.','especia roja en un cono','un bote de especia seca','chill','none'),
(723,'es','El médico le enseña la columna vertebral, hueso a hueso.','El médico le enseña el cráneo, hueso a hueso.','huesos de la columna vertebral','el lomo de un libro','nerd','none'),
(724,'es','¡Cada salpicadura es más grande!','¡Cada salpicadura es más pequeña!','una salpicadura enorme','una salpicadura de leche','dramatic','exclamation'),
(726,'es','Llegó la primavera, fuera chaqueta.','Llegó el invierno, fuera chaqueta.','primavera bajo los cerezos','lluvia de primavera en la ciudad','chill','none'),
(727,'es','¡Esprintó hasta la meta!','¡Caminó hasta la meta!','esprintando hacia la línea de meta','esprintando para pillar el autobús','dramatic','exclamation'),
(729,'es','La ardilla está planificando el invierno.','El conejo está planificando el invierno.','una ardilla con una bellota','una ardilla con una pizza','business','guessing'),
(730,'es','La plantilla posa junta.','La plantilla come junta.','la plantilla de un restaurante trabajando','la plantilla de un tren','chill','none'),
(731,'es','Le está poniendo un sello.','Le está poniendo una moneda.','un sello en un sobre','un sello en un pasaporte','chill','none'),
(733,'es','Dos Estados firmaron un tratado.','Tres Estados firmaron un tratado.','dos Estados firmando un tratado','un estado de caos','business','none'),
(734,'es','El perro quiere ese filete.','El gato quiere ese filete.','un filete rosado por dentro','un filete en el congelador','gossip','guessing'),
(735,'es','¡El vapor le empañó las gafas!','¡La lluvia le empañó las gafas!','una nube de vapor','una nube de humo','dramatic','exclamation'),
(736,'es','¡Hola, nuevo hermanastro!','¡Hola, nueva hermanastra!','conociendo a un nuevo hermanastro','peleando con un hermanastro','dramatic','exclamation'),
(737,'es','El padrastro del año arregló la bici.','El padrastro del año arregló el coche.','un padrastro arreglando una bici','un padrastro en una boda','gossip','exaggeration'),
(738,'es','Dibujó un corazón en una nota adhesiva.','Dibujó una estrella en una nota adhesiva.','una nota adhesiva con corazón','notas adhesivas en una pantalla','flirt','none'),
(739,'es','Paró a por pizza. Las normas son las normas.','Paró a por sushi. Las normas son las normas.','parar a por pizza','parar a echar gasolina','ironic','cliche'),
(740,'es','¡El cronómetro debe de estar roto!','¡El móvil debe de estar roto!','pulsando un cronómetro','pulsando la cámara del móvil','ironic','bad_excuse'),
(741,'es','Gran tormenta fuera, té dentro.','Gran solazo fuera, té dentro.','viendo una tormenta con té','caminando bajo una tormenta','chill','none'),
(742,'es','Los cuatro fuegos de la cocina están encendidos.','Solo un fuego de la cocina está encendido.','cuatro fuegos en una cocina','un hornillo de camping','business','none'),
(743,'es','La carretera es recta a tope.','La carretera tiene curvas a tope.','una fila recta de ladrillos','una respuesta directa','slang','none'),
(744,'es','Conoció a un desconocido con paraguas.','Conoció a un desconocido con un perrazo.','un desconocido con paraguas','un desconocido con bici','gossip','none'),
(746,'es','¡Están saltando el arroyo!','¡Están saltando la valla!','saltando un arroyo','nadando en un arroyo','dramatic','exclamation'),
(747,'es','Solo es un poquito de estrés.','Solo es un poquito de lluvia.','estrés en la oficina','estrés en el gimnasio','ironic','understatement'),
(749,'es','Se están estirando juntos.','Están bailando juntos.','estirarse antes de correr','estirar una goma elástica','chill','none'),
(750,'es','El cordel sujeta la caja con firmeza.','El cordel sujeta la bolsa con firmeza.','una caja atada con cordel','una cuerda de guitarra','business','none'),
(751,'es','¿Ir conjuntada? No es su estilo.','¿Botas moradas? No es su estilo.','su propio estilo atrevido','un estilo de música','gossip','guessing'),
(752,'es','¡El azúcar salvó su café!','¡La leche salvó su café!','azúcar en café solo','azúcar sobre una tarta','dramatic','exaggeration'),
(753,'es','Ese traje azul le queda genial.','Ese traje gris le queda genial.','probándose un traje azul','lavando un traje azul','flirt','none'),
(754,'es','Su amiga la está apoyando.','Su amiga la está ignorando.','apoyando a su amiga','apoyando a un equipo de fútbol','chill','none'),
(755,'es','Aquí cada superficie es lisa.','Aquí cada superficie es rugosa.','una superficie lisa y brillante','una superficie llena de arañazos','chill','none'),
(757,'es','¡Un cachorro en una caja! ¡Qué sorpresa!','¡Un gatito en una caja! ¡Qué sorpresa!','una sorpresa en una caja','una fiesta sorpresa en casa','dramatic','exclamation'),
(758,'es','El cisne se está acicalando.','El cisne se está comiendo un pez.','un cisne en un lago','un cisne en la hierba','chill','none'),
(759,'es','Lluvia fuera, jersey dentro.','Sol fuera, jersey dentro.','poniéndose un jersey calentito','tejiendo un jersey calentito','chill','none'),
(760,'es','¡Oh, no! ¡Se le está hinchando el tobillo!','¡Oh, no! ¡Se le está hinchando la muñeca!','un tobillo hinchándose','una muñeca hinchándose','dramatic','none'),
(761,'es','Tiene una gran hinchazón en el pie.','Tiene una gran hinchazón en la mano.','una hinchazón en el tobillo','una hinchazón en la rodilla','chill','none'),
(762,'es','No, no, a lo mejor... ¡esa camiseta!','No, no, a lo mejor... ¡esa chaqueta!','poniéndose una camiseta turquesa','doblando una camiseta turquesa','slang','none'),
(763,'es','El mantel sale volando.','La cortina sale volando.','lanzando un mantel al aire','un mantel con manchas de vino','chill','none'),
(764,'es','Está dibujando en una tableta.','Está dibujando en una servilleta.','dibujando en una tableta','una tableta de chocolate','chill','none'),
(766,'es','¡Este tatuaje es para siempre!','¡Esta pegatina es para siempre!','un tatuaje de pájaro recién hecho','un tatuaje en la pierna','dramatic','exclamation'),
(767,'es','¡Las hojas de té están bailando!','¡Las bolsitas de té están bailando!','sirviendo té de menta','té con leche','dramatic','exclamation'),
(768,'es','El equipo rema al unísono.','El equipo corre al unísono.','un equipo de remo al amanecer','un equipo en una oficina','business','none'),
(769,'es','Las cucharillas son diminutas.','Las cucharillas son enormes.','removiendo con una cucharilla','una cucharilla de azúcar','chill','none'),
(770,'es','¡Se lanzó a por una pelota de tenis!','¡Se lanzó a por una pelota de golf!','tirándose en un partido de tenis','tenis en pista de hierba','dramatic','exclamation'),
(771,'es','La terminal es enorme.','La terminal es diminuta.','una enorme terminal de cristal','una pequeña terminal de autobuses','chill','none'),
(772,'es','La terapia está ayudando al cliente.','El yoga está ayudando al cliente.','una sesión de terapia','una sesión de yoga','business','none'),
(773,'es','¡Su termómetro se ha vuelto loco!','¡Su reloj se ha vuelto loco!','un termómetro en la boca','un termómetro en la pared','slang','exaggeration'),
(775,'es','¡Tanto pensar para un solo movimiento!','¡Tanto pensar para un solo gol!','pensar a fondo en el ajedrez','pensar a fondo en las cartas','slang','exclamation'),
(776,'es','Una gota para tanta sed.','Una galleta para tanta sed.','una sed terrible','sed de aventura','ironic','understatement'),
(778,'es','¡Un hilo de kilómetros de largo!','¡Una cuerda de kilómetros de largo!','un largo hilo rojo','un hilo de chat','dramatic','exaggeration'),
(779,'es','Esta nutria quiere una siesta.','Este gato quiere una siesta.','una nutria dormilona','una nutria en un río','chill','guessing'),
(780,'es','¡Los gatos están de pie como soldados!','¡Los perros están de pie como soldados!','gatos de pie en una cama','gatos de pie en una mesa','dramatic','exaggeration'),
(781,'es','Uno, dos, tres... ¡trueno!','Uno, dos, tres... ¡arcoíris!','esperando el trueno','truenos en un estadio de fútbol','dramatic','exclamation'),
(782,'es','Segundo intento, corbata perfecta.','Segundo intento, tarta perfecta.','anudando una corbata granate','comprando una corbata granate','business','none'),
(783,'es','¡Tigre mojado, mal rollo!','¡León mojado, mal rollo!','un tigre en un río','un tigre en un árbol','slang','guessing'),
(784,'es','Está inclinando el paraguas.','Está cerrando el paraguas.','inclinando el paraguas','inclinando la cabeza','chill','none'),
(785,'es','Está consultando el horario.','Está consultando el periódico.','un gran horario de trenes','un horario escolar','business','none'),
(786,'es','Está un poco cansado.','No está nada cansado.','cansado después del trabajo','cansado de esperar','ironic','understatement'),
(787,'es','Ella no juzga a su amiga.','Ella no juzga a su perro.','no juzgar a una amiga','juzgar un concurso de cocina','chill','none'),
(788,'es','Después quiere calentar lo suyo en el microondas.','Después quiere calentar lo suyo en el horno.','calentar fideos en el microondas','calentar leche en el microondas','gossip','none'),
(789,'es','¡La tostadora ha disparado la tostada!','¡El horno ha disparado la tostada!','una tostadora saltando','un horno tostador','slang','exaggeration'),
(790,'es','Buen trabajo con ese tomate.','Buen trabajo con esa cebolla.','cortando un tomate maduro','plantando un tomate','flirt','none'),
(791,'es','Primero cogió la herramienta equivocada.','Primero cogió la herramienta correcta.','eligiendo la herramienta correcta','una herramienta de jardín','chill','none'),
(792,'es','¡Demasiada pasta de dientes!','¡Demasiado champú!','una torre de pasta de dientes','un tubo de pasta de dientes','dramatic','exaggeration'),
(793,'es','Puso la última piedra en la cima.','Puso la última concha en la cima.','una piedra en la cima','el techo de un coche','chill','none'),
(794,'es','¡El chico ganó el torneo!','¡El marinero ganó el torneo!','un torneo de pulsos','un torneo de ajedrez','dramatic','exclamation'),
(795,'es','¡El perro también tiene toalla!','¡El gato también tiene toalla!','secarse con una toalla','tumbarse en una toalla de playa','dramatic','exclamation'),
(797,'es','¡Están compitiendo en la pista!','¡Están compitiendo en la piscina!','una pista de atletismo roja','una vía de tren','dramatic','exclamation'),
(798,'es','¡Banda de chándal en el callejón!','¡Banda de chándal en la playa!','chándales turquesa a juego','chándales en una pista de atletismo','slang','exclamation'),
(800,'es','Entrenamiento hecho, piernas muertas.','Partido hecho, piernas muertas.','entrenamiento bajo los focos','adiestramiento de un cachorro','slang','exaggeration'),
(801,'es','¡Está volando en una cama elástica!','¡Está volando en una cama!','saltando en una cama elástica','escondiéndose bajo una cama elástica','dramatic','exaggeration'),
(802,'es','Hace de LeBron con una papelera.','Hace de LeBron con una bañera.','una papelera como canasta','la tapa de una papelera','slang','guessing'),
(804,'es','Le flipa viajar.','Odia viajar a muerte.','viajar en avión','viajar en autobús','slang','none'),
(805,'es','¡Viaje en tren y justo a tiempo!','¡Viaje en autobús y justo a tiempo!','de viaje por los Alpes','viaje en barco','dramatic','exclamation'),
(806,'es','Lleva bandejas como una pro.','Lleva cajas como una pro.','una bandeja en alto','una bandeja en el suelo','slang','cliche'),
(807,'es','La cinta de correr casi gana, tío.','La bici casi gana, tío.','corriendo en una cinta de correr','caminando en una cinta de correr','slang','guessing'),
(808,'es','¡El árbol es enorme!','¡La roca es enorme!','un árbol viejo y enorme','una casa en el árbol','dramatic','exclamation'),
(809,'es','¡Hasta el corgi sigue la tendencia!','¡Hasta el gato sigue la tendencia!','siguiendo la tendencia del gorro amarillo','empezando una nueva tendencia','gossip','exaggeration'),
(811,'es','¡Trofeo arriba, confeti abajo!','¡Medalla arriba, confeti abajo!','levantando un trofeo dorado','limpiando un trofeo dorado','slang','exclamation'),
(812,'es','Confianza total: ¡se suelta de la roca!','Confianza total: ¡se suelta de la cuerda!','confianza en su compañero','confianza en su suerte','dramatic','exclamation'),
(813,'es','El pavo posa como una estrella.','El ganso posa como una estrella.','un pavo sobre la paja','un pavo en un plato','chill','exaggeration'),
(814,'es','Está apagando el ventilador.','Está apagando la tele.','apagar la luz','salir de la carretera','chill','none'),
(815,'es','La tortuga ya está en el mar.','La tortuga ya está en una piscina.','una tortuga en la playa','una tortuga en un acuario','chill','none'),
(816,'es','Le queda genial el esmoquin.','Le queda genial el chándal.','poniéndose un esmoquin','alquilando un esmoquin','flirt','none'),
(818,'es','¡Su tecleo es rapidísimo!','¡Su lectura es rapidísima!','tecleo rápido','tecleando un mensaje','slang','exclamation'),
(819,'es','Bonito paraguas. ¿Hay sitio para mí?','Bonito coche. ¿Hay sitio para mí?','compartiendo paraguas','un paraguas en la playa','flirt','banter'),
(821,'es','De vuelta en casa: ¡hora de la ropa interior!','De vuelta en casa: ¡hora del pijama!','quedándose en ropa interior','comprando ropa interior nueva','slang','exclamation'),
(823,'es','La pantalla muestra las cifras.','La pantalla muestra el tiempo.','señalando la pantalla','limpiando la pantalla','business','none'),
(825,'es','Al perro también le encanta la vista.','Al gato también le encanta la vista.','vista de picos rocosos','vista al mar','low_iq','guessing'),
(826,'es','Están filmando en una oficina.','Están filmando en un bosque.','filmando con un dolly','filmando una boda','chill','none'),
(827,'es','Aquí hay muchos animales.','Aquí hay dos animales.','animales en un libro de cuentos','animales en un zoo de verdad','chill','none'),
(828,'es','¿Cotilleo fresco? Ella parece sorprendida.','¿Cotilleo fresco? Él parece sorprendido.','sorprendida en una cafetería','sorprendida en la puerta','gossip','guessing'),
(830,'es','Está explicando los cambios.','Está explicando el menú.','explicando el diseño de la app','explicando un problema de mates','business','none'),
(831,'es','Está dando un discurso.','Está dando un concierto.','un discurso en un atril','un discurso en una boda','business','none'),
(832,'es','Deshace la maleta y sale la bufanda más larga del mundo.','Deshace la maleta y sale el calcetín más largo del mundo.','deshaciendo una maleta','sacando la compra','low_iq','exaggeration'),
(833,'es','Deshaciendo las maletas: ¡la concha ha sobrevivido!','Deshaciendo las maletas: ¡la taza ha sobrevivido!','deshacer las maletas tras un viaje','desembalar un móvil nuevo','dramatic','exclamation'),
(834,'es','La anfitriona ya pasa de ellos.','El camarero ya pasa de ellos.','una anfitriona atareada sirviendo','una azafata de vuelo','gossip','guessing'),
(835,'es','¡El falso fontanero acabó empapado!','¡El falso fontanero acabó forrado!','un fontanero en el fregadero','un fontanero en el tejado','dramatic','exclamation'),
(836,'es','Él está muy preparado. Demasiado.','Ella está muy preparada. Demasiado.','un estudiante preparado','un plato preparado','ironic','exaggeration'),
(837,'es','Este taxi cabe en cualquier callejón.','Este autobús cabe en cualquier callejón.','un taxi en un callejón','un taxi en el aeropuerto','ironic','exaggeration'),
(838,'es','El piloto se cree una estrella.','El chef se cree una estrella.','un piloto con chaqueta','un piloto en un avión','gossip','guessing'),
(839,'es','¡Está alargando su mesa!','¡Está alargando su cama!','alargando una mesa de comedor','alargando un visado','dramatic','exclamation'),
(840,'es','Hizo senderismo hasta arriba solo para un selfie.','Nadó hasta allí solo para un selfie.','haciendo senderismo hasta un lago','haciendo senderismo hasta una playa','ironic','guessing'),
(841,'es','Derritió el hielo. ¿Y ahora qué?','Congeló el agua. ¿Y ahora qué?','derretir cubitos de hielo','derretir chocolate','ironic','guessing'),
(842,'es','El bebé quiere todas las letras.','El bebé quiere todas las galletas.','un bebé jugando con letras','un bebé jugando con comida','gossip','guessing'),
(843,'es','¡Más alto! ¡Arriba con la cesta!','¡Más alto! ¡Arriba con el cubo!','tirar de una cesta hacia arriba','tirar de un barco hacia arriba','dramatic','exclamation'),
(844,'es','¡Qué valle verde tan enorme!','¡Qué desierto verde tan enorme!','un valle verde abajo','un valle bajo la nieve','dramatic','exclamation'),
(845,'es','¡Otra vez algo desaparece! Gracias, mar.','¡Otra vez algo desaparece! Gracias, perro.','un dibujo que desaparece','un barco que desaparece','ironic','blaming_someone'),
(847,'es','Su victoria está clara.','Su derrota está clara.','victoria en una regata','victoria en una partida de ajedrez','chill','none'),
(848,'es','¿Vinagre? ¡Su cara dice que no!','¿Miel? ¡Su cara dice que no!','un chorrito de vinagre','limpiando con vinagre','slang','exclamation'),
(849,'es','¡Consiguió su visado!','¡Perdió su visado!','un visado en un pasaporte','un visado para las vacaciones','dramatic','exclamation'),
(850,'es','El volcán echa humo. Que nadie se asuste.','La chimenea echa humo. Que nadie se asuste.','un volcán humeante','un volcán bajo el mar','ironic','understatement'),
(851,'es','Está esperando. Y esperando.','Está bailando. Y bailando.','esperar el autobús','esperar un taxi','low_iq','exaggeration'),
(852,'es','¡El camarero es rapidísimo!','¡El camarero es lentísimo!','un camarero con platos','un camarero con la carta','slang','exclamation'),
(853,'es','Está caminando por el parque.','Está corriendo por el parque.','caminar junto al lago','pasear al perro','chill','none'),
(855,'es','Están dando un paseo junto al mar.','Están haciendo footing junto al mar.','un paseo junto al mar','un paseo por la montaña','chill','none'),
(857,'es','Encontró su cartera y se llevó una flor.','Encontró su cartera y se llevó una tarta.','devolviendo una cartera perdida','robando una cartera perdida','gossip','none'),
(859,'es','¡El armario la ha atacado!','¡La nevera la ha atacado!','un armario lleno de abrigos','un armario lleno de zapatos','dramatic','blaming_someone'),
(861,'es','Su reloj dice: ¡tarde!','Su móvil dice: ¡tarde!','mirando un reloj','comprando un reloj','dramatic','exclamation'),
(864,'es','Esta agua es cristalina a tope.','Esta leche es cristalina a tope.','agua clara en una botella','agua en un vaso de plástico','slang','exaggeration'),
(866,'es','¡Un arcoíris en la cascada!','¡Un arcoíris en el lago!','una cascada alta en Islandia','una cascada en un jardín','dramatic','exclamation'),
(867,'es','A la albahaca le gusta el riego.','A la rosa le gusta el riego.','riego de las tomateras','riego del césped','chill','guessing'),
(868,'es','Solo es una olita.','Solo es un tiburoncito.','una ola rompiendo sobre bañistas','un gesto con la mano','ironic','understatement'),
(869,'es','Está cargando un peso.','Está cargando una caja.','un peso redondo y pesado','perdiendo peso rápido','chill','none'),
(870,'es','El sol se pone por el oeste.','El sol se pone por el este.','viendo el sol irse al oeste','conduciendo al oeste de noche','chill','none'),
(873,'es','¡Su esposa sabe voltear tortitas!','¡Su esposa sabe voltear hamburguesas!','una esposa volteando tortitas','una esposa haciendo un pastel','flirt','exclamation'),
(874,'es','La peluca rosa le queda genial.','El sombrero rosa le queda genial.','poniéndose una peluca rosa','cepillando una peluca rosa','flirt','none'),
(875,'es','¡El viento le robó la bufanda!','¡El viento le robó el sombrero!','una bufanda al viento','viento soplando nieve','dramatic','blaming_someone'),
(876,'es','¿Vino tinto al atardecer? Qué clase.','¿Cerveza fría al atardecer? Qué clase.','una copa de vino tinto','una botella de vino blanco','flirt','cliche'),
(877,'es','¿Ganador lleno de barro? ¡Leyenda!','¿Ganador limpito? ¡Leyenda!','ganador de una carrera de barro','ganador de una carrera de natación','slang','none'),
(878,'es','¡Diversión de invierno en trineo!','¡Diversión de invierno en esquís!','un día de invierno en trineo','un día de invierno en casa','slang','exclamation'),
(879,'es','¡El lobo está aullando!','¡El lobo está durmiendo!','un lobo en la nieve','un lobo en una playa','dramatic','exclamation'),
(880,'es','¡El cordero lleva su propia lana!','¡El cordero lleva un gorro de lana!','un ovillo de lana','una manta de lana','dramatic','exaggeration'),
(882,'es','El perro dirige su entrenamiento.','El gato dirige su entrenamiento.','un entrenamiento completo','un entrenamiento en la playa','low_iq','exaggeration'),
(884,'es','Le está enseñando el mundo.','Le está enseñando el mapa.','un mundo de luces de ciudad','un mapa del mundo','chill','exaggeration'),
(885,'es','La lombriz se mete bajo tierra.','La lombriz sube a un árbol.','una lombriz en la tierra','una lombriz en un anzuelo','chill','none'),
(886,'es','La abuela se ha ganado sus arrugas.','La niña se ha ganado sus arrugas.','arrugas profundas en la cara','arrugas en una camisa','chill','none'),
(887,'es','Está escribiendo en su diario.','Está escribiendo en su portátil.','escribir en un diario','escribir en una pared','chill','none'),
(888,'es','Bostezar es contagioso, hasta para los perros.','Reír es contagioso, hasta para los perros.','bostezando en la cocina','bostezando en el coche','nerd','cliche'),
(889,'es','¡Su yogur no cae!','¡Su miel no cae!','un tarro de yogur espeso','bebiendo yogur de un tarro','dramatic','exclamation'),
(891,'es','Ups, ¡qué caro es ese coche!','Ups, ¡qué cara es esa bici!','un adorno de coche caro','un lavado de coche caro','slang','exclamation'),
(893,'es','Cremallera subida y lista para la nieve.','Cremallera subida y lista para el sol.','subir la cremallera de una chaqueta','subir la cremallera de una maleta','chill','none'),
(895,'es','Atasco enorme. ¿Un accidente?','Fiesta enorme. ¿Un accidente?','un accidente en la autopista','un accidente en la cocina','dramatic','guessing'),
(898,'es','La actriz está girando.','La actriz está durmiendo.','una actriz en el rodaje','una actriz en un póster','chill','none'),
(899,'es','Es una tarde soleada.','Es una tarde de nieve.','una tarde en el parque','una tarde en la playa','chill','none'),
(900,'es','El agente está al teléfono.','El agente está en el autobús.','un agente al teléfono','una agencia de viajes','business','none'),
(901,'es','Respira el aire fresco con los brazos abiertos.','Respira el aire de la ciudad con los brazos abiertos.','aire fresco de montaña','aire fresco en la ciudad','chill','none'),
(902,'es','¡Está saludando al avión!','¡Está saludando al tren!','un avión volando bajo','un avión de papel','dramatic','exclamation'),
(904,'es','Tiene alergia al polen.','Tiene alergia al polvo.','alergia al polen','alergia a los gatos','chill','none'),
(905,'es','Un gato cruza el callejón.','Un perro cruza el callejón.','un callejón estrecho empedrado','un callejón lleno de tiendas','chill','none'),
(907,'es','¿Hay alguien aquí? Solo palomas.','¿Hay alguien aquí? Solo gatos.','alguien en la estación','alguien en la fiesta','chill','understatement'),
(909,'es','Él pregunta si hay alguien en casa.','Ella pregunta si hay alguien en casa.','preguntar si hay alguien en casa','preguntar si alguien tiene hambre','chill','none'),
(911,'es','Un apartamento luminoso y soleado.','Un apartamento oscuro y lúgubre.','un apartamento moderno y luminoso','una oficina moderna y luminosa','chill','none'),
(912,'es','El arquitecto tiene un plano.','El arquitecto tiene un martillo.','un arquitecto con planos','un arquitecto en la playa','business','none'),
(913,'es','Tiene el brazo bien arriba.','Tiene el brazo bien abajo.','un brazo estirado hacia arriba','un brazo en cabestrillo','chill','none'),
(914,'es','¡Le encanta este sillón!','¡Le encanta este sofá!','dejándose caer en un sillón','dejándose caer en una piscina','dramatic','exclamation'),
(916,'es','Está usando un cajero automático.','Está usando un móvil.','un cajero automático bajo la lluvia','un cajero automático en una tienda','chill','none'),
(917,'es','El desván está lleno de trastos.','El desván está lleno de agua.','un desván viejo y polvoriento','un desván nuevo y luminoso','slang','none'),
(918,'es','El público está aplaudiendo.','El público se está yendo.','un público aplaudiendo','el público de la tele','business','none'),
(919,'es','Su tía es de las divertidas.','Su tío es de los divertidos.','bailando con su tía','de compras con su tía','slang','none'),
(920,'es','¿Columpiarse en Austria? Un sueño.','¿Esquiar en Austria? Un sueño.','columpiándose en Austria','esquiando en Austria','slang','cliche'),
(921,'es','Está sirviendo tarta austriaca.','Está sirviendo cerveza austriaca.','una cafetería austriaca','una cervecería austriaca','business','none'),
(926,'es','¡El pan del panadero está listo!','¡La pizza del panadero está lista!','un panadero junto al horno','un panadero en la caja','dramatic','exclamation'),
(927,'es','Está sacudiendo una alfombra en el balcón.','Está sacudiendo una toalla en el balcón.','una alfombra colgando del balcón','una planta en el balcón','chill','none'),
(929,'es','Está enrollando una venda.','Está envolviendo un regalo.','enrollando una venda blanca','enrollando una bufanda blanca','chill','none'),
(933,'es','Está en el baño.','Está en la cocina.','lavándose en el baño','limpiando el baño','chill','none'),
(934,'es','¡Chof! Está en la bañera.','¡Chof! Está en la piscina.','chapoteando en una bañera','chapoteando en un charco','slang','exclamation'),
(938,'es','Está haciendo la cama.','Está haciendo una tarta.','hacer la cama','irse a la cama','chill','none'),
(939,'es','¡Almohadas arriba! ¡Fiesta en el dormitorio!','¡Almohadas arriba! ¡Fiesta en la cocina!','un dormitorio luminoso y desordenado','una cocina luminosa y desordenada','slang','exclamation'),
(941,'es','¡Las palomas atacaron su banco!','¡Los patos atacaron su banco!','una mujer en un banco','un banco en la estación','dramatic','exaggeration'),
(942,'es','Va en bicicleta.','Va en patinete.','una bicicleta en otoño','una bicicleta en la nieve','chill','none'),
(943,'es','Está empapelando una valla publicitaria.','Está pintando una valla publicitaria.','una valla publicitaria gigante vacía','un anuncio en un autobús','chill','none'),
(944,'es','Se le olvidó usar los prismáticos.','Se le olvidó usar el telescopio.','prismáticos negros al pecho','prismáticos negros en una mesa','ironic','guessing'),
(947,'es','Le está sangrando la nariz.','Le está sangrando la rodilla.','una nariz sangrando','una rodilla sangrando','chill','none'),
(948,'es','¿Frutos del bosque en la licuadora? ¡Qué rico!','¿Cerezas en la licuadora? ¡Qué rico!','llenando una licuadora','limpiando una licuadora','slang','none'),
(949,'es','¡Ay, una ampolla en el talón!','¡Ay, una ampolla en el dedo del pie!','una ampolla en el talón','una ampolla en la mano','dramatic','exclamation'),
(950,'es','Está donando sangre.','Está dando un discurso.','una bolsa de sangre donada','sangre en una camisa blanca','chill','none'),
(952,'es','Está remando en una barca de madera.','Está remando en una barca hinchable.','remando en una barca de madera','una barca en un puerto','chill','none'),
(953,'es','La frontera está abierta para el coche.','La frontera está abierta para el autobús.','un paso de frontera','un borde de flores','business','none'),
(954,'es','El jefe está dando una charla.','El jefe está dando un regalo.','un jefe en una reunión','un jefe en una fiesta','business','none'),
(956,'es','Está estudiando un modelo de cerebro.','Está estudiando un modelo de corazón.','una maqueta de un cerebro','un dibujo de un cerebro','chill','none'),
(957,'es','Un petirrojo está posado en la rama.','Un búho está posado en la rama.','un columpio en una rama','un columpio en el parque','chill','none'),
(958,'es','¡La novia está lista!','¡El novio está listo!','una novia con rosas blancas','una novia con rosas rojas','dramatic','exclamation'),
(959,'es','Camina por debajo de un puente.','Camina por encima de un puente.','un enorme puente colgante','un pequeño puente de madera','chill','none'),
(960,'es','Está barriendo con una escoba.','Está barriendo con un rastrillo.','una escoba de paja','la escoba de una bruja','chill','none'),
(961,'es','El hermano mayor gana otra vez.','La hermana mayor gana otra vez.','un hermano inmovilizado','boxeando con un hermano','slang','cliche'),
(962,'es','Tiene un moratón enorme en la rodilla.','Tiene un moratón enorme en el brazo.','un moratón en una rodilla','un moratón en un ojo','chill','none'),
(963,'es','El albañil está levantando un muro.','El albañil está levantando un tejado.','un albañil con una paleta','un albañil con un martillo','chill','none'),
(965,'es','La paleta del albañil está llena.','El cubo del albañil está lleno.','una paleta llena de mortero','una paleta llena de tierra','chill','none'),
(967,'es','Este conductor de autobús está demasiado contento.','Este taxista está demasiado contento.','un conductor de autobús sonriente','un conductor de autobús en huelga','ironic','exaggeration'),
(970,'es','El carnicero está cortando ternera.','El carnicero está cortando pan.','un carnicero cortando ternera','un carnicero vendiendo pescado','chill','none'),
(973,'es','Un pájaro se ha posado en el cactus.','Una abeja se ha posado en el cactus.','un pájaro en un cactus','un cactus en una maceta','chill','none'),
(974,'es','Es una cafetería pequeña y llena.','Es una cafetería pequeña y vacía.','una cafetería acogedora y soleada','una cafetería cerrada','chill','none'),
(977,'es','Está apuntando con su cámara.','Está apuntando con su móvil.','una cámara antigua','una cámara de seguridad','chill','none'),
(981,'es','Coche verde, vistas al mar, puro estilo.','Coche verde, vistas a la ciudad, puro estilo.','un coche clásico verde','un coche familiar verde','flirt','exaggeration'),
(983,'es','El cajero está escaneando un tarro.','El cajero está escaneando una lata.','un cajero en la caja','un cajero en un banco','chill','none'),
(984,'es','La escayola todavía está húmeda.','La escayola ya está seca.','una escayola nueva en el brazo','una escayola nueva en la pierna','nerd','none'),
(986,'es','Una oruga se está zampando el almuerzo.','Un caracol se está zampando el almuerzo.','una oruga comiendo una hoja','una oruga en una flor','chill','understatement'),
(989,'es','Está facturando su maleta.','Está facturando a su perro.','facturando en el aeropuerto','haciendo el check-in en un hotel','business','none'),
(990,'es','El chef está usando pinzas.','El chef está usando una cuchara.','un chef emplatando','un chef probando la sopa','chill','none'),
(991,'es','Tiene el pecho descubierto.','Tiene el pecho tapado.','un pecho descubierto','un cofre del tesoro','chill','none'),
(996,'es','Unas manos modelan arcilla húmeda.','Unas manos modelan arena húmeda.','modelando una vasija de arcilla','pintando una vasija de arcilla','chill','none'),
(998,'es','Vuelan papeles y el oficinista sigue sellando.','Vuelan papeles y el oficinista sigue durmiendo.','un oficinista sellando papeles','un recepcionista de hotel','dramatic','exaggeration'),
(1000,'es','El clima se está calentando.','El clima se está enfriando.','un clima de montaña cambiante','un clima de isla tropical','nerd','none'),
(1003,'es','Solo una nube hoy.','Solo dos nubes hoy.','una gran nube blanca','una nube gris de lluvia','chill','understatement'),
(1004,'es','El entrenador no está susurrando.','El entrenador no está gritando.','un entrenador con silbato','un autocar lleno de turistas','chill','understatement'),
(1006,'es','La cafetera va demasiado lenta.','La tostadora va demasiado lenta.','una cafetera goteando','una cafetera nueva','chill','blaming_someone'),
(1007,'es','Dos colegas están hablando.','Dos colegas están comiendo.','colegas en una pizarra','colegas en una fiesta','chill','none'),
(1008,'es','La comunidad está plantando.','La comunidad está pintando.','un huerto de la comunidad','una comunidad gamer','business','none'),
(1010,'es','Ha hecho un contacto útil.','Ha hecho una llamada útil.','un nuevo contacto de negocios','un contacto en su móvil','business','none'),
(1011,'es','¡Este cocinero necesita dos cucharas!','¡Este cocinero necesita dos ollas!','un cocinero probando la comida','un cocinero leyendo una receta','dramatic','exclamation'),
(1012,'es','¡Está tosiendo muchísimo!','¡Se está riendo muchísimo!','tosiendo en el codo','tosiendo en un pañuelo','dramatic','exclamation'),
(1013,'es','Dos primos se ríen a carcajadas.','Dos primos lloran a moco tendido.','dos primos en la hierba','dos primos en una mesa','chill','none'),
(1015,'es','Se está sujetando la pantorrilla.','Se está sujetando la cabeza.','sujetándose la pantorrilla','dando de comer a un ternero','chill','none'),
(1022,'es','Este cojín ha perdido la pelea.','Este sofá ha perdido la pelea.','ahuecar un cojín','sentarse en un cojín','ironic','exaggeration'),
(1025,'es','Ese ciclista es valiente a tope.','Ese corredor es valiente a tope.','un ciclista tomando una curva rápido','un ciclista en la ciudad','slang','none'),
(1026,'es','¿Cerveza checa? ¡Sí, por favor!','¿Vino checo? ¡Sí, por favor!','una cervecería checa','una bodega checa','slang','exclamation'),
(1028,'es','Ella está en la República Checa.','Él está en la República Checa.','atardecer en la República Checa','nieve en la República Checa','chill','none'),
(1030,'es','¡Flores de su hija!','¡Flores de su hijo!','flores de una hija','flores para una hija','dramatic','exclamation'),
(1033,'es','¡El desierto no tiene fin!','¡El bosque no tiene fin!','camellos en el desierto','nieve en el desierto','dramatic','exaggeration'),
(1035,'es','No ve su destino.','No ve el tráfico.','lejos del destino','llegando al destino','ironic','guessing'),
(1037,'es','Más detergente, más espuma.','Más detergente, cero espuma.','echando detergente lavavajillas','detergente para la ropa','slang','cliche'),
(1040,'es','Pronto estarán divorciados.','Pronto estarán casados.','divorciándose','casándose','gossip','guessing'),
(1041,'es','A ella le da un mareo fuerte.','A él le da un mareo fuerte.','una oleada de mareo','mareo en un barco','dramatic','none'),
(1043,'es','¡El arco del delfín se lleva un diez!','¡El arco de la foca se lleva un diez!','el arco de un delfín saltando','el arco de un arcoíris','slang','exaggeration'),
(1048,'es','Esa mancuerna pesa una barbaridad.','Esa mancuerna no pesa nada.','levantando una mancuerna pesada','una mancuerna en el suelo','slang','exaggeration'),
(1050,'es','¿Tulipanes en bici? ¡Muy neerlandés!','¿Queso en bici? ¡Muy neerlandés!','casas neerlandesas altas','un mercado de queso neerlandés','slang','cliche'),
(1057,'es','El empleador está dando la mano.','El empleador se está lavando las manos.','un empleador acogedor','un empleador enfadado','business','none'),
(1064,'es','¡Todos están animando!','¡Todos están durmiendo!','todos levantando los brazos','todos sentándose','dramatic','exclamation'),
(1067,'es','Es un auténtico experto en relojes.','Es un auténtico experto en vinos.','un experto en relojes','un experto en la tele','chill','none'),
(1069,'es','Este ojo es verde y marrón.','Este ojo es azul intenso.','un ojo abierto','un ojo cerrado','chill','none'),
(1070,'es','Tiene cara de risa.','Tiene cara de llanto.','una cara riendo','una cara durmiendo','chill','none'),
(1071,'es','El granjero trabaja hasta tarde.','El granjero duerme hasta tarde.','un granjero con una horca','un granjero con una vaca','chill','guessing'),
(1072,'es','Estos dos tipos están felicísimos.','Estos dos tipos están cabreadísimos.','dos tipos dándose la mano','un compañero de clase saludando','slang','none'),
(1073,'es','¡La escaladora está volando!','¡El escalador está volando!','una escaladora','una corredora','dramatic','exaggeration'),
(1074,'es','Le está tomando la fiebre.','Le está mirando el móvil.','tomándole la fiebre','tomándole el pulso','chill','none'),
(1076,'es','Un dedo está tocando una gota.','Un dedo está tocando una abeja.','un dedo tocando una gota','un dedo cerca de una abeja','chill','none'),
(1078,'es','El bombero está de servicio.','El bombero está de vacaciones.','un bombero con una manguera','un bombero con un gato','business','none'),
(1079,'es','Está dando primeros auxilios.','Está dando indicaciones.','un botiquín de primeros auxilios abierto','un curso de primeros auxilios','chill','none'),
(1082,'es','¡El pescador ha pillado un montón!','¡El pescador no ha pillado nada!','un pescador con red','un pescador con caña','slang','exclamation'),
(1084,'es','El vuelo acaba de despegar.','El vuelo está a punto de aterrizar.','un vuelo tras el despegue','un tramo de escaleras','business','none'),
(1085,'es','Está fregando un suelo de madera.','Está fregando un suelo de piedra.','un amplio suelo de madera','la primera planta','business','none'),
(1088,'es','Un pie descalzo en la hierba.','Un pie descalzo en la nieve.','un pie descalzo en la hierba','un pie con calcetín','chill','none'),
(1096,'es','Está en una galería blanca.','Está en una cocina blanca.','paseando por una galería','paseando por una tienda','chill','none'),
(1097,'es','Está cerrando el garaje.','Está cerrando la ventana.','cerrando la puerta del garaje','abriendo la puerta del garaje','chill','none'),
(1100,'es','El jardinero está cortando rosas.','El jardinero está cortando el césped.','un jardinero con rosas','un jardinero con un cortacésped','chill','none'),
(1104,'es','¡Todo un caballero!','¡Toda una dama!','un caballero quitándose el sombrero','un caballero cerrando la puerta','flirt','exclamation'),
(1107,'es','Está abrazando a su novia.','Está llevando en brazos a su novia.','abrazando a su novia','una novia al teléfono','flirt','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
