begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(1110,'es','¡Besitos de la nieta!','¡Besitos del nieto!','el beso de una nieta','el dibujo de una nieta','slang','exclamation'),
(1112,'es','La abuela está haciendo pan.','La abuela está haciendo sopa.','horneando con la abuela','tejiendo con la abuela','chill','none'),
(1115,'es','¿Bailando en Grecia? Menudo estilo.','¿Buceando en Grecia? Menudo estilo.','bailando en Grecia','nadando en Grecia','flirt','none'),
(1119,'es','El guía dirige la visita.','El guía dirige la carrera.','un guía con un paraguas','un guía de montaña escalando','business','none'),
(1120,'es','Este tío lanza sus llaves, qué guay.','Este tío lanza su móvil, qué guay.','un tío con una pizza','un tío con una guitarra','slang','none'),
(1123,'es','¡Su pasillo es una pista de baile!','¡Su cocina es una pista de baile!','bailando por un pasillo','corriendo por un pasillo','slang','exclamation'),
(1125,'es','Los barcos descansan en el puerto.','Los barcos descansan en la playa.','barcos en el puerto','barcos en el canal','chill','none'),
(1126,'es','El trabajo le dio dolor de cabeza.','La música le dio dolor de cabeza.','dolor de cabeza por la noche','dolor de cabeza al sol','chill','blaming_someone'),
(1127,'es','¡Pura salud y felicidad!','¡Pura lluvia y oscuridad!','rebosante de salud y alegría','un chequeo de salud','dramatic','cliche'),
(1129,'es','¡El médico sostiene un corazón!','¡El médico sostiene un cerebro!','una maqueta de un corazón','una maqueta de un cerebro','dramatic','exclamation'),
(1131,'es','Los dos talones están levantados del suelo.','Los dos talones están apoyados en el suelo.','levantando los dos talones','llevando tacones altos','chill','none'),
(1133,'es','La ayudante tiene su bolso.','La ayudante tiene su perro.','una ayudante con su bolso','una ayudante en la cocina','chill','none'),
(1134,'es','¿A que no sabes quién come en la colina? Las ovejas.','¿A que no sabes quién come en la colina? Las vacas.','un árbol en la colina','una casa en la colina','gossip','guessing'),
(1135,'es','Tiene la mano en la cadera.','Tiene la mano en la cabeza.','una mano en la cadera','una mano en el hombro','chill','none'),
(1136,'es','¡Por fin está de vuelta en su hogar!','¡Por fin está de vuelta en el trabajo!','volviendo al hogar con una bolsa','saliendo del hogar con una bolsa','dramatic','exclamation'),
(1138,'es','Día tranquilo en el hospital.','Día tranquilo en el aeropuerto.','un pasillo de hospital luminoso','una planta de hospital llena','gossip','guessing'),
(1139,'es','El anfitrión hace un brindis.','El anfitrión hace una tarta.','un anfitrión alzando su copa','un presentador de televisión','business','none'),
(1141,'es','Un huésped sale del hotel.','Un huésped entra en el hotel.','saliendo de un gran hotel','un hotel junto al mar','business','none'),
(1143,'es','Aquí solo hay un humano.','Aquí solo hay un camello.','un humano en el desierto','una multitud de humanos','ironic','understatement'),
(1144,'es','El cazador está de rodillas.','El cazador está corriendo.','un cazador con prismáticos','un cazador con un rifle','chill','none'),
(1147,'es','Tiene una infección en el codo.','Tiene una infección en la rodilla.','una infección en el codo','una infección en el ojo','chill','none'),
(1148,'es','La inyección está lista. ¡Corre!','La venda está lista. ¡Corre!','una bandeja para una inyección','una bandeja lista para la cena','low_iq','exclamation'),
(1149,'es','Insomnio: él contra el techo.','Insomnio: él contra la nevera.','insomnio en plena noche','insomnio antes de un examen','ironic','exaggeration'),
(1151,'es','Su plancha echa vapor.','Su hervidor echa vapor.','una plancha echando vapor','una verja de hierro','business','none'),
(1152,'es','Se está montando una tabla de planchar.','Se está montando una silla de playa.','montando una tabla de planchar','sentado en una tabla de planchar','chill','none'),
(1154,'es','El periodista quiere respuestas.','El médico quiere respuestas.','un periodista con una grabadora','un periodista en su escritorio','gossip','guessing'),
(1156,'es','El loro manda en esta selva.','El mono manda en esta selva.','un loro en la selva','un loro en una jaula','slang','exaggeration'),
(1158,'es','El agua del hervidor está caliente. ¿Quién lo diría?','El agua del grifo está caliente. ¿Quién lo diría?','sirviendo agua del hervidor','un hervidor en el fogón','low_iq','understatement'),
(1160,'es','La cocina está muy bien equipada.','La cocina está casi vacía.','una cocina luminosa','una cocina oscura','business','none'),
(1161,'es','Se está poniendo hielo en la rodilla.','Se está poniendo hielo en la cabeza.','hielo en una rodilla doblada','con una rodilla en el suelo','business','none'),
(1163,'es','La dama lleva guantes blancos.','La dama lleva guantes negros.','una dama en la escalera','una dama en el bar','chill','none'),
(1166,'es','Está moviendo una lámpara grande.','Está moviendo una planta grande.','una lámpara de mesa','una lámpara de jardín','chill','none'),
(1170,'es','El bibliotecario está en una escalera.','El bibliotecario está en una mesa.','un bibliotecario en una escalera','un bibliotecario frente al ordenador','chill','none'),
(1173,'es','¡Un relámpago cae sobre el mar!','¡Un relámpago cae sobre un árbol!','un relámpago sobre el mar','un relámpago sobre una ciudad','dramatic','exclamation'),
(1175,'es','Vuelan palomitas por todo el salón.','Vuelan palomitas por toda la cocina.','amigos en un salón','amigos en una sala de espera','slang','exaggeration'),
(1178,'es','El perdedor está debajo de una toalla.','El perdedor está debajo de una mesa.','el perdedor del partido','el perdedor de la carrera','dramatic','none'),
(1180,'es','La etiqueta de equipaje está en blanco.','La etiqueta de equipaje es roja.','atando una etiqueta de equipaje','cortando una etiqueta de equipaje','chill','none'),
(1183,'es','Un atleta masculino está remando.','Una atleta femenina está remando.','un remero masculino','un nadador masculino','chill','none'),
(1185,'es','El encargado está dando órdenes.','El encargado está dando regalos.','un encargado con un portátil','un encargado con un móvil','business','none'),
(1188,'es','Recién casados y ya están bailando.','Recién casados y ya se están peleando.','una pareja casada bailando','una pareja casada discutiendo','chill','none'),
(1189,'es','Están cargando un colchón.','Están cargando un piano.','un colchón escaleras arriba','un colchón en el suelo','chill','none'),
(1193,'es','Abre bien la boca para la medicina.','Abre bien la boca para el helado.','medicina líquida en una cuchara','medicina en un pastillero','chill','cliche'),
(1195,'es','¡Una tortilla mexicana voladora!','¡Un taco mexicano volador!','un puesto callejero mexicano','un restaurante mexicano','dramatic','exclamation'),
(1198,'es','La modelo manda en la pasarela.','La modelo manda en la playa.','una modelo en la pasarela','un modelo de avión','slang','exaggeration'),
(1200,'es','Le encanta esta mañana soleada.','Le encanta esta mañana lluviosa.','una mañana soleada','una mañana lluviosa','chill','guessing'),
(1203,'es','¡Su moto está echando chispas!','¡Su escúter está echando chispas!','una moto en una curva','una moto en un garaje','dramatic','exclamation'),
(1206,'es','¡Vuela barro por todas partes!','¡Vuela nieve por todas partes!','un zapato hundido en el barro','un zapato en nieve fresca','dramatic','exclamation'),
(1208,'es','¡Un dinosaurio en el museo!','¡Una ballena en el museo!','un dinosaurio en un museo','un museo de arte moderno','dramatic','exclamation'),
(1211,'es','Toda una nación cantando a una.','Toda una nación bailando a una.','una nación cantando unida','una nación de amantes del café','dramatic','cliche'),
(1213,'es','Grandes olas, grandes náuseas.','Olas pequeñas, grandes náuseas.','náuseas en un mar agitado','náuseas tras una comilona','dramatic','none'),
(1214,'es','Está estirando el cuello.','Está estirando la pierna.','un cuello largo estirado','una bufanda al cuello','chill','none'),
(1215,'es','Los vecinos están charlando.','Los vecinos se están peleando.','vecinos en la valla del jardín','un vecino ruidoso','chill','none'),
(1216,'es','Bici, tulipanes, molinos. Sí, los Países Bajos.','Coche, tulipanes, molinos. Sí, los Países Bajos.','tulipanes en los Países Bajos','un mercado en los Países Bajos','chill','cliche'),
(1218,'es','No hay nadie en el parque infantil. ¡Qué mal rollo!','Hay niños en el parque infantil. ¡Qué mal rollo!','nadie en los columpios','nadie en la playa','dramatic','exclamation'),
(1219,'es','No ha venido nadie. Menudo fiestón.','Han venido todos. Menudo fiestón.','nadie en la mesa','una mesa llena de comensales','ironic','understatement'),
(1221,'es','El oficial está saludando.','El oficial está bailando.','un oficial saludando','un oficial conduciendo','chill','none'),
(1225,'es','Al pintor le encanta el verde azulado.','Al pintor le encanta el rosa.','un pintor en una escalera','un pintor ante un caballete','chill','guessing'),
(1227,'es','Modo padre: a correr.','Modo padre: a dormir.','un padre junto a una bici','un padre arreglando una bici','slang','cliche'),
(1230,'es','El pasajero está profundamente dormido.','El pasajero está completamente despierto.','un pasajero dormido en el tren','un pasajero en un taxi','chill','none'),
(1232,'es','El paciente está tomando aire.','El paciente está comiendo.','un paciente respirando hondo','un paciente en la cama','chill','none'),
(1233,'es','El peatón va con un café.','El peatón va con un perro.','un peatón con un café','un puente peatonal','chill','none'),
(1235,'es','¡La gente está vitoreando!','¡La gente está llorando!','gente vitoreando de noche','gente vitoreando en un estadio','dramatic','exclamation'),
(1238,'es','La farmacia tiene un montón de tarros.','La farmacia tiene un montón de juguetes.','una farmacia antigua y acogedora','una farmacia con cruz roja','chill','none'),
(1241,'es','¡El fotógrafo está tumbado en la calle mojada!','¡El fotógrafo está de pie en la calle mojada!','un fotógrafo en el suelo','un fotógrafo en un estudio','dramatic','exclamation'),
(1242,'es','Está colgando un cuadro.','Está colgando un espejo.','un cuadro en la pared','una foto en su móvil','chill','none'),
(1248,'es','¡El planeta tiene anillos!','¡El planeta no tiene anillos!','un planeta con anillos','un planeta en un mapa','dramatic','exclamation'),
(1254,'es','El fontanero está arreglando una tubería.','El fontanero está arreglando una puerta.','un fontanero bajo un fregadero','un fontanero en un tejado','chill','none'),
(1255,'es','Es invierno en Polonia.','Es verano en Polonia.','una plaza nevada en Polonia','una playa de arena en Polonia','chill','none'),
(1256,'es','El policía está sonriendo.','El policía está llorando.','un policía señalando','un policía corriendo','chill','none'),
(1258,'es','Ha hecho empanadillas polacas.','Ha hecho salchichas polacas.','empanadillas polacas en fila','salchichas polacas a la parrilla','chill','none'),
(1260,'es','Está corriendo en Portugal.','Está montando en bici en Portugal.','corriendo en Portugal','en tranvía por Portugal','chill','none'),
(1262,'es','¡Canela sobre pasteles portugueses!','¡Chocolate sobre pasteles portugueses!','pasteles de nata portugueses','sardinas portuguesas','dramatic','exclamation'),
(1263,'es','El cartero está repartiendo cartas.','El cartero está repartiendo pizzas.','un cartero en una puerta','un cartero en una furgoneta','business','none'),
(1266,'es','¡El presidente está hablando y los flashes no paran!','¡El presidente está cantando y los flashes no paran!','un presidente dando un discurso','un presidente dando la mano','dramatic','exclamation'),
(1268,'es','El catedrático está dando clase.','El catedrático está durmiendo.','un catedrático dando clase','el despacho de un catedrático','chill','none'),
(1270,'es','Está chapoteando en un charco.','Está chapoteando en la nieve.','saltando a un charco','un charco de leche derramada','chill','none'),
(1274,'es','Un arcoíris enorme sobre las colinas.','Un arcoíris enorme sobre el mar.','un arcoíris sobre colinas verdes','un arcoíris sobre una ciudad','chill','none'),
(1275,'es','Se está rascando el sarpullido.','Se está rascando la cabeza.','rascando un sarpullido rojo','un sarpullido en la cara','chill','none'),
(1278,'es','La recepción tiene un timbre de latón.','La recepción tiene una lámpara de latón.','una llave en recepción','una recepción de boda','business','none'),
(1287,'es','¿Una habitación vacía? ¡A bailar!','¿Una tienda vacía? ¡A bailar!','una habitación vacía y soleada','una playa vacía y soleada','slang','exclamation'),
(1290,'es','¡Esta ruta tiene muchísimas curvas!','¡Esta ruta tiene muchísimos camiones!','una ruta montaña arriba','una ruta por la costa','dramatic','exclamation'),
(1299,'es','Le encanta su escáner, por lo visto.','Odia su escáner, por lo visto.','un paciente haciéndose un escáner','un escáner en el aeropuerto','ironic','guessing'),
(1303,'es','¡Qué paseo en escúter con estilo!','¡Qué paseo en bici con estilo!','un escúter en Italia','un escúter en la playa','flirt','exaggeration'),
(1304,'es','¡El secretario está ocupadísimo!','¡El secretario está aburridísimo!','un secretario muy ocupado','un secretario de vacaciones','dramatic','exclamation'),
(1305,'es','Cae una semilla de judía.','Cae una piedrecita.','plantando una semilla de judía','un pájaro comiendo semillas','chill','none'),
(1306,'es','El vendedor está muy contento.','El vendedor está muy enfadado.','un vendedor de verduras','un vendedor de libros','chill','none'),
(1307,'es','El sirviente lleva una bandeja de plata.','El sirviente lleva una campanilla de plata.','un sirviente con una bandeja','un sirviente en una cocina','chill','none'),
(1308,'es','¡Hasta su sombra está bailando!','¡Hasta su amiga está bailando!','una sombra gigante en la pared','una sombra bajo un árbol','dramatic','exclamation'),
(1311,'es','¡Está saludando a un barco enorme!','¡Está saludando a un barco diminuto!','saludando a un gran barco','saludando desde un gran barco','dramatic','exclamation'),
(1312,'es','La dependienta lleva un abrigo.','La dependienta lleva un sombrero.','una dependienta trabajando','una dependienta en su descanso','business','none'),
(1314,'es','Hay que revisarle el hombro.','Hay que revisarle la rodilla.','examinando un hombro','un bolso al hombro','business','none'),
(1315,'es','¿Ducha de lluvia? ¡Más bien una cascada!','¿Ducha de jardín? ¡Más bien una cascada!','una gran ducha de lluvia','una cortina de ducha','dramatic','exaggeration'),
(1316,'es','Los hermanos se están riendo.','Los hermanos están discutiendo.','hermanos riendo juntos','hermanos peleándose por un juguete','chill','none'),
(1317,'es','Está en una acera de piedra.','Está en una acera de madera.','una acera ancha de piedra','una acera llena de gente','business','none'),
(1319,'es','Está soltera y feliz.','Está soltera y triste.','feliz de estar soltera','una única taza de té','chill','none'),
(1321,'es','Aquí tiene su plato, señor.','Aquí tiene su cuenta, señor.','su plato, señor','su cuenta, señor','business','none'),
(1325,'es','Está durmiendo. La almohada es su amiga.','Está durmiendo. El gato es su amigo.','durmiendo en una cama','durmiendo en un tren','low_iq','guessing'),
(1326,'es','Zapatillas de casa peluditas, mañana de pereza.','Calcetines peluditos, mañana de pereza.','poniéndose zapatillas de casa','zapatillas de casa en una tienda','chill','none'),
(1327,'es','Él lleva ropa tradicional eslovaca.','Ella lleva ropa tradicional eslovaca.','traje tradicional eslovaco','una camiseta de fútbol eslovaca','chill','none'),
(1328,'es','¡Está bailando en Eslovaquia!','¡Está nadando en Eslovaquia!','un prado en Eslovaquia','una playa en Eslovaquia','dramatic','exclamation'),
(1337,'es','Están jugando en el sofá.','Están jugando en el suelo.','amigos en un sofá gris','amigos en un autobús gris','chill','none'),
(1340,'es','Alguien se va a escondidas.','Alguien baila a escondidas.','alguien alejándose','alguien paseando a un perro','gossip','guessing'),
(1342,'es','¡Su hijo ha vuelto a casa!','¡Su hija ha vuelto a casa!','abrazando a su hijo adulto','despidiéndose de su hijo','dramatic','exclamation'),
(1344,'es','La araña está trabajando.','La hormiga está trabajando.','una araña en su telaraña','una araña en la bañera','business','none'),
(1346,'es','El boxeador está escupiendo agua.','El boxeador está bebiendo agua.','escupiendo agua en un cubo','escupiendo un chicle','chill','none'),
(1347,'es','Una mano está estrujando una esponja.','Una mano está estrujando un limón.','una esponja con jabón estrujada','un bizcocho esponjoso','chill','none'),
(1350,'es','Está cruzando la plaza. ¡Adiós, palomas!','Está cruzando el río. ¡Adiós, palomas!','corriendo por una plaza','sentada en una plaza tranquila','slang','none'),
(1353,'es','Una estrella brillante. ¡Pide un deseo!','Una luna brillante. ¡Pide un deseo!','señalando una estrella brillante','una estrella en un árbol','slang','exclamation'),
(1354,'es','¡Otra vez tarde en la estación!','¡Otra vez tarde en el aeropuerto!','corriendo por una estación','durmiendo en la estación','dramatic','guessing'),
(1355,'es','Manos al volante.','Manos al móvil.','manos en el volante','el timón de un barco','chill','none'),
(1358,'es','Su madrastra le está haciendo una trenza.','Su madrastra le está cortando el pelo.','una madrastra trenzando el pelo','una madrastra en el colegio','chill','none'),
(1359,'es','Las hermanastras no pueden parar de reír.','Las hermanastras no pueden parar de llorar.','hermanastras riendo juntas','hermanastras compartiendo cama','gossip','exaggeration'),
(1360,'es','Está usando un estetoscopio. ¡Chis!','Está usando un termómetro. ¡Chis!','escuchando con un estetoscopio','un estetoscopio en una mesa','dramatic','exclamation'),
(1362,'es','Al corte le están dando puntos de sutura.','Al corte le están poniendo una tirita.','puntos de sutura en un antebrazo','puntadas en una camisa','chill','none'),
(1363,'es','Esta piedra va a nadar, ¿no?','Esta hoja va a nadar, ¿no?','una piedra sobre un lago','una piedra en un muro','low_iq','guessing'),
(1365,'es','¡Un desconocido la está parando!','¡Un policía la está parando!','un desconocido con capucha','un desconocido con un perro','dramatic','none'),
(1366,'es','Una hoja está surfeando el arroyo.','Una rana está surfeando el arroyo.','un arroyo claro en el bosque','un arroyo lleno de peces','low_iq','exaggeration'),
(1367,'es','Está cruzando una calle concurrida.','Está cruzando un puente concurrido.','una calle concurrida de gran ciudad','una calle tranquila de pueblo','business','none'),
(1369,'es','¿Lluvia? ¡Está bailando con una farola!','¿Lluvia? ¡Está bailando con un semáforo!','una hilera de farolas encendidas','una hilera de velas encendidas','dramatic','exclamation'),
(1371,'es','El metro va superrápido.','El metro va superlento.','un metro pasando a toda velocidad','un plano del metro','slang','exaggeration'),
(1372,'es','Su maleta es gris y práctica.','Su maleta es roja y práctica.','tirando de una maleta gris','haciendo una maleta gris','business','none'),
(1375,'es','¡El sudor sale volando de su guante!','¡El sudor sale volando de su zapato!','sudor en su brazo','sudor en una camiseta','dramatic','exclamation'),
(1378,'es','Está comiendo fondue suiza.','Está comiendo chocolate suizo.','una fondue de queso suiza','una fondue de chocolate suiza','chill','none'),
(1379,'es','Alguien ha encontrado el interruptor. Guau.','Alguien ha encontrado el móvil. Guau.','un interruptor de la luz','un cambio de agujas de tren','low_iq','exaggeration'),
(1380,'es','Suiza: hasta las vacas tienen música.','Suiza: hasta las cabras tienen música.','una trompa alpina en Suiza','una tienda de cencerros en Suiza','chill','exaggeration'),
(1381,'es','¡La jeringa está echando un chorro!','¡La botella está echando un chorro!','una jeringa echando un chorro','llenando una jeringa','dramatic','exclamation'),
(1383,'es','El sastre está arreglando una chaqueta.','El sastre está arreglando un zapato.','un sastre con una cinta métrica','un sastre vendiendo zapatos','chill','none'),
(1385,'es','¡Agua de un grifo! ¡Hala!','¡Agua de una manguera! ¡Hala!','abriendo el grifo','una palmadita en el hombro','low_iq','exclamation'),
(1386,'es','¡El taxista está saludando!','¡El taxista está durmiendo!','un taxista saludando','un taxista de noche','slang','exclamation'),
(1389,'es','A ella le caen las lágrimas.','A él le caen las lágrimas.','una lágrima en su mejilla','un roto en su vestido','dramatic','none'),
(1390,'es','Quiere tocar la luna.','Quiere tocar el sol.','intentando alcanzar la luna','una luna sobre el mar','dramatic','guessing'),
(1394,'es','Un gran sol naranja sobre el mar.','Un gran sol naranja sobre la nieve.','el sol sobre el mar','el sol sobre las montañas','chill','none'),
(1396,'es','¡Todo el teatro es para ella!','¡Todo el teatro es para él!','un teatro antiguo vacío','un teatro lleno de gente','dramatic','exaggeration'),
(1398,'es','¡Su termómetro es enorme!','¡Su cepillo de dientes es enorme!','un gran termómetro de cristal','un termómetro en la pared','dramatic','exclamation'),
(1400,'es','Le están revisando la garganta.','Le están revisando el oído.','una luz en la garganta','aclarándose la garganta','business','none'),
(1404,'es','Su lengua está cazando nieve para comer.','Su mano está cazando nieve para comer.','sacando la lengua','mordiéndose la lengua','low_iq','guessing'),
(1405,'es','Están revisando cada diente, uno a uno.','Están revisando cada uña, una a una.','revisando un diente','el Ratoncito Pérez','business','none'),
(1410,'es','Está en un semáforo.','Está en una parada de autobús.','esperando en un semáforo','esperando en una estación de tren','chill','none'),
(1411,'es','Tranvía antiguo, gran sonrisa, mucho estilo.','Autobús antiguo, gran sonrisa, mucho estilo.','un tranvía verde antiguo','un autobús verde antiguo','flirt','none'),
(1413,'es','Cinta de correr: corriendo hacia ninguna parte.','Cinta de correr: caminando hacia ninguna parte.','corriendo en una cinta de correr','arreglando una cinta de correr rota','ironic','cliche'),
(1414,'es','¡Hala, el roble es enorme!','¡Hala, la palmera es enorme!','un roble enorme','una cesta de pícnic enorme','low_iq','exclamation'),
(1415,'es','Se está subiendo a su camión.','Se está subiendo a su coche.','un gran camión plateado','un gran autobús plateado','chill','none'),
(1416,'es','Está saliendo de un túnel.','Está saliendo de un garaje.','saliendo de un túnel de carretera','entrando en un túnel de tren','chill','none'),
(1419,'es','Gemelas, mismo vestido. ¿Casualidad?','Gemelas, mismo sombrero. ¿Casualidad?','gemelas con vestidos iguales','gemelos en un cochecito','gossip','guessing'),
(1420,'es','¡El mejor tío del mundo!','¡La mejor tía del mundo!','a hombros de su tío','en la bici de su tío','slang','exaggeration'),
(1422,'es','Una mano está señalando la pantalla.','Una mano está señalando la ventana.','señalar una pantalla','señalar la puerta','chill','none'),
(1423,'es','Señalando un gráfico de barras.','Señalando un gráfico circular.','gráficos de barras y de líneas','un gráfico en papel','business','none'),
(1424,'es','El colega que está de pie va de azul.','El colega que está de pie va de rojo.','colega con camisa azul','colega con camisa roja','chill','none'),
(1425,'es','¿A que no sabes quién va con correa?','¿A que no sabes quién va en el sofá?','un perro con correa','un perro sin correa','gossip','none'),
(1427,'es','¡Mantiene el equilibrio sobre una cuerda!','¡Mantiene el equilibrio sobre un tronco!','manteniendo el equilibrio en una cuerda','manteniendo el equilibrio en una rama','dramatic','exclamation'),
(1429,'es','Está cantando para sus amigos.','Está bailando para sus amigos.','cantando al micrófono','cantando en la ducha','chill','none'),
(1432,'es','Está cantando con disfraz. El zapato de cristal ya está listo.','Está bailando con disfraz. El zapato de cristal ya está listo.','cantando con disfraz','comprando un disfraz','gossip','guessing'),
(1433,'es','Solo estamos bailando en casa, lo normal.','Solo estamos cenando en casa, lo normal.','bailando disfrazados','bailando en un escenario','chill','understatement'),
(1434,'es','Nadie ve al ladrón en la lámpara de araña.','Nadie ve al ladrón en el tejado.','un ladrón con una bolsa','un ladrón con una pistola','ironic','guessing'),
(1435,'es','No piensa compartir el micrófono.','No piensa compartir la guitarra.','un micrófono en su pie','un micrófono en un móvil','ironic','guessing'),
(1436,'es','Las personas tienen edades diversas.','Las personas son todas adolescentes.','cinco retratos diversos','cinco paisajes diversos','chill','none'),
(1438,'es','Él está grabando un pódcast.','Ella está grabando un pódcast.','grabando un pódcast','escuchando un pódcast','chill','none'),
(1441,'es','Su victoria mereció el esfuerzo.','Su victoria mereció el dinero.','merece el esfuerzo','un esfuerzo por no dormirse','chill','none'),
(1442,'es','Esta oficina está llena de plantas.','Esta oficina está llena de perros.','una oficina diáfana y luminosa','una oficina oscura y vacía','business','none'),
(1446,'es','¡La conferencia está a reventar!','¡La conferencia está vacía!','una sala de conferencias abarrotada','una videoconferencia','dramatic','exclamation'),
(1447,'es','La vacuna duele un poquito.','La vacuna hace un poquito de cosquillas.','una vacuna en el brazo','una vacuna en la pierna','chill','understatement'),
(1450,'es','Flores de una visita. Qué detalle.','Caramelos de una visita. Qué detalle.','una visita con flores','un visitante en el museo','flirt','none'),
(1451,'es','Esta vitamina la hace reír.','Esta vitamina la hace llorar.','una vitamina de gominola naranja','una vitamina de gominola verde','gossip','guessing'),
(1452,'es','El volcán está un poco enfadado.','El volcán está un poco dormido.','un volcán en erupción de noche','un volcán cubierto de nieve','ironic','understatement'),
(1453,'es','El barco está en una larga travesía.','El barco está en una travesía fluvial.','una travesía por el océano','una travesía por el río','chill','none'),
(1454,'es','Se está midiendo la cintura.','Se está midiendo el brazo.','una cinta alrededor de la cintura','un cinturón en la cintura','business','none'),
(1457,'es','La camarera está sirviendo un batido.','La camarera está sirviendo una pizza.','una camarera sirviendo el desayuno','una camarera desayunando','business','none'),
(1458,'es','El caminante va con un perro dorado.','El caminante va con un perro negro.','un caminante con bastones','un caminante con un carrito','chill','none'),
(1459,'es','Está pintando la pared de blanco.','Está pintando la pared de azul.','una pared grande y desnuda','un muro alrededor de un jardín','chill','none'),
(1466,'es','¿Lluvia o sol? El tiempo no se decide.','¿Nieve o sol? El tiempo no se decide.','tiempo cambiante en una colina','tiempo soleado en una playa','ironic','guessing'),
(1467,'es','Un mecánico hace rodar una rueda.','Un mecánico lava una rueda.','haciendo rodar una rueda de coche','una rueda de bicicleta','business','none'),
(1468,'es','¡A toda velocidad en una silla de ruedas de carreras!','¡A toda velocidad en un kart de carreras!','una silla de ruedas de carreras','una rampa para sillas de ruedas','dramatic','exclamation'),
(1473,'es','El trabajador sostiene una viga.','El trabajador sostiene una tubería.','un trabajador con gafas protectoras','un trabajador con traje','chill','none'),
(1476,'es','El escritor escribe a máquina de noche, cómo no.','El escritor escribe a máquina a mediodía, cómo no.','un escritor con máquina de escribir','un escritor con un portátil','ironic','cliche'),
(1477,'es','La radiografía muestra los huesos de una mano.','La radiografía muestra los huesos de un pie.','una radiografía de una mano','una radiografía de un pie','nerd','none'),
(1479,'es','Hora de comer en el zoo.','Hora de comer en la granja.','una jirafa en el zoo','un león en el zoo','business','none'),
(1481,'es','El castillo tiene dos arcos.','El castillo tiene cuatro arcos.','un arco bajo la escalinata','un arco sobre el río','chill','none'),
(1482,'es','¡Qué pendientes de oro tan bonitos!','¡Qué pendientes de plata tan bonitos!','grandes pendientes de aro dorados','pendientes en una caja de regalo','flirt','exclamation'),
(1483,'es','Las fresas están rojas.','Las fresas están verdes.','una planta de fresas','un batido de fresa','chill','none'),
(1484,'es','Esta música no tiene botón de play.','Este poema no tiene botón de play.','una partitura de música antigua','una vieja caja de música','ironic','exaggeration'),
(1485,'es','Quieren vender la casa.','Quieren vender el coche.','vendiendo una casa blanca','vendiendo un coche rojo','chill','none'),
(1487,'es','El dios tiene un trono dorado.','El dios tiene un trono plateado.','un dios en un trono','un rey a caballo','chill','none'),
(1488,'es','Unos caballos tiran de un carruaje.','Unos bueyes tiran de un carruaje.','un carruaje real dorado','un vagón de tren dorado','chill','none'),
(1489,'es','La mejor amiga del hada es una rana.','La mejor amiga del hada es una gata.','un hada sobre el musgo','un hada en el cielo','gossip','guessing'),
(1491,'es','¡Cuántas mariposas!','¡Cuántos pájaros!','mariposas sobre las flores','mariposas en una camisa','dramatic','exaggeration'),
(1495,'es','Dato: un unicornio tiene un cuerno.','Dato: un unicornio tiene dos cuernos.','un unicornio encabritado','un unicornio dormido','nerd','cliche'),
(1497,'es','El violín descansa sobre partituras antiguas.','La guitarra descansa sobre partituras antiguas.','un violín con rosas','una clase de violín','chill','none'),
(1498,'es','Dos tíos en un globo. ¡Chao!','Dos tíos a caballo. ¡Chao!','un globo con dos hombres','un globo con dos perros','slang','none'),
(1499,'es','Los tallos son largos y rizados.','Los tallos son cortos y gruesos.','tallos largos y rizados','tallos en un jarrón','nerd','none'),
(1501,'es','Está vertiendo un líquido verde.','Está vertiendo un líquido rojo.','vertiendo desde un cuenco ancho','vertiendo té en una taza','chill','none'),
(1504,'es','El filósofo tiene barba.','El filósofo tiene sombrero.','un filósofo con barba','un filósofo riendo','chill','none'),
(1505,'es','Visita al supermercado, estilo años 50.','Visita a la panadería, estilo años 50.','la caja de un supermercado','el aparcamiento de un supermercado','slang','cliche'),
(1508,'es','La iglesia tiene una torre alta.','La iglesia tiene una torre diminuta.','una vieja iglesia de piedra','un viejo puente de piedra','business','none'),
(1510,'es','¿Por qué está gritando la figura?','¿Por qué está cantando la figura?','gritando en un puente','gritando en una montaña rusa','low_iq','guessing'),
(1513,'es','Manos juntas para rezar.','Manos juntas para aplaudir.','manos juntas para rezar','rezando con las manos abiertas','chill','none'),
(1514,'es','La religión en un cuadro antiguo.','La religión en unos dibujos modernos.','un cuadro sobre religión','un libro sobre religión','nerd','none'),
(1519,'es','¡Qué bonitas son sus flores!','¡Qué bonitas son sus plumas!','flores bonitas en el pelo','cintas bonitas en el pelo','flirt','none'),
(1520,'es','¿Pelo rizado y perlas? Con clase.','¿Pelo corto y perlas? Con clase.','pelo largo, rubio y rizado','un perro de pelo rizado','flirt','none'),
(1522,'es','Tiene una cesta de cerezas.','Tiene una cesta de manzanas.','una cesta de cerezas','un perro en una cesta','chill','none'),
(1523,'es','Pelo rubio lleno de flores.','Pelo negro lleno de flores.','melena rubia larga y ondulada','pelo rubio corto','chill','none'),
(1524,'es','Hace autostop y le para un ovni.','Hace autostop y le para un autobús.','haciendo autostop en la montaña','haciendo autostop en la autopista','gossip','guessing'),
(1525,'es','¡El tren viene hacia nosotros!','¡El camión viene hacia nosotros!','un tren de vapor negro','entrenar para una carrera','dramatic','exclamation'),
(1526,'es','El guerrero lleva casco.','El guerrero lleva escudo.','un guerrero samurái','un guerrero a caballo','chill','none'),
(1527,'es','La catedral tiene una cúpula enorme.','La catedral tiene un tejado plano.','una cúpula de catedral barroca','un coro cantando en la catedral','chill','none'),
(1528,'es','¡Globos sobre Japón!','¡Pájaros sobre Japón!','símbolos de Japón','un mapa de Japón','dramatic','exclamation'),
(1529,'es','Dos torres, un volcán.','Dos torres, dos volcanes.','dos torres redondas de castillo','dos altas torres de agua','chill','none'),
(1530,'es','El pueblo está en una colina. Dicen que las vistas son preciosas.','El pueblo está junto al mar. Dicen que las vistas son preciosas.','un pueblo antiguo en una colina','un pueblo costero nuevo','gossip','none'),
(1531,'es','Un arco enmarca la iglesia.','Un árbol enmarca la iglesia.','un gran arco apuntado','una gran torre puntiaguda','chill','none'),
(1534,'es','¡Hala, un cuerno en cada caballo!','¡Hala, dos cuernos en cada caballo!','el largo cuerno de un unicornio','el claxon ruidoso de un coche','low_iq','exclamation'),
(1537,'es','El faraón de Egipto tiene un arco.','El faraón de Egipto tiene una espada.','un faraón de Egipto','una pirámide en Egipto','chill','none'),
(1538,'es','Está entre dos columnas.','Está entre dos árboles.','dos columnas decoradas','una columna en un periódico','chill','none'),
(1541,'es','Capilla mini, vibes nevadas.','Capilla mini, vibes soleadas.','una capilla blanca nevada','una capilla llena de invitados','slang','none'),
(1543,'es','Sostiene una col enorme.','Sostiene una calabaza enorme.','un huerto lleno de coles','una col en una maceta','chill','none'),
(1544,'es','Está tendiendo la colada.','Está tendiendo las banderas.','tendiendo la colada blanca','doblando la colada blanca','chill','none'),
(1545,'es','¡La gorguera de la reina es enorme!','¡El perro de la reina es enorme!','una reina con cetro','una reina con espada','gossip','none'),
(1548,'es','Hay gente en cada ventana.','Hay gatos en cada ventana.','una familia en cada ventana','un gato en cada ventana','chill','none'),
(1549,'es','¡Alguien ha derramado toda la pintura!','¡Alguien ha derramado toda la leche!','gotas de pintura','una lata de pintura','dramatic','blaming_someone'),
(1551,'es','¡El cielo nos ha enviado una guitarra!','¡El cielo nos ha enviado un violín!','sosteniendo en alto una guitarra','afinando una guitarra','dramatic','exclamation'),
(1554,'es','El monje tiene un paraguas rojo.','El monje tiene un paraguas negro.','un monje de rosa','un monje de negro','chill','none'),
(1555,'es','La figura sostiene una gran espada.','La figura sostiene una gran lanza.','sosteniendo una espada en vertical','una espada en la pared','chill','none'),
(1559,'es','Los girasoles llenan un jarrón amarillo.','Las rosas llenan un jarrón amarillo.','girasoles en un jarrón','girasoles en un campo','chill','none'),
(1560,'es','Está de pie junto a un columpio.','Está de pie junto a una verja.','un columpio de cuerda','un baile swing','chill','none'),
(1562,'es','¡El vaquero cabalga hacia el atardecer!','¡El vaquero cabalga hacia el mar!','un vaquero a caballo','un vaquero sobre un toro','dramatic','cliche'),
(1565,'es','Está hecha de engranajes oxidados.','Está hecha de cadenas oxidadas.','engranajes de metal oxidados','cadenas de metal oxidadas','chill','none'),
(1567,'es','¡El avión está subiendo!','¡El avión está cayendo!','un avión subiendo','un avión bajando','dramatic','exclamation'),
(1568,'es','Navega bajo la luna.','Navega bajo el sol.','navegar de noche','navegar al sol','chill','none'),
(1569,'es','Es un retrato de tramado cruzado.','Es un retrato de acuarela.','un retrato a pluma y tinta','un retrato al óleo','nerd','none'),
(1574,'es','Un farol cuelga de una rama.','Un farol cuelga de un tejado.','un farol con una cadena','un farol en su mano','chill','none'),
(1575,'es','La pareja se está abrazando.','La pareja se está peleando.','una pareja bajo la luna','una pareja en una playa','chill','none'),
(1576,'es','En su sueño, se columpia en la luna.','En su sueño, se columpia en un árbol.','un sueño sobre la luna','un sueño sobre el mar','chill','guessing'),
(1579,'es','Los móviles han construido una casa.','Los libros han construido una casa.','una casa de móviles','un móvil en un bolsillo','chill','exaggeration'),
(1581,'es','¡Vida en furgoneta, colega!','¡Vida en tienda de campaña, colega!','una furgoneta con tabla de surf','una furgoneta con una bici','slang','exclamation'),
(1583,'es','¡El astronauta se aleja volando!','¡El piloto se aleja volando!','un astronauta en el espacio','un astronauta en la luna','dramatic','exclamation'),
(1584,'es','Su falda también está bailando.','Su perro también está bailando.','bailando con falda roja','bailar bajo la lluvia','chill','exaggeration'),
(1585,'es','Hay cinco rosas blancas.','Hay cinco rosas rojas.','cinco flores de rosa blancas','rosas blancas en un jarrón','chill','none'),
(1586,'es','Contaminación mires donde mires.','Flores mires donde mires.','contaminación de una fábrica','contaminación de un barco','dramatic','exaggeration'),
(1589,'es','Esta persona parece triste.','Esta persona parece feliz.','una figura triste de pelo naranja','una figura triste de pelo azul','chill','none'),
(1590,'es','La capucha está llena de estrellas.','La capucha está llena de flores.','una capucha estrellada','una capucha tapando los ojos','chill','none'),
(1591,'es','Este faro tiene rayas.','Este faro tiene lunares.','un faro de rayas','una caseta de playa de rayas','chill','none'),
(1592,'es','El robot tiene los labios azules. ¿Tendrá frío?','El robot tiene los labios rojos. ¿Tendrá frío?','una cabeza de robot metálica','un robot aspirador','low_iq','guessing'),
(1595,'es','Dos pirámides. Muy puntiagudas.','Dos torres. Muy puntiagudas.','dos pirámides marrones','una pirámide de naranjas','low_iq','none'),
(1596,'es','La luna brilla sobre Rusia.','El sol brilla sobre Rusia.','una iglesia en Rusia','un palacio en Rusia','chill','none'),
(1597,'es','¡Uy, tiene la cara bajo el agua!','¡Uy, tiene la cara en la arena!','un perro bajo el agua','un perro sobre el agua','dramatic','exclamation'),
(1598,'es','Jesús levanta una mano.','Jesús levanta las dos manos.','Jesús dando una bendición','Jesús cargando con la cruz','chill','none'),
(1600,'es','Hay un barquito en el canal.','Hay un gran barco en el canal.','un barco en el canal','un barco en el lago','chill','none'),
(1609,'es','¡Está haciendo ballet sobre una roca!','¡Está haciendo ballet sobre un barco!','ballet sobre una roca','ballet en un estudio','dramatic','exclamation'),
(1611,'es','Una paloma vuela en la luz.','Un cuervo vuela en la luz.','una paloma con las alas abiertas','una paloma en una jaula','chill','none'),
(1612,'es','Unos niños de Corea están saludando.','Unos niños de Corea están bailando.','niños de Corea saludando','niños de Corea cantando','chill','none'),
(1613,'es','¡Tres cohetes están despegando!','¡Dos cohetes están despegando!','cohetes elevándose al atardecer','un cohete aterrizando al atardecer','dramatic','exclamation'),
(1614,'es','¡Toros corriendo en España!','¡Caballos corriendo en España!','toros corriendo en España','carreras de caballos en España','dramatic','exclamation'),
(1617,'es','El ángel guía a un niño.','El ángel guía a un cordero.','un ángel guiando a un niño','un ángel tocando el arpa','chill','none'),
(1618,'es','Hay ángeles volando a su alrededor.','Hay pájaros volando a su alrededor.','ángeles alados entre las nubes','ángeles en un árbol de Navidad','chill','none'),
(1619,'es','El gran barco lleva las velas desplegadas.','El gran barco no lleva velas.','velas hinchadas por el viento','velas rotas al viento','chill','none'),
(1620,'es','Hoy el cielo está muy concurrido.','Hoy el cielo está muy vacío.','querubines volando en el cielo','un cielo lleno de santos','ironic','exaggeration'),
(1623,'es','¡Cuántos rascacielos!','¡Cuántos puentes!','rascacielos al anochecer','un rascacielos en construcción','dramatic','exclamation'),
(1629,'es','Solo una piña. Qué soledad.','Solo un plátano. Qué soledad.','una sola piña de pie','una piña en rodajas','dramatic','exaggeration'),
(1630,'es','El pulpo tiene ocho brazos. Los he contado.','El pulpo tiene seis brazos. Los he contado.','un pulpo con ocho brazos','un pulpo en un tarro','low_iq','none'),
(1631,'es','La bruja tiene una escoba. Qué lista.','La bruja tiene un gato. Qué lista.','una bruja con su escoba','una bruja montada en su escoba','low_iq','none'),
(1633,'es','Esta estatua te está mirando.','Este perro te está mirando.','una estatua de gárgola','una estatua de caballo','gossip','guessing'),
(1635,'es','¿Cola de sirena? Verde total.','¿Cola de sirena? Azul total.','una sirena de dibujos sonriente','una sirena sobre una roca','slang','none'),
(1638,'es','Las cortinas enmarcan un mar a la luz de la luna.','Las cortinas enmarcan un mar soleado.','gruesas cortinas moradas','gruesas alfombras moradas','dramatic','none'),
(1639,'es','Dato: el bebé está en un establo.','Dato: el bebé está en un castillo.','un bebé en un establo','un caballo en un establo','nerd','none'),
(1641,'es','Un payaso aterrador y un cuervo.','Un payaso aterrador y un gato.','ojos aterradores en el cielo','una noche de peli aterradora','chill','none'),
(1642,'es','El cielo del pueblo está rojo.','El cielo del pueblo está azul.','un pueblo al atardecer','un pueblo bajo mucha nieve','business','none'),
(1643,'es','Lleva un sombrero de vaquero.','Lleva una gorra de béisbol.','un sombrero de vaquero','un sombrero de paja','chill','none'),
(1644,'es','El caballero lleva armadura completa.','El caballero no lleva armadura.','un caballero con armadura de metal','un caballero sin armadura','chill','none'),
(1647,'es','En la postal hay una mujer.','En la postal hay un hombre.','una postal vieja y rota','una postal de una playa','chill','none'),
(1649,'es','¡Aquí todo es colorido!','¡Aquí todo es gris!','un camino colorido de arcoíris','un paraguas colorido','dramatic','exclamation'),
(1650,'es','Castillo bonito, acantilado de miedo.','Castillo bonito, puente de miedo.','un castillo en un acantilado','un acantilado sobre el mar','gossip','understatement'),
(1651,'es','Su capa azul tiene estrellas.','Su capa roja tiene estrellas.','una capa azul llena de estrellas','una capa hecha de plumas','chill','none'),
(1652,'es','¡Va a tocar la mariposa!','¡Va a tocar el pájaro!','tocar una mariposa brillante','atrapar una mariposa brillante','dramatic','guessing'),
(1655,'es','¡Hala, su corona es altísima!','¡Hala, su corona es pequeñísima!','una corona dorada alta','una corona pequeña de plata','low_iq','exclamation'),
(1656,'es','Tiene los labios rojos.','Tiene los labios azules.','labios rojos brillantes','labios en una copa','chill','none'),
(1658,'es','Piedra oscura, rosas rojas, qué guay.','Piedra oscura, rosas blancas, qué guay.','un arco gótico oscuro','un sendero oscuro en el bosque','slang','none'),
(1660,'es','¡Un cofre lleno de tesoros!','¡Un cofre lleno de botellas!','un cofre del tesoro abierto','un mapa del tesoro en papel','dramatic','exclamation'),
(1661,'es','La hora no está muy clara.','El mapa no está muy claro.','decir la hora','una máquina del tiempo','chill','understatement'),
(1664,'es','El sacerdote está escuchando.','El sacerdote está cantando.','un sacerdote en un confesionario','un sacerdote en una boda','chill','none'),
(1665,'es','Está en un templo antiguo.','Está en un castillo antiguo.','un antiguo templo egipcio','un antiguo templo griego','chill','none'),
(1666,'es','Una cobra se posa sobre el faraón.','Un halcón se posa sobre el faraón.','un faraón de perfil','un faraón en un trono','nerd','none'),
(1667,'es','París de noche. ¡Pura magia!','París a mediodía. ¡Pura magia!','París de noche','París bajo la lluvia','dramatic','exclamation'),
(1669,'es','Dos alas, pero la estatua no puede volar.','Cuatro alas, pero la estatua no puede volar.','dos alas con plumas','dos alas de avión','low_iq','understatement'),
(1670,'es','Un autobús rojo en Londres. Un clásico.','Un coche rojo en Londres. Un clásico.','un autobús rojo en Londres','un autobús rojo en París','chill','cliche'),
(1672,'es','Praga brilla al anochecer.','Praga brilla a mediodía.','el castillo de Praga al anochecer','el castillo de Praga con nieve','chill','none'),
(1674,'es','Cielo morado, colinas moradas.','Cielo morado, colinas verdes.','un cielo morado estrellado','un campo de flores moradas','chill','none'),
(1675,'es','Está solo junto a un árbol.','Está solo junto a una casa.','solo en un campo vacío','solo en una habitación vacía','dramatic','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
