begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(1676,'es','¿Sentarse con un cafecito? Buen rollo.','¿Sentarse con un libro? Buen rollo.','sentarse en un sillón','sentarse al escritorio','slang','cliche'),
(1677,'es','No están mirando la ciudad.','No están mirando sus móviles.','una ciudad al anochecer','una ciudad a mediodía','ironic','cliche'),
(1679,'es','El templo es dorado.','El templo es plateado.','un templo junto a un estanque','un templo en una ciudad','chill','none'),
(1681,'es','¡Qué cola tan larga, pavo real!','¡Qué cola tan corta, pavo real!','un pavo real en una rama','un pavo real en el suelo','dramatic','exclamation'),
(1684,'es','Hasta la Mona Lisa lleva mascarilla ya.','Hasta la Mona Lisa lleva sombrero ya.','una mascarilla médica blanca','una máscara de carnaval','gossip','exaggeration'),
(1685,'es','¡La multitud sale huyendo!','¡La multitud entra corriendo!','una multitud huyendo del templo','una multitud rezando dentro','dramatic','exclamation'),
(1686,'es','Está cargando su propia batería.','Está cargando la batería del móvil.','cargando desde un enchufe','cargando la batería de un coche','low_iq','none'),
(1689,'es','Jesús está de pie junto a una cueva.','Jesús está de pie junto a un lago.','Jesús junto a una cueva','Jesús junto al mar','chill','none'),
(1693,'es','Un caballero blande una espada.','Un caballero blande un hacha.','un caballero con armadura','un caballero a caballo','chill','none'),
(1694,'es','El jefe lleva una pluma.','El jefe lleva una corona.','un jefe con una pluma','un jefe con una corona','chill','none'),
(1695,'es','Tiene una pistola en la mano.','Tiene un móvil en la mano.','sujetando la pistola hacia abajo','sujetando la pistola hacia arriba','chill','none'),
(1697,'es','Abanico y kimono: elegancia total.','Libro y kimono: elegancia total.','un abanico abierto','un ventilador en verano','flirt','none'),
(1699,'es','Alguien nada al ritmo de la música.','Alguien vuela al ritmo de la música.','nadando en aguas tranquilas','nadando en una piscina','chill','none'),
(1701,'es','Un lirio crece de una jarra.','Una rosa crece de una jarra.','un lirio en una jarra','un lirio en un estanque','chill','none'),
(1703,'es','Lee suspendida en el aire.','Duerme suspendida en el aire.','leyendo un libro que brilla','leyendo un mensaje','chill','none'),
(1704,'es','Pone ''Feliz Navidad''.','Pone ''Feliz cumpleaños''.','una vieja tarjeta de Navidad','un viejo árbol de Navidad','chill','none'),
(1709,'es','La profesora está explicando.','La profesora está durmiendo.','una profesora en la pizarra','una profesora en su mesa','chill','none'),
(1710,'es','La pizarra está vacía.','La pizarra está llena.','una pizarra vacía','una pizarra llena de apuntes','chill','none'),
(1711,'es','El esqueleto parece muy feliz.','El esqueleto parece muy triste.','un esqueleto con un lazo','un esqueleto en un museo','ironic','none'),
(1713,'es','Cientos de plumas en lo alto.','Cientos de flores en lo alto.','un tocado de plumas largas','una almohada llena de plumas','chill','exaggeration'),
(1716,'es','El traje espacial es blanco.','El traje espacial es naranja.','un traje espacial blanco','un traje espacial en una percha','chill','none'),
(1717,'es','Este instrumento es un violín.','Este instrumento es una guitarra.','un instrumento de cuerda','un instrumento de viento','nerd','none'),
(1718,'es','El Buda está 100 % tranquilo.','El Buda está 100 % enfadado.','una cara tranquila','un mar tranquilo','nerd','exaggeration'),
(1724,'es','¡Está sosteniendo la luna!','¡Está sosteniendo el sol!','sosteniendo la luna','sosteniendo una amapola','dramatic','exclamation'),
(1725,'es','Una cruz yace en el suelo.','Una escalera yace en el suelo.','una cruz en el suelo','una cruz en una iglesia','chill','none'),
(1726,'es','Hace girar una capa roja.','Hace girar una bufanda roja.','haciendo girar una capa roja','con capa y antifaz','chill','none'),
(1728,'es','¡Abanico rojo arriba, pierna arriba!','¡Sombrero rojo arriba, pierna arriba!','agitando un abanico rojo','un ventilador de techo','dramatic','exclamation'),
(1729,'es','Tiene dos mascotas.','Tiene tres mascotas.','una chica con sus mascotas','una chica comprando una mascota','chill','none'),
(1731,'es','¡Una flecha le dio a su bandera!','¡Una flecha le dio a su caballo!','flechas en una bandera','flechas en una diana','dramatic','exclamation'),
(1733,'es','¿Adivina qué sujeta el elfo? Una luz.','¿Adivina qué sujeta el elfo? Una espada.','un elfo con orejas puntiagudas','un elfo con un arco','gossip','guessing'),
(1734,'es','Este superhéroe es Spider-Man.','Este superhéroe es Batman.','un superhéroe con máscara','un superhéroe con capa','chill','none'),
(1738,'es','Lleva un velo largo y oscuro.','Lleva un velo largo y blanco.','un velo largo y oscuro','un velo de novia','chill','none'),
(1741,'es','El emperador lleva laureles.','El emperador lleva una corona.','un emperador con laureles','un emperador a caballo','nerd','none'),
(1742,'es','El ángel sostiene un escudo.','El ángel sostiene una espada.','un gran escudo redondo','un escudo en el suelo','chill','none'),
(1743,'es','¿Helado en Italia? Pues claro.','¿Pizza en Italia? Pues claro.','una torre inclinada en Italia','un horno de pizza en Italia','chill','cliche'),
(1751,'es','Cada cartel muestra un paisaje.','Cada cartel muestra una ciudad.','carteles de flecha con paisajes','carteles de flecha con precios','chill','none'),
(1756,'es','Están discutiendo por teléfono.','Están cantando por teléfono.','discutiendo por teléfono','discutiendo en la cocina','chill','none'),
(1757,'es','¿Música bajo las flores? Qué romántico.','¿Baile bajo las flores? Qué romántico.','flores de cerezo rosas','té de flor de cerezo','flirt','none'),
(1762,'es','¡Un hombre está cayendo dentro de una ballena!','¡Un hombre está cayendo dentro de un barco!','la boca de una ballena','una ballena en un acuario','dramatic','exclamation'),
(1765,'es','¡Qué codicioso! ¡Fuera las manos del oro!','¡Qué codicioso! ¡Fuera las manos del pastel!','un hombre codicioso con monedas','un perro codicioso con comida','dramatic','exclamation'),
(1766,'es','Moras negras y rojas.','Moras negras y verdes.','moras maduras en una rama','moras en una tarta','chill','none'),
(1777,'es','Este tío está tocando el banjo.','Este tío está tocando la batería.','tocando un banjo','afinando un banjo','slang','none'),
(1779,'es','¡Su cadena está fuera de control!','¡Su cuerda está fuera de control!','una cadena girando a su alrededor','una cadena al cuello','dramatic','exaggeration'),
(1780,'es','¡Un perro persigue su bici!','¡Un gato persigue su bici!','un paseo en bici cuesta abajo','un paseo en bici cuesta arriba','dramatic','exclamation'),
(1783,'es','Cuatro niños, un regazo, un abrazo para cada niño.','Cuatro niños, un regazo, un regalo para cada niño.','un hombre abrazando a cada niño','un hombre enseñando a cada niño','chill','none'),
(1785,'es','Es un dibujo hermoso.','Es una foto hermosa.','un retrato hermoso','un atardecer hermoso','chill','none'),
(1786,'es','Caen meteoros como lluvia.','Caen hojas como lluvia.','una lluvia de meteoros','un meteoro en un museo','nerd','none'),
(1787,'es','Bufanda roja bajo una farola. Con estilo.','Bufanda azul bajo una farola. Con estilo.','una farola encendida','una farola rota','flirt','none'),
(1788,'es','¡Un monstruo marino con pasajeros!','¡Una tortuga marina con pasajeros!','un monstruo marino emergiendo','un monstruo debajo de la cama','dramatic','exclamation'),
(1792,'es','Están construyendo una torre.','Están construyendo un barco.','construir una torre enorme','construir una casa pequeña','chill','none'),
(1794,'es','¡Cuántas plumas de pavo real!','¡Cuántas plumas de cisne!','plumas de pavo real brillantes','una pluma en una almohada','dramatic','exclamation'),
(1799,'es','El violonchelo es el más grande.','El violín es el más grande.','un violonchelo grande y oscuro','un violonchelo pequeño y oscuro','nerd','none'),
(1800,'es','Están escondiendo una sonrisa.','Están escondiendo un móvil.','escondiéndose detrás de un libro','escondiéndose debajo de una mesa','chill','guessing'),
(1802,'es','¡De la guitarra salen chorros de notas!','¡De la guitarra salen chorros de monedas!','una cascada de notas','un taco de notas','dramatic','exclamation'),
(1803,'es','Va a lanzar la pelota.','Va a chutar la pelota.','a punto de lanzar la pelota','lanzar un frisbi','chill','none'),
(1807,'es','Hay cráneos flotando a su alrededor.','Hay corazones flotando a su alrededor.','cráneos entre llamas rosas','cráneos en una bandera pirata','chill','none'),
(1808,'es','Su casco es enorme, tío.','Su gorro es enorme, tío.','un casco aparatoso','un piloto con casco','slang','none'),
(1811,'es','El impermeable está cumpliendo su función.','El paraguas está cumpliendo su función.','un impermeable largo y amarillo','un impermeable en un perchero','business','none'),
(1812,'es','El gato también está mirando fuera.','El perro también está mirando fuera.','mirando por la ventana','cuidar a un gato','chill','none'),
(1823,'es','Esta noche se siente sola.','Esta mañana se siente sola.','sola en un balcón','sola entre la multitud','dramatic','none'),
(1827,'es','El gato odia las mates.','El perro odia las mates.','paredes llenas de mates','libros de mates en el suelo','low_iq','guessing'),
(1831,'es','Hay una cabaña dentro de la bombilla.','Hay una cabaña dentro de la taza.','una bombilla nevada','una bombilla rota','chill','none'),
(1832,'es','Está haciendo una foto. ¡Qué guay!','Está haciendo una llamada. ¡Qué guay!','haciendo una foto de noche','haciendo una foto en casa','slang','exclamation'),
(1833,'es','Está apoyado en su guitarra.','Está apoyado en su piano.','apoyado en una guitarra','apoyado en un árbol','chill','none'),
(1834,'es','Un dios está enseñando a un guerrero.','Un dios está enseñando a un niño.','enseñando a un guerrero','enseñando a una multitud','chill','none'),
(1840,'es','¡Una máquina gigante hecha de engranajes!','¡Una máquina gigante hecha de madera!','una máquina de engranajes oxidados','una máquina de café','dramatic','exaggeration'),
(1843,'es','Un barrio nevado de noche.','Un barrio nevado a mediodía.','un barrio nevado','una fiesta de barrio','chill','none'),
(1846,'es','Una grulla vuela junto al sol.','Una grulla vuela junto a la luna.','una grulla blanca volando','una grúa levantando cajas','chill','none'),
(1847,'es','Cuento tres árboles de Navidad.','Cuento cinco árboles de Navidad.','tres arbolitos de Navidad','un árbol de Navidad con regalos','low_iq','none'),
(1849,'es','¡Su magia está brillando!','¡Su pelo está brillando!','magia azul brillante','un truco de magia con cartas','dramatic','exclamation'),
(1851,'es','La niebla se traga los valles.','La nieve se traga los valles.','niebla en el valle','un valle lleno de casas','dramatic','none'),
(1853,'es','El dragón escupe fuego.','El dragón escupe hielo.','un pequeño dragón blanco','un gran dragón verde','chill','none'),
(1854,'es','La guitarra tiene cuerdas blancas.','La guitarra tiene cuerdas negras.','cuerdas blancas en una guitarra','cuerdas blancas en una cometa','nerd','none'),
(1855,'es','¡El pavo real tiene una cola enorme!','¡El pavo real tiene una cola corta!','un pavo real luciendo la cola','un pavo real escondiendo la cola','dramatic','exaggeration'),
(1856,'es','La figura es diminuta. El cielo es grande.','La figura es enorme. El cielo es grande.','una figura diminuta en la hierba','una figurita diminuta en una estantería','low_iq','none'),
(1857,'es','Es un cartel de Pascua.','Es un cartel de Navidad.','un cartel de Pascua','una búsqueda de huevos de Pascua','chill','none'),
(1858,'es','El niño tiene una bufanda larga y un globo grande.','El niño tiene una espada larga y un globo grande.','una bufanda larga de rayas','una bufanda en un cajón','chill','none'),
(1860,'es','Su cabeza es una pila de libros.','Su cabeza es una pila de platos.','una pila de libros','una pila de cajas','ironic','none'),
(1861,'es','Este asiento antiguo tiene un cisne.','Este asiento antiguo tiene un león.','un asiento antiguo tallado','un reloj antiguo tallado','chill','none'),
(1862,'es','El jarrón tiene rosas rosadas.','El jarrón tiene rosas blancas.','un jarrón clásico gris','un jarrón clásico roto','chill','none'),
(1863,'es','¡El columpio cuelga de la luna!','¡El columpio cuelga de un árbol!','colgando de la luna','colgando de un árbol','dramatic','exclamation'),
(1865,'es','¿Esas aletas azules? Pura moda.','¿Esas aletas rojas? Pura moda.','grandes aletas ondulantes','aletas de buceo','gossip','exaggeration'),
(1866,'es','Gafas de sol y pistola: un espía de manual.','Gafas de sol y cuchillo: un espía de manual.','un espía con pistola','un espía con cámara','ironic','cliche'),
(1868,'es','La justicia necesita muchos libros gordos.','La justicia necesita muchas velas.','la balanza de la justicia','la espada de la justicia','chill','exaggeration'),
(1870,'es','¡El pelo le llega a los pies!','¡El pelo le llega a la barbilla!','pelo oscuro muy largo','un pelo en la sopa','dramatic','exaggeration'),
(1871,'es','Su ojo brilla de color blanco.','Su ojo brilla de color rojo.','un ojo brillando en blanco','una lámpara brillando en blanco','chill','none'),
(1872,'es','El gato negro adora los libros.','El gato blanco adora los libros.','un gato negro sobre libros','un gato negro en la calle','chill','guessing'),
(1874,'es','Están sentados en el muelle.','Están sentados en el barco.','sentados en un muelle','sentados en un puente','chill','none'),
(1876,'es','Casco low cost: una pecera.','Casco low cost: un cubo.','una pecera en la cabeza','una pecera en la mesa','ironic','cheap_quality'),
(1878,'es','¡Su cabeza es invisible!','¡Su traje es invisible!','una cabeza invisible','una mano invisible','dramatic','exclamation'),
(1879,'es','¡La cúpula brilla como el oro!','¡La cúpula brilla como la plata!','una cúpula dorada','una cúpula de cristal','dramatic','none'),
(1880,'es','El mejor invento de la historia: un barco volador.','El mejor invento de la historia: un coche volador.','un invento volador','un invento con ruedas','slang','exaggeration'),
(1881,'es','Está meditando con calma.','Está durmiendo con calma.','meditando en posición de loto','meditando antes de un examen','chill','none'),
(1883,'es','Las gallinas comen fuera.','Las gallinas comen dentro.','gallinas en un corral','gallinas en una cocina','chill','none'),
(1884,'es','El reflejo está del revés.','El reflejo está muy borroso.','un reflejo en agua quieta','un reflejo en un espejo','nerd','none'),
(1885,'es','El hombre rico está arriba del todo.','El hombre rico está abajo del todo.','un hombre rico en la cima','un hombre rico en la cárcel','chill','none'),
(1886,'es','El plato del consumidor está vacío.','El plato del consumidor está lleno.','un consumidor hambriento','un consumidor en una tienda','business','none'),
(1887,'es','Está empujando un carro pesado.','Está empujando un coche pesado.','empujando un carro sobrecargado','empujando un carrito de bebé','chill','none'),
(1889,'es','¡Se mueve como un rayo!','¡Está sentada como una estatua!','moviéndose al ritmo de la música','mudándose a un piso nuevo','slang','exaggeration'),
(1892,'es','El viejo tiene un bastón fino.','El viejo tiene un paraguas.','el bastón del viejo','el paraguas del viejo','chill','none'),
(1897,'es','Estas calabazas son del cuervo.','Estas calabazas son del gato.','tres calabazas apiladas','una tarta de calabaza','low_iq','guessing'),
(1899,'es','Dos gigantes se sientan junto a las ruinas.','Dos leones se sientan junto a las ruinas.','ruinas de templos antiguos','ruinas de un castillo','chill','none'),
(1905,'es','¡Estos gatos son supercuriosos!','¡Estos perros son supercuriosos!','tres gatos curiosos','tres gatos dormilones','dramatic','exclamation'),
(1906,'es','Tiene el pelo azul.','Tiene el pelo rojo.','pelo largo y azul','un vestido azul de verano','chill','none'),
(1908,'es','Tío, la garza está en modo chill.','Tío, el cisne está en modo chill.','una garza en una rama','una garza en el agua','slang','none'),
(1909,'es','La hoja de su espada brilla.','La hoja de su espada está oxidada.','una larga hoja de acero','una hoja corta y rota','chill','none'),
(1910,'es','Tiene un montón de pétalos rosas.','Tiene un montón de plumas rosas.','grandes pétalos rosas','pétalos en el suelo','slang','exaggeration'),
(1911,'es','Esta princesa tiene un estilazo.','Este príncipe tiene un estilazo.','una princesa de azul','una princesa de rojo','flirt','none'),
(1912,'es','Sus tatuajes son azules.','Sus tatuajes son rojos.','tatuajes faciales azules en espiral','un tatuaje en la mano','chill','none'),
(1914,'es','El piano está abierto. ¿Tiene hambre?','La puerta está abierta. ¿Tiene hambre?','un piano de cola abierto','una clase de piano','low_iq','guessing'),
(1915,'es','El contrabajo tiene cuatro cuerdas.','El contrabajo tiene seis cuerdas.','un contrabajo de cuatro cuerdas','un contrabajo de seis cuerdas','nerd','none'),
(1916,'es','Hay ovnis en el cielo.','Hay pájaros en el cielo.','ovnis en el cielo','un ovni aterrizando','chill','none'),
(1917,'es','Un casco diseñado para la velocidad.','Un casco diseñado para el ciclismo.','un casco hecho para la velocidad','velocidad en bicicleta','business','none'),
(1921,'es','Una cara conmocionada junto al agua.','Una cara conmocionada en el bosque.','una cara conmocionada que grita','conmocionado por la factura del móvil','chill','none'),
(1922,'es','Estudiar le da dolor de cabeza.','Cocinar le da dolor de cabeza.','estudiando un libro enorme','estudiando en el jardín','dramatic','guessing'),
(1923,'es','¡Las estanterías de libros están a reventar!','¡Las estanterías de libros están vacías!','altas estanterías llenas de libros','una estantería de libros vacía','dramatic','exaggeration'),
(1924,'es','¡Cuántos colores vivos!','¡Cuántos colores apagados!','remolinos de colores vivos','un sueño muy vivo','gossip','exclamation'),
(1926,'es','¡El cráneo tiene todos sus dientes!','¡El cráneo no tiene dientes!','los dientes sonrientes de un cráneo','los dientes afilados de un perro','dramatic','exclamation'),
(1927,'es','¿Raíces de oro? No es un árbol barato.','¿Hojas de oro? No es un árbol barato.','raíces doradas con joyas','hojas doradas con joyas','ironic','cheap_quality'),
(1928,'es','El centro brilla en rojo. Qué guay.','El centro brilla en verde. Qué guay.','una calle del centro con neones','una mañana tranquila en el centro','slang','none'),
(1930,'es','El pueblo medieval parece acogedor.','La ciudad moderna parece acogedora.','un pueblo medieval de piedra','un día de mercado medieval','chill','none'),
(1931,'es','Una calle lluviosa de la ciudad.','Una calle soleada de la ciudad.','una calle lluviosa','una playa lluviosa','chill','none'),
(1932,'es','El ordenador está en una mesa roja.','El ordenador está en un sofá rojo.','un ordenador en una mesa','un ordenador en el regazo','chill','none'),
(1933,'es','Es un espíritu del árbol.','Es un espíritu del agua.','un viejo espíritu del árbol','un espíritu del océano','chill','none'),
(1934,'es','Estas estanterías son surrealistas.','Estas estanterías son normales.','estanterías surrealistas que se doblan','un reloj surrealista derretido','nerd','none'),
(1935,'es','Está atardeciendo en Nueva York.','Es de noche en Nueva York.','Nueva York al atardecer','Nueva York de noche','chill','none'),
(1936,'es','¡Su corona de flores es enorme!','¡Su corona de plumas es enorme!','con una corona de flores','haciendo una corona de flores','dramatic','exclamation'),
(1937,'es','El hacker lleva capucha.','El hacker lleva gorra.','un hacker con capucha','un hacker en el parque','chill','none'),
(1938,'es','Una ballena solitaria frente a la costa.','Un tiburón solitario frente a la costa.','una costa de arena desde arriba','una costa rocosa con acantilados','dramatic','none'),
(1940,'es','Los dientes de león rodean su cabeza.','Las rosas rodean su cabeza.','vilanos blancos de diente de león','soplando un diente de león','chill','none'),
(1941,'es','Este ratón pirata es clavado a Jack Sparrow.','Este gato pirata es clavado a Jack Sparrow.','un ratón pirata','un barco pirata','slang','exaggeration'),
(1943,'es','El gorro del gnomo es verde. Hala.','El gorro del gnomo es rojo. Hala.','un gnomo de verde','un gnomo de rojo','low_iq','none'),
(1944,'es','Dato: se le ven las costillas.','Dato: se le ve el corazón.','un armazón de costillas','costillas a la parrilla','nerd','none'),
(1945,'es','¡Qué castillo tan tenebroso!','¡Qué iglesia tan tenebrosa!','un castillo tenebroso sobre rocas','un castillo tenebroso en la nieve','dramatic','exclamation'),
(1947,'es','Una melena arcoíris normal y corriente.','Una melena negra normal y corriente.','una melena arcoíris','un arcoíris sobre un león','ironic','understatement'),
(1948,'es','¡Su pelo ondulado está por todas partes!','¡Su pelo corto está por todas partes!','pelo ondulado lleno de hojas','pelo ondulado lleno de flores','dramatic','exclamation'),
(1949,'es','Este bosque está encantado total.','Este bosque está quemado total.','un sendero de bosque encantado','un castillo encantado','slang','none'),
(1950,'es','Esta torre malvada necesita un ascensor.','Esta iglesia malvada necesita un ascensor.','una fortaleza malvada','una madrastra malvada','ironic','exaggeration'),
(1951,'es','Un sillón espera a un lector.','Un sofá espera a un lector.','un sillón de cuero gastado','un sillón de plástico nuevo','chill','guessing'),
(1952,'es','Una luna llena detrás de un árbol.','Una luna llena detrás de dos árboles.','luna llena tras un árbol','luna llena sobre el mar','chill','none'),
(1953,'es','¿Corona de copos de nieve? Rollo reina.','¿Corona de flores? Rollo reina.','una corona de copos de nieve','copos de nieve en una ventana','flirt','exaggeration'),
(1955,'es','Madre mía, es una casa de cuento de hadas.','Madre mía, es un barco de cuento de hadas.','una cabaña de cuento de hadas','un castillo de cuento de hadas','gossip','none'),
(1957,'es','Los adoquines están mojados.','Los adoquines están nevados.','adoquines mojados de noche','adoquines en una playa','chill','none'),
(1958,'es','Escaleras de piedra y flores rosas.','Escaleras de piedra y flores rojas.','escaleras de piedra en un pueblo','escaleras de piedra en un castillo','chill','none'),
(1959,'es','La trenza le llega a la cintura.','La trenza le llega a las rodillas.','una trenza hasta la cintura','una trenza corta','chill','none'),
(1960,'es','Camina como una auténtica samurái.','Baila como una auténtica samurái.','un samurái con espada','un samurái con arco','flirt','none'),
(1961,'es','A estos huesos les encanta un buen libro.','A estos huesos les encanta una buena peli.','huesos sobre un libro abierto','un perro con un hueso','gossip','guessing'),
(1962,'es','¡Esta fortaleza da miedo!','¡Esta cabaña da miedo!','una fortaleza oscura en una colina','una fortaleza en el desierto','dramatic','exclamation'),
(1964,'es','Esa casa tiene que estar embrujada.','Ese colegio tiene que estar embrujado.','una vieja casa embrujada','un viejo barco embrujado','gossip','guessing'),
(1965,'es','Cabaña acogedora. Un poquito de nieve.','Cabaña acogedora. Un poquito de arena.','una cabaña de madera nevada','un camarote en un barco','ironic','understatement'),
(1966,'es','El sendero es de piedras.','El sendero es de madera.','un sendero empedrado','un sendero del bosque','chill','none'),
(1967,'es','¡El zorrito es adorable!','¡El osito es adorable!','un zorrito adorable','un pajarito adorable','dramatic','exclamation'),
(1968,'es','Creo que son cuervos.','Creo que son loros.','cuervos volando a su alrededor','cuervos posados en su brazo','low_iq','guessing'),
(1969,'es','¿Un ramo desde el espacio? ¡Qué romántico!','¿Un ramo desde el mar? ¡Qué romántico!','recogiendo un ramo','lanzando un ramo','flirt','exclamation'),
(1970,'es','La cabaña tiene una puerta de tablones. Básica, pero sólida.','La cabaña tiene una puerta de cristal. Básica, pero sólida.','una cabañita nevada','una cabañita de playa','business','cheap_quality'),
(1971,'es','Cimas sobre las nubes. Brutal.','Cimas bajo las nubes. Brutal.','cimas nevadas sobre las nubes','cimas cubiertas de bosque','slang','none'),
(1972,'es','¡Ese turbante es una torre entera!','¡Esa corona es una torre entera!','un turbante alto con joyas','un turbante en el desierto','dramatic','exaggeration'),
(1973,'es','Esta diosa parece egipcia.','Esta diosa parece japonesa.','una diosa con alas doradas','una diosa con un arco','nerd','none'),
(1974,'es','La bailarina está de puntillas.','La bailarina está de rodillas.','una bailarina con tutú','una zapatilla de bailarina','chill','none'),
(1976,'es','Cuatro niños patinan mientras las ardillas los juzgan.','Cuatro niños patinan mientras los perros los juzgan.','patinando en un estanque helado','patinando en una rampa','ironic','guessing'),
(1977,'es','¡Los murciélagos lo hacen aún más espeluznante!','¡Los búhos lo hacen aún más espeluznante!','una casa en ruinas espeluznante','una muñeca antigua espeluznante','dramatic','exclamation'),
(1979,'es','Se lo ha teñido de morado. ¡Qué atrevida!','Se lo ha teñido de verde. ¡Qué atrevida!','pelo teñido de morado intenso','pelo teñido de verde intenso','gossip','exclamation'),
(1982,'es','La habitación está «un poco» abarrotada.','La habitación está «un poco» vacía.','estanterías abarrotadas','un escritorio abarrotado','ironic','understatement'),
(1983,'es','Tiene las pestañas muy largas.','Tiene las pestañas muy cortas.','pestañas largas y oscuras','pestañas postizas en una caja','chill','none'),
(1984,'es','Tiene la cara muy pálida.','Tiene la cara muy oscura.','una cara pálida y blanca','un cielo azul pálido','chill','none'),
(1985,'es','¡El árbol es rojo brillante!','¡El árbol es verde brillante!','hojas de un rojo brillante','manzanas de un rojo brillante','dramatic','exclamation'),
(1986,'es','El árbol está desnudo. Qué pena.','El árbol está verde. Qué pena.','un árbol desnudo de noche','pies desnudos en la hierba','low_iq','none'),
(1987,'es','Esta ciudad es del futuro.','Esta ciudad es del pasado.','una ciudad del futuro','una ciudad del pasado','business','none'),
(1988,'es','La valla tiene pinchos afilados.','La valla no tiene puerta.','una valla de hierro con pinchos','una valla de madera de jardín','chill','none'),
(1989,'es','Viejas pociones llenan los estantes.','Viejos zapatos llenan los estantes.','estantes de pociones antiguas','una poción en un caldero','chill','none'),
(1990,'es','Un sillón supercómodo.','Un sofá supercómodo.','un sillón dorado cómodo','una cama dorada cómoda','slang','none'),
(1991,'es','¡Teclea como una máquina!','¡Pinta como una máquina!','tecleando en un teclado','tecleando en un móvil','slang','exclamation'),
(1992,'es','Escucha con unos cascos verdes enormes.','Escucha con unos cascos rojos enormes.','escuchando música','escuchando a un profesor','chill','none'),
(1994,'es','Un gato está encima de los libros.','Un gato está encima del seto.','encima de los libros','encima del coche','chill','none'),
(1995,'es','Este umbral lleva a otro mundo.','Este umbral lleva a un sótano oscuro.','un umbral en arco que brilla','el umbral de la cocina','dramatic','guessing'),
(1997,'es','¡Esa hacha de guerra es enorme!','¡Ese escudo de guerra es enorme!','sujetando un hacha de guerra','sujetando una bandera de guerra','dramatic','exclamation'),
(1998,'es','En esta mansión vive gente rica.','En esta cabaña vive gente rica.','una mansión al anochecer','una mansión en la playa','gossip','guessing'),
(1999,'es','Tío, qué pelaje más espeso.','Tío, qué pelaje más negro.','pelaje blanco y espeso','un abrigo de pelo blanco','slang','none'),
(2000,'es','La luz de luna brilla sobre el agua.','La luz del sol brilla sobre el agua.','luz de luna sobre una marisma','luz de luna en un dormitorio','chill','none'),
(2001,'es','El búho tiene el pico de oro. ¡Búho rico!','El búho tiene el pico rojo. ¡Búho rico!','el pico dorado de un búho','el pico roto de un búho','low_iq','exaggeration'),
(2002,'es','El gato tiene los bigotes largos.','El gato tiene los bigotes cortos.','un gato con bigotes largos','un hombre con bigote largo','chill','none'),
(2005,'es','El cuervo espera noticias.','El búho espera noticias.','un cuervo en una rama','un cuervo sobre un espantapájaros','dramatic','guessing'),
(2008,'es','El tronco es enorme y retorcido.','El tronco es fino y liso.','un tronco enorme y retorcido','la trompa de un elefante','chill','none'),
(2010,'es','¡La historia está cobrando vida!','¡La historia está ardiendo!','una historia que cobra vida','una historia sobre una ciudad','dramatic','exclamation'),
(2011,'es','La puerta está abierta de par en par.','La puerta está cerrada.','una puerta de cristal abierta','un portátil abierto','chill','none'),
(2013,'es','¿Su maquillaje? Gótico total.','¿Su maquillaje? Rosa total.','un look gótico','una iglesia gótica','gossip','none'),
(2014,'es','A solas al anochecer. Qué misterio.','A solas a mediodía. Qué misterio.','un callejón antiguo al anochecer','anochecer en una playa vacía','dramatic','cliche'),
(2015,'es','Dato: el monumento es de piedra.','Dato: el monumento es de madera.','un antiguo monumento de piedra','un monumento en una plaza','nerd','none'),
(2016,'es','Harry Potter necesita esta varita mágica, tío.','Harry Potter necesita esta escoba, tío.','una varita mágica brillante','una varita mágica rota','slang','guessing'),
(2019,'es','La locomotora funciona con vapor.','La locomotora funciona con diésel.','una vieja locomotora de vapor','una vieja locomotora diésel','nerd','none'),
(2021,'es','Las constelaciones llenan el cielo.','Los arcoíris llenan el cielo.','constelaciones sobre la casa','constelaciones en un mapa','nerd','none'),
(2024,'es','¡Letreros de neón por todas partes!','¡Letreros de papel por todas partes!','letreros de neón rosas y verdes','una chaqueta verde neón','slang','exclamation'),
(2025,'es','Ciudad futurista, ¿año 3000?','Pueblo futurista, ¿año 3000?','torres futuristas de noche','un coche volador futurista','nerd','guessing'),
(2026,'es','¡Qué despacho más de ensueño!','¡Qué cocina más de ensueño!','un despacho lleno de flores','un despacho lleno de estudiantes','slang','exclamation'),
(2028,'es','Una jarra blanca entre libros.','Un gato blanco entre libros.','una jarra en una estantería','una jarra en una mesa','chill','none'),
(2029,'es','El sendero desaparece en la niebla.','El sendero desaparece en el mar.','un sendero pedregoso de montaña','un rastro de huellas','dramatic','none'),
(2031,'es','Tiene ramitas en el pelo. Qué raro.','Tiene flores en el pelo. Qué raro.','ramitas en el pelo','un nido de ramitas','low_iq','none'),
(2032,'es','Un portal a una ciudad dorada.','Un portal a un bosque oscuro.','un portal redondo brillante','un portal bajo el mar','chill','none'),
(2033,'es','¡La guitarra está en un remolino!','¡La guitarra está en un desierto!','una guitarra en un remolino','un barco en un remolino','dramatic','exclamation'),
(2034,'es','Esta amapola es roja. Muy roja.','Esta amapola es azul. Muy azul.','una amapola roja en flor','un campo de amapolas','low_iq','none'),
(2035,'es','Este romance tiene un corazón rosa.','Este romance tiene un corazón rojo.','un romance en primavera','una novela romántica','flirt','none'),
(2036,'es','Las lanzas, claramente, no escasean.','Las espadas, claramente, no escasean.','un ejército alzando lanzas','un ejército arrojando lanzas','business','understatement'),
(2037,'es','Una criatura con alas oscuras.','Una criatura con cuernos largos.','una criatura oscura con alas','una criatura en el mar','chill','none'),
(2038,'es','Está asustada, y los pájaros lo saben.','Está asustada, y los lobos lo saben.','asustada en un bosque oscuro','asustada por un perro grande','dramatic','guessing'),
(2040,'es','Hay decoraciones en todos los tejados.','Hay muñecos de nieve en todos los tejados.','decoraciones en los tejados','decoraciones en una caja','chill','none'),
(2041,'es','¡En esta botella vive una puesta de sol entera!','¡En esta botella vive un océano entero!','una botella de cristal oscuro','una botella de vino tinto','dramatic','exaggeration'),
(2042,'es','¡Esa luna es enorme!','¡Ese sol es enorme!','una enorme luna llena','un enorme castillo antiguo','dramatic','exclamation'),
(2045,'es','Estas piedras son superaltas.','Estos árboles son superaltos.','altas piedras erguidas','árboles altos en un campo','slang','exaggeration'),
(2046,'es','Noche nevada en el bosque. Qué silencio...','Noche nevada en la ciudad. Qué silencio...','un bosque nevado de noche','una calle nevada de noche','dramatic','none'),
(2048,'es','¡Este lobo es salvaje!','¡Este perro es salvaje!','un lobo salvaje','una fiesta salvaje','dramatic','exclamation'),
(2052,'es','La taza está sobre una pila de libros.','La taza está sobre una pila de cajas.','una taza plateada sobre libros','una taza de leche fría','chill','none'),
(2053,'es','Hay botellas en todos los estantes.','Hay libros en todos los estantes.','estantes de botellas viejas','estantes de libros viejos','chill','none'),
(2055,'es','El «Rejuvenecedor» es veneno.','El «Rejuvenecedor» es zumo.','una botella de veneno','una botella de vino','ironic','none'),
(2056,'es','Los estantes están llenos de libros.','Los estantes están llenos de tarros.','estantes llenos de libros viejos','estantes llenos de juguetes viejos','chill','none'),
(2058,'es','Un oso intenta alcanzar una estrella.','Un oso intenta alcanzar un pájaro.','intentando alcanzar una estrella','intentando alcanzar la miel','chill','none'),
(2059,'es','La luz del sol solo da en un lado.','La luz de la luna solo da en un lado.','ramas bajo la luz del sol','luz del sol sobre el agua','nerd','none'),
(2061,'es','La galaxia se está luciendo.','La luna se está luciendo.','una galaxia morada brillante','una galaxia en una camiseta','slang','exaggeration'),
(2062,'es','Alguien ha equilibrado estas piedras.','Alguien ha equilibrado estas tazas.','piedras equilibradas en una torre','equilibrarse sobre una pierna','gossip','guessing'),
(2064,'es','La bola de nieve tiene una iglesia.','La bola de nieve tiene un castillo.','una bola de nieve que brilla','una bola de nieve rota','chill','none'),
(2067,'es','Una farola, mucha nieve.','Una farola, mucha lluvia.','una farola encendida','un perro junto a una farola','chill','understatement'),
(2068,'es','La puerta roja está abierta.','La puerta azul está abierta.','una puerta roja abierta','una puerta roja de garaje','chill','none'),
(2069,'es','El reno ha tenido un mal vuelo.','El reno ha tenido un vuelo divertido.','un reno atascado en un aerogenerador','un reno tirando de un trineo','chill','understatement'),
(2070,'es','¡La guitarra eléctrica es un cohete!','¡La guitarra eléctrica se está hundiendo!','una guitarra eléctrica despegando','una guitarra eléctrica en el escenario','slang','exaggeration'),
(2071,'es','Bonito coche vintage, muy festivo.','Bonita furgoneta vintage, muy festiva.','un coche rojo vintage','un vestido rojo vintage','flirt','none'),
(2072,'es','¡Los cables cubren toda la habitación!','¡Las plantas cubren toda la habitación!','cables azules brillantes','cables en un puente','dramatic','exaggeration'),
(2075,'es','Hay libros en el alféizar.','Hay gatos en el alféizar.','libros en un alféizar','plantas en un alféizar','chill','none'),
(2076,'es','Tanta literatura y tan poco tiempo.','Tantas pizzas y tan poco tiempo.','estanterías de literatura antigua','literatura en el móvil','nerd','cliche'),
(2077,'es','¡El búho me está mirando fijamente!','¡El gato me está mirando fijamente!','mirando fijamente al espectador','mirando fijamente la luna','dramatic','exclamation'),
(2078,'es','Dos llamas iluminan el libro.','Tres llamas iluminan el libro.','dos llamas de vela','llamas en una chimenea','chill','none'),
(2079,'es','Aquí todo es de madera.','Aquí todo es de plástico.','altas estanterías de madera','altas escaleras de madera','low_iq','exaggeration'),
(2080,'es','Nieva sobre la pagoda.','Llueve sobre la pagoda.','una pagoda roja en la nieve','una pagoda en la selva','chill','none'),
(2081,'es','Unas pasaderas cruzan un lago.','Unas pasaderas cruzan una carretera.','pasaderas sobre el agua','pasaderas en un jardín','chill','none'),
(2082,'es','Sujeta un bastón fino.','Sujeta una pipa fina.','sujetando un bastón','un bastón en la nieve','chill','none'),
(2084,'es','Un tren sobre una vía férrea mojada.','Un tren sobre una vía férrea seca.','una vía férrea de noche','una vía férrea en el desierto','chill','none'),
(2086,'es','¡La calle está superfestiva!','¡La calle está supersoleada!','una calle festiva y nevada','una mesa festiva para cenar','slang','exclamation'),
(2087,'es','Un horizonte urbano steampunk entre niebla.','Un horizonte urbano de desierto entre niebla.','un horizonte urbano entre niebla','un horizonte urbano a medianoche','chill','none'),
(2088,'es','El hombre guapo tiene barba.','El hombre guapo tiene gafas.','un hombre guapo con barba','un hombre guapo con gafas','flirt','none'),
(2089,'es','Tío, qué cornamenta más enorme.','Tío, qué cornamenta más diminuta.','una enorme cornamenta ramificada','una cornamenta en la pared','slang','none'),
(2091,'es','El pino está solo.','La palmera está sola.','un pino escarchado','un pino con luces','dramatic','none'),
(2092,'es','¡Qué búho tan esponjoso!','¡Qué gato tan esponjoso!','un búho azul esponjoso','una manta azul esponjosa','dramatic','exclamation'),
(2093,'es','Toda la ciudad es verde.','Toda la ciudad es gris.','torres verdes llenas de árboles','pintura verde en las torres','business','none'),
(2095,'es','Su pelo largo es verde azulado.','Su pelo largo es negro.','pelo largo verde azulado','un paseo largo','chill','none'),
(2096,'es','¡Hasta el cielo es rojo!','¡Hasta el cielo es verde!','un cielo rojo del desierto','un deportivo rojo','dramatic','exclamation'),
(2097,'es','¡Esas orejas son más grandes que su cabeza!','¡Esos ojos son más grandes que su cabeza!','enormes orejas redondas','orejas bajo un gorro','dramatic','exclamation'),
(2101,'es','Caminan juntos.','Corren juntos.','caminando muy juntos','sentados juntos en un café','chill','none'),
(2102,'es','¡Menuda colección de libros!','¡Menuda colección de zapatos!','una colección de libros antiguos','una colección de monedas antiguas','dramatic','exclamation'),
(2104,'es','¡Cuántas joyas de oro!','¡Cuántas joyas de plata!','cubierta de joyas de oro','vendiendo joyas de oro','gossip','exclamation'),
(2105,'es','Los montones de libros podrían caerse.','Los montones de tazas podrían caerse.','montones de libros inclinados','un montón de ropa','chill','guessing'),
(2107,'es','¿Dónde está todo el mundo en esta nave espacial?','¿Dónde está todo el mundo en este tren?','dentro de una nave espacial','una nave espacial aterrizando','low_iq','guessing'),
(2108,'es','Hay tuberías a lo largo del techo.','Hay cables a lo largo del techo.','tuberías a lo largo del techo','tuberías bajo el suelo','chill','none'),
(2109,'es','Los libros están en filas ordenadas.','Las tazas están en filas ordenadas.','filas ordenadas de libros','un escritorio ordenado','chill','none'),
(2110,'es','Silueta oscura, ciudad de neón. ¿Batman?','Silueta oscura, playa soleada. ¿Batman?','una silueta con abrigo','la silueta de un gato','slang','guessing'),
(2112,'es','Su blazer es amarillo chillón.','Su blazer es verde oscuro.','un blazer amarillo chillón','quitándose un blazer','chill','none'),
(2113,'es','Las flores son de un amarillo intenso.','Las flores son de un morado intenso.','una paloma sobre flores amarillas','flores amarillas en un jarrón','chill','none'),
(2116,'es','Hay algas flotando a su alrededor.','Hay plástico flotando a su alrededor.','algas alrededor de su cabeza','algas en un rollo de sushi','chill','none'),
(2117,'es','Nada de móvil, solo un reloj de bolsillo.','Nada de móvil, solo un reloj de pulsera.','un reloj de bolsillo dorado','mirando un reloj de bolsillo','ironic','understatement'),
(2118,'es','¡Qué tiendas doradas tan elegantes!','¡Qué tiendas plateadas tan elegantes!','escaparates dorados elegantes','una fiesta de disfraces','dramatic','exclamation'),
(2119,'es','El búho tiene patrones rojos.','El búho tiene patrones verdes.','patrones de plumas','patrones en un vestido','chill','none'),
(2120,'es','Un pájaro está posado en una ramita.','Un pájaro está posado en un cable.','posado en una rama en flor','posado en un alféizar','chill','none'),
(2121,'es','Rocas pesadas, equilibrio perfecto.','Ladrillos pesados, equilibrio perfecto.','una torre de rocas pesadas','una bolsa pesada de rocas','business','none'),
(2123,'es','Esta fábrica toca el cielo.','Esta fábrica toca el mar.','una fábrica steampunk gigante','una fábrica steampunk diminuta','dramatic','exaggeration'),
(2124,'es','Camina por una carretera mojada.','Camina por una playa mojada.','caminando por una carretera comarcal','conduciendo por una carretera comarcal','chill','none'),
(2126,'es','¡El gatito ha derramado el café!','¡El gatito ha derramado la leche!','café derramado en la mesa','derramando pintura en el suelo','low_iq','blaming_someone'),
(2127,'es','Hay un libro sobre la mesa.','Hay un gato sobre la mesa.','una mesa de madera tallada','una mesa junto al fuego','chill','none'),
(2128,'es','¡Dispara desde un carro de guerra!','¡Dispara desde un barco!','disparando una flecha','disparando una foto','dramatic','exclamation'),
(2132,'es','La biblioteca está abandonada.','El colegio está abandonado.','una biblioteca abandonada','un coche abandonado','chill','none'),
(2133,'es','Pilares de piedra en la nieve.','Pilares de piedra en la arena.','pilares de piedras apiladas','un pilar de un templo','chill','none'),
(2134,'es','A la emperatriz no le hace ninguna gracia.','A la emperatriz le hace muchísima gracia.','una emperatriz severa','una emperatriz a caballo','ironic','understatement'),
(2135,'es','Este gato está hecho de remolinos.','Este gato está hecho de cuadrados.','remolinos dorados','remolinos de humo','chill','none'),
(2136,'es','Los guantes rojos quedan genial.','Los guantes azules quedan genial.','guantes espaciales rojos','guantes de boxeo rojos','flirt','none'),
(2137,'es','¿Aureola dorada? Con mucho estilo.','¿Aureola plateada? Con mucho estilo.','una aureola dorada como corona','una aureola de humo oscuro','flirt','none'),
(2140,'es','Este sitio es una máquina enorme.','Este sitio es un jardín enorme.','una enorme máquina oxidada','una lavadora enorme','chill','none'),
(2141,'es','Algo brilla en el sótano.','Algo arde en el sótano.','la puerta abierta de un sótano','un sótano lleno de cajas','gossip','none'),
(2143,'es','Rocas apiladas como Lego.','Ladrillos apilados como Lego.','una torre de rocas','una roca rodando cuesta abajo','low_iq','exaggeration'),
(2144,'es','Lleva una camiseta blanca.','Lleva una camiseta negra.','camiseta blanca y chaqueta','una camiseta en una percha','chill','none'),
(2146,'es','Francia tiene una torre morada.','Francia tiene una torre verde.','una torre en Francia','un puente en Francia','low_iq','guessing'),
(2149,'es','Cresta tras cresta, todo gris.','Cresta tras cresta, todo verde.','filas de crestas montañosas','una cresta cubierta de nieve','chill','none'),
(2150,'es','Coleta hecha. Va a salir ahí fuera.','Pelo suelto. Va a salir ahí fuera.','una coleta junto a la ventana','una coleta en un caballo','chill','guessing'),
(2151,'es','La media luna está en modo chill.','La luna llena está en modo chill.','una media luna entre nubes','una media luna a mediodía','slang','none'),
(2152,'es','Su pintalabios es rojo intenso.','Su pintalabios es rosa intenso.','pintalabios rojo intenso','pintalabios rosa intenso','chill','none'),
(2153,'es','¡China tiene un dragón volador!','¡China tiene un dragón dormido!','un dragón de China','un tigre de China','dramatic','exclamation'),
(2154,'es','La barba del general es blanca.','La barba del general es negra.','un viejo general con armadura','un joven general con armadura','chill','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
