begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(2155,'es','Esa sonrisa tan segura de sí misma funciona.','Esa sonrisa tan nerviosa funciona.','media sonrisa segura de sí misma','carcajada segura de sí misma','flirt','none'),
(2156,'es','El sol descansa en el horizonte.','La luna descansa en el horizonte.','el sol en el horizonte','un barco en el horizonte','chill','none'),
(2157,'es','Un bebé de la India lleva oro.','Un bebé de la India lleva rojo.','un cuadro de la India','una alfombra de la India','chill','none'),
(2158,'es','¡Me encanta el pañuelo naranja!','¡Me encanta el pañuelo azul!','un pañuelo naranja','quitándose un pañuelo','flirt','exclamation'),
(2159,'es','El gato se siente muy majestuoso.','El perro se siente muy majestuoso.','un gato majestuoso','un león majestuoso','ironic','guessing'),
(2161,'es','El genio tiene una idea nueva.','El genio tiene un gato nuevo.','un genio mirando las estrellas','un genio escribiendo fórmulas','nerd','guessing'),
(2162,'es','Su melena pelirroja es perfecta.','Su melena negra es perfecta.','larga melena pelirroja ondulada','pelo pelirrojo en un moño','flirt','none'),
(2164,'es','Un sendero se adentra en el bosque. ¿Quién va primero?','Un río se adentra en el bosque. ¿Quién va primero?','un sendero por el bosque','una cabaña en el bosque','dramatic','guessing'),
(2172,'es','Un coche deportivo en una tormenta de pintura.','Un coche deportivo en una tormenta de nieve.','un coche deportivo azul oscuro','un coche familiar azul oscuro','dramatic','exaggeration'),
(2174,'es','¡Un árbol está floreciendo en la nieve!','¡Un árbol está ardiendo en la nieve!','un árbol floreciendo de noche','flores que florecen en primavera','dramatic','exclamation'),
(2175,'es','Medianoche en el pinar.','Medianoche en el desierto.','medianoche bajo las estrellas','una fiesta a medianoche','chill','none'),
(2176,'es','¡Está lloviendo en el pasillo!','¡Está nevando en el pasillo!','un pasillo lluvioso de biblioteca','un pasillo de súper abarrotado','dramatic','exclamation'),
(2177,'es','¡Hasta la luna vino a ver al DJ!','¡Hasta el sol vino a ver al DJ!','un DJ en la calle','un DJ en una discoteca','slang','exaggeration'),
(2178,'es','Psst, dos gatos se están asomando.','Psst, dos perros se están asomando.','asomándose tras las hojas','asomándose por una ventana','gossip','none'),
(2181,'es','La calle está demasiado abarrotada.','La calle está demasiado vacía.','una calle de neón abarrotada','un vagón de tren abarrotado','slang','none'),
(2184,'es','¡El tigre está rugiendo!','¡El león está rugiendo!','un tigre rugiendo','un tigre durmiendo','dramatic','exclamation'),
(2185,'es','El pianista tiene el pelo rubio.','El pianista tiene el pelo negro.','un pianista al piano','un pianista con un teclado','chill','none'),
(2186,'es','Jesús lleva una corona de espinas.','Jesús lleva una corona de oro.','una corona de espinas','una rosa con espinas','chill','none'),
(2187,'es','Buda está meditando.','Buda está bailando.','Buda meditando','Buda tumbado','chill','none'),
(2188,'es','El niño llora, mamá no.','El niño canta, mamá no.','llorando en una bici','llorando en la cama','ironic','none'),
(2189,'es','¡Alguien se está cayendo por la borda!','¡Alguien se está tirando por la borda!','cayendo por la borda de espaldas','quedándose dormido en el barco','dramatic','exclamation'),
(2190,'es','Este villano tiene los ojos en llamas.','Este villano tiene los ojos azules.','un villano entre ruinas en llamas','un villano en un castillo','dramatic','none'),
(2191,'es','El androide tiene cara humana.','El androide tiene una barba larga.','una androide que brilla','un androide en una cocina','nerd','none'),
(2192,'es','A Harry Potter le encantarían estos frascos.','A Harry Potter le encantarían estas escobas.','frascos de cristal brillantes','un termo de café','nerd','guessing'),
(2194,'es','Las hojas tropicales son grandes. Guau.','Las hojas tropicales son diminutas. Guau.','hojas tropicales densas','una playa tropical','low_iq','none'),
(2195,'es','La acuarela está goteando.','El óleo está goteando.','un retrato en acuarela','un paisaje en acuarela','chill','none'),
(2199,'es','¡Rosas delicadas por todas partes!','¡Tulipanes delicados por todas partes!','delicadas rosas rosadas','un delicado jarrón de cristal','dramatic','exaggeration'),
(2200,'es','Está elegante con su vestido de gala.','Está elegante con su abrigo.','un vestido largo y elegante','un traje negro elegante','flirt','none'),
(2201,'es','¡Su armadura naranja mola mucho!','¡Su armadura rosa mola mucho!','pelo y armadura naranjas','una naranja en la mano','flirt','exclamation'),
(2202,'es','Su americana blanca es muy elegante.','Su americana roja es muy elegante.','una americana blanca elegante','un traje oscuro elegante','chill','none'),
(2204,'es','Tiene un cordero en brazos.','Tiene un perro en brazos.','un cordero en sus brazos','un cordero en un prado','chill','none'),
(2207,'es','La mano robótica está señalando.','La mano robótica está saludando.','señalando una pantalla','señalando el cielo','chill','none'),
(2208,'es','Tiene el pelo rosa chillón.','Tiene el pelo verde chillón.','pelo rosa chillón','un vestido rosa chillón','business','none'),
(2211,'es','¿Adivina quién tiene un tridente? El dios del mar.','¿Adivina quién tiene un martillo? El dios del mar.','un dios con un tridente','un tridente en la arena','gossip','guessing'),
(2212,'es','¡Bonitas rayas, tigre!','¡Bonitas manchas, tigre!','un tigre con rayas negras','una cebra con rayas negras','slang','exclamation'),
(2213,'es','Dato: los carneros tienen cuernos rizados.','Dato: los carneros tienen cuernos planos.','un carnero con cuernos rizados','un carnero comiendo hierba','nerd','cliche'),
(2216,'es','Está rezando ante un altar.','Está cantando ante un altar.','rezando ante un altar con velas','casándose en el altar','chill','none'),
(2217,'es','Está lanzando un hechizo. Qué guay.','Está lanzando una red. Qué guay.','lanzando un hechizo mágico','una racha de mal tiempo','slang','none'),
(2218,'es','Está rodeado de circuitos.','Está rodeado de flores.','líneas de circuito brillantes','un circuito de carreras','nerd','none'),
(2220,'es','Está contando el dinero con cuidado.','Está contando las monedas con cuidado.','contando un fajo de billetes','contando los segundos','business','none'),
(2224,'es','Van de la mano.','Se dan la mano.','de la mano bajo la lluvia','de la mano bajo el sol','flirt','none'),
(2225,'es','Pobre chica, tiene el pelo empapado.','Pobre chica, tiene el pelo seco.','empapada bajo la lluvia','empapada en agua caliente','gossip','none'),
(2226,'es','Lleva pulseras doradas.','Lleva guantes dorados.','pulseras doradas en las muñecas','una pulsera en una tienda','chill','none'),
(2227,'es','Echa un vistazo hacia atrás. ¿A ti?','Echa un vistazo hacia abajo. ¿A ti?','echando un vistazo atrás','echando un vistazo al móvil','gossip','guessing'),
(2228,'es','Está sentada encima de la ciudad.','Está sentada encima del mar.','muy por encima de la ciudad','encima de las nubes','chill','none'),
(2231,'es','Una esfinge dorada gigante.','Una esfinge plateada gigante.','una estatua de esfinge dorada','un gato esfinge durmiendo','chill','none'),
(2232,'es','El Buda parece tranquilo.','El Buda parece enfadado.','un Buda dorado tranquilo','un templo dorado tranquilo','chill','none'),
(2233,'es','Tiene dos guantes de béisbol.','Tiene dos bates de béisbol.','guantes de béisbol en ambas manos','béisbol en la tele','chill','none'),
(2234,'es','El guerrero tiene músculos enormes.','El guerrero tiene un escudo enorme.','los músculos de un guerrero','el escudo de un guerrero','chill','none'),
(2235,'es','Aparece totalmente de perfil.','Aparece totalmente de espaldas.','un hombre totalmente de perfil','una foto de perfil online','nerd','none'),
(2236,'es','Un palacio bajo una luna enorme. ¡Guau!','Un palacio bajo un sol enorme. ¡Guau!','un palacio en las montañas','un palacio en el desierto','dramatic','exclamation'),
(2237,'es','¡Mira este coche amarillo tan brillante!','¡Mira este coche rojo tan brillante!','un coche amarillo brillante','un autobús amarillo brillante','slang','exclamation'),
(2238,'es','La mezquita tiene muchas cúpulas.','La mezquita tiene una sola cúpula.','una gran mezquita con cúpulas','una mezquita en el desierto','chill','none'),
(2242,'es','La bandada no tiene ni un asiento libre.','La bandada tiene muchos asientos libres.','una bandada de pajaritos','un rebaño de ovejas','business','exaggeration'),
(2245,'es','Solo está un poquito cubierto de maleza.','Solo está un poquito nevado.','una casita cubierta de maleza','un césped cubierto de maleza','ironic','understatement'),
(2246,'es','La exposición presenta una casita en miniatura.','La exposición presenta un castillo en miniatura.','un jardín nocturno en miniatura','un tren en miniatura','business','none'),
(2247,'es','Escocia tiene una iglesia solitaria.','Escocia tiene un castillo solitario.','una iglesia en Escocia','un castillo en Escocia','chill','none'),
(2248,'es','Flota de forma grácil.','Baila de forma grácil.','flotando grácil en el aire','un baile grácil en el escenario','chill','none'),
(2249,'es','Una ciudad steampunk de engranajes.','Una ciudad steampunk de cristal.','torres steampunk de latón','una fiesta de disfraces steampunk','chill','none'),
(2250,'es','Está contemplando la ciudad.','Está contemplando el mar.','contemplando una ciudad lluviosa','contemplando un cielo estrellado','dramatic','none'),
(2251,'es','Código de vestimenta del cielo: túnica blanca.','Código de vestimenta del cielo: túnica negra.','una larga túnica blanca','una túnica con capucha','business','cliche'),
(2254,'es','Un palacio congelado. ¡Hola, Elsa!','Un lago congelado. ¡Hola, Elsa!','un palacio nevado y congelado','guisantes congelados en bolsa','slang','exclamation'),
(2256,'es','Sus piernas son totalmente mecánicas.','Sus piernas son totalmente de madera.','brazos y piernas mecánicos','un reloj mecánico','nerd','none'),
(2257,'es','Sus cejas son muy oscuras.','Sus cejas son muy claras.','cejas gruesas y oscuras','cejas finas y rubias','chill','none'),
(2258,'es','La iglesia tiene una aguja alta.','La iglesia tiene una cúpula redonda.','una alta aguja de iglesia','una aguja en un castillo','chill','none'),
(2259,'es','¡Llévame a esta laguna ya!','¡Llévame a este glaciar ya!','una laguna turquesa con palmeras','una laguna helada en invierno','dramatic','exclamation'),
(2262,'es','Puntos y líneas los conectan.','Puntos y líneas los separan.','líneas que conectan a dos personas','un cable conectando un móvil','nerd','none'),
(2268,'es','Está en la cuerda floja. ¡Sin red!','Está en una escalera. ¡Sin red!','equilibrio en la cuerda floja','cuerda floja en un circo','dramatic','exclamation'),
(2269,'es','Su blusa es holgada y blanca.','Su vestido es holgado y blanco.','una blusa blanca holgada','una blusa negra ajustada','chill','none'),
(2271,'es','Está de chill en un pasillo.','Está de chill en una cocina.','el pasillo de una nave espacial','un pasillo de hospital','slang','none'),
(2273,'es','Vaqueros rotos, look total denim.','Vaqueros rotos, look total negro.','vaqueros azules muy rotos','planchando unos vaqueros azules','slang','none'),
(2274,'es','¡Ese cuello de encaje es de lo más fino!','¡Ese cuello de piel es de lo más fino!','un cuello de encaje recargado','atando un cordón','gossip','none'),
(2275,'es','¡Bonito conjunto, zapatillas enormes!','¡Bonito conjunto, zapatillas diminutas!','un conjunto de estilo urbano','un conjunto para una boda','flirt','exclamation'),
(2278,'es','Está mirando hacia arriba, al cielo.','Está mirando hacia arriba, a un avión.','mirar hacia arriba a las nubes','buscar una palabra','chill','none'),
(2280,'es','La está abrazando al atardecer.','La está abrazando en un coche.','abrazados en un velero','abrazar una nueva idea','flirt','none'),
(2282,'es','Vela al atardecer. Qué chill.','Surf al atardecer. Qué chill.','vela al atardecer','vela en plena tormenta','slang','none'),
(2284,'es','¿Plumas? Peinado atrevido.','¿Perlas? Peinado atrevido.','un peinado de plumas','un peinado corto','flirt','none'),
(2285,'es','Su sudadera es enorme.','Su mochila es enorme.','una sudadera azul grande','una sudadera en una silla','chill','exaggeration'),
(2287,'es','Está sentado solo, en pleno duelo.','Está sentado solo, en un coche.','duelo en un jardín oscuro','duelo en un funeral','dramatic','none'),
(2288,'es','Top corto en el puerto deportivo.','Top corto en la estación de esquí.','un top corto negro','un top corto blanco','chill','none'),
(2291,'es','Solo unos cuantos asteroides. Tranqui.','Solo unos cuantos pájaros. Tranqui.','asteroides flotando','un asteroide chocando con la Tierra','ironic','understatement'),
(2295,'es','¡Esas mangas son enormes!','¡Esas botas son enormes!','mangas blancas anchas','mangas negras cortas','dramatic','exclamation'),
(2296,'es','¡Su vestido floreado va a juego con la pared!','¡Su vestido de rayas va a juego con la pared!','un vestido floreado naranja','una camisa floreada de playa','gossip','exaggeration'),
(2297,'es','Las olas rompen en la orilla.','Las olas rompen contra el barco.','palmeras en la orilla','un barco en la orilla','chill','none'),
(2300,'es','¡La guitarra está en llamas!','¡El piano está en llamas!','una guitarra en llamas','una casa en llamas','dramatic','exclamation'),
(2301,'es','Están lanzando el transbordador.','Están lanzando el avión.','lanzando un transbordador espacial','lanzando un nuevo producto','chill','none'),
(2302,'es','Está ingrávido y relajado.','Está ingrávido y asustado.','un astronauta ingrávido','una pluma ingrávida','chill','none'),
(2305,'es','Un camino rocoso hacia un faro.','Un camino rocoso hacia un castillo.','un cabo rocoso','una playa rocosa con tumbonas','chill','none'),
(2306,'es','El campo no se acaba nunca.','La ciudad no se acaba nunca.','niños en el campo','niños dejando el campo','chill','exaggeration'),
(2308,'es','El vikingo sostiene una espada.','El vikingo sostiene un hacha.','un vikingo con pieles','un vikingo en un barco','chill','none'),
(2310,'es','Una melodía sale del piano.','Una melodía sale del tambor.','una melodía dorada que sube','una melodía dorada que baja','dramatic','none'),
(2311,'es','La vidriera es enorme.','La vidriera es diminuta.','altas vidrieras','una lámpara de vidriera','chill','none'),
(2312,'es','Un coche de carreras junto a las palmeras.','Un coche de carreras junto a los pinos.','un coche de carreras rojo','un caballo de carreras','chill','none'),
(2313,'es','Tu casa está donde esté tu furgoneta camper.','Tu casa está donde esté tu tienda naranja.','una furgoneta camper naranja','una furgoneta camper en la ciudad','chill','cliche'),
(2314,'es','El disfraz del fantasma: una sábana vieja.','El disfraz del fantasma: una toalla vieja.','un fantasma de sábana blanca','un fantasma en un castillo','low_iq','cheap_quality'),
(2315,'es','¡Este paisaje es de papel!','¡Este paisaje es de cristal!','un paisaje de papel','una foto de paisaje','dramatic','exclamation'),
(2317,'es','Lleva la capucha roja puesta.','Lleva la capucha roja bajada.','una capucha roja puesta','el capó de un coche','chill','none'),
(2318,'es','Tiene una espada larguísima.','Tiene una lanza larguísima.','una espada larga y curva','una espada larga y recta','chill','none'),
(2322,'es','¡El cristal está roto!','¡El reloj está roto!','un retrato en un espejo roto','un brazo roto escayolado','dramatic','exclamation'),
(2324,'es','¡Canta como una estrella!','¡Baila como una estrella!','cantando al micrófono','cantando en la ducha','flirt','exaggeration'),
(2326,'es','El príncipe tiene un pelo azul muy guay.','El príncipe tiene un pelo rosa muy guay.','un príncipe con corona','un príncipe a caballo','slang','none'),
(2327,'es','Este coche y las palmeras molan un montón.','Esta bici y las palmeras molan un montón.','palmeras al atardecer','palmeras en una isla','slang','none'),
(2328,'es','¡Qué trono tan "humilde"!','¡Qué cama tan "humilde"!','un enorme trono dorado','un trono dorado vacío','ironic','exclamation'),
(2330,'es','Quiere darte flores.','Quiere darte una tarta.','dando tres flores amarillas','dando rosas rojas','flirt','guessing'),
(2333,'es','¡Están tan enamorados!','¡Están tan enfadados!','enamorados bajo hojas otoñales','enamorados en una playa','dramatic','exclamation'),
(2340,'es','Esta casa es un poco extraña.','Este coche es un poco extraño.','una casa alta y extraña','un barco viejo y extraño','chill','understatement'),
(2341,'es','Las flores hacen que la muerte parezca bonita.','Las velas hacen que la muerte parezca bonita.','la muerte entre flores','muerte en un accidente de coche','ironic','none'),
(2344,'es','Las casas están un poco torcidas.','Los árboles están un poco torcidos.','casas altas y torcidas','un marco torcido','ironic','understatement'),
(2345,'es','¡Qué barba de mago tan larga!','¡Qué barba de mago tan corta!','un viejo mago de gris','un viejo mago de rojo','dramatic','exclamation'),
(2347,'es','Está explorando un exoplaneta.','Está explorando una cueva profunda.','explorando un mundo alienígena','explorando un castillo antiguo','nerd','none'),
(2349,'es','¡Hasta el gato se ha disfrazado!','¡Hasta el perro se ha disfrazado!','disfrazados de brujas','disfrazados de piratas','gossip','exclamation'),
(2350,'es','¡Alguien ha tallado caras! ¡Hala!','¡Alguien ha tallado nombres! ¡Hala!','caras talladas en calabazas','caras talladas en madera','low_iq','exclamation'),
(2351,'es','Alguien conduce un coche verde.','Alguien conduce un coche amarillo.','conducir por el otoño','conducir por la nieve','chill','none'),
(2353,'es','Las setas son gigantes, tío.','Las setas son diminutas, tío.','setas rosas gigantes','flores rosas gigantes','slang','none'),
(2354,'es','¡Un tocado dorado enorme!','¡Un tocado plateado enorme!','un enorme tocado dorado','quitándose un tocado','dramatic','exclamation'),
(2356,'es','El camino lleva hacia un planeta.','El camino lleva hacia un castillo.','hacia un planeta enorme','hacia una ciudad enorme','dramatic','none'),
(2357,'es','La casa está en blanco y negro.','La casa está en rojo y blanco.','un dibujo en blanco y negro','una película en blanco y negro','chill','none'),
(2358,'es','La granja tiene tejados rojos.','La granja tiene tejados azules.','una granja en una ladera','una granja con vacas','chill','none'),
(2359,'es','Llevan ropa tradicional.','Llevan ropa moderna.','ropa tradicional india','una tarta de boda tradicional','chill','none'),
(2360,'es','Ese coche rojo parece rápido que flipas.','Esa furgoneta roja parece rápida que flipas.','un coche rojo rápido','un barco rojo rápido','slang','exaggeration'),
(2363,'es','Se está convirtiendo en un humo misterioso.','Se está convirtiendo en un agua misteriosa.','una misteriosa mujer de humo','una misteriosa puerta cerrada','dramatic','none'),
(2364,'es','Detrás de él hay un toro blanco.','Detrás de él hay un caballo blanco.','un toro con cuernos curvos','un toro en una plaza','chill','none'),
(2367,'es','Este coche está un poquito sucio.','Este autobús está un poquito sucio.','un viejo deportivo sucio','un autobús viejo y sucio','ironic','understatement'),
(2368,'es','Esta playa es el paraíso total.','Este desierto es el paraíso total.','un paraíso tropical al atardecer','un paraíso para esquiadores','slang','none'),
(2371,'es','El ángel está sumido en la pena.','El ángel está sumido en un libro.','un ángel lleno de pena','un ángel lleno de alegría','dramatic','none'),
(2372,'es','Parece totalmente agotado.','Parece totalmente emocionado.','un trabajador agotado','una batería de móvil agotada','slang','none'),
(2373,'es','El universo parece abarrotado.','El universo parece vacío.','un universo lleno de planetas','un universo sin estrellas','ironic','exaggeration'),
(2375,'es','Mitad gris, mitad amarillo. No se decide.','Mitad gris, mitad verde. No se decide.','la mitad de un coche amarillo','la mitad de un autobús amarillo','low_iq','guessing'),
(2378,'es','Ahora está relajándose a tope.','Ahora está corriendo a tope.','relajándose bajo la luna','relajándose en la playa','slang','none'),
(2379,'es','Caen hojas rojas.','Caen manzanas rojas.','hojas cayendo bajo la lluvia','nieve cayendo sobre coches','chill','none'),
(2380,'es','¡El coche está escapando del fuego!','¡El coche está escapando de la inundación!','escapando de un bosque en llamas','escapando de una casa en llamas','dramatic','exclamation'),
(2381,'es','¡Esas garras están afiladísimas!','¡Esos dientes están afiladísimos!','garras en una rama','las garras de un gato','dramatic','exclamation'),
(2382,'es','Mira, su cola tiene escamas azules.','Mira, su cola tiene escamas rosas.','una cola con escamas azules','pesándose en la báscula','gossip','none'),
(2383,'es','¡Fuego y gemas por todas partes!','¡Hielo y gemas por todas partes!','gemas brillantes de colores','gemas en una cueva oscura','dramatic','exaggeration'),
(2384,'es','Un reino diminuto sobre una colina.','Un reino diminuto en una isla.','un reino de cuento','el reino animal','chill','none'),
(2385,'es','Un paisaje alienígena morado.','Un paisaje alienígena verde.','un mundo alienígena morado','un alienígena en una nave','nerd','none'),
(2386,'es','La barandilla da al atardecer.','La barandilla da a una montaña.','una barandilla metálica de balcón','la barandilla de una escalera','chill','none'),
(2387,'es','El árbol está retorcido. Guay.','El árbol está recto. Guay.','un viejo árbol retorcido','una valla metálica retorcida','low_iq','none'),
(2388,'es','Este gamer ama el rosa.','Este gamer ama el verde.','un gamer de rosa','un gamer de azul','gossip','none'),
(2389,'es','Está rezando con fe.','Está rezando con los brazos abiertos.','rezando con mucha fe','perdiendo la fe','chill','none'),
(2390,'es','¡Qué elegante en la playa!','¡Qué elegante en un barco!','un look de playa elegante','un abrigo de invierno elegante','flirt','exclamation'),
(2391,'es','Paisaje épico, cielo rojo.','Paisaje épico, cielo azul.','un paisaje con una luna enorme','un decorado para una obra escolar','slang','none'),
(2392,'es','¿Un paseo con sombrero de paja? Con estilo.','¿Un paseo con sombrero rojo? Con estilo.','un paseo entre flores','un paseo por la playa','flirt','none'),
(2393,'es','Look de oficina con tacones altos.','Look de oficina con zapatillas.','tacones altos negros con tiras','tacones altos en una caja','business','none'),
(2394,'es','Tiene que elegir un camino.','Tiene que elegir un barco.','eligiendo el camino correcto','eligiendo el vestido correcto','dramatic','guessing'),
(2395,'es','Su chaleco tiene botones dorados.','Su chaleco tiene botones plateados.','un chaleco de cuero negro','un chaleco bajo una chaqueta','chill','none'),
(2396,'es','Ese corsé de cordones es espectacular.','Ese guante de cordones es espectacular.','un corsé de cordones','botas de cordones','flirt','none'),
(2397,'es','¡Esta habitación es tan lúgubre!','¡Esta habitación es tan soleada!','una habitación gótica lúgubre','un día lluvioso y lúgubre','dramatic','exclamation'),
(2400,'es','¡Menudo vikingo más feroz!','¡Menudo pirata más feroz!','una mirada feroz y furiosa','una tormenta feroz en el mar','dramatic','exclamation'),
(2404,'es','Este loto tiene el centro naranja.','Este loto tiene el centro morado.','una flor de loto blanca','la postura del loto','nerd','none'),
(2406,'es','¡Un todoterreno, demasiadas bolsas!','¡Una bici, demasiadas bolsas!','un todoterreno lleno de bolsas','un todoterreno en la ciudad','dramatic','exaggeration'),
(2408,'es','La imaginación abre un camino real.','La imaginación abre una puerta real.','un libro de imaginación','nada de imaginación','chill','none'),
(2411,'es','¡Esa corona es de lo más recargada!','¡Esa máscara es de lo más recargada!','una corona dorada recargada','una puerta de madera recargada','gossip','none'),
(2412,'es','Caminan del brazo.','Corren del brazo.','caminando del brazo','sentados del brazo','chill','none'),
(2413,'es','¡Está abrazando a un cachorro de lobo!','¡Está abrazando a un cachorro de oso!','abrazando a un cachorro de lobo','abrazando a un lobo grande','dramatic','exclamation'),
(2415,'es','El dios lleva guirnaldas de flores.','El dios lleva guirnaldas de papel.','guirnaldas de flores rojas','guirnaldas en un árbol de Navidad','chill','none'),
(2417,'es','Oscuridad y luz en armonía.','Rojo y azul en armonía.','una esfera de armonía','cantando en armonía','nerd','none'),
(2418,'es','Creo que es un ave cantora.','Creo que es una paloma.','un ave cantora en una rama','un ave cantora en un tejado','low_iq','guessing'),
(2420,'es','Esta torre destartalada es "segura".','Este puente destartalado es "seguro".','una torre destartalada de casas','una silla vieja destartalada','ironic','understatement'),
(2421,'es','Este hongo es grande. Pero grande grande.','Este hongo es pequeño. Pero pequeño pequeño.','un hongo gigante y pálido','moho en pan viejo','low_iq','exaggeration'),
(2422,'es','Está leyendo con un peto.','Está durmiendo con un peto.','un peto vaquero azul','un peto lleno de pintura','chill','none'),
(2424,'es','Los cipreses crecen a la izquierda.','Los cipreses crecen a la derecha.','una hilera de cipreses','un ciprés en una maceta','nerd','none'),
(2425,'es','¡Un gato negro en un marco siniestro!','¡Un gato blanco en un marco siniestro!','un marco con rosas negras','el cuadro de una bici','dramatic','exclamation'),
(2428,'es','Tres monitores, concentración máxima.','Dos monitores, concentración máxima.','tres monitores grandes','un vigilabebés','business','exaggeration'),
(2429,'es','Tío, el ciervo está en un arroyo.','Tío, el ciervo está en un prado.','un ciervo en un arroyo','un ciervo en la nieve','slang','none'),
(2432,'es','¡Su pose de flamenco está que arde!','¡Su pose de ballet está que arde!','flamenco con abanico','flamenco en un escenario','slang','exclamation'),
(2433,'es','¡El caballo viene galopando hacia nosotros!','¡El burro viene galopando hacia nosotros!','un caballo blanco galopando','un caballo negro galopando','dramatic','exclamation'),
(2434,'es','El bodegón muestra flores.','El bodegón muestra naranjas.','un bodegón con flores','un bodegón con fruta','nerd','none'),
(2435,'es','El arroyo está lleno de guijarros.','El arroyo está lleno de peces.','guijarros lisos y redondos','guijarros en una playa','chill','none'),
(2439,'es','La calle está mojada por la noche.','La calle está seca por la noche.','una calle mojada de noche','una playa de arena mojada','business','none'),
(2440,'es','¡La electricidad está por todas partes!','¡El agua está por todas partes!','chispas de electricidad','una factura de la electricidad','dramatic','exaggeration'),
(2446,'es','¡Lazos grandes, cordones largos!','¡Lazos grandes, cordones cortos!','cordones amarillos largos','cordones amarillos rotos','low_iq','exclamation'),
(2449,'es','Solo "unos pocos" escaparates iluminados.','Solo "unos pocos" escaparates a oscuras.','escaparates iluminados','un escaparate roto','ironic','understatement'),
(2450,'es','Una tormenta sobre el agua.','Una tormenta sobre la ciudad.','una tormenta sobre el agua','una tormenta sobre un pueblo','chill','none'),
(2451,'es','Un pájaro cerca de la torre Eiffel.','Un avión cerca de la torre Eiffel.','la torre Eiffel junto al río','la torre Eiffel nevada','chill','none'),
(2452,'es','¡El paseo nevado es romántico!','¡El paseo lluvioso es romántico!','un paseo romántico en la nieve','una cena romántica con velas','flirt','exclamation'),
(2454,'es','El camino serpenteante tiene farolillos.','El camino recto tiene farolas.','un camino empedrado serpenteante','un río de montaña serpenteante','chill','none'),
(2455,'es','Lleva pantalones cortos verdes.','Lleva pantalones largos verdes.','pantalones cortos vaqueros verdes','un bañador verde','chill','none'),
(2457,'es','La enfermera tiene un estetoscopio.','La enfermera tiene una carpeta.','una enfermera de uniforme','una enfermera con un bebé','chill','none'),
(2460,'es','Flores silvestres en una maceta azul, qué monas.','Flores silvestres en una maceta roja, qué monas.','una maceta de flores silvestres','un campo de flores silvestres','slang','none'),
(2462,'es','El cielo estrellado tiene luna.','El cielo estrellado tiene arcoíris.','un cielo nocturno estrellado','una noche estrellada en la ciudad','chill','none'),
(2463,'es','El valle ofrece peonías rosas.','El valle ofrece tulipanes rosas.','peonías rosas en una colina','peonías en un jarrón','business','none'),
(2464,'es','Los patrones son simétricos.','Los patrones son coloridos.','patrones simétricos de hojas','un edificio simétrico','nerd','none'),
(2465,'es','Está flotando. Nada del otro mundo.','Está nadando. Nada del otro mundo.','flotando en un cielo azul','flotando en una piscina','ironic','understatement'),
(2466,'es','Su vestido está hecho de cristales.','Su vestido está hecho de plumas.','un vestido de cristales brillantes','un vaso de cristal con agua','chill','none'),
(2470,'es','El saxofón tiene la campana curvada.','El saxofón tiene la campana recta.','un saxofón flotando','un saxofonista','nerd','none'),
(2472,'es','Su uniforme está impecable.','Su abrigo está impecable.','un uniforme escolar','un uniforme de policía','chill','none'),
(2473,'es','La corona está en una puerta roja.','La corona está en una puerta azul.','una corona en la puerta','una corona en la cabeza','chill','none'),
(2474,'es','Espuma salvaje en un mar embravecido.','Espuma salvaje en un mar en calma.','espuma sobre olas de tormenta','café con espuma de leche','dramatic','none'),
(2475,'es','Está leyendo descalza.','Está bailando descalza.','descalza en un diván','descalza en la playa','chill','none'),
(2477,'es','El viento lo ha despeinado.','La lluvia lo ha despeinado.','pelo castaño despeinado','un dormitorio desordenado','low_iq','blaming_someone'),
(2478,'es','El médico nos está sonriendo.','El médico nos está gritando.','un médico de dibujos sonriente','un médico en el quirófano','chill','none'),
(2481,'es','Sostiene un globo terráqueo.','Sostiene un balón.','sosteniendo un globo terráqueo','una bola de nieve','chill','none'),
(2482,'es','¡Cuántas torretas en un solo castillo!','¡Cuántas banderas en un solo castillo!','torretas puntiagudas de castillo','la torreta de un tanque','gossip','exclamation'),
(2483,'es','Hay flores secas en el libro.','Hay flores frescas en el libro.','flores secas en un libro','fruta deshidratada en un bol','chill','none'),
(2484,'es','La iglesia tiene un campanario alto.','El castillo tiene un campanario alto.','un campanario en la nieve','un campanario en una ciudad','chill','none'),
(2485,'es','El hombre cuervo parece siniestro.','El hombre gato parece siniestro.','un siniestro hombre cuervo','un siniestro gato negro','dramatic','none'),
(2486,'es','Los jeroglíficos cubren la pared.','Las flores cubren la pared.','una pared de jeroglíficos','jeroglíficos en un libro de texto','chill','none'),
(2490,'es','¡Bonito sombrero! ¿Tiene frío el muñeco de nieve?','¡Bonito sombrero! ¿Tiene frío el perro?','un muñeco de nieve con sombrero','haciendo un muñeco de nieve','low_iq','guessing'),
(2492,'es','¡El pueblo está tan concurrido!','¡El pueblo está tan tranquilo!','un pueblo nevado concurrido','una playa de verano concurrida','dramatic','exclamation'),
(2494,'es','Calle victoriana. ¿Ese es Sherlock?','Calle moderna. ¿Ese es Sherlock?','una calle victoriana nevada','una merienda victoriana','gossip','guessing'),
(2495,'es','He contado dos gorriones.','He contado cuatro gorriones.','dos gorriones en una rama','dos gorriones en la nieve','low_iq','none'),
(2497,'es','Papá Noel se está tomando un descanso.','Papá Noel se está dando un baño.','Papá Noel con regalos','Papá Noel con renos','gossip','guessing'),
(2498,'es','Se dan un abrazo tierno.','Se dan un beso tierno.','un abrazo tierno','un filete tierno','chill','none'),
(2499,'es','Dos ositos de peluche se están abrazando.','Dos ositos de peluche se están peleando.','ositos de peluche en la nieve','ositos de peluche en una cama','chill','none'),
(2500,'es','Está escribiendo en un portátil.','Está escribiendo en un móvil.','escribiendo en un portátil','llevando un portátil','chill','none'),
(2501,'es','Shivá está meditando sobre una roca.','Shivá está meditando en un barco.','Shivá con un tridente','Shivá con una espada','nerd','none'),
(2502,'es','Un santuario del bosque lleno de musgo.','Un santuario del desierto lleno de arena.','un santuario musgoso en el bosque','un santuario en una ciudad','chill','none'),
(2504,'es','Krishna tiene una pluma de pavo real.','Krishna tiene una pluma de águila.','Krishna con corona','Krishna con flauta','nerd','none'),
(2505,'es','Lluvia, un fusil y cero quejas.','Sol, un fusil y cero quejas.','un fusil largo con mira','un fusil en el suelo','chill','understatement'),
(2506,'es','Aquí todo es geométrico.','Aquí todo es azul.','formas geométricas rosas','un examen de geometría','chill','none'),
(2509,'es','Un camino atraviesa la lavanda.','Un camino atraviesa el trigo.','hileras de lavanda morada','un bote de aceite de lavanda','chill','none'),
(2510,'es','¡Hora de dormir para un niño y un gato!','¡Hora de dormir para un niño y un perro!','hora de dormir bajo la manta','cuento de buenas noches con libro','dramatic','exclamation'),
(2511,'es','Saltan chispas a su alrededor.','Vuelan hojas a su alrededor.','chispas alrededor de una pareja','una chispa de un enchufe','flirt','none'),
(2514,'es','Está echando hierbas en un bol.','Está echando sal en un bol.','espolvoreando hierbas secas','picando hierbas frescas','chill','none'),
(2516,'es','Estamos en el año 2024.','Estamos en el año 2025.','el año 2024 brillando','el año 2025','chill','none'),
(2519,'es','¿Has visto este patio trasero? ¡Un flamenco!','¿Has visto este patio trasero? ¡Un columpio!','un patio trasero muy animado','un huerto en el patio trasero','gossip','exclamation'),
(2520,'es','¡Una luz sagrada desde arriba!','¡Una luz sagrada desde abajo!','un haz de luz sagrado','un río sagrado','dramatic','exclamation'),
(2522,'es','Los tréboles tienen cuatro hojas.','Los tréboles tienen tres hojas.','tréboles de cuatro hojas','un campo de trébol con vacas','nerd','none'),
(2523,'es','La nevada es intensa esta noche.','La lluvia es intensa esta noche.','una nevada intensa sobre un pueblo','una nevada ligera en una ciudad','chill','none'),
(2524,'es','Tiene un bastón.','Tiene un paraguas grande.','apoyado en un bastón','un bastón de senderismo','chill','none'),
(2525,'es','Mamá está levantando a su osezno.','Mamá está levantando a su zorrito.','levantar a la cría','levantar una caja pesada','chill','none'),
(2526,'es','Poseidón tiene dos lanzas.','Poseidón tiene dos espadas.','Poseidón surgiendo de las olas','Poseidón hundiendo un barco','nerd','none'),
(2527,'es','El DJ lleva una máscara de gas. ¿Por qué?','El DJ lleva un pasamontañas. ¿Por qué?','máscara de gas y cascos','máscara de gas y gafas protectoras','ironic','guessing'),
(2529,'es','Tiene una cara amable.','Tiene un perro amable.','una cara amable y tranquila','un mar suave y tranquilo','chill','none'),
(2531,'es','Hasta el cielo brilla para ellos.','Hasta el mar brilla para ellos.','un cielo nocturno que brilla','agua con gas en un vaso','flirt','none'),
(2532,'es','Su vestido tiene volantes grises.','Su vestido tiene volantes rojos.','un vestido con volantes grises','volantes en un sombrero rojo','chill','none'),
(2533,'es','El fondo está neblinoso.','El fondo está soleado.','una calle antigua neblinosa','un lago de montaña neblinoso','chill','none'),
(2536,'es','Este chimpancé parece un motero de los serios.','Este chimpancé parece un surfero de los serios.','un chimpancé en moto','un chimpancé en un árbol','gossip','cliche'),
(2538,'es','Caperucita Roja se fía del lobo.','Caperucita Roja se fía del oso.','el lobo de Caperucita Roja','la abuela de Caperucita Roja','gossip','guessing'),
(2539,'es','La inteligencia artificial vive en su cabeza.','La inteligencia artificial vive en su coche.','un robot con inteligencia artificial','una app de inteligencia artificial','nerd','none'),
(2540,'es','Qué mazmorra tan "acogedora".','Qué jardín tan "acogedor".','una mazmorra oscura con velas','una bodega oscura con vino','ironic','none'),
(2541,'es','Nadie ha limpiado esta escalera.','Nadie ha limpiado esta cocina.','una escalera de piedra en ruinas','un puente de piedra en ruinas','ironic','understatement'),
(2543,'es','El elefante tiene colmillos largos.','El elefante tiene colmillos cortos.','dos largos colmillos blancos','una morsa con colmillos','chill','none'),
(2544,'es','Hanumán tiene una corona dorada.','Hanumán tiene una corona plateada.','Hanumán con un bastón dorado','Hanumán con una espada','nerd','none'),
(2545,'es','El mono está adorando a su dios.','El mono está durmiendo.','adorando en escalones de piedra','adorando a una estrella del fútbol','chill','none'),
(2546,'es','Esta sala es "bastante" espaciosa.','Esta sala es "bastante" diminuta.','una sala espaciosa','un coche espacioso','ironic','understatement'),
(2547,'es','¡Estas amanitas matamoscas son enormes!','¡Estas amanitas matamoscas son diminutas!','amanitas matamoscas gigantes','amanitas matamoscas en una cesta','slang','exclamation'),
(2548,'es','Cuántos barriles. ¿Cerveza, quizá?','Cuántas bicis. ¿Cerveza, quizá?','barriles de madera apilados','un barril de cerveza fría','low_iq','guessing'),
(2549,'es','¡Padre e hijo lo están celebrando!','¡Padre e hijo están llorando!','un padre llevando a su hijo','un padre llevando la compra','dramatic','exclamation'),
(2550,'es','Está sentada con las piernas cruzadas, descalza.','Está sentada con las piernas cruzadas, con botas.','sentada con las piernas cruzadas','de pie con las piernas cruzadas','chill','none'),
(2551,'es','Rollo Miami: palmeras y neón.','Rollo Miami: nieve y neón.','una calle de Miami con neón','una playa de Miami a mediodía','slang','none'),
(2552,'es','Está en la realidad virtual.','Está en una piscina.','unas gafas de realidad virtual','realidad virtual en clase','chill','none'),
(2556,'es','Dato: el cerebro está brillando.','Dato: el corazón está brillando.','un cerebro que brilla','un cerebro en un frasco','nerd','none'),
(2557,'es','Espera, ¿el velero es de cristal?','Espera, ¿el velero es de madera?','un velero de cristal','un velero en una botella','low_iq','none'),
(2558,'es','Está volando. ¡Libertad total!','Está nadando. ¡Libertad total!','libertad sobre el mar','libertad bajo el mar','dramatic','exclamation'),
(2559,'es','¡Este árbol da monedas!','¡Este árbol da manzanas!','monedas cayendo de un árbol','monedas en una hucha','dramatic','exclamation'),
(2560,'es','¿Caminar sobre el agua? ¡Un milagro!','¿Caminar sobre el fuego? ¡Un milagro!','un milagro en el océano','un remedio milagro para el resfriado','dramatic','exclamation'),
(2564,'es','Este racimo de hortensia es azul.','Este racimo de hortensia es rosa.','una hortensia azul','una hortensia en un jarrón','nerd','none'),
(2567,'es','La santa lleva un velo blanco.','La santa lleva un velo rojo.','una santa con aureola','una santa a caballo','chill','none'),
(2571,'es','El niño está gruñón. Otra vez.','La niña está gruñona. Otra vez.','un niño pequeño gruñón','un viejo gruñón','ironic','guessing'),
(2572,'es','Los triángulos brillan.','Los círculos brillan.','triángulos de neón brillantes','una señal de tráfico triangular','chill','none'),
(2575,'es','El DJ es totalmente anónimo.','El chef es totalmente anónimo.','un DJ anónimo con capucha','una carta anónima','slang','none'),
(2576,'es','Está desconsolado en París.','Está desconsolado en Roma.','desconsolado bajo la lluvia','desconsolado en la nieve','dramatic','none'),
(2578,'es','La visera es como un espejo.','La visera es como una ventana.','una visera de casco espejada','una gorra con visera','chill','none'),
(2579,'es','Sus gafas son rarísimas.','Su sombrero es rarísimo.','una máquina retro rara','un coche viejo raro','slang','exaggeration'),
(2580,'es','El arquero está tensando su arco.','El arquero está desenvainando una espada.','una estatua de un arquero','un cuadro de un arquero','chill','none'),
(2581,'es','Está tocando una flauta de bambú.','Está tocando un tambor de bambú.','tocando una flauta de bambú','tallando una flauta de bambú','chill','none'),
(2583,'es','Está disfrutando del buen rollo.','Está disfrutando de la pizza.','disfrutando de la música','disfrutando del sol','slang','none'),
(2584,'es','Es un bautismo en un río.','Es un bautismo en una iglesia.','un bautismo en el río','un bautismo en la iglesia','chill','none'),
(2586,'es','La mejor amistad del mundo: un robot gigante y una niña.','La mejor amistad del mundo: un perro gigante y una niña.','una amistad improbable','una pulsera de la amistad','dramatic','exaggeration'),
(2594,'es','El robot está aprendiendo sobre sí mismo.','El robot está aprendiendo sobre gatos.','un robot aprendiendo a leer','un robot aprendiendo a volar','low_iq','guessing'),
(2600,'es','Tío, dos escarabajos están de chill.','Tío, dos caracoles están de chill.','escarabajos subiendo por hojas','escarabajos volando sobre flores','slang','none'),
(2601,'es','El hombre está arrodillado rezando.','El hombre está sentado rezando.','arrodillado en suelo de piedra','arrodillado en un sofá blando','chill','none'),
(2602,'es','Están esquiando cuesta abajo a toda pastilla.','Están esquiando cuesta arriba a toda pastilla.','esquiando por una pista empinada','esquiando por una carretera llana','slang','none'),
(2603,'es','La partitura está escrita a mano.','La partitura está impresa.','una vieja partitura escrita a mano','una partitura nueva impresa','nerd','none'),
(2605,'es','Está acunando a un bebé.','Está acunando a un cordero.','acunar a un bebé','acunar un móvil','chill','none'),
(2606,'es','Su cabeza es puro mecanismo de relojería.','Su cabeza es puro cristal.','cabeza con mecanismo de relojería','un ratoncito de juguete de cuerda','nerd','exaggeration'),
(2607,'es','Los gatos llevan puestos abrigos formales.','Los perros llevan puestos abrigos formales.','gatos con abrigos largos puestos','gatos con collares','business','none'),
(2611,'es','Su cinturón tiene una hebilla de metal.','Su bolso tiene una hebilla de metal.','una hebilla de cinturón metálica','abrochándose el cinturón','chill','none'),
(2612,'es','Dos capullos aún no se han abierto.','Dos capullos ya se han abierto.','dos capullos rojos cerrados','dos capullos rojos abiertos','nerd','none'),
(2614,'es','Dos chicos están cerca de un minarete.','Dos chicas están cerca de un minarete.','caminando hacia un minarete','subiendo a un minarete','chill','none'),
(2621,'es','El mástil tiene un montón de jarcias.','El mástil tiene un montón de banderas.','un mástil alto con jarcias','un mástil con banderas piratas','nerd','none'),
(2623,'es','La hiedra cubre la estantería.','La nieve cubre la estantería.','una estantería cubierta de hiedra','un castillo cubierto de hiedra','chill','none'),
(2625,'es','El ingeniero sueña con grúas.','El ingeniero sueña con caballos.','el casco de un ingeniero','un ingeniero frente al ordenador','nerd','guessing'),
(2626,'es','Una ciudad vive en su cabeza calva.','Una granja vive en su cabeza calva.','una cabeza calva de perfil','una cabeza calva con gafas','chill','none'),
(2629,'es','Lleva el pelo en dos coletas.','Lleva el pelo en dos moños.','dos largas coletas trenzadas','dos coletas cortas rizadas','chill','none'),
(2631,'es','Sus gafas tienen lentes redondas.','Sus gafas no tienen lentes.','lentes redondas tintadas','una lente de cámara','chill','none'),
(2634,'es','Todas las botellas tienen corcho.','Todas las botellas tienen pajita.','botellas cerradas con corchos','un tablón de corcho con notas','chill','none'),
(2635,'es','La magnolia es de un blanco cremoso.','La magnolia es de un amarillo intenso.','una flor de magnolia abierta','un árbol de magnolia','chill','none'),
(2648,'es','¡Esta hormiga es más grande que yo!','¡Esta abeja es más grande que yo!','una hormiga negra enorme','un hormiguero enorme','low_iq','exaggeration'),
(2649,'es','¡Esas gafas protectoras son enormes!','¡Esos pendientes son enormes!','gafas protectoras brillantes','gafas de natación','dramatic','exclamation'),
(2651,'es','El tejado rojo tiene lunares blancos.','El tejado rojo tiene lunares negros.','una gorra con lunares blancos','un perro con manchas blancas','chill','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
