begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(4904,'es','Esas sillas parecen un pelín arriesgadas.','Esas mesas parecen un pelín arriesgadas.','una pila de sillas arriesgada','una apuesta arriesgada a caballos','ironic','understatement'),
(4905,'es','El puente atraviesa el cañón.','El puente atraviesa la calle.','arcos atravesando un cañón','un periodo de atención corto','business','none'),
(4907,'es','Altavoz enorme, agua bailando.','Altavoz enorme, leche bailando.','un altavoz enorme de discoteca','un orador en una conferencia','slang','exaggeration'),
(4908,'es','Alguien está doblando una rama.','Alguien está cortando una rama.','doblando una rama de manzano','una sucursal de un banco','chill','none'),
(4909,'es','La graban como si fuera famosa.','La pintan como si fuera famosa.','famosa por un minuto','famosa por sus canciones','chill','exaggeration'),
(4910,'es','¡Está gritando con la bufanda de su equipo!','¡Está durmiendo con la bufanda de su equipo!','una bufanda de rayas del equipo','una bufanda calentita de invierno','dramatic','exclamation'),
(4911,'es','¡Ella es la nueva dueña!','¡Él es el nuevo dueño!','la nueva dueña del café','la nueva cocinera del café','gossip','exclamation'),
(4912,'es','El instructor está dando patadas.','El instructor está bailando.','un instructor de kárate','un instructor de autoescuela','chill','none'),
(4913,'es','Se está abrochando una pulsera.','Se está abrochando un collar.','una pulsera tejida de cuentas','comprando una pulsera de oro','chill','none'),
(4914,'es','Todo el mundo adora al de la guitarra.','Todo el mundo adora al de la batería.','tocando una guitarra acústica','arreglando una guitarra acústica','gossip','guessing'),
(4915,'es','Caminan hombro con hombro.','Están sentados hombro con hombro.','brazos sobre los hombros','un bolso al hombro','chill','none'),
(4916,'es','¡Lo logramos! Dos bicicletas, un atardecer.','¡Lo logramos! Dos patinetes, un atardecer.','bicicletas en un muelle','bicicletas en un tren','dramatic','exclamation'),
(4917,'es','El rojo le disparó al azul. ¡Te pillé!','El azul le disparó al rojo. ¡Te pillé!','disparando pintura a un jugador','tirando a canasta','dramatic','exclamation'),
(4918,'es','Está subiendo las escaleras.','Está bajando las escaleras resbalando.','escaleras arriba con bolsas','escaleras abajo solo','chill','none'),
(4919,'es','Se apuntó a la membresía.','Se apuntó a yoga.','una membresía de club de fotografía','una tarjeta de membresía del gimnasio','chill','none'),
(4921,'es','El sendero está lleno de raíces.','El sendero está lleno de nieve.','un sendero agreste por el bosque','un rastro de huellas','chill','none'),
(4922,'es','El anfitrión da la bienvenida a sus invitados.','El anfitrión ignora a sus invitados.','un anfitrión alzando su copa','el presentador de un programa','business','none'),
(4924,'es','Ve una cara familiar.','Ve un perro familiar.','una cara familiar','una canción familiar','chill','none'),
(4925,'es','Está cuidando a un paciente.','Está cuidando a un bebé.','cuidando a un paciente del hospital','cuidando un jardín','business','none'),
(4926,'es','El dentista tiene un espejo.','El dentista tiene un móvil.','un dentista con un espejo','un dentista sacando una muela','chill','none'),
(4927,'es','El abogado está estrechando la mano.','El abogado va cogido de la mano.','un abogado con maletín','un abogado con portátil','chill','none'),
(4928,'es','¡Arregló la fuga él solito!','¡Arregló el coche él solito!','arreglando un fregadero que gotea','arreglando un coche averiado','dramatic','exclamation'),
(4929,'es','¡Adivina quién sacó una nota altísima!','¡Adivina quién sacó una nota malísima!','una nota altísima','una nota malísima','gossip','exclamation'),
(4930,'es','¡Su recompensa es una estrella dorada!','¡Su recompensa es una estrella plateada!','una estrella dorada de recompensa','una recompensa por unas llaves perdidas','dramatic','exclamation'),
(4931,'es','Está explicando un diagrama.','Está explicando un poema.','un diagrama con tiza','un diagrama de libro de texto','nerd','none'),
(4932,'es','¡Qué gorra! Lleva el volante de un taxi.','¡Qué gorra! Lleva el timón de un barco.','al volante de un taxi amarillo','al timón de un barco amarillo','flirt','none'),
(4934,'es','Se está poniendo unos cascos.','Se está poniendo un casco de moto.','unos cascos verdes de piloto','unas gafas de realidad virtual','chill','none'),
(4935,'es','Está tocando la brújula.','Está tocando la radio.','una brújula de latón de barco','un compás para dibujar círculos','nerd','none'),
(4936,'es','Está cocinando en una cocina.','Está cocinando en un jardín.','una cocina profesional','una cocina de casa','chill','none'),
(4937,'es','Hace sonar la campanilla.','Hace sonar el timbre de la puerta.','haciendo sonar la campanilla','llamando a un amigo','business','none'),
(4938,'es','Es una camarera muy liada.','Es una enfermera muy liada.','una camarera en una terraza','una camarera en una cocina','chill','none'),
(4939,'es','Corteza dorada. Buen trabajo, panadero.','Corteza quemada. Gran trabajo, panadero.','cruasanes bien dorados','un anillo de boda dorado','flirt','none'),
(4940,'es','El carnicero está envolviendo carne.','El carnicero está envolviendo regalos.','un carnicero envolviendo filetes','un carnicero cortando pollo','chill','none'),
(4941,'es','¡El bombero salvó a un gato!','¡El bombero salvó a un perro!','un bombero salvando a un gato','un bombero apagando un incendio','dramatic','exclamation'),
(4942,'es','¿Todo el equipaje en una bolsa? ¡Crack!','¿Todo el equipaje en cinco bolsas? ¡Crack!','el equipaje al hombro','el equipaje en un carrito','slang','exclamation'),
(4943,'es','Le encantan todos estos elogios.','Odia todos estos elogios.','elogios del equipo de rodaje','elogios de su profesor','gossip','guessing'),
(4945,'es','Está cantando al micro.','Está cantando al móvil.','cantando al micrófono','cantando en un coro','chill','none'),
(4946,'es','Su coleta también está bailando.','Su bufanda también está bailando.','una coleta al vuelo','una coleta bajo la gorra','chill','exaggeration'),
(4947,'es','Retrato terminado. ¡Brazos arriba!','Paisaje terminado. ¡Brazos arriba!','un retrato terminado','un retrato de un gato','dramatic','none'),
(4948,'es','Maquillaje con vistas al horizonte urbano. Qué nivel.','Maquillaje con vistas a la playa. Qué nivel.','un horizonte urbano detrás de ella','un horizonte urbano al atardecer','gossip','none'),
(4949,'es','Picos nevados: un paisaje increíble.','Dunas de arena: un paisaje increíble.','paisaje de montaña desde la cima','paisaje desde la ventana del tren','chill','none'),
(4950,'es','Manos en las caderas. Muy en serio.','Manos en la cabeza. Muy en serio.','manos en las caderas','moviendo las caderas','ironic','understatement'),
(4951,'es','¡Ha vuelto a casa y el perro está feliz!','¡Ha vuelto a casa y el gato está feliz!','volviendo a casa con el perro','saliendo de casa para trabajar','dramatic','exclamation'),
(4952,'es','Echaba muchísimo de menos su cama.','Echaba muchísimo de menos su coche.','tirándose en la cama','haciendo la cama','dramatic','guessing'),
(4953,'es','Está esperando la fotosíntesis.','Está esperando una tormenta.','esperando un brote','esperando un arcoíris','nerd','exaggeration'),
(4954,'es','¡La visita la hace tan feliz!','¡La visita la pone tan triste!','una visita al hospital','una visita al zoo','dramatic','exclamation'),
(4955,'es','Aquí solo las taquillas parecen ordenadas.','Aquí solo las literas parecen ordenadas.','una fila de taquillas grises','una taquilla en la piscina','ironic','exaggeration'),
(4956,'es','Va caminando hacia la recepción.','Va caminando hacia la cocina.','la recepción del albergue','un banquete de boda','chill','none'),
(4957,'es','Los precios de hotel van de baratos a 2.000 €.','Los precios de hotel van de baratos a 20 €.','tres tipos de hotel','un hotel junto al mar','business','cheap_quality'),
(4958,'es','¡De una choza a una villa de cristal!','¡De una choza a una villa de madera!','una enorme villa de cristal','una villa de vacaciones en alquiler','dramatic','exclamation'),
(4959,'es','Una cabaña con un girasol.','Una cabaña con un manzano.','una cabañita de madera','una cabaña junto a un lago','chill','none'),
(4960,'es','¡Se están abrazando en llegadas!','¡Se están peleando en llegadas!','abrazo en grupo en llegadas','abrazando un osito de peluche','dramatic','exclamation'),
(4961,'es','La mascota está cazando un juguete.','La mascota está cazando una pelota.','un gato mascota cazando','un gato mascota durmiendo','chill','none'),
(4962,'es','Está usando prismáticos. ¡Alerta ciervo!','Está usando un telescopio. ¡Alerta ciervo!','mirando por los prismáticos','prismáticos en la ópera','dramatic','exclamation'),
(4963,'es','¡Se hizo daño en un dedo y luego en el del pie!','¡Se hizo daño en un dedo y luego en la oreja!','un dedo herido','señalándolo con el dedo','dramatic','exclamation'),
(4964,'es','Primero prueba la sopa, luego flores. Qué arte.','Primero prueba la sopa, luego chocolate. Qué arte.','probando sopa de una cuchara','probando vino en una fiesta','flirt','cliche'),
(4965,'es','La rutina del baño, lista.','La rutina de la cocina, lista.','lavándose los dientes en el baño','cantando en el baño','business','none'),
(4966,'es','El hielo se partió en dos.','El hielo se partió en tres.','partiendo un bloque de hielo','partiendo un tronco de leña','nerd','none'),
(4967,'es','Un escáner comprueba su identidad.','Un escáner comprueba su equipaje.','comprobando su identidad','ocultando su identidad','nerd','none'),
(4968,'es','¡Ya tiene su carné nuevo!','¡Ya tiene su móvil nuevo!','un carné de identidad nuevo','una tarjeta de cumpleaños nueva','slang','exclamation'),
(4970,'es','¡Fuegos artificiales por la independencia!','¡Velas por la independencia!','celebrando la independencia','luchando por la independencia','dramatic','none'),
(4971,'es','Los fuegos artificiales iluminan la cúpula.','Los fuegos artificiales iluminan el puente.','fuegos artificiales sobre una cúpula','fuegos artificiales sobre un lago','chill','none'),
(4972,'es','¡Qué noche tan patriótica!','¡Qué mañana tan patriótica!','una multitud patriótica','un desfile militar patriótico','dramatic','exclamation'),
(4973,'es','Está posando en un monumento.','Está posando en una cascada.','posando en un monumento blanco','un monumento en una montaña','chill','none'),
(4974,'es','El vendedor sirve el té como un pro.','El vendedor hace malabares como un pro.','un vendedor de té sirviendo','un vendedor de flores','flirt','cliche'),
(4975,'es','¡El estilo de ella es tan diferente!','¡El estilo de él es tan diferente!','diferente al resto','diferente a su hermana','flirt','exclamation'),
(4976,'es','Va vadeando por el agua.','Va vadeando por la nieve.','vadeando arrozales','vadeando nieve profunda','chill','none'),
(4977,'es','Una mano indica el camino.','Un perro indica el camino.','una mano abierta y tendida','una mano llena de arroz','chill','none'),
(4978,'es','¡El cocinero está jugando con fuego!','¡El cocinero está jugando con hielo!','un cocinero con un wok','un cocinero en la parrilla','slang','cliche'),
(4979,'es','¡Toda la oficina está enferma!','¡Toda la oficina está dormida!','tosiendo en la oficina','cantando en la oficina','dramatic','exaggeration'),
(4980,'es','Están respirando hondo.','Están gritando muy fuerte.','respirar aire fresco','respirar bajo el agua','chill','none'),
(4981,'es','Todos se pusieron la vacuna. ¡Bien!','Nadie se puso la vacuna. ¡Bien!','vacunas en el brazo','una vacuna en la pierna','dramatic','exclamation'),
(4982,'es','Se está sujetando el tobillo.','Se está sujetando la cabeza.','un tobillo lesionado','una pulsera en el tobillo','chill','none'),
(4983,'es','¡El oficial lo revisa todo, hasta debajo de la furgoneta!','¡El oficial lo revisa todo, hasta debajo del autobús!','un oficial revisando una furgoneta','un oficial en un barco','dramatic','exaggeration'),
(4984,'es','¡Maletín en mano, y patinando!','¡Café en mano, y patinando!','patinando con maletín','un maletín lleno de papeles','gossip','exclamation'),
(4985,'es','Las pantallas están fijadas en su sitio.','Los espejos están fijados en su sitio.','fijando pantallas a la pared','fijando la fecha de una reunión','business','none'),
(4986,'es','La pared es un pelín brillante.','La pared es un pelín oscura.','pantallas azules brillantes','un día de sol brillante','ironic','understatement'),
(4987,'es','Ella presentó. Ganó el café.','Ella presentó. Ganó la pizza.','presentando su trabajo','presentando un programa de tele','ironic','exaggeration'),
(4988,'es','¡Empieza el ataque!','¡Empieza el pícnic!','un ataque medieval','un ataque al corazón','dramatic','exclamation'),
(4989,'es','¡Bajan la colina a la carga!','¡Bajan la carretera a la carga!','cargando colina abajo','rodando colina abajo','dramatic','exclamation'),
(4990,'es','Está usando una plancha pesada.','Está usando un martillo pesado.','una plancha de vapor pesada','una plancha de cocina','chill','none'),
(4991,'es','¡Qué montón de ropa tan desordenado!','¡Qué montón de libros tan desordenado!','un montón de ropa desordenado','una mesa de cocina desordenada','dramatic','exclamation'),
(4992,'es','¡Cuánta ropa que planchar! Está ocupada.','¡Cuánta comida que cocinar! Está ocupada.','ocupada con la plancha','ocupada con los platos','dramatic','exclamation'),
(4993,'es','Está solita en el lago.','Está solita en la playa.','sola en una isla diminuta','sola en una gran ciudad','chill','none'),
(4994,'es','Está usando una cuchara de madera.','Está usando una cuchara de metal.','una cuchara larga de madera','una tabla de cortar de madera','chill','none'),
(4995,'es','Una fuente con una escultura.','Una fuente con un reloj.','una escultura de fuente de piedra','una escultura de hielo de boda','chill','none'),
(4996,'es','Las palomas adoran su cucurucho.','Las gaviotas adoran su cucurucho.','un cucurucho de helado','un cono naranja de tráfico','gossip','guessing'),
(4997,'es','Tiene una risa escandalosa.','Tiene una risa muy bajita.','una risa en el Coliseo','una risa en París','chill','none'),
(4998,'es','El túnel está hecho de pórticos.','El túnel está hecho de árboles.','un túnel de pórticos de santuario','un túnel bajo el mar','chill','none'),
(4999,'es','Está combatiendo contra un espadachín.','Está combatiendo contra un arquero.','combatiendo contra un espadachín','combatiendo un resfriado','chill','none'),
(5000,'es','Sus lonchas finas se ven perfectas.','Sus lonchas gruesas se ven perfectas.','lonchas finas de pescado','lonchas finas de pan','flirt','none'),
(5001,'es','Merece la pena por este paisaje.','Merece la pena por esta playa.','un paisaje de montaña','un cuadro de paisaje','slang','cliche'),
(5002,'es','Se tiran al agua al anochecer.','Se tiran al agua al mediodía.','un lago del bosque al anochecer','el anochecer en una gran ciudad','chill','none'),
(5003,'es','Un explorador está abriendo un camino.','Un explorador está talando un árbol.','un explorador con machete','un explorador con un mapa','chill','none'),
(5004,'es','El canguro salta hacia delante.','El canguro salta hacia atrás.','saltar por la arena','saltar de la cama','chill','none'),
(5005,'es','Ella lo ve todo en esta bahía.','Ella lo ve todo en este parque.','barcos en una bahía tranquila','una bahía llena de hielo','gossip','guessing'),
(5006,'es','Su hervidor está trabajando a tope.','Su tostadora está trabajando a tope.','hirviendo agua en un hervidor','un hervidor sobre el fuego','chill','exaggeration'),
(5007,'es','¡Sí! ¡Su llave está en la cerradura!','¡Sí! ¡Su llave está en el coche!','una llave en la cerradura','un candado en una bici','dramatic','exclamation'),
(5009,'es','El niño baja deslizándose.','El niño sube trepando.','un niño en un tobogán','un niño en un columpio','chill','none'),
(5010,'es','¡Viva el rey!','¡Viva la reina!','un rey en un balcón','un rey a caballo','dramatic','cliche'),
(5011,'es','¡La pareja de viejitos se está besando, qué monos!','¡La pareja de viejitos está bailando, qué monos!','una pareja de viejitos besándose','una pareja de viejitos bailando','gossip','exclamation'),
(5013,'es','La cocina barata es vieja.','La cocina barata es enorme.','una cocina barata y vieja','un coche barato y rápido','chill','none'),
(5014,'es','El cocinero rico tiene las mejores vistas.','El cocinero rico tiene el mejor perro.','la cocina de un hombre rico','el coche de un hombre rico','gossip','none'),
(5015,'es','Pan casero, hecho a mano.','Pasta casera, hecha a mano.','una hogaza de pan casero','mermelada casera en tarros','chill','none'),
(5016,'es','Está flexionando las rodillas.','Está flexionando los brazos.','rodillas al aire en sentadilla','con una rodilla en el suelo','business','none'),
(5017,'es','¡Un arcoíris de verduras cortadas!','¡Un arcoíris de fruta cortada!','verduras cortadas en filas','flores cortadas en un jarrón','dramatic','exclamation'),
(5018,'es','¡Qué sabrosa se ve esa comida!','¡Qué sabrosa se ve esa sopa!','un sabroso bol de arroz','un sabroso trozo de tarta','gossip','exclamation'),
(5019,'es','Está asando ternera a la parrilla.','Está asando pescado a la parrilla.','lonchas de ternera a la parrilla','una hamburguesa de ternera con patatas','chill','none'),
(5020,'es','¡Dos personas para reemplazar una bombilla!','¡Cinco personas para reemplazar una bombilla!','reemplazando una bombilla fundida','reemplazando una rueda pinchada','low_iq','cliche'),
(5021,'es','Qué dama tan elegante sirviendo té.','Qué dama tan elegante sirviendo vino.','una dama con cofia','una dama a caballo','flirt','none'),
(5022,'es','¡La lámpara de araña está brillando!','¡El espejo está brillando!','una lámpara de araña brillando','zapatos brillando','dramatic','exclamation'),
(5023,'es','¡Está vitoreando a un avión!','¡Está vitoreando a un tren!','un avión aterrizando bajito','un avión despegando','dramatic','exclamation'),
(5024,'es','¡Tiene todos los diccionarios!','¡Tiene todos los libros de cocina!','una pila de diccionarios','una app de diccionario','dramatic','exaggeration'),
(5025,'es','¡Madre mía, este chiste es buenísimo!','¡Madre mía, esta clase es buenísima!','un chiste en el móvil','un chiste del profe','gossip','exclamation'),
(5026,'es','Su móvil está divertidísimo hoy.','Su libro está divertidísimo hoy.','divertidísimo en clase','divertidísimo en una boda','gossip','none'),
(5027,'es','La jueza está usando su mazo.','La jueza está usando su móvil.','una jueza con mazo','un juez con peluca','business','none'),
(5028,'es','¿Caso difícil? Solo unos cuantos libros.','¿Caso difícil? Solo unos cuantos bolis.','un caso judicial difícil','un examen difícil','ironic','understatement'),
(5029,'es','El gesto de él dice: ¡he ganado!','El gesto de ella dice: ¡he ganado!','un gesto de puño ganador','un gesto grosero con la mano','dramatic','guessing'),
(5030,'es','¡Su disfraz tiene todos los colores!','¡Su sombrero tiene todos los colores!','un disfraz de plumas arcoíris','un disfraz de Halloween','gossip','exaggeration'),
(5031,'es','El líder señala hacia delante.','El líder está sentado.','un líder en una montaña','un líder en una playa','chill','none'),
(5033,'es','Seguro que los vecinos oyen estos tambores.','Seguro que los vecinos oyen estas trompetas.','tocando los tambores','un solo de tambor','ironic','guessing'),
(5034,'es','¡En su casa todo se derrama!','¡En su casa todo se quema!','leche derramándose en la mesa','derramando café en el portátil','ironic','exaggeration'),
(5035,'es','¡Ese malabarista tiene talento!','¡Ese cantante tiene talento!','talento para los malabares','un concurso de talentos','slang','exclamation'),
(5036,'es','Ella enseña, él aprende. Despacito.','Él enseña, ella aprende. Despacito.','aprendiendo malabares','aprendiendo a bailar','chill','banter'),
(5038,'es','Ritmo constante subiendo la Gran Muralla.','Ritmo constante bajando la Gran Muralla.','un ritmo de carrera constante','un ritmo de paseo lento','chill','none'),
(5039,'es','Está abriendo las jaulas.','Está cerrando las jaulas.','abriendo las jaulas de pájaros','limpiando las jaulas de pájaros','chill','none'),
(5040,'es','¿Un sillón? ¿En una bici? Claro que sí.','¿Un sofá? ¿En una bici? Claro que sí.','un sillón de terciopelo amarillo','un sillón en un coche','ironic','understatement'),
(5041,'es','Un destello blanco ilumina el tejado.','Un destello verde ilumina el tejado.','un destello blanco cegador','un flash de cámara en interior','dramatic','none'),
(5042,'es','¡El día de pierna fue doloroso!','¡El día de brazo fue doloroso!','piernas rígidas y doloridas','una quemadura de sol dolorosa','dramatic','exclamation'),
(5043,'es','El león no es nada silencioso.','El león no está nada solo.','un león nada silencioso','un león silencioso','ironic','understatement'),
(5044,'es','Puede oír a través de la puerta.','Puede oír a través de la pared.','oyendo a través de una puerta','oyendo sonar el timbre','chill','none'),
(5045,'es','¡Los altavoces hacen un sonido enorme!','¡Los tambores hacen un sonido enorme!','sonido de un radiocasete','sonido de la radio del coche','low_iq','exclamation'),
(5046,'es','¡La televisión le hizo pegar un bote!','¡La televisión le hizo llorar!','viendo la televisión','arreglando la televisión','slang','blaming_someone'),
(5047,'es','Esta noche nadie sale del salón.','Esta noche nadie sale de la cocina.','un salón acogedor','limpiando el salón','gossip','guessing'),
(5048,'es','Candado enorme, puertas aún cerradas.','Candado enorme, puertas abiertas de par en par.','puertas bien cerradas','ojos bien cerrados','ironic','understatement'),
(5049,'es','Está cerrando la puerta de entrada.','Está cerrando la puerta del garaje.','cerrando la puerta de entrada','cerrando una tienda','chill','none'),
(5050,'es','Perdió, y los invitados se fueron.','Ganó, y los invitados se fueron.','perdiendo unas elecciones','perdiendo las llaves del coche','gossip','none'),
(5051,'es','Lo ha perdido. ¿El pasaporte, quizás?','Lo ha encontrado. ¿El pasaporte, quizás?','perdiendo algo importante','perdiendo un partido de fútbol','gossip','guessing'),
(5052,'es','Las maletas no son ligeras.','Las sillas no son ligeras.','maletas nada ligeras','equipaje de mano ligero','chill','understatement'),
(5053,'es','La etiqueta muestra su foto.','La etiqueta muestra su perro.','una etiqueta con su foto','una etiqueta en un tarro','business','none'),
(5055,'es','Dos órganos rosas: los pulmones.','Dos órganos rosas: los riñones.','un par de órganos para respirar','un órgano de iglesia sonando','nerd','none'),
(5057,'es','¡Su correo vuela por todas partes!','¡Su dinero vuela por todas partes!','correo del buzón','correo en el ordenador','dramatic','exaggeration'),
(5058,'es','Ahora el niño adora al cartero.','Ahora el niño adora al profe.','un cartero con cartas','un cartero con un perro','gossip','guessing'),
(5059,'es','¡Le han llegado un montón de cartas!','¡Le han llegado un montón de flores!','una pila de cartas','una carta del colegio','slang','exclamation'),
(5060,'es','En este vídeo solo salen varones.','En este vídeo solo salen chicas.','varones de todas las edades','varones en un equipo de fútbol','gossip','none'),
(5061,'es','¡Madre mía, qué acuario!','¡Madre mía, qué volcán!','un acuario enorme','una piscina enorme','dramatic','exclamation'),
(5062,'es','El jefe está dibujando un gráfico.','El jefe está dibujando un gato.','un jefe dando instrucciones','un jefe tomándose un descanso','business','none'),
(5063,'es','La columna avanza en orden.','La multitud avanza en orden.','una columna de filas en marcha','una columna en un periódico','business','none'),
(5065,'es','Un largo pasillo de especias.','Un largo pasillo de zapatos.','un pasillo de puestos de especias','el pasillo de un avión','chill','none'),
(5066,'es','Solo una aceituna, de muestra.','Solo un dátil, de muestra.','una aceituna de muestra','una muestra de especias','ironic','understatement'),
(5067,'es','¡El matrimonio empieza con un beso!','¡El matrimonio empieza con una pelea!','un matrimonio con confeti','un matrimonio en una iglesia','dramatic','exclamation'),
(5068,'es','La novia está dando un anillo.','La novia está dando un discurso.','una novia en la playa','una novia en una iglesia','chill','none'),
(5069,'es','¡Madre mía! Está disfrutando del masaje.','¡Madre mía! Está disfrutando del café.','disfrutar de un masaje de cuello','disfrutar de un masaje de pies','dramatic','exclamation'),
(5070,'es','Está probando todos los colchones.','Está probando todas las almohadas.','tumbada en un colchón','cargando un colchón','chill','none'),
(5071,'es','Está revisando el vehículo.','Está revisando la bicicleta.','revisando un coche plateado','revisando una lavadora','business','none'),
(5072,'es','El líquido marrón es muy viscoso.','El líquido verde es muy viscoso.','vertiendo un líquido marrón','vertiendo un líquido transparente','nerd','none'),
(5073,'es','¡Esta medicina sabe fatal!','¡Esta medicina sabe genial!','una cucharada de medicina marrón','una medicina para perros','dramatic','exclamation'),
(5074,'es','Todos se le están presentando a ella.','Todos se le están presentando a él.','presentando a una compañera nueva','presentando un producto nuevo','business','none'),
(5076,'es','Es miembro nuevo del club.','Es miembro nuevo del grupo de música.','un miembro nuevo del club','un miembro de una banda','business','none'),
(5077,'es','Él recordó todas las tarjetas, fácil.','Ella recordó todas las tarjetas, fácil.','recordando respuestas en tarjetas','retirando un coche defectuoso','slang','understatement'),
(5078,'es','Está haciendo tacos de cerdo.','Está haciendo tacos de pescado.','cortando cerdo asado','chuletas de cerdo en la sartén','chill','none'),
(5079,'es','Primero el taco, luego la pirámide.','Primero el taco, luego la playa.','una pirámide en la selva','una pirámide en el desierto','ironic','cliche'),
(5080,'es','El vestido amarillo le queda genial.','El abrigo amarillo le queda genial.','un vestido amarillo chillón','un chubasquero amarillo chillón','flirt','none'),
(5081,'es','El morado es su color.','El verde es su color.','un vestido morado ajustado','un pañuelo de seda morado','flirt','none'),
(5082,'es','¿Dos moños? Peinado top.','¿Dos trenzas? Peinado top.','un peinado con dos moños','un peinado con flequillo','flirt','none'),
(5083,'es','Están añadiendo bayas.','Están añadiendo frutos secos.','bayas rojas en la masa','cogiendo bayas en el bosque','chill','none'),
(5084,'es','¡El vestido verde es impresionante!','¡El vestido rojo es impresionante!','un vestido largo verde','un bolso de noche verde','dramatic','exclamation'),
(5085,'es','¡Está posando como la estatua!','¡Está posando como el guardia!','un selfi con una estatua','un selfi con un caballo','gossip','exclamation'),
(5086,'es','¡El suelo está tan brillante!','¡El suelo está tan polvoriento!','un suelo de piedra brillante','un móvil nuevo y brillante','dramatic','exclamation'),
(5087,'es','Las patas dejaron el suelo sucio.','Las patas dejaron la pared sucia.','un suelo de baldosas sucio','platos sucios en el fregadero','gossip','blaming_someone'),
(5088,'es','El niño está despierto y bosteza.','El niño está despierto y come.','despierto al amanecer','despierto a medianoche','chill','none'),
(5090,'es','Una habitación del bebé acogedora y llena de juguetes.','Una cocina acogedora y llena de juguetes.','una habitación del bebé con cuna','un vivero de plantas','chill','none'),
(5091,'es','La moto pequeña es verde.','La moto pequeña es roja.','una moto verde en el pueblo','una moto verde en venta','chill','none'),
(5092,'es','Nuestro ayudante mueve cajas como un crack.','Nuestro ayudante mueve plantas como un crack.','un ayudante con una caja','un ayudante con una lámpara','slang','exaggeration'),
(5093,'es','El césped estaba un pelín cubierto de maleza.','La piscina estaba un pelín cubierta de maleza.','cortando hierba cubierta de maleza','un seto cubierto de maleza','ironic','understatement'),
(5094,'es','Está sacando músculo con su brazo flaco.','Está sacando músculo con su pierna flaca.','sacando músculo con un brazo flaco','con vaqueros pitillo','chill','none'),
(5095,'es','¡Mira hacia arriba con asombro!','¡Mira hacia abajo con asombro!','asombro ante un esqueleto gigante','asombro ante una moneda diminuta','dramatic','exclamation'),
(5096,'es','Las setas crecen en el suelo.','Las setas crecen en el agua.','una seta en el suelo','una seta en una pizza','chill','none'),
(5097,'es','Su música paró la calle.','Su música vació la calle.','música callejera','una tienda de música','chill','exaggeration'),
(5098,'es','Él adora a su selección nacional.','Ella adora a su selección nacional.','colores nacionales en la cara','una fiesta nacional','chill','guessing'),
(5099,'es','¡Todos están añadiendo una foto!','¡Todos están añadiendo un sello!','fotos en un mapamundi','un álbum de fotos','gossip','none'),
(5100,'es','Están fijando fotos en un mapa.','Están fijando fotos en una puerta.','fijando fotos en un mapa','fijando mapas en la pared','chill','none'),
(5102,'es','¡Este callejón es superestrecho!','¡Este callejón es superancho!','un callejón estrecho de la medina','un callejón lleno de gatos','slang','exaggeration'),
(5103,'es','¡El cuello de una jirafa está encima de ella!','¡El cuello de un caballo está encima de ella!','el largo cuello de una jirafa','una serpiente alrededor del cuello','dramatic','exclamation'),
(5105,'es','Una zanja llena de patos.','Una zanja llena de barcas.','una zanja recta de agua','una zanja junto a la autopista','chill','exaggeration'),
(5107,'es','Los dos están acunando al bebé.','Los dos están bañando al bebé.','acunar a un recién nacido','acunar una taza de té','chill','none'),
(5108,'es','El pueblo está sobre el agua.','El pueblo está sobre la colina.','un pueblo sobre pilotes','un pueblo en la nieve','business','none'),
(5109,'es','Una docena de cupcakes dulces, y come sola.','Una docena de galletas dulces, y come sola.','una bandeja de cupcakes dulces','una taza de té dulce','ironic','guessing'),
(5110,'es','El parque está muy tranquilo.','La playa está muy tranquila.','un parque tranquilo con niebla','una playa tranquila con niebla','chill','none'),
(5111,'es','Está cuidando a un niño enfermo.','Está cuidando a un cachorro enfermo.','cuidando a un niño enfermo','cuidando a un abuelo enfermo','chill','none'),
(5112,'es','Hay granos volando por el aire.','Hay granos cayendo en una taza.','granos de arroz cayendo','un grano de arena','chill','none'),
(5113,'es','Buen consejo: come más pescado.','Buen consejo: come más pastel.','consejos sobre comida sana','consejos sobre dinero','business','none'),
(5114,'es','Los flamencos se van volando.','Los cisnes se van volando.','una bandada de flamencos','un flamenco en el zoo','chill','none'),
(5115,'es','Está examinando un insecto.','Está examinando una flor.','examinando un insecto pequeño','estudiando para un examen','chill','none'),
(5116,'es','¡Está abriendo todas las ventanas!','¡Está cerrando todas las ventanas!','abrir las ventanas','abrir un regalo','dramatic','exclamation'),
(5117,'es','¡Le flipa esta librería!','¡Odia esta librería!','una librería antigua abarrotada','una librería que cierra','slang','exclamation'),
(5118,'es','La luz del sol cae a chorros sobre él. ¡Qué mañana!','La lluvia cae a chorros sobre él. ¡Qué mañana!','luz del sol por una ventana','luz del sol entre los árboles','dramatic','none'),
(5119,'es','La entrada tiene puertas de madera.','La entrada tiene puertas de cristal.','la entrada del parque','la entrada del museo','chill','none'),
(5120,'es','¡Listo! Los cirujanos están contentos.','¡Listo! Los panaderos están contentos.','cirujanos alrededor de un paciente','cirujanos en la sala de espera','dramatic','exclamation'),
(5121,'es','Está sacando las magdalenas.','Está sacando las galletas.','sacando una bandeja de magdalenas','sacando la puerta del horno','chill','none'),
(5122,'es','Todos lograron su objetivo.','Todos fallaron su objetivo.','logrando un objetivo difícil','logrando buenas notas','chill','none'),
(5124,'es','Maratón por el casco antiguo.','Maratón por el bosque.','corriendo un maratón urbano','un maratón de pelis','chill','none'),
(5125,'es','¡Están representando una revolución!','¡Están representando una boda!','representando una obra antigua','montando una protesta','dramatic','exclamation'),
(5126,'es','Está orgulloso de su negocio.','Está orgulloso de su coche.','un pequeño negocio de barrio','un gran negocio online','chill','none'),
(5127,'es','¡La maleta no cierra!','¡La maleta no abre!','cerrar una maleta llena','cerrar una ventana','dramatic','exclamation'),
(5129,'es','Los muebles están bajo fundas.','Los muebles están bajo toallas.','fundas grises en los muebles','una funda en un libro','business','none'),
(5130,'es','¡Su cometa vuela altísimo!','¡Su dron vuela altísimo!','volando una cometa','una cometa en un árbol','slang','exaggeration'),
(5131,'es','Se está concentrando en el balón.','Se está concentrando en los chicos.','concentrarse en el balón','concentrarse en el público','chill','none'),
(5132,'es','Está vertiendo la mezcla.','Está removiendo la mezcla.','mezcla de tortitas en la sartén','una mezcla de colores de pintura','chill','none'),
(5135,'es','Plaza estrecha, aparcamiento perfecto.','Plaza amplia, aparcamiento perfecto.','una plaza de aparcamiento estrecha','el lanzamiento de un cohete espacial','flirt','none'),
(5136,'es','¡El debate está subiendo de volumen!','¡El debate está bajando de volumen!','un debate a gritos','un debate en la tele','dramatic','exclamation'),
(5137,'es','El parlamento está lleno hoy.','El parlamento está vacío hoy.','un parlamento lleno','un parlamento vacío','business','none'),
(5138,'es','Ya está en el tren.','Ya está en el autobús.','un asiento en el tren','un asiento en el avión','chill','none'),
(5139,'es','Al principio las páginas estaban en blanco.','Al principio las páginas estaban llenas.','una página del pasaporte en blanco','una cara inexpresiva','chill','none'),
(5140,'es','El sello le permite entrar.','El sello le permite conducir.','permitido entrar','permitido fumar','business','none'),
(5141,'es','El médico tiene un estetoscopio.','El médico tiene una cámara.','un médico con estetoscopio','un médico en una ambulancia','chill','none'),
(5142,'es','El barrio está decorado.','El barrio está vacío.','un barrio decorado','un mercadillo del barrio','chill','none'),
(5143,'es','Los soldados están haciendo la paz.','Los soldados están haciendo la guerra.','haciendo la paz','paz y tranquilidad en casa','chill','none'),
(5144,'es','¡Las chicas están soltando palomas!','¡Los chicos están soltando palomas!','soltando palomas blancas','dando de comer a palomas blancas','dramatic','exclamation'),
(5145,'es','El tranvía está justo detrás de él.','El autobús está justo detrás de él.','un tranvía en la plaza','un tranvía en un puente','chill','none'),
(5146,'es','¡La piel es una sola tira larga!','¡La piel son dos tiras cortas!','una larga tira de piel','una tira de cinta adhesiva','dramatic','exclamation'),
(5147,'es','¡Cuánta gente está cruzando!','¡Cuántos coches están cruzando!','gente llenando el paso de peatones','gente esperando el autobús','dramatic','exclamation'),
(5148,'es','Mañana tranquila: ¡buenos días, ciudad vacía!','Noche tranquila: ¡buenas noches, ciudad vacía!','una calle vacía por la mañana','una calle concurrida por la mañana','dramatic','exclamation'),
(5149,'es','¡Qué farmacia más grande y antigua!','¡Qué panadería más grande y antigua!','una gran farmacia antigua','una farmacia en un hospital','dramatic','exclamation'),
(5150,'es','Está entregando una receta.','Está entregando un billete de tren.','entregando una receta','escribiendo una receta','business','none'),
(5151,'es','El marco es plateado.','El marco es dorado.','un marco de fotos plateado','un marco de ventana plateado','chill','none'),
(5152,'es','¡Su dormitorio es todo cojines!','¡Su dormitorio es todo libros!','cojines en el dormitorio','cojines en el salón','dramatic','exaggeration'),
(5153,'es','El equipo está plantando el bancal.','El equipo está pintando el bancal.','un bancal elevado de huerto','una cama sin hacer','business','none'),
(5155,'es','¡Almuerzo para toda la familia!','¡Almuerzo para solo dos personas!','un gran almuerzo familiar','un almuerzo rápido en el trabajo','dramatic','exclamation'),
(5156,'es','Ha marcado, así que se arrodilla.','Ha fallado, así que se arrodilla.','arrodillarse en el césped','arrodillarse para rezar','dramatic','none'),
(5157,'es','¡Todo el vecindario está jugando al fútbol!','¡Todo el vecindario está jugando al voleibol!','un partido de fútbol del vecindario','una carrera de bicis del vecindario','dramatic','exaggeration'),
(5158,'es','Está conectando los cables.','Está cortando los cables.','conectando un equipo gamer','conectando con amigos','nerd','none'),
(5159,'es','La tubería lo mojó a propósito.','El perro lo mojó a propósito.','mojando la cara del fontanero','mojando las plantas de la cocina','ironic','blaming_someone'),
(5160,'es','Sale disparado bajo la lluvia.','Sale disparado bajo la nieve.','pasando disparado entre palomas','pasando disparado ante la policía','chill','none'),
(5162,'es','Vistas hermosas y empanadillas.','Vistas hermosas y tortitas.','un hermoso lago de montaña','una playa hermosa','chill','none'),
(5163,'es','Políticos discutiendo, como siempre.','Políticos abrazándose, como siempre.','políticos enfadados señalando','políticos dándose la mano','ironic','cliche'),
(5164,'es','Esta campaña lo tiene todo: carteles, debates, confeti.','Esta campaña lo tiene todo: carteles, debates, fuegos artificiales.','una campaña electoral','una campaña contra el tabaco','gossip','exaggeration'),
(5165,'es','El río está lleno de plástico.','El río está lleno de peces.','plástico en el río','plástico en el contenedor de reciclaje','dramatic','none'),
(5166,'es','El tranvía está en las vías.','El tranvía está en el césped.','vías de tranvía entre adoquines','vías de tranvía en un túnel','chill','none'),
(5168,'es','La hornada de pastelitos está bien.','La hornada de pan está bien.','una hornada de pasteles de nata','una hornada de galletas','chill','understatement'),
(5169,'es','Está enviando una postal por correo.','Está enviando un paquete por correo.','enviar una postal por correo','enviar un paquete por correo','chill','none'),
(5170,'es','Está entregando un paquete.','Está entregando una pizza.','un paquete envuelto de cumpleaños','un paquete de vacaciones','chill','none'),
(5171,'es','Está añadiendo caldo a la olla.','Está añadiendo leche a la olla.','añadiendo verduras a la olla','añadiendo sal a la sopa','chill','none'),
(5172,'es','¡Pobre masa! La está golpeando.','¡Pobre puerta! La está golpeando.','golpeando la masa de pan','golpeando la puerta de entrada','dramatic','exclamation'),
(5173,'es','Menos mal que lleva impermeable.','Menos mal que lleva pamela.','un impermeable rojo con capucha','un impermeable en el perchero','chill','understatement'),
(5174,'es','Es una cena alegre.','Es un desayuno alegre.','una cena familiar alegre','una fiesta de oficina alegre','chill','none'),
(5175,'es','Bonito bigote, pulso firme.','Bonita barba, pulso firme.','un camarero con bigote','un camarero afeitándose el bigote','flirt','none'),
(5176,'es','Café caliente en una taza grande.','Té caliente en una taza grande.','una taza grande y blanca','una taza sin asa','chill','none'),
(5177,'es','Está sirviendo de una tetera.','Está sirviendo de una botella.','sirviendo de una tetera blanca','una tetera en el fuego','chill','none'),
(5178,'es','Está horneando con pañuelo en la cabeza.','Está horneando con sombrero en la cabeza.','un pañuelo azul marino','un pañuelo al viento','chill','none'),
(5179,'es','Mete la mano para alcanzar algo del horno.','Mete la mano para alcanzar algo de la nevera.','alcanzando el horno caliente','alcanzando el estante de arriba','chill','none'),
(5180,'es','El orador está en el atril.','El orador está al piano.','un orador en el atril','un orador entre el público','business','none'),
(5181,'es','Su firma está en tinta azul.','Su firma está en tinta roja.','una firma azul recién hecha','una firma en un cheque','business','none'),
(5183,'es','¡Tan apasionado que vuela la tiza!','¡Tan apasionado que vuelan los libros!','un profe mayor apasionado','un cantante joven apasionado','dramatic','exaggeration'),
(5184,'es','Le pidió matrimonio. ¡Qué romántico!','Le cantó una canción. ¡Qué romántico!','una pedida romántica','una comedia romántica','flirt','exclamation'),
(5185,'es','La amabilidad mantiene seco al hombre.','La amabilidad mantiene seco al perro.','amabilidad bajo la lluvia','amabilidad bajo el sol','chill','none'),
(5186,'es','El público está en la plaza.','El público está en la iglesia.','el público en la plaza','el público en el teatro','chill','none'),
(5187,'es','¡Qué chico tan fuerte! ¡Tira de un carro!','¡Qué chico tan fuerte! ¡Tira de un coche!','tirando de un carro de granja','tirando de un carro de caballos','low_iq','exclamation'),
(5188,'es','¿Una bota? Decepción total.','¿Un pez? Decepción total.','decepción en un embarcadero','decepción en un zoo','ironic','understatement'),
(5189,'es','Parte del tiempo: sigue lloviendo.','Parte del tiempo: sigue nevando.','comprobando el tiempo con la mano','el tiempo en la tele','chill','none'),
(5190,'es','¿Día ventoso? ¡A ella le encanta!','¿Día soleado? ¡A ella le encanta!','un paseo marítimo ventoso','una cima ventosa','slang','exclamation'),
(5191,'es','Una bandera en una llanura nevada.','Una bandera en una playa de arena.','una llanura blanca nevada','una calle nevada de ciudad','chill','none'),
(5192,'es','Solo nieve hasta el horizonte.','Solo arena hasta el horizonte.','nieve hasta el horizonte','el mar en el horizonte','dramatic','none'),
(5193,'es','¿Crema en el sarpullido? ¡Escuece!','¿Crema en la quemadura? ¡Escuece!','crema en un sarpullido rojo','un sarpullido en la mejilla','gossip','exclamation'),
(5194,'es','¿Adivina a quién le encanta esta novela?','¿Adivina a quién le encanta esta peli?','leyendo una novela gorda','escribiendo una novela','gossip','none'),
(5195,'es','Sus libros ocupan todo el banco.','Sus zapatos ocupan todo el banco.','libros en un banco del parque','un perro en un banco','gossip','exaggeration'),
(5196,'es','Su moño y su libro van a todas partes.','Su moño y su perro van a todas partes.','un moño rubio en lo alto','un bollo dulce','chill','exaggeration'),
(5197,'es','¡La oficina se está rebelando!','¡La oficina se está durmiendo!','rebelándose contra el trabajo','rebelándose contra los padres','dramatic','exclamation'),
(5198,'es','Le está dando una hoja.','Le está dando una taza.','una hoja pequeña escrita a mano','una sábana en la cama','chill','none'),
(5199,'es','Receta seguida paso a paso.','Mapa seguido paso a paso.','siguiendo una receta escrita a mano','siguiendo a un amigo en redes','business','none'),
(5200,'es','¡Qué grupo tan animado!','¡Qué perro tan animado!','un salón muy animado','una discoteca animada','dramatic','exclamation'),
(5201,'es','El agua lo refleja todo, hasta el volcán.','El agua lo refleja todo, hasta la luna.','un volcán reflejado en el agua','una cara en un espejo','business','none'),
(5202,'es','¡Ha puesto toda la tienda en la nevera!','¡Ha puesto toda la tienda en el horno!','poniendo comida en la nevera','poniendo comida en la mesa','dramatic','exaggeration'),
(5203,'es','¡Han llegado los parientes!','¡Se han ido los parientes!','parientes en la puerta de casa','parientes en un aeropuerto','dramatic','exclamation'),
(5204,'es','La habitación ha mejorado muchísimo.','El jardín ha mejorado muchísimo.','mejorando una habitación vieja','mejorando su inglés','business','none'),
(5205,'es','Ella está haciendo el juramento.','Él está haciendo el juramento.','haciendo un juramento','rompiendo un juramento','chill','none'),
(5206,'es','¡Encontró la prueba!','¡Perdió la prueba!','colgando pruebas en el tablón','escondiendo la prueba','dramatic','guessing'),
(5207,'es','Montañas enormes, mucho sudor.','Lagos enormes, mucho sudor.','chorreando sudor','sudor después de la sauna','dramatic','none'),
(5208,'es','¡Cada cocina le fascina!','¡Cada bebida le fascina!','tres cocinas diferentes','una sola cocina','gossip','exaggeration'),
(5209,'es','Nadie trabaja; todos están holgazaneando.','Nadie trabaja; todos están bailando.','holgazaneando en una hamaca','holgazaneando en un barco','ironic','exaggeration')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
