begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(2155,'sk','Ten sebavedomý úsmev funguje.','Ten nervózny úsmev funguje.','sebavedomý polúsmev','sebavedomý hlasný smiech','flirt','none'),
(2156,'sk','Slnko sedí na horizonte.','Mesiac sedí na horizonte.','slnko na horizonte','loď na horizonte','chill','none'),
(2157,'sk','Bábätko z Indie má na sebe zlato.','Bábätko z Indie má na sebe červenú.','obraz z Indie','koberec z Indie','chill','none'),
(2158,'sk','Milujem túto oranžovú šatku na hlavu!','Milujem túto modrú šatku na hlavu!','oranžová šatka na hlavu','sťahovanie šatky z hlavy','flirt','exclamation'),
(2159,'sk','Mačka si pripadá veľmi majestátna.','Pes si pripadá veľmi majestátny.','majestátna mačka','majestátny lev','ironic','guessing'),
(2161,'sk','Génius má nový nápad.','Génius má novú mačku.','génius hľadiaci na hviezdy','génius píšuci vzorce','nerd','guessing'),
(2162,'sk','Jej ryšavé vlasy vyzerajú dokonale.','Jej čierne vlasy vyzerajú dokonale.','dlhé vlnité ryšavé vlasy','ryšavé vlasy v drdole','flirt','none'),
(2164,'sk','Do lesa vedie cestička. Kto pôjde prvý?','Do lesa tečie rieka. Kto pôjde prvý?','cestička cez les','chatka v lese','dramatic','guessing'),
(2172,'sk','Športové auto v búrke farieb.','Športové auto v snehovej búrke.','tmavomodré športové auto','tmavomodré rodinné auto','dramatic','exaggeration'),
(2174,'sk','Strom kvitne v snehu!','Strom horí v snehu!','strom kvitnúci v noci','kvety kvitnúce na jar','dramatic','exclamation'),
(2175,'sk','Polnoc v borovicovom lese.','Polnoc na púšti.','polnoc pod hviezdami','párty o polnoci','chill','none'),
(2176,'sk','V uličke prší!','V uličke sneží!','daždivá ulička v knižnici','rušná ulička v supermarkete','dramatic','exclamation'),
(2177,'sk','Aj mesiac prišiel kvôli didžejovi!','Aj slnko prišlo kvôli didžejovi!','didžej na ulici','didžej v klube','slang','exaggeration'),
(2178,'sk','Pst, dve mačky kukajú.','Pst, dva psy kukajú.','kukanie spoza lístia','kukanie cez okno','gossip','none'),
(2181,'sk','Ulica je fakt až moc preplnená.','Ulica je fakt až moc prázdna.','preplnená neónová ulica','preplnený vagón vlaku','slang','none'),
(2182,'sk','Turista má červený batoh.','Turista má modrý batoh.','turista na skalnej rímse','turista v stane','chill','none'),
(2184,'sk','Tiger reve!','Lev reve!','revúci tiger','spiaci tiger','dramatic','exclamation'),
(2185,'sk','Klavirista má blond vlasy.','Klavirista má čierne vlasy.','klavirista pri klavíri','klavirista pri klávesoch','chill','none'),
(2186,'sk','Ježiš nosí korunu z tŕňov.','Ježiš nosí korunu zo zlata.','koruna z tŕňov','ruža s tŕňmi','chill','none'),
(2187,'sk','Budha medituje.','Budha tancuje.','meditujúci Budha','ležiaci Budha','chill','none'),
(2188,'sk','Chlapec plače, mama nie.','Chlapec spieva, mama nie.','plačúci na bicykli','plačúci v posteli','ironic','none'),
(2189,'sk','Niekto padá cez palubu!','Niekto skáče cez palubu!','padať cez palubu dozadu','zaspávať v člne','dramatic','exclamation'),
(2190,'sk','Tento zloduch má horiace oči.','Tento zloduch má modré oči.','zloduch v horiacich ruinách','zloduch na hrade','dramatic','none'),
(2191,'sk','Android má ľudskú tvár.','Android má dlhú bradu.','žiariaca androidka','android v kuchyni','nerd','none'),
(2192,'sk','Harry Potter by tieto banky zbožňoval.','Harry Potter by tieto metly zbožňoval.','žiariace sklenené banky','termoska na čaj','nerd','guessing'),
(2194,'sk','Tropické listy sú veľké. Wau.','Tropické listy sú maličké. Wau.','husté tropické listy','tropická pláž','low_iq','none'),
(2195,'sk','Akvarel steká.','Olejová farba steká.','portrét v akvareli','krajina v akvareli','chill','none'),
(2199,'sk','Všade jemné ruže!','Všade jemné tulipány!','jemné ružové ruže','jemná sklenená váza','dramatic','exaggeration'),
(2200,'sk','V tej róbe je taká elegantná.','V tom kabáte je taká elegantná.','elegantná splývavá róba','elegantný čierny oblek','flirt','none'),
(2201,'sk','Jej oranžové brnenie je fakt super!','Jej ružové brnenie je fakt super!','oranžové vlasy a brnenie','pomaranč v jej ruke','flirt','exclamation'),
(2202,'sk','Jeho biele sako je elegantné.','Jeho červené sako je elegantné.','elegantné biele sako','elegantný tmavý oblek','chill','none'),
(2204,'sk','Drží jahňa.','Drží psa.','jahňa v jeho náručí','jahňa na lúke','chill','none'),
(2207,'sk','Robotická ruka ukazuje.','Robotická ruka máva.','ukazovanie na obrazovku','ukazovanie na oblohu','chill','none'),
(2208,'sk','Jej vlasy sú žiarivo ružové.','Jej vlasy sú žiarivo zelené.','žiarivo ružové vlasy','žiarivo ružové šaty','business','none'),
(2211,'sk','Hádaj, kto má trojzubec? Boh mora.','Hádaj, kto má kladivo? Boh mora.','boh s trojzubcom','trojzubec v piesku','gossip','guessing'),
(2212,'sk','Pekné pruhy, tiger!','Pekné fľaky, tiger!','tiger s čiernymi pruhmi','zebra s čiernymi pruhmi','slang','exclamation'),
(2213,'sk','Fakt: barany majú zatočené rohy.','Fakt: barany majú rovné rohy.','baran so zatočenými rohmi','baran spásajúci trávu','nerd','cliche'),
(2214,'sk','Cez to vidím hrad.','Cez to vidím kostol.','pohľad cez dieru v skale','pohľad cez okno','chill','none'),
(2216,'sk','Modlí sa pri oltári.','Spieva pri oltári.','modlitba pri oltári so sviečkami','svadba pred oltárom','chill','none'),
(2217,'sk','Zosiela kúzlo. Super.','Hádže sieť. Super.','zosielanie kúzla','hádzanie rybárskej siete','slang','none'),
(2218,'sk','Všade okolo neho sú obvody.','Všade okolo neho sú kvety.','žiariace dráhy obvodov','pretekársky okruh','nerd','none'),
(2220,'sk','Starostlivo počíta peniaze.','Starostlivo počíta mince.','počítanie kopy bankoviek','odpočítavanie sekúnd','business','none'),
(2224,'sk','Držia sa za ruky.','Podávajú si ruky.','držať sa za ruky v daždi','držať sa za ruky na slnku','flirt','none'),
(2225,'sk','Chúďa, má úplne premočené vlasy.','Chúďa, má úplne suché vlasy.','premočená v silnom daždi','premočená v horúcej vode','gossip','none'),
(2226,'sk','Má zlaté náramky.','Má zlaté rukavice.','zlaté náramky na zápästiach','náramok v obchode','chill','none'),
(2228,'sk','Sedí vysoko nad mestom.','Sedí vysoko nad morom.','vysoko nad mestom','nad oblakmi','chill','none'),
(2231,'sk','Obrovská zlatá sfinga.','Obrovská strieborná sfinga.','socha zlatej sfingy','spiaca mačka sfinga','chill','none'),
(2232,'sk','Budha je taký pokojný.','Budha je taký nahnevaný.','pokojný zlatý Budha','pokojný zlatý chrám','chill','none'),
(2233,'sk','Má dve rukavice na bejzbal.','Má dve pálky na bejzbal.','rukavice na bejzbal v oboch rukách','bejzbal v telke','chill','none'),
(2234,'sk','Bojovník má veľké svaly.','Bojovník má veľký štít.','veľké svaly bojovníka','veľký štít bojovníka','chill','none'),
(2235,'sk','Je zobrazený presne z profilu.','Je zobrazený zozadu.','muž presne z profilu','profilová fotka online','nerd','none'),
(2236,'sk','Palác pod obrovským mesiacom. Wau!','Palác pod obrovským slnkom. Wau!','palác v horách','palác na púšti','dramatic','exclamation'),
(2237,'sk','Pozri na to lesklé žlté auto!','Pozri na to lesklé červené auto!','lesklé žlté auto','lesklý žltý autobus','slang','exclamation'),
(2238,'sk','Mešita má veľa kupol.','Mešita má jednu kupolu.','veľkolepá mešita s kupolami','mešita na púšti','chill','none'),
(2242,'sk','Kŕdeľ má nula voľných miest.','Kŕdeľ má veľa voľných miest.','kŕdeľ malých vtákov','stádo oviec','business','exaggeration'),
(2245,'sk','Je to len trochu zarastené.','Je to len trochu zasnežené.','zarastená chalupa','zarastený trávnik','ironic','understatement'),
(2247,'sk','V Škótsku stojí osamelý kostol.','V Škótsku stojí osamelý hrad.','kostol v Škótsku','hrad v Škótsku','chill','none'),
(2249,'sk','Steampunkové mesto z ozubených kolies.','Steampunkové mesto zo skla.','mosadzné steampunkové veže','steampunková kostýmová párty','chill','none'),
(2250,'sk','Uprene hľadí na mesto.','Uprene hľadí na more.','uprene hľadieť na daždivé mesto','uprene hľadieť na hviezdnu oblohu','dramatic','none'),
(2251,'sk','Dress code v nebi: biele rúcho.','Dress code v nebi: čierne rúcho.','dlhé biele rúcho','rúcho s kapucňou','business','cliche'),
(2254,'sk','Zamrznutý palác. Ahoj, Elsa!','Zamrznuté jazero. Ahoj, Elsa!','zamrznutý zasnežený palác','mrazený hrášok vo vrecku','slang','exclamation'),
(2256,'sk','Jej nohy sú úplne mechanické.','Jej nohy sú úplne drevené.','mechanické ruky a nohy','mechanické hodinky','nerd','none'),
(2257,'sk','Jej obočie je veľmi tmavé.','Jej obočie je veľmi svetlé.','husté tmavé obočie','tenké blond obočie','chill','none'),
(2258,'sk','Kostol má vysokú špicatú vežu.','Kostol má okrúhlu kupolu.','vysoká špicatá veža kostola','špicatá veža na hrade','chill','none'),
(2259,'sk','Vezmi ma k tejto lagúne hneď teraz!','Vezmi ma k tomuto ľadovcu hneď teraz!','tyrkysová lagúna s palmami','zamrznutá lagúna v zime','dramatic','exclamation'),
(2260,'sk','Chudák veslica, nikto ju nechce.','Chudák loď, nikto ju nechce.','prázdna drevená veslica','veslica plná ľudí','dramatic','exaggeration'),
(2262,'sk','Bodky a čiary ich spájajú.','Bodky a čiary ich rozdeľujú.','čiary spájajúce dvoch ľudí','kábel spájajúci telefón','nerd','none'),
(2268,'sk','Je na napnutom lane. Bez siete!','Je na rebríku. Bez siete!','balansovanie na napnutom lane','cirkusové číslo na napnutom lane','dramatic','exclamation'),
(2269,'sk','Jej blúzka je voľná a biela.','Jej šaty sú voľné a biele.','voľná biela blúzka','tesná čierna blúzka','chill','none'),
(2271,'sk','Chilluje na chodbe.','Chilluje v kuchyni.','chodba vesmírnej lode','nemocničná chodba','slang','none'),
(2273,'sk','Roztrhané džínsy, celá v denime.','Roztrhané džínsy, celá v čiernom.','poriadne roztrhané modré džínsy','žehlenie modrých džínsov','slang','none'),
(2274,'sk','Ten golier z čipky je taký fancy!','Ten golier z kožušiny je taký fancy!','zdobený golier z čipky','zaväzovanie šnúrok na topánkach','gossip','none'),
(2275,'sk','Pekný outfit, obrie tenisky!','Pekný outfit, mini tenisky!','streetový outfit','outfit na svadbu','flirt','exclamation'),
(2278,'sk','Pozerá hore na oblohu.','Pozerá hore na lietadlo.','pozrieť hore na oblaky','vyhľadať slovo v slovníku','chill','none'),
(2280,'sk','Objíma ju pri západe slnka.','Objíma ju v aute.','objímať sa na plachetnici','prijať nový nápad','flirt','none'),
(2282,'sk','Plachtenie pri západe slnka. Pohodička.','Surfovanie pri západe slnka. Pohodička.','plachtenie pri západe slnka','plachtenie v búrke','slang','none'),
(2284,'sk','Perie? Odvážny účes.','Perly? Odvážny účes.','účes z peria','krátky účes','flirt','none'),
(2285,'sk','Jej mikina je obrovská.','Jej batoh je obrovský.','veľká modrá mikina','mikina na stoličke','chill','exaggeration'),
(2287,'sk','Sedí sám, ponorený do žiaľu.','Sedí sám v aute.','žiaľ v tmavej záhrade','žiaľ na pohrebe','dramatic','none'),
(2288,'sk','Crop top v prístave.','Crop top v lyžiarskom stredisku.','čierny crop top','biely crop top','chill','none'),
(2291,'sk','Len pár asteroidov. Pohoda.','Len pár vtákov. Pohoda.','vznášajúce sa asteroidy','asteroid dopadajúci na Zem','ironic','understatement'),
(2295,'sk','Tie rukávy sú obrovské!','Tie čižmy sú obrovské!','široké biele rukávy','krátke čierne rukávy','dramatic','exclamation'),
(2296,'sk','Jej kvetinové šaty ladia so stenou!','Jej pruhované šaty ladia so stenou!','oranžové kvetinové šaty','kvetinová plážová košeľa','gossip','exaggeration'),
(2297,'sk','Vlny narážajú na breh.','Vlny narážajú na loď.','palmy na brehu','loď na brehu','chill','none'),
(2300,'sk','Gitara je v plameňoch!','Klavír je v plameňoch!','gitara v plameňoch','dom v plameňoch','dramatic','exclamation'),
(2301,'sk','Raketoplán práve vypúšťajú.','Lietadlo práve vypúšťajú.','vypúšťanie raketoplánu','uvedenie nového produktu','chill','none'),
(2302,'sk','Je v beztiažovom stave a uvoľnený.','Je v beztiažovom stave a vystrašený.','astronaut v beztiažovom stave','pierko v beztiažovom stave','chill','none'),
(2305,'sk','Skalnatá cesta k majáku.','Skalnatá cesta k hradu.','skalnatý výbežok','skalnatá pláž s lehátkami','chill','none'),
(2306,'sk','Vidiek nemá konca.','Mesto nemá konca.','deti na vidieku','deti odchádzajúce z vidieka','chill','exaggeration'),
(2308,'sk','Viking drží čepeľ.','Viking drží sekeru.','viking v kožušine','viking na lodi','chill','none'),
(2310,'sk','Z klavíra stúpa melódia.','Z bubna stúpa melódia.','stúpajúca zlatá melódia','klesajúca zlatá melódia','dramatic','none'),
(2311,'sk','Vitráž je obrovská.','Vitráž je maličká.','vysoké okná s vitrážou','lampa s vitrážou','chill','none'),
(2312,'sk','Pretekárske auto pri palmách.','Pretekárske auto pri borovicách.','červené pretekárske auto','červený dostihový kôň','chill','none'),
(2313,'sk','Domov je tam, kde je obytná dodávka.','Domov je tam, kde je oranžový stan.','oranžová obytná dodávka','obytná dodávka v meste','chill','cliche'),
(2314,'sk','Kostým ducha: jedna stará plachta.','Kostým ducha: jeden starý uterák.','duch z bielej plachty','duch na hrade','low_iq','cheap_quality'),
(2315,'sk','Táto krajina je z papiera!','Táto krajina je zo skla!','krajina z papiera','fotka krajiny','dramatic','exclamation'),
(2318,'sk','Má veľmi dlhý meč.','Má veľmi dlhú kopiju.','dlhý zahnutý meč','dlhý rovný meč','chill','none'),
(2322,'sk','Sklo je rozbité!','Hodiny sú rozbité!','portrét v rozbitom zrkadle','zlomená ruka v sadre','dramatic','exclamation'),
(2324,'sk','Spieva ako hviezda!','Tancuje ako hviezda!','spievať do mikrofónu','spievať v sprche','flirt','exaggeration'),
(2326,'sk','Princ má cool modré vlasy.','Princ má cool ružové vlasy.','princ s korunou','princ na koni','slang','none'),
(2327,'sk','Toto auto a palmy vyzerajú tak cool.','Tento bicykel a palmy vyzerajú tak cool.','palmy pri západe slnka','palmy na ostrove','slang','none'),
(2328,'sk','Aký „skromný“ trón!','Aká „skromná“ posteľ!','obrovský zlatý trón','prázdny zlatý trón','ironic','exclamation'),
(2330,'sk','Chce ti dať kvety.','Chce ti dať tortu.','dáva tri žlté kvety','dáva červené ruže','flirt','guessing'),
(2333,'sk','Sú do seba tak zamilovaní!','Sú na seba tak nahnevaní!','zamilovaní pod jesenným lístím','zamilovaní na pláži','dramatic','exclamation'),
(2340,'sk','Tento dom je trochu zvláštny.','Toto auto je trochu zvláštne.','zvláštny vysoký dom','zvláštna stará loď','chill','understatement'),
(2341,'sk','S kvetmi vyzerá aj smrť pekne.','So sviečkami vyzerá aj smrť pekne.','smrť medzi kvetmi','smrť pri autonehode','ironic','none'),
(2344,'sk','Domy sú trochu krivé.','Stromy sú trochu krivé.','vysoké krivé domy','krivý rám obrazu','ironic','understatement'),
(2345,'sk','Aká dlhá brada čarodejníka!','Aká krátka brada čarodejníka!','starý čarodejník v sivom','starý čarodejník v červenom','dramatic','exclamation'),
(2347,'sk','Preskúmava exoplanétu.','Preskúmava hlbokú jaskyňu.','preskúmavanie cudzieho sveta','preskúmavanie starého hradu','nerd','none'),
(2349,'sk','Aj mačka sa prezliekla do kostýmu!','Aj pes sa prezliekol do kostýmu!','prezlečené za čarodejnice','prezlečení za pirátov','gossip','exclamation'),
(2350,'sk','Niekto vyrezal tváre! Wau!','Niekto vyrezal mená! Wau!','vyrezávané tváre z tekvíc','vyrezávané drevené tváre','low_iq','exclamation'),
(2351,'sk','Niekto šoféruje zelené auto.','Niekto šoféruje žlté auto.','šoférovať cez jeseň','šoférovať cez sneh','chill','none'),
(2353,'sk','Tie huby sú obrovské, brácho.','Tie huby sú maličké, brácho.','obrovské ružové huby','obrovské ružové kvety','slang','none'),
(2354,'sk','Obrovská zlatá slávnostná pokrývka hlavy!','Obrovská strieborná slávnostná pokrývka hlavy!','obrovská zlatá slávnostná pokrývka hlavy','skladanie slávnostnej pokrývky hlavy','dramatic','exclamation'),
(2356,'sk','Cesta vedie k planéte.','Cesta vedie k hradu.','k obrovskej planéte','k obrovskému mestu','dramatic','none'),
(2357,'sk','Dom je čiernobiely.','Dom je červenobiely.','čiernobiela kresba','čiernobiely film','chill','none'),
(2358,'sk','Farma má červené strechy.','Farma má modré strechy.','farma na svahu','farma s kravami','chill','none'),
(2359,'sk','Majú na sebe tradičné oblečenie.','Majú na sebe moderné oblečenie.','tradičné indické oblečenie','tradičná svadobná torta','chill','none'),
(2360,'sk','To červené auto je šialene rýchle.','Tá červená dodávka je šialene rýchla.','rýchle červené auto','rýchla červená loď','slang','exaggeration'),
(2363,'sk','Mení sa na záhadný dym.','Mení sa na záhadnú vodu.','záhadná žena z dymu','záhadné zamknuté dvere','dramatic','none'),
(2364,'sk','Za ním je biely býk.','Za ním je biely kôň.','býk so zahnutými rohmi','býk v aréne','chill','none'),
(2365,'sk','Jeho oblek z kovu je taký lesklý.','Jeho oblek z kovu je taký špinavý.','červený oblek z kovu','červené auto z kovu','slang','none'),
(2367,'sk','Toto auto je trošku špinavé.','Tento autobus je trošku špinavý.','staré špinavé športové auto','špinavý starý autobus','ironic','understatement'),
(2368,'sk','Táto pláž je totálny raj.','Táto púšť je totálny raj.','tropický raj pri západe slnka','raj pre lyžiarov','slang','none'),
(2371,'sk','Anjel je ponorený do žiaľu.','Anjel je ponorený do knihy.','anjel plný žiaľu','anjel plný radosti','dramatic','none'),
(2372,'sk','Vyzerá totálne vyčerpaný.','Vyzerá totálne nadšený.','vyčerpaný robotník','vybitá batéria mobilu','slang','none'),
(2373,'sk','Vo vesmíre je nejako plno.','Vo vesmíre je nejako prázdno.','vesmír plný planét','vesmír bez hviezd','ironic','exaggeration'),
(2375,'sk','Polovica sivá, polovica žltá. Nevie sa rozhodnúť.','Polovica sivá, polovica zelená. Nevie sa rozhodnúť.','polovica žltého auta','polovica žltého autobusu','low_iq','guessing'),
(2378,'sk','Teraz totálne relaxuje.','Teraz totálne beží.','relaxovanie pod mesiacom','relaxovanie na pláži','slang','none'),
(2379,'sk','Padajú červené listy.','Padajú červené jablká.','listy padajúce v daždi','sneh padajúci na autá','chill','none'),
(2380,'sk','Auto uniká pred ohňom!','Auto uniká pred povodňou!','uniknúť z horiaceho lesa','uniknúť z horiaceho domu','dramatic','exclamation'),
(2381,'sk','Tie pazúry sú fakt ostré!','Tie zuby sú fakt ostré!','pazúry na konári','pazúry mačky','dramatic','exclamation'),
(2382,'sk','Pozri, jej chvost má modré šupiny.','Pozri, jej chvost má ružové šupiny.','chvost s modrými šupinami','váženie sa na váhe','gossip','none'),
(2383,'sk','Všade oheň a drahokamy!','Všade ľad a drahokamy!','trblietavé farebné drahokamy','drahokamy v tmavej jaskyni','dramatic','exaggeration'),
(2384,'sk','Maličké kráľovstvo na kopci.','Maličké kráľovstvo na ostrove.','rozprávkové kráľovstvo','ríša zvierat','chill','none'),
(2385,'sk','Fialová mimozemská krajina.','Zelená mimozemská krajina.','fialový mimozemský svet','mimozemšťan vo vesmírnej lodi','nerd','none'),
(2386,'sk','Zábradlie je otočené k západu slnka.','Zábradlie je otočené k hore.','kovové zábradlie balkóna','zábradlie na schodisku','chill','none'),
(2387,'sk','Strom je pokrútený. Super.','Strom je rovný. Super.','pokrútený starý strom','pokrútený kovový plot','low_iq','none'),
(2388,'sk','Tento gamer miluje ružovú.','Tento gamer miluje zelenú.','gamer v ružovom','gamer v modrom','gossip','none'),
(2389,'sk','Modlí sa s vierou.','Modlí sa s roztiahnutými rukami.','modlitba s hlbokou vierou','strácanie viery','chill','none'),
(2390,'sk','Taká štýlová na pláži!','Taká štýlová na lodi!','štýlový plážový look','štýlový zimný kabát','flirt','exclamation'),
(2391,'sk','Epická scenéria, červená obloha.','Epická scenéria, modrá obloha.','scenéria s obrovským mesiacom','kulisy na školské predstavenie','slang','none'),
(2392,'sk','Prechádzka v slamenom klobúku? Štýlové.','Prechádzka v červenom klobúku? Štýlové.','prechádzka medzi kvetmi','prechádzka po pláži','flirt','none'),
(2393,'sk','Kancelársky look s lodičkami na podpätku.','Kancelársky look s teniskami.','čierne lodičky na podpätku s remienkami','lodičky na podpätku v krabici','business','none'),
(2394,'sk','Musí si vybrať cestu.','Musí si vybrať loď.','vyberanie správnej cesty','vyberanie správnych šiat','dramatic','guessing'),
(2395,'sk','Jeho vesta má zlaté gombíky.','Jeho vesta má strieborné gombíky.','čierna kožená vesta','vesta pod sakom','chill','none'),
(2396,'sk','Ten šnurovaný korzet je úžasný.','Tá šnurovaná rukavica je úžasná.','šnurovaný korzet','šnurovacie čižmy','flirt','none'),
(2397,'sk','Táto izba je taká pochmúrna!','Táto izba je taká slnečná!','pochmúrna gotická izba','pochmúrny daždivý deň','dramatic','exclamation'),
(2398,'sk','Terasa ponúka výhľad na more.','Terasa ponúka výhľad na mesto.','vykachličkovaná terasa pri mori','terasa v horách','business','none'),
(2400,'sk','To je ale zúrivý viking!','To je ale zúrivý pirát!','zúrivý nahnevaný pohľad','zúrivá búrka na mori','dramatic','exclamation'),
(2401,'sk','Chodník do sveta fantázie.','Chodník do rušného mesta.','lesný chodník vo svete fantázie','obálka fantasy knihy','chill','none'),
(2404,'sk','Tento lotos má oranžový stred.','Tento lotos má fialový stred.','biely kvet lotosu','jogová pozícia lotosu','nerd','none'),
(2406,'sk','Jeden džíp, priveľa tašiek!','Jeden bicykel, priveľa tašiek!','džíp plný tašiek','džíp v meste','dramatic','exaggeration'),
(2408,'sk','Predstavivosť otvára skutočnú cestu.','Predstavivosť otvára skutočné dvere.','kniha predstavivosti','žiadna predstavivosť','chill','none'),
(2411,'sk','Tá koruna je taká zdobná!','Tá maska je taká zdobná!','zdobná zlatá koruna','zdobné drevené dvere','gossip','none'),
(2412,'sk','Kráčajú zavesení do seba.','Bežia zavesení do seba.','kráčať zavesení do seba','sedieť zavesení do seba','chill','none'),
(2413,'sk','Objíma vlčie mláďa!','Objíma medvedie mláďa!','objímanie vlčieho mláďaťa','objímanie veľkého vlka','dramatic','exclamation'),
(2415,'sk','Boh nosí girlandy z kvetov.','Boh nosí girlandy z papiera.','girlandy z červených kvetov','girlandy na vianočnom stromčeku','chill','none'),
(2417,'sk','Tma a svetlo v harmónii.','Červená a modrá v harmónii.','guľa harmónie','spev v harmónii','nerd','none'),
(2418,'sk','Myslím, že je to spevavec.','Myslím, že je to holub.','spevavec na konári','spevavec na streche','low_iq','guessing'),
(2420,'sk','Táto rozheganá veža je „bezpečná“.','Tento rozheganý most je „bezpečný“.','rozheganá veža z domov','rozheganá stará stolička','ironic','understatement'),
(2421,'sk','Táto huba je veľká. Fakt veľká.','Táto huba je malá. Fakt malá.','obrovská bledá huba','pleseň na starom chlebe','low_iq','exaggeration'),
(2422,'sk','Číta si v trakových nohaviciach.','Spí v trakových nohaviciach.','modré rifľové trakové nohavice','trakové nohavice od farby','chill','none'),
(2424,'sk','Cyprusy rastú vľavo.','Cyprusy rastú vpravo.','rad cyprusov','cyprus v kvetináči','nerd','none'),
(2425,'sk','Čierna mačka v strašidelnom ráme!','Biela mačka v strašidelnom ráme!','rám s čiernymi ružami','rám bicykla','dramatic','exclamation'),
(2428,'sk','Tri monitory, maximálne sústredenie.','Dva monitory, maximálne sústredenie.','tri veľké monitory','elektronická pestúnka','business','exaggeration'),
(2429,'sk','Jou, jeleň stojí v potoku.','Jou, jeleň stojí na poli.','jeleň v potoku','jeleň v snehu','slang','none'),
(2430,'sk','Rieka tečie popri skalách.','Rieka tečie popri domoch.','rieka tečúca pomedzi skaly','rieka tečúca cez mesto','chill','none'),
(2433,'sk','Kôň cvála priamo na nás!','Osol cvála priamo na nás!','cválajúci biely kôň','cválajúci čierny kôň','dramatic','exclamation'),
(2434,'sk','Zátišie zobrazuje rozkvitnuté vetvičky.','Zátišie zobrazuje pomaranče.','zátišie s rozkvitnutými vetvičkami','zátišie s ovocím','nerd','none'),
(2435,'sk','Potok je plný kamienkov.','Potok je plný rýb.','hladké okrúhle kamienky','kamienky na pláži','chill','none'),
(2439,'sk','Ulica je v noci mokrá.','Ulica je v noci suchá.','mokrá nočná ulica','mokrá piesočná pláž','business','none'),
(2440,'sk','Elektrina je všade!','Voda je všade!','iskry elektriny','účet za elektrinu','dramatic','exaggeration'),
(2446,'sk','Veľké mašle, dlhé šnúrky!','Veľké mašle, krátke šnúrky!','dlhé žlté šnúrky','roztrhnuté žlté šnúrky','low_iq','exclamation'),
(2449,'sk','Len „pár“ svietiacich výkladov.','Len „pár“ tmavých výkladov.','svietiace výklady','rozbitý výklad','ironic','understatement'),
(2450,'sk','Búrka nad vodou.','Búrka nad mestom.','búrka nad vodou','búrka nad mestečkom','chill','none'),
(2451,'sk','Vták pri Eiffelovej veži.','Lietadlo pri Eiffelovej veži.','Eiffelova veža pri rieke','Eiffelova veža v snehu','chill','none'),
(2452,'sk','Prechádzka v snehu je romantická!','Prechádzka v daždi je romantická!','romantická prechádzka v snehu','romantická večera pri sviečkach','flirt','exclamation'),
(2454,'sk','Kľukatý chodník má lampáše.','Rovný chodník má lampy.','kľukatý dláždený chodník','kľukatá horská rieka','chill','none'),
(2455,'sk','Má na sebe zelené šortky.','Má na sebe zelené nohavice.','zelené rifľové šortky','zelené plavecké šortky','chill','none'),
(2457,'sk','Zdravotná sestra má stetoskop.','Zdravotná sestra má podložku s papiermi.','zdravotná sestra v uniforme','zdravotná sestra s bábätkom','chill','none'),
(2458,'sk','Gazdovský dom so svietiacimi oknami.','Gazdovský dom s tmavými oknami.','gazdovský dom pri západe slnka','gazdovský dom pri mori','chill','none'),
(2460,'sk','Poľné kvety v modrom kvetináči, zlatučké.','Poľné kvety v červenom kvetináči, zlatučké.','kvetináč s poľnými kvetmi','lúka plná poľných kvetov','slang','none'),
(2462,'sk','Na hviezdnatej oblohe je mesiac.','Na hviezdnatej oblohe je dúha.','hviezdnatá nočná obloha','hviezdnatá noc v meste','chill','none'),
(2463,'sk','V údolí nájdete ružové pivonky.','V údolí nájdete ružové tulipány.','ružové pivonky na kopci','pivonky vo váze','business','none'),
(2464,'sk','Vzory sú symetrické.','Vzory sú farebné.','symetrické vzory listov','symetrická budova','nerd','none'),
(2465,'sk','Vznáša sa. Nič zvláštne.','Pláva. Nič zvláštne.','vznášať sa na modrom nebi','vznášať sa v bazéne','ironic','understatement'),
(2466,'sk','Jej šaty sú z kryštálov.','Jej šaty sú z peria.','šaty zo žiariacich kryštálov','krištáľový pohár vody','chill','none'),
(2470,'sk','Saxofón má zahnutý koniec.','Saxofón má rovný koniec.','vznášajúci sa saxofón','saxofonista na pódiu','nerd','none'),
(2471,'sk','Je to fakt knihomoľka.','Je to fakt gamerka.','knihomoľ s knihou','knihomoľ s mobilom','gossip','none'),
(2472,'sk','Jej uniforma vyzerá fakt úhľadne.','Jej kabát vyzerá fakt úhľadne.','školská uniforma','policajná uniforma','chill','none'),
(2473,'sk','Veniec visí na červených dverách.','Veniec visí na modrých dverách.','veniec na dverách','veniec na jej hlave','chill','none'),
(2474,'sk','Divoká pena na rozbúrenom mori.','Divoká pena na pokojnom mori.','pena na rozbúrených vlnách','káva s mliečnou penou','dramatic','none'),
(2475,'sk','Číta si bosá.','Tancuje bosá.','bosá na lehátku','bosá na pláži','chill','none'),
(2477,'sk','Od vetra má strapaté vlasy.','Od dažďa má strapaté vlasy.','strapaté hnedé vlasy','neporiadna spálňa','low_iq','blaming_someone'),
(2478,'sk','Lekár sa na nás usmieva.','Lekár na nás kričí.','usmiaty kreslený lekár','lekár na operácii','chill','none'),
(2480,'sk','Auto má priveľa darčekov!','Auto má priveľa psov!','darčeky na streche auta','darčeky pod stromčekom','dramatic','exaggeration'),
(2481,'sk','Drží glóbus.','Drží loptu.','držať glóbus','snežná guľa','chill','none'),
(2482,'sk','Toľko vežičiek na jednom hrade!','Toľko vlajok na jednom hrade!','špicaté hradné vežičky','veža tanku','gossip','exclamation'),
(2483,'sk','V knihe ležia sušené kvety.','V knihe ležia čerstvé kvety.','sušené kvety v knihe','sušené ovocie v miske','chill','none'),
(2484,'sk','Kostolná veža je poriadne vysoká.','Hradná veža je poriadne vysoká.','kostolná veža v snehu','kostolná veža vo veľkomeste','chill','none'),
(2485,'sk','Vraní muž je fakt zlovestný.','Mačací muž je fakt zlovestný.','zlovestná postava s hlavou vrany','zlovestná čierna mačka','dramatic','none'),
(2486,'sk','Hieroglyfy pokrývajú stenu.','Kvety pokrývajú stenu.','stena plná hieroglyfov','hieroglyfy v učebnici','chill','none'),
(2490,'sk','Pekný klobúk! Je snehuliakovi zima?','Pekný klobúk! Je psovi zima?','snehuliak v klobúku','stavanie snehuliaka','low_iq','guessing'),
(2492,'sk','Dedinka je taká rušná!','Dedinka je taká tichá!','rušná zasnežená dedinka','rušná letná pláž','dramatic','exclamation'),
(2493,'sk','Farma je ušitá ako prešívaná deka.','Farma je ušitá ako vlajka.','farma ako prešívaná deka','prešívaná deka na posteli','nerd','none'),
(2494,'sk','Viktoriánska ulica. Nie je to Sherlock?','Moderná ulica. Nie je to Sherlock?','zasnežená viktoriánska ulica','viktoriánsky čajový večierok','gossip','guessing'),
(2495,'sk','Narátal som dva vrabce.','Narátal som štyri vrabce.','dva vrabce na konári','dva vrabce v snehu','low_iq','none'),
(2497,'sk','Santa Claus si dáva pauzu.','Santa Claus si dáva kúpeľ.','Santa Claus s darčekmi','Santa Claus so sobmi','gossip','guessing'),
(2498,'sk','Spája ich nežné objatie.','Spája ich nežný bozk.','nežné objatie','šťavnatý steak','chill','none'),
(2499,'sk','Dva plyšové medvedíky sa túlia.','Dva plyšové medvedíky sa bijú.','plyšové medvedíky v snehu','plyšové medvedíky na posteli','chill','none'),
(2500,'sk','Píše na laptope.','Píše na mobile.','písanie na laptope','nosenie laptopu','chill','none'),
(2501,'sk','Šiva medituje na skale.','Šiva medituje v člne.','Šiva s trojzubcom','Šiva s mečom','nerd','none'),
(2502,'sk','Lesná svätyňa plná machu.','Púštna svätyňa plná piesku.','machom obrastená lesná svätyňa','svätyňa v meste','chill','none'),
(2504,'sk','Krišna má pávie pero.','Krišna má orlie pero.','Krišna s korunou','Krišna s flautou','nerd','none'),
(2505,'sk','Dážď, puška a nula sťažností.','Slnko, puška a nula sťažností.','dlhá puška s optikou','puška na zemi','chill','understatement'),
(2506,'sk','Všetko je tu geometrické.','Všetko je tu modré.','ružové geometrické tvary','písomka z geometrie','chill','none'),
(2509,'sk','Chodník vedie cez levanduľu.','Chodník vedie cez pšenicu.','rady fialovej levandule','fľaštička levanduľového oleja','chill','none'),
(2510,'sk','Čas spánku pre chlapca aj mačku!','Čas spánku pre chlapca aj psa!','čas spánku pod dekou','rozprávka na dobrú noc s knihou','dramatic','exclamation'),
(2511,'sk','Okolo nich lietajú iskry.','Okolo nich lietajú listy.','iskry okolo páru','iskra zo zásuvky','flirt','none'),
(2512,'sk','Táto omaľovánka ťa potrebuje.','Tento fotoalbum ťa potrebuje.','stránka z omaľovánky','obálka omaľovánky','chill','guessing'),
(2514,'sk','Pridáva bylinky do misky.','Pridáva soľ do misky.','posýpanie sušenými bylinkami','krájanie čerstvých byliniek','chill','none'),
(2516,'sk','Je rok 2024.','Je rok 2025.','žiariaci rok 2024','rok 2025','chill','none'),
(2519,'sk','Videl si tento dvor za domom? Plameniak!','Videl si tento dvor za domom? Hojdačka!','rušný malý dvor za domom','zeleninový záhon za domom','gossip','exclamation'),
(2520,'sk','Posvätné svetlo zhora!','Posvätné svetlo zdola!','posvätný lúč svetla','posvätná rieka','dramatic','exclamation'),
(2522,'sk','Ďateliny majú štyri lístky.','Ďateliny majú tri lístky.','štvorlístky ďateliny','pole ďateliny s kravami','nerd','none'),
(2523,'sk','Dnes v noci je silné sneženie.','Dnes v noci je silný dážď.','silné sneženie nad dedinou','slabé sneženie v meste','chill','none'),
(2524,'sk','Má vychádzkovú palicu.','Má veľký dáždnik.','opiera sa o vychádzkovú palicu','vychádzková palica na túry','chill','none'),
(2525,'sk','Mama dvíha svoje medvieďa.','Mama dvíha svoje líšča.','zdvihnúť mláďa','zdvihnúť ťažkú krabicu','chill','none'),
(2526,'sk','Poseidón má dve kopije.','Poseidón má dva meče.','Poseidón vystupujúci z vĺn','Poseidón potápajúci loď','nerd','none'),
(2527,'sk','Didžej má plynovú masku. Prečo?','Didžej má lyžiarsku kuklu. Prečo?','plynová maska a slúchadlá','plynová maska a okuliare','ironic','guessing'),
(2528,'sk','Fialový cylinder? Odvážna voľba.','Čierny cylinder? Odvážna voľba.','lesklý fialový cylinder','kúzelníkov cylinder','gossip','understatement'),
(2529,'sk','Má jemnú tvár.','Má jemného psa.','jemná pokojná tvár','jemné pokojné more','chill','none'),
(2530,'sk','Svetlo sviečky žiari medzi ružami.','Svetlo sviečky žiari medzi knihami.','svetlo sviečky v lampáši','svetlo sviečky na torte','chill','none'),
(2531,'sk','Aj obloha sa pre nich trblieta.','Aj more sa pre nich trblieta.','trblietavá nočná obloha','perlivá voda v pohári','flirt','none'),
(2532,'sk','Jej šaty majú sivé volány.','Jej šaty majú červené volány.','šaty so sivými volánmi','volány na červenom klobúku','chill','none'),
(2533,'sk','Vzadu je to hmlisté.','Vzadu je to slnečné.','hmlistá stará ulica','hmlisté horské jazero','chill','none'),
(2536,'sk','Tento šimpanz vyzerá ako poriadny motorkár.','Tento šimpanz vyzerá ako poriadny surfer.','šimpanz na motorke','šimpanz na strome','gossip','cliche'),
(2537,'sk','Dievča číta rozprávku na dobrú noc.','Chlapec číta rozprávku na dobrú noc.','rozprávka na dobrú noc v posteli','rozprávka na dobrú noc v telke','chill','none'),
(2538,'sk','Červená čiapočka verí vlkovi.','Červená čiapočka verí medveďovi.','vlk Červenej čiapočky','babka Červenej čiapočky','gossip','guessing'),
(2539,'sk','V jej hlave žije umelá inteligencia.','V jej aute žije umelá inteligencia.','robot s umelou inteligenciou','aplikácia s umelou inteligenciou','nerd','none'),
(2540,'sk','Aký „útulný“ žalár.','Aká „útulná“ záhrada.','tmavý žalár so sviečkami','tmavá pivnica s vínom','ironic','none'),
(2541,'sk','Toto schodisko nikto neupratoval.','Túto kuchyňu nikto neupratoval.','rozpadajúce sa kamenné schodisko','rozpadajúci sa kamenný most','ironic','understatement'),
(2543,'sk','Slon má dlhé kly.','Slon má krátke kly.','dva dlhé biele kly','mrož s klami','chill','none'),
(2544,'sk','Hanuman má zlatú korunu.','Hanuman má striebornú korunu.','Hanuman so zlatým žezlom','Hanuman s mečom','nerd','none'),
(2545,'sk','Opica uctieva bohov.','Opica spí.','uctievanie na kamenných schodoch','uctievanie futbalovej hviezdy','chill','none'),
(2546,'sk','Táto sála je „celkom“ priestranná.','Táto sála je „celkom“ maličká.','priestranná sála','priestranné auto','ironic','understatement'),
(2547,'sk','Tieto muchotrávky sú obrovské!','Tieto muchotrávky sú maličké!','obrie červené muchotrávky','muchotrávky v košíku','slang','exclamation'),
(2548,'sk','Toľko sudov. Asi pivo?','Toľko bicyklov. Asi pivo?','naskladané drevené sudy','sud studeného piva','low_iq','guessing'),
(2549,'sk','Otec so synom jasajú!','Otec so synom plačú!','otec nesie syna','otec nesie nákup','dramatic','exclamation'),
(2550,'sk','Sedí so skríženými nohami, bosá.','Sedí so skríženými nohami, v čižmách.','sedieť so skríženými nohami','stáť so skríženými nohami','chill','none'),
(2551,'sk','Miami vibe: palmy a neón.','Miami vibe: sneh a neón.','neónová ulica v Miami','pláž v Miami na poludnie','slang','none'),
(2552,'sk','Je vo virtuálnej realite.','Je v bazéne.','headset na virtuálnu realitu','virtuálna realita v škole','chill','none'),
(2556,'sk','Fakt: mozog žiari.','Fakt: srdce žiari.','žiariaci mozog','mozog v pohári','nerd','none'),
(2557,'sk','Počkaj, plachetnica je zo skla?','Počkaj, plachetnica je z dreva?','sklenená plachetnica','plachetnica vo fľaši','low_iq','none'),
(2558,'sk','Letí. Čistá sloboda!','Pláva. Čistá sloboda!','sloboda nad morom','sloboda pod morom','dramatic','exclamation'),
(2559,'sk','Na tomto strome rastú mince!','Na tomto strome rastú jablká!','mince padajúce zo stromu','mince v prasiatku','dramatic','exclamation'),
(2560,'sk','Chôdza po vode? Zázrak!','Chôdza po ohni? Zázrak!','zázrak na oceáne','zázračný liek na nádchu','dramatic','exclamation'),
(2562,'sk','Daždivá noc, osamelý detektív.','Slnečný deň, osamelý detektív.','detektív v daždi','detektív na mieste činu','dramatic','cliche'),
(2563,'sk','Kupec kontroluje obilie.','Kupec kontroluje mince.','kupec pri sviečke','kupec na trhu','chill','none'),
(2564,'sk','Toto súkvetie hortenzie je modré.','Toto súkvetie hortenzie je ružové.','modré súkvetie hortenzie','hortenzia vo váze','nerd','none'),
(2567,'sk','Svätec má biely závoj.','Svätec má červený závoj.','svätec so svätožiarou','svätec na koni','chill','none'),
(2571,'sk','Chlapec je mrzutý. Zase.','Dievča je mrzuté. Zase.','mrzutý chlapček','mrzutý starček','ironic','guessing'),
(2572,'sk','Trojuholníky svietia.','Kruhy svietia.','svietiace neónové trojuholníky','trojuholníková dopravná značka','chill','none'),
(2575,'sk','Didžej je totálne anonymný.','Kuchár je totálne anonymný.','anonymný didžej v kapucni','anonymný list','slang','none'),
(2576,'sk','V Paríži je zlomený žiaľom.','V Ríme je zlomený žiaľom.','zlomený žiaľom v daždi','zlomený žiaľom v snehu','dramatic','none'),
(2578,'sk','Priezor je ako zrkadlo.','Priezor je ako okno.','zrkadlový priezor prilby','čiapka so šiltom','chill','none'),
(2579,'sk','Jej okuliare sú fakt čudné.','Jej klobúk je fakt čudný.','čudný retro stroj','čudné staré auto','slang','exaggeration'),
(2580,'sk','Lukostrelec napína luk.','Lukostrelec tasí meč.','socha lukostrelca','obraz lukostrelca','chill','none'),
(2581,'sk','Hrá na bambusovú flautu.','Hrá na bambusový bubon.','hra na bambusovej flaute','vyrezávanie bambusovej flauty','chill','none'),
(2583,'sk','Užíva si ten vibe.','Užíva si tú pizzu.','užívať si hudbu','užívať si slnko','slang','none'),
(2584,'sk','Je to krst v rieke.','Je to krst v kostole.','krst v rieke','krst v kostole','chill','none'),
(2586,'sk','Najlepšie priateľstvo ever: obrovský robot a malé dievčatko.','Najlepšie priateľstvo ever: obrovský pes a malé dievčatko.','nečakané priateľstvo','náramok priateľstva','dramatic','exaggeration'),
(2594,'sk','Robot sa učí o sebe.','Robot sa učí o mačkách.','robot sa učí čítať','robot sa učí lietať','low_iq','guessing'),
(2595,'sk','Niekto nechal koncertné krídlo vonku.','Niekto nechal koncertné krídlo vnútri.','koncertné krídlo vonku','koncertné krídlo vnútri','ironic','guessing'),
(2600,'sk','Brácho, dva chrobáky chillujú.','Brácho, dva slimáky chillujú.','chrobáky lezúce po listoch','chrobáky lietajúce nad kvetmi','slang','none'),
(2601,'sk','Muž si kľakol k modlitbe.','Muž si sadol k modlitbe.','kľaknúť si na kamennú zem','kľaknúť si na mäkkú pohovku','chill','none'),
(2602,'sk','Lyžujú dole kopcom strašne rýchlo.','Lyžujú hore kopcom strašne rýchlo.','lyžovanie dole strmým svahom','lyžovanie po rovnej ceste','slang','none'),
(2603,'sk','Noty sú písané rukou.','Noty sú vytlačené.','staré ručne písané noty','nové tlačené noty','nerd','none'),
(2605,'sk','Chová v náručí bábätko.','Chová v náručí jahňa.','chovať bábätko v náručí','chovať mobil v náručí','chill','none'),
(2606,'sk','Jej hlava je čistý hodinový strojček.','Jej hlava je čisté sklo.','hlava plná hodinových strojčekov','naťahovacia hračka myška','nerd','exaggeration'),
(2607,'sk','Mačky nosia elegantné kabáty.','Psy nosia elegantné kabáty.','mačky nosiace dlhé kabáty','mačky nosiace obojky','business','none'),
(2611,'sk','Jeho opasok má kovovú pracku.','Jeho taška má kovovú pracku.','kovová pracka opaska','zapínanie bezpečnostného pásu','chill','none'),
(2612,'sk','Dva púčiky sa ešte neotvorili.','Dva púčiky sa už otvorili.','dva zatvorené červené púčiky','dva otvorené červené púčiky','nerd','none'),
(2614,'sk','Dvaja chlapci sú pri minarete.','Dve dievčatá sú pri minarete.','kráčať k minaretu','liezť na minaret','chill','none'),
(2618,'sk','Rukopis je v písanom písme.','Rukopis je v tlačenom písme.','vyblednutý písaný rukopis','úhľadný tlačený rukopis','nerd','none'),
(2621,'sk','Na sťažni je veľa lán.','Na sťažni je veľa vlajok.','vysoký sťažeň s lanovím','sťažeň s pirátskymi vlajkami','nerd','none'),
(2622,'sk','Maličká Socha slobody!','Maličká Eiffelova veža!','mini Socha slobody','kostým Sochy slobody','dramatic','exclamation'),
(2623,'sk','Brečtan pokrýva knižnicu.','Sneh pokrýva knižnicu.','knižnica pokrytá brečtanom','hrad pokrytý brečtanom','chill','none'),
(2625,'sk','Inžinier sníva o žeriavoch.','Inžinier sníva o koňoch.','inžinierova prilba','inžinier za počítačom','nerd','guessing'),
(2626,'sk','V jeho plešatej hlave žije mesto.','V jeho plešatej hlave žije farma.','plešatá hlava z profilu','plešatá hlava s okuliarmi','chill','none'),
(2629,'sk','Vlasy má v dvoch vrkočoch.','Vlasy má v dvoch drdoloch.','dva dlhé zapletené vrkoče','dva krátke kučeravé chvostíky','chill','none'),
(2631,'sk','Jej okuliare majú okrúhle šošovky.','Jej okuliare nemajú žiadne šošovky.','okrúhle tónované šošovky','šošovka na fotoaparáte','chill','none'),
(2633,'sk','Ten strom je disko. Pozri na tie lúče!','Ten strom je disko. Pozri na tie vtáky!','lúče farebného svetla','drevené trámy strechy','low_iq','exaggeration'),
(2634,'sk','Každá fľaša má korkovú zátku.','Každá fľaša má slamku.','fľaše zavreté korkovými zátkami','korková nástenka s lístkami','chill','none'),
(2635,'sk','Magnólia je krémovo biela.','Magnólia je žiarivo žltá.','rozkvitnutý kvet magnólie','strom magnólie','chill','none'),
(2641,'sk','Lúče zapĺňajú oblohu!','Lúče zapĺňajú izbu!','zlaté lúče svetla','lúče cez okno','dramatic','exclamation'),
(2648,'sk','Tento mravec je väčší ako ja!','Táto včela je väčšia ako ja!','obrovský čierny mravec','obrovské mravenisko','low_iq','exaggeration'),
(2649,'sk','Tie ochranné okuliare sú obrovské!','Tie náušnice sú obrovské!','žiariace ochranné okuliare','okuliare na plávanie','dramatic','exclamation'),
(2651,'sk','Červená strecha má biele bodky.','Červená strecha má čierne bodky.','čiapka s bielymi bodkami','pes s bielymi bodkami','chill','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
