begin;
insert into public.tinder_sentences (media_id, language_code, true_sentence, false_sentence, true_phrase, false_phrase, tone, device) values
(5210,'sk','Jedna „strašná“ hus ich prinútila ustúpiť.','Jeden „strašný“ pes ich prinútil ustúpiť.','ustupujú pred husou','ustupujú pred dažďom','ironic','exaggeration'),
(5211,'sk','Aký šťastný návrat domov!','Aký smutný návrat domov!','šťastný návrat domov','návrat do školy','dramatic','exclamation'),
(5212,'sk','Veľké objatia na stanici!','Veľké objatia na letisku!','objímanie na stanici','rozhlasová stanica','dramatic','exclamation'),
(5213,'sk','Na železnici stojí červený vlak.','Na železnici stojí červená električka.','nástupište na železnici','železnica v horách','chill','none'),
(5214,'sk','Bicykel, kolobežka a potom púšť!','Bicykel, kolobežka a potom džungľa!','ťava na púšti','ťava v zoo','dramatic','exclamation'),
(5215,'sk','Na cyklistiku si vybrala fjord.','Na cyklistiku si vybrala mesto.','cyklistika popri fjorde','cyklistika v meste','chill','none'),
(5216,'sk','Ide na pomalú prechádzku.','Ide si pomaly zaplávať.','prechádzka popri stánkoch s kvetmi','prechádzka po pláži','chill','none'),
(5217,'sk','Má na sebe žltú vestu.','Má na sebe oranžovú vestu.','žltá reflexná vesta','vesta pod košeľou','chill','none'),
(5218,'sk','Kontroluje každú izbu.','Upratuje každú izbu.','izba s oblúkovými oknami','izba s krbom','chill','none'),
(5219,'sk','Spolubývajúci spravili cestoviny. Mňam.','Spolubývajúci spravili pizzu. Mňam.','dvaja spolubývajúci v byte','dvaja spolubývajúci sa sťahujú','low_iq','none'),
(5220,'sk','Niekto odstrihuje ružu.','Niekto polieva ružu.','odstrihnúť stonku ruže','odstrihnúť psovi pazúry','chill','none'),
(5221,'sk','Chodník sa vinie hore kopcami.','Rieka sa vinie hore kopcami.','chodník vinúci sa do hôr','rieka vinúca sa dolu kopcom','chill','none'),
(5222,'sk','Stúpa po kamenných schodoch.','Stúpa po drevených schodoch.','kamenné schody na horu','kamenné schody k pláži','chill','none'),
(5223,'sk','Jej trasa je vyznačená červenou.','Jej trasa je vyznačená modrou.','trasa na mape','trasa autobusu cez mesto','chill','none'),
(5224,'sk','Má kráľovskú kapelu.','Má kráľovského koňa.','kráľovský trón','kráľovská svadba','chill','none'),
(5226,'sk','Stihol naskočiť do vozňa!','Stihol naskočiť do taxíka!','skok do vlakového vozňa','koč ťahaný koňmi','dramatic','exclamation'),
(5227,'sk','Má niekoľko nových fanúšikov.','Má niekoľko nových mačiek.','niekoľko bežiacich psov','niekoľko idúcich áut','gossip','exaggeration'),
(5228,'sk','Poriadne sneží!','Poriadne prší!','sneží na námestí','sneží na pláži','dramatic','exclamation'),
(5229,'sk','Hodila hrsť snehu.','Hodila hrsť piesku.','hrsť prašanu','hrsť mincí','chill','none'),
(5230,'sk','V bábike je ďalšia bábika!','V bábike je minca!','maľovaná drevená bábika','domček pre bábiky','dramatic','exclamation'),
(5231,'sk','K jej pohostinnosti patrí čaj.','K jej pohostinnosti patrí pivo.','pohostinnosť s čajom a jedlom','práca v pohostinstve','business','none'),
(5232,'sk','Plaví sa na jachte.','Čistí jachtu.','klasická plachetná jachta','jachta v prístave','chill','none'),
(5233,'sk','Vojenská prehliadka je obrovská.','Vojenská prehliadka je maličká.','vojenská prehliadka','vojenská nemocnica','chill','none'),
(5234,'sk','Každý rad je dokonale rovný.','Každý rad je totálny chaos.','rady salutujúcich žien','rady bežiacich mužov','business','none'),
(5235,'sk','Pečiatkuje náklad.','Maľuje náklad.','náklad v kontajnerovom prístave','náklad na letisku','chill','none'),
(5236,'sk','Mesto je vo veľkej vzdialenosti.','Ťava je vo veľkej vzdialenosti.','veže vo veľkej vzdialenosti','hovor na veľkú vzdialenosť','chill','none'),
(5237,'sk','Čaj pod oblohou plnou hviezd.','Čaj pod oblohou plnou vtákov.','hviezdy nad púštnym táborom','hviezdy nad mestom','chill','none'),
(5238,'sk','Selfie na červenej dune? Ikonické.','Selfie na bielej dune? Ikonické.','selfie na červenej dune','jazda buginou po dunách','slang','none'),
(5239,'sk','Aké dokonalé vypustenie!','Aké dokonalé pristátie!','vypustenie sokola','vydanie albumu','dramatic','exclamation'),
(5240,'sk','Sokol má roztiahnuté krídla.','Sokol má zložené krídla.','roztiahnuté obe krídla','kuracie krídla na tanieri','chill','none'),
(5241,'sk','Žena vkĺzava do komory.','Muž vkĺzava do komory.','svietiaca lekárska komora','koncert komornej hudby','chill','none'),
(5242,'sk','Jej saténový župan vyzerá elegantne.','Jej vlnený župan vyzerá elegantne.','elegantný saténový župan','elegantná večerná párty','flirt','none'),
(5243,'sk','Naplánovala si celý mesiac.','Naplánovala si celý týždeň.','naplánovať celý mesiac','naplánovať stretnutie','business','none'),
(5244,'sk','Spolužiaci uzavreli dohodu.','Učitelia uzavreli dohodu.','stretnutie dvoch spolužiakov','oslava spolužiaka','chill','guessing'),
(5245,'sk','Chemikália svieti fialovo!','Chemikália svieti oranžovo!','svietiaca fialová chemikália','chemikália v nádrži','dramatic','exclamation'),
(5246,'sk','Drží ružovú banku.','Drží ružový telefón.','banka s modrou tekutinou','banka s horúcim čajom','nerd','none'),
(5247,'sk','Babka zúri kvôli stopám.','Babka zúri kvôli rozbitej váze.','blatisté stopy v chodbe','blatisté stopy v záhrade','gossip','blaming_someone'),
(5248,'sk','Platí nájomné za kolobežku.','Platí nájomné za bicykel.','nájomné za kolobežku','nájomné za byt','chill','none'),
(5249,'sk','Umýva panvicu, ktorá už zažila lepšie časy.','Umýva hrnček, ktorý už zažil lepšie časy.','umývanie začadeného hrnca','umývanie tváre','ironic','cliche'),
(5250,'sk','Má pracovný hovor.','Má videohovor.','hovor na stolovom telefóne','videohovor na notebooku','business','none'),
(5251,'sk','Píše na klávesnici a pritom telefonuje!','Píše na klávesnici a pritom obeduje!','písanie na klávesnici pri telefonovaní','písanie SMS správy','dramatic','exclamation'),
(5252,'sk','Tropické ovocie je v akcii.','Mrazené ovocie je v akcii.','kopa tropického ovocia','tropické akvárium','business','none'),
(5253,'sk','Títo starší ľudia tancujú lepšie ako ja.','Títo starší ľudia plávajú lepšie ako ja.','starší tanečníci v parku','starší plavci v bazéne','slang','exaggeration'),
(5254,'sk','Pozri, ako tí partneri tancujú!','Pozri, ako tí partneri plávajú!','tanec s partnerom','kartová hra s partnerom','flirt','exclamation'),
(5255,'sk','On vyzerá veľmi vinne a riadne šokovane.','Ona vyzerá veľmi vinne a riadne šokovane.','vinný mladý muž','vinný sudca','gossip','guessing'),
(5256,'sk','Prihovára sa im sudca.','Prihovára sa im zdravotná sestra.','prihovárať sa plnej sále','písať adresu na list','chill','none'),
(5257,'sk','Komorník nesie čaj.','Komorník nesie víno.','komorník nesúci čaj','komorník otvára dvere','chill','none'),
(5258,'sk','Bar na streche, párty so šejkrom!','Bar v suteréne, párty so šejkrom!','bar na streche pri západe slnka','tabuľka čokolády','slang','exclamation'),
(5259,'sk','Veľký pes si otriasa mokrú srsť. Sprchu dostanú všetci.','Veľká mačka si otriasa mokrú srsť. Sprchu dostanú všetci.','otriasanie mokrej srsti','česanie mokrej srsti','ironic','exaggeration'),
(5260,'sk','Nachytať sa pri torte. Tá hanba!','Nachytať sa pri pizzi. Tá hanba!','hanba kvôli torte','hanba kvôli rozbitému tanieru','dramatic','exclamation'),
(5261,'sk','Aj bežec dostal svoj podiel!','Aj cyklista dostal svoj podiel!','podiel z pizze','podiel vo firme','gossip','exclamation'),
(5262,'sk','Taká „stabilná“ polica!','Taký „stabilný“ stôl!','nie veľmi stabilná polica','stabilná drevená stolička','ironic','exclamation'),
(5263,'sk','Na polici je fotografia.','Na polici je zrkadlo.','zarámovaná rodinná fotografia','robiť rodinnú fotografiu','chill','none'),
(5264,'sk','Presúva gauč.','Presúva chladničku.','presúvanie nábytku','preraďovanie rýchlostí v aute','chill','none'),
(5265,'sk','Loď vezie kontajnery.','Loď vezie autá.','loď s kontajnermi','kamión s kontajnermi','chill','none'),
(5266,'sk','Pustila telefón!','Pustila šálku!','spadnutý telefón','telefónna búdka','dramatic','exclamation'),
(5267,'sk','Jej zbraň leží na stojane.','Jej zbraň leží na stoličke.','zbraň na stojane','zbraň v puzdre','business','none'),
(5268,'sk','Mieri puškou.','Čistí pušku.','streľba z pušky v ľahu','puška na chrbte pri lyžovaní','chill','none'),
(5269,'sk','Kúpila si kabát.','Kúpila si šaty.','kúpiť olivový kabát','kúpiť nové auto','business','none'),
(5270,'sk','Kupuje všetky cereálie v supermarkete!','Kupuje všetky polievky v supermarkete!','nákupný vozík v supermarkete','parkovisko supermarketu','gossip','exaggeration'),
(5271,'sk','Ich výkrik napĺňa kaňon!','Ich pieseň napĺňa kaňon!','výkrik nad kaňonom','výkrik o pomoc','dramatic','exclamation'),
(5272,'sk','Turisti úplne šalejú.','Turisti idú domov.','turisti jasajú pri kaňone','turisti oddychujú v stane','slang','none'),
(5273,'sk','Modelka to v zelených nohaviciach úplne dáva.','Modelka to v oranžových nohaviciach úplne dáva.','modelka na móle','model lietadla','slang','none'),
(5274,'sk','Sprcha zapnutá. Teraz je premočený.','Sprcha vypnutá. Teraz je premočený.','premočený v sprche','premočený v daždi','low_iq','none'),
(5275,'sk','Dve sebecké deti, jeden ovládač.','Dve sebecké deti, jeden mobil.','sebecké deti sa hádajú','sebecký vodič parkuje','gossip','none'),
(5276,'sk','Jeden keksík, dvaja súrodenci: vojna.','Jedna torta, dvaja súrodenci: vojna.','súrodenci stavajú bunker','súrodenci robia úlohy','dramatic','exaggeration'),
(5277,'sk','Súhlasili: pol na pol.','Súhlasili: všetko jemu.','súhlasiť s delením keksíka','súhlasiť so spoločnou izbou','chill','none'),
(5278,'sk','Roh dosiahnutý. Ideme ďalej.','Rieka dosiahnutá. Ideme ďalej.','roh dvoch ulíc','roh izby','business','none'),
(5279,'sk','Podpisuje obrovský zvitok obrovským perom!','Podpisuje obrovský zvitok maličkým perom!','podpisovanie obrovského zvitku','čítanie starého zvitku','dramatic','exclamation'),
(5280,'sk','Číta rázcestník.','Natiera rázcestník.','čítanie dreveného rázcestníka','natieranie dreveného rázcestníka','chill','none'),
(5281,'sk','Hviezda spieva na pódiu.','Hviezda tancuje na pódiu.','hviezda na pódiu','hviezda na oblohe','chill','none'),
(5282,'sk','Všetci spievajú pieseň.','Všetci píšu pieseň.','spievanie piesne','pieseň v rádiu','gossip','none'),
(5283,'sk','Je to len malá veža z tanierov.','Je to len malá veža zo šálok.','veža z tanierov','veža z pohárov','chill','understatement'),
(5284,'sk','Páči sa mi tvoje kovové brnenie, rytier.','Páči sa mi tvoja kovová koruna, rytier.','celé kovové brnenie','metalová kapela','flirt','none'),
(5285,'sk','Čisté šťastie v záhrade.','Čisté šťastie v kuchyni.','šťastie v slnečnej záhrade','šťastie na slnečnej pláži','chill','none'),
(5286,'sk','Obaja chcú tú mikinu!','Obaja chcú toho plyšového macka!','ťahanie svetlofialovej mikiny','pranie svetlofialovej mikiny','dramatic','exclamation'),
(5287,'sk','Pätnásť dievčat, nula ticha!','Pätnásť chlapcov, nula ticha!','izba bez ticha','minúta ticha','dramatic','exaggeration'),
(5288,'sk','Letí dolu na lyžiach!','Letí dolu na saniach!','carving na lyžiach','lyže opreté o stenu','dramatic','exaggeration'),
(5289,'sk','Pokožke chýba vlhkosť.','Pokožke chýbajú póry.','pokožka bez vlhkosti','vlhkosť na okne','nerd','none'),
(5290,'sk','Aký vysoký mrakodrap!','Aký vysoký maják!','mrakodrap so špicou','mrakodrap vo výstavbe','dramatic','exclamation'),
(5291,'sk','Každý podnikateľ spí.','Každý podnikateľ číta.','podnikatelia spiaci v lietadle','podnikatelia spiaci vo vlaku','chill','none'),
(5292,'sk','Nikto tu nie je veľmi produktívny.','Všetci sú tu veľmi produktívni.','nie veľmi produktívny deň','produktívna tímová porada','ironic','understatement'),
(5293,'sk','Loptička je už v jeho rukavici.','Loptička je už v jeho čiapke.','kožená baseballová rukavica','zimná rukavica','chill','none'),
(5295,'sk','Trúbi na obrovský roh.','Trúbi na maličký roh.','trúbenie na dlhý roh','roh barana','chill','none'),
(5296,'sk','Pripravuje tradičné jedlo!','Kupuje tradičné jedlo!','varenie tradičného jedla','tradičný tanec','dramatic','exclamation'),
(5297,'sk','Starý hrad je v úplnom rozpade.','Starý most je v úplnom rozpade.','hrad v rozpade','hrad v snehu','chill','none'),
(5298,'sk','Jej sako je béžové.','Jej sako je čierne.','béžové strihané sako','skúšanie saka','chill','none'),
(5299,'sk','Jej klobásy sú tu nelegálne!','Jej knihy sú tu nelegálne!','nelegálne jedlo v kufri','nelegálne parkovanie na letisku','gossip','exclamation'),
(5300,'sk','Vretenica je skutočná hrozba.','Jašterica je skutočná hrozba.','hrozba na skalách','hrozba v liste','dramatic','none'),
(5301,'sk','Jej alergia neznáša túto lúku.','Jej alergia neznáša túto pláž.','alergia na peľ','alergia na psy','low_iq','exaggeration'),
(5302,'sk','Kvety ho rozkýchali!','Kvety ho rozplakali!','kýchanie pod kvetmi','maľovanie čerešňových kvetov','dramatic','blaming_someone'),
(5303,'sk','Snehové vločky na jej palčiaku.','Snehové vločky na jej topánke.','snehová vločka na palčiaku','snehová vločka na okne','chill','none'),
(5304,'sk','Fuj! Špina po celých rukách!','Fuj! Farba po celých rukách!','špina na jej rukách','špina na jej topánkach','dramatic','exclamation'),
(5305,'sk','Ich spoločnosť tvrdo pracuje.','Ich spoločnosť je na dovolenke.','celá spoločnosť pri práci','spoločnosť na párty','business','none'),
(5306,'sk','Pohodlný gauč pre všetkých naraz!','Pohodlná posteľ pre všetkých naraz!','pohodlný gauč plný ľudí','pohodlná veľká posteľ','dramatic','exclamation'),
(5307,'sk','Izba je veľmi priestranná.','Izba je veľmi malá.','priestranná obývačka','priestranný kufor auta','business','none'),
(5308,'sk','Muž jej nesie slnečnice.','Muž jej nesie ruže.','kytica slnečníc','pole slnečníc','chill','none'),
(5309,'sk','Niekto jej nechal milý odkaz.','Niekto jej nechal smutný odkaz.','odkaz so smajlíkom','odkaz na chladničke','gossip','none'),
(5310,'sk','Syn pomáha opravovať auto.','Syn pomáha umývať auto.','syn drží francúzsky kľúč','syn umýva auto','chill','none'),
(5311,'sk','Teraz je celá skupina pokojná.','Teraz je celá skupina nahnevaná.','pokojní pod dekami','pokojný pod tlakom','chill','none'),
(5312,'sk','Grilovačka na dvore za domom? Ideme!','Párty pri bazéne na dvore za domom? Ideme!','grilovačka na dvore za domom','bazén na dvore za domom','slang','exclamation'),
(5313,'sk','Neónové nápisy pokrývajú každú stenu.','Papierové nápisy pokrývajú každú stenu.','svietiace neónové nápisy','neónové svetlá v klube','chill','none'),
(5314,'sk','V jej košíku je celý Paríž!','V jej taške je celý Paríž!','košík suvenírov','košík ovocia','slang','exaggeration'),
(5315,'sk','Má kopu pohľadníc. Pre koho?','Má kopu známok. Pre koho?','pohľadnice Paríža','písanie pohľadnice','gossip','guessing'),
(5316,'sk','Zbožňujem jej nadýchané kučeravé vlasy.','Zbožňujem jej nadýchané rovné vlasy.','husté kučeravé tmavé vlasy','dlhé kučeravé blond vlasy','flirt','none'),
(5317,'sk','Jej volány lietajú!','Jej topánky lietajú!','vrstvy červených volánov','volány na golieri košele','dramatic','exclamation'),
(5318,'sk','Hovorí pred publikom.','Spieva pred publikom.','hovoriť do mikrofónu','hovoriť do telefónu','business','none'),
(5319,'sk','Pavúk je pod svojou pavučinou.','Pavúk je nad svojou pavučinou.','pavučina medzi konármi','pavučina v rohu','chill','none'),
(5320,'sk','Predvádza model chrbtice.','Predvádza model srdca.','predvádzanie na modeli chrbtice','demonštrácia na ulici','business','none'),
(5321,'sk','Korčuľuje sa ako profík.','Lyžuje sa ako profík.','korčuľovanie na jednej nohe','korčuľovanie na ceste','slang','cliche'),
(5322,'sk','Hnusná polievka! Vypľul ju.','Hnusný čaj! Vypľul ho.','vypľúvanie zelenej polievky','vypľúvanie čerešňovej kôstky','low_iq','none'),
(5323,'sk','Ten kameň spravil poriadne čľup.','Tá loďka spravila poriadne čľup.','hádzanie veľkého kameňa','hádzanie žabiek plochým kameňom','slang','exaggeration'),
(5324,'sk','Špongia porazila omáčku!','Špongia porazila syr!','špongia plná peny','piškótový koláč','dramatic','exclamation'),
(5325,'sk','Manželia podpísali dokument.','Manželia spálili dokument.','manželia podpisujú papiere','manželia sa hádajú doma','business','none'),
(5326,'sk','Tréner jej tejpuje členok.','Tréner jej tejpuje zápästie.','tréner pomáha gymnastke','tréner kričí na hráčov','chill','none'),
(5327,'sk','Zákazník má na sebe čierny plášť.','Zákazník má na sebe biely plášť.','čierny kadernícky plášť','plášť superhrdinu','chill','none'),
(5328,'sk','Ovoniava broskyňovú blúzku.','Ovoniava bielu blúzku.','broskyňová blúzka s volánmi','žehlenie broskyňovej blúzky','chill','none'),
(5329,'sk','Semienko má maličký korienok!','Semienko má maličký kvietok!','semienko s korienkom','semienko v zobáku','dramatic','exclamation'),
(5330,'sk','„Tajný“ špión má v novinách dieru.','„Tajný“ špión má v klobúku dieru.','špión za novinami','špión za dverami','ironic','none'),
(5331,'sk','Jej kondícia? Drví melóny!','Jej kondícia? Drví kokosy!','kondícia pri plážovom bare','fitness aplikácia','slang','exaggeration'),
(5332,'sk','Personál prejavuje silnú jednotu.','Hostia prejavujú silnú jednotu.','jednota tímu','jednota krajiny','business','none'),
(5333,'sk','Každé schodisko je honosnejšie!','Každé schodisko je špinavšie!','veľkolepé mramorové schodisko','schodisko v majáku','dramatic','exclamation'),
(5334,'sk','Fanúšikovia rešpektujú túto chvíľu.','Fanúšikovia ignorujú túto chvíľu.','rešpektovať tú chvíľu','rešpektovať rýchlostný limit','chill','none'),
(5335,'sk','Je nadšená fanúšička.','Je nadšená hráčka.','nadšená futbalová fanúšička','nadšená tenisová fanúšička','chill','none'),
(5336,'sk','Jeho čiapka ukazuje jeho vernosť.','Jeho šál ukazuje jeho vernosť.','vernosť klubu','vernosť kráľovi','dramatic','none'),
(5337,'sk','S croissantom v ústach cestuje železnicou.','S pizzou v ústach cestuje železnicou.','cestovanie železnicou','cestovanie lietadlom','gossip','none'),
(5338,'sk','Zostať môžeš za 10 eur alebo za 10 000 eur.','Zostať môžeš za 10 eur alebo za 1 000 eur.','zostať v hosteli','zostať doma','business','cheap_quality'),
(5339,'sk','Ovláda autobus.','Ovláda električku.','ovládanie mestského autobusu','ovládanie drona','chill','none'),
(5340,'sk','Krabica ide do garáže.','Krabica ide do auta.','otvorená garáž','garáž plná áut','business','none'),
(5341,'sk','Chlapec pribíja dosku.','Chlapec natiera dosku.','pribíjanie dosky','pribíjanie plagátu','chill','none'),
(5342,'sk','Poleva na jej jazyku. Mňam!','Kečup na jej jazyku. Mňam!','poleva na jej jazyku','popálený jazyk od čaju','slang','exclamation'),
(5343,'sk','Dievčatá majú rovnaké postele.','Dievčatá majú poschodovú posteľ.','dve rovnaké postele','hotelová izba s dvoma posteľami','chill','none'),
(5344,'sk','Ušili veľkú prešívanú deku!','Ušili veľkú vlajku!','hotová prešívaná deka','prešívaná deka na posteli','dramatic','exclamation'),
(5345,'sk','Opiera sa o zábradlie.','Opiera sa o strom.','opierať sa o zábradlie mosta','opierať sa o záhradný plot','chill','none'),
(5346,'sk','Poklepkáva sa po žalúdku.','Poklepkáva sa po hlave.','plný žalúdok','žalúdok plný polievky','chill','none'),
(5347,'sk','Premávka smeruje k zastaveniu.','Vlaky smerujú k zastaveniu.','zastavenie premávky','zastavenie na kávu','chill','none'),
(5348,'sk','Ďakuje mužovi s dáždnikom.','Ďakuje mužovi so psom.','poďakovať milému cudzincovi','poďakovať šoférovi autobusu','chill','none'),
(5349,'sk','Udeľuje už ďalšiu medailu!','Udeľuje už ďalšiu trofej!','udelenie medaily','udelenie ceny za pieseň','dramatic','exaggeration'),
(5350,'sk','Vo vzduchu nad potokom. Odvaha!','Vo vzduchu nad jazerom. Odvaha!','skok cez potok','plávanie v potoku','dramatic','exclamation'),
(5351,'sk','Oranžové pouličné lampy, taká pohoda.','Modré pouličné lampy, taká pohoda.','rad pouličných lámp','pokazená pouličná lampa','slang','none'),
(5352,'sk','Jej frustrácia je na 1000 %.','Jej frustrácia je na 0 %.','frustrácia pri notebooku','frustrácia z učiteľa','nerd','exaggeration'),
(5353,'sk','Administratíva vyhráva.','Administratívy ubúda.','stohy administratívy','administratíva na notebooku','dramatic','exaggeration'),
(5354,'sk','Trieda ju dobre sleduje.','Trieda ho dobre sleduje.','trieda v parku','trieda v škole','business','none'),
(5355,'sk','Aj mačka napodobňuje trénera!','Aj pes napodobňuje trénera!','tréner v parku','cvičiteľ psov s maškrtami','gossip','exclamation'),
(5356,'sk','Joga na streche pri západe slnka? Sen.','Joga na pláži pri západe slnka? Sen.','joga na streche','hodina jogy v telocvični','slang','exaggeration'),
(5357,'sk','Pes má honosnejší kočík než väčšina bábätiek.','Mačka má honosnejší kočík než väčšina bábätiek.','honosný chrómový kočík','honosná kostýmová párty','dramatic','exaggeration'),
(5358,'sk','Kuká pomedzi knihy.','Kuká pomedzi žalúzie.','kukanie cez škáru','kuknúť do knihy','gossip','none'),
(5359,'sk','Hroch sa pred ňou skrýva.','Kačka sa pred ňou skrýva.','hroch v rieke','hroch na móle','chill','guessing'),
(5360,'sk','Metro je „trochu“ plné.','Metro je „trochu“ prázdne.','preplnená stanica metra','prázdna stanica metra','ironic','understatement'),
(5361,'sk','Tlačiť šesť tašiek je „ľahké“.','Tlačiť šesť krabíc je „ľahké“.','nie ľahký výlet','nie ľahká skúška','ironic','understatement'),
(5362,'sk','Najbláznivejšie okuliare na ostrove!','Najbláznivejší klobúk na ostrove!','bláznivé okuliare v tvare srdca','bláznivé balóny v tvare srdca','dramatic','exaggeration'),
(5363,'sk','Pomáhajú bežcovi.','Pomáhajú cyklistovi.','pomáhať vyčerpanému bežcovi','pomáhať stratenému turistovi','chill','none'),
(5364,'sk','Asistujú jej dvaja hrdinovia!','Asistujú jej dve sestričky!','asistovať unavenej bežkyni','asistovať unavenému vodičovi','dramatic','exaggeration'),
(5365,'sk','Spúšťa zbraň.','Čistí zbraň.','spúšťanie paintballovej zbrane','nabíjanie paintballovej zbrane','chill','none'),
(5366,'sk','Vzdáva sa!','Útočí!','vzdáva sa so zdvihnutými rukami','odovzdanie pasu','dramatic','exclamation'),
(5368,'sk','Trpia v horúčave.','Trpia v zime.','trpieť v horúčave','trpieť nádchou','dramatic','none'),
(5369,'sk','Tvrdý boxer, zmáčaný potom.','Tvrdý boxer, zmáčaný dažďom.','tvrdý mladý boxer','tvrdý kus mäsa','chill','none'),
(5370,'sk','Pádluje na žltom kanoe.','Pádluje na červenom kanoe.','pádlovanie na žltom kanoe','nesenie kanoe domov','chill','none'),
(5371,'sk','V kvetinových girlandách vyzerajú super.','V papierových korunách vyzerajú super.','v kvetinových girlandách','vešanie girlandy v interiéri','slang','none'),
(5372,'sk','Jeho metla zhŕňa lístie.','Jeho metla zhŕňa sneh.','metla a suché lístie','metla v kuchyni','chill','none'),
(5373,'sk','Všetko sa zväčšuje!','Všetko sa zmenšuje!','nafukovací hrad sa zväčšuje','firma sa rozširuje do zahraničia','dramatic','exclamation'),
(5374,'sk','Voda je trochu plytká.','Voda je trochu hlboká.','plávanie v plytkej vode','plytká miska na polievku','ironic','understatement'),
(5375,'sk','Švihá ako profík.','Pláva ako profík.','švihnutie golfovou palicou','švihnutie baseballovou pálkou','flirt','cliche'),
(5376,'sk','Stlačil vypínač. Svetlo!','Kopol do vypínača. Svetlo!','stláčanie vypínača','výhybka na železnici','dramatic','exclamation'),
(5377,'sk','Pozbierala taniere.','Pozbierala jablká.','pozbierané špinavé taniere','zbieranie červených jabĺk','business','none'),
(5378,'sk','Prestiera stôl.','Nastavuje budík.','prestrieť stôl','nastaviť budík','business','none'),
(5379,'sk','Krajčír upravil sako.','Krajčír upravil košeľu.','upraviť tmavomodré sako','upraviť plány cesty','chill','none'),
(5380,'sk','Vzal si aj tú krabicu!','Vzala si aj tú krabicu!','brať veci z krabice','vziať krabicu do školy','gossip','exclamation'),
(5381,'sk','Káva a poriadny rozhovor.','Pivo a poriadny rozhovor.','rozhovor pri káve','rozhovor cez e-mail','chill','none'),
(5382,'sk','Všetci pri stole o tom diskutujú naraz!','Všetci v autobuse o tom diskutujú naraz!','diskutovať pri stole v kaviarni','diskutovať o tom po telefóne','dramatic','exaggeration'),
(5383,'sk','Toľko taxíkov na bulvári!','Toľko autobusov na bulvári!','široký bulvár plný taxíkov','aleja starých stromov','slang','exclamation'),
(5384,'sk','Šampióni úplne šalejú.','Šampióni idú domov.','šampióni v pruhovaných dresoch','šampión na stupni víťazov','slang','none'),
(5385,'sk','Výmena sa končí víťazstvom.','Výmena sa končí prehrou.','víťazstvo v plážovom volejbale','víťazstvo v kartách','chill','none'),
(5386,'sk','Trhá zmluvu.','Trhá záclony.','trhanie zmluvy napoly','trhanie strán z knihy','business','none'),
(5387,'sk','Delia sa o svoj žiaľ.','Delia sa o svoju pizzu.','žiaľ na gauči','žiaľ na pohrebe','dramatic','none'),
(5388,'sk','Vyhrala balíček čipsov!','Vyhrala balíček cukríkov!','chytanie balíčka čipsov','balíček semienok','slang','banter'),
(5389,'sk','On jej uhýba ako Messi.','Ona mu uhýba ako Messi.','uhýbanie pred jej rukami','uhýbanie pred futbalovou loptou','slang','exaggeration'),
(5390,'sk','Mladík jazdí na skejte, tak cool.','Mladík jazdí na bicykli, tak cool.','mladík na skejtborde','mladík na bicykli','slang','none'),
(5391,'sk','Pekný západ slnka, a oni civia do mobilu.','Pekný západ slnka, a oni civia do knihy.','civenie do mobilu','civenie na západ slnka','ironic','none'),
(5392,'sk','Kričia od hrôzy!','Kričia v aute!','krik od hrôzy','krik od radosti','dramatic','exclamation'),
(5393,'sk','T-rex jej vzal pokoj.','Pes jej vzal pokoj.','stráca pokoj','zachováva pokoj','gossip','blaming_someone'),
(5394,'sk','Niekto si to nárokoval ako prvý!','Nikto si to nenárokoval ako prvý!','nárokovať si zamrznutú zem','nárokovať si stratenú tašku','gossip','exclamation'),
(5395,'sk','Pomocník z ranča jazdí popri plote.','Pomocník z ranča jazdí popri rieke.','jazdiaci pomocník z ranča','ranč plný dobytka','chill','none'),
(5396,'sk','Oranžové vlajky označujú čiaru.','Modré vlajky označujú čiaru.','označovanie čiary vlajkami','opravovanie písomky','business','none'),
(5397,'sk','Jedna mohutná vlna, štyri pokojné čajky.','Jedna mohutná vlna, štyri pokojné kačice.','lámajúca sa mohutná vlna','mohutný kráľ','ironic','understatement'),
(5398,'sk','Ľudia tvoria ľudskú reťaz.','Ľudia tvoria ľudskú vežu.','ľudská reťaz okolo Zeme','zlatá reťaz na krk','chill','none'),
(5399,'sk','Dvaja herci hrajú v divadelnej hre.','Dva psy hrajú v divadelnej hre.','divadelná hra v divadle','divadelná hra v škole','chill','none'),
(5400,'sk','Je v opere a má štýl.','Je v kine a má štýl.','večer v opere','operná speváčka','flirt','none'),
(5401,'sk','Všetci rozmýšľajú.','Všetci spia.','rozmýšľanie nad problémom','rozmýšľanie o počasí','chill','none'),
(5402,'sk','Kontroluje mu hrdlo.','Kontroluje mu uši.','prehliadka hrdla','šál okolo hrdla','chill','none'),
(5403,'sk','Kontroluje čas.','Kontroluje mapu.','kontrola času','strácanie času','chill','none'),
(5404,'sk','Je taký chamtivý na toasty!','Je taký chamtivý na tortu!','chamtivý jedák toastov','chamtivý jedák torty','dramatic','exclamation'),
(5405,'sk','Batoľa chodí!','Batoľa lezie!','prvé kroky batoľaťa','prvé slová batoľaťa','dramatic','exclamation'),
(5406,'sk','Jej prsty na nohách sú vedľa mušle.','Jej prsty na nohách sú vedľa kraba.','prsty na nohách roztiahnuté v piesku','prsty na nohách v žabkách','chill','none'),
(5407,'sk','Všetci teraz potrebujú na záchod.','Všetci teraz potrebujú k východu.','rad na záchod','čistenie záchoda','gossip','exaggeration'),
(5408,'sk','Súprava vyriešila problém so stoličkou.','Súprava vyriešila problém so stolom.','červená súprava náradia','súprava prvej pomoci','business','none'),
(5409,'sk','Ukazuje zuby.','Ukazuje jazyk.','predné zuby zblízka','chýbajúci predný zub','chill','none'),
(5410,'sk','Má zelenú zubnú kefku.','Má modrú zubnú kefku.','zelená zubná kefka','elektrická zubná kefka','chill','none'),
(5411,'sk','On dostal šmuhu, ona víry.','On dostal víry, ona šmuhu.','vír zubnej pasty','vír šľahačky','gossip','banter'),
(5412,'sk','Grécke stĺpy, drážkovaný mramor.','Grécke stĺpy, ružový mramor.','obrovské drážkované mramorové stĺpy','stĺp v parkovacom dome','nerd','none'),
(5413,'sk','Všade autá. Beznádejné!','Všade bicykle. Beznádejné!','beznádejná zápcha','beznádejný futbalový tím','low_iq','exclamation'),
(5414,'sk','Drží sa kovového zábradlia.','Drží sa kovovej brány.','zábradlie lávky','vlak na koľajniciach','chill','none'),
(5415,'sk','Čaká na červenú.','Čaká na autobusovej zastávke.','červené svetlo na semafore','červená značka stop','chill','none'),
(5416,'sk','Tú lokomotívu zbožňuje.','Ten vrtuľník zbožňuje.','oranžová elektrická lokomotíva','oranžová parná lokomotíva','gossip','guessing'),
(5417,'sk','Električka skončí v depe.','Električka skončí v múzeu.','električky v depe','autobusy v depe','chill','none'),
(5418,'sk','Interiér je celý z dreva.','Interiér je celý z plastu.','drevený interiér električky','moderný interiér auta','chill','none'),
(5419,'sk','Stihne každý presun.','Zmešká každý presun.','presun na trajekt','bankový prevod','chill','none'),
(5420,'sk','Nastupuje na biele plavidlo.','Nastupuje na červené plavidlo.','malé osobné plavidlo','obrovské nákladné plavidlo','chill','none'),
(5421,'sk','Odpadky sú všade!','Kvety sú všade!','kôš plný odpadkov','kôš plný kvetov','dramatic','exaggeration'),
(5423,'sk','Jeho ruksak je celosvetový cestovateľ.','Jeho ruksak zostáva v jednom meste.','celosvetové cestovanie','celosvetová mobilná sieť','chill','none'),
(5424,'sk','Podpísali zmluvu.','Roztrhali zmluvu.','podanie rúk nad zmluvou','trhanie zmluvy','business','none'),
(5425,'sk','Obchod je dohodnutý.','Obchod je zrušený.','podpis veľkého obchodu','obchod na trhu','business','none'),
(5426,'sk','Obe delegácie majú dohodu.','Žiadna delegácia nemá dohodu.','stretnutie dvoch delegácií','delegácia na letisku','business','none'),
(5427,'sk','Obálka má červenú pečať.','Obálka má modrú pečať.','červená vosková pečať','tuleň na pláži','chill','none'),
(5428,'sk','Kamión vezie náklad.','Vlak vezie náklad.','náklad na veľkom kamióne','náklad na lodi','chill','none'),
(5429,'sk','Dôveruje im so zavretými očami.','Dôveruje im s otvorenými očami.','dôverovať tímu, že ju chytí','dôverovať cudzincovi na nete','chill','none'),
(5430,'sk','Na cestnom bicykli je rýchla.','Na skejtborde je rýchla.','rýchla jazda tunelmi','rýchla jazda mestom','chill','none'),
(5431,'sk','Letí v balóne.','Letí v lietadle.','balón nad skalami','balónik na párty','chill','none'),
(5432,'sk','Napaľuje toho chudáka!','Napaľuje toho chudáka psíka!','napáliť zákazníka','napáliť učiteľa','dramatic','exclamation'),
(5433,'sk','Zapína svetlá.','Vypína svetlá.','zapnúť svetelnú reťaz','zapnúť telku','chill','none'),
(5434,'sk','Plytvá elektrinou!','Plytvá papierom!','veľká spotreba elektriny','elektrina zo solárnych panelov','dramatic','exaggeration'),
(5435,'sk','OMG, ich outfity sú úplne podobné.','OMG, ich outfity sú úplne odlišné.','úplne podobné outfity','podobní v školských uniformách','gossip','none'),
(5436,'sk','Tím krúti cesto.','Tím krája cesto.','krútenie šnúry cesta','krútenie šnúry vlny','business','none'),
(5437,'sk','Párty na nádvorí!','Párty v kuchyni!','párty na nádvorí so svetielkami','školské nádvorie cez prestávku','slang','exclamation'),
(5438,'sk','Miska červenej plnky.','Miska zelenej plnky.','červená ovocná plnka','plomba u zubára','chill','none'),
(5439,'sk','Štyria muži, jeden sivý dáždnik!','Štyria muži, jeden červený dáždnik!','sivé daždivé mesto','sivý zimný kabát','dramatic','exclamation'),
(5440,'sk','Deň šarkanov so synovcom.','Deň šarkanov so psom.','púšťanie šarkanov so synovcom','rybačka so synovcom','chill','none'),
(5441,'sk','Strýko ju nechal vyhrať.','Strýko ho nechal vyhrať.','pretláčanie rukou so strýkom','boxovanie so strýkom','gossip','guessing'),
(5442,'sk','Bojuje s každým rukávom!','Bojuje s každým zipsom!','vyťahovanie rúk z rukávov','vyhŕňanie rukávov','dramatic','exaggeration'),
(5443,'sk','Solidarita napĺňa ulicu.','Solidarita napĺňa štadión.','reťaz solidarity','reťazec obchodov','dramatic','none'),
(5444,'sk','Spolupracujú na mape.','Spolupracujú na aute.','spolupracovať na puzzle','spolupracovať s políciou','chill','none'),
(5445,'sk','Jeho dáždnik je teraz nepoužiteľný.','Jeho aktovka je teraz nepoužiteľná.','nepoužiteľný dáždnik','nepoužiteľný dáždnik na slnku','dramatic','none'),
(5446,'sk','Kopce sú hmlisté.','Kopce sú slnečné.','hmlisté kopce nad jazerom','zahmlené oči na svadbe','chill','none'),
(5447,'sk','Táto cesta je veľmi odľahlá.','Táto cesta je veľmi rušná.','odľahlá púštna cesta','diaľkové ovládanie','chill','none'),
(5448,'sk','Bilbordy na každej stene!','Obrazy na každej stene!','obrovské svietiace bilbordy','bilbord na poli','dramatic','exaggeration'),
(5449,'sk','Konečne stojí v dvernom otvore.','Konečne stojí v záhrade.','otvorený kamenný dverný otvor','dverný otvor so závesom','chill','none'),
(5450,'sk','Šetrí peniaze: odpája zariadenia.','Šetrí peniaze: zapája zariadenia.','odpájanie každého zariadenia','nabíjanie každého zariadenia','business','none'),
(5451,'sk','Jedna injekcia a je z neho Hulk!','Jedna tabletka a je z neho Hulk!','injekcia do ruky','injekcia do nohy','slang','exaggeration'),
(5452,'sk','Pokojné jazero v hmle.','Pokojná pláž v hmle.','pokojné horské jazero','pokojná horská dedinka','chill','none'),
(5453,'sk','Plní modrú vázu.','Plní červenú vázu.','dávanie kvetov do vázy','rozbitie vázy na kvety','chill','none'),
(5454,'sk','Atrament strieka po celom pase.','Voda strieka po celom pase.','kvapky čierneho atramentu','modrý atrament na prstoch','slang','exaggeration'),
(5455,'sk','Dostal schválenie!','Nedostal schválenie!','schválenie pasu','súhlas od rodičov','dramatic','exclamation'),
(5456,'sk','Dostal povolenie.','Nedostal povolenie.','povolenie cestovať','povolenie parkovať','chill','none'),
(5457,'sk','Návštevníci priniesli tortu.','Návštevníci priniesli psa.','návštevníci s tortou','návštevníci v múzeu','chill','none'),
(5458,'sk','Vitamín šumí ako šialený!','Mlieko šumí ako šialené!','šumivý vitamín v tablete','topiaci sa gumený vitamín','slang','exclamation'),
(5459,'sk','Láva na každom svahu.','Sneh na každom svahu.','žiariace prúdy lávy','láva v lampe','dramatic','none'),
(5460,'sk','Točiace sa šálky spôsobujú nevoľnosť!','Ruské koleso spôsobuje nevoľnosť!','nevoľnosť po jazde','nevoľnosť na lodi','dramatic','exclamation'),
(5461,'sk','Každý vhadzuje hlasovací lístok.','Každý vhadzuje list.','vhadzovanie zloženého hlasovacieho lístka','čítanie dlhého hlasovacieho lístka','chill','none'),
(5462,'sk','Demokracia v jednej plastovej krabici.','Demokracia v jednej drevenej krabici.','demokracia v akcii','demokracia v televízii','ironic','understatement'),
(5463,'sk','Píše si denník na mori. Pohoda.','Píše si denník v posteli. Pohoda.','písanie cestovného denníka','čítanie vedeckého časopisu','slang','none'),
(5464,'sk','Je štíhla.','Je štíhly.','štíhla žena v rifliach','štíhla žena v šortkách','chill','none'),
(5465,'sk','Pás zmeraný. Opasok sedí.','Ruka zmeraná. Opasok sedí.','meranie jej pásu','zástera okolo jej pásu','business','none'),
(5466,'sk','Čašník pôsobí veľmi formálne.','Čašník pôsobí veľmi neformálne.','formálna uniforma čašníka','formálna sťažnosť v liste','chill','none'),
(5467,'sk','Chlapec sa v šoku budí!','Pes sa v šoku budí!','prebúdzanie na poschodovej posteli','prebúdzanie v stane','dramatic','exclamation'),
(5468,'sk','Reklamné tabule svietia.','Stromy svietia.','obrovské svietiace reklamné tabule','značka stop','chill','none'),
(5469,'sk','Tento chodec spravil 10 000 krokov!','Tento chodec spravil 100 krokov!','chodec s nordic walking palicami','chodec v horách','gossip','exclamation'),
(5470,'sk','Rýchla chôdza po centre mesta v obleku.','Rýchla chôdza po centre mesta v rifliach.','cesta do práce v centre mesta','strešný bar v centre mesta','business','none'),
(5471,'sk','Bublina hovorí, že je to vodorovné.','Bublina hovorí, že je to nakrivo.','vodorovný rám obrazu','vodorovná cesta','nerd','none'),
(5472,'sk','Bankovky vypadávajú.','Kľúče vypadávajú.','bankovky padajúce z peňaženky','bankovky v bankomate','chill','none'),
(5473,'sk','„Bohatý“ muž s prázdnou peňaženkou.','„Bohatý“ muž s plnou peňaženkou.','nie až taký bohatý muž','veľký dom bohatého muža','ironic','understatement'),
(5474,'sk','Triedi svoje mince.','Triedi svoje karty.','mince z peňaženky','mince vo fontáne','chill','none'),
(5475,'sk','Za nimi ide tank!','Za nimi ide kôň!','tank v dyme','nádrž plná vody','dramatic','exclamation'),
(5476,'sk','Kráča po troskách.','Kráča po kvetoch.','chôdza cez trosky','zametanie trosiek','chill','none'),
(5477,'sk','Najlepšia bitka o snehovú pevnosť vôbec.','Najlepšia bitka o pieskovú pevnosť vôbec.','pevnosť zo snehu','pevnosť z kameňa','slang','exaggeration'),
(5478,'sk','Jej veci na ňu útočia!','Jej knihy na ňu útočia!','vypadávajúce veci','veci pod posteľou','dramatic','exaggeration'),
(5479,'sk','Rúcho a „maličký“ šatník.','Rúcho a „maličká“ kuchyňa.','dlhé saténové rúcho','hotelový wellness župan','ironic','understatement'),
(5480,'sk','Jeho úloha je veža z tanierov.','Jeho úloha je veža z topánok.','ťažká úloha v kuchyni','úloha pri počítači','low_iq','none'),
(5481,'sk','Ružové vlasy, biele tričko. Uf.','Ružové vlasy, ružové tričko. Uf.','dlhé žiarivo ružové vlasy','ružová práčka','gossip','guessing'),
(5482,'sk','Pes si dáva kúpeľ. Wellness deň!','Mačka si dáva kúpeľ. Wellness deň!','pes v kúpeli','pes v bazéne','slang','cliche'),
(5483,'sk','Skúma pláž. Koho hľadá?','Skúma les. Koho hľadá?','skúmanie pobrežia','skenovanie čiarového kódu','gossip','guessing'),
(5484,'sk','Uprene hľadia na ohňostroj.','Uprene hľadia na more.','uprene hľadieť na oblohu','uprene hľadieť na obrazovku','chill','none'),
(5485,'sk','Používa krhlu.','Používa záhradnú hadicu.','zelená krhla','prázdna krhla','chill','none'),
(5486,'sk','Polieva kvetináč.','Maľuje kvetináč.','kvetináč na parapete','rozbitý kvetináč','chill','none'),
(5487,'sk','Surfovanie vo vnútri vlny je super!','Potápanie vo vnútri vlny je super!','surfovanie na obrovskej vlne','surfovanie po internete','slang','exclamation'),
(5488,'sk','Táto rozlúčka trvá večnosť.','Toto privítanie trvá večnosť.','rozlúčka v prístave','rozlúčka na letisku','dramatic','exaggeration'),
(5489,'sk','Každý kabát nosí tak skvele.','Každý oblek nosí tak skvele.','nosiť klobúk s perím','nosiť slamený klobúk','flirt','none'),
(5490,'sk','Vytrhol obrovskú burinu!','Vytrhol obrovskú mrkvu!','vytrhávanie buriny','burina v dlažbe','dramatic','exaggeration'),
(5491,'sk','Je tu taký vítaný!','Je tu taký osamelý!','vítaný hosť','vítaná prestávka v práci','dramatic','exclamation'),
(5492,'sk','Koleso má tenké špice.','Koleso nemá žiadne špice.','tenké kovové špice','tenké drevené špice','chill','none'),
(5493,'sk','Miluje každý náboj, ktorý uvidí.','Miluje každé auto, ktoré uvidí.','náboj kolesa','srdce mesta','gossip','guessing'),
(5494,'sk','Zdravotne postihnutý muž ide rýchlo.','Zdravotne postihnutý muž ide pomaly.','zdravotne postihnutý na vozíku','zdravotne postihnutý muž o barlách','chill','none'),
(5495,'sk','Klebeta v knižnici!','Klebeta v kuchyni!','posúvanie klebety ďalej','spustenie klebety na internete','dramatic','exclamation'),
(5496,'sk','Upravuje mu kravatu.','Upravuje mu klobúk.','upravovanie uzla kravaty','nastavovanie hodiniek','flirt','none'),
(5497,'sk','Kandidát vyhral!','Kandidát prehral!','víťazný kandidát','porazený kandidát','dramatic','exclamation'),
(5498,'sk','Každé okno, nový výhľad!','Každé dvere, nový výhľad!','vykláňanie sa z okna','umývanie okna','slang','exaggeration'),
(5499,'sk','Žena v červenom sa točí.','Žena v červenom behá.','žena polieva kvety','žena kupuje kvety','chill','none'),
(5500,'sk','Čerstvé rezivo leží na kope.','Čerstvé rezivo leží na kamióne.','kopa čerstvého reziva','kamión čerstvého reziva','chill','none'),
(5501,'sk','Pracuje v ťažkom priemysle.','Pracuje v kvetinárstve.','fabrika ťažkého priemyslu','turistický priemysel','business','none'),
(5502,'sk','Krabice idú na skladovanie.','Krabice idú do koša.','krabice na skladovanie','úložisko v telefóne','business','none'),
(5503,'sk','Je v polohe planku.','Je v polohe lotosu.','vysoká poloha planku','pozícia vo firme','chill','none'),
(5504,'sk','Posiela list.','Posiela balík.','posielanie ručne písaného listu','posielanie SMS','chill','none'),
(5505,'sk','Študuje röntgenový film.','Študuje papierovú mapu.','röntgenový film','film v kine','nerd','none'),
(5506,'sk','Doslova všetci prišli na túto tanečnú zábavu.','Doslova nikto neprišiel na túto tanečnú zábavu.','pouličná tanečná zábava pri západe','tanečná hodina v škole','slang','exaggeration'),
(5507,'sk','Zabáva sa v zoo.','Zabáva sa na pláži.','deň v zoo','deň na farme','chill','none')
on conflict (media_id, language_code) do update set true_sentence=excluded.true_sentence, false_sentence=excluded.false_sentence, true_phrase=excluded.true_phrase, false_phrase=excluded.false_phrase, tone=excluded.tone, device=excluded.device, created_at=now();
commit;
